const qglFinal = [
    { "chinese": "n.(C)对手；反对者", "english": "opponent", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)原理，原则", "english": "principle", "type": "单词", "keyWords": [] },
    { "chinese": "v.移转，转送；调职", "english": "transfer", "type": "单词", "keyWords": [] },
    { "chinese": "a.人造的；合成的", "english": "synthetic", "type": "单词", "keyWords": [] },
    { "chinese": "a.通情达理的；明智的；合情合理的", "english": "sensible", "type": "单词", "keyWords": [] },
    { "chinese": "a.不变的，耐久的", "english": "permanent", "type": "单词", "keyWords": [] },
    { "chinese": "a.严格守时的", "english": "punctual", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)反叛分子", "english": "rebel", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)节奏；韵律", "english": "rhythm", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)疑心", "english": "suspicion", "type": "单词", "keyWords": [] },
    { "chinese": "茫然不知所措", "english": "at a loss", "type": "短语", "keyWords": [] },
    { "chinese": "辨认出", "english": "make out", "type": "短语", "keyWords": [] },
    { "chinese": "镇压", "english": "put down", "type": "短语", "keyWords": [] },
    { "chinese": "一度", "english": "at one time", "type": "短语", "keyWords": [] },
    { "chinese": "看穿", "english": "see through", "type": "短语", "keyWords": [] },
    { "chinese": "留出", "english": "set aside", "type": "短语", "keyWords": [] },
    { "chinese": "雇用；承担", "english": "take on", "type": "短语", "keyWords": [] },
    { "chinese": "拒绝", "english": "turn down", "type": "短语", "keyWords": [] },
    { "chinese": "搭载旅客", "english": "pick up passengers", "type": "短语", "keyWords": ["pick up"] },
    { "chinese": "偷；带着……速跑", "english": "make off with ....", "type": "短语", "keyWords": ["make off"] },
    { "chinese": "编造；构成；凑足", "english": "make up", "type": "短语", "keyWords": [] },
    { "chinese": "献给母亲的鲜花", "english": "flowers meant for one's mother", "type": "短语", "keyWords": ["mean for"] },
    { "chinese": "反对某人/(做)某事", "english": "object to sb./to (doing) sth.= raise an objection to sb./to (doing) sth.", "type": "短语", "keyWords": ["object", "objection"] },
    { "chinese": "与其说是一本语法书，不如说是一本词典", "english": "be more a dictionary than one on grammar", "type": "短语", "keyWords": ["more...than..."] },
    { "chinese": "出于好奇心", "english": "out of curiosity", "type": "短语", "keyWords": ["curiosity"] },
    { "chinese": "把我的成功归功于我的老师们", "english": "owe my success to my teachers", "type": "短语", "keyWords": ["owe...to..."] },
    { "chinese": "宁死也不做叛徒", "english": "prefer to die rather than turn traitor/would rather die than turn traitor", "type": "短语", "keyWords": ["prefer...rather than...", "would rather...than..."] },
    { "chinese": "在口袋中到处摸着找火柴", "english": "search one's pocket for a match", "type": "短语", "keyWords": ["search...for..."] },
    { "chinese": "尽管；不管，不顾", "english": "in spite of", "type": "短语", "keyWords": [] },
    { "chinese": "呈现新面貌，具有新气象", "english": "take on a new look", "type": "短语", "keyWords": ["take on"] },
    { "chinese": "多亏了社会各界人士的慷慨解囊，这个孤儿院才得以在今年年初办了起来。", "english": "Thanks to the generous donation made by people from all walks of life, the orphanage was founded early this year.", "type": "句子", "keyWords": ["thanks to", "all walks of life", "found"] },
    { "chinese": "国家领导人出席了典礼，为人民教育家颁发荣誉奖章。", "english": "The leaders of the country attended the ceremony to present/and presented the Medal of Honour to the People's Educator.", "type": "句子", "keyWords": ["attend", "present...to...", "Medal of Honour"] },
    { "chinese": "据报道上海迪士尼乐园的面积是香港迪士尼的4倍。", "english": "The area of the Disney Park in Shanghai is reported to be four times as big (large) as/three times bigger (larger) than/four times the size of that in Hong Kong.", "type": "句子", "keyWords": ["be reported to", "times", "size"] },
    { "chinese": "虽然他很快恢复了健康，医生还是建议他不要熬夜太晚。", "english": "Despite his rapid recovery from illness, the doctor still suggested that he shouldn't stay up too late.", "type": "句子", "keyWords": ["despite", "recovery from", "suggest", "stay up"] },
    { "chinese": "该论文声称，独处能够让我们更好地进行自我反思。", "english": "It is claimed in the essay that spending time alone can help us better reflect on ourselves.", "type": "句子", "keyWords": ["it is claimed that", "spend time alone", "reflect on"] },
    { "chinese": "他现在已经退休七八年了，可他总是闲不住，还在积极参加社会公益活动。", "english": "It is/has been seven or eight years since he retired from work,but he is always keeping himself busy,(and) actively participating in social welfare activities.", "type": "句子", "keyWords": ["it is/has been...since...", "retire from", "participate in", "social welfare activities"] },
    { "chinese": "事实证明当我们的国家在面临困难时，每个中国人，不管在国内还是国外，都愿意为自己的祖国做出贡献。", "english": "It turns out that when our country is facing difficulties, every Chinese,whether at home or abroad, is willing to make contributions to their motherland.", "type": "句子", "keyWords": ["it turns out that", "face difficulties", "whether...or...", "make contributions to"] },
    { "chinese": "食物只能维持一周。", "english": "The food supplies could hold out only for a week.", "type": "句子", "keyWords": ["food supplies", "hold out"] },
    { "chinese": "即使他把你烦透了，出于礼貌你也不能让他看出来。礼貌行为正在减少确实是个事实。", "english": "Even if he bores you stiff,it is good manners not to let him know it.It is a real fact that good manners are in decline.", "type": "句子", "keyWords": ["even if", "bore...stiff", "good manners", "in decline"] },
    { "chinese": "重要的是不要因为一次遗憾，而忘却了我们仍要风雨兼程的旅行。", "english": "What matters most is not to forget our nonstop journey with winds and rains because of one pity.", "type": "句子", "keyWords": ["what matters most", "because of"] },
    { "chinese": "他一到法国就发现很难适应那里的生活，所以半年以后他毅然回到了曾经养育他的祖国。", "english": "No sooner had he reached France than he found it very difficult to be accustomed to the life there. So half a year later,he returned to the motherland where he was raised.", "type": "句子", "keyWords": ["no sooner...than...", "be accustomed to", "where引导定语从句"] },
    { "chinese": "我养成了习惯，趁记忆貌新，就把难忘的经历写下来。", "english": "I have formed/developed/ cultivated a habit of writing down the unforgettable experiences while they're still fresh in my mind/ memory.", "type": "句子", "keyWords": ["form/develop/cultivate a habit of", "write down", "while", "fresh in one's mind/memory"] },
    { "chinese": "生命充满了挑战，但是只要你有学习新事物的意愿，就能得到克服障碍的正确态度。", "english": "Life is full of changes,but a willingness to learn something new gives people the right attitude for overcoming obstacles.", "type": "句子", "keyWords": ["be full of", "willingness to do", "attitude for", "overcome obstacles"] },
    { "chinese": "正是老一辈人的艰苦奋斗使祖国发生了巨大变化，未来掌握在我们年轻人手中，我们决不辜负期望。", "english": "It was the old generation who worked hard to make these/the great changes happen in our motherland; the future lies in the hands of us young people and we'll live up to their expectations.// It was the old generation who worked hard to make these/the great changes happen in our motherland, while the future lies in the hands of us young people and we shall never fail to live up to their expectations.", "type": "句子", "keyWords": ["it is...who...(强调句)", "work hard", "make...happen", "lie in the hands of", "live up to"] },
    { "chinese": "如果能找到任何适合你的学习方法，你的学习效率就可能明显提高。", "english": "If you can find whatever learning method (that) suits you, your study/learning efficiency is likely to improve remarkably.", "type": "句子", "keyWords": ["whatever", "suit", "learning efficiency", "be likely to", "improve remarkably"] },
    { "chinese": "n.[U]混凝土a.混凝土(制)的；具体的；实在的", "english": "concrete", "type": "单词", "keyWords": [] },
    { "chinese": "a.壮观的；不凡的", "english": "imposing", "type": "单词", "keyWords": [] },
    { "chinese": "v.收缩；退缩", "english": "shrink", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)症状，征兆", "english": "symptom", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)工具v.执行，履行(契约)", "english": "implement", "type": "单词", "keyWords": [] },
    { "chinese": "a.全面的；综合的；悟性好的", "english": "comprehensive", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)提倡者", "english": "advocate", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)奴隶制", "english": "slavery", "type": "单词", "keyWords": [] },
    { "chinese": "v.商定，协商", "english": "negotiate", "type": "单词", "keyWords": [] },
    { "chinese": "a.海产的；海运的", "english": "marine", "type": "单词", "keyWords": [] },
    { "chinese": "生产出", "english": "turn out", "type": "短语", "keyWords": [] },
    { "chinese": "投宿", "english": "put up", "type": "短语", "keyWords": [] },
    { "chinese": "着手", "english": "set about", "type": "短语", "keyWords": [] },
    { "chinese": "接管；接收", "english": "take over", "type": "短语", "keyWords": [] },
    { "chinese": "使某人相信……", "english": "convince sb.of/that ..", "type": "短语", "keyWords": ["convince"] },
    { "chinese": "被发行或发表；(应试)结果", "english": "come out", "type": "短语", "keyWords": [] },
    { "chinese": "使他陶醉", "english": "carry him away", "type": "短语", "keyWords": ["carry away"] },
    { "chinese": "对……做出(满意的)解释；占", "english": "account for", "type": "短语", "keyWords": [] },
    { "chinese": "发生在某人身上；被某人想起", "english": "occur to sb.", "type": "短语", "keyWords": ["occur"] },
    { "chinese": "陈述了他对这个计划的反对意见", "english": "set out his objections to the plan", "type": "短语", "keyWords": ["set out", "objection to"] },
    { "chinese": "成形；体现；具体化", "english": "take shape", "type": "短语", "keyWords": [] },
    { "chinese": "代表；支持；象征", "english": "stand for", "type": "短语", "keyWords": [] },
    { "chinese": "逆流而行；反潮流", "english": "go against the stream", "type": "短语", "keyWords": ["go against"] },
    { "chinese": "让我觉得它极为可笑，给我的印象是极为可笑", "english": "strike me as extremely funny", "type": "短语", "keyWords": ["strike...as..."] },
    { "chinese": "受支配，从属于；常遭受……", "english": "be subject to", "type": "短语", "keyWords": [] },
    { "chinese": "接管这家公司", "english": "take over the company", "type": "短语", "keyWords": ["take over"] },
    { "chinese": "占用你更多的时间", "english": "take up more of your time", "type": "短语", "keyWords": ["take up"] },
    { "chinese": "保存期限；贮藏寿命；适用期", "english": "shelf life", "type": "短语", "keyWords": [] },
    { "chinese": "从事，忙于(常指坏事)；取决于，由……决定", "english": "up to...", "type": "短语", "keyWords": [] },
    { "chinese": "事故的目击者", "english": "a witness to the accident", "type": "短语", "keyWords": ["witness to"] },
    { "chinese": "在这场可怕的事故中，还有几个人似乎受了重伤。", "english": "Several other people appeared to have been seriously wounded in the terrible accident.", "type": "句子", "keyWords": ["appear to have been done", "seriously wounded"] },
    { "chinese": "每当他试图讲话时，他都害怕得喉咙发紧说不出话来。", "english": "Every time he tried to speak/ Whenever he tried to speak, his throat locks up with fear.", "type": "句子", "keyWords": ["every time/whenever", "try to do", "lock up", "with fear"] },
    { "chinese": "作为东盟国家的邻国，中国一贯非常重视同东盟的关系。", "english": "As a neighbour of ASEAN countries,China has always attached great importance to the relations with ASEAN.", "type": "句子", "keyWords": ["as", "attach great importance to"] },
    { "chinese": "很多人认为让孩子在幼儿园学习外语并不好，因为这可能会导致他们混淆母语和外语。", "english": "Many think it no good/think it's no good letting kids learn a foreign language at kindergarten because it might cause confusion between their native language and the foreign one.", "type": "句子", "keyWords": ["think it no good doing", "cause confusion between...and...", "native language"] },
    { "chinese": "孩子们费了很大劲才与国外的爸爸取得了联系。", "english": "The sons and daughters had great trouble/difficulty/a hard time (in) getting in touch with their father abroad.", "type": "句子", "keyWords": ["have trouble/difficulty/a hard time (in) doing", "get in touch with", "abroad"] },
    { "chinese": "由于在其他地方享受到了更高的服务标准，以色列人回国后对本国服务业也抱有相同期望。", "english": "Exposed to higher standards of service elsewhere,Israelis are returning home expecting the same.", "type": "句子", "keyWords": ["exposed to", "standard of service", "return home", "expect"] },
    { "chinese": "我们必须去做那些有待完成但别人没有时间完成的任务。", "english": "We must accomplish the things that need doing/that need to be done that no one has had time for.", "type": "句子", "keyWords": ["accomplish", "need doing/need to be done", "that引导定语从句"] },
    { "chinese": "正如上面所指出的，浏览器必须能理解额外的角色和状态信息，并通过可访问性API将其提供给辅助技术。", "english": "As stated above, the browser has to interpret the additional role and state information and provide it to the assistive technology via the accessibility API.", "type": "句子", "keyWords": ["as stated above", "interpret", "provide...to...", "via"] },
    { "chinese": "现在好像抱怨已毫无意义，不管怎样他们明天都要走了。", "english": "There seems to be no point complaining now-they're leaving tomorrow in any case.", "type": "句子", "keyWords": ["there seems to be", "no point doing", "in any case"] },
    { "chinese": "请注意保证包装可以适合长途海运。", "english": "Please see to it that the packing is suitable for a long sea voyage.", "type": "句子", "keyWords": ["see to it that", "be suitable for", "sea voyage"] },
    { "chinese": "这个年轻人不仅从来没有因为残疾而怨天尤人，反而一直在挑战自己，因为他知道生命太短暂，追梦不迟疑。", "english": "Instead of blaming fate or others for his disability, the young man has kept challenging himself, for he knows (clearly) that life is too short to hesitate in pursuing one's dream.", "type": "句子", "keyWords": ["instead of", "blame...for...", "disability", "keep doing", "too...to...", "pursue one's dream"] },
    { "chinese": "很多医生表情严肃说着难懂的术语，但张医生是个例外，他做事脚踏实地，话语浅显幽默，赢得了公众的认可。", "english": "Many doctors are serious and talk in complex medical terms,but Doctor Zhang is an exception, whose down-to-earth/practical behaviour and (whose) plain and funny speech have won the recognition of the public.", "type": "句子", "keyWords": ["complex medical terms", "exception", "whose引导定语从句", "down-to-earth/practical", "win the recognition of"] },
    { "chinese": "我决心已定，无论你怎么劝我，我也不会同意放弃这个通过夜以继日的努力工作才获得的机会。", "english": "I have made up my mind,so however you try to persuade me,I won't agree to give up the opportunity that I got after working hard day and night.", "type": "句子", "keyWords": ["make up one's mind", "however", "persuade", "agree to do", "give up", "that引导定语从句", "day and night"] },
    { "chinese": "抑郁症，表现为情绪低落，甚至觉得人生没有意义，其实是一种情绪紊乱，我们只有先了解，才能降低患病风险。", "english": "Depression,which involves feeling down and even finding the life meaningless, is actually a kind of emotional disorder, and only if we understand it can we reduce the risk of suffering from it.", "type": "句子", "keyWords": ["depression", "involve", "emotional disorder", "only if引导倒装句", "reduce the risk of", "suffer from"] },
    { "chinese": "春暖花开的四月是欣赏这个南方小镇美景的最佳时机。", "english": "April when the spring flowers bloom is the perfect time (the optimum/optimal time) to enjoy the beauty of this southern town.// April, when it gets warmer and flowers start blooming, is the best time to appreciate the beautiful scenery of this southern town.", "type": "句子", "keyWords": ["when引导定语从句", "spring flowers bloom", "perfect/best time to do", "enjoy/appreciate", "southern town", "beauty/scenery"] }
];
qglFinal.sort(() => Math.random() - 0.5);
