const qgl113_120 = [
    { "chinese": "在接下去的几天里请继续收听我们更多的详细报道", "english": "Stay tuned for more details in the days to follow.", "type": "句子", "keyWords": ["follow"] },
    { "chinese": "如下", "english": "as follows", "type": "短语", "keyWords": ["follow"] },
    { "chinese": "具体措施如下", "english": "Concrete measures are as follows.", "type": "句子", "keyWords": ["follow"] },
    { "chinese": "其结果当然是...", "english": "It follows that...", "type": "短语", "keyWords": ["follow"] },
    { "chinese": "a.喜爱的（只作表语）", "english": "fond", "type": "单词", "keyWords": [] },
    { "chinese": "爱好；喜欢", "english": "be fond of", "type": "短语", "keyWords": ["fond"] },
    { "chinese": "n.[U]食物", "english": "food", "type": "单词", "keyWords": [] },
    { "chinese": "各种食物", "english": "foods", "type": "短语", "keyWords": ["food"] },
    { "chinese": "食物链", "english": "food chain", "type": "短语", "keyWords": ["food"] },
    { "chinese": "食品添加剂", "english": "food additives", "type": "短语", "keyWords": ["food"] },
    { "chinese": "n.[C]蠢人 vt.欺骗，愚弄", "english": "fool", "type": "单词", "keyWords": [] },
    { "chinese": "a.愚蠢的，荒谬的", "english": "foolish", "type": "单词", "keyWords": [] },
    { "chinese": "嘲弄，欺骗", "english": "make a fool of...", "type": "短语", "keyWords": ["fool"] },
    { "chinese": "傻到做某事", "english": "be fool enough to do sth.", "type": "短语", "keyWords": ["fool"] },
    { "chinese": "某人做某事是愚蠢的", "english": "It's foolish/ stupid/ silly of sb. to do sth.", "type": "句子", "keyWords": ["foolish"] },
    { "chinese": "n.[C]脚；（山）麓；英尺", "english": "foot", "type": "单词", "keyWords": [] },
    { "chinese": "脚注，补充", "english": "foot-note", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "脚印", "english": "footprint", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "站着", "english": "be on one's feet", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "步行", "english": "on foot", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "（挣扎着）站起来", "english": "struggle to one's feet", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "失足；踏空", "english": "miss one's foot", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "站起来", "english": "rise to get on one's feet", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "突然站起，跳起", "english": "jump/ spring to one's feet", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "在山脚下，在山的下部", "english": "at the foot of the mountain", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "n.[C]脚步；脚步声；一步跨出去的距离", "english": "footstep", "type": "单词", "keyWords": [] },
    { "chinese": "prep.为了；因为；至于；适合于；对...支持；等值，等量；达；计 conj.因为", "english": "for", "type": "单词", "keyWords": [] },
    { "chinese": "赞成，支持", "english": "be for", "type": "短语", "keyWords": ["for"] },
    { "chinese": "毫无疑问，肯定地，有把握", "english": "for sure/certain", "type": "短语", "keyWords": ["for"] },
    { "chinese": "暂时；目前", "english": "for the time being", "type": "短语", "keyWords": ["for"] },
    { "chinese": "出售，待售", "english": "for sale", "type": "短语", "keyWords": ["for"] },
    { "chinese": "为了...（起见/缘故）", "english": "for the sake of...", "type": "短语", "keyWords": ["for"] },
    { "chinese": "永远", "english": "for good", "type": "短语", "keyWords": ["for"] },
    { "chinese": "把...视为当然", "english": "take ... for granted", "type": "短语", "keyWords": ["for"] },
    { "chinese": "不收费；白白地", "english": "for nothing", "type": "短语", "keyWords": ["for"] },
    { "chinese": "每前进三步后退一步", "english": "take a step back for every three steps forward", "type": "句子", "keyWords": ["for"] },
    { "chinese": "儿童图书", "english": "books (meant/ intended) for children", "type": "短语", "keyWords": ["for"] },
    { "chinese": "第一/一则，...再说/再则...", "english": "For one thing,...and for another,...", "type": "句子", "keyWords": ["for"] },
    { "chinese": "就他的年龄而言，他是个高个子", "english": "He is tall for his age.", "type": "句子", "keyWords": ["for"] },
    { "chinese": "要不是某人的话", "english": "If it were not for sb.,...", "type": "句子", "keyWords": ["for"] },
    { "chinese": "尽管", "english": "for all...", "type": "短语", "keyWords": ["for"] },
    { "chinese": "尽管还存在许多问题，这仍不失为一次宝贵的经历", "english": "For all the problems, it was a valuable experience.", "type": "句子", "keyWords": ["for"] },
    { "chinese": "尽管你这样说，我还是喜欢他", "english": "For all you say,I still like him.", "type": "句子", "keyWords": ["for"] },
    { "chinese": "vt.禁止，不许", "english": "forbid", "type": "单词", "keyWords": [] },
    { "chinese": "a.禁止的，严禁的", "english": "forbidden", "type": "单词", "keyWords": ["forbid"] },
    { "chinese": "禁止某人...", "english": "forbid sb. sth.", "type": "短语", "keyWords": ["forbid"] },
    { "chinese": "他的父母不准他喝酒", "english": "His parents forbid him wine.", "type": "句子", "keyWords": ["forbid"] },
    { "chinese": "禁止某人去做某事", "english": "forbid sb. to do sth.", "type": "短语", "keyWords": ["forbid"] },
    { "chinese": "大多数父母都同意禁止自己的孩子抽烟", "english": "Most of the parents agree to forbid their children to smoke.", "type": "句子", "keyWords": ["forbid"] },
    { "chinese": "禁止做某事", "english": "forbid doing sth.", "type": "短语", "keyWords": ["forbid"] },
    { "chinese": "火车上禁止吸烟", "english": "forbid smoking on trains", "type": "句子", "keyWords": ["forbid"] },
    { "chinese": "禁区", "english": "forbidden zone", "type": "短语", "keyWords": ["forbidden"] },
    { "chinese": "紫禁城", "english": "Forbidden City", "type": "短语", "keyWords": ["forbidden"] },
    { "chinese": "n.[U]力，力量；暴力；气势 [C]势力；军队，兵力 vt./n.逼迫；强加；强取", "english": "force", "type": "单词", "keyWords": [] },
    { "chinese": "地心引力的力量", "english": "the force of gravity", "type": "短语", "keyWords": ["force"] },
    { "chinese": "强颜欢笑，苦笑", "english": "a forced smile", "type": "短语", "keyWords": ["force"] },
    { "chinese": "开始实施，生效", "english": "come/go into force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "强颜欢笑，苦笑", "english": "force a smile", "type": "短语", "keyWords": ["force"] },
    { "chinese": "使生效，实施", "english": "put/ bring ...into force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "逼迫某人做某事", "english": "force sb. to do/into doing sth.", "type": "短语", "keyWords": ["force"] },
    { "chinese": "把他的意见强加给别人", "english": "force his ideas upon others", "type": "句子", "keyWords": ["force"] },
    { "chinese": "用暴力", "english": "by force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "武力侵占", "english": "take.. by force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "生效，有效", "english": "be in force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "强行进入", "english": "force an entry", "type": "短语", "keyWords": ["force"] },
    { "chinese": "强行穿过人群", "english": "force our way through the crowd", "type": "句子", "keyWords": ["force"] },
    { "chinese": "a.有力的；有说服力的", "english": "forceful", "type": "单词", "keyWords": ["force"] },
    { "chinese": "ad.强有力地，激烈地", "english": "forcefully", "type": "单词", "keyWords": ["forceful"] },
    { "chinese": "前臂", "english": "forearm", "type": "单词", "keyWords": [] },
    { "chinese": "祖先", "english": "forefather", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]预测；预报", "english": "forecast", "type": "单词", "keyWords": [] },
    { "chinese": "天气预报", "english": "the weather forecast", "type": "短语", "keyWords": ["forecast"] },
    { "chinese": "n.[C]额；前额", "english": "forehead", "type": "单词", "keyWords": [] },
    { "chinese": "a.外国的；对外的", "english": "foreign", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]外国人", "english": "foreigner", "type": "单词", "keyWords": ["foreign"] },
    { "chinese": "无关；不适宜的", "english": "be foreign to sb.", "type": "短语", "keyWords": ["foreign"] },
    { "chinese": "你的争辩与本问题无关", "english": "Your argument is foreign to the question.", "type": "句子", "keyWords": ["foreign"] },
    { "chinese": "a.最先的，最初的；最重要的", "english": "foremost", "type": "单词", "keyWords": [] },
    { "chinese": "首先，第一", "english": "first and foremost", "type": "短语", "keyWords": ["foremost"] },
    { "chinese": "vt.预见；预知", "english": "foresee", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]林区；森林", "english": "forest", "type": "单词", "keyWords": [] },
    { "chinese": "雨林", "english": "rain forest", "type": "短语", "keyWords": ["forest"] },
    { "chinese": "禁伐区；森林保护区", "english": "a forest reserve", "type": "短语", "keyWords": ["forest"] },
    { "chinese": "ad.永远", "english": "forever", "type": "单词", "keyWords": [] },
    { "chinese": "vt./vi.忘记", "english": "forget", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]健忘", "english": "forgetfulness", "type": "单词", "keyWords": ["forget"] },
    { "chinese": "忘了已经做过某事", "english": "forget doing...", "type": "短语", "keyWords": ["forget"] },
    { "chinese": "忘了去做某事", "english": "forget to do...", "type": "短语", "keyWords": ["forget"] },
    { "chinese": "噢，别再提了！", "english": "Oh,forget (about) it.", "type": "句子", "keyWords": ["forget"] },
    { "chinese": "关于某事不记得什么了", "english": "forget (all) about sth.", "type": "短语", "keyWords": ["forget"] },
    { "chinese": "别忘记代我问候你的父母亲", "english": "Don't forget me to your parents.", "type": "句子", "keyWords": ["forget"] },
    { "chinese": "让我们不念旧恶/摒弃前嫌/捐弃前嫌", "english": "Let's forgive and forget.", "type": "句子", "keyWords": ["forget"] },
    { "chinese": "a.容易被忘的；可忘记的", "english": "forgettable", "type": "单词", "keyWords": ["forget"] },
    { "chinese": "vt.宽恕，原谅", "english": "forgive", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]宽恕，宽仁之心", "english": "forgiveness", "type": "单词", "keyWords": ["forgive"] },
    { "chinese": "原谅某事", "english": "forgive doing sth.", "type": "短语", "keyWords": ["forgive"] },
    { "chinese": "原谅某人做某事", "english": "forgive sb. for doing sth.", "type": "短语", "keyWords": ["forgive"] },
    { "chinese": "n.[C]餐叉；（树、路的）分支 v.（使）成叉状；分岔", "english": "fork", "type": "单词", "keyWords": [] },
    { "chinese": "（吃西餐用的）一副刀叉", "english": "a knife and fork", "type": "短语", "keyWords": ["fork"] },
    { "chinese": "n.[C]形式；方式；外形；表格 v.形成；构成；组成，建立 v.成形", "english": "form", "type": "单词", "keyWords": [] },
    { "chinese": "填写表格", "english": "fill (in/ out) a form", "type": "短语", "keyWords": ["form"] },
    { "chinese": "形式与内容", "english": "form and content", "type": "短语", "keyWords": ["form"] },
    { "chinese": "以...的形式", "english": "in the form of", "type": "短语", "keyWords": ["form"] },
    { "chinese": "a.正式的", "english": "formal", "type": "单词", "keyWords": ["form"] },
    { "chinese": "a.非正式的", "english": "informal", "type": "单词", "keyWords": ["formal"] },
    { "chinese": "a.在前的；以前的；（两者中）前面的", "english": "former", "type": "单词", "keyWords": [] },
    { "chinese": "前任总统/以前的学生/前妻", "english": "former president/student/wife", "type": "短语", "keyWords": ["former"] },
    { "chinese": "前者是…后者是…", "english": "The former is...and the latter...", "type": "句子", "keyWords": ["former"] },
    { "chinese": "ad.向前", "english": "forth", "type": "单词", "keyWords": [] },
    { "chinese": "提出；产生", "english": "bring/put... forth", "type": "短语", "keyWords": ["forth"] },
    { "chinese": "来来往往地，来回地", "english": "back and forth", "type": "短语", "keyWords": ["forth"] },
    { "chinese": "num.四十", "english": "forty", "type": "单词", "keyWords": [] },
    { "chinese": "num.第四十；四十分之一", "english": "fortieth", "type": "单词", "keyWords": ["forty"] },
    { "chinese": "在他们四十几岁时", "english": "in their forties", "type": "短语", "keyWords": ["forty"] },
    { "chinese": "在20世纪40年代早期", "english": "in the early nineteen forties = in the early 1940's/ 1940s", "type": "句子", "keyWords": ["forty"] },
    { "chinese": "a.幸运的，侥幸的；吉利的；幸福的", "english": "fortunate", "type": "单词", "keyWords": [] },
    { "chinese": "ad.幸运地；幸亏", "english": "fortunately", "type": "单词", "keyWords": ["fortunate"] },
    { "chinese": "幸运的是我避开了飓风", "english": "Fortunately, I missed the hurricane.", "type": "句子", "keyWords": ["fortunately"] },
    { "chinese": "n.[C]财富 [C][U]（好）运气", "english": "fortune", "type": "单词", "keyWords": [] },
    { "chinese": "一小/一大笔钱", "english": "a small/ large fortune", "type": "短语", "keyWords": ["fortune"] },
    { "chinese": "发财", "english": "make a fortune", "type": "短语", "keyWords": ["fortune"] },
    { "chinese": "碰碰运气", "english": "try one's fortune", "type": "短语", "keyWords": ["fortune"] },
    { "chinese": "算命者", "english": "fortune teller", "type": "短语", "keyWords": ["fortune"] },
    { "chinese": "a.向前的；前进的 ad.向前；前进 v.促进；转变；发送", "english": "forward", "type": "单词", "keyWords": [] },
    { "chinese": "ad.向前；前进", "english": "forwards", "type": "单词", "keyWords": ["forward"] },
    { "chinese": "向前运动", "english": "a forward movement", "type": "短语", "keyWords": ["forward"] },
    { "chinese": "提出建议", "english": "put forward a proposal", "type": "短语", "keyWords": ["forward"] },
    { "chinese": "期盼；等待", "english": "look forward to (doing) sth.", "type": "短语", "keyWords": ["forward"] },
    { "chinese": "客户的申请转发给银行员工进行审核", "english": "The customer's application is forwarded to a bank employee for review.", "type": "句子", "keyWords": ["forward"] },
    { "chinese": "v.创立；创建", "english": "found", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]基金（会）；基础 [U]创建", "english": "foundation", "type": "单词", "keyWords": ["found"] },
    { "chinese": "n.[C]创建者", "english": "founder", "type": "单词", "keyWords": ["found"] },
    { "chinese": "为...打下坚实的基础", "english": "lay a solid foundation for", "type": "短语", "keyWords": ["foundation"] },
    { "chinese": "n.[C]泉水；人造喷泉；源泉", "english": "fountain", "type": "单词", "keyWords": [] },
    { "chinese": "智慧的源泉", "english": "a fountain/ source of wisdom", "type": "短语", "keyWords": ["fountain"] },
    { "chinese": "n.[C]狐狸", "english": "fox", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]框架，构架；窗框；镜框 v.给...装框；构筑；制定，拟定", "english": "frame", "type": "单词", "keyWords": [] },
    { "chinese": "为画装上框", "english": "frame a painting", "type": "短语", "keyWords": ["frame"] },
    { "chinese": "a.坦白的，直率的；真诚的", "english": "frank", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]坦白，直率；真诚", "english": "frankness", "type": "单词", "keyWords": ["frank"] },
    { "chinese": "坦白地说，...", "english": "To be frank (with you),...", "type": "句子", "keyWords": ["frank"] },
    { "chinese": "a.免费的；自由的；空闲的 v.使自由，释放，解放；使摆脱；清除 ad.免费", "english": "free", "type": "单词", "keyWords": [] },
    { "chinese": "释放某人", "english": "set sb. free=free sb.", "type": "短语", "keyWords": ["free"] },
    { "chinese": "无息贷款", "english": "an interest-free loan", "type": "短语", "keyWords": ["free"] },
    { "chinese": "不冻港", "english": "an ice-free harbor", "type": "短语", "keyWords": ["free"] },
    { "chinese": "禁烟室", "english": "a smoke-free room", "type": "短语", "keyWords": ["free"] },
    { "chinese": "免费", "english": "for free", "type": "短语", "keyWords": ["free"] },
    { "chinese": "绳的没有固定住的那一端", "english": "the free end of a rope", "type": "短语", "keyWords": ["free"] },
    { "chinese": "没有...的；免除的", "english": "be free of/from", "type": "短语", "keyWords": ["free"] },
    { "chinese": "免费", "english": "free of charge", "type": "短语", "keyWords": ["free"] },
    { "chinese": "老妇人一直在受苦", "english": "The old lady is never free from pain.", "type": "句子", "keyWords": ["free"] },
    { "chinese": "免税的那部分收入", "english": "the income that is free of all taxes", "type": "短语", "keyWords": ["free"] },
    { "chinese": "n.[U]自由", "english": "freedom", "type": "单词", "keyWords": ["free"] },
    { "chinese": "vi.结冰，凝固；变得极度寒冷；惊呆住，愣住 vt.使冷冻，使结冰", "english": "freeze", "type": "单词", "keyWords": [] },
    { "chinese": "我简直冻僵了", "english": "I'm freezing (to death).", "type": "句子", "keyWords": ["freeze"] },
    { "chinese": "冻死", "english": "freeze to death", "type": "短语", "keyWords": ["freeze"] },
    { "chinese": "吓得浑身冰冷", "english": "make one's blood freeze", "type": "短语", "keyWords": ["freeze"] },
    { "chinese": "吓得呆住了", "english": "freeze with fear", "type": "短语", "keyWords": ["freeze"] },
    { "chinese": "他们脸上的笑容僵住了", "english": "Smiles froze on their faces.", "type": "句子", "keyWords": ["freeze"] },
    { "chinese": "a.冻结的，极冷的 n.[U]冻结；冰点", "english": "freezing", "type": "单词", "keyWords": ["freeze"] },
    { "chinese": "a.冰冻的", "english": "frozen", "type": "单词", "keyWords": ["freeze"] },
    { "chinese": "冰点", "english": "freezing point", "type": "短语", "keyWords": ["freezing"] },
    { "chinese": "极冷的", "english": "freezing cold", "type": "短语", "keyWords": ["freezing"] },
    { "chinese": "冻肉", "english": "frozen meat", "type": "短语", "keyWords": ["frozen"] },
    { "chinese": "n.[U]法语 a.法国的；法国人的；法语的", "english": "French", "type": "单词", "keyWords": [] },
    { "chinese": "法国人", "english": "the French", "type": "短语", "keyWords": ["French"] },
    { "chinese": "a.时常发生的，频繁的", "english": "frequent", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]经常；频繁 [C]频率", "english": "frequency", "type": "单词", "keyWords": ["frequent"] },
    { "chinese": "ad.时常地；频繁地", "english": "frequently", "type": "单词", "keyWords": ["frequent"] },
    { "chinese": "a.新鲜的", "english": "fresh", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]气味清新，精神饱满", "english": "freshness", "type": "单词", "keyWords": ["fresh"] },
    { "chinese": "清新的空气", "english": "fresh air", "type": "短语", "keyWords": ["fresh"] },
    { "chinese": "新生，大学一年级学生", "english": "freshman", "type": "单词", "keyWords": ["fresh"] },
    { "chinese": "新鲜的食物", "english": "fresh food", "type": "短语", "keyWords": ["fresh"] },
    { "chinese": "淡水", "english": "fresh water", "type": "短语", "keyWords": ["fresh"] },
    { "chinese": "n.[C]星期五", "english": "Friday", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]冰箱", "english": "fridge", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]朋友", "english": "friend", "type": "单词", "keyWords": [] },
    { "chinese": "a.友好的；朋友（般）的", "english": "friendly", "type": "单词", "keyWords": ["friend"] },
    { "chinese": "n.[U]友好", "english": "friendliness", "type": "单词", "keyWords": ["friendly"] },
    { "chinese": "与...交朋友", "english": "make/be friends with", "type": "短语", "keyWords": ["friend"] },
    { "chinese": "心腹之交，密友，知己", "english": "close friends", "type": "短语", "keyWords": ["friend"] },
    { "chinese": "友好地", "english": "in a friendly way", "type": "短语", "keyWords": ["friendly"] },
    { "chinese": "与…友好", "english": "be friendly to sb.", "type": "短语", "keyWords": ["friendly"] },
    { "chinese": "陈酒味醇，老友情深", "english": "Old friends and old wine are best.", "type": "句子", "keyWords": ["friend"] },
    { "chinese": "n.[C][U]友谊；友好", "english": "friendship", "type": "单词", "keyWords": ["friend"] },
    { "chinese": "50年的友情", "english": "a friendship of 50years", "type": "短语", "keyWords": ["friendship"] },
    { "chinese": "促进友谊", "english": "promote friendship", "type": "短语", "keyWords": ["friendship"] },
    { "chinese": "vt.使..惊恐", "english": "frighten", "type": "单词", "keyWords": [] },
    { "chinese": "a.受惊吓的", "english": "frightened", "type": "单词", "keyWords": ["frighten"] },
    { "chinese": "a.令人惊恐的", "english": "frightening", "type": "单词", "keyWords": ["frighten"] },
    { "chinese": "n.[C][U]惊骇，吃惊", "english": "fright", "type": "单词", "keyWords": ["frighten"] },
    { "chinese": "a.可怕的；非常的", "english": "frightful", "type": "单词", "keyWords": ["fright"] },
    { "chinese": "处于惊恐状态", "english": "in fright", "type": "短语", "keyWords": ["fright"] },
    { "chinese": "吓跑，吓走", "english": "frighten...away", "type": "短语", "keyWords": ["frighten"] },
    { "chinese": "用恐吓手段迫使某人做/不做某事", "english": "frighten sb. into/out of doing sth.", "type": "短语", "keyWords": ["frighten"] },
    { "chinese": "害怕做某事", "english": "be frightened to do sth.", "type": "短语", "keyWords": ["frightened"] },
    { "chinese": "害怕某事", "english": "be frightened of sth.", "type": "短语", "keyWords": ["frightened"] },
    { "chinese": "使某人受惊；吓某人一跳", "english": "give sb. a fright", "type": "短语", "keyWords": ["fright"] },
    { "chinese": "把某人吓死", "english": "frighten sb. to death", "type": "短语", "keyWords": ["frighten"] },
    { "chinese": "因...受惊", "english": "be frightened at sth.", "type": "短语", "keyWords": ["frightened"] },
    { "chinese": "n.[C]蛙", "english": "frog", "type": "单词", "keyWords": [] },
    { "chinese": "prep.从；（表来源）来自于；离开（脱离）；由于", "english": "from", "type": "单词", "keyWords": [] },
    { "chinese": "挨家挨户", "english": "from house to house", "type": "短语", "keyWords": ["from"] },
    { "chinese": "从桌下", "english": "from under the table", "type": "短语", "keyWords": ["from"] },
    { "chinese": "从我的观点看", "english": "from my point of view", "type": "短语", "keyWords": ["from"] },
    { "chinese": "愈来愈坏，每况愈下", "english": "from bad to worse", "type": "短语", "keyWords": ["from"] },
    { "chinese": "从那时起", "english": "from then on", "type": "短语", "keyWords": ["from"] },
    { "chinese": "饿昏了", "english": "faint from hunger", "type": "句子", "keyWords": ["from"] },
    { "chinese": "辨别是非", "english": "know right from wrong", "type": "短语", "keyWords": ["from"] },
    { "chinese": "n.[C]（the）前线；前面", "english": "front", "type": "单词", "keyWords": [] },
    { "chinese": "标题版，头版", "english": "front page", "type": "短语", "keyWords": ["front"] },
    { "chinese": "在...前面（外）", "english": "in front of", "type": "短语", "keyWords": ["front"] },
    { "chinese": "在...前部（内）", "english": "in the front of", "type": "短语", "keyWords": ["front"] },
    { "chinese": "n.[U]水果 [C]水果种类；产物；成果", "english": "fruit", "type": "单词", "keyWords": [] },
    { "chinese": "a.不结果实的；没结果的", "english": "fruitless", "type": "单词", "keyWords": ["fruit"] },
    { "chinese": "a.果实结得多的，多产的；富有成效的", "english": "fruitful", "type": "单词", "keyWords": ["fruit"] },
    { "chinese": "结果实；产生效果", "english": "bear fruit", "type": "短语", "keyWords": ["fruit"] },
    { "chinese": "v.挫败，阻挠（计划、企图等）；使感到灰心；使受挫", "english": "frustrate", "type": "单词", "keyWords": [] },
    { "chinese": "a.感到/使人灰心的", "english": "frustrated/frustrating", "type": "单词", "keyWords": ["frustrate"] },
    { "chinese": "n.[U]挫败，挫折", "english": "frustration", "type": "单词", "keyWords": ["frustrate"] },
    { "chinese": "警察挫败了恐怖分子抢劫银行的企图", "english": "The police frustrated the terrorists' attempt to rob the bank.", "type": "句子", "keyWords": ["frustrate"] },
    { "chinese": "vt.油煎；油炒；油炸", "english": "fry", "type": "单词", "keyWords": [] },
    { "chinese": "a.油炸的", "english": "fried", "type": "单词", "keyWords": ["fry"] },
    { "chinese": "煎锅，长柄平锅", "english": "frying pan", "type": "短语", "keyWords": ["fry"] },
    { "chinese": "n.[U][C]燃料，燃烧剂 v.给...加燃料，供以燃料 v.加燃料", "english": "fuel", "type": "单词", "keyWords": [] },
    { "chinese": "v.履行；实现；满足", "english": "fulfil(l)", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]履行，实行", "english": "fulfillment", "type": "单词", "keyWords": ["fulfil(l)"] },
    { "chinese": "完成任务/履行职责/履行合同/实现梦想/实现愿望", "english": "fulfil the task/ one's duty, a contract/ one's dream/ one's desire", "type": "短语", "keyWords": ["fulfil(l)"] },
    { "chinese": "a.（充）满的", "english": "full", "type": "单词", "keyWords": [] },
    { "chinese": "满月", "english": "a full moon", "type": "短语", "keyWords": ["full"] },
    { "chinese": "a.（牛奶等）全脂的", "english": "full-fat", "type": "单词", "keyWords": ["full"] },
    { "chinese": "充满的；有很多的", "english": "be full of", "type": "短语", "keyWords": ["full"] },
    { "chinese": "充分（享受）；彻底（享受）", "english": "(enjoy it) to the full", "type": "短语", "keyWords": ["full"] },
    { "chinese": "n.[C]（常用复数）烟雾；气味", "english": "fume", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]乐趣", "english": "fun", "type": "单词", "keyWords": [] },
    { "chinese": "多有趣！", "english": "What fun!", "type": "句子", "keyWords": ["fun"] },
    { "chinese": "为了消遣", "english": "for fun", "type": "短语", "keyWords": ["fun"] },
    { "chinese": "开玩笑", "english": "make fun of", "type": "短语", "keyWords": ["fun"] },
    { "chinese": "a.滑稽可笑的；逗人发笑的；奇异的，古怪的", "english": "funny", "type": "单词", "keyWords": ["fun"] },
    { "chinese": "vi.（器官等）活动；（机器等）运行；起作用 n.[C]作用，功能；机能；[数]函数", "english": "function", "type": "单词", "keyWords": [] },
    { "chinese": "那电池没用了", "english": "The battery doesn't function.", "type": "句子", "keyWords": ["function"] },
    { "chinese": "行政职能", "english": "administrative function", "type": "短语", "keyWords": ["function"] },
    { "chinese": "n.[C]基金；(pl)资金，现款 v.资助，投资；为..提供经费", "english": "fund", "type": "单词", "keyWords": [] },
    { "chinese": "建立基金", "english": "set up a fund", "type": "短语", "keyWords": ["fund"] },
    { "chinese": "募集资金", "english": "raise a fund", "type": "短语", "keyWords": ["fund"] },
    { "chinese": "为该项目提供经费", "english": "fund the project", "type": "句子", "keyWords": ["fund"] },
    { "chinese": "adj.基本的；基础的；主要的", "english": "fundamental", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]葬礼", "english": "funeral", "type": "单词", "keyWords": [] },
    { "chinese": "在葬礼/追悼会上", "english": "at the funeral", "type": "短语", "keyWords": ["funeral"] },
    { "chinese": "n.[U]（熊等的）软毛，柔毛 [C]毛皮衣服，毛皮制品；裘", "english": "fur", "type": "单词", "keyWords": [] },
    { "chinese": "穿着裘皮大衣的妇女", "english": "the woman in furs=the woman in a fur coat", "type": "句子", "keyWords": ["fur"] },
    { "chinese": "vt.装设备于；供应；为（房间）配备家具", "english": "furnish", "type": "单词", "keyWords": [] },
    { "chinese": "给某人以食物/真相/他所需要的东西", "english": "furnish/ equip/ supply sb. with food/ facts/ what he needs = furnish food/ facts/ what he needs to sb.", "type": "句子", "keyWords": ["furnish"] },
    { "chinese": "这房屋室内布置得很好", "english": "The house is well furnished.", "type": "句子", "keyWords": ["furnish"] },
    { "chinese": "n.[U]（总称）家具", "english": "furniture", "type": "单词", "keyWords": ["furnish"] },
    { "chinese": "一件家具", "english": "a piece of furniture", "type": "短语", "keyWords": ["furniture"] },
    { "chinese": "a.更多的；另外的；深一层的 ad.更远地；更大程度上地；进一步 v.促进", "english": "further", "type": "单词", "keyWords": [] },
    { "chinese": "ad.此外", "english": "furthermore", "type": "单词", "keyWords": ["further"] },
    { "chinese": "进一步研究，深造", "english": "further study", "type": "短语", "keyWords": ["further"] },
    { "chinese": "继续教育", "english": "further education", "type": "短语", "keyWords": ["further"] },
    { "chinese": "得到更多信息", "english": "get further information", "type": "短语", "keyWords": ["further"] },
    { "chinese": "太累而无法走得更远", "english": "too tired to walk any further", "type": "句子", "keyWords": ["further"] },
    { "chinese": "还有多少路？", "english": "How much further is it?", "type": "句子", "keyWords": ["further"] },
    { "chinese": "我没有别的话要说了", "english": "I have nothing further to say.", "type": "句子", "keyWords": ["further"] },
    { "chinese": "攻读工商管理硕士学位", "english": "further his study for MBA", "type": "句子", "keyWords": ["further"] },
    { "chinese": "n.[C]未来；将来 a.未来的，将来的", "english": "future", "type": "单词", "keyWords": [] },
    { "chinese": "将来", "english": "in (the) future", "type": "短语", "keyWords": ["future"] },
    { "chinese": "在不久/久远的将来", "english": "in the near/distant future", "type": "短语", "keyWords": ["future"] },
    { "chinese": "他的未婚妻", "english": "his future wife", "type": "短语", "keyWords": ["future"] },
    { "chinese": "没有前途/前途远大", "english": "have no/a great future", "type": "短语", "keyWords": ["future"] },
    { "chinese": "未来未知。/前途未卜", "english": "One's future is uncertain.", "type": "句子", "keyWords": ["future"] },
    { "chinese": "n.[U]获得；(pl)收益 v.获得，赢得，赚到；增进；(表)走快，变快 vi.获利；增加", "english": "gain", "type": "单词", "keyWords": [] },
    { "chinese": "获得...经验/支持/名声/对...的控制权", "english": "gain experience/support/a reputation/ control of sth.", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "他使自己落下一个办事不公的名声", "english": "He has gained himself a reputation for unfairness.", "type": "句子", "keyWords": ["gain"] },
    { "chinese": "(手表等)一天快/慢20秒", "english": "gain/ lose twenty seconds a day", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "渐渐增加体重/速度/高度/时间", "english": "gain weight/ speed/height/time", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "这部车下山时速度加快了", "english": "The car gained speed as it went down the hill.", "type": "句子", "keyWords": ["gain"] },
    { "chinese": "(把某人)从敌对的一方争取过来", "english": "gain/win sb.over", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "从..中获得...", "english": "gain...from...", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "没有辛苦就没有收获。/不劳则无获", "english": "No pains,no gains.", "type": "句子", "keyWords": ["gain"] },
    { "chinese": "n.[C]走廊；(艺术品)陈列馆(或室)；画廊", "english": "gallery", "type": "单词", "keyWords": [] },
    { "chinese": "vi.赌博(on) v.赌掉，输光 n.[C]赌博；冒险", "english": "gamble", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]赌博；投机", "english": "gambling", "type": "单词", "keyWords": ["gamble"] },
    { "chinese": "n.[C]赌徒", "english": "gambler", "type": "单词", "keyWords": ["gamble"] },
    { "chinese": "输光他的全部财产", "english": "gamble away all his wealth", "type": "句子", "keyWords": ["gamble"] },
    { "chinese": "n.[C]游戏；运动；比赛；(总称)猎物", "english": "game", "type": "单词", "keyWords": [] },
    { "chinese": "一头猎物", "english": "a head of game", "type": "短语", "keyWords": ["game"] },
    { "chinese": "敷衍塞责；耍花腔", "english": "play games", "type": "短语", "keyWords": ["game"] },
    { "chinese": "n.[C](一)伙；(歹徒等的)一帮", "english": "gang", "type": "单词", "keyWords": [] },
    { "chinese": "(一)伙，(一)帮", "english": "a gang of", "type": "短语", "keyWords": ["gang"] },
    { "chinese": "n.[C]豁缝，缺口；隔阂；差距", "english": "gap", "type": "单词", "keyWords": [] },
    { "chinese": "填补空白/缩短差距", "english": "fill in/close the gaps", "type": "短语", "keyWords": ["gap"] },
    { "chinese": "n.[C]车库；汽车修理处；加油站", "english": "garage", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]垃圾", "english": "garbage", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]花园", "english": "garden", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]园丁", "english": "gardener", "type": "单词", "keyWords": ["garden"] },
    { "chinese": "n.[U]园艺；园林工人的工作", "english": "gardening", "type": "单词", "keyWords": ["garden"] },
    { "chinese": "n.[U]大蒜；蒜头", "english": "garlic", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]衣服；外衣(书面语，多用于文学作品)", "english": "garment", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]气态；气体 n.[U]煤气；天然气；可燃气体；[口]汽油", "english": "gas", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U][美]汽油[英]petrol", "english": "gasoline", "type": "单词", "keyWords": ["gas"] },
    { "chinese": "n.[C]/vi.喘息，气喘", "english": "gasp", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]大门；*事件；丑闻", "english": "gate", "type": "单词", "keyWords": [] },
    { "chinese": "伊朗门事件", "english": "Irangate", "type": "短语", "keyWords": ["gate"] },
    { "chinese": "水门事件", "english": "Watergate", "type": "短语", "keyWords": ["gate"] },
    { "chinese": "vi.(使)集合；(使)聚集；收集；搜集；集合；聚集 v.收割", "english": "gather", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]集合", "english": "gathering", "type": "单词", "keyWords": ["gather"] },
    { "chinese": "把...围住；聚拢来", "english": "gather around", "type": "短语", "keyWords": ["gather"] },
    { "chinese": "聚会；聚集；收集", "english": "gather together", "type": "短语", "keyWords": ["gather"] },
    { "chinese": "收割庄稼", "english": "gather/get in crops", "type": "短语", "keyWords": ["gather"] },
    { "chinese": "搜集情报", "english": "gather information", "type": "短语", "keyWords": ["gather"] },
    { "chinese": "a.快乐的；色彩鲜艳的", "english": "gay", "type": "单词", "keyWords": [] },
    { "chinese": "vi./n.[C]盯着看，凝视", "english": "gaze", "type": "单词", "keyWords": [] },
    { "chinese": "注视；凝视", "english": "gaze at", "type": "短语", "keyWords": ["gaze"] },
    { "chinese": "国内生产总值", "english": "GDP", "type": "短语", "keyWords": [] },
    { "chinese": "n.[C][U][语法]性；[口]性别；性", "english": "gender", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][遗传]基因", "english": "gene", "type": "单词", "keyWords": [] },
    { "chinese": "a.遗传的", "english": "genetic", "type": "单词", "keyWords": ["gene"] },
    { "chinese": "a.一般的，普通的；综合的，概括的；大体的；总的(级别最高的) n.[C]将军 v.归纳", "english": "general", "type": "单词", "keyWords": [] },
    { "chinese": "一般概念；大意", "english": "general idea", "type": "短语", "keyWords": ["general"] },
    { "chinese": "大选；普选", "english": "general election", "type": "短语", "keyWords": ["general"] },
    { "chinese": "一般，大体上", "english": "in general", "type": "短语", "keyWords": ["general"] },
    { "chinese": "人们一般都喜欢她", "english": "In general,people like her.", "type": "句子", "keyWords": ["general"] },
    { "chinese": "原则上；一般地说", "english": "as a general rule", "type": "短语", "keyWords": ["general"] },
    { "chinese": "通常我不接受采访，但这一次算是例外", "english": "I don't give interviews as a general rule, but in this case I'll make an exception.", "type": "句子", "keyWords": ["general"] },
    { "chinese": "一般说来", "english": "generally speaking", "type": "短语", "keyWords": ["general"] },
    { "chinese": "一般说来，你为立体声设备花钱越多，设备就越好", "english": "Generally speaking, the more you pay for stereo equipment, the better the system (is).", "type": "句子", "keyWords": ["general"] },
    { "chinese": "n.[C]一代(人)", "english": "generation", "type": "单词", "keyWords": [] },
    { "chinese": "代沟", "english": "generation gap", "type": "短语", "keyWords": ["generation"] },
    { "chinese": "一代又一代", "english": "from generation to generation/ generation after generation", "type": "短语", "keyWords": ["generation"] },
    { "chinese": "a.慷慨的，大方的", "english": "generous", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]慷慨，大方", "english": "generosity", "type": "单词", "keyWords": ["generous"] },
    { "chinese": "他花钱大方", "english": "He is generous with his money.", "type": "句子", "keyWords": ["generous"] },
    { "chinese": "n.[C](pl geniuses或genii)天才；天赋", "english": "genius", "type": "单词", "keyWords": [] },
    { "chinese": "有音乐天赋", "english": "have a genius/ talent/ gift for music", "type": "短语", "keyWords": ["genius"] },
    { "chinese": "a.柔和的；温和的；文雅的", "english": "gentle", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]柔和；文雅", "english": "gentleness", "type": "单词", "keyWords": ["gentle"] },
    { "chinese": "对待...很温和", "english": "be gentle with", "type": "短语", "keyWords": ["gentle"] },
    { "chinese": "n.[C]有教养的人；绅士；先生", "english": "gentleman", "type": "单词", "keyWords": [] },
    { "chinese": "a.真的；非人造的；非伪造的；真诚的", "english": "genuine", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]地理", "english": "geography", "type": "单词", "keyWords": [] },
    { "chinese": "a.地理学的，地理的", "english": "geographical", "type": "单词", "keyWords": ["geography"] },
    { "chinese": "n.[U]地质学", "english": "geology", "type": "单词", "keyWords": [] },
    { "chinese": "a.地质学的，地质的", "english": "geological", "type": "单词", "keyWords": ["geology"] },
    { "chinese": "n.[U]几何学", "english": "geometry", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]病菌，细菌", "english": "germ", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]手势；示意动作；姿态，表示 v.打手势；用动作示意", "english": "gesture", "type": "单词", "keyWords": [] },
    { "chinese": "打手势让我停下来", "english": "gesture for me to stop = make me stop with gestures", "type": "句子", "keyWords": ["gesture"] },
    { "chinese": "v.得到；达到；收获；使得；变得；成为", "english": "get", "type": "单词", "keyWords": [] },
    { "chinese": "开始做某事", "english": "get doing sth.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "我们不久就谈了起来", "english": "We soon got talking.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "让某人开始做某事", "english": "get sb.doing sth.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "让钟走起来", "english": "get the clock going", "type": "短语", "keyWords": ["get"] },
    { "chinese": "把工作开展起来", "english": "get things moving", "type": "短语", "keyWords": ["get"] },
    { "chinese": "逐渐知道/意识到/明白/爱上..", "english": "get come to know/realize/ understand/ love..", "type": "短语", "keyWords": ["get"] },
    { "chinese": "让某人去做某事", "english": "get sb. to do sth.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "让别人或自己把某事做了", "english": "get sth.done", "type": "短语", "keyWords": ["get"] },
    { "chinese": "使某人理解....", "english": "get...across to sb.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "横过；穿过", "english": "get across", "type": "短语", "keyWords": ["get"] },
    { "chinese": "努力使他们理解我的意思", "english": "try to get my idea across to them", "type": "句子", "keyWords": ["get"] },
    { "chinese": "生活；相处；进展；前进", "english": "get along (with sb/sth.)", "type": "短语", "keyWords": ["get"] },
    { "chinese": "你和姑母相处得好吗？", "english": "Do you get along well with your aunt?", "type": "句子", "keyWords": ["get"] },
    { "chinese": "即使没有任何助手，我们也要进行下去", "english": "We must get along somehow without any assistant.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "开始认真对待", "english": "get down to (sth/doing sth.)", "type": "短语", "keyWords": ["get"] },
    { "chinese": "度过了愉快的假期后很难一下子认真投入工作", "english": "It's hard to get down to work after a nice holiday.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "克服/战胜困难；从(疾病、震惊等)中恢复", "english": "get over", "type": "短语", "keyWords": ["get"] },
    { "chinese": "他刚刚痊愈", "english": "He is just getting over an illness.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "做完；(使)通过(考试等)；打通(电话)", "english": "get through", "type": "短语", "keyWords": ["get"] },
    { "chinese": "请你给我接通人事部", "english": "Please get me through to the Personnel Department.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "听到你(考试)及格时，我们很高兴", "english": "We were delighted when we heard you'd got through (your exam).", "type": "句子", "keyWords": ["get"] },
    { "chinese": "到处走动，传开", "english": "get around", "type": "短语", "keyWords": ["get"] },
    { "chinese": "收割庄稼", "english": "get in crops", "type": "短语", "keyWords": ["get"] },
    { "chinese": "下车；动身", "english": "get off", "type": "短语", "keyWords": ["get"] },
    { "chinese": "做了坏事未受惩处", "english": "get away with sth.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "为...做准备", "english": "get ready for", "type": "短语", "keyWords": ["get"] },
    { "chinese": "起床；起立", "english": "get up", "type": "短语", "keyWords": ["get"] },
    { "chinese": "使起床；使起立", "english": "get...up", "type": "短语", "keyWords": ["get"] },
    { "chinese": "逃跑", "english": "get away", "type": "短语", "keyWords": ["get"] },
    { "chinese": "到达", "english": "get to", "type": "短语", "keyWords": ["get"] },
    { "chinese": "n.[C]聚会", "english": "get-together", "type": "单词", "keyWords": ["get"] },
    { "chinese": "n.[C]鬼，幽灵", "english": "ghost", "type": "单词", "keyWords": [] },
    { "chinese": "a.像鬼般的", "english": "ghostly", "type": "单词", "keyWords": ["ghost"] },
    { "chinese": "a.巨大的 n.[C]伟人；巨人；大力士", "english": "giant", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]礼物，赠品；天赋", "english": "gift", "type": "单词", "keyWords": [] },
    { "chinese": "在某方面有天赋", "english": "have a gift/talent for", "type": "短语", "keyWords": ["gift"] },
    { "chinese": "她有学语言的天赋", "english": "She has a gift for learning languages.", "type": "句子", "keyWords": ["gift"] },
    { "chinese": "a.有天赋的；有天才的", "english": "gifted", "type": "单词", "keyWords": ["gift"] },
    { "chinese": "一个有天赋的钢琴家", "english": "a talented/ gifted pianist", "type": "短语", "keyWords": ["gifted"] },
    { "chinese": "n.[U]生姜", "english": "ginger", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]女孩", "english": "girl", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]少女时代", "english": "girlhood", "type": "单词", "keyWords": ["girl"] },
    { "chinese": "n.[C]女朋友", "english": "girlfriend", "type": "单词", "keyWords": ["girl"] },
    { "chinese": "v.给；赠送 a.赠予的；特定的；假设的", "english": "give", "type": "单词", "keyWords": [] },
    { "chinese": "屈服，让位", "english": "give way (to sb)", "type": "短语", "keyWords": ["give"] },
    { "chinese": "散发出(蒸汽、光等)", "english": "give off", "type": "短语", "keyWords": ["give"] },
    { "chinese": "在设定期间内", "english": "within a given time", "type": "短语", "keyWords": ["give"] },
    { "chinese": "发出警告", "english": "give a warning", "type": "短语", "keyWords": ["give"] },
    { "chinese": "投降；屈服；上交", "english": "give in", "type": "短语", "keyWords": ["give"] },
    { "chinese": "引起反对意见", "english": "give rise to (=cause) objections", "type": "短语", "keyWords": ["give"] },
    { "chinese": "放弃", "english": "give up", "type": "短语", "keyWords": ["give"] },
    { "chinese": "考虑这个问题", "english": "give thought to(=consider) the problem", "type": "短语", "keyWords": ["give"] },
    { "chinese": "发出(热、气味等)；分发；(供给等)用完；筋疲力尽", "english": "give out", "type": "短语", "keyWords": ["give"] },
    { "chinese": "油用光了", "english": "The oil gave out.", "type": "句子", "keyWords": ["give"] },
    { "chinese": "跑完十圈后他精疲力尽了", "english": "He (His leg) gave out after ten laps.", "type": "句子", "keyWords": ["give"] },
    { "chinese": "赠送；分发；放弃(机会)；泄露(秘密等)；出卖", "english": "give..away", "type": "短语", "keyWords": ["give"] },
    { "chinese": "出卖他", "english": "give him away", "type": "短语", "keyWords": ["give"] },
    { "chinese": "把财产送给别人", "english": "give away his fortune", "type": "短语", "keyWords": ["give"] },
    { "chinese": "泄露我的秘密", "english": "give away my secret", "type": "短语", "keyWords": ["give"] }
];
