const qgl121_128 = [
    { "chinese": "请代我问候某人", "english": "give my sincere regards/ greetings/ love/ best wishes to sb.", "type": "短语", "keyWords": [] },
    { "chinese": "倘若...；假定...；考虑到；在有...的情况下", "english": "given sth./that...", "type": "短语", "keyWords": [] },
    { "chinese": "就发动机目前的状况，倘若它还能发动的话，可真是不可思议", "english": "Given the condition of the engine, it is a wonder that it even starts.", "type": "句子", "keyWords": [] },
    { "chinese": "a.高兴的；乐意的", "english": "glad", "type": "单词", "keyWords": [] },
    { "chinese": "对……感到高兴", "english": "be glad about/at", "type": "短语", "keyWords": ["glad"] },
    { "chinese": "非常乐意做某事", "english": "be only too/ more than glad to do sth.", "type": "短语", "keyWords": ["glad"] },
    { "chinese": "v.看一眼；扫视，匆匆一看；一瞥 n.[C]一眼，一看", "english": "glance", "type": "单词", "keyWords": [] },
    { "chinese": "看一眼", "english": "glance/ stare at", "type": "短语", "keyWords": ["glance"] },
    { "chinese": "看一眼……", "english": "take/ have a glance (at...)", "type": "短语", "keyWords": ["glance"] },
    { "chinese": "一看（就……）", "english": "at a glance", "type": "短语", "keyWords": ["glance"] },
    { "chinese": "乍一看", "english": "at first glance/sight", "type": "短语", "keyWords": ["glance"] },
    { "chinese": "乍一看此计划好像行不通", "english": "At first glance the plan seemed unfeasible.", "type": "句子", "keyWords": ["glance"] },
    { "chinese": "vi./n.[C]怒视(at sth.)；发出耀眼的光", "english": "glare", "type": "单词", "keyWords": [] },
    { "chinese": "耀眼的光", "english": "glaring light", "type": "短语", "keyWords": ["glare"] },
    { "chinese": "n.[C](常用单数)一瞥，一看 vi.瞥见", "english": "glimpse", "type": "单词", "keyWords": [] },
    { "chinese": "瞥见……", "english": "catch/ get a glimpse of...", "type": "短语", "keyWords": ["glimpse"] },
    { "chinese": "n.[C]玻璃杯 n.[U]玻璃 (pl.glasses)眼镜", "english": "glass", "type": "单词", "keyWords": [] },
    { "chinese": "v.滑行；滑翔；悄悄地走 n.[C]滑行，滑翔", "english": "glide", "type": "单词", "keyWords": [] },
    { "chinese": "vi.闪闪发光", "english": "glitter", "type": "单词", "keyWords": [] },
    { "chinese": "闪闪发光者，未必尽黄金", "english": "All is not gold that glitters.", "type": "句子", "keyWords": ["glitter"] },
    { "chinese": "n.[C]地球仪；球形体；(the)地球，世界", "english": "globe", "type": "单词", "keyWords": [] },
    { "chinese": "a.球形的；全球的；全世界的", "english": "global", "type": "单词", "keyWords": ["globe"] },
    { "chinese": "vt.使全球化", "english": "globalize", "type": "单词", "keyWords": ["globe"] },
    { "chinese": "一个地球仪", "english": "a globe", "type": "短语", "keyWords": ["globe"] },
    { "chinese": "a.光荣的；辉煌的", "english": "glorious", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]光荣，荣耀；声誉", "english": "glory", "type": "单词", "keyWords": [] },
    { "chinese": "vt.赞美，赞颂；给予……荣耀", "english": "glorify", "type": "单词", "keyWords": ["glory"] },
    { "chinese": "n.[C]手套", "english": "glove", "type": "单词", "keyWords": [] },
    { "chinese": "一副手套", "english": "a pair of gloves", "type": "短语", "keyWords": ["glove"] },
    { "chinese": "n.[U]胶水 v.胶合，粘贴，黏合", "english": "glue", "type": "单词", "keyWords": [] },
    { "chinese": "vi.去，走；（时间）消逝；归属于……，落入……手中；成为；变为 n.[C]试试", "english": "go", "type": "单词", "keyWords": [] },
    { "chinese": "追（捕）；追求", "english": "go after", "type": "短语", "keyWords": ["go"] },
    { "chinese": "发生故障；出错；出毛病", "english": "go wrong", "type": "短语", "keyWords": ["go"] },
    { "chinese": "回过来谈；追溯到", "english": "go back to", "type": "短语", "keyWords": ["go"] },
    { "chinese": "爆炸；（枪等）响", "english": "go off", "type": "短语", "keyWords": ["go"] },
    { "chinese": "继续做", "english": "go on doing sth.", "type": "短语", "keyWords": ["go"] },
    { "chinese": "进行；进展；（时间）流逝", "english": "go on", "type": "短语", "keyWords": ["go"] },
    { "chinese": "爱好，喜欢；从事", "english": "go in for", "type": "短语", "keyWords": ["go"] },
    { "chinese": "走上前去", "english": "go up to", "type": "短语", "keyWords": ["go"] },
    { "chinese": "出去；（灯火）熄灭", "english": "go out", "type": "短语", "keyWords": ["go"] },
    { "chinese": "违反；对……不利", "english": "(sth.) go against", "type": "短语", "keyWords": ["go"] },
    { "chinese": "变得无用，浪费掉", "english": "go to waste", "type": "短语", "keyWords": ["go"] },
    { "chinese": "下沉；下降", "english": "go down", "type": "短语", "keyWords": ["go"] },
    { "chinese": "松手，放开；释放", "english": "let go of sb. or sth.", "type": "短语", "keyWords": ["go"] },
    { "chinese": "干吧，说吧；继续", "english": "go ahead (with...)", "type": "短语", "keyWords": ["go"] },
    { "chinese": "忙碌", "english": "on the go/ run", "type": "短语", "keyWords": ["go"] },
    { "chinese": "复习；走到另一边去；检查", "english": "go over", "type": "短语", "keyWords": ["go"] },
    { "chinese": "越来越糟", "english": "go from bad to worse", "type": "短语", "keyWords": ["go"] },
    { "chinese": "双/单膝跪", "english": "go/ get down on one's knee(s)", "type": "短语", "keyWords": ["go"] },
    { "chinese": "竭尽全力/鼓足干劲去做", "english": "go all out to do...", "type": "短语", "keyWords": ["go"] },
    { "chinese": "变疯/秃/腐烂/坏/酸/聋/瞎/饿/红/白", "english": "go mad/ bald/ rotten/ bad/ sour/ deaf/ blind/ hungry/ red/ white", "type": "短语", "keyWords": ["go"] },
    { "chinese": "无一定方向走动；着手进行(sth./doing sth.)；传开", "english": "go about", "type": "短语", "keyWords": ["go"] },
    { "chinese": "（疾病、消息）传播；访问；顺便走访；足够分配", "english": "go round/around", "type": "短语", "keyWords": ["go"] },
    { "chinese": "目前重感冒正在流行", "english": "There are a lot of very bad colds going around at the moment.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "如果没有足够的椅子分给每个人坐，有些人就必须站着", "english": "If there are not enough chairs to go round/ around, some people will have to stand.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "经历（苦难等）；审阅；讨论；检查；翻找；看一遍；做完；用完", "english": "go through", "type": "短语", "keyWords": ["go"] },
    { "chinese": "审阅试卷/翻抽屉", "english": "go through the papers/ drawers", "type": "短语", "keyWords": ["go"] },
    { "chinese": "胜利永远属于强者", "english": "Victory always goes to the strong.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "事情进展得非常顺利", "english": "Things are going very well.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "那首歌/诗是怎么说的", "english": "How does that song/poem go?", "type": "句子", "keyWords": ["go"] },
    { "chinese": "故事说/据说他很富裕", "english": "The story goes that he was very rich.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "就像谚语所说，活到老学到老", "english": "As the saying goes, never too old to learn.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "没有……而勉强应付", "english": "go without (sth.)", "type": "短语", "keyWords": ["go"] },
    { "chinese": "那时候我们常常没晚饭吃，将就一下熬过去", "english": "In those days we often had to go without supper.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "恐怕你要将就一下，早饭没有牛奶喝", "english": "I'm afraid you'll have to go without milk for breakfast.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "伴随，与……相配", "english": "go with..", "type": "短语", "keyWords": ["go"] },
    { "chinese": "这条领带和你的衬衫很配", "english": "The tie goes very well with your shirt.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "鱼和茶不配", "english": "Fish doesn't go well with tea.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "犯罪不一定总和贫困联系在一起", "english": "Crime doesn't necessarily go (hand in hand) with poverty.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "痛苦已经过去", "english": "The pain has gone.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "时光飞逝", "english": "Time went by quickly.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "依赖他的日子一去不复返了", "english": "Gone are the days when we had to depend on him.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "让我们来试试", "english": "Let's have a go at it.", "type": "句子", "keyWords": ["go"] },
    { "chinese": "竭尽全力/鼓足干劲去做", "english": "go to all lengths to do...", "type": "短语", "keyWords": ["go"] },
    { "chinese": "n.[C]中间人，媒人，掮客", "english": "go-between", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]目标；目的；球门；进球", "english": "goal", "type": "单词", "keyWords": [] },
    { "chinese": "生活目标", "english": "life goal", "type": "短语", "keyWords": ["goal"] },
    { "chinese": "长远目标", "english": "a long-term goal", "type": "短语", "keyWords": ["goal"] },
    { "chinese": "完成目标", "english": "achieve a goal", "type": "短语", "keyWords": ["goal"] },
    { "chinese": "以三比二获胜", "english": "win by three goals to two", "type": "短语", "keyWords": ["goal"] },
    { "chinese": "进球", "english": "score a goal", "type": "短语", "keyWords": ["goal"] },
    { "chinese": "n.[C](足球等运动)守门员", "english": "goalkeeper", "type": "单词", "keyWords": ["goal"] },
    { "chinese": "n.[C]山羊", "english": "goat", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]神；上帝( God)", "english": "god", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]女神", "english": "goddess", "type": "单词", "keyWords": ["god"] },
    { "chinese": "上帝与你同在", "english": "God be with you.", "type": "句子", "keyWords": ["god"] },
    { "chinese": "上帝知道（他去哪儿了）", "english": "God knows (where he went).", "type": "句子", "keyWords": ["god"] },
    { "chinese": "n.[U]金，黄金 n.[C]金牌 a.金(制)的，金色的，似金的", "english": "gold", "type": "单词", "keyWords": [] },
    { "chinese": "金粉", "english": "gold dust", "type": "短语", "keyWords": ["gold"] },
    { "chinese": "n.[C]淘金热", "english": "the gold rush", "type": "短语", "keyWords": ["gold"] },
    { "chinese": "n.(单复同)金鱼", "english": "goldfish", "type": "单词", "keyWords": ["gold"] },
    { "chinese": "a.黄金般的；金色的；极好的；重要的", "english": "golden", "type": "单词", "keyWords": ["gold"] },
    { "chinese": "黄金时代", "english": "a golden age", "type": "短语", "keyWords": ["golden"] },
    { "chinese": "黄金法则", "english": "a golden rule", "type": "短语", "keyWords": ["golden"] },
    { "chinese": "极好的机会", "english": "a golden opportunity", "type": "短语", "keyWords": ["golden"] },
    { "chinese": "幸福的时刻", "english": "golden hours", "type": "短语", "keyWords": ["golden"] },
    { "chinese": "n.[U]高尔夫球", "english": "golf", "type": "单词", "keyWords": [] },
    { "chinese": "a.走了的，离去的；死去的；用光的；无望的，不可挽救的", "english": "gone", "type": "单词", "keyWords": ["go"] },
    { "chinese": "a.好的；足足的；好心的；有益的 n.[U]有利的事；好处；好事；用处", "english": "good", "type": "单词", "keyWords": [] },
    { "chinese": "善与恶", "english": "good and evil", "type": "短语", "keyWords": ["good"] },
    { "chinese": "擅长", "english": "be good at", "type": "短语", "keyWords": ["good"] },
    { "chinese": "永远", "english": "for good (and all)", "type": "短语", "keyWords": ["good"] },
    { "chinese": "对某人/某物有好处", "english": "do good to sb./sth.", "type": "短语", "keyWords": ["good"] },
    { "chinese": "对某人好", "english": "be good/ kind to sb.", "type": "短语", "keyWords": ["good"] },
    { "chinese": "对……有好处", "english": "be good for...", "type": "短语", "keyWords": ["good"] },
    { "chinese": "好一会", "english": "for a good while", "type": "短语", "keyWords": ["good"] },
    { "chinese": "给了好一顿责骂", "english": "give a good scolding", "type": "短语", "keyWords": ["good"] },
    { "chinese": "足有三英里", "english": "It's a good three miles.", "type": "句子", "keyWords": ["good"] },
    { "chinese": "为了……的好处", "english": "for the good of sb./ sth.= for one's good", "type": "短语", "keyWords": ["good"] },
    { "chinese": "我为了身体健康去游泳", "english": "I go swimming for the good of health.", "type": "句子", "keyWords": ["good"] },
    { "chinese": "做某事没用/不好/不行", "english": "It's no good/ not much good/ not any good doing sth.", "type": "句子", "keyWords": ["good"] },
    { "chinese": "跟他讲没用，因为他从来不会听", "english": "It's no good talking to him, because he never listens.", "type": "句子", "keyWords": ["good"] },
    { "chinese": "interj.再见 n.[C][U]告别", "english": "goodbye", "type": "单词", "keyWords": ["good"] },
    { "chinese": "跟某人挥手告别", "english": "wave sb. goodbye", "type": "短语", "keyWords": ["goodbye"] },
    { "chinese": "跟某人告别/道别", "english": "say goodbye to sb.", "type": "短语", "keyWords": ["goodbye"] },
    { "chinese": "a.友善的；愉快的；不易动怒的", "english": "good-natured", "type": "单词", "keyWords": ["good"] },
    { "chinese": "脾气好的", "english": "good-tempered", "type": "单词", "keyWords": ["good"] },
    { "chinese": "漂亮的", "english": "good-looking", "type": "单词", "keyWords": ["good"] },
    { "chinese": "快乐的，愉快的；脾气好的", "english": "good-humoured", "type": "单词", "keyWords": ["good"] },
    { "chinese": "n.[U]仁慈；善(良)；美德 interj.(用于感叹句)天啊；啊呀", "english": "goodness", "type": "单词", "keyWords": ["good"] },
    { "chinese": "谢天谢地", "english": "Thank goodness!", "type": "句子", "keyWords": ["goodness"] },
    { "chinese": "看在老天爷的份上", "english": "for goodness'sake", "type": "短语", "keyWords": ["goodness"] },
    { "chinese": "n.(pl.)货物；商品", "english": "goods", "type": "单词", "keyWords": ["good"] },
    { "chinese": "n.[C](pl geese)鹅", "english": "goose", "type": "单词", "keyWords": [] },
    { "chinese": "杀鸡取卵；自断财路", "english": "kill the goose that lays the golden eggs", "type": "短语", "keyWords": ["goose"] },
    { "chinese": "a.[口]好极了的；漂亮的；令人满意的", "english": "gorgeous", "type": "单词", "keyWords": [] },
    { "chinese": "v.闲聊；说长道短；传布流言蜚语 n.[C]说长道短；爱说闲话的人 n.[U]闲话", "english": "gossip", "type": "单词", "keyWords": [] },
    { "chinese": "闲谈，搬弄是非", "english": "gossip about", "type": "短语", "keyWords": ["gossip"] },
    { "chinese": "v.统治；支配；管理", "english": "govern", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]统治者；州长；总督；管理者", "english": "governor", "type": "单词", "keyWords": ["govern"] },
    { "chinese": "n.[C]政府(集合名词，用作单或复)；政体；治理；管理", "english": "government", "type": "单词", "keyWords": ["govern"] },
    { "chinese": "地方/中央政府", "english": "local/ central government", "type": "短语", "keyWords": ["government"] },
    { "chinese": "v.突然抓住；抢夺，攫取；夺取；匆忙做某事", "english": "grab", "type": "单词", "keyWords": [] },
    { "chinese": "a.优雅的；优美的；得体的；体面的", "english": "graceful", "type": "单词", "keyWords": [] },
    { "chinese": "a.不优雅的", "english": "disgraceful", "type": "单词", "keyWords": ["graceful"] },
    { "chinese": "n.[U]优美，雅致，优雅", "english": "grace", "type": "单词", "keyWords": [] },
    { "chinese": "优雅地跳舞", "english": "dance with grace", "type": "短语", "keyWords": ["grace"] },
    { "chinese": "interj.(在感叹句中表示惊讶)啊呀! a.亲切的；仁慈宽厚的", "english": "gracious", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]年级；级别；成绩；评分等级 v.把……按级分类；批改(作业等)", "english": "grade", "type": "单词", "keyWords": [] },
    { "chinese": "a.逐渐的，逐步的，渐进的", "english": "gradual", "type": "单词", "keyWords": [] },
    { "chinese": "ad.渐渐地；逐步地", "english": "gradually", "type": "单词", "keyWords": ["gradual"] },
    { "chinese": "n.[C](尤指学士)学位获得者；(美)毕业生 v.接受学位；(美)毕业 v.(美)授予……学位；使毕业", "english": "graduate", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]毕业", "english": "graduation", "type": "单词", "keyWords": ["graduate"] },
    { "chinese": "毕业于", "english": "graduate from = be graduated from", "type": "短语", "keyWords": ["graduate"] },
    { "chinese": "n.[U]谷物 n.[C]一粒(沙、盐等)；谷粒", "english": "grain", "type": "单词", "keyWords": [] },
    { "chinese": "沙粒/米粒", "english": "grains of sand/rice", "type": "短语", "keyWords": ["grain"] },
    { "chinese": "n.[C]克", "english": "gram", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]语法 n.[C]语法书", "english": "grammar", "type": "单词", "keyWords": [] },
    { "chinese": "a.语法的", "english": "grammatical", "type": "单词", "keyWords": ["grammar"] },
    { "chinese": "a.宏伟的；庄重的；主要的", "english": "grand", "type": "单词", "keyWords": [] },
    { "chinese": "n.(外)祖父/母", "english": "grandfather/grandmother", "type": "单词", "keyWords": ["grand"] },
    { "chinese": "n.(外)祖父/母", "english": "grandpa/ grandma", "type": "单词", "keyWords": ["grandfather/grandmother"] },
    { "chinese": "n.(外)祖父/母", "english": "grandparent", "type": "单词", "keyWords": ["grand"] },
    { "chinese": "n.(外)曾祖父", "english": "great grandfather", "type": "单词", "keyWords": ["grand"] },
    { "chinese": "n.(外)孙子/孙女", "english": "grandchild/ grandson/ granddaughter", "type": "单词", "keyWords": ["grand"] },
    { "chinese": "v.同意，准予；承认(某事为真)；授予(常暗含施与者比接受者地位更高) n.[C]同意，准许；授予物；承认", "english": "grant", "type": "单词", "keyWords": [] },
    { "chinese": "认为……理所当然", "english": "take ... for granted/ take it for granted that...", "type": "短语", "keyWords": ["grant"] },
    { "chinese": "假定……，即使……", "english": "granting that.../granted sth./that...", "type": "短语", "keyWords": ["grant"] },
    { "chinese": "准许", "english": "grant permission", "type": "短语", "keyWords": ["grant"] },
    { "chinese": "n.[C]葡萄", "english": "grape", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]/v.抓住；抓牢；领悟；理解", "english": "grasp", "type": "单词", "keyWords": [] },
    { "chinese": "设法抓住", "english": "grasp at (the rope...)", "type": "短语", "keyWords": ["grasp"] },
    { "chinese": "抓住机遇", "english": "grasp a chance/ an opportunity", "type": "短语", "keyWords": ["grasp"] },
    { "chinese": "领会……精神", "english": "grasp the spirit of", "type": "短语", "keyWords": ["grasp"] },
    { "chinese": "紧紧抓住绳子", "english": "take a firm grasp on the rope", "type": "短语", "keyWords": ["grasp"] },
    { "chinese": "贪多必失", "english": "Grasp all, lose all.", "type": "句子", "keyWords": ["grasp"] },
    { "chinese": "n.[U]草；(the)草地 n.[C]草种", "english": "grass", "type": "单词", "keyWords": [] },
    { "chinese": "勿踏草地", "english": "Keep off the grass.", "type": "句子", "keyWords": ["grass"] },
    { "chinese": "a.感激的；感谢的", "english": "grateful", "type": "单词", "keyWords": [] },
    { "chinese": "因……感激某人", "english": "be grateful to sb. for sth./ doing sth.", "type": "短语", "keyWords": ["grateful"] },
    { "chinese": "如果你能……我会很感激", "english": "I would be grateful if you could...", "type": "句子", "keyWords": ["grateful"] },
    { "chinese": "n.[U]感激(之情)", "english": "gratitude", "type": "单词", "keyWords": ["grateful"] },
    { "chinese": "感激地", "english": "with gratitude", "type": "短语", "keyWords": ["gratitude"] },
    { "chinese": "n.[C]墓(穴) a.严肃的；(声音)低沉的；庄严的；重大的", "english": "grave", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]重力，引力；严重性；严肃；庄重", "english": "gravity", "type": "单词", "keyWords": ["grave"] },
    { "chinese": "a.伟大的；巨大的；崇高的；[口]美妙的", "english": "great", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]伟大；崇高", "english": "greatness", "type": "单词", "keyWords": ["great"] },
    { "chinese": "n.希腊", "english": "Greece", "type": "单词", "keyWords": [] },
    { "chinese": "a.希腊的，希腊人的，希腊语的 n.希腊人，希腊语", "english": "Greek", "type": "单词", "keyWords": ["Greece"] },
    { "chinese": "a.贪婪的", "english": "greedy", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]贪婪", "english": "greed", "type": "单词", "keyWords": ["greedy"] },
    { "chinese": "渴望利润/权力/名声", "english": "be greedy for profit/ power/fame", "type": "短语", "keyWords": ["greedy"] },
    { "chinese": "n.[U]绿色；(城市)公共草地 a.绿色的；未成熟的；新鲜的", "english": "green", "type": "单词", "keyWords": [] },
    { "chinese": "温室效应", "english": "greenhouse effect", "type": "短语", "keyWords": ["green"] },
    { "chinese": "工作生疏", "english": "be green at the job", "type": "短语", "keyWords": ["green"] },
    { "chinese": "我还不至于幼稚到相信那种事的地步", "english": "I'm not so green as to believe that.", "type": "句子", "keyWords": ["green"] },
    { "chinese": "v.问候；招呼", "english": "greet", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]问候；招呼", "english": "greeting", "type": "单词", "keyWords": ["greet"] },
    { "chinese": "用微笑迎接/招呼某人", "english": "greet sb. with a smile", "type": "短语", "keyWords": ["greet"] },
    { "chinese": "在大门口迎接客人", "english": "greet/ receive guests at the gate", "type": "短语", "keyWords": ["greet"] },
    { "chinese": "n.[U]灰色 a.灰色的；晦暗的", "english": "grey", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]悲伤，悲痛；不幸；伤心的事", "english": "grief", "type": "单词", "keyWords": [] },
    { "chinese": "v.(使)感到悲痛(at about over)", "english": "grieve", "type": "单词", "keyWords": ["grief"] },
    { "chinese": "n.[C]烤架；烧烤店；烤炙 v.(在烤架等上面)烤炙 vi.受烤炙", "english": "grill", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]杂货店；(pl)杂货", "english": "grocery", "type": "单词", "keyWords": [] },
    { "chinese": "n.(the)地面；土地 [C]场地；战场；(pl.)根据，理由(of, for)", "english": "ground", "type": "单词", "keyWords": [] },
    { "chinese": "你没有这么做的理由", "english": "You have no ground(s) of/ for doing it.", "type": "句子", "keyWords": ["ground"] },
    { "chinese": "你根据什么说它是真的", "english": "On what ground do you say that it is true?", "type": "句子", "keyWords": ["ground"] },
    { "chinese": "n.[C]组；(集合名词)团体 v.把……分组(或归类)；聚集 vi.聚集", "english": "group", "type": "单词", "keyWords": [] },
    { "chinese": "三五成群地站着", "english": "stand about in small groups", "type": "短语", "keyWords": ["group"] },
    { "chinese": "v.种植；栽种 vi.生长，成长；发育；变得", "english": "grow", "type": "单词", "keyWords": [] },
    { "chinese": "a.不断增长的", "english": "growing", "type": "单词", "keyWords": ["grow"] },
    { "chinese": "a.成年的；成熟的", "english": "grown", "type": "单词", "keyWords": ["grow"] },
    { "chinese": "长高了两英寸", "english": "grow 2 inches", "type": "短语", "keyWords": ["grow"] },
    { "chinese": "发育中的孩子", "english": "a growing child", "type": "短语", "keyWords": ["growing"] },
    { "chinese": "长成为", "english": "grow into", "type": "短语", "keyWords": ["grow"] },
    { "chinese": "他长成了一个翩翩少年", "english": "He has grown into a fine young man.", "type": "句子", "keyWords": ["grow"] },
    { "chinese": "长大成人", "english": "grow up", "type": "短语", "keyWords": ["grow"] },
    { "chinese": "你长大后想当什么", "english": "What do you want to be when you grow up?", "type": "句子", "keyWords": ["grow"] },
    { "chinese": "因长大而穿不下；由……产生", "english": "grow out of", "type": "短语", "keyWords": ["grow"] },
    { "chinese": "她长大了，外套穿不下了", "english": "She grows out of her coat.", "type": "句子", "keyWords": ["grow"] },
    { "chinese": "争论源于误解", "english": "Arguments grow out of misunderstandings.", "type": "句子", "keyWords": ["grow"] },
    { "chinese": "a.成熟的，成年人的 n.[C](pl grown-ups)成年人", "english": "grown-up", "type": "单词", "keyWords": ["grow"] },
    { "chinese": "n.[U]生长，发育；种植，栽培；增长", "english": "growth", "type": "单词", "keyWords": ["grow"] },
    { "chinese": "增长率", "english": "growth rate", "type": "短语", "keyWords": ["growth"] },
    { "chinese": "vi./n.[C]抱怨，发牢骚，咕哝", "english": "grumble", "type": "单词", "keyWords": [] },
    { "chinese": "就……抱怨，发牢骚", "english": "grumble about", "type": "短语", "keyWords": ["grumble"] },
    { "chinese": "n.[C]抵押品；担保物；保证，担保 v.保证，担保", "english": "guarantee", "type": "单词", "keyWords": [] },
    { "chinese": "保用两年的手表", "english": "a watch with a two-year guarantee", "type": "短语", "keyWords": ["guarantee"] },
    { "chinese": "我的表保修一年", "english": "My watch is guaranteed for one year.", "type": "句子", "keyWords": ["guarantee"] },
    { "chinese": "我敢保证", "english": "I can guarantee that...", "type": "句子", "keyWords": ["guarantee"] },
    { "chinese": "买了票也不一定有座位", "english": "Buying a ticket doesn't guarantee you a seat.", "type": "句子", "keyWords": ["guarantee"] },
    { "chinese": "n.[C]卫兵；哨兵；看守 n.[U]守卫，警戒 v.保卫；守卫；警卫；看守", "english": "guard", "type": "单词", "keyWords": [] },
    { "chinese": "守门", "english": "keep guard at the door", "type": "短语", "keyWords": ["guard"] },
    { "chinese": "提防；防范", "english": "guard against", "type": "短语", "keyWords": ["guard"] },
    { "chinese": "vi./v./n.[C]猜测；推测；认为", "english": "guess", "type": "单词", "keyWords": [] },
    { "chinese": "猜测", "english": "(have/ make a) guess at sth. = answer ... by guess", "type": "短语", "keyWords": ["guess"] },
    { "chinese": "n.[C]宾客，客人", "english": "guest", "type": "单词", "keyWords": [] },
    { "chinese": "贵宾，主宾", "english": "the guest of honour", "type": "短语", "keyWords": ["guest"] },
    { "chinese": "n.[U]指导，引导；咨询", "english": "guidance", "type": "单词", "keyWords": [] },
    { "chinese": "在某人的指导下", "english": "under the guidance of sb.", "type": "短语", "keyWords": ["guidance"] },
    { "chinese": "n.[C]指南；向导；导游 v.给……领路；引导；指导", "english": "guide", "type": "单词", "keyWords": [] },
    { "chinese": "巴黎旅游指南", "english": "a guide to Paris", "type": "短语", "keyWords": ["guide"] },
    { "chinese": "a.有罪的；有过失的；内疚的", "english": "guilty", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]罪行；内疚", "english": "guilt", "type": "单词", "keyWords": ["guilty"] },
    { "chinese": "内疚", "english": "a guilty conscience", "type": "短语", "keyWords": ["guilty"] },
    { "chinese": "(因……)感到内疚", "english": "feel guilty (about sth.)", "type": "短语", "keyWords": ["guilty"] },
    { "chinese": "他犯有谋杀罪", "english": "He was guilty of murder.", "type": "句子", "keyWords": ["guilty"] },
    { "chinese": "n.[C]吉他", "english": "guitar", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl. gulfs)海湾；鸿沟", "english": "gulf", "type": "单词", "keyWords": [] },
    { "chinese": "墨西哥湾", "english": "the Gulf of Mexico", "type": "短语", "keyWords": ["gulf"] },
    { "chinese": "贫富之间的悬殊差异", "english": "the gulf between rich and poor", "type": "短语", "keyWords": ["gulf"] },
    { "chinese": "n.[U]口香糖；黏胶；黏合剂 v.以树胶黏合，粘住", "english": "gum", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]炮；枪", "english": "gun", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]黑色火药，有烟火药", "english": "gunpowder", "type": "单词", "keyWords": ["gun"] },
    { "chinese": "n.[C]家伙，小伙子；人", "english": "guy", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl gymnasia) 健身房；体育馆", "english": "gymnasium", "type": "单词", "keyWords": [] },
    { "chinese": "a.体操的", "english": "gymnastic", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]体操", "english": "gymnastics", "type": "单词", "keyWords": ["gymnastic"] },
    { "chinese": "n.[C]习惯；(动物的)习性", "english": "habit", "type": "单词", "keyWords": [] },
    { "chinese": "使某人染上某嗜好", "english": "get sb.into the habit of", "type": "短语", "keyWords": ["habit"] },
    { "chinese": "(做...)只是出于习惯", "english": "out of habit", "type": "短语", "keyWords": ["habit"] },
    { "chinese": "改掉习惯", "english": "break away from/ get rid of the habit", "type": "短语", "keyWords": ["habit"] },
    { "chinese": "饮食习惯", "english": "eating/ drinking habit", "type": "短语", "keyWords": ["habit"] },
    { "chinese": "养成做某事的习惯", "english": "form a habit of doing.. = fall/ get into/ develop the habit of doing", "type": "短语", "keyWords": ["habit"] },
    { "chinese": "有...的习惯", "english": "be in the habit of doing = have the/ a habit of", "type": "短语", "keyWords": ["habit"] },
    { "chinese": "我通常没有借钱给人的习惯，但这一回我会破例", "english": "I am not in the habit of lending money, but I make an exception in this case.", "type": "句子", "keyWords": ["habit"] },
    { "chinese": "a.习惯的，惯常的", "english": "habitual", "type": "单词", "keyWords": ["habit"] },
    { "chinese": "惯犯", "english": "a habitual criminal", "type": "短语", "keyWords": ["habitual"] },
    { "chinese": "v.有（have的过去式）", "english": "had", "type": "单词", "keyWords": [] },
    { "chinese": "还是..好，最好还是", "english": "had better", "type": "短语", "keyWords": ["had"] },
    { "chinese": "最好不要这样，是不是？", "english": "Better not, had you?", "type": "句子", "keyWords": ["had"] },
    { "chinese": "n.[C][U]头发；毛发", "english": "hair", "type": "单词", "keyWords": [] },
    { "chinese": "使某人毛骨悚然", "english": "make one's hair stand on end", "type": "短语", "keyWords": ["hair"] },
    { "chinese": "n.[C]理发", "english": "haircut", "type": "单词", "keyWords": ["hair"] },
    { "chinese": "n.[C]理发师", "english": "hairdresser", "type": "单词", "keyWords": ["hair"] },
    { "chinese": "n.[U]理发", "english": "hairdressing", "type": "单词", "keyWords": ["hair"] },
    { "chinese": "n.[C]一半，半 a.一半的；不完全的；半途的 ad.一半（程度）地", "english": "half", "type": "单词", "keyWords": [] },
    { "chinese": "切成两半/缩减一半", "english": "cut/ reduce sth.by half", "type": "短语", "keyWords": ["half"] },
    { "chinese": "切成两半（碎片）", "english": "break/ cut sth. in half/ into halves ( into pieces)", "type": "短语", "keyWords": ["half"] },
    { "chinese": "a.中途的，半路的；部分的，不彻底的 ad.在中途；一半路程", "english": "halfway", "type": "单词", "keyWords": ["half"] },
    { "chinese": "n.[C]大厅；礼堂；走廊；门厅", "english": "hall", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]汉堡包；汉堡牛排或牛肉煎饼", "english": "hamburger", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]铁锤，锤子，榔头；槌 v.锤击；用头敲", "english": "hammer", "type": "单词", "keyWords": [] },
    { "chinese": "v.递给 n.[C]手；帮手；（钟表等的）指针", "english": "hand", "type": "单词", "keyWords": [] },
    { "chinese": "把某物移交（给...）", "english": "hand... over (to sb.)", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "分发", "english": "hand... out", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "上交", "english": "hand ... in=turn .. in", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "在手边；在附近；就要到来", "english": "at hand", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "试着做某事", "english": "try one's hand at (doing) sth.", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "我们缺人手", "english": "We're short of hands.", "type": "句子", "keyWords": ["hand"] },
    { "chinese": "一方面...另一方面...", "english": "on the one hand...on the other hand", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "把某物递给某人", "english": "hand...to sb.", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "给每个人提供（饮食等）", "english": "hand sth.(a)round", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "交还", "english": "hand ... back (to sb.)", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "在某人的掌握中", "english": "in sb.'s hands", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "用人工；靠手工", "english": "by hand", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "勉强糊口度日", "english": "live from hand to mouth", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "勿碰机器！", "english": "(Keep your) hands off the machine!", "type": "句子", "keyWords": ["hand"] },
    { "chinese": "把...传给后代；把（东西）往下递", "english": "hand .. on/ down (to sb.)", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "在某事上帮某人忙", "english": "give/ lend (sb.) a (helping) hand with sth.", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "帮忙抬一下这张沉重的桌子好吗？", "english": "Could you give me a hand with this heavy table?", "type": "句子", "keyWords": ["hand"] },
    { "chinese": "手拉手；与...相配合；与...一致；与...结合在一起", "english": "hand in hand (with...)", "type": "短语", "keyWords": ["hand"] },
    { "chinese": "愚昧无知必生偏见", "english": "Prejudice goes hand in hand with ignorance.", "type": "句子", "keyWords": ["hand"] },
    { "chinese": "n.[C]手提包", "english": "handbag", "type": "单词", "keyWords": ["hand"] },
    { "chinese": "n.[C]一把；少数", "english": "handful", "type": "单词", "keyWords": ["hand"] },
    { "chinese": "只有少数几个人", "english": "only a handful of people", "type": "短语", "keyWords": ["handful"] },
    { "chinese": "一把石子", "english": "a handful of stones", "type": "短语", "keyWords": ["handful"] },
    { "chinese": "n.[C]手帕", "english": "handkerchief", "type": "单词", "keyWords": ["hand"] },
    { "chinese": "v.触，摸；用手拿起；弄；抓；操纵；操作；处理，管理，应付 n.[C]手柄；把手", "english": "handle", "type": "单词", "keyWords": ["hand"] },
    { "chinese": "a.英俊的；漂亮的；相当大的，可观的", "english": "handsome", "type": "单词", "keyWords": ["hand"] },
    { "chinese": "一笔可观的回报/薪水", "english": "a handsome reward/salary", "type": "短语", "keyWords": ["handsome"] },
    { "chinese": "n.[U]书法；书写；笔迹", "english": "handwriting", "type": "单词", "keyWords": ["hand"] },
    { "chinese": "a.手边的，就近的，唾手可得的，容易取得的；便利的；手巧的", "english": "handy", "type": "单词", "keyWords": ["hand"] },
    { "chinese": "n.[C]分发的印刷品", "english": "handout", "type": "单词", "keyWords": ["hand"] },
    { "chinese": "vi./vt. (hung, hung) 悬挂；吊死，(hanged, hanged)绞死", "english": "hang", "type": "单词", "keyWords": [] },
    { "chinese": "（电话）等一等", "english": "hang on", "type": "短语", "keyWords": ["hang"] },
    { "chinese": "挂断电话", "english": "hang up", "type": "短语", "keyWords": ["hang"] },
    { "chinese": "闲待着；闲荡", "english": "hang around/ hang about", "type": "短语", "keyWords": ["hang"] },
    { "chinese": "vi.（偶然）发生；碰巧（后接不定式）", "english": "happen", "type": "单词", "keyWords": [] },
    { "chinese": "碰巧...", "english": "It (so) happens that...", "type": "句子", "keyWords": ["happen"] },
    { "chinese": "临到...头上", "english": "happen to sb./sth.", "type": "短语", "keyWords": ["happen"] },
    { "chinese": "碰巧在/正在/已经做某事", "english": "sb. happens to do/ to be doing sth./ to have done sth.", "type": "短语", "keyWords": ["happen"] },
    { "chinese": "这是昨天发生的车祸的照片", "english": "This is the picture of the accident that happened yesterday. (不可省略that)", "type": "句子", "keyWords": ["happen"] },
    { "chinese": "n.(pl)意外发生的事", "english": "happenings", "type": "单词", "keyWords": ["happen"] },
    { "chinese": "a.愉快的；满意的；乐意的", "english": "happy", "type": "单词", "keyWords": [] },
    { "chinese": "ad.愉快地；幸福地", "english": "happily", "type": "单词", "keyWords": ["happy"] },
    { "chinese": "n.[U]快乐；幸福", "english": "happiness", "type": "单词", "keyWords": ["happy"] },
    { "chinese": "n.[C]海港，港口；港湾", "english": "harbor", "type": "单词", "keyWords": [] },
    { "chinese": "a.困难的；艰难的；猛烈的；坚硬的 ad.困难地；艰难地；猛烈地；努力地", "english": "hard", "type": "单词", "keyWords": [] },
    { "chinese": "待人苛刻，对某人要求过严", "english": "be hard on sb.", "type": "短语", "keyWords": ["hard"] },
    { "chinese": "刻苦工作", "english": "be hard at work", "type": "短语", "keyWords": ["hard"] },
    { "chinese": "和她很难相处", "english": "She is hard to get along with. (用主动表示被动)", "type": "句子", "keyWords": ["hard"] },
    { "chinese": "众口难调", "english": "It is hard to please all.", "type": "句子", "keyWords": ["hard"] },
    { "chinese": "v.（使）变硬/牢固", "english": "harden", "type": "单词", "keyWords": ["hard"] },
    { "chinese": "ad.几乎不", "english": "hardly", "type": "单词", "keyWords": ["hard"] },
    { "chinese": "几乎没有什么人", "english": "hardly anybody =almost nobody", "type": "短语", "keyWords": ["hardly"] },
    { "chinese": "我星期天不太出去", "english": "I hardly ever (= almost never) go out on Sunday.", "type": "句子", "keyWords": ["hardly"] },
    { "chinese": "才...就...", "english": "hardly .. when .. = no sooner ... than ...", "type": "短语", "keyWords": ["hardly"] },
    { "chinese": "他才开口就被听众打断了", "english": "Hardly had he begun to speak when the audience interrupted him.", "type": "句子", "keyWords": ["hardly"] },
    { "chinese": "n.[C][U]艰难，困苦", "english": "hardship", "type": "单词", "keyWords": ["hard"] },
    { "chinese": "a.努力工作的，勤勉的", "english": "hardworking", "type": "单词", "keyWords": ["hard"] },
    { "chinese": "v./n.[U]伤害；损害；危害", "english": "harm", "type": "单词", "keyWords": [] },
    { "chinese": "对...有害/有益", "english": "do harm/ damage/ good to sb./ sth. →do sb./ sth. harm/ damage/ good", "type": "短语", "keyWords": ["harm"] },
    { "chinese": "弊多利少", "english": "do more harm than good", "type": "短语", "keyWords": ["harm"] },
    { "chinese": "a.有害的", "english": "harmful", "type": "单词", "keyWords": ["harm"] },
    { "chinese": "对...有害", "english": "be harmful to", "type": "短语", "keyWords": ["harmful"] },
    { "chinese": "a.无害的", "english": "harmless", "type": "单词", "keyWords": ["harm"] },
    { "chinese": "n.[U]协调，和谐；和睦，融洽；友好", "english": "harmony", "type": "单词", "keyWords": [] },
    { "chinese": "a.和谐的，协调的；和睦的；悦耳的", "english": "harmonious", "type": "单词", "keyWords": ["harmony"] },
    { "chinese": "n.[C]/v.收割，收获", "english": "harvest", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]匆忙；仓促；轻率", "english": "haste", "type": "单词", "keyWords": [] },
    { "chinese": "欲速则不达", "english": "More haste, less speed.", "type": "句子", "keyWords": ["haste"] },
    { "chinese": "a.匆忙的，草率的", "english": "hasty", "type": "单词", "keyWords": ["haste"] },
    { "chinese": "n.[C]帽子", "english": "hat", "type": "单词", "keyWords": [] },
    { "chinese": "vt/vi.孵化", "english": "hatch", "type": "单词", "keyWords": [] },
    { "chinese": "孵化鸡蛋", "english": "hatch eggs", "type": "短语", "keyWords": ["hatch"] },
    { "chinese": "孵出小鸡", "english": "hatch chickens", "type": "短语", "keyWords": ["hatch"] },
    { "chinese": "v.憎恨；对..感到遗憾；不喜欢", "english": "hate", "type": "单词", "keyWords": [] },
    { "chinese": "不喜欢做某事", "english": "hate doing/ to do sth.", "type": "短语", "keyWords": ["hate"] },
    { "chinese": "n.[U]仇恨；敌意", "english": "hatred", "type": "单词", "keyWords": ["hate"] },
    { "chinese": "他对...的恨", "english": "his hatred for/ of...", "type": "短语", "keyWords": ["hatred"] },
    { "chinese": "vt.有；使，让，叫；允许，容忍（常用于否定结构）", "english": "have", "type": "单词", "keyWords": [] },
    { "chinese": "与...有关", "english": "have something to do with", "type": "短语", "keyWords": ["have"] },
    { "chinese": "让某人做某事；有某种遭遇", "english": "have sth.done", "type": "短语", "keyWords": ["have"] },
    { "chinese": "让某人做某事", "english": "have sb. do sth. (get sb.to do sth.)", "type": "短语", "keyWords": ["have"] },
    { "chinese": "使...（一直）处在某状态；允许，容忍（常用于否定结构）", "english": "have sth./sb.doing", "type": "短语", "keyWords": ["have"] },
    { "chinese": "我让车在外面等着", "english": "I had the car waiting outside.", "type": "句子", "keyWords": ["have"] },
    { "chinese": "我们不能允许你那样戏弄他们", "english": "We can't have you teasing them that way.", "type": "句子", "keyWords": ["have"] },
    { "chinese": "当时没有人帮他们", "english": "They had nobody helping them at that time.", "type": "句子", "keyWords": ["have"] },
    { "chinese": "今天没有事/没有安排；今天穿（...）衣服", "english": "have(nothing...) on today", "type": "短语", "keyWords": ["have"] },
    { "chinese": "我明天晚上没有安排", "english": "I have nothing on tomorrow evening.", "type": "句子", "keyWords": ["have"] },
    { "chinese": "在某方面有困难", "english": "have difficulty/ trouble/ a hard time with sth./ (in) doing sth.", "type": "短语", "keyWords": ["have"] },
    { "chinese": "n.[C]头部；头领；(pl)牛/羊的头数 v.在...部；为...的首脑；率领（代表团等）；使（车/船等）朝某方向前进", "english": "head", "type": "单词", "keyWords": [] },
    { "chinese": "从头到脚", "english": "from head to foot", "type": "短语", "keyWords": ["head"] },
    { "chinese": "他名列第一", "english": "His name headed the list.", "type": "句子", "keyWords": ["head"] },
    { "chinese": "前往某地", "english": "be headed for ...=head for...", "type": "短语", "keyWords": ["head"] },
    { "chinese": "看完戏我们全都去了酒吧", "english": "After the play we all headed for the bar.", "type": "句子", "keyWords": ["head"] },
    { "chinese": "向北前进", "english": "head (the ship) north", "type": "短语", "keyWords": ["head"] },
    { "chinese": "20头牛/20匹马", "english": "20 head of cattle/ horses", "type": "短语", "keyWords": ["head"] },
    { "chinese": "n.[C]头痛；头痛的事，麻烦事", "english": "headache", "type": "单词", "keyWords": ["head"] },
    { "chinese": "n.[C]大字标题；(pl)头版头条新闻；新闻广播内容提要", "english": "headline", "type": "单词", "keyWords": ["head"] },
    { "chinese": "n.[C]标题；信纸上端所印文字；信头", "english": "heading", "type": "单词", "keyWords": ["head"] },
    { "chinese": "n.[C]（中学或小学的）男校长", "english": "headmaster", "type": "单词", "keyWords": ["head"] },
    { "chinese": "n.[C]耳机", "english": "headphone", "type": "单词", "keyWords": ["head"] },
    { "chinese": "n.(pl)（后接单数或复数动词）（企业）总部；（军、警的）指挥部，司令部", "english": "headquarters", "type": "单词", "keyWords": ["head"] },
    { "chinese": "vt/vi.治愈，(使)痊愈", "english": "heal", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]健康；保健", "english": "health", "type": "单词", "keyWords": [] },
    { "chinese": "为某人的健康干杯", "english": "drink to sb's health", "type": "短语", "keyWords": ["health"] },
    { "chinese": "身心健康", "english": "physical and mental health", "type": "短语", "keyWords": ["health"] },
    { "chinese": "身体状况良好/差", "english": "in good/ poor health", "type": "短语", "keyWords": ["health"] },
    { "chinese": "保健", "english": "health care", "type": "短语", "keyWords": ["health"] },
    { "chinese": "a.（不）健康的；（不）健壮的", "english": "(un)healthy", "type": "单词", "keyWords": ["health"] },
    { "chinese": "n.[U]健康", "english": "healthiness", "type": "单词", "keyWords": ["health"] },
    { "chinese": "n.[C]一堆；大量 v.堆起，使堆成 vi.积成堆", "english": "heap", "type": "单词", "keyWords": [] },
    { "chinese": "把落叶堆起来", "english": "heap (up) fallen leaves", "type": "短语", "keyWords": ["heap"] },
    { "chinese": "一堆/很多", "english": "a heap of/heaps of (近piles of)", "type": "短语", "keyWords": ["heap"] },
    { "chinese": "v.听说，得知；听见", "english": "hear", "type": "单词", "keyWords": [] },
    { "chinese": "听见...做...", "english": "hear sb.doing/ do sth.", "type": "短语", "keyWords": ["hear"] },
    { "chinese": "听说；知道，了解", "english": "hear of/about sth. (近hear that...)", "type": "短语", "keyWords": ["hear"] },
    { "chinese": "n.[U]听力，听觉；听（指动作或过程）", "english": "hearing", "type": "单词", "keyWords": ["hear"] }
];
