const qgl153_160 = [
    { chinese: "n.（坐下时）大腿前部，膝盖；（跑道）一圈", english: "lap", type: "单词", keyWords: [] },
    { chinese: "n.便携式电脑；膝上型电脑", english: "laptop", type: "单词", keyWords: [] },
    { chinese: "a.大的", english: "large", type: "单词", keyWords: [] },
    { chinese: "ad.主要地，大量地，很大程度上", english: "largely", type: "单词", keyWords: [] },
    { chinese: "未受控制的；（危险人物或野兽）自由自在到处跑；详细地（in detail）", english: "at large", type: "短语", keyWords: ["large"] },
    { chinese: "n.激光", english: "laser", type: "单词", keyWords: [] },
    { chinese: "a.最近的，刚刚过去的；最后的；最不可能的；ad.最后；n.（the）最后一个", english: "last", type: "单词", keyWords: [] },
    { chinese: "导致失败之最后一击；致命的打击；灭顶之灾", english: "the last straw", type: "短语", keyWords: ["last"] },
    { chinese: "最后但并非最不重要的（一点）是", english: "last but not least", type: "短语", keyWords: ["last"] },
    { chinese: "终于，最后（指经过长时间艰辛的等待或耽搁终于达到理想的目的）", english: "at (long) last", type: "短语", keyWords: ["last"] },
    { chinese: "vi.持续", english: "last", type: "单词", keyWords: [] },
    { chinese: "a.持久的，永久的，永恒的", english: "lasting/everlasting", type: "单词", keyWords: [] },
    { chinese: "永久价值", english: "lasting value", type: "短语", keyWords: ["lasting"] },
    { chinese: "持久的和平", english: "lasting peace", type: "短语", keyWords: ["lasting"] },
    { chinese: "这种布很耐穿。", english: "This cloth lasts well.", type: "句子", keyWords: ["last"] },
    { chinese: "a.迟的，晚的；已故的；ad.晚，迟；最近", english: "late", type: "单词", keyWords: [] },
    { chinese: "n.迟，晚", english: "lateness", type: "单词", keyWords: [] },
    { chinese: "没准时赶上", english: "be late for", type: "短语", keyWords: ["late"] },
    { chinese: "开会迟到", english: "be late for a meeting", type: "短语", keyWords: ["late"] },
    { chinese: "迟做某事", english: "be late with sth.", type: "短语", keyWords: ["late"] },
    { chinese: "晚做作业", english: "be late with one's homework", type: "短语", keyWords: ["late"] },
    { chinese: "我们必须趁早采取行动，否则来不及了。", english: "We must take action before it is too late.", type: "句子", keyWords: ["late"] },
    { chinese: "常常学习到深夜", english: "often study late/far into the night", type: "短语", keyWords: ["late"] },
    { chinese: "深夜不眠，熬夜", english: "sit up late/stay up late", type: "短语", keyWords: ["late"] },
    { chinese: "纪念已故的探险家", english: "in memory of the late explorer", type: "短语", keyWords: ["late"] },
    { chinese: "做总比不做好。迟来总比不来强。", english: "Better late than never.", type: "句子", keyWords: ["late"] },
    { chinese: "活到老，学到老。", english: "It is never too late to learn.", type: "句子", keyWords: ["late"] },
    { chinese: "ad.近来，最近（同recently，常和现在完成时连用）", english: "lately", type: "单词", keyWords: [] },
    { chinese: "ad.过后，稍后（常用later on）；a.（late的比较级）更/较迟；更后", english: "later", type: "单词", keyWords: [] },
    { chinese: "a.最近的，最新的", english: "latest", type: "单词", keyWords: [] },
    { chinese: "最新时尚", english: "the latest fashion", type: "短语", keyWords: ["latest"] },
    { chinese: "n.纬度", english: "latitude", type: "单词", keyWords: [] },
    { chinese: "a.后面的；后一半的；末了的；（两者中）后者的（the latter与the former相对）", english: "latter", type: "单词", keyWords: [] },
    { chinese: "v.（大）笑；v.以笑表示；使笑得；n.（C）笑（声）", english: "laugh", type: "单词", keyWords: [] },
    { chinese: "a.带笑的，可笑的", english: "laughing", type: "单词", keyWords: [] },
    { chinese: "嘲笑；讥笑；对……一笑了之", english: "laugh at", type: "短语", keyWords: ["laugh"] },
    { chinese: "放声大笑；尽情地笑", english: "have a good laugh", type: "短语", keyWords: ["laugh"] },
    { chinese: "这可不是什么闹着玩的事。", english: "This is no laughing matter.", type: "句子", keyWords: ["laugh"] },
    { chinese: "笑到最后的人笑得最好。", english: "He laughs best who laughs last.", type: "句子", keyWords: ["laugh"] },
    { chinese: "n.（U）笑（声）", english: "laughter", type: "单词", keyWords: [] },
    { chinese: "听到远处的笑声", english: "hear laughter in the distance", type: "短语", keyWords: ["laughter"] },
    { chinese: "突然大笑起来", english: "burst into laughter", type: "短语", keyWords: ["laughter"] },
    { chinese: "（船）下水；掷（标枪）；发射（导弹、火箭等），投；开办；发动；使开始从事；n.（C）发射；（船）下水", english: "launch", type: "单词", keyWords: [] },
    { chinese: "发射人造卫星", english: "launch an artificial satellite", type: "短语", keyWords: ["launch"] },
    { chinese: "创办一个新企业", english: "launch a new enterprise", type: "短语", keyWords: ["launch"] },
    { chinese: "使船下水", english: "launch a ship", type: "短语", keyWords: ["launch"] },
    { chinese: "开始攻击", english: "launch an attack", type: "短语", keyWords: ["launch"] },
    { chinese: "n.洗衣店，洗衣房", english: "laundry", type: "单词", keyWords: [] },
    { chinese: "n.厕所；盥洗室", english: "lavatory", type: "单词", keyWords: [] },
    { chinese: "n.法规；定律；n.（U）（总称，与the连用）法律；n.（U）法学；法治", english: "law", type: "单词", keyWords: [] },
    { chinese: "犯法", english: "break the law", type: "短语", keyWords: ["law"] },
    { chinese: "按法律规定", english: "by law", type: "短语", keyWords: ["law"] },
    { chinese: "供需法则", english: "the law of supply and demand", type: "短语", keyWords: ["law"] },
    { chinese: "法律与秩序；法治", english: "law and order", type: "短语", keyWords: ["law"] },
    { chinese: "自然规律；自然法则", english: "the law of nature", type: "短语", keyWords: ["law"] },
    { chinese: "维护社会治安", english: "keep/maintain law and order", type: "短语", keyWords: ["law"] },
    { chinese: "法律面前，人人平等。", english: "All citizens are equal before the law.", type: "句子", keyWords: ["law"] },
    { chinese: "刑法", english: "criminal law", type: "短语", keyWords: ["law"] },
    { chinese: "违法", english: "be against the law", type: "短语", keyWords: ["law"] },
    { chinese: "n.犯法者", english: "lawbreaker", type: "单词", keyWords: [] },
    { chinese: "n.立法者", english: "lawmaker", type: "单词", keyWords: [] },
    { chinese: "建立法治", english: "establish law and order", type: "短语", keyWords: ["law"] },
    { chinese: "n.律师", english: "lawyer", type: "单词", keyWords: [] },
    { chinese: "n.草坪", english: "lawn", type: "单词", keyWords: [] },
    { chinese: "n.割草机", english: "lawnmower", type: "单词", keyWords: [] },
    { chinese: "放置；放下；（架）设；产（卵）；lie的过去式", english: "lay", type: "单词", keyWords: [] },
    { chinese: "砌砖；铺设石油管道；设陷阱；下蛋", english: "lay bricks / lay oil pipes / lay traps / lay eggs", type: "短语", keyWords: ["lay"] },
    { chinese: "强调", english: "lay emphasis on sth.", type: "短语", keyWords: ["lay"] },
    { chinese: "摆饭桌预备开席", english: "lay the table", type: "短语", keyWords: ["lay"] },
    { chinese: "搞到", english: "lay one's hands on sth. = get sth.", type: "短语", keyWords: ["lay"] },
    { chinese: "为国牺牲", english: "lay down one's life for one's country", type: "短语", keyWords: ["lay"] },
    { chinese: "缴械投降", english: "lay down their arms", type: "短语", keyWords: ["lay"] },
    { chinese: "搁置；为将来贮存（钱物）", english: "lay aside", type: "短语", keyWords: ["lay"] },
    { chinese: "解雇（员工）", english: "lay...off", type: "短语", keyWords: ["lay"] },
    { chinese: "n.层", english: "layer", type: "单词", keyWords: [] },
    { chinese: "一层灰尘", english: "a layer of dust", type: "短语", keyWords: ["layer"] },
    { chinese: "a.懒惰的，懒散的", english: "lazy", type: "单词", keyWords: [] },
    { chinese: "v.领（路）；为……指路；致使；领导；通向；导致；n.（C）领导；领先", english: "lead", type: "单词", keyWords: [] },
    { chinese: "引路", english: "lead the way", type: "短语", keyWords: ["lead"] },
    { chinese: "主持讨论", english: "lead a discussion", type: "短语", keyWords: ["lead"] },
    { chinese: "带头，领导", english: "take the lead", type: "短语", keyWords: ["lead"] },
    { chinese: "这条小径把他们带向了一个山村。", english: "The path led them to a mountain village.", type: "句子", keyWords: ["lead"] },
    { chinese: "诱使某人做某事（近cause sb. to do sth.）", english: "lead sb. to do sth.", type: "短语", keyWords: ["lead"] },
    { chinese: "通向；导致", english: "lead to", type: "短语", keyWords: ["lead"] },
    { chinese: "通向厨房的门", english: "a door leading to the kitchen", type: "短语", keyWords: ["lead"] },
    { chinese: "这将导致以后的麻烦。", english: "This will lead to trouble in the future.", type: "句子", keyWords: ["lead"] },
    { chinese: "完全控制某人；使某人完全听命于自己；牵着某人鼻子走", english: "lead sb. by the nose", type: "短语", keyWords: ["lead"] },
    { chinese: "条条道路通罗马。", english: "All roads lead to Rome.", type: "句子", keyWords: ["lead"] },
    { chinese: "n.铅", english: "lead", type: "单词", keyWords: [] },
    { chinese: "n.领导；领导人；领袖；向导", english: "leader", type: "单词", keyWords: [] },
    { chinese: "a.处于领导地位的；主要的", english: "leading", type: "单词", keyWords: [] },
    { chinese: "导致高通货膨胀率的主要原因", english: "the leading cause of the high inflation", type: "短语", keyWords: ["leading"] },
    { chinese: "n.（U）领导", english: "leadership", type: "单词", keyWords: [] },
    { chinese: "在……领导下", english: "under the leadership of...", type: "短语", keyWords: ["leadership"] },
    { chinese: "n.叶；n.（U）（金属）箔；薄金属片；v.翻（书页）", english: "leaf", type: "单词", keyWords: [] },
    { chinese: "翻开崭新的一页；悔过自新", english: "turn over a new leaf", type: "短语", keyWords: ["leaf"] },
    { chinese: "一些银箔", english: "some silver leaf", type: "短语", keyWords: ["leaf"] },
    { chinese: "n.传单；单页印刷品；小册子", english: "leaflet", type: "单词", keyWords: [] },
    { chinese: "浏览目录", english: "leaf through the catalog", type: "短语", keyWords: ["leaf"] },
    { chinese: "n.联盟；协会，社团", english: "league", type: "单词", keyWords: [] },
    { chinese: "美国橄榄球联盟", english: "American Football League", type: "短语", keyWords: ["league"] },
    { chinese: "团组织", english: "the Youth League organization", type: "短语", keyWords: ["league"] },
    { chinese: "入团", english: "join the League", type: "短语", keyWords: ["league"] },
    { chinese: "v.泄露；v.使泄露；使漏；n.（C）裂缝；漏洞", english: "leak", type: "单词", keyWords: [] },
    { chinese: "顶上的裂缝", english: "a leak in the roof", type: "短语", keyWords: ["leak"] },
    { chinese: "v.使倾斜；vi.倚；靠；依赖；倾斜；倾向，偏向；n.（U）倾斜；倾斜度；瘦肉；a.瘦的", english: "lean", type: "单词", keyWords: [] },
    { chinese: "瘦肉", english: "lean meat", type: "短语", keyWords: ["lean"] },
    { chinese: "俯身向前", english: "lean forward", type: "短语", keyWords: ["lean"] },
    { chinese: "比萨斜塔", english: "the Leaning Tower of Pisa", type: "短语", keyWords: ["lean"] },
    { chinese: "把自行车斜靠墙", english: "lean the bike against the wall", type: "短语", keyWords: ["lean"] },
    { chinese: "依靠某人做某事", english: "lean on / depend on / rely on / count on / calculate on sb. to do sth.", type: "短语", keyWords: ["lean"] },
    { chinese: "v.跳，跃；跳过；跃过；使跳；n.（C）跳，跃", english: "leap", type: "单词", keyWords: [] },
    { chinese: "价格的暴涨", english: "a leap in prices", type: "短语", keyWords: ["leap"] },
    { chinese: "三思而后行。", english: "Look before you leap.", type: "句子", keyWords: ["leap"] },
    { chinese: "v.学习；得知；获悉", english: "learn", type: "单词", keyWords: [] },
    { chinese: "获悉；得知；听说；了解", english: "learn about/of", type: "短语", keyWords: ["learn"] },
    { chinese: "从错误中吸取教训/学雷锋", english: "learn from one's mistake/Lei Feng", type: "短语", keyWords: ["learn"] },
    { chinese: "（从错误中）得到教训（以后不会再做）", english: "learn your lesson", type: "短语", keyWords: ["learn"] },
    { chinese: "记住，记忆", english: "learn... by heart / keep... in mind / bear... in mind / memorize", type: "短语", keyWords: ["learn"] },
    { chinese: "学无止境。", english: "Live and learn.", type: "句子", keyWords: ["learn"] },
    { chinese: "a.有学问的；博学的；精通的", english: "learned", type: "单词", keyWords: [] },
    { chinese: "n.学习者；初学者", english: "learner", type: "单词", keyWords: [] },
    { chinese: "n.（U）学习；学问，学识", english: "learning", type: "单词", keyWords: [] },
    { chinese: "一知半解是危险的。", english: "A little learning/knowledge is a dangerous thing.", type: "句子", keyWords: ["learning"] },
    {"chinese": "a.（little 最高级）最小（的）；最少（的）；ad. 最少；n.（U）最少量；最小", "english": "least", "type": "单词", "keyWords": [] },
    { "chinese": "一点也不", "english": "not in the least /not the slightest = not a bit = not at all", "type": "短语", "keyWords": ["least"] },
    { "chinese": "至少；最低限度", "english": "at least", "type": "短语", "keyWords": ["least"] },
    { "chinese": "n. 皮革", "english": "leather", "type": "单词", "keyWords": [] },
    { "chinese": "v.离开；把…留下；放弃；听任；n.(U)准假；假期", "english": "leave", "type": "单词", "keyWords": [] },
    { "chinese": "前往；向…出发", "english": "leave for a place", "type": "短语", "keyWords": ["leave"] },
    { "chinese": "忘了带；遗留", "english": "leave...behind", "type": "短语", "keyWords": ["leave"] },
    { "chinese": "让…独自待着；不去动它", "english": "leave...alone", "type": "短语", "keyWords": ["leave"] },
    { "chinese": "省略；遗漏；忽视", "english": "leave...out", "type": "短语", "keyWords": ["leave"] },
    { "chinese": "(死后)把…留给某人；让某人决定/选择/处理", "english": "leave sth. to sb.", "type": "短语", "keyWords": ["leave"] },
    { "chinese": "使…处于某种状态；听任", "english": "leave sb. doing", "type": "短语", "keyWords": ["leave"] },
    { "chinese": "别让小男孩一直等在拐角处。", "english": "Don't leave the boy waiting at the corner.", "type": "句子", "keyWords": ["leave"] },
    { "chinese": "请假", "english": "ask (sb.) for leave", "type": "短语", "keyWords": ["leave"] },
    { "chinese": "向我请一天假", "english": "ask me for a day's leave", "type": "短语", "keyWords": ["leave"] },
    { "chinese": "余下的钱（left常作后置定语，remaining常作前置定语）", "english": "the money left (= the remaining money)", "type": "短语", "keyWords": ["leave"] },
    { "chinese": "n.(C)讲座；讲演；vi.讲演(on/about)", "english": "lecture", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)演讲者；讲师", "english": "lecturer", "type": "单词", "keyWords": [] },
    { "chinese": "听讲座/讲演", "english": "go to/attend/receive a lecture", "type": "短语", "keyWords": ["lecture"] },
    { "chinese": "讲…；作关于…的讲演", "english": "give (sb.)/deliver a lecture on sth. = lecture on sth.", "type": "短语", "keyWords": ["lecture"] },
    { "chinese": "a.左边的；留下的；左派的，左翼的；n.(U)左边，左面；ad.在左边；向左", "english": "left", "type": "单词", "keyWords": [] },
    { "chinese": "向左转", "english": "turn left = turn to the left", "type": "短语", "keyWords": ["left"] },
    { "chinese": "在某人左面", "english": "on one's left", "type": "短语", "keyWords": ["left"] },
    { "chinese": "左边第三个门", "english": "the third door to the left", "type": "短语", "keyWords": ["left"] },
    { "chinese": "在左面", "english": "on the left", "type": "短语", "keyWords": ["left"] },
    { "chinese": "a.(用)左手的", "english": "left-handed", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)左利手，左手优势", "english": "left-handedness", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)左撇子", "english": "left-hander", "type": "单词", "keyWords": [] },
    { "chinese": "a.(只在名词前)左手的；左边的", "english": "left-hand", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)腿；腿部；一段行程/航程/赛程", "english": "leg", "type": "单词", "keyWords": [] },
    { "chinese": "足马力，拼命跑", "english": "run as fast as one's legs can carry one", "type": "短语", "keyWords": ["leg"] },
    { "chinese": "(久坐后)走动走动，散散步", "english": "stretch one's legs", "type": "短语", "keyWords": ["leg"] },
    { "chinese": "a.法律上的；合法的", "english": "legal", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)传说；传奇人物", "english": "legend", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)空闲，闲暇；悠闲，安逸；a.空闲的，闲暇的", "english": "leisure", "type": "单词", "keyWords": [] },
    { "chinese": "空闲时间", "english": "leisure time", "type": "短语", "keyWords": ["leisure"] },
    { "chinese": "有空，闲着无事(类似at work, at play)", "english": "at leisure", "type": "短语", "keyWords": ["leisure"] },
    { "chinese": "当某人空闲的时候；方便时(类似at birth, at that time)", "english": "at one's leisure", "type": "短语", "keyWords": ["leisure"] },
    { "chinese": "有空我就会来拜访。", "english": "I'll call on you at my leisure.", "type": "句子", "keyWords": ["leisure"] },
    { "chinese": "n.(C/U)柠檬；n.(U)柠檬汁；柠檬色", "english": "lemon", "type": "单词", "keyWords": [] },
    { "chinese": "v.把…借给；出借", "english": "lend", "type": "单词", "keyWords": [] },
    { "chinese": "帮忙；伸出援助之手", "english": "lend sb. a hand (with sth.)", "type": "短语", "keyWords": ["lend"] },
    { "chinese": "n.(U)长；长度；n.(C)一段，一段标准长度，一节；一段时间", "english": "length", "type": "单词", "keyWords": [] },
    { "chinese": "v.延长；(使)变长", "english": "lengthen", "type": "单词", "keyWords": [] },
    { "chinese": "竭尽全力做某事；不遗余力做某事", "english": "go to all/great lengths to do sth. = do sth. at all costs", "type": "短语", "keyWords": ["length"] },
    { "chinese": "一根二十米长的管子", "english": "a pipe 20 metres in length", "type": "短语", "keyWords": ["length"] },
    { "chinese": "一节(管子)；一段(时间)", "english": "a length of (pipe/time)", "type": "短语", "keyWords": ["length"] },
    { "chinese": "这条河长100千米。", "english": "This river has a length of 100 kilometers.", "type": "句子", "keyWords": ["length"] },
    { "chinese": "一段相当长的时间之后", "english": "after a considerable length of time", "type": "短语", "keyWords": ["length"] },
    { "chinese": "结局，最后(近at last)；详细，充分(in detail)", "english": "at length", "type": "短语", "keyWords": ["length"] },
    { "chinese": "避免与某人亲近，对某人敬而远之", "english": "keep sb. at arm's length", "type": "短语", "keyWords": ["length"] },
    { "chinese": "n.(C)豹，美洲豹", "english": "leopard", "type": "单词", "keyWords": [] },
    { "chinese": "less构成形容词，表示“不，无”，-lessness构成名词，如：helpless, helplessness", "english": "less", "type": "单词", "keyWords": [] },
    { "chinese": "a.(little比较级)少的；小的；ad.较少地；小地；n.(U)较小数；较少量", "english": "less", "type": "单词", "keyWords": [] },
    { "chinese": "不少于", "english": "no less than", "type": "短语", "keyWords": ["less"] },
    { "chinese": "近来见到他的机会少", "english": "see less of him recently", "type": "短语", "keyWords": ["less"] },
    { "chinese": "n.(C)课，(一节)课；功课；教训", "english": "lesson", "type": "单词", "keyWords": [] },
    { "chinese": "给某人一个教训", "english": "teach sb. a lesson", "type": "短语", "keyWords": ["lesson"] },
    { "chinese": "对…是一个教训", "english": "be a lesson to sb.", "type": "短语", "keyWords": ["lesson"] },
    { "chinese": "v.让；允许；出租", "english": "let", "type": "单词", "keyWords": [] },
    { "chinese": "泄露秘密/发出叫声/出租他的汽车", "english": "let out a secret / let out a cry / let out his car", "type": "短语", "keyWords": ["let"] },
    { "chinese": "此屋出租。", "english": "The house is to be let.", "type": "句子", "keyWords": ["let"] },
    { "chinese": "更不用说，更谈不上", "english": "let alone", "type": "短语", "keyWords": ["let"] },
    { "chinese": "我不会说意大利语，更别说写了。", "english": "I cannot speak Italian, let alone write it.", "type": "句子", "keyWords": ["let"] },
    { "chinese": "我们抽不出时间，更别说费用了。", "english": "We cannot afford the time, let alone the expense.", "type": "句子", "keyWords": ["let"] },
    { "chinese": "放任不管；不碰；使…保持原状", "english": "let/leave sb. alone (= let sb. be)", "type": "短语", "keyWords": ["let"] },
    { "chinese": "使某人失望", "english": "let...down (= disappoint sb.)", "type": "短语", "keyWords": ["let"] },
    { "chinese": "松手；放开绳子/把手", "english": "let go (of) the rope / the handle", "type": "短语", "keyWords": ["let"] },
    { "chinese": "n.(C)信；字母", "english": "letter", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)水平线/面；平面，平地；水平，水准；水位；等级；含量；a.平的；v.(使)成水平；(使)平坦，(使)变平", "english": "level", "type": "单词", "keyWords": [] },
    { "chinese": "海拔4000米", "english": "4,000 metres above sea level", "type": "短语", "keyWords": ["level"] },
    { "chinese": "最高级会谈", "english": "top-level talks", "type": "短语", "keyWords": ["level"] },
    { "chinese": "眼睛/肩那么高", "english": "at eye/shoulder level", "type": "短语", "keyWords": ["level"] },
    { "chinese": "平地", "english": "level ground", "type": "短语", "keyWords": ["level"] },
    { "chinese": "在一般水准以上/下", "english": "above/below the general level", "type": "短语", "keyWords": ["level"] },
    { "chinese": "先进的技术水平", "english": "advanced technical level", "type": "短语", "keyWords": ["level"] },
    { "chinese": "用压路机把路面压平", "english": "level the driveway with a roller", "type": "短语", "keyWords": ["level"] },
    { "chinese": "n.(C)说谎者", "english": "liar", "type": "单词", "keyWords": [] },
    { "chinese": "v.解放；使获得自由；[化]释放", "english": "liberate", "type": "单词", "keyWords": [] },
    { "chinese": "a.被解放了的", "english": "liberated", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)释放，解放", "english": "liberation", "type": "单词", "keyWords": [] },
    { "chinese": "解放区", "english": "the liberated area", "type": "短语", "keyWords": ["liberation"] },
    { "chinese": "中国人民解放军(the PLA)", "english": "the Chinese People's Liberation Army (the PLA)", "type": "短语", "keyWords": ["liberation"] },
    { "chinese": "n.(U)(言论、行动等的)自由", "english": "liberty", "type": "单词", "keyWords": [] },
    { "chinese": "选择的自由/言论自由", "english": "liberty of choice/speech", "type": "短语", "keyWords": ["liberty"] },
    { "chinese": "n.(C)图书管理员", "english": "librarian", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)图书馆；书房", "english": "library", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)执照，许可证；n.(U)许可，特许；v.给予许可(证)", "english": "license/licence", "type": "单词", "keyWords": [] },
    { "chinese": "驾驶执照", "english": "a driver's license", "type": "短语", "keyWords": ["license"] },
    { "chinese": "申请驾驶执照", "english": "apply for a driving license", "type": "短语", "keyWords": ["license"] },
    { "chinese": "n.(C)盖子；眼皮，眼睑(=eyelid)", "english": "lid", "type": "单词", "keyWords": [] },
    { "chinese": "揭开盖子", "english": "take the lid off", "type": "短语", "keyWords": ["lid"] },
    { "chinese": "n.(C)谎话；vi.(lay, lain, lying)平放；位于；在于；vi.(lied, lied)说谎", "english": "lie", "type": "单词", "keyWords": [] },
    { "chinese": "躺着未睡", "english": "lie awake", "type": "短语", "keyWords": ["lie"] },
    { "chinese": "侧卧", "english": "lie on one's side", "type": "短语", "keyWords": ["lie"] },
    { "chinese": "就某事向某人撒谎", "english": "lie to sb. about sth.", "type": "短语", "keyWords": ["lie"] },
    { "chinese": "躺着不动", "english": "lie still", "type": "短语", "keyWords": ["lie"] },
    { "chinese": "仰卧", "english": "lie on one's back", "type": "短语", "keyWords": ["lie"] },
    { "chinese": "说你天大谎", "english": "tell lies / tell a lie", "type": "短语", "keyWords": ["lie"] },
    { "chinese": "那本书摊开在桌上。", "english": "The book lies open on the table.", "type": "句子", "keyWords": ["lie"] },
    { "chinese": "别把你的书四处乱扔。", "english": "Don't leave your books lying about.", "type": "句子", "keyWords": ["lie"] },
    { "chinese": "位于中国以东", "english": "lie (to the) east of China", "type": "短语", "keyWords": ["lie"] },
    { "chinese": "位于；(原因、本质等)在于", "english": "lie in", "type": "短语", "keyWords": ["lie"] },
    { "chinese": "答案在于研究。", "english": "The solution lies in research.", "type": "句子", "keyWords": ["lie"] },
    { "chinese": "n.（C）一生；使用期限；性命；n.（U）生活；生存；（总称）生物", "english": "life", "type": "单词", "keyWords": [] },
    { "chinese": "生活质量", "english": "quality of life", "type": "短语", "keyWords": ["life"] },
    { "chinese": "过着……生活", "english": "lead a...life", "type": "短语", "keyWords": ["life"] },
    { "chinese": "死了不少人。", "english": "Many lives were lost.", "type": "句子", "keyWords": ["life"] },
    { "chinese": "苏醒；恢复生机", "english": "come to life", "type": "短语", "keyWords": ["life"] },
    { "chinese": "人造卫星的寿命", "english": "the life of an artificial satellite", "type": "短语", "keyWords": ["life"] },
    { "chinese": "n.（C）生命周期", "english": "life cycle", "type": "单词", "keyWords": [] },
    { "chinese": "让某人搭车/要求搭车", "english": "give sb./ask for a lift", "type": "短语", "keyWords": ["lift"] },
    { "chinese": "抬头/抬起双眼", "english": "lift up one's head/eyes", "type": "短语", "keyWords": ["lift"] },
    { "chinese": "n.（C）电梯；免费搭车；v.提；举起；v.被提（或举）起", "english": "lift", "type": "单词", "keyWords": [] },
    { "chinese": "乘电梯", "english": "take the lift", "type": "短语", "keyWords": ["lift"] },
    { "chinese": "举重", "english": "lift weights", "type": "短语", "keyWords": ["lift"] },
    { "chinese": "（往上提起的）窗子打不开。", "english": "The window will not lift.", "type": "句子", "keyWords": ["lift"] },
    { "chinese": "n.（C）救生员", "english": "lifeguard", "type": "单词", "keyWords": [] },
    { "chinese": "留得青山在，不怕没柴烧。", "english": "While there is life there is hope.", "type": "句子", "keyWords": ["life"] },
    { "chinese": "n.（C）灯塔", "english": "lighthouse", "type": "单词", "keyWords": [] },
    { "chinese": "暴露，揭露", "english": "bring... to light", "type": "短语", "keyWords": ["light"] },
    { "chinese": "n.（U）光；光线；光亮；n.（C）灯；v.（lit, lit / lighted, lighted）点着；点燃；v.亮起来", "english": "light", "type": "单词", "keyWords": [] },
    { "chinese": "点着的火柴", "english": "a lighted match", "type": "短语", "keyWords": ["light"] },
    { "chinese": "显露，出现", "english": "come to light", "type": "短语", "keyWords": ["light"] },
    { "chinese": "（使）照亮；（使）容光焕发", "english": "light up", "type": "短语", "keyWords": ["light"] },
    { "chinese": "她脸上喜气洋洋。", "english": "Her face lit up (with happiness).", "type": "句子", "keyWords": ["light"] },
    { "chinese": "根据……；基于对……的考虑", "english": "in (the) light of", "type": "短语", "keyWords": ["light"] },
    { "chinese": "根据已变化了的情况来看，会议最好推迟。", "english": "In the light of the changed circumstances, the meeting had better be postponed.", "type": "句子", "keyWords": ["light"] },
    { "chinese": "（使）变亮；点亮；缓和；减少；（使）变轻", "english": "lighten", "type": "单词", "keyWords": [] },
    { "chinese": "a.闪电的；极快的；n.（U）闪电（注意后面没有e，是 -ning）", "english": "lightning", "type": "单词", "keyWords": [] },
    { "chinese": "prep.像，跟……一样；例如……等；n.（C）相似的人（物）；同样的人（物）", "english": "like", "type": "单词", "keyWords": [] },
    { "chinese": "看起来像", "english": "look like", "type": "短语", "keyWords": ["like"] },
    { "chinese": "……是什么样的人", "english": "What is sb. like?", "type": "句子", "keyWords": ["like"] },
    { "chinese": "想做某事", "english": "feel like doing sth.", "type": "短语", "keyWords": ["like"] },
    { "chinese": "希特勒之流", "english": "Hitler and his like", "type": "短语", "keyWords": ["like"] },
    { "chinese": "差不多100美元/有几分像演员", "english": "something like 100 dollars / something like an actor", "type": "短语", "keyWords": ["like"] },
    { "chinese": "v.喜欢；喜爱；（常与should, would连用）希望，想要；n.（pl.）嗜好", "english": "like", "type": "单词", "keyWords": [] },
    { "chinese": "想要某人去做某事（近intend sb. to do sth.）", "english": "would like sb. to do sth.", "type": "短语", "keyWords": ["like"] },
    { "chinese": "随你的便", "english": "as you like", "type": "短语", "keyWords": ["like"] },
    { "chinese": "你喜欢怎么做就怎么做。", "english": "Do as you like.", "type": "句子", "keyWords": ["like"] },
    { "chinese": "如果你愿意的话", "english": "if you like", "type": "短语", "keyWords": ["like"] },
    { "chinese": "高兴的话请过来。", "english": "You may come if you like.", "type": "句子", "keyWords": ["like"] },
    { "chinese": "认为……怎么样？", "english": "How do you like... = What do you think of...?", "type": "句子", "keyWords": ["like"] },
    { "chinese": "一个人的好恶/爱憎", "english": "one's likes and dislikes", "type": "短语", "keyWords": ["like"] },
    { "chinese": "a.很可能的；ad.很可能", "english": "likely", "type": "单词", "keyWords": [] },
    { "chinese": "很可能……", "english": "It is likely / quite possible that...", "type": "句子", "keyWords": ["likely"] },
    { "chinese": "某人有可能做某事", "english": "sb. is likely to do sth.", "type": "句子", "keyWords": ["likely"] },
    { "chinese": "说得倒像！煞有介事！", "english": "That's a likely story!", "type": "句子", "keyWords": ["likely"] },
    { "chinese": "n.（C）限制；限度（to）；v.限制；限定（to）", "english": "limit", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）（U）限制；局限性；限制因素", "english": "limitation", "type": "单词", "keyWords": [] },
    { "chinese": "对……加以限制", "english": "set a limit to (the cost...)", "type": "短语", "keyWords": ["limit"] },
    { "chinese": "有限度地；在一定范围内", "english": "within limits", "type": "短语", "keyWords": ["limit"] },
    { "chinese": "由于篇幅限制", "english": "owing to the limitation of space", "type": "短语", "keyWords": ["limitation"] },
    { "chinese": "凡事都有限度。", "english": "There is a limit to everything.", "type": "句子", "keyWords": ["limit"] },
    { "chinese": "a.有限的，有限制的", "english": "limited", "type": "单词", "keyWords": [] },
    { "chinese": "一家有限公司", "english": "a limited company", "type": "短语", "keyWords": ["limited"] },
    { "chinese": "n.（C）线；行；路线，铁路线；航线；（pl.）台词；v.使排成行；沿……排列；vi.排成行", "english": "line", "type": "单词", "keyWords": [] },
    { "chinese": "给某人写封短信", "english": "drop sb. a line", "type": "短语", "keyWords": ["line"] },
    { "chinese": "电话占线。", "english": "The line is engaged / busy.", "type": "句子", "keyWords": ["line"] },
    { "chinese": "读出言外之意", "english": "read between the lines", "type": "短语", "keyWords": ["line"] },
    { "chinese": "人们夹道欢迎。", "english": "People line the streets to welcome.", "type": "句子", "keyWords": ["line"] },
    { "chinese": "两旁种着树的路", "english": "a road (which is) lined with trees", "type": "短语", "keyWords": ["line"] },
    { "chinese": "成一排；成一直线；有秩序", "english": "in line", "type": "短语", "keyWords": ["line"] },
    { "chinese": "不要放电话", "english": "hold the line", "type": "短语", "keyWords": ["line"] },
    { "chinese": "排列成行；排队", "english": "line up", "type": "短语", "keyWords": ["line"] },
    { "chinese": "n.（C）联系；环节（to / with）；v.连接；联系（to / with）；vi.连接起来；联系在一起", "english": "link", "type": "单词", "keyWords": [] },
    { "chinese": "我们与过去的纽带", "english": "grandparents, our link with the past", "type": "短语", "keyWords": ["link"] },
    { "chinese": "n.（C）狮子", "english": "lion", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）嘴唇", "english": "lip", "type": "单词", "keyWords": [] },
    { "chinese": "上唇", "english": "the upper lip", "type": "短语", "keyWords": ["lip"] },
    { "chinese": "下唇", "english": "the lower lip", "type": "短语", "keyWords": ["lip"] },
    { "chinese": "n.（C）（U）液体；a.液体的，液态的", "english": "liquid", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）表；一览表；v.列出，列举；列入名单（筛）中，把……输入一览表", "english": "list", "type": "单词", "keyWords": [] },
    { "chinese": "购物清单", "english": "a shopping list", "type": "短语", "keyWords": ["list"] },
    { "chinese": "v.听；留神听", "english": "listen", "type": "单词", "keyWords": [] },
    { "chinese": "听……；听从……", "english": "listen to", "type": "短语", "keyWords": ["listen"] },
    { "chinese": "听着等待（……）", "english": "listen for (further sound, the postman, an answer)", "type": "短语", "keyWords": ["listen"] },
    { "chinese": "n.（U）文学（作品）；文献", "english": "literature", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）识字，有文化；读写能力；熟谙文学；善于写作", "english": "literacy", "type": "单词", "keyWords": [] },
    { "chinese": "a.有读写能力的；受过良好教育的；有文化的（反illiterate）", "english": "literate", "type": "单词", "keyWords": [] },
    { "chinese": "文化水准", "english": "the level of literacy", "type": "短语", "keyWords": ["literacy"] },
    { "chinese": "文化修养极高的父母", "english": "highly literate parents", "type": "短语", "keyWords": ["literate"] },
    { "chinese": "a.文学的，文学上的；书面语的；精通文学的", "english": "literary", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）（容量单位）升", "english": "litre / liter", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）废（弃）物；垃圾；杂乱无章；v.乱丢；弄乱（with sth.）；vi.乱丢废（弃）物", "english": "litter", "type": "单词", "keyWords": [] },
    { "chinese": "不准乱丢垃圾。", "english": "No littering.", "type": "句子", "keyWords": ["litter"] },
    { "chinese": "在沙滩上乱扔废纸", "english": "litter the beach with paper", "type": "短语", "keyWords": ["litter"] },
    { "chinese": "到处有废纸的沙滩", "english": "a beach littered with paper", "type": "短语", "keyWords": ["litter"] },
    { "chinese": "n.（C）废物箱", "english": "litterbin", "type": "单词", "keyWords": [] },
    { "chinese": "a.小的；少量的；少到几乎没有的；ad.很少；（用于know, think, care等之前）毫不；n.（U）很少（表否定）", "english": "little", "type": "单词", "keyWords": [] },
    { "chinese": "一点点 / 很少", "english": "a little / only a little", "type": "短语", "keyWords": ["little"] },
    { "chinese": "相当", "english": "not a little", "type": "短语", "keyWords": ["little"] },
    { "chinese": "现在很少见到他。", "english": "I see very little of him now.", "type": "句子", "keyWords": ["little"] },
    { "chinese": "根本没（想到）", "english": "Little did I think.", "type": "句子", "keyWords": ["little"] },
    { "chinese": "他们根本不知道我们在监视他们。", "english": "Little did they know that we were watching them. = They little knew that we were watching them.", "type": "句子", "keyWords": ["little"] },
    { "chinese": "我仅有的一点都给了你。", "english": "I've given you the little I've got / what little I've got.", "type": "句子", "keyWords": ["little"] },
    { "chinese": "这事花掉了我仅有的一点点空余时间。", "english": "This has taken what little there is of my spare time.", "type": "句子", "keyWords": ["little"] },
    { "chinese": "逐渐地；一点一点地", "english": "little by little", "type": "短语", "keyWords": ["little"] },
    { "chinese": "睡得很少", "english": "sleep very little", "type": "短语", "keyWords": ["little"] },
    { "chinese": "v.居住；过活；经历；留在人们记忆中；a.活生生的（不是假想的）；带电的；燃着的；直播的；生动的；热门的；ad.以实况转播地", "english": "live", "type": "单词", "keyWords": [] },
    { "chinese": "过着穷困潦倒的生活", "english": "live a dog's life", "type": "短语", "keyWords": ["live"] },
    { "chinese": "在一场恶性事故中活下来", "english": "live through a bad accident", "type": "短语", "keyWords": ["live"] },
    { "chinese": "(靠)……生活", "english": "live by doing", "type": "短语", "keyWords": ["live"] },
    { "chinese": "海岛上的居民靠打鱼为生。", "english": "The islanders live by fishing.", "type": "句子", "keyWords": ["live"] },
    { "chinese": "遵守；实践；符合；不辜负", "english": "live up to", "type": "短语", "keyWords": ["live"] },
    { "chinese": "他符合你的期望吗？", "english": "Did he live up to your expectations?", "type": "句子", "keyWords": ["live"] },
    { "chinese": "尚在争论中的问题", "english": "a live issue", "type": "短语", "keyWords": ["live"] },
    { "chinese": "电视现场直播的表演", "english": "a live television show", "type": "短语", "keyWords": ["live"] },
    { "chinese": "带电的电线", "english": "a live wire", "type": "短语", "keyWords": ["live"] },
    { "chinese": "比赛将有电视现场播出。", "english": "The race will be televised live.", "type": "句子", "keyWords": ["live"] },
    { "chinese": "a.充满活力的；灵敏的；栩栩如生的", "english": "lively", "type": "单词", "keyWords": [] },
    { "chinese": "生动的描述", "english": "a lively description", "type": "短语", "keyWords": ["lively"] },
    { "chinese": "a.（可作前置定语）活的；在世的；现存的；n.（只用单数）生活，生计", "english": "living", "type": "单词", "keyWords": [] },
    { "chinese": "仍在使用中的语言", "english": "a living language", "type": "短语", "keyWords": ["living"] },
    { "chinese": "n.肝脏", "english": "liver", "type": "单词", "keyWords": [] },
    { "chinese": "以稻米为生", "english": "live/feed on rice", "type": "短语", "keyWords": ["live"] },
    { "chinese": "活鱼", "english": "live fish", "type": "短语", "keyWords": ["live"] },
    { "chinese": "打猎为生", "english": "make their living by hunting", "type": "短语", "keyWords": ["living"] },
    { "chinese": "n.负荷；v.装；装载；v.装货；上客；装弹药", "english": "load", "type": "单词", "keyWords": [] },
    { "chinese": "一架照相机装有一整卷胶卷。", "english": "The camera has a full load of film.", "type": "句子", "keyWords": ["load"] },
    { "chinese": "这个好消息卸去了我心头的重担。", "english": "Good news took load of my mind.", "type": "句子", "keyWords": ["load"] },
    { "chinese": "一支装有子弹的枪", "english": "a loaded gun", "type": "短语", "keyWords": ["load"] },
    { "chinese": "把粮食装上火车", "english": "load grain onto a train", "type": "短语", "keyWords": ["load"] },
    { "chinese": "把煤装上船", "english": "load a ship with coal", "type": "短语", "keyWords": ["load"] },
    { "chinese": "装煤的轮船", "english": "a ship (which was) loaded with coal", "type": "短语", "keyWords": ["load"] },
    { "chinese": "n.（pl. loaves）（面包的）一条", "english": "loaf", "type": "单词", "keyWords": [] },
    { "chinese": "一条面包", "english": "a loaf of bread", "type": "短语", "keyWords": ["loaf"] },
    { "chinese": "n.贷款；v.借出；贷与", "english": "loan", "type": "单词", "keyWords": [] },
    { "chinese": "一笔银行贷款", "english": "a bank loan", "type": "短语", "keyWords": ["loan"] },
    { "chinese": "向储蓄银行贷款", "english": "ask for/obtain a loan from savings banks", "type": "短语", "keyWords": ["loan"] },
    { "chinese": "a.当地的；地方的；(pl.)当地居民", "english": "local", "type": "单词", "keyWords": [] },
    { "chinese": "地方政府", "english": "local government", "type": "短语", "keyWords": ["local"] },
    { "chinese": "地方当局", "english": "the local authorities", "type": "短语", "keyWords": ["local"] },
    { "chinese": "v.确定···的地点；使···落于", "english": "locate", "type": "单词", "keyWords": [] },
    { "chinese": "n.位置，地点", "english": "location", "type": "单词", "keyWords": [] },
    { "chinese": "坐落(在…)", "english": "be located (in/by/near…)", "type": "短语", "keyWords": ["locate"] },
    { "chinese": "新厂拟建于此。", "english": "A new factory is to be located on this site.", "type": "句子", "keyWords": ["locate"] },
    { "chinese": "确定...的地点；找到某人/物", "english": "locate sb./sth.", "type": "短语", "keyWords": ["locate"] },
    { "chinese": "在地图上指出一城市的位置", "english": "locate a city on the map", "type": "短语", "keyWords": ["locate"] },
    { "chinese": "n.锁；水闸；v.锁；锁上；v.被锁上；锁得上", "english": "lock", "type": "单词", "keyWords": [] },
    { "chinese": "这门锁不上。", "english": "The door doesn't lock.", "type": "句子", "keyWords": ["lock"] },
    { "chinese": "n.有锁的存物柜", "english": "locker", "type": "单词", "keyWords": [] },
    { "chinese": "n.机车；火车头", "english": "locomotive", "type": "单词", "keyWords": [] },
    { "chinese": "n.原木；圆形木材；v.伐(木)；[计]登录", "english": "log", "type": "单词", "keyWords": [] },
    { "chinese": "睡得像死人", "english": "sleep like a log", "type": "短语", "keyWords": ["log"] },
    { "chinese": "[计]进入；注册；登录", "english": "log on/login", "type": "短语", "keyWords": ["log"] },
    { "chinese": "n.逻辑；逻辑学；逻辑性", "english": "logic", "type": "单词", "keyWords": [] },
    { "chinese": "a.逻辑(上)的；符合逻辑的", "english": "logical", "type": "单词", "keyWords": [] },
    { "chinese": "a.不合逻辑的，不合理的", "english": "illogical", "type": "单词", "keyWords": [] },
    { "chinese": "a.寂寞的；孤寂的；偏僻的，人迹罕至的", "english": "lonely", "type": "单词", "keyWords": [] },
    { "chinese": "n.孤独；寂寞", "english": "loneliness", "type": "单词", "keyWords": [] },
    { "chinese": "v.(对不易获得的东西强烈)渴望(for)；a.长的；ad.长期；始终；n.[U]长期", "english": "long", "type": "单词", "keyWords": [] },
    { "chinese": "再见", "english": "so long", "type": "短语", "keyWords": ["long"] },
    { "chinese": "只要", "english": "as/so long as", "type": "短语", "keyWords": ["long"] },
    { "chinese": "渴望得到某物/渴望做某事(近be dying for/be eager to)", "english": "long for sth./long to do sth.", "type": "短语", "keyWords": ["long"] },
    { "chinese": "渴望某人做某事(arrange for/wait for sb. to do.)", "english": "long for sb. to do sth.", "type": "短语", "keyWords": ["long"] },
    { "chinese": "很久以前(单独用或后接sth.或句子)(辨析见ago)", "english": "long before", "type": "短语", "keyWords": ["long"] },
    { "chinese": "很久以后真相才会大白。", "english": "It will be long before we know the truth.", "type": "句子", "keyWords": ["long"] },
    { "chinese": "不久，不久以后(近soon/soon after/shortly after)", "english": "before long", "type": "短语", "keyWords": ["long"] },
    { "chinese": "不再；已不(近not...any longer,not...any more,no more)", "english": "no longer", "type": "短语", "keyWords": ["long"] },
    { "chinese": "思乡", "english": "a longing for home", "type": "短语", "keyWords": ["long"] },
    { "chinese": "渴望的目光", "english": "a longing look", "type": "短语", "keyWords": ["long"] },
    { "chinese": "a.长期的", "english": "long-term", "type": "单词", "keyWords": [] },
    { "chinese": "长期投资", "english": "a long-term investment", "type": "短语", "keyWords": ["long-term"] },
    { "chinese": "n.(U)长寿", "english": "longevity", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)经度，经线", "english": "longitude", "type": "单词", "keyWords": [] },
    { "chinese": "纽约的经度是西经74度。", "english": "The longitude of New York is 74 degrees west of Greenwich.", "type": "句子", "keyWords": ["longitude"] },
    { "chinese": "vi.看；好像；显得；n.[C](可a连用)看；脸色；神态；(pl.)容貌；v.打量；注视", "english": "look", "type": "单词", "keyWords": [] },
    { "chinese": "看一看；请看", "english": "have a look at sth.", "type": "短语", "keyWords": ["look"] },
    { "chinese": "环视；东张西望", "english": "look (a)round", "type": "短语", "keyWords": ["look"] },
    { "chinese": "照顾", "english": "look after", "type": "短语", "keyWords": ["look"] },
    { "chinese": "调查", "english": "look into", "type": "短语", "keyWords": ["look"] } 
];
