const qgl161_164 = [
    { "chinese": "回顾", "english": "look back on/to...", "type": "短语", "keyWords": ["look"] },
    { "chinese": "轻视，看不起", "english": "look down on", "type": "短语", "keyWords": ["look"] },
    { "chinese": "寻找", "english": "look for(search for, hunt for)", "type": "短语", "keyWords": ["look"] },
    { "chinese": "看作…", "english": "look on/upon...as...", "type": "短语", "keyWords": ["look"] },
    { "chinese": "期待，盼望", "english": "look forward to (doing) sth.", "type": "短语", "keyWords": ["look"] },
    { "chinese": "看上去与年龄相符", "english": "look one's age", "type": "短语", "keyWords": ["look"] },
    { "chinese": "上下打量某人", "english": "look sb. up and down", "type": "短语", "keyWords": ["look"] },
    { "chinese": "查看/过目一下(文件)", "english": "look over(the document)", "type": "短语", "keyWords": ["look"] },
    { "chinese": "指望(某人帮助)", "english": "look to(sb. for help)", "type": "短语", "keyWords": ["look"] },
    { "chinese": "当心落石/搜寻或守候某人", "english": "look out for falling rocks/sb.", "type": "短语", "keyWords": ["look"] },
    { "chinese": "旁观", "english": "look on", "type": "短语", "keyWords": ["look"] },
    { "chinese": "注意；留神", "english": "look out", "type": "短语", "keyWords": ["look"] },
    { "chinese": "浏览；核查；看穿，识破", "english": "look through", "type": "短语", "keyWords": ["look"] },
    { "chinese": "像…，似…", "english": "look like", "type": "短语", "keyWords": ["look"] },
    { "chinese": "(健康)正常", "english": "look oneself", "type": "短语", "keyWords": ["look"] },
    { "chinese": "向上看；查阅", "english": "look up", "type": "短语", "keyWords": ["look"] },
    { "chinese": "尊敬", "english": "look up to", "type": "短语", "keyWords": ["look"] },
    { "chinese": "n.[C]环，线（绳）圈；回路，回线；闭合电路", "english": "loop", "type": "单词", "keyWords": [] },
    { "chinese": "a.松的；松散的", "english": "loose", "type": "单词", "keyWords": [] },
    { "chinese": "v.解开；松开；vi.变松；松开；松弛", "english": "loosen", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]卡车", "english": "lorry", "type": "单词", "keyWords": [] },
    { "chinese": "v.失去；损失；丢失；（钟、表等）走慢；vi.受损失；输掉", "english": "lose", "type": "单词", "keyWords": [] },
    { "chinese": "输了一个球", "english": "lose by a goal", "type": "短语", "keyWords": ["lose"] },
    { "chinese": "灰心", "english": "lose heart", "type": "短语", "keyWords": ["lose"] },
    { "chinese": "失去希望", "english": "lose one's hope", "type": "短语", "keyWords": ["lose"] },
    { "chinese": "失去记忆", "english": "lose one's memory", "type": "短语", "keyWords": ["lose"] },
    { "chinese": "失去理智", "english": "lose one's mind", "type": "短语", "keyWords": ["lose"] },
    { "chinese": "体重减轻", "english": "lose weight", "type": "短语", "keyWords": ["lose"] },
    { "chinese": "迷路", "english": "lose one's way", "type": "短语", "keyWords": ["lose"] },
    { "chinese": "立刻做某事", "english": "lose no time (in) doing sth.", "type": "短语", "keyWords": ["lose"] },
    { "chinese": "陷入，沉于", "english": "(be) lost in", "type": "短语", "keyWords": ["lose"] },
    { "chinese": "n.[U]遗失；丧失；n.[C]失去的东西；损失人员/物的数量", "english": "loss", "type": "单词", "keyWords": [] },
    { "chinese": "遭受……极大的损失", "english": "have/suffer a (great/heavy) loss in/ of...", "type": "短语", "keyWords": ["loss"] },
    { "chinese": "茫然不知所措", "english": "at a loss", "type": "短语", "keyWords": ["loss"] },
    { "chinese": "不知道说什么好", "english": "be at a loss for words", "type": "短语", "keyWords": ["loss"] },
    { "chinese": "pron./ad.许多（a lot/lots）；n.（抽）签，（抓）阄", "english": "lot", "type": "单词", "keyWords": [] },
    { "chinese": "抽签", "english": "draw lots", "type": "短语", "keyWords": ["lot"] },
    { "chinese": "好多了", "english": "a lot better", "type": "短语", "keyWords": ["lot"] },
    { "chinese": "很多人", "english": "such/ quite a lot of people", "type": "短语", "keyWords": ["lot"] },
    { "chinese": "经常见到", "english": "see a lot of...", "type": "短语", "keyWords": ["lot"] },
    { "chinese": "许许多多的，大量的", "english": "lots and lots of", "type": "短语", "keyWords": ["lot"] },
    { "chinese": "a.亮的；大声的；ad.高声地，大声地（常与speak，talk，read等连用）", "english": "loud", "type": "单词", "keyWords": [] },
    { "chinese": "清楚明白地说", "english": "say sth. loud and clear", "type": "短语", "keyWords": ["loud"] },
    { "chinese": "ad.响亮地，大声地（常有吵闹、喧闹、影响他人之意）", "english": "loudly", "type": "单词", "keyWords": [] },
    { "chinese": "v.爱；喜欢；n.[U]爱，热爱，爱情；n.[C]（常与a连用）爱好，热爱", "english": "love", "type": "单词", "keyWords": [] },
    { "chinese": "爱上……", "english": "fall in love with (sb.)", "type": "短语", "keyWords": ["love"] },
    { "chinese": "向某人问候", "english": "give/send one's love to sb.", "type": "短语", "keyWords": ["love"] },
    { "chinese": "对……的爱", "english": "(have) a/one's/the love (of/for...)", "type": "短语", "keyWords": ["love"] },
    { "chinese": "爱情是盲目的。情人眼里出西施。", "english": "Love is blind.", "type": "句子", "keyWords": ["love"] },
    { "chinese": "爱屋及乌。打狗要看主人面。", "english": "Love me, love my dog.", "type": "句子", "keyWords": ["love"] },
    { "chinese": "a.可爱的；好看的；美丽动人的；美好的", "english": "lovely", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]爱好者；爱人；情人", "english": "lover", "type": "单词", "keyWords": [] },
    { "chinese": "a.钟爱的（可构成复合词表示“热爱……的”）", "english": "loving", "type": "单词", "keyWords": [] },
    { "chinese": "a.低的；矮的；ad.低低地；低下地，谦卑地", "english": "low", "type": "单词", "keyWords": [] },
    { "chinese": "a.较低的；v.放下；降下（反raise）；vi.降低；跌落；减弱（反rise）", "english": "lower", "type": "单词", "keyWords": [] },
    { "chinese": "下层阶级", "english": "the lower class", "type": "短语", "keyWords": ["lower"] },
    { "chinese": "放低声音", "english": "lower one's voice", "type": "短语", "keyWords": ["lower"] },
    { "chinese": "a.忠诚的，忠心的（to）", "english": "loyal", "type": "单词", "keyWords": [] },
    { "chinese": "忠于（某人/事业）", "english": "be loyal to (sb./a cause)", "type": "短语", "keyWords": ["loyal"] },
    { "chinese": "n.（U）忠诚；忠心耿耿（to）", "english": "loyalty", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]运气", "english": "luck", "type": "单词", "keyWords": [] },
    { "chinese": "a.幸运的；侥幸的；吉祥的", "english": "lucky", "type": "单词", "keyWords": [] },
    { "chinese": "碰运气", "english": "try one's luck at (doing) sth.", "type": "短语", "keyWords": ["luck"] },
    { "chinese": "不幸，倒霉", "english": "bad/ill luck", "type": "短语", "keyWords": ["luck"] },
    { "chinese": "幸运儿", "english": "a lucky dog", "type": "短语", "keyWords": ["luck"] },
    { "chinese": "祝你好运！", "english": "Wish you (good) luck! Good luck to you!", "type": "句子", "keyWords": ["luck"] },
    { "chinese": "我命里已注定这样。", "english": "It's just my luck.", "type": "句子", "keyWords": ["luck"] },
    { "chinese": "幸运；不幸；侥幸（视上下文而定）", "english": "as luck would have it", "type": "短语", "keyWords": ["luck"] },
    { "chinese": "n.[U]行李", "english": "luggage", "type": "单词", "keyWords": [] },
    { "chinese": "四件行李", "english": "four pieces of luggage/ baggage", "type": "短语", "keyWords": ["luggage"] },
    { "chinese": "n.[C][U]午餐", "english": "lunch", "type": "单词", "keyWords": [] },
    { "chinese": "在吃午饭（时）", "english": "at lunch", "type": "短语", "keyWords": ["lunch"] },
    { "chinese": "n.[C]肺脏，肺", "english": "lung", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]奢侈，豪华；n.[C]奢侈品/事", "english": "luxury", "type": "单词", "keyWords": [] },
    { "chinese": "a.豪华的，奢侈的", "english": "luxurious", "type": "单词", "keyWords": [] },
    { "chinese": "生活奢华", "english": "live in luxury", "type": "短语", "keyWords": ["luxury"] },
    { "chinese": "n.[C]机器", "english": "machine", "type": "单词", "keyWords": [] },
    { "chinese": "机器制作", "english": "by machine", "type": "短语", "keyWords": ["machine"] },
    { "chinese": "a.机械的", "english": "mechanical", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]机械；（总称）机器", "english": "machinery", "type": "单词", "keyWords": [] },
    { "chinese": "a.发疯的；狂热的，入迷的；[口]愤怒的，生气的", "english": "mad", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]癫狂；狂乱；疯狂", "english": "madness", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]疯人院", "english": "madhouse", "type": "单词", "keyWords": [] },
    { "chinese": "狂喜", "english": "be mad/wild with joy", "type": "短语", "keyWords": ["mad"] },
    { "chinese": "发狂似的想；迷于，迷着…", "english": "be mad about sth.", "type": "短语", "keyWords": ["mad"] },
    { "chinese": "发疯似的，迅速地，猛烈地", "english": "like mad/crazy(口)", "type": "短语", "keyWords": ["mad"] },
    { "chinese": "对…发怒", "english": "be/get mad at sb./sth./about sth. with sb.", "type": "短语", "keyWords": ["mad"] },
    { "chinese": "不要对我发脾气！", "english": "Don't get mad at me!", "type": "句子", "keyWords": ["mad"] },
    { "chinese": "使某人发疯", "english": "drive/send sb. mad", "type": "短语", "keyWords": ["mad"] },
    { "chinese": "发疯", "english": "go mad", "type": "短语", "keyWords": ["mad"] },
    { "chinese": "我回家迟了，所以妈妈发火了。", "english": "Mother got mad with me for coming home late.", "type": "句子", "keyWords": ["mad"] },
    { "chinese": "n.[C]夫人；女士（称呼妇女的尊称）；太太", "english": "madam", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]杂志；期刊", "english": "magazine", "type": "单词", "keyWords": [] },
    { "chinese": "a.有魔力的；n.[U]魔法；巫术；魔力", "english": "magic", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]巫师；法师；魔术师", "english": "magician", "type": "单词", "keyWords": [] },
    { "chinese": "神奇地；不可思议地", "english": "like magic", "type": "短语", "keyWords": ["magic"] },
    { "chinese": "变魔术，变戏法", "english": "perform magic", "type": "短语", "keyWords": ["magic"] },
    { "chinese": "a.巫术的；（似）魔术的，有魔力的；神秘的", "english": "magical", "type": "单词", "keyWords": [] },
    { "chinese": "有魔力地，不可思议地", "english": "magically", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]磁铁/石", "english": "magnet", "type": "单词", "keyWords": [] },
    { "chinese": "a.磁的；有磁性的", "english": "magnetic", "type": "单词", "keyWords": [] },
    { "chinese": "a.壮丽的；宏伟的", "english": "magnificent", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]壮丽；宏伟", "english": "magnificence", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]女仆，女佣", "english": "maid", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]邮件；邮政[英]post；v.邮寄[英]post；vi.寄出，付邮", "english": "mail", "type": "单词", "keyWords": [] },
    { "chinese": "寄航空邮件", "english": "send sth.by air mail", "type": "短语", "keyWords": ["mail"] },
    { "chinese": "寄平信", "english": "by ordinary mail", "type": "短语", "keyWords": ["mail"] },
    { "chinese": "寄…给某人", "english": "mail sth.to sb.", "type": "短语", "keyWords": ["mail"] },
    { "chinese": "a.主要的（指起到主体作用）", "english": "main", "type": "单词", "keyWords": [] },
    { "chinese": "ad.主要地；大部分地", "english": "mainly", "type": "单词", "keyWords": [] },
    { "chinese": "主句", "english": "main clause", "type": "短语", "keyWords": ["main"] },
    { "chinese": "铁路干线", "english": "main line", "type": "短语", "keyWords": ["main"] },
    { "chinese": "干线", "english": "main road", "type": "短语", "keyWords": ["main"] },
    { "chinese": "主菜", "english": "main course", "type": "短语", "keyWords": ["main"] },
    { "chinese": "n.[C]大陆（常用the mainland）；a.大陆的", "english": "mainland", "type": "单词", "keyWords": [] },
    { "chinese": "v.维持；供养；维修，保养；（坚决）主张，强调，断言", "english": "maintain", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]维持；保养", "english": "maintenance", "type": "单词", "keyWords": [] },
    { "chinese": "养家", "english": "maintain one's family", "type": "短语", "keyWords": ["maintain"] },
    { "chinese": "守纪", "english": "maintain discipline", "type": "短语", "keyWords": ["maintain"] },
    { "chinese": "保养公路", "english": "maintain highways", "type": "短语", "keyWords": ["maintain"] },
    { "chinese": "a.主要的（minor）；大的；主修的；vi.主修（in）；n.[C]主修课程；主修学生", "english": "major", "type": "单词", "keyWords": [] },
    { "chinese": "主修（工程学）", "english": "major in(engineering)", "type": "短语", "keyWords": ["major"] },
    { "chinese": "她是历史专业的学生。她的专业是历史。", "english": "She is a history major./ Her major is history.", "type": "句子", "keyWords": ["major"] },
    { "chinese": "n.[C]（常用the majority of）大多数；半数以上（用作单或复数）", "english": "majority", "type": "单词", "keyWords": [] },
    { "chinese": "少数应服从多数。", "english": "The minority should submit to the majority.", "type": "句子", "keyWords": ["majority"] },
    { "chinese": "大多数人爱好和平。", "english": "The majority of the people love/ loves peace.", "type": "句子", "keyWords": ["majority"] },
    { "chinese": "他以（876票的）绝对多数当选。", "english": "He was elected by a large majority(of 876).", "type": "句子", "keyWords": ["majority"] },
    { "chinese": "v.做；使；（有条件）成为；选举；[口]走，行；n.[C]牌子，型号；式样", "english": "make", "type": "单词", "keyWords": [] },
    { "chinese": "充分利用", "english": "make the most of", "type": "短语", "keyWords": ["make"] },
    { "chinese": "捉弄，使出洋相", "english": "make a fool of", "type": "短语", "keyWords": ["make"] },
    { "chinese": "收支相抵", "english": "make ends meet", "type": "短语", "keyWords": ["make"] },
    { "chinese": "打定主意；决定", "english": "make up one's mind", "type": "短语", "keyWords": ["make"] },
    { "chinese": "整理床铺，铺床", "english": "make the bed", "type": "短语", "keyWords": ["make"] },
    { "chinese": "一天走10英里", "english": "make ten miles a day", "type": "短语", "keyWords": ["make"] },
    { "chinese": "泡茶，沏茶", "english": "make tea", "type": "短语", "keyWords": ["make"] },
    { "chinese": "使他成为军人", "english": "make him a soldier", "type": "短语", "keyWords": ["make"] },
    { "chinese": "与…和好", "english": "make peace with...", "type": "短语", "keyWords": ["make"] },
    { "chinese": "好好去做（不喜欢做的事）", "english": "make the best of", "type": "短语", "keyWords": ["make"] },
    { "chinese": "他是被迫去的。", "english": "He was made to go.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "使人理解自己的意思", "english": "make oneself understood", "type": "短语", "keyWords": ["make"] },
    { "chinese": "我做了一套新的衣服给他。", "english": "I made him a new suit.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "2加2得（等于）4。", "english": "Two and two make four.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "用…制成…（指制成品看得出原材料，否则用from）", "english": "make...out of...", "type": "短语", "keyWords": ["make"] },
    { "chinese": "把他塑造成医生", "english": "make a doctor of him/out of him(make him into a doctor)", "type": "短语", "keyWords": ["make"] },
    { "chinese": "凉茶是夏天的好饮料。", "english": "Cold tea makes an excellent drink in summer.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "尽力做到，保证；深信，有把握", "english": "make sure of that...", "type": "短语", "keyWords": ["make"] },
    { "chinese": "你必须把时间和地点弄清楚。", "english": "You must make sure of the time and place.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "确保孩子有充足的睡眠。", "english": "Make sure your child gets sufficient sleep.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "（有目的且快速地）冲向（近leave for，head for）", "english": "make for", "type": "短语", "keyWords": ["make"] },
    { "chinese": "开始下雨了，所以她向最近的避雨处奔去。", "english": "It started raining, so she made for the nearest shelter.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "及时到达；成功", "english": "make it", "type": "短语", "keyWords": ["make"] },
    { "chinese": "你能来吗？", "english": "Can you make it?", "type": "句子", "keyWords": ["make"] },
    { "chinese": "匆匆离开", "english": "make off", "type": "短语", "keyWords": ["make"] },
    { "chinese": "强盗一看见警察就跑了。", "english": "The robber made off the moment he saw a policeman.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "偷；带···逃跑", "english": "make off with...", "type": "短语", "keyWords": ["make"] },
    { "chinese": "屋子里的东西被贼洗劫一空。", "english": "The thieves made off with everything in the house.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "①开出，写出（make out a cheque/a bill/a list）；②理解；③辨认出", "english": "make out", "type": "短语", "keyWords": ["make"] },
    { "chinese": "我不明白警察要的是什么。", "english": "I couldn't make out what the police wanted.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "我看见远处有一条船。", "english": "I made out a ship in the distance.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "①编造；②构成；凑足（比较be made up of）；③弥补；偿还；④v./vi.化装；化妆", "english": "make up", "type": "短语", "keyWords": ["make"] },
    { "chinese": "整个故事是虚构的。", "english": "The whole story is made up.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "互通有无。", "english": "Each makes up what the other lacks.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "她不化妆是从不外出的。", "english": "She never goes out without making herself up first.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "细胞构成了人体组织。", "english": "Cells make up human tissue.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "人体组织是由细胞构成的。", "english": "Human tissue is made up of cells.", "type": "句子", "keyWords": ["make"] } 
];
