const qgl165_172 = [
    { "chinese": "每种物质，不管是什么，都由原子构成。", "english": "Each substance, whatever it is, is made up of atoms.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "补偿；弥补", "english": "make up (for) sth.", "type": "短语", "keyWords": ["make"] },
    { "chinese": "补回损失的时间", "english": "make up (for) lost time", "type": "短语", "keyWords": ["make"] },
    { "chinese": "弥补损失", "english": "make up (for) a loss", "type": "短语", "keyWords": ["make"] },
    { "chinese": "这是完全捏造的故事。", "english": "It's all a made-up story.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "(家具、衣服等) 定制的，定做的", "english": "made-to-measure", "type": "短语", "keyWords": ["make"] },
    { "chinese": "这是什么牌子的汽车？", "english": "What make of car is this?", "type": "句子", "keyWords": ["make"] },
    { "chinese": "趁晴晒草。勿失良机。", "english": "Make hay while the sun shines.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "n. 疟疾", "english": "malaria", "type": "单词", "keyWords": [] },
    { "chinese": "a. 男性的；阳性的；[植]雄性的；n. [C]男子；雄性动物；[植]雄性植物", "english": "male", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]林荫路；步行街；[美]购物中心，商场", "english": "mall", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]人；男人；男子汉；n. [U]人类（不带冠词，同mankind）；v. 给··配置兵员", "english": "man", "type": "单词", "keyWords": [] },
    { "chinese": "他父亲死后，他就变得像个大人了。", "english": "His father's death has made a man of him.", "type": "句子", "keyWords": ["man"] },
    { "chinese": "他有足够的勇气来接受挑战吗？", "english": "Was he man enough to take the challenge?", "type": "句子", "keyWords": ["man"] },
    { "chinese": "v. 设法做到；管理；经营；操纵，开动；vi. 处理，设法对付；管理；经营", "english": "manage", "type": "单词", "keyWords": [] },
    { "chinese": "成功地做成某事（近try to do sth./try one's best to do sth.尽力办成某事）", "english": "manage to do sth.", "type": "短语", "keyWords": ["manage"] },
    { "chinese": "你能再吃一片蛋糕吗？", "english": "Can you manage another slice of cake?", "type": "句子", "keyWords": ["manage"] },
    { "chinese": "我能办成。", "english": "I can manage(it).", "type": "句子", "keyWords": ["manage"] },
    { "chinese": "n. [C]经理", "english": "manager", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]处理；管理，经营", "english": "management", "type": "单词", "keyWords": [] },
    { "chinese": "a. 易处理的，易办的；易管理的；易掌控的", "english": "manageable", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]芒果；芒果树", "english": "mango", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]人类", "english": "mankind", "type": "单词", "keyWords": [] },
    { "chinese": "a. 人造的；人为的（比较machine-made机制的）", "english": "man-made", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]方式；态度；举止（侧重指具有个人特色的行为，办事方式）；(pl)礼貌；规矩", "english": "manner", "type": "单词", "keyWords": [] },
    { "chinese": "餐桌礼仪", "english": "table manners", "type": "短语", "keyWords": ["manner"] },
    { "chinese": "……（没）有礼貌的", "english": "It's bad/good manners to do sth....", "type": "句子", "keyWords": ["manner"] },
    { "chinese": "以……方式（近by...means）", "english": "in a...manner/way/mode", "type": "短语", "keyWords": ["manner"] },
    { "chinese": "n. [C]大厦；大楼", "english": "mansion", "type": "单词", "keyWords": [] },
    { "chinese": "a. 手工的；体力的；n. [C]手册", "english": "manual", "type": "单词", "keyWords": [] },
    { "chinese": "体力活", "english": "manual work", "type": "短语", "keyWords": ["manual"] },
    { "chinese": "家用维修手册", "english": "a manual of home repairs", "type": "短语", "keyWords": ["manual"] },
    { "chinese": "v. [T]（指大量）制造；生产；manufacturer n. [C]制造商", "english": "manufacture", "type": "单词", "keyWords": [] },
    { "chinese": "a. 许多；pron. 许多人/物", "english": "many", "type": "单词", "keyWords": [] },
    { "chinese": "许多（用法同many）", "english": "a good/great many", "type": "短语", "keyWords": ["many"] },
    { "chinese": "许多学生获得了这样的机会。", "english": "Many a student has got such an opportunity.", "type": "句子", "keyWords": ["many"] },
    { "chinese": "来多少就可以接纳多少。", "english": "They admit as many as come.", "type": "句子", "keyWords": ["many"] },
    { "chinese": "n. [C]地图；v. (mapped, mapping)绘制……的地图", "english": "map", "type": "单词", "keyWords": [] },
    { "chinese": "科学家绘制了月球表面的地图。", "english": "The scientists mapped the surface of the moon.", "type": "句子", "keyWords": ["map"] },
    { "chinese": "仔细规划她的将来", "english": "map out her future", "type": "短语", "keyWords": ["map"] },
    { "chinese": "n. [C]马拉松赛跑（全程约26英里或42公里）", "english": "marathon", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]三月（略作Mar.）", "english": "March", "type": "单词", "keyWords": [] },
    { "chinese": "v. 行军；行进；v. 使行军；使行进；n. [C]行军；行进；[音]进行曲", "english": "march", "type": "单词", "keyWords": [] },
    { "chinese": "在进行中", "english": "on the march", "type": "短语", "keyWords": ["march"] },
    { "chinese": "长征", "english": "the Long March", "type": "短语", "keyWords": ["march"] },
    { "chinese": "n. [C]页边的空白，(湖、池等的)边缘；marginal a. 边的，边缘的；在外的", "english": "margin", "type": "单词", "keyWords": [] },
    { "chinese": "在页边作记号表示有遗漏", "english": "put a mark in the margin to show the omission", "type": "短语", "keyWords": ["margin"] },
    { "chinese": "那老人已濒临死亡。", "english": "The old man was on the margin of death.", "type": "句子", "keyWords": ["margin"] },
    { "chinese": "a. 海(洋)的；航海的；海军的；marine life海洋生物", "english": "marine", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](考试等)分数；记号；痕迹；*德国马克(币)；v. 给…打分；做记号；*注意；标志", "english": "mark", "type": "单词", "keyWords": [] },
    { "chinese": "给某人高（低）分", "english": "give sb.a good/high/bad/poor/zero mark", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "赞赏某人（做）某事", "english": "give sb.full marks for (doing)sth.", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "英语得80分/满分", "english": "get 80 marks/full marks for English", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "在有疑问的地方做一个记号。", "english": "Make a mark where you have any doubts or questions.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "在……方面成功；成名（近make a name for oneself）", "english": "make one's/a mark(on)", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "他想在历史上留名。", "english": "He wants to make his mark on history.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "注意听。", "english": "Mark my words.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "豹身上有黑斑纹。", "english": "The leopard's skin is marked with black spots.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "留有足迹的泥路", "english": "a muddy road (which was) marked with footprints", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "他的死标志着一个时代的结束。", "english": "His death marked the end of an era.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "n. [C]市场；v. 在市场上进行交易；销售；*marketing n. [U]销售；销售学", "english": "market", "type": "单词", "keyWords": [] },
    { "chinese": "上市；出售", "english": "on the market", "type": "短语", "keyWords": ["market"] },
    { "chinese": "他们在市场上出售他们的房子。", "english": "They've put their houses on the market.", "type": "句子", "keyWords": ["market"] },
    { "chinese": "某东西需求量很大。", "english": "There is a big market for sth.", "type": "句子", "keyWords": ["market"] },
    { "chinese": "销售体系", "english": "*marketing system", "type": "短语", "keyWords": ["market"] },
    { "chinese": "n. [C](U)结婚；婚姻", "english": "marriage", "type": "单词", "keyWords": [] },
    { "chinese": "v. 娶；嫁；与……结婚；把…嫁出；使…娶亲；vi. 结婚", "english": "marry", "type": "单词", "keyWords": [] },
    { "chinese": "使……与……结婚", "english": "marry sb.to sb.", "type": "短语", "keyWords": ["marry"] },
    { "chinese": "与……结了婚", "english": "be married to sb.", "type": "短语", "keyWords": ["marry"] },
    { "chinese": "他把女儿嫁给了一个农民。", "english": "He married his daughter to a farmer.", "type": "句子", "keyWords": ["marry"] },
    { "chinese": "去年他的女儿嫁给了一个农民。", "english": "His daughter got married to a farmer last year.", "type": "句子", "keyWords": ["marry"] },
    { "chinese": "他的女儿嫁给了一个农民。", "english": "His daughter was married to a farmer.", "type": "句子", "keyWords": ["marry"] },
    { "chinese": "a. 已婚的；a married man已婚男子，有配偶的男人", "english": "married", "type": "单词", "keyWords": [] },
    { "chinese": "n. 火星", "english": "Mars", "type": "单词", "keyWords": [] },
    { "chinese": "a. 令人惊奇的；奇特的；奇迹般的；绝妙的", "english": "marvel(I)ous", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]面具；口罩；*v. 在(脸)上戴假面具", "english": "mask", "type": "单词", "keyWords": [] },
    { "chinese": "戴假面具，掩盖真面目", "english": "put on/wear the mask", "type": "短语", "keyWords": ["mask"] },
    { "chinese": "戴了面具的强盗", "english": "a masked robber", "type": "短语", "keyWords": ["mask"] },
    { "chinese": "n. (C]大量；团；块；(the masses)群众，民众；massive a. 巨大的；大规模的", "english": "mass", "type": "单词", "keyWords": [] },
    { "chinese": "一大块泥土", "english": "a mass of earth", "type": "短语", "keyWords": ["mass"] },
    { "chinese": "一大堆信件", "english": "a mass of letters", "type": "短语", "keyWords": ["mass"] },
    { "chinese": "人民群众有无限的创造力。", "english": "The masses have boundless creative power.", "type": "句子", "keyWords": ["mass"] },
    { "chinese": "v. 精通，掌握；n. [C]主人；雇主；名家，大师；船长；名家作品；硕士；[英]男教师", "english": "master", "type": "单词", "keyWords": [] },
    { "chinese": "独立自主，不受别人牵制", "english": "be one's own master", "type": "短语", "keyWords": ["master"] },
    { "chinese": "精通英文", "english": "master English", "type": "短语", "keyWords": ["master"] },
    { "chinese": "n. [C]杰作", "english": "masterpiece", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]比赛；竞赛；对手；相配的人或物；火柴；v. 和……相配；使相配；和……匹敌；vi. 相配；相适合（辨析见fit）", "english": "match", "type": "单词", "keyWords": [] },
    { "chinese": "棋逢对手", "english": "meet in one's match", "type": "短语", "keyWords": ["match"] },
    { "chinese": "拳击者遇到了他的对手。", "english": "The boxer met his match.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "餐巾和桌布相配得很好。", "english": "The napkins were nice and matched for the tablecloth.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "这两种颜色很相配。", "english": "The colors were a close match.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "外衣和裙子很相配。", "english": "The coat matches the dress.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "衬衫的颜色与上衣的颜色不相配。", "english": "The color of the shirt does not match that of the coat.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "与……相匹配", "english": "match sth. with sth.", "type": "短语", "keyWords": ["match"] },
    { "chinese": "我们应该像他们一样慷慨大方。", "english": "We should match their generosity with our own.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "窗帘与室内装潢不相配。", "english": "The curtains do not match with the decoration.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "n. [C]一对中的一个；配偶；伙伴；同事", "english": "mate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](U]材料；资料；物资；n. [U](写书用的)素材；*.物质上的；重要的", "english": "material", "type": "单词", "keyWords": [] },
    { "chinese": "物质世界", "english": "the material world", "type": "短语", "keyWords": ["material"] },
    { "chinese": "建筑材料/教材", "english": "building/ teaching materials", "type": "短语", "keyWords": ["material"] },
    { "chinese": "收集写作素材", "english": "gather material for an article", "type": "短语", "keyWords": ["material"] },
    { "chinese": "n. [U]唯物主义；(贬义)物质(中心)主义", "english": "*materialism", "type": "单词", "keyWords": [] },
    { "chinese": "a. 唯物论的；唯物主义的", "english": "*materialistic", "type": "单词", "keyWords": [] },
    { "chinese": "a. 数学的", "english": "mathematical", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]数学（常略作math或maths）", "english": "mathematics", "type": "单词", "keyWords": [] },
    { "chinese": "n. (the)麻烦事；n. [C]事情；问题；n. [U]物质（近substance n. (C])；vi. (多用在否定句、疑问句和条件句中)要紧；有重大关系", "english": "matter", "type": "单词", "keyWords": [] },
    { "chinese": "事实上", "english": "as a matter of fact", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "……怎么了？", "english": "What's the matter with sb./sth.?", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "生死攸关的事", "english": "a matter of life and death", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "这对他们来说是生死攸关的问题。", "english": "It was a matter of life and death for them.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "不是闹着玩的事", "english": "no laughing matter", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "不管怎样/什么/何时（近however, whatever, whenever...，注意no matter不单独用作连词）", "english": "No matter how/what/when", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "令事情更糟糕的是（常作插入语用）", "english": "to make matters worse/ what makes matters worse", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "情况就是这样。", "english": "That's how matters stand.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "物质以三种状态存在：固态、液态和气态。", "english": "Matter exists in three states: solid, liquid and gas.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "你留下来还是和他们一起去对他们来说无所谓。", "english": "It doesn't matter to them whether you stay or go with them.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "最重要的是你所关注的东西。", "english": "What matters most is what you focus on.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "“那有什么关系呢？”她带着一种傲慢的神情问道。", "english": "\"What does that matter?\" she asked, with a proud air.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "重要的不是身材的高矮，而是心胸的宽窄。", "english": "It is not the size of a man but the size of his heart that matters.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "a. (成)熟的，成年人的；到期的；明白事理的，稳重的；慎重的；v. 使成熟；使长成；vi. 成熟，到期", "english": "mature", "type": "单词", "keyWords": [] },
    { "chinese": "经过深思熟虑的计划", "english": "a mature plan", "type": "短语", "keyWords": ["mature"] },
    { "chinese": "n. [U]成熟；(计划等)完备；(票据等)到期", "english": "maturity", "type": "单词", "keyWords": [] },
    { "chinese": "a. 最大的，最高的", "english": "maximal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl.maximums/maxima)最大量；最大限度；最大限", "english": "maximum", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]五月；on May Day在五一劳动节", "english": "May", "type": "单词", "keyWords": [] },
    { "chinese": "aux. 可以（表许可或用于请求许可）；或许（常用于肯定句、否定句中）；祝", "english": "may", "type": "单词", "keyWords": [] },
    { "chinese": "祝你快乐！", "english": "May you be happy!", "type": "句子", "keyWords": ["may"] },
    { "chinese": "或许……做过", "english": "may/might have done sth.", "type": "短语", "keyWords": ["may"] },
    { "chinese": "还是……好；倒不如", "english": "may/might as well do sth.", "type": "短语", "keyWords": ["may"] },
    { "chinese": "ad. 大概，或许", "english": "maybe", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]市长；be elected mayor被选为市长", "english": "mayor", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]膳食；一餐", "english": "meal", "type": "单词", "keyWords": [] },
    { "chinese": "v. 意思是；意指；意味着，即是；意欲，打算；a. 卑鄙的；吝啬的；中间的；中等的；普通的；平均的；*meanness n. 卑鄙，吝啬", "english": "mean", "type": "单词", "keyWords": [] },
    { "chinese": "对……极其/很/不重要", "english": "mean a great deal/a lot/nothing to sb.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "她视金钱如粪土。", "english": "Money means nothing to her.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "意味着", "english": "mean(doing) sth.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "充分利用时间并不意味着从早到晚不停地看书。", "english": "Making the best of time doesn't mean keeping on reading from morning till night.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "我不是有心的。我不是故意的。", "english": "I did not mean it.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "本意为；打算（比较want, intend, plan, hope, wish等用法）", "english": "mean to do sth.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "我没有侮辱你的意思。", "english": "I don't mean to insult you.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "对不起。我不是有意伤你感情的。", "english": "I'm sorry. I did not mean to hurt you/your feeling.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "本来想做某事（但没做成）", "english": "meant to have done.../had meant to do...", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "我本想告诉你的，可是我忘记了。", "english": "I meant to have told you about it, but forgot to do so.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "你那样说是什么意思？", "english": "What do you mean by (saying) that?", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "他提到的“他们”是指谁？", "english": "Whom did he mean by \"they\"?", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "所谓四个保证，就是指这四件事情。", "english": "These are what we mean by the four guarantees.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "为某人准备……；用于；为……准备的；预定", "english": "mean sth. for sb./be meant for...", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "他准备把这栋房子给女儿。", "english": "He meant this house for his daughter.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "这就是笑话。", "english": "This was meant for a joke.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "本来是准备把他培养成为医生的。", "english": "He was meant for/to be a doctor.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "要某人做某事；被认为/期望做某事；应该做某事（be expected/supposed to do）", "english": "mean sb. to do sth./be meant to do sth.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "不要靠吃药过生活。", "english": "Medicines are not meant to live on.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "你不该在这里抽烟。", "english": "You are not meant to smoke here.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "a. 卑鄙的动机", "english": "a mean motive", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "一毛不拔", "english": "be mean with one's money", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "简陋的房子", "english": "a mean cottage", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "在……方面很小气/吝啬", "english": "be mean about/over sth.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "n. [C](U)意义；意思；meaningful a. 意味深长的；meaningless a. 无意义的", "english": "meaning", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]（单复同）方法；手段；工具（指为达到目的而采取的手段，也可指交通工具）", "english": "means", "type": "单词", "keyWords": [] },
    { "chinese": "生产手段，生产工具，生产资料", "english": "means of production", "type": "短语", "keyWords": ["means"] },
    { "chinese": "千方百计", "english": "try many/every means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "运输工具；交通设施；运输方式", "english": "means of transportation", "type": "短语", "keyWords": ["means"] },
    { "chinese": "(表示同意)当然可以，没问题；无论如何，不惜一切地，千方百计地", "english": "by all means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "想个办法；以某种方法（近in one way or another）", "english": "by some means(or other)", "type": "短语", "keyWords": ["means"] },
    { "chinese": "通过；用；借助于", "english": "by means of", "type": "短语", "keyWords": ["means"] },
    { "chinese": "用这种方法", "english": "by this means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "怎样", "english": "by what means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "[口]用一切可能的方法或手段", "english": "by any means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "不，一点也不（见account）", "english": "by no means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "要满足每一个人绝非易事。（倒装）", "english": "By no means is it easy to satisfy everyone.", "type": "句子", "keyWords": ["means"] },
    { "chinese": "n. 间隔时间；同时；期间", "english": "meantime", "type": "单词", "keyWords": [] },
    { "chinese": "(与此)同时", "english": "in the meantime", "type": "短语", "keyWords": ["meantime"] },
    { "chinese": "n. 间隔时间；同时；期间", "english": "meanwhile", "type": "单词", "keyWords": [] },
    { "chinese": "(与此)同时", "english": "in the meanwhile", "type": "短语", "keyWords": ["meanwhile"] },
    { "chinese": "警察马上就来，在此期间，你应该保持冷静。", "english": "The police will be here soon. Meanwhile/Meantime/in the meanwhile/in the meantime you should stay calm.", "type": "句子", "keyWords": ["meantime", "meanwhile"] },
    { "chinese": "v. 量，测量；vi. (测)量；可测量；尺寸是；n. [C]措施；n. [C](U)度量，尺寸，量", "english": "measure", "type": "单词", "keyWords": [] },
    { "chinese": "量身裁衣", "english": "make clothes to my measure", "type": "短语", "keyWords": ["measure"] },
    { "chinese": "桌子宽55厘米。", "english": "The desk measures 55cm across.", "type": "句子", "keyWords": ["measure"] },
    { "chinese": "桌子长98厘米，宽55厘米。", "english": "The desk measures 98x55cm(98 by 55cm).", "type": "句子", "keyWords": ["measure"] },
    { "chinese": "采取措施做某事", "english": "take measures/steps/action to do sth.", "type": "短语", "keyWords": ["measure"] },
    { "chinese": "裁缝量了我的尺寸准备帮我做新衣服。", "english": "The tailor took my measure for a new suit.", "type": "句子", "keyWords": ["measure"] },
    { "chinese": "n. [U]肉", "english": "meat", "type": "单词", "keyWords": [] },
    { "chinese": "利于甲者未必利于乙。", "english": "One man's meat is another man's poison.", "type": "句子", "keyWords": ["meat"] },
    { "chinese": "n. [C]技工；机械工人；*mechanics n. (单数用)力学；机械学", "english": "mechanic", "type": "单词", "keyWords": [] },
    { "chinese": "a. 机械的；mechanically ad. 机械地；无意识地", "english": "mechanical", "type": "单词", "keyWords": [] },
    { "chinese": "机械能", "english": "mechanical energy", "type": "短语", "keyWords": ["mechanical"] },
    { "chinese": "n. [C]奖牌；纪念章", "english": "medal", "type": "单词", "keyWords": [] },
    { "chinese": "a. 医学的；医疗的；内科的（反surgical）", "english": "medical", "type": "单词", "keyWords": [] },
    { "chinese": "进行体格检查", "english": "have a medical examination", "type": "短语", "keyWords": ["medical"] },
    { "chinese": "n. [U]医学；内科(治疗)（反surgery）；n. [C](U)药", "english": "medicine", "type": "单词", "keyWords": [] },
    { "chinese": "感冒良药", "english": "a good medicine for cold", "type": "短语", "keyWords": ["medicine"] },
    { "chinese": "吃药", "english": "take medicine", "type": "短语", "keyWords": ["medicine"] },
    { "chinese": "n. [C]媒介物；(常用pl.media)新闻媒体，传媒；a. 中间的；中等的；适度的（以-um结尾的词：bacterium, memorandum, datum, maximum, minimum, gymnasium, stadium, curriculum）", "english": "medium", "type": "单词", "keyWords": [] },
    { "chinese": "v. 遇见；会见；满足；相遇；(路、河流等)相合；vi. 相遇；(路、河流等)相合", "english": "meet", "type": "单词", "keyWords": [] },
    { "chinese": "她的目光和我的相遇。", "english": "Hereyes met mine.", "type": "句子", "keyWords": ["meet"] },
    { "chinese": "符合某人的需要/需求/要求/希望", "english": "meet one's needs/demands/requirements/expenses/one's hopes", "type": "短语", "keyWords": ["meet"] },
    { "chinese": "偶然遇到；遭遇（近run/bump into，come across，*chance upon）", "english": "meet with", "type": "短语", "keyWords": ["meet"] },
    { "chinese": "n. [C]会议；会合；聚集", "english": "meeting", "type": "单词", "keyWords": [] },
    { "chinese": "解散会议，闭会", "english": "break up a meeting", "type": "短语", "keyWords": ["meeting"] },
    { "chinese": "召集大会", "english": "call a meeting", "type": "短语", "keyWords": ["meeting"] },
    { "chinese": "n. [C]瓜(尤指甜瓜、西瓜等)", "english": "melon", "type": "单词", "keyWords": [] },
    { "chinese": "西瓜", "english": "water melon", "type": "短语", "keyWords": ["melon"] },
    { "chinese": "v. 使熔化；使融化；使溶解；vi. 熔化；融化；溶解", "english": "melt", "type": "单词", "keyWords": [] },
    { "chinese": "熔点，融点", "english": "melting point", "type": "短语", "keyWords": ["melt"] },
    { "chinese": "n. [C]成员；会员；*membership n. [U]成员资格；成员身份", "english": "member", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl.memos)[口]备忘录(=memorandum)", "english": "memo", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl.memorandums或memoranda)备忘录", "english": "memorandum", "type": "单词", "keyWords": [] },
    { "chinese": "a. 值得纪念的", "english": "memorable", "type": "单词", "keyWords": [] },
    { "chinese": "a. 纪念性的；追悼的；n. [C]纪念碑(to sb.)", "english": "memorial", "type": "单词", "keyWords": [] },
    { "chinese": "为……立的纪念碑；作为……的纪念物", "english": "a memorial to sb.", "type": "短语", "keyWords": ["memorial"] },
    { "chinese": "教堂的礼拜仪式是为纪念死于战争中的人而举行的。", "english": "The church service is a memorial to those killed in the war.", "type": "句子", "keyWords": ["memorial"] },
    { "chinese": "v. 记住；熟记", "english": "memorize", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](U)记忆(力)；n. [C]回忆；留在记忆中的人或物；[计]存储器；n. [U]纪念", "english": "memory", "type": "单词", "keyWords": [] },
    { "chinese": "对某事的记忆力很好/差", "english": "have a good/bad/poor memory for sth.", "type": "短语", "keyWords": ["memory"] },
    { "chinese": "记着，没有忘记", "english": "bear/have/keep...in memory/mind", "type": "短语", "keyWords": ["memory"] },
    { "chinese": "凭记忆(发言)", "english": "(make a speech) from memory", "type": "短语", "keyWords": ["memory"] },
    { "chinese": "那不过是我的校园生活/学生时代的一个美好回忆而已。", "english": "It is but a good memory of my schooldays.", "type": "句子", "keyWords": ["memory"] },
    { "chinese": "以纪念（近in honour of，in celebration of，in search of）", "english": "in memory of", "type": "短语", "keyWords": ["memory"] },
    { "chinese": "他们为了纪念那位科学家种了一棵树。", "english": "They planted a tree in memory of the scientist.", "type": "句子", "keyWords": ["memory"] },
    { "chinese": "有很多东西要记", "english": "have a lot of memory work to do", "type": "句子", "keyWords": ["memory"] },
    { "chinese": "v. 修理，修补；弥补，改善", "english": "mend", "type": "单词", "keyWords": [] },
    { "chinese": "a. 精神的；智力的；内心的；mentally ad. 智力上地；精神上地；*mentality n. [U]智力；mental disorder精神错乱；mental hospital精神病院", "english": "mental", "type": "单词", "keyWords": [] },
    { "chinese": "v. 提到，说起；make mention of...；n. [U]说到，提及", "english": "mention", "type": "单词", "keyWords": [] },
    { "chinese": "提及做某事", "english": "mention doing sth.", "type": "短语", "keyWords": ["mention"] },
    { "chinese": "不用谢；不用客气。", "english": "Don't mention it.", "type": "句子", "keyWords": ["mention"] },
    { "chinese": "更不用说，此外（let alone）", "english": "not to mention", "type": "短语", "keyWords": ["mention"] },
    { "chinese": "已发现的就有1000万片，更不用说还有埋在地底下没有动过的。", "english": "The discovered pieces have amounted to ten million not to mention those lying untouched underground.", "type": "句子", "keyWords": ["mention"] },
    { "chinese": "说起（近at the sight/thought/command of）", "english": "at the mention of...", "type": "短语", "keyWords": ["mention"] },
    { "chinese": "n. [C]菜单；[计]菜单", "english": "menu", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]商人", "english": "merchant", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](U)慈悲；宽容；merciful a. 慈悲的；merciless a. 无情的，残忍的", "english": "mercy", "type": "单词", "keyWords": [] },
    { "chinese": "任……的摆布 = (be) left to the mercy/mercies of...", "english": "at the mercy of", "type": "短语", "keyWords": ["mercy"] },
    { "chinese": "农民是靠天吃饭的。", "english": "Farmers are at the mercy of the weather.", "type": "句子", "keyWords": ["mercy"] },
    { "chinese": "怜悯某人；可怜某人", "english": "show mercy to sb. = have mercy on sb.", "type": "短语", "keyWords": ["mercy"] },
    { "chinese": "冷酷无情地", "english": "without mercy = mercilessly", "type": "短语", "keyWords": ["mercy"] },
    { "chinese": "n. [C][U]安乐死", "english": "*mercy killing", "type": "单词", "keyWords": [] },
    { "chinese": "a. 仅仅的；merely ad. 仅仅，只不过(=only)；纯粹；全然", "english": "mere", "type": "单词", "keyWords": [] },
    { "chinese": "仅仅是个孩子", "english": "a mere child", "type": "短语", "keyWords": ["mere"] },
    { "chinese": "只有100米", "english": "a mere 100 metres", "type": "短语", "keyWords": ["mere"] },
    { "chinese": "完全是一个形式问题。", "english": "This is merely a matter of form.", "type": "句子", "keyWords": ["mere"] },
    { "chinese": "n. [C]优点(常pl.merits)", "english": "*merit", "type": "单词", "keyWords": [] },
    { "chinese": "a. 欢乐的；轻快的；merrily ad. 欢乐地；*meriment n. [U]欢乐", "english": "merry", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](常与a连用)凌乱状态；混乱局面；困境；vt. 弄脏；弄乱；messy a. 凌乱的；脏的(近in a mess肮脏；混乱)", "english": "mess", "type": "单词", "keyWords": [] },
    { "chinese": "(计划等事情)弄糟；把……弄得脏乱不堪", "english": "mess...up = make a mess of", "type": "短语", "keyWords": ["mess"] },
    { "chinese": "n. [C](口头、书面或用信号传达的)信息；消息，音信；留言；电报", "english": "message", "type": "单词", "keyWords": [] },
    { "chinese": "给某人带个信", "english": "give sb.a message", "type": "短语", "keyWords": ["message"] },
    { "chinese": "给某人留个信/条", "english": "leave a message for sb.", "type": "短语", "keyWords": ["message"] },
    { "chinese": "我能为你传个话吗？", "english": "Can I take a message for you?", "type": "句子", "keyWords": ["message"] },
    { "chinese": "n. [C]送信者；通信员", "english": "messenger", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]金属；metallic a. 金属(质)的；金属性的", "english": "metal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]米(公制长度单位)；measure the road by the metre以米为单位量路的长度", "english": "meter/mètre", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]测量仪表；计量器；an electric meter电表；a water meter水表", "english": "meter", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]方法；办法(系统的、有步骤的方法，侧重指做事方法的科学性、系统性)", "english": "method", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](U)地下铁道；地铁；travel on the metro/by metro乘地铁旅行", "english": "metro", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]扩音器；话筒", "english": "microphone", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]微波；a. 微波的；a microwave oven微波炉", "english": "microwave", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]中午；at midday在正午", "english": "midday", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]中间；中部；腰部；a. 中间的；middle-aged a. 中年的；middle class中产阶级；in the Middle East在中东；in the middle of...在……中间(近in the midst of, in the centre of)", "english": "middle", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]午夜；半夜；at midnight在午夜；after midnight午夜后", "english": "midnight", "type": "单词", "keyWords": [] },
    { "chinese": "v. (尤指)移居海外；迁移；(鸟等)迁往", "english": "*migrate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]候鸟；移栖动物；移居者；a. 迁移的；migrant workers外出务工人员", "english": "*migrant", "type": "单词", "keyWords": [] },
    { "chinese": "aux. 可以(表示许可或用于请求许可)；或许，可能(常用于肯定句、否定句中)；n. [U]力；力气；力量；*mighty a. 强大的；巨/浩大的；[口]非常的", "english": "might", "type": "单词", "keyWords": [] },
    { "chinese": "a. 和缓的；温和的；温暖的；*mildness n. [U]和缓；温和；温暖", "english": "mild", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]英里", "english": "mile", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]里程碑；a milestone in human history人类历史上划时代事件", "english": "milestone", "type": "单词", "keyWords": [] },
    { "chinese": "a. 军事的；军用的", "english": "military", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]牛奶；奶；v. 挤……的奶；*milky a. 乳白色的；乳状的；milk the cow挤母牛的奶；*the Milky Way银河系", "english": "milk", "type": "单词", "keyWords": [] },
    { "chinese": "对无法挽回的事哭也没用。", "english": "It's/There's no good/use crying over spilt milk.", "type": "句子", "keyWords": ["milk"] },
    { "chinese": "n. [C]磨坊；工场；工厂；a paper mill造纸厂", "english": "mill", "type": "单词", "keyWords": [] },
    { "chinese": "num. 百万；(pl.)许多；无数；数百万", "english": "million", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]百万富翁；大富翁", "english": "millionaire", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]理智；意向；头脑；具……头脑的人；vt./vi. 介意，反对；注意；留心", "english": "mind", "type": "单词", "keyWords": [] },
    { "chinese": "牢记某事", "english": "bear/keep sth. in mind (bear/keep in mind that...", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "想起", "english": "bring...back to mind = call...to mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "思想开放；愿意听取意见", "english": "have an open mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "浮现在某人的脑海中；想到", "english": "come into sb.'s mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "如释重负；搬掉某人心中的一块石头", "english": "take a load/weight off sb.'s mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "改变主意", "english": "change/alter one's mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "被忘却；发疯", "english": "go/be out of one's mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "看出……的心事", "english": "read one's mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "拿定主意做某事", "english": "make up one's mind to do sth.", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "当代有才智的人(们)", "english": "the great mind(s) of the time", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "在乎……", "english": "mind doing sth.", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "别管闲事", "english": "mind one's own business", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "请注意；你听着", "english": "mind you", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "要是你不反对/不介意", "english": "if you don't mind...", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "当心脚下。", "english": "Mind the step.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "记住我的话。", "english": "Mind what I say!", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "别担心；不要紧。", "english": "Never mind.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "健全的精神寓于强壮的体格。", "english": "A sound mind in a sound body.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "毕竟，健康身体加上健康头脑才是最好的状态。", "english": "After all, a sound mind in a sound body is the best state to be in.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "眼不见，心不想。离久情疏。", "english": "Out of sight, out of mind.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "英雄所见略同。", "english": "Great minds think alike.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "pron. 我的(所有物)", "english": "mine", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]矿(山)；矿井；地雷；v. 采(矿)；布雷；mining n. [U]采矿业；矿业；mine coal采煤；*lay mines布雷", "english": "mine", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]矿物；a. 矿物的", "english": "mineral", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]超短裙/衣服，迷你裙(=miniskirt)；小型的东西；a. (裙等)超短的；小型的", "english": "mini", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl.minima或minimums)最低量；最低限度；*a. 最低量的；最低(限度)的；*minimal a. 最小的；极小的；最低(限度)的", "english": "minimum", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](政府的)部；Ministry全体部长(或阁员)；全体牧师", "english": "ministry", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]牧师；部长；the Prime Minister首相；行政院长；总理", "english": "minister", "type": "单词", "keyWords": [] },
    { "chinese": "a. 较次要的；较小的，不严重的(反major)；a minor injury轻伤", "english": "minor", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]少数；少数民族；a minority of the...少数……；The minority is/are against...少数反对……", "english": "minority", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 减去；a. 负(的)；减的；零下的(反plus)；Seven minus four is three.七减四等于三。；minus twenty degrees Celsius摄氏零下二十度", "english": "minus", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]分钟；in a minute马上，立刻；just a minute稍等片刻；the minute/the moment/immediately/directly/instantly...一……就……", "english": "minute", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]奇迹；miraculous a. 令人惊奇的；神奇的；不可思议的", "english": "miracle", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]镜子；v. 反射；反映；映照；look in the mirror照镜子；mirror public opinion quite well充分地反映了公众的意见", "english": "mirror", "type": "单词", "keyWords": [] },
    { "chinese": "表示“错；误；失”，如：misspell拼写错误，misprint印刷错误，misunderstand误解，mislead误导，misuse错用", "english": "mis-", "type": "前缀", "keyWords": [] },
    { "chinese": "n. [C]印刷错误；v. 印刷错误", "english": "misprint", "type": "单词", "keyWords": [] } 
];
