const qgl173_180 = [
    { "chinese": "n.痛苦；悲惨的境遇；不幸；苦痛", "english": "misery", "type": "单词", "keyWords": [] },
    { "chinese": "a.痛苦的；悲惨的", "english": "miserable", "type": "单词", "keyWords": [] },
    { "chinese": "vt.错过；未赶上；缺（课等）；惦念；未击中；没抓住；没理解", "english": "miss", "type": "单词", "keyWords": [] },
    { "chinese": "失足", "english": "miss one's footing step", "type": "短语", "keyWords": ["miss"] },
    { "chinese": "错过某事", "english": "miss doing sth.", "type": "短语", "keyWords": ["miss"] },
    { "chinese": "不懂（俏皮话等的）妙处/要领", "english": "miss the point of sth.", "type": "短语", "keyWords": ["miss"] },
    { "chinese": "险些丧命", "english": "barely miss being killed", "type": "短语", "keyWords": ["miss"] },
    { "chinese": "房子在下一个拐角处。你不会看不到的。", "english": "The house is at the next corner. You can't miss it.", "type": "句子", "keyWords": ["miss"] },
    { "chinese": "n.小姐（用于对未婚妇女的称呼）", "english": "Miss", "type": "单词", "keyWords": [] },
    { "chinese": "a.失踪的；（页、单词等）缺掉的", "english": "missing", "type": "单词", "keyWords": [] },
    { "chinese": "n.（外交）使团；使命；任务；[美]使馆", "english": "mission", "type": "单词", "keyWords": [] },
    { "chinese": "执行秘密使命", "english": "carry out a secret mission", "type": "短语", "keyWords": ["mission"] },
    { "chinese": "被带有使命派出去", "english": "be sent on a mission", "type": "短语", "keyWords": ["mission"] },
    { "chinese": "n.（由于有缺陷的判断、知识不足或粗心造成的）错误；vt.弄错；把…错认；误解", "english": "mistake", "type": "单词", "keyWords": [] },
    { "chinese": "犯错误，做错；想错，误解", "english": "make a mistake (about sth.)", "type": "短语", "keyWords": ["mistake"] },
    { "chinese": "错误地", "english": "by mistake", "type": "短语", "keyWords": ["mistake"] },
    { "chinese": "我错拿了你的手提包，还以为是我的呢。", "english": "I took your bag instead of mine by mistake.", "type": "句子", "keyWords": ["mistake"] },
    { "chinese": "把…误认为…", "english": "mistake...for...", "type": "短语", "keyWords": ["mistake"] },
    { "chinese": "他把那根棍子错看成蛇了。", "english": "He mistook that stick for a snake.", "type": "句子", "keyWords": ["mistake"] },
    { "chinese": "误解；误会", "english": "be mistaken about sth./ sb.", "type": "短语", "keyWords": ["mistake"] },
    { "chinese": "你弄错了。", "english": "You are mistaken.", "type": "句子", "keyWords": ["mistake"] },
    { "chinese": "n.先生", "english": "mister", "type": "单词", "keyWords": [] },
    { "chinese": "n.主妇；女主人", "english": "mistress", "type": "单词", "keyWords": [] },
    { "chinese": "vt.误解；误会", "english": "misunderstand", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（U]误解；误会；分歧；曲解", "english": "misunderstanding", "type": "单词", "keyWords": [] },
    { "chinese": "vt.使混合；拌和；（with）", "english": "mix", "type": "单词", "keyWords": [] },
    { "chinese": "a.混合的，混杂的", "english": "mixed", "type": "单词", "keyWords": [] },
    { "chinese": "男女同学的学校", "english": "a mixed school", "type": "短语", "keyWords": ["mixed"] },
    { "chinese": "把…与…混合（be mixed with...与…混合）", "english": "mix sth. with sth.", "type": "短语", "keyWords": ["mix"] },
    { "chinese": "使弄不清；使混乱", "english": "mix...up", "type": "短语", "keyWords": ["mix"] },
    { "chinese": "悲（惊）喜交集", "english": "have mixed feelings", "type": "短语", "keyWords": ["mixed"] },
    { "chinese": "n.[U]混合，拌和；混合状态；n.[C]混合物；混合剂", "english": "mixture", "type": "单词", "keyWords": [] },
    { "chinese": "a.（用车拖载）流动的，机动的；活动的；可动的；n.[C][口]汽车（=automobile）", "english": "mobile", "type": "单词", "keyWords": [] },
    { "chinese": "流动图书馆", "english": "a mobile library", "type": "短语", "keyWords": ["mobile"] },
    { "chinese": "巡回医疗队", "english": "a mobile medical team", "type": "短语", "keyWords": ["mobile"] },
    { "chinese": "n.[C]方法；方式；形式；（服饰等的）式样；风尚；（电子设备或相机等的）模式，状态", "english": "mode", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]模型；典范；型；模特儿；a.模型的；模范的", "english": "model", "type": "单词", "keyWords": [] },
    { "chinese": "a.有节制的；中等的；适度的；温和的；（价格）公道的；花费不多的", "english": "moderate", "type": "单词", "keyWords": [] },
    { "chinese": "饮酒适量", "english": "be moderate in drinking", "type": "短语", "keyWords": ["moderate"] },
    { "chinese": "公道的价格", "english": "moderate prices", "type": "短语", "keyWords": ["moderate"] },
    { "chinese": "中等的收入", "english": "a moderate income", "type": "短语", "keyWords": ["moderate"] },
    { "chinese": "以中等速度", "english": "at a moderate speed", "type": "短语", "keyWords": ["moderate"] },
    { "chinese": "a.现代的；现代化的", "english": "modern", "type": "单词", "keyWords": [] },
    { "chinese": "v.（使）现代化", "english": "modernize", "type": "单词", "keyWords": [] },
    { "chinese": "a.现代化的", "english": "modernized", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（U）现代化", "english": "modernization", "type": "单词", "keyWords": [] },
    { "chinese": "四个现代化", "english": "four modernizations", "type": "短语", "keyWords": ["modernization"] },
    { "chinese": "a.谦虚的（about sth.）", "english": "modest", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]谦虚", "english": "modesty", "type": "单词", "keyWords": [] },
    { "chinese": "vt.修改；[语]修饰", "english": "modify", "type": "单词", "keyWords": [] },
    { "chinese": "a.润湿的，潮湿的；多雨的", "english": "moist", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]湿气；水分；潮湿；湿度", "english": "moisture", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]片刻；瞬间；a.瞬息间的，片刻的；暂时的", "english": "moment", "type": "单词", "keyWords": [] },
    { "chinese": "一……就……", "english": "the moment；the minute", "type": "短语", "keyWords": ["moment", "minute"] },
    { "chinese": "马上；立刻", "english": "in a moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "随时，无论什么时候", "english": "at any moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "暂时；目前", "english": "for the moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "此刻，目前；那时，当时", "english": "at the moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "片刻，一会儿", "english": "for a moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "刻不容缓。", "english": "There is not a moment to be lost.", "type": "句子", "keyWords": ["moment"] },
    { "chinese": "n.[C]（U）星期一（略作Mon.）", "english": "Monday", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]钱；货币；a.货币的", "english": "money", "type": "单词", "keyWords": [] },
    { "chinese": "赚钱", "english": "make money", "type": "短语", "keyWords": ["money"] },
    { "chinese": "集资", "english": "raise/collect money", "type": "短语", "keyWords": ["money"] },
    { "chinese": "纸币", "english": "paper money", "type": "短语", "keyWords": ["money"] },
    { "chinese": "赚钱的", "english": "moneymaking", "type": "单词", "keyWords": ["money"] },
    { "chinese": "放贷者", "english": "moneylender", "type": "单词", "keyWords": ["money"] },
    { "chinese": "省钱的", "english": "moneysaving", "type": "单词", "keyWords": ["money"] },
    { "chinese": "金钱万能。", "english": "Money talks.", "type": "句子", "keyWords": ["money"] },
    { "chinese": "金钱是罪恶之源。", "english": "Money is the root of all evil.", "type": "句子", "keyWords": ["money"] },
    { "chinese": "n.[C]班长；监视器；[计]显示器；vt.监控；监测；监视，密切注视", "english": "monitor", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]猴子", "english": "monkey", "type": "单词", "keyWords": [] },
    { "chinese": "a.每月的；每月一次的；按月的；ad.每月一次；每月；按月；n.[C]月刊", "english": "monthly", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]纪念碑（to）（近a memorial to sb.）", "english": "monument", "type": "单词", "keyWords": [] },
    { "chinese": "亡者纪念碑", "english": "a monument to the dead", "type": "短语", "keyWords": ["monument"] },
    { "chinese": "人民英雄纪念碑", "english": "the Monument to the People's Heroes", "type": "短语", "keyWords": ["monument"] },
    { "chinese": "n.[C]心情；情绪；a.脾气不好的；喜怒无常的", "english": "mood", "type": "单词", "keyWords": [] },
    { "chinese": "心情好/坏", "english": "in a good/bright/bad mood", "type": "短语", "keyWords": ["mood"] },
    { "chinese": "(没)有心情做某事", "english": "be in no/in the mood for (doing sth./to do sth.)", "type": "短语", "keyWords": ["mood"] },
    { "chinese": "n.[C]月亮；月球", "english": "moon", "type": "单词", "keyWords": [] },
    { "chinese": "一轮弦/满/新月", "english": "a crescent/full/new moon", "type": "短语", "keyWords": ["moon"] },
    { "chinese": "在一个没月光的晚上", "english": "on a moonless night", "type": "短语", "keyWords": ["moon"] },
    { "chinese": "n.[U]月光；在月光下", "english": "moonlight", "type": "单词", "keyWords": [] },
    { "chinese": "vt.用拖把拖洗；vi.用拖把拖地", "english": "mop", "type": "单词", "keyWords": [] },
    { "chinese": "a.道德上的；有道德的；a.没有道德的；n.[U]道德（规范）", "english": "moral", "type": "单词", "keyWords": [] },
    { "chinese": "过着合乎道德的生活", "english": "lead a moral life", "type": "短语", "keyWords": ["moral"] },
    { "chinese": "道德教训", "english": "a moral lesson", "type": "短语", "keyWords": ["moral"] },
    { "chinese": "道德标准", "english": "moral standards", "type": "短语", "keyWords": ["moral"] },
    { "chinese": "商业道德", "english": "commercial morality", "type": "短语", "keyWords": ["moral"] },
    { "chinese": "a.更多的，较多的（many，much的比较级）；附加的；ad.更（用于构成形容词或副词比较级）；更多地，更大程度地（much的比较级）；pron.更多的量", "english": "more", "type": "单词", "keyWords": [] },
    { "chinese": "比起玛丽来他更该受责备。", "english": "He is more to blame than Mary.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "越来越……", "english": "more and more (beautiful/interesting)", "type": "短语", "keyWords": ["more"] },
    { "chinese": "①差不多；几乎；②或多或少；大约", "english": "more or less", "type": "短语", "keyWords": ["more"] },
    { "chinese": "我们的说明会或多或少有些帮助。", "english": "Our explanation will prove more or less helpful.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "我猜他和这件事或多或少有点牵连。", "english": "I suspect that he is more or less involved in the affair.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "越……越……", "english": "the more...，the more...", "type": "短语", "keyWords": ["more"] },
    { "chinese": "他越讲越不着边际。", "english": "The more he talked，the further he strayed from the point.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "离岸越远，视野越宽。", "english": "The further away I am off shore，the more far-sighted I will be.=I will be more far-sighted，the further away I am off shore.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "超过，多于；非常；不仅仅是", "english": "more than", "type": "短语", "keyWords": ["more"] },
    { "chinese": "非常乐意做某事", "english": "be more than happy/glad/willing to do sth.", "type": "短语", "keyWords": ["more"] },
    { "chinese": "冬眠不仅仅是睡眠，而是一种沉睡。", "english": "Hibernation is more than sleep.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "与其说……不如说……；而不是……", "english": "more...than...", "type": "短语", "keyWords": ["more"] },
    { "chinese": "与其说我气恼倒不如说受惊不小。", "english": "I was more surprised than annoyed.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "他有勇无谋。", "english": "He is more brave than wise.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "不再（近not any more）", "english": "no more", "type": "短语", "keyWords": ["more"] },
    { "chinese": "不再听到响声了。", "english": "No more sound was heard.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "只有，只不过是；也不，和……一样不", "english": "no more(..than)", "type": "短语", "keyWords": ["more"] },
    { "chinese": "我的房子跟棚子差不多。", "english": "My house is no more than a shelter.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "他和我一样不称职。", "english": "He is no more fit than I am.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "正如马不是鱼一样，鲸也不是鱼。", "english": "A whale is no more a fish than a horse is.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "另外；更重要的是（近besides）", "english": "(and) what is more", "type": "短语", "keyWords": ["more"] },
    { "chinese": "ad.而且；此外", "english": "moreover", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]早晨", "english": "morning", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]蚊子", "english": "mosquito", "type": "单词", "keyWords": [] },
    { "chinese": "a.最多的（many和much的最高级）；大多数的，大部分的；ad.最（much的最高级；用于构成最高级）；最大程度上；pron.大多数；大部分；最大量", "english": "most", "type": "单词", "keyWords": [] },
    { "chinese": "大部分时间", "english": "most of the time/day", "type": "短语", "keyWords": ["most"] },
    { "chinese": "至多", "english": "at (the) most", "type": "短语", "keyWords": ["most"] },
    { "chinese": "一般说来，大部分", "english": "for the most part", "type": "短语", "keyWords": ["most"] },
    { "chinese": "充分利用", "english": "make the most of", "type": "短语", "keyWords": ["most"] },
    { "chinese": "一篇给人印象很深的文章", "english": "a most impressive piece of writing", "type": "短语", "keyWords": ["most"] },
    { "chinese": "ad.主要地；几乎全部地，大部分（比较most ad.最；最大程度上）", "english": "mostly", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]汽车旅馆", "english": "motel", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]蛾", "english": "moth", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]母亲；a.母亲般的；慈母般的；慈祥的", "english": "mother", "type": "单词", "keyWords": [] },
    { "chinese": "母语", "english": "mother tongue", "type": "短语", "keyWords": ["mother"] },
    { "chinese": "婆母；岳母", "english": "mother(s)-in-law", "type": "单词", "keyWords": ["mother"] },
    { "chinese": "孕妇；准妈妈", "english": "mother(s)-to-be", "type": "单词", "keyWords": ["mother"] },
    { "chinese": "失败是成功之母。", "english": "Failure is the mother of success.", "type": "句子", "keyWords": ["mother"] },
    { "chinese": "n.[U]（移）动；运动（与“静止”相对）；n.[C]示意动作；动议，提议；v.（向…）做手势；（向…）点（或摇）头示意；a.静止不动的", "english": "motion", "type": "单词", "keyWords": [] },
    { "chinese": "电影", "english": "motion picture", "type": "短语", "keyWords": ["motion"] },
    { "chinese": "用手示意；提议，动议", "english": "make a motion", "type": "短语", "keyWords": ["motion"] },
    { "chinese": "在开动中，在运转中", "english": "in motion", "type": "短语", "keyWords": ["motion"] },
    { "chinese": "汽车行驶的时候千万不能下车。", "english": "You must not get out of the car when it is in motion.", "type": "句子", "keyWords": ["motion"] },
    { "chinese": "vt.使产生动机；激起行动；激发…的积极性；促使；n.[C]动机", "english": "motivate", "type": "单词", "keyWords": [] },
    { "chinese": "调动某人做某事的积极性", "english": "motivate sb. to do sth.", "type": "短语", "keyWords": ["motivate"] },
    { "chinese": "杀人动机", "english": "a motive for the murder", "type": "短语", "keyWords": ["motive"] },
    { "chinese": "n.[C]电动机，马达；汽车；高速公路", "english": "motor", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]摩托车（=motorbike）；n.[C]骑摩托车的人", "english": "motorcycle", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]座右铭，格言", "english": "motto", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]山；峰；vt.爬上；使上马", "english": "mount", "type": "单词", "keyWords": [] },
    { "chinese": "峨眉山", "english": "Mount Emei", "type": "短语", "keyWords": ["mount"] },
    { "chinese": "骑警", "english": "mounted police", "type": "短语", "keyWords": ["mount"] },
    { "chinese": "n.[C]山；a.有山的；多山的；n.[C]登山运动员；vi.登山；n.[U]登山运动", "english": "mountain", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（pl.mice）老鼠；（计算机）鼠标", "english": "mouse", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]口，嘴；n.[C]一口，满口", "english": "mouth", "type": "单词", "keyWords": [] },
    { "chinese": "保持缄默", "english": "keep one's mouth shut", "type": "短语", "keyWords": ["mouth"] },
    { "chinese": "在河口处", "english": "at the river mouth", "type": "短语", "keyWords": ["mouth"] },
    { "chinese": "吃了一口食物", "english": "take a mouthful of food", "type": "短语", "keyWords": ["mouth"] },
    { "chinese": "勉强糊口；勉强过活", "english": "live from hand to mouth", "type": "短语", "keyWords": ["mouth"] },
    { "chinese": "消息通过口头流传。", "english": "The news got round by word of mouth.", "type": "句子", "keyWords": ["mouth"] },
    { "chinese": "vt.移动；搬家；运转；vi.移动；搬（家）；开动（机器）；使感动（辨析见affect）；n.[C]动；移动（指位置的变化）；搬（家）；a.感人的；动人的；a.被感动了的；a.可移动的，活动的", "english": "move", "type": "单词", "keyWords": [] },
    { "chinese": "走一步；搬家；开始行动", "english": "make a move", "type": "短语", "keyWords": ["move"] },
    { "chinese": "在忙碌", "english": "on the move/go", "type": "短语", "keyWords": ["move"] },
    { "chinese": "n.[C]运动；活动（侧重指具体的动作，也可指政治运动）", "english": "movement", "type": "单词", "keyWords": [] },
    { "chinese": "(美)民权运动", "english": "Civil Rights Movement", "type": "短语", "keyWords": ["movement"] },
    { "chinese": "民族解放运动", "english": "national liberation movement", "type": "短语", "keyWords": ["movement"] },
    { "chinese": "n.[C]电影", "english": "movie", "type": "单词", "keyWords": [] },
    { "chinese": "去看电影", "english": "go to the movies", "type": "短语", "keyWords": ["movie"] },
    { "chinese": "制片者", "english": "moviemaker", "type": "单词", "keyWords": ["movie"] },
    { "chinese": "常看电影的人", "english": "movie-goer", "type": "单词", "keyWords": ["movie"] },
    { "chinese": "vt.割（草、麦等）", "english": "mow", "type": "单词", "keyWords": [] },
    { "chinese": "割草坪", "english": "mow the lawn", "type": "短语", "keyWords": ["mow"] },
    { "chinese": "割草的人；割草机", "english": "(lawn) mower", "type": "单词", "keyWords": ["mow"] },
    { "chinese": "每小时英里数（=miles per hour）", "english": "m.p.h.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]先生（用于男子姓、姓名前）", "english": "Mr/Mr./'msta/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]夫人（用于已婚妇女姓名前）", "english": "Mrs/Mrs./msiz/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]女士（用于婚姻状况不明或不愿提及婚姻状况的女子姓、姓名前）", "english": "Ms/Ms./mrz/", "type": "单词", "keyWords": [] },
    { "chinese": "a.许多的；大量的；ad.非常，很多；更加；pron.许多；大量", "english": "much", "type": "单词", "keyWords": [] },
    { "chinese": "程度高；频率高（常用于否定句或疑问句中）", "english": "much of", "type": "短语", "keyWords": ["much"] },
    { "chinese": "他不是什么了不起的学者。", "english": "He isn't much of a scholar.", "type": "句子", "keyWords": ["much"] },
    { "chinese": "我不大见到他。", "english": "I don't see much of him.", "type": "句子", "keyWords": ["much"] },
    { "chinese": "同样多；同样程度", "english": "as much", "type": "短语", "keyWords": ["much"] },
    { "chinese": "几乎一样", "english": "much the same", "type": "短语", "keyWords": ["much"] },
    { "chinese": "太甜了", "english": "be much too sweet", "type": "短语", "keyWords": ["much"] },
    { "chinese": "这/那么多，这/那么些", "english": "this/that much", "type": "短语", "keyWords": ["much"] },
    { "chinese": "非力所能及；干不了；受不了，应付不了；过分了", "english": "This is too much for me.[俗]", "type": "句子", "keyWords": ["much"] },
    { "chinese": "就说这么多。", "english": "So much for today/the story.", "type": "句子", "keyWords": ["much"] },
    { "chinese": "n.[U]泥；泥浆；a.泥泞的", "english": "mud", "type": "单词", "keyWords": [] },
    { "chinese": "表示“多，一个以上”", "english": "multi-", "type": "单词", "keyWords": [] },
    { "chinese": "a.多个（或多种、多部分等）的；许多的；n.[C]倍数", "english": "multiple", "type": "单词", "keyWords": [] },
    { "chinese": "多项选择的", "english": "multiple-choice", "type": "单词", "keyWords": ["multiple"] },
    { "chinese": "多项选择问题", "english": "a multiple-choice question", "type": "短语", "keyWords": ["multiple"] },
    { "chinese": "多元文化共存", "english": "coexistence of multiple cultures", "type": "短语", "keyWords": ["multiple"] },
    { "chinese": "7乘以5等于35，所以35是7的倍数。", "english": "7x5 = 35, so 35 is a multiple of 7.", "type": "句子", "keyWords": ["multiple"] },
    { "chinese": "vt.乘；使相乘；vi.做乘法；增多", "english": "multiply", "type": "单词", "keyWords": [] },
    { "chinese": "以3乘5", "english": "multiply five by three", "type": "短语", "keyWords": ["multiply"] },
    { "chinese": "5乘以3等于15。", "english": "5 multiplied by 3 is 15.", "type": "句子", "keyWords": ["multiply"] },
    { "chinese": "n.[C]妈妈；n.[C][儿语]妈咪，[口]妈妈；n.[C]木乃伊，干瘪的人", "english": "mum/mummy", "type": "单词", "keyWords": [] },
    { "chinese": "vt./n.[C][U]谋杀", "english": "murder", "type": "单词", "keyWords": [] },
    { "chinese": "杀人犯，凶手", "english": "murderer", "type": "单词", "keyWords": ["murder"] },
    { "chinese": "凶杀案", "english": "a case of murder", "type": "短语", "keyWords": ["murder"] },
    { "chinese": "vt.喃喃地说；咕哝；嘀咕", "english": "murmur", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]肌肉；n.[U]体力", "english": "muscle", "type": "单词", "keyWords": [] },
    { "chinese": "a.肌肉的；肌肉发达的；强健的", "english": "muscular", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]博物馆", "english": "museum", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]蘑菇", "english": "mushroom", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]音乐；勇于承担责任；临危不惧", "english": "music", "type": "单词", "keyWords": [] },
    { "chinese": "a.音乐的；和谐的；悦耳的；n.[C]音乐片；音乐舞台剧", "english": "musical", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]音乐家；作曲家；乐师", "english": "musician", "type": "单词", "keyWords": [] },
    { "chinese": "aux.v.（指义务、命令）必须；一定，肯定（只用于肯定推测）；偏要，硬要；n.[C]必须做的事", "english": "must", "type": "单词", "keyWords": [] },
    { "chinese": "詹姆森夫人的流感一定是完全好了，因为昨天我看见她外出了。", "english": "Mrs. Jameson must have got over her flu, for I saw her go out yesterday.", "type": "句子", "keyWords": ["must"] },
    { "chinese": "为什么你偏要这么固执？", "english": "Why must you be so stubborn?", "type": "句子", "keyWords": ["must"] },
    { "chinese": "住山里必须备有保暖衣服。", "english": "Warm clothes are a must in the mountains.", "type": "句子", "keyWords": ["must"] },
    { "chinese": "a.哑的；不说话的；静音的", "english": "mute", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]羊肉", "english": "mutton", "type": "单词", "keyWords": [] },
    { "chinese": "a.互相的", "english": "mutual", "type": "单词", "keyWords": [] },
    { "chinese": "相互间的尊敬", "english": "mutual respect", "type": "短语", "keyWords": ["mutual"] },
    { "chinese": "互相谅解", "english": "mutual understanding", "type": "短语", "keyWords": ["mutual"] },
    { "chinese": "a.神秘的；难以理解的", "english": "mysterious", "type": "单词", "keyWords": [] },
    { "chinese": "神秘的符号", "english": "mysterious symbols", "type": "短语", "keyWords": ["mysterious"] },
    { "chinese": "n.[C]神秘的事物；难以理解的事物；n.[U]奥秘；神秘性", "english": "mystery", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]神话；谎言；虚构的观点或理论等", "english": "myth", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]钉子；指甲；vt.钉；使固定", "english": "nail", "type": "单词", "keyWords": [] },
    { "chinese": "a.天真的", "english": "naive", "type": "单词", "keyWords": [] },
    { "chinese": "幼稚的话", "english": "a naive remark", "type": "短语", "keyWords": ["naive"] },
    { "chinese": "天真的女孩", "english": "a naive girl", "type": "短语", "keyWords": ["naive"] },
    { "chinese": "a.裸体的；无遮盖的", "english": "naked", "type": "单词", "keyWords": [] },
    { "chinese": "肉眼能看见", "english": "be visible to the naked eye", "type": "短语", "keyWords": ["naked"] },
    { "chinese": "n.[C]姓名；名义；名声；vt.给…取名字，为…命名；列举；说出某物的名称", "english": "name", "type": "单词", "keyWords": [] },
    { "chinese": "坏名声", "english": "a bad/an ill name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "笔名", "english": "a pen name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "姓", "english": "a family name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "一个叫汤姆的男子", "english": "a man named Tom/ by the name of Tom", "type": "短语", "keyWords": ["name"] },
    { "chinese": "以…的名义，代表（近on behalf of）；凭…的权威", "english": "in the name of", "type": "短语", "keyWords": ["name"] },
    { "chinese": "（表惊奇感叹语）上帝啊！（起誓用语）上帝作证，苍天在上", "english": "in the name of God", "type": "短语", "keyWords": ["name"] },
    { "chinese": "我代表她家人发言。", "english": "I speak in the name of her family.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "凭借法律的权威", "english": "in the name of the law", "type": "短语", "keyWords": ["name"] },
    { "chinese": "出名，成名", "english": "make a name for oneself", "type": "短语", "keyWords": ["name"] },
    { "chinese": "他以交响乐钢琴演奏家成名。", "english": "He made a name for himself as a concert pianist.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "以…名字；以…为笔名", "english": "under the name of...", "type": "短语", "keyWords": ["name"] },
    { "chinese": "他以真名发表了他的新作。", "english": "He published his new book under his real name.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "（以别人、别物的名字）命名", "english": "name...after/for...", "type": "短语", "keyWords": ["name"] },
    { "chinese": "这孩子取名于他祖父母的名字。", "english": "The child was named after both his grandparents.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "名叫；只在名字上", "english": "by name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "我在那里碰到了一个名叫约翰的警察。", "english": "I met a policeman there, John by name.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "仅仅知道某人的名字（没有见过面）", "english": "know sb. by name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "您尊姓大名？", "english": "May I ask/have your name?", "type": "句子", "keyWords": ["name"] },
    { "chinese": "骂某人", "english": "call sb. names", "type": "短语", "keyWords": ["name"] },
    { "chinese": "他们有毒品问题、酗酒问题、枪支问题--应有尽有（你能想得到的/你能说得出的，他们都有）。", "english": "They've had drug problems, alcohol problems, gun problems - you name it, they've got it.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "美名难得而易失。", "english": "A good name is sooner lost than won.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "ad.即，也就是（=that is to say）", "english": "namely", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]/vi.小睡", "english": "nap", "type": "单词", "keyWords": [] },
    { "chinese": "打个盹儿", "english": "take/have a nap", "type": "短语", "keyWords": ["nap"] },
    { "chinese": "n.[C]餐巾；小毛巾；[英]尿布", "english": "napkin", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]水仙花", "english": "narcissus", "type": "单词", "keyWords": [] },
    { "chinese": "vt.叙述，讲述；a.叙述性的；n.[C]讲述者，叙述者", "english": "narrate", "type": "单词", "keyWords": [] },
    { "chinese": "a.狭窄的；有局限的；狭隘的；勉强的；v.（使）变窄；（使）变狭隘；（使）有局限；（使）缩小；n.[U]狭窄，狭小；偏狭，气量小；ad.狭窄地；仅仅，勉强；a.气量小的，小心眼的", "english": "narrow", "type": "单词", "keyWords": [] },
    { "chinese": "在狭义上", "english": "in a narrow sense", "type": "短语", "keyWords": ["narrow"] },
    { "chinese": "勉强逃脱；九死一生", "english": "a narrow escape", "type": "短语", "keyWords": ["narrow"] },
    { "chinese": "他们把可能性减至三个。", "english": "They narrowed the possibilities down to three.", "type": "句子", "keyWords": ["narrow"] },
    { "chinese": "居住在偏僻的乡下使他眼光变窄了。", "english": "Living in the remote countryside has narrowed him.", "type": "句子", "keyWords": ["narrow"] },
    { "chinese": "差一点被淹死", "english": "narrowly escape being drowned", "type": "短语", "keyWords": ["narrow"] },
    { "chinese": "a.污秽的，肮脏的；引人作呕的；令人厌恶的", "english": "nasty", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]国家；民族；a.全国性的；在全国范围内的", "english": "nation", "type": "单词", "keyWords": [] },
    { "chinese": "a.国家的；国民的；民族的", "english": "national", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]民族；国籍", "english": "nationality", "type": "单词", "keyWords": [] },
    { "chinese": "a.本土的；本国的；出生地的；土产的；土著的；n.[C]本地人；本国人", "english": "native", "type": "单词", "keyWords": [] },
    { "chinese": "某人的母语", "english": "one's native language", "type": "短语", "keyWords": ["native"] },
    { "chinese": "北京本地人", "english": "a native of Beijing", "type": "短语", "keyWords": ["native"] },
    { "chinese": "原产于", "english": "be native to", "type": "短语", "keyWords": ["native"] },
    { "chinese": "亚洲原产的植物", "english": "a plant native to Asia", "type": "短语", "keyWords": ["native"] },
    { "chinese": "香蕉是台湾的土（特）产。", "english": "Banana is native to Taiwan.", "type": "句子", "keyWords": ["native"] },
    { "chinese": "a.自然界的；自然的；合乎自然规律的；ad.自然地", "english": "natural", "type": "单词", "keyWords": [] },
    { "chinese": "……是自然的/天生的/人之常情", "english": "It's natural that...(should) do...; It's natural for sb. to do sth.", "type": "短语", "keyWords": ["natural"] },
    { "chinese": "n.[C]博物学家；自然主义者", "english": "naturalist", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]大自然，自然界；自然状态；本性，天性", "english": "nature", "type": "单词", "keyWords": [] },
    { "chinese": "在自然界；实际上，事实上", "english": "in nature", "type": "短语", "keyWords": ["nature"] },
    { "chinese": "心地善良/不良的", "english": "good/ill-natured", "type": "单词", "keyWords": ["nature"] },
    { "chinese": "违反自然/人性；不自然地", "english": "against nature", "type": "短语", "keyWords": ["nature"] },
    { "chinese": "天生地；天性地", "english": "by nature", "type": "短语", "keyWords": ["nature"] },
    { "chinese": "a.顽皮的；不听话的；n.[U]顽皮，不听话", "english": "naughty", "type": "单词", "keyWords": [] },
    { "chinese": "a.海军的", "english": "naval", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]海军", "english": "navy", "type": "单词", "keyWords": [] },
    { "chinese": "参加海军", "english": "join the navy", "type": "短语", "keyWords": ["navy"] },
    { "chinese": "prep.在…附近；a.近的；靠近的，接近的；在附近的；ad.近；在附近", "english": "near", "type": "单词", "keyWords": [] },
    { "chinese": "差点丧命", "english": "near/close to killing himself", "type": "短语", "keyWords": ["near"] },
    { "chinese": "靠近", "english": "be near to", "type": "短语", "keyWords": ["near"] },
    { "chinese": "到处（近here and there）", "english": "far and near", "type": "短语", "keyWords": ["near"] },
    { "chinese": "近亲", "english": "a near relative", "type": "短语", "keyWords": ["near"] },
    { "chinese": "a.附近的；邻近的；ad.在附近；prep.在…附近", "english": "nearby", "type": "单词", "keyWords": [] },
    { "chinese": "在附近的商场里", "english": "in the mall nearby/in the nearby mall", "type": "短语", "keyWords": ["nearby"] },
    { "chinese": "ad.几乎；差不多", "english": "nearly", "type": "单词", "keyWords": [] },
    { "chinese": "绝不，相差甚远，远非", "english": "not nearly", "type": "短语", "keyWords": ["nearly"] },
    { "chinese": "远不及以前漂亮。", "english": "It is not nearly so pretty as it was before.", "type": "句子", "keyWords": ["nearly"] },
    { "chinese": "a.整洁的；简洁的；n.[U]整洁；简洁", "english": "neat", "type": "单词", "keyWords": [] },
    { "chinese": "a.必要的；必需的；ad.必要地；必需地，不可避免地", "english": "necessary", "type": "单词", "keyWords": [] },
    { "chinese": "不一定（如此）", "english": "not necessarily(so)", "type": "短语", "keyWords": ["necessary"] },
    { "chinese": "你不一定要出席。", "english": "You don't necessarily have to attend it.", "type": "句子", "keyWords": ["necessary"] },
    { "chinese": "……是必要的", "english": "It is necessary that...(should) do...; It is necessary for sb. to do sth.", "type": "短语", "keyWords": ["necessary"] },
    { "chinese": "如果有必要", "english": "(it is)necessary", "type": "短语", "keyWords": ["necessary"] },
    { "chinese": "n.[U]必要性；需要；n.[C]必需品", "english": "necessity", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]颈；脖子；n.[C]项链；项圈", "english": "neck", "type": "单词", "keyWords": [] },
    { "chinese": "aux.v.必要，必须；必定（用于疑问句和否定句）；v.需要；须要，一定要；n.[C]（U）需要（物）；必要；缺乏，欠缺；a.不需要的，不必要的", "english": "need", "type": "单词", "keyWords": [] },
    { "chinese": "本不必做某事（做了不必做的事）", "english": "needn't have done sth.", "type": "短语", "keyWords": ["need"] },
    { "chinese": "非常需要某物", "english": "need sth. badly", "type": "短语", "keyWords": ["need"] },
    { "chinese": "需要修理（近want，require，deserve）", "english": "need mending=need to be mended=need repairs(n.)", "type": "短语", "keyWords": ["need"] },
    { "chinese": "满足某人的需要", "english": "satisfy/meet/answer one's needs", "type": "短语", "keyWords": ["need"] },
    { "chinese": "需要/不需要某物/做某事", "english": "there is a great need/no need for sth./to do sth.", "type": "短语", "keyWords": ["need"] },
    { "chinese": "不用着急。", "english": "There is no need for hurrying.=There is no need to hurry.", "type": "句子", "keyWords": ["need"] },
    { "chinese": "没必要担忧。", "english": "There's no need to be concerned.", "type": "句子", "keyWords": ["need"] },
    { "chinese": "需要", "english": "be in need/demand (of sth./sb.)", "type": "短语", "keyWords": ["need"] },
    { "chinese": "患难之交才是真正的朋友。", "english": "A friend in need is a friend indeed.", "type": "句子", "keyWords": ["need"] },
    { "chinese": "不用说，他又像往常一样迟到了。", "english": "Needless to say, he came late as usual.", "type": "句子", "keyWords": ["need"] },
    { "chinese": "n.[C]针；缝衣针", "english": "needle", "type": "单词", "keyWords": [] },
    { "chinese": "针和线", "english": "a needle and thread", "type": "短语", "keyWords": ["needle"] },
    { "chinese": "n.[U]缝纫活", "english": "needlework", "type": "单词", "keyWords": ["needle"] },
    { "chinese": "a.否定的；消极的；负的；反的；反面的，负面的（反positive）", "english": "negative", "type": "单词", "keyWords": [] },
    { "chinese": "vt./n.[U]疏忽；忽略（一般指因粗心等原因而没有重视）", "english": "neglect", "type": "单词", "keyWords": [] },
    { "chinese": "忘了锁门", "english": "neglect to lock the door=neglect locking the door", "type": "短语", "keyWords": ["neglect"] },
    { "chinese": "玩忽职守", "english": "neglect one's duty", "type": "短语", "keyWords": ["neglect"] },
    { "chinese": "疏于职守", "english": "the neglect of duty", "type": "短语", "keyWords": ["neglect"] },
    { "chinese": "vt.谈判；协商；洽谈（with sb. about sth.）；vi.商定；通过谈判达成或解决", "english": "negotiate", "type": "单词", "keyWords": [] },
    { "chinese": "协商合同", "english": "negotiate a contract", "type": "短语", "keyWords": ["negotiate"] },
    { "chinese": "n.[C](U]谈判；协商", "english": "negotiation", "type": "单词", "keyWords": ["negotiate"] },
    { "chinese": "n.[C](Negroes)黑人（目前带有贬义，一般用black）；a.黑（种）人的", "english": "Negro", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]邻居；紧挨着；a.附近的，毗邻的", "english": "neighbo(ur)", "type": "单词", "keyWords": [] },
    { "chinese": "隔壁邻居", "english": "next-door neighbours", "type": "短语", "keyWords": ["neighbo(ur)"] },
    { "chinese": "邻村/邻国", "english": "neighbouring villages/countries", "type": "短语", "keyWords": ["neighbo(ur)"] },
    { "chinese": "n.[C]邻近地区；街坊；住宅区，居民点", "english": "neighbourhood", "type": "单词", "keyWords": ["neighbo(ur)"] },
    { "chinese": "在……附近", "english": "in the neighbourhood (of...)", "type": "短语", "keyWords": ["neighbourhood"] },
    { "chinese": "a.两者都不；pron.两者中的无一个；ad.也不", "english": "neither", "type": "单词", "keyWords": [] },
    { "chinese": "双方都不", "english": "neither side is...；neither of the two sides is...；neither is...", "type": "短语", "keyWords": ["neither"] },
    { "chinese": "既不……也不……", "english": "neither...nor...", "type": "短语", "keyWords": ["neither"] },
    { "chinese": "你，我，其他任何人都不知道答案。", "english": "Neither you nor I, nor anybody else knows the answer.", "type": "句子", "keyWords": ["neither"] },
    { "chinese": "理论没有实践不行，实践没有理论也不行。", "english": "Neither could theory do without practice, nor could practice do without theory.", "type": "句子", "keyWords": ["neither"] },
    { "chinese": "n.[C]侄子；外甥", "english": "nephew", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]神经；(pl.)紧张；[U]勇气；胆量", "english": "nerve", "type": "单词", "keyWords": [] },
    { "chinese": "刺激某人的神经；使某人心烦意乱/发脾气", "english": "get on sb.'s nerves", "type": "短语", "keyWords": ["nerve"] },
    { "chinese": "a.神经的；神经紧张的；n.[U]神经过敏", "english": "nervous", "type": "单词", "keyWords": [] },
    { "chinese": "神经系统", "english": "nervous system", "type": "短语", "keyWords": ["nervous"] },
    { "chinese": "对……神经紧张", "english": "be nervous about", "type": "短语", "keyWords": ["nervous"] },
    { "chinese": "常加在形容词后面构成名词，表示“性质，状态，程度”", "english": "-ness", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]巢", "english": "nest", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]网；网状物；a.纯的；净的", "english": "net", "type": "单词", "keyWords": [] },
    { "chinese": "净重", "english": "net weight", "type": "短语", "keyWords": ["net"] },
    { "chinese": "净利润", "english": "net profit", "type": "短语", "keyWords": ["net"] },
    { "chinese": "n.[C]网状组织；网络", "english": "network", "type": "单词", "keyWords": [] } 
];
qgl173_180.sort(() => Math.random() - 0.5);