const qgl197_204 = [
    { "chinese": "充满激情地(说…)", "english": "speak with passion", "type": "短语", "keyWords": ["passion"] },
    { "chinese": "热爱…", "english": "have a passion for...", "type": "短语", "keyWords": ["passion"] },
    { "chinese": "a. 消极的；被动的(反active)", "english": "passive", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]护照", "english": "passport", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]口令；密码", "english": "password", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 超过；经过；n. (the)过去，以前，旧时；往事；a. 以前的，过去的；ad. (从旁)过去", "english": "past", "type": "单词", "keyWords": [] },
    { "chinese": "他快六十了。", "english": "He is well past fifty.", "type": "句子", "keyWords": ["past"] },
    { "chinese": "在过去，从前", "english": "in the past", "type": "短语", "keyWords": ["past"] },
    { "chinese": "在过去的几年里（与完成时连用）", "english": "in the past few years + 完成时", "type": "短语", "keyWords": ["past"] },
    { "chinese": "往事", "english": "memories of the past", "type": "短语", "keyWords": ["past"] },
    { "chinese": "他走过(我身旁)时挥了挥手。", "english": "He waved as he walked past (me).", "type": "句子", "keyWords": ["past"] },
    { "chinese": "vt. 轻拍，轻打；n. [C]拍打", "english": "pat", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]专利；专利权；专利发明；a. 专利权的；受专利权保护的；vt. 得到(发明等)的专利权；给…特许状(或专利证)", "english": "patent", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]路，小道，小径；(物体运动的)路径", "english": "path", "type": "单词", "keyWords": [] },
    { "chinese": "通向成功的道路", "english": "the path to success", "type": "短语", "keyWords": ["path"] },
    { "chinese": "n. 忍耐；耐心", "english": "patience", "type": "单词", "keyWords": [] },
    { "chinese": "对(某人)有耐心", "english": "have patience with sb.", "type": "短语", "keyWords": ["patience"] },
    { "chinese": "耐心地", "english": "with patience", "type": "短语", "keyWords": ["patience"] },
    { "chinese": "n. 病人；a. 有耐心的", "english": "patient", "type": "单词", "keyWords": [] },
    { "chinese": "对(某人)有耐心", "english": "be patient with sb.", "type": "短语", "keyWords": ["patient"] },
    { "chinese": "a. 爱国的", "english": "patriotic", "type": "单词", "keyWords": [] },
    { "chinese": "n. 爱国者", "english": "patriot", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]爱国心，爱国主义", "english": "patriotism", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]图案，花样；模范，典范；样式，模式", "english": "pattern", "type": "单词", "keyWords": [] },
    { "chinese": "花的图案，印花的式样", "english": "a pattern of flowers", "type": "短语", "keyWords": ["pattern"] },
    { "chinese": "文化模式", "english": "cultural pattern", "type": "短语", "keyWords": ["pattern"] },
    { "chinese": "句型", "english": "a sentence pattern", "type": "短语", "keyWords": ["pattern"] },
    { "chinese": "服装式样", "english": "a dress pattern", "type": "短语", "keyWords": ["pattern"] },
    { "chinese": "vi./vt. 暂停；中止；n. [C]暂停；中止；停顿", "english": "pause", "type": "单词", "keyWords": [] },
    { "chinese": "中止，暂停", "english": "make a pause", "type": "短语", "keyWords": ["pause"] },
    { "chinese": "短暂的停顿后", "english": "after a pause", "type": "短语", "keyWords": ["pause"] },
    { "chinese": "停顿片刻", "english": "pause for a while", "type": "短语", "keyWords": ["pause"] },
    { "chinese": "vt. 铺路；为…做准备", "english": "pave", "type": "单词", "keyWords": [] },
    { "chinese": "为将来的研究工作铺平道路的实验", "english": "experiments that paved the way for future research", "type": "短语", "keyWords": ["pave"] },
    { "chinese": "n. [C][英]人行道；[美]sidewalk", "english": "pavement", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 支付；付钱给…报酬；vi. 付款；n. [C]报酬；工资", "english": "pay", "type": "单词", "keyWords": [] },
    { "chinese": "偿还(欠款)；报答；报仇", "english": "pay sb. back", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "买票才能进", "english": "have to pay to go in", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "还清(债款)", "english": "pay off (one's debts)", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "花钱买", "english": "pay sb. some money for sth.", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "为他的愚蠢付出代价", "english": "pay for his stupidity", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "计划成功了。", "english": "The plan paid off.", "type": "句子", "keyWords": ["pay"] },
    { "chinese": "n. [U]支付；n. [C]支付的一笔钱", "english": "payment", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]和平；安宁", "english": "peace", "type": "单词", "keyWords": [] },
    { "chinese": "a. 和平的；安宁的", "english": "peaceful", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 和平地", "english": "peacefully", "type": "单词", "keyWords": [] },
    { "chinese": "和…讲和", "english": "make peace with", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "破坏治安", "english": "break the peace", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "和平地", "english": "in peace(=peacefully)", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "维护和平", "english": "maintain peace", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "处于和平/和睦/平静状态；安息，长眠", "english": "at peace", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "与某人和解；同某人言归于好", "english": "make one's peace with...", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "n. [C]桃子", "english": "peach", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]孔雀", "english": "peacock", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]山峰；顶点；vi. 到达最大值；到达高峰", "english": "peak", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]花生；花生米", "english": "peanut", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]梨", "english": "pear", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]珍珠", "english": "pearl", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]农民", "english": "peasant", "type": "单词", "keyWords": [] },
    { "chinese": "a. 古怪的；独特的", "english": "peculiar", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]特性，怪癖", "english": "peculiarity", "type": "单词", "keyWords": [] },
    { "chinese": "某人/某地特有的", "english": "be peculiar to sb./a place", "type": "短语", "keyWords": ["peculiar"] },
    { "chinese": "这个地区所特有的物种", "english": "a species(which is) peculiar to this area", "type": "短语", "keyWords": ["peculiar"] },
    { "chinese": "n. [C]行人；a. 徒步的，步行的；行人的", "english": "pedestrian", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 剥…的皮", "english": "peel", "type": "单词", "keyWords": [] },
    { "chinese": "v. 偷看(at)", "english": "peep", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]同辈，同等的人；(才能、学识等)相匹配的人", "english": "peer", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]钢笔", "english": "pen", "type": "单词", "keyWords": [] },
    { "chinese": "用钢笔", "english": "in pen=with a pen", "type": "短语", "keyWords": ["pen"] },
    { "chinese": "n. [C]处罚；刑罚；罚球", "english": "penalty", "type": "单词", "keyWords": [] },
    { "chinese": "(足球)罚球区", "english": "penalty area", "type": "短语", "keyWords": ["penalty"] },
    { "chinese": "死刑", "english": "the death penalty", "type": "短语", "keyWords": ["penalty"] },
    { "chinese": "n. [C]铅笔", "english": "pencil", "type": "单词", "keyWords": [] },
    { "chinese": "用铅笔", "english": "in pencil=with a pencil", "type": "短语", "keyWords": ["pencil"] },
    { "chinese": "n. [C]便士(两种复数形式：pence强调面值，pennies强调硬币数量)", "english": "penny", "type": "单词", "keyWords": [] },
    { "chinese": "请给我把这个十便士的硬币换成十个一便士的硬币。", "english": "Please give me ten pennies for this tenpence.", "type": "句子", "keyWords": ["penny"] },
    { "chinese": "省一文等于挣一文。", "english": "A penny saved is a penny gained.", "type": "句子", "keyWords": ["penny"] },
    { "chinese": "n. [C]养老金；退休金；抚恤金；vt. 给某人发养老金或抚恤金等", "english": "pension", "type": "单词", "keyWords": [] },
    { "chinese": "n. (pl.)人，人们；(the)人民；n. [C]民族", "english": "people", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]胡椒粉；n. [C]辣椒", "english": "pepper", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 每，每一", "english": "per", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]百分之一；百分率；a. 百分之…的", "english": "percent", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]百分比；百分率；(全部中的)所占比例", "english": "percentage", "type": "单词", "keyWords": [] },
    { "chinese": "现在大部分教科书有插图。", "english": "A large/great percentage of school books now have pictures.", "type": "句子", "keyWords": ["percentage"] },
    { "chinese": "a. 完美的；十足的；熟练的；vt. 使完美；改善；提高", "english": "perfect", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 完美地；极佳地", "english": "perfectly", "type": "单词", "keyWords": [] },
    { "chinese": "熟能生巧。", "english": "Practice makes perfect.", "type": "句子", "keyWords": ["perfect"] },
    { "chinese": "vt. 演出；进行；做；执行；vi. 表演；表现", "english": "perform", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]表演者；执行者", "english": "performer", "type": "单词", "keyWords": [] },
    { "chinese": "做手术/履行义务/尽责任", "english": "perform the operation/obligations/one's duties", "type": "短语", "keyWords": ["perform"] },
    { "chinese": "n. [C]表演；n. [U]进行；执行，履行；表现，性能", "english": "performance", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 也许，可能", "english": "perhaps", "type": "单词", "keyWords": [] },
    { "chinese": "n. (一段)时间；句号", "english": "period", "type": "单词", "keyWords": [] },
    { "chinese": "a. 周期的，定期的", "english": "periodic", "type": "单词", "keyWords": [] },
    { "chinese": "a. 长久的；永久的；长期不变的", "english": "permanent", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]长久", "english": "permanence", "type": "单词", "keyWords": [] },
    { "chinese": "某人的永久地址", "english": "one's permanent address", "type": "短语", "keyWords": ["permanent"] },
    { "chinese": "n. [U]允许；准许", "english": "permission", "type": "单词", "keyWords": [] },
    { "chinese": "经(某人)容许", "english": "with (one's) permission", "type": "短语", "keyWords": ["permission"] },
    { "chinese": "请求许可", "english": "ask for permission", "type": "短语", "keyWords": ["permission"] },
    { "chinese": "未经许可，擅自", "english": "without permission", "type": "短语", "keyWords": ["permission"] },
    { "chinese": "vt. 允许，许可；vi. (常用否定)容许(of)；n. [C]许可证", "english": "permit", "type": "单词", "keyWords": [] },
    { "chinese": "允许做某事", "english": "permit doing sth.", "type": "短语", "keyWords": ["permit"] },
    { "chinese": "允许某人做某事", "english": "permit sb. to do sth.", "type": "短语", "keyWords": ["permit"] },
    { "chinese": "情势刻不容缓。", "english": "The situation doesn't permit of any delay.", "type": "句子", "keyWords": ["permit"] },
    { "chinese": "旅游签证/工作许可证", "english": "a travel/work permit", "type": "短语", "keyWords": ["permit"] },
    { "chinese": "vt. 坚持(做)(in/with sth., in doing sth.)", "english": "persevere", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]百折不挠", "english": "perseverance", "type": "单词", "keyWords": [] },
    { "chinese": "a. 不屈不挠的", "english": "persevering", "type": "单词", "keyWords": [] },
    { "chinese": "坚持改革开放", "english": "persevere in the reform and opening-up policy", "type": "短语", "keyWords": ["persevere"] },
    { "chinese": "vi. 固执；坚持不懈(in sth./doing sth.)", "english": "persist", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]执意，坚持", "english": "persistence", "type": "单词", "keyWords": [] },
    { "chinese": "a. 执意的，坚持的", "english": "persistent", "type": "单词", "keyWords": [] },
    { "chinese": "(固执地)坚持", "english": "persist in doing sth.", "type": "短语", "keyWords": ["persist"] },
    { "chinese": "n. [C]人", "english": "person", "type": "单词", "keyWords": [] },
    { "chinese": "a. 个人的；私人的；亲自的", "english": "personal", "type": "单词", "keyWords": [] },
    { "chinese": "亲自", "english": "in person", "type": "短语", "keyWords": ["personal"] },
    { "chinese": "n. [C]/[U]个性", "english": "personality", "type": "单词", "keyWords": [] },
    { "chinese": "n. (用作单或复)全体员工；人事部门", "english": "personnel", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]透视画法；透视图；[C]远景；景观；视角；观点；想法", "english": "perspective", "type": "单词", "keyWords": [] },
    { "chinese": "从不同的角度来看这个问题", "english": "see the issue from a different perspective", "type": "短语", "keyWords": ["perspective"] },
    { "chinese": "正确地，合理地；符合透视法地", "english": "in perspective", "type": "短语", "keyWords": ["perspective"] },
    { "chinese": "合理地评价某人的作用", "english": "judge sb.'s role in perspective", "type": "短语", "keyWords": ["perspective"] },
    { "chinese": "vt. 说服，劝服；a. 有说服力的", "english": "persuade；persuasive", "type": "单词", "keyWords": [] },
    { "chinese": "说服某人做某事", "english": "persuade sb. to do...；be able to advise sb. to do...", "type": "短语", "keyWords": ["persuade"] },
    { "chinese": "设法说服他干这个工作", "english": "try to persuade him to take the job", "type": "短语", "keyWords": ["persuade"] },
    { "chinese": "说服某人做/别做某事", "english": "persuade sb. into/out of doing sth.", "type": "短语", "keyWords": ["persuade"] },
    { "chinese": "她父亲说服了她嫁给约翰。", "english": "Her father persuaded her into marrying John.", "type": "句子", "keyWords": ["persuade"] },
    { "chinese": "a. 悲观的；悲观主义的", "english": "pessimistic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]/[U]杀虫剂；农药(近insecticide)", "english": "pesticide", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]宠物；玩赏动物；vt. 宠爱，溺爱", "english": "pet", "type": "单词", "keyWords": [] },
    { "chinese": "养宠物", "english": "keep/raise a pet", "type": "短语", "keyWords": ["pet"] },
    { "chinese": "n. [U]汽油", "english": "petrol", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl. phenomena)现象；奇迹；杰出的人才", "english": "phenomenon", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]哲学；人生观；(学科等的)基本原理；a. 哲学的", "english": "philosophy；philosophical", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]电话；vt. 给……打电话", "english": "phone", "type": "单词", "keyWords": [] },
    { "chinese": "给……打电话", "english": "phone sb.；call sb. up；ring sb. up；make a phone call to sb.；give sb. a ring", "type": "短语", "keyWords": ["phone"] },
    { "chinese": "在打电话；在接电话", "english": "on the phone", "type": "短语", "keyWords": ["phone"] },
    { "chinese": "有人要你接电话。", "english": "You are wanted on the phone.", "type": "句子", "keyWords": ["phone"] },
    { "chinese": "在电话里和某人讲话", "english": "talk to sb. over/on the phone", "type": "短语", "keyWords": ["phone"] },
    { "chinese": "挂断/接电话", "english": "hang up/answer the phone", "type": "短语", "keyWords": ["phone"] },
    { "chinese": "n. [C]照片(=photograph)；vt. 复印", "english": "photo；photocopy", "type": "单词", "keyWords": [] },
    { "chinese": "和某人合影", "english": "have a photo taken with sb.", "type": "短语", "keyWords": ["photo"] },
    { "chinese": "n. [C]摄影者", "english": "photographer", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]摄影术；摄影", "english": "photography", "type": "单词", "keyWords": [] },
    { "chinese": "a. 摄影的；摄影般的；逼真的", "english": "photographic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]短语，词组；习语", "english": "phrase", "type": "单词", "keyWords": [] },
    { "chinese": "a. 物理的；自然的；身体的；物质的；有形的；实物的", "english": "physical", "type": "单词", "keyWords": [] },
    { "chinese": "体育锻炼", "english": "physical training", "type": "短语", "keyWords": ["physical"] },
    { "chinese": "物理变化", "english": "a physical change", "type": "短语", "keyWords": ["physical"] },
    { "chinese": "n. [C][内科]医生(反surgeon外科医生)", "english": "physician", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]物理学家", "english": "physicist", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]物理学", "english": "physics", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]生理学；n. [C]生理学家", "english": "physiology；physiologist", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]钢琴；n. [C]钢琴家，钢琴演奏家", "english": "piano；pianist", "type": "单词", "keyWords": [] },
    { "chinese": "弹钢琴", "english": "play (on) the piano", "type": "短语", "keyWords": ["piano"] },
    { "chinese": "vt. 采摘；摘；拾；捡；vi. (被)采摘；n. [C]扒手", "english": "pick；pick - pocket", "type": "单词", "keyWords": [] },
    { "chinese": "他们在采棉花。", "english": "They were picking cotton.", "type": "句子", "keyWords": ["pick"] },
    { "chinese": "我的口袋被扒了。", "english": "My pocket was picked.", "type": "句子", "keyWords": ["pick"] },
    { "chinese": "分辨出，挑出；选出", "english": "pick out", "type": "短语", "keyWords": ["pick"] },
    { "chinese": "把汤姆从人群中认出来。", "english": "Pick out Tom from the crowd.", "type": "句子", "keyWords": ["pick"] },
    { "chinese": "①拾起；②加快速度；③获得；学会；买到；④取物，(用车、船)接人；救起；⑤(借助仪器)看到/收听到/侦察到；听到(谣传)；⑥染上(病)；形成(习惯)", "english": "pick up", "type": "短语", "keyWords": ["pick"] },
    { "chinese": "把帽子拾起来", "english": "pick up the hat", "type": "短语", "keyWords": ["pick up"] },
    { "chinese": "加速", "english": "pick up speed", "type": "短语", "keyWords": ["pick up"] },
    { "chinese": "小孩子学外语相当快。", "english": "Young children pick up a foreign language fairly quickly.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "她喜欢在旧货店买些有趣的旧货。", "english": "She likes to pick up some interesting junk in junk shops.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "每隔一天我得去学校接孩子们。", "english": "I have to pick up children from school every other day.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "汽车停下来搭乘客。", "english": "The bus stopped to pick up passengers.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "水手们被路过的客轮救起。", "english": "The sailors were picked up by a passing liner.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "我的收音机可收听BBC广播。", "english": "My radio can pick up the BBC.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "你从哪里听说的?", "english": "Where did you pick that up?", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "蚊子在感染了疟疾的人身上吸血时得疟疾。", "english": "Mosquitoes pick up malaria by sucking blood from an infected person.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "n. [C]野餐；vi. (picnicked,picnicking)去野餐；参加野餐", "english": "picnic", "type": "单词", "keyWords": [] },
    { "chinese": "去野餐", "english": "go for/have a picnic；go out on a picnic", "type": "短语", "keyWords": ["picnic"] },
    { "chinese": "n. [C]图片；描写；记忆，情景；vt. 绘，画；描绘；构想；想象", "english": "picture", "type": "单词", "keyWords": [] },
    { "chinese": "清楚地了解", "english": "get a clear picture of", "type": "短语", "keyWords": ["picture"] },
    { "chinese": "生动地描述", "english": "give a vivid picture of", "type": "短语", "keyWords": ["picture"] },
    { "chinese": "去看电影", "english": "go to the pictures", "type": "短语", "keyWords": ["picture"] },
    { "chinese": "她的情况有很大差异。", "english": "The picture varies considerably from place to place.", "type": "句子", "keyWords": ["picture"] },
    { "chinese": "n. [C]/[U]馅饼", "english": "pie", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]块，片，段(表示不可数名词的量)；vt. 拼凑；缝合；修补", "english": "piece", "type": "单词", "keyWords": [] },
    { "chinese": "破碎，碎裂", "english": "go to pieces", "type": "短语", "keyWords": ["piece"] },
    { "chinese": "拼凑一则故事", "english": "piece together a story", "type": "短语", "keyWords": ["piece"] },
    { "chinese": "n. [C]猪", "english": "pig", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]鸽子", "english": "pigeon", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]堆，积，叠；vt. 堆积", "english": "pile", "type": "单词", "keyWords": [] },
    { "chinese": "堆积，累积", "english": "pile...up", "type": "短语", "keyWords": ["pile"] },
    { "chinese": "一堆(麻烦、报纸等)", "english": "a pile of (trouble,newspapers..)", "type": "短语", "keyWords": ["pile"] },
    { "chinese": "一大堆，好多", "english": "piles of", "type": "短语", "keyWords": ["pile"] },
    { "chinese": "n. [C]药丸；药片", "english": "pill", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]立柱", "english": "pillar", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]枕头", "english": "pillow", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]飞行员；领航员；vt. (为船舶)引航；驾驶(飞机等)；带领；引导；试用，试验；a. 引航员的；指引的；实验性的，试点的", "english": "pilot", "type": "单词", "keyWords": [] },
    { "chinese": "他以高超的技术把这条船引进了那个小港湾。", "english": "With great skill, he piloted the boat into the little harbour.", "type": "句子", "keyWords": ["pilot"] },
    { "chinese": "世界银行的贷款可以被用于基础建设和一个“全方位电动车生态系统”的试点项目，这将包括投资建立电瓶站和电池研发。", "english": "World Bank loans could help finance infrastructure and a \"comprehensive electric vehicle ecosystem\" pilot project that would include investment in battery stations and batteries.", "type": "句子", "keyWords": ["pilot"] },
    { "chinese": "n. [C]别针；发夹；vt. 用别针别起来；钉住", "english": "pin", "type": "单词", "keyWords": [] },
    { "chinese": "安全别针", "english": "a safety pin", "type": "短语", "keyWords": ["pin"] },
    { "chinese": "把布告钉在墙上", "english": "pin a notice on the wall", "type": "短语", "keyWords": ["pin"] },
    { "chinese": "n. [C]松树", "english": "pine", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]菠萝", "english": "pineapple", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]粉红色；a. 粉红色的", "english": "pink", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](容量单位)品脱", "english": "pint", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]先锋；开拓者；创立者，创办者；vt. 开拓，开发；为…开始；开创；vi. 当先驱，当先锋", "english": "pioneer", "type": "单词", "keyWords": [] },
    { "chinese": "少先队(员)", "english": "the Young Pioneer", "type": "短语", "keyWords": ["pioneer"] },
    { "chinese": "n. [C]管子；烟斗；导管", "english": "pipe", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]海盗；vt. 盗版", "english": "pirate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]同情；可怜；n. [C](只用单)遗憾；vt. 同情；a. 值得同情的；a. 可怜的", "english": "pity；pitable；pitiful", "type": "单词", "keyWords": [] },
    { "chinese": "同情/可怜某人", "english": "have/take pity on sb.", "type": "短语", "keyWords": ["pity"] },
    { "chinese": "真遗憾她竟然没在大会上发表她的意见。", "english": "It's a pity that she should not set out her idea at the conference.", "type": "句子", "keyWords": ["pity"] },
    { "chinese": "未受过正规教育的人应该得到同情而不是责备。", "english": "The uneducated are more to be pitied than blamed.", "type": "句子", "keyWords": ["pity"] },
    { "chinese": "n. [C]/[U]比萨饼", "english": "pizza", "type": "单词", "keyWords": [] },
    { "chinese": "n. 人民解放军", "english": "PLA (the People's Liberation Army缩略)", "type": "单词", "keyWords": [] },
    { "chinese": "一个人民解放军战士", "english": "a PLA man", "type": "短语", "keyWords": ["PLA"] },
    { "chinese": "vt. (小心)放置；安置；n. [C]地方；场所，地点；名次；地位", "english": "place", "type": "单词", "keyWords": [] },
    { "chinese": "首先", "english": "in the first place", "type": "短语", "keyWords": ["place"] },
    { "chinese": "在适当的位置上(反out of place合适的)", "english": "in place", "type": "短语", "keyWords": ["place"] },
    { "chinese": "代替(近instead of)", "english": "in place of", "type": "短语", "keyWords": ["place"] },
    { "chinese": "发生，举行", "english": "take place", "type": "短语", "keyWords": ["place"] },
    { "chinese": "代替，取代(近replace)", "english": "take the place of", "type": "短语", "keyWords": ["place"] },
    { "chinese": "①代替(=take the place of)；②就位", "english": "take one's place", "type": "短语", "keyWords": ["place"] },
    { "chinese": "n. [C]平原；a. 明白的，简明的；简易的；简朴的", "english": "plain", "type": "单词", "keyWords": [] },
    { "chinese": "以简明的语言", "english": "in plain language", "type": "短语", "keyWords": ["plain"] },
    { "chinese": "浅显的道理", "english": "a plain truth", "type": "短语", "keyWords": ["plain"] },
    { "chinese": "v. 计划，安排；n. [C]计划；平面图", "english": "plan", "type": "单词", "keyWords": [] },
    { "chinese": "计划做某事", "english": "plan to do sth.", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "按计划", "english": "as planned", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "该项目正按计划进行。", "english": "The project is progressing as planned.", "type": "句子", "keyWords": ["plan"] },
    { "chinese": "五年计划", "english": "a five-year plan", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "实施计划", "english": "carry out a plan", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "为……制订计划", "english": "work out/make plans for", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "n. [C]飞机", "english": "plane", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]行星", "english": "planet", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]植物；工厂(重工业为主)；v. 种植，栽种", "english": "plant", "type": "单词", "keyWords": [] },
    { "chinese": "发电厂", "english": "power plant", "type": "短语", "keyWords": ["plant"] },
    { "chinese": "炼钢厂", "english": "steel plant", "type": "短语", "keyWords": ["plant"] },
    { "chinese": "n. [C]种植园", "english": "plantation", "type": "单词", "keyWords": [] },
    { "chinese": "咖啡种植园", "english": "coffee plantation", "type": "短语", "keyWords": ["plantation"] },
    { "chinese": "橡胶种植园", "english": "rubber plantation", "type": "短语", "keyWords": ["plantation"] },
    { "chinese": "a. 塑料(制)的；可塑的；(pl.)塑料；塑料制品；*(作单数)塑料学", "english": "plastic", "type": "单词", "keyWords": [] },
    { "chinese": "塑料杯", "english": "plastic cups", "type": "短语", "keyWords": ["plastic"] },
    { "chinese": "由塑料制成", "english": "be made of plastic(s)", "type": "短语", "keyWords": ["plastic"] },
    { "chinese": "n. [C]盘子，碟子；金属板；(汽车等的)牌照", "english": "plate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]站台，月台；讲台；平台", "english": "platform", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]剧本；戏剧；游戏；玩耍；v. 玩，打(球)；比赛；演出", "english": "play", "type": "单词", "keyWords": [] },
    { "chinese": "与我下棋", "english": "play me at chess/play chess with me", "type": "短语", "keyWords": ["play"] },
    { "chinese": "玩火，冒险", "english": "play with fire", "type": "短语", "keyWords": ["play"] },
    { "chinese": "与某人比赛", "english": "play(against)sb.", "type": "短语", "keyWords": ["play"] },
    { "chinese": "在玩，在游戏(反at work)", "english": "at play", "type": "短语", "keyWords": ["play"] },
    { "chinese": "公正合理；公平的比赛；光明正大的行动", "english": "fair play", "type": "短语", "keyWords": ["play"] },
    { "chinese": "n. [C]比赛者；运动员；游戏的人(玩耍、打牌、下棋)", "english": "player", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]操场", "english": "playground", "type": "单词", "keyWords": [] },
    { "chinese": "a. 令人愉快的；和蔼可亲的", "english": "pleasant", "type": "单词", "keyWords": [] },
    { "chinese": "悦耳的声音", "english": "a pleasant voice", "type": "短语", "keyWords": ["pleasant"] },
    { "chinese": "悦耳", "english": "be pleasant to the ear", "type": "短语", "keyWords": ["pleasant"] },
    { "chinese": "宜人的天气", "english": "pleasant weather", "type": "短语", "keyWords": ["pleasant"] },
    { "chinese": "愉快地度过时光", "english": "have a pleasant time", "type": "短语", "keyWords": ["pleasant"] },
    { "chinese": "v. 请(if you please的略语)；v. 使满意；使高兴", "english": "please", "type": "单词", "keyWords": [] },
    { "chinese": "(if you)please,...请；请听我说；对不起(礼貌地请求某人注意)", "english": "(if you)please,...", "type": "短语", "keyWords": ["please"] },
    { "chinese": "众口难调。", "english": "It is difficult to please everybody.", "type": "句子", "keyWords": ["please"] },
    { "chinese": "一幅悦目的图画", "english": "a picture that pleases the eye", "type": "短语", "keyWords": ["please"] },
    { "chinese": "你想去那里就去那里。", "english": "Go there as you please.", "type": "句子", "keyWords": ["please"] },
    { "chinese": "你爱怎么着就怎么着!", "english": "Do what you please!", "type": "句子", "keyWords": ["please"] },
    { "chinese": "要面面俱到者，面面不到。", "english": "Please all and you please none.", "type": "句子", "keyWords": ["please"] },
    { "chinese": "a. 高兴的；喜欢的(意指给人满意的感觉)", "english": "pleased", "type": "单词", "keyWords": [] },
    { "chinese": "对某事感到满意", "english": "be pleased at/about sth.", "type": "短语", "keyWords": ["pleased"] },
    { "chinese": "对某人/物感到满意", "english": "be pleased with sb./sth.", "type": "短语", "keyWords": ["pleased"] },
    { "chinese": "n. [U]愉快，高兴；n. [C]乐趣；乐事", "english": "pleasure", "type": "单词", "keyWords": [] },
    { "chinese": "为了享受，作为消遣", "english": "for pleasure", "type": "短语", "keyWords": ["pleasure"] },
    { "chinese": "喜欢……；以……为乐(=take delight/interest in)", "english": "take(a)pleasure in...", "type": "短语", "keyWords": ["pleasure"] },
    { "chinese": "很荣幸地；很高兴地；(多用于回答)没问题", "english": "with pleasure", "type": "短语", "keyWords": ["pleasure"] },
    { "chinese": "不客气。", "english": "It's a pleasure.=My pleasure.", "type": "句子", "keyWords": ["pleasure"] },
    { "chinese": "很乐意做某事。", "english": "It's a pleasure to do sth.", "type": "句子", "keyWords": ["pleasure"] },
    { "chinese": "n. [U]充足；大量；a. 充足的；多的", "english": "plenty；plentiful", "type": "单词", "keyWords": [] },
    { "chinese": "大量的；充足的(注意前面不用a)", "english": "plenty of", "type": "短语", "keyWords": ["plenty"] },
    { "chinese": "我家里还有很多。", "english": "I have plenty more at home.", "type": "句子", "keyWords": ["plenty"] },
    { "chinese": "n. [C]犁；v. 耕，犁", "english": "plough", "type": "单词", "keyWords": [] },
    { "chinese": "犁地", "english": "plough a field", "type": "短语", "keyWords": ["plough"] },
    { "chinese": "n. [C]插头；塞子；v. 给……通电", "english": "plug", "type": "单词", "keyWords": [] },
    { "chinese": "即插即用", "english": "plug and play", "type": "短语", "keyWords": ["plug"] },
    { "chinese": "插上(电视机的)插头", "english": "plug in (the TV set)", "type": "短语", "keyWords": ["plug"] },
    { "chinese": "v. 纵身跳入；陷入；投身；v. 把……投入；将……插入", "english": "plunge", "type": "单词", "keyWords": [] },
    { "chinese": "我们跳进冰冷的山间湖中。", "english": "We plunged into the icy mountain lake.", "type": "句子", "keyWords": ["plunge"] },
    { "chinese": "他将手插入水中。", "english": "He plunged his hand into the water.", "type": "句子", "keyWords": ["plunge"] },
    { "chinese": "她陷入了绝望的深渊。", "english": "She was plunged into the depth of despair.", "type": "句子", "keyWords": ["plunge"] },
    { "chinese": "prep. 加，加上；a. 正的；加的", "english": "plus", "type": "单词", "keyWords": [] },
    { "chinese": "8加7等于15。", "english": "Eight plus seven equals fifteen.", "type": "句子", "keyWords": ["plus"] },
    { "chinese": "她的成绩是B+。", "english": "She got a grade of B plus.", "type": "句子", "keyWords": ["plus"] },
    { "chinese": "n. [C]衣袋；a. 袖珍的", "english": "pocket", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]诗；诗篇；诗体文", "english": "poem", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]诗人；a. 诗的；有诗意的", "english": "poet；poetic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U](总称)诗；诗篇", "english": "poetry", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]点；小数点；尖(端)；观点；道理；v. 指；指出，指明", "english": "point", "type": "单词", "keyWords": [] },
    { "chinese": "持不同的观点", "english": "take/form a different point of view", "type": "短语", "keyWords": ["point"] },
    { "chinese": "转折点，转向处", "english": "a turning point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "在(临死…)之时", "english": "at the point of (death)", "type": "短语", "keyWords": ["point"] },
    { "chinese": "比尔把乔未讲完的故事接着往下讲。", "english": "Bill took up the story at the point where Joe had left off.", "type": "句子", "keyWords": ["point"] },
    { "chinese": "这时(=at this moment)", "english": "at this point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "要……时……；正要做某事时……", "english": "be on the point of doing sth. when...；be going/about to do sth. when...", "type": "短语", "keyWords": ["point"] },
    { "chinese": "没听清；不得要领；不懂妙处", "english": "miss the point of(his joke)", "type": "短语", "keyWords": ["point"] },
    { "chinese": "做某事没有意义", "english": "there's no point/sense in doing sth.", "type": "短语", "keyWords": ["point"] },
    { "chinese": "我不明白/理解让他自行其是有什么道理。", "english": "I didn't see the point of/any point in letting him have his own way.", "type": "句子", "keyWords": ["point"] },
    { "chinese": "离题", "english": "beside/off the point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "中肯；恰到好处", "english": "to the point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "说到要点；到正题上来", "english": "come to the point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "提出论点", "english": "make a point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "指着", "english": "point at", "type": "短语", "keyWords": ["point"] },
    { "chinese": "指向", "english": "point to", "type": "短语", "keyWords": ["point"] },
    { "chinese": "指出", "english": "point out", "type": "短语", "keyWords": ["point"] },
    { "chinese": "这件事再讨论下去有什么意义呢?", "english": "What is the point of discussing this issue further?", "type": "句子", "keyWords": ["point"] },
    { "chinese": "a. 尖的", "english": "pointed", "type": "单词", "keyWords": [] },
    { "chinese": "有尖头的棍子", "english": "a pointed stick", "type": "短语", "keyWords": ["pointed"] },
    { "chinese": "n. [C]/[U]毒物；毒药；v. 毒死；使中毒；投毒于；vi. 下毒", "english": "poison", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有毒的；恶毒的，有恶意的", "english": "poisonous", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]极(点)；地极(区域)；电极；杆，电线杆", "english": "pole", "type": "单词", "keyWords": [] },
    { "chinese": "北/南极", "english": "the North/South Pole", "type": "短语", "keyWords": ["pole"] },
    { "chinese": "a. 两极的；极地的", "english": "polar", "type": "单词", "keyWords": [] },
    { "chinese": "北极熊", "english": "polar bear", "type": "短语", "keyWords": ["polar"] },
    { "chinese": "n. (作复数用)(the)警察，警方；警察部门", "english": "police", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]警察", "english": "policeman", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]政策；方针", "english": "policy", "type": "单词", "keyWords": [] },
    { "chinese": "开放政策", "english": "the open-door policy", "type": "短语", "keyWords": ["policy"] },
    { "chinese": "诚实才是上策。", "english": "Honesty is the best policy.", "type": "句子", "keyWords": ["policy"] },
    { "chinese": "v. 磨光；擦亮；润色，使完美；vi. 变得平滑、光亮", "english": "polish", "type": "单词", "keyWords": [] },
    { "chinese": "擦鞋", "english": "polish shoes", "type": "短语", "keyWords": ["polish"] },
    { "chinese": "修改润色文章", "english": "polish an article", "type": "短语", "keyWords": ["polish"] },
    { "chinese": "v. 磨光；擦亮；润色，使完美；vi. 变得平滑、光亮", "english": "polish", "type": "单词", "keyWords": [] },
    { "chinese": "擦鞋", "english": "polish shoes", "type": "短语", "keyWords": ["polish"] },
    { "chinese": "修改润色文章", "english": "polish an article", "type": "短语", "keyWords": ["polish"] },
    { "chinese": "用这块特殊的布能很容易把银器擦亮。", "english": "Silver polishes easily with this special cloth.", "type": "句子", "keyWords": ["polish"] },
    { "chinese": "a. 有礼貌的；有教养的；n. [U]有礼貌", "english": "polite；politeness", "type": "单词", "keyWords": [] },
    { "chinese": "a. 政治的", "english": "political", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]政治家；[贬]政客", "english": "politician", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]政治；(pl.)政治活动；*政治见解", "english": "politics", "type": "单词", "keyWords": [] },
    { "chinese": "进入政界", "english": "go into politics", "type": "短语", "keyWords": ["politics"] },
    { "chinese": "你的政见如何?", "english": "What are your politics?", "type": "句子", "keyWords": ["politics"] },
    { "chinese": "vt. 污染；弄脏；a. 被污染的；n. [U]污染", "english": "pollute；polluted；pollution", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]池塘", "english": "pond", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]水池；水塘；*一摊，一片", "english": "pool", "type": "单词", "keyWords": [] },
    { "chinese": "游泳池", "english": "a swimming pool", "type": "短语", "keyWords": ["pool"] },
    { "chinese": "一摊鲜血", "english": "a pool of blood", "type": "短语", "keyWords": ["pool"] },
    { "chinese": "a. 可怜的；贫穷的；差劲的", "english": "poor", "type": "单词", "keyWords": [] },
    { "chinese": "缺乏(反be rich in, be high in)", "english": "be poor in", "type": "短语", "keyWords": ["poor"] },
    { "chinese": "这个国家矿物不丰富。", "english": "The country is poor in minerals.", "type": "句子", "keyWords": ["poor"] },
    { "chinese": "不善于(反be good at, be clever at)", "english": "be poor at", "type": "短语", "keyWords": ["poor"] },
    { "chinese": "a. 大众的；流行的；通俗的；n. [U]流行音乐/歌曲；通俗艺术", "english": "pop", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]爆玉米花", "english": "popcorn", "type": "单词", "keyWords": [] },
    { "chinese": "a. 大众化的；流行的；广受欢迎的；n. [U]普及；流行", "english": "popular；popularity", "type": "单词", "keyWords": [] },
    { "chinese": "科普读物", "english": "popular science readings", "type": "短语", "keyWords": ["popular"] },
    { "chinese": "受……的欢迎", "english": "be popular with sb.", "type": "短语", "keyWords": ["popular"] },
    { "chinese": "n. [C]人口(数字)；(the)居住于某一地区的(全体)居民", "english": "population", "type": "单词", "keyWords": [] },
    { "chinese": "这个城市的人口是多少?", "english": "What is the population of this city?", "type": "句子", "keyWords": ["population"] },
    { "chinese": "全村的人都以旅游业为生。", "english": "The whole population of the village lives on tourism.", "type": "句子", "keyWords": ["population"] },
    { "chinese": "有……的人口", "english": "have a large/small population of...", "type": "短语", "keyWords": ["population"] },
    { "chinese": "vt. 居住于，聚居于…中", "english": "populate", "type": "单词", "keyWords": [] },
    { "chinese": "生活于大洋洋底的生物", "english": "creatures that populate the ocean depths", "type": "短语", "keyWords": ["populate"] },
    { "chinese": "n. [U]猪肉", "english": "pork", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]港口", "english": "port", "type": "单词", "keyWords": [] },
    { "chinese": "a. 便于携带的；轻便的", "english": "portable", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]门卫；搬运工", "english": "porter", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]一部分；(从整体上分离出来的)一份", "english": "portion", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]肖像；画像", "english": "portrait", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]位置；方位；职位；地位；处境；姿势", "english": "position", "type": "单词", "keyWords": [] },
    { "chinese": "处于适当的位置(近in place)", "english": "in position", "type": "短语", "keyWords": ["position"] },
    { "chinese": "在不适当的位置，不得其所(近out of place)", "english": "out of position", "type": "短语", "keyWords": ["position"] },
    { "chinese": "处于有利地位", "english": "in a favorable position", "type": "短语", "keyWords": ["position"] },
    { "chinese": "使…处于尴尬的境地", "english": "put...in a ridiculous position", "type": "短语", "keyWords": ["position"] },
    { "chinese": "(没)有权利或能力做某事", "english": "in a/no position to do sth.", "type": "短语", "keyWords": ["position"] },
    { "chinese": "我不能借钱给你。", "english": "I'm not in a position to lend you money.", "type": "句子", "keyWords": ["position"] },
    { "chinese": "a. 积极的；明确的；确实的；肯定的；正的", "english": "positive", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 占有，拥有；具有(品质等)；*(也常用于被动)控制，主宰", "english": "possess", "type": "单词", "keyWords": [] },
    { "chinese": "他整天就想着发财。", "english": "The thought of getting rich possessed him.", "type": "句子", "keyWords": ["possess"] },
    { "chinese": "他整天就想着发财。", "english": "He was possessed by the thought of getting rich.", "type": "句子", "keyWords": ["possess"] },
    { "chinese": "n. [U]占有；拥有；n. [C](常pl.)财产", "english": "possession", "type": "单词", "keyWords": [] } 
];
qgl197_204.sort(() => Math.random() - 0.5);