const qgl1_8 = [
    { "chinese": "art. 一(个、件…);同一(个…);任何一(个…);每一(个…);某一", "english": "a", "type": "单词", "keyWords": [] },
    { "chinese": "art. 一(个、件…);同一(个…);任何一(个…);每一(个…);某一", "english": "an", "type": "单词", "keyWords": [] },
    { "chinese": "一张8英镑的优惠券", "english": "an 8-pound coupon", "type": "短语", "keyWords": ["an"] },
    { "chinese": "一轮新月", "english": "a new moon", "type": "短语", "keyWords": ["a"] },
    { "chinese": "一年两次", "english": "twice a year", "type": "短语", "keyWords": ["a"] },
    { "chinese": "一天5美元", "english": "$5 a day (=per day)", "type": "短语", "keyWords": ["a"] },
    { "chinese": "多么（接单数名词）", "english": "such/what a/a.n.../", "type": "短语", "keyWords": ["a"] },
    { "chinese": "这样一个物品/人", "english": "such a thing/ man", "type": "短语", "keyWords": ["a"] },
    { "chinese": "有些/非常难管的孩子（接单数名词）", "english": "rather/ quite a difficult child", "type": "短语", "keyWords": ["a"] },
    { "chinese": "许多父母…（注意many a后面接单数名词，并且与单数动词连用）", "english": "Many a parent is...", "type": "句子", "keyWords": ["a"] },
    { "chinese": "苏格拉底式的智慧", "english": "the wisdom of a Socrates", "type": "短语", "keyWords": ["a"] },
    { "chinese": "特朗普的搞笑视频", "english": "videos of a funny Trump", "type": "短语", "keyWords": ["a"] },
    { "chinese": "一两年", "english": "a year or two (= one or two years)", "type": "短语", "keyWords": ["a"] },
    { "chinese": "他们是同龄人。", "english": "They are of an age.", "type": "句子", "keyWords": ["an"] },
    { "chinese": "志趣相投的人", "english": "birds of a feather", "type": "短语", "keyWords": ["a"] },
    { "chinese": "请一次给我两个。", "english": "Please give me two at a time.", "type": "句子", "keyWords": ["a"] },
    { "chinese": "连续第五个年份的干旱预计将对加利福尼亚州的经济产生巨大影响。", "english": "A fifth year of drought is expected to have dramatic effects on California's economy.", "type": "句子", "keyWords": ["a"] },
    { "chinese": "v. 放弃；抛弃；遗弃", "english": "abandon", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 放弃；抛弃", "english": "abandonment", "type": "单词", "keyWords": ["abandon"] },
    { "chinese": "放弃沉船/尝试/希望/构思", "english": "abandon the sinking ship/ the attempt/ the hope/ the design", "type": "短语", "keyWords": ["abandon"] },
    { "chinese": "那个木匠遗弃了他的妻子和孩子。", "english": "The carpenter abandoned his wife and child.", "type": "句子", "keyWords": ["abandon"] },
    { "chinese": "n. [C][U] 能力；本领", "english": "ability", "type": "单词", "keyWords": [] },
    { "chinese": "有才干的人", "english": "a man of ability", "type": "短语", "keyWords": ["ability"] },
    { "chinese": "能…", "english": "have the ability to do sth.", "type": "短语", "keyWords": ["ability"] },
    { "chinese": "对多目标的分辨能力", "english": "an ability to distinguish between multiple targets", "type": "短语", "keyWords": ["ability"] },
    { "chinese": "附在动词或名词后构成形容词：①表示“可…的；能…的”；②表示“易…的；倾向于…的”；③表示“提供…的；与…有关的”", "english": "able", "type": "单词", "keyWords": [] },
    { "chinese": "有能力的，聪明能干的", "english": "able", "type": "单词", "keyWords": [] },
    { "chinese": "能干的人们", "english": "able men", "type": "短语", "keyWords": ["able"] },
    { "chinese": "成功地做成某事", "english": "was/ were able to do sth.", "type": "短语", "keyWords": ["able"] },
    { "chinese": "a. 反常的；异常的", "english": "abnormal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U] 反常；异常；畸形", "english": "abnormality", "type": "单词", "keyWords": ["abnormal"] },
    { "chinese": "我们一直都认为这样的反常现象不会持续很久。", "english": "Never do we think such an abnormal phenomenon will last long.", "type": "句子", "keyWords": ["abnormal"] },
    { "chinese": "prep. 在车（船、飞机）上；ad. 上车（船、飞机等）；在车（船、飞机）上", "english": "aboard", "type": "单词", "keyWords": [] },
    { "chinese": "她上了飞机。", "english": "She went aboard the plane.", "type": "句子", "keyWords": ["aboard"] },
    { "chinese": "欢迎登机。", "english": "(You are) Welcome aboard.", "type": "句子", "keyWords": ["aboard"] },
    { "chinese": "他已上车/船/飞机了。", "english": "He has gone aboard.", "type": "句子", "keyWords": ["aboard"] },
    { "chinese": "请大家上船/登机。", "english": "All aboard.", "type": "句子", "keyWords": ["aboard"] },
    { "chinese": "ad. 附近；大约；转向；周围，四周，到处；prep. 关于；大约；在…周围（无固定方向）；在…附近", "english": "about", "type": "单词", "keyWords": [] },
    { "chinese": "四处漂泊，无处可去", "english": "wander about with no place to go", "type": "短语", "keyWords": ["about"] },
    { "chinese": "他把书扔得到处都是。", "english": "He left books lying about/ dropped books about.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "这消息正在传开。", "english": "The news is going about.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "工作差不多要完成了。", "english": "The job is about done.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "…怎么样？/怎么办？", "english": "What/ How about (doing) sth.?", "type": "短语", "keyWords": ["about"] },
    { "chinese": "准备；将要；正打算", "english": "be about to do sth.", "type": "短语", "keyWords": ["about"] },
    { "chinese": "我正想说话，奥巴马就插嘴了。", "english": "I was about to speak when Obama cut in.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "…的时候了（表虚拟语气，也可用should）", "english": "It's about/ high time (+过去时分句).", "type": "短语", "keyWords": ["about"] },
    { "chinese": "该是你去找更有效治疗深度烧伤疗法的时候了。", "english": "It's about time you found/ should find a more effective therapy for deep burns.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "prep. 在…上面；a. 在…上面；ad. 在上面；向上面；n. [U] 上文", "english": "above", "type": "单词", "keyWords": [] },
    { "chinese": "看前面例子。", "english": "See the examples given above.", "type": "句子", "keyWords": ["above"] },
    { "chinese": "战士应该把荣誉看得高于生命。", "english": "A soldier should value honour above his life.", "type": "句子", "keyWords": ["above"] },
    { "chinese": "这个我理解不了。", "english": "It is above my comprehension/ understanding.", "type": "句子", "keyWords": ["above"] },
    { "chinese": "最重要的是，首先；尤其是", "english": "above all", "type": "短语", "keyWords": ["above"] },
    { "chinese": "海平面以上", "english": "above the sea level", "type": "短语", "keyWords": ["above"] },
    { "chinese": "以上提到的问题", "english": "the above-mentioned problems", "type": "短语", "keyWords": ["above"] },
    { "chinese": "由于上述原因", "english": "for the above reasons", "type": "短语", "keyWords": ["above"] },
    { "chinese": "比一般的要好，中上", "english": "above the average", "type": "短语", "keyWords": ["above"] },
    { "chinese": "ad. 在国外；往国外", "english": "abroad", "type": "单词", "keyWords": [] },
    { "chinese": "国内外新闻", "english": "the news at home and abroad", "type": "短语", "keyWords": ["abroad"] },
    { "chinese": "出国/去国外旅游", "english": "go/ get/ travel abroad", "type": "短语", "keyWords": ["abroad"] },
    { "chinese": "去国外留学", "english": "study abroad", "type": "短语", "keyWords": ["abroad"] },
    { "chinese": "n. [U]（可和of连用）不在，缺席；缺乏，没有，不存在", "english": "absence", "type": "单词", "keyWords": [] },
    { "chinese": "黑暗就是没有光亮。", "english": "Darkness is the absence of light.", "type": "句子", "keyWords": ["absence"] },
    { "chinese": "当他不在此地而在意大利的时候", "english": "in/ during his absence in Italy", "type": "短语", "keyWords": ["absence"] },
    { "chinese": "汤姆离开公司三个礼拜后，终于回来了。", "english": "Tom finally returned after an absence of three weeks from the company.", "type": "句子", "keyWords": ["absence"] },
    { "chinese": "a. 缺席的；不在场的；缺乏的", "english": "absent", "type": "单词", "keyWords": [] },
    { "chinese": "a. 茫然的；心不在焉的", "english": "absent-minded", "type": "单词", "keyWords": ["absent"] },
    { "chinese": "缺席，不在", "english": "be absent from", "type": "短语", "keyWords": ["absent"] },
    { "chinese": "那个代表没有出席年度大会。", "english": "The representative was absent from the annual conference.", "type": "句子", "keyWords": ["absent"] },
    { "chinese": "a. 完全的；不容置疑的；绝对的", "english": "absolute", "type": "单词", "keyWords": [] },
    { "chinese": "完全无知", "english": "absolute ignorance", "type": "短语", "keyWords": ["absolute"] },
    { "chinese": "ad. 完全地；极其；[美俚]（用于答话）是，当然是，正是如此", "english": "absolutely", "type": "单词", "keyWords": ["absolute"] },
    { "chinese": "这绝对不可能。", "english": "It's absolutely impossible.", "type": "句子", "keyWords": ["absolutely"] },
    { "chinese": "“你是这样想的吗？”“当然是。”", "english": '"Do you think so?" "Absolutely."', "type": "句子", "keyWords": ["absolutely"] },
    { "chinese": "v. 吸收；吸引…的注意力；接受", "english": "absorb", "type": "单词", "keyWords": [] },
    { "chinese": "吸引某人的注意力", "english": "absorb one's attention", "type": "短语", "keyWords": ["absorb"] },
    { "chinese": "从空气中吸收水分", "english": "absorb moisture from the air", "type": "短语", "keyWords": ["absorb"] },
    { "chinese": "专心致志于", "english": "be absorbed in", "type": "短语", "keyWords": ["absorb"] },
    { "chinese": "他专心读书。", "english": "He is absorbed in his study.", "type": "句子", "keyWords": ["absorb"] },
    { "chinese": "他专心致志工作，到了废寝忘食的地步。", "english": "Absorbed in the work, he neglected food and sleep.", "type": "句子", "keyWords": ["absorb"] },
    { "chinese": "n. [U] 吸收；专心致志（in）", "english": "absorption", "type": "单词", "keyWords": ["absorb"] },
    { "chinese": "显而易见，他专心于研究。", "english": "His complete absorption in study can be clearly seen.", "type": "句子", "keyWords": ["absorption"] },
    { "chinese": "a. 抽象的；n. [C] 摘要，梗概；v. 摘要；提炼；抽象化", "english": "abstract", "type": "单词", "keyWords": [] },
    { "chinese": "科技文摘，科学文摘", "english": "science abstract", "type": "短语", "keyWords": ["abstract"] },
    { "chinese": "从矿砂中提炼金属", "english": "abstract metal from ore", "type": "短语", "keyWords": ["abstract"] },
    { "chinese": "a. 大量的，充足的；丰富的，充裕的", "english": "abundant", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 丰富，充裕", "english": "abundance", "type": "单词", "keyWords": ["abundant"] },
    { "chinese": "a. 学院的；学术的，理论的", "english": "academic", "type": "单词", "keyWords": [] },
    { "chinese": "学年", "english": "academic year", "type": "短语", "keyWords": ["academic"] },
    { "chinese": "学术研究", "english": "academic research", "type": "短语", "keyWords": ["academic"] },
    { "chinese": "n. [C]（高等）专科院校，研究院，学会，学术团体，学院", "english": "academy", "type": "单词", "keyWords": ["academic"] },
    { "chinese": "n. [C] 重音；口音，腔调；重音符", "english": "accent", "type": "单词", "keyWords": [] },
    { "chinese": "爱尔兰腔调", "english": "an Irish accent", "type": "短语", "keyWords": ["accent"] },
    { "chinese": "v. 接受；认可", "english": "accept", "type": "单词", "keyWords": [] },
    { "chinese": "a. 公认的", "english": "accepted", "type": "单词", "keyWords": ["accept"] },
    { "chinese": "承受某人的命运", "english": "accept one's fate", "type": "短语", "keyWords": ["accept"] },
    { "chinese": "从…接受…", "english": "accept sth. from sb.", "type": "短语", "keyWords": ["accept"] },
    { "chinese": "他们接收我为俱乐部新成员。", "english": "They accepted me as a new member of the club.", "type": "句子", "keyWords": ["accept"] },
    { "chinese": "这样的风俗被普遍认同。", "english": "Such customs are widely accepted.", "type": "句子", "keyWords": ["accept"] },
    { "chinese": "人们普遍认为…", "english": "It is widely accepted that...", "type": "短语", "keyWords": ["accept"] },
    { "chinese": "作为公认的事实", "english": "an accepted fact", "type": "短语", "keyWords": ["accepted"] },
    { "chinese": "a. 可接受的", "english": "acceptable", "type": "单词", "keyWords": ["accept"] },
    { "chinese": "a. 不可接受的", "english": "unacceptable", "type": "单词", "keyWords": ["accept"] },
    { "chinese": "n. [C][U] 接受；承诺；容忍；赞同；相信", "english": "acceptance", "type": "单词", "keyWords": ["accept"] },
    { "chinese": "n. [U] 接近/进入的机会；享用权；通路；访问，入门；vt. [计] 存取；接近", "english": "access", "type": "单词", "keyWords": [] },
    { "chinese": "到镇上唯一的通路是经过这座桥。", "english": "The only access to the town is the bridge.", "type": "句子", "keyWords": ["access"] },
    { "chinese": "接近…的机会，进入…的权利", "english": "have/ get/ gain access to", "type": "短语", "keyWords": ["access"] },
    { "chinese": "5岁孩童中只有40%能享受学前教育。", "english": "Only 40% of 5-year-olds have access to preschool education.", "type": "句子", "keyWords": ["access"] },
    { "chinese": "市民可以免费使用图书馆。", "english": "Citizens may have free access to the library.", "type": "句子", "keyWords": ["access"] },
    { "chinese": "易于接近的人，平易近人的人", "english": "a man of easy access (=an accessible man)", "type": "短语", "keyWords": ["access"] },
    { "chinese": "容易/难接近", "english": "be easy/ hard of access", "type": "短语", "keyWords": ["access"] },
    { "chinese": "a. 容易达到的；易接近的", "english": "accessible", "type": "单词", "keyWords": ["access"] },
    { "chinese": "地区通邮率超过95%。", "english": "Over 95% of the district is accessible to postal services.", "type": "句子", "keyWords": ["accessible"] },
    { "chinese": "n. [C] 意外事件；事故", "english": "accident", "type": "单词", "keyWords": [] },
    { "chinese": "碰上/遭遇车祸/交通事故", "english": "meet with/ have a car/ traffic accident", "type": "短语", "keyWords": ["accident"] },
    { "chinese": "意外地", "english": "by accident/ chance (=accidentally)", "type": "短语", "keyWords": ["accident"] },
    { "chinese": "a. 偶然的；意外的", "english": "accidental", "type": "单词", "keyWords": ["accident"] },
    { "chinese": "v. 供给…住宿（或膳宿）；容纳", "english": "accommodate", "type": "单词", "keyWords": [] },
    { "chinese": "客人们受到很好的招待。", "english": "The guests are well accommodated.", "type": "句子", "keyWords": ["accommodate"] },
    { "chinese": "留（某人）住一夜", "english": "accommodate (sb.) for the night", "type": "短语", "keyWords": ["accommodate"] },
    { "chinese": "n. [U] 住处；膳宿；方便设施", "english": "accommodation", "type": "单词", "keyWords": ["accommodate"] },
    { "chinese": "我们会给您提供免费住宿。", "english": "We will offer you free accommodation.", "type": "句子", "keyWords": ["accommodation"] },
    { "chinese": "您的食宿将由我们来负责。", "english": "We will be responsible for your meals and accommodation.", "type": "句子", "keyWords": ["accommodation"] },
    { "chinese": "v. 陪伴，陪同；为…伴奏/伴唱；伴随；vi. 伴奏；伴唱", "english": "accompany", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 伴奏，伴随；陪伴物", "english": "accompaniment", "type": "单词", "keyWords": ["accompany"] },
    { "chinese": "伴随着打雷的闪电", "english": "lightning accompanied with thunder", "type": "短语", "keyWords": ["accompany"] },
    { "chinese": "给歌手伴奏", "english": "accompany the singer", "type": "短语", "keyWords": ["accompany"] },
    { "chinese": "他陪朋友去看电影。", "english": "He accompanied his friend to the film.", "type": "句子", "keyWords": ["accompany"] },
    { "chinese": "疾病常随饥荒而来。", "english": "Disease is often an accompaniment of famine.", "type": "句子", "keyWords": ["accompaniment"] },
    { "chinese": "v. 完成；达到；实现", "english": "accomplish", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U][C] 完成；成就", "english": "accomplishment", "type": "单词", "keyWords": ["accomplish"] },
    { "chinese": "实现目标/完成使命", "english": "accomplish one's purpose/ a goal/ one's mission", "type": "短语", "keyWords": ["accomplish"] },
    { "chinese": "一事无成/完成了一件任务", "english": "accomplish nothing/ a task", "type": "短语", "keyWords": ["accomplish"] },
    { "chinese": "a. 相符的，相应的", "english": "according", "type": "单词", "keyWords": [] },
    { "chinese": "根据…", "english": "according to", "type": "短语", "keyWords": ["according"] },
    { "chinese": "ad. 于是，因此；相应地", "english": "accordingly", "type": "单词", "keyWords": ["according"] },
    { "chinese": "n. [U] 一致，和谐；符合", "english": "accordance", "type": "单词", "keyWords": ["according"] },
    { "chinese": "根据条例行事", "english": "act in accordance with the rules", "type": "短语", "keyWords": ["accordance"] },
    { "chinese": "v. 说明，提出理由（for）；报账；（在数量、比例方面）占（for）；vt. 把…视作；把…归因于（to）；n. [C] 说明，陈述；理由；账户；计算，估计", "english": "account", "type": "单词", "keyWords": [] },
    { "chinese": "对…作出（满意的）解释；占", "english": "account for", "type": "短语", "keyWords": ["account"] },
    { "chinese": "延期那么久是因为坏天气。", "english": "Bad weather accounted for the long delay.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "他因为生病而缺席。", "english": "His illness accounted for his absence.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "电脑占了这个国家商业用电的5%。", "english": "Computers account for 5% of the country's commercial electricity consumption.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "认为自己是个成功人士", "english": "account oneself (to be) a success", "type": "短语", "keyWords": ["account"] },
    { "chinese": "把…归结于，把…归因于…", "english": "account sth. to...", "type": "短语", "keyWords": ["account"] },
    { "chinese": "归结到那个英雄身上的许多美德", "english": "the many virtues accounted to that hero", "type": "短语", "keyWords": ["account"] },
    { "chinese": "在银行开户", "english": "open/ get an account with the bank", "type": "短语", "keyWords": ["account"] },
    { "chinese": "你是何时在我们银行开账户的？", "english": "When did you get an account with us?", "type": "句子", "keyWords": ["account"] },
    { "chinese": "说明，叙述", "english": "give an account of (=describe)", "type": "短语", "keyWords": ["account"] },
    { "chinese": "因为，由于", "english": "on account of/ due to/ owing to/ because of/ as a result of/ thanks to", "type": "短语", "keyWords": ["account"] },
    { "chinese": "由于天气原因，比赛延期进行。", "english": "The match was postponed on account of the weather.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "决不可以，切勿", "english": "on no account/ by no means/ in no case/ under no condition/ on no occasion/ under no circumstances/ in no way", "type": "短语", "keyWords": ["account"] },
    { "chinese": "你绝不可以怀疑他撒谎。", "english": "On no account must you suspect him of lying.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "考虑进去", "english": "take...into account/ consideration", "type": "短语", "keyWords": ["account"] },
    { "chinese": "我们应该考虑父母的建议，反之亦然。", "english": "We should take into account the proposals of our parents and vice versa.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "n. [C] 会计人员", "english": "accountant", "type": "单词", "keyWords": ["account"] },
    { "chinese": "n. [U] 会计学；清算账目", "english": "accounting", "type": "单词", "keyWords": ["account"] },
    { "chinese": "a. 准确的（与事实、标准没出入）；精确的；正确无误的", "english": "accurate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 准确性；精确性", "english": "accuracy", "type": "单词", "keyWords": ["accurate"] },
    { "chinese": "准确地", "english": "with accuracy", "type": "短语", "keyWords": ["accuracy"] },
    { "chinese": "v. 指责；控告", "english": "accuse", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U][C] 指责", "english": "accusation", "type": "单词", "keyWords": ["accuse"] },
    { "chinese": "指责/控告某人某事", "english": "accuse sb. of sth. (=charge sb. with sth.)", "type": "短语", "keyWords": ["accuse"] },
    { "chinese": "他们控告他受贿。", "english": "They accused him of taking bribes.", "type": "句子", "keyWords": ["accuse"] },
    { "chinese": "被告，被控诉者", "english": "the accused", "type": "短语", "keyWords": ["accuse"] },
    { "chinese": "控告者，指责者", "english": "the accuser", "type": "短语", "keyWords": ["accuse"] },
    { "chinese": "被告人不承认所控之罪。", "english": "The accused (man) denied the charge.", "type": "句子", "keyWords": ["accuse"] },
    { "chinese": "v. 使习惯于", "english": "accustom", "type": "单词", "keyWords": [] },
    { "chinese": "使自己习惯于（做）某事", "english": "accustom oneself to (doing) sth.", "type": "短语", "keyWords": ["accustom"] },
    { "chinese": "我已习惯于长时间工作。", "english": "I have accustomed myself to working long hours.", "type": "句子", "keyWords": ["accustom"] },
    { "chinese": "a. 适应了的；习惯的", "english": "accustomed", "type": "单词", "keyWords": ["accustom"] },
    { "chinese": "习惯于", "english": "be/ become/ grow/ get accustomed to (doing) sth.", "type": "短语", "keyWords": ["accustomed"] },
    { "chinese": "我的眼睛很快适应了黑暗。", "english": "My eyes soon grew accustomed to the darkness.", "type": "句子", "keyWords": ["accustomed"] },
    { "chinese": "v. （持续而隐隐地）作痛；n. [C] 疼痛；酸痛", "english": "ache", "type": "单词", "keyWords": [] },
    { "chinese": "我全身骨头都痛了。", "english": "My bones ache.", "type": "句子", "keyWords": ["ache"] },
    { "chinese": "她感到肩膀隐隐作痛。", "english": "She felt an ache in her shoulder.", "type": "句子", "keyWords": ["ache"] },
    { "chinese": "v. （常强调通过努力）完成，实现；达到，得到", "english": "achieve", "type": "单词", "keyWords": [] },
    { "chinese": "一事无成/达到目的/取得成功", "english": "achieve nothing/ one's purpose/ success", "type": "短语", "keyWords": ["achieve"] },
    { "chinese": "n. [U][C] 成就；成绩", "english": "achievement", "type": "单词", "keyWords": ["achieve"] },
    { "chinese": "达到目的", "english": "the achievement of one's object", "type": "短语", "keyWords": ["achievement"] },
    { "chinese": "学业成绩；学术成就", "english": "academic achievements", "type": "短语", "keyWords": ["achievement"] },
    { "chinese": "a. 酸的；n. [U][C] [化] 酸", "english": "acid", "type": "单词", "keyWords": [] },
    { "chinese": "酸雨", "english": "acid rain", "type": "短语", "keyWords": ["acid"] },
    { "chinese": "v. 承认；告知/确认收到（信等）；对…表示感谢", "english": "acknowledge", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U][C] 承认，确认", "english": "acknowledgement", "type": "单词", "keyWords": ["acknowledge"] },
    { "chinese": "承认失败", "english": "acknowledge one's defeat", "type": "短语", "keyWords": ["acknowledge"] },
    { "chinese": "确认收到他的来信", "english": "acknowledge his letter", "type": "短语", "keyWords": ["acknowledge"] },
    { "chinese": "大家公认…", "english": "It is universally acknowledged that...", "type": "短语", "keyWords": ["acknowledge"] },
    { "chinese": "v. （通过自己的努力）取得，获得；学得", "english": "acquire", "type": "单词", "keyWords": [] },
    { "chinese": "精通", "english": "acquire a good knowledge of...", "type": "短语", "keyWords": ["acquire"] },
    { "chinese": "获得好名声", "english": "acquire a good reputation", "type": "短语", "keyWords": ["acquire"] },
    { "chinese": "a. 已获得的，通过自己后天努力得到的", "english": "acquired", "type": "单词", "keyWords": ["acquire"] },
    { "chinese": "n. [U][C] 获得", "english": "acquisition", "type": "单词", "keyWords": ["acquire"] },
    { "chinese": "信息采集/获取", "english": "information acquisition", "type": "短语", "keyWords": ["acquisition"] },
    { "chinese": "语言习得/掌握", "english": "language acquisition", "type": "短语", "keyWords": ["acquisition"] },
    { "chinese": "ad. 横过（从一边到另一边）；交叉地；在对面；prep. 横过；越过；交叉；在…的另一边；在…对面", "english": "across", "type": "单词", "keyWords": [] },
    { "chinese": "在纸上画交叉线", "english": "draw lines across the paper", "type": "短语", "keyWords": ["across"] },
    { "chinese": "抱臂坐着", "english": "be seated with arms across/ with arms crossed", "type": "短语", "keyWords": ["across"] },
    { "chinese": "他的办公室就在街对面。", "english": "His office is just across the street.", "type": "句子", "keyWords": ["across"] },
    { "chinese": "他在大厅的那一头和我说话。", "english": "He addressed me from across the hall.", "type": "句子", "keyWords": ["across"] },
    { "chinese": "vi. 行动；做事；表演；起作用；v. 扮演；n. [C] 行为，动作；法令；条例；（剧）幕", "english": "act", "type": "单词", "keyWords": [] },
    { "chinese": "他在作弊时被当场抓住。", "english": "He was caught in the (very) act of cheating.", "type": "句子", "keyWords": ["act"] },
    { "chinese": "独幕剧", "english": "a one-act play", "type": "短语", "keyWords": ["act"] },
    { "chinese": "代理经理", "english": "acting manager", "type": "短语", "keyWords": ["act"] },
    { "chinese": "表演", "english": "act...out", "type": "短语", "keyWords": ["act"] },
    { "chinese": "担当；充当", "english": "act as", "type": "短语", "keyWords": ["act"] },
    { "chinese": "这片森林将起到防御沙漠尘土的作用。", "english": "The forest will act as a defence against desert dust.", "type": "句子", "keyWords": ["act"] },
    { "chinese": "作用于心脏/移动的物体", "english": "act upon the heart/ the moving object", "type": "短语", "keyWords": ["act"] },
    { "chinese": "n. [U]（复杂抽象的）行动；动作；作用；战斗；n. [C] 行为", "english": "action", "type": "单词", "keyWords": ["act"] },
    { "chinese": "一个能干的妇女", "english": "a woman of action", "type": "短语", "keyWords": ["action"] },
    { "chinese": "阵亡", "english": "be killed in action", "type": "短语", "keyWords": ["action"] },
    { "chinese": "采取行动", "english": "take action/ put it into action/ take measures/ take steps", "type": "短语", "keyWords": ["action"] },
    { "chinese": "行动胜于空谈。", "english": "Actions speak louder than words.", "type": "句子", "keyWords": ["action"] },
    { "chinese": "a. 积极的；主动的；活跃的；勤奋的", "english": "active", "type": "单词", "keyWords": ["act"] },
    { "chinese": "ad. 积极地；勤奋地", "english": "actively", "type": "单词", "keyWords": ["active"] },
    { "chinese": "在政界相当活跃", "english": "be active in politics", "type": "短语", "keyWords": ["active"] },
    { "chinese": "积极参加", "english": "take an active part in", "type": "短语", "keyWords": ["active"] },
    { "chinese": "v. 刺激，使活动", "english": "activate", "type": "单词", "keyWords": ["active"] },
    { "chinese": "他的崇高精神大大激励了别人。", "english": "His lofty spirit has really activated others.", "type": "句子", "keyWords": ["activate"] },
    { "chinese": "n. [C] 活动", "english": "activity", "type": "单词", "keyWords": ["active"] },
    { "chinese": "社交活动，社会活动", "english": "social activities", "type": "短语", "keyWords": ["activity"] },
    { "chinese": "n. [C] 男演员", "english": "actor", "type": "单词", "keyWords": ["act"] },
    { "chinese": "n. [C] 女演员", "english": "actress", "type": "单词", "keyWords": ["act"] },
    { "chinese": "a. 事实上的；真实的；实际的", "english": "actual", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 事实上；实际上", "english": "actually", "type": "单词", "keyWords": ["actual"] },
    { "chinese": "事实上；实际上", "english": "in actual fact/ as a matter of fact/ actually", "type": "短语", "keyWords": ["actual"] },
    { "chinese": "v. （使）适应；（使）适合（为达到新要求而做出巨大改变）；改编", "english": "adapt", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 适应，改编；n. [C] 改写本", "english": "adaptation", "type": "单词", "keyWords": ["adapt"] },
    { "chinese": "随遇而安", "english": "adapt yourself to new customs", "type": "短语", "keyWords": ["adapt"] },
    { "chinese": "他很快就适应了高山气候。", "english": "He quickly adapted to the climate in the high mountains.", "type": "句子", "keyWords": ["adapt"] },
    { "chinese": "这部电影是由小说改编的。", "english": "The movie was adapted from a novel.", "type": "句子", "keyWords": ["adapt"] },
    { "chinese": "因地制宜的原则", "english": "the principle of adaptation to local conditions", "type": "短语", "keyWords": ["adaptation"] },
    { "chinese": "v. 增加，添加；计算…总和；补充说，又说；vi. 加，加起来；增添", "english": "add", "type": "单词", "keyWords": [] },
    { "chinese": "往…里加…", "english": "add...to...", "type": "短语", "keyWords": ["add"] },
    { "chinese": "火上浇油", "english": "add fuel to the flame", "type": "短语", "keyWords": ["add"] },
    { "chinese": "再往名单上加几个名字", "english": "add a few more names to the list", "type": "短语", "keyWords": ["add"] },
    { "chinese": "雪上加霜；进一步伤人感情", "english": "add insult to injury", "type": "短语", "keyWords": ["add"] },
    { "chinese": "40加50等于90。", "english": "Forty added to/ plus fifty makes ninety.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "增加；对…起增添作用", "english": "add to", "type": "短语", "keyWords": ["add"] },
    { "chinese": "食品开销的上涨增加了我们的困难。", "english": "The rise in food costs has added to our difficulties.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "实际上，这使得经济更加稳定。", "english": "Indeed, this should add to economic stability.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "把…全加起来", "english": "add (all the numbers) up", "type": "短语", "keyWords": ["add"] },
    { "chinese": "总计达；[口] 总括起来；意味着", "english": "add up to", "type": "短语", "keyWords": ["add"] },
    { "chinese": "三角形的三个角总和是180度。", "english": "The three angles of a triangle add up to 180.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "我认为这些事实不说明任何问题。", "english": "I do not think these facts will add up to anything.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "n. [U] 加；增加，加法；n. [C] 增加物；增加的人", "english": "addition", "type": "单词", "keyWords": ["add"] },
    { "chinese": "除了…之外，另外", "english": "in addition to", "type": "短语", "keyWords": ["addition"] },
    { "chinese": "除了伤亡之外，还有许多人失踪。", "english": "In addition to the dead and wounded, many were missing.", "type": "句子", "keyWords": ["addition"] },
    { "chinese": "a. 附加的；额外的", "english": "additional", "type": "单词", "keyWords": ["addition"] },
    { "chinese": "阻止额外热量的散失至关重要。", "english": "Preventing additional heat loss is of great importance.", "type": "句子", "keyWords": ["additional"] },
    { "chinese": "v. 使沉溺，使入迷；使成瘾；使（某人）染上（某些恶习）；n. 入迷的人；有瘾的人", "english": "addict", "type": "单词", "keyWords": [] },
    { "chinese": "a. 成瘾的；沉迷的", "english": "addicted", "type": "单词", "keyWords": ["addict"] },
    { "chinese": "沉迷在…中", "english": "be addicted to", "type": "短语", "keyWords": ["addict"] },
    { "chinese": "a. 附加的，添加的；n. [C] 添加剂", "english": "additive", "type": "单词", "keyWords": ["add"] },
    { "chinese": "食品添加剂", "english": "food additives", "type": "短语", "keyWords": ["additive"] },
    { "chinese": "食用色素添加剂", "english": "color food additive", "type": "短语", "keyWords": ["additive"] },
    { "chinese": "n. [C] 讲话；称呼；演讲；地址；住址；v. 向…讲话；给…写上姓名和地址；忙着做，处理", "english": "address", "type": "单词", "keyWords": [] },
    { "chinese": "信中的称呼形式", "english": "form of address in the letter", "type": "短语", "keyWords": ["address"] },
    { "chinese": "致开幕词/闭幕词", "english": "deliver an opening/ a closing address", "type": "短语", "keyWords": ["address"] },
    { "chinese": "（话）讲给…；把（信）写给…", "english": "address...to...", "type": "短语", "keyWords": ["address"] },
    { "chinese": "向大会/国民发表演说", "english": "address the meeting/ the nation", "type": "短语", "keyWords": ["address"] },
    { "chinese": "给信写上地址", "english": "address the letter", "type": "短语", "keyWords": ["address"] },
    { "chinese": "处理问题", "english": "address an issue", "type": "短语", "keyWords": ["address"] },
    { "chinese": "我应当怎样称呼您呢？", "english": "How shall I address you?", "type": "句子", "keyWords": ["address"] },
    { "chinese": "a. 足够的；适当的", "english": "adequate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 足够", "english": "adequacy", "type": "单词", "keyWords": ["adequate"] },
    { "chinese": "给城市居民供给充足的水源已经成为所有政府不能掉以轻心的问题。", "english": "An adequate water supply for city people is already a problem no government can take lightly.", "type": "句子", "keyWords": ["adequate"] },
    { "chinese": "v. 调整；调节（1.把人或东西调整到准确的位置或状态 2.纠正；校准）", "english": "adjust", "type": "单词", "keyWords": [] },
    { "chinese": "调整手表/望远镜/室温", "english": "adjust one's watch/ the telescope/ the temperature of the house", "type": "短语", "keyWords": ["adjust"] },
    { "chinese": "调整自己以适应新环境", "english": "adjust yourself to new conditions", "type": "短语", "keyWords": ["adjust"] },
    { "chinese": "a. 可调整的", "english": "adjustable", "type": "单词", "keyWords": ["adjust"] },
    { "chinese": "n. [U][C] 调整，调节，调节器", "english": "adjustment", "type": "单词", "keyWords": ["adjust"] },
    { "chinese": "v. 管理；经营；支配", "english": "administrate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 管理；经营；n. [C] 管理部门，行政机关", "english": "administration", "type": "单词", "keyWords": ["administrate"] },
    { "chinese": "a. 管理的；行政的", "english": "administrative", "type": "单词", "keyWords": ["administration"] },
    { "chinese": "（高等学校）教务处；学术行政", "english": "academic administration", "type": "短语", "keyWords": ["administration"] },
    { "chinese": "美国联邦航空管理局", "english": "Federal Aviation Administration", "type": "短语", "keyWords": ["administration"] },
    { "chinese": "管理/经营才能", "english": "administrative ability", "type": "短语", "keyWords": ["administrative"] },
    { "chinese": "行政单位", "english": "an administrative unit", "type": "短语", "keyWords": ["administrative"] },
    { "chinese": "v. 赞赏，钦佩，羡慕", "english": "admire", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 钦佩地，羡慕地", "english": "admiringly", "type": "单词", "keyWords": ["admire"] },
    { "chinese": "n. [C] 赞赏者，敬慕者", "english": "admirer", "type": "单词", "keyWords": ["admire"] },
    { "chinese": "钦佩某人的…", "english": "admire sb. for...", "type": "短语", "keyWords": ["admire"] },
    { "chinese": "所有在场者都佩服她良好的记忆力和出色的表演。", "english": "Everybody present admired her for her good memory and performance.", "type": "句子", "keyWords": ["admire"] },
    { "chinese": "赞赏地看了他一眼", "english": "give him an admiring glance", "type": "短语", "keyWords": ["admiringly"] },
    { "chinese": "v. 承认；准许…进入/加入；录用；vi. 容许，给…留有余地（of）", "english": "admit", "type": "单词", "keyWords": [] },
    { "chinese": "承认做某事", "english": "admit doing sth.", "type": "短语", "keyWords": ["admit"] },
    { "chinese": "她承认偷了文件。", "english": "She admitted stealing/ having stolen the document.", "type": "句子", "keyWords": ["admit"] },
    { "chinese": "被那所大学录取", "english": "be admitted into/ to the university", "type": "短语", "keyWords": ["admit"] },
    { "chinese": "n. [U][C] 许可入场/入学/入会；录用；承认；入场费", "english": "admission", "type": "单词", "keyWords": ["admit"] },
    { "chinese": "认罪", "english": "an admission of guilt", "type": "短语", "keyWords": ["admission"] },
    { "chinese": "获准进入", "english": "gain/ obtain admission to/ into", "type": "短语", "keyWords": ["admission"] },
    { "chinese": "只能凭考试成绩进入这所大学。", "english": "Admission to the college is by examination only.", "type": "句子", "keyWords": ["admission"] },
    { "chinese": "a. 青春期的；青少年的；n. [C]（尤指16岁以下的）青少年", "english": "adolescent", "type": "单词", "keyWords": [] },
    { "chinese": "v. 采纳；通过，批准；收养", "english": "adopt", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U][C] 采纳；批准；收养", "english": "adoption", "type": "单词", "keyWords": ["adopt"] },
    { "chinese": "一名领养儿童", "english": "an adopted child", "type": "短语", "keyWords": ["adopt"] },
    { "chinese": "采纳的解决方案（后置定语）", "english": "the solution adopted/ chosen", "type": "短语", "keyWords": ["adopt"] },
    { "chinese": "v. 崇拜，敬爱，爱慕；[口] 极度喜爱", "english": "adore", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可爱的", "english": "adorable", "type": "单词", "keyWords": ["adore"] },
    { "chinese": "n. [U] 崇拜，敬爱", "english": "adoration", "type": "单词", "keyWords": ["adore"] },
    { "chinese": "姐妹俩很喜欢看电影。", "english": "The two sisters adored (going to) the cinema.", "type": "句子", "keyWords": ["adore"] },
    { "chinese": "n. [C] 成年人；a. 成年的", "english": "adult", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 成年", "english": "adulthood", "type": "单词", "keyWords": ["adult"] },
    { "chinese": "n. [U][C] 前进；提升；vi. 前进，向前移动；v. 使向前移动；促进；提前；提出", "english": "advance", "type": "单词", "keyWords": [] },
    { "chinese": "职务晋升", "english": "an advance in rank", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "预先，提前", "english": "in advance", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "我们不得不提前两周交付租金。", "english": "We had to pay the rent two weeks in advance.", "type": "句子", "keyWords": ["advance"] },
    { "chinese": "预付（收）", "english": "pay/ receive in advance", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "超越了他的时代", "english": "in advance of his time", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "随着冬天的来临，白天变短了。", "english": "With the advance of winter the days grow shorter.", "type": "句子", "keyWords": ["advance"] },
    { "chinese": "努力发展生产", "english": "advance production energetically", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "一个月过去了，但工作无任何进展。", "english": "A month has passed and the work has not advanced.", "type": "句子", "keyWords": ["advance"] },
    { "chinese": "a. 先进的，高级的；年迈的", "english": "advanced", "type": "单词", "keyWords": ["advance"] },
    { "chinese": "n. [U] 进步，进展（指比喻意义上的进步或提高）", "english": "advancement", "type": "单词", "keyWords": ["advance"] },
    { "chinese": "先进的工业国家", "english": "the advanced industrial nations", "type": "短语", "keyWords": ["advanced"] },
    { "chinese": "他年事已高。", "english": "He is advanced in years.", "type": "句子", "keyWords": ["advanced"] },
    { "chinese": "学业/知识/科学上的进步", "english": "advancement of learning/ knowledge/ science", "type": "短语", "keyWords": ["advancement"] },
    { "chinese": "n. [C] 优越性，有利方面；n. [U] 优势，有利条件，利益", "english": "advantage", "type": "单词", "keyWords": [] },
    { "chinese": "明智地投资对你很有利。", "english": "It is to your advantage to invest wisely.", "type": "句子", "keyWords": ["advantage"] },
    { "chinese": "利用；占…的便宜", "english": "take advantage of", "type": "短语", "keyWords": ["advantage"] },
    { "chinese": "你应当抓住每一次赔钱的机会，提高你对市场行为的了解。", "english": "You should take advantage of every loss to prove your knowledge of market action.", "type": "句子", "keyWords": ["advantage"] },
    { "chinese": "你应该对他们的过失加以利用。", "english": "You should take advantage of their mistakes.", "type": "句子", "keyWords": ["advantage"] },
    { "chinese": "占/获得/赢得优势", "english": "have/ gain/ win an advantage over", "type": "短语", "keyWords": ["advantage"] },
    { "chinese": "陶器的优点在于比木器更容易保持清洁。", "english": "Earthenware has an advantage over wood in being more easily kept clean.", "type": "句子", "keyWords": ["advantage"] }
];
qgl1_8.sort(() => Math.random() - 0.5);
