const qgl205_212 = [
    { "chinese": "获得/占有/购得某物", "english": "be in possession of sth.", "type": "短语", "keyWords": ["possession"] },
    { "chinese": "被某人占有；某物落入某人手中", "english": "be in the possession of sb.", "type": "短语", "keyWords": ["possession"] },
    { "chinese": "物落入某人手中", "english": "sth. comes into the possession of sb.", "type": "短语", "keyWords": ["possession"] },
    { "chinese": "某人得到/占有某物", "english": "sb. comes into possession of sth.", "type": "短语", "keyWords": ["possession"] },
    { "chinese": "a. 可能的", "english": "possible", "type": "单词", "keyWords": [] },
    { "chinese": "尽可能好的方法", "english": "the best possible method = the best method possible", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "尽可能早/快地", "english": "as soon as possible", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "如果可能的话", "english": "if (it is) possible", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "(某人)有可能做某事", "english": "It is possible (for sb.) to do sth.", "type": "句子", "keyWords": ["possible"] },
    { "chinese": "即使不见得会发生，至少是可能的", "english": "possible, if not probable", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "使……成为可能（宾语较长时后置）", "english": "make sth. possible (make possible sth.)", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "n. [U] 可能（性）；[C] 可能发生的事物", "english": "possibility", "type": "单词", "keyWords": [] },
    { "chinese": "他不可能来的。", "english": "There is no possibility/ chance/ hope of his coming.", "type": "句子", "keyWords": ["possibility"] },
    { "chinese": "n. [C] 柱；标杆；职务，职位；（军警）岗位，哨位；[U] 邮政；vt. 张贴（布告等）；邮寄，投寄", "english": "post", "type": "单词", "keyWords": [] },
    { "chinese": "表示“在…之后”，例如：postgraduate 研究生，postwar 战后的", "english": "post-（前缀）", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 邮费，邮资", "english": "postage", "type": "单词", "keyWords": [] },
    { "chinese": "邮资已付", "english": "postage paid", "type": "短语", "keyWords": ["postage"] },
    { "chinese": "免付邮费", "english": "postage free", "type": "短语", "keyWords": ["postage"] },
    { "chinese": "a. 邮政的；邮局的", "english": "postal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 明信片", "english": "postcard", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [英] 邮政编码", "english": "postcode", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 海报，招贴；布告", "english": "poster", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 邮递员", "english": "postman", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 邮政局（或所）长", "english": "postmaster", "type": "单词", "keyWords": [] },
    { "chinese": "v. 推迟；使延期", "english": "postpone", "type": "单词", "keyWords": [] },
    { "chinese": "推迟做某事", "english": "postpone/ put off doing sth.", "type": "短语", "keyWords": ["postpone"] },
    { "chinese": "暂缓答复", "english": "postpone/ put off sending an answer", "type": "短语", "keyWords": ["postpone"] },
    { "chinese": "n. [C] 罐；壶", "english": "pot", "type": "单词", "keyWords": [] },
    { "chinese": "熔化锅；大熔炉，各种民族融合的国家/地方", "english": "a melting pot", "type": "短语", "keyWords": ["pot"] },
    { "chinese": "心急喝不了热粥。", "english": "A watched pot never boils.", "type": "句子", "keyWords": ["pot"] },
    { "chinese": "n. [C] (pl. potatoes) 土豆", "english": "potato", "type": "单词", "keyWords": [] },
    { "chinese": "红薯", "english": "a sweet potato", "type": "短语", "keyWords": ["potato"] },
    { "chinese": "沙发上的土豆；花过多时间坐着或躺着的人（常为看电视）", "english": "a couch potato", "type": "短语", "keyWords": ["potato"] },
    { "chinese": "棘手的问题，烫手的山芋；难对付的人", "english": "a hot potato", "type": "短语", "keyWords": ["potato"] },
    { "chinese": "a. 可能的；潜在的；n. [U] 可能性；潜在性；潜能", "english": "potential", "type": "单词", "keyWords": [] },
    { "chinese": "潜在的问题/危险", "english": "a potential problem/ danger", "type": "短语", "keyWords": ["potential"] },
    { "chinese": "n. [C] 英镑（符号）；磅", "english": "pound", "type": "单词", "keyWords": [] },
    { "chinese": "v. 倒；不断流出；吐出，倾诉；vi. 倒；下倾盆大雨；涌出/入", "english": "pour", "type": "单词", "keyWords": [] },
    { "chinese": "对（想法、计划）泼冷水", "english": "pour cold water on...", "type": "短语", "keyWords": ["pour"] },
    { "chinese": "吐出一肚子的苦水", "english": "pour out all one's bitternes", "type": "短语", "keyWords": ["pour"] },
    { "chinese": "涌入/出大厅", "english": "pour into/ out of the hall", "type": "短语", "keyWords": ["pour"] },
    { "chinese": "火上浇油；煽动情绪", "english": "pour oil on the flames", "type": "短语", "keyWords": ["pour"] },
    { "chinese": "不雨则已，一雨倾盆。祸不单行。", "english": "It never rains but it pours.", "type": "句子", "keyWords": ["pour"] },
    { "chinese": "n. [U] 贫穷，穷困；贫乏，不足", "english": "poverty", "type": "单词", "keyWords": [] },
    { "chinese": "过穷日子", "english": "live in poverty", "type": "短语", "keyWords": ["poverty"] },
    { "chinese": "n. [U] 粉末；火药；v. 给…搽粉；使成粉末", "english": "powder", "type": "单词", "keyWords": [] },
    { "chinese": "搽粉", "english": "powder one's face", "type": "短语", "keyWords": ["powder"] },
    { "chinese": "速溶奶粉", "english": "instant powdered milk", "type": "短语", "keyWords": ["powder"] },
    { "chinese": "n. [U] 力；电力；能力；权力；政权；[C] 强国；有势力的人；幂；vt. 给…提供动力，使开动", "english": "power", "type": "单词", "keyWords": [] },
    { "chinese": "上台；执政", "english": "come into/to power", "type": "短语", "keyWords": ["power"] },
    { "chinese": "在执政；在掌权", "english": "in power", "type": "短语", "keyWords": ["power"] },
    { "chinese": "有宣战的权力", "english": "have the power to declare war", "type": "短语", "keyWords": ["power"] },
    { "chinese": "我不能以更低的价格出售。", "english": "It is beyond my power to sell it cheaper.", "type": "句子", "keyWords": ["power"] },
    { "chinese": "核潜艇", "english": "a nuclear-powered submarine", "type": "短语", "keyWords": ["power"] },
    { "chinese": "100 的四次幂", "english": "the fourth power of 100", "type": "短语", "keyWords": ["power"] },
    { "chinese": "a. 强有力的；大功率的", "english": "powerful", "type": "单词", "keyWords": [] },
    { "chinese": "a. 无能为力的；无权力的", "english": "powerless", "type": "单词", "keyWords": [] },
    { "chinese": "a. 实践的；实用的；实际的", "english": "practical", "type": "单词", "keyWords": [] },
    { "chinese": "恶作剧", "english": "a practical joke", "type": "短语", "keyWords": ["practical"] },
    { "chinese": "a. 不切实际的；无用的", "english": "impractical", "type": "单词", "keyWords": [] },
    { "chinese": "理论上的", "english": "theoretical", "type": "单词", "keyWords": [] },
    { "chinese": "v. 练习；经常做；实习；实践；（医生、律师）开业", "english": "practise（英式）/ practice（美式）", "type": "单词", "keyWords": [] },
    { "chinese": "练习/常做某事", "english": "practise/ practice (doing) sth.", "type": "短语", "keyWords": ["practise"] },
    { "chinese": "我从前开业当律师/开业行医，但现在我教英文。", "english": "I used to practice law/ medicine, but now I teach English.", "type": "句子", "keyWords": ["practise"] },
    { "chinese": "n. [U] 练习；实践；[C] 习惯（做法）；习俗；（医生、律师、会计）开业", "english": "practice", "type": "单词", "keyWords": [] },
    { "chinese": "社会实践", "english": "social practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "在实践中；实际上；在不断练习中", "english": "in practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "将…付诸实施", "english": "put (a plan, a theory...) into practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "一个难以付诸实践的理论", "english": "a theory that is difficult to put into practice", "type": "句子", "keyWords": ["practice"] },
    { "chinese": "风俗，习惯", "english": "a common practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "按照国际惯例", "english": "according to the international practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "从事律师业", "english": "the practice of law", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "v. 赞扬，表扬；n. [U] 赞扬，表扬；(pl.) 赞词，赞美之辞", "english": "praise", "type": "单词", "keyWords": [] },
    { "chinese": "因为某事表扬某人", "english": "praise sb. for sth.", "type": "短语", "keyWords": ["praise"] },
    { "chinese": "高度赞扬某人", "english": "sing high praise for/ sing sb's praises", "type": "短语", "keyWords": ["praise"] },
    { "chinese": "v. 祈祷；祈求；vt. 请求，恳求；[宗] 祈祷；n. 祷辞；祈望；[U] 祈祷", "english": "pray", "type": "单词", "keyWords": [] },
    { "chinese": "祈求做某事", "english": "pray to do sth.", "type": "短语", "keyWords": ["pray"] },
    { "chinese": "为了某事而祈祷", "english": "pray (to God) for sth.", "type": "短语", "keyWords": ["pray"] },
    { "chinese": "祈求某事", "english": "pray that...", "type": "短语", "keyWords": ["pray"] },
    { "chinese": "做祷告", "english": "say one's prayers", "type": "短语", "keyWords": ["pray"] },
    { "chinese": "表示“在…前；预先；前面”，如：prefix 前缀；prehistoric 史前的", "english": "pre-（前缀）", "type": "单词", "keyWords": [] },
    { "chinese": "a. 珍贵的；贵重的", "english": "precious", "type": "单词", "keyWords": [] },
    { "chinese": "宝石，钻石", "english": "precious stones", "type": "短语", "keyWords": ["precious"] },
    { "chinese": "a. 精确的；准确的", "english": "precise", "type": "单词", "keyWords": [] },
    { "chinese": "v. 预言；预报；n. [C]/[U] 预言", "english": "predict", "type": "单词", "keyWords": [] },
    { "chinese": "v. 宁可；更喜欢；n. 偏爱；[C] 更喜欢的东西", "english": "prefer", "type": "单词", "keyWords": [] },
    { "chinese": "n. 偏爱", "english": "preference", "type": "单词", "keyWords": [] },
    { "chinese": "偏爱某物", "english": "have a preference for sth.", "type": "短语", "keyWords": ["preference"] },
    { "chinese": "比起 B 来更喜欢 A", "english": "prefer (doing) A to (doing) B", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "宁愿…也不…", "english": "(would) prefer to do sth. rather than do sth. else = would rather do sth. than do sth. else", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "宁愿…", "english": "(would) prefer that... (do...)", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "我希望房间里有中央空调。", "english": "I prefer that the room (should) be fitted with central air conditioning.", "type": "句子", "keyWords": ["prefer"] },
    { "chinese": "宁愿；情愿", "english": "prefer doing/to do sth.", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "宁愿；情愿", "english": "would prefer to do sth.", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "宁愿；情愿", "english": "would prefer sb. to do...", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "A 比 B 好；A 比 B 更可取。", "english": "A is preferable to B.", "type": "句子", "keyWords": ["prefer"] },
    { "chinese": "a. 怀孕的，妊娠的；n. [U] 怀孕", "english": "pregnant", "type": "单词", "keyWords": [] },
    { "chinese": "怀着孩子/新思想", "english": "be pregnant with a child/ new ideas", "type": "短语", "keyWords": ["pregnant"] },
    { "chinese": "n. [U]/[C] 偏见，成见", "english": "prejudice", "type": "单词", "keyWords": [] },
    { "chinese": "对…抱有偏见", "english": "have a prejudice against...", "type": "短语", "keyWords": ["prejudice"] },
    { "chinese": "n. [U] 准备；预备；[C] 准备工作", "english": "preparation", "type": "单词", "keyWords": [] },
    { "chinese": "为某事做准备", "english": "make preparations for sth.", "type": "短语", "keyWords": ["preparation"] },
    { "chinese": "准备中", "english": "in preparation (for...)", "type": "短语", "keyWords": ["preparation"] },
    { "chinese": "v. 准备；预备", "english": "prepare", "type": "单词", "keyWords": [] },
    { "chinese": "(使某人)为…准备", "english": "prepare (sb.) for sth.", "type": "短语", "keyWords": ["prepare"] },
    { "chinese": "为…做好准备", "english": "be prepared for sth.", "type": "短语", "keyWords": ["prepare"] },
    { "chinese": "你还是做好最坏的打算。", "english": "Prepare yourself for the worst.", "type": "句子", "keyWords": ["prepare"] },
    { "chinese": "乐于/愿意做某事", "english": "be prepared/ ready to do sth.", "type": "短语", "keyWords": ["prepare"] },
    { "chinese": "n. [U] 在场；出席", "english": "presence", "type": "单词", "keyWords": [] },
    { "chinese": "请你务必出席。", "english": "Your presence is urgently required.", "type": "句子", "keyWords": ["presence"] },
    { "chinese": "在…面前", "english": "in the presence of sb./sth. (in sb's presence)", "type": "短语", "keyWords": ["presence"] },
    { "chinese": "她在生人/困难面前感到很不安。", "english": "She was ill at ease in the presence of strangers/ difficulties.", "type": "句子", "keyWords": ["presence"] },
    { "chinese": "n. [C] 礼物；(the present) 现在，目前；a. 现在的，目前的；存在的；出席的（作定语时后置）；vt. /prɪˈzent/ 赠送；授予；提供；呈现；描述", "english": "present", "type": "单词", "keyWords": [] },
    { "chinese": "现在，目前", "english": "at present (n.) = at the present time (a.)", "type": "短语", "keyWords": ["present"] },
    { "chinese": "眼前；暂时", "english": "for the present moment", "type": "短语", "keyWords": ["present"] },
    { "chinese": "现政府", "english": "the present government", "type": "短语", "keyWords": ["present"] },
    { "chinese": "出席", "english": "be present at...", "type": "短语", "keyWords": ["present"] },
    { "chinese": "目前的状况关系到所有在场的学生。", "english": "The present situation concerns all the students present.（后置定语）", "type": "句子", "keyWords": ["present"] },
    { "chinese": "赠送；提供", "english": "present sth. to sb. / present (provide) sb. with sth.", "type": "短语", "keyWords": ["present"] },
    { "chinese": "这份计划呈送给了艾登。", "english": "The plan was presented to Eden.", "type": "句子", "keyWords": ["present"] },
    { "chinese": "n. [U] 呈现；授课；赠送；上演；[C] 演示；介绍；陈述", "english": "presentation", "type": "单词", "keyWords": [] },
    { "chinese": "对…作陈述/演示", "english": "give a presentation of...", "type": "短语", "keyWords": ["presentation"] },
    { "chinese": "ad. 不久；即刻", "english": "presently", "type": "单词", "keyWords": [] },
    { "chinese": "v. 保护；保存（食品等）", "english": "preserve", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 保存", "english": "preservation", "type": "单词", "keyWords": ["preserve"] },
    { "chinese": "保存参考资料", "english": "preserve reference materials", "type": "短语", "keyWords": ["preserve"] },
    { "chinese": "维护秩序", "english": "preserve order (=keep order)", "type": "短语", "keyWords": ["preserve"] },
    { "chinese": "咸蛋；皮蛋", "english": "a preserved egg", "type": "短语", "keyWords": ["preserve"] },
    { "chinese": "n. [C] 总统；（公司等的）总裁，董事长", "english": "president", "type": "单词", "keyWords": [] },
    { "chinese": "a. 总统的", "english": "presidential", "type": "单词", "keyWords": ["president"] },
    { "chinese": "v. 压；压平；使贴紧；催促；n. [C] 压；印刷业；(the press) 新闻界，报业，报刊", "english": "press", "type": "单词", "keyWords": [] },
    { "chinese": "不要逼迫他们高谈科学和民主。", "english": "Don't press them to talk about science and democracy.", "type": "句子", "keyWords": ["press"] },
    { "chinese": "他向新闻界透露了那消息。", "english": "He leaked the news to the press.", "type": "句子", "keyWords": ["press"] },
    { "chinese": "记者招待会", "english": "a press/ news conference", "type": "短语", "keyWords": ["press"] },
    { "chinese": "(书报等) 付印", "english": "go to press", "type": "短语", "keyWords": ["press"] },
    { "chinese": "n. [U] 压；[C]/[U] 压力", "english": "pressure", "type": "单词", "keyWords": [] },
    { "chinese": "给…施压", "english": "put pressure on sb. or sth.", "type": "短语", "keyWords": ["pressure"] },
    { "chinese": "压力锅，高压锅", "english": "pressure cooker", "type": "短语", "keyWords": ["pressure"] },
    { "chinese": "在…的压力下", "english": "under the pressure of...", "type": "短语", "keyWords": ["pressure"] },
    { "chinese": "气/血压", "english": "air/ blood pressure", "type": "短语", "keyWords": ["pressure"] },
    { "chinese": "v. 假装", "english": "pretend", "type": "单词", "keyWords": [] },
    { "chinese": "假装做某事/在做某事/已做某事", "english": "pretend to do sth./ to be doing sth./ to have done sth.", "type": "短语", "keyWords": ["pretend"] },
    { "chinese": "a. 漂亮的，美丽的；可爱的，机灵的；ad. 相当；颇", "english": "pretty", "type": "单词", "keyWords": [] },
    { "chinese": "v. 阻止；妨碍（被动句中不省略 from）", "english": "prevent", "type": "单词", "keyWords": [] },
    { "chinese": "阻止某人/某物做某事", "english": "prevent sb./sth. (from) doing sth.", "type": "短语", "keyWords": ["prevent"] },
    { "chinese": "（近 stop/keep/hold back/ban/prohibit sb. from doing sth.；这些动词需要跟带 to 的不定式：forbid/permit/allow sb. to do sth.）", "english": "(近 stop/keep/hold back/ban/prohibit sb. from doing sth.；这些动词需要跟带 to 的不定式：forbid/permit/allow sb. to do sth.)", "type": "句子", "keyWords": ["prevent"] },
    { "chinese": "n. [U] 阻止；预防（可和 a 连用）；a. 预防性的", "english": "prevention", "type": "单词", "keyWords": ["prevent"] },
    { "chinese": "治病不如防病。", "english": "Prevention is better than cure.", "type": "句子", "keyWords": ["prevention"] },
    { "chinese": "v. 预习；预演；试映；预展", "english": "preview", "type": "单词", "keyWords": [] },
    { "chinese": "a. 前的", "english": "previous", "type": "单词", "keyWords": [] },
    { "chinese": "代表大会于我们访问的前一天召开。", "english": "The congress had assembled on the day previous to our visit.", "type": "句子", "keyWords": ["previous"] },
    { "chinese": "n. [U] 猎物，捕获物；捕食；vi. 捕食", "english": "prey", "type": "单词", "keyWords": [] },
    { "chinese": "捕食斑马", "english": "prey on zebras", "type": "短语", "keyWords": ["prey"] },
    { "chinese": "鹿被狮子捕食了。（比较：fall victim to）", "english": "The deer fell prey to the lion.", "type": "句子", "keyWords": ["prey"] },
    { "chinese": "n. [C] 价格；代价；vt. 给…定价或标价", "english": "price", "type": "单词", "keyWords": [] },
    { "chinese": "a. 无价的，极贵重的", "english": "priceless", "type": "单词", "keyWords": ["price"] },
    { "chinese": "无论花多大代价；无论如何", "english": "at any price", "type": "短语", "keyWords": ["price"] },
    { "chinese": "他决心不惜任何代价达到他的目的。", "english": "He will accomplish his purpose at any price.", "type": "句子", "keyWords": ["price"] },
    { "chinese": "自己不想要的东西，再便宜都觉得贵。", "english": "A thing you do not want is dear at any price.", "type": "句子", "keyWords": ["price"] },
    { "chinese": "以…价格", "english": "at the price of...", "type": "短语", "keyWords": ["price"] },
    { "chinese": "他们牺牲了很多人才赢得了战役的胜利。", "english": "They won the battle at the price of many lives.", "type": "句子", "keyWords": ["price"] },
    { "chinese": "每张票定价 200 元。", "english": "The tickets are priced at 200 yuan each.", "type": "句子", "keyWords": ["price"] },
    { "chinese": "n. [U] 自豪；骄傲；v. [pride oneself on/upon] 以…自豪；vi. 自豪；骄傲；得意", "english": "pride", "type": "单词", "keyWords": [] },
    { "chinese": "直到最近，该大学还以其友好的形象而自豪。", "english": "Until recently the university prided itself on/upon its friendly image.", "type": "句子", "keyWords": ["pride"] },
    { "chinese": "伤害某人的自尊心", "english": "wound sb's pride", "type": "短语", "keyWords": ["pride"] },
    { "chinese": "为…感到自豪", "english": "take pride in...", "type": "短语", "keyWords": ["pride"] },
    { "chinese": "骄者必败。", "english": "Pride goes before a fall.", "type": "句子", "keyWords": ["pride"] },
    { "chinese": "a. 最初的；初等的；主要的；基本的", "english": "primary", "type": "单词", "keyWords": [] },
    { "chinese": "词的原义", "english": "primary meaning of a word", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "初等教育，小学教育", "english": "primary education", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "（指红、黄、蓝）基色，原色", "english": "primary colour", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "头等重要的事情", "english": "a matter of primary importance", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "首相；总理", "english": "prime minister", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "(广播或电视的) 黄金时段", "english": "prime time", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "n. [C] 王子", "english": "prince", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 公主", "english": "princess", "type": "单词", "keyWords": ["prince"] },
    { "chinese": "a. 最重要的；主要的；n. [C] 为首者；校长", "english": "principal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 原理；原则", "english": "principle", "type": "单词", "keyWords": [] },
    { "chinese": "原则上", "english": "in principle", "type": "短语", "keyWords": ["principle"] },
    { "chinese": "根据既定的原则，按照规定/习惯", "english": "on principle", "type": "短语", "keyWords": ["principle"] },
    { "chinese": "v. 印刷；[计] 打印；打上（印记等）；铭记", "english": "print", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 印刷，印刷术；[C] 一次印刷", "english": "printing", "type": "单词", "keyWords": ["print"] },
    { "chinese": "n. [U]（时间、顺序上的）先，前；优先，重点；优先权；[C] 优先考虑的事", "english": "priority", "type": "单词", "keyWords": [] },
    { "chinese": "a. 优先的；在前/先的（to）", "english": "prior", "type": "单词", "keyWords": [] },
    { "chinese": "给予…优先权", "english": "give (first) priority to...", "type": "短语", "keyWords": ["priority"] },
    { "chinese": "在…方面比…享有优先权", "english": "have/enjoy priority over sb. in sth.", "type": "短语", "keyWords": ["priority"] },
    { "chinese": "予以最优先考虑的事", "english": "a first priority", "type": "短语", "keyWords": ["priority"] },
    { "chinese": "准备函数的上传工作要先于结束计算的过程。", "english": "The functions are available for uploading prior to finishing computation.", "type": "句子", "keyWords": ["priority"] },
    { "chinese": "n. [C]/[U] 监狱；监禁", "english": "prison", "type": "单词", "keyWords": [] },
    { "chinese": "v. 监禁", "english": "imprison", "type": "单词", "keyWords": ["prison"] },
    { "chinese": "在坐牢", "english": "be in prison", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "去坐牢", "english": "go to prison", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "战俘集中营", "english": "a prison camp", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "把某人关进监狱", "english": "cast/throw/put sb. into prison", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "(近 bar sb. in)", "english": "(近 bar sb. in)", "type": "句子", "keyWords": ["prison"] },
    { "chinese": "把某人关进监狱", "english": "send/take sb. to prison", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "n. [C] 囚犯；俘虏", "english": "prisoner", "type": "单词", "keyWords": [] },
    { "chinese": "战俘（略作 P.O.W. 或 POW）", "english": "prisoner(s) of war", "type": "短语", "keyWords": ["prisoner"] },
    { "chinese": "被俘（只用单数，无冠词）", "english": "be taken prisoner", "type": "短语", "keyWords": ["prisoner"] },
    { "chinese": "除了当俘虏之外，唯一的选择就是战死。", "english": "The only alternative to being taken prisoner was to die fighting.", "type": "句子", "keyWords": ["prisoner"] },
    { "chinese": "a. 私人（用）的；私有的", "english": "private", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 隐私", "english": "privacy", "type": "单词", "keyWords": ["private"] },
    { "chinese": "秘密地；私下地", "english": "in private", "type": "短语", "keyWords": ["private"] },
    { "chinese": "n. [C] 奖品；奖赏；adj. 作为奖品的；vt. 重视，珍视；估价，评价", "english": "prize", "type": "单词", "keyWords": [] },
    { "chinese": "赢得头奖", "english": "win first prize", "type": "短语", "keyWords": ["prize"] },
    { "chinese": "莫言，真名管漠业，获2012年诺贝尔文学奖。", "english": "Mo Yan, whose real name is Guan Moye, won the 2012 Nobel Prize in Literature.", "type": "句子", "keyWords": ["prize"] },
    { "chinese": "n. [C] 赞成的观点", "english": "pro", "type": "单词", "keyWords": [] },
    { "chinese": "权衡正反两方面的意见", "english": "weigh the pros and cons", "type": "短语", "keyWords": ["pro"] },
    { "chinese": "a. 很可能发生的；大概的", "english": "probable", "type": "单词", "keyWords": [] },
    { "chinese": "成功是有可能的，但不一定。", "english": "Success is possible but hardly probable.", "type": "句子", "keyWords": ["probable"] },
    { "chinese": "极有可能…", "english": "It is probable to do sth./ that...", "type": "短语", "keyWords": ["probable"] },
    { "chinese": "ad. 大概；很可能，极有可能；或许", "english": "probably", "type": "单词", "keyWords": ["probable"] },
    { "chinese": "n. [C] 问题；习题", "english": "problem", "type": "单词", "keyWords": [] },
    { "chinese": "(表示乐意帮忙) 没问题；(回答感谢) 没关系", "english": "no problem", "type": "短语", "keyWords": ["problem"] },
    { "chinese": "n. [C] 程序；手续；(为完成某事采取的一系列) 步骤", "english": "procedure", "type": "单词", "keyWords": [] },
    { "chinese": "v. 继续进行（近 go on，后接 to sth./to do sth. 指做另一件事，接 with 则指开始做或继续做同一件事）；向前走（近 go, advance；后接 to a place）", "english": "proceed", "type": "单词", "keyWords": [] },
    { "chinese": "着手另一工作", "english": "proceed to the next business", "type": "短语", "keyWords": ["proceed"] },
    { "chinese": "v. 处理；加工；n. [C] 过程；(尤指工业上的) 生产过程，方法；程序", "english": "process", "type": "单词", "keyWords": [] },
    { "chinese": "数据处理", "english": "data processing", "type": "短语", "keyWords": ["process"] },
    { "chinese": "在进行中", "english": "in process", "type": "短语", "keyWords": ["process"] },
    { "chinese": "在…期间/过程中", "english": "in (the) process of...", "type": "短语", "keyWords": ["process"] },
    { "chinese": "v. 制造；生产；引起；拿出，出示；n. /ˈprɒdjuːs/ [U] 农产品", "english": "produce", "type": "单词", "keyWords": [] },
    { "chinese": "监制一出舞台剧", "english": "produce a stage play", "type": "短语", "keyWords": ["produce"] },
    { "chinese": "提出证据", "english": "produce evidence", "type": "短语", "keyWords": ["produce"] },
    { "chinese": "手伸进口袋，拿出了一盒火柴", "english": "reach into a pocket and produce a packet of matches", "type": "句子", "keyWords": ["produce"] },
    { "chinese": "土特产（品）", "english": "the native produce", "type": "短语", "keyWords": ["produce"] },
    { "chinese": "n. [C] 产品", "english": "product", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 生产；产量；出示", "english": "production", "type": "单词", "keyWords": ["product"] },
    { "chinese": "a. 生产的；富有成效的；多产的", "english": "productive", "type": "单词", "keyWords": ["product"] },
    { "chinese": "多产作家/高产的农场", "english": "a productive writer/ farm", "type": "短语", "keyWords": ["productive"] },
    { "chinese": "n. [C] 职业", "english": "profession", "type": "单词", "keyWords": [] },
    { "chinese": "职业是…", "english": "by profession", "type": "短语", "keyWords": ["profession"] },
    { "chinese": "他职业是电气技师。", "english": "He is an electrical engineer by profession.", "type": "句子", "keyWords": ["profession"] },
    { "chinese": "n. [C] 专业人员；a. 职业（性）的，专业的；内行的", "english": "professional", "type": "单词", "keyWords": [] },
    { "chinese": "v. (使) 职业化", "english": "professionalize", "type": "单词", "keyWords": ["professional"] },
    { "chinese": "n. [C] 大学教授", "english": "professor", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 利润；收益；n. [U] 好处；益处；v. (使) 得益；(使) 赚钱", "english": "profit", "type": "单词", "keyWords": [] },
    { "chinese": "出售某物而获利", "english": "sell sth. at a profit", "type": "短语", "keyWords": ["profit"] },
    { "chinese": "从…中获利…", "english": "make a profit of $,000 from...", "type": "短语", "keyWords": ["profit"] },
    { "chinese": "受益于（他的忠告）", "english": "profit from (his advice)", "type": "短语", "keyWords": ["profit"] },
    { "chinese": "a. 有利的；有赢利的", "english": "profitable", "type": "单词", "keyWords": ["profit"] },
    { "chinese": "n. [C] 节目，节目单；计划，方案；程序；v. 为…安排节目或制定计划；使按预定计划或步骤工作；[计] 为…编制程序", "english": "program(me)", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] [计] 编程；(广播等) 节目编排", "english": "programming", "type": "单词", "keyWords": ["program"] },
    { "chinese": "n. [U] 进步；进展；前进，行进；vi. /prəˈgres/ 前进；进展", "english": "progress", "type": "单词", "keyWords": [] },
    { "chinese": "a. 进步的；前进的", "english": "progressive", "type": "单词", "keyWords": ["progress"] },
    { "chinese": "在（英语）方面取得进步", "english": "make progress (in English)", "type": "短语", "keyWords": ["progress"] },
    { "chinese": "在进展中", "english": "in progress", "type": "短语", "keyWords": ["progress"] },
    { "chinese": "v. 禁止；阻止（辨析见 ban）", "english": "prohibit", "type": "单词", "keyWords": [] },
    { "chinese": "妨碍/阻止某事", "english": "prohibit (doing) sth.", "type": "短语", "keyWords": ["prohibit"] },
    { "chinese": "阻止某人做某事", "english": "prohibit sb. from doing sth.", "type": "短语", "keyWords": ["prohibit"] },
    { "chinese": "(近 keep/hold back/prevent/ban/stop sb. from doing sth.，这些动词需要跟带 to 的不定式：forbid/permit/allow sb. to do sth.)", "english": "(近 keep/hold back/prevent/ban/stop sb. from doing sth.，这些动词需要跟带 to 的不定式：forbid/permit/allow sb. to do sth.)", "type": "句子", "keyWords": ["prohibit"] },
    { "chinese": "n. [C] 计划，规划，方案；工程，企业；科研项目；(学校的) 课题；作业；v. /prəˈdʒekt/ 计划，规划；放映，投射；提出", "english": "project", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 放映机；投影仪", "english": "projector", "type": "单词", "keyWords": ["project"] },
    { "chinese": "推出一个更好的系统", "english": "project a better system", "type": "短语", "keyWords": ["project"] },
    { "chinese": "将一束光投射到墙上", "english": "project a beam of light on the wall", "type": "短语", "keyWords": ["project"] },
    { "chinese": "n. [C] 允诺；诺言；v. /ˈprɒmɪs/ [U] 有希望；可能会；a. 有希望的，有前途的", "english": "promise", "type": "单词", "keyWords": [] },
    { "chinese": "许诺某人某物", "english": "promise sb. sth.", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "答应去做某事", "english": "promise to do sth.", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "答应某人要去做某事", "english": "promise sb. to do sth.", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "答应（某人）某事", "english": "promise (sb.) that...", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "我保证不久你就会见到他们。", "english": "I promise you shall see them again before long.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "我敢肯定。说句老实话。我警告你。", "english": "I promise you.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "晴朗的天空预示好天气。", "english": "The clear sky promises fine weather.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "明天有希望是个好天。", "english": "It promises to be fine tomorrow.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "云预示着有可能下雨。", "english": "The clouds promise rain.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "一定有发展的企业", "english": "an enterprise that promises well", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "违背诺言", "english": "break a promise", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "履行诺言", "english": "carry out one's promise", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "许下诺言", "english": "make/give a promise", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "守约", "english": "stick to/keep one's promise/word", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "大有希望的，前程远大的", "english": "of (great) promise", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "一个很有前途的年轻演员（=a promising young player）", "english": "a young player of great promise", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "v. 提升（to）；使（学生）升级；促进；促销（产品）", "english": "promote", "type": "单词", "keyWords": [] },
    { "chinese": "提升为上尉", "english": "be promoted to the rank of captain", "type": "短语", "keyWords": ["promote"] },
    { "chinese": "促进增长/理解", "english": "promote growth/understanding", "type": "短语", "keyWords": ["promote"] },
    { "chinese": "促销新产品", "english": "promote a new product", "type": "短语", "keyWords": ["promote"] },
    { "chinese": "n. [C]/[U] 促进；提拔；宣传，推销", "english": "promotion", "type": "单词", "keyWords": ["promote"] },
    { "chinese": "v. 发音；宣布；宣称", "english": "pronounce", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 发音；[C] 发音法", "english": "pronunciation", "type": "单词", "keyWords": ["pronounce"] },
    { "chinese": "n. [U] 证明；[C] 证据；a. 耐…的；能防…的", "english": "proof", "type": "单词", "keyWords": [] },
    { "chinese": "防水的", "english": "water-proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "防弹的", "english": "bullet-proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "防火的", "english": "fire-proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "抗震的", "english": "shock-proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "缩水的织物", "english": "a fabric (which is) proof against shrinkage", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "出示凭据", "english": "give proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "a. 适当的，正当的（反 improper）", "english": "proper", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 财产；[C]/[U]（房）地产；[C] 性能；特性，属性", "english": "property", "type": "单词", "keyWords": [] },
    { "chinese": "公共财产", "english": "public property", "type": "短语", "keyWords": ["property"] },
    { "chinese": "金属性能", "english": "the metal properties", "type": "短语", "keyWords": ["property"] },
    { "chinese": "他有一小块房地产。", "english": "He has a small property.", "type": "句子", "keyWords": ["property"] },
    { "chinese": "n. [C]（整体内各部分之间和谐的）比例；部分", "english": "proportion", "type": "单词", "keyWords": [] },
    { "chinese": "调味时油和醋的适当比例", "english": "the proper proportion between oil and vinegar in the dressing", "type": "短语", "keyWords": ["proportion"] },
    { "chinese": "成比例地；相应地", "english": "in proportion (to sth.)", "type": "短语", "keyWords": ["proportion"] },
    { "chinese": "一般而言，上述各数之间存在一定的反比例关系。", "english": "In general, the figures mentioned above are to some extent in inverse proportion.", "type": "句子", "keyWords": ["proportion"] },
    { "chinese": "要注意使你的支出与收入一定相称。", "english": "See to it that your expenditure is in fixed proportion to your income.", "type": "句子", "keyWords": ["proportion"] },
    { "chinese": "n. [C] 提议；建议", "english": "proposal", "type": "单词", "keyWords": [] },
    { "chinese": "提议", "english": "present/ put forward/ put forth/ make a proposal", "type": "短语", "keyWords": ["proposal"] },
    { "chinese": "v. 提议，建议（+doing）；计划，打算（+to do）", "english": "propose", "type": "单词", "keyWords": [] },
    { "chinese": "提议早点出发", "english": "propose an early start = propose we (should) start early = propose starting early", "type": "短语", "keyWords": ["propose"] },
    { "chinese": "（近 suggest）", "english": "(近 suggest)", "type": "句子", "keyWords": ["propose"] },
    { "chinese": "打算做某事", "english": "propose to do sth.", "type": "短语", "keyWords": ["propose"] },
    { "chinese": "（近 mean/intend to do sth.）", "english": "(近 mean/intend to do sth.)", "type": "句子", "keyWords": ["propose"] },
    { "chinese": "我打算每月还贷20美元。", "english": "I propose to repay the loan at $20 a month.", "type": "句子", "keyWords": ["propose"] },
    { "chinese": "向某人求婚", "english": "*propose to sb.", "type": "短语", "keyWords": ["propose"] },
    { "chinese": "n. [C] 预期；景色；前景；v. /prəˈspekt/ 勘探；勘察（for）", "english": "prospect", "type": "单词", "keyWords": [] },
    { "chinese": "前途乐观；前景美好。", "english": "The prospect is cheerful.", "type": "句子", "keyWords": ["prospect"] },
    { "chinese": "破产的危险正逐渐加大。", "english": "The prospect of bankruptcy is getting greater.", "type": "句子", "keyWords": ["prospect"] },
    { "chinese": "勘探石油", "english": "prospect for oil", "type": "短语", "keyWords": ["prospect"] },
    { "chinese": "v. 保护；防护（辨析见 defend）", "english": "protect", "type": "单词", "keyWords": [] },
    { "chinese": "保护某人免受…的侵害", "english": "protect... from/against sth.", "type": "短语", "keyWords": ["protect"] },
    { "chinese": "保护儿童免受暴力侵犯", "english": "protect children from violence", "type": "短语", "keyWords": ["protect"] },
    { "chinese": "保护你的眼睛免受太阳光的伤害", "english": "protect your eyes from sunshine", "type": "短语", "keyWords": ["protect"] },
    { "chinese": "n. [U] 保护，防护；[C] 保护物（from/against）", "english": "protection", "type": "单词", "keyWords": ["protect"] },
    { "chinese": "a. 保护性的，防护性的", "english": "protective", "type": "单词", "keyWords": ["protect"] },
    { "chinese": "n. [C] 保护者；保护物；[器] 保护装置", "english": "protector", "type": "单词", "keyWords": ["protect"] },
    { "chinese": "n. [C]/[U] 蛋白质", "english": "protein", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 抗议；异议，反对；v. /prəˈtest/ 抗议；（对-）提出异议", "english": "protest", "type": "单词", "keyWords": [] },
    { "chinese": "抗议；提出异议", "english": "(make a) protest about/against/at...", "type": "短语", "keyWords": ["protest"] },
    { "chinese": "人们对新税种提出抗议。", "english": "The people protested/ made a protest against the new tax.", "type": "句子", "keyWords": ["protest"] },
    { "chinese": "抗议游行", "english": "protest march", "type": "短语", "keyWords": ["protest"] },
    { "chinese": "乖乖地；心甘情愿地", "english": "without protest", "type": "短语", "keyWords": ["protest"] },
    { "chinese": "a. 自豪的，骄傲的", "english": "proud", "type": "单词", "keyWords": [] },
    { "chinese": "为…而感到自豪", "english": "be proud of...", "type": "短语", "keyWords": ["proud"] },
    { "chinese": "v. 证明；证实；vi. 证明是；结果是，原来是", "english": "prove", "type": "单词", "keyWords": [] },
    { "chinese": "这将向世人证明这幅画是赝品。", "english": "This will prove to the world that the painting is a fake.", "type": "句子", "keyWords": ["prove"] },
    { "chinese": "她证明自己无罪了吗？", "english": "Did she prove herself (to be) innocent?", "type": "句子", "keyWords": ["prove"] },
    { "chinese": "证明是；结果是，原来是", "english": "prove/ turn out (to be) + adj.", "type": "短语", "keyWords": ["prove"] },
    { "chinese": "谣言结果并不总是事实。", "english": "A rumour doesn't always prove (to be) a fact.", "type": "句子", "keyWords": ["prove"] },
    { "chinese": "他原来是个医生。", "english": "He proved (to be) a doctor.", "type": "句子", "keyWords": ["prove"] },
    { "chinese": "n. [C] 谚语；常言；格言", "english": "proverb", "type": "单词", "keyWords": [] },
    { "chinese": "俗话说…", "english": "As the proverb goes/says...", "type": "短语", "keyWords": ["proverb"] },
    { "chinese": "俗话说，一个萝卜一个坑儿。", "english": "Every pot, as the proverb has it, finds its cover.", "type": "句子", "keyWords": ["proverb"] },
    { "chinese": "v. 供给；提供（辨析见 afford）", "english": "provide", "type": "单词", "keyWords": [] },
    { "chinese": "n. [pl.] 供应品；[U] 供给；供应", "english": "provision", "type": "单词", "keyWords": ["provide"] },
    { "chinese": "为某人提供某物", "english": "provide/equip/supply sb. with sth.", "type": "短语", "keyWords": ["provide"] },
    { "chinese": "他们的食品不足。", "english": "They are ill provided with food.", "type": "句子", "keyWords": ["provide"] },
    { "chinese": "为某人提供某物", "english": "provide sth. for sb.", "type": "短语", "keyWords": ["provide"] },
    { "chinese": "（近 supply sth. to sb./feed sb. with sth.）", "english": "(近 supply sth. to sb./feed sb. with sth.)", "type": "句子", "keyWords": ["provide"] },
    { "chinese": "如果；在…条件下（if）", "english": "provided (that)/providing (that)", "type": "短语", "keyWords": ["provide"] },
    { "chinese": "只要双方共同努力，中日关系的前景一定是光明的。", "english": "Provided that China and Japan make joint efforts, the Sino-Japanese relations must have a bright future.", "type": "句子", "keyWords": ["provide"] },
    { "chinese": "n. [C] 省；行政区", "english": "province", "type": "单词", "keyWords": [] },
    { "chinese": "a. 省的", "english": "provincial", "type": "单词", "keyWords": ["province"] },
    { "chinese": "n. [C] 心理学", "english": "psychology", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 心理学家", "english": "psychologist", "type": "单词", "keyWords": ["psychology"] },
    { "chinese": "a. 心理（学）的", "english": "psychological", "type": "单词", "keyWords": ["psychology"] },
    { "chinese": "n. [C] 酒馆，客栈；酒吧", "english": "pub", "type": "单词", "keyWords": [] },
    { "chinese": "a. 大众的，公共的；公开的", "english": "public", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 宣传；推广；广告", "english": "publicity", "type": "单词", "keyWords": ["public"] },
    { "chinese": "v. （尤指用广告）宣传；引人注意", "english": "publicize", "type": "单词", "keyWords": ["public"] },
    { "chinese": "ad. 公开地", "english": "publicly", "type": "单词", "keyWords": ["public"] },
    { "chinese": "当众，公开地", "english": "in public (=publicly)", "type": "短语", "keyWords": ["public"] },
    { "chinese": "（用作单或复数）公众", "english": "the public", "type": "短语", "keyWords": ["public"] },
    { "chinese": "民意，舆论", "english": "public opinion", "type": "短语", "keyWords": ["public"] },
    { "chinese": "公共交通工具", "english": "public transport", "type": "短语", "keyWords": ["public"] },
    { "chinese": "公开…", "english": "make... public", "type": "短语", "keyWords": ["public"] },
    { "chinese": "（近 make... known）", "english": "(近 make... known)", "type": "句子", "keyWords": ["public"] },
    { "chinese": "对公众开放", "english": "be open to the public", "type": "短语", "keyWords": ["public"] },
    { "chinese": "n. [U] 出版；发行；[C] 出版物", "english": "publication", "type": "单词", "keyWords": ["public"] },
    { "chinese": "v. 出版；发行；发表，公布", "english": "publish", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 出版者，发行人", "english": "publisher", "type": "单词", "keyWords": ["publish"] },
    { "chinese": "出版社", "english": "a publishing house", "type": "短语", "keyWords": ["publish"] },
    { "chinese": "n. [C]/[U] 布丁（西餐中最后上的一道松软甜食）", "english": "pudding", "type": "单词", "keyWords": [] },
    { "chinese": "v. 拉，拖；n. [U]（可加 a）拉，扯；（吸）引力", "english": "pull", "type": "单词", "keyWords": [] },
    { "chinese": "做鬼脸", "english": "pull a face", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "（近 =make a face）", "english": "(近 =make a face)", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "愁眉苦脸", "english": "pull a long face", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "拉扯…", "english": "pull at...", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "然后那猫用尖利的爪子拉扯自己的毛。", "english": "Then the cat pulled at its own fur with its sharp claws.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "(车辆) 驶离（路边）；离开；后退；(v.) 拉走", "english": "pull (away)", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "她企图从抓着她的那个男人挣脱出来。", "english": "She tried to pull away from the man who was holding her.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "(火车) 进站；(车辆等) 驶向路边停车", "english": "pull in", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "汽车开到车库停住了。", "english": "The car pulled in at the garage.", "type": "句子", "keyWords": ["pull"] }
];
qgl205_212.sort(() => Math.random() - 0.5);
