const qgl213_220 = [
    { "chinese": "v.拔出；拉出；（火车）离站；（船）划出", "english": "pull out", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "v.使停住；提起；停住", "english": "pull up", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "拆除（房子）；把…拉倒/下来", "english": "pull (the house...) down", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "（指匆忙时）穿上，戴上", "english": "pull...on", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "(使车、船)驶向/到路边或岸边", "english": "pull over", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "(使)恢复健康或度过危机", "english": "pull through (v./n.)", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "拉一下绳子", "english": "give a pull at the rope", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "n.[C]（毛线）套衫", "english": "pullover /'pʊləʊvə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]脉搏；有节奏的搏动", "english": "pulse /pʌls/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "给某人诊脉", "english": "feel sb.'s pulse", "type": "短语", "keyWords": ["pulse"] },
    { "chinese": "n.[C]泵 v.(用泵)抽(水)；用打气筒打(气)(up)", "english": "pump /pʌmp/ n.[C] v.", "type": "单词", "keyWords": [] },
    { "chinese": "往轮胎里打气", "english": "pump air into a tyre = pump up a tire", "type": "短语", "keyWords": ["pump"] },
    { "chinese": "为经济注入新生命", "english": "pump new life into the economy", "type": "短语", "keyWords": ["pump"] },
    { "chinese": "心脏使血液循环。", "english": "The heart pumps blood.", "type": "句子", "keyWords": ["pump"] },
    { "chinese": "n.[C]南瓜", "english": "pumpkin /'pʌmpkɪn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.守时的；准时的", "english": "punctual /'pʌŋktjʊəl/ adj.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]标点(符号)", "english": "punctuation /ˌpʌŋktʃʊ'eɪʃn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "一个标点符号", "english": "a punctuation mark", "type": "短语", "keyWords": ["punctuation"] },
    { "chinese": "v.罚，处罚 n.[C]惩罚，处罚", "english": "punish /'pʌnɪʃ/ v. punishment n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "因某事通过某方式惩罚某人", "english": "punish sb. for (doing) sth. by doing sth.", "type": "短语", "keyWords": ["punish"] },
    { "chinese": "n.[C]小学生；学生；[C]瞳孔", "english": "pupil /'pjuːpl/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]小狗", "english": "puppy /'pʌpɪ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "v./n.[U]采购；购买 n.[C]所购物", "english": "purchase /'pɜːtʃəs/ v./n.[U] n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "购买", "english": "make purchases", "type": "短语", "keyWords": ["purchase"] },
    { "chinese": "(社会)购买力", "english": "(social) purchasing power", "type": "短语", "keyWords": ["purchase"] },
    { "chinese": "adj.纯的；完美的；*十足的，完全的(反impure) *purify v.使纯净；净化 *purity n.[U]纯净，纯洁，纯度", "english": "pure /pjʊə/ adj. *purify v. *purity n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "十足的浪费时间", "english": "a pure waste of time", "type": "短语", "keyWords": ["pure"] },
    { "chinese": "n.[U]紫色 adj.紫色的", "english": "purple /'pɜːpl/ n.[U] adj.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]目的；意图(辨析见aim) purposeful a.有目的的(反purposeless)", "english": "purpose /'pɜːpəs/ n.[C] purposeful a.", "type": "单词", "keyWords": [] },
    { "chinese": "故意地；有意地", "english": "on purpose", "type": "短语", "keyWords": ["purpose"] },
    { "chinese": "为的是；为了…的目的", "english": "for the purpose of...", "type": "短语", "keyWords": ["purpose"] },
    { "chinese": "n.[C]钱包；女用小包", "english": "purse /'pɜːs/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "v.追逐，追捕；继续；从事", "english": "pursue /pə'sjuː/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "追击敌人", "english": "pursue the enemy", "type": "短语", "keyWords": ["pursue"] },
    { "chinese": "从事研究", "english": "pursue one's studies", "type": "短语", "keyWords": ["pursue"] },
    { "chinese": "寻欢作乐", "english": "pursue pleasure", "type": "短语", "keyWords": ["pursue"] },
    { "chinese": "继续讨论", "english": "pursue a discussion", "type": "短语", "keyWords": ["pursue"] },
    { "chinese": "对世界人民我们一贯奉行友好政策。", "english": "We have always pursued a friendly policy towards the people all over the world.", "type": "句子", "keyWords": ["pursue"] },
    { "chinese": "n.[U]追捕；追求 n.(C)爱好", "english": "pursuit /pə'sjuːt/ n.[U] n.(C)", "type": "单词", "keyWords": [] },
    { "chinese": "追求，寻求(近in search of)", "english": "in pursuit of", "type": "短语", "keyWords": ["pursuit"] },
    { "chinese": "v.推，推动；敦促 n.[C]推，推动；奋发", "english": "push /pʊʃ/ v. n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "推开门", "english": "push a door open", "type": "短语", "keyWords": ["push"] },
    { "chinese": "从人群中挤出", "english": "push one's way through a crowd", "type": "短语", "keyWords": ["push"] },
    { "chinese": "推动某人去做某事", "english": "push sb. to do sth. = push sb. into doing sth.", "type": "短语", "keyWords": ["push"] },
    { "chinese": "鞭策这孩子更努力地学习", "english": "push a child to study harder", "type": "短语", "keyWords": ["push"] },
    { "chinese": "向前推进，奋力前进", "english": "push on", "type": "短语", "keyWords": ["push"] },
    { "chinese": "我在大雪中努力前进。", "english": "I pushed on through the snow.", "type": "句子", "keyWords": ["push"] },
    { "chinese": "坚决进行(下去)，继续(进行)", "english": "*push on/ahead with", "type": "短语", "keyWords": ["push"] },
    { "chinese": "继续贯彻这个计划", "english": "push ahead with the plan", "type": "短语", "keyWords": ["push"] },
    { "chinese": "她使劲一推，门开了。", "english": "She gave the door a hard push, and it opened.", "type": "句子", "keyWords": ["push"] },
    { "chinese": "v.放；表达，说；使处于某状态", "english": "put /pʊt/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "把…收起，放好；存储", "english": "put...away", "type": "短语", "keyWords": ["put"] },
    { "chinese": "请你把餐具擦干，收拾好。", "english": "Please dry the dishes and put them away.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "她存了不少钱。", "english": "She has a nice sum of money put away.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "放下；记下；镇压", "english": "put...down", "type": "短语", "keyWords": ["put"] },
    { "chinese": "制止流言", "english": "put down rumors", "type": "短语", "keyWords": ["put"] },
    { "chinese": "扫平叛乱", "english": "put down a rebellion", "type": "短语", "keyWords": ["put"] },
    { "chinese": "提出；建议；把(钟表指针)前拨", "english": "put forward", "type": "短语", "keyWords": ["put"] },
    { "chinese": "关掉，熄灭；脱掉；推迟；让…下车；*使讨厌", "english": "put...off", "type": "短语", "keyWords": ["put"] },
    { "chinese": "你想在哪儿下车？", "english": "Where do you want to be put off (the bus)?", "type": "句子", "keyWords": ["put"] },
    { "chinese": "出言不逊使她很反感。", "english": "She has been put off by his unkind remarks.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "穿上；上演；开(灯、收音机等)；装出(asmile,airs)", "english": "put...on", "type": "短语", "keyWords": ["put"] },
    { "chinese": "穿鞋/上演戏剧", "english": "put on shoes/a play", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他交了个百万富翁朋友后就学会了装腔作势。", "english": "He put on airs after making friends with a millionaire.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "熄灭；出版；公布；伸出(近stick out)，生产(近turn out)", "english": "put...out", "type": "短语", "keyWords": ["put"] },
    { "chinese": "关灯/灭火/熄掉烟", "english": "put out the lights/the fire/the cigarette", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他们已经出版了一种新的期刊。", "english": "They have already put out a new periodical.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "伸出某人的舌头/手", "english": "put out one's tongue/one's hand", "type": "短语", "keyWords": ["put"] },
    { "chinese": "把头伸出窗外", "english": "put/stick your head out of the window", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他们生产了几台高级发动机。", "english": "They put out some motors of high standards.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "举起；搭建；张贴；提出(计划等)；留宿(v./vi)", "english": "put...up", "type": "短语", "keyWords": ["put"] },
    { "chinese": "手举起来！", "english": "Put up your hands!", "type": "句子", "keyWords": ["put"] },
    { "chinese": "张贴启事/海报", "english": "put up a notice/posters", "type": "短语", "keyWords": ["put"] },
    { "chinese": "搭起帐篷/盖楼", "english": "put up the tent/buildings", "type": "短语", "keyWords": ["put"] },
    { "chinese": "我们在农舍投宿了一夜。", "english": "We put up for the night at a farmhouse.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "无论你们何时进城，我们都很乐意为你们提供膳宿。", "english": "We shall be happy to put you up whenever you come to town.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "容忍", "english": "put up with...", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他们接受对方的要求并容忍对方的缺点。", "english": "They accept demands and put up with shortcomings.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "她得忍受十个孩子的吵闹。", "english": "She had ten children to put up with.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "使…睡觉；把…放或送到床上", "english": "put sb./sth. to bed", "type": "短语", "keyWords": ["put"] },
    { "chinese": "母亲要洗碗碟又要哄孩子睡觉，以致开会迟到。", "english": "With dishes to wash and children to put to bed, Mother was late for the meeting.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "纠正(put表示\"使处于某状态\")", "english": "put sb. right", "type": "短语", "keyWords": ["put"] },
    { "chinese": "小错误必须很快得到纠正。", "english": "Minor mistakes must be quickly put right.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "那使得我有点气喘吁吁。", "english": "That put me a little out of breath.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "我不知道该怎么表达。", "english": "I don't know how to put/express it.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "她，该怎么说呢，并不真胖，但就她年龄而言她是比较壮实了一些。", "english": "She is--how shall I put it?--not exactly fat, but rather well-built for her age.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "制止；终结", "english": "put an end to...", "type": "短语", "keyWords": ["put"] },
    { "chinese": "人类必须消灭战争，否则战争将消灭人类。", "english": "Mankind must put an end to war or war will put an end to mankind.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "放一边；存储", "english": "put...aside", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他们决定暂且抛开彼此的分歧。", "english": "They decided to put aside their differences for a moment.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "使穿过；接通(电话)(=get...through)；经受；使完成", "english": "put...through(to...)", "type": "短语", "keyWords": ["put"] },
    { "chinese": "请把电话接进来。", "english": "Put him through, please.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "请您转马丁先生。", "english": "Please put me through to Mr. Martin.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "他使我遇到许多麻烦。", "english": "He put me through a lot of trouble.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "尼克靠父亲遗留下来的钱念完了大学。", "english": "Nick was put through university with the money left by his father.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "他在周末做成了一笔重要的生意。", "english": "He put through an important business deal over the weekend.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "考验；检验", "english": "put...to the test", "type": "短语", "keyWords": ["put"] },
    { "chinese": "理论必须通过实践来检验。", "english": "Theories must be put to the test of practice.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "实施、贯彻等", "english": "put...into force/effect/use/practice/operation", "type": "短语", "keyWords": ["put"] },
    { "chinese": "体重增加", "english": "put on weight", "type": "短语", "keyWords": ["put"] },
    { "chinese": "v.(使) 迷惑；(使) 为难 n.[C] 难题；费解之事，迷惑；谜 puzzling a. 使迷惑的，使莫名其妙的 puzzled a. 困惑的", "english": "puzzle /'pʌzl/v. n.[C] puzzling a. puzzled a.", "type": "单词", "keyWords": [] },
    { "chinese": "对听到或看到的事感到困惑", "english": "be puzzled at", "type": "短语", "keyWords": ["puzzle"] },
    { "chinese": "他不愿意帮忙让我有点困惑。", "english": "I was somewhat puzzled at his unwillingness to help.", "type": "句子", "keyWords": ["puzzle"] },
    { "chinese": "听了这话我感到有些迷惑不解。", "english": "I felt rather puzzled at the words.", "type": "句子", "keyWords": ["puzzle"] },
    { "chinese": "对… 感到迷惑", "english": "be puzzled over/about...", "type": "短语", "keyWords": ["puzzle"] },
    { "chinese": "他完全不知道接下去该怎么办。", "english": "He was quite puzzled about what to do next.", "type": "句子", "keyWords": ["puzzle"] },
    { "chinese": "思冥想 (vi)(意义源于主动)", "english": "puzzle over/about...", "type": "短语", "keyWords": ["puzzle"] },
    { "chinese": "n.(pl.) 睡衣", "english": "pyjamas /pə'dʒɑːməz/n.(pl.)", "type": "单词", "keyWords": [] },
    { "chinese": "一套睡衣", "english": "a pair of pyjamas", "type": "短语", "keyWords": ["pyjamas"] },
    { "chinese": "n.[C] 金字塔；角锥状物", "english": "pyramid /'pɪrəmɪd/n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C] 地震 vi. 震动；摇动；颤动 (辨析见 shake)", "english": "quake /kweɪk/n.[C] vi.", "type": "单词", "keyWords": [] },
    { "chinese": "n.C资格；资格 (证明)","english":"qualification /ˌkwɒlɪfɪ'keɪʃn/n.[C]","type":" 单词 ","keyWords": [] },
    { "chinese": "adj. 合格的，有资格的；胜任的 (反 unqualified)", "english": "qualified /'kwɒlɪfaɪd/adj.", "type": "单词", "keyWords": [] },
    { "chinese": "胜任做某事", "english": "be qualified/fit for sth./to do sth.", "type": "短语", "keyWords": ["qualified"] },
    { "chinese": "v. 使具有资格；使胜任 vi. 取得资格；胜任", "english": "qualify /'kwɒlɪfaɪ/vt. vi.", "type": "单词", "keyWords": [] },
    { "chinese": "使… 有… 资格", "english": "qualify (sb.) for sth./as...", "type": "短语", "keyWords": ["qualify"] },
    { "chinese": "你具备获得联邦政府贷款项目的资格吗？", "english": "Do you qualify for any of the federal loan programs?", "type": "句子", "keyWords": ["qualify"] },
    { "chinese": "约翰逊没有通过当医生的资格考试，决定从事绘画工作。", "english": "Johnson, having failed to qualify as a doctor, decided to take up painting.", "type": "句子", "keyWords": ["qualify"] },
    { "chinese": "他的技术使他能胜任这份工作。", "english": "His skill qualifies him for the job.", "type": "句子", "keyWords": ["qualify"] },
    { "chinese": "你必须使自己具备担任这一工作的资格。", "english": "You must qualify yourself for the post.", "type": "句子", "keyWords": ["qualify"] },
    { "chinese": "n.[U] 品质；品级；质量 n.[C] 特点，特性，性质", "english": "quality /'kwɒlətɪ/n.[U] n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "质量好 / 低劣", "english": "be of good/high/low/poor quality", "type": "短语", "keyWords": ["quality"] },
    { "chinese": "在质量或大小上都属下等的", "english": "be inferior in quality or size", "type": "短语", "keyWords": ["quality"] },
    { "chinese": "n.[C][U] 量；数量；总量 (近 amount)", "english": "quantity /'kwɒntətɪ/n.[C][U]", "type": "单词", "keyWords": [] },
    { "chinese": "大 / 小量的", "english": "large/small quantities of = a large/small quantity of", "type": "短语", "keyWords": ["quantity"] },
    { "chinese": "大 / 少量销售煤炭", "english": "sell coal in large/small quantities", "type": "短语", "keyWords": ["quantity"] },
    { "chinese": "桌上有大量食物。", "english": "Quantities of food are on the table. = A large quantity of food is on the table.", "type": "句子", "keyWords": ["quantity"] },
    { "chinese": "桌上有大量报纸。", "english": "Quantities of newspapers are on the table. = A large quantity of newspapers are on the table.", "type": "句子", "keyWords": ["quantity"] },
    { "chinese": "我重质量胜过数量。", "english": "I prefer quality to quantity.", "type": "句子", "keyWords": ["quantity"] },
    { "chinese": "v./n.[C] 争吵；吵嘴；失和", "english": "quarrel /'kwɒrəl/v./n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "因某事同某人吵架", "english": "(have a) quarrel with sb. about sth.", "type": "短语", "keyWords": ["quarrel"] },
    { "chinese": "n.[C] 一刻钟；四分之一；季度；城市的特定地区；(美、加) 两角五分的辅币；(pl)(尤指佣人或军人) 住所；军营 (近 headquarters 军队司令部，大本营)", "english": "quarter /'kwɔːtə/n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "法国人特区", "english": "the French Quarter", "type": "短语", "keyWords": ["quarter"] },
    { "chinese": "您有一些 25 分的硬币吗？", "english": "Have you got some quarters?", "type": "句子", "keyWords": ["quarter"] },
    { "chinese": "我们必须在天黑之前找到住处。", "english": "We must find quarters before night falls.", "type": "句子", "keyWords": ["quarter"] },
    { "chinese": "n.[C] 女王；王后", "english": "queen /kwiːn/n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]问题 n.[U]怀疑 v.询问；审问；怀疑", "english": "question /'kwestʃən/ n.[C] n.[U] v.", "type": "单词", "keyWords": [] },
    { "chinese": "不是钱财问题", "english": "be not a question of money", "type": "短语", "keyWords": ["question"] },
    { "chinese": "它的消失只是一个时间问题。", "english": "Its extinction is just a question of time.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "我们取得这些商品的进口许可证是不成问题的。", "english": "There is no question about/as to our getting the import license for these articles.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "没问题(近beyond doubt)", "english": "beyond/out of/without question", "type": "短语", "keyWords": ["question"] },
    { "chinese": "受盘问(类under consideration/ repair/ discussion/way/attack/ construction)", "english": "*under question", "type": "短语", "keyWords": ["question"] },
    { "chinese": "正被讨论；在讨论中", "english": "*in question", "type": "短语", "keyWords": ["question"] },
    { "chinese": "那不是要考虑的要点。", "english": "That is not the point in question.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "关于是否存在全球变暖的问题，仍在讨论中。", "english": "The existence of global warming is in question.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "不可能", "english": "*out of the question", "type": "短语", "keyWords": ["question"] },
    { "chinese": "从头开始是不可能的。", "english": "Starting over is out of the question.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "n.[C](等候的人或车的)长队，队列 v.排队(等候)", "english": "queue /kjuː/ n.[C] v.", "type": "单词", "keyWords": [] },
    { "chinese": "插队；抢先", "english": "jump the queue", "type": "短语", "keyWords": ["queue"] },
    { "chinese": "他们排队等候出租汽车。", "english": "They queued(up) for a taxi.", "type": "句子", "keyWords": ["queue"] },
    { "chinese": "adj.快的；迅速的；敏锐(捷)的，聪明的，脑子反应快的(辨析见fast) quickness n.[U]迅速，敏捷 quicken vt.加快 quickly ad.快地，迅速地", "english": "quick /kwɪk/ adj. quickness n.[U] quicken vt. quickly ad.", "type": "单词", "keyWords": [] },
    { "chinese": "有敏捷的头脑", "english": "have a quick mind", "type": "短语", "keyWords": ["quick"] },
    { "chinese": "学某事学得快", "english": "be quick to learn sth.", "type": "短语", "keyWords": ["quick"] },
    { "chinese": "在(做)某事方面迅速(近be clever/good/clumsy at)", "english": "be quick at(doing) sth.", "type": "短语", "keyWords": ["quick"] },
    { "chinese": "adj.安静的；平静的；轻声的 v.(使)平静 quietly ad.安静地 quietness n.(U)", "english": "quiet /'kwaɪət/ adj. v. quietly ad. quietness n.(U)", "type": "单词", "keyWords": [] },
    { "chinese": "对某事保守秘密，隐瞒某事", "english": "keep quiet about sth.", "type": "短语", "keyWords": ["quiet"] },
    { "chinese": "非常安静，不声不响", "english": "*be as quiet as a mouse", "type": "短语", "keyWords": ["quiet"] },
    { "chinese": "辨析：still, quiet, silent, calm still指没有运动或骚扰，常表示静止不动或平静，通常这种情况是暂时的；quiet指没有噪音、混乱、骚乱、烦扰、波澜，有时隐含有永久的味道；silent指没有声音或噪音，并不一定和动作有关；calm主要指天气或大海的平静，也指心态不受激动、急躁等的干扰而显得平静、镇静。", "english": "辨析:still, quiet, silent, calm still指没有运动或骚扰，常表示静止不动或平静，通常这种情况是暂时的；quiet指没有噪音、混乱、骚乱、烦扰、波澜，有时隐含有永久的味道；silent指没有声音或噪音，并不一定和动作有关；calm主要指天气或大海的平静，也指心态不受激动、急躁等的干扰而显得平静、镇静。", "type": "句子", "keyWords": ["quiet"] },
    { "chinese": "n.[C]被子", "english": "quilt /kwɪlt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "v.停止；放弃；离开；离职，辞职", "english": "quit /kwɪt/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "辞去工作", "english": "quit a job", "type": "短语", "keyWords": ["quit"] },
    { "chinese": "停止说话", "english": "quit talking", "type": "短语", "keyWords": ["quit"] },
    { "chinese": "adv.很，十分；完全，彻底(辨析见fairly)", "english": "quite /kwaɪt/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "很不同的一种语言", "english": "quite a different language", "type": "短语", "keyWords": ["quite"] },
    { "chinese": "非常多(的人)(近quite a few)", "english": "quite a lot(of people)", "type": "短语", "keyWords": ["quite"] },
    { "chinese": "和…完全一样…(用于同级比较结构前)", "english": "quite as...as...", "type": "短语", "keyWords": ["quite"] },
    { "chinese": "极不可能的/不同的/合理的/完美的/正确的/确定的(用于无比较级的形容词或副词前)", "english": "quite impossible/different/reasonable/perfect/right/certain", "type": "短语", "keyWords": ["quite"] },
    { "chinese": "我并不完全理解你。", "english": "I don't quite follow you.", "type": "句子", "keyWords": ["quite"] },
    { "chinese": "这已过时。", "english": "It's quite out of fashion.", "type": "句子", "keyWords": ["quite"] },
    { "chinese": "n.[C](pl.quizzes)(短的口头或书面)测试；(电视中的)问答比赛", "english": "quiz /kwɪz/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "v.引用；援引(from) quotation n.[C](U)引语；引文；语录", "english": "quote /kwəʊt/ v. quotation n.[C](U)", "type": "单词", "keyWords": [] },
    { "chinese": "作者经常引用莎士比亚作品里的话。", "english": "The author frequently quoted Shakespeare.", "type": "句子", "keyWords": ["quote"] },
    { "chinese": "这位牧师引用了《圣经》里的话。", "english": "The minister quoted from the Bible.", "type": "句子", "keyWords": ["quote"] },
    { "chinese": "n.[C]兔子", "english": "rabbit /'ræbɪt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "v.和…赛速度；和…竞赛 n.[C]赛跑；竞赛；人种；种族", "english": "race /reɪs/ v. n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "及时冲回家", "english": "race home in time", "type": "短语", "keyWords": ["race"] },
    { "chinese": "和汤姆赛跑", "english": "run a race with Tom", "type": "短语", "keyWords": ["race"] },
    { "chinese": "和时间赛跑", "english": "a race against time", "type": "短语", "keyWords": ["race"] },
    { "chinese": "种族歧视/种族冲突", "english": "racial discrimination/conflict", "type": "短语", "keyWords": ["race"] },
    { "chinese": "人类", "english": "the human race", "type": "短语", "keyWords": ["race"] },
    { "chinese": "adj.种族的", "english": "racial /'reɪʃəl/ adj.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]雷达", "english": "radar /'reɪdɑː/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]辐射 *n.[C][U]辐射物 *radiate v.发光，辐射；放射", "english": "radiation /ˌreɪdɪ'eɪʃn/ n.[U] *n.[C][U] *radiate v.", "type": "单词", "keyWords": [] },
    { "chinese": "adj.激进的 n.[C]激进分子", "english": "radical /'rædɪkl/ adj. n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]收音机 n.[U]无线电；无线电台；无线通信", "english": "radio /'reɪdɪəʊ/ n.[C] n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "通过无线电", "english": "by radio", "type": "短语", "keyWords": ["radio"] },
    { "chinese": "作广播讲话", "english": "speak over/on the radio", "type": "短语", "keyWords": ["radio"] },
    { "chinese": "n.[U]放射性", "english": "radioactivity /'reɪdɪəʊæk'tɪvəti/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.放射性的", "english": "radioactive adj.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]镭", "english": "radium /'reɪdiəm/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]破布；抹布", "english": "rag /ræg/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "衣衫褴褛", "english": "(be dressed) in rags", "type": "短语", "keyWords": ["rag"] },
    { "chinese": "被撕碎", "english": "be torn to rags", "type": "短语", "keyWords": ["rag"] },
    { "chinese": "n.[C]提杆；栏杆；(常pl)铁路；铁轨", "english": "rail /reɪl/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "靠在栏杆上", "english": "lean over the rail", "type": "短语", "keyWords": ["rail"] },
    { "chinese": "n.[C]铁路[美]railroad", "english": "railway /'reɪlweɪ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "火车站", "english": "railway station", "type": "短语", "keyWords": ["railway"] },
    { "chinese": "v.下(雨)；(使)如雨下 n.[U](可与a连用)雨；下雨；如雨般降落", "english": "rain /reɪn/ v. n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.有雨的；多雨的", "english": "rainy a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]雨量", "english": "rainfall n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]雨滴，雨点", "english": "raindrop n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "弹如雨下", "english": "a rain of bullets", "type": "短语", "keyWords": ["rain"] },
    { "chinese": "看来要下雨", "english": "look like rain", "type": "短语", "keyWords": ["rain"] },
    { "chinese": "n.[C]雨衣", "english": "raincoat n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]热带雨林", "english": "rainforest n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "下倾盆大雨", "english": "rain cats and dogs", "type": "短语", "keyWords": ["rain"] },
    { "chinese": "一阵大/小/细雨", "english": "a heavy/light/fine rain", "type": "短语", "keyWords": ["rain"] },
    { "chinese": "雨过天晴；否极泰来。", "english": "After rain comes fair weather.", "type": "句子", "keyWords": ["rain"] },
    { "chinese": "不下则已，一下倾盆。不来则已，一来便接踵而至(尤指坏事)", "english": "It never rains but it pours.", "type": "句子", "keyWords": ["rain"] },
    { "chinese": "n.[C]彩虹", "english": "rainbow /'reɪnbəʊ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.防雨的；防水的", "english": "rainproof /'reɪnpruːf/ adj.", "type": "单词", "keyWords": [] },
    { "chinese": "v.举起；使升高；筹集；招募；种植；养育", "english": "raise /reɪz/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "抬起头/提高嗓门", "english": "raise one's head/one's voice", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "站起来", "english": "raise oneself", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "对……表示钦佩", "english": "raise one's hat to sb.", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "扬起一片尘土", "english": "raise a cloud of dust", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "提出一个问题", "english": "raise a question/an issue", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "养育孩子/养牛/种植小麦", "english": "raise children/cattle/wheat", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "声音大得能把死人吵醒", "english": "noise that would raise the dead", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "为一个慈善组织筹款", "english": "raise money/funds for a charity", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "凸起的点/高出周围地面的站台", "english": "raised dots/platform", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "n.[U]随意行动；随机(只用于at random) adj.任意(选取)的；随机的", "english": "random /'rændəm/ n.[U] adj.", "type": "单词", "keyWords": [] },
    { "chinese": "随便地，胡乱地，漫无目的地", "english": "at random", "type": "短语", "keyWords": ["random"] },
    { "chinese": "n.[C]排；行；走向；山脉；等级；幅度；范围；射程 v.排列；把…分类 vi.(在某范围内)变动，变化；绵亘，延伸", "english": "range /reɪndʒ/ n.[C] v. vi.", "type": "单词", "keyWords": [] },
    { "chinese": "一排楼房", "english": "a range of buildings", "type": "短语", "keyWords": ["range"] },
    { "chinese": "视觉范围", "english": "the range of vision", "type": "短语", "keyWords": ["range"] },
    { "chinese": "每年的温度变化范围", "english": "the annual range of temperature", "type": "短语", "keyWords": ["range"] },
    { "chinese": "广博的知识", "english": "a wide range of knowledge", "type": "短语", "keyWords": ["range"] },
    { "chinese": "把书排列在书架上", "english": "range books on the shelf", "type": "短语", "keyWords": ["range"] },
    { "chinese": "在…到…之间变化；绵亘", "english": "range from...to.../between...and...", "type": "短语", "keyWords": ["range"] },
    { "chinese": "两岁至五岁年龄段", "english": "ages that ranged from two to five", "type": "短语", "keyWords": ["range"] },
    { "chinese": "价格自五美元至十美元不等。", "english": "Prices ranged from 5 dollars to 10.", "type": "句子", "keyWords": ["range"] },
    { "chinese": "从A地延伸到B地的边界", "english": "a boundary that ranges from A to B", "type": "短语", "keyWords": ["range"] },
    { "chinese": "这炮的射程可达五英里多。", "english": "The gun ranges over five miles.", "type": "句子", "keyWords": ["range"] },
    { "chinese": "在射程外", "english": "out of/beyond range", "type": "短语", "keyWords": ["range"] },
    { "chinese": "航程", "english": "flying range", "type": "短语", "keyWords": ["range"] },
    { "chinese": "能力达不到的；知识以外的", "english": "out of one's range", "type": "短语", "keyWords": ["range"] },
    { "chinese": "v.(给…)分等；把…排成行 n.[C]排；行，列；队列；地位；军衔；等级", "english": "rank /ræŋk/ v. n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "名单上位居第一", "english": "rank first on the list", "type": "短语", "keyWords": ["rank"] },
    { "chinese": "(是)一流的", "english": "(be) of (the) first rank", "type": "短语", "keyWords": ["rank"] },
    { "chinese": "各阶层的人们", "english": "*people of all ranks", "type": "短语", "keyWords": ["rank"] },
    { "chinese": "adj.快的；迅速的 rapidly ad.迅速地", "english": "rapid /'ræpɪd/ adj. rapidly ad.", "type": "单词", "keyWords": [] },
    { "chinese": "adj.稀有的；罕见的，难得的；珍奇的 rarely ad. *rarity /'reərəti/ n.[U]稀有 [C]稀有物", "english": "rare /reə/ adj. rarely ad. *rarity /'reərəti/ n.[U] [C]", "type": "单词", "keyWords": [] },
    { "chinese": "难得地", "english": "on rare occasions", "type": "短语", "keyWords": ["rare"] },
    { "chinese": "珍禽", "english": "a rare bird", "type": "短语", "keyWords": ["rare"] },
    { "chinese": "辨析：rare, scarce rare指本来世界上就少见；scarce指一时供不应求而少见。", "english": "辨析:rare, scarce rare指本来世界上就少见；scarce指一时供不应求而少见。", "type": "句子", "keyWords": ["rare"] },
    { "chinese": "n.[C]大老鼠", "english": "rat /ræt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]率，比率；等级", "english": "rate /reɪt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "以…的比率/速度", "english": "at the/a rate of", "type": "短语", "keyWords": ["rate"] },
    { "chinese": "目前每年利率是1%。", "english": "Interest is paid at the rate of 1% per year at present.", "type": "句子", "keyWords": ["rate"] },
    { "chinese": "以每公斤3元/特别折扣价…", "english": "(at the speed/the price/the expense/the cost) 3 yuan a kilo/a special discount...", "type": "短语", "keyWords": ["rate"] },
    { "chinese": "不管怎样", "english": "at any rate", "type": "短语", "keyWords": ["rate"] },
    { "chinese": "不管怎样，大家相信情况就是这样。", "english": "At any rate, that is believed to be the case.", "type": "句子", "keyWords": ["rate"] },
    { "chinese": "照这/那样下去", "english": "at this/that rate", "type": "短语", "keyWords": ["rate"] },
    { "chinese": "照这种形势看来，我们就无法度假了。", "english": "At this rate we will be unable to have a holiday.", "type": "句子", "keyWords": ["rate"] },
    { "chinese": "adv.相当，颇(辨析见fairly)；宁愿，宁可；更确切地(说)", "english": "rather /'rɑːðə/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "非常热的一天", "english": "rather (quite) a hot day/ a rather hot day", "type": "短语", "keyWords": ["rather"] },
    { "chinese": "更糟糕/太差(可修饰比较级和too短语)", "english": "rather worse/ rather too bad", "type": "短语", "keyWords": ["rather"] }
];
