const qgl229_236 = [
    { "chinese": "研究；探索", "english": "research into/on sth. (vi.) = research sth. (vt.)", "type": "单词", "keyWords": ["research"] },
    { "chinese": "对…做调查/研究", "english": "carry out/do/make/conduct some research into/on sth.", "type": "短语", "keyWords": ["research"] },
    { "chinese": "n. 研究人员", "english": "researcher", "type": "单词", "keyWords": [] },
    { "chinese": "v. 与…相似，像", "english": "resemble", "type": "单词", "keyWords": [] },
    { "chinese": "n. 相似处", "english": "resemblance", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 保留；储备；预订 n. 储备；自然保护区", "english": "reserve", "type": "单词", "keyWords": [] },
    { "chinese": "所有名字与标志是其拥有者的财产，将保留一切权利。", "english": "All names and logos are the property of their respective owners and all rights are reserved.", "type": "句子", "keyWords": ["reserve"] },
    { "chinese": "这些座位是为特别的来宾保留的。", "english": "These seats are reserved for special guests.", "type": "句子", "keyWords": ["reserve"] },
    { "chinese": "他们已预订了旅馆房间。", "english": "They have reserved rooms at a hotel.", "type": "句子", "keyWords": ["reserve"] },
    { "chinese": "预定的座位", "english": "reserved seats", "type": "短语", "keyWords": ["reserve"] },
    { "chinese": "探明储量", "english": "proved reserves", "type": "短语", "keyWords": ["reserve"] },
    { "chinese": "自然保护区", "english": "a nature reserve", "type": "短语", "keyWords": ["reserve"] },
    { "chinese": "n. 保留意见；预订", "english": "reservation", "type": "单词", "keyWords": [] },
    { "chinese": "你跟餐馆订好两桌酒席了吗？", "english": "Did you make reservations for two tables at the restaurant?", "type": "句子", "keyWords": ["reservation"] },
    { "chinese": "n. 水库", "english": "reservoir", "type": "单词", "keyWords": [] },
    { "chinese": "n. 居住；住处", "english": "residence", "type": "单词", "keyWords": [] },
    { "chinese": "n. 居民", "english": "resident", "type": "单词", "keyWords": [] },
    { "chinese": "a. 居民的；居住的；住所的", "english": "residential", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 居住，定居", "english": "reside", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 辞职 vt. 放弃；辞去", "english": "resign", "type": "单词", "keyWords": [] },
    { "chinese": "辞职", "english": "resign (from) his post", "type": "短语", "keyWords": ["resign"] },
    { "chinese": "放弃董事职务", "english": "resign his directorship", "type": "短语", "keyWords": ["resign"] },
    { "chinese": "n. 辞职；辞职书", "english": "resignation", "type": "单词", "keyWords": [] },
    { "chinese": "v. 抵抗；忍住，按捺；抗，耐 vi. 抵抗", "english": "resist", "type": "单词", "keyWords": [] },
    { "chinese": "抑制（做）某事", "english": "resist (doing) sth.", "type": "短语", "keyWords": ["resist"] },
    { "chinese": "真玉摸起来有凉的感觉并且不怕金属刮划。", "english": "Jade is always cool to touch and will resist scratching with metal.", "type": "句子", "keyWords": ["resist"] },
    { "chinese": "我无法抵制糖的诱惑。", "english": "I couldn't resist the temptation to eat sweets.", "type": "句子", "keyWords": ["resist"] },
    { "chinese": "a. 抵抗的，耐…的", "english": "resistant", "type": "单词", "keyWords": [] },
    { "chinese": "n. 抵抗", "english": "resistance", "type": "单词", "keyWords": [] },
    { "chinese": "反对变革/耐化学品的", "english": "be resistant to change/chemicals", "type": "短语", "keyWords": ["resistant"] },
    { "chinese": "n. 决心；决议；坚决；解决", "english": "resolution", "type": "单词", "keyWords": [] },
    { "chinese": "v. 决定，决意；解决；分解", "english": "resolve", "type": "单词", "keyWords": [] },
    { "chinese": "解决冲突", "english": "resolve a conflict", "type": "短语", "keyWords": ["resolve"] },
    { "chinese": "她决定早早出发。", "english": "She resolved on making an early start.", "type": "句子", "keyWords": ["resolve"] },
    { "chinese": "水可以分解成氧和氢。", "english": "Water may be resolved into oxygen and hydrogen.", "type": "句子", "keyWords": ["resolve"] },
    { "chinese": "n. 常去的热闹地方；胜地 vi. 凭借，采用", "english": "resort", "type": "单词", "keyWords": [] },
    { "chinese": "假日游乐场", "english": "a holiday resort", "type": "短语", "keyWords": ["resort"] },
    { "chinese": "避暑/避寒胜地", "english": "a summer/winter resort", "type": "短语", "keyWords": ["resort"] },
    { "chinese": "使用（武力），诉诸（武力）", "english": "resort to (armed force)", "type": "短语", "keyWords": ["resort"] },
    { "chinese": "不使用（武力）", "english": "without resorting to (force)", "type": "短语", "keyWords": ["resort"] },
    { "chinese": "n. 资源", "english": "resource", "type": "单词", "keyWords": [] },
    { "chinese": "自然资源", "english": "natural resources", "type": "短语", "keyWords": ["resource"] },
    { "chinese": "n. 尊重；重视；关系；方面；敬意 v. 尊重", "english": "respect", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可敬的", "english": "respected", "type": "单词", "keyWords": [] },
    { "chinese": "a. 尊重人的，有礼貌的", "english": "respectful", "type": "单词", "keyWords": [] },
    { "chinese": "a. 分别的，各自的", "english": "respective", "type": "单词", "keyWords": [] },
    { "chinese": "a. 值得尊敬的；体面的", "english": "respectable", "type": "单词", "keyWords": [] },
    { "chinese": "可敬的老师", "english": "a respectable teacher", "type": "短语", "keyWords": ["respectable"] },
    { "chinese": "尊重", "english": "have/show respect for (=be respectful to/towards)", "type": "短语", "keyWords": ["respect"] },
    { "chinese": "问候", "english": "send one's respects to", "type": "短语", "keyWords": ["respect"] },
    { "chinese": "我觉得你各方面都错了。", "english": "I think you are wrong in every respect.", "type": "句子", "keyWords": ["respect"] },
    { "chinese": "关于；就…而论", "english": "in respect of sth., in/with respect to sth.", "type": "短语", "keyWords": ["respect"] },
    { "chinese": "提及/关于某事物", "english": "in/with respect to sb.", "type": "短语", "keyWords": ["respect"] },
    { "chinese": "尊敬的主席先生", "english": "respected Mr. Chairman", "type": "短语", "keyWords": ["respected"] },
    { "chinese": "各人有各人的职责。", "english": "All men have their respective duties.", "type": "句子", "keyWords": ["respective"] },
    { "chinese": "v. 回答；答复；作出反应；响应", "english": "respond", "type": "单词", "keyWords": [] },
    { "chinese": "回答；对…作出反应", "english": "respond/reply to sb./sth.", "type": "短语", "keyWords": ["respond"] },
    { "chinese": "n. 回答；答复；反应；响应", "english": "response", "type": "单词", "keyWords": [] },
    { "chinese": "应号召", "english": "in response/answer/reply to a call", "type": "短语", "keyWords": ["response"] },
    { "chinese": "他没回答。", "english": "He said nothing in response. = He made no response.", "type": "句子", "keyWords": ["response"] },
    { "chinese": "他们很快答复了我的询问。", "english": "They make a quick response to my inquiry.", "type": "句子", "keyWords": ["response"] },
    { "chinese": "n. 责任", "english": "responsibility", "type": "单词", "keyWords": [] },
    { "chinese": "对…（全）负责", "english": "take/shoulder/bear (full) responsibility for", "type": "短语", "keyWords": ["responsibility"] },
    { "chinese": "a. 负责任的；有责任感的，可靠的", "english": "responsible", "type": "单词", "keyWords": [] },
    { "chinese": "对…负责；是…的原因", "english": "be responsible for", "type": "短语", "keyWords": ["responsible"] },
    { "chinese": "这损失是暴风雨造成的。", "english": "The storm was responsible for the damage.", "type": "句子", "keyWords": ["responsible"] },
    { "chinese": "v./vi. （使）休息；停留；依靠 n. 休息；睡眠；其余", "english": "rest", "type": "单词", "keyWords": [] },
    { "chinese": "a. 焦躁不安的；得不到休息的；不平静的", "english": "restless", "type": "单词", "keyWords": [] },
    { "chinese": "（被）支撑，（使）倚靠", "english": "rest (sth) on/against sth.", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "他的目光落在一个奇怪的物体上。", "english": "His gaze rested on a strange object.", "type": "句子", "keyWords": ["rest"] },
    { "chinese": "机器安装在宽钢板底座上。", "english": "The machine rests on a wide base of steel.", "type": "句子", "keyWords": ["rest"] },
    { "chinese": "她朝我看并微笑。", "english": "She rested her eyes on me and smiled.", "type": "句子", "keyWords": ["rest"] },
    { "chinese": "在休息中；静止，不动；处于安宁状态；安息", "english": "at rest", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "在有生之年", "english": "for the rest of one's life", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "其他时间", "english": "The rest of the time is...", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "我们其他人", "english": "The rest of us are...", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "度过了一个不眠之夜", "english": "spend a restless night", "type": "短语", "keyWords": ["restless"] },
    { "chinese": "n. 餐馆，饭店", "english": "restaurant", "type": "单词", "keyWords": [] },
    { "chinese": "v. 恢复；使恢复健康；修复", "english": "restore", "type": "单词", "keyWords": [] },
    { "chinese": "n. 恢复", "english": "restoration", "type": "单词", "keyWords": [] },
    { "chinese": "使某人苏醒过来", "english": "restore sb. to life", "type": "短语", "keyWords": ["restore"] },
    { "chinese": "使某人复职", "english": "restore sb. to his old post", "type": "短语", "keyWords": ["restore"] },
    { "chinese": "使某人恢复知觉", "english": "restore sb. to consciousness", "type": "短语", "keyWords": ["restore"] },
    { "chinese": "把书放回书架", "english": "restore the book to the shelf", "type": "短语", "keyWords": ["restore"] },
    { "chinese": "v. 限制，约束", "english": "restrict", "type": "单词", "keyWords": [] },
    { "chinese": "n. 限制", "english": "restriction", "type": "单词", "keyWords": [] },
    { "chinese": "这些文件仍仅限公务员使用。", "english": "Access to the documents remains restricted to civil servants only.", "type": "句子", "keyWords": ["restrict"] },
    { "chinese": "a. 严格的，受严控的", "english": "restricted", "type": "单词", "keyWords": [] },
    { "chinese": "禁区", "english": "a restricted area", "type": "短语", "keyWords": ["restricted"] },
    { "chinese": "a. 限制性的", "english": "restrictive", "type": "单词", "keyWords": [] },
    { "chinese": "工业方面的限制性措施", "english": "restrictive practices in industry", "type": "短语", "keyWords": ["restrictive"] },
    { "chinese": "n. 结果；成果；成绩 vi. 作为结果发生；产生", "english": "result", "type": "单词", "keyWords": [] },
    { "chinese": "作为结果，因此", "english": "as a result", "type": "短语", "keyWords": ["result"] },
    { "chinese": "由…导致", "english": "result from", "type": "短语", "keyWords": ["result"] },
    { "chinese": "由于", "english": "as a result of", "type": "短语", "keyWords": ["result"] },
    { "chinese": "导致", "english": "result in", "type": "短语", "keyWords": ["result"] },
    { "chinese": "n. 摘要，概略；[美]（求职者等的）简历，履历", "english": "resume", "type": "单词", "keyWords": [] },
    { "chinese": "v. （使）退休/职；退隐", "english": "retire", "type": "单词", "keyWords": [] },
    { "chinese": "n. 退休；退隐", "english": "retirement", "type": "单词", "keyWords": [] },
    { "chinese": "离群索居；退隐；隐居", "english": "retire from the world", "type": "短语", "keyWords": ["retire"] },
    { "chinese": "一个退休工人", "english": "a retired worker", "type": "短语", "keyWords": ["retired"] },
    { "chinese": "v. 返回；归还；回答 n. 返回；归还；回访；报答", "english": "return", "type": "单词", "keyWords": [] },
    { "chinese": "作为…的交换；作为…的回报", "english": "in return (for)", "type": "短语", "keyWords": ["return"] },
    { "chinese": "他回送了她一些玫瑰（以答谢她的好意）。", "english": "He gave her some roses in return (for her kindness).", "type": "句子", "keyWords": ["return"] },
    { "chinese": "他刚从乡下回来就认真工作起来。", "english": "On his return from the countryside, he set to work in earnest.", "type": "句子", "keyWords": ["return"] },
    { "chinese": "福寿无疆！长命百岁！", "english": "Many happy returns (of the day)!", "type": "句子", "keyWords": ["return"] },
    { "chinese": "v. 重新统一；（使）重新结合/联合；（使）重聚", "english": "reunite", "type": "单词", "keyWords": [] },
    { "chinese": "n. 聚会；团聚", "english": "reunion", "type": "单词", "keyWords": [] },
    { "chinese": "v. 揭示，揭露；泄露；暴露；展现", "english": "reveal", "type": "单词", "keyWords": [] },
    { "chinese": "身份", "english": "reveal one's identity", "type": "短语", "keyWords": ["reveal"] },
    { "chinese": "他们向我透露实验失败了。", "english": "They revealed to me that the experiment had failed.", "type": "句子", "keyWords": ["reveal"] },
    { "chinese": "他切开长筒靴后发现被藏的珠宝。", "english": "His cut in the boot revealed the hidden jewels.", "type": "句子", "keyWords": ["reveal"] },
    { "chinese": "vi./n. 报仇，复仇 v. 替…报仇；报…之仇", "english": "revenge", "type": "单词", "keyWords": [] },
    { "chinese": "因某事报复某人", "english": "get/have/take one's revenge on sb. for sth.", "type": "短语", "keyWords": ["revenge"] },
    { "chinese": "（为…）报复性地/出于报复做某事", "english": "do sth. out of revenge/in revenge (for sth.)", "type": "短语", "keyWords": ["revenge"] },
    { "chinese": "哈姆雷特向凶手报了杀父之仇。", "english": "Hamlet revenged his dead father (on the murderer).", "type": "句子", "keyWords": ["revenge"] },
    { "chinese": "对不正义采取报复", "english": "revenge an injustice", "type": "短语", "keyWords": ["revenge"] },
    { "chinese": "a. 逆向的；倒退的；颠倒的 n. 相反情况；反面；背面；逆转；挫折 v. 颠倒；（使）倒退", "english": "reverse", "type": "单词", "keyWords": [] },
    { "chinese": "次序颠倒地", "english": "in reverse order", "type": "短语", "keyWords": ["reverse"] },
    { "chinese": "做违背别人期望的事", "english": "do the reverse of what one is expected to do", "type": "短语", "keyWords": ["reverse"] },
    { "chinese": "硬币的反面压印的是一只鹰。", "english": "The reverse of the coin is stamped with an eagle.", "type": "句子", "keyWords": ["reverse"] },
    { "chinese": "遭受财政困难", "english": "suffer financial reverses", "type": "短语", "keyWords": ["reverse"] },
    { "chinese": "把车倒进", "english": "reverse one's car (into...)", "type": "短语", "keyWords": ["reverse"] },
    { "chinese": "v./n. 复习；审核；回顾；检阅；评论", "english": "review", "type": "单词", "keyWords": [] },
    { "chinese": "观察形势", "english": "review the situation", "type": "短语", "keyWords": ["review"] },
    { "chinese": "回顾过去", "english": "review the past", "type": "短语", "keyWords": ["review"] },
    { "chinese": "检阅仪仗队", "english": "review the guard of honour", "type": "短语", "keyWords": ["review"] },
    { "chinese": "给一本新出版的小说写书评", "english": "review a new novel", "type": "短语", "keyWords": ["review"] },
    { "chinese": "v. 复习；修订；校订；修正", "english": "revise", "type": "单词", "keyWords": [] },
    { "chinese": "我已重新考虑了对他的意见。", "english": "I have revised my opinion of him.", "type": "句子", "keyWords": ["revise"] },
    { "chinese": "n. 复习，修正；修订稿/本", "english": "revision", "type": "单词", "keyWords": [] },
    { "chinese": "经过四次修订", "english": "after four revisions", "type": "短语", "keyWords": ["revision"] },
    { "chinese": "n. 革命；大变革；旋转；绕转", "english": "revolution", "type": "单词", "keyWords": [] },
    { "chinese": "v. 发动革命", "english": "revolutionize", "type": "单词", "keyWords": [] },
    { "chinese": "美国独立战争", "english": "American Revolution (1775-1783)", "type": "短语", "keyWords": ["revolution"] },
    { "chinese": "在现代物理学领域中实现大变革", "english": "bring about a revolution in modern physics", "type": "短语", "keyWords": ["revolution"] },
    { "chinese": "a. 革命的；旋转的；绕转的 n. 革命者", "english": "revolutionary", "type": "单词", "keyWords": [] },
    { "chinese": "vt./n. 报答；奖赏", "english": "reward", "type": "单词", "keyWords": [] },
    { "chinese": "(因…)而(用…)来酬谢某人", "english": "reward sb. (with sth.) (for sth.)", "type": "短语", "keyWords": ["reward"] },
    { "chinese": "(因某事)没获得任何报酬", "english": "get nothing in reward (for sth.)", "type": "短语", "keyWords": ["reward"] },
    { "chinese": "a. 值得的；有益的；有回报的", "english": "rewarding", "type": "单词", "keyWords": [] },
    { "chinese": "有利可图的商业冒险", "english": "a rewarding business venture", "type": "短语", "keyWords": ["rewarding"] },
    { "chinese": "v. 重写；改写", "english": "rewrite", "type": "单词", "keyWords": [] },
    { "chinese": "n. 节奏，韵律", "english": "rhythm", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有节奏的", "english": "rhythmic", "type": "单词", "keyWords": [] },
    { "chinese": "n. 肋骨", "english": "rib", "type": "单词", "keyWords": [] },
    { "chinese": "n. 稻；米饭", "english": "rice", "type": "单词", "keyWords": [] },
    { "chinese": "a. （丰）富的；富饶的，盛产的；肥沃的；充足的", "english": "rich", "type": "单词", "keyWords": [] },
    { "chinese": "n. 富有", "english": "richness", "type": "单词", "keyWords": [] },
    { "chinese": "在…方面很丰富", "english": "be rich in (oil, fat...)", "type": "短语", "keyWords": ["rich"] },
    { "chinese": "v. 摆脱", "english": "rid", "type": "单词", "keyWords": [] },
    { "chinese": "摆脱；除去", "english": "get/be rid of (him/the pain/the toothache)", "type": "短语", "keyWords": ["rid"] },
    { "chinese": "v./n. 骑；骑马；乘车旅行", "english": "ride", "type": "单词", "keyWords": [] },
    { "chinese": "骑自行车", "english": "ride (on) a bicycle", "type": "短语", "keyWords": ["ride"] },
    { "chinese": "乘车", "english": "ride on a bus", "type": "短语", "keyWords": ["ride"] },
    { "chinese": "n. 骑马（或其他牲口、自行车）者；滑水/冲浪运动员", "english": "rider", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可笑的；荒谬的", "english": "ridiculous", "type": "单词", "keyWords": [] },
    { "chinese": "n. 嘲笑", "english": "ridicule", "type": "单词", "keyWords": [] },
    { "chinese": "n. 来复枪；步枪", "english": "rifle", "type": "单词", "keyWords": [] },
    { "chinese": "a. 正确的；右边的；合适的；正当的；健康的 ad. 就，恰好；正确；直接，完全；向上；往右 n. 右边，右面；正确；权利", "english": "right", "type": "单词", "keyWords": [] },
    { "chinese": "修好；纠正", "english": "put...right", "type": "短语", "keyWords": ["right"] },
    { "chinese": "把事情办好", "english": "put things right", "type": "短语", "keyWords": ["right"] },
    { "chinese": "学会在适当的时候说适当的话。", "english": "Learn to say the right thing at the right time.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "他是做这份工作最合适的人选。", "english": "He is the right man for the job.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "感觉一切都好吗（就身体而言）？", "english": "Do you feel all right?", "type": "句子", "keyWords": ["right"] },
    { "chinese": "立刻；马上", "english": "right away/off", "type": "短语", "keyWords": ["right"] },
    { "chinese": "他饭后立刻给我打了电话。", "english": "He called me right after dinner.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "事故正好发生在那里。", "english": "The accident happened right over there.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "把它放在正中间。", "english": "Put it right in the middle.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "习惯用右手的人", "english": "right-handed people", "type": "短语", "keyWords": ["right"] },
    { "chinese": "在某人的右面", "english": "on one's right (side)", "type": "短语", "keyWords": ["right"] },
    { "chinese": "明辨是非", "english": "know the difference between right and wrong", "type": "短语", "keyWords": ["right"] },
    { "chinese": "这本书的版权", "english": "the right to the book", "type": "短语", "keyWords": ["right"] },
    { "chinese": "(成)直角", "english": "(at) a right angle", "type": "短语", "keyWords": ["right"] },
    { "chinese": "(他)罪有应得。活该。", "english": "It serves (him) right.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "n. 戒指；圈；环 v. 按（铃），打电话给 vi. 鸣；（铃等）响；按铃；打电话", "english": "ring", "type": "单词", "keyWords": [] },
    { "chinese": "回某人电话", "english": "ring (you) back", "type": "短语", "keyWords": ["ring"] },
    { "chinese": "挂断电话", "english": "ring off", "type": "短语", "keyWords": ["ring"] },
    { "chinese": "打他电话", "english": "ring him up/give him a ring", "type": "短语", "keyWords": ["ring"] },
    { "chinese": "我会按铃叫护士。", "english": "I'll ring for the nurse.", "type": "句子", "keyWords": ["ring"] },
    { "chinese": "爆炸的声音使我的耳朵嗡嗡作响。", "english": "My ears were ringing from the sound of the blast.", "type": "句子", "keyWords": ["ring"] },
    { "chinese": "a. 成熟的", "english": "ripe", "type": "单词", "keyWords": [] },
    { "chinese": "v. （使）成熟", "english": "ripen", "type": "单词", "keyWords": [] },
    { "chinese": "革命的时机已经成熟", "english": "be ripe for revolution", "type": "短语", "keyWords": ["ripe"] },
    { "chinese": "n. 升起；上升；上涨；增长，增加；兴起 vi. 升起；上升；起立，起床；起义", "english": "rise", "type": "单词", "keyWords": [] },
    { "chinese": "在上涨/增长", "english": "on the rise", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "引起", "english": "give rise to (doing) sth.", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "使人对她的动机产生怀疑的事实", "english": "facts that give rise to doubts about her motives", "type": "句子", "keyWords": ["rise"] },
    { "chinese": "站起来", "english": "rise to his feet", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "天亮时就起床", "english": "rise at dawn", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "高40英尺", "english": "rise 40 feet", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "起义；起来", "english": "rise up", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "n. 危险，风险 vt. 冒…的危险；使（生命、财产等）遭受危险", "english": "risk", "type": "单词", "keyWords": [] },
    { "chinese": "a. 危险的，有风险的", "english": "risky", "type": "单词", "keyWords": [] },
    { "chinese": "在（高度）危险中", "english": "at (high) risk", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "地中海沿岸地区有90%的土地被认为处于高危状态。", "english": "More than 90% of land bordering the Mediterranean is identified as being at high risk.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "留有…的危险；使…冒有危险", "english": "at a risk of (doing) sth.", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "他冒着生命危险救了我的命。", "english": "He saved my life at the risk of his own.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "尽管可能会使读者感到无聊，我还是要再加上几个实例。", "english": "At the risk of being dull, I must add a few more illustrations.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "冒险做某事；冒…的危险", "english": "risk doing sth. = run/take the risk of doing sth.", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "冒遭遇风暴之险", "english": "risk getting caught in a storm", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "那些观点有煽动暴力的危险。", "english": "Those ideas risked encouraging violence.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "冒着生命危险", "english": "risk one's life", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "他冒着生命危险救那个溺水儿童。", "english": "He risked his life (in) saving the drowning child.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "n. 江，河", "english": "river", "type": "单词", "keyWords": [] },
    { "chinese": "n. 河床", "english": "riverbed", "type": "单词", "keyWords": [] },
    { "chinese": "n. 路；道路，公路；街道", "english": "road", "type": "单词", "keyWords": [] },
    { "chinese": "成功之路", "english": "the roads to success", "type": "短语", "keyWords": ["road"] },
    { "chinese": "路标", "english": "road sign", "type": "短语", "keyWords": ["road"] },
    { "chinese": "v. （狮等）叫；发出隆隆声；大声叫喊 v. 呼喊；大声喊出 n. 吼叫，怒号；狂笑", "english": "roar", "type": "单词", "keyWords": [] },
    { "chinese": "虎啸", "english": "the roars of a tiger", "type": "短语", "keyWords": ["roar"] },
    { "chinese": "大炮的轰鸣声", "english": "the roars of guns", "type": "短语", "keyWords": ["roar"] },
    { "chinese": "听了我的笑话而哄堂大笑", "english": "roar with laughter at my joke", "type": "短语", "keyWords": ["roar"] },
    { "chinese": "v. 烤，炙，烘 a. 烤过的", "english": "roast", "type": "单词", "keyWords": [] },
    { "chinese": "v. 抢劫；（非法）剥夺；使丧失", "english": "rob", "type": "单词", "keyWords": [] },
    { "chinese": "n. 强盗", "english": "robber", "type": "单词", "keyWords": [] },
    { "chinese": "n. 抢劫；抢劫案", "english": "robbery", "type": "单词", "keyWords": [] },
    { "chinese": "抢劫某人/某地某物", "english": "rob sb./sw. of sth.", "type": "短语", "keyWords": ["rob"] },
    { "chinese": "n. 机器人", "english": "robot", "type": "单词", "keyWords": [] },
    { "chinese": "n. 摇滚乐/舞；岩石；岩块；巨石 v. （使）摇动", "english": "rock", "type": "单词", "keyWords": [] },
    { "chinese": "坚如磐石", "english": "as solid/firm as a rock", "type": "短语", "keyWords": ["rock"] },
    { "chinese": "摇椅", "english": "rocking chair", "type": "短语", "keyWords": ["rock"] },
    { "chinese": "n. 火箭 vi. 迅速上升或猛涨", "english": "rocket", "type": "单词", "keyWords": [] },
    { "chinese": "宇宙火箭", "english": "a space rocket", "type": "短语", "keyWords": ["rocket"] },
    { "chinese": "n. 杆；竿", "english": "rod", "type": "单词", "keyWords": [] },
    { "chinese": "n. 角色；作用", "english": "role", "type": "单词", "keyWords": [] },
    { "chinese": "在…中起重要作用", "english": "play an important/leading part/role in (doing) sth.", "type": "短语", "keyWords": ["role"] },
    { "chinese": "v. 滚动；转动；滚落；被卷起；（云、浪等）翻滚 v. 使滚动；卷；绕 n. 名单，花名册；（一）卷；滚动", "english": "roll", "type": "单词", "keyWords": [] },
    { "chinese": "点名", "english": "call the roll", "type": "短语", "keyWords": ["roll"] },
    { "chinese": "一卷磁带", "english": "a roll of tape", "type": "短语", "keyWords": ["roll"] },
    { "chinese": "滚滚浓烟", "english": "the rolling smoke", "type": "短语", "keyWords": ["roll"] },
    { "chinese": "波涛滚滚的大海", "english": "the rolling sea", "type": "短语", "keyWords": ["roll"] },
    { "chinese": "山羊翻了一个身，死了。", "english": "The goat rolled over, dead.", "type": "句子", "keyWords": ["roll"] },
    { "chinese": "n. 浪漫故事/作品；浪漫，传奇性", "english": "romance", "type": "单词", "keyWords": [] },
    { "chinese": "a. 浪漫的；传奇（式）的；有浪漫色彩的 n. 浪漫的人", "english": "romantic", "type": "单词", "keyWords": [] },
    { "chinese": "n. 浪漫精神；浪漫主义", "english": "romanticism", "type": "单词", "keyWords": [] },
    { "chinese": "n. 屋顶", "english": "roof", "type": "单词", "keyWords": [] },
    { "chinese": "同住一屋", "english": "live under the same roof", "type": "短语", "keyWords": ["roof"] },
    { "chinese": "喧闹不休，（在屋内）吵翻天", "english": "raise the roof", "type": "短语", "keyWords": ["roof"] },
    { "chinese": "n. 房间；室；空间；空位子；余地", "english": "room", "type": "单词", "keyWords": [] },
    { "chinese": "为…留下空间", "english": "leave room for", "type": "短语", "keyWords": ["room"] },
    { "chinese": "给…腾出地方", "english": "make room for", "type": "短语", "keyWords": ["room"] },
    { "chinese": "（没）有…余地", "english": "There's (no) room for...", "type": "短语", "keyWords": ["room"] },
    { "chinese": "你的工作还有改进的余地。", "english": "There's room for improvement in your work.", "type": "句子", "keyWords": ["room"] },
    { "chinese": "n. 根；根茎；词根；根源 v. （使）生/扎根；（使）牢固树立", "english": "root", "type": "单词", "keyWords": [] },
    { "chinese": "生（扎）根", "english": "take root", "type": "短语", "keyWords": ["root"] },
    { "chinese": "平方根", "english": "square root", "type": "短语", "keyWords": ["root"] },
    { "chinese": "连根拔起；根除，肃清", "english": "root up (the trees)", "type": "短语", "keyWords": ["root"] },
    { "chinese": "这种现象根源于国人的重理轻文。", "english": "This phenomenon is rooted in the Chinese thoughts that value sciences and neglect humanities.", "type": "句子", "keyWords": ["root"] },
    { "chinese": "n. 绳索；粗绳", "english": "rope", "type": "单词", "keyWords": [] },
    { "chinese": "n. 玫瑰", "english": "rose", "type": "单词", "keyWords": [] },
    { "chinese": "不尽人意", "english": "be not all roses", "type": "短语", "keyWords": ["rose"] },
    { "chinese": "人生绝非事事如意。", "english": "Life is not all roses by any means.", "type": "句子", "keyWords": ["rose"] },
    { "chinese": "没有十全十美。", "english": "There's no rose without a thorn.", "type": "句子", "keyWords": ["rose"] },
    { "chinese": "vi. 腐烂，腐败 v. 使腐烂；使腐朽", "english": "rot", "type": "单词", "keyWords": [] },
    { "chinese": "a. 腐烂的；腐臭的；腐败的；堕落的", "english": "rotten", "type": "单词", "keyWords": [] },
    { "chinese": "a. 粗糙的；粗制的；崎岖的；狂暴的；粗鲁的；粗略的；有暴风雨的", "english": "rough", "type": "单词", "keyWords": [] },
    { "chinese": "崎岖的小路", "english": "a rough road", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "狂风暴雨的天气", "english": "rough weather", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "在波涛汹涌的海上", "english": "in/on the rough sea", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "粗略地了解", "english": "get a rough idea of", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "（未切边的）毛边书", "english": "a book with rough edges", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "a. 圆的；环形的；十足的 prep. 围（绕）着；在…各处；在…一带/四周；大约 ad. 转过来；围绕 n. 一轮回，一回合", "english": "round", "type": "单词", "keyWords": [] },
    { "chinese": "来回的旅行", "english": "a round trip", "type": "短语", "keyWords": ["round"] },
    { "chinese": "十足的谎话", "english": "a round lie", "type": "短语", "keyWords": ["round"] },
    { "chinese": "另一轮的外交谈判", "english": "another round of diplomatic talks", "type": "短语", "keyWords": ["round"] },
    { "chinese": "正好相反；用正好相反的方法", "english": "be/go the other way round", "type": "短语", "keyWords": ["round"] },
    { "chinese": "(就)在拐弯处；即将到来", "english": "round the corner", "type": "短语", "keyWords": ["round"] },
    { "chinese": "就在街角拐弯处。", "english": "It's just round the corner of the street.", "type": "句子", "keyWords": ["round"] },
    { "chinese": "复活节就要来了。", "english": "Easter is round the corner.", "type": "句子", "keyWords": ["round"] },
    { "chinese": "全天候营业商店", "english": "a round-the-clock shop", "type": "短语", "keyWords": ["round"] },
    { "chinese": "把…聚集在一起；包围", "english": "round...up", "type": "短语", "keyWords": ["round"] },
    { "chinese": "将奶牛圈在一处挤奶", "english": "round up the cows for milking", "type": "短语", "keyWords": ["round"] },
    { "chinese": "n. （道）路；路/航线；途径 v. 给…规定路线/次序/程序", "english": "route", "type": "单词", "keyWords": [] },
    { "chinese": "去欧洲最快的路线", "english": "the quickest route to take to Europe", "type": "短语", "keyWords": ["route"] },
    { "chinese": "n. 例行公事；惯例 a. 例行的；常规的", "english": "routine", "type": "单词", "keyWords": [] },
    { "chinese": "v. 划（船） v. 使成行/排 n. （一）排；（一）行", "english": "row", "type": "单词", "keyWords": [] },
    { "chinese": "坐成一排", "english": "sit in a row", "type": "短语", "keyWords": ["row"] },
    { "chinese": "a. 国王的；女王的；王室的", "english": "royal", "type": "单词", "keyWords": [] },
    { "chinese": "v. 擦；摩擦", "english": "rub", "type": "单词", "keyWords": [] },
    { "chinese": "木炭块同玻璃棒一摩擦棒上就带电。", "english": "No sooner had the pieces of charcoal been rubbed against the glass rod than electricity appeared on the rod.", "type": "句子", "keyWords": ["rub"] },
    { "chinese": "n. 橡胶；橡皮", "english": "rubber", "type": "单词", "keyWords": [] },
    { "chinese": "n. 垃圾，废物", "english": "rubbish", "type": "单词", "keyWords": [] },
    { "chinese": "说废话", "english": "talk rubbish", "type": "短语", "keyWords": ["rubbish"] },
    { "chinese": "a. 粗鲁的；粗糙的；猛烈的；简单的", "english": "rude", "type": "单词", "keyWords": [] },
    { "chinese": "n. 粗鲁，粗暴", "english": "rudeness", "type": "单词", "keyWords": [] },
    { "chinese": "草图，简图", "english": "a rude drawing", "type": "短语", "keyWords": ["rude"] },
    { "chinese": "对某人粗暴无礼", "english": "be rude to sb.", "type": "短语", "keyWords": ["rude"] },
    { "chinese": "v./n. 毁坏；毁灭；毁掉（前途）；使破产；废墟", "english": "ruin", "type": "单词", "keyWords": [] },
    { "chinese": "坏掉；毁灭，灭亡；崩溃", "english": "go/come/fall to ruin", "type": "短语", "keyWords": ["ruin"] },
    { "chinese": "成为废墟", "english": "be in ruins", "type": "短语", "keyWords": ["ruin"] },
    { "chinese": "n. 规则，规章；惯例，准则；统治，治理；控制；支配", "english": "rule", "type": "单词", "keyWords": [] },
    { "chinese": "v. 统治，治理", "english": "rule", "type": "单词", "keyWords": [] },
    { "chinese": "按规定，按规则，依照规则；机械地", "english": "by rule", "type": "短语", "keyWords": ["rule"] },
    { "chinese": "通常；总体上", "english": "as a rule", "type": "短语", "keyWords": ["rule"] },
    { "chinese": "养成习惯；规定…", "english": "make it a rule to do sth.", "type": "短语", "keyWords": ["rule"] },
    { "chinese": "有规则必有例外。", "english": "There is no rule without an exception.", "type": "句子", "keyWords": ["rule"] },
    { "chinese": "n. 直尺；统治者，管理者", "english": "ruler", "type": "单词", "keyWords": [] },
    { "chinese": "v. 跑；奔；竞选；（机器等）运转；流淌；（织物上染料）渗化或渗色；变（成） v. 使跑；使奔；在…上跑；经营，管理", "english": "run", "type": "单词", "keyWords": [] },
    { "chinese": "偶然遇见；撞上；陷入（困境等）", "english": "run/bump into", "type": "短语", "keyWords": ["run"] },
    { "chinese": "我们开始负债了。", "english": "We ran into debt.", "type": "句子", "keyWords": ["run"] },
    { "chinese": "汽车撞倒并碾过他的身体。", "english": "The car ran over him.", "type": "句子", "keyWords": ["run"] },
    { "chinese": "用完，耗尽（主动）", "english": "(sb.) run out of sth.", "type": "短语", "keyWords": ["run"] },
    { "chinese": "被耗尽/变松（被动）", "english": "run out/loose", "type": "短语", "keyWords": ["run"] },
    { "chinese": "(因耗尽而)缺少", "english": "(sb.) run short of sth.", "type": "短语", "keyWords": ["run"] },
    { "chinese": "变冷/干涸/被用完", "english": "run cold/dry/short", "type": "短语", "keyWords": ["run"] },
    { "chinese": "颜色褪色。", "english": "The color runs.", "type": "句子", "keyWords": ["run"] },
    { "chinese": "偶遇，不期而遇", "english": "run/come across", "type": "短语", "keyWords": ["run"] },
    { "chinese": "赶快去求救", "english": "run for help", "type": "短语", "keyWords": ["run"] },
    { "chinese": "到处跑，跑来跑去", "english": "run about", "type": "短语", "keyWords": ["run"] },
    { "chinese": "竞选市长", "english": "run for mayor", "type": "短语", "keyWords": ["run"] },
    { "chinese": "追赶；追捕；跟踪", "english": "run after", "type": "短语", "keyWords": ["run"] },
    { "chinese": "忙碌", "english": "be on the run", "type": "短语", "keyWords": ["run"] },
    { "chinese": "从长远来看；终究", "english": "in the long run", "type": "短语", "keyWords": ["run"] },
    { "chinese": "发高烧；说胡话", "english": "run a high fever", "type": "短语", "keyWords": ["run"] },
    { "chinese": "流鼻涕", "english": "have a running nose", "type": "短语", "keyWords": ["run"] },
    { "chinese": "这个剧连演了六个月。", "english": "The play ran for six months.", "type": "句子", "keyWords": ["run"] },
    { "chinese": "n. 跑步的人；赛跑的人（或马等）", "english": "runner", "type": "单词", "keyWords": [] },
    { "chinese": "a. 农村的；乡下的，田园的，乡村风味的", "english": "rural", "type": "单词", "keyWords": [] },
    { "chinese": "v. 冲；奔；猛攻 v. 急冲；逼；催促；猛攻；急送", "english": "rush", "type": "单词", "keyWords": [] },
    { "chinese": "n. 冲；奔；匆忙；（交通、事务等）繁忙；猛攻", "english": "rush", "type": "单词", "keyWords": [] },
    { "chinese": "把他急匆匆地送到医院", "english": "rush him to a hospital", "type": "短语", "keyWords": ["rush"] },
    { "chinese": "为什么这样急急忙忙的？", "english": "Why all this rush?", "type": "句子", "keyWords": ["rush"] },
    { "chinese": "猛然冲向（出口处）", "english": "make a rush for (the exit)", "type": "短语", "keyWords": ["rush"] },
    { "chinese": "这本小说是以1849年加利福尼亚州淘金热为背景的。", "english": "This novel is set in the 1849 California gold rush.", "type": "句子", "keyWords": ["rush"] },
    { "chinese": "在交通高峰期", "english": "in the rush hour", "type": "短语", "keyWords": ["rush"] },
    { "chinese": "急速地", "english": "in a rush", "type": "短语", "keyWords": ["rush"] },
    { "chinese": "v.（使）生锈", "english": "rust", "type": "单词", "keyWords": [] },
    { "chinese": "a. 生锈的；迟钝的；腐蚀了的", "english": "rusty", "type": "单词", "keyWords": [] },
    { "chinese": "n. 麻袋；包；（一）大袋；纸袋；[口]解雇", "english": "sack", "type": "单词", "keyWords": [] },
    { "chinese": "被解雇", "english": "get the sack", "type": "短语", "keyWords": ["sack"] },
    { "chinese": "解雇某人", "english": "give sb. the sack", "type": "短语", "keyWords": ["sack"] },
    { "chinese": "n. 献身，牺牲；祭献；祭品；供奉 v. 牺牲；祭献；献出", "english": "sacrifice", "type": "单词", "keyWords": [] },
    { "chinese": "宰羊作为供品", "english": "kill sheep as a sacrifice", "type": "短语", "keyWords": ["sacrifice"] },
    { "chinese": "亏本/蚀本出售", "english": "sell sth. at a sacrifice", "type": "短语", "keyWords": ["sacrifice"] },
    { "chinese": "我绝没想到要你作出这样的牺牲。", "english": "I would never dream of asking you to make such a sacrifice.", "type": "句子", "keyWords": ["sacrifice"] },
    { "chinese": "他为拯救落水的孩子而献出自己的生命。", "english": "He sacrificed his life to save the drowning child.", "type": "句子", "keyWords": ["sacrifice"] },
    { "chinese": "为…而献身", "english": "sacrifice/lose one's life for (one's motherland)", "type": "短语", "keyWords": ["sacrifice"] },
    { "chinese": "a. 伤心的；难过的；令人悲伤的", "english": "sad", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 伤心地，难过地", "english": "sadly", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使悲伤；使伤心", "english": "sadden", "type": "单词", "keyWords": [] },
    { "chinese": "n. 悲伤，伤心", "english": "sadness", "type": "单词", "keyWords": [] },
    { "chinese": "a. 安全的；平安的；谨慎的", "english": "safe", "type": "单词", "keyWords": [] },
    { "chinese": "n. 保险箱；冷藏柜/室", "english": "safe", "type": "单词", "keyWords": [] },
    { "chinese": "平安无事地归来", "english": "return safe and sound", "type": "短语", "keyWords": ["safe"] },
    { "chinese": "没…危险的，安全的", "english": "be safe from...", "type": "短语", "keyWords": ["safe"] },
    { "chinese": "他安全到达。", "english": "He arrived safe.", "type": "句子", "keyWords": ["safe"] },
    { "chinese": "n. 安全；平安；安全地点", "english": "safety", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 安全地，平安地", "english": "safely", "type": "单词", "keyWords": [] },
    { "chinese": "把某人带到安全地带", "english": "carry sb. to safety", "type": "短语", "keyWords": ["safety"] },
    { "chinese": "安全带", "english": "safety belt", "type": "短语", "keyWords": ["safety"] },
    { "chinese": "安全别针", "english": "safety pin", "type": "短语", "keyWords": ["safety"] },
    { "chinese": "vi. 航行 v. 航行于；驾驶（船）", "english": "sail", "type": "单词", "keyWords": [] },
    { "chinese": "n. 帆", "english": "sail", "type": "单词", "keyWords": [] },
    { "chinese": "n. 海员，水手", "english": "sailor", "type": "单词", "keyWords": [] },
    { "chinese": "起航去某地", "english": "set sail for... / sail for...", "type": "短语", "keyWords": ["sail"] },
    { "chinese": "横渡太平洋", "english": "sail the Pacific", "type": "短语", "keyWords": ["sail"] },
    { "chinese": "n. 缘故；利益", "english": "sake", "type": "单词", "keyWords": [] },
    { "chinese": "为了…的利益/缘故，为了…", "english": "for the sake of sb. = for sb.'s sake", "type": "短语", "keyWords": ["sake"] },
    { "chinese": "看在上帝的份上", "english": "for God's/goodness/heaven's sake", "type": "短语", "keyWords": ["sake"] },
    { "chinese": "n. 色拉；凉拌菜", "english": "salad", "type": "单词", "keyWords": [] },
    { "chinese": "色拉用调料", "english": "salad dressing", "type": "短语", "keyWords": ["salad"] },
    { "chinese": "n. 薪水", "english": "salary", "type": "单词", "keyWords": [] },
    { "chinese": "薪水微薄/丰厚", "english": "a small/good/high/handsome salary", "type": "短语", "keyWords": ["salary"] },
    { "chinese": "n. 出售；廉价出售；销量；销售额", "english": "sale", "type": "单词", "keyWords": [] },
    { "chinese": "有售；上市；廉价出售", "english": "on sale", "type": "短语", "keyWords": ["sale"] },
    { "chinese": "供出售；待售", "english": "for sale", "type": "短语", "keyWords": ["sale"] },
    { "chinese": "销货损益", "english": "sales profit and loss", "type": "短语", "keyWords": ["sales"] },
    { "chinese": "营业部", "english": "sales department", "type": "短语", "keyWords": ["sales"] },
    { "chinese": "n. 推销员", "english": "salesman", "type": "单词", "keyWords": [] },
    { "chinese": "n. 盐 v. 在…中/上加盐；腌", "english": "salt", "type": "单词", "keyWords": [] },
    { "chinese": "a. 含盐的；咸的", "english": "salty", "type": "单词", "keyWords": [] }
];
qgl229_236.sort(() => Math.random() - 0.5);
