const qgl237_244 = [
    { "chinese": "a.相同的;同样的(常与the连用)", "english": "same", "type": "单词", "keyWords": [] },
    { "chinese": "仍然;还是;完全一样,无所谓", "english": "all just the same (to sb.or sth.)", "type": "短语", "keyWords": ["same"] },
    { "chinese": "差不多完全一样,几乎一样;大同小异", "english": "about/much the same", "type": "短语", "keyWords": ["same"] },
    { "chinese": "有点两样", "english": "not quite the same", "type": "短语", "keyWords": ["same"] },
    { "chinese": "和...一样", "english": "the same ...as/ that...", "type": "短语", "keyWords": ["same"] },
    { "chinese": "[口]我也这样祝愿你!", "english": "The same to you!", "type": "句子", "keyWords": ["same"] },
    { "chinese": "...一样", "english": "It is the same with.../ So it is with...", "type": "短语", "keyWords": ["same"] },
    { "chinese": "...也是如此", "english": "The same is true of...", "type": "短语", "keyWords": ["same"] },
    { "chinese": "n.[C]样品;试样;实例 vt.抽样检查;品尝(食品)", "english": "sample", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]沙;(pl.)沙滩;大片沙地", "english": "sand", "type": "单词", "keyWords": [] },
    { "chinese": "a.沙地的,多沙的", "english": "sandy", "type": "单词", "keyWords": [] },
    { "chinese": "不切实际;不稳固的;不稳妥的", "english": "be built on sand", "type": "短语", "keyWords": ["sand"] },
    { "chinese": "n.[C]三明治 vt.把..夹在中间;插入,夹入", "english": "sandwich", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]卫星", "english": "satellite", "type": "单词", "keyWords": [] },
    { "chinese": "卫星城市", "english": "a satellite city", "type": "短语", "keyWords": ["satellite"] },
    { "chinese": "n.[C/U]满意,满足 n.[C]令人满意的事物", "english": "satisfaction", "type": "单词", "keyWords": [] },
    { "chinese": "对...表示满意", "english": "express one's satisfaction at/ with", "type": "短语", "keyWords": ["satisfaction"] },
    { "chinese": "满意地", "english": "with satisfaction", "type": "短语", "keyWords": ["satisfaction"] },
    { "chinese": "达到使某人满意的程度", "english": "to sb's satisfaction", "type": "短语", "keyWords": ["satisfaction"] },
    { "chinese": "a.令人满意的;可喜的", "english": "satisfactory", "type": "单词", "keyWords": [] },
    { "chinese": "很不令人满意", "english": "be anything but satisfactory", "type": "短语", "keyWords": ["satisfactory"] },
    { "chinese": "完全不令人满意", "english": "be far from satisfactory", "type": "短语", "keyWords": ["satisfactory"] },
    { "chinese": "vt.使满意;满足(需要);达到(要求),符合(条件)", "english": "satisfy", "type": "单词", "keyWords": [] },
    { "chinese": "对...感到满意", "english": "be satisfied with", "type": "短语", "keyWords": ["satisfy"] },
    { "chinese": "满意的神情", "english": "a satisfied look", "type": "短语", "keyWords": ["satisfy"] },
    { "chinese": "令人满意的结局", "english": "a satisfying ending", "type": "短语", "keyWords": ["satisfy"] },
    { "chinese": "n.[C]星期六(缩)Sat.", "english": "Saturday", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]沙司,调味汁", "english": "sauce", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]茶碟;碟状物", "english": "saucer", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]香肠,腊肠", "english": "sausage", "type": "单词", "keyWords": [] },
    { "chinese": "vt.搭救;节省;储蓄(up) vi.节省(on)", "english": "save", "type": "单词", "keyWords": [] },
    { "chinese": "搭救..;使...免于...", "english": "save...from...", "type": "短语", "keyWords": ["save"] },
    { "chinese": "节约用电/节约用气", "english": "save/ economize on electricity/ gas", "type": "短语", "keyWords": ["save"] },
    { "chinese": "n.[C]节省;救助;(pl.)储蓄(金);存款", "english": "saving", "type": "单词", "keyWords": [] },
    { "chinese": "v.说话;讲话 v.说;讲;假定;比如说;显示;写着 n.[C]发言权", "english": "say", "type": "单词", "keyWords": [] },
    { "chinese": "自言自语", "english": "say sth. to oneself", "type": "短语", "keyWords": ["say"] },
    { "chinese": "我想,大概", "english": "I dare say", "type": "短语", "keyWords": ["say"] },
    { "chinese": "据说在.../已经...", "english": "be said to be doing/ to have done", "type": "短语", "keyWords": ["say"] },
    { "chinese": "现在时间是两点半。", "english": "The clock says half past two.", "type": "句子", "keyWords": ["say"] },
    { "chinese": "不用说,不言而喻,理所当然", "english": "It goes without saying that...", "type": "短语", "keyWords": ["say"] },
    { "chinese": "很难说;没法知道;没法预料", "english": "There is no saying...", "type": "短语", "keyWords": ["say"] },
    { "chinese": "更不用说(近let alone, not to mention)", "english": "to say nothing of", "type": "短语", "keyWords": ["say"] },
    { "chinese": "报上说", "english": "It says in the newspaper that...", "type": "短语", "keyWords": ["say"] },
    { "chinese": "即,换句话说(无过去式)", "english": "that is (to say) (=in other words)", "type": "短语", "keyWords": ["say"] },
    { "chinese": "否定,拒绝,反对/肯定,赞成,同意", "english": "say no/ yes to (doing) sth.", "type": "短语", "keyWords": ["say"] },
    { "chinese": "[口]你对某事有什么意见?你赞成不赞成做某事?", "english": "What do/ would you say to doing sth.?", "type": "句子", "keyWords": ["say"] },
    { "chinese": "余下的数目不大,姑且说,只有十个吧。", "english": "The number left was not great, say, only ten.", "type": "句子", "keyWords": ["say"] },
    { "chinese": "对此事父亲有最后的决定权。", "english": "The father had the final say in the matter.", "type": "句子", "keyWords": ["say"] },
    { "chinese": "说起来容易做起来难。", "english": "Easier said than done.", "type": "句子", "keyWords": ["say"] },
    { "chinese": "n.[C]谚语,俗语;格言", "english": "saying", "type": "单词", "keyWords": [] },
    { "chinese": "俗话说;常言道", "english": "As the saying goes (As the proverb says)....", "type": "短语", "keyWords": ["saying"] },
    { "chinese": "俗话说:常言道", "english": "A saying goes that...", "type": "短语", "keyWords": ["saying"] },
    { "chinese": "n.[C]等级(表);刻度;比例;规模;范围;鳞片;(pl.)天平;(磅)秤 v.量(为)(近weigh)(被)过称", "english": "scale", "type": "单词", "keyWords": [] },
    { "chinese": "罗盘标度", "english": "compass scale", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "折尺", "english": "a folding scale", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "大规模地", "english": "on a big/large scale", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "按...比例;按...规模", "english": "on the/ a scale of", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "在磅秤上称体重", "english": "weigh sth. on the scales", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "v.快读;扫描", "english": "scan", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]扫描仪;扫描器", "english": "scanner", "type": "单词", "keyWords": [] },
    { "chinese": "a.缺乏的;稀有的", "english": "scarce", "type": "单词", "keyWords": [] },
    { "chinese": "ad.几乎不;刚刚;才", "english": "scarcely", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U](可与a连用)稀缺资源", "english": "scarcity", "type": "单词", "keyWords": [] },
    { "chinese": "稀缺资源", "english": "scarce resources", "type": "短语", "keyWords": ["scarce"] },
    { "chinese": "一...就....", "english": "scarcely/hardly ... when ...", "type": "短语", "keyWords": ["scarcely"] },
    { "chinese": "他刚刚到达就不得不又离开。", "english": "Scarcely had he arrived when he had to leave again.", "type": "句子", "keyWords": ["scarcely"] },
    { "chinese": "v.使惊恐,使害怕 n.[U]惊恐,恐慌", "english": "scare", "type": "单词", "keyWords": [] },
    { "chinese": "把...吓跑", "english": "scare ...away", "type": "短语", "keyWords": ["scare"] },
    { "chinese": "吓得要死", "english": "be scared to death", "type": "短语", "keyWords": ["scare"] },
    { "chinese": "害怕...", "english": "be scared/ afraid/ frightened of", "type": "短语", "keyWords": ["scare"] },
    { "chinese": "吓得做/不敢做某事", "english": "be scared into/ out of doing sth.", "type": "短语", "keyWords": ["scare"] },
    { "chinese": "n.[C]围巾;(肩)巾", "english": "scarf", "type": "单词", "keyWords": [] },
    { "chinese": "vt.撒;分散;驱散 vi.散开", "english": "scatter", "type": "单词", "keyWords": [] },
    { "chinese": "把种子撒播在地里", "english": "scatter the fields with seeds = scatter seeds on the fields", "type": "短语", "keyWords": ["scatter"] },
    { "chinese": "稀疏的人口", "english": "a thinly scattered population", "type": "短语", "keyWords": ["scatter"] },
    { "chinese": "n.[C]景色;布景,场景;地点;现场", "english": "scene", "type": "单词", "keyWords": [] },
    { "chinese": "a.风景优美的,舞台的", "english": "scenic", "type": "单词", "keyWords": [] },
    { "chinese": "一派繁荣景象", "english": "a scene of prosperity", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "第一幕第二场", "english": "Act I Scene II", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "在现场;到现场", "english": "on the scene/spot", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "犯罪/车祸现场", "english": "the scene of the crime/ a traffic accident", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "景点(近tourist attractions, places of interest)", "english": "scenic spots", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "n.[U]风景,景色", "english": "scenery", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]时间表;计划(表);日程安排(表);进度表 v.将....列入时间表中,排定(在某时间做某事)", "english": "schedule", "type": "单词", "keyWords": [] },
    { "chinese": "定期航班", "english": "a scheduled flight", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "晚了", "english": "behind schedule", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "提前(近ahead of time, beforehand )", "english": "ahead of schedule", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "准时:按照时间表(近according to schedule)", "english": "on schedule", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "下周工作时间进度表", "english": "time schedule for next week", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "罢工计划在黎明开始实施。", "english": "The strike was scheduled to begin at dawn.", "type": "句子", "keyWords": ["schedule"] },
    { "chinese": "n.[C]计划;方案:规划;阴谋,诡计 v.搞阴谋;兼划;密谋", "english": "scheme", "type": "单词", "keyWords": [] },
    { "chinese": "想出筹钱的方法", "english": "work out a scheme for raising money", "type": "短语", "keyWords": ["scheme"] },
    { "chinese": "n.[C]学者", "english": "scholar", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]奖学金 n.[U]学问", "english": "scholarship", "type": "单词", "keyWords": [] },
    { "chinese": "获奖学金", "english": "win a scholarship", "type": "短语", "keyWords": ["scholarship"] },
    { "chinese": "n.[C]学校;流派,学派;(鱼)群 n.[U]上学,在学习", "english": "school", "type": "单词", "keyWords": [] },
    { "chinese": "上学", "english": "at school", "type": "短语", "keyWords": ["school"] },
    { "chinese": "毕业", "english": "leave/ finish school", "type": "短语", "keyWords": ["school"] },
    { "chinese": "入学", "english": "start school", "type": "短语", "keyWords": ["school"] },
    { "chinese": "学生时代", "english": "school days", "type": "短语", "keyWords": ["school"] },
    { "chinese": "一群鲸", "english": "a school of whales", "type": "短语", "keyWords": ["school"] },
    { "chinese": "校舍", "english": "schoolhouse", "type": "单词", "keyWords": [] },
    { "chinese": "新分析法学派", "english": "new analytical school of law", "type": "短语", "keyWords": ["school"] },
    { "chinese": "n.[U]学校教育", "english": "schooling", "type": "单词", "keyWords": [] },
    { "chinese": "他们没受过什么学校教育。", "english": "They have little schooling.", "type": "句子", "keyWords": ["schooling"] },
    { "chinese": "n.[U]科学;自然科学 n.[C]一门(科学的)学科", "english": "science", "type": "单词", "keyWords": [] },
    { "chinese": "科学技术,科技", "english": "science and technology", "type": "短语", "keyWords": ["science"] },
    { "chinese": "天文学是一个非常复杂的学科。", "english": "Astronomy is a very complicated science.", "type": "句子", "keyWords": ["science"] },
    { "chinese": "a.科学(上)的;科学性的", "english": "scientific", "type": "单词", "keyWords": [] },
    { "chinese": "ad.科学地", "english": "scientifically", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]科学家", "english": "scientist", "type": "单词", "keyWords": [] },
    { "chinese": "n.(作pl.)剪刀", "english": "scissors", "type": "单词", "keyWords": [] },
    { "chinese": "一把剪刀", "english": "a pair of scissors", "type": "短语", "keyWords": ["scissors"] },
    { "chinese": "v.责骂;谩骂;叱责", "english": "scold", "type": "单词", "keyWords": [] },
    { "chinese": "因某事而责备某人", "english": "scold sb. for (doing) sth.", "type": "短语", "keyWords": ["scold"] },
    { "chinese": "(因某事)挨一顿大骂", "english": "get/ receive a good scolding (for sth.)", "type": "短语", "keyWords": ["scold"] },
    { "chinese": "把某人大骂一顿", "english": "give sb. a good scolding", "type": "短语", "keyWords": ["scold"] },
    { "chinese": "n.[C](比赛中)得分,比分;(测验中)成绩,分数;二十个(单复同) vt.得 (分);记(分);赢得 vi.得分;得胜", "english": "score", "type": "单词", "keyWords": [] },
    { "chinese": "踢进一个球", "english": "score a goal", "type": "短语", "keyWords": ["score"] },
    { "chinese": "得一分", "english": "score a point", "type": "短语", "keyWords": ["score"] },
    { "chinese": "70个人", "english": "three score and ten people", "type": "短语", "keyWords": ["score"] },
    { "chinese": "许多年", "english": "scores of years", "type": "短语", "keyWords": ["score"] },
    { "chinese": "40个鸡蛋", "english": "two score of eggs", "type": "短语", "keyWords": ["score"] },
    { "chinese": "vt.抓;划伤 n.[C]抓痕;搔", "english": "scratch", "type": "单词", "keyWords": [] },
    { "chinese": "vi.(因恐惧、痛苦等)尖声喊叫;惊叫 n.[C]尖叫声", "english": "scream", "type": "单词", "keyWords": [] },
    { "chinese": "放声大笑", "english": "scream with laughter", "type": "短语", "keyWords": ["scream"] },
    { "chinese": "大叫", "english": "scream out", "type": "短语", "keyWords": ["scream"] },
    { "chinese": "n.[C]屏;幕;银幕 vt.遮蔽;掩护", "english": "screen", "type": "单词", "keyWords": [] },
    { "chinese": "vt.用力擦洗;擦净", "english": "scrub", "type": "单词", "keyWords": [] },
    { "chinese": "擦洗地板", "english": "scrub the floor", "type": "短语", "keyWords": ["scrub"] },
    { "chinese": "n.[U]雕刻,雕塑 n.[C]雕刻品,雕塑品 v.雕塑", "english": "sculpture", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]海,海洋;大量", "english": "sea", "type": "单词", "keyWords": [] },
    { "chinese": "(住)在海外", "english": "(live) beyond the sea(s)", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "一大片,大量...", "english": "a sea of (flowers/ troubles...)", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "去当海员", "english": "go to sea", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "到海边去", "english": "go to the sea", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "在海上(= on the sea);不知所措,茫然(=at a loss)", "english": "at sea", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "这艘船驶向大海。", "english": "The ship headed out to sea.", "type": "句子", "keyWords": ["sea"] },
    { "chinese": "n.[U]海产食品;海味,海鲜", "english": "seafood", "type": "单词", "keyWords": [] },
    { "chinese": "海鸥", "english": "sea gull", "type": "单词", "keyWords": [] },
    { "chinese": "海马", "english": "sea horse", "type": "单词", "keyWords": [] },
    { "chinese": "海贝壳", "english": "seashell", "type": "单词", "keyWords": [] },
    { "chinese": "海岸", "english": "seashore", "type": "单词", "keyWords": [] },
    { "chinese": "晕船的", "english": "seasick", "type": "单词", "keyWords": [] },
    { "chinese": "海藻,海草", "english": "seaweed", "type": "单词", "keyWords": [] },
    { "chinese": "海平面", "english": "sea level", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]印章/记;图章;封印/蜡/条/铅;批准;海豹 v.盖章于;(密)封;批准", "english": "seal", "type": "单词", "keyWords": [] },
    { "chinese": "在箱子上贴上封条", "english": "put a seal on the box", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "在合同上盖章", "english": "seal a contract", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封信封", "english": "seal an envelope", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封锁大楼", "english": "seal off the building", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封在罐子里", "english": "seal...in a can", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封好口的信", "english": "a sealed letter", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封,火漆", "english": "sealing wax", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "n.[C]搜寻,搜查 v.搜查;细查;在...中搜寻 vi.搜寻,搜查;追/探求", "english": "search", "type": "单词", "keyWords": [] },
    { "chinese": "仔细打量我;盘诘性地看我", "english": "give me a searching look", "type": "短语", "keyWords": ["search"] },
    { "chinese": "搜索水下的那个运动目标是一个较难的问题。", "english": "The search for the moving target under water was a tough problem.", "type": "句子", "keyWords": ["search"] },
    { "chinese": "在搜查房子时发现了两支没注册登记的枪。", "english": "The search of the house produced two unregistered guns.", "type": "句子", "keyWords": ["search"] },
    { "chinese": "搜寻、寻找", "english": "search...for...", "type": "短语", "keyWords": ["search"] },
    { "chinese": "警察在住宅内搜查藏匿的武器。", "english": "The police search a house for a hidden weapon.", "type": "句子", "keyWords": ["search"] },
    { "chinese": "(为了)寻找(常用作状语或表语)", "english": "in search of/ for", "type": "短语", "keyWords": ["search"] },
    { "chinese": "他们出发去寻找走失的孩子。", "english": "They set off in search of the lost child.", "type": "句子", "keyWords": ["search"] },
    { "chinese": "n.[C]海边;海滨 a.海边的;海滨的", "english": "seaside", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]时节,旺季;季(节);(体育、文艺、社交或商业季)活跃季节 v.调味,给...加调味料", "english": "season", "type": "单词", "keyWords": [] },
    { "chinese": "a.季节(性)的", "english": "seasonal", "type": "单词", "keyWords": [] },
    { "chinese": "上市", "english": "come into season", "type": "短语", "keyWords": ["season"] },
    { "chinese": "上市;当令;在旺季;在度假旺季", "english": "in season", "type": "短语", "keyWords": ["season"] },
    { "chinese": "不上市;不当令;不在旺季;在度假淡季", "english": "out of season", "type": "短语", "keyWords": ["season"] },
    { "chinese": "用盐和胡椒来调味", "english": "season the dish with salt and pepper", "type": "短语", "keyWords": ["season"] },
    { "chinese": "a.调过味的", "english": "seasoned", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]调味品,调料", "english": "seasoning", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]座位 v.使坐下,使就座;能容纳", "english": "seat", "type": "单词", "keyWords": [] },
    { "chinese": "就座(近take one's place就座;代替)", "english": "take one's seat", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "坐下", "english": "take/ have a seat", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "容纳200人", "english": "seat/ hold 200 people", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "就座", "english": "seat oneself", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "请坐。", "english": "Please be/ get seated.", "type": "句子", "keyWords": ["seat"] },
    { "chinese": "发现他独自坐在房间里", "english": "find him seated/ sitting alone in the room", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "a.第二的 ad.第二,其次地 n.[C]秒;片刻;第二", "english": "second", "type": "单词", "keyWords": [] },
    { "chinese": "仅次于", "english": "(be) second only to...", "type": "短语", "keyWords": ["second"] },
    { "chinese": "[口]比谁都好;首屈一指", "english": "(be) second to none", "type": "短语", "keyWords": ["second"] },
    { "chinese": "你还需要一双。", "english": "You need a second pair.", "type": "句子", "keyWords": ["second"] },
    { "chinese": "获第二", "english": "come (in) second", "type": "短语", "keyWords": ["second"] },
    { "chinese": "再经考虑我会接受那个报价的。", "english": "On second thoughts I will accept the offer.", "type": "句子", "keyWords": ["second"] },
    { "chinese": "第一/二个离开(不用leaving)", "english": "(be) the frst/ second to leave", "type": "短语", "keyWords": ["second"] },
    { "chinese": "a.(教育、学校等)中等的;第二的", "english": "secondary", "type": "单词", "keyWords": [] },
    { "chinese": "a.用过的;旧的;间接的;(第)二手的", "english": "secondhand", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]秘密;秘诀(of) a.秘密的;暗中的", "english": "secret", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]秘密,保密", "english": "secrecy", "type": "单词", "keyWords": [] },
    { "chinese": "公开的秘密", "english": "an open secret", "type": "短语", "keyWords": ["secret"] },
    { "chinese": "秘密地(=secretly)", "english": "in secret", "type": "短语", "keyWords": ["secret"] },
    { "chinese": "不把某事告诉某人", "english": "keep sth. (a) secret (from sb.)", "type": "短语", "keyWords": ["secret"] },
    { "chinese": "n.[C]秘书;书记", "english": "secretary", "type": "单词", "keyWords": [] },
    { "chinese": "总书记", "english": "secretary general", "type": "短语", "keyWords": ["secretary"] },
    { "chinese": "n.[C]部分;(文章等)段,节;(部门)处,科,股;地段;切面", "english": "section", "type": "单词", "keyWords": [] },
    { "chinese": "a.安全可靠的,有保障的;牢固的;安心的;无忧虑的 v.使安全;保卫;妥善保管;获得", "english": "secure", "type": "单词", "keyWords": [] },
    { "chinese": "不致受到危害", "english": "be secure/safe from harm", "type": "短语", "keyWords": ["secure"] },
    { "chinese": "对未来感到放心", "english": "feel secure about/ as to one's future", "type": "短语", "keyWords": ["secure"] },
    { "chinese": "有必胜的信念", "english": "be secure/ sure/ certain of victory", "type": "短语", "keyWords": ["secure"] },
    { "chinese": "他关紧门窗。", "english": "He secured the doors and windows.", "type": "句子", "keyWords": ["secure"] },
    { "chinese": "她已获得一份好工作。", "english": "She has secured a good job.", "type": "句子", "keyWords": ["secure"] },
    { "chinese": "n.[U]平安;安全感;保护措施(against/ from)", "english": "security", "type": "单词", "keyWords": [] },
    { "chinese": "安全感", "english": "sense of security", "type": "短语", "keyWords": ["security"] },
    { "chinese": "保安警察", "english": "security police", "type": "短语", "keyWords": ["security"] },
    { "chinese": "公安", "english": "public security", "type": "短语", "keyWords": ["security"] },
    { "chinese": "警卫", "english": "security guard", "type": "短语", "keyWords": ["security"] },
    { "chinese": "v.看见;观看;领会,理解;查明;注意,留神", "english": "see", "type": "单词", "keyWords": [] },
    { "chinese": "经常/较少/较多见到某人", "english": "see a lot/ less/ more of sb.", "type": "短语", "keyWords": ["see"] },
    { "chinese": "亲自去看/亲自去了解", "english": "see for oneself", "type": "短语", "keyWords": ["see"] },
    { "chinese": "她必须亲自查看,便走进车库。", "english": "she had to see for herself and went into the garage.", "type": "句子", "keyWords": ["see"] },
    { "chinese": "[口]再见!", "english": "I'll be seeing you!= See you!", "type": "句子", "keyWords": ["see"] },
    { "chinese": "为...送行/把某人送到门口", "english": "see sb.off/ see sb. to the door", "type": "短语", "keyWords": ["see"] },
    { "chinese": "看穿/识破(鬼把戏)", "english": "see through (a trick)", "type": "短语", "keyWords": ["see"] },
    { "chinese": "很清楚他的表面功夫", "english": "see through his superficial charm", "type": "短语", "keyWords": ["see"] },
    { "chinese": "注意;处理,负责,照料", "english": "see to (doing) sth.", "type": "短语", "keyWords": ["see"] },
    { "chinese": "负责此事/负责把汽车开出来", "english": "see to the matter/ see to getting the car out", "type": "短语", "keyWords": ["see"] },
    { "chinese": "务必,保证;留心(=make sure that...)", "english": "see (to it) that...", "type": "短语", "keyWords": ["see"] },
    { "chinese": "确定可以立刻完成。", "english": "See to it that it gets done right away.", "type": "句子", "keyWords": ["see"] },
    { "chinese": "在我看来...", "english": "As far as I can see...", "type": "短语", "keyWords": ["see"] },
    { "chinese": "我明白了。", "english": "I see.", "type": "句子", "keyWords": ["see"] },
    { "chinese": "你只见树木不见森林。", "english": "You cannot see the wood for the trees.", "type": "句子", "keyWords": ["see"] },
    { "chinese": "中华人民共和国成立于1949年。", "english": "1949 saw the founding of the PRC.", "type": "句子", "keyWords": ["see"] },
    { "chinese": "许多人把她当作世界领袖。", "english": "Many saw her as a world leader.", "type": "句子", "keyWords": ["see"] },
    { "chinese": "耳听为虚,眼见为实。/百闻不如一见。", "english": "Words are but wind, but seeing is believing.", "type": "句子", "keyWords": ["see"] },
    { "chinese": "n.[C/U]种子 vt.播种(近sowvt.) vi.结籽", "english": "seed", "type": "单词", "keyWords": [] },
    { "chinese": "vt.寻找;寻求,探求(after/for);设法,企图(to do sth.)", "english": "seek", "type": "单词", "keyWords": [] },
    { "chinese": "vi.好像,似乎", "english": "seem", "type": "单词", "keyWords": [] },
    { "chinese": "ad.表面上,看起来", "english": "seemingly", "type": "单词", "keyWords": [] },
    { "chinese": "在我看来...", "english": "It seems to me that...", "type": "短语", "keyWords": ["seem"] },
    { "chinese": "看起来好像...", "english": "It seems asif...", "type": "短语", "keyWords": ["seem"] },
    { "chinese": "好像正/已经做某事", "english": "sb.seems tobe doing sth./to havedone sth.", "type": "短语", "keyWords": ["seem"] },
    { "chinese": "v.抓住;夺取,攻占;理解;(疾病)侵袭(常被动)", "english": "seize", "type": "单词", "keyWords": [] },
    { "chinese": "抓住机会", "english": "seize a chance", "type": "短语", "keyWords": ["seize"] },
    { "chinese": "得了病/惊惶失措", "english": "be seized with a disease/ panic", "type": "短语", "keyWords": ["seize"] },
    { "chinese": "ad.很少", "english": "seldom", "type": "单词", "keyWords": [] },
    { "chinese": "这个岛难得有船停靠。", "english": "The island is seldom, if ever,visited by ships.", "type": "句子", "keyWords": ["seldom"] },
    { "chinese": "他很少激动。", "english": "Seldom does he get excited.", "type": "句子", "keyWords": ["seldom"] },
    { "chinese": "v.选择;(谨慎)挑选 a.精选的", "english": "select", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]挑选,选集", "english": "selection", "type": "单词", "keyWords": [] },
    { "chinese": "表示\"自己的,(为、靠、由于)自己的,自动\"", "english": "self-", "type": "单词", "keyWords": [] },
    { "chinese": "自我为中心的", "english": "self-centred", "type": "单词", "keyWords": [] },
    { "chinese": "自信的", "english": "self-confident", "type": "单词", "keyWords": [] },
    { "chinese": "自控", "english": "self-control", "type": "单词", "keyWords": [] },
    { "chinese": "自尊", "english": "self-respect", "type": "单词", "keyWords": [] },
    { "chinese": "a.自私的", "english": "selfish", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]自私", "english": "selfishness", "type": "单词", "keyWords": [] },
    { "chinese": "v.卖,出售 vi.有销路", "english": "sell", "type": "单词", "keyWords": [] },
    { "chinese": "畅销", "english": "(sth.) sell well", "type": "短语", "keyWords": ["sell"] },
    { "chinese": "售完", "english": "sell out (be sold out)", "type": "短语", "keyWords": ["sell"] },
    { "chinese": "某物卖多少钱", "english": "sell sth. for (money)", "type": "短语", "keyWords": ["sell"] },
    { "chinese": "n.[C][美]学期", "english": "semester", "type": "单词", "keyWords": [] },
    { "chinese": "v.发送;寄;派遣;迫使(人或物迅速去)...vi.送信;派人", "english": "send", "type": "单词", "keyWords": [] },
    { "chinese": "派人去请(医生等)", "english": "send for(the doctor...)", "type": "短语", "keyWords": ["send"] },
    { "chinese": "使他发疯", "english": "send him crazy", "type": "短语", "keyWords": ["send"] },
    { "chinese": "发出(请柬等);放射(光等);长出(枝芽等)", "english": "send out", "type": "短语", "keyWords": ["send"] },
    { "chinese": "把某人打发走;撵走;解雇;开除", "english": "send sb.away", "type": "短语", "keyWords": ["send"] },
    { "chinese": "使...迅速去做某事(如移动)", "english": "send sb./sth.doing sth.", "type": "短语", "keyWords": ["send"] },
    { "chinese": "突如其来的大雨促使人们急忙找地方躲雨。", "english": "The sudden heavy rain sent people dashing for shelter.", "type": "句子", "keyWords": ["send"] },
    { "chinese": "a.较年长的;地位或级别较高的 n.[C]年长者;长辈;资历深者;高中三年级学生;大学四年级学生(反junior,类似superior/inferior)", "english": "senior", "type": "单词", "keyWords": [] },
    { "chinese": "比...年长的/地位或级别较高的", "english": "be senior to sb.", "type": "短语", "keyWords": ["senior"] },
    { "chinese": "她比我大四岁。", "english": "She is four years senior to me.", "type": "句子", "keyWords": ["senior"] },
    { "chinese": "他比我大三岁。", "english": "He is my senior by three years.", "type": "句子", "keyWords": ["senior"] },
    { "chinese": "老约翰·史密斯(与儿子同名的父亲)", "english": "John Smith Senior", "type": "短语", "keyWords": ["senior"] },
    { "chinese": "n.[C]感觉;知觉;理念,概念;意义,意思 v.觉得;意识到", "english": "sense", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]传感器", "english": "sensor", "type": "单词", "keyWords": [] },
    { "chinese": "醒悟", "english": "come to one's senses", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "神志不清", "english": "be out of one's senses", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "使某人恢复理性", "english": "bring sb. to one's senses", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "常识", "english": "common sense", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "在某种意义上", "english": "in a sense/ way", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "在广/狭义上", "english": "in a broad narrow sense", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "视/听/嗅/味/触觉", "english": "a sense of sight/ hearing/ smell/ taste/ touch", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "敏锐的幽默感", "english": "a keen sense ofhumor", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "有意义;有道理(可以和作形式主语的it连用)", "english": "make sense", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "让小孩玩火柴有意义吗?", "english": "Does it make sense to let children play with matches?", "type": "句子", "keyWords": ["sense"] },
    { "chinese": "理解", "english": "make sense (out) of", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "这些关于牺牲和英雄主义的故事是我们了解世界过程中的一部分。", "english": "Their stories about sacrifice and heroism are a part of the way we make sense of the world.", "type": "句子", "keyWords": ["sense"] },
    { "chinese": "做某事是没有意义的", "english": "There is no sense/ point in doing sth.", "type": "短语", "keyWords": ["sense"] },
    { "chinese": "这词你用作何意?", "english": "In what sense are you using the word?", "type": "句子", "keyWords": ["sense"] },
    { "chinese": "a.失去知觉的", "english": "senseless", "type": "单词", "keyWords": [] },
    { "chinese": "a.明智的,合情合理的;有知觉的", "english": "sensible", "type": "单词", "keyWords": [] },
    { "chinese": "a.敏感的;神经过敏的;灵敏的(to sth.)", "english": "sensitive", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]句子;宣判;判决 vt.宣判;判决", "english": "sentence", "type": "单词", "keyWords": [] },
    { "chinese": "判某人死刑/十年有期徒刑", "english": "sentence sb. to dcath/ ten years in prison", "type": "短语", "keyWords": ["sentence"] },
    { "chinese": "a.分开的;各自的;单独的 vi.分开;分居;分手,别离 v.使分开;使单独;划分;区分(from)", "english": "separate", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]分开,分离", "english": "separation", "type": "单词", "keyWords": [] },
    { "chinese": "孩子们各睡各人的床。", "english": "The children sleep in separate beds.", "type": "句子", "keyWords": ["separate"] },
    { "chinese": "不把这一个与其他的混放在一起", "english": "keep this one separate from the others", "type": "短语", "keyWords": ["separate"] },
    { "chinese": "把好的和坏的分开", "english": "separate the good ones from the bad ones", "type": "短语", "keyWords": ["separate"] },
    { "chinese": "我们谈到午夜才分手。", "english": "We talked until midnight and then separated.", "type": "句子", "keyWords": ["separate"] },
    { "chinese": "与家人分离五年后", "english": "after a separation of five years from his family", "type": "短语", "keyWords": ["separate"] },
    { "chinese": "n.[C]九月", "english": "september", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]系列;(单复同)连续(类似means, species)", "english": "series", "type": "单词", "keyWords": [] },
    { "chinese": "一系列", "english": "a series of ...(is ...)", "type": "短语", "keyWords": ["series"] },
    { "chinese": "连续地", "english": "in series", "type": "短语", "keyWords": ["series"] },
    { "chinese": "a.严重的;严肃的;当真的", "english": "serious", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]严重性,严肃,认真", "english": "seriousness", "type": "单词", "keyWords": [] },
    { "chinese": "对某事认真,不开玩笑", "english": "be serious about sth.", "type": "短语", "keyWords": ["serious"] },
    { "chinese": "重视;认真对待/想;当真", "english": "take..seriously", "type": "短语", "keyWords": ["serious"] },
    { "chinese": "n.[C]仆人,佣人", "english": "servant", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl. serfs) 农奴", "english": "serf", "type": "单词", "keyWords": [] },
    { "chinese": "vt.端(饭菜等);为...服务/效力;接待(顾客)vi.有用,起作用;服役;担公职;帮佣,当仆人", "english": "serve", "type": "单词", "keyWords": [] },
    { "chinese": "达到目的;管用", "english": "serve the purpose", "type": "短语", "keyWords": ["serve"] },
    { "chinese": "全心全意为人民服务", "english": "serve the people heart and soul", "type": "短语", "keyWords": ["serve"] },
    { "chinese": "在军队里服役/在政府里担任公职", "english": "serve in the army/ the government", "type": "短语", "keyWords": ["serve"] },
    { "chinese": "适用;充当...用(近act as)", "english": "serve as/for", "type": "短语", "keyWords": ["serve"] },
    { "chinese": "这只箱子能当个座儿。", "english": "The box will serve for a seat.", "type": "句子", "keyWords": ["serve"] },
    { "chinese": "有助于做某事", "english": "serve to dosth.", "type": "短语", "keyWords": ["serve"] },
    { "chinese": "隐藏或遮盖东西的遮盖物", "english": "a covering that serves to conceal or shelter something", "type": "短语", "keyWords": ["serve"] },
    { "chinese": "先到先得。", "english": "First come first served.", "type": "句子", "keyWords": ["serve"] },
    { "chinese": "罪有应得", "english": "serve (someone) right", "type": "短语", "keyWords": ["serve"] },
    { "chinese": "他活该。", "english": "It servos him right.", "type": "句子", "keyWords": ["serve"] },
    { "chinese": "n.[C/U]服务 n.[U]接待工作 n.[C]公用事业的公共设施;服务机构;兵役;宗教仪式;发球(方式)", "english": "service", "type": "单词", "keyWords": [] },
    { "chinese": "售后服务", "english": "after-sales service", "type": "短语", "keyWords": ["service"] },
    { "chinese": "听...差遣", "english": "at one's service", "type": "短语", "keyWords": ["service"] },
    { "chinese": "在使用;可用", "english": "in service/use", "type": "短语", "keyWords": ["service"] },
    { "chinese": "不可使用", "english": "out of service", "type": "短语", "keyWords": ["service"] },
    { "chinese": "对...有好处;为...服务", "english": "be of service/ use/ help/ value to...", "type": "短语", "keyWords": ["service"] },
    { "chinese": "vt.放;设置;安置;确定;使开始(sb. doing sth.)vi.(日、月等)落,下沉(=go down) n.[C]一套,一批 a.约定的;固定的", "english": "set", "type": "单词", "keyWords": [] },
    { "chinese": "定速度", "english": "set the pace", "type": "短语", "keyWords": ["set"] },
    { "chinese": "释放", "english": "set. free (from..)", "type": "短语", "keyWords": ["set"] },
    { "chinese": "把食物放在桌上", "english": "set the food on the table", "type": "短语", "keyWords": ["set"] },
    { "chinese": "给我们树立一个好榜样", "english": "set a good example to us", "type": "短语", "keyWords": ["set"] },
    { "chinese": "开始/着手做某事", "english": "set about doing sth.", "type": "短语", "keyWords": ["set"] },
    { "chinese": "决定会议日期", "english": "set a date for the meeting = set the meeting for..", "type": "短语", "keyWords": ["set"] },
    { "chinese": "以威尼斯为背景的剧", "english": "a play that is set in Venice", "type": "短语", "keyWords": ["set"] },
    { "chinese": "放火烧房子", "english": "set fire to the house = set the house on fire", "type": "短语", "keyWords": ["set"] },
    { "chinese": "置于一旁,把...搁置;留出,拔出", "english": "set...aside", "type": "短语", "keyWords": ["set"] },
    { "chinese": "拨两间房子给经理", "english": "set aside two rooms for the manager", "type": "短语", "keyWords": ["set"] },
    { "chinese": "每周存入一定数额的钱", "english": "set aside a certain sum each week", "type": "短语", "keyWords": ["set"] },
    { "chinese": "阻碍...的进展;使受挂;延缓", "english": "set(sb./one'splan...) back", "type": "短语", "keyWords": ["set"] },
    { "chinese": "出发;启程;着手(=set outto do sth.)", "english": "set off", "type": "短语", "keyWords": ["set"] },
    { "chinese": "使爆炸;使(闹钟等)发出响;燃放(鞭炮等);引发", "english": "set...off", "type": "短语", "keyWords": ["set"] },
    { "chinese": "放鞭炮/引爆炸弹", "english": "set off fireworks/the bomb", "type": "短语", "keyWords": ["set"] },
    { "chinese": "引起哄堂大笑", "english": "set off roars of laughing", "type": "短语", "keyWords": ["set"] },
    { "chinese": "家里来信引起了他的思乡病。", "english": "A letter from home set off an attack of homesickness.", "type": "句子", "keyWords": ["set"] },
    { "chinese": "出发(=set off);开始(to do sth.);成列;安排;列举;详述", "english": "set out", "type": "短语", "keyWords": ["set"] },
    { "chinese": "出发/开始工作", "english": "set out/ off to work~set about working~set to work", "type": "短语", "keyWords": ["set"] },
    { "chinese": "阐明想法", "english": "set out hisideas", "type": "短语", "keyWords": ["set"] },
    { "chinese": "他列举了他这样做的理由。", "english": "He set outhis reasonsfor what hehad done.", "type": "句子", "keyWords": ["set"] },
    { "chinese": "竖立;建立,设立;引起", "english": "set up", "type": "短语", "keyWords": ["set"] },
    { "chinese": "设置路障", "english": "set up roadblocks", "type": "短语", "keyWords": ["set"] },
    { "chinese": "设立一个委员会", "english": "set up a committee", "type": "短语", "keyWords": ["set"] },
    { "chinese": "(口令)预备", "english": "get set", "type": "短语", "keyWords": ["set"] },
    { "chinese": "开动机器", "english": "set the machine going", "type": "短语", "keyWords": ["set"] },
    { "chinese": "n.[C]环境;安装;调节;(舞台等)布置;(小说等)背景", "english": "setting", "type": "单词", "keyWords": [] },
    { "chinese": "vi.定居;安顿下来(down);降落,停留;平静下来 vr.使定居;确定;解决(难题等);安排", "english": "settle", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]移居者;殖民者", "english": "settler", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]解决 n.[C]定居点;殖民地", "english": "settlement", "type": "单词", "keyWords": [] },
    { "chinese": "解决问题", "english": "settle/ work out/ solve a problem", "type": "短语", "keyWords": ["settle"] },
    { "chinese": "那只昆虫/鸟落在树枝上。", "english": "The insect/bird settled on a branch.", "type": "句子", "keyWords": ["settle"] },
    { "chinese": "最后他的目光落在了我的身上。", "english": "Finally his eyes settled/ fell rested on me.", "type": "句子", "keyWords": ["settle"] },
    { "chinese": "一言为定/就那么决定了!", "english": "It's settled!", "type": "句子", "keyWords": ["settle"] },
    { "chinese": "a.几个,若干 pron.几个,若干", "english": "several", "type": "单词", "keyWords": [] },
    { "chinese": "a.严重的,严厉的;严格的(强调无情)", "english": "severe", "type": "单词", "keyWords": [] },
    { "chinese": "ad.严厉地,严重地", "english": "severely", "type": "单词", "keyWords": [] },
    { "chinese": "v 缝(制)", "english": "sew", "type": "单词", "keyWords": [] },
    { "chinese": "缝合两块布", "english": "sew two pieces of cloth together", "type": "短语", "keyWords": ["sew"] },
    { "chinese": "n.[U]性,性别", "english": "sex", "type": "单词", "keyWords": [] },
    { "chinese": "a.性的,性别的", "english": "sexual", "type": "单词", "keyWords": [] },
    { "chinese": "a.性感的,迷人的;色情的", "english": "sexy", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]萌,阴凉处 n.[C]灯罩;百叶窗 vt.遮光;覆盖", "english": "shade", "type": "单词", "keyWords": [] },
    { "chinese": "在树荫下", "english": "in the shade of a tree", "type": "短语", "keyWords": ["shade"] },
    { "chinese": "窗帘", "english": "a shade of the window", "type": "短语", "keyWords": ["shade"] },
    { "chinese": "遮起你的眼睛以避开阳光", "english": "shade your eyes fromthe sun", "type": "短语", "keyWords": ["shade"] },
    { "chinese": "n.[C]影子", "english": "shadow", "type": "单词", "keyWords": [] },
    { "chinese": "这只狗与你形影相随。", "english": "The dog is your shadow.", "type": "句子", "keyWords": ["shadow"] },
    { "chinese": "v.握(手);摇(头等);猛摇 vi.摇动;震动;发抖", "english": "shake", "type": "单词", "keyWords": [] },
    { "chinese": "同某人握手", "english": "shake hands with sb./ shake sb.by the hand", "type": "短语", "keyWords": ["shake"] },
    { "chinese": "a.颤抖的;不稳的;靠不住的,动摇的", "english": "shaky", "type": "单词", "keyWords": [] },
    { "chinese": "aux.v.将要(第一人称);应该,必须,可(在陈述语气中,主语是第二人称线系三人称时,表示说话者或执笔者的意图,含有命令、承诺、要求、恐吓或义务等,支配着时或第三者的行动);应,必须(表示义务或规定,现常用于正式文件中);能,要不要(用何人称的疑问句或否定句等表示请示)", "english": "shall", "type": "单词", "keyWords": [] }
];
