const qgl245_252 = [
    { "chinese": "你说你不做，但我说你就该做。(命令/要求)", "english": "You say you will not do it, but I say you shall do it.", "type": "句子", "keyWords": ["shall"] },
    { "chinese": "明天你可以得到答复。(承诺)", "english": "You shall have an answer by tomorrow.", "type": "句子", "keyWords": ["shall"] },
    { "chinese": "任何一方不得单方面违约。(明文规定)", "english": "Each party shall not break the contract unilaterally.", "type": "句子", "keyWords": ["shall"] },
    { "chinese": "能让那个男孩进来吗？(请示)", "english": "Shall the boy come in?", "type": "句子", "keyWords": ["shall"] },
    { "chinese": "浅的；肤浅的", "english": "shallow", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]肤浅", "english": "shallowness", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]遗憾的事；带来耻辱的人或事 n.[U]羞耻；耻辱 *vt.使蒙羞", "english": "shame", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 可耻的", "english": "shameful", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 不知羞耻的", "english": "shameless", "type": "单词", "keyWords": [] },
    { "chinese": "真可惜今天下雨了！", "english": "What a shame (it is) that it rained today!", "type": "句子", "keyWords": ["shame"] },
    { "chinese": "n.[C][U]洗发剂，香波；*清洗剂 *v.洗(头/发)", "english": "shampoo", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]形状 v.使成形；形成，塑造，制作", "english": "shape", "type": "单词", "keyWords": [] },
    { "chinese": "在形状上(作状语)；健康，处于良好的状态(=fit)", "english": "in shape", "type": "短语", "keyWords": ["shape"] },
    { "chinese": "变形，走样；处于不良的(健康)状况", "english": "out of shape", "type": "短语", "keyWords": ["shape"] },
    { "chinese": "成形；变得有条理(近take root扎根)", "english": "take shape", "type": "短语", "keyWords": ["shape"] },
    { "chinese": "一种新型的亚非关系已经建立。", "english": "A new relationship between Africa and Asia has taken shape.", "type": "句子", "keyWords": ["shape"] },
    { "chinese": "堆雪人", "english": "shape the snow into a man", "type": "短语", "keyWords": ["shape"] },
    { "chinese": "有些人认为环境塑造人的性格。", "english": "Some people think that environment shapes personality.", "type": "句子", "keyWords": ["shape"] },
    { "chinese": "v.共有，分享/担；分摊 vi.共有，分享/担(in) n.[C](分担或分享的)一份；股份", "english": "share", "type": "单词", "keyWords": [] },
    { "chinese": "与某人分享/合用某物；与…有共同之处；将某事告知某人", "english": "share sth. with sb.", "type": "短语", "keyWords": ["share"] },
    { "chinese": "和…同甘共苦", "english": "share joys and sorrows with sb.", "type": "短语", "keyWords": ["share"] },
    { "chinese": "在结束前，我想告诉您一个故事。", "english": "Before I end, let me share with you one story.", "type": "句子", "keyWords": ["share"] },
    { "chinese": "承担一份…；参加…", "english": "take/ bear one's share of...", "type": "短语", "keyWords": ["share"] },
    { "chinese": "我愿意承担我那一份费用。", "english": "I'll take/ bear my share of the expenses.", "type": "句子", "keyWords": ["share"] },
    { "chinese": "n.[C][鱼]鲨；鲨鱼", "english": "shark", "type": "单词", "keyWords": [] },
    { "chinese": "没有科学研究表明鱼翅对健康有益。", "english": "No scientific studies show that shark fins are good for health.", "type": "句子", "keyWords": ["shark"] },
    { "chinese": "a.锋利的；急转向的；鲜明的；急剧的 ad.整点，正", "english": "sharp", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 急剧地，锐利地", "english": "sharply", "type": "单词", "keyWords": [] },
    { "chinese": "急转弯", "english": "a sharp turn", "type": "短语", "keyWords": ["sharp"] },
    { "chinese": "鲜明的对比", "english": "a sharp contrast", "type": "短语", "keyWords": ["sharp"] },
    { "chinese": "价格的急剧上涨", "english": "a sharp rise in price", "type": "短语", "keyWords": ["sharp"] },
    { "chinese": "灵敏的目光/耳朵/思维", "english": "sharp eyes/ ears/ mind", "type": "短语", "keyWords": ["sharp"] },
    { "chinese": "剧痛/尖锐的批评/尖叫", "english": "sharp pain/ criticism/ scream", "type": "短语", "keyWords": ["sharp"] },
    { "chinese": "敏锐的嗅觉", "english": "a sharp sense of smell", "type": "短语", "keyWords": ["sharp"] },
    { "chinese": "十点整", "english": "ten (o'clock) sharp", "type": "短语", "keyWords": ["sharp"] },
    { "chinese": "v.削尖，磨快 vi.变锐利；变尖", "english": "sharpen", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]卷笔刀", "english": "sharpener", "type": "单词", "keyWords": [] },
    { "chinese": "v.剃（毛发），刮（脸）；修剪（草坪） vi./n.[C]刮脸，修面", "english": "shave", "type": "单词", "keyWords": [] },
    { "chinese": "pron.她（主格） *n.[C]（常与a连用）雌性动物", "english": "she", "type": "单词", "keyWords": [] },
    { "chinese": "是她提出这个论据的。", "english": "It was she who put forth the argument.", "type": "句子", "keyWords": ["she"] },
    { "chinese": "你的狗是公的，还是母的？", "english": "Is your dog a he or a she?", "type": "句子", "keyWords": ["she"] },
    { "chinese": "n.[C]（单复同）羊，绵羊", "english": "sheep", "type": "单词", "keyWords": [] },
    { "chinese": "一群羊", "english": "a flock of sheep", "type": "短语", "keyWords": ["sheep"] },
    { "chinese": "害群之马；败类", "english": "a black sheep", "type": "短语", "keyWords": ["sheep"] },
    { "chinese": "n.[C]薄片；一张（纸），纸张；被单", "english": "sheet", "type": "单词", "keyWords": [] },
    { "chinese": "一张纸", "english": "a sheet of paper", "type": "短语", "keyWords": ["sheet"] },
    { "chinese": "一张金属片", "english": "a sheet of metal", "type": "短语", "keyWords": ["sheet"] },
    { "chinese": "答卷", "english": "an answer sheet", "type": "短语", "keyWords": ["sheet"] },
    { "chinese": "n.[C]（墙壁、书橱等的）架子；搁板", "english": "shelf", "type": "单词", "keyWords": [] },
    { "chinese": "贮藏寿命；货架寿命（商品储放的保质期）", "english": "shelf life", "type": "短语", "keyWords": ["shelf"] },
    { "chinese": "把我的计划束之高阁", "english": "put my plan on the shelf", "type": "短语", "keyWords": ["shelf"] },
    { "chinese": "n.[C]壳，壳状物；贝壳；*炮弹 *shellfish 甲壳水生动物", "english": "shell", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]掩蔽处；庇护所 n.[U]掩蔽；保护 v.掩蔽；庇护", "english": "shelter", "type": "单词", "keyWords": [] },
    { "chinese": "躲避（风雨）", "english": "take/ seek shelter (from rain)", "type": "短语", "keyWords": ["shelter"] },
    { "chinese": "v./n.[C]转移；移动；变换 n.[C]轮班", "english": "shift", "type": "单词", "keyWords": [] },
    { "chinese": "将重担从一肩移至另一肩上", "english": "shift a burden from one shoulder to the other", "type": "短语", "keyWords": ["shift"] },
    { "chinese": "风转向南吹。", "english": "The wind shifted to the south.", "type": "句子", "keyWords": ["shift"] },
    { "chinese": "他们轮流上夜班。", "english": "They were taking turns to be on the night shift.", "type": "句子", "keyWords": ["shift"] },
    { "chinese": "我是你日间轮班的护士。", "english": "I'm your day shift nurse.", "type": "句子", "keyWords": ["shift"] },
    { "chinese": "v.照耀，发光", "english": "shine", "type": "单词", "keyWords": [] },
    { "chinese": "adj.擦亮的；有光泽的；晴朗的", "english": "shiny", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]海船；舰；大船；宇宙飞船 v.用船或火车等载运", "english": "ship", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]造船厂；船坞", "english": "shipyard", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]船只失事，海难", "english": "shipwreck", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]造船术，造船业", "english": "shipbuilding", "type": "单词", "keyWords": [] },
    { "chinese": "船运保险", "english": "shipping insurance", "type": "短语", "keyWords": ["ship"] },
    { "chinese": "你最终把家具运走了吗？", "english": "Have you shipped the furniture off at last?", "type": "句子", "keyWords": ["ship"] },
    { "chinese": "n.[C]（男式）衬衫", "english": "shirt", "type": "单词", "keyWords": [] },
    { "chinese": "vi./n.[C]（因冷或好像因冷而）颤抖，哆嗦（辨析见shake）", "english": "shiver", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]休克 n.[C](U]震动；震惊；冲撞 *n.[C]电击 vt./vi.（使）震惊；（使）震动", "english": "shock", "type": "单词", "keyWords": [] },
    { "chinese": "感到/使人震惊的", "english": "shocked/ shocking a.", "type": "单词", "keyWords": [] },
    { "chinese": "使极为震惊", "english": "a terrible shock to sb.", "type": "短语", "keyWords": ["shock"] },
    { "chinese": "文化冲击", "english": "culture shock", "type": "短语", "keyWords": ["shock"] },
    { "chinese": "触电；（遭）电击", "english": "(get an) electric shock", "type": "短语", "keyWords": ["shock"] },
    { "chinese": "听到丈夫死去的消息，她晕了过去。", "english": "She was shocked at the news of her husband's death.", "type": "句子", "keyWords": ["shock"] },
    { "chinese": "n.[C]鞋", "english": "shoe", "type": "单词", "keyWords": [] },
    { "chinese": "v.射中；射死；发射；放射；开（枪/炮）；射（门），投（篮） vi.射击；开枪/炮；*迅速喷出/上涨等；射门 *n.[C]芽；照相", "english": "shoot", "type": "单词", "keyWords": [] },
    { "chinese": "把他射死", "english": "shoot him dead", "type": "短语", "keyWords": ["shoot"] },
    { "chinese": "射中他的腿", "english": "shoot him in the leg", "type": "短语", "keyWords": ["shoot"] },
    { "chinese": "对准靶子射击", "english": "shoot at the target", "type": "短语", "keyWords": ["shoot"] },
    { "chinese": "竹笋", "english": "bamboo shoots", "type": "短语", "keyWords": ["shoot"] },
    { "chinese": "向某人连续发问", "english": "shoot questions at somebody", "type": "短语", "keyWords": ["shoot"] },
    { "chinese": "她对他投以愤怒的眼色。", "english": "She shot an angry look at him.", "type": "句子", "keyWords": ["shoot"] },
    { "chinese": "这孩子长得很快。", "english": "The boy is shooting up.", "type": "句子", "keyWords": ["shoot"] },
    { "chinese": "价格飞涨。", "english": "Prices have shot up.", "type": "句子", "keyWords": ["shoot"] },
    { "chinese": "n.[C]商店 v.到店里购物", "english": "shop", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]购物者，顾客", "english": "shopper", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]店主", "english": "shopkeeper", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]购物", "english": "shopping", "type": "单词", "keyWords": [] },
    { "chinese": "去逛商店", "english": "go window-shopping", "type": "短语", "keyWords": ["shop"] },
    { "chinese": "购物", "english": "do some shopping", "type": "短语", "keyWords": ["shop"] },
    { "chinese": "大型购物中心", "english": "shopping mall", "type": "短语", "keyWords": ["shop"] },
    { "chinese": "购物单/袋", "english": "shopping list/ bag", "type": "短语", "keyWords": ["shop"] },
    { "chinese": "n.[C]岸，滨", "english": "shore", "type": "单词", "keyWords": [] },
    { "chinese": "a.短的；矮的；*短缺的 n.[C]（常用pl.）（宽松运动）短裤", "english": "short", "type": "单词", "keyWords": [] },
    { "chinese": "v./vi. 变短，变少", "english": "shorten", "type": "单词", "keyWords": [] },
    { "chinese": "走捷径", "english": "take a short cut", "type": "短语", "keyWords": ["short"] },
    { "chinese": "简言之", "english": "in short/ brief", "type": "短语", "keyWords": ["short"] },
    { "chinese": "急需、短缺", "english": "be run short of sth.", "type": "短语", "keyWords": ["short"] },
    { "chinese": "缺某东西", "english": "(sth.) run short", "type": "短语", "keyWords": ["short"] },
    { "chinese": "称为NBC", "english": "be called NBC for short", "type": "短语", "keyWords": ["short"] },
    { "chinese": "n.[C][U]不足，缺少", "english": "shortage", "type": "单词", "keyWords": [] },
    { "chinese": "五十吨的短缺额", "english": "a shortage of 50 tons", "type": "短语", "keyWords": ["shortage"] },
    { "chinese": "n.[C]缺点，不足", "english": "shortcoming", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]近路，捷径（=short cut）", "english": "shortcut", "type": "单词", "keyWords": [] },
    { "chinese": "众所周知，学英语没有捷径。", "english": "As we all know, there is no shortcut to learning English.", "type": "句子", "keyWords": ["shortcut"] },
    { "chinese": "n.[U]速记（法）", "english": "shorthand", "type": "单词", "keyWords": [] },
    { "chinese": "进行速记", "english": "take shorthand", "type": "短语", "keyWords": ["shorthand"] },
    { "chinese": "用速记记下某事", "english": "take sth. down in shorthand", "type": "短语", "keyWords": ["shorthand"] },
    { "chinese": "ad.不久，立即（近presently, soon, in no time）", "english": "shortly", "type": "单词", "keyWords": [] },
    { "chinese": "不久以后", "english": "shortly after", "type": "短语", "keyWords": ["shortly"] },
    { "chinese": "在…之后立即", "english": "shortly after+句子/sth.", "type": "短语", "keyWords": ["shortly"] },
    { "chinese": "a.近视的；眼光短浅的", "english": "short-sighted", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]射击，枪声；射门；射手；拍摄；打针（shoot的过去式/过去分词）", "english": "shot", "type": "单词", "keyWords": [] },
    { "chinese": "枪声响彻群山。", "english": "The shot echoed through the hills.", "type": "句子", "keyWords": ["shot"] },
    { "chinese": "aux.将（shall的过去式）；应该，应当（表示义务、责任）；应该，必须（用于表示建议、命令、决定等的从句中）（虚拟语气）；万一（表示语气较强的假设）（虚拟语气）；应该，竟然会（用于表示必要、适当、惊奇、遗憾等的从句中）（虚拟语气）；可能，本）该（表示可能性、推测、推论，有时指实际没发生）；*倒（是（表谦虚）；竟）会（常用于问句，表示惊异、赞叹、不满等）", "english": "should", "type": "单词", "keyWords": [] },
    { "chinese": "万一失败，我还要试一试。", "english": "If I should fail, I would try again.", "type": "句子", "keyWords": ["should"] },
    { "chinese": "我怕伤风，所以呆在屋里。", "english": "I stayed in lest I should catch a cold.", "type": "句子", "keyWords": ["should"] },
    { "chinese": "他现在可能在我的家里。", "english": "He should be in my house now.", "type": "句子", "keyWords": ["should"] },
    { "chinese": "我倒（是）并不那样想。", "english": "I should hardly think so.", "type": "句子", "keyWords": ["should"] },
    { "chinese": "我怎么会知道呢？", "english": "How should I know?", "type": "句子", "keyWords": ["should"] },
    { "chinese": "n.[C]肩膀 v.肩起，挑起，担负，承担（责任等）", "english": "shoulder", "type": "单词", "keyWords": [] },
    { "chinese": "（和…）肩并肩", "english": "shoulder to shoulder (with...)", "type": "短语", "keyWords": ["shoulder"] },
    { "chinese": "耸肩", "english": "shrug one's shoulders", "type": "短语", "keyWords": ["shoulder"] },
    { "chinese": "她承担了那天的所有过错。", "english": "She shouldered the blame for all that had gone wrong that day.", "type": "句子", "keyWords": ["shoulder"] },
    { "chinese": "n.[C]/v.呼喊，叫喊", "english": "shout", "type": "单词", "keyWords": [] },
    { "chinese": "叫喊表示反对", "english": "shout their disapproval", "type": "短语", "keyWords": ["shout"] },
    { "chinese": "冲…吼", "english": "shout at sb.", "type": "短语", "keyWords": ["shout"] },
    { "chinese": "大喊危险", "english": "give a shout of warning", "type": "短语", "keyWords": ["shout"] },
    { "chinese": "大声发布命令", "english": "shout (out) orders", "type": "短语", "keyWords": ["shout"] },
    { "chinese": "v.出示；展出；显示，表明，说明；演出；放映；教 vi.显露，露面 n.(C)展览(会)；演出；节目(常与a连用)；显露", "english": "show", "type": "单词", "keyWords": [] },
    { "chinese": "放映幻灯片", "english": "give a slide show", "type": "短语", "keyWords": ["show"] },
    { "chinese": "才艺表演会", "english": "talent show", "type": "短语", "keyWords": ["show"] },
    { "chinese": "脱口秀；访谈节目", "english": "talk show", "type": "短语", "keyWords": ["show"] },
    { "chinese": "时装秀", "english": "fashion show", "type": "短语", "keyWords": ["show"] },
    { "chinese": "（规模较小）被陈列着，出展（近on display/exhibition）", "english": "on show", "type": "短语", "keyWords": ["show"] },
    { "chinese": "带领（某人）参观（某处）", "english": "show...round", "type": "短语", "keyWords": ["show"] },
    { "chinese": "炫耀，卖弄（近put on airs）", "english": "show off", "type": "短语", "keyWords": ["show"] },
    { "chinese": "（使）显眼，（使）显现；到达；露面；揭发", "english": "show up", "type": "短语", "keyWords": ["show"] },
    { "chinese": "在阳光下玻璃杯上的指纹显得很清楚。", "english": "The fingerprints on the glass show up in the sunlight.", "type": "句子", "keyWords": ["show"] },
    { "chinese": "除了杰克以外所有的人都来了。", "english": "Everyone showed up except Jack.", "type": "句子", "keyWords": ["show"] },
    { "chinese": "揭穿谎言", "english": "to show up one's lie", "type": "短语", "keyWords": ["show"] },
    { "chinese": "n.[C]阵雨；淋浴 v.喷淋；下阵雨", "english": "shower", "type": "单词", "keyWords": [] },
    { "chinese": "v.收缩；退缩(from)；缩水", "english": "shrink", "type": "单词", "keyWords": [] },
    { "chinese": "v.关上，关闭", "english": "shut", "type": "单词", "keyWords": [] },
    { "chinese": "关门；停工", "english": "shutdown", "type": "短语", "keyWords": ["shut"] },
    { "chinese": "住口；把…关起来", "english": "shut up", "type": "短语", "keyWords": ["shut"] },
    { "chinese": "（使）关闭；（使）停工", "english": "shut down", "type": "短语", "keyWords": ["shut"] },
    { "chinese": "n.[C]（来回于两地间的）穿梭运输车辆或飞机等；（织机的）梭子；穿梭 v.穿梭；来回移动", "english": "shuttle", "type": "单词", "keyWords": [] },
    { "chinese": "a.怕羞的，胆怯的(of)", "english": "shy", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 害羞地", "english": "shyly", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]害羞", "english": "shyness", "type": "单词", "keyWords": [] },
    { "chinese": "她对陌生人是害羞的。", "english": "She is shy of strangers.", "type": "句子", "keyWords": ["shy"] },
    { "chinese": "这敏感问题我不敢说得太多。", "english": "I am shy of saying too much on this delicate subject.", "type": "句子", "keyWords": ["shy"] },
    { "chinese": "a.有病的(尤指身体不适)；恶心的；病人的", "english": "sick", "type": "单词", "keyWords": [] },
    { "chinese": "使患病/恶心", "english": "sicken", "type": "单词", "keyWords": [] },
    { "chinese": "病倒", "english": "fall sick/ill", "type": "短语", "keyWords": ["sick"] },
    { "chinese": "打电话请病假", "english": "ring/call in sick", "type": "短语", "keyWords": ["sick"] },
    { "chinese": "在休病假；对…感到厌烦（近be tired of）", "english": "be/go on sick leave；be sick of...", "type": "短语", "keyWords": ["sick"] },
    { "chinese": "n.[U]患病；疾病；呕吐，恶心", "english": "sickness", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]旁边；侧面；身体的侧边 a.旁边的，侧面的；附带的，副的", "english": "side", "type": "单词", "keyWords": [] },
    { "chinese": "站在某人一边，支持某人", "english": "be on the side of sb./on one's side", "type": "短语", "keyWords": ["side"] },
    { "chinese": "站在某人一边，支持某人", "english": "take the side of sb.=take one's side", "type": "短语", "keyWords": ["side"] },
    { "chinese": "在…的两边（近on both sides of）", "english": "on each/either side of", "type": "短语", "keyWords": ["side"] },
    { "chinese": "熊沿着岸边向前走，一边走一边把头晃来晃去。", "english": "The bear walked along the shore shaking his head from side to side.", "type": "句子", "keyWords": ["side"] },
    { "chinese": "让小孩侧躺", "english": "lay the child on his side", "type": "短语", "keyWords": ["side"] },
    { "chinese": "肩并肩地，支持（与…）", "english": "side by side (=shoulder to shoulder) (with...)", "type": "短语", "keyWords": ["side"] },
    { "chinese": "（某物的）副作用", "english": "side effects (of sth.)", "type": "短语", "keyWords": ["side"] },
    { "chinese": "边门", "english": "side door", "type": "短语", "keyWords": ["side"] },
    { "chinese": "n.[C]人行道[英]pavement", "english": "sidewalk", "type": "单词", "keyWords": [] },
    { "chinese": "ad./a.一旁（的），向侧面（的）", "english": "sideways", "type": "单词", "keyWords": [] },
    { "chinese": "向旁边跨了一步", "english": "take a step sideways", "type": "短语", "keyWords": ["sideways"] },
    { "chinese": "斜着眼看了一下", "english": "take a sideways glance", "type": "短语", "keyWords": ["sideways"] },
    { "chinese": "n.[C]/v.叹气，叹息", "english": "sigh", "type": "单词", "keyWords": [] },
    { "chinese": "松了一口气", "english": "sigh with relief=give sigh of relief", "type": "短语", "keyWords": ["sigh"] },
    { "chinese": "n.[U]视域；视力；看见 (pl.)景色，景物(辨析见scene) v.看见", "english": "sight", "type": "单词", "keyWords": [] },
    { "chinese": "乍一看", "english": "at first sight", "type": "短语", "keyWords": ["sight"] },
    { "chinese": "看不见了", "english": "be/go/get out of sight", "type": "短语", "keyWords": ["sight"] },
    { "chinese": "看得见", "english": "in/within sight", "type": "短语", "keyWords": ["sight"] },
    { "chinese": "呈现在眼前", "english": "come in/into sight", "type": "短语", "keyWords": ["sight"] },
    { "chinese": "我一看见他就讨厌。", "english": "I hate the very sight of him.", "type": "句子", "keyWords": ["sight"] },
    { "chinese": "发现，看出", "english": "catch/have/gain/get sight of", "type": "短语", "keyWords": ["sight"] },
    { "chinese": "一看见(on seeing...)", "english": "at the sight of...", "type": "短语", "keyWords": ["sight"] },
    { "chinese": "某人的意见；在某人看来", "english": "in the sight of sb./in sb.'s sight", "type": "短语", "keyWords": ["sight"] },
    { "chinese": "我们终于看见陆地了。", "english": "We sighted land at last.", "type": "句子", "keyWords": ["sight"] },
    { "chinese": "眼不见，心不烦。人别则情疏。", "english": "Out of sight, out of mind.", "type": "句子", "keyWords": ["sight"] },
    { "chinese": "n.[U]观光；游览", "english": "sightseeing", "type": "单词", "keyWords": [] },
    { "chinese": "去观光", "english": "go sightseeing", "type": "短语", "keyWords": ["sightseeing"] },
    { "chinese": "观光旅游", "english": "sightseeing tour", "type": "短语", "keyWords": ["sightseeing"] },
    { "chinese": "n.[C]招牌；标记，符号；征兆，迹象；手势；示意动作 v.签(名)；签署(文件等)；以手势示意 vi.签名；以手势等表示", "english": "sign", "type": "单词", "keyWords": [] },
    { "chinese": "交通标志", "english": "traffic signs", "type": "短语", "keyWords": ["sign"] },
    { "chinese": "下雨的预兆", "english": "a sign of rain", "type": "短语", "keyWords": ["sign"] },
    { "chinese": "有时代的特征", "english": "bear the sign of the times", "type": "短语", "keyWords": ["sign"] },
    { "chinese": "签到", "english": "sign in", "type": "短语", "keyWords": ["sign"] },
    { "chinese": "他做手势要我安静。", "english": "He signed me to be quiet.", "type": "句子", "keyWords": ["sign"] },
    { "chinese": "n.[C]签名", "english": "signature", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]信号 vt./vi.(向…)发信号 v.用信号表示；预示", "english": "signal", "type": "单词", "keyWords": [] },
    { "chinese": "红灯通常是危险的信号。", "english": "A red light is usually a signal of danger.", "type": "句子", "keyWords": ["signal"] },
    { "chinese": "在约定的信号发出时，他们投入了战斗。", "english": "They went into action at a given signal.", "type": "句子", "keyWords": ["signal"] },
    { "chinese": "他发出求教信号。", "english": "He signaled (=sent/gave a signal) for help.", "type": "句子", "keyWords": ["signal"] },
    { "chinese": "n.[U]重要性，重大(尤指意义深远)(insignificant(不)重要的)", "english": "significance", "type": "单词", "keyWords": [] },
    { "chinese": "对我们来说无关紧要", "english": "be of little/no significance to us", "type": "短语", "keyWords": ["significance"] },
    { "chinese": "n.[U](可与a连用)沉默，静默 n.[U]寂静 *v.使安静", "english": "silence", "type": "单词", "keyWords": [] },
    { "chinese": "沉默着，静静地", "english": "in silence (=silently)", "type": "短语", "keyWords": ["silence"] },
    { "chinese": "保持沉默", "english": "keep silence (=keep silent)", "type": "短语", "keyWords": ["silence"] },
    { "chinese": "沉默二十分钟后", "english": "after a silence of 20 minutes", "type": "短语", "keyWords": ["silence"] },
    { "chinese": "言多必失，沉默是金。", "english": "Speech is silver, silence is gold.", "type": "句子", "keyWords": ["silence"] },
    { "chinese": "a.静的；无声的(辨析见quiet)", "english": "silent", "type": "单词", "keyWords": [] },
    { "chinese": "无声电影", "english": "a silent film", "type": "短语", "keyWords": ["silent"] },
    { "chinese": "不发音的字母", "english": "a silent letter", "type": "短语", "keyWords": ["silent"] },
    { "chinese": "对…保持沉默，对…只字不提", "english": "be/keep/remain silent about sth.", "type": "短语", "keyWords": ["silent"] },
    { "chinese": "n.[U]丝；绸 *silky a.丝的，柔滑的 *silkworm n.[C]蚕，桑蚕", "english": "silk", "type": "单词", "keyWords": [] },
    { "chinese": "a.愚蠢的；缺乏常识或理智的", "english": "silly", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]愚蠢", "english": "silliness", "type": "单词", "keyWords": [] },
    { "chinese": "你做那事多愚蠢呀！", "english": "How silly of you to do that!", "type": "句子", "keyWords": ["silly"] },
    { "chinese": "n.[U]银；银色 *[C]银牌 a.银(质/色)的", "english": "silver", "type": "单词", "keyWords": [] },
    { "chinese": "a.相像的；类似的 *similarity n.相似性", "english": "similar", "type": "单词", "keyWords": [] },
    { "chinese": "与…相像，类似", "english": "be similar to...", "type": "短语", "keyWords": ["similar"] },
    { "chinese": "a.简易的；朴素的；单纯的；头脑简单的 adv.仅；简单地；简直", "english": "simple", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]简单；朴素；天真", "english": "simplicity", "type": "单词", "keyWords": [] },
    { "chinese": "像小孩一样天真", "english": "as simple as a child", "type": "短语", "keyWords": ["simple"] },
    { "chinese": "头脑简单的", "english": "simple-minded", "type": "短语", "keyWords": ["simple"] },
    { "chinese": "这只不过是一个时间的问题。", "english": "It is simply a matter of time.", "type": "句子", "keyWords": ["simple"] },
    { "chinese": "简直荒谬得很！", "english": "That is simply absurd!", "type": "句子", "keyWords": ["simple"] },
    { "chinese": "对制造商来说这简直一点意义也没有。", "english": "That simply made no sense to manufacturers.", "type": "句子", "keyWords": ["simple"] },
    { "chinese": "v.简化", "english": "simplify", "type": "单词", "keyWords": [] },
    { "chinese": "n.简化", "english": "simplification", "type": "单词", "keyWords": [] },
    { "chinese": "简体字，简化字", "english": "simplified character", "type": "短语", "keyWords": ["simplify"] },
    { "chinese": "简写本", "english": "simplified edition", "type": "短语", "keyWords": ["simplify"] },
    { "chinese": "prep./conj.从…以来 conj.既然 ad.从那以后", "english": "since", "type": "单词", "keyWords": [] },
    { "chinese": "久违数载。/多年未见。", "english": "It's years since we parted.", "type": "句子", "keyWords": ["since"] },
    { "chinese": "从那时起至今日", "english": "ever since=ever since then", "type": "短语", "keyWords": ["since"] },
    { "chinese": "此后我再也没有见过他。", "english": "I haven't seen him since.", "type": "句子", "keyWords": ["since"] },
    { "chinese": "长久/早已为人所遗忘的名字", "english": "a name long since forgotten", "type": "短语", "keyWords": ["since"] },
    { "chinese": "a.真诚的，诚挚的", "english": "sincere", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]真诚", "english": "sincerity", "type": "单词", "keyWords": [] },
    { "chinese": "adv.真诚地", "english": "sincerely", "type": "单词", "keyWords": [] },
    { "chinese": "v.唱，唱歌；演唱", "english": "sing", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]歌手", "english": "singer", "type": "单词", "keyWords": [] },
    { "chinese": "a.单一的；单个的；未婚的；(车票等)单程的 n.单打(比赛)", "english": "single", "type": "单词", "keyWords": [] },
    { "chinese": "单人房", "english": "a single room", "type": "短语", "keyWords": ["single"] },
    { "chinese": "女子单打", "english": "the women's singles", "type": "短语", "keyWords": ["single"] },
    { "chinese": "那天那里一个人也见不到。", "english": "Not a single person was seen there that day.", "type": "句子", "keyWords": ["single"] },
    { "chinese": "v.(sank,sunk)(船等)下沉；(价格等)降低 v.使下沉；使降低 n.(C](厨房的)洗涤槽；污水井(池)；阴沟", "english": "sink", "type": "单词", "keyWords": [] },
    { "chinese": "adj.沉没的", "english": "sunken", "type": "单词", "keyWords": [] },
    { "chinese": "沉船", "english": "a sunken ship", "type": "短语", "keyWords": ["sink"] },
    { "chinese": "正在下沉的船", "english": "a sinking ship", "type": "短语", "keyWords": ["sink"] },
    { "chinese": "想到战争他的情绪就显得十分低落。", "english": "His heart sank at the thought of war.", "type": "句子", "keyWords": ["sink"] },
    { "chinese": "表示“中国的”，例如：中意关系", "english": "Sino-", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]先生", "english": "sir", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]姐妹", "english": "sister", "type": "单词", "keyWords": [] },
    { "chinese": "嫂子；弟媳；姑；姨", "english": "sister(s)-in-law", "type": "短语", "keyWords": ["sister"] },
    { "chinese": "v.坐；*参加考试(for)", "english": "sit", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]起居室；会客室", "english": "sitting room", "type": "短语", "keyWords": ["sit"] },
    { "chinese": "向后靠着坐；放松", "english": "sit back", "type": "短语", "keyWords": ["sit"] },
    { "chinese": "端坐，坐直；熬夜(近stay up)", "english": "sit up", "type": "短语", "keyWords": ["sit"] },
    { "chinese": "[美]临时代人照顾婴孩者", "english": "baby sitter", "type": "短语", "keyWords": ["sit"] },
    { "chinese": "应试，参加考试", "english": "sit for an examination", "type": "短语", "keyWords": ["sit"] },
    { "chinese": "n.[C]场所；地点；选址；遗址；旧址", "english": "site", "type": "单词", "keyWords": [] },
    { "chinese": "建筑工地", "english": "a construction site", "type": "短语", "keyWords": ["site"] },
    { "chinese": "露营地", "english": "a camp site", "type": "短语", "keyWords": ["site"] },
    { "chinese": "n.[C]情况；处境；场面；形势；(建筑物等的)位置(in)", "english": "situation", "type": "单词", "keyWords": [] },
    { "chinese": "也只有在这样的场合，演讲人才能掌控整个听众的肃静气氛。", "english": "In no other situation can one speaker command the silence of an entire group of people.", "type": "句子", "keyWords": ["situation"] },
    { "chinese": "你能想出一个使用这个成语的情况吗？", "english": "Can you think of a situation where this idiom can be used?", "type": "句子", "keyWords": ["situation"] },
    { "chinese": "v.（常被动）使位于，使处于(in)", "english": "situate", "type": "单词", "keyWords": [] },
    { "chinese": "位于(近lie in)", "english": "be situated/ located in/on/at...", "type": "短语", "keyWords": ["situate"] },
    { "chinese": "n.[C][U]尺寸，大小", "english": "size", "type": "单词", "keyWords": [] },
    { "chinese": "在尺寸方面", "english": "in size", "type": "短语", "keyWords": ["size"] },
    { "chinese": "三倍于橘子大小的洞", "english": "a hole three times the size of an orange", "type": "短语", "keyWords": ["size"] },
    { "chinese": "这些男孩个头差不多。", "english": "All the boys are much of a size.", "type": "句子", "keyWords": ["size"] },
    { "chinese": "vi./n.[U]溜冰，滑水 *n(C]冰鞋 *skatingn.[U]滑冰(运动)", "english": "skate", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]滑雪板 vi.滑雪", "english": "ski", "type": "单词", "keyWords": [] },
    { "chinese": "去滑雪", "english": "go skiing", "type": "短语", "keyWords": ["ski"] },
    { "chinese": "n.[C]滑雪运动员", "english": "skier", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]技能，专门技术；技巧；熟练", "english": "skill", "type": "单词", "keyWords": [] },
    { "chinese": "a.灵巧的；熟练的", "english": "skill(ful)", "type": "单词", "keyWords": [] },
    { "chinese": "a.有技能的；需技术的", "english": "skilled", "type": "单词", "keyWords": [] },
    { "chinese": "v./vi.浏览；略读", "english": "skim", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C](U)皮(肤(多用单数形式)；果皮 *v.剥皮", "english": "skin", "type": "单词", "keyWords": [] },
    { "chinese": "骨瘦如柴", "english": "be skin and bone(s)=be skinny", "type": "短语", "keyWords": ["skin"] },
    { "chinese": "肤浅的", "english": "skin-deep", "type": "短语", "keyWords": ["skin"] },
    { "chinese": "v.蹦跳；跳绳 v.跳过；故意略去；漏过", "english": "skip", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]裙子", "english": "skirt", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]天空*sky-blue a.天蓝色(的)；蔚蓝色(的", "english": "sky", "type": "单词", "keyWords": [] },
    { "chinese": "在清晨蓝天的衬托下这座山显得雄伟壮丽。", "english": "The mountain looks magnificent against the morning sky.", "type": "句子", "keyWords": ["sky"] },
    { "chinese": "n.[C]摩天大楼", "english": "skyscraper", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]俚语", "english": "slang", "type": "单词", "keyWords": [] },
    { "chinese": "俚语用词", "english": "slang words", "type": "短语", "keyWords": ["slang"] },
    { "chinese": "n.[C]奴隶", "english": "slave", "type": "单词", "keyWords": [] },
    { "chinese": "成为酒鬼", "english": "be a slave to drink", "type": "短语", "keyWords": ["slave"] },
    { "chinese": "m.[U]奴隶制；奴隶身份", "english": "slavery", "type": "单词", "keyWords": [] },
    { "chinese": "v.睡m.[U](只用单)睡眠", "english": "sleep", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 失眠的", "english": "sleepless", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 睡着的，睡熟的", "english": "asleep", "type": "单词", "keyWords": [] },
    { "chinese": "睡得很熟", "english": "sleep well/like a log/soundly/sound", "type": "短语", "keyWords": ["sleep"] },
    { "chinese": "睡得很熟", "english": "have a sound/fast/deep sleep=be sound/fast asleep", "type": "短语", "keyWords": ["sleep"] },
    { "chinese": "安眠药", "english": "sleeping pill", "type": "短语", "keyWords": ["sleep"] },
    { "chinese": "a. 疲乏的，欲睡的", "english": "sleepy", "type": "单词", "keyWords": [] },
    { "chinese": "n. 睡意，瞌睡", "english": "sleepiness", "type": "单词", "keyWords": [] },
    { "chinese": "m.[C]袖子", "english": "sleeve", "type": "单词", "keyWords": [] },
    { "chinese": "a.苗条的；细长的；微薄的；微弱的", "english": "slender", "type": "单词", "keyWords": [] },
    { "chinese": "n[C)(切下的)薄片，切片；部分v.切成薄片；切开；削", "english": "slice", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]幻灯片；滑行/动v(使)滑行/动", "english": "slide", "type": "单词", "keyWords": [] },
    { "chinese": "a.轻微的；细小的；少量的；不足道的", "english": "slight", "type": "单词", "keyWords": [] },
    { "chinese": "ad.稍；些许", "english": "slightly", "type": "单词", "keyWords": [] },
    { "chinese": "轻微的头疼/微小的区别", "english": "a slight headache/difference", "type": "短语", "keyWords": ["slight"] },
    { "chinese": "很小的成功可能性", "english": "a slight possibility of success", "type": "短语", "keyWords": ["slight"] },
    { "chinese": "一点不，完全不", "english": "not in the slightest/least=not at all/not a bit", "type": "短语", "keyWords": ["slight"] },
    { "chinese": "a.苗条的(近slender)；微小的；不足的；少的*", "english": "slim", "type": "单词", "keyWords": [] },
    { "chinese": "n. 细长，微薄", "english": "slimness", "type": "单词", "keyWords": [] },
    { "chinese": "v.滑；失脚；滑落；滑行；时间流逝v.悄悄放/塞；错过m[C]纸片，纸条；滑倒；(植物的)幼枝", "english": "slip", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 滑的；易滑脱的", "english": "slippery", "type": "单词", "keyWords": [] },
    { "chinese": "(从)滑落；滑脱；溜走", "english": "slip from/out of/through", "type": "短语", "keyWords": ["slip"] },
    { "chinese": "溜进/出；穿上/脱下", "english": "slip into/out of", "type": "短语", "keyWords": ["slip"] },
    { "chinese": "他悄悄把钱塞进口袋。", "english": "He slipped the money into his pocket.", "type": "句子", "keyWords": ["slip"] },
    { "chinese": "她悄悄溜走未被看见。", "english": "She slipped away without being seen.", "type": "句子", "keyWords": ["slip"] },
    { "chinese": "她滑倒在发亮的地板上了。", "english": "She slipped on the shiny floor and fell.", "type": "句子", "keyWords": ["slip"] },
    { "chinese": "说走了嘴/出现笔误。", "english": "It's a slip of the tongue/pen.", "type": "句子", "keyWords": ["slip"] },
    { "chinese": "n.[C]斜坡v(使)倾斜；(使)有坡度", "english": "slope", "type": "单词", "keyWords": [] },
    { "chinese": "缓坡", "english": "a gentle slope", "type": "短语", "keyWords": ["slope"] },
    { "chinese": "公园向下倾斜一直到河边。", "english": "The park sloped to the river.", "type": "句子", "keyWords": ["slope"] },
    { "chinese": "a.慢的；反应慢的ad.缓慢v(使)慢下来", "english": "slow", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 缓慢地", "english": "slowly", "type": "单词", "keyWords": [] },
    { "chinese": "（使）慢下来", "english": "slow...down", "type": "短语", "keyWords": ["slow"] },
    { "chinese": "行动缓慢", "english": "slow in action", "type": "短语", "keyWords": ["slow"] },
    { "chinese": "我的表慢了五分钟。", "english": "My watch is five minutes slow.", "type": "句子", "keyWords": ["slow"] },
    { "chinese": "a.小的*", "english": "small", "type": "单词", "keyWords": [] },
    { "chinese": "感到惭愧；自惭形秽", "english": "feel small", "type": "短语", "keyWords": ["small"] },
    { "chinese": "a.漂亮的；时髦的；聪明的，伶俐的", "english": "smart", "type": "单词", "keyWords": [] },
    { "chinese": "v(被)捣碎；(被)打碎；猛撞n.[C]破碎声；撞车", "english": "smash", "type": "单词", "keyWords": [] },
    { "chinese": "听到厨房里哗啦一声响", "english": "hear a smash in the kitchen", "type": "短语", "keyWords": ["smash"] },
    { "chinese": "撞得粉碎", "english": "be smashed to pieces", "type": "短语", "keyWords": ["smash"] },
    { "chinese": "汽车撞到了一棵树上。", "english": "The car smashed into a tree.", "type": "句子", "keyWords": ["smash"] },
    { "chinese": "n.[U]嗅觉 n.[C]气味；臭味；嗅，闻 v.嗅/闻(到) v.闻起来；嗅觉(well/badly)；发出难闻的气味；有…气味(of)", "english": "smell", "type": "单词", "keyWords": [] },
    { "chinese": "一股烤鸡的味儿", "english": "a smell of fried chicken", "type": "短语", "keyWords": ["smell"] },
    { "chinese": "多难闻的气味啊！", "english": "What a smell!", "type": "句子", "keyWords": ["smell"] },
    { "chinese": "觉得会有麻烦", "english": "smell sense trouble coming", "type": "短语", "keyWords": ["smell"] },
    { "chinese": "闻到厨房里有什么东西烧着了", "english": "smell something burning in the kitchen", "type": "短语", "keyWords": ["smell"] },
    { "chinese": "发出香气，闻起来很香", "english": "smell sweet", "type": "短语", "keyWords": ["smell"] },
    { "chinese": "这肉发臭了。", "english": "The meat smells.", "type": "句子", "keyWords": ["smell"] },
    { "chinese": "我感冒了，嗅觉不灵敏了。", "english": "I have a cold and can't smell well.", "type": "句子", "keyWords": ["smell"] },
    { "chinese": "这间房间有油漆气味。", "english": "This room smells of paint.", "type": "句子", "keyWords": ["smell"] },
    { "chinese": "发出鱼的腥味/有大蒜味", "english": "smell of fish/garlic", "type": "短语", "keyWords": ["smell"] },
    { "chinese": "a.发臭的；有难闻气味的", "english": "smelly", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]/vi.微笑(at) v.以微笑表示；露出(笑容)", "english": "smile", "type": "单词", "keyWords": [] },
    { "chinese": "满面笑容", "english": "be all smiles", "type": "短语", "keyWords": ["smile"] },
    { "chinese": "脸上的笑容", "english": "a smile on his face", "type": "短语", "keyWords": ["smile"] },
    { "chinese": "强作欢颜", "english": "force a smile", "type": "短语", "keyWords": ["smile"] },
    { "chinese": "微笑以示感谢", "english": "smile her thanks", "type": "短语", "keyWords": ["smile"] },
    { "chinese": "n.[U]烟雾", "english": "smog", "type": "单词", "keyWords": [] },
    { "chinese": "v.冒烟；冒雾气；吸烟 v.抽(烟等)*熏 n.[C]烟；烟雾；雾气", "english": "smoke", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]抽烟；冒烟", "english": "smoking", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]吸烟者", "english": "smoker", "type": "单词", "keyWords": [] },
    { "chinese": "出去吸烟", "english": "go out for a smoke", "type": "短语", "keyWords": ["smoke"] },
    { "chinese": "烟熏蚊子", "english": "smoke out mosquitoes", "type": "短语", "keyWords": ["smoke"] },
    { "chinese": "禁烟室", "english": "a smoke-free room", "type": "短语", "keyWords": ["smoke"] },
    { "chinese": "烟瘾很大", "english": "smoke like a chimney", "type": "短语", "keyWords": ["smoke"] },
    { "chinese": "烟色玻璃", "english": "smoked glass", "type": "短语", "keyWords": ["smoke"] },
    { "chinese": "熏肉，熏制肉", "english": "smoked meat", "type": "短语", "keyWords": ["smoke"] },
    { "chinese": "吸烟车厢", "english": "smoking car", "type": "短语", "keyWords": ["smoke"] },
    { "chinese": "老烟枪", "english": "a heavy smoker", "type": "短语", "keyWords": ["smoke"] },
    { "chinese": "无火不起烟。/无风不起浪。", "english": "There is no smoke without fire. = Where there's smoke, there's fire.", "type": "句子", "keyWords": ["smoke"] },
    { "chinese": "a.烟雾弥漫的", "english": "smoky", "type": "单词", "keyWords": [] },
    { "chinese": "a.平滑的，平整的，平稳的，顺利的 v.使平滑；使顺利", "english": "smooth", "type": "单词", "keyWords": [] },
    { "chinese": "顺利的旅程", "english": "a smooth journey", "type": "短语", "keyWords": ["smooth"] },
    { "chinese": "光滑的纸", "english": "smooth paper", "type": "短语", "keyWords": ["smooth"] },
    { "chinese": "消除忧虑/解决困难", "english": "smooth away one's worry/difficulties", "type": "短语", "keyWords": ["smooth"] },
    { "chinese": "n.[C]小吃，快餐，点心", "english": "snack", "type": "单词", "keyWords": [] },
    { "chinese": "一家流动快餐店", "english": "a mobile snack bar", "type": "短语", "keyWords": ["snack"] },
    { "chinese": "n.[C]蛇", "english": "snake", "type": "单词", "keyWords": [] },
    { "chinese": "v.攫取(迅速、急切或突然地握住或夺走)", "english": "snatch", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]/vi.打喷嚏", "english": "sneeze", "type": "单词", "keyWords": [] },
    { "chinese": "v.下雪 v.使雪片似的落下；用雪覆盖/困住 n.[U]雪", "english": "snow", "type": "单词", "keyWords": [] },
    { "chinese": "a.雪白的", "english": "snow-white", "type": "单词", "keyWords": [] },
    { "chinese": "一场大雪", "english": "a heavy (fall of) snow", "type": "短语", "keyWords": ["snow"] },
    { "chinese": "降雪，降雪量", "english": "snowfall", "type": "单词", "keyWords": [] },
    { "chinese": "雪盲的", "english": "snowblind", "type": "单词", "keyWords": [] },
    { "chinese": "暴风雪", "english": "snowstorm", "type": "单词", "keyWords": [] },
    { "chinese": "我们被大雪困在屋里了。", "english": "We were snowed in.", "type": "句子", "keyWords": ["snow"] },
    { "chinese": "ad.这么；那么；如此；也，同样(常用倒装结构) conj.因而", "english": "so", "type": "单词", "keyWords": [] },
    { "chinese": "大约；在…左右", "english": "or so", "type": "短语", "keyWords": ["so"] },
    { "chinese": "要是那样的话", "english": "if so", "type": "短语", "keyWords": ["so"] },
    { "chinese": "[口]再见！", "english": "So long!", "type": "句子", "keyWords": ["so"] },
    { "chinese": "关于…事情就谈这么多", "english": "so much for...", "type": "短语", "keyWords": ["so"] },
    { "chinese": "所谓的，号称的(常含贬义)", "english": "so-called", "type": "短语", "keyWords": ["so"] },
    { "chinese": "等等，以此类推", "english": "and so forth (=and so on)", "type": "短语", "keyWords": ["so"] },
    { "chinese": "那么又怎样呢？结果怎样？那有什么关系呢？", "english": "So what?", "type": "句子", "keyWords": ["so"] },
    { "chinese": "为了，以便；结果，以致(不用于句首)", "english": "so as to do sth.", "type": "短语", "keyWords": ["so"] },
    { "chinese": "表示“为的是，使得；以致，结果是”", "english": "so that + 句子", "type": "短语", "keyWords": ["so"] },
    { "chinese": "表示“如此…以致…”(注意倒装的用法)", "english": "so...that + 句子", "type": "短语", "keyWords": ["so"] },
    { "chinese": "这书写得太不认真了，以至于对事实给出了错误的概念。", "english": "The book is so carelessly written that it gives a wrong idea of the facts.", "type": "句子", "keyWords": ["so"] },
    { "chinese": "如此…以致…", "english": "so....as to do sth.", "type": "短语", "keyWords": ["so"] },
    { "chinese": "他竟然幼稚得连这种谎言都相信。", "english": "He is so naive as to believe such a lie.", "type": "句子", "keyWords": ["so"] },
    { "chinese": "请您…", "english": "Would you be so kind as to...", "type": "短语", "keyWords": ["so"] },
    { "chinese": "正巧…", "english": "It so happened that...", "type": "短语", "keyWords": ["so"] },
    { "chinese": "n.[U]肥皂", "english": "soap", "type": "单词", "keyWords": [] },
    { "chinese": "肥皂剧", "english": "soap opera", "type": "短语", "keyWords": ["soap"] },
    { "chinese": "一条肥皂", "english": "a bar of soap", "type": "短语", "keyWords": ["soap"] },
    { "chinese": "v.哭泣 n.(声)，哭泣(声)", "english": "sob", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]英式足球", "english": "soccer", "type": "单词", "keyWords": [] },
    { "chinese": "a.好交际的；社交的，合群的", "english": "sociable", "type": "单词", "keyWords": [] }
];
qgl245_252.sort(() => Math.random() - 0.5);
