const qgl253_260 = [
    { "chinese": "adj.会交际的；社交的", "english": "social /'səʊʃl/", "type": "单词", "keyWords": [] },
    { "chinese": "社会道德/社会实践/联谊会", "english": "social morality/practice/gathering", "type": "短语", "keyWords": ["social"] },
    { "chinese": "n.[U]社会 n.[C]社团，协会，学会", "english": "society /sə'saɪəti/", "type": "单词", "keyWords": [] },
    { "chinese": "在（现代）社会里", "english": "in (modern) society", "type": "短语", "keyWords": ["society"] },
    { "chinese": "n.[U]社会主义（制度）", "english": "socialism /'səʊʃəlɪzəm/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]社会主义者 adj.社会主义的", "english": "socialist /'səʊʃəlɪst/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]短袜", "english": "sock /sɒk/", "type": "单词", "keyWords": [] },
    { "chinese": "一双短袜", "english": "a pair of socks", "type": "短语", "keyWords": ["sock"] },
    { "chinese": "n.[C]插座；插口", "english": "socket /'sɒkɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（长）沙发", "english": "sofa /'səʊfə/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.柔软的；轻声的；轻微的 v.（使）软化；（使）温柔", "english": "soft /sɒft/", "type": "单词", "keyWords": [] },
    { "chinese": "柔和的光", "english": "soft light", "type": "短语", "keyWords": ["soft"] },
    { "chinese": "软饮料", "english": "soft drinks", "type": "短语", "keyWords": ["soft"] },
    { "chinese": "低声地", "english": "in a soft voice", "type": "短语", "keyWords": ["soft"] },
    { "chinese": "n.[U]（总称）（电脑）软件", "english": "software /'sɒftweə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]泥土；土壤；大地", "english": "soil /sɔɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.太阳的；太阳能的", "english": "solar", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]士兵；军人", "english": "soldier", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]固体 adj.固体的；结实的；实心的；实在的，可靠的", "english": "solid", "type": "单词", "keyWords": [] },
    { "chinese": "理由充分的论点", "english": "solid arguments", "type": "短语", "keyWords": ["solid"] },
    { "chinese": "固体食物", "english": "solid food", "type": "短语", "keyWords": ["solid"] },
    { "chinese": "奠定/打下牢固的基础", "english": "lay a solid foundation for...", "type": "短语", "keyWords": ["solid"] },
    { "chinese": "n.[C][U]解决方法 n.[U]解答；解决", "english": "solution", "type": "单词", "keyWords": [] },
    { "chinese": "解决…的办法", "english": "a solution to (doing) sth.", "type": "短语", "keyWords": ["solution"] },
    { "chinese": "找到一种访问web数据库的完整的解决方案", "english": "find a complete solution to accessing the web database", "type": "句子", "keyWords": ["solution"] },
    { "chinese": "vt.解决；解答（近settle, work out, figure out）", "english": "solve", "type": "单词", "keyWords": [] },
    { "chinese": "adv.大约 adj.一些；某一 pron.一些", "english": "some", "type": "单词", "keyWords": [] },
    { "chinese": "某本书里", "english": "in some book or other", "type": "短语", "keyWords": ["some"] },
    { "chinese": "有的…（有的…）其他的…", "english": "Some...Some... others...", "type": "短语", "keyWords": ["some"] },
    { "chinese": "pron.有人；某人（不是\"一些人\"）；重要人物", "english": "somebody", "type": "单词", "keyWords": [] },
    { "chinese": "在这里他是小人物，但在他自己的村里却是个了不起的人。", "english": "He's (a) nobody here but he's (a) somebody in his own village.", "type": "句子", "keyWords": ["somebody"] },
    { "chinese": "adv.不知怎么地；以某种方式", "english": "somehow", "type": "单词", "keyWords": [] },
    { "chinese": "她不知道怎么竟迷了路。", "english": "She somehow got lost.", "type": "句子", "keyWords": ["somehow"] },
    { "chinese": "pron.某人，有人（=somebody）", "english": "someone", "type": "单词", "keyWords": [] },
    { "chinese": "pron.某事，某物；重要人物，有地位的人", "english": "something", "type": "单词", "keyWords": [] },
    { "chinese": "有比没有好。", "english": "Something is better than nothing.", "type": "句子", "keyWords": ["something"] },
    { "chinese": "理论虽重要，实践更重要。", "english": "Theory is something but practice is everything.", "type": "句子", "keyWords": ["something"] },
    { "chinese": "和…有关系", "english": "have something to do with...", "type": "短语", "keyWords": ["something"] },
    { "chinese": "或是…之类", "english": "...or something", "type": "短语", "keyWords": ["something"] },
    { "chinese": "你是从太空来的吗？（你好奇怪喔！）", "english": "Are you from outer space or something?", "type": "句子", "keyWords": ["something"] },
    { "chinese": "有大约十元", "english": "have something like 10 yuan", "type": "短语", "keyWords": ["something"] },
    { "chinese": "有点像，在某种程度上像是（在撒谎）", "english": "be something of (a liar)", "type": "短语", "keyWords": ["something"] },
    { "chinese": "他认为他穿上制服就神气非凡。", "english": "He thinks he is something in that uniform.", "type": "句子", "keyWords": ["something"] },
    { "chinese": "adv.某个时候（比较some time, a time 一段时间）", "english": "sometime", "type": "单词", "keyWords": [] },
    { "chinese": "adv.有时（比较at times, from time to time）", "english": "sometimes", "type": "单词", "keyWords": [] },
    { "chinese": "adv.在某处 n.[U]某处", "english": "somewhere", "type": "单词", "keyWords": [] },
    { "chinese": "我丢失了七八美元。", "english": "I lost somewhere between 7 and 8 dollars.", "type": "句子", "keyWords": ["somewhere"] },
    { "chinese": "有所进展，有结果，有所成效", "english": "get somewhere", "type": "短语", "keyWords": ["somewhere"] },
    { "chinese": "如果你只讲事实，可能我们会谈出一些结果。", "english": "If you deal with just the facts, maybe we'll get somewhere.", "type": "句子", "keyWords": ["somewhere"] },
    { "chinese": "希望不是吧，要我和他在一起，那可是连门儿都没有。", "english": "I hope not. He's not going to get anywhere with me.", "type": "句子", "keyWords": ["somewhere"] },
    { "chinese": "n.[C]儿子", "english": "son", "type": "单词", "keyWords": [] },
    { "chinese": "女婿", "english": "son(s)-in-law", "type": "短语", "keyWords": ["son"] },
    { "chinese": "n.[C]歌曲", "english": "song", "type": "单词", "keyWords": [] },
    { "chinese": "流行歌曲", "english": "pop song", "type": "短语", "keyWords": ["song"] },
    { "chinese": "adv.不久，很快", "english": "soon", "type": "单词", "keyWords": [] },
    { "chinese": "一…就…", "english": "as soon as", "type": "短语", "keyWords": ["soon"] },
    { "chinese": "迟早", "english": "sooner or later", "type": "短语", "keyWords": ["soon"] },
    { "chinese": "这么快；太快", "english": "so/too soon", "type": "短语", "keyWords": ["soon"] },
    { "chinese": "愈早愈好。", "english": "The sooner, the better.", "type": "句子", "keyWords": ["soon"] },
    { "chinese": "尽可能快地", "english": "as soon as possible", "type": "短语", "keyWords": ["soon"] },
    { "chinese": "你说得太急/早了。", "english": "You spoke too soon.", "type": "句子", "keyWords": ["soon"] },
    { "chinese": "对不起我没有早点说。", "english": "I'm sorry I didn't say it sooner.", "type": "句子", "keyWords": ["soon"] },
    { "chinese": "一…就…（常用倒装句型）", "english": "no sooner...than...", "type": "短语", "keyWords": ["soon"] },
    { "chinese": "我刚走她就打来了电话。", "english": "No sooner had I left than she called.", "type": "句子", "keyWords": ["soon"] },
    { "chinese": "adj.痛的，酸痛的；痛苦的；痛心的；艰辛的", "english": "sore", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]悲伤，痛苦", "english": "soreness", "type": "单词", "keyWords": [] },
    { "chinese": "喉咙痛", "english": "have a sore throat", "type": "短语", "keyWords": ["sore"] },
    { "chinese": "n.[C][U]悲哀；悲痛", "english": "sorrow", "type": "单词", "keyWords": [] },
    { "chinese": "adj.悲伤的", "english": "sorrowful", "type": "单词", "keyWords": [] },
    { "chinese": "沉浸在深切的悲痛之中", "english": "be in deep sorrow", "type": "短语", "keyWords": ["sorrow"] },
    { "chinese": "adj.抱歉的，对不起的；难过的；遗憾的；后悔的", "english": "sorry", "type": "单词", "keyWords": [] },
    { "chinese": "感到难过；为…感到遗憾", "english": "be/feel sorry for/about...", "type": "短语", "keyWords": ["sorry"] },
    { "chinese": "感到抱歉，对不起", "english": "be/feel sorry about...", "type": "短语", "keyWords": ["sorry"] },
    { "chinese": "对不起，但…", "english": "I'm sorry but...", "type": "短语", "keyWords": ["sorry"] },
    { "chinese": "n.[C]种类 v.把…分类；整理；拣出", "english": "sort", "type": "单词", "keyWords": [] },
    { "chinese": "（作状语用）有几分；在一定程度上（近somewhat）", "english": "sort/kind of", "type": "短语", "keyWords": ["sort"] },
    { "chinese": "我多少有点猜到这件事有可能会发生。", "english": "I sort of thought this might happen.", "type": "句子", "keyWords": ["sort"] },
    { "chinese": "整理；挑出", "english": "sort...out", "type": "短语", "keyWords": ["sort"] },
    { "chinese": "挑选出要扔掉的文件", "english": "sort out the papers to be thrown away", "type": "短语", "keyWords": ["sort"] },
    { "chinese": "n.[C]灵魂；心灵；人（主要在否定句中） n.[U]精神；精力", "english": "soul", "type": "单词", "keyWords": [] },
    { "chinese": "这些愿望，他们说，来自灵魂深处。", "english": "These wishes they say come from the depths of the soul.", "type": "句子", "keyWords": ["soul"] },
    { "chinese": "一个人也看不到。", "english": "Not a soul was to be seen.", "type": "句子", "keyWords": ["soul"] },
    { "chinese": "全心全意做事", "english": "do sth. (with one's) heart and soul", "type": "短语", "keyWords": ["soul"] },
    { "chinese": "全身心贯注于学习", "english": "put his heart and soul into his study", "type": "短语", "keyWords": ["soul"] },
    { "chinese": "勉强维持生计；勉强活下去", "english": "keep body and soul together", "type": "短语", "keyWords": ["soul"] },
    { "chinese": "vi.听起来；似乎 vi./vt.（使）发出声音 n.[C]声音；响声 adj.健康的；合理的；完全的，彻底的 adv.彻底（用于熟睡）", "english": "sound", "type": "单词", "keyWords": [] },
    { "chinese": "发出警报", "english": "sound the alarm", "type": "短语", "keyWords": ["sound"] },
    { "chinese": "这音乐听起来多美啊！", "english": "How sweet the music sounds!", "type": "句子", "keyWords": ["sound"] },
    { "chinese": "酣睡", "english": "a fast/sound sleep", "type": "短语", "keyWords": ["sound"] },
    { "chinese": "甜睡", "english": "be sound asleep/ sleep soundly", "type": "短语", "keyWords": ["sound"] },
    { "chinese": "身心健康", "english": "have a sound mind in a sound body", "type": "短语", "keyWords": ["sound"] },
    { "chinese": "n.[U]汤", "english": "soup", "type": "单词", "keyWords": [] },
    { "chinese": "adj.酸的；酸腐的，酸臭的；易怒的，脾气坏的；郁闷的", "english": "sour", "type": "单词", "keyWords": [] },
    { "chinese": "变酸；坏了", "english": "go sour", "type": "短语", "keyWords": ["sour"] },
    { "chinese": "发酸的牛奶", "english": "sour milk", "type": "短语", "keyWords": ["sour"] },
    { "chinese": "酸葡萄（心理）", "english": "sour grapes", "type": "短语", "keyWords": ["sour"] },
    { "chinese": "n.[C]来源；出处（辨析见origin）", "english": "source", "type": "单词", "keyWords": [] },
    { "chinese": "尼罗河的发源地", "english": "the sources of the Nile", "type": "短语", "keyWords": ["source"] },
    { "chinese": "知识的源泉/传染源", "english": "the source of knowledge/ the infection", "type": "短语", "keyWords": ["source"] },
    { "chinese": "水源/光源/信息源；情报源", "english": "water/ light/ information source", "type": "短语", "keyWords": ["source"] },
    { "chinese": "来自可靠的史料", "english": "come from reliable historical sources", "type": "短语", "keyWords": ["source"] },
    { "chinese": "n.[C]/a.南；南方（的） adv.朝/向南（用法见north）", "english": "south", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]/a.东南；东南方（的） adv.朝/向东南", "english": "southeast", "type": "单词", "keyWords": [] },
    { "chinese": "adj.南方的 n.[C]南方人", "english": "southern", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]/a.西南；西南方（的） adv.朝/向西南", "english": "southwest", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]纪念品，纪念物", "english": "souvenir", "type": "单词", "keyWords": [] },
    { "chinese": "vt.播种（可用于抽象意义）", "english": "sow", "type": "单词", "keyWords": [] },
    { "chinese": "在…心中播下仇恨的种子", "english": "sow the seeds of hatred among sb.", "type": "短语", "keyWords": ["sow"] },
    { "chinese": "种瓜得瓜，种豆得豆。", "english": "As a man sows so he shall reap.", "type": "句子", "keyWords": ["sow"] },
    { "chinese": "n.[C]黄豆；大豆", "english": "soybean", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]空间；太空 n.[C]间隔；（词间或行间的）空白处", "english": "space", "type": "单词", "keyWords": [] },
    { "chinese": "在（外层）太空", "english": "in (outer) space", "type": "短语", "keyWords": ["space"] },
    { "chinese": "航天飞机", "english": "space shuttle", "type": "短语", "keyWords": ["space"] },
    { "chinese": "…间一个4英寸的间隔", "english": "a space of 4 inches between...", "type": "短语", "keyWords": ["space"] },
    { "chinese": "n.[C]（单复同）宇宙飞船", "english": "spacecraft", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]宇宙飞船", "english": "spaceship", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]铲子，铁锹；黑桃（牌） v.（用铲或铁锹）挖掘或铲", "english": "spade", "type": "单词", "keyWords": [] },
    { "chinese": "说实话，直言不讳", "english": "call a spade a spade", "type": "短语", "keyWords": ["spade"] },
    { "chinese": "adj.多余的；空闲的；备用的 v.节约；抽出；匀出；饶恕", "english": "spare", "type": "单词", "keyWords": [] },
    { "chinese": "在某人的业余时间", "english": "in one's spare time", "type": "短语", "keyWords": ["spare"] },
    { "chinese": "备用零件/备用的一双/备胎", "english": "a spare part/ pair/ tire", "type": "短语", "keyWords": ["spare"] },
    { "chinese": "不遗余力地做某事", "english": "spare no efforts/ pains to do sth.", "type": "短语", "keyWords": ["spare"] },
    { "chinese": "不惜工本", "english": "spare no expense", "type": "短语", "keyWords": ["spare"] },
    { "chinese": "抽出十分钟帮我忙", "english": "spare me ten minutes to help me", "type": "短语", "keyWords": ["spare"] },
    { "chinese": "你能匀给我几升汽油吗？", "english": "Can you spare me a few litres of petrol?", "type": "句子", "keyWords": ["spare"] },
    { "chinese": "这本书能让我看一会儿吗？", "english": "Can you spare me this book for a while?", "type": "句子", "keyWords": ["spare"] },
    { "chinese": "他只差几分钟就赶不上火车了。", "english": "He caught the train with only a few minutes to spare.", "type": "句子", "keyWords": ["spare"] },
    { "chinese": "v.说；讲；讲话 vi.会讲（某语言）；说出（真相、想法等）", "english": "speak /spi:k/", "type": "单词", "keyWords": [] },
    { "chinese": "说实话", "english": "speak the truth", "type": "短语", "keyWords": ["speak"] },
    { "chinese": "大胆讲话", "english": "speak out", "type": "短语", "keyWords": ["speak"] },
    { "chinese": "坦率地说出看法", "english": "speak one's mind (speak up)", "type": "短语", "keyWords": ["speak"] },
    { "chinese": "称赞，高度评价", "english": "speak highly/well of", "type": "短语", "keyWords": ["speak"] },
    { "chinese": "谈到…", "english": "Speaking of...", "type": "短语", "keyWords": ["speak"] },
    { "chinese": "严格地说/一般来说/粗略地说", "english": "Strictly/ Generally/ Roughly speaking...", "type": "短语", "keyWords": ["speak"] },
    { "chinese": "代表…说话，为…辩护，为…讲好话", "english": "speak for", "type": "短语", "keyWords": ["speak"] },
    { "chinese": "说…的坏话，作不利于…的陈述，发言反对", "english": "speak against", "type": "短语", "keyWords": ["speak"] },
    { "chinese": "行动胜于空谈。", "english": "Actions speak louder than words.", "type": "句子", "keyWords": ["speak"] },
    { "chinese": "n.[C]说话者，演讲者；扬声器，喇叭", "english": "speaker /'spi:kə/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.特殊的；专门的", "english": "special /'speʃl/", "type": "单词", "keyWords": [] },
    { "chinese": "adv.特别地", "english": "specially", "type": "单词", "keyWords": ["special"] },
    { "chinese": "n.[C]专家", "english": "specialist", "type": "单词", "keyWords": ["special"] },
    { "chinese": "特别地区，特区", "english": "special area", "type": "短语", "keyWords": ["special"] },
    { "chinese": "专列", "english": "special train", "type": "短语", "keyWords": ["special"] },
    { "chinese": "她女儿特地来探望", "english": "a special visit from her daughter", "type": "短语", "keyWords": ["special"] },
    { "chinese": "我个人专用的椅子", "english": "my own special chair", "type": "短语", "keyWords": ["special"] },
    { "chinese": "计算机的专有特性", "english": "the special features of a computer", "type": "短语", "keyWords": ["special"] },
    { "chinese": "adj.特殊的；专门的；专科的(in)", "english": "specialized /'speʃəlaɪzd/", "type": "单词", "keyWords": [] },
    { "chinese": "专攻(in)（近major, expert, be experienced in）", "english": "specialize in", "type": "短语", "keyWords": ["specialized"] },
    { "chinese": "专门机构，专业机构", "english": "specialized agencies", "type": "短语", "keyWords": ["specialized"] },
    { "chinese": "本公司是专业生产各类织物的厂家。", "english": "Our company is specialized in all kinds of fabrics.", "type": "句子", "keyWords": ["specialized"] },
    { "chinese": "她专门从事室内设计。", "english": "She specializes in interior design.", "type": "句子", "keyWords": ["specialized"] },
    { "chinese": "n.[C]（单复同）种类；物种（类似means, series）", "english": "species /'spi:ʃi:z/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.明确的；详细而精确的；特定的；具体的", "english": "specific /spə'sɪfɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "明确的到货时间", "english": "specific time of arrival", "type": "短语", "keyWords": ["specific"] },
    { "chinese": "明确指令，详细指导", "english": "specific instructions", "type": "短语", "keyWords": ["specific"] },
    { "chinese": "n.[C]（比赛等的）观众；旁观者", "english": "spectator /spek'teɪtə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]讲话 n.[C]演讲", "english": "speech /spi:tʃ/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.一时说不出话的", "english": "speechless", "type": "单词", "keyWords": ["speech"] },
    { "chinese": "发表演说", "english": "deliver/ make/ give a speech", "type": "短语", "keyWords": ["speech"] },
    { "chinese": "n.[C][U]速度 adj.快的，迅速的", "english": "speed /spi:d/", "type": "单词", "keyWords": [] },
    { "chinese": "快速地，迅速地", "english": "at high/ full top speed= with great/ all speed", "type": "短语", "keyWords": ["speed"] },
    { "chinese": "以…的速度", "english": "at the speed of...", "type": "短语", "keyWords": ["speed"] },
    { "chinese": "（使）加快速度（近pick up speed）", "english": "speed(...) up", "type": "短语", "keyWords": ["speed"] },
    { "chinese": "v.写；用字母拼 vi.拼写", "english": "spell /spel/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]拼写 n.[C]拼法", "english": "spelling", "type": "单词", "keyWords": ["spell"] },
    { "chinese": "v.花（钱）；花费；度过，花（时间等）", "english": "spend /spend/", "type": "单词", "keyWords": [] },
    { "chinese": "在作业上花很多时间", "english": "spend a lot of time on his homework", "type": "短语", "keyWords": ["spend"] },
    { "chinese": "花很多时间做家庭作业", "english": "spend a lot of time (in) doing his homework", "type": "短语", "keyWords": ["spend"] },
    { "chinese": "n.[C]蜘蛛", "english": "spider /'spaɪdə/", "type": "单词", "keyWords": [] },
    { "chinese": "v.（使）溢出；（使）泼出；（使）洒落", "english": "spill /spɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "溢出", "english": "spill over", "type": "短语", "keyWords": ["spill"] },
    { "chinese": "v.纺；（蜘蛛）结网；编造（故事等）；旋转", "english": "spin /spɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "纺棉线", "english": "spin cotton into thread", "type": "短语", "keyWords": ["spin"] },
    { "chinese": "结网", "english": "spin webs", "type": "短语", "keyWords": ["spin"] },
    { "chinese": "旋转盘", "english": "a spinning disk", "type": "短语", "keyWords": ["spin"] },
    { "chinese": "n.[U]精神 n.[C]灵魂，精灵；(pl.)情绪；心境；活力；勇气", "english": "spirit /'spɪrɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.精神的，灵魂的", "english": "spiritual", "type": "单词", "keyWords": ["spirit"] },
    { "chinese": "在精神上", "english": "in spirit", "type": "短语", "keyWords": ["spirit"] },
    { "chinese": "精神生活", "english": "spiritual life", "type": "短语", "keyWords": ["spirit"] },
    { "chinese": "他是天国的精灵之一。", "english": "He was one of the spirits in heaven.", "type": "句子", "keyWords": ["spirit"] },
    { "chinese": "情绪极佳/心情不好", "english": "in high/ great/ low/ poor spirits", "type": "短语", "keyWords": ["spirit"] },
    { "chinese": "v.吐痰，吐唾液 v.吐出（唾液等） n.[U]唾液，唾沫", "english": "spit /spɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "吐出；厉声说出", "english": "spit...out", "type": "短语", "keyWords": ["spit"] },
    { "chinese": "突然口出恶语", "english": "spit out an insult", "type": "短语", "keyWords": ["spit"] },
    { "chinese": "n.[U]怨恨", "english": "spite /spaɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "不顾；不管（近despite）", "english": "in spite of", "type": "短语", "keyWords": ["spite"] },
    { "chinese": "尽管，虽然（比较Although...）", "english": "In spite of the fact that...", "type": "短语", "keyWords": ["spite"] },
    { "chinese": "adj.光彩的；壮丽的，辉煌的；[口]极好的", "english": "splendid /'splendɪd/", "type": "单词", "keyWords": [] },
    { "chinese": "v.劈开；切开；使破裂 vi.被劈开；裂开 n.[C]/a.裂开（的）", "english": "split /splɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "v.损坏；糟蹋；宠坏 vi.（食物）变质（辨析见damage）", "english": "spoil /spɔɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "破坏聚会/糟蹋假日/宠坏孩子", "english": "spoil a party/ holiday/ child", "type": "短语", "keyWords": ["spoil"] },
    { "chinese": "惜了棍棒害了儿。/孩子不打不成器。", "english": "Spare the rod and spoil the child.", "type": "句子", "keyWords": ["spoil"] },
    { "chinese": "adj.口头的；口语的", "english": "spoken /'spəʊkən/", "type": "单词", "keyWords": [] },
    { "chinese": "v.主办；资助 n.[C]发起人；主办者；赞助者", "english": "sponsor /'spɒnsə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]匙，调羹", "english": "spoon /spu:n/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]一满匙", "english": "spoonful", "type": "单词", "keyWords": ["spoon"] },
    { "chinese": "n.[U]游戏；娱乐 n.[C]运动", "english": "sport /spɔ:t/", "type": "单词", "keyWords": [] },
    { "chinese": "田赛", "english": "field sports", "type": "短语", "keyWords": ["sport"] },
    { "chinese": "个人运动", "english": "individual sports", "type": "短语", "keyWords": ["sport"] },
    { "chinese": "团体运动", "english": "team sports", "type": "短语", "keyWords": ["sport"] },
    { "chinese": "运动设备", "english": "sports equipment", "type": "短语", "keyWords": ["sport"] },
    { "chinese": "n.[C]运动员", "english": "sportsman /'spɔ:tsmən/", "type": "单词", "keyWords": ["sport"] },
    { "chinese": "n.[U]运动员精神；运动员品格", "english": "sportsmanship /'spɔ:tsmənʃɪp/", "type": "单词", "keyWords": ["sport"] },
    { "chinese": "n.[C]点；地点，场所；斑点；污渍 v.认出，发现（辨析见see）；玷污", "english": "spot /spɒt/", "type": "单词", "keyWords": [] },
    { "chinese": "污斑", "english": "a dirty spot", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "在/到现场", "english": "on the spot/ scene", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "风景胜地", "english": "a scenic spot", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "古迹", "english": "a historic spot", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "在人群中认出一个朋友", "english": "spot a friend in the crowd", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "n.[C]配偶（指夫或妻）", "english": "spouse /spaʊs/", "type": "单词", "keyWords": [] },
    { "chinese": "v.喷酒；喷溅", "english": "spray /spreɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "v.伸展；传开；蔓延；涂，抹；铺开", "english": "spread /spred/", "type": "单词", "keyWords": [] },
    { "chinese": "传播消息/疾病/知识", "english": "spread news/ disease/ knowledge", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "在面包上涂黄油", "english": "spread butter on the bread= spread the bread with butter", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "像野火一样迅速蔓延/传播", "english": "spread like wildfire", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "摊开地图", "english": "spread out a map", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "教育的普及", "english": "the spread of education", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "n.[C][U]春天，春季 n.[C]泉；弹簧 n.[U]弹性 vi.跃；涌现", "english": "spring /sprɪŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "跳板", "english": "spring board", "type": "短语", "keyWords": ["spring"] },
    { "chinese": "温泉", "english": "a hot spring", "type": "短语", "keyWords": ["spring"] },
    { "chinese": "他一跃而起。", "english": "He sprang to his feet.", "type": "句子", "keyWords": ["spring"] },
    { "chinese": "新兴商业迅速涌现。", "english": "New businesses were springing up rapidly.", "type": "句子", "keyWords": ["spring"] },
    { "chinese": "n.[C]间谍；密探；暗中监视者 v.当间谍；暗中监视(on)", "english": "spy /spaɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "暗中监视某人", "english": "spy on/upon sb.", "type": "短语", "keyWords": ["spy"] },
    { "chinese": "窥探别人的事务", "english": "spy into other people's activities", "type": "短语", "keyWords": ["spy"] },
    { "chinese": "n.[C]正方形；方形物；广场；平方 a.方的；平方的", "english": "square /skweə/", "type": "单词", "keyWords": [] },
    { "chinese": "3平方米", "english": "3 square meters", "type": "短语", "keyWords": ["square"] },
    { "chinese": "5米见方。", "english": "It's 5m square.", "type": "句子", "keyWords": ["square"] },
    { "chinese": "v.榨取；挤取；挤压 vi.挤", "english": "squeeze /skwi:z/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.稳定的，稳固的 *stabilize v.使稳定 *stability n.[U]稳定性", "english": "stable /'steɪbl/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl.stadiums或stadia)(设有看台的)露天体育场", "english": "stadium /'steɪdiəm/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]全体职员；全体雇员(用作单或复) v.为……配备职员；担任……的职员", "english": "staff /stɑ:f/", "type": "单词", "keyWords": [] },
    { "chinese": "是在职，在编", "english": "be on the staff", "type": "短语", "keyWords": ["staff"] },
    { "chinese": "全体职员是……", "english": "The staff is/ are...", "type": "句子", "keyWords": ["staff"] },
    { "chinese": "n.[C]舞台；发展阶段，发展时期；(火箭的)级", "english": "stage /steɪdʒ/", "type": "单词", "keyWords": [] },
    { "chinese": "当演员", "english": "go/ be on the stage", "type": "短语", "keyWords": ["stage"] },
    { "chinese": "舞台效果", "english": "stage effect", "type": "短语", "keyWords": ["stage"] },
    { "chinese": "三级火箭 目前；眼下(近at present)", "english": "*a three-stage rocket at this stage", "type": "短语", "keyWords": ["stage"] },
    { "chinese": "n.[C]楼梯；梯级 *staircase n.[C]楼梯(间)", "english": "stair /steə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]货摊，摊位；书亭(近stand)", "english": "stall /stɔ:l/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]邮票；印，图章 v.盖印于……(近seal)；贴邮票于；跺脚；踩踏", "english": "stamp /stæmp/", "type": "单词", "keyWords": [] },
    { "chinese": "v.站，立；起立；保持不动；处于某种状态/境地 v.使站立；竖放；忍受 n.[C]站立；停留；售货处；摊位(尤指报摊)；(常用pl.)看台", "english": "stand /stænd/", "type": "单词", "keyWords": [] },
    { "chinese": "靠自己", "english": "stand on one's own", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "站住，不许动！", "english": "Stand still!", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "倒立", "english": "stand on one's head/ hands", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "代表，象征", "english": "stand for", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "站着不动", "english": "stand still/firm", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "站起来", "english": "stand up", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "使某人毛发悚然", "english": "make sb.'s hair stand on end", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "站在一边；袖手旁观；支持，忠于", "english": "stand by", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "作某人的后盾", "english": "stand behind sb.(=support sb./back sb.up)", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "(在天空的映衬下显得)突出；出色", "english": "stand out (against the sky)", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "使孩子站立/倒立", "english": "stand the child on his feet/his head", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "忍受(某人做)某事", "english": "stand/ bear/ endure (one's) doing sth.", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "再等下去我可受不了啦。", "english": "I cannot stand waiting any longer.", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "我对此事的立场与三年前无异。", "english": "*My stand on this is just the same as it was three years ago.", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "某物或某人六英尺高。", "english": "*Sth./Sb. stands six feet tall", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "按照现在情况，事实是这样", "english": "*as it stands", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "常委", "english": "*standing committee", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "实际情况就那样。", "english": "*That's how matters stand.", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "n.[C]标准；水平；规范；准则 a.标准的", "english": "standard /'stændəd/", "type": "单词", "keyWords": [] },
    { "chinese": "生活水平", "english": "the standard of living", "type": "短语", "keyWords": ["standard"] },
    { "chinese": "普通话", "english": "standard Chinese", "type": "短语", "keyWords": ["standard"] },
    { "chinese": "n.[C]星星；明星；主角；星号，星形物 v.使担任主角；使成为明星；用星号/星形物标出 vi.当明星；主演", "english": "star /stɑ:/", "type": "单词", "keyWords": [] },
    { "chinese": "他曾主演过许多部影片。", "english": "He has starred in many pictures.", "type": "句子", "keyWords": ["star"] },
    { "chinese": "他将主演一部新片。", "english": "He is to be starred in a new film.", "type": "句子", "keyWords": ["star"] },
    { "chinese": "我已把该读的重要文章都打上了星号。", "english": "I have starred the important articles to read.", "type": "句子", "keyWords": ["star"] },
    { "chinese": "vi./n.[C]凝视，注视(at) *vt.凝视，注视", "english": "stare /steə/", "type": "单词", "keyWords": [] },
    { "chinese": "凝视远方", "english": "stare into the distance", "type": "短语", "keyWords": ["stare"] },
    { "chinese": "盯着某人的眼睛", "english": "*stare sb. in the eyes", "type": "短语", "keyWords": ["stare"] },
    { "chinese": "冷冷地盯着", "english": "look at sb. with a cold stare = stare at sb. coldly", "type": "短语", "keyWords": ["stare"] },
    { "chinese": "v.出发，开始；(机器等)发动；惊起 v.发动(机器等)；开始；使开始；惊动；使吓一跳 n.[C]惊跳；出发；开始", "english": "start /stɑ:t/", "type": "单词", "keyWords": [] },
    { "chinese": "开始明白/意识到", "english": "start to see/ realize", "type": "短语", "keyWords": ["start"] },
    { "chinese": "创业/点火/发动汽车/发动战争", "english": "start a business/ a fire/ a car/ a war", "type": "短语", "keyWords": ["start"] },
    { "chinese": "起程旅行", "english": "start on a journey", "type": "短语", "keyWords": ["start"] },
    { "chinese": "以……开始", "english": "start with", "type": "短语", "keyWords": ["start"] },
    { "chinese": "知识始于实践。", "english": "Knowledge starts with practice.", "type": "句子", "keyWords": ["start"] },
    { "chinese": "烟呛得他咳嗽。", "english": "*Smoke started him coughing.", "type": "句子", "keyWords": ["start"] },
    { "chinese": "他被那响亮的吵闹声吓了一跳。", "english": "He started at the loud noise.", "type": "句子", "keyWords": ["start"] },
    { "chinese": "引擎发动不起来。", "english": "The engine won't start.", "type": "句子", "keyWords": ["start"] },
    { "chinese": "得到一个好机会而开始自己的事业", "english": "get a good start in life", "type": "短语", "keyWords": ["start"] },
    { "chinese": "提供某人开始自立的机会", "english": "give sb. a start in life", "type": "短语", "keyWords": ["start"] },
    { "chinese": "早点动身", "english": "make an early start", "type": "短语", "keyWords": ["start"] },
    { "chinese": "突然惊醒", "english": "awake with a start", "type": "短语", "keyWords": ["start"] },
    { "chinese": "n.[U]饥饿；饿死", "english": "starvation /stɑ:'veɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "vi.挨饿；饿死 v.使挨饿；使饿死", "english": "starve /stɑ:v/", "type": "单词", "keyWords": [] },
    { "chinese": "他饿死了。", "english": "He (was) starved to death.", "type": "句子", "keyWords": ["starve"] },
    { "chinese": "我要饿死了！", "english": "I'm starving!", "type": "句子", "keyWords": ["starve"] },
    { "chinese": "渴望得到某物", "english": "starve for sth.", "type": "短语", "keyWords": ["starve"] },
    { "chinese": "孩子渴望得到疼爱。", "english": "Children starve for affection.", "type": "句子", "keyWords": ["starve"] },
    { "chinese": "使某人饿得非做某事不可", "english": "starve sb. into (doing) sth.", "type": "短语", "keyWords": ["starve"] },
    { "chinese": "n.[C]国家；(美国的)州，邦；状态 v.陈述；声明", "english": "state /steɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "处于混乱的状况", "english": "in a state of confusion", "type": "短语", "keyWords": ["state"] },
    { "chinese": "心境，心情；思想(精神)状态/事态", "english": "the state of mind/affairs", "type": "短语", "keyWords": ["state"] },
    { "chinese": "如上所述", "english": "as stated above", "type": "短语", "keyWords": ["state"] },
    { "chinese": "事实", "english": "the stated facts", "type": "短语", "keyWords": ["state"] },
    { "chinese": "n.[C]陈述；声明", "english": "statement /'steɪtmənt/", "type": "单词", "keyWords": [] },
    { "chinese": "作出陈述；发表声明", "english": "make/ issue a statement", "type": "短语", "keyWords": ["statement"] },
    { "chinese": "n.[C]车站 *vt.安置；派驻；驻扎", "english": "station /'steɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "把士兵们驻扎在柏林", "english": "*station the soldiers at Berlin", "type": "短语", "keyWords": ["station"] },
    { "chinese": "n.[U]文具", "english": "stationery /'steɪʃənri/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]雕像；塑像", "english": "statue /'stætʃu:/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]身份；地位；情形；状态，状况", "english": "status /'steɪtəs/", "type": "单词", "keyWords": [] },
    { "chinese": "社会地位", "english": "social status", "type": "短语", "keyWords": ["status"] },
    { "chinese": "vi.停留，暂住；保持，继续是 n.[C]逗留，停留；逗留时间", "english": "stay /steɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "保持单身，不结婚", "english": "stay single", "type": "短语", "keyWords": ["stay"] },
    { "chinese": "呆在外面，不在家", "english": "stay out", "type": "短语", "keyWords": ["stay"] },
    { "chinese": "留下来(近be left behind)", "english": "stay behind", "type": "短语", "keyWords": ["stay"] },
    { "chinese": "你为什么不上学？", "english": "Why did you stay away from school?", "type": "句子", "keyWords": ["stay"] },
    { "chinese": "不睡觉，熬夜(近sit up)；没倒塌", "english": "stay up", "type": "短语", "keyWords": ["stay"] },
    { "chinese": "洪水过后，房屋仍在。", "english": "The house stayed up even after the flood.", "type": "句子", "keyWords": ["stay"] },
    { "chinese": "adj.稳的，稳定的(反unsteady/unstable)", "english": "steady /'stedi/", "type": "单词", "keyWords": [] },
    { "chinese": "稳如磐石", "english": "as steady as a rock", "type": "短语", "keyWords": ["steady"] },
    { "chinese": "踏实的人", "english": "a steady man", "type": "短语", "keyWords": ["steady"] },
    { "chinese": "n.[U]牛排；猪排", "english": "steak /steɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "v.偷，偷窃；剽窃 vi.偷偷地溜", "english": "steal /sti:l/", "type": "单词", "keyWords": [] },
    { "chinese": "溜入房间", "english": "steal into her room", "type": "短语", "keyWords": ["steal"] },
    { "chinese": "偷看一眼", "english": "steal a glance at...", "type": "短语", "keyWords": ["steal"] },
    { "chinese": "从…偷东西", "english": "steal sth. from sb./ sth.", "type": "短语", "keyWords": ["steal"] },
    { "chinese": "n.[U]水蒸气；水汽 vi.冒热气 v.蒸", "english": "steam /sti:m/", "type": "单词", "keyWords": [] },
    { "chinese": "馒头", "english": "steamed bread", "type": "短语", "keyWords": ["steam"] },
    { "chinese": "蒸汽机", "english": "steam engine", "type": "短语", "keyWords": ["steam"] },
    { "chinese": "蒸汽带动的", "english": "steam-driven", "type": "短语", "keyWords": ["steam"] },
    { "chinese": "n.[C]汽船", "english": "steamship /'sti:mʃɪp/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]钢", "english": "steel /sti:l/", "type": "单词", "keyWords": [] },
    { "chinese": "炼钢工人", "english": "steelworker", "type": "单词", "keyWords": ["steel"] },
    { "chinese": "钢珠", "english": "steel ball", "type": "短语", "keyWords": ["steel"] },
    { "chinese": "adj.陡峭的，险峻的", "english": "steep /sti:p/", "type": "单词", "keyWords": [] },
    { "chinese": "v.为(船舶)操舵；驾驶(车、船、飞机等)；指导；引导", "english": "steer /stɪə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]茎；干 vi.起源于；基于，由…造成(from)", "english": "stem /stem/", "type": "单词", "keyWords": [] },
    { "chinese": "如果让其自然生长，主干会长到12英尺左右。", "english": "The main stem will extend to around 12 feet if left to grow naturally.", "type": "句子", "keyWords": ["stem"] },
    { "chinese": "北欧渐进的农业革命源于人口增长时期对粮食供应的担忧。", "english": "A gradual agricultural revolution in northern Europe stemmed from concerns over food supplies at a time of rising populations.", "type": "句子", "keyWords": ["stem"] },
    { "chinese": "n.[C](脚)步(声)；台阶；步骤；措施 vi.跨步；踩；行走", "english": "step /step/", "type": "单词", "keyWords": [] },
    { "chinese": "与…步调一致/不一致", "english": "in/ out of step with", "type": "短语", "keyWords": ["step"] },
    { "chinese": "与…步调一致", "english": "keep step with...= keep pace with...", "type": "短语", "keyWords": ["step"] },
    { "chinese": "当心脚下；做事谨慎", "english": "mind/watch one's step", "type": "短语", "keyWords": ["step"] },
    { "chinese": "采取措施做某事", "english": "take steps/ measures/ action to do sth.", "type": "短语", "keyWords": ["step"] },
    { "chinese": "逐渐地(近bit by bit, little by little)", "english": "step by step", "type": "短语", "keyWords": ["step"] },
    { "chinese": "走到一旁；避到一旁让给别人；让位", "english": "step aside", "type": "短语", "keyWords": ["step"] },
    { "chinese": "后退，后退一步", "english": "step back", "type": "短语", "keyWords": ["step"] },
    { "chinese": "进入新阶段", "english": "step into a new stage", "type": "短语", "keyWords": ["step"] },
    { "chinese": "万事开头难。", "english": "It is the first step that costs.", "type": "句子", "keyWords": ["step"] },
    { "chinese": "n.[C]棍，棒；枝条，柴枝；手杖 vi.坚持；被刺入；被粘贴 vt.刺；粘贴 *sticky a.粘的，粘性的", "english": "stick /stɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "把手伸进口袋", "english": "stick his hands in his pocket", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "将叉刺进鱼里", "english": "stick the fork into the fish", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "陷在雪里/卡在喉咙里", "english": "be/get stuck in the snow/ throat", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "坚持基本原则(近keep to, hold out, persist in, persevere in, insist on, adhere to, cling to)", "english": "stick to basic principles", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "(使)突出，(使)伸出", "english": "stick(...) out", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "ad.还；仍旧；更(接比较级) a.静止的；寂静的(辨析见quiet)", "english": "still /stɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "v.激励；刺激 *stimulation n.[U] stimulus /'stɪmjʊləs/(pl. stimuli /'stɪmjʊlaɪ/)n.[C]刺激(物)，促进(因素)", "english": "stimulate /'stɪmjuleɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "激励某人作更大的努力", "english": "stimulate sb. into greater effort= stimulate sb. to make greater efforts", "type": "短语", "keyWords": ["stimulate"] },
    { "chinese": "v.搅动，搅拌；使…激动；使…不安；激发 n.[C](用单数)微动；惊动；轰动；搅动；骚乱", "english": "stir /stɜ:/", "type": "单词", "keyWords": [] },
    { "chinese": "喝汤之前先搅一搅", "english": "stir the soup before tasting it", "type": "短语", "keyWords": ["stir"] },
    { "chinese": "激动人心的演说", "english": "a stirring speech", "type": "短语", "keyWords": ["stir"] },
    { "chinese": "激起某人的想象", "english": "stir one's imagination", "type": "短语", "keyWords": ["stir"] },
    { "chinese": "v.给…备货；储备；供应 n.[C]树，根茎；库存(物)，存货；股票，股份；证券 n.[U](总)牲畜，家畜", "english": "stock /stɒk/", "type": "单词", "keyWords": [] },
    { "chinese": "家畜(总称)", "english": "live stock", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "证券交易所", "english": "stock exchange", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "黄金储备", "english": "the gold stock", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "股票市场", "english": "stock market", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "大批玩具存货", "english": "a large stock of toys", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "股东", "english": "stockholder", "type": "单词", "keyWords": ["stock"] },
    { "chinese": "没有现货，脱销", "english": "out of stock", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "在库存里，备有现货，有现货可卖", "english": "have/keep in stock", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "他的头脑里主意很多。", "english": "His head is well stocked with ideas.", "type": "句子", "keyWords": ["stock"] },
    { "chinese": "n.[C]长筒袜", "english": "stocking /'stɒkɪŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl. stomachs)胃；腹部", "english": "stomach /'stʌmək/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]胃痛，肚子痛", "english": "stomachache", "type": "单词", "keyWords": ["stomach"] },
    { "chinese": "n.[U]石(料)；石头 n.[C]石块；石子；宝石", "english": "stone /stəʊn/", "type": "单词", "keyWords": [] },
    { "chinese": "宝石", "english": "a precious stone", "type": "短语", "keyWords": ["stone"] },
    { "chinese": "一箭之遥，在附近", "english": "within a stone's throw", "type": "短语", "keyWords": ["stone"] },
    { "chinese": "垫脚石；跳板；进身之阶", "english": "a stepping stone", "type": "短语", "keyWords": ["stone"] },
    { "chinese": "一石二鸟。", "english": "Kill two birds with one stone.", "type": "句子", "keyWords": ["stone"] },
    { "chinese": "滚石不生苔，转行不成材。", "english": "A rolling stone gathers no moss.", "type": "句子", "keyWords": ["stone"] },
    { "chinese": "v.堵塞；阻塞；停止，停下；停留；阻止；拦截 n.[C]停车站；停止", "english": "stop /stɒp/", "type": "单词", "keyWords": [] },
    { "chinese": "用一块布堵住漏洞", "english": "stop a leak with a piece of cloth", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "阻止某人做某事(近prevent, ban, prohibit, hold back, keep...from, forbid sb. to do sth.)", "english": "stop sb. (from) doing sth.", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "停止做某事", "english": "stop/cease doing sth.= cease to do sth.", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "停下来(原来在做的事)而去做某事", "english": "stop to do sth.", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "停止(近come to an end)", "english": "come to a stop", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "使…停止(近put an end to sth.)", "english": "bring sth. to a stop", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "v.贮存，贮藏 n.[C]贮存，贮藏；(美)店 n.[U]贮存，贮藏", "english": "store /stɔ:/", "type": "单词", "keyWords": [] },
    { "chinese": "贮存，贮藏某物(近reserve, stock)", "english": "keep/have sth. in store", "type": "短语", "keyWords": ["store"] },
    { "chinese": "n.[C]零售商；零售店店主", "english": "storekeeper /'stɔ:ki:pə/", "type": "单词", "keyWords": ["store"] }
];
qgl253_260.sort(() => Math.random() - 0.5);
