const qgl25_32 = [
    { "chinese": "中国可供出口的商品种类繁多。", "english": "Chinese commodities available for export are varied.", "type": "句子", "keyWords": ["available"] },
    { "chinese": "可取得的；可采用的", "english": "(sth.) is available to sb.", "type": "短语", "keyWords": ["available"] },
    { "chinese": "这些商品只供会员购买。", "english": "These goods are available to members only.", "type": "句子", "keyWords": ["available"] },
    { "chinese": "n. 林萌道；（南北向的）大街", "english": "avenue", "type": "单词", "keyWords": [] },
    { "chinese": "a. 中等的；平常的；平均的 n.（C）（U）平均，平均数；一般水平，中等水平；平均标准 v. 均分；算出...平均数 vi. 平均数为", "english": "average", "type": "单词", "keyWords": [] },
    { "chinese": "平均以上/以下", "english": "above/ below average", "type": "短语", "keyWords": ["average"] },
    { "chinese": "普通智力的", "english": "of average intelligence", "type": "短语", "keyWords": ["average"] },
    { "chinese": "平均，平均来说", "english": "on (the/an) average", "type": "短语", "keyWords": ["average"] },
    { "chinese": "在三月至七月期间，房地产价格平均下跌大约44%。", "english": "Property prices fell on average by about 44 per cent between March and July.", "type": "句子", "keyWords": ["average"] },
    { "chinese": "4和6平均得5。", "english": "If you average 4 and 6, you get 5.", "type": "句子", "keyWords": ["average"] },
    { "chinese": "v. 避免（+doing...）", "english": "avoid", "type": "单词", "keyWords": [] },
    { "chinese": "a. 能避免的", "english": "avoidable", "type": "单词", "keyWords": [] },
    { "chinese": "不应有的损失", "english": "avoidable losses", "type": "短语", "keyWords": ["avoidable"] },
    { "chinese": "我不能避而不见她。", "english": "I cannot avoid seeing her.", "type": "句子", "keyWords": ["avoid"] },
    { "chinese": "尽量避免人身攻击。", "english": "Try to avoid making personal comments.", "type": "句子", "keyWords": ["avoid"] },
    { "chinese": "v. 等待（强调满怀期望地等待；暗含肯定性）（wait for）", "english": "await", "type": "单词", "keyWords": [] },
    { "chinese": "我们必须等待事态的进一步发展。", "english": "We must await further developments.", "type": "句子", "keyWords": ["await"] },
    { "chinese": "a. 醒着的；意识到的；认识到的（to）v.（awoke, awoken/awaked）唤醒；（使）觉醒（辨析见wake）", "english": "awake", "type": "单词", "keyWords": [] },
    { "chinese": "知晓，觉察", "english": "be awake to", "type": "短语", "keyWords": ["awake"] },
    { "chinese": "醒着躺在床上", "english": "lie (wide) awake in bed", "type": "短语", "keyWords": ["awake"] },
    { "chinese": "他深知危险。", "english": "He's awake to the danger.", "type": "句子", "keyWords": ["awake"] },
    { "chinese": "一个巨大的响声把孩子吵醒了。", "english": "A great noise awoke the baby.", "type": "句子", "keyWords": ["awake"] },
    { "chinese": "v.（过去式/过去分词+ed）唤醒；使意识到；使认识到（to）（辨析见wake）", "english": "awaken", "type": "单词", "keyWords": [] },
    { "chinese": "请于六点叫醒我。", "english": "Please awaken me at six.", "type": "句子", "keyWords": ["awaken"] },
    { "chinese": "唤起某人的同情心", "english": "awaken sb.'s sympathy", "type": "短语", "keyWords": ["awaken"] },
    { "chinese": "觉醒了的人民", "english": "the awakened people", "type": "短语", "keyWords": ["awaken"] },
    { "chinese": "一定要唤醒人们，让他们清楚地认识到这些化学武器的危险性。", "english": "People must be awakened to the danger of these chemical weapons.", "type": "句子", "keyWords": ["awaken"] },
    { "chinese": "vt. 授予（奖品等）；给予报酬 n.（C）奖；奖品；奖状（for sth.）", "english": "award", "type": "单词", "keyWords": [] },
    { "chinese": "授予某人某物", "english": "award sb. sth.", "type": "短语", "keyWords": ["award"] },
    { "chinese": "授奖品给某人", "english": "award a prize to sb.", "type": "短语", "keyWords": ["award"] },
    { "chinese": "授予他一等奖", "english": "award him the first prize", "type": "短语", "keyWords": ["award"] },
    { "chinese": "a. 意识到的（近conscious）", "english": "aware", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）意识；感悟能力（前可加不定词）", "english": "awareness", "type": "单词", "keyWords": [] },
    { "chinese": "文化意识", "english": "cultural awareness", "type": "短语", "keyWords": ["awareness"] },
    { "chinese": "意识到（反be unaware of...没意识到）", "english": "be/ become aware of sth./that....", "type": "短语", "keyWords": ["aware"] },
    { "chinese": "ad. 远离；向不同方向；...去掉（与v.连用，表示损失、减少、变弱、耗尽）", "english": "away", "type": "单词", "keyWords": [] },
    { "chinese": "废除（某种制度等）；干掉", "english": "do away with", "type": "短语", "keyWords": ["away"] },
    { "chinese": "放弃", "english": "give ... away", "type": "短语", "keyWords": ["away"] },
    { "chinese": "收拾好，整理好；放在一边", "english": "put/ lay .. away", "type": "短语", "keyWords": ["away"] },
    { "chinese": "离...很远", "english": "be far away from...", "type": "短语", "keyWords": ["away"] },
    { "chinese": "别靠近火。", "english": "Keep away from the fire.", "type": "句子", "keyWords": ["away"] },
    { "chinese": "声音逐渐消逝了。", "english": "The sounds died away.", "type": "句子", "keyWords": ["away"] },
    { "chinese": "a. [口]非常的；糟透了的；可怕的；不舒服的 *awe n.（U）/v.（使）敬畏", "english": "awful", "type": "单词", "keyWords": [] },
    { "chinese": "a. 笨拙的；难对付的，使用不便的；尴尬的", "english": "awkward", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）尴尬，不便", "english": "awkwardness", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 尴尬地", "english": "awkwardly", "type": "单词", "keyWords": [] },
    { "chinese": "觉得局促不安，真尴尬，真别扭", "english": "feel awkward", "type": "短语", "keyWords": ["awkward"] },
    { "chinese": "难对付的顾客", "english": "awkward customer", "type": "短语", "keyWords": ["awkward"] },
    { "chinese": "处境困难", "english": "be in an awkward situation", "type": "短语", "keyWords": ["awkward"] },
    { "chinese": "n.（C）婴孩", "english": "baby", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）（代人临时）照看婴儿的人", "english": "baby-sitter", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）单身汉；学士", "english": "bachelor", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）背部；背面；后部，后面 a. 后面的；背后的；向后动的 ad. 向后；回；往回 v. 给...做后援，支持；倒（车等）；（使）倒/后退", "english": "back", "type": "单词", "keyWords": [] },
    { "chinese": "房屋背后", "english": "at the back of a house", "type": "短语", "keyWords": ["back"] },
    { "chinese": "仰卧", "english": "lie on one's back", "type": "短语", "keyWords": ["back"] },
    { "chinese": "偏僻街道", "english": "a back street", "type": "短语", "keyWords": ["back"] },
    { "chinese": "后门", "english": "a back door", "type": "短语", "keyWords": ["back"] },
    { "chinese": "逆流", "english": "a back current", "type": "短语", "keyWords": ["back"] },
    { "chinese": "来来回回", "english": "back and forth", "type": "短语", "keyWords": ["back"] },
    { "chinese": "隐瞒真相", "english": "keep back the truth", "type": "短语", "keyWords": ["back"] },
    { "chinese": "回顾", "english": "look back to/ on", "type": "短语", "keyWords": ["back"] },
    { "chinese": "在某人背后，背着某人", "english": "behind one's back", "type": "短语", "keyWords": ["back"] },
    { "chinese": "别过脸去不理；背弃，抛弃", "english": "turn one's back on/ upon", "type": "短语", "keyWords": ["back"] },
    { "chinese": "在我来的中国/家乡情况也是如此。", "english": "It's the same back in China/ in my hometown.", "type": "句子", "keyWords": ["back"] },
    { "chinese": "阻止向前；忍住；扣下；隐瞒", "english": "keep (sth.) back", "type": "短语", "keyWords": ["back"] },
    { "chinese": "支持...；备份（文件等）", "english": "back...up", "type": "短语", "keyWords": ["back"] },
    { "chinese": "把车倒入车库", "english": "back the car into the garage", "type": "短语", "keyWords": ["back"] },
    { "chinese": "a. 非常辛劳的（工作）", "english": "backbreaking (work)", "type": "短语", "keyWords": ["back"] },
    { "chinese": "n.（C）背景；隐蔽的（不引人注目的）地位；幕后", "english": "background", "type": "单词", "keyWords": [] },
    { "chinese": "她在艺术上的阅历让人印象深刻。", "english": "Her background in the arts is impressive.", "type": "句子", "keyWords": ["background"] },
    { "chinese": "a. 向后的；落后的 ad. 向后", "english": "backward", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 向后；倒逆", "english": "backwards", "type": "单词", "keyWords": [] },
    { "chinese": "n.（pl）细菌（单bacterium）", "english": "bacteria", "type": "单词", "keyWords": [] },
    { "chinese": "a. 细菌的", "english": "bacterial", "type": "单词", "keyWords": [] },
    { "chinese": "a. 坏的；腐败的；臭的；不道德的；有害的", "english": "bad", "type": "单词", "keyWords": [] },
    { "chinese": "剧痛", "english": "bad pains", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "越来越坏，每况愈下", "english": "go from bad to worse", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "不善于", "english": "be bad at...", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "对...是有害的；对...不好", "english": "be bad for...", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "为...感到懊悔，为...感到遗憾", "english": "feel bad about", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "那太糟了。/那太可惜了。/那真过意不去。", "english": "That's too bad.", "type": "句子", "keyWords": ["bad"] },
    { "chinese": "ad. 严重地；厉害地 a. [口]健康状况不好的；有病的；情绪低落的", "english": "badly", "type": "单词", "keyWords": [] },
    { "chinese": "他的脚伤得厉害。", "english": "His foot was badly hurt.", "type": "句子", "keyWords": ["badly"] },
    { "chinese": "n.（U）羽毛球运动", "english": "badminton", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）钱包；袋；袋状物，书包", "english": "bag", "type": "单词", "keyWords": [] },
    { "chinese": "泄露机密（无意）", "english": "let the cat out of the bag", "type": "短语", "keyWords": ["bag"] },
    { "chinese": "a. 宽松的；宽松下垂的", "english": "baggy", "type": "单词", "keyWords": [] },
    { "chinese": "肥大的裤子", "english": "baggy trousers", "type": "短语", "keyWords": ["baggy"] },
    { "chinese": "n.（U）[美]行李 [英]luggage", "english": "baggage", "type": "单词", "keyWords": [] },
    { "chinese": "v. 烘烤", "english": "bake", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）面包店（见-ery）", "english": "bakery", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）平衡（C）天平（=scales）；[商]收支差额；结存（常用单数形式）v. 使均等，使平衡；权衡", "english": "balance", "type": "单词", "keyWords": [] },
    { "chinese": "身体失去平衡，摔倒；慌乱", "english": "lose one's balance", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "天平；秤", "english": "a pair of balances", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "保持（身体）平衡", "english": "keep one's balance", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "均衡的饮食", "english": "a balanced diet", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "保持自然平衡", "english": "keep the balance of nature", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "使收支平衡；结账", "english": "balance accounts", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "贸易顺/逆差", "english": "a favorable/ an unfavorable balance of trade", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "支付结欠的50元", "english": "pay a balance of 50 yuan", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "银行里有结存50元", "english": "have a balance of 50 yuan in the bank", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "n.（C）露台，阳台；（戏院）楼厅", "english": "balcony", "type": "单词", "keyWords": [] },
    { "chinese": "a. 秃（头）的；无毛的；无叶的；无树的", "english": "bald", "type": "单词", "keyWords": [] },
    { "chinese": "秃顶", "english": "go bald", "type": "短语", "keyWords": ["bald"] },
    { "chinese": "n.（C）（盛大且正式的）舞会；球", "english": "ball", "type": "单词", "keyWords": [] },
    { "chinese": "化装舞会", "english": "a fancy ball", "type": "短语", "keyWords": ["ball"] },
    { "chinese": "n.（U）芭蕾舞（C）芭蕾舞剧", "english": "ballet", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）气球", "english": "balloon", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）竹；竹子", "english": "bamboo", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）竹笋", "english": "bamboo shoot", "type": "短语", "keyWords": ["bamboo"] },
    { "chinese": "v. 禁止；取缔；查禁 n.（C）禁止，禁令", "english": "ban", "type": "单词", "keyWords": [] },
    { "chinese": "禁止他销售烟（近forbid sb. to do sth. forbid doing sth.禁止某人做某事）", "english": "ban/ prohibit him from selling cigarettes", "type": "短语", "keyWords": ["ban"] },
    { "chinese": "禁止...", "english": "place/ put ... under a ban", "type": "短语", "keyWords": ["ban"] },
    { "chinese": "被禁止", "english": "be under a ban", "type": "短语", "keyWords": ["ban"] },
    { "chinese": "n.（C）香蕉", "english": "banana", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）乐队；一帮，一伙，一群；带状物；带子", "english": "band", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）绷带 v. 用绷带扎缚", "english": "bandage", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）银行；岸", "english": "bank", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）银行家", "english": "banker", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）银行业", "english": "banking", "type": "单词", "keyWords": [] },
    { "chinese": "a. 破产了的 n.（C）破产者 v. 使破产", "english": "bankrupt", "type": "单词", "keyWords": [] },
    { "chinese": "破产", "english": "go bankrupt", "type": "短语", "keyWords": ["bankrupt"] },
    { "chinese": "n.（C）棒，杆；闩；栅栏；酒吧间；售酒、食物或饮料的柜台 vt. 阻挡，拦住", "english": "bar", "type": "单词", "keyWords": [] },
    { "chinese": "一块肥皂", "english": "a bar of soap", "type": "短语", "keyWords": ["bar"] },
    { "chinese": "快餐店，小吃店", "english": "a snack bar", "type": "短语", "keyWords": ["bar"] },
    { "chinese": "结果被关在监狱/禁闭室中", "english": "end up behind (the) bars", "type": "短语", "keyWords": ["bar"] },
    { "chinese": "把他关起来", "english": "bar him in (=keep him in)", "type": "短语", "keyWords": ["bar"] },
    { "chinese": "n.（C）[美]（吃烧烤的）野外大宴会，户外烤肉餐；野餐烤肉架 v.（尤指户外）烤（肉类）", "english": "barbecue", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）理发师", "english": "barber", "type": "单词", "keyWords": [] },
    { "chinese": "去理发店", "english": "go to the barber's", "type": "短语", "keyWords": ["barber"] },
    { "chinese": "a. 无遮盖的，赤裸的；光秃的；极少的，勉勉强强的，刚刚够的", "english": "bare", "type": "单词", "keyWords": [] },
    { "chinese": "赤手空拳", "english": "bare hands", "type": "短语", "keyWords": ["bare"] },
    { "chinese": "光秃秃的树", "english": "bare trees", "type": "短语", "keyWords": ["bare"] },
    { "chinese": "光着脚的", "english": "bare-footed", "type": "短语", "keyWords": ["bare"] },
    { "chinese": "光着头的", "english": "bare-headed", "type": "短语", "keyWords": ["bare"] },
    { "chinese": "ad. 几乎不；刚刚，勉强", "english": "barely", "type": "单词", "keyWords": [] },
    { "chinese": "他好不容易才退了出来。", "english": "He barely escaped.", "type": "句子", "keyWords": ["barely"] },
    { "chinese": "刚..就....（近be about to...when...正要...这时...）", "english": "barely/scarcely...when...", "type": "短语", "keyWords": ["barely"] },
    { "chinese": "他刚到又得走了。", "english": "Barely had he arrived when he had to leave again.", "type": "句子", "keyWords": ["barely"] },
    { "chinese": "n.（C）交易，买卖；特价商品，便宜货；（通过讨价还价）成交的商品 vi. 谈判；讲价；[口]讨价还价", "english": "bargain", "type": "单词", "keyWords": [] },
    { "chinese": "买得不合算/合算", "english": "a bad/ good bargain", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "买便宜货", "english": "buy a bargain", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "（非正式）真便宜。", "english": "It's a real bargain.", "type": "句子", "keyWords": ["bargain"] },
    { "chinese": "特价日", "english": "a bargain day", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "那就这样定了。", "english": "It's a bargain. (=I agree.)", "type": "句子", "keyWords": ["bargain"] },
    { "chinese": "讨价还价", "english": "bargain over the price", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "和汤姆就鞋子讨价还价", "english": "bargain/ make a bargain with Tom about the shoes", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "n.（U）树皮（C）（狗、狐等）吠声，叫声 v.（狗、狐等）吠，叫 v. 厉声叫喊出", "english": "bark", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）障碍（物）；栅栏", "english": "barrier", "type": "单词", "keyWords": [] },
    { "chinese": "进步的障碍", "english": "a barrier to progress", "type": "短语", "keyWords": ["barrier"] },
    { "chinese": "n.（C）基，底；（纪念碑等的）底座；基地；基础 v. 把..基于；把基地设在", "english": "base", "type": "单词", "keyWords": [] },
    { "chinese": "空军基地", "english": "an air base", "type": "短语", "keyWords": ["base"] },
    { "chinese": "基于，以...为基础", "english": "base...on...", "type": "短语", "keyWords": ["base"] },
    { "chinese": "纪念碑基部/底座", "english": "the base of the monument", "type": "短语", "keyWords": ["base"] },
    { "chinese": "以事实作论辩根据", "english": "base one's arguments upon facts", "type": "短语", "keyWords": ["base"] },
    { "chinese": "该影片改编自D.H.劳伦斯的小说。", "english": "It's a film based on a novel by D. H. Lawrance.", "type": "句子", "keyWords": ["base"] },
    { "chinese": "n.（C）棒球（U）棒球运动", "english": "baseball", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）地下室；地下楼层", "english": "basement", "type": "单词", "keyWords": [] },
    { "chinese": "a. 基础的，基本的，根本的", "english": "basic", "type": "单词", "keyWords": [] },
    { "chinese": "基础工业", "english": "basic industry", "type": "短语", "keyWords": ["basic"] },
    { "chinese": "基础英语", "english": "basic English", "type": "短语", "keyWords": ["basic"] },
    { "chinese": "ad. 基本上，主要地", "english": "basically", "type": "单词", "keyWords": [] },
    { "chinese": "基本原理", "english": "a basic principle", "type": "短语", "keyWords": ["basic"] },
    { "chinese": "n.（C）盆；洗脸盆；盆地；*流域", "english": "basin", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）（pl.bases）基础（辨析见base）；根据；（fig.）前提", "english": "basis", "type": "单词", "keyWords": [] },
    { "chinese": "论据", "english": "the basis of argument", "type": "短语", "keyWords": ["basis"] },
    { "chinese": "在...基础上；根据", "english": "on the basis of", "type": "短语", "keyWords": ["basis"] },
    { "chinese": "评估标准", "english": "the basis of assessment", "type": "短语", "keyWords": ["basis"] },
    { "chinese": "根据一次测验来预测结果可靠吗？", "english": "Is it safe to predict the result on the basis of one test?", "type": "句子", "keyWords": ["basis"] },
    { "chinese": "n.（C）篮子；笼，篓，筐", "english": "basket", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）篮球（U）篮球运动", "english": "basketball", "type": "单词", "keyWords": [] },
    { "chinese": "v. 打，击；击球 n.（C）蝙蝠；（棒球等的）球棒，（乒乓球、网球等的）球拍", "english": "bat", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）洗澡；浴缸；澡盆；浴室", "english": "bath", "type": "单词", "keyWords": [] },
    { "chinese": "日光浴", "english": "sun bath", "type": "短语", "keyWords": ["bath"] },
    { "chinese": "vi. 游泳；洗澡 v. 把..浸泡在液体中；使沐浴", "english": "bathe", "type": "单词", "keyWords": [] },
    { "chinese": "他满脸是汗/泪流满面。", "english": "His face was bathed in sweat/ tears.", "type": "句子", "keyWords": ["bathe"] },
    { "chinese": "沐浴在日光中", "english": "be bathed in the sun", "type": "短语", "keyWords": ["bathe"] },
    { "chinese": "游泳衣/帽", "english": "bathing suit/ dress/ cap", "type": "短语", "keyWords": ["bathe"] },
    { "chinese": "n.（C）浴室；盥洗室", "english": "bathroom", "type": "单词", "keyWords": [] },
    { "chinese": "v. 连续地猛打/捶/捣", "english": "batter", "type": "单词", "keyWords": [] },
    { "chinese": "严重撞坏了的汽车", "english": "a badly battered car", "type": "短语", "keyWords": ["batter"] },
    { "chinese": "n.（C）电池（组）", "english": "battery", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）战役，战斗，搏斗 v. 和..作战，和...斗争", "english": "battle", "type": "单词", "keyWords": [] },
    { "chinese": "战舰", "english": "battle ship", "type": "短语", "keyWords": ["battle"] },
    { "chinese": "战场", "english": "battle field", "type": "短语", "keyWords": ["battle"] },
    { "chinese": "争取平等权利/反对污染的斗争", "english": "a battle for equal rights/ against pollution", "type": "短语", "keyWords": ["battle"] },
    { "chinese": "n.（C）湾（比gulf小），海湾（常为河流的出海口）", "english": "bay", "type": "单词", "keyWords": [] },
    { "chinese": "公元前（=Before Christ的缩写）", "english": "B.C.=BC", "type": "短语", "keyWords": [] },
    { "chinese": "公元前44年", "english": "44 BC", "type": "短语", "keyWords": [] },
    { "chinese": "v. 是", "english": "be", "type": "单词", "keyWords": [] },
    { "chinese": "以...而出名", "english": "be famous for", "type": "短语", "keyWords": ["be"] },
    { "chinese": "对...满意", "english": "be pleased with", "type": "短语", "keyWords": ["be"] },
    { "chinese": "习惯于", "english": "be used/ accustomed to", "type": "短语", "keyWords": ["be"] },
    { "chinese": "目前", "english": "for the time being", "type": "短语", "keyWords": ["be"] },
    { "chinese": "将要，应该（表示约定、计划、职责、义务、愿望、可能、命运等）", "english": "be to do sth.", "type": "短语", "keyWords": ["be"] },
    { "chinese": "新书即将出版。", "english": "The new book is to come.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "他们预定在五月结婚。", "english": "They are to be married in May.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "你不该做那件事。（相当于must/ have to/ should）", "english": "You are not to do that.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "听不到任何声音。（相当于can/ may ）", "english": "Not a sound was to be heard.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "他此后就再没有和妻子见面了。（多用过去式）", "english": "He was never to see his wife again.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "如果要出席宴会，你会穿什么？", "english": "If you are to attend the banquet, what will you wear?", "type": "句子", "keyWords": ["be"] },
    { "chinese": "n.（C）海滨；海滩；湖滨；江滨", "english": "beach", "type": "单词", "keyWords": [] },
    { "chinese": "海水浴场", "english": "a bathing beach", "type": "短语", "keyWords": ["beach"] },
    { "chinese": "在海滩上", "english": "on the beach", "type": "短语", "keyWords": ["beach"] },
    { "chinese": "n.（C）豆；蚕豆；菜豆属植物", "english": "bean", "type": "单词", "keyWords": [] },
    { "chinese": "刀豆", "english": "sword bean", "type": "短语", "keyWords": ["bean"] },
    { "chinese": "豇豆", "english": "string bean", "type": "短语", "keyWords": ["bean"] },
    { "chinese": "大豆", "english": "soy(a) bean", "type": "短语", "keyWords": ["bean"] },
    { "chinese": "n.（U）豆腐", "english": "bean curd", "type": "短语", "keyWords": ["bean"] },
    { "chinese": "n.（C）熊 vt.（bore, bore）忍受；标有，刻有；承受；怀有；（bore, born）生育", "english": "bear", "type": "单词", "keyWords": [] },
    { "chinese": "a. 难堪的，不能忍受的", "english": "unbearable", "type": "单词", "keyWords": ["bear"] },
    { "chinese": "我受不了了。", "english": "This is more than I can bear.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "这布料很耐洗。", "english": "This cloth will bear washing.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "她脸上有泪痕。", "english": "Her face bears the marks/ signs of tears.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "这封信没注明日期。", "english": "The letter bears no date.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "这棵树不结果。", "english": "This tree has borne no fruit.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "承受上面楼层的重量", "english": "bear the weight of the upper floors", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "我心里谁也不恨。", "english": "I bear no hatred towards anybody./I bear hatred against no man.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "承担...的费用/责任", "english": "bear the cost of/ responsibility for...", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "你须负起养育孩子的责任。", "english": "You have to bear the responsibility for bringing up your child.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "受不了", "english": "can't bear (sb.) doing sth.", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "生来平等", "english": "be born equal", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "牢记...", "english": "bear/ keep sth. in mind; bear/ keep in mind that...", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "n.（C）胡须", "english": "beard", "type": "单词", "keyWords": [] },
    { "chinese": "下巴上留着胡子", "english": "wear/ grow a beard", "type": "短语", "keyWords": ["beard"] },
    { "chinese": "有胡须的人", "english": "a bearded man", "type": "短语", "keyWords": ["beard"] },
    { "chinese": "n.（C）野兽；走兽；*凶残的人；举止粗野的人", "english": "beast", "type": "单词", "keyWords": [] },
    { "chinese": "v. 连续打，击；打败 vi.（心脏）跳动；连打 n.（C）跳动；（音乐）拍子，节拍", "english": "beat", "type": "单词", "keyWords": [] },
    { "chinese": "把他打晕", "english": "beat him unconscious", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "击鼓", "english": "beat a drum", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "把人打得青一块紫一块", "english": "beat a man black and blue", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "在象棋上打败某人", "english": "beat sb. at chess", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "波浪拍岸。", "english": "The waves were beating against the shore.", "type": "句子", "keyWords": ["beat"] },
    { "chinese": "拨打草丛搜索猎物；旁敲侧击地刺探人意", "english": "beat about the bush", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "狠狠打了他一顿", "english": "give him a good beating", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "用脚打拍子", "english": "beat time with his foot", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "被打了一顿", "english": "get a beating", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "走成一条路", "english": "beat a path", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "a. 美丽的；出色的，极好的", "english": "beautiful", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 美丽地；出色地；完美地", "english": "beautifully", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）美丽（C）美人；美景", "english": "beauty", "type": "单词", "keyWords": [] },
    { "chinese": "美貌只是外表。/人不可以貌相。", "english": "Beauty is but skin-deep.", "type": "句子", "keyWords": ["beauty"] },
    { "chinese": "v. 美化", "english": "beautify", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）美化；装饰", "english": "beautification", "type": "单词", "keyWords": [] },
    { "chinese": "conj. 因为", "english": "because", "type": "单词", "keyWords": [] },
    { "chinese": "因为，由于", "english": "because of", "type": "短语", "keyWords": ["because"] },
    { "chinese": "是因为·..才...", "english": "It is because..that...", "type": "短语", "keyWords": ["because"] },
    { "chinese": "不因...便...", "english": "not...because...", "type": "短语", "keyWords": ["because"] },
    { "chinese": "他并不是因为受到邀请才来的。", "english": "He didn't come because he was invited.", "type": "句子", "keyWords": ["because"] },
    { "chinese": "vi. 变成，开始变得", "english": "become", "type": "单词", "keyWords": [] },
    { "chinese": "发生；降临（近happen to）", "english": "become of", "type": "短语", "keyWords": ["become"] },
    { "chinese": "他/他的书怎么了？他/他的书下落如何？", "english": "What has become of him/his book?", "type": "句子", "keyWords": ["become"] },
    { "chinese": "n.（C）床；*河/海床；地基", "english": "bed", "type": "单词", "keyWords": [] },
    { "chinese": "单/双人床", "english": "a single/ double bed", "type": "短语", "keyWords": ["bed"] },
    { "chinese": "收拾床铺；铺床", "english": "make the bed", "type": "短语", "keyWords": ["bed"] },
    { "chinese": "让（孩子等）睡觉", "english": "put (the child) to bed", "type": "短语", "keyWords": ["bed"] },
    { "chinese": "花坛/海床", "english": "flower/sea bed", "type": "短语", "keyWords": ["bed"] },
    { "chinese": "n.（C）床上用品", "english": "bedding", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）卧室", "english": "bedroom", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）就寝时间 a. 适用于临睡前的", "english": "bedtime", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）蜜蜂", "english": "bee", "type": "单词", "keyWords": [] },
    { "chinese": "n.（多用作不可数）牛肉", "english": "beef", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）啤酒（C）某种啤酒；一杯或一瓶啤酒", "english": "beer", "type": "单词", "keyWords": [] },
    { "chinese": "两杯啤酒", "english": "two beers=two glasses of beer", "type": "短语", "keyWords": ["beer"] },
    { "chinese": "prep. 在...以前；当着..的面 conj. 在...之前 ad. 在前，以前", "english": "before", "type": "单词", "keyWords": [] },
    { "chinese": "我还没来得及插话他就冲了出去。（不等...就....）", "english": "Before I could get in a word, he had rushed out.", "type": "句子", "keyWords": ["before"] },
    { "chinese": "还要过很长时间我们才能再见面。", "english": "It'll be a long time before we meet again.", "type": "句子", "keyWords": ["before"] },
    { "chinese": '不久就...（对比It is...since+过去式，"...已发生了一段时间")', "english": "It wasn't long before...", "type": "短语", "keyWords": ["before"] },
    { "chinese": "好久以前", "english": "long before/ ago", "type": "短语", "keyWords": ["before"] },
    { "chinese": "不久", "english": "before long", "type": "短语", "keyWords": ["before"] },
    { "chinese": "当着某人的面", "english": "before sb.'s very eyes", "type": "短语", "keyWords": ["before"] },
    { "chinese": "前天晚上", "english": "the night before last", "type": "短语", "keyWords": ["before"] },
    { "chinese": "本末倒置。", "english": "Put the cart before the horse.", "type": "句子", "keyWords": ["before"] },
    { "chinese": "骄者必败。", "english": "Pride goes before a fall.", "type": "句子", "keyWords": ["before"] },
    { "chinese": "三思而后行。", "english": "Look before you leap.", "type": "句子", "keyWords": ["before"] },
    { "chinese": "ad. 事先，预先（近ahead of time, in advance）", "english": "beforehand", "type": "单词", "keyWords": [] },
    { "chinese": "vt./vi. 乞求；恳求", "english": "beg", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）乞丐（比较liar, scholar, burglar）", "english": "beggar", "type": "单词", "keyWords": [] },
    { "chinese": "讨钱", "english": "beg (sb.) for money", "type": "短语", "keyWords": ["beg"] },
    { "chinese": "恳求某人做某事", "english": "beg sb. to do sth.", "type": "短语", "keyWords": ["beg"] },
    { "chinese": "（对不起）请再说一遍=pardon (me)", "english": "beg your pardon", "type": "短语", "keyWords": ["beg"] },
    { "chinese": "v. 开始", "english": "begin", "type": "单词", "keyWords": [] },
    { "chinese": "由...开始（...）反end (...) with...", "english": "begin (...) with...", "type": "短语", "keyWords": ["begin"] },
    { "chinese": "认识从实践开始。", "english": "Knowledge begins with practice.", "type": "句子", "keyWords": ["begin"] },
    { "chinese": "我们首先参观大钟寺。", "english": "We began our tour with the Great Bell Temple.", "type": "句子", "keyWords": ["begin"] },
    { "chinese": "首先；第一", "english": "to begin with", "type": "短语", "keyWords": ["begin"] },
    { "chinese": "我们是去不成了--首先是天气太冷，此外，我们没有钱。", "english": "We can't possibly go - to begin with, it's too cold, and besides, we have no money.", "type": "句子", "keyWords": ["begin"] },
    { "chinese": "良好的开端是成功的一半。", "english": "Well begun is half done.", "type": "句子", "keyWords": ["begin"] },
    { "chinese": "n.（C）（U）开始，开端", "english": "beginning", "type": "单词", "keyWords": [] },
    { "chinese": "在...一开始，在...初；从...开始（反at the end of）", "english": "at the beginning of...", "type": "短语", "keyWords": ["beginning"] },
    { "chinese": "从头至尾", "english": "from beginning to end", "type": "短语", "keyWords": ["beginning"] },
    { "chinese": "从头开始", "english": "from the (very) beginning", "type": "短语", "keyWords": ["beginning"] },
    { "chinese": "n. 利益；方面；支持", "english": "behalf", "type": "单词", "keyWords": [] },
    { "chinese": "作为...的代表；代表；为了...的利益", "english": "on behalf of...", "type": "短语", "keyWords": ["behalf"] },
    { "chinese": "vi. 举止；表现 v. 使举止得当，使守规矩（后接反身代词）", "english": "behave", "type": "单词", "keyWords": [] },
    { "chinese": "表现好", "english": "behave well", "type": "短语", "keyWords": ["behave"] },
    { "chinese": "表现不好/好的", "english": "badly/well-behaved", "type": "短语", "keyWords": ["behave"] },
    { "chinese": "规矩点！", "english": "Behave yourself!", "type": "句子", "keyWords": ["behave"] },
    { "chinese": "n.（U）行为；举止；表现；态度", "english": "behaviour", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 在...后面 ad. 在后；向后；在幕后，在背后", "english": "behind", "type": "单词", "keyWords": [] },
    { "chinese": "误时", "english": "behind time/ behind schedule", "type": "短语", "keyWords": ["behind"] },
    { "chinese": "留在后头；忘记拿", "english": "leave sb./sth. behind", "type": "短语", "keyWords": ["behind"] },
    { "chinese": "落在时代后面的", "english": "behind the times", "type": "短语", "keyWords": ["behind"] },
    { "chinese": "里头还有情况。/还有内情。", "english": "There's something behind the story/it/him.", "type": "句子", "keyWords": ["behind"] },
    { "chinese": "英语成绩比别人差", "english": "be behind the others in English", "type": "短语", "keyWords": ["behind"] },
    { "chinese": "汽车驾驶人，司机", "english": "the person behind the wheel of a car", "type": "短语", "keyWords": ["behind"] },
    { "chinese": "留下不走", "english": "stay behind", "type": "短语", "keyWords": ["behind"] },
    { "chinese": "落后；落伍", "english": "fall/ lag behind", "type": "短语", "keyWords": ["behind"] },
    { "chinese": "n.（U）存在（C）人；生物", "english": "being", "type": "单词", "keyWords": [] },
    { "chinese": "暂时；一时；临时", "english": "for the time being", "type": "短语", "keyWords": ["being"] },
    { "chinese": "使产出，使形成", "english": "bring...into being", "type": "短语", "keyWords": ["being"] },
    { "chinese": "人", "english": "(a) human being(s)", "type": "短语", "keyWords": ["being"] },
    { "chinese": "发生，诞生，成立", "english": "come into being", "type": "短语", "keyWords": ["being"] },
    { "chinese": "n.（U）相信；信念（C）信仰；*信条（beliefs of the Christian Church）", "english": "belief(s)", "type": "单词", "keyWords": [] },
    { "chinese": "信得过", "english": "have belief in (=believe in)", "type": "短语", "keyWords": ["belief"] },
    { "chinese": "难以置信；想象以外地", "english": "beyond belief", "type": "短语", "keyWords": ["belief"] },
    { "chinese": "我相信；在我看来", "english": "My belief is that...", "type": "句子", "keyWords": ["belief"] },
    { "chinese": "v. 相信；认为", "english": "believe", "type": "单词", "keyWords": [] },
    { "chinese": "信不信由你", "english": "believe it or not", "type": "短语", "keyWords": ["believe"] },
    { "chinese": "我想我不认识他。", "english": "I don't believe I know him.", "type": "句子", "keyWords": ["believe"] },
    { "chinese": "认为某人是/已经...（过）", "english": "believe/ think/ consider sb. to be/ to have done", "type": "短语", "keyWords": ["believe"] },
    { "chinese": "我认为他是诚实的。", "english": "I believe him (to be) honest.", "type": "句子", "keyWords": ["believe"] },
    { "chinese": "据信...", "english": "It is believed that..", "type": "短语", "keyWords": ["believe"] },
    { "chinese": "相信上帝", "english": "believe in God", "type": "短语", "keyWords": ["believe"] },
    { "chinese": "假装他不落后", "english": "make believe that he didn't fall behind", "type": "短语", "keyWords": ["believe"] },
    { "chinese": "我们信任医生。", "english": "We believe in doctors.", "type": "句子", "keyWords": ["believe"] },
    { "chinese": "眼见为实。", "english": "Seeing is believing.", "type": "句子", "keyWords": ["believe"] },
    { "chinese": "n.（C）铃，钟；钟声；铃声；钟状物", "english": "bell", "type": "单词", "keyWords": [] },
    { "chinese": "打钟，按铃", "english": "ring the bell", "type": "短语", "keyWords": ["bell"] },
    { "chinese": "铃响了。（倒装句）", "english": "There goes the bell.", "type": "句子", "keyWords": ["bell"] },
    { "chinese": "vi.（常与介词to连用）属；附属；应归入（某）部类", "english": "belong", "type": "单词", "keyWords": [] },
    { "chinese": "属于（前面不能加be，一般不用于进行时）", "english": "belong to", "type": "短语", "keyWords": ["belong"] },
    { "chinese": "这本字典属于我。", "english": "The dictionary belongs to me.", "type": "句子", "keyWords": ["belong"] },
    { "chinese": "这东西原来放在哪里就放哪里。", "english": "Put it where it belongs.", "type": "句子", "keyWords": ["belong"] },
    { "chinese": "他是本地人。", "english": "He belongs here.", "type": "句子", "keyWords": ["belong"] },
    { "chinese": "n.（pl）所有物；财产；行李；附属品，附件", "english": "belongings", "type": "单词", "keyWords": [] },
    { "chinese": "a. 亲爱的，被热爱的（用作修饰语）", "english": "beloved", "type": "单词", "keyWords": [] },
    { "chinese": "我们敬爱的领袖", "english": "our beloved leader", "type": "短语", "keyWords": ["beloved"] },
    { "chinese": "ad. 在下面 prep. 在...之下；低于；劣于 n.（U）下面", "english": "below", "type": "单词", "keyWords": [] },
    { "chinese": "读下面的例子", "english": "read the examples below", "type": "短语", "keyWords": ["below"] },
    { "chinese": "平均水平以下", "english": "below the average", "type": "短语", "keyWords": ["below"] },
    { "chinese": "见下文", "english": "see below", "type": "短语", "keyWords": ["below"] },
    { "chinese": "自下", "english": "from below", "type": "短语", "keyWords": ["below"] },
    { "chinese": "n.（C）带子；皮带；腰带；绶带；线条；带状物", "english": "belt", "type": "单词", "keyWords": [] },
    { "chinese": "束紧裤带", "english": "tighten the belt", "type": "短语", "keyWords": ["belt"] },
    { "chinese": "安全带", "english": "safety belt", "type": "短语", "keyWords": ["belt"] },
    { "chinese": "产棉地带", "english": "the cotton belt", "type": "短语", "keyWords": ["belt"] },
    { "chinese": "n.（C）长凳；长椅", "english": "bench", "type": "单词", "keyWords": [] },
    { "chinese": "v.（bent,bent）使弯曲 vi. 变弯曲；弯腰；做出让步 n.（C）弯曲部分；弯角；（道路或河流的）转弯处", "english": "bend", "type": "单词", "keyWords": [] },
    { "chinese": "弯下身来", "english": "bend down", "type": "短语", "keyWords": ["bend"] },
    { "chinese": "低着头站着", "english": "stand with his head bent", "type": "短语", "keyWords": ["bend"] },
    { "chinese": "弯腰；身子贴近；伏在...上", "english": "bend over", "type": "短语", "keyWords": ["bend"] },
    { "chinese": "路上的转弯处", "english": "a bend in the road", "type": "短语", "keyWords": ["bend"] },
    { "chinese": "他埋头读书。", "english": "His head was bent over his book.", "type": "句子", "keyWords": ["bend"] },
    { "chinese": "枝条因果实的重压而下垂。", "english": "The branches were bending with the weight of the fruit.", "type": "句子", "keyWords": ["bend"] },
    { "chinese": "ad. 在...之下（面）prep. 在..之下（面）；往...下面；低于", "english": "beneath", "type": "单词", "keyWords": [] },
    { "chinese": "同住一屋", "english": "live beneath the same roof", "type": "短语", "keyWords": ["beneath"] },
    { "chinese": "大地被厚厚的白雪覆盖。", "english": "The earth lay beneath a blanket of snow.", "type": "句子", "keyWords": ["beneath"] },
    { "chinese": "a. 有益的 (比较 substance →substantial influence →influential )", "english": "beneficial", "type": "单词", "keyWords": [] },
    { "chinese": "对...有益", "english": "be beneficial to sth./sb.=be of benefit to sth./sb.", "type": "短语", "keyWords": ["beneficial"] },
    { "chinese": "体育运动有益于增进我们的体质。", "english": "Sports are beneficial to building our bodies.", "type": "句子", "keyWords": ["beneficial"] },
    { "chinese": "v. 有益于 vi. 得益，受益（from） n.（C）（U）利益，恩惠；救济金（C）义演；义赛", "english": "benefit", "type": "单词", "keyWords": [] },
    { "chinese": "网球义赛", "english": "a tennis benefit", "type": "短语", "keyWords": ["benefit"] },
    { "chinese": "这使人民受益。", "english": "This benefits the people.", "type": "句子", "keyWords": ["benefit"] },
    { "chinese": "受益，获益", "english": "benefit from", "type": "短语", "keyWords": ["benefit"] },
    { "chinese": "谁最有可能因老夫人去世而获益？", "english": "Who's most likely to benefit from the old lady's death?", "type": "句子", "keyWords": ["benefit"] },
    { "chinese": "对某人很有帮助", "english": "be of great benefit/ help/ use/ value/ service to sb.", "type": "短语", "keyWords": ["benefit"] },
    { "chinese": "新规章对我们大家都会大有好处。", "english": "The new regulations will be of great benefit to us all.", "type": "句子", "keyWords": ["benefit"] },
    { "chinese": "为了···好或利益", "english": "for the benefit/ good of→for the sake of→in the interest(s) of", "type": "短语", "keyWords": ["benefit"] },
    { "chinese": "他那样做是为我好吗？", "english": "Was he doing that for my benefit?", "type": "句子", "keyWords": ["benefit"] },
    { "chinese": "prep. 在...旁边", "english": "beside", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 除了...之外（还）ad. 加之，更，又，还有，而且；另外 近in addition (to sth.)", "english": "besides", "type": "单词", "keyWords": [] },
    { "chinese": "a./ad. 最好（good和well的最高级）n.（与the/sb's连用）最好的东西", "english": "best", "type": "单词", "keyWords": [] },
];
