const qgl269_276 = [
    { "chinese": "n.[C]桌子；工作台；表格", "english": "table", "type": "单词", "keyWords": [] },
    { "chinese": "在吃饭（期间）", "english": "at table", "type": "短语", "keyWords": ["table"] },
    { "chinese": "预定一桌位", "english": "book a table", "type": "短语", "keyWords": ["table"] },
    { "chinese": "摆餐具准备吃饭", "english": "lay/ set the table", "type": "短语", "keyWords": ["table"] },
    { "chinese": "乒乓", "english": "table tennis", "type": "短语", "keyWords": ["table"] },
    { "chinese": "在座的人都听到了他的话。", "english": "The whole table heard what he said.", "type": "句子", "keyWords": ["table"] },
    { "chinese": "如上表所示，误差可能会高达20%。", "english": "The error may be as much as 20%, as shown in the above table.", "type": "句子", "keyWords": ["table"] },
    { "chinese": "n.[C]药片；平板电脑", "english": "tablet", "type": "单词", "keyWords": [] },
    { "chinese": "v.品尝；vi.尝起来；有……味道(of)；n.[C](U)味，味道；喜欢；鉴赏力", "english": "taste", "type": "单词", "keyWords": [] },
    { "chinese": "adj.好吃的，可口的", "english": "tasty", "type": "单词", "keyWords": ["taste"] },
    { "chinese": "adj.无味的", "english": "tasteless", "type": "单词", "keyWords": ["taste"] },
    { "chinese": "尝一尝这种茶", "english": "have/ take a taste of this tea", "type": "短语", "keyWords": ["taste"] },
    { "chinese": "合某人的意图/口味", "english": "to one's taste", "type": "短语", "keyWords": ["taste"] },
    { "chinese": "体会幸福生活的欢乐", "english": "taste the joys of the happy life", "type": "短语", "keyWords": ["taste"] },
    { "chinese": "爱好音乐", "english": "have a taste for music", "type": "短语", "keyWords": ["taste"] },
    { "chinese": "这饮料有柠檬味儿。", "english": "The drink tastes of lemon.", "type": "句子", "keyWords": ["taste"] },
    { "chinese": "n.[C](U)税；v.对……征税", "english": "tax", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]征税", "english": "taxation", "type": "单词", "keyWords": ["tax"] },
    { "chinese": "adj.免税的", "english": "tax-free", "type": "单词", "keyWords": ["tax"] },
    { "chinese": "缴税", "english": "pay one's taxes", "type": "短语", "keyWords": ["tax"] },
    { "chinese": "免税", "english": "free of tax", "type": "短语", "keyWords": ["tax"] },
    { "chinese": "对酒类课重税", "english": "impose a heavy tax upon wines(tax wines heavily)", "type": "短语", "keyWords": ["tax"] },
    { "chinese": "n.[C]出租汽车", "english": "taxi", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]标签；标牌，铭牌", "english": "tag", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]尾巴；尾状物", "english": "tail", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]裁缝；v.剪裁，缝制（衣服）；使适应特定需要，适合(to)", "english": "tailor", "type": "单词", "keyWords": [] },
    { "chinese": "在裁缝店", "english": "at the tailor's", "type": "短语", "keyWords": ["tailor"] },
    { "chinese": "你应该量入为出。", "english": "You should tailor your spending to your income.", "type": "句子", "keyWords": ["tailor"] },
    { "chinese": "这是一本为迎合大众口味而创作的小说。", "english": "This is a novel tailored to popular taste.", "type": "句子", "keyWords": ["tailor"] },
    { "chinese": "佛靠金装，人靠衣装。", "english": "The tailor makes the man.", "type": "句子", "keyWords": ["tailor"] },
    { "chinese": "n.[C](U)才能；天资；才干；n.[C](U)人才", "english": "talent", "type": "单词", "keyWords": [] },
    { "chinese": "adj.天才的；有才干的（近gifted）", "english": "talented", "type": "单词", "keyWords": ["talent"] },
    { "chinese": "我妹妹有音乐才能。", "english": "My sister has a talent/ gift/ genius for music.", "type": "句子", "keyWords": ["talent"] },
    { "chinese": "n.[C]故事；传说；假话", "english": "tale", "type": "单词", "keyWords": [] },
    { "chinese": "神话故事", "english": "a fairy tale", "type": "短语", "keyWords": ["tale"] },
    { "chinese": "n.[C]谈话，说话，话语；商讨；n.(U)流言蜚语", "english": "talk", "type": "单词", "keyWords": [] },
    { "chinese": "adj.爱说话的；多嘴的", "english": "talkative", "type": "单词", "keyWords": ["talk"] },
    { "chinese": "和谈", "english": "peace talks", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "脱口秀", "english": "talk show", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "谈到；谈论", "english": "talk about", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "谈及，说到", "english": "talk of", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "吹牛；说大话", "english": "talk big", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "胡说八道", "english": "talk nonsense", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "顶嘴；反驳", "english": "talk back", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "背后议论某人", "english": "talk behind sb.'s back", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "说到某人/某事", "english": "talking of sb./ sth.", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "谈到运动，我最喜欢高尔夫球了。", "english": "Talking of sports, I like golf best.", "type": "句子", "keyWords": ["talk"] },
    { "chinese": "在谈话中度过了傍晚的时光", "english": "talk the evening away", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "说服某人做/不做某事", "english": "talk sb. into/ out of (doing) sth.", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "他说服了他父亲把车借给他。", "english": "He talked his father into lending him the car.", "type": "句子", "keyWords": ["talk"] },
    { "chinese": "有传闻说要破产。", "english": "There is talk of bankruptcy.", "type": "句子", "keyWords": ["talk"] },
    { "chinese": "成为镇上人们议论的话题的一部歌舞片", "english": "a musical that is the talk of the town", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "有钱能使鬼推磨。", "english": "Money talks.", "type": "句子", "keyWords": ["talk"] },
    { "chinese": "adj.（人）高的；（树、建筑物等）高大的", "english": "tall", "type": "单词", "keyWords": [] },
    { "chinese": "adj.（动物）驯化的，驯服的；温顺的；v.驯服，驯化", "english": "tame", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]温顺，驯服", "english": "tameness", "type": "单词", "keyWords": ["tame"] },
    { "chinese": "n.[C]（盛液体、气体的大容器）桶，箱；坦克", "english": "tank", "type": "单词", "keyWords": [] },
    { "chinese": "油箱", "english": "a petrol tank", "type": "短语", "keyWords": ["tank"] },
    { "chinese": "油船，油轮", "english": "tankship(= *tanker)", "type": "短语", "keyWords": ["tank"] },
    { "chinese": "v.[C]轻拍，轻叩；[美]选择；指定；n.[C]水龙头；阀门", "english": "tap", "type": "单词", "keyWords": [] },
    { "chinese": "轻拍某人的肩膀", "english": "tap sb. on the shoulder", "type": "短语", "keyWords": ["tap"] },
    { "chinese": "敲打出一种节奏", "english": "tap out a rhythm", "type": "短语", "keyWords": ["tap"] },
    { "chinese": "n.[C]磁带；带子；卷尺；胶布；v.用带子（将包裹等）捆起来", "english": "tape", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]靶子；目标；对象；v.把……作为目标；瞄准；规定……的指标", "english": "target", "type": "单词", "keyWords": [] },
    { "chinese": "达到指标；射中靶子", "english": "hit a target", "type": "短语", "keyWords": ["target"] },
    { "chinese": "未射中靶子；未完成指标", "english": "miss the target", "type": "短语", "keyWords": ["target"] },
    { "chinese": "目标客户", "english": "targeted customers", "type": "短语", "keyWords": ["target"] },
    { "chinese": "目标语言", "english": "target language", "type": "短语", "keyWords": ["target"] },
    { "chinese": "这些游戏的主要顾客是青少年。", "english": "The games are targeted on teenagers.", "type": "句子", "keyWords": ["target"] },
    { "chinese": "指标定为", "english": "be targeted for", "type": "短语", "keyWords": ["target"] },
    { "chinese": "钢产量去年指标定为六万吨。", "english": "Steel production was targeted for 60,000 tons last year.", "type": "句子", "keyWords": ["target"] },
    { "chinese": "n.[C]任务；工作", "english": "task", "type": "单词", "keyWords": [] },
    { "chinese": "分派某人一项任务", "english": "assign sb. a task", "type": "短语", "keyWords": ["task"] },
    { "chinese": "adj.技术的，工艺的", "english": "technical", "type": "单词", "keyWords": [] },
    { "chinese": "专门名词，术语", "english": "technical terms", "type": "短语", "keyWords": ["technical"] },
    { "chinese": "n.[C]技师，技术员", "english": "technician", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]技术；技能；工艺；方法", "english": "technique", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]技术", "english": "technology", "type": "单词", "keyWords": [] },
    { "chinese": "adj.技术的", "english": "technological", "type": "单词", "keyWords": ["technology"] },
    { "chinese": "科学和技术", "english": "science and technology", "type": "短语", "keyWords": ["technology"] },
    { "chinese": "n.[C]（13至19岁）少年", "english": "teenager", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]电报；电文", "english": "telegram", "type": "单词", "keyWords": [] },
    { "chinese": "发急电", "english": "send an express telegram", "type": "短语", "keyWords": ["telegram"] },
    { "chinese": "n.[C]电报机；n.[U]电报（指通讯方式）；v.发电报给", "english": "telegraph", "type": "单词", "keyWords": [] },
    { "chinese": "v.打电话给；vi.打电话，通电话；n.[C](U)电话；电话机", "english": "telephone", "type": "单词", "keyWords": [] },
    { "chinese": "通过电话", "english": "by telephone", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "接电话", "english": "answer the telephone", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "有某人的电话", "english": "be wanted on the (telephone)", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "打（某人）电话", "english": "make a telephone call (to sb.)", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "n.[C]望远镜", "english": "telescope", "type": "单词", "keyWords": [] },
    { "chinese": "用望远镜", "english": "through telescope", "type": "短语", "keyWords": ["telescope"] },
    { "chinese": "v.用电视播放", "english": "televise", "type": "单词", "keyWords": [] },
    { "chinese": "用电视直播", "english": "televise sth. live", "type": "短语", "keyWords": ["televise"] },
    { "chinese": "（略作TV）n.[U]电视（节目）；n.[C]电视机（TV set）", "english": "television", "type": "单词", "keyWords": [] },
    { "chinese": "v.教；教导；训练；讲授（侧重传授知识和技能）", "english": "teach", "type": "单词", "keyWords": [] },
    { "chinese": "教某人做某事", "english": "teach sb. to do sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "自学……", "english": "teach oneself sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "给……一个教训", "english": "teach sb. a lesson = teach a lesson to sb.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "教某人如何做某事", "english": "teach sb. how to do sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "n.[C]教师；老师；导师", "english": "teacher", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]教学；（常用pl.）教义", "english": "teaching", "type": "单词", "keyWords": ["teacher"] },
    { "chinese": "有其师必有其徒。", "english": "Like teacher, like pupil.", "type": "句子", "keyWords": ["teacher"] },
    { "chinese": "n.[C]队；组", "english": "team", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]配合，协同工作；小组作业", "english": "teamwork", "type": "单词", "keyWords": ["team"] },
    { "chinese": "他是那个队的成员吗？", "english": "Is he on that team?", "type": "句子", "keyWords": ["team"] },
    { "chinese": "n.[C]（常用pl.）眼泪；v.流泪；含泪；/teə/ v.撕，撕裂；vi.被撕破", "english": "tear", "type": "单词", "keyWords": [] },
    { "chinese": "adj.流泪的", "english": "tearful", "type": "单词", "keyWords": ["tear"] },
    { "chinese": "忍住眼泪", "english": "keep back one's tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "感动得流泪", "english": "be moved to tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "突然哭起来", "english": "burst into tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "流着泪", "english": "in tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "流泪", "english": "tears come into/ to one's eyes", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "伤心/辛酸泪", "english": "bitter tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "鳄鱼的眼泪；伪善的眼泪，假哭", "english": "crocodile tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "为他的死而假哭了一场", "english": "shed crocodile tears over his death", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "这种料子很容易（被）撕破。", "english": "This material tears easily.", "type": "句子", "keyWords": ["tear"] },
    { "chinese": "把……撕得粉碎", "english": "tear sth. into pieces(tear sth. up)", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "（互相用指甲）猛力去抓或扯，撕扯", "english": "tear at (each other with their nails)", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "拆毁（房屋等）", "english": "tear...down", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "泪眼", "english": "tearful eyes", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "v.取笑，逗恼，戏弄；挑逗", "english": "tease", "type": "单词", "keyWords": [] },
    { "chinese": "adj.技术的，工艺的", "english": "technical", "type": "单词", "keyWords": [] },
    { "chinese": "专门名词，术语", "english": "technical terms", "type": "短语", "keyWords": ["technical"] },
    { "chinese": "n.[C]技师，技术员", "english": "technician", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]技术；技能；工艺；方法", "english": "technique", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]技术", "english": "technology", "type": "单词", "keyWords": [] },
    { "chinese": "adj.技术的", "english": "technological", "type": "单词", "keyWords": ["technology"] },
    { "chinese": "科学和技术", "english": "science and technology", "type": "短语", "keyWords": ["technology"] },
    { "chinese": "n.[C]（13至19岁）少年", "english": "teenager", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]电报；电文", "english": "telegram", "type": "单词", "keyWords": [] },
    { "chinese": "发急电", "english": "send an express telegram", "type": "短语", "keyWords": ["telegram"] },
    { "chinese": "n.[C]电报机；n.[U]电报（指通讯方式）；v.发电报给", "english": "telegraph", "type": "单词", "keyWords": [] },
    { "chinese": "v.打电话给；vi.打电话，通电话；n.[C](U)电话；电话机", "english": "telephone", "type": "单词", "keyWords": [] },
    { "chinese": "通过电话", "english": "by telephone", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "接电话", "english": "answer the telephone", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "有某人的电话", "english": "be wanted on the (telephone)", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "打（某人）电话", "english": "make a telephone call (to sb.)", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "n.[C]望远镜", "english": "telescope", "type": "单词", "keyWords": [] },
    { "chinese": "用望远镜", "english": "through telescope", "type": "短语", "keyWords": ["telescope"] },
    { "chinese": "v.用电视播放", "english": "televise", "type": "单词", "keyWords": [] },
    { "chinese": "用电视直播", "english": "televise sth. live", "type": "短语", "keyWords": ["televise"] },
    { "chinese": "（略作TV）n.[U]电视（节目）；n.[C]电视机（TV set）", "english": "television", "type": "单词", "keyWords": [] },
    { "chinese": "v.教；教导；训练；讲授（侧重传授知识和技能）", "english": "teach", "type": "单词", "keyWords": [] },
    { "chinese": "教某人做某事", "english": "teach sb. to do sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "自学……", "english": "teach oneself sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "给……一个教训", "english": "teach sb. a lesson = teach a lesson to sb.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "教某人如何做某事", "english": "teach sb. how to do sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "n.[C]教师；老师；导师", "english": "teacher", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]教学；（常用pl.）教义", "english": "teaching", "type": "单词", "keyWords": ["teacher"] },
    { "chinese": "有其师必有其徒。", "english": "Like teacher, like pupil.", "type": "句子", "keyWords": ["teacher"] },
    { "chinese": "n.[C]队；组", "english": "team", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]配合，协同工作；小组作业", "english": "teamwork", "type": "单词", "keyWords": ["team"] },
    { "chinese": "他是那个队的成员吗？", "english": "Is he on that team?", "type": "句子", "keyWords": ["team"] },
    { "chinese": "v.告诉；讲述；吩咐；分辨；判断；vi.确定地说出", "english": "tell", "type": "单词", "keyWords": [] },
    { "chinese": "说谎", "english": "tell a lie", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "算命", "english": "tell one's fortune", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "报时", "english": "tell the time", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "区分；辨别", "english": "tell...from...", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "区分；辨别", "english": "tell them apart", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "讲述", "english": "tell of/ about", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "要某人去做某事", "english": "tell sb. to do sth.", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "说出，判断出", "english": "can tell", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "说实话", "english": "tell the truth", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "他判断不出是哪一栋房子。", "english": "He couldn't tell which house it was.", "type": "句子", "keyWords": ["tell"] },
    { "chinese": "不可能知道；难以预料", "english": "There's no telling/ knowing...", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "（谁也）不可能知道会发生什么事。", "english": "There's no telling what may happen.", "type": "句子", "keyWords": ["tell"] },
    { "chinese": "n.[C]（常与a连用）心情，脾气", "english": "temper", "type": "单词", "keyWords": [] },
    { "chinese": "脾气（不）好的", "english": "bad/ good-tempered", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "心情不好", "english": "be in a temper", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "发脾气", "english": "be in a bad temper", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "发脾气", "english": "lose one's temper", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "发脾气", "english": "get into a temper", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "adj.温带的；温和的", "english": "temperate", "type": "单词", "keyWords": [] },
    { "chinese": "在吃喝上自我克制", "english": "be temperate in eating and drinking", "type": "短语", "keyWords": ["temperate"] },
    { "chinese": "温和的批评", "english": "temperate criticism", "type": "短语", "keyWords": ["temperate"] },
    { "chinese": "温和的气候", "english": "temperate climate", "type": "短语", "keyWords": ["temperate"] },
    { "chinese": "n.[C]温度；体温", "english": "temperature", "type": "单词", "keyWords": [] },
    { "chinese": "量体温", "english": "take one's temperature", "type": "短语", "keyWords": ["temperature"] },
    { "chinese": "正常体温", "english": "normal temperature", "type": "短语", "keyWords": ["temperature"] },
    { "chinese": "n.[C]庙宇，寺院", "english": "temple", "type": "单词", "keyWords": [] },
    { "chinese": "adj.临时的，暂时的", "english": "temporary", "type": "单词", "keyWords": [] },
    { "chinese": "adv.暂时地", "english": "temporarily", "type": "单词", "keyWords": ["temporary"] },
    { "chinese": "v.吸引；引诱", "english": "tempt", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]诱惑；n.[C]诱惑物", "english": "temptation", "type": "单词", "keyWords": ["tempt"] },
    { "chinese": "吸引人的提议", "english": "a tempting offer", "type": "短语", "keyWords": ["tempt"] },
    { "chinese": "诱人的气味", "english": "a tempting smell", "type": "短语", "keyWords": ["tempt"] },
    { "chinese": "诱惑某人做某事", "english": "tempt sb. to do sth.", "type": "短语", "keyWords": ["tempt"] },
    { "chinese": "诱惑某人做某事", "english": "tempt sb. into doing sth.", "type": "短语", "keyWords": ["tempt"] },
    { "chinese": "抵制……的诱惑", "english": "resist the temptation to do...", "type": "短语", "keyWords": ["temptation"] },
    { "chinese": "num.十", "english": "ten", "type": "单词", "keyWords": [] },
    { "chinese": "十有八九他会赢。", "english": "Ten to one he will win.", "type": "句子", "keyWords": ["ten"] },
    { "chinese": "n.[C]租户；房客；佃户", "english": "tenant", "type": "单词", "keyWords": [] },
    { "chinese": "v.照管，护理（近attend to, look after）；vi.易于，趋向；倾向", "english": "tend", "type": "单词", "keyWords": [] },
    { "chinese": "照料伤员", "english": "tend the wounded", "type": "短语", "keyWords": ["tend"] },
    { "chinese": "经营酒吧", "english": "tend a bar", "type": "短语", "keyWords": ["tend"] },
    { "chinese": "易于/趋向做某事；往往会（=be inclined to do sth）", "english": "tend to do sth.", "type": "短语", "keyWords": ["tend"] },
    { "chinese": "一个人的处境是苦是乐常是主观的。", "english": "People tend to judge their lives subjectively.", "type": "句子", "keyWords": ["tend"] },
    { "chinese": "冬天蔬菜往往较贵。", "english": "Vegetables tend to be more expensive in winter.", "type": "句子", "keyWords": ["tend"] },
    { "chinese": "n.[C]趋势；趋向；（性格、性质或作品）倾向(to)", "english": "tendency", "type": "单词", "keyWords": [] },
    { "chinese": "倾向/喜欢……", "english": "have a tendency to do...", "type": "短语", "keyWords": ["tendency"] },
    { "chinese": "adj.嫩的；温柔的；亲切的", "english": "tender", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]亲切，柔和", "english": "tenderness", "type": "单词", "keyWords": ["tender"] },
    { "chinese": "adv.温和地，体贴地", "english": "tenderly", "type": "单词", "keyWords": ["tender"] },
    { "chinese": "慈母", "english": "a tender mother", "type": "短语", "keyWords": ["tender"] },
    { "chinese": "嫩肉", "english": "tender meat", "type": "短语", "keyWords": ["tender"] },
    { "chinese": "n.[U]网球（运动）", "english": "tennis", "type": "单词", "keyWords": [] },
    { "chinese": "打网球", "english": "play tennis", "type": "短语", "keyWords": ["tennis"] },
    { "chinese": "adj.绷紧的；紧张的；n.[C]时态；v.（使）拉紧/紧张", "english": "tense", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]张力，拉力", "english": "tension", "type": "单词", "keyWords": ["tense"] },
    { "chinese": "绷紧的肌肉", "english": "tense muscles", "type": "短语", "keyWords": ["tense"] },
    { "chinese": "队员们在比赛开始时很紧张。", "english": "The players were tense at the start of the game.", "type": "句子", "keyWords": ["tense"] },
    { "chinese": "n.[C]帐篷", "english": "tent", "type": "单词", "keyWords": [] },
    { "chinese": "搭帐篷", "english": "put up a tent", "type": "短语", "keyWords": ["tent"] },
    { "chinese": "拆帐篷", "english": "take down a tent", "type": "短语", "keyWords": ["tent"] },
    { "chinese": "n.[C]学期；名称，术语；任期，限期", "english": "term", "type": "单词", "keyWords": [] },
    { "chinese": "专门名词，术语", "english": "technical terms", "type": "短语", "keyWords": ["term"] },
    { "chinese": "科学术语", "english": "scientific terms", "type": "短语", "keyWords": ["term"] },
    { "chinese": "他即将开始他的四年总统任期。", "english": "He is about to begin his four-year term as President.", "type": "句子", "keyWords": ["term"] },
    { "chinese": "就长远/中期/短期而言", "english": "in the long/ medium/ short term", "type": "短语", "keyWords": ["term"] },
    { "chinese": "短期内我们会赔钱，但从长远看，利润将会是丰厚的。", "english": "In the short term we will lose money, but in the long term the profits will be very large.", "type": "句子", "keyWords": ["term"] },
    { "chinese": "关于；至于；从...角度来讲", "english": "in terms of/ in...terms", "type": "短语", "keyWords": ["term"] },
    { "chinese": "我们现在的生产技术水平是什么状况？", "english": "Where do we stand in terms of production technology?", "type": "句子", "keyWords": ["term"] },
    { "chinese": "n.[C]末端；终点；[计]终端(设备)；航站(楼)；a.末端的；定期的", "english": "terminal", "type": "单词", "keyWords": [] },
    { "chinese": "adj.很糟的；可怕的", "english": "terrible", "type": "单词", "keyWords": [] },
    { "chinese": "adv.(口)极；非常；很", "english": "terribly", "type": "单词", "keyWords": ["terrible"] },
    { "chinese": "adj.可怕的，吓人的；(口)非常好的；(美)了不起的；极好的", "english": "terrific", "type": "单词", "keyWords": [] },
    { "chinese": "以高速度开车", "english": "drive at a terrific speed", "type": "短语", "keyWords": ["terrific"] },
    { "chinese": "妙极啦！", "english": "It's terrific!", "type": "句子", "keyWords": ["terrific"] },
    { "chinese": "v.使恐怖，恐吓", "english": "terrify", "type": "单词", "keyWords": [] },
    { "chinese": "adj.使/感到惊恐", "english": "terrifying/ terrified", "type": "单词", "keyWords": ["terrify"] },
    { "chinese": "对...感到惊恐（近be afraid/ scared/ frightened of）", "english": "be terrified of", "type": "短语", "keyWords": ["terrify"] },
    { "chinese": "被...吓了一跳（近be frightened at）", "english": "be terrified at", "type": "短语", "keyWords": ["terrify"] },
    { "chinese": "多么可怕的经历啊！", "english": "What a terrifying experience!", "type": "句子", "keyWords": ["terrify"] },
    { "chinese": "n.[U]恐怖；n.[C]令人恐怖的人或事", "english": "terror", "type": "单词", "keyWords": [] },
    { "chinese": "惊恐地", "english": "in terror", "type": "短语", "keyWords": ["terror"] },
    { "chinese": "n.[U]恐怖主义(手段或政治)", "english": "terrorism", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]恐怖分子", "english": "terrorist", "type": "单词", "keyWords": ["terrorism"] },
    { "chinese": "n.[C](U]领土；版图；领地；地区", "english": "territory", "type": "单词", "keyWords": [] },
    { "chinese": "这个岛是我国领土。", "english": "This island is our territory.", "type": "句子", "keyWords": ["territory"] },
    { "chinese": "进入他们的领地", "english": "enter their territory", "type": "短语", "keyWords": ["territory"] },
    { "chinese": "无人居住区", "english": "uninhabited territory", "type": "短语", "keyWords": ["territory"] },
    { "chinese": "n.[C]/v.测试，测验；试验；考验；化验（辨析见check）", "english": "test", "type": "单词", "keyWords": [] },
    { "chinese": "使经受考验，检验", "english": "put...to the test", "type": "短语", "keyWords": ["test"] },
    { "chinese": "经得起...的考验", "english": "stand the test of...", "type": "短语", "keyWords": ["test"] },
    { "chinese": "n.[C]课文；文本；(手机)短信；v.向…发送短信息", "english": "text", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]教科书；课本", "english": "textbook", "type": "单词", "keyWords": ["text"] },
    { "chinese": "conj.比", "english": "than", "type": "单词", "keyWords": [] },
    { "chinese": "事情进行得比预料的要顺利。", "english": "Things went better than (had been) expected.", "type": "句子", "keyWords": ["than"] },
    { "chinese": "v.感谢；谢谢；n.(pl.)感谢；谢意", "english": "thank", "type": "单词", "keyWords": [] },
    { "chinese": "adj.感谢的", "english": "thankful", "type": "单词", "keyWords": ["thank"] },
    { "chinese": "因…而感谢…（近appreciate sth.）", "english": "thank sb. for sth.", "type": "短语", "keyWords": ["thank"] },
    { "chinese": "多谢。", "english": "Many thanks/ Thanks a lot.", "type": "句子", "keyWords": ["thank"] },
    { "chinese": "因某事而感谢某人（近be grateful/ obliged to sb. for sth.）", "english": "be thankful to sb. for sth.", "type": "短语", "keyWords": ["thank"] },
    { "chinese": "多亏/由于（辨析见account）", "english": "thanks to...", "type": "短语", "keyWords": ["thank"] },
    { "chinese": "求你安静点。（埋怨口气）", "english": "Will you thank you to be quiet.", "type": "句子", "keyWords": ["thank"] },
    { "chinese": "pron./a.那，那个；ad.（与形容词或副词连用）那样；那么；conj.引导名词性从句或状语从句", "english": "that", "type": "单词", "keyWords": [] },
    { "chinese": "就是说；即", "english": "that is (to say)", "type": "短语", "keyWords": ["that"] },
    { "chinese": "因为", "english": "in that (because)", "type": "短语", "keyWords": ["that"] },
    { "chinese": "既然（~since）", "english": "now that", "type": "短语", "keyWords": ["that"] },
    { "chinese": "强调句型", "english": "It is/ was...that/ who...", "type": "句式", "keyWords": ["that"] },
    { "chinese": "（表示厌烦、不满或赞赏等感情色彩）", "english": "that...of sb.'s", "type": "短语", "keyWords": ["that"] },
    { "chinese": "我很不喜欢他的那个儿子。", "english": "I don't like that son of his.", "type": "句子", "keyWords": ["that"] },
    { "chinese": "主要问题是成本问题。", "english": "The main question is that of cost (=the cost question).", "type": "句子", "keyWords": ["that"] },
    { "chinese": "我无法走那么远。（近so）", "english": "I cannot walk that far.", "type": "句子", "keyWords": ["that"] },
    { "chinese": "有大约那么高吗？", "english": "Is it about that high?", "type": "句子", "keyWords": ["that"] },
    { "chinese": "不是（因为）…而是（因为）…", "english": "not that...but that...", "type": "句式", "keyWords": ["that"] },
    { "chinese": "不是我不满意，而是我还有很多事情要做。", "english": "Not that I am dissatisfied, but that I have my own business to tend to.", "type": "句子", "keyWords": ["that"] },
    { "chinese": "art.（定冠词）这（那）个；这（那）些", "english": "the", "type": "单词", "keyWords": [] },
    { "chinese": "两个中高的那个", "english": "the taller of the two", "type": "短语", "keyWords": ["the"] },
    { "chinese": "我们4个人", "english": "the four of us", "type": "短语", "keyWords": ["the"] },
    { "chinese": "我们中4个人", "english": "four of us", "type": "短语", "keyWords": ["the"] },
    { "chinese": "怀特一家人（比较at White's/ at the Whites' 在怀特家）", "english": "the Whites", "type": "短语", "keyWords": ["the"] },
    { "chinese": "巴西总统贾伊尔·波索纳罗有时被称为“热带地区的特朗普式人物”。", "english": "Brazilian President Jair Bolsonaro is sometimes called the 'Trump of the Tropics'.", "type": "句子", "keyWords": ["the"] },
    { "chinese": "越早越好。", "english": "The sooner, the better.", "type": "句子", "keyWords": ["the"] },
    { "chinese": "计时付酬", "english": "be paid by the hour", "type": "短语", "keyWords": ["the"] },
    { "chinese": "在（20世纪）60年代", "english": "in the sixties/ in the 1960's/ in the 60s", "type": "短语", "keyWords": ["the"] },
    { "chinese": "穷人/伤员/下列（表示一个类别，用作单或复）", "english": "the poor/ the wounded/ the following", "type": "短语", "keyWords": ["the"] },
    { "chinese": "只会更好/糟/…", "english": "all the better/ worse/...", "type": "短语", "keyWords": ["the"] },
    { "chinese": "她衣衫褴褛，却显得更美丽了。", "english": "She is all the more beautiful in her shabby clothing.", "type": "句子", "keyWords": ["the"] },
    { "chinese": "n.[C]戏院", "english": "theatre", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]经常看戏的人", "english": "theatregoer", "type": "单词", "keyWords": ["theatre"] },
    { "chinese": "n.[C](U]偷窃；失窃；偷盗罪", "english": "theft", "type": "单词", "keyWords": [] },
    { "chinese": "偷窃", "english": "commit a theft", "type": "短语", "keyWords": ["theft"] },
    { "chinese": "他因为偷窃被关进监狱。", "english": "He was put in prison for theft.", "type": "句子", "keyWords": ["theft"] },
    { "chinese": "pron.他/她/它们的", "english": "their", "type": "单词", "keyWords": [] },
    { "chinese": "pron.他/她/它们的（名词性物主代词）", "english": "theirs", "type": "单词", "keyWords": [] },
    { "chinese": "这是他们的一种习惯。", "english": "It's a habit of theirs.", "type": "句子", "keyWords": ["theirs"] },
    { "chinese": "pron.他（她、它）们自己", "english": "themselves", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（谈话、写作或讨论等的）题目，主题；vt.赋予…主题", "english": "theme", "type": "单词", "keyWords": [] },
    { "chinese": "adv.那时；（常与and,but连用）接着；（常用于句首或句尾）那么", "english": "then", "type": "单词", "keyWords": [] },
    { "chinese": "从那时起", "english": "from then on", "type": "短语", "keyWords": ["then"] },
    { "chinese": "从那时以来（到现在）", "english": "since then", "type": "短语", "keyWords": ["then"] },
    { "chinese": "间或；不时地", "english": "now and then", "type": "短语", "keyWords": ["then"] },
    { "chinese": "一直到那时，到那时为止", "english": "till then", "type": "短语", "keyWords": ["then"] },
    { "chinese": "接着到了考试的日子。（倒装）", "english": "Then came the day of the exams.", "type": "句子", "keyWords": ["then"] },
    { "chinese": "如果交通拥挤，那就允许超时。", "english": "If traffic is heavy, then extra time will be allowed.", "type": "句子", "keyWords": ["then"] },
    { "chinese": "当时，当场", "english": "then and there", "type": "短语", "keyWords": ["then"] },
    { "chinese": "他当场拒绝了他们的建议。", "english": "He turned down their proposal then and there.", "type": "句子", "keyWords": ["then"] },
    { "chinese": "n.[C](U]理论；学说；论说", "english": "theory", "type": "单词", "keyWords": [] },
    { "chinese": "adj.理论的；理论上的", "english": "theoretical", "type": "单词", "keyWords": ["theory"] },
    { "chinese": "在/从理论上；按理论", "english": "in theory", "type": "短语", "keyWords": ["theory"] },
    { "chinese": "n.[C](U]疗法；治疗", "english": "therapy", "type": "单词", "keyWords": [] },
    { "chinese": "adv.（在）那里；往那儿；（作引导词，与be等动词连用）有，存在", "english": "there", "type": "单词", "keyWords": [] },
    { "chinese": "喂！你听得见吗？（打电话用语）", "english": "Are you there?", "type": "句子", "keyWords": ["there"] },
    { "chinese": "好像/碰巧/据说/以前/一定有…", "english": "There seems/ appears/ happens/ is said/ used/ is sure to be ...", "type": "句式", "keyWords": ["there"] },
    { "chinese": "普遍认为在新几内亚这种物种现存有60种。", "english": "There are thought to be sixty species of this class alive in New Guinea.", "type": "句子", "keyWords": ["there"] },
    { "chinese": "（某地）有…（存在）", "english": "There lived/ stands/ remains a...", "type": "句式", "keyWords": ["there"] },
    { "chinese": "公共汽车来了。", "english": "There comes the bus.", "type": "句子", "keyWords": ["there"] },
    { "chinese": "不可能知道；难以预料", "english": "There is no telling/ knowing...", "type": "句式", "keyWords": ["there"] },
    { "chinese": "过去曾…", "english": "There was a time when...", "type": "句式", "keyWords": ["there"] },
    { "chinese": "我倒是有很多次想，你没有干过演员怎么能做这份工作。", "english": "There were times when I wondered how you could do this job without having been an actor.", "type": "句子", "keyWords": ["there"] },
    { "chinese": "没有做某事的必要", "english": "there is no need to do sth.", "type": "句式", "keyWords": ["there"] },
    { "chinese": "adv.（可与and连用）因此，以此，以这种方式", "english": "thereby", "type": "单词", "keyWords": [] },
    { "chinese": "他成了公民，因此取得了投票权。", "english": "He became a citizen, thereby gaining the right to vote.", "type": "句子", "keyWords": ["thereby"] },
    { "chinese": "adv.因此；所以（可与and连用，比so正式）", "english": "therefore", "type": "单词", "keyWords": [] },
    { "chinese": "pron./a.这些", "english": "these", "type": "单词", "keyWords": [] },
    { "chinese": "pron.他/她/它们（主格）", "english": "they", "type": "单词", "keyWords": [] },
    { "chinese": "adj.厚的；粗的；浓的；密的", "english": "thick", "type": "单词", "keyWords": [] },
    { "chinese": "v./vi.使变厚", "english": "thicken", "type": "单词", "keyWords": ["thick"] },
    { "chinese": "n.[U]厚度，浓度", "english": "thickness", "type": "单词", "keyWords": ["thick"] },
    { "chinese": "空气中浓烟弥漫。", "english": "The air was thick with smoke.", "type": "句子", "keyWords": ["thick"] },
    { "chinese": "n.[C]贼，小偷；偷窃犯", "english": "thief", "type": "单词", "keyWords": [] },
    { "chinese": "捉贼！", "english": "Stop thief!", "type": "句子", "keyWords": ["thief"] },
    { "chinese": "adj.薄的；瘦的；细的；稀疏的；v./vi.（使）变薄；（使）变细", "english": "thin", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]事情；东西；事（物）；(pl)情况", "english": "thing", "type": "单词", "keyWords": [] },
    { "chinese": "情况在好转。", "english": "Things are getting better now.", "type": "句子", "keyWords": ["thing"] },
    { "chinese": "[口]近况如何？", "english": "How are things?", "type": "句子", "keyWords": ["thing"] },
    { "chinese": "（说明理由）首先…，其次…", "english": "for one thing...for another...", "type": "短语", "keyWords": ["thing"] },
    { "chinese": "知道是一回事，会教又完全是另一回事。（学者未必是良师。）", "english": "To know is one thing, to teach is quite another.", "type": "句子", "keyWords": ["thing"] },
    { "chinese": "随遇而安，安于现状，对一切事情处之泰然", "english": "take things as they are", "type": "短语", "keyWords": ["thing"] },
    { "chinese": "万事开头难。/凡事总是由难而易。", "english": "All things are difficult before they are easy.", "type": "句子", "keyWords": ["thing"] },
    { "chinese": "v.想；认为", "english": "think", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]想法；思考；a.理性的；爱思考的", "english": "thinking", "type": "单词", "keyWords": ["think"] },
    { "chinese": "认为…是……（比较think of...as）", "english": "think sb./sth./it (to be) +n./a.", "type": "短语", "keyWords": ["think"] },
    { "chinese": "这个计划被认为是行不通的。", "english": "The plan was thought to be unfeasible.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "这个计划被认为是行不通的。", "english": "The plan was thought of as (being) unfeasible.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "再等一会儿你看好不好？", "english": "Do you think it (to be) advisable to wait a little longer?", "type": "句子", "keyWords": ["think"] },
    { "chinese": "（经…）认为/相信/觉得某人/某物…", "english": "think/ consider/ believe/ suppose sb. to have/ be sth.", "type": "短语", "keyWords": ["think"] },
    { "chinese": "巴斯曼找到了据信已在20年前死去的兄弟。", "english": "Bussman found a brother who was thought to have been killed twenty years before.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "你看我们在哪儿能搞到这种机器？（复杂特殊疑问句）", "english": "Where do you think we can get this machine?", "type": "句子", "keyWords": ["think"] },
    { "chinese": "我想/我估计（你的方法是不正确的。）", "english": "I should/ would think (your approach is incorrect.)", "type": "句子", "keyWords": ["think"] },
    { "chinese": "自言自语", "english": "think aloud", "type": "短语", "keyWords": ["think"] },
    { "chinese": "考虑；思考", "english": "think about...", "type": "短语", "keyWords": ["think"] },
    { "chinese": "想出（计划等）", "english": "think out", "type": "短语", "keyWords": ["think"] },
    { "chinese": "心中想，自忖", "english": "think to oneself", "type": "短语", "keyWords": ["think"] },
    { "chinese": "仔细考虑", "english": "think...over", "type": "短语", "keyWords": ["think"] },
    { "chinese": "再三考虑，三思", "english": "think twice", "type": "短语", "keyWords": ["think"] },
    { "chinese": "考虑（=think about）；想起，想到（某人、事）；对…有某种看法", "english": "think of", "type": "短语", "keyWords": ["think"] },
    { "chinese": "我知道你指的是谁，但是我一时想不起他的名字。", "english": "I know the person you refer to, but I cannot think of his name at the moment.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "你认为…怎么样？", "english": "What do you think of...?", "type": "句子", "keyWords": ["think"] },
    { "chinese": "轻视；认为没什么了不起；不放在眼里", "english": "think nothing/ little/ poorly of", "type": "短语", "keyWords": ["think"] },
    { "chinese": "看重；器重；评价极高；赞美", "english": "think well/ much/ highly of", "type": "短语", "keyWords": ["think"] },
    { "chinese": "他在整个地区评价很高。", "english": "He was very well thought of all over the district.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "独立思考", "english": "independent thinking", "type": "短语", "keyWords": ["think"] },
    { "chinese": "不假思索", "english": "without thinking", "type": "短语", "keyWords": ["think"] },
    { "chinese": "我们是理性的动物。", "english": "We are thinking animals.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "num.第三；三分之一；第三名", "english": "third", "type": "单词", "keyWords": [] },
    { "chinese": "三分之二", "english": "two thirds", "type": "短语", "keyWords": ["third"] },
    { "chinese": "第三世界", "english": "the Third World", "type": "短语", "keyWords": ["third"] }
];
