const qgl277_284 = [
    { "chinese": "第三方", "english": "the third party", "type": "短语", "keyWords": ["third"] },
    { "chinese": "第三人称", "english": "the third person", "type": "短语", "keyWords": ["third"] },
    { "chinese": "adj.口渴的；干旱的；渴望的(for)；n.[U]口渴，渴望", "english": "thirsty /ˈθɜːsti/ a.；thirst n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "他渴望得到知识。", "english": "He is thirsty for knowledge.=He has a thirst for knowledge.", "type": "句子", "keyWords": ["thirsty", "thirst"] },
    { "chinese": "pron./adj.这；这个；以上或以下所述；adv.这么；这样（比较that）", "english": "this /ðɪs/ a. pron.；ad.", "type": "单词", "keyWords": [] },
    { "chinese": "这/那就是为什么我坚持这样。", "english": "This/ That is why I insisted on this.", "type": "句子", "keyWords": ["this", "that"] },
    { "chinese": "理由如下。（that一般只能承接上文）", "english": "The reason is this. (that一般只能承接上文)", "type": "句子", "keyWords": ["this", "that"] },
    { "chinese": "我从来没在外面待到这么晚。", "english": "I've never been out this late before.", "type": "句子", "keyWords": ["this"] },
    { "chinese": "尽管如此，（见for）", "english": "For all this,... (见for)", "type": "短语", "keyWords": ["this"] },
    { "chinese": "adj.彻底的，完全的；周密的；adv.彻底地；n.[U]完全，彻底", "english": "thorough /ˈθʌrə/ a.；thoroughly ad.；thoroughness n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "pron./adj.那些", "english": "those /ðəʊz/ pron./a.", "type": "单词", "keyWords": [] },
    { "chinese": "conj.虽然，尽管；adv.但（用于句中或句末）", "english": "though /ðəʊ/ conj.；ad.", "type": "单词", "keyWords": [] },
    { "chinese": "恰如，好像", "english": "as though(=as if)", "type": "短语", "keyWords": ["though"] },
    { "chinese": "即使，纵然", "english": "even though(=even if)", "type": "短语", "keyWords": ["though"] },
    { "chinese": "这是件艰难的工作，可是我还是挺喜欢的。", "english": "It's hard work. I enjoy it, though.", "type": "句子", "keyWords": ["though"] },
    { "chinese": "n.[C]打算；想法；意图（见idea）；n.[U]思考（能力），思维；思想，（特定的）思想方法；关心，着想（think的过去式和过去分词）", "english": "thought /θɔːt/ n.[C]；n.[U] (think的过去式和过去分词)", "type": "单词", "keyWords": [] },
    { "chinese": "她把视线转向别处，陷入沉思，然后毫无怨言地离开了。", "english": "She looked away for a moment, deep/ lost in thought, and then left without a word of complaint.", "type": "句子", "keyWords": ["thought"] },
    { "chinese": "他不在乎她说什么。", "english": "He didn't give much thought to what she said.", "type": "句子", "keyWords": ["thought"] },
    { "chinese": "不为……着想", "english": "have no thought for/ without thought for", "type": "短语", "keyWords": ["thought"] },
    { "chinese": "一想到……", "english": "at the thought of...", "type": "短语", "keyWords": ["thought"] },
    { "chinese": "一想到再也见不到他了，我们两眼充满泪水。", "english": "Tears fled our eyes at the thought of never seeing him again.", "type": "句子", "keyWords": ["thought"] },
    { "chinese": "又一想，再三考虑后", "english": "on a second thought/on second thoughts", "type": "短语", "keyWords": ["thought"] },
    { "chinese": "他本来想去，但进一步考虑后，打消了这个念头。", "english": "He had intended to go, but on second thoughts, he gave up the idea.", "type": "句子", "keyWords": ["thought"] },
    { "chinese": "adj.思考的，深思的；有思想的，表达思想的；考虑周到的", "english": "thoughtful /ˈθɔːtfl/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "沉思的表情", "english": "thoughtful looks", "type": "短语", "keyWords": ["thoughtful"] },
    { "chinese": "富有思想的书", "english": "a thoughtful book", "type": "短语", "keyWords": ["thoughtful"] },
    { "chinese": "你带花来真是考虑周全。", "english": "It was thoughtful of you to bring flowers.", "type": "句子", "keyWords": ["thoughtful"] },
    { "chinese": "num.千", "english": "thousand /ˈθaʊznd/ num.", "type": "单词", "keyWords": [] },
    { "chinese": "数千", "english": "thousands of...", "type": "短语", "keyWords": ["thousand"] },
    { "chinese": "大批地，成千上万地", "english": "by the thousands", "type": "短语", "keyWords": ["thousand"] },
    { "chinese": "以万计的……", "english": "tens of thousands of...", "type": "短语", "keyWords": ["thousand"] },
    { "chinese": "数以万计（的……）", "english": "thousands upon thousands (of...)", "type": "短语", "keyWords": ["thousand"] },
    { "chinese": "n.[C]线；vt.穿（针、线）等", "english": "thread /θred/ n.[C]；vt.", "type": "单词", "keyWords": [] },
    { "chinese": "穿针引线", "english": "thread a needle", "type": "短语", "keyWords": ["thread"] },
    { "chinese": "针线在抽屉里。", "english": "The needle and thread is in the drawer.", "type": "句子", "keyWords": ["thread"] },
    { "chinese": "n.[C]威胁；构成威胁的人或事物", "english": "threat /θret/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "洪水对村庄的威胁解除了。", "english": "The threat of the flood to the village has been relieved.", "type": "句子", "keyWords": ["threat"] },
    { "chinese": "v.威胁；预示（多表示预示着不希望发生的事）", "english": "threaten /ˈθretn/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "威胁要做某事", "english": "threaten to do...", "type": "短语", "keyWords": ["threaten"] },
    { "chinese": "男孩的父亲威胁说如果他再偷东西的话，就要揍他。", "english": "His father threatened to beat the boy if he stole again.", "type": "句子", "keyWords": ["threaten"] },
    { "chinese": "用……恐吓某人", "english": "threaten sb. with sth.", "type": "短语", "keyWords": ["threaten"] },
    { "chinese": "受到……的威胁", "english": "be threatened with...", "type": "短语", "keyWords": ["threaten"] },
    { "chinese": "乌云预示有雨。", "english": "Black clouds threaten to rain.", "type": "句子", "keyWords": ["threaten"] },
    { "chinese": "v./vi.（使）激动，（使）兴奋；（因突然兴奋或激动而）（使）颤抖；adj.毛骨悚然的；惊心动魄的，使人感动的；使人发抖的，震颤的", "english": "thrill /θrɪl/ vt./vi.；thrilling a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]咽喉，喉咙", "english": "throat /θrəʊt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "清清喉咙", "english": "clear one's throat", "type": "短语", "keyWords": ["throat"] },
    { "chinese": "掐住咽喉", "english": "catch/ hold/ seize/ take sb. by the throat", "type": "短语", "keyWords": ["throat"] },
    { "chinese": "梗在某人喉头", "english": "stick in sb.'s throat", "type": "短语", "keyWords": ["throat"] },
    { "chinese": "prep.通过；穿过；adv.贯穿地，从头到尾，自始至终", "english": "through /θruː/ prep.；ad.", "type": "单词", "keyWords": [] },
    { "chinese": "法国各地之旅", "english": "a tour through France", "type": "短语", "keyWords": ["through"] },
    { "chinese": "贯穿整个……", "english": "all through (the year, one's life)", "type": "短语", "keyWords": ["through"] },
    { "chinese": "请帮我接通琼斯先生的电话。", "english": "Can you put me through to Mr Jones?", "type": "句子", "keyWords": ["through"] },
    { "chinese": "你看完信了吗？", "english": "Have you read the letter through?", "type": "句子", "keyWords": ["through"] },
    { "chinese": "做好，结束（工作等）", "english": "be through with", "type": "短语", "keyWords": ["through"] },
    { "chinese": "她完成了这个项目。", "english": "She was through with the project.", "type": "句子", "keyWords": ["through"] },
    { "chinese": "prep.遍及；贯穿（时间或地区）（近all through）", "english": "throughout /θruːˈaʊt/ prep.", "type": "单词", "keyWords": [] },
    { "chinese": "全年", "english": "throughout the year/ all the year round/ the whole year", "type": "短语", "keyWords": ["throughout"] },
    { "chinese": "全世界", "english": "throughout the world/ all over the world/ the world over", "type": "短语", "keyWords": ["throughout"] },
    { "chinese": "v.投；掷；抛；扔；n.[C]投掷（距离或高度）", "english": "throw /θrəʊ/ v.；n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "匆忙地穿衣或脱衣", "english": "throw...on/off", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "丢回；掷回", "english": "throw...back", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "朝……扔……（恶意用at，善意用to）", "english": "throw...at(恶意)/to(善意)sb.", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "呕吐", "english": "throw...up", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "扔掉，抛弃；浪费（钱、时间等）；错过（机会等）", "english": "throw...away", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "投掷70米远", "english": "a throw of 70 meters", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "投石可及的距离，附近；一箭之地", "english": "a stone's throw(from...)", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "n.[C]拇指", "english": "thumb /θʌm/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "笨手笨脚", "english": "be all thumbs", "type": "短语", "keyWords": ["thumb"] },
    { "chinese": "n.[U]雷；雷声；雷鸣般的响声；轰隆声；vi.打雷", "english": "thunder /ˈθʌndə/ n.[U]；vi.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]雷暴", "english": "thunderstorm /ˈθʌndəstɔːm/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]星期四", "english": "Thursday /ˈθɜːzdeɪ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adv.如此，这样；因而", "english": "thus /ðʌs/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "原文就是这样的。", "english": "The text runs thus.", "type": "句子", "keyWords": ["thus"] },
    { "chinese": "n.[C]（车、戏等）票，票证，入场券；（给违反交通规则者的）传票", "english": "ticket /ˈtɪkɪt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "超速违章通知单/星期五的票", "english": "a ticket for speeding/ Friday", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "来回票", "english": "a return ticket", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "入场票", "english": "an admission ticket", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "单程票", "english": "a one-way ticket", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "季票，定期票", "english": "season ticket", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "n.[C]潮（汐）；潮水；潮流，趋势；浪潮；v.（使）随潮水漂流", "english": "tide /taɪd/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "倒行逆施", "english": "attempt to go against the tide of history", "type": "短语", "keyWords": ["tide"] },
    { "chinese": "顺应潮流；随波逐流", "english": "go/ swim with the tide", "type": "短语", "keyWords": ["tide"] },
    { "chinese": "岁月不等人。/时不我待。", "english": "Time and tide wait for no man.", "type": "句子", "keyWords": ["tide"] },
    { "chinese": "adj.整齐的，整洁的（反untidy）；v.使整洁（可加up）", "english": "tidy /ˈtaɪdi/ a.；v.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]领带；领结；平局；联系，纽带；v.拴，扎，系上", "english": "tie /taɪ/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "血缘关系", "english": "a blood tie", "type": "短语", "keyWords": ["tie"] },
    { "chinese": "把风筝拴到柱子上", "english": "tie the kite to a post", "type": "短语", "keyWords": ["tie"] },
    { "chinese": "这场比赛打成平局。", "english": "The game ended in a tie.", "type": "句子", "keyWords": ["tie"] },
    { "chinese": "n.[C]老虎", "english": "tiger /ˈtaɪɡə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.紧的；紧身的；拉紧的；adv.紧紧地；v.使……紧；紧缩银根", "english": "tight /taɪt/ a.；ad.；tighten v.；tight money", "type": "单词", "keyWords": [] },
    { "chinese": "把它紧紧握住", "english": "hold it tight", "type": "短语", "keyWords": ["tight"] },
    { "chinese": "conj./prep.直到……（一般不位于句首）", "english": "till /tɪl/ conj./prep.", "type": "单词", "keyWords": [] },
    { "chinese": "从早到晚", "english": "from morning till night", "type": "短语", "keyWords": ["till"] },
    { "chinese": "n.[C]次；回；[U]时间；(pl.)时期；v.测时间；安排……的时间；adj.及时（的）；适时（发生）的；n.[C]时刻表；课程表", "english": "time /taɪm/ n.[C]/[U]/(pl.)；v.；time a.；timetable n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "提前", "english": "ahead of time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "暂时", "english": "for the time being", "type": "短语", "keyWords": ["time"] },
    { "chinese": "一度，暂时", "english": "for a time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "从前", "english": "once upon a time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "曾经；一度", "english": "at one time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "一次一个", "english": "one at a time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "同时", "english": "at the same time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "一次又一次；重复地", "english": "time and again", "type": "短语", "keyWords": ["time"] },
    { "chinese": "过时；落后", "english": "behind the times", "type": "短语", "keyWords": ["time"] },
    { "chinese": "有时，不时地", "english": "from time to time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "……的时候", "english": "by the time...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "及时；最终（经过适当时候）", "english": "in time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "与时俱进", "english": "change with the times", "type": "短语", "keyWords": ["time"] },
    { "chinese": "时间才会给出答案。", "english": "Only time will tell.", "type": "句子", "keyWords": ["time"] },
    { "chinese": "耗费时间的", "english": "time-consuming", "type": "短语", "keyWords": ["time"] },
    { "chinese": "有时间做某事", "english": "have the time for...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "一直；始终", "english": "all the time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "有时", "english": "at times", "type": "短语", "keyWords": ["time"] },
    { "chinese": "立刻；很快", "english": "in no time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "准时", "english": "on time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "定时炸弹", "english": "a time bomb", "type": "短语", "keyWords": ["time"] },
    { "chinese": "光阴似箭！", "english": "Time flies!", "type": "句子", "keyWords": ["time"] },
    { "chinese": "节约时间的", "english": "time-saving", "type": "短语", "keyWords": ["time"] },
    { "chinese": "常常；多次", "english": "many a time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "在其他时候；在另外场合", "english": "at other times", "type": "短语", "keyWords": ["time"] },
    { "chinese": "（钟、表）走时准", "english": "keep good time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "消磨时间，打发时间", "english": "kill time = pass the time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "做某事时碰到困难", "english": "have a hard time (in) doing sth.", "type": "短语", "keyWords": ["time"] },
    { "chinese": "抓紧时间做某事", "english": "lose no time in doing sth.", "type": "短语", "keyWords": ["time"] },
    { "chinese": "（祝你）过（或玩）得愉快", "english": "have a good time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "短时间内，一度", "english": "for a time/ while/ moment", "type": "短语", "keyWords": ["time"] },
    { "chinese": "他深思了一会儿。", "english": "He remained thoughtful for a time.", "type": "句子", "keyWords": ["time", "thoughtful"] },
    { "chinese": "随着时间的推移", "english": "As time goes on...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "当……（近each time, next time, the first time 引导句子）", "english": "every time...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "来得及做某事", "english": "...in time (to do sth.)", "type": "短语", "keyWords": ["time"] },
    { "chinese": "她到得正是时候，刚好赶上参加考试。", "english": "She arrived just in time to take the exam.", "type": "句子", "keyWords": ["time"] },
    { "chinese": "应该立刻做某事的时候（虚拟语气）", "english": "It's about/high time (that)...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "你们该起来了。", "english": "It's high time you were all up.", "type": "句子", "keyWords": ["time"] },
    { "chinese": "adj.胆怯的；羞怯的；n.[U]胆怯", "english": "timid /ˈtɪmɪd/ a.；timidity n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]罐头；v.把……保存或装在罐头中；罐头食品", "english": "tin /tɪn/ n.[C]；v.；tinned food", "type": "单词", "keyWords": [] },
    { "chinese": "adj.微小的；极小的", "english": "tiny /ˈtaɪni/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]顶端，尖端；小费；倾斜，倾侧；告诫，指点；v.给……小费；（使）倾斜；（使）翻倒；（使）倾翻；n.[C]脚趾尖；vi.踮着脚走；蹑手蹑脚地走", "english": "tip /tɪp/ n.[C]；v.；tiptoe /ˈtɪptəʊ/ n.[C]；vi.", "type": "单词", "keyWords": [] },
    { "chinese": "差点说出", "english": "on the tip of one's tongue", "type": "短语", "keyWords": ["tip"] },
    { "chinese": "她的名字就在我嘴边却说不出来。", "english": "I have her name on the tip of my tongue.", "type": "句子", "keyWords": ["tip"] },
    { "chinese": "用脚尖走", "english": "on tiptoe", "type": "短语", "keyWords": ["tiptoe"] },
    { "chinese": "v.使疲劳；使厌倦；n.[C]轮胎", "english": "tire /ˈtaɪə/ v.；n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "使……十分疲劳", "english": "tire...out", "type": "短语", "keyWords": ["tire"] },
    { "chinese": "adj.累的，疲劳的；厌倦的(of)；n.[U]疲劳；adj.累人的", "english": "tired /ˈtaɪəd/ a.；tiredness n.[U]；tiring a.", "type": "单词", "keyWords": [] },
    { "chinese": "对……厌倦", "english": "be tired of", "type": "短语", "keyWords": ["tired"] },
    { "chinese": "累得要死，累极了", "english": "be tired out = be worn out", "type": "短语", "keyWords": ["tired"] },
    { "chinese": "adj.令人厌烦的；讨厌的", "english": "tiresome /ˈtaɪəsəm/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][生]组织；薄的织物；手巾纸；卫生纸；[U]棉纸，薄纸", "english": "tissue /ˈtɪʃuː/ n.[C]；tissue paper n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "肌肉组织", "english": "the muscular tissue", "type": "短语", "keyWords": ["tissue"] },
    { "chinese": "n.[C]标题；题目；称号；职称；头衔；(常pl.)字幕；adj.有头衔的", "english": "title /ˈtaɪtl/ n.[C]；titled a.", "type": "单词", "keyWords": [] },
    { "chinese": "prep.（表示方向）到，向，往；（表示间接关系）给……，于……", "english": "to /tuː, tə, tu/ prep.", "type": "单词", "keyWords": [] },
    { "chinese": "中肯", "english": "to the point", "type": "短语", "keyWords": ["to"] },
    { "chinese": "在一定程度上", "english": "to some extent", "type": "短语", "keyWords": ["to"] },
    { "chinese": "为……干杯", "english": "drink to", "type": "短语", "keyWords": ["to"] },
    { "chinese": "来回地，来来往往地", "english": "to and fro", "type": "短语", "keyWords": ["to"] },
    { "chinese": "村庄位于树林的东面。", "english": "The village is to the east of the woods.", "type": "句子", "keyWords": ["to"] },
    { "chinese": "这把锁的钥匙", "english": "the key to the lock", "type": "短语", "keyWords": ["to"] },
    { "chinese": "部长的私人秘书", "english": "a private secretary to the minister", "type": "短语", "keyWords": ["to"] },
    { "chinese": "是他国家的光荣", "english": "be an honor to his country", "type": "短语", "keyWords": ["to"] },
    { "chinese": "随着曲子起舞/唱歌", "english": "sing/dance to the tune", "type": "短语", "keyWords": ["to"] },
    { "chinese": "这画栩栩如生。如果你想去的话就去吧。", "english": "The picture is true to life. Go if you want to.", "type": "句子", "keyWords": ["to", "true"] },
    { "chinese": "n.[C]祝酒；干杯；烤，烘；吐司；v.向……祝酒；v.烤，烘；n.烤箱", "english": "toast /təʊst/ n.[C]；v.；toaster n.", "type": "单词", "keyWords": [] },
    { "chinese": "为……干杯", "english": "drink a toast to sb./ sth. = drink to sb./ sth. = toast sb./ sth.", "type": "短语", "keyWords": ["toast"] },
    { "chinese": "我们为新娘新郎干杯。", "english": "We toasted the bride and bridegroom.", "type": "句子", "keyWords": ["toast"] },
    { "chinese": "n.[U]烟草", "english": "tobacco /təˈbækəʊ/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.（常用在名词后构成复合词）未来的，即将的", "english": "to-be /ˈtuːbi/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "未来的新娘", "english": "a bride-to-be", "type": "短语", "keyWords": ["to-be"] },
    { "chinese": "某人的未婚妻", "english": "sb.'s wife-to-be", "type": "短语", "keyWords": ["to-be"] },
    { "chinese": "adv.今天", "english": "today /təˈdeɪ/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]脚趾，足尖；（鞋袜等的）足尖部", "english": "toe /təʊ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adv.一起", "english": "together /təˈɡeðə/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]厕所；卫生间；盥洗室；抽水马桶", "english": "toilet /ˈtɔɪlət/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "vt.忍受，容忍", "english": "tolerate /ˈtɒləreɪt/ vt.", "type": "单词", "keyWords": [] },
    { "chinese": "adj.容忍的；宽恕的(of)", "english": "tolerant /ˈtɒlərənt/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl.tomatoes)西红柿，番茄", "english": "tomato /təˈmɑːtəʊ/ n.[C](pl.tomatoes)", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]坟墓；冢；葬身之地", "english": "tomb /tuːm/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "ad.[U]明天", "english": "tomorrow /təˈmɒrəʊ/ ad.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "未来世界将和现在大不相同。", "english": "The world of tomorrow will be quite different from the world of today.", "type": "句子", "keyWords": ["tomorrow", "today"] },
    { "chinese": "今日事今日毕。", "english": "Never put off till tomorrow what you can do today.", "type": "句子", "keyWords": ["tomorrow", "today", "till"] },
    { "chinese": "切莫依赖明天。", "english": "Tomorrow never comes.", "type": "句子", "keyWords": ["tomorrow"] },
    { "chinese": "n.[C]吨；n.[C]公吨", "english": "ton /tʌn/ n.[C]；tonne /tʌn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]语气；音调；音质", "english": "tone /təʊn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "优美的声音", "english": "sweet tone", "type": "短语", "keyWords": ["tone"] },
    { "chinese": "带着怒气说话", "english": "speak in an angry tone", "type": "短语", "keyWords": ["tone"] },
    { "chinese": "用升→降→升调", "english": "in the rise-fall-rise tone", "type": "短语", "keyWords": ["tone"] },
    { "chinese": "n.[C]舌头；语言；方言，土语", "english": "tongue /tʌŋ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "本国语", "english": "mother/ native tongue", "type": "短语", "keyWords": ["tongue"] },
    { "chinese": "绕口令", "english": "tongue twister", "type": "短语", "keyWords": ["tongue"] },
    { "chinese": "一言不发，保持安静；（用于祈使句中）住嘴", "english": "hold one's tongue", "type": "短语", "keyWords": ["tongue"] },
    { "chinese": "失声；（由于震惊等）失去说话的能力", "english": "lose one's tongue", "type": "短语", "keyWords": ["tongue"] },
    { "chinese": "adv.今夜，今晚；n.[U]今夜，今晚", "english": "tonight /təˈnaɪt/ ad.；n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "adv.也（否定句中用either）；太", "english": "too /tuː/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "太……，远过于（后接形容词/副词）", "english": "far too + a./ad.", "type": "短语", "keyWords": ["too"] },
    { "chinese": "有些太（后接形容词/副词）", "english": "rather too + a./ad.", "type": "短语", "keyWords": ["too"] },
    { "chinese": "太……（后接形容词/副词）", "english": "much too + a./ad.", "type": "短语", "keyWords": ["too"] },
    { "chinese": "实在太（快/早等）", "english": "all too (quickly/ soon)", "type": "短语", "keyWords": ["too"] },
    { "chinese": "我也到过纽约。", "english": "I, too, have been to New York.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "此事的确了结得太快了！", "english": "It was over all too soon!", "type": "句子", "keyWords": ["too"] },
    { "chinese": "对我们别太厉害了。", "english": "Don't be too hard on us.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "（对于……说）对付不了，过分；无法承受（后接不可数名词）", "english": "too much (+n.(U)) (for...)", "type": "短语", "keyWords": ["too"] },
    { "chinese": "全天工作她恐怕吃不消。", "english": "A full-time job may be too much for her.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "太……（表肯定）", "english": "only/but all too...", "type": "短语", "keyWords": ["too"] },
    { "chinese": "他非常愿意帮助你。", "english": "He's only too willing to help you.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "他很细心，不会不注意到这点的。", "english": "He is too careful not to have noticed it.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "……也不过分", "english": "can't...too...", "type": "短语", "keyWords": ["too"] },
    { "chinese": "在这种问题上再怎么小心都不为过。", "english": "One can't be too careful in matters like this.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "我们再怎么强调保护眼睛的重要性也不为过。", "english": "We cannot emphasize the importance of protecting our eyes too much.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "n.[C]工具；器具；器械；手段", "english": "tool /tuːl/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.(pl.teeth)齿；n.[C]牙刷；n.[U]牙膏；n.[U]牙痛（可与a连用）", "english": "tooth /tuːθ/ n.(pl.teeth)；toothbrush n.[C]；toothpaste n.[U]；toothache n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "武装到牙齿", "english": "be armed to the teeth", "type": "短语", "keyWords": ["tooth"] },
    { "chinese": "张牙舞爪；作威胁状", "english": "show one's teeth", "type": "短语", "keyWords": ["tooth"] },
    { "chinese": "n.[C]顶部，顶点，顶端；上部/端/面；最高点；最高地位；adj.最好的；最上面的；最优良的；最重要的；vt.高过；胜过；成……之冠/首；给……加盖（或顶）", "english": "top /tɒp/ n.[C]；a.；vt.", "type": "单词", "keyWords": [] },
    { "chinese": "在……顶上/上面", "english": "on top of", "type": "短语", "keyWords": ["top"] },
    { "chinese": "优等生，尖子学生", "english": "top student", "type": "短语", "keyWords": ["top"] },
    { "chinese": "最高级的", "english": "top-class", "type": "短语", "keyWords": ["top"] },
    { "chinese": "最高级别的", "english": "top-level", "type": "短语", "keyWords": ["top"] },
    { "chinese": "绝密的", "english": "top secret", "type": "短语", "keyWords": ["top"] },
    { "chinese": "在……顶部/上（反at the bottom of）", "english": "at the top of", "type": "短语", "keyWords": ["top"] },
    { "chinese": "非常愉快或自豪", "english": "feel on top of the world", "type": "短语", "keyWords": ["top"] },
    { "chinese": "他比他父亲高出半头。", "english": "He tops his father by half a head.", "type": "句子", "keyWords": ["top"] },
    { "chinese": "她在班里排名第一。", "english": "She topped her class.", "type": "句子", "keyWords": ["top"] },
    { "chinese": "n.[C]题目；话题，主题", "english": "topic /ˈtɒpɪk/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]火把，火炬；（英）手电筒", "english": "torch /tɔːtʃ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]龙卷风；旋风；飓风", "english": "tornado /tɔːˈneɪdəʊ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.总（计）的；全部的；完全的；n.[C]总数，总计；v.合计；计算……的总和；adv.完全；彻底地", "english": "total /ˈtəʊtl/ a.；n.[C]；v.；totally ad.", "type": "单词", "keyWords": [] },
    { "chinese": "彻头彻尾的傻瓜", "english": "a total fool", "type": "短语", "keyWords": ["total"] },
    { "chinese": "彻底的失败", "english": "a total failure", "type": "短语", "keyWords": ["total"] },
    { "chinese": "总计（近in all）", "english": "in total", "type": "短语", "keyWords": ["total"] },
    { "chinese": "总产量", "english": "total output", "type": "短语", "keyWords": ["total"] },
    { "chinese": "总计30美元（近add up to, amount to, come to）", "english": "total (1) 30", "type": "短语", "keyWords": ["total"] },
    { "chinese": "我完全同意。", "english": "I totally agree.", "type": "句子", "keyWords": ["totally"] },
    { "chinese": "v.触摸；接触；涉及；感动（见affect）；adj.令人感动的；adj.受感动的", "english": "touch /tʌtʃ/ v.；touching a.；touched a.", "type": "单词", "keyWords": [] },
    { "chinese": "与……有/无联系；了解/不了解", "english": "be in/out of touch with...", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "使A与B取得联系", "english": "bring A into touch with B", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "与……取得联系", "english": "get in touch with...", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "与……保持联系", "english": "keep in touch with...", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "与……失去联系", "english": "lose touch with...", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "一碰就倒", "english": "fall at a touch", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "adj.坚韧的；能吃苦耐劳的；难做的；固执的；顽强的；强硬的；蛮横的；v.使……坚韧", "english": "tough /tʌf/ a.；toughen v.", "type": "单词", "keyWords": [] },
    { "chinese": "嚼不动的肉", "english": "tough meat", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "棘手的工作", "english": "a tough job", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "一个严冬", "english": "a tough winter", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "难伺候的顾客", "english": "a tough customer", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "无赖", "english": "a tough guy", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "意志坚强的人", "english": "a tough-minded person", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "n.[C]/v.旅行；参观；游览；观光；游历；巡回演出/比赛", "english": "tour /tʊə/ n.[C]/v.", "type": "单词", "keyWords": [] },
    { "chinese": "环球旅行", "english": "a round-the-world tour", "type": "短语", "keyWords": ["tour"] },
    { "chinese": "巡回音乐会", "english": "a concert tour", "type": "短语", "keyWords": ["tour"] },
    { "chinese": "漫游；巡回；周游世界", "english": "go on/take a tour of the world", "type": "短语", "keyWords": ["tour"] },
    { "chinese": "周游（世界）", "english": "make a tour of (the world)", "type": "短语", "keyWords": ["tour"] },
    { "chinese": "n.[C]旅游的（人）；游览的（人）；观光的（人）；n.[U]旅游；旅游业", "english": "tourist /ˈtʊərɪst/ n.[C]；tourism n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "prep.朝，向", "english": "toward(s) /təˈwɔːd(z)/ prep.", "type": "单词", "keyWords": [] },
    { "chinese": "将近晚上时天开始下雨了。", "english": "Towards evening, it began to rain.", "type": "句子", "keyWords": ["toward(s)"] },
    { "chinese": "n.[C]毛巾", "english": "towel /ˈtaʊəl/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]塔；塔楼；（机场的）塔台", "english": "tower /ˈtaʊə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "瞭望楼；机场指挥塔", "english": "a watch tower；the airport control tower", "type": "短语", "keyWords": ["tower"] },
    { "chinese": "万丈高楼平地起。", "english": "The highest towers begin from the ground.", "type": "句子", "keyWords": ["tower"] },
    { "chinese": "n.[C]城镇；（不用冠词）市（商业）中心，城区", "english": "town /taʊn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "进城", "english": "go to town", "type": "短语", "keyWords": ["town"] },
    { "chinese": "在城里", "english": "in town", "type": "短语", "keyWords": ["town"] },
    { "chinese": "不在城里，在乡下", "english": "out of town", "type": "短语", "keyWords": ["town"] },
    { "chinese": "全体市民都很愤慨。", "english": "The whole town was angry.", "type": "句子", "keyWords": ["town"] },
    { "chinese": "n.[C]镇民；市民", "english": "townsman /ˈtaʊnzmən/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]玩具；无价值的东西", "english": "toy /tɔɪ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "玩具车", "english": "a toy car", "type": "短语", "keyWords": ["toy"] },
    { "chinese": "n.[C]痕迹，踪迹；足迹；小径，小路；少量；v.跟踪；追踪；追溯(back)", "english": "trace /treɪs/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "岁月在她脸上留下了痕迹。", "english": "Age has left its traces on her face.", "type": "句子", "keyWords": ["trace"] },
    { "chinese": "一丝笑意", "english": "a mere trace of a smile", "type": "短语", "keyWords": ["trace"] },
    { "chinese": "追查谣言的根源", "english": "trace a rumour to its source", "type": "短语", "keyWords": ["trace"] },
    { "chinese": "n.[C]路径，轨迹；足迹；车辙；小道；跑道；轨道；田径运动；v.跟踪", "english": "track /træk/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "径赛项目", "english": "track events=tracks", "type": "短语", "keyWords": ["track"] },
    { "chinese": "风暴的路径", "english": "the track of a storm", "type": "短语", "keyWords": ["track"] },
    { "chinese": "跟踪雪地里的足迹", "english": "follow the tracks in the snow", "type": "短语", "keyWords": ["track"] },
    { "chinese": "n.[C]拖拉机；牵引车", "english": "tractor /ˈtræktə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]贸易，商业；n.[C]行业；v.互相交换，与……进行交换；vi.从事贸易，进行交易；adj.贸易的，交易的；n.[C]商人", "english": "trade /treɪd/ n.[U]/[C]；v.；vi.；a.；trader n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "工会", "english": "trade union", "type": "短语", "keyWords": ["trade"] },
    { "chinese": "贸易谈判", "english": "trade talks", "type": "短语", "keyWords": ["trade"] },
    { "chinese": "用A换取B", "english": "trade A for B", "type": "短语", "keyWords": ["trade"] },
    { "chinese": "和某人做……生意", "english": "trade with sb. in sth.", "type": "短语", "keyWords": ["trade"] },
    { "chinese": "n.[C]商标", "english": "trademark /ˈtreɪdmɑːk/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]传统；adj.传统的；习俗的；惯例的", "english": "tradition /trəˈdɪʃn/ n.[C][U]；traditional a.", "type": "单词", "keyWords": [] },
    { "chinese": "按照传统", "english": "by tradition", "type": "短语", "keyWords": ["tradition"] },
    { "chinese": "中医", "english": "traditional Chinese medicine", "type": "短语", "keyWords": ["traditional"] },
    { "chinese": "n.[U]交通（量）；通行，往来；空中交通", "english": "traffic /ˈtræfɪk/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "交通指示灯", "english": "traffic lights", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "交通规则", "english": "traffic regulations/ rules", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "交通堵塞", "english": "a traffic jam", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "通车", "english": "be open to traffic", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "出交通事故", "english": "have traffic accidents", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "交通繁忙", "english": "full of heavy/much traffic", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "n.[C][U]悲剧；灾难，惨事；adj.悲剧的；悲惨的", "english": "tragedy /ˈtrædʒədi/ n.[C][U]；tragic a.", "type": "单词", "keyWords": [] },
    { "chinese": "某人的巨大不幸", "english": "a tragedy to sb.", "type": "短语", "keyWords": ["tragedy"] },
    { "chinese": "以惨祸而告终", "english": "end in tragedy", "type": "短语", "keyWords": ["tragedy"] },
    { "chinese": "v.训练；培养；锻炼；n.[C]火车，列车；一连串，一系列", "english": "train /treɪn/ v.；n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "为田径赛训练（运动员）", "english": "train (athletes) for track-and-field competitions", "type": "短语", "keyWords": ["train"] },
    { "chinese": "她在学习护理。", "english": "She is training to be a nurse.", "type": "句子", "keyWords": ["train"] },
    { "chinese": "在……换乘火车", "english": "change trains at...", "type": "短语", "keyWords": ["train"] },
    { "chinese": "一列快车", "english": "an express train", "type": "短语", "keyWords": ["train"] },
    { "chinese": "训练某人做某事", "english": "train sb. to do sth.", "type": "短语", "keyWords": ["train"] },
    { "chinese": "一连串事件", "english": "a train of events", "type": "短语", "keyWords": ["train"] },
    { "chinese": "n.[U]训练；锻炼；培养；n.[C]教练员；驯兽师", "english": "training /ˈtreɪnɪŋ/ n.[U]；trainer n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "表示“横穿，变化，转移”（前缀）", "english": "trans-（前缀）", "type": "单词", "keyWords": [] },
    { "chinese": "v.搬授；转移；转换；调动(to)", "english": "transfer /trænsˈfɜː/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "被调职", "english": "be transferred to another post", "type": "短语", "keyWords": ["transfer"] },
    { "chinese": "转让财产给某人", "english": "transfer property to a person", "type": "短语", "keyWords": ["transfer"] },
    { "chinese": "他已被从北京调到了上海。", "english": "He has been transferred from Beijing to Shanghai.", "type": "句子", "keyWords": ["transfer"] },
    { "chinese": "v.改造；改革；（使）彻底改变（形式、外表、性质、机能等）", "english": "transform /trænsˈfɔːm/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "v.译；转换；n.[U]翻译；n.[C]译文；v.把……翻译成……；把……变成……", "english": "translate /trænsˈleɪt/ v.；translation n.[U]/[C]；translate...into...", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]译员；翻译者；译码机", "english": "translator /trænsˈleɪtə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "vt.传送，输送；播送；遗传；vi.播送（或发射）信号；流传下来；n.[C][U]（无线电、电视等信号的）播送，发送；（电台或电视等）信息，广播；传递，传播，传染；n.[C]发射机，发射台；传播者，传递媒介", "english": "transmit /trænsˈmɪt/ vt.；vi.；transmission n.[C][U]；transmitter n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "数码相机拍摄、处理、传输图像的速度惊人。", "english": "The speed with which digital cameras can take, process, and transmit an image is great.", "type": "句子", "keyWords": ["transmit"] },
    { "chinese": "在一项长达12年的研究中，利亚布克和列兹尼科娃发现了蚂蚁可以传递非常复杂信息的证据。", "english": "In a twelve-year programme of work, Ryabko and Reznikova have found evidence that ants can transmit very complex messages.", "type": "句子", "keyWords": ["transmit"] },
    { "chinese": "v.（尤指）移植（植物、组织或器官等）", "english": "transplant /trænsˈplɑːnt/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "v.运输；运送；输送；n.[U]运输", "english": "transport /trænsˈpɔːt/ v.；/ˈtrænspɔːt/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]运输（系统）；公共交通（网）；客运；货运；[美]运输工具", "english": "transportation /ˌtrænspɔːˈteɪʃn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]陷阱，圈套，诡计；夹子；v.设圈套；诱骗某人；使陷于困境", "english": "trap /træp/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "陷入；被困在（近be stranded in）", "english": "be trapped in (a burning house)", "type": "短语", "keyWords": ["trap"] },
    { "chinese": "诱捕小偷", "english": "set a trap for the thieves (trap the thieves)", "type": "短语", "keyWords": ["trap"] },
    { "chinese": "v.旅行；（光、物）移动、走、行进（辨析见tour）；n.[U]旅行", "english": "travel /ˈtrævl/ v.；n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "周游世界", "english": "travel round the world", "type": "短语", "keyWords": ["travel"] },
    { "chinese": "旅行社；旅行包", "english": "travel agency；a travelling bag", "type": "短语", "keyWords": ["travel"] },
    { "chinese": "光比声音传得快。", "english": "Light travels faster than sound.", "type": "句子", "keyWords": ["travel"] },
    { "chinese": "n.[C]旅客；旅行者，游客", "english": "travel(l)er /ˈtrævlə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]托盘", "english": "tray /treɪ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]（或pl.）宝物；金银财宝；财富；珍品；v.珍惜；珍爱", "english": "treasure /ˈtreʒə/ n.[U](或pl.)；v.", "type": "单词", "keyWords": [] },
    { "chinese": "近来，找到失去的财宝的梦想几乎变成了现实。", "english": "Dreams of finding lost treasure almost came true recently.", "type": "句子", "keyWords": ["treasure"] },
    { "chinese": "他珍爱母亲送给他的表。", "english": "He treasures the watch his mother gave him.", "type": "句子", "keyWords": ["treasure"] },
    { "chinese": "v.对待，视为，看待；医治，医疗；处理；请客；n.[C]请客，款待；乐事", "english": "treat /triːt/ v.；n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "把某物/某人看作……；像对待……一样对待……", "english": "treat sth./sb. as...；treat...like...", "type": "短语", "keyWords": ["treat"] },
    { "chinese": "此产品不是用于治疗、治愈或预防任何疾病的。", "english": "This product is not intended to treat, cure or prevent any disease.", "type": "句子", "keyWords": ["treat"] },
    { "chinese": "给某人/自己用……来款待；舍得（吃、穿等）", "english": "treat sb./ oneself to...", "type": "短语", "keyWords": ["treat"] },
    { "chinese": "请某人吃一杯冰淇淋", "english": "treat sb. to an ice-cream", "type": "短语", "keyWords": ["treat"] },
    { "chinese": "她花了一天时间在乡间游玩。", "english": "She treated herself to a day in the country.", "type": "句子", "keyWords": ["treat"] },
    { "chinese": "这次我请客。", "english": "It's my treat this time.", "type": "句子", "keyWords": ["treat"] },
    { "chinese": "对一个生活在城市里的人来说，在乡下待上一天真是一件乐事。", "english": "A day in the country is a real treat for a city dweller.", "type": "句子", "keyWords": ["treat"] },
    { "chinese": "n.[U]对待；待遇；n.[C]治疗；疗法；疗程；n.[C][U]处理", "english": "treatment /ˈtriːtmənt/ n.[U]/[C]", "type": "单词", "keyWords": [] },
    { "chinese": "在治疗中", "english": "under treatment", "type": "短语", "keyWords": ["treatment"] },
    { "chinese": "流感新疗法", "english": "a new treatment for flu", "type": "短语", "keyWords": ["treatment"] },
    { "chinese": "n.[C]树；家谱，世系图", "english": "tree /triː/ n.[C]；a family tree", "type": "单词", "keyWords": [] },
    { "chinese": "谚：树倒在何处，就躺在何处。（指事物有其必然的规律）", "english": "谚：As a tree falls, so shall it lie.", "type": "句子", "keyWords": ["tree"] },
    { "chinese": "谚：观其果而知其树；观其行而知其人。", "english": "谚：A tree is known by its fruit.", "type": "句子", "keyWords": ["tree"] },
    { "chinese": "v.抖动，摇动，颤抖（辨析见shake）", "english": "tremble /ˈtrembl/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "因寒冷/愤怒/害怕而颤抖", "english": "tremble with cold/ anger/ fear", "type": "短语", "keyWords": ["tremble"] },
    { "chinese": "我一想到这件事就不寒而栗。", "english": "I tremble at the very thought of it.", "type": "句子", "keyWords": ["tremble", "thought"] },
    { "chinese": "颤抖的手", "english": "trembling hand", "type": "短语", "keyWords": ["tremble"] },
    { "chinese": "用颤抖的声音", "english": "in a trembling voice", "type": "短语", "keyWords": ["tremble"] },
    { "chinese": "adj.极大的，巨大的（近enormous, immense, huge, gigantic, colossal, vast）", "english": "tremendous /trəˈmendəs/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（路、河流等）走向；倾向；趋势；时尚；vi.倾向，趋向", "english": "trend /trend/ n.[C]；vi.", "type": "单词", "keyWords": [] },
    { "chinese": "海岸线的走向", "english": "the trend of a coast-line", "type": "短语", "keyWords": ["trend"] },
    { "chinese": "现代生活的趋势", "english": "the trend of modern living", "type": "短语", "keyWords": ["trend"] },
];
