const qgl285_292 = [
    { "chinese": "n.趋势；趋向", "english": "trend", "type": "单词", "keyWords": [] },
    { "chinese": "家庭逐渐缩小的趋向", "english": "the trend to/towards smaller families", "type": "短语", "keyWords": ["trend"] },
    { "chinese": "服装界最新潮流", "english": "the latest trend in fashion", "type": "短语", "keyWords": ["trend"] },
    { "chinese": "创新风；领导新潮流", "english": "set a/the trend", "type": "短语", "keyWords": ["trend"] },
    { "chinese": "n.诡计；戏法；技巧 v.欺诈", "english": "trick", "type": "单词", "keyWords": [] },
    { "chinese": "adj.诡计多端的", "english": "tricky", "type": "单词", "keyWords": [] },
    { "chinese": "我会玩魔术。", "english": "I can do magic tricks.", "type": "句子", "keyWords": ["trick"] },
    { "chinese": "学这行生意的诀窍", "english": "learn the tricks of the trade", "type": "短语", "keyWords": ["trick"] },
    { "chinese": "用计诱使某人（做）某事", "english": "trick/trap sb. into (doing) sth.", "type": "短语", "keyWords": ["trick"] },
    { "chinese": "他哄骗我给了他钱。", "english": "He tricked me into giving him the money.", "type": "句子", "keyWords": ["trick"] },
    { "chinese": "骗走某人某物", "english": "trick sb. out of sth.", "type": "短语", "keyWords": ["trick"] },
    { "chinese": "捉弄某人；开某人玩笑", "english": "play a trick on sb.", "type": "短语", "keyWords": ["trick"] },
    { "chinese": "n.旅行；旅程 vi.旅行；出行；轻捷地走；绊；倾斜；失误 vt.将…绊倒；使犯错误；意外触动", "english": "trip", "type": "单词", "keyWords": [] },
    { "chinese": "她说了声再见就连蹦带跳地沿路走了。", "english": "She said goodbye and tripped off along the road.", "type": "句子", "keyWords": ["trip"] },
    { "chinese": "她绊了一跤，膝盖磕在桌子上。", "english": "She tripped and banged her knee on the desk.", "type": "句子", "keyWords": ["trip"] },
    { "chinese": "这道难题我们答错了。", "english": "The difficult question tripped us.", "type": "句子", "keyWords": ["trip"] },
    { "chinese": "在去…的旅途中", "english": "on a trip to...", "type": "短语", "keyWords": ["trip"] },
    { "chinese": "去…旅行", "english": "make/go on/take a trip to...", "type": "短语", "keyWords": ["trip"] },
    { "chinese": "n.手推车；电车", "english": "trolley", "type": "单词", "keyWords": [] },
    { "chinese": "n.无轨电车", "english": "trolleybus", "type": "单词", "keyWords": [] },
    { "chinese": "n.军队，部队；一群，一队 vi.成群结队地走，排队前进", "english": "troop", "type": "单词", "keyWords": [] },
    { "chinese": "学生们列队走入礼堂。", "english": "The students trooped into the hall.", "type": "句子", "keyWords": ["troop"] },
    { "chinese": "adj.热带的", "english": "tropical", "type": "单词", "keyWords": [] },
    { "chinese": "热带植物", "english": "tropical plant", "type": "短语", "keyWords": ["tropical"] },
    { "chinese": "热带", "english": "tropical zone", "type": "短语", "keyWords": ["tropical"] },
    { "chinese": "n.麻烦；烦恼；困难；纷争；故障 v.（使）麻烦；（使）苦恼", "english": "trouble", "type": "单词", "keyWords": [] },
    { "chinese": "处于困境", "english": "be in trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "（使某人）陷入困境", "english": "get (sb.) into trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "心脏疾病", "english": "heart trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "制造麻烦，捣乱", "english": "make trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "自寻烦恼", "english": "ask for/look for trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "在（做）某事上有困难", "english": "have trouble/difficulty (in) doing/with sth.", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "麻烦某人去做某事", "english": "trouble sb. to do sth.", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "我能麻烦你把衬衫烫一下吗？", "english": "Can I trouble you to iron the shirt?", "type": "句子", "keyWords": ["trouble"] },
    { "chinese": "麻烦某人（做某事）", "english": "put sb. to the trouble (of doing sth.)", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "很抱歉，给你添了这么多麻烦。", "english": "I'm sorry to have put you to so much trouble.", "type": "句子", "keyWords": ["trouble"] },
    { "chinese": "不辞辛苦地做某事", "english": "take trouble to do sth.", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "多谢你费力相助。", "english": "Thank you for all the trouble you have taken to help me.", "type": "句子", "keyWords": ["trouble"] },
    { "chinese": "浑水摸鱼，趁机取利", "english": "fish in troubled waters", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "麻烦没来找你，就别去自找麻烦。", "english": "Never trouble trouble until trouble troubles you.", "type": "句子", "keyWords": ["trouble"] },
    { "chinese": "adj.令人讨厌的，令人烦恼的", "english": "troublesome", "type": "单词", "keyWords": [] },
    { "chinese": "n.长裤（复数）", "english": "trousers", "type": "单词", "keyWords": [] },
    { "chinese": "两条长裤", "english": "two pairs of trousers", "type": "短语", "keyWords": ["trousers"] },
    { "chinese": "n.卡车", "english": "truck", "type": "单词", "keyWords": [] },
    { "chinese": "adj.真的，真实的", "english": "true", "type": "单词", "keyWords": [] },
    { "chinese": "ad.真实地，不假", "english": "truly", "type": "单词", "keyWords": [] },
    { "chinese": "实现", "english": "come true", "type": "短语", "keyWords": ["true"] },
    { "chinese": "真实的；自然的", "english": "be true to life", "type": "短语", "keyWords": ["true"] },
    { "chinese": "逼真", "english": "be true to nature", "type": "短语", "keyWords": ["true"] },
    { "chinese": "信守诺言", "english": "be true to one's word", "type": "短语", "keyWords": ["true"] },
    { "chinese": "不到长城非好汉。", "english": "He who doesn't reach the Great Wall is not a true man.", "type": "句子", "keyWords": ["true"] },
    { "chinese": "符合于…，…适用", "english": "be true of", "type": "短语", "keyWords": ["true"] },
    { "chinese": "n.真理；真相，实情", "english": "truth", "type": "单词", "keyWords": [] },
    { "chinese": "说实在话，老实说", "english": "to tell the truth", "type": "短语", "keyWords": ["truth"] },
    { "chinese": "n.树干；皮箱；行李箱；大旅行箱；象鼻", "english": "trunk", "type": "单词", "keyWords": [] },
    { "chinese": "n.信任；信心；受托；托拉斯 v.信任，信赖；托付", "english": "trust", "type": "单词", "keyWords": [] },
    { "chinese": "他们建立了托拉斯，意图实现垄断。", "english": "They set up the trust in the hope of gaining a monopoly.", "type": "句子", "keyWords": ["trust"] },
    { "chinese": "v.尝试；努力；试图；试验；考验；审问；审判 n.尝试", "english": "try", "type": "单词", "keyWords": [] },
    { "chinese": "试穿", "english": "try...on", "type": "短语", "keyWords": ["try"] },
    { "chinese": "碰运气", "english": "try one's luck", "type": "短语", "keyWords": ["try"] },
    { "chinese": "值得一试", "english": "be worth a try", "type": "短语", "keyWords": ["try"] },
    { "chinese": "试试看，尝试一下", "english": "have a try", "type": "短语", "keyWords": ["try"] },
    { "chinese": "别逼得我忍无可忍。", "english": "Don't try my patience.", "type": "句子", "keyWords": ["try"] },
    { "chinese": "他们的案子将在下个月开审。", "english": "Their case will be tried in court next month.", "type": "句子", "keyWords": ["try"] },
    { "chinese": "尝试一下做某事", "english": "try doing", "type": "短语", "keyWords": ["try"] },
    { "chinese": "设法做成某事", "english": "try (one's best) to do", "type": "短语", "keyWords": ["try"] },
    { "chinese": "试用，试验…", "english": "try out (this method, a new car...)", "type": "短语", "keyWords": ["try"] },
    { "chinese": "第一次试着（滑雪）", "english": "try one's hand at (skiing...)", "type": "短语", "keyWords": ["try"] },
    { "chinese": "n.管子；软管；[英]地铁", "english": "tube", "type": "单词", "keyWords": [] },
    { "chinese": "试管", "english": "a test tube", "type": "短语", "keyWords": ["tube"] },
    { "chinese": "一管牙膏", "english": "a tube of toothpaste", "type": "短语", "keyWords": ["tube"] },
    { "chinese": "n.星期二", "english": "Tuesday", "type": "单词", "keyWords": [] },
    { "chinese": "n.学费；教学；讲授", "english": "tuition", "type": "单词", "keyWords": [] },
    { "chinese": "学费", "english": "tuition fee", "type": "短语", "keyWords": ["tuition"] },
    { "chinese": "n.曲子，曲调 v.调音，调整", "english": "tune", "type": "单词", "keyWords": [] },
    { "chinese": "调子准；入调", "english": "in tune", "type": "短语", "keyWords": ["tune"] },
    { "chinese": "走调", "english": "out of tune", "type": "短语", "keyWords": ["tune"] },
    { "chinese": "n.隧道，地道", "english": "tunnel", "type": "单词", "keyWords": [] },
    { "chinese": "n.轮替；交流；变化；转动；转弯 v.使转动；使转向；使变得", "english": "turn", "type": "单词", "keyWords": [] },
    { "chinese": "那位作家成为一名演员。", "english": "The writer turned actor.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "关掉", "english": "turn...off", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "使变成；翻译", "english": "turn...into...", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "开；打开", "english": "turn...on", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "转向；求助于；查阅（字典等）", "english": "turn to...", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "依次", "english": "in turn", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "转过去，转身", "english": "turn around (=turn round)", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "轮流；交替", "english": "by turns", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "在世纪之交", "english": "at the turn of the century", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "上交；拐弯进入", "english": "turn (...in)", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "转过脸不再看某人某物", "english": "turn away (from sb./sth.)", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "拒绝帮助某人；不准许某人进入", "english": "turn (sb.) away (from...)", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "医生是不能见死不救的。", "english": "A doctor cannot turn away a dying man.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "（把音量）调低；拒绝", "english": "turn...down", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "拒绝了我的帮助", "english": "turn down my offer/turn me down", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "关掉；生产，制造；原来（是）；最后证明是", "english": "turn...out", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "关掉了灯", "english": "turn out the lights", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "生产100000台电脑", "english": "turn out 100,000 computers", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "这项计划结果归于失败。", "english": "The plan turned out (to be) a failure.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "结果谈判真的是谈了两年。", "english": "It turned out that the negotiations did take two years.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "移交；仔细考虑；翻阅；翻身", "english": "turn...over", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "改过自新", "english": "turn over a new leaf", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "交出了非法资金", "english": "turn over the illegal funds", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "仔细考虑这个问题", "english": "turn over the problem in her mind", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "开大，调大；出现；查阅；卷起", "english": "turn up", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "文件迟早会找到的。", "english": "The papers will turn up sooner or later.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "出席会议", "english": "turn up at the meeting", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "在字典里查生词", "english": "turn/look up the new word in the dictionary", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "她的袖子卷起来了。", "english": "Her sleeves were turned up.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "轮流做某事", "english": "take turns at doing sth.", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "拐错弯", "english": "take the wrong turning", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "标志我们历史的一个转折点", "english": "mark a turning point in our history", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "n.家庭教师；（大学）导师 v.当…的教师；辅导，指导", "english": "tutor", "type": "单词", "keyWords": [] },
    { "chinese": "adj.私人教师的；大学导师的", "english": "tutorial", "type": "单词", "keyWords": [] },
    { "chinese": "ad.两次；两倍", "english": "twice", "type": "单词", "keyWords": [] },
    { "chinese": "有两倍之多", "english": "have twice as many", "type": "短语", "keyWords": ["twice"] },
    { "chinese": "n.双胞胎之一 adj.双胞胎的", "english": "twin", "type": "单词", "keyWords": [] },
    { "chinese": "v.旋转，转动；扭；搓；蜿蜒曲折地走；盘绕 n.拐弯；曲折；扭，拧", "english": "twist", "type": "单词", "keyWords": [] },
    { "chinese": "这条小路盘绕在小山上。", "english": "The path twisted up the hill.", "type": "句子", "keyWords": ["twist"] },
    { "chinese": "弯弯曲曲的路", "english": "a road full of twists and turns", "type": "短语", "keyWords": ["twist"] },
    { "chinese": "num.二 n.两个", "english": "two", "type": "单词", "keyWords": [] },
    { "chinese": "三三两两地，零星地", "english": "in twos and threes", "type": "短语", "keyWords": ["two"] },
    { "chinese": "（分成）两半", "english": "in two", "type": "短语", "keyWords": ["two"] },
    { "chinese": "一两（天…）", "english": "a (day) or two = one or two (days)", "type": "短语", "keyWords": ["two"] },
    { "chinese": "二人成伴，三人不欢。", "english": "Two is company, but three is none.", "type": "句子", "keyWords": ["two"] },
    { "chinese": "孤掌难鸣。", "english": "It takes two to make a quarrel.", "type": "句子", "keyWords": ["two"] },
    { "chinese": "n.类型；品种；典型 v.用打字机打 vi.打字", "english": "type", "type": "单词", "keyWords": [] },
    { "chinese": "n.打字机", "english": "typewriter", "type": "单词", "keyWords": [] },
    { "chinese": "n.打字", "english": "typing", "type": "单词", "keyWords": [] },
    { "chinese": "n.打字员", "english": "typist", "type": "单词", "keyWords": [] },
    { "chinese": "n.台风", "english": "typhoon", "type": "单词", "keyWords": [] },
    { "chinese": "adj.典型的，有代表性的；模范的；特有的；象征性的", "english": "typical", "type": "单词", "keyWords": [] },
    { "chinese": "一个有代表性的学生/例子", "english": "a typical pupil/example", "type": "短语", "keyWords": ["typical"] },
    { "chinese": "代表；象征", "english": "be typical of...", "type": "短语", "keyWords": ["typical"] },
    { "chinese": "他才会作出那样具有讽刺意味的回答。", "english": "That sarcastic reply is typical of him.", "type": "句子", "keyWords": ["typical"] },
    { "chinese": "典型的巴洛克时期的作品", "english": "a composition typical of the baroque period", "type": "短语", "keyWords": ["typical"] },
    { "chinese": "n.轮胎", "english": "tyre", "type": "单词", "keyWords": [] },
    { "chinese": "轮胎没气了", "english": "have got a flat tyre", "type": "短语", "keyWords": ["tyre"] },
    { "chinese": "n.不明飞行物，飞碟", "english": "UFO", "type": "单词", "keyWords": [] },
    { "chinese": "adj.难看的；丑陋的；令人不愉快的；丑恶的", "english": "ugly", "type": "单词", "keyWords": [] },
    { "chinese": "n.伞", "english": "umbrella", "type": "单词", "keyWords": [] },
    { "chinese": "在联合国的保护下", "english": "under the umbrella of the UN", "type": "短语", "keyWords": ["umbrella"] },
    { "chinese": "前缀“不；相反；除去”", "english": "un-", "type": "单词", "keyWords": [] },
    { "chinese": "adj.不能的；不会的", "english": "unable", "type": "单词", "keyWords": [] },
    { "chinese": "他想来，但他不能来，是吗？", "english": "He wanted to come but he was unable to, wasn't he?", "type": "句子", "keyWords": ["unable"] },
    { "chinese": "adj.未意识到的", "english": "unaware", "type": "单词", "keyWords": [] },
    { "chinese": "adj.难以置信的", "english": "unbelievable", "type": "单词", "keyWords": [] },
    { "chinese": "adj.失去知觉的；未发觉的", "english": "unconscious", "type": "单词", "keyWords": [] },
    { "chinese": "n.伯父；叔叔；叔父；舅舅；姨丈", "english": "uncle", "type": "单词", "keyWords": [] },
    { "chinese": "山姆大叔（美国、美国政府或美国人的绰号）", "english": "Uncle Sam", "type": "短语", "keyWords": ["uncle"] },
    { "chinese": "前缀“在…以下；不足的；次于”", "english": "under-", "type": "单词", "keyWords": [] },
    { "chinese": "prep.在…下面；低于", "english": "under", "type": "单词", "keyWords": [] },
    { "chinese": "在讨论/建设/考虑/调查/修理中/在进行中；在航行中", "english": "under discussion/construction/consideration/investigation/repair/way", "type": "短语", "keyWords": ["under"] },
    { "chinese": "在治疗中", "english": "under medical treatment", "type": "短语", "keyWords": ["under"] },
    { "chinese": "用假名", "english": "under a false name", "type": "短语", "keyWords": ["under"] },
    { "chinese": "v.经受；经历；遭受", "english": "undergo", "type": "单词", "keyWords": [] },
    { "chinese": "遭受巨大苦难", "english": "undergo great hardship", "type": "短语", "keyWords": ["undergo"] },
    { "chinese": "adj.地下的；秘密的 ad.在地下；秘密地", "english": "underground", "type": "单词", "keyWords": [] },
    { "chinese": "地铁", "english": "the underground", "type": "短语", "keyWords": ["underground"] },
    { "chinese": "地铁", "english": "the underground railway", "type": "短语", "keyWords": ["underground"] },
    { "chinese": "v.在…下面画线；强调", "english": "underline", "type": "单词", "keyWords": [] },
    { "chinese": "v.理解；懂；熟知；通晓；认为；推断", "english": "understand", "type": "单词", "keyWords": [] },
    { "chinese": "理解为什么做某事", "english": "understand doing sth.", "type": "短语", "keyWords": ["understand"] },
    { "chinese": "说明白自己的意思；使别人理解自己的意思", "english": "make oneself understood", "type": "短语", "keyWords": ["understand"] },
    { "chinese": "使某人理解某人或某事", "english": "make sb. understand sb./sth.", "type": "短语", "keyWords": ["understand"] },
    { "chinese": "adj.有理解能力的；通情达理的 n.理解（力）；同情，谅解", "english": "understanding", "type": "单词", "keyWords": [] },
    { "chinese": "达成协议；取得谅解", "english": "come to/arrive at/reach an understanding", "type": "短语", "keyWords": ["understanding"] },
    { "chinese": "会心的微笑", "english": "an understanding smile", "type": "短语", "keyWords": ["understanding"] },
    { "chinese": "通情达理的人；聪明的人", "english": "an understanding man", "type": "短语", "keyWords": ["understanding"] },
    { "chinese": "v.接受，着手；承担；答应，同意", "english": "undertake", "type": "单词", "keyWords": [] },
    { "chinese": "接受任务", "english": "undertake a task", "type": "短语", "keyWords": ["undertake"] },
    { "chinese": "答应再勘探", "english": "undertake to prospect again", "type": "短语", "keyWords": ["undertake"] },
    { "chinese": "自己承担照顾年长的亲戚", "english": "undertake oneself to care for an elderly relative", "type": "短语", "keyWords": ["undertake"] },
    { "chinese": "v.解开，松开；取消，废除", "english": "undo", "type": "单词", "keyWords": [] },
    { "chinese": "覆水难收。事已定局，无可挽回。", "english": "What is done cannot be undone.", "type": "句子", "keyWords": ["undo"] },
    { "chinese": "adj.不幸的；令人遗憾的", "english": "unfortunate", "type": "单词", "keyWords": [] },
    { "chinese": "ad.不幸地", "english": "unfortunately", "type": "单词", "keyWords": [] },
    { "chinese": "n.制服；军服 adj.一致的，一式的", "english": "uniform", "type": "单词", "keyWords": [] },
    { "chinese": "穿着校服的学生", "english": "students dressed in school uniforms", "type": "短语", "keyWords": ["uniform"] },
    { "chinese": "大小和形状一样的东西", "english": "things of uniform size and shape", "type": "短语", "keyWords": ["uniform"] },
    { "chinese": "n.协会；联盟；团结；联合，合并", "english": "union", "type": "单词", "keyWords": [] },
    { "chinese": "中国作家协会", "english": "the Union of Chinese Writers", "type": "短语", "keyWords": ["union"] },
    { "chinese": "美满的婚姻", "english": "a happy union", "type": "短语", "keyWords": ["union"] },
    { "chinese": "工会", "english": "a trade union", "type": "短语", "keyWords": ["union"] },
    { "chinese": "学生会", "english": "student union", "type": "短语", "keyWords": ["union"] },
    { "chinese": "团结就是力量。", "english": "Union is strength.", "type": "句子", "keyWords": ["union"] },
    { "chinese": "adj.（同类中）独特的；唯一的", "english": "unique", "type": "单词", "keyWords": [] },
    { "chinese": "只有海岸区域才有的问题", "english": "a problem unique to coastal areas", "type": "短语", "keyWords": ["unique"] },
    { "chinese": "n.单元；单位", "english": "unit", "type": "单词", "keyWords": [] },
    { "chinese": "英镑是英国货币的标准单位。", "english": "The pound is the standard unit of money in Britain.", "type": "句子", "keyWords": ["unit"] },
    { "chinese": "v.联合；结合", "english": "unite", "type": "单词", "keyWords": [] },
    { "chinese": "adj.联合的；统一的；共同的", "english": "united", "type": "单词", "keyWords": [] },
    { "chinese": "作出共同努力", "english": "make united/joint efforts", "type": "短语", "keyWords": ["united"] },
    { "chinese": "联合；统一团结", "english": "unite...with...", "type": "短语", "keyWords": ["unite"] },
    { "chinese": "合即立，分即垮。", "english": "United we stand, divided we fall.", "type": "句子", "keyWords": ["united"] },
    { "chinese": "n.团结；统一（性），一致，协调", "english": "unity", "type": "单词", "keyWords": [] },
    { "chinese": "adj.普遍的；全世界的，宇宙的", "english": "universal", "type": "单词", "keyWords": [] },
    { "chinese": "ad.普遍地；到处", "english": "universally", "type": "单词", "keyWords": [] },
    { "chinese": "n.宇宙；世界", "english": "universe", "type": "单词", "keyWords": [] },
    { "chinese": "n.（综合性）大学", "english": "university", "type": "单词", "keyWords": [] },
    { "chinese": "adj.未知的；默默无闻的 n.未知的事物或人", "english": "unknown", "type": "单词", "keyWords": [] },
    { "chinese": "conj.除非", "english": "unless", "type": "单词", "keyWords": [] },
    { "chinese": "prep.不像，和…不同 adj.不同的，不相似的", "english": "unlike", "type": "单词", "keyWords": [] },
    { "chinese": "不打电话过来对他来说是不多见的。", "english": "It's unlike him not to call.", "type": "句子", "keyWords": ["unlike"] },
    { "chinese": "prep./conj.直到…为止", "english": "until", "type": "单词", "keyWords": [] },
    { "chinese": "在前些日子，我对这事一无所知/直到最近我才得知此事。", "english": "Until quite recently, I knew nothing at all about it.", "type": "句子", "keyWords": ["until"] },
    { "chinese": "一直到几年后瑞士人才凭着新型的斯沃奇系列表追赶上来，重新获得市场领先地位。", "english": "It was not until years later that the Swiss caught up and regained their leading position in the marketplace with the creation of Swatch watches.", "type": "句子", "keyWords": ["until"] },
    { "chinese": "Not until…+倒装结构", "english": "Not until...+inversion", "type": "短语", "keyWords": ["until"] },
    { "chinese": "直到1996年，奥斯陆和平协议创造了可能性，他才重返巴勒斯坦。", "english": "Not until 1996, after the Oslo peace agreement made it possible, did he return to Palestine.", "type": "句子", "keyWords": ["until"] },
    { "chinese": "ad.向上；向高处；直立；向北；完全；成碎片 prep.往…较高处；沿着", "english": "up", "type": "单词", "keyWords": [] },
    { "chinese": "举起手来！", "english": "Hands up!", "type": "句子", "keyWords": ["up"] },
    { "chinese": "时间到了。", "english": "Time's up.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "到伦敦去", "english": "up to London", "type": "短语", "keyWords": ["up"] },
    { "chinese": "怎么了？", "english": "What's up?", "type": "句子", "keyWords": ["up"] },
    { "chinese": "一直到", "english": "up until...", "type": "短语", "keyWords": ["up"] },
    { "chinese": "在床上坐起来", "english": "sit up in bed", "type": "短语", "keyWords": ["up"] },
    { "chinese": "到我这边来", "english": "come up to me", "type": "短语", "keyWords": ["up"] },
    { "chinese": "上上下下；来回地", "english": "up and down", "type": "短语", "keyWords": ["up"] },
    { "chinese": "在山的高处", "english": "high up in the mountains", "type": "短语", "keyWords": ["up"] },
    { "chinese": "已起床（状态）", "english": "be up", "type": "短语", "keyWords": ["up"] },
    { "chinese": "她已经起床半天了。", "english": "She has been up for hours.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "多达；直到；从事；取决于", "english": "up to", "type": "短语", "keyWords": ["up"] },
    { "chinese": "他可以在假期工作达四个月。", "english": "He can work for up to four months during his school break.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "直到现在为止，地球和它的卫星之间还没有建立任何直接联系。", "english": "Up to the present day no bond exists between the earth and its satellite.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "你昨天干什么去了？我打电话给你，但你家里没人。", "english": "What were you up to yesterday? I called you, but there wasn't anybody home.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "从清单上你确实能看到职位的价值有多大是由雇主决定的。", "english": "The list does show you that determining a job's value is up to the employer.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "因此，我的旅行到底是容易的还是困难的都是由你决定的。", "english": "So it is up to you to decide how easy or difficult you want my journey to be.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "adj.即将来临的", "english": "upcoming", "type": "单词", "keyWords": [] },
    { "chinese": "v.使现代化；更新", "english": "update", "type": "单词", "keyWords": [] },
    { "chinese": "prep.在…上（较正式，口语用on）", "english": "upon", "type": "单词", "keyWords": [] },
    { "chinese": "adj.较高的，上层的，上部的", "english": "upper", "type": "单词", "keyWords": [] },
    { "chinese": "上流社会", "english": "the upper class", "type": "短语", "keyWords": ["upper"] },
    { "chinese": "上唇", "english": "the upper lip", "type": "短语", "keyWords": ["upper"] },
    { "chinese": "尼罗河上游地区", "english": "the upper Nile", "type": "短语", "keyWords": ["upper"] },
    { "chinese": "高地地区", "english": "upper regions", "type": "短语", "keyWords": ["upper"] },
    { "chinese": "adj.最高的；最主要的", "english": "uppermost", "type": "单词", "keyWords": [] },
    { "chinese": "adj.竖直的；挺直的；正直的 ad.笔直，竖立着", "english": "upright", "type": "单词", "keyWords": [] },
    { "chinese": "坐直", "english": "hold yourself upright", "type": "短语", "keyWords": ["upright"] },
    { "chinese": "v.弄翻；打乱；打扰，使心烦意乱 adj.弄翻的；心烦的", "english": "upset", "type": "单词", "keyWords": [] },
    { "chinese": "打乱我们的计划/会议", "english": "upset our plan/the meeting", "type": "短语", "keyWords": ["upset"] },
    { "chinese": "弄翻一杯牛奶", "english": "upset a glass of milk", "type": "短语", "keyWords": ["upset"] },
    { "chinese": "感到不安", "english": "feel upset about sth.", "type": "短语", "keyWords": ["upset"] },
    { "chinese": "ad.在楼上；往楼上", "english": "upstairs", "type": "单词", "keyWords": [] },
    { "chinese": "adj.现代的；最新的", "english": "up-to-date", "type": "单词", "keyWords": [] },
    { "chinese": "adj.向上的 ad.向上", "english": "upward", "type": "单词", "keyWords": [] },
    { "chinese": "ad.向上", "english": "upwards", "type": "单词", "keyWords": [] },
    { "chinese": "n.铀", "english": "uranium", "type": "单词", "keyWords": [] },
    { "chinese": "adj.城市的；市内的", "english": "urban", "type": "单词", "keyWords": [] },
    { "chinese": "v.催促；推进，鼓励", "english": "urge", "type": "单词", "keyWords": [] },
    { "chinese": "赶马往前跑", "english": "urge a horse on", "type": "短语", "keyWords": ["urge"] },
    { "chinese": "他催促她休息。", "english": "He urged her to rest.", "type": "句子", "keyWords": ["urge"] },
    { "chinese": "adj.急迫的；紧要的", "english": "urgent", "type": "单词", "keyWords": [] },
    { "chinese": "n.紧急，紧迫", "english": "urgency", "type": "单词", "keyWords": [] },
    { "chinese": "pron.（宾格）我们", "english": "us", "type": "单词", "keyWords": [] },
    { "chinese": "n.使用；用法；惯用法；习语", "english": "usage", "type": "单词", "keyWords": [] },
    { "chinese": "n.使用；用处，好处；用途 v.使用", "english": "use", "type": "单词", "keyWords": [] },
    { "chinese": "开始被使用", "english": "come into use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "使用着", "english": "in use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "停止被使用", "english": "go out of use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "不再使用了", "english": "out of use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "开始使用", "english": "put sth. to use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "开始使用（某物）", "english": "bring sth. into use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "（充分）利用", "english": "make (full/good) use of = make the most of", "type": "短语", "keyWords": ["use"] },
    { "chinese": "有用", "english": "be of (no, little...) use to sb./sth.", "type": "短语", "keyWords": ["use"] },
    { "chinese": "做某事是无济于事的", "english": "It's/There's no use/good doing sth.", "type": "短语", "keyWords": ["use"] },
    { "chinese": "（被）用于", "english": "be used to do sth./for (doing) sth.", "type": "短语", "keyWords": ["use"] },
    { "chinese": "用尽", "english": "use...up", "type": "短语", "keyWords": ["use"] },
    { "chinese": "v.惯常（仅用过去时，后接不定式）", "english": "used", "type": "单词", "keyWords": [] },
    { "chinese": "adj.已适应，已习惯（to doing sth.）；用旧了的", "english": "used", "type": "单词", "keyWords": [] },
    { "chinese": "过去常常做", "english": "used to do sth.", "type": "短语", "keyWords": ["used"] },
    { "chinese": "习惯于（做）某事", "english": "be/get/become used/accustomed to (doing) sth.", "type": "短语", "keyWords": ["used"] },
    { "chinese": "出售旧汽车", "english": "sell used cars", "type": "短语", "keyWords": ["used"] },
    { "chinese": "adj.有用的；有益的", "english": "useful", "type": "单词", "keyWords": [] },
    { "chinese": "n.有用；有益", "english": "usefulness", "type": "单词", "keyWords": [] },
    { "chinese": "adj.无用的；无益的；无价值的", "english": "useless", "type": "单词", "keyWords": [] },
    { "chinese": "n.无用；无益", "english": "uselessness", "type": "单词", "keyWords": [] },
    { "chinese": "adj.通常的", "english": "usual", "type": "单词", "keyWords": [] },
    { "chinese": "ad.通常", "english": "usually", "type": "单词", "keyWords": [] },
    { "chinese": "像往常一样", "english": "as usual", "type": "短语", "keyWords": ["usual"] },
    { "chinese": "比往常", "english": "than usual", "type": "短语", "keyWords": ["usual"] },
    { "chinese": "n.空；空白；（职位）空缺；没表情，失神", "english": "vacancy", "type": "单词", "keyWords": [] },
    { "chinese": "对不起，职员的空缺已有人补上。", "english": "Sorry, the vacancy in the office has been filled.", "type": "句子", "keyWords": ["vacancy"] },
    { "chinese": "脸上茫然若失的神情", "english": "a look of vacancy on his face", "type": "短语", "keyWords": ["vacancy"] },
    { "chinese": "adj.空（闲）的；空白的；（职位）空缺的；没表情的，失神的", "english": "vacant", "type": "单词", "keyWords": [] },
    { "chinese": "空缺职位", "english": "a vacant position", "type": "短语", "keyWords": ["vacant"] },
    { "chinese": "茫然的凝视", "english": "a vacant stare", "type": "短语", "keyWords": ["vacant"] },
    { "chinese": "这家旅馆有空房间吗？", "english": "Are there any rooms vacant in this hotel?", "type": "句子", "keyWords": ["vacant"] },
    { "chinese": "n.休假；假期", "english": "vacation", "type": "单词", "keyWords": [] },
    { "chinese": "在休假", "english": "on vacation", "type": "短语", "keyWords": ["vacation"] },
    { "chinese": "adj.含糊的；不明确的", "english": "vague", "type": "单词", "keyWords": [] },
    { "chinese": "徒劳，徒然，枉然", "english": "in vain", "type": "短语", "keyWords": [] },
    { "chinese": "n.山谷；溪谷；流域", "english": "valley", "type": "单词", "keyWords": [] },
    { "chinese": "长江流域", "english": "the Yangtze valley", "type": "短语", "keyWords": ["valley"] },
    { "chinese": "adj.有效的；具有法律效力的", "english": "valid", "type": "单词", "keyWords": [] },
    { "chinese": "三个月有效", "english": "be valid for three months", "type": "短语", "keyWords": ["valid"] },
    { "chinese": "adj.有价值的；很有用的", "english": "valuable", "type": "单词", "keyWords": [] },
    { "chinese": "n.价值；重要性；面值；价值观 v.给…估价；重视，珍视", "english": "value", "type": "单词", "keyWords": [] },
    { "chinese": "对某人有很大价值", "english": "be of great value to sb.", "type": "短语", "keyWords": ["value"] },
    { "chinese": "我们基本的价值观和利益", "english": "our basic values and interests", "type": "短语", "keyWords": ["value"] },
    { "chinese": "他估计这枚戒指价值800美元。", "english": "He valued the ring at $800.", "type": "句子", "keyWords": ["value"] },
    { "chinese": "我很看重你的劝告。", "english": "I value your advice.", "type": "句子", "keyWords": ["value"] },
    { "chinese": "评价不高；不怎么重视", "english": "put little value on/upon...", "type": "短语", "keyWords": ["value"] },
    { "chinese": "井干方知水可贵。", "english": "We never know the value of water till the well is dry.", "type": "句子", "keyWords": ["value"] },
    { "chinese": "adj.没有价值的；毫无用处的", "english": "valueless", "type": "单词", "keyWords": [] },
    { "chinese": "n.有篷载重卡车，运货车", "english": "van", "type": "单词", "keyWords": [] },
    { "chinese": "n.蒸气，水汽；雾", "english": "vapour", "type": "单词", "keyWords": [] },
    { "chinese": "n.品种，种类；各种，种种；变化，多样化", "english": "variety", "type": "单词", "keyWords": [] },
    { "chinese": "各种各样的，种类繁多的", "english": "a considerable/great/wide variety of", "type": "短语", "keyWords": ["variety"] },
    { "chinese": "adj.不同的；各种各样的；多方面的", "english": "various", "type": "单词", "keyWords": [] },
    { "chinese": "v.使不同；改变；使多样化；呈差异；变化，有不同", "english": "vary", "type": "单词", "keyWords": [] }
];
