const qgl301_308 = [
    { "chinese": "a. (向)西方的", "english": "western /ˈwestən/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 西方人", "english": "westerner", "type": "单词", "keyWords": [] },
    { "chinese": "a. 湿的；(油漆等)未干的；多雨的；雨天的；v. 弄湿；使潮湿；vi. 变湿；变潮", "english": "wet /wet/", "type": "单词", "keyWords": [] },
    { "chinese": "漆未干！", "english": "Wet paint!", "type": "句子", "keyWords": ["wet"] },
    { "chinese": "尿床", "english": "wet the bed", "type": "短语", "keyWords": ["wet"] },
    { "chinese": "n. [C] 鲸", "english": "whale /weɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "pron. (疑问代词)什么，什么样的人(事、物等)", "english": "what /wɒt/", "type": "单词", "keyWords": [] },
    { "chinese": "某人/某物怎么样？", "english": "What is sb./sth. like?", "type": "句子", "keyWords": ["what"] },
    { "chinese": "他是做什么的？", "english": "What is he?", "type": "句子", "keyWords": ["what"] },
    { "chinese": "如果…怎么样？", "english": "What if...", "type": "短语", "keyWords": ["what"] },
    { "chinese": "假若下起雨来，我们又没处避雨怎么办？", "english": "What if it rains when we can't get under shelter?", "type": "句子", "keyWords": ["what"] },
    { "chinese": "用光了我仅有的一点", "english": "use up what little I got", "type": "短语", "keyWords": ["what"] },
    { "chinese": "我愿尽绵薄之力予以相助。", "english": "I will give you what little I can.", "type": "句子", "keyWords": ["what"] },
    { "chinese": "每个人都应该做自己认为是正确的事。", "english": "Everyone should do what he thinks is right.", "type": "句子", "keyWords": ["what"] },
    { "chinese": "她有做医生的必要条件。", "english": "She has what it takes to be a doctor.", "type": "句子", "keyWords": ["what"] },
    { "chinese": "（插入语）加之，而且", "english": "what's more", "type": "短语", "keyWords": ["what"] },
    { "chinese": "多漂亮的花儿！", "english": "What pretty flowers!", "type": "句子", "keyWords": ["what"] },
    { "chinese": "多么大的房子！", "english": "What a big house! = How big the house is!", "type": "句子", "keyWords": ["what"] },
    { "chinese": "（征求意见，询问消息等）好不好？", "english": "What about...?", "type": "短语", "keyWords": ["what"] },
    { "chinese": "这有什么关系？", "english": "What does it matter?", "type": "句子", "keyWords": ["what"] },
    { "chinese": "不管发生什么事", "english": "come what may", "type": "短语", "keyWords": ["what"] },
    { "chinese": "不管发生什么事，我们都会支持你们。", "english": "We will stand by you, come what may.", "type": "句子", "keyWords": ["what"] },
    { "chinese": "pron. 无论什么；任何…的事物；a. 任何…的；无论怎样的", "english": "whatever /wɒtˈevə/", "type": "单词", "keyWords": [] },
    { "chinese": "你喜欢做什么就做什么。", "english": "Do whatever you please.", "type": "句子", "keyWords": ["whatever"] },
    { "chinese": "她将所有剩下的精力都用到这项任务上。", "english": "She applied whatever strength she had left to the task.", "type": "句子", "keyWords": ["whatever"] },
    { "chinese": "剩下来的所有的东西都是你的。", "english": "Whatever is left over is yours. = Anything that is left over is yours. = Whatever is left over, it is yours. = No matter what is left over, it is yours.", "type": "句子", "keyWords": ["whatever"] },
    { "chinese": "他学习任何语言都会遇到困难，不论是希腊语、汉语或是其他语言。", "english": "He has difficulty in learning any language - Greek, Chinese, or whatever.", "type": "句子", "keyWords": ["whatever"] },
    { "chinese": "n. [U] 小麦", "english": "wheat /wiːt/", "type": "单词", "keyWords": [] },
    { "chinese": "种植小麦", "english": "grow wheat", "type": "短语", "keyWords": ["wheat"] },
    { "chinese": "n. [C] 车轮；方向盘；v. 旋动；转向；转动", "english": "wheel /wiːl/", "type": "单词", "keyWords": [] },
    { "chinese": "（病人等用的）轮椅", "english": "wheelchair", "type": "短语", "keyWords": ["wheel"] },
    { "chinese": "驾驶员，舵手，指挥者", "english": "the man at the wheel", "type": "短语", "keyWords": ["wheel"] },
    { "chinese": "ad. 什么时候，何时；conj. 就在这时；在…时；尽管", "english": "when /wen/", "type": "单词", "keyWords": [] },
    { "chinese": "从什么时候起事情像这样的？", "english": "Since when has this been going on?", "type": "句子", "keyWords": ["when"] },
    { "chinese": "那是汽车很罕见的时代。", "english": "It was a time when motorcars were rare.", "type": "句子", "keyWords": ["when"] },
    { "chinese": "一个月前她来过信，从那时起我们就没听到过她的消息。", "english": "She wrote a month ago, since when we've heard nothing about her.", "type": "句子", "keyWords": ["when"] },
    { "chinese": "正要…这时…", "english": "be about to do... / be on the point of doing... / be doing... when...", "type": "短语", "keyWords": ["when"] },
    { "chinese": "我们正要离开，（这时）突然下起雨来了。", "english": "We were about to leave when it started to rain. = We were leaving when it started to rain.", "type": "句子", "keyWords": ["when"] },
    { "chinese": "妻子继续问了好多问题，这时她突然发现丈夫帽子上有个洞。", "english": "The wife went on asking questions, when she suddenly noticed a big hole in her husband's hat.", "type": "句子", "keyWords": ["when"] },
    { "chinese": "…刚…就…", "english": "Hardly / Scarcely... when...", "type": "短语", "keyWords": ["when"] },
    { "chinese": "我刚开门他就告诉了我此事。", "english": "Hardly / Scarcely had I opened the door when he told me about it.", "type": "句子", "keyWords": ["when"] },
    { "chinese": "他不用功的话怎么拿高分呢？", "english": "How can he get good grades when he won't study?", "type": "句子", "keyWords": ["when"] },
    { "chinese": "尽管她应该继续下去，她却突然停住了。", "english": "She stopped short when she ought to have continued.", "type": "句子", "keyWords": ["when"] },
    { "chinese": "conj. 无论何时；每当（近no matter when）", "english": "whenever /wenˈevə/", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 在（往）哪里；（表语、状语从句）在…的地方", "english": "where /weə/", "type": "单词", "keyWords": [] },
    { "chinese": "conj. 无论在哪里；无论什么情况下（近no matter where）", "english": "wherever /weərˈevə/", "type": "单词", "keyWords": [] },
    { "chinese": "conj. 是否（接名词从句）；不管…还…（接让步状语从句，相当于no matter whether）", "english": "whether /ˈweðə/", "type": "单词", "keyWords": [] },
    { "chinese": "不管她是赢是输，这都是她最后一次参加锦标赛。", "english": "Whether (= No matter whether) she wins or loses, this is her last tournament.", "type": "句子", "keyWords": ["whether"] },
    { "chinese": "pron./a. （接名词从句）哪（个）；（接定语从句，指代先行词）那个，那些", "english": "which /wɪtʃ/", "type": "单词", "keyWords": [] },
    { "chinese": "哪个孩子知道答案？", "english": "Which child knows the answer?", "type": "句子", "keyWords": ["which"] },
    { "chinese": "这对双胞胎长得太像了，我简直分不清谁是谁了。", "english": "The twins are so alike that I can't tell which is which.", "type": "句子", "keyWords": ["which"] },
    { "chinese": "天开始下雨了，我们跑了起来。", "english": "It started to rain, at which point we ran.", "type": "句子", "keyWords": ["which"] },
    { "chinese": "他改变了主意，这使我很生气。", "english": "He changed his mind, which made me very angry.", "type": "句子", "keyWords": ["which"] },
    { "chinese": "pron. 无论哪个；无论哪些", "english": "whichever /wɪtʃˈevə/", "type": "单词", "keyWords": [] },
    { "chinese": "你们之中随便谁要，我就给谁。", "english": "I'll give it to whichever of you wants it.", "type": "句子", "keyWords": ["whichever"] },
    { "chinese": "不论他怎么做，结果都一样。", "english": "It produced the same result, whichever way he did it.（接状语从句）= No matter which way he did it, it produced the same result.", "type": "句子", "keyWords": ["whichever"] },
    { "chinese": "随你拿哪一个。", "english": "Take whichever you like. = Whichever you like, take it. = No matter which you like, take it.", "type": "句子", "keyWords": ["whichever"] },
    { "chinese": "conj. …时候，…同时；虽然；然而；n. [C] 一会儿，一段时间", "english": "while /waɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "过了一会儿；不久", "english": "after a while", "type": "短语", "keyWords": ["while"] },
    { "chinese": "片刻", "english": "for a while", "type": "短语", "keyWords": ["while"] },
    { "chinese": "有时；偶尔", "english": "once in a while", "type": "短语", "keyWords": ["while"] },
    { "chinese": "完成这项工作花了我许多时间。", "english": "It took me quite a long / good while to finish the work.", "type": "句子", "keyWords": ["while"] },
    { "chinese": "这阵子你一直在做什么？", "english": "What have you been doing all this while?", "type": "句子", "keyWords": ["while"] },
    { "chinese": "值得花费时间，值得（干）（近worthwhile）", "english": "worth (one's) while", "type": "短语", "keyWords": ["while"] },
    { "chinese": "这个任务值得你干吗？", "english": "Is it worth your while undertaking / to undertake this task?", "type": "句子", "keyWords": ["while"] },
    { "chinese": "有些人喜欢咖啡，而有些人喜欢茶。", "english": "Some people like coffee, while others like tea.", "type": "句子", "keyWords": ["while"] },
    { "chinese": "尽管，虽然（常位于句首）", "english": "While...", "type": "短语", "keyWords": ["while"] },
    { "chinese": "虽然我们意见相左，但我们还是朋友。", "english": "While we don't agree, we remain friends.", "type": "句子", "keyWords": ["while"] },
    { "chinese": "n. [C] 鞭子；（常用whipping）鞭打，抽打；v. 鞭打，抽打", "english": "whip /wɪp/", "type": "单词", "keyWords": [] },
    { "chinese": "策马前进", "english": "whip the horses on", "type": "短语", "keyWords": ["whip"] },
    { "chinese": "冰冷的寒风鞭笞着我的脸。", "english": "Icy winds whipped my face.", "type": "句子", "keyWords": ["whip"] },
    { "chinese": "v. 使旋转；vi. 旋转；n. [C]（只用单）旋转", "english": "whirl /wɜːl/", "type": "单词", "keyWords": [] },
    { "chinese": "风把树叶卷到了空中。", "english": "The wind whirled the leaves into the air.", "type": "句子", "keyWords": ["whirl"] },
    { "chinese": "她猛地转过身来面对着他。", "english": "She whirled around to face him.", "type": "句子", "keyWords": ["whirl"] },
    { "chinese": "我头晕。", "english": "My head is in a whirl!", "type": "句子", "keyWords": ["whirl"] },
    { "chinese": "v./n. [C] 低语；耳语；密谈；（风等）发出飒飒声；v. 低声说", "english": "whisper /ˈwɪspə/", "type": "单词", "keyWords": [] },
    { "chinese": "她对我悄悄说了这个消息。", "english": "She whispered the news in my ear.", "type": "句子", "keyWords": ["whisper"] },
    { "chinese": "他的冒险经历都传遍了。", "english": "His adventures have been whispered everywhere.", "type": "句子", "keyWords": ["whisper"] },
    { "chinese": "据秘密传闻", "english": "It is whispered that...", "type": "短语", "keyWords": ["whisper"] },
    { "chinese": "风在松树林中飒飒作响。", "english": "The wind whispered in the pines.", "type": "句子", "keyWords": ["whisper"] },
    { "chinese": "她是低声说的。", "english": "She said it in a whisper.", "type": "句子", "keyWords": ["whisper"] },
    { "chinese": "n. [C] 口哨，哨子；汽笛声；v. 吹口哨，吹哨子；鸣（汽）笛；啸叫", "english": "whistle /ˈwɪsl/", "type": "单词", "keyWords": [] },
    { "chinese": "鸣笛；吹口哨", "english": "blow / give a whistle", "type": "短语", "keyWords": ["whistle"] },
    { "chinese": "吹出一个调子", "english": "whistle a tune", "type": "短语", "keyWords": ["whistle"] },
    { "chinese": "他向他的狗吹了个口哨。", "english": "He whistled to his dog.", "type": "句子", "keyWords": ["whistle"] },
    { "chinese": "风从窗户的裂缝中呼呼地灌进来。", "english": "Wind whistled through the cracks in the windows.", "type": "句子", "keyWords": ["whistle"] },
    { "chinese": "子弹从我头顶呼啸而过。", "english": "The bullets whistled past my head.", "type": "句子", "keyWords": ["whistle"] },
    { "chinese": "a. 白色的；白人的；加牛奶的（咖啡）；n. [U] 白色；[C] 白种人", "english": "white /waɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "面色惨白", "english": "(as) white as a sheet", "type": "短语", "keyWords": ["white"] },
    { "chinese": "白领阶层的", "english": "white-collar", "type": "短语", "keyWords": ["white"] },
    { "chinese": "pron. （接名词从句）谁；（接定语从句，指代先行词）那（些）人", "english": "who /huː/", "type": "单词", "keyWords": [] },
    { "chinese": "这雨衣还有可能是其他什么人的呢？", "english": "Who else's / Whose else can this raincoat be?", "type": "句子", "keyWords": ["who"] },
    { "chinese": "约翰说谁将支持他？", "english": "Who did John say was to support him?", "type": "句子", "keyWords": ["who"] },
    { "chinese": "pron. 无论谁（接状语从句）；凡…的人（接名词从句）", "english": "whoever /huːˈevə/", "type": "单词", "keyWords": [] },
    { "chinese": "无论谁来都会受到欢迎。", "english": "Whoever comes will be welcomed. = Anyone who comes will be welcomed. = Whoever comes, he will be welcomed.（接状语从句）= No matter who comes, he will be welcomed.", "type": "句子", "keyWords": ["whoever"] },
    { "chinese": "a. 全部的，全体的；整个的，完整的；n. [C] 全部，全体，整体", "english": "whole /həʊl/", "type": "单词", "keyWords": [] },
    { "chinese": "作为一个整体，整个来看", "english": "as a whole", "type": "短语", "keyWords": ["whole"] },
    { "chinese": "全麦做的", "english": "whole-wheat", "type": "短语", "keyWords": ["whole"] },
    { "chinese": "总的说来，基本上", "english": "on the whole", "type": "短语", "keyWords": ["whole"] },
    { "chinese": "整个地煮", "english": "cook sth. whole", "type": "短语", "keyWords": ["whole"] },
    { "chinese": "许多城市整个地被震毁了。", "english": "Whole cities were destroyed by the earthquake.", "type": "句子", "keyWords": ["whole"] },
    { "chinese": "a. 全心全意的；全神贯注的", "english": "Wholehearted", "type": "单词", "keyWords": ["whole"] },
    { "chinese": "ad. 全心全意；全神贯注", "english": "wholeheartedly", "type": "单词", "keyWords": ["whole"] },
    { "chinese": "pron. 谁（宾格）；那（些）人（接定语从句，指代先行词）", "english": "whom /huːm/", "type": "单词", "keyWords": [] },
    { "chinese": "pron. …的（接名词从句）；那（些）人的（定语从句中指代先行词）", "english": "whose /huːz/", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 为什么，…的原因", "english": "why /waɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "这就是为什么…，这就是…的原因", "english": "That is why...", "type": "短语", "keyWords": ["why"] },
    { "chinese": "我说不出理由。", "english": "I cannot explain why.", "type": "句子", "keyWords": ["why"] },
    { "chinese": "为何不再试一下？（接不带to不定式）", "english": "Why not try again?", "type": "句子", "keyWords": ["why"] },
    { "chinese": "嗯！当然，如果你希望这样，我就去做。", "english": "Why, yes, I will if you wish.", "type": "句子", "keyWords": ["why"] },
    { "chinese": "a. 宽的，宽阔的，广阔的；广泛的；ad. 充分，完全；广阔地；v.（使）变宽", "english": "wide /waɪd/; widen /ˈwaɪdn/ vt./vi.", "type": "单词", "keyWords": [] },
    { "chinese": "完全醒着", "english": "be wide awake", "type": "短语", "keyWords": ["wide"] },
    { "chinese": "大开着", "english": "wide open", "type": "短语", "keyWords": ["wide"] },
    { "chinese": "游历很广", "english": "travel far and wide", "type": "短语", "keyWords": ["wide"] },
    { "chinese": "宽4米", "english": "be four meters wide", "type": "短语", "keyWords": ["wide"] },
    { "chinese": "ad. 广泛地，普遍地；很大程度上地（用于抽象概念）", "english": "widely /ˈwaɪdli/", "type": "单词", "keyWords": ["wide"] },
    { "chinese": "n. [C] 宽度；n. [U] 宽阔", "english": "width /wɪdθ/", "type": "单词", "keyWords": ["wide"] },
    { "chinese": "十英尺的宽度", "english": "a width of ten feet", "type": "短语", "keyWords": ["width"] },
    { "chinese": "宽十英尺", "english": "ten feet in width", "type": "短语", "keyWords": ["width"] },
    { "chinese": "a. 分布（或散布）广的；普遍的，广泛的", "english": "widespread /ˈwaɪdspred/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 妻子", "english": "wife /waɪf/", "type": "单词", "keyWords": [] },
    { "chinese": "n. 无线传输系统", "english": "Wi-Fi /ˈwaɪ faɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 野的；野生的；荒芜的；狂热的；极为激动的；n.（the）荒野", "english": "wild /waɪld/", "type": "单词", "keyWords": [] },
    { "chinese": "欣喜若狂/狂怒", "english": "be wild with joy/anger", "type": "短语", "keyWords": ["wild"] },
    { "chinese": "在野外", "english": "in the wild", "type": "短语", "keyWords": ["wild"] },
    { "chinese": "n.（the）荒无人烟的地区", "english": "wilderness /ˈwɪldənəs/", "type": "单词", "keyWords": ["wild"] },
    { "chinese": "n. [U]（总称）野生动物；野生植物", "english": "wildlife /ˈwaɪldlaɪf/", "type": "单词", "keyWords": ["wild"] },
    { "chinese": "aux. 将；会；愿，要；n. [U] 意志；意愿；n. [C] 意志力；遗嘱", "english": "will /wɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "您愿意…（用Would you更婉转）", "english": "Will you...?", "type": "短语", "keyWords": ["will"] },
    { "chinese": "如果你们愿意降一点价的话我就买。", "english": "If you will lower the price, I'll buy it.", "type": "句子", "keyWords": ["will"] },
    { "chinese": "钥匙转不动了，它需要上油了。", "english": "The key won't move. It needs oiling.", "type": "句子", "keyWords": ["will"] },
    { "chinese": "决心获胜的候选人", "english": "a candidate with the will to win", "type": "短语", "keyWords": ["will"] },
    { "chinese": "坚强的意志", "english": "a strong will", "type": "短语", "keyWords": ["will"] },
    { "chinese": "违心地，不情愿地", "english": "against one's will", "type": "短语", "keyWords": ["will"] },
    { "chinese": "你立下遗嘱了吗？", "english": "Have you made your will yet?", "type": "句子", "keyWords": ["will"] },
    { "chinese": "有志者事竟成。", "english": "Where there is a will, there is a way.", "type": "句子", "keyWords": ["will"] },
    { "chinese": "a.（不）愿意的", "english": "(un)willing", "type": "单词", "keyWords": ["will"] },
    { "chinese": "ad. 心甘情愿地；自动地", "english": "willingly", "type": "单词", "keyWords": ["will"] },
    { "chinese": "（不）愿意做某事", "english": "be (un)willing to do sth.", "type": "短语", "keyWords": ["willing"] },
    { "chinese": "v.（获）胜；赢；v. 在（比赛等）中获胜；赢得（奖等）", "english": "win /wɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "把…争取过来", "english": "win sb. over/round", "type": "短语", "keyWords": ["win"] },
    { "chinese": "n. [C][U] 风；a. 有风的，多风的，风强的", "english": "wind /wɪnd/; windy", "type": "单词", "keyWords": [] },
    { "chinese": "大风", "english": "high/ strong winds", "type": "短语", "keyWords": ["wind"] },
    { "chinese": "[气象]风力等级", "english": "wind scale", "type": "短语", "keyWords": ["wind"] },
    { "chinese": "v. …上发条；使蜿蜒前进；绕，缠；vi. 蜿蜒前进；绕，缠", "english": "wind /waɪnd/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "给表上发条", "english": "wind a watch", "type": "短语", "keyWords": ["wind"] },
    { "chinese": "袅袅上升的一缕烟", "english": "a column of smoke winding into the sky", "type": "短语", "keyWords": ["wind"] },
    { "chinese": "山谷中蜿蜒的河流", "english": "a river winding (its way) through a valley", "type": "短语", "keyWords": ["wind"] },
    { "chinese": "他用绷带包扎他的手指。", "english": "He wound the bandage on his finger.", "type": "句子", "keyWords": ["wind"] },
    { "chinese": "n. [C] 窗；窗口；橱窗；陈列窗", "english": "window /ˈwɪndəʊ/", "type": "单词", "keyWords": [] },
    { "chinese": "装点门面", "english": "dress the window", "type": "短语", "keyWords": ["window"] },
    { "chinese": "（商品等）摆在橱窗里", "english": "in the (shop) window", "type": "短语", "keyWords": ["window"] },
    { "chinese": "n. [U] 橱窗布置", "english": "window dressing", "type": "短语", "keyWords": ["window"] },
    { "chinese": "逛街看橱窗；逛商店", "english": "go window shopping", "type": "短语", "keyWords": ["window"] },
    { "chinese": "我不知道通过“心灵的窗口”——眼睛看透一个朋友的内心是怎么一回事。", "english": "I do not know what it is to see into the heart of a friend through that window of the soul, the eye.", "type": "句子", "keyWords": ["window"] },
    { "chinese": "了解世界的手段；世界之窗", "english": "a window on the world", "type": "短语", "keyWords": ["window"] },
    { "chinese": "n. [C][U] 酒；葡萄酒", "english": "wine /waɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "酒醉智昏。", "english": "When wine is in, wit is out.", "type": "句子", "keyWords": ["wine"] },
    { "chinese": "n. [C] 翅膀，翼", "english": "wing /wɪŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "工党的右翼", "english": "the right wing of the Labour Party", "type": "短语", "keyWords": ["wing"] },
    { "chinese": "n. [C] 获胜者，优胜者，得奖者", "english": "winner /ˈwɪnə/", "type": "单词", "keyWords": ["win"] },
    { "chinese": "n. [C][U] 冬天，冬季", "english": "winter /ˈwɪntə/", "type": "单词", "keyWords": [] },
    { "chinese": "在1935年严冬", "english": "in the severe winter of 1935", "type": "短语", "keyWords": ["winter"] },
    { "chinese": "v. 擦，抹；消灭；使消失", "english": "wipe /waɪp/", "type": "单词", "keyWords": [] },
    { "chinese": "擦干某人的眼泪", "english": "wipe one's tears away", "type": "短语", "keyWords": ["wipe"] },
    { "chinese": "把桌子上的灰尘擦去", "english": "wipe the dust off the table", "type": "短语", "keyWords": ["wipe"] },
    { "chinese": "消灭敌人/消除记忆", "english": "wipe the enemy/the memory out", "type": "短语", "keyWords": ["wipe"] },
    { "chinese": "n. [C] 线；电线；金属线", "english": "wire /ˈwaɪə/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 智慧，学问，才智", "english": "wisdom /ˈwɪzdəm/", "type": "单词", "keyWords": [] },
    { "chinese": "从旁人的愚行中学到智慧。", "english": "Learn wisdom by the follies of others.", "type": "句子", "keyWords": ["wisdom"] },
    { "chinese": "a. 有智慧的；聪明的；英明的", "english": "wise /waɪz/", "type": "单词", "keyWords": [] },
    { "chinese": "为这样的行为辩护是不太明智的。", "english": "It's not very wise of you to justify such conduct.", "type": "句子", "keyWords": ["wise"] },
    { "chinese": "n. [C]/v. 祝愿；希望；vi. 希望", "english": "wish /wɪʃ/", "type": "单词", "keyWords": [] },
    { "chinese": "盼望着有（近be eager for, be hungry for等）", "english": "wish for sth.", "type": "短语", "keyWords": ["wish"] },
    { "chinese": "希望做某事", "english": "wish to do sth. = have a wish to do sth.", "type": "短语", "keyWords": ["wish"] },
    { "chinese": "祝愿（此用法hope不适用）", "english": "wish sb. sth. (n./adj.)", "type": "短语", "keyWords": ["wish"] },
    { "chinese": "我祝愿你健康愉快。（近May you be well and happy!）", "english": "I wish you well and happy.", "type": "句子", "keyWords": ["wish"] },
    { "chinese": "希望某人做某事（此用法hope不适用）", "english": "wish sb. to do sth.", "type": "短语", "keyWords": ["wish"] },
    { "chinese": "但愿（这里的宾语从句中用虚拟语气，此时hope不适用）", "english": "wish that...", "type": "短语", "keyWords": ["wish"] },
    { "chinese": "他没这样做该多好。", "english": "I wish he hadn't done it.（比较If only he hadn't done it./I'd rather he hadn't done it.）", "type": "句子", "keyWords": ["wish"] },
    { "chinese": "请代我向她致以最良好的祝福。", "english": "Please send her my best wishes.", "type": "句子", "keyWords": ["wish"] },
    { "chinese": "愿望若是马，乞丐也可乘。愿望不能代替实际。", "english": "If wishes were horses, beggars might ride.", "type": "句子", "keyWords": ["wish"] },
    { "chinese": "n. [U]/pl. 才智，智力；风趣，妙语；a. 富于机智的，诙谐的", "english": "wit /wɪt/; witty", "type": "单词", "keyWords": [] },
    { "chinese": "她不知道如何回绝别人。", "english": "She hadn't the wit to say no.", "type": "句子", "keyWords": ["wit"] },
    { "chinese": "智穷计尽，一筹莫展；全然不知所措", "english": "be at one's wits'/wit's end", "type": "短语", "keyWords": ["wit"] },
    { "chinese": "prep. 和…（一起）；用（使用的工具或手段）；带有，具有；随着；因为", "english": "with /wɪð/", "type": "单词", "keyWords": [] },
    { "chinese": "热情地说话", "english": "speak with enthusiasm", "type": "短语", "keyWords": ["with"] },
    { "chinese": "顺风起帆", "english": "sail with the wind", "type": "短语", "keyWords": ["with"] },
    { "chinese": "手拿拐棍走路（接复合结构）", "english": "walk with a stick in one's hand", "type": "短语", "keyWords": ["with"] },
    { "chinese": "汽车出了毛病", "english": "have trouble with the car", "type": "短语", "keyWords": ["with"] },
    { "chinese": "随着温度而变化", "english": "change with the temperature", "type": "短语", "keyWords": ["with"] },
    { "chinese": "逐年增加", "english": "increase with years", "type": "短语", "keyWords": ["with"] },
    { "chinese": "感染了流行性感冒", "english": "fall sick with flu", "type": "短语", "keyWords": ["with"] },
    { "chinese": "害怕得发抖", "english": "tremble with fear", "type": "短语", "keyWords": ["with"] },
    { "chinese": "在那个议题上他和我们观点一致。", "english": "He is with us on that issue.", "type": "句子", "keyWords": ["with"] },
    { "chinese": "我没异议。", "english": "It's all right with me.", "type": "句子", "keyWords": ["with"] },
    { "chinese": "他说完这些话便离开了房间。", "english": "With these words, he left the room.", "type": "句子", "keyWords": ["with"] },
    { "chinese": "她这样决定，我们很高兴。", "english": "We are pleased with her decision.", "type": "句子", "keyWords": ["with"] },
    { "chinese": "v. 抽回，收回；提取；撤退，撤离；vi. 撤退；撤离，退出；退缩", "english": "withdraw /wɪðˈdrɔː/", "type": "单词", "keyWords": [] },
    { "chinese": "把手从热火炉旁缩回", "english": "withdraw one's hands from the hot stove", "type": "短语", "keyWords": ["withdraw"] },
    { "chinese": "收回一句话", "english": "withdraw a remark", "type": "短语", "keyWords": ["withdraw"] },
    { "chinese": "从某地撤军", "english": "withdraw troops from a place", "type": "短语", "keyWords": ["withdraw"] },
    { "chinese": "从银行取款", "english": "withdraw money from the bank", "type": "短语", "keyWords": ["withdraw"] },
    { "chinese": "退出竞争/比赛", "english": "withdraw from the competition/ the race", "type": "短语", "keyWords": ["withdraw"] },
    { "chinese": "prep. 在（时间、空间、限度…）内；ad. 在内部，在内心里", "english": "within /wɪˈðɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "她感到怒火从心头燃起。", "english": "She felt the anger mounting up within her.", "type": "句子", "keyWords": ["within"] },
    { "chinese": "离我大学很近", "english": "within walking distance of my university", "type": "短语", "keyWords": ["within"] },
    { "chinese": "留在附近（叫得应/听得见/看得到的地方）", "english": "remain within reach (call/ hearing/sight)", "type": "短语", "keyWords": ["within"] },
    { "chinese": "尽力而为！", "english": "Do what's within your power!", "type": "句子", "keyWords": ["within"] },
    { "chinese": "这扇门从里面开的。", "english": "The door opens from within.", "type": "句子", "keyWords": ["within"] },
    { "chinese": "prep. 无；没有；缺少", "english": "without /wɪˈðaʊt/", "type": "单词", "keyWords": [] },
    { "chinese": "没有也行；设法对付；将就（近manage without）", "english": "do without", "type": "短语", "keyWords": ["without"] },
    { "chinese": "人缺不了水。", "english": "Man cannot do without water.", "type": "句子", "keyWords": ["without"] },
    { "chinese": "n. [C] 见证人，目击者；证据；证词；v. 目击；为…作证，证明；vi. 作证", "english": "witness /ˈwɪtnɪs/", "type": "单词", "keyWords": [] },
    { "chinese": "事故的目击者", "english": "a witness to the accident", "type": "短语", "keyWords": ["witness"] },
    { "chinese": "亲眼看见那个意外事故", "english": "witness the accident", "type": "短语", "keyWords": ["witness"] },
    { "chinese": "这些事实证明了他的粗心。", "english": "These facts are a witness to his carelessness.", "type": "句子", "keyWords": ["witness"] },
    { "chinese": "n. [C] 狼", "english": "wolf /wʊlf/", "type": "单词", "keyWords": [] },
    { "chinese": "披着羊皮的狼", "english": "a wolf in sheep's clothing", "type": "短语", "keyWords": ["wolf"] },
    { "chinese": "非常贪婪，贪得无厌", "english": "(as) greedy as a wolf", "type": "短语", "keyWords": ["wolf"] },
    { "chinese": "虚张声势；发假情报，喊叫“狼来了”", "english": "cry wolf", "type": "短语", "keyWords": ["wolf"] },
    { "chinese": "跟狼在一起，就会学狼叫。近墨者黑。", "english": "He who keeps company with a wolf will learn to howl.", "type": "句子", "keyWords": ["wolf"] },
    { "chinese": "n. [C] 妇女；（总称）女人；a. 像女人的，柔弱的", "english": "woman /ˈwʊmən/; womanish", "type": "单词", "keyWords": [] },
    { "chinese": "v. 对…感到惊讶或疑虑；想知道；vi. 感到惊讶或疑虑；n. [C] 奇迹；奇事；惊奇；疑惑；[U] 奇怪；奇妙；a. 极好的；精彩的；令人惊叹的；令人高兴的", "english": "wonder /ˈwʌndə/; wonderful", "type": "单词", "keyWords": [] },
    { "chinese": "难怪；并不奇怪", "english": "(It's) no wonder...", "type": "短语", "keyWords": ["wonder"] },
    { "chinese": "难怪他们被控缺乏诚信。", "english": "No wonder they were accused of lacking honesty and faith.", "type": "句子", "keyWords": ["wonder"] },
    { "chinese": "创造奇迹", "english": "do/work wonders/ miracles", "type": "短语", "keyWords": ["wonder"] },
    { "chinese": "惊奇地看着某物", "english": "look at sth. in wonder", "type": "短语", "keyWords": ["wonder"] },
    { "chinese": "感到十分惊异", "english": "be filled with wonder", "type": "短语", "keyWords": ["wonder"] },
    { "chinese": "对某事感到惊奇", "english": "wonder at sth.", "type": "短语", "keyWords": ["wonder"] },
    { "chinese": "你的耐心使我惊异。", "english": "I wonder at your patience.", "type": "句子", "keyWords": ["wonder"] },
    { "chinese": "他是个奇才。", "english": "He's a wonder.", "type": "句子", "keyWords": ["wonder"] },
    { "chinese": "真想不到！", "english": "What a wonder!", "type": "句子", "keyWords": ["wonder"] },
    { "chinese": "长城是世界奇观之一。", "english": "The Great Wall is one of the wonders of the world.", "type": "句子", "keyWords": ["wonder"] },
    { "chinese": "奇怪的是他居然拒绝了这个提议。", "english": "It is a wonder/ a surprise that he declined this offer.", "type": "句子", "keyWords": ["wonder"] },
    { "chinese": "n. [U] 木头；木材；n. [C] 小树林；a. 木（质）的；木制的", "english": "wood /wʊd/; wooden", "type": "单词", "keyWords": [] },
    { "chinese": "在树林里（迷了路）", "english": "(be/get lost) in the wood(s)", "type": "短语", "keyWords": ["wood"] },
    { "chinese": "见树不见林；只注重局部不全面看问题", "english": "cannot see the wood for the trees", "type": "短语", "keyWords": ["wood"] },
    { "chinese": "n. [U] 羊毛；a. 羊毛的；毛纺的", "english": "wool /wʊl/; wool(en)", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 词，单词；言辞，话；（只用单数）诺言；命令；[U] 消息，信息", "english": "word /wɜːd/", "type": "单词", "keyWords": [] },
    { "chinese": "一句话，总而言之", "english": "in a word", "type": "短语", "keyWords": ["word"] },
    { "chinese": "换句话说", "english": "in other words", "type": "短语", "keyWords": ["word"] },
    { "chinese": "沉默寡言的人", "english": "a man of few words", "type": "短语", "keyWords": ["word"] },
    { "chinese": "插话", "english": "get a word in", "type": "短语", "keyWords": ["word"] },
    { "chinese": "无法用语言表达", "english": "beyond words", "type": "短语", "keyWords": ["word"] },
    { "chinese": "食言，失信", "english": "break one's word", "type": "短语", "keyWords": ["word"] },
    { "chinese": "（被迫）收回前言", "english": "take back one's words", "type": "短语", "keyWords": ["word"] },
    { "chinese": "法语中“冒犯”这个词怎么说？", "english": "What's the French word for 'offend'?", "type": "句子", "keyWords": ["word"] },
    { "chinese": "用自己的话（表达）", "english": "in one's own words", "type": "短语", "keyWords": ["word"] },
    { "chinese": "消息传来", "english": "Word came that...", "type": "短语", "keyWords": ["word"] },
    { "chinese": "听了这些话，他感到热血直往上涌。", "english": "At these words, he felt the blood rushing up.", "type": "句子", "keyWords": ["word"] },
    { "chinese": "留言说…，留下字条或口信说…", "english": "leave word that...", "type": "短语", "keyWords": ["word"] },
    { "chinese": "有传言说他们在办离婚。", "english": "Word has it (that) they're divorcing.", "type": "句子", "keyWords": ["word"] },
    { "chinese": "遵守诺言（近be as good as one's word）", "english": "keep one's word", "type": "短语", "keyWords": ["word"] },
    { "chinese": "向某人保证…", "english": "give sb. one's word that... = promise sb. that...", "type": "短语", "keyWords": ["word"] },
    { "chinese": "和某人说话（尤指秘密地）", "english": "have a word with sb.", "type": "短语", "keyWords": ["word"] },
    { "chinese": "同某人争吵", "english": "have words with sb.", "type": "短语", "keyWords": ["word"] },
    { "chinese": "玩弄字眼，说双关语", "english": "play on words", "type": "短语", "keyWords": ["word"] },
    { "chinese": "（被迫）承认说错/收回自己的话", "english": "eat one's words", "type": "短语", "keyWords": ["word"] },
    { "chinese": "口头地", "english": "by word of mouth", "type": "短语", "keyWords": ["word"] },
    { "chinese": "替某人说情；推荐某人；为某人辩护", "english": "put in a (good) word for sb.", "type": "短语", "keyWords": ["word"] },
    { "chinese": "你听着/记住我的话好了！你会后悔的！", "english": "Mark my words! You'll regret it!", "type": "句子", "keyWords": ["word"] },
    { "chinese": "智者一言已足。明白人用不着细说。", "english": "A word to the wise is enough.", "type": "句子", "keyWords": ["word"] },
    { "chinese": "逐词地；原原本本地", "english": "word for word", "type": "短语", "keyWords": ["word"] },
    { "chinese": "n. [U] 工作；职业；[C] 著作；作品；产品；工艺品；(pl.)（用作单或复）工厂；(用作复)工程；[军]（防御）工事；v.（使）工作；（使）劳动；（使）运转；起作用", "english": "work /wɜːk/", "type": "单词", "keyWords": [] },
    { "chinese": "在工作（比较at play）；在起作用，在运转", "english": "at work", "type": "短语", "keyWords": ["work"] },
    { "chinese": "一件/很多件工艺品", "english": "a work/ many works of art", "type": "短语", "keyWords": ["work"] },
    { "chinese": "产生效果；起作用", "english": "do one's work = work (vi)", "type": "短语", "keyWords": ["work"] },
    { "chinese": "这些工厂被关掉了。（复数）", "english": "The works have been closed down.", "type": "句子", "keyWords": ["work"] },
    { "chinese": "学习，研究，致力于；从事于", "english": "work at...", "type": "短语", "keyWords": ["work"] },
    { "chinese": "攻读西班牙语", "english": "work at Spanish", "type": "短语", "keyWords": ["work"] },
    { "chinese": "致力于；从事（某工作）；对…起作用；继续工作", "english": "work on...", "type": "短语", "keyWords": ["work"] },
    { "chinese": "写书/制订计划/造楼房", "english": "work on a book/a plan/a building", "type": "短语", "keyWords": ["work"] },
    { "chinese": "这种新药对她不起作用。", "english": "The new drug didn't work on her.", "type": "句子", "keyWords": ["work"] },
    { "chinese": "这幢房子在我离开前就动工了。", "english": "Work on the building had begun before I left.", "type": "句子", "keyWords": ["work"] },
    { "chinese": "开一部机器", "english": "work a machine", "type": "短语", "keyWords": ["work"] },
    { "chinese": "这机器是电动的。", "english": "The machine is worked by electricity.", "type": "句子", "keyWords": ["work"] },
    { "chinese": "解决；算出；制订出；弄懂，理解（近figure out）", "english": "work... out", "type": "短语", "keyWords": ["work"] },
    { "chinese": "我还欠你多少你算出来了没有？", "english": "Have you worked out what I owe you yet?", "type": "句子", "keyWords": ["work"] },
    { "chinese": "他们制订出了新的进攻方案。", "english": "They worked out a new plan of attack.", "type": "句子", "keyWords": ["work"] },
    { "chinese": "没有人清楚火是怎样发生的。", "english": "No one can work out how the fire started.", "type": "句子", "keyWords": ["work"] },
    { "chinese": "事情的结果很不错。（vi.）", "english": "Things worked out quite well.", "type": "句子", "keyWords": ["work"] },
    { "chinese": "n. [C] 工人；a. 工作的，劳动的；经营的", "english": "worker /ˈwɜːkə/; working", "type": "单词", "keyWords": ["work"] },
    { "chinese": "先进工作者", "english": "advanced worker", "type": "短语", "keyWords": ["worker"] },
    { "chinese": "职业母亲", "english": "working mothers", "type": "短语", "keyWords": ["working"] },
    { "chinese": "工人阶级", "english": "the working class", "type": "短语", "keyWords": ["working"] },
    { "chinese": "执行委员会", "english": "a working committee", "type": "短语", "keyWords": ["working"] },
    { "chinese": "n. [C] 车间；工厂，工场；研习会，讨论会", "english": "workshop /ˈwɜːkʃɒp/", "type": "单词", "keyWords": ["work"] },
    { "chinese": "n. [C] 世界；地球；天下", "english": "world /wɜːld/", "type": "单词", "keyWords": [] },
    { "chinese": "动物世界", "english": "the animal world", "type": "短语", "keyWords": ["world"] },
    { "chinese": "第三世界", "english": "the Third World", "type": "短语", "keyWords": ["world"] },
    { "chinese": "全世界都知道这件事。", "english": "The whole world knows about it.", "type": "句子", "keyWords": ["world"] },
    { "chinese": "遍及全世界", "english": "all over/ throughout/ around the world", "type": "短语", "keyWords": ["world"] },
    { "chinese": "在世界上；到底（用于加强疑问语气）", "english": "in the world", "type": "短语", "keyWords": ["world"] },
    { "chinese": "这世界真小。", "english": "It's a small world.", "type": "句子", "keyWords": ["world"] },
    { "chinese": "有工作/失业", "english": "in/out of work", "type": "短语", "keyWords": ["work"] },
    { "chinese": "一家钢厂…（单数）", "english": "a steel works...", "type": "短语", "keyWords": ["work"] },
    { "chinese": "努力学习", "english": "work hard at...", "type": "短语", "keyWords": ["work"] },
    { "chinese": "经营农场", "english": "work a farm", "type": "短语", "keyWords": ["work"] },
    { "chinese": "体力劳动者", "english": "manual workers", "type": "短语", "keyWords": ["worker"] },
    { "chinese": "工作时间", "english": "working hours", "type": "短语", "keyWords": ["working"] },
    { "chinese": "工作条件", "english": "working conditions", "type": "短语", "keyWords": ["working"] },
    { "chinese": "闻名世界的", "english": "world-famous", "type": "短语", "keyWords": ["world"] },
    { "chinese": "科学界", "english": "the scientific world", "type": "短语", "keyWords": ["world"] },
    { "chinese": "生孩子", "english": "bring a child into the world", "type": "短语", "keyWords": ["world"] },
    { "chinese": "a. 全世界的", "english": "worldwide /ˈwɜːldwaɪd/", "type": "单词", "keyWords": ["world"] },
    { "chinese": "n. [C] 虫；蠕虫；[计] 蠕虫病毒", "english": "worm /wɜːm/", "type": "单词", "keyWords": [] },
    { "chinese": "蚕；蚯蚓；极爱读书的人；书呆子", "english": "silkworm; earthworm; bookworm", "type": "短语", "keyWords": ["worm"] },
    { "chinese": "v.（使）担心；（使）发愁；n. [C][U] 烦恼，忧虑，苦恼", "english": "worry /ˈwʌri/", "type": "单词", "keyWords": [] },
    { "chinese": "为…担心", "english": "be worried about", "type": "短语", "keyWords": ["worry"] },
    { "chinese": "为…担心", "english": "worry about", "type": "短语", "keyWords": ["worry"] },
    { "chinese": "我从未度过如此令人担忧的一天。", "english": "I have never spent a more worrying day.", "type": "句子", "keyWords": ["worry"] },
    { "chinese": "a. 更坏的，更糟的；健康状况更坏的；ad. 较坏（badly 比较级）", "english": "worse /wɜːs/", "type": "单词", "keyWords": [] },
    { "chinese": "（常作插入语）更糟的是", "english": "to make matters worse", "type": "短语", "keyWords": ["worse"] },
    { "chinese": "比以前更穷/不愉快/不健康/更不幸等", "english": "be worse off", "type": "短语", "keyWords": ["worse"] },
    { "chinese": "每况愈下", "english": "go from bad to worse", "type": "短语", "keyWords": ["worse"] },
    { "chinese": "更糟的是", "english": "Worse still...", "type": "短语", "keyWords": ["worse"] },
    { "chinese": "a. 最坏的；最差的；最糟的；ad. 最坏，最差", "english": "worst /wɜːst/", "type": "单词", "keyWords": [] },
    { "chinese": "v.（使）变得更坏，恶化", "english": "worsen /ˈwɜːsn/", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. [U] 崇拜；尊敬", "english": "worship /ˈwɜːʃɪp/", "type": "单词", "keyWords": [] },
    { "chinese": "信仰上帝", "english": "worship God", "type": "短语", "keyWords": ["worship"] },
    { "chinese": "prep. 值…钱；值…的；n. [U] 价值；值（或相当于）…的数量", "english": "worth /wɜːθ/", "type": "单词", "keyWords": [] },
    { "chinese": "值得一读/买（用主动形式表示被动）", "english": "be worth reading/ buying", "type": "短语", "keyWords": ["worth"] },
    { "chinese": "价值很大/小的", "english": "be of great/ little worth/ value", "type": "短语", "keyWords": ["worth"] },
    { "chinese": "价值数千镑的（货物/损失等）…", "english": "Thousands of pounds worth of (goods/ damage etc.) was...", "type": "短语", "keyWords": ["worth"] },
    { "chinese": "值得某人一干（见while）", "english": "worth one's while", "type": "短语", "keyWords": ["worth"] },
    { "chinese": "值得做某事", "english": "It is worth (one's) while (=worthwhile) + to do/ doing sth.", "type": "短语", "keyWords": ["worth"] },
    { "chinese": "a. 无价值的；没用处的", "english": "worthless /ˈwɜːθləs/", "type": "单词", "keyWords": ["worth"] },
    { "chinese": "a. 值得的", "english": "worthwhile /ˈwɜːθwaɪl/", "type": "单词", "keyWords": ["worth"] },
    { "chinese": "值得做的工作", "english": "a worthwhile job", "type": "短语", "keyWords": ["worthwhile"] },
    { "chinese": "a. 值得的，配得上的；有价值的（不用于钱）；可敬可佩的", "english": "worthy /ˈwɜːði/", "type": "单词", "keyWords": [] },
    { "chinese": "可敬可佩的人", "english": "a worthy fellow", "type": "短语", "keyWords": ["worthy"] },
    { "chinese": "值得…的", "english": "be worthy of sth.", "type": "短语", "keyWords": ["worthy"] },
    { "chinese": "（某事）值得一做", "english": "be worthy of being done/ to be done", "type": "短语", "keyWords": ["worthy"] },
    { "chinese": "aux. 愿，想要；（过去将来）将；过去常常会；会（虚拟语气）", "english": "would /wʊd/", "type": "单词", "keyWords": [] },
    { "chinese": "保持肃静，好吗？", "english": "Keep quiet, would you?", "type": "句子", "keyWords": ["would"] },
    { "chinese": "要是我愿意，我能够这样做（但我不愿意）。", "english": "I could do so if I would.", "type": "句子", "keyWords": ["would"] },
    { "chinese": "过去他常常会坐几个钟头什么事也不做。", "english": "He would sit for hours doing nothing.", "type": "句子", "keyWords": ["would"] },
    { "chinese": "想要（某人）做某事", "english": "would like (sb.) to do sth.", "type": "短语", "keyWords": ["would"] },
    { "chinese": "本想…", "english": "would like to have done sth. = would have liked to do sth.", "type": "短语", "keyWords": ["would"] },
    { "chinese": "宁愿，宁可", "english": "would rather do sth.", "type": "短语", "keyWords": ["would"] },
    { "chinese": "宁愿某人做某事（虚拟语气）", "english": "would rather sb. did/ had done sth.", "type": "短语", "keyWords": ["would"] },
    { "chinese": "n. [C] 创伤；伤口；v. 使受伤；伤害（辨析见damage）", "english": "wound /wuːnd/", "type": "单词", "keyWords": [] },
    { "chinese": "伤了她的自尊心", "english": "a wound to her pride", "type": "短语", "keyWords": ["wound"] },
    { "chinese": "这个士兵的胳膊受伤了。", "english": "The soldier was wounded in the arm.", "type": "句子", "keyWords": ["wound"] },
    { "chinese": "v. 包，裹；包扎；缠绕；n. [C]（常用复数）包装材料", "english": "wrap /ræp/; wrapping", "type": "单词", "keyWords": [] },
    { "chinese": "用…来包裹", "english": "wrap sb./ sth. (up) in...", "type": "短语", "keyWords": ["wrap"] },
    { "chinese": "埋头于；全神贯注于；被…迷住", "english": "be wrapped up in...", "type": "短语", "keyWords": ["wrap"] },
    { "chinese": "v. 造成（船舶等）失事；n. [C] 遇难船只；残骸；n. [U] 破坏，毁坏", "english": "wreck /rek/", "type": "单词", "keyWords": [] },
    { "chinese": "失事船舶", "english": "a wrecked ship", "type": "短语", "keyWords": ["wreck"] }
];
