const qgl309_313 = [
    { "chinese": "那船遭遇了海难。", "english": "The ship was wrecked.", "type": "句子", "keyWords": ["wreck"] },
    { "chinese": "失事船只的所有幸存者已被及时救起。", "english": "All the survivors of the shipwreck were picked up in time.", "type": "句子", "keyWords": ["wreck"] },
    { "chinese": "n. [C] 皱纹；v.（使）起皱纹；a. 有皱纹的", "english": "wrinkle /ˈrɪŋkl/; wrinkled", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 手腕，腕关节", "english": "wrist /rɪst/", "type": "单词", "keyWords": [] },
    { "chinese": "v. 写，书写；写信（给）；n. [C] 作家，作者；书写者", "english": "write /raɪt/; writer", "type": "单词", "keyWords": [] },
    { "chinese": "写信给他", "english": "write (him) a letter/ write a letter to him/ write to him", "type": "短语", "keyWords": ["write"] },
    { "chinese": "n. [U] 书写；写作；书法（=handwriting）；(pl.) 文学作品", "english": "writing /ˈraɪtɪŋ/", "type": "单词", "keyWords": ["write"] },
    { "chinese": "a. 错的；不正当的；邪恶的；n. [C][U] 错误；坏事；邪恶；不公正，冤屈；v. 委屈，错怪；不公正对待；ad. 不正当地；错误地", "english": "wrong /rɒŋ/; wrongly", "type": "单词", "keyWords": [] },
    { "chinese": "打电话拨错号码", "english": "have got the wrong number", "type": "短语", "keyWords": ["wrong"] },
    { "chinese": "走错了路", "english": "take the wrong way/ road", "type": "短语", "keyWords": ["wrong"] },
    { "chinese": "电机出故障了。", "english": "There is something wrong with the motor.", "type": "句子", "keyWords": ["wrong"] },
    { "chinese": "这怎么啦？/这有什么不好？（反语）", "english": "What's wrong with it?", "type": "句子", "keyWords": ["wrong"] },
    { "chinese": "出差错，出故障；变坏了", "english": "go wrong", "type": "短语", "keyWords": ["wrong"] },
    { "chinese": "做错事；犯罪，作恶", "english": "do wrong", "type": "短语", "keyWords": ["wrong"] },
    { "chinese": "明辨是非", "english": "know right from wrong", "type": "短语", "keyWords": ["wrong"] },
    { "chinese": "我受了冤屈。", "english": "I was wronged.", "type": "句子", "keyWords": ["wrong"] },
    { "chinese": "对待某人不公平；冤枉某人，委屈某人", "english": "do sb. a great wrong/ do a wrong to sb./ wrong sb.", "type": "短语", "keyWords": ["wrong"] },
    { "chinese": "以恶报恶于事无补。", "english": "Two wrongs don't make a right.", "type": "句子", "keyWords": ["wrong"] },
    { "chinese": "a. X光的，X射线的，使用X射线的；vt. 用X射线检查", "english": "X-ray /ˈeksˌreɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "骨骼的X光检查", "english": "an X-ray examination of bones in the body", "type": "短语", "keyWords": ["X-ray"] },
    { "chinese": "昨天我的牙进行了X光检查。", "english": "I had my teeth X-rayed yesterday.", "type": "句子", "keyWords": ["X-ray"] },
    { "chinese": "n. [C] 码（长度单位，3 feet=36 inches=0.9144 metre）；院子，庭院", "english": "yard /jɑːd/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 呵欠；vi. 打呵欠", "english": "yawn /jɔːn/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 年；(pl.) 很久（近ages）；好多年", "english": "year /jɪə, jɜː/", "type": "单词", "keyWords": [] },
    { "chinese": "全年", "english": "all the year round", "type": "短语", "keyWords": ["year"] },
    { "chinese": "在1988年这一年", "english": "in the year 1988", "type": "短语", "keyWords": ["year"] },
    { "chinese": "逐年", "english": "year by year", "type": "短语", "keyWords": ["year"] },
    { "chinese": "学年", "english": "academic/ school year", "type": "短语", "keyWords": ["year"] },
    { "chinese": "光年", "english": "light year", "type": "短语", "keyWords": ["year"] },
    { "chinese": "每隔一年", "english": "every other year", "type": "短语", "keyWords": ["year"] },
    { "chinese": "年复一年，连续多年（作状语）", "english": "year in year out= year after year", "type": "短语", "keyWords": ["year"] },
    { "chinese": "我们已有好几年没有见到她了。", "english": "It's been years since we saw her.", "type": "句子", "keyWords": ["year"] },
    { "chinese": "a. 每年的，一年一度的；ad. 每年，一年一次地；n. [C] 年刊", "english": "yearly /ˈjɪəli/", "type": "单词", "keyWords": ["year"] },
    { "chinese": "v./n. [C]（因痛苦、害怕、惊讶或热情而）大声喊叫", "english": "yell /jel/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 黄色的；n. [U] 黄色", "english": "yellow /ˈjeləʊ/", "type": "单词", "keyWords": [] },
    { "chinese": "[U] 黄热病", "english": "yellow fever", "type": "短语", "keyWords": ["yellow"] },
    { "chinese": "黄页（电话）查号簿", "english": "yellow pages", "type": "短语", "keyWords": ["yellow"] },
    { "chinese": "ad./n. [C] 是，是的", "english": "yes /jes/", "type": "单词", "keyWords": [] },
    { "chinese": "回答“是”", "english": "answer with a yes", "type": "短语", "keyWords": ["yes"] },
    { "chinese": "n. [U] 昨天", "english": "yesterday /ˈjestədeɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 还；迄今；仍然；尚；已经；然而，但是", "english": "yet /jet/", "type": "单词", "keyWords": [] },
    { "chinese": "尚未；还没", "english": "not yet", "type": "短语", "keyWords": ["yet"] },
    { "chinese": "然而；可是", "english": "and yet", "type": "短语", "keyWords": ["yet"] },
    { "chinese": "迄今", "english": "as yet", "type": "短语", "keyWords": ["yet"] },
    { "chinese": "n. [U] 酸奶，酸乳（=yogurt/yoghurt）", "english": "yoghourt /ˈjəʊɡət/", "type": "单词", "keyWords": [] },
    { "chinese": "pron. 你；你们", "english": "you /juː/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 年轻的；幼小的；n. (the) 年轻人；[U]（总称，常为一群）幼禽", "english": "young /jʌŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "老老少少；不分老少", "english": "young and old", "type": "短语", "keyWords": ["young"] },
    { "chinese": "尊老爱幼", "english": "respect the aged and love the young", "type": "短语", "keyWords": ["young"] },
    { "chinese": "动物保护它们的幼崽。", "english": "Animals protect their young.", "type": "句子", "keyWords": ["young"] },
    { "chinese": "n. [C] 少年；年轻人；小孩", "english": "youngster /ˈjʌŋstə/", "type": "单词", "keyWords": ["young"] },
    { "chinese": "pron. 你的；你们的", "english": "your /jɔː/", "type": "单词", "keyWords": [] },
    { "chinese": "pron. 你的；你们的；你全家人（常用于信中）", "english": "yours /jɔːz/", "type": "单词", "keyWords": [] },
    { "chinese": "（信末用语）谨上", "english": "yours faithfully", "type": "短语", "keyWords": ["yours"] },
    { "chinese": "祝福您和您全家人。", "english": "Best wishes to you and yours.", "type": "句子", "keyWords": ["yours"] },
    { "chinese": "pron. 你自己", "english": "yourself /jɔːˈself/", "type": "单词", "keyWords": [] },
    { "chinese": "pron. 你们自己", "english": "yourselves /jɔːˈselvz/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]（可加a）青（少）年时期；青春；n. [C] 青年人；(the)（总称）青年们", "english": "youth /juːθ/", "type": "单词", "keyWords": [] },
    { "chinese": "我的青春已不复存在。", "english": "My youth has gone.", "type": "句子", "keyWords": ["youth"] },
    { "chinese": "在他（们）年轻时", "english": "in their/ his youth", "type": "短语", "keyWords": ["youth"] },
    { "chinese": "一个国家的青年们", "english": "the youth of a nation", "type": "短语", "keyWords": ["youth"] },
    { "chinese": "那个年轻人…", "english": "the youth...", "type": "短语", "keyWords": ["youth"] },
    { "chinese": "少壮不努力，老大徒伤悲。", "english": "An idle youth, a needy age.", "type": "句子", "keyWords": ["youth"] },
    { "chinese": "一个二十岁的青年", "english": "a youth of twenty", "type": "短语", "keyWords": ["youth"] },
    { "chinese": "n. [C] 斑马；a. 有黑白相间条纹的", "english": "zebra /ˈziːbrə/", "type": "单词", "keyWords": [] },
    { "chinese": "人行横道线", "english": "zebra crossing", "type": "短语", "keyWords": ["zebra"] },
    { "chinese": "斑马条纹可能会以一堆令人困惑的图像出现，使捕食者很难锁定单个斑马。", "english": "Zebra stripes may appear as a mass of confusing images, making it difficult for predators to target individual zebras.", "type": "句子", "keyWords": ["zebra"] },
    { "chinese": "n. [C] 零；零点；零度；没有", "english": "zero /ˈzɪərəʊ/", "type": "单词", "keyWords": [] },
    { "chinese": "零摄氏度以上/下", "english": "above/ below zero degrees centigrade", "type": "短语", "keyWords": ["zero"] },
    { "chinese": "零增长，不增长", "english": "zero growth", "type": "短语", "keyWords": ["zero"] },
    { "chinese": "n. [C]（英）拉链；v. 拉上/开拉链", "english": "zip /zɪp/", "type": "单词", "keyWords": [] },
    { "chinese": "她拉上了裙子的拉链。", "english": "She zipped up her dress.", "type": "句子", "keyWords": ["zip"] },
    { "chinese": "闭上你的嘴！", "english": "Zip your lips!", "type": "句子", "keyWords": ["zip"] },
    { "chinese": "n. [C]（美）邮政编码（=zip code）；（英）postcode", "english": "zip", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 时区；地域，地带，地区，环带；范围", "english": "zone /zəʊn/", "type": "单词", "keyWords": [] },
    { "chinese": "工业区", "english": "industrial zones", "type": "短语", "keyWords": ["zone"] },
    { "chinese": "商业区", "english": "a business zone", "type": "短语", "keyWords": ["zone"] },
    { "chinese": "英语区", "english": "the English-speaking zone", "type": "短语", "keyWords": ["zone"] },
    { "chinese": "时区", "english": "time zone", "type": "短语", "keyWords": ["zone"] },
    { "chinese": "经济开发区", "english": "economic development zone", "type": "短语", "keyWords": ["zone"] },
    { "chinese": "出口工业加工区", "english": "export processing zone", "type": "短语", "keyWords": ["zone"] },
    { "chinese": "北/南温带", "english": "the North/South Temperate Zone", "type": "短语", "keyWords": ["zone"] },
    { "chinese": "n. [C] 动物园（=zoological garden）", "english": "zoo /zuː/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 动物学", "english": "zoology /zuˈɒlədʒi/", "type": "单词", "keyWords": [] }
];
