const qgl41_48 = [
    { "chinese": "想起...(近recall, review)", "english": "bring.. back to one's mind", "type": "短语", "keyWords": ["bring"] },
    { "chinese": "将...带到安全处", "english": "bring.. to safety", "type": "短语", "keyWords": ["bring"] },
    { "chinese": "引起疾病/故障", "english": "bring on disease/ breakdown", "type": "短语", "keyWords": ["bring"] },
    { "chinese": "让人知道...", "english": "bring new evidence/ the truth to light", "type": "短语", "keyWords": ["bring"] },
    { "chinese": "n. 不列颠(英格兰、威尔士和苏格兰的总称)；英国", "english": "Britain", "type": "单词", "keyWords": [] },
    { "chinese": "a. 英国的；英语的；n. 英国人", "english": "British", "type": "单词", "keyWords": [] },
    { "chinese": "大不列颠", "english": "Great Britain", "type": "短语", "keyWords": ["Britain"] },
    { "chinese": "英国人(总称)", "english": "the British", "type": "短语", "keyWords": ["British"] },
    { "chinese": "a. 宽的；宽广的；广泛的", "english": "broad", "type": "单词", "keyWords": [] },
    { "chinese": "v. 加宽；vi. 变宽", "english": "broaden", "type": "单词", "keyWords": [] },
    { "chinese": "气量大的", "english": "broad-minded", "type": "短语", "keyWords": ["broad"] },
    { "chinese": "宽肩", "english": "broad shoulders", "type": "短语", "keyWords": ["broad"] },
    { "chinese": "广义上", "english": "in the broad sense", "type": "短语", "keyWords": ["broad"] },
    { "chinese": "v./n. (C) 广播", "english": "broadcast", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 广播(业)", "english": "broadcasting", "type": "单词", "keyWords": [] },
    { "chinese": "无线电广播", "english": "radio broadcasting", "type": "短语", "keyWords": ["broadcasting"] },
    { "chinese": "广播电台", "english": "a broadcasting station", "type": "短语", "keyWords": ["broadcasting"] },
    { "chinese": "足球赛实况转播", "english": "a live broadcast of a football game", "type": "短语", "keyWords": ["broadcast"] },
    { "chinese": "n. [U] 青铜；青铜色；[C] 青铜制品；铜像", "english": "bronze", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 兄弟", "english": "brother", "type": "单词", "keyWords": [] },
    { "chinese": "a. 兄弟的；亲兄弟般的", "english": "brotherly", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 兄弟般情谊", "english": "brotherhood", "type": "单词", "keyWords": [] },
    { "chinese": "与...兄弟般的关系", "english": "brotherly relations with", "type": "短语", "keyWords": ["brotherly"] },
    { "chinese": "n. (C) 额(头)；眉；眉毛(=eyebrow常用复数)；眉脊", "english": "brow", "type": "单词", "keyWords": [] },
    { "chinese": "a. 棕色的；n. (U) 棕色", "english": "brown", "type": "单词", "keyWords": [] },
    { "chinese": "v. 随便翻阅", "english": "browse", "type": "单词", "keyWords": [] },
    { "chinese": "浏览书籍", "english": "browse through books", "type": "短语", "keyWords": ["browse"] },
    { "chinese": "n. (U) 早午餐(将早、中餐合二为一，晚吃的早餐)", "english": "brunch", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 刷子；画笔；v. 刷，擦", "english": "brush", "type": "单词", "keyWords": [] },
    { "chinese": "擦去灰尘", "english": "brush the dirt off", "type": "短语", "keyWords": ["brush"] },
    { "chinese": "理学学士", "english": "B.S. (= Bachelor of Science)", "type": "短语", "keyWords": [] },
    { "chinese": "n. (C) 泡；vi. 起泡；冒泡；(感情)激动", "english": "bubble", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 水桶", "english": "bucket", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 预算(案)；v. 做预算；编入预算；安排", "english": "budget", "type": "单词", "keyWords": [] },
    { "chinese": "来年的预算(案)", "english": "the budget for the coming year", "type": "短语", "keyWords": ["budget"] },
    { "chinese": "明智地安排我的时间", "english": "budget my time wisely", "type": "短语", "keyWords": ["budget"] },
    { "chinese": "把购买汽车编入预算", "english": "budget the car payments", "type": "短语", "keyWords": ["budget"] },
    { "chinese": "n. (C) (pl. buffaloes) 水牛", "english": "buffalo", "type": "单词", "keyWords": [] },
    { "chinese": "n. 自助餐；快餐", "english": "buffet", "type": "单词", "keyWords": [] },
    { "chinese": "v. 建造，建设，发展，建立；积聚；增长；n. [U][C] 体形，体态，体格", "english": "build", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 大楼；建筑物，房屋", "english": "building", "type": "单词", "keyWords": [] },
    { "chinese": "a. 嵌入的；固定的；内在的；固有的", "english": "built-in", "type": "单词", "keyWords": [] },
    { "chinese": "建设社会主义", "english": "build socialism", "type": "短语", "keyWords": ["build"] },
    { "chinese": "增进健康，锻炼；加强；积聚；建立", "english": "build up (v./vi)", "type": "短语", "keyWords": ["build"] },
    { "chinese": "增进健康/建立卫生系统", "english": "build up the body/ the health system", "type": "短语", "keyWords": ["build"] },
    { "chinese": "建立良好关系/生意兴隆", "english": "build up good relations/ a good business", "type": "短语", "keyWords": ["build"] },
    { "chinese": "你的词汇量在逐渐增长。", "english": "Your vocabulary is gradually building up.", "type": "句子", "keyWords": ["build"] },
    { "chinese": "内嵌式壁橱", "english": "built-in cabinets", "type": "短语", "keyWords": ["built-in"] },
    { "chinese": "伟业非一日之功。", "english": "Rome was not built in a day.", "type": "句子", "keyWords": ["build"] },
    { "chinese": "n. (C) 灯泡；(植物)球茎", "english": "bulb", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 公牛", "english": "bull", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 子弹，枪弹", "english": "bullet", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 欺侮，欺负", "english": "bully", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 碰，撞；颠；n. (C) 撞击；碰撞声；a. 颠簸的；崎岖不平的", "english": "bump", "type": "单词", "keyWords": [] },
    { "chinese": "那部老爷车在路上颠簸着行驶。", "english": "The old car bumped along the road.", "type": "句子", "keyWords": ["bump"] },
    { "chinese": "(把头)撞在门上", "english": "bump (one's head) against the door", "type": "短语", "keyWords": ["bump"] },
    { "chinese": "撞；巧遇(meet with, run into, come across, encounter)", "english": "bump into", "type": "短语", "keyWords": ["bump"] },
    { "chinese": "那人滑了一下，撞在一个小男孩的身上。", "english": "The man slipped and bumped into a little boy.", "type": "句子", "keyWords": ["bump"] },
    { "chinese": "昨天我遇到一个多年未见的老朋友。", "english": "I bumped into an old friend yesterday whom I had not seen for years.", "type": "句子", "keyWords": ["bump"] },
    { "chinese": "n. (C) 束；串", "english": "bunch", "type": "单词", "keyWords": [] },
    { "chinese": "一串葡萄/一束花/一串钥匙", "english": "a bunch of grapes/flowers/ keys", "type": "短语", "keyWords": ["bunch"] },
    { "chinese": "n. (C) 捆；束；包", "english": "bundle", "type": "单词", "keyWords": [] },
    { "chinese": "一包衣服", "english": "a bundle of clothes", "type": "短语", "keyWords": ["bundle"] },
    { "chinese": "n. (C) 负荷，负重；v. 给予负担或麻烦；加负荷于", "english": "burden", "type": "单词", "keyWords": [] },
    { "chinese": "很重的负担", "english": "a heavy burden", "type": "短语", "keyWords": ["burden"] },
    { "chinese": "负有..的沉重负担", "english": "be burdened with", "type": "短语", "keyWords": ["burden"] },
    { "chinese": "使百姓承担沉重的赋税", "english": "burden the people with heavy taxes", "type": "短语", "keyWords": ["burden"] },
    { "chinese": "n. (C) 窃贼，夜盗", "english": "burglar", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C)[U] 盗窃", "english": "burglary", "type": "单词", "keyWords": [] },
    { "chinese": "v. 燃烧；发热；烧焦；呈绯红；n. [C] 烧伤；灼伤；电击伤；辐射伤；烧焦", "english": "burn", "type": "单词", "keyWords": [] },
    { "chinese": "被烧死", "english": "be burnt to death", "type": "短语", "keyWords": ["burn"] },
    { "chinese": "烧成灰烬", "english": "burn... down to the ground", "type": "短语", "keyWords": ["burn"] },
    { "chinese": "烧完，烧尽；(炉火等)烧了起来，旺起来；使恼怒，激怒", "english": "burn(..) up(vi/vt)", "type": "短语", "keyWords": ["burn"] },
    { "chinese": "闻到有东西烧焦", "english": "smell something burning", "type": "短语", "keyWords": ["burn"] },
    { "chinese": "她羞得脸绯红。", "english": "Her cheeks were burning with shame.", "type": "句子", "keyWords": ["burn"] },
    { "chinese": "读书(工作)到深夜，开夜车(近stay up, sit up)", "english": "burn the midnight oil", "type": "短语", "keyWords": ["burn"] },
    { "chinese": "手上的烧伤", "english": "a burn on the hand", "type": "短语", "keyWords": ["burn"] },
    { "chinese": "灼热(反freezing cold)", "english": "burning hot", "type": "短语", "keyWords": ["burn"] },
    { "chinese": "一个强烈的欲望", "english": "a burning desire", "type": "短语", "keyWords": ["burn"] },
    { "chinese": "vi/n. (C) 爆裂；胀破；爆炸；突然发出；进发；冲；间；v. 使爆裂；撞；突破", "english": "burst", "type": "单词", "keyWords": [] },
    { "chinese": "花蕾正在绽开。", "english": "The buds are bursting.", "type": "句子", "keyWords": ["burst"] },
    { "chinese": "门猛然打开。", "english": "The door burst open.", "type": "句子", "keyWords": ["burst"] },
    { "chinese": "扑进，闯进；插嘴", "english": "burst in (upon our conversation)", "type": "短语", "keyWords": ["burst"] },
    { "chinese": "忽然进入...状态", "english": "burst into (tears/ flames/ angry speech)", "type": "短语", "keyWords": ["burst"] },
    { "chinese": "哈哈大笑起来；忽然大笑起来", "english": "burst into laughter", "type": "短语", "keyWords": ["burst"] },
    { "chinese": "冒出；现出；突然发作；突然发生", "english": "burst out", "type": "短语", "keyWords": ["burst"] },
    { "chinese": "忽然大笑/大哭起来", "english": "burst out laughing/ crying", "type": "短语", "keyWords": ["burst"] },
    { "chinese": "突然大怒/大哭", "english": "a burst of anger/ tears", "type": "短语", "keyWords": ["burst"] },
    { "chinese": "vt. 掩埋；埋藏，遮盖，掩藏；埋头于(in)；n. (C) 埋葬，葬礼", "english": "bury/ burial", "type": "单词", "keyWords": [] },
    { "chinese": "埋头读书", "english": "bury oneself in one's book", "type": "短语", "keyWords": ["bury"] },
    { "chinese": "出神沉思", "english": "be buried in thought", "type": "短语", "keyWords": ["bury"] },
    { "chinese": "被活埋(近be caught alive被活捉)", "english": "be buried alive", "type": "短语", "keyWords": ["bury"] },
    { "chinese": "n. (C) 公共汽车", "english": "bus", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 灌木丛)；矮树丛；丛林；a. (灌木)茂密的，浓密的", "english": "bush/ bushy", "type": "单词", "keyWords": [] },
    { "chinese": "在树丛里", "english": "in the bush(es)", "type": "短语", "keyWords": ["bush"] },
    { "chinese": "旁敲侧击；说话拐弯抹角", "english": "beat around/ about the bush", "type": "短语", "keyWords": ["bush"] },
    { "chinese": "n. (U) 商业；生意；应做的事，任务，职责；n. (C) 行业；企业", "english": "business", "type": "单词", "keyWords": [] },
    { "chinese": "商业信", "english": "a business letter", "type": "短语", "keyWords": ["business"] },
    { "chinese": "营业时间", "english": "business hours", "type": "短语", "keyWords": ["business"] },
    { "chinese": "开业/歇业", "english": "open/ close a business", "type": "短语", "keyWords": ["business"] },
    { "chinese": "(因公)出差", "english": "on business", "type": "短语", "keyWords": ["business"] },
    { "chinese": "精通本行", "english": "know one's business", "type": "短语", "keyWords": ["business"] },
    { "chinese": "停业；破产，失业", "english": "go out of business", "type": "短语", "keyWords": ["business"] },
    { "chinese": "公事公办。", "english": "Business is business.", "type": "句子", "keyWords": ["business"] },
    { "chinese": "不要管闲事。", "english": "Mind your own business.", "type": "句子", "keyWords": ["business"] },
    { "chinese": "不关你事，别管闲事。", "english": "It is none of your business.", "type": "句子", "keyWords": ["business"] },
    { "chinese": "认真干起来；开始谈正经事；言归正传", "english": "get down to business/ (doing) sth.", "type": "短语", "keyWords": ["business"] },
    { "chinese": "a. 忙的；繁忙的；占线的", "english": "busy", "type": "单词", "keyWords": [] },
    { "chinese": "工作忙", "english": "be busy with/ over one's task", "type": "短语", "keyWords": ["busy"] },
    { "chinese": "忙于做某事(近be engaged in)", "english": "be busy (in) doing sth.", "type": "短语", "keyWords": ["busy"] },
    { "chinese": "这会儿电话占线。", "english": "The line's busy/ engaged at the moment.", "type": "句子", "keyWords": ["busy"] },
    { "chinese": "conj. 但是；(而)不(与否定式连用)；prep. 除了；ad. 不过，仅仅", "english": "but", "type": "单词", "keyWords": [] },
    { "chinese": "对不起，...", "english": "I'm sorry/Excuse me, but...", "type": "短语", "keyWords": ["but"] },
    { "chinese": "最后但并非最不重要", "english": "last but not least", "type": "短语", "keyWords": ["but"] },
    { "chinese": "老是，只是(but表示'除了')", "english": "do nothing but...", "type": "短语", "keyWords": ["but"] },
    { "chinese": "他只是一个劲地抱怨。", "english": "He does nothing but complain.", "type": "句子", "keyWords": ["but"] },
    { "chinese": "不得不；只得", "english": "have no choice but to do sth.", "type": "短语", "keyWords": ["but"] },
    { "chinese": "不得不；不禁(but表示'除了')", "english": "cannot but do sth/can't help but do sth./ can't choose but do sth.", "type": "短语", "keyWords": ["but"] },
    { "chinese": "他们不得不承认我们的要求是合理的。", "english": "They cannot (choose/ help) but admit that our requirement is reasonable.", "type": "句子", "keyWords": ["but"] },
    { "chinese": "根本不(可接形容词等，but表示'除了')", "english": "anything but", "type": "短语", "keyWords": ["but"] },
    { "chinese": "那绝不是真的。", "english": "That's anything but true.", "type": "句子", "keyWords": ["but"] },
    { "chinese": "不要把它放在地板上。", "english": "Put it anywhere but on the floor.", "type": "句子", "keyWords": ["but"] },
    { "chinese": "倒数第二(三)", "english": "last but one (two)", "type": "短语", "keyWords": ["but"] },
    { "chinese": "不是我不爱恺撒，而是我更爱罗马。", "english": "Not that I love Caesar less, but that I love Rome more.", "type": "句子", "keyWords": ["but"] },
    { "chinese": "要是没有(用虚拟语气)(近without, if it weren't/hadn't been for)", "english": "but for", "type": "短语", "keyWords": ["but"] },
    { "chinese": "倘若没有你，我早已淹死了。", "english": "But for you I should have been drowned.", "type": "句子", "keyWords": ["but"] },
    { "chinese": "几乎/差一点(就)完成了。", "english": "The job is all but finished.", "type": "句子", "keyWords": ["but"] },
    { "chinese": "她不过是一个孩子罢了。", "english": "She is but a child.", "type": "句子", "keyWords": ["but"] },
    { "chinese": "就照我说的办。/不要有二话。", "english": "There are no ifs or buts about it.", "type": "句子", "keyWords": ["but"] },
    { "chinese": "n. (C) 屠夫；屠户；肉食品商；vt. 屠宰；屠杀(近kill)", "english": "butcher", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 黄油；v. 涂黄油于", "english": "butter", "type": "单词", "keyWords": [] },
    { "chinese": "在面包上涂黄油", "english": "spread butter on bread", "type": "短语", "keyWords": ["butter"] },
    { "chinese": "谋生的职业；谋生之道", "english": "bread and butter", "type": "短语", "keyWords": ["butter"] },
    { "chinese": "n. (C) 蝴蝶", "english": "butterfly", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 扣子；纽扣；电钮，按钮(开关)", "english": "button", "type": "单词", "keyWords": [] },
    { "chinese": "vt/vi. 购买，购物；n. [C] 购买；便宜货", "english": "buy", "type": "单词", "keyWords": [] },
    { "chinese": "五块钱买了...", "english": "buy sth. for 5 yuan", "type": "短语", "keyWords": ["buy"] },
    { "chinese": "为某人买了某物", "english": "buy sth. for sb.", "type": "短语", "keyWords": ["buy"] },
    { "chinese": "购买力", "english": "buying power", "type": "短语", "keyWords": ["buy"] },
    { "chinese": "赊买", "english": "buy ... on credit", "type": "短语", "keyWords": ["buy"] },
    { "chinese": "买的车挺新/挺便宜", "english": "buy the car new/cheap", "type": "短语", "keyWords": ["buy"] },
    { "chinese": "美元的购买力下降了。", "english": "The dollar buys less today.", "type": "句子", "keyWords": ["buy"] },
    { "chinese": "这是一笔价钱合算的买卖。", "english": "It's a real buy at that price.", "type": "句子", "keyWords": ["buy"] },
    { "chinese": "prep. 靠近；(表示方法、手段)用，通过；经，由；到...为止；按照；ad. 在旁；过去", "english": "by", "type": "单词", "keyWords": [] },
    { "chinese": "夜行", "english": "walk by night", "type": "短语", "keyWords": ["by"] },
    { "chinese": "通常", "english": "by rule", "type": "短语", "keyWords": ["by"] },
    { "chinese": "顺便问一下", "english": "by the way", "type": "短语", "keyWords": ["by"] },
    { "chinese": "由于差错", "english": "by mistake", "type": "短语", "keyWords": ["by"] },
    { "chinese": "不久以后", "english": "by and by", "type": "短语", "keyWords": ["by"] },
    { "chinese": "轮流，交替", "english": "by turns", "type": "短语", "keyWords": ["by"] },
    { "chinese": "由后门进来", "english": "enter by the back door", "type": "短语", "keyWords": ["by"] },
    { "chinese": "经上海回来", "english": "return by Shanghai = return by way of Shanghai", "type": "短语", "keyWords": ["by"] },
    { "chinese": "我的表现在是五点。", "english": "It's just five o'clock by my watch.", "type": "句子", "keyWords": ["by"] },
    { "chinese": "他名叫约翰。", "english": "He is John by name.", "type": "句子", "keyWords": ["by"] },
    { "chinese": "生性/生来/习惯", "english": "by nature/by birth/by habit", "type": "短语", "keyWords": ["by"] },
    { "chinese": "你说'借'是什么意思？", "english": "What do you mean by 'borrow'?", "type": "句子", "keyWords": ["by"] },
    { "chinese": "用这种方法/决不/千方百计", "english": "by this/ no/all means", "type": "短语", "keyWords": ["by"] },
    { "chinese": "使吃惊；奇袭；学习，学会；认识到", "english": "take sb. by surprise; learn... by heart", "type": "短语", "keyWords": ["by"] },
    { "chinese": "按重量/体积/面积计(数)", "english": "by weight/ volume/size", "type": "短语", "keyWords": ["by"] },
    { "chinese": "按小时/加仑/周/百计(数)", "english": "by the hour/ the gallon/ the week/ the hundred", "type": "短语", "keyWords": ["by"] },
    { "chinese": "我按周领薪。", "english": "I'm paid by the week.", "type": "句子", "keyWords": ["by"] },
    { "chinese": "数以百计", "english": "by (the) hundreds", "type": "短语", "keyWords": ["by"] },
    { "chinese": "牵着某人的手走(近seize sb. by the collar/ arm/sleeve)", "english": "lead sb. by the hand", "type": "短语", "keyWords": ["by"] },
    { "chinese": "时光(飞逝)逝去", "english": "(time) go/fly by", "type": "短语", "keyWords": ["by"] },
    { "chinese": "那时附近没人。", "english": "There was no one by at the time.", "type": "句子", "keyWords": ["by"] },
    { "chinese": "每月存100元用以养老", "english": "lay (put) ¥100 by a month for old age", "type": "短语", "keyWords": ["by"] },
    { "chinese": "空中/陆地/海上旅行", "english": "travel by air/land/sea", "type": "短语", "keyWords": ["by"] },
    { "chinese": "我最迟五点到这里。", "english": "I will be here by five o'clock.", "type": "句子", "keyWords": ["by"] },
    { "chinese": "一点一点地/逐字地", "english": "little by little/ word by word", "type": "短语", "keyWords": ["by"] },
    { "chinese": "最最好的(老师)", "english": "by far the best (teacher)", "type": "短语", "keyWords": ["by"] },
    { "chinese": "一间长12英尺宽10英尺的房间", "english": "a room 10 feet by 12 feet", "type": "短语", "keyWords": ["by"] },
    { "chinese": "迟两分钟误了火车(by指增加或减少的幅度等)", "english": "miss the train by two minutes", "type": "短语", "keyWords": ["by"] },
    { "chinese": "从其交友知其为人。/察其友，知其人。", "english": "A man is known by the company he keeps.", "type": "句子", "keyWords": ["by"] },
    { "chinese": "interj. 再见", "english": "bye", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U] 卷心菜；甘蓝", "english": "cabbage", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 机舱；船舱；小(木)屋", "english": "cabin", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C)[U] 钢索；电缆；电报；adj. 有线电视的", "english": "cable", "type": "单词", "keyWords": [] },
    { "chinese": "通过电报", "english": "by cable", "type": "短语", "keyWords": ["cable"] },
    { "chinese": "有线电视", "english": "cable TV", "type": "短语", "keyWords": ["cable"] },
    { "chinese": "缆车", "english": "a cable car", "type": "短语", "keyWords": ["cable"] },
    { "chinese": "n. (C) 咖啡馆；小餐馆", "english": "cafe", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 自助餐厅(或食堂)", "english": "cafeteria", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 灾难，灾害；困苦；不幸(近disaster)", "english": "calamity", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 笼子", "english": "cage", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U] 蛋糕；饼；糕；肥皂等饼状物", "english": "cake", "type": "单词", "keyWords": [] },
    { "chinese": "一块肥皂", "english": "a cake of soap", "type": "短语", "keyWords": ["cake"] },
    { "chinese": "这是件轻松的事。", "english": "(It's) a piece of cake.", "type": "句子", "keyWords": ["cake"] },
    { "chinese": "不能两全。/不能兼得。", "english": "You can't eat your cake and have it (too).", "type": "句子", "keyWords": ["cake"] },
    { "chinese": "vi/vt. 计算；估计；揣测；n. (C)[U] 计算", "english": "calculate/ calculation", "type": "单词", "keyWords": [] },
    { "chinese": "指望；预期；期待(近depend on, rely on, count on, look to)", "english": "calculate on", "type": "短语", "keyWords": ["calculate"] },
    { "chinese": "指望明天天晴", "english": "calculate on the fine weather tomorrow", "type": "短语", "keyWords": ["calculate"] },
    { "chinese": "指望挣大钱", "english": "calculate on earning big money", "type": "短语", "keyWords": ["calculate"] },
    { "chinese": "n. (C) 计算器", "english": "calculator", "type": "单词", "keyWords": [] },
    { "chinese": "袖珍计算器", "english": "pocket calculator", "type": "短语", "keyWords": ["calculator"] },
    { "chinese": "n. (C) 日历；历法；日程表", "english": "calendar", "type": "单词", "keyWords": [] },
    { "chinese": "阴/阳历", "english": "the lunar/ solar calendar", "type": "短语", "keyWords": ["calendar"] },
    { "chinese": "v. 打电话给；请来；拜访；喊；称呼；把..叫；n. [C] 叫声；召唤；电话来访；呼叫", "english": "call", "type": "单词", "keyWords": [] },
    { "chinese": "大声叫喊；使出动，动员；召集", "english": "call out", "type": "短语", "keyWords": ["call"] },
    { "chinese": "召集会议", "english": "call a meeting", "type": "短语", "keyWords": ["call"] },
    { "chinese": "响应...的号召", "english": "answer the call of sb.", "type": "短语", "keyWords": ["call"] },
    { "chinese": "[美]点名", "english": "call the roll", "type": "短语", "keyWords": ["call"] },
    { "chinese": "直呼其名", "english": "call a person by name", "type": "短语", "keyWords": ["call"] },
    { "chinese": "骂人", "english": "call a person names", "type": "短语", "keyWords": ["call"] },
    { "chinese": "叫喊；需要；找", "english": "call for...", "type": "短语", "keyWords": ["call"] },
    { "chinese": "喊回来；回电话", "english": "call...back", "type": "短语", "keyWords": ["call"] },
    { "chinese": "晚些时候我来找你。", "english": "I'll call for you later.", "type": "句子", "keyWords": ["call"] },
    { "chinese": "这工作需要耐心。", "english": "The work calls for patience.", "type": "句子", "keyWords": ["call"] },
    { "chinese": "访问(某人的家)；停靠(港口、车站等)", "english": "call at...", "type": "短语", "keyWords": ["call"] },
    { "chinese": "这趟公交车每站都停。", "english": "The bus calls at every stop.", "type": "句子", "keyWords": ["call"] },
    { "chinese": "需要；号召；拜访某人(=pay a call on sb.)", "english": "call on...", "type": "短语", "keyWords": ["call"] },
    { "chinese": "昨日来访，适逢外出，甚憾。", "english": "I called on you yesterday, but unfortunately you were out.", "type": "句子", "keyWords": ["call"] },
    { "chinese": "叫来警察/叫来医生", "english": "call in the police/ call the doctor in", "type": "短语", "keyWords": ["call"] },
    { "chinese": "取消；叫开/走", "english": "call...off", "type": "短语", "keyWords": ["call"] },
    { "chinese": "停止罢工/取消约会/取消比赛/取消记者招待会", "english": "call off a strike/ the appointment/ the game/ the press conference", "type": "短语", "keyWords": ["call"] },
    { "chinese": "唤醒；回忆；想起；打电话", "english": "call...up", "type": "短语", "keyWords": ["call"] },
    { "chinese": "这张照片使我想起童年时代。", "english": "The photo called up the story of my childhood.", "type": "句子", "keyWords": ["call"] },
    { "chinese": "想起，记起", "english": "call sb/sth. to mind", "type": "短语", "keyWords": ["call"] },
    { "chinese": "这事使人想起那事实/他的名字。", "english": "This called the fact/ his name to mind.", "type": "句子", "keyWords": ["call"] },
    { "chinese": "a. 镇静的；(天气、海洋等)静的，平静的(无风状态)；v/vi. (使)镇静，(使)平静(辨析见quiet)；n. (U) 冷静，镇静；平静", "english": "calm/ calmness", "type": "单词", "keyWords": [] },
    { "chinese": "保持镇静", "english": "remain calm", "type": "短语", "keyWords": ["calm"] },
    { "chinese": "(使)镇静", "english": "calm (..) down", "type": "短语", "keyWords": ["calm"] },
    { "chinese": "n. (C) 卡，卡路里(热量单位)", "english": "calorie", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 骆驼", "english": "camel", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 照相机；摄像机；n. (C) 照相师，摄影师(尤指电影)", "english": "camera/ cameraman", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C)[U] 营；野营；阵营；vi. 宿营，野营；设营；n. (C) 露营者", "english": "camp/ camper", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 营地", "english": "campsite = campground", "type": "单词", "keyWords": [] },
    { "chinese": "夏令营", "english": "a summer camp", "type": "短语", "keyWords": ["camp"] },
    { "chinese": "去露营", "english": "go camping", "type": "短语", "keyWords": ["camp"] },
    { "chinese": "n. (C) 战役；(政治或商业性)活动；竞选运动；vi. 斗争；开展/参加运动；从事/参加竞选运动", "english": "campaign", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (大学)校园", "english": "campus", "type": "单词", "keyWords": [] },
    { "chinese": "在校园里", "english": "on (the) campus", "type": "短语", "keyWords": ["campus"] },
    { "chinese": "n. (C)[美] 罐头，听头[英]tin；v. 把..装成罐头；a. 罐装的", "english": "can/ canned", "type": "单词", "keyWords": [] },
    { "chinese": "罐头肉", "english": "canned meat", "type": "短语", "keyWords": ["canned"] },
    { "chinese": "aux.v. 会；能够；可能(用于否定句、疑问句)；理论上可能(可用于肯定句中)", "english": "can", "type": "单词", "keyWords": [] },
    { "chinese": "决不会...太...，无论...也不为过", "english": "cannot.. too...", "type": "短语", "keyWords": ["can"] },
    { "chinese": "人越谦虚越好。/无论怎样谦虚都不为过。", "english": "You cannot be too modest.", "type": "句子", "keyWords": ["can"] },
    { "chinese": "怎么可能(...)？", "english": "How can it be(that...)?", "type": "短语", "keyWords": ["can"] },
    { "chinese": "好奇可能招引麻烦。", "english": "Curiosity can get you into trouble.", "type": "句子", "keyWords": ["can"] },
    { "chinese": "n. (C) 运河；沟渠；水道", "english": "canal", "type": "单词", "keyWords": [] },
    { "chinese": "大运河", "english": "the Grand Canal", "type": "短语", "keyWords": ["canal"] },
    { "chinese": "v. 取消；删去(近call off)", "english": "cancel", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C)[U] 癌(症)", "english": "cancer", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 候选人；求职者", "english": "candidate", "type": "单词", "keyWords": [] },
    { "chinese": "市长候选人", "english": "the candidate for mayor", "type": "短语", "keyWords": ["candidate"] },
    { "chinese": "n. [C] 蜡烛", "english": "candle", "type": "单词", "keyWords": [] },
    { "chinese": "点燃了的蜡烛", "english": "a lighted candle", "type": "短语", "keyWords": ["candle"] },
    { "chinese": "n. (C)[U][美] 糖果[英]sweets", "english": "candy", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 手杖；棒；甘蔗", "english": "cane/ sugar cane", "type": "单词", "keyWords": [] },
    { "chinese": "aux.v. 不能(can的否定式，比can not更常用)", "english": "cannot", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 小卖部；临时餐室；食堂", "english": "canteen", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 帽子，便帽；v. 给...戴帽/加盖/加顶；覆盖；笼罩", "english": "cap", "type": "单词", "keyWords": [] },
    { "chinese": "冰冠，冰盖", "english": "ice cap", "type": "短语", "keyWords": ["cap"] },
    { "chinese": "a. 有能力的(of)；n. (C)[U] 能力(of)", "english": "capable/ capability", "type": "单词", "keyWords": [] },
    { "chinese": "有能力做...", "english": "be capable of doing sth.", "type": "短语", "keyWords": ["capable"] },
    { "chinese": "n. (C) 首都；首府；资本；大写字母；a. 可判死刑的；首都的；政府所在地的，资本的；主要的；大写的", "english": "capital", "type": "单词", "keyWords": [] },
    { "chinese": "死罪", "english": "a capital crime", "type": "短语", "keyWords": ["capital"] },
    { "chinese": "死刑", "english": "capital punishment", "type": "短语", "keyWords": ["capital"] },
    { "chinese": "大写字母", "english": "capital letters", "type": "短语", "keyWords": ["capital"] },
    { "chinese": "a. 资本主义的；n. [C] 资本家；n. [C] 资本主义(制度)", "english": "capitalist/ capitalism", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) [药]胶囊；[航空]密封舱", "english": "capsule", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 首领；船长；(球队的)队长；上尉", "english": "captain", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 捕获；俘虏；占领；n. (C) 俘虏；战利品；U 捕获，夺得", "english": "capture", "type": "单词", "keyWords": [] },
    { "chinese": "被活捉", "english": "be captured alive", "type": "短语", "keyWords": ["capture"] },
    { "chinese": "n. (C) 汽车，小汽车；(火车载客的)车厢", "english": "car", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 碳；a. (含)碳的", "english": "carbon/ carbonic", "type": "单词", "keyWords": [] },
    { "chinese": "二氧化碳", "english": "carbon dioxide", "type": "短语", "keyWords": ["carbon"] },
    { "chinese": "n. (C) 卡片；扑克牌", "english": "card", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 羊毛开衫", "english": "cardigan", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 挂念；忧虑，烦恼；照管，看护；注意，当心；vi. 照管，看护(for)；爱好，愿意(for)；关心，介意(about)", "english": "care", "type": "单词", "keyWords": [] },
    { "chinese": "照顾(可以用于肯定句)；喜欢，想要(一般用于疑问句和否定句)", "english": "care for", "type": "短语", "keyWords": ["care"] },
    { "chinese": "什么肉我都不吃，鱼也不对我的胃口。", "english": "I do not care much for meat of any kind, and I cannot stand fish.", "type": "句子", "keyWords": ["care"] },
    { "chinese": "关心，在乎(用于一般疑问句和否定句)", "english": "care about", "type": "短语", "keyWords": ["care"] },
    { "chinese": "没有人在乎我干什么。", "english": "Nobody cares (about) what I do.", "type": "句子", "keyWords": ["care"] },
    { "chinese": "他愿不愿跟我们一块儿去？", "english": "Will he care to come with us?", "type": "句子", "keyWords": ["care"] },
    { "chinese": "照管；爱护；照料", "english": "take care of", "type": "短语", "keyWords": ["care"] },
    { "chinese": "当心不要把它打碎了。", "english": "Take care not to break it. = Take care you don't break it.", "type": "句子", "keyWords": ["care"] },
    { "chinese": "把...托给...照顾", "english": "leave...in/ under sb.'s care", "type": "短语", "keyWords": ["care"] },
    { "chinese": "n. (C) 生涯，职业", "english": "career", "type": "单词", "keyWords": [] },
    { "chinese": "从事实业，在商界", "english": "a business career", "type": "短语", "keyWords": ["career"] },
    { "chinese": "从政", "english": "a political career", "type": "短语", "keyWords": ["career"] },
    { "chinese": "a. 小心的，仔细的", "english": "careful", "type": "单词", "keyWords": [] },
    { "chinese": "当心别从梯子上掉下来。", "english": "Be careful not to fall off the ladder. = Be careful that you don't fall off the ladder.", "type": "句子", "keyWords": ["careful"] },
    { "chinese": "花钱/用钱时慎重些", "english": "be careful with your money", "type": "短语", "keyWords": ["careful"] },
    { "chinese": "当心火线。", "english": "Be careful with the live wires.", "type": "句子", "keyWords": ["careful"] },
    { "chinese": "关切；珍重，注意，留意", "english": "be careful of", "type": "短语", "keyWords": ["careful"] },
    { "chinese": "a. 粗心的，疏忽的；n. (C) 粗心", "english": "careless/ carelessness", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 由船、飞机、车辆装载的)货物", "english": "cargo", "type": "单词", "keyWords": [] },
    { "chinese": "一船/车铁", "english": "a cargo of iron", "type": "短语", "keyWords": ["cargo"] },
    { "chinese": "货船", "english": "a cargo ship", "type": "短语", "keyWords": ["cargo"] },
    { "chinese": "载/卸货", "english": "load/ unload a cargo", "type": "短语", "keyWords": ["cargo"] },
    { "chinese": "n. (C) 木匠", "english": "carpenter", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 地毯；地毯状覆盖物", "english": "carpet", "type": "单词", "keyWords": [] },
    { "chinese": "红地毯", "english": "red carpet", "type": "短语", "keyWords": ["carpet"] },
    { "chinese": "一层厚厚的落叶", "english": "a carpet of leaves", "type": "短语", "keyWords": ["carpet"] },
    { "chinese": "n. [C] 载客的)四轮马车；车辆；[英]铁路客车车厢[美]car", "english": "carriage", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 胡萝卜", "english": "carrot", "type": "单词", "keyWords": [] },
    { "chinese": "v. 传送；搬运；运载；提；背；搬；负载；携带；传递，登出(消息等)；担负", "english": "carry", "type": "单词", "keyWords": [] },
    { "chinese": "撤开腿拼命跑", "english": "run as fast as his legs could carry him", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "携带枪支", "english": "carry a gun", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "肩上扛着盒子", "english": "carry a box on one's shoulder", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "大梁支撑屋顶的全部重量。", "english": "The timber carries the whole weight of the roof.", "type": "句子", "keyWords": ["carry"] },
    { "chinese": "带去，拿去；冲走；使激动得失控，使倾倒", "english": "carry..away", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "音乐使他陶醉。", "english": "Music has carried him away.", "type": "句子", "keyWords": ["carry"] },
    { "chinese": "完成，成就，了结；贯彻，落实，实行，执行(计划、命令)", "english": "carry..out", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "他没有资金落实他的计划。", "english": "He hasn't the funds to carry out his design.", "type": "句子", "keyWords": ["carry"] },
    { "chinese": "进行(下去)", "english": "carry (.) on (with sth.) (vt/vi)", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "夜间施工", "english": "carry on construction work at night", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "把我们的工作进行下去", "english": "carry on with our work", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "坚持到底，支持到底；贯彻，实行，完成(计划等)", "english": "carry...through", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "无论如何我们要拼搏到底。", "english": "At all events we will carry the struggle through to the end.", "type": "句子", "keyWords": ["carry"] },
    { "chinese": "得(奖)；夺去；诱拐；(病)夺去人命", "english": "carry...off", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "赢得奖品/奖牌", "english": "carry off the prize/ the medal", "type": "短语", "keyWords": ["carry"] },
    { "chinese": "他患肺癌死了。", "english": "He was carried off by lung cancer.", "type": "句子", "keyWords": ["carry"] },
    { "chinese": "n. (C) 运送人；运载工具；航空母舰", "english": "carrier", "type": "单词", "keyWords": [] },
    { "chinese": "航空母舰", "english": "an aircraft carrier", "type": "短语", "keyWords": ["carrier"] },
    { "chinese": "n. (C) 大车；手推车", "english": "cart", "type": "单词", "keyWords": [] },
    { "chinese": "前后颠倒；本末倒置", "english": "put the cart before the horse", "type": "短语", "keyWords": ["cart"] },
    { "chinese": "n. (C) 动画片；漫画", "english": "cartoon", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 雕刻，刻；切开；划分；深深印在...上", "english": "carve", "type": "单词", "keyWords": [] },
    { "chinese": "用石头雕像", "english": "carve a figure out of stone", "type": "短语", "keyWords": ["carve"] },
    { "chinese": "n. [C] 实例，事例，情况；案例；病例；箱，盒", "english": "case", "type": "单词", "keyWords": [] },
    { "chinese": "病历，个人历史", "english": "case history", "type": "短语", "keyWords": ["case"] },
    { "chinese": "这是常有的事", "english": "as is often the case", "type": "短语", "keyWords": ["case"] },
    { "chinese": "他没有来，这是常有的事。", "english": "He was absent, as is often the case.", "type": "句子", "keyWords": ["case"] },
    { "chinese": "假使(=if)；免得，以免(=lest)；以防(万一)", "english": "in case(连词)", "type": "短语", "keyWords": ["case"] },
    { "chinese": "万一下雨，就别等我了。", "english": "In case it should rain, don't expect me.", "type": "句子", "keyWords": ["case"] },
    { "chinese": "带上伞，以防下雨。", "english": "Take your umbrella, in case it rains.", "type": "句子", "keyWords": ["case"] },
    { "chinese": "天可能下雨，你最好带上伞以防万一。", "english": "It may rain. You'd better take an umbrella (just) in case.", "type": "句子", "keyWords": ["case"] },
    { "chinese": "遇到...的时候", "english": "in case of", "type": "短语", "keyWords": ["case"] },
    { "chinese": "遇必要时，在紧急时", "english": "in case of need", "type": "短语", "keyWords": ["case"] },
    { "chinese": "遇火警时，即按警铃。", "english": "In case of fire, ring the alarm bell.", "type": "句子", "keyWords": ["case"] },
    { "chinese": "就...来说；至于(近in/ with respect to, in/ with regard to, as to, as for)", "english": "in the case of...", "type": "短语", "keyWords": ["case"] },
    { "chinese": "古时候，医生碰到病人患各种热病时总是给病人放血。", "english": "In old times, in the case of fevers, the physician always let blood from the patient.", "type": "句子", "keyWords": ["case"] },
    { "chinese": "如果是那样的话", "english": "in that case", "type": "短语", "keyWords": ["case"] },
    { "chinese": "无论如何，总之", "english": "in any case", "type": "短语", "keyWords": ["case"] },
    { "chinese": "决不(见account)", "english": "in no case", "type": "短语", "keyWords": ["case"] },
    { "chinese": "n. (U) 现金，现款；v. 把..兑换现款", "english": "cash", "type": "单词", "keyWords": [] },
    { "chinese": "把支票兑现", "english": "cash this check", "type": "短语", "keyWords": ["cash"] },
    { "chinese": "你们可以用支票付款，也可以用现金付款。", "english": "You can pay the bill in check or in cash.", "type": "句子", "keyWords": ["cash"] },
    { "chinese": "n. (C) 出纳员；收银员", "english": "cashier", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 磁带盒；胶卷暗盒；卡带", "english": "cassette", "type": "单词", "keyWords": [] },
    { "chinese": "v. 扔，投，抛(只用于若干特殊句子)；选派/指定(某人)扮演角色", "english": "cast", "type": "单词", "keyWords": [] },
    { "chinese": "把渔网撒进了大海", "english": "cast their nets into the sea", "type": "短语", "keyWords": ["cast"] },
    { "chinese": "掷骰子", "english": "cast a dice", "type": "短语", "keyWords": ["cast"] },
    { "chinese": "用(眼光)一扫", "english": "cast a glance at", "type": "短语", "keyWords": ["cast"] },
    { "chinese": "指定由她主演", "english": "cast her as the lead", "type": "短语", "keyWords": ["cast"] }
];
