const qgl49_56 = [
    { "chinese": "n. 城堡", "english": "castle", "type": "单词", "keyWords": [] },
    { "chinese": "抱幻想，存梦想", "english": "build castles in the air", "type": "短语", "keyWords": ["castle"] },
    { "chinese": "空中楼阁，空想", "english": "a castle in the air", "type": "短语", "keyWords": ["castle"] },
    { "chinese": "adj. 偶然的；随便的；不经意的", "english": "casual", "type": "单词", "keyWords": [] },
    { "chinese": "便服", "english": "casual clothes", "type": "短语", "keyWords": ["casual"] },
    { "chinese": "即席发言", "english": "a casual remark", "type": "短语", "keyWords": ["casual"] },
    { "chinese": "随意", "english": "in a casual way", "type": "短语", "keyWords": ["casual"] },
    { "chinese": "n. 猫", "english": "cat", "type": "单词", "keyWords": [] },
    { "chinese": "下倾盆大雨。/大雨滂沱。", "english": "It rains cats and dogs.", "type": "句子", "keyWords": ["cat"] },
    { "chinese": "使秘密泄露，露马脚", "english": "let the cat out of the bag", "type": "短语", "keyWords": ["cat"] },
    { "chinese": "猫儿不在，老鼠成精。", "english": "When the cat's away, the mice will play.", "type": "句子", "keyWords": ["cat"] },
    { "chinese": "n. 目录（簿或册）；v. 编目录", "english": "catalogue", "type": "单词", "keyWords": [] },
    { "chinese": "v. 抓住；逮着，捕获；看到，发觉；赶上；绊（夹）住；听懂；染上（疾病）", "english": "catch", "type": "单词", "keyWords": [] },
    { "chinese": "风筝被树挂住了。", "english": "The kite caught in a tree.", "type": "句子", "keyWords": ["catch"] },
    { "chinese": "门把手钩住了她的衣服。", "english": "Her dress caught on the handle. = The handle caught her dress.", "type": "句子", "keyWords": ["catch"] },
    { "chinese": "引起某人注意", "english": "catch one's eye", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "抓住", "english": "catch hold of", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "抓住某人的手臂", "english": "catch sb. by the arm", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "看到", "english": "catch sight of", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "看到一眼", "english": "catch a glimpse of", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "设法抓住；想抓住", "english": "catch at", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "追着，赶上", "english": "catch up with", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "着凉，感冒", "english": "catch (a) cold", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "遇雨/遇上交通堵塞/落入陷阱或圈套", "english": "be caught in the rain/the traffic/a trap", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "（突然知道或意识到）发觉某人正在...，当场撞见某人在...", "english": "catch sb. doing sth.", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "喘口气；吓一跳；（由于惊吓）暂时停止呼吸", "english": "catch one's breath", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "懂某人的意思", "english": "catch one's meaning", "type": "短语", "keyWords": ["catch"] },
    { "chinese": "vi. 供应伙食；迎合，满足（to/for）", "english": "cater", "type": "单词", "keyWords": [] },
    { "chinese": "投合一般人的趣味/迎合顾客的需求", "english": "cater to popular tastes/ the need of the customers", "type": "短语", "keyWords": ["cater"] },
    { "chinese": "n. 牛（只用作复数，比较people, police, clothes）", "english": "cattle", "type": "单词", "keyWords": [] },
    { "chinese": "20头牛", "english": "20 (head of) cattle", "type": "短语", "keyWords": ["cattle"] },
    { "chinese": "n. 起因，原因；事业；v. 使发生（bring about）；给...带来", "english": "cause", "type": "单词", "keyWords": [] },
    { "chinese": "因果", "english": "cause and effect", "type": "短语", "keyWords": ["cause"] },
    { "chinese": "导致洪水/火灾产生的原因", "english": "the cause of the flood/ the fire", "type": "短语", "keyWords": ["cause"] },
    { "chinese": "教育事业/和平事业", "english": "the cause of education/peace", "type": "短语", "keyWords": ["cause"] },
    { "chinese": "使...做某事", "english": "cause sb./sth. to do sth.", "type": "短语", "keyWords": ["cause"] },
    { "chinese": "给某人带来...；惹起", "english": "cause sb. sth. = cause sth. to sb.", "type": "短语", "keyWords": ["cause"] },
    { "chinese": "n. 小心；谨慎；警告；v. 警告；劝...小心", "english": "caution", "type": "单词", "keyWords": [] },
    { "chinese": "托尼告诫说不要歪曲事实。", "english": "Tony cautioned against misrepresenting the situation.", "type": "句子", "keyWords": ["caution"] },
    { "chinese": "很显然，这份声明用意在于警告首尔别再试图阻止委员会的行动。", "english": "The statement clearly was intended to caution Seoul against attempting to block the council's action again.", "type": "句子", "keyWords": ["caution"] },
    { "chinese": "警告某人不要做某事", "english": "caution/ warn sb. not to do sth.", "type": "短语", "keyWords": ["caution"] },
    { "chinese": "n. 山洞；地洞；洞穴；vi. 塌落，倒坍，陷落", "english": "cave", "type": "单词", "keyWords": [] },
    { "chinese": "坍塌", "english": "cave in", "type": "短语", "keyWords": ["cave"] },
    { "chinese": "n. 激光唱片", "english": "CD (=compact disc)", "type": "单词", "keyWords": [] },
    { "chinese": "v. 停止；n. 停止（现在仅用于成语without cease中）", "english": "cease", "type": "单词", "keyWords": [] },
    { "chinese": "停止做某事（书面语，现在通常说stop doing）", "english": "cease to do/ doing", "type": "短语", "keyWords": ["cease"] },
    { "chinese": "雨停", "english": "cease to rain/raining", "type": "短语", "keyWords": ["cease"] },
    { "chinese": "不再存在，死亡；灭亡", "english": "cease to exist", "type": "短语", "keyWords": ["cease"] },
    { "chinese": "这位伟人与世长辞了。", "english": "The great man ceased to think.", "type": "句子", "keyWords": ["cease"] },
    { "chinese": "n. 庆祝会、活动；v. 庆祝，赞颂", "english": "celebrate", "type": "单词", "keyWords": [] },
    { "chinese": "庆祝国庆", "english": "celebrate National Day", "type": "短语", "keyWords": ["celebrate"] },
    { "chinese": "举行庆祝会", "english": "hold a celebration", "type": "短语", "keyWords": ["celebration"] },
    { "chinese": "为庆祝...（in honour of, in memory of, in search of...）", "english": "in celebration of", "type": "短语", "keyWords": ["celebration"] },
    { "chinese": "n. 名人", "english": "celebrity", "type": "单词", "keyWords": [] },
    { "chinese": "n. 细胞；电池；单人牢房", "english": "cell", "type": "单词", "keyWords": [] },
    { "chinese": "n. 手机，移动电话", "english": "cellphone", "type": "单词", "keyWords": [] },
    { "chinese": "n. 水泥", "english": "cement", "type": "单词", "keyWords": [] },
    { "chinese": "n. 墓地，坟地", "english": "cemetery", "type": "单词", "keyWords": [] },
    { "chinese": "n. 分（美国货币单位），分币", "english": "cent", "type": "单词", "keyWords": [] },
    { "chinese": "a./n. 摄氏（的）；百分度（的）", "english": "centigrade (=Celsius)", "type": "单词", "keyWords": [] },
    { "chinese": "n. 厘米", "english": "centimeter", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 中心的；中央的；主要的", "english": "central", "type": "单词", "keyWords": [] },
    { "chinese": "中央空调", "english": "central air conditioning", "type": "短语", "keyWords": ["central"] },
    { "chinese": "n. 中心；中央", "english": "centre", "type": "单词", "keyWords": [] },
    { "chinese": "在...中央", "english": "in the centre of", "type": "短语", "keyWords": ["centre"] },
    { "chinese": "n. 百年，一世纪", "english": "century", "type": "单词", "keyWords": [] },
    { "chinese": "n. 典礼；仪式", "english": "ceremony", "type": "单词", "keyWords": [] },
    { "chinese": "举行开幕/闭幕式", "english": "perform the opening/closing ceremony", "type": "短语", "keyWords": ["ceremony"] },
    { "chinese": "adj. 某一，某些（只作定语）；一定程度的；确实的（+ to do）；有把握的（作表语+ of）", "english": "certain", "type": "单词", "keyWords": [] },
    { "chinese": "需要某些技能", "english": "call for certain skills", "type": "短语", "keyWords": ["certain"] },
    { "chinese": "一个叫作史密斯的人", "english": "a certain Smith", "type": "短语", "keyWords": ["certain"] },
    { "chinese": "到某种程度", "english": "to a certain degree/ extent", "type": "短语", "keyWords": ["certain"] },
    { "chinese": "确定地；肯定地（近for sure）", "english": "for certain", "type": "短语", "keyWords": ["certain"] },
    { "chinese": "一定会...（近be sure to do..., be bound to do...）", "english": "be certain to do sth.", "type": "短语", "keyWords": ["certain"] },
    { "chinese": "他一定会成功。", "english": "He is certain to succeed.", "type": "句子", "keyWords": ["certain"] },
    { "chinese": "对...有把握（近be sure of, be sure that）", "english": "be certain of...", "type": "短语", "keyWords": ["certain"] },
    { "chinese": "我对成功有把握。", "english": "I am certain of my success. = I am certain that I will succeed.", "type": "句子", "keyWords": ["certain"] },
    { "chinese": "把...弄明白，弄确实，保证", "english": "make certain (of/that)", "type": "短语", "keyWords": ["certain"] },
    { "chinese": "要弄清楚我们是在往哪儿走。", "english": "Make certain where we are going.", "type": "句子", "keyWords": ["certain"] },
    { "chinese": "搞清楚他来的日期。", "english": "Please make certain of the date of his arrival.", "type": "句子", "keyWords": ["certain"] },
    { "chinese": "...是肯定的；一定会...（不能用sure）", "english": "It's certain that...", "type": "短语", "keyWords": ["certain"] },
    { "chinese": "（毫无疑问）他一定会赢。", "english": "It's certain that he'll win. / It is out of question that he'll win. / It is doubtless that he'll win. / (There is) no doubt that he'll win. / He is sure to win. / He is bound to win.", "type": "句子", "keyWords": ["certain"] },
    { "chinese": "adv. 的确，无疑地，必定；[口]当然，当然可以", "english": "certainly", "type": "单词", "keyWords": [] },
    { "chinese": "n. 确定性；确信，肯定；确定的事，必然的事（uncertainty）", "english": "certainty", "type": "单词", "keyWords": [] },
    { "chinese": "n. 证书；证明；（毕业）文凭；v. （常用被动）发证书", "english": "certificate", "type": "单词", "keyWords": [] },
    { "chinese": "v. 证明...", "english": "certify", "type": "单词", "keyWords": [] },
    { "chinese": "n. 链条；连锁；系列；（pl.）镣铐；v. 用链子拴住", "english": "chain", "type": "单词", "keyWords": [] },
    { "chinese": "被链条拴着（近in furs穿着毛皮大衣，in rags衣衫褴褛）", "english": "in chains", "type": "短语", "keyWords": ["chain"] },
    { "chinese": "n. 椅子；v. 使入座；担任（会议的）主席；担任（宴会等的）主持人", "english": "chair", "type": "单词", "keyWords": [] },
    { "chinese": "n. 主席；议长；董事长；会长", "english": "chairman", "type": "单词", "keyWords": [] },
    { "chinese": "被推选为会长", "english": "be made chairman", "type": "短语", "keyWords": ["chairman"] },
    { "chinese": "n. 粉笔", "english": "chalk", "type": "单词", "keyWords": [] },
    { "chinese": "n. 挑战；v. （向...）提出挑战", "english": "challenge", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 挑战性的，挑逗的", "english": "challenging", "type": "单词", "keyWords": [] },
    { "chinese": "应战", "english": "accept/take a challenge", "type": "短语", "keyWords": ["challenge"] },
    { "chinese": "公然对抗权威", "english": "a challenge to the authority", "type": "短语", "keyWords": ["challenge"] },
    { "chinese": "向我挑战下棋", "english": "challenge me to a game of chess/ me to play a game of chess", "type": "短语", "keyWords": ["challenge"] },
    { "chinese": "很具有挑战性的任务", "english": "a challenging task", "type": "短语", "keyWords": ["challenging"] },
    { "chinese": "adj. 得第一名的；冠军的；优胜的；第一流的；n. 冠军；斗争者；捍卫者", "english": "champion", "type": "单词", "keyWords": [] },
    { "chinese": "n. 冠军头衔/称号/地位；锦标赛", "english": "championship", "type": "单词", "keyWords": [] },
    { "chinese": "锦标赛", "english": "a championship series", "type": "短语", "keyWords": ["championship"] },
    { "chinese": "n. （常指因运气或偶然而出现的）机遇；机会；侥幸；可能性；vi. 碰巧；偶然发生", "english": "chance", "type": "单词", "keyWords": [] },
    { "chinese": "偶然；意外地", "english": "by chance", "type": "短语", "keyWords": ["chance"] },
    { "chinese": "不知道为什么", "english": "by some chance", "type": "短语", "keyWords": ["chance"] },
    { "chinese": "碰运气；好歹试试看", "english": "take chances/ one's chance/ a chance", "type": "短语", "keyWords": ["chance"] },
    { "chinese": "偶然发现那本书/他的朋友", "english": "chance on/ upon the book/his friend", "type": "短语", "keyWords": ["chance"] },
    { "chinese": "碰巧（happen to do sth.）", "english": "chance to do sth.", "type": "短语", "keyWords": ["chance"] },
    { "chinese": "听天由命，听其自然", "english": "leave things to chance", "type": "短语", "keyWords": ["chance"] },
    { "chinese": "很可能...", "english": "Chances are that...", "type": "短语", "keyWords": ["chance"] },
    { "chinese": "她很可能已登记注册。", "english": "Chances are that she's already registered.", "type": "句子", "keyWords": ["chance"] },
    { "chinese": "不大可能做某事", "english": "There is little chance of doing sth.", "type": "短语", "keyWords": ["chance"] },
    { "chinese": "几乎不可能产生有害的辐射物了。", "english": "There is little chance of producing harmful radiations.", "type": "句子", "keyWords": ["chance"] },
    { "chinese": "vi./v. 改变；变化；换（车、衣服）；n. 改变，变更；找头，零钱", "english": "change", "type": "单词", "keyWords": [] },
    { "chinese": "把一张50镑钞票兑换成金币", "english": "change a fifty-pound note into gold", "type": "短语", "keyWords": ["change"] },
    { "chinese": "拿...换...", "english": "change ...for...", "type": "短语", "keyWords": ["change"] },
    { "chinese": "她把衣服拿回商店换了一件大号的。", "english": "She took the coat back to the shop and changed it for one of a bigger size.", "type": "句子", "keyWords": ["change"] },
    { "chinese": "换乘14路公交车", "english": "change to Bus No.14", "type": "短语", "keyWords": ["change"] },
    { "chinese": "去换衣服！", "english": "Get changed!", "type": "句子", "keyWords": ["change"] },
    { "chinese": "在5号站台换乘去南京的火车", "english": "change trains for Nanjing at platform five", "type": "短语", "keyWords": ["change"] },
    { "chinese": "为了替换买了两条领带", "english": "buy two ties for a change", "type": "短语", "keyWords": ["change"] },
    { "chinese": "我没有零钱。", "english": "I have no small change about me.", "type": "句子", "keyWords": ["change"] },
    { "chinese": "adj. 易变的；可变的", "english": "changeable", "type": "单词", "keyWords": [] },
    { "chinese": "易变的天气", "english": "changeable weather", "type": "短语", "keyWords": ["changeable"] },
    { "chinese": "n. （电视）频道；海峡；途径；（常pl.）官方渠道", "english": "channel", "type": "单词", "keyWords": [] },
    { "chinese": "通过可靠途径", "english": "through a reliable channel", "type": "短语", "keyWords": ["channel"] },
    { "chinese": "英吉利海峡", "english": "the English Channel", "type": "短语", "keyWords": ["channel"] },
    { "chinese": "n. （书等的）章，回，篇", "english": "chapter", "type": "单词", "keyWords": [] },
    { "chinese": "把你们的书翻到第四章。", "english": "Open your books at Chapter 4.", "type": "句子", "keyWords": ["chapter"] },
    { "chinese": "n. 性格，品格，个性；（事物的）特性，性质；（戏剧等中的）人物；角色；（汉）字", "english": "character", "type": "单词", "keyWords": [] },
    { "chinese": "有着不同的性质", "english": "be different in character", "type": "短语", "keyWords": ["character"] },
    { "chinese": "意志坚强/薄弱", "english": "a strong/ weak character", "type": "短语", "keyWords": ["character"] },
    { "chinese": "主角", "english": "a leading character", "type": "短语", "keyWords": ["character"] },
    { "chinese": "有个性的人，有骨气的人", "english": "a man of character", "type": "短语", "keyWords": ["character"] },
    { "chinese": "培养品性", "english": "build up one's character", "type": "短语", "keyWords": ["character"] },
    { "chinese": "汉字", "english": "Chinese characters", "type": "短语", "keyWords": ["character"] },
    { "chinese": "狄更斯小说中的人物", "english": "the characters in Charles Dickens' novels", "type": "短语", "keyWords": ["character"] },
    { "chinese": "n. 特征，特性，特色；adj. 特有的；有特性的；表特性的", "english": "characteristic", "type": "单词", "keyWords": [] },
    { "chinese": "中国人区别于日本人的特征是什么？", "english": "What are the characteristics that distinguish the Chinese from the Japanese?", "type": "句子", "keyWords": ["characteristic"] },
    { "chinese": "苹果所特有的味道", "english": "the characteristic flavor of apples", "type": "短语", "keyWords": ["characteristic"] },
    { "chinese": "n. 主管，掌管；指控；费用；充电；v. 收费，要价；控诉；充电", "english": "charge", "type": "单词", "keyWords": [] },
    { "chinese": "就....（向某人）要价", "english": "charge (sb.) some money for sth.", "type": "短语", "keyWords": ["charge"] },
    { "chinese": "双人间你们收费多少？", "english": "How much do you charge (me) for a double room?", "type": "句子", "keyWords": ["charge"] },
    { "chinese": "控告某人（近accuse sb. of sth.）", "english": "charge...with...", "type": "短语", "keyWords": ["charge"] },
    { "chinese": "以盗窃罪控告某人，控告某人行窃", "english": "charge sb. with theft", "type": "短语", "keyWords": ["charge"] },
    { "chinese": "免费", "english": "free of charge", "type": "短语", "keyWords": ["charge"] },
    { "chinese": "担任；保管；看守，看管", "english": "take charge of...", "type": "短语", "keyWords": ["charge"] },
    { "chinese": "主管；负责", "english": "in charge of...", "type": "短语", "keyWords": ["charge"] },
    { "chinese": "主任医师", "english": "the doctor in charge", "type": "短语", "keyWords": ["charge"] },
    { "chinese": "由某人管理", "english": "in the charge of sb.", "type": "短语", "keyWords": ["charge"] },
    { "chinese": "交给保姆照看的孩子", "english": "the child in the charge of the nurse", "type": "短语", "keyWords": ["charge"] },
    { "chinese": "n. 仁慈；慈善；慈善机构/组织；慈善团体；慈善业；施舍（物或行为）", "english": "charity", "type": "单词", "keyWords": [] },
    { "chinese": "贫民学校，慈善学校", "english": "a charity school", "type": "短语", "keyWords": ["charity"] },
    { "chinese": "义演", "english": "a charity performance", "type": "短语", "keyWords": ["charity"] },
    { "chinese": "她出于慈善帮助他。", "english": "She helped him out of charity.", "type": "句子", "keyWords": ["charity"] },
    { "chinese": "adj. 仁慈的，宽恕的，（为）慈善事业的", "english": "charitable", "type": "单词", "keyWords": [] },
    { "chinese": "n. 魅力；v. 迷住，使陶醉", "english": "charm", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 迷人的；可爱的", "english": "charming", "type": "单词", "keyWords": [] },
    { "chinese": "女性美", "english": "female charms", "type": "短语", "keyWords": ["charm"] },
    { "chinese": "可爱的笑容", "english": "charming smiles", "type": "短语", "keyWords": ["charming"] },
    { "chinese": "心醉于，给...迷住", "english": "be charmed with...", "type": "短语", "keyWords": ["charm"] },
    { "chinese": "n. 图表；航海图；v. 绘制..的海图/地图", "english": "chart", "type": "单词", "keyWords": [] },
    { "chinese": "工艺流程图", "english": "a flow chart", "type": "短语", "keyWords": ["chart"] },
    { "chinese": "vt./vi./n. 追逐；追击；驱逐", "english": "chase", "type": "单词", "keyWords": [] },
    { "chinese": "n. 猎人；驱逐舰", "english": "chaser", "type": "单词", "keyWords": [] },
    { "chinese": "vi./n. 闲聊；聊天", "english": "chat", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 饶舌的，爱讲闲话的", "english": "chatty", "type": "单词", "keyWords": [] },
    { "chinese": "和...闲谈", "english": "have a chat with sb. = chat with sb.", "type": "短语", "keyWords": ["chat"] },
    { "chinese": "vi. 喋喋不休地聊；n. 聊天，闲谈；唠叨", "english": "chatter", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 便宜的；廉价的", "english": "cheap", "type": "单词", "keyWords": [] },
    { "chinese": "买贱卖贵", "english": "buy cheap and sell dear", "type": "短语", "keyWords": ["cheap"] },
    { "chinese": "很便宜地买下一部新车", "english": "get/ buy the new car cheap", "type": "短语", "keyWords": ["cheap"] },
    { "chinese": "vt./vi. 欺骗，欺诈（辨析见deceive）；n. 骗子；欺诈行为", "english": "cheat", "type": "单词", "keyWords": [] },
    { "chinese": "玩纸牌时作弊", "english": "cheat at cards", "type": "短语", "keyWords": ["cheat"] },
    { "chinese": "骗某人100美元", "english": "cheat sb. (out) of $100", "type": "短语", "keyWords": ["cheat"] },
    { "chinese": "vi. 检查；核对；制止，（使）突然停止；（下棋用语）将；n. 检查；账单；（美）支票", "english": "check", "type": "单词", "keyWords": [] },
    { "chinese": "突然停止脚步", "english": "check one's steps", "type": "短语", "keyWords": ["check"] },
    { "chinese": "抑制怒火", "english": "check his anger", "type": "短语", "keyWords": ["check"] },
    { "chinese": "风向突然一转，森林大火就被遏制了。", "english": "A sudden change of wind checked the forest fire.", "type": "句子", "keyWords": ["check"] },
    { "chinese": "登记办理住宿手续；办理登记手续", "english": "check in", "type": "短语", "keyWords": ["check"] },
    { "chinese": "（向旅馆）结账后离开；检查，核对", "english": "check out", "type": "短语", "keyWords": ["check"] },
    { "chinese": "n. 登记处；报到处", "english": "check-in", "type": "单词", "keyWords": [] },
    { "chinese": "n. （超市等的）付款台；收银台；（从宾馆等）结账离开", "english": "check-out", "type": "单词", "keyWords": [] },
    { "chinese": "在付账柜台", "english": "at the check-out counter", "type": "短语", "keyWords": ["check-out"] },
    { "chinese": "n. 面颊", "english": "cheek", "type": "单词", "keyWords": [] },
    { "chinese": "n. （为..-）欢呼；（为..-）喝彩；（使）高兴，（使）振奋；adj. 愉快的；高兴的；adv. 愉快地", "english": "cheer", "type": "单词", "keyWords": [] },
    { "chinese": "啦啦队队长", "english": "cheer leader", "type": "短语", "keyWords": ["cheer"] },
    { "chinese": "向...欢呼致敬", "english": "cheer for...", "type": "短语", "keyWords": ["cheer"] },
    { "chinese": "（使）高兴起来；（使）振作起来（vt./vi.）", "english": "cheer(...) up", "type": "短语", "keyWords": ["cheer"] },
    { "chinese": "你的到来使难民们感到精神一振。", "english": "Your visit cheered up the refugees.", "type": "句子", "keyWords": ["cheer"] },
    { "chinese": "给赛跑运动员加油", "english": "cheer the runners on", "type": "短语", "keyWords": ["cheer"] },
    { "chinese": "n. 奶酪", "english": "cheese", "type": "单词", "keyWords": [] },
    { "chinese": "n. 化学药品/制品；adj. 化学的", "english": "chemical", "type": "单词", "keyWords": [] },
    { "chinese": "化学反应", "english": "chemical reaction", "type": "短语", "keyWords": ["chemical"] },
    { "chinese": "n. 化学家；药剂师；药商", "english": "chemist", "type": "单词", "keyWords": [] },
    { "chinese": "药店", "english": "(at) a chemist's shop", "type": "短语", "keyWords": ["chemist"] },
    { "chinese": "n. 化学", "english": "chemistry", "type": "单词", "keyWords": [] },
    { "chinese": "n. （英）支票（美check）", "english": "cheque", "type": "单词", "keyWords": [] },
    { "chinese": "用支票支付", "english": "pay for sth. by cheque", "type": "短语", "keyWords": ["cheque"] },
    { "chinese": "10万美元的支票", "english": "a cheque for $100,000", "type": "短语", "keyWords": ["cheque"] },
    { "chinese": "n. 国际象棋", "english": "chess", "type": "单词", "keyWords": [] },
    { "chinese": "和某人下一盘象棋", "english": "have/ play (a game of) chess with sb.", "type": "短语", "keyWords": ["chess"] },
    { "chinese": "n. 胸，胸部；大木箱；柜子，橱", "english": "chest", "type": "单词", "keyWords": [] },
    { "chinese": "v. 咀嚼", "english": "chew", "type": "单词", "keyWords": [] },
    { "chinese": "n. 口香糖", "english": "chewing gum", "type": "短语", "keyWords": ["chew"] },
    { "chinese": "n. 小鸡", "english": "chick", "type": "单词", "keyWords": [] },
    { "chinese": "n. 小鸡；鸡肉", "english": "chicken", "type": "单词", "keyWords": [] },
    { "chinese": "水痘", "english": "chicken pox", "type": "短语", "keyWords": ["chicken"] },
    { "chinese": "蛋未孵出先数鸡；过早乐观", "english": "count one's chickens before they are hatched", "type": "短语", "keyWords": ["chicken"] },
    { "chinese": "adj. 主要的（指处于较高地位）；n. 首领，领袖；上司，头头；首长，族长", "english": "chief", "type": "单词", "keyWords": [] },
    { "chinese": "总编辑", "english": "editor(s)-in-chief", "type": "短语", "keyWords": ["chief"] },
    { "chinese": "总司令", "english": "commander(s)-in-chief", "type": "短语", "keyWords": ["chief"] },
    { "chinese": "居领导地位", "english": "in chief", "type": "短语", "keyWords": ["chief"] },
    { "chinese": "总工程师", "english": "chief engineer", "type": "短语", "keyWords": ["chief"] },
    { "chinese": "首席执行官（略作CEO）", "english": "chief executive officer", "type": "短语", "keyWords": ["chief"] },
    { "chinese": "n. 孩子；子女", "english": "child", "type": "单词", "keyWords": [] },
    { "chinese": "在儿童节", "english": "on Children's Day", "type": "短语", "keyWords": ["child"] },
    { "chinese": "n. 分娩，生产", "english": "childbirth", "type": "单词", "keyWords": [] },
    { "chinese": "n. 童年，幼年", "english": "childhood", "type": "单词", "keyWords": [] },
    { "chinese": "在童年时", "english": "in one's childhood", "type": "短语", "keyWords": ["childhood"] },
    { "chinese": "adj. （成人）孩子似的，幼稚的（近childlike天真的；单纯的；孩子般的）", "english": "childish", "type": "单词", "keyWords": [] },
    { "chinese": "n. 寒冷；着凉，风寒；adj. 冷的；adj. 打寒战的；不友好的", "english": "chill", "type": "单词", "keyWords": [] },
    { "chinese": "打冷战", "english": "have a chill", "type": "短语", "keyWords": ["chill"] },
    { "chinese": "着凉", "english": "catch a chill", "type": "短语", "keyWords": ["chill"] },
    { "chinese": "受到冷漠的欢迎", "english": "be given a chilly welcome", "type": "短语", "keyWords": ["chilly"] },
    { "chinese": "n. 烟囱", "english": "chimney", "type": "单词", "keyWords": [] },
    { "chinese": "n. 下巴", "english": "chin", "type": "单词", "keyWords": [] },
    { "chinese": "n. 瓷器", "english": "china", "type": "单词", "keyWords": [] },
    { "chinese": "n. 中国人；汉语（普通话旧称Mandarin）；adj. 中国的；中国人的；中国话的", "english": "Chinese", "type": "单词", "keyWords": [] },
    { "chinese": "n. （食物等的）削片，薄片；（pl.）炸马铃薯片，油炸土豆条", "english": "chip", "type": "单词", "keyWords": [] },
    { "chinese": "n. 巧克力", "english": "chocolate", "type": "单词", "keyWords": [] },
    { "chinese": "n. 选择，挑选；供选择物；被选中的东西；adj. 精选的，上等的", "english": "choice", "type": "单词", "keyWords": [] },
    { "chinese": "编辑得在两首诗中选择一首。", "english": "The editor had to make a choice between the two poems.", "type": "句子", "keyWords": ["choice"] },
    { "chinese": "只能做某事", "english": "have no choice but to do sth. = can't choose/ help but do sth.", "type": "短语", "keyWords": ["choice"] },
    { "chinese": "予以选择机会", "english": "offer a choice", "type": "短语", "keyWords": ["choice"] },
    { "chinese": "精选货品", "english": "choice goods", "type": "短语", "keyWords": ["choice"] },
    { "chinese": "n. 唱诗班；合唱团", "english": "choir", "type": "单词", "keyWords": [] },
    { "chinese": "v. 选择；挑选；情愿", "english": "choose", "type": "单词", "keyWords": [] },
    { "chinese": "有很多可供选择", "english": "have many to choose from", "type": "短语", "keyWords": ["choose"] },
    { "chinese": "从...中选(...)", "english": "choose (...) from...", "type": "短语", "keyWords": ["choose"] },
    { "chinese": "选择沉默", "english": "choose to be silent", "type": "短语", "keyWords": ["choose"] },
    { "chinese": "不得不服从", "english": "cannot choose/ help but obey", "type": "短语", "keyWords": ["choose"] },
    { "chinese": "v. 砍，劈，斩；剁（肉）；n. 排骨肉；砍，劈，剁，切断", "english": "chop", "type": "单词", "keyWords": [] },
    { "chinese": "劈柴", "english": "chop wood", "type": "短语", "keyWords": ["chop"] },
    { "chinese": "斩掉，砍倒", "english": "chop...down", "type": "短语", "keyWords": ["chop"] },
    { "chinese": "切细", "english": "chop...up", "type": "短语", "keyWords": ["chop"] },
    { "chinese": "n. 筷子", "english": "chopstick(s)", "type": "单词", "keyWords": [] },
    { "chinese": "n. 基督教徒；adj. 基督教的", "english": "Christian", "type": "单词", "keyWords": [] },
    { "chinese": "n. 基督教；基督徒精神", "english": "Christianity", "type": "单词", "keyWords": [] },
    { "chinese": "n. 圣诞节（略写作Xmas）", "english": "Christmas", "type": "单词", "keyWords": [] },
    { "chinese": "在圣诞节", "english": "at Christmas", "type": "短语", "keyWords": ["Christmas"] },
    { "chinese": "恭贺圣诞！", "english": "A merry Christmas (to you)!", "type": "句子", "keyWords": ["Christmas"] },
    { "chinese": "在圣诞节前夕", "english": "on Christmas Eve", "type": "短语", "keyWords": ["Christmas"] },
    { "chinese": "在圣诞节", "english": "on Christmas Day", "type": "短语", "keyWords": ["Christmas"] },
    { "chinese": "n. 教堂，礼拜堂；礼拜；教会组织；教派", "english": "church", "type": "单词", "keyWords": [] },
    { "chinese": "去做礼拜", "english": "go to church", "type": "短语", "keyWords": ["church"] },
    { "chinese": "非常贫穷", "english": "as poor as a church mouse", "type": "短语", "keyWords": ["church"] },
    { "chinese": "去那个教堂", "english": "go to the church", "type": "短语", "keyWords": ["church"] },
    { "chinese": "n. 雪茄烟", "english": "cigar", "type": "单词", "keyWords": [] },
    { "chinese": "n. 香烟，卷烟，纸烟", "english": "cigarette", "type": "单词", "keyWords": [] },
    { "chinese": "烟蒂", "english": "cigarette end", "type": "短语", "keyWords": ["cigarette"] },
    { "chinese": "打火机", "english": "cigarette lighter", "type": "短语", "keyWords": ["cigarette"] },
    { "chinese": "n. 电影院；影业", "english": "cinema", "type": "单词", "keyWords": [] },
    { "chinese": "v. 环绕；圈出；vi. 盘旋；n. 圆；环状物", "english": "circle", "type": "单词", "keyWords": [] },
    { "chinese": "呈圆形，作环状", "english": "in a circle", "type": "短语", "keyWords": ["circle"] },
    { "chinese": "环绕太阳转", "english": "circle the sun (=go around the sun)", "type": "短语", "keyWords": ["circle"] },
    { "chinese": "围成圈（比较stand in line）", "english": "stand in a circle", "type": "短语", "keyWords": ["circle"] },
    { "chinese": "adj. 圆（形）的，环形的；环绕/行的；循环的", "english": "circular", "type": "单词", "keyWords": [] },
    { "chinese": "v. （使）循环；（使）流通，周转", "english": "circulate", "type": "单词", "keyWords": [] },
    { "chinese": "n. 电路；环形线，周线；环行；巡回", "english": "circuit", "type": "单词", "keyWords": [] },
    { "chinese": "集成电路", "english": "integrated circuit", "type": "短语", "keyWords": ["circuit"] },
    { "chinese": "电视线路", "english": "a television circuit", "type": "短语", "keyWords": ["circuit"] },
    { "chinese": "n. 情况，形势；（pl.）境况，境遇", "english": "circumstance", "type": "单词", "keyWords": [] },
    { "chinese": "决不，无论如何也不，在任何情况下决不", "english": "in no circumstances (=under no circumstances)", "type": "短语", "keyWords": ["circumstance"] },
    { "chinese": "n. 市民；公民", "english": "citizen", "type": "单词", "keyWords": [] },
    { "chinese": "n. 公民资格，公民身份", "english": "citizenship", "type": "单词", "keyWords": [] },
    { "chinese": "n. 城市", "english": "city", "type": "单词", "keyWords": [] },
    { "chinese": "卫星城", "english": "a satellite city", "type": "短语", "keyWords": ["city"] },
    { "chinese": "adj. 国内的；市民的，公民的；民用的；[法]民事的", "english": "civil", "type": "单词", "keyWords": [] },
    { "chinese": "内战", "english": "a civil war", "type": "短语", "keyWords": ["civil"] },
    { "chinese": "民法", "english": "civil law", "type": "短语", "keyWords": ["civil"] },
    { "chinese": "公民的权利", "english": "civil rights", "type": "短语", "keyWords": ["civil"] },
    { "chinese": "公民的义务", "english": "civil duties", "type": "短语", "keyWords": ["civil"] },
    { "chinese": "n. 平民；adj. 平民的", "english": "civilian", "type": "单词", "keyWords": [] },
    { "chinese": "便装", "english": "civilian clothes", "type": "短语", "keyWords": ["civilian"] },
    { "chinese": "n. 文化，文明（阶段、世界等）；生活方式；开化，教养", "english": "civilization", "type": "单词", "keyWords": [] },
    { "chinese": "人类文明", "english": "the civilization of mankind", "type": "短语", "keyWords": ["civilization"] },
    { "chinese": "近代世界的文明", "english": "the civilization of the modern world", "type": "短语", "keyWords": ["civilization"] },
    { "chinese": "vt. 使文明；使开化", "english": "civilize", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 文明的；有教养的；已变成文明（社会）的", "english": "civilized", "type": "单词", "keyWords": [] },
    { "chinese": "vt./vi./n. 根据权利而提出的（财产、名声等）要求；认领，索取；宣称，声称", "english": "claim", "type": "单词", "keyWords": [] },
    { "chinese": "认领这钱包", "english": "claim this purse", "type": "短语", "keyWords": ["claim"] },
    { "chinese": "自称是，声称是", "english": "claim to be sth.", "type": "短语", "keyWords": ["claim"] },
    { "chinese": "向他索要100美元作为伤害赔偿", "english": "claim 100 dollars from him for injuries suffered", "type": "短语", "keyWords": ["claim"] },
    { "chinese": "v./vi. 拍（手），鼓（掌）；n. （只用单数）拍手（声）", "english": "clap", "type": "单词", "keyWords": [] },
    { "chinese": "拍手，鼓掌", "english": "clap one's hands", "type": "短语", "keyWords": ["clap"] },
    { "chinese": "给他鼓掌", "english": "give him a clap", "type": "短语", "keyWords": ["clap"] },
    { "chinese": "n. 班级，课，等级；门类；阶级；社会等级；v. 把..归类/分等级", "english": "class", "type": "单词", "keyWords": [] },
    { "chinese": "头等，第一流", "english": "the first class", "type": "短语", "keyWords": ["class"] },
    { "chinese": "工人阶级", "english": "the working class", "type": "短语", "keyWords": ["class"] },
    { "chinese": "n. 经典作品；经典作家；adj. （文学艺术）第一流的，优秀的；典型的", "english": "classic", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 古典的；经典的，传统的，权威的；古典文学的", "english": "classical", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 把...归类；分类；分级", "english": "classify", "type": "单词", "keyWords": [] },
    { "chinese": "n. 分类，等级，门类", "english": "classification", "type": "单词", "keyWords": [] },
    { "chinese": "n. 同班同学", "english": "classmate", "type": "单词", "keyWords": [] },
    { "chinese": "n. 教室；课堂", "english": "classroom", "type": "单词", "keyWords": [] },
    { "chinese": "n. 黏土", "english": "clay", "type": "单词", "keyWords": [] },
    { "chinese": "v. 打扫；把..收拾干净；adj. 清洁的；（精神、品质等）纯洁的；（历史等）清白的", "english": "clean", "type": "单词", "keyWords": [] },
    { "chinese": "保持...清洁", "english": "keep...clean", "type": "短语", "keyWords": ["clean"] },
    { "chinese": "清白，无罪", "english": "have clean hands", "type": "短语", "keyWords": ["clean"] },
    { "chinese": "n. 吸尘器，清洁器；清洁工", "english": "cleaner", "type": "单词", "keyWords": [] },
    { "chinese": "v. 清扫；清除；（天气）放晴；adj. 清澈的，透明的；清楚的，明白的；清白的；（天气）晴朗的；adv. 清晰地；完全地", "english": "clear", "type": "单词", "keyWords": [] },
    { "chinese": "把街上的人和杂物弄走", "english": "clear the street", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "收拾桌子", "english": "clear the table", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "收拾碗筷", "english": "clear away the dinner", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "清嗓子", "english": "clear one's throat", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "纯利", "english": "a clear profit", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "空地", "english": "a clear space", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "说话响亮清楚", "english": "speak loud and clear", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "清除了的，没有的，摆脱了", "english": "be clear/free of...", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "河水里没有水草。", "english": "The river is clear of weeds.", "type": "句子", "keyWords": ["clear"] },
    { "chinese": "没有人来往的路", "english": "roads clear of traffic", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "把...解释清楚", "english": "make sth. clear", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "我必须表明清楚我不会辞职。", "english": "I must make it clear that I won't resign.", "type": "句子", "keyWords": ["clear"] },
    { "chinese": "解答；放晴；整理", "english": "clear up", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "收拾房间", "english": "clear up a room", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "解开谜团", "english": "clear up a mystery", "type": "短语", "keyWords": ["clear"] },
    { "chinese": "我肯定天气很快会转晴。", "english": "I bet the weather will clear up soon.", "type": "句子", "keyWords": ["clear"] },
    { "chinese": "n. 职员，办事员", "english": "clerk", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 聪明的；灵巧的；n. 聪明；伶俐", "english": "clever", "type": "单词", "keyWords": [] },
    { "chinese": "擅长绘画", "english": "be clever/ good at painting", "type": "短语", "keyWords": ["clever"] },
    { "chinese": "v. 发出咔嗒一声响；按击（鼠标）；n. 咔嗒声，嘀嗒声", "english": "click", "type": "单词", "keyWords": [] },
    { "chinese": "n. 客户，顾客（近customer）", "english": "client", "type": "单词", "keyWords": [] },
    { "chinese": "n. 悬崖，绝壁", "english": "cliff", "type": "单词", "keyWords": [] },
    { "chinese": "n. 气候；（某一社会、时期等的）风气；环境气氛", "english": "climate", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. 爬，攀登", "english": "climb", "type": "单词", "keyWords": [] },
    { "chinese": "n. 爬山者，攀登者", "english": "climber", "type": "单词", "keyWords": [] },
    { "chinese": "n. 诊所；门诊部；私人诊所；adj. 临床的；诊所的；病房（用）的", "english": "clinic", "type": "单词", "keyWords": [] },
    { "chinese": "n. （时）钟", "english": "clock", "type": "单词", "keyWords": [] },
    { "chinese": "钟楼", "english": "clock tower", "type": "短语", "keyWords": ["clock"] },
    { "chinese": "昼夜不停，连续一整天工作", "english": "work round the clock", "type": "短语", "keyWords": ["clock"] },
    { "chinese": "对钟", "english": "set a clock", "type": "短语", "keyWords": ["clock"] },
    { "chinese": "给钟上发条", "english": "wind up a clock", "type": "短语", "keyWords": ["clock"] },
    { "chinese": "把钟拨快/慢一个小时", "english": "advance/ set back the clock one hour", "type": "短语", "keyWords": ["clock"] },
    { "chinese": "adj./ad. 顺时针方向", "english": "clockwise", "type": "单词", "keyWords": [] },
    { "chinese": "逆时针方向", "english": "counterclockwise = anticlockwise", "type": "短语", "keyWords": [] },
    { "chinese": "n. 无性繁殖的动植物，克隆的动植物；v. 无性繁殖，复制，克隆", "english": "clone", "type": "单词", "keyWords": [] },
    { "chinese": "v. 关闭；adj. 接近的；亲密的；严密的；紧密的；adv. 接近；adj. 关闭着的", "english": "close", "type": "单词", "keyWords": [] },
    { "chinese": "这门关不上。", "english": "The door won't close.", "type": "句子", "keyWords": ["close"] },
    { "chinese": "（使）关闭掉；（使）停业；（使）停止", "english": "close down", "type": "短语", "keyWords": ["close"] },
    { "chinese": "势均力敌的比赛", "english": "a close game", "type": "短语", "keyWords": ["close"] },
    { "chinese": "临近的；在….近旁的；接近于", "english": "be close to", "type": "短语", "keyWords": ["close"] },
    { "chinese": "同…有密切关系", "english": "have a close relationship with", "type": "短语", "keyWords": ["close"] },
    { "chinese": "幸运的脱险", "english": "a close call", "type": "短语", "keyWords": ["close"] },
    { "chinese": "严密的盖子", "english": "a close lid", "type": "短语", "keyWords": ["close"] },
    { "chinese": "在近旁", "english": "be close at hand", "type": "短语", "keyWords": ["close"] },
    { "chinese": "离得不远", "english": "close by", "type": "短语", "keyWords": ["close"] },
    { "chinese": "adv. 精密地；严密地；细心地", "english": "closely", "type": "单词", "keyWords": [] },
    { "chinese": "n. 布；织物；（pl. cloths）某种特殊用途的布", "english": "cloth", "type": "单词", "keyWords": [] },
    { "chinese": "一块洗碗布/桌布", "english": "a dish/table cloth", "type": "短语", "keyWords": ["cloth"] },
    { "chinese": "n. 衣服（无单数；不与具体数字连用）", "english": "clothes", "type": "单词", "keyWords": [] },
    { "chinese": "n. （总称）衣服", "english": "clothing", "type": "单词", "keyWords": [] },
    { "chinese": "衣食住", "english": "food, clothing and shelter", "type": "短语", "keyWords": ["clothing"] },
    { "chinese": "一套衣服", "english": "a suit of clothing", "type": "短语", "keyWords": ["clothing"] },
    { "chinese": "一件衣服", "english": "an article/a piece of clothing", "type": "短语", "keyWords": ["clothing"] },
    { "chinese": "n. 云；烟尘；v. （云、烟等）覆盖，遮蔽；使阴暗；使模糊；vi. 云层密布（over/up）；变暗；变模糊；adj. 多云的", "english": "cloud", "type": "单词", "keyWords": [] },
    { "chinese": "n. （马戏）小丑", "english": "clown", "type": "单词", "keyWords": [] },
    { "chinese": "n. 俱乐部；夜总会；棍棒；（马球等的）球棒；（纸牌的）梅花", "english": "club", "type": "单词", "keyWords": [] },
    { "chinese": "n. 线索，提示（后接to）", "english": "clue", "type": "单词", "keyWords": [] },
    { "chinese": "adj. （手脚）笨拙的；愚笨的，不圆滑的", "english": "clumsy", "type": "单词", "keyWords": [] },
    { "chinese": "美国有线新闻网（Cable News Network）", "english": "CNN", "type": "单词", "keyWords": [] },
    { "chinese": "n. 长途汽车；（铁路）车厢；（体育等）教练；v. 训练，指导（应考生、运动员等）", "english": "coach", "type": "单词", "keyWords": [] },
    { "chinese": "n. 煤", "english": "coal", "type": "单词", "keyWords": [] },
    { "chinese": "n. 煤田", "english": "coalfield", "type": "单词", "keyWords": [] },
    { "chinese": "n. 煤矿", "english": "coal mine", "type": "短语", "keyWords": ["coal"] },
    { "chinese": "煤矿工人", "english": "coal miner", "type": "短语", "keyWords": ["coal"] },
    { "chinese": "n. 海岸；海滨；沿海地区；adj. 沿海的；沿岸的；n. 海岸线", "english": "coast", "type": "单词", "keyWords": [] },
    { "chinese": "远离海岸的岛屿", "english": "the islands off the coast", "type": "短语", "keyWords": ["coast"] },
    { "chinese": "n. 海岸警卫队", "english": "the coastguard", "type": "短语", "keyWords": ["coast"] },
    { "chinese": "n. 上衣；外套；（动物的）皮毛；层；v. 在…上涂一层；（用）覆盖", "english": "coat", "type": "单词", "keyWords": [] },
    { "chinese": "给门漆上一层漆", "english": "put a coat of paint on the door", "type": "短语", "keyWords": ["coat"] }
];
