const qgl57_64 = [
    { "chinese": "这些药丸外面有一层糖衣。", "english": "The pills were coated with sugar.", "type": "句子", "keyWords": [] },
    { "chinese": "n.(U)可卡因", "english": "cocaine /kəʊ'keɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)公鸡", "english": "cock /kɒk/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)鸡尾酒", "english": "cocktail", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)茧；状物", "english": "cocoon /kə'ku:n/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)椰子", "english": "coconut /'kəʊkənʌt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)密码；代码；代号；准则，规范；法典 v.给...编码", "english": "code /kəʊd/", "type": "单词", "keyWords": [] },
    { "chinese": "行为准则", "english": "a code of behaviour", "type": "短语", "keyWords": ["code"] },
    { "chinese": "n.(U)咖啡（粉）；(C)一杯咖啡", "english": "coffee /'kɒfi/", "type": "单词", "keyWords": [] },
    { "chinese": "纯咖啡", "english": "black coffee", "type": "短语", "keyWords": ["coffee"] },
    { "chinese": "牛奶咖啡", "english": "white coffee", "type": "短语", "keyWords": ["coffee"] },
    { "chinese": "请给我来两杯咖啡。", "english": "Please bring me two coffees.", "type": "句子", "keyWords": ["coffee"] },
    { "chinese": "n.(C)硬币；钱币 v.铸（币）；创造，杜撰（新字等）", "english": "coin /kɔɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)巧合", "english": "coincidence /kəʊ'ɪnsɪdəns/", "type": "单词", "keyWords": [] },
    { "chinese": "只是巧合", "english": "a mere coincidence", "type": "短语", "keyWords": ["coincidence"] },
    { "chinese": "n.(C)(U)（一杯或一瓶）可乐", "english": "Coke /kəʊk (= Coca-Cola)", "type": "单词", "keyWords": [] },
    { "chinese": "a.冷的；寒冷的；冷淡的，无情的 n.(U)寒冷；(C)伤风；感冒", "english": "cold /kəʊld/", "type": "单词", "keyWords": [] },
    { "chinese": "对...泼冷水", "english": "throw cold water on", "type": "短语", "keyWords": ["cold"] },
    { "chinese": "冷战", "english": "a cold war", "type": "短语", "keyWords": ["cold"] },
    { "chinese": "冷冰冰的欢迎", "english": "a cold welcome", "type": "短语", "keyWords": ["cold"] },
    { "chinese": "冷得发抖", "english": "shiver with cold", "type": "短语", "keyWords": ["cold"] },
    { "chinese": "着凉；感冒", "english": "catch/ take/ have a bad cold", "type": "短语", "keyWords": ["cold"] },
    { "chinese": "a.残酷的；冷血的（与'温血'相对）", "english": "cold-blooded", "type": "单词", "keyWords": ["cold"] },
    { "chinese": "vi.塌下；崩溃 n.(C)（可和a连用）倒塌，崩溃，衰弱", "english": "collapse /kə'læps/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)衣领；（动物）颈圈", "english": "collar /'kɒlə/", "type": "单词", "keyWords": [] },
    { "chinese": "蓝领的", "english": "blue-collar", "type": "短语", "keyWords": ["collar"] },
    { "chinese": "白领的", "english": "white-collar", "type": "短语", "keyWords": ["collar"] },
    { "chinese": "n.(C)同事", "english": "colleague /'kɒli:g/", "type": "单词", "keyWords": [] },
    { "chinese": "v.收集；采集；收取；集中；取（东西）或接（人）", "english": "collect /kə'lekt/", "type": "单词", "keyWords": [] },
    { "chinese": "a.集体的", "english": "collective", "type": "单词", "keyWords": ["collect"] },
    { "chinese": "募集（捐款）；征收", "english": "collect money", "type": "短语", "keyWords": ["collect"] },
    { "chinese": "集邮", "english": "collect stamps", "type": "短语", "keyWords": ["collect"] },
    { "chinese": "收拾走财物/接走宠物", "english": "collect one's belongings/pet", "type": "短语", "keyWords": ["collect"] },
    { "chinese": "他理了下思路。", "english": "He collected his thoughts.", "type": "句子", "keyWords": ["collect"] },
    { "chinese": "共同努力", "english": "collective efforts", "type": "短语", "keyWords": ["collective"] },
    { "chinese": "集体领导", "english": "collective leadership", "type": "短语", "keyWords": ["collective"] },
    { "chinese": "一大批", "english": "a large collection of", "type": "短语", "keyWords": ["collect"] },
    { "chinese": "收票员", "english": "a ticket collector", "type": "短语", "keyWords": ["collect"] },
    { "chinese": "n.(C)（综合大学中的）学院；（独立的）学院", "english": "college /'kɒlɪdʒ/", "type": "单词", "keyWords": [] },
    { "chinese": "在上大学时", "english": "at/ in college", "type": "短语", "keyWords": ["college"] },
    { "chinese": "上大学", "english": "go to college", "type": "短语", "keyWords": ["college"] },
    { "chinese": "n.(C)殖民地", "english": "colony /'kɒləni/", "type": "单词", "keyWords": [] },
    { "chinese": "vt.拓殖，殖民", "english": "colonize /'kɒlənaɪz/", "type": "单词", "keyWords": ["colony"] },
    { "chinese": "a.殖民的，殖民地的", "english": "colonial /kə'ləʊniəl/", "type": "单词", "keyWords": ["colony"] },
    { "chinese": "n.殖民者", "english": "colonist /'kɒlənɪst/", "type": "单词", "keyWords": ["colony"] },
    { "chinese": "n.(C)(U)颜色 vt.给...着/上色；改变...的颜色", "english": "colour /'kʌlə/", "type": "单词", "keyWords": [] },
    { "chinese": "a.彩色的；着色的；有色人种的", "english": "coloured", "type": "单词", "keyWords": ["colour"] },
    { "chinese": "n.(U)着色", "english": "colouring", "type": "单词", "keyWords": ["colour"] },
    { "chinese": "在颜色方面", "english": "in color", "type": "短语", "keyWords": ["colour"] },
    { "chinese": "a.色盲的", "english": "colour-blind", "type": "单词", "keyWords": ["colour"] },
    { "chinese": "n.(C)柱子，柱状物；印刷的纵列；专栏", "english": "column /'kɒləm/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)专栏作家", "english": "columnist /'kɒləmnɪst/", "type": "单词", "keyWords": ["column"] },
    { "chinese": "n.(C)梳子 v.梳（发）；（到处）搜寻，搜遍", "english": "comb /kəʊm/", "type": "单词", "keyWords": [] },
    { "chinese": "全城搜捕叛军", "english": "comb the city for rebels", "type": "短语", "keyWords": ["comb"] },
    { "chinese": "v./n.(C)(U)斗争；战斗（with/ against）", "english": "combat /'kɒmbæt/", "type": "单词", "keyWords": [] },
    { "chinese": "v.（使）结合；组合；联合", "english": "combine /kəm'baɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)结合；联合；混合（体）", "english": "combination", "type": "单词", "keyWords": ["combine"] },
    { "chinese": "a.结合的", "english": "combined", "type": "单词", "keyWords": ["combine"] },
    { "chinese": "理论联系实际", "english": "combine theory with practice", "type": "短语", "keyWords": ["combine"] },
    { "chinese": "同...相结合", "english": "be combined with...", "type": "短语", "keyWords": ["combine"] },
    { "chinese": "v.来；变成；开始，...起来（后接不定式）", "english": "come /kʌm/", "type": "单词", "keyWords": [] },
    { "chinese": "a.即将来临的", "english": "coming", "type": "单词", "keyWords": ["come"] },
    { "chinese": "跑着进来", "english": "come running in", "type": "短语", "keyWords": ["come"] },
    { "chinese": "成真", "english": "come true", "type": "短语", "keyWords": ["come"] },
    { "chinese": "提出（正确的答案）", "english": "come up with (a proper answer)", "type": "短语", "keyWords": ["come"] },
    { "chinese": "裂开；破裂；垮下来，崩溃", "english": "come apart", "type": "短语", "keyWords": ["come"] },
    { "chinese": "快；走吧；进行，进展；降临", "english": "come on", "type": "短语", "keyWords": ["come"] },
    { "chinese": "碰见；被理解", "english": "come across", "type": "短语", "keyWords": ["come"] },
    { "chinese": "发生", "english": "come about", "type": "短语", "keyWords": ["come"] },
    { "chinese": "一起去；赶快", "english": "come along", "type": "短语", "keyWords": ["come"] },
    { "chinese": "结束，终止", "english": "come to an end", "type": "短语", "keyWords": ["come"] },
    { "chinese": "碰见；突袭", "english": "come upon", "type": "短语", "keyWords": ["come"] },
    { "chinese": "共计；恢复知觉，苏醒，清醒；谈及，涉及；实际是指", "english": "come to", "type": "短语", "keyWords": ["come"] },
    { "chinese": "绕道；来访", "english": "come (a) round (to)", "type": "短语", "keyWords": ["come"] },
    { "chinese": "谈正题", "english": "come to the point", "type": "短语", "keyWords": ["come"] },
    { "chinese": "差一点就（...）", "english": "come close to (killing himself)", "type": "短语", "keyWords": ["come"] },
    { "chinese": "发行；发表；（应试）结果", "english": "come out", "type": "短语", "keyWords": ["come"] },
    { "chinese": "比赛结果为（第一）", "english": "come in (first)", "type": "短语", "keyWords": ["come"] },
    { "chinese": "在未来的岁月里", "english": "in the years to come", "type": "短语", "keyWords": ["come"] },
    { "chinese": "不论发生什么事情", "english": "come what may", "type": "短语", "keyWords": ["come"] },
    { "chinese": "怎么会...？", "english": "How come...?", "type": "短语", "keyWords": ["come"] },
    { "chinese": "落；（物价）下跌；（树）被砍倒", "english": "come down", "type": "短语", "keyWords": ["come"] },
    { "chinese": "说起；谈到", "english": "When it comes to...", "type": "短语", "keyWords": ["come"] },
    { "chinese": "（使）形成，产生", "english": "come (bring ...) into being", "type": "短语", "keyWords": ["come"] },
    { "chinese": "暴露出来，成为人所共知", "english": "come to light", "type": "短语", "keyWords": ["come"] },
    { "chinese": "他怎么会迟到？", "english": "How come he is late?", "type": "句子", "keyWords": ["come"] },
    { "chinese": "长出地面；（为了攀谈）走近；（问题等）被提出；出现，发生", "english": "come up", "type": "短语", "keyWords": ["come"] },
    { "chinese": "逐渐意识到", "english": "come to know/ understand/ realize", "type": "短语", "keyWords": ["come"] },
    { "chinese": "n.(C)喜剧演员", "english": "comedian /kə'mi:diən/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)喜剧", "english": "comedy /'kɒmədi/", "type": "单词", "keyWords": [] },
    { "chinese": "a.滑稽的，喜剧的；连环画的，漫画的 n.(C)喜剧演员；连环画，漫画书", "english": "comic /'kɒmɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "vt.使舒适；安慰 n.(U)舒适；安慰 (C)舒适的事物", "english": "comfort /'kʌmfət/", "type": "单词", "keyWords": [] },
    { "chinese": "和你待在一起是个安慰。", "english": "It's a comfort to be with you.", "type": "句子", "keyWords": ["comfort"] },
    { "chinese": "生活舒适", "english": "live in comfort", "type": "短语", "keyWords": ["comfort"] },
    { "chinese": "a.舒畅的；舒适的", "english": "comfortable /'kʌmfətəbl/", "type": "单词", "keyWords": ["comfort"] },
    { "chinese": "n.(U)指挥；命令；掌握（可加a） v.指挥；命令；掌握；博得", "english": "command /kə'mɑ:nd/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)司令员，指挥官", "english": "commander", "type": "单词", "keyWords": ["command"] },
    { "chinese": "n.(C)总司令", "english": "commander(s)-in-chief", "type": "单词", "keyWords": ["command"] },
    { "chinese": "英语很好", "english": "have a good command of English", "type": "短语", "keyWords": ["command"] },
    { "chinese": "由...指挥", "english": "be under command of...", "type": "短语", "keyWords": ["command"] },
    { "chinese": "军队由国王直接统率。", "english": "The army is under the king's command.", "type": "句子", "keyWords": ["command"] },
    { "chinese": "命令某人去做某事", "english": "command sb. to do sth.", "type": "短语", "keyWords": ["command"] },
    { "chinese": "命令某人去做某事（虚拟语气）", "english": "command that sb. (should) do sth.", "type": "短语", "keyWords": ["command"] },
    { "chinese": "vi./n.(C)评论", "english": "comment /'kɒment/", "type": "单词", "keyWords": [] },
    { "chinese": "评论...", "english": "make comments on sth. = comment on sth.", "type": "短语", "keyWords": ["comment"] },
    { "chinese": "n.(U)商业，贸易", "english": "commerce /'kɒmɜ:s/", "type": "单词", "keyWords": [] },
    { "chinese": "a.与商业有关的；商务的；营利性的 n.(C)商业广告", "english": "commercial /kə'mɜ:ʃəl/", "type": "单词", "keyWords": [] },
    { "chinese": "v.使商业化/商品化", "english": "commercialize /kə'mɜ:ʃəlaɪz/", "type": "单词", "keyWords": ["commercial"] },
    { "chinese": "v.犯（错误、罪行），干（坏事）；委托；提交；使承担义务", "english": "commit /kə'mɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "自杀/行贿", "english": "commit suicide/ bribery", "type": "短语", "keyWords": ["commit"] },
    { "chinese": "使某人承诺做某事", "english": "commit sb. to (doing) sth.", "type": "短语", "keyWords": ["commit"] },
    { "chinese": "他不愿做任何承诺。", "english": "He would not commit himself in any way.", "type": "句子", "keyWords": ["commit"] },
    { "chinese": "犯罪", "english": "commit a crime", "type": "短语", "keyWords": ["commit"] },
    { "chinese": "记住...", "english": "commit... to memory", "type": "短语", "keyWords": ["commit"] },
    { "chinese": "n.(C)委员会（集合名词）", "english": "committee /kə'mɪti/", "type": "单词", "keyWords": [] },
    { "chinese": "是委员会成员", "english": "be on the committee", "type": "短语", "keyWords": ["committee"] },
    { "chinese": "n.(C)商品", "english": "commodity /kə'mɒdəti/", "type": "单词", "keyWords": [] },
    { "chinese": "a.寻/平常的；一般的，通常的；普通的；共同的", "english": "common /'kɒmən/", "type": "单词", "keyWords": [] },
    { "chinese": "ad.通常地，一般地", "english": "commonly", "type": "单词", "keyWords": ["common"] },
    { "chinese": "常识", "english": "common knowledge", "type": "短语", "keyWords": ["common"] },
    { "chinese": "常识；理智", "english": "common sense", "type": "短语", "keyWords": ["common"] },
    { "chinese": "平民", "english": "the common people", "type": "短语", "keyWords": ["common"] },
    { "chinese": "常见错误", "english": "common mistakes", "type": "短语", "keyWords": ["common"] },
    { "chinese": "与某人在某方面有共同之处", "english": "have sth. in common with sb.", "type": "短语", "keyWords": ["common"] },
    { "chinese": "约翰与我毫无共同之处。", "english": "John and I have nothing in common.", "type": "句子", "keyWords": ["common"] },
    { "chinese": "vi.通信；交流思想；交际；交往 v.传达；传送；传播", "english": "communicate /kə'mju:nɪkeɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "向...传达...", "english": "communicate sth. to sb.", "type": "短语", "keyWords": ["communicate"] },
    { "chinese": "n.(U)传播；信息；交通；通信；交流 n.(pl)交通/通信手段", "english": "communication /kə,mju:nɪ'keɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "交流手段", "english": "means of communication", "type": "短语", "keyWords": ["communication"] },
    { "chinese": "通信卫星", "english": "communications satellite", "type": "短语", "keyWords": ["communication"] },
    { "chinese": "a.共产主义的 n.(C)共产主义者", "english": "communist /'kɒmjunɪst/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)共产主义", "english": "communism /'kɒmjunɪzəm/", "type": "单词", "keyWords": ["communist"] },
    { "chinese": "共产主义事业", "english": "the communist cause", "type": "短语", "keyWords": ["communist"] },
    { "chinese": "中国共产党", "english": "the Communist Party of China", "type": "短语", "keyWords": ["communist"] },
    { "chinese": "n.(C)社会；群落；社区；共同体，共同组织；团体", "english": "community /kə'mju:nəti/", "type": "单词", "keyWords": [] },
    { "chinese": "激光唱片；光盘（缩写CD）", "english": "compact disk /'kɒmpækt dɪsk/", "type": "短语", "keyWords": [] },
    { "chinese": "n.(C)伴侣；同伴", "english": "companion /kəm'pæniən/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)作伴，结伴，陪同；伴侣，同伴 (C)公司；商号；一伙", "english": "company /'kʌmpəni/", "type": "单词", "keyWords": [] },
    { "chinese": "和....一道", "english": "in company with sb.", "type": "短语", "keyWords": ["company"] },
    { "chinese": "结交好（坏）朋友", "english": "keep good/ bad company", "type": "短语", "keyWords": ["company"] },
    { "chinese": "与……亲密交往；与……形影不离", "english": "keep company with sb.", "type": "短语", "keyWords": ["company"] },
    { "chinese": "陪伴某人", "english": "keep sb. company", "type": "短语", "keyWords": ["company"] },
    { "chinese": "从其交友知其为人。", "english": "A man is known by the company he keeps.", "type": "句子", "keyWords": ["company"] },
    { "chinese": "a.相比较而言的；相对的", "english": "comparative /kəm'pærətɪv/", "type": "单词", "keyWords": [] },
    { "chinese": "ad.比较上；相对地", "english": "comparatively", "type": "单词", "keyWords": ["comparative"] },
    { "chinese": "vt.比较，对照（with）；把...比作（to）", "english": "compare /kəm'peə/", "type": "单词", "keyWords": [] },
    { "chinese": "与...相比", "english": "be compared with", "type": "短语", "keyWords": ["compare"] },
    { "chinese": "把...比作", "english": "be compared to", "type": "短语", "keyWords": ["compare"] },
    { "chinese": "在诗中诗人把他的情人比作玫瑰。", "english": "The poet compares his lover to a rose in his poems.", "type": "句子", "keyWords": ["compare"] },
    { "chinese": "人生常被喻为蜡烛。", "english": "Man's life is often compared to a candle.", "type": "句子", "keyWords": ["compare"] },
    { "chinese": "与...相比（常位于句首）", "english": "Compared with/ to sth./ sb.,...", "type": "短语", "keyWords": ["compare"] },
    { "chinese": "n.(C)(U)比较", "english": "comparison /kəm'pærɪsn/", "type": "单词", "keyWords": [] },
    { "chinese": "在...和...间作比较", "english": "make a comparison between ... and...", "type": "短语", "keyWords": ["comparison"] },
    { "chinese": "比较起来", "english": "by comparison", "type": "短语", "keyWords": ["comparison"] },
    { "chinese": "比较起来这个比较便宜。", "english": "This one is cheaper by comparison.", "type": "句子", "keyWords": ["comparison"] },
    { "chinese": "同...比起来", "english": "in comparison with", "type": "短语", "keyWords": ["comparison"] },
    { "chinese": "我的鞋子比我妹妹的要小。", "english": "My shoes are smaller in comparison with my sister's.", "type": "句子", "keyWords": ["comparison"] },
    { "chinese": "n.(C)罗盘；(pl)圆规", "english": "compass /'kʌmpəs/", "type": "单词", "keyWords": [] },
    { "chinese": "一副圆规", "english": "a pair of compasses", "type": "短语", "keyWords": ["compass"] },
    { "chinese": "vi.比赛；竞争", "english": "compete /kəm'pi:t/", "type": "单词", "keyWords": [] },
    { "chinese": "为·..与某人竞争", "english": "compete for sth. with/against sb.", "type": "短语", "keyWords": ["compete"] },
    { "chinese": "n.(C)竞争者；对手；参赛者", "english": "competitor /kəm'petɪtə/", "type": "单词", "keyWords": ["compete"] },
    { "chinese": "n.(C)(U)比赛；竞争；竞赛", "english": "competition /,kɒmpə'tɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "在与...的竞争中", "english": "in competition with...", "type": "短语", "keyWords": ["competition"] },
    { "chinese": "a.竞争（或比赛）性的；（商品等）有竞争力的", "english": "competitive /kəm'petətɪv/", "type": "单词", "keyWords": ["compete"] },
    { "chinese": "vi.抱怨；发牢骚 v.抱怨；诉说（that...）", "english": "complain /kəm'pleɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "抱怨", "english": "complain about", "type": "短语", "keyWords": ["complain"] },
    { "chinese": "诉说（病痛）", "english": "complain of", "type": "短语", "keyWords": ["complain"] },
    { "chinese": "n.(C)(U)抱怨", "english": "complaint /kəm'pleɪnt/", "type": "单词", "keyWords": [] },
    { "chinese": "毫无怨言", "english": "without complaint", "type": "短语", "keyWords": ["complaint"] },
    { "chinese": "向某人抱怨某事", "english": "make a complaint to sb. about sth.", "type": "短语", "keyWords": ["complaint"] },
    { "chinese": "vt.完成；结束；使完全/完美 a.完全的；十足的；完整的；完成的；结束的", "english": "complete /kəm'pli:t/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)完成；结束", "english": "completion /kəm'pli:ʃn/", "type": "单词", "keyWords": ["complete"] },
    { "chinese": "全集", "english": "complete works", "type": "短语", "keyWords": ["complete"] },
    { "chinese": "结业", "english": "complete a course", "type": "短语", "keyWords": ["complete"] },
    { "chinese": "a.复杂的；合成的，组合的（强调错综复杂的成分或关系）n.(C)复合体，集合体，复合体", "english": "complex /'kɒmpleks/", "type": "单词", "keyWords": [] },
    { "chinese": "复合句", "english": "a complex sentence", "type": "短语", "keyWords": ["complex"] },
    { "chinese": "大工业中心", "english": "an industrial complex", "type": "短语", "keyWords": ["complex"] },
    { "chinese": "a.复杂的；难解的（强调难于理解或分析，通常不用于具体物体）", "english": "complicated /'kɒmplɪkeɪtɪd/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)赞美（话）；恭维（话）；敬意 (pl)问候 vt.恭维", "english": "compliment /'kɒmplɪmənt/", "type": "单词", "keyWords": [] },
    { "chinese": "恭维，夸奖某人", "english": "pay sb. a compliment (on sth.) = compliment sb. on...", "type": "短语", "keyWords": ["compliment"] },
    { "chinese": "请代为问候您的家人！", "english": "My compliments to your family!", "type": "句子", "keyWords": ["compliment"] },
    { "chinese": "n.(C)组成部分；部件", "english": "component /kəm'pəʊnənt/", "type": "单词", "keyWords": [] },
    { "chinese": "v.写作，创作（音乐、文学作品）；组成，构成 vi.创作，作曲", "english": "compose /kəm'pəʊz/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)作曲家", "english": "composer /kəm'pəʊzə/", "type": "单词", "keyWords": ["compose"] },
    { "chinese": "作曲", "english": "compose music", "type": "短语", "keyWords": ["compose"] },
    { "chinese": "作诗", "english": "compose a poem", "type": "短语", "keyWords": ["compose"] },
    { "chinese": "由...组成（近be made up of, consist of）", "english": "be composed of", "type": "短语", "keyWords": ["compose"] },
    { "chinese": "水是由氢和氧组成的。", "english": "Water is composed of hydrogen and oxygen.", "type": "句子", "keyWords": ["compose"] },
    { "chinese": "n.(C)乐曲；（音乐、文学或美术）作品；作文 (U)创作；组成；成分", "english": "composition /,kɒmpə'zɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)复合物，复合词 a.复合的；化合的", "english": "compound /'kɒmpaʊnd/", "type": "单词", "keyWords": [] },
    { "chinese": "v.理解；领悟；懂", "english": "comprehend /,kɒmprɪ'hend/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)理解（力）；包含，包括；广泛性", "english": "comprehension", "type": "单词", "keyWords": ["comprehend"] },
    { "chinese": "a.全面的，广泛的；综合的；悟性好的，有理解力的", "english": "comprehensive /,kɒmprɪ'hensɪv/", "type": "单词", "keyWords": [] },
    { "chinese": "面面俱到的描写", "english": "a comprehensive description", "type": "短语", "keyWords": ["comprehensive"] },
    { "chinese": "a.强迫的，强制的；义务的 n.(C)体育比赛中规定动作", "english": "compulsory /kəm'pʌlsəri/", "type": "单词", "keyWords": [] },
    { "chinese": "必修科目", "english": "compulsory subjects", "type": "短语", "keyWords": ["compulsory"] },
    { "chinese": "义务教育", "english": "compulsory education", "type": "短语", "keyWords": ["compulsory"] },
    { "chinese": "v./vi.计算", "english": "compute /kəm'pju:t/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)计算机", "english": "computer /kəm'pju:tə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)计算", "english": "computation", "type": "单词", "keyWords": ["compute"] },
    { "chinese": "计算机病毒", "english": "computer virus", "type": "短语", "keyWords": ["computer"] },
    { "chinese": "计算机科学", "english": "computer science", "type": "短语", "keyWords": ["computer"] },
    { "chinese": "a.计算机辅助的", "english": "computer-aided = computer-assisted", "type": "短语", "keyWords": ["computer"] },
    { "chinese": "计算机辅助设计（CAD）", "english": "computer-aided design", "type": "短语", "keyWords": ["computer"] },
    { "chinese": "v.隐藏（常指有目的地、非常巧妙地隐藏或隐瞒）；掩盖；隐瞒", "english": "conceal /kən'si:l/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)隐藏；隐瞒；掩盖", "english": "concealment", "type": "单词", "keyWords": ["conceal"] },
    { "chinese": "向某人隐瞒某事", "english": "conceal sth. from sb.", "type": "短语", "keyWords": ["conceal"] },
    { "chinese": "vi.集中；专心，全神贯注 v.集中（很少用）", "english": "concentrate /'kɒnsntreɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "全神贯注于（近focus... on..., fix... on...）", "english": "concentrate(...) on sth.", "type": "短语", "keyWords": ["concentrate"] },
    { "chinese": "n.(U)专心；集中（注意力）", "english": "concentration /,kɒnsn'treɪʃn/", "type": "单词", "keyWords": ["concentrate"] },
    { "chinese": "n.(C)概念；理论；观念，想法，思想", "english": "concept /'kɒnsept/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)有关的事；关心；忧虑 v.与..有关；使关心；使担心", "english": "concern /kən'sɜ:n/", "type": "单词", "keyWords": [] },
    { "chinese": "prep.关于，论及，就...说（其他见as for）", "english": "concerning", "type": "单词", "keyWords": ["concern"] },
    { "chinese": "关心此事", "english": "have concern about the matter", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "这不关你的事。", "english": "It is no concern of yours.", "type": "句子", "keyWords": ["concern"] },
    { "chinese": "那与我无关。", "english": "That doesn't concern me.", "type": "句子", "keyWords": ["concern"] },
    { "chinese": "关心（近be worried about）", "english": "be concerned about..", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "与...有关（近be connected/ associated with, have something to do with）", "english": "be concerned with...", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "就我个人来说", "english": "as/ so far as I am concerned", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "有关的（近associated）（作前置定语）担忧的（近worried）", "english": "concerned(作后置定语)", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "与凶杀案有牵连的人都已查明。", "english": "Everyone concerned in the murder case has been identified.", "type": "句子", "keyWords": ["concern"] },
    { "chinese": "一副担忧的表情", "english": "a concerned look", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "n.(C)音乐会", "english": "concert /'kɒnsət/", "type": "单词", "keyWords": [] },
    { "chinese": "vt.推断出；缔结 vi.结束，终结", "english": "conclude /kən'klu:d/", "type": "单词", "keyWords": [] },
    { "chinese": "结束段/结束语", "english": "the concluding paragraph/ remarks", "type": "短语", "keyWords": ["conclude"] },
    { "chinese": "n.(C)结论，推论；结束，结尾，结局；缔结", "english": "conclusion /kən'klu:ʒn/", "type": "单词", "keyWords": [] },
    { "chinese": "a.结论性的；确凿的", "english": "conclusive", "type": "单词", "keyWords": ["conclusion"] },
    { "chinese": "所得的结论是", "english": "arrive at/ reach/ draw/ come to the conclusion that...", "type": "短语", "keyWords": ["conclusion"] },
    { "chinese": "匆忙得出...的结论", "english": "jump to the conclusion that...", "type": "短语", "keyWords": ["conclusion"] },
    { "chinese": "确凿的证据", "english": "a conclusive proof", "type": "短语", "keyWords": ["conclusive"] },
    { "chinese": "n.(U)混凝土 a.混凝土（制）的；具体的；实在的 v.用混凝土浇筑（或涂于）", "english": "concrete /'kɒŋkri:t/", "type": "单词", "keyWords": [] },
    { "chinese": "具体的事实/想法/证据", "english": "concrete facts/ thoughts/ evidence", "type": "短语", "keyWords": ["concrete"] },
    { "chinese": "v.谴责；判处", "english": "condemn /kən'dem/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)状况 (C)条件 (pl)环境", "english": "condition /kən'dɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "a.有条件的", "english": "conditional", "type": "单词", "keyWords": ["condition"] },
    { "chinese": "n.(C)（冷/暖）空气调节器；护发剂", "english": "conditioner /kən'dɪʃənə/", "type": "单词", "keyWords": ["condition"] },
    { "chinese": "健康正常；保存得好", "english": "in good condition", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "在目前情况下", "english": "in/ under existing conditions", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "只要，在...条件下", "english": "on condition that...", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "空调房", "english": "an air-conditioned room", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "绝不", "english": "in/ under no condition", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "只要你不乱花钱，我就让你去。", "english": "I'll let you go on condition that you never waste money.", "type": "句子", "keyWords": ["condition"] },
    { "chinese": "vt.进行；传导（电、热）；引领（近lead）；控制，管理（近control, manage） n.(U)行为，举止；管理（近behaviour）", "english": "conduct /kən'dʌkt/", "type": "单词", "keyWords": [] },
    { "chinese": "引导我们游览城市", "english": "conduct us around the city", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "进行会议/调查", "english": "conduct a meeting/survey", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "优良/不良的品行", "english": "good/ bad conduct", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "有导游陪同的旅行", "english": "a conducted tour", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "表现；为人", "english": "conduct oneself", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "n.(C)公交车等的）售票员；列车员；（乐队的）指挥；导体", "english": "conductor /kən'dʌktə/", "type": "单词", "keyWords": ["conduct"] },
    { "chinese": "n.(C)（正式的）会议；讨论会，协商会", "english": "conference /'kɒnfərəns/", "type": "单词", "keyWords": [] },
    { "chinese": "（在）记者招待会/新闻发布会（上）", "english": "(at)a press/ news conference", "type": "短语", "keyWords": ["conference"] },
    { "chinese": "vt.vi.承认；坦白（辨析见admit）", "english": "confess /kən'fes/", "type": "单词", "keyWords": [] },
    { "chinese": "承认偷了....", "english": "confess (to) having stolen...", "type": "短语", "keyWords": ["confess"] },
    { "chinese": "向某人承认", "english": "confess to sb. that...", "type": "短语", "keyWords": ["confess"] },
    { "chinese": "承认错误", "english": "confess oneself to be in the wrong", "type": "短语", "keyWords": ["confess"] },
    { "chinese": "n.(C)(U)供词；认罪；坦白；承认", "english": "confession /kən'feʃn/", "type": "单词", "keyWords": ["confess"] },
    { "chinese": "承认错误；供认罪行；交代", "english": "make a confession", "type": "短语", "keyWords": ["confession"] },
    { "chinese": "n.(U)信任；信心", "english": "confidence /'kɒnfɪdəns/", "type": "单词", "keyWords": [] },
    { "chinese": "a.有信心的；自信的", "english": "confident", "type": "单词", "keyWords": ["confidence"] },
    { "chinese": "对...缺乏/有信心", "english": "lack/ have confidence in", "type": "短语", "keyWords": ["confidence"] },
    { "chinese": "满怀信心地；有把握地", "english": "with confidence", "type": "短语", "keyWords": ["confidence"] },
    { "chinese": "对...有信心的（近be sure of）", "english": "be confident of...", "type": "短语", "keyWords": ["confident"] },
    { "chinese": "vt.（进一步）证实；确认；使更坚固（坚定、坚强）", "english": "confirm /kən'fɜ:m/", "type": "单词", "keyWords": [] },
    { "chinese": "a.可确定的；能证实的", "english": "confirmable", "type": "单词", "keyWords": ["confirm"] },
    { "chinese": "n.(C)(U)证实；确认", "english": "confirmation", "type": "单词", "keyWords": ["confirm"] },
    { "chinese": "还待确认。", "english": "It wants yet to be confirmed.", "type": "句子", "keyWords": ["confirm"] },
    { "chinese": "你所告诉我的有关里奥的事证实了我对他打妻子的怀疑。", "english": "What you had told me about Leo confirmed me in my suspicion (= confirmed my suspicion) that he beat his wife.", "type": "句子", "keyWords": ["confirm"] },
    { "chinese": "vi./n.(C)(U)争论；战斗；冲突，矛盾，抵触（with）", "english": "conflict /'kɒnflɪkt/", "type": "单词", "keyWords": [] },
    { "chinese": "意见的冲突", "english": "a conflict of opinions/views", "type": "短语", "keyWords": ["conflict"] },
    { "chinese": "相互矛盾的证据", "english": "conflicting evidence", "type": "短语", "keyWords": ["conflict"] },
    { "chinese": "和...冲突", "english": "come into conflict with/ be in conflict with/ conflict with", "type": "短语", "keyWords": ["conflict"] },
    { "chinese": "v.使..混乱；使..慌乱；使...困惑", "english": "confuse /kən'fju:z/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)困惑；糊涂", "english": "confusion /kən'fju:ʒn/", "type": "单词", "keyWords": ["confuse"] },
    { "chinese": "感到/使人困惑的", "english": "confused/ confusing", "type": "单词", "keyWords": ["confuse"] },
    { "chinese": "被...弄迷糊/弄得发慌", "english": "feel/ be confused (with/at/ about sth.)", "type": "短语", "keyWords": ["confuse"] },
    { "chinese": "他脸上困惑的表情", "english": "a confused expression on his face", "type": "短语", "keyWords": ["confuse"] },
    { "chinese": "n.(U)挤满；拥塞；充血", "english": "congestion /kən'dʒestʃən/", "type": "单词", "keyWords": [] },
    { "chinese": "vt.祝贺，向...道喜", "english": "congratulate /kən'ɡrætʃuleɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "向某人祝贺某事", "english": "congratulate sb. on sth.", "type": "短语", "keyWords": ["congratulate"] },
    { "chinese": "n.(pl)祝贺，道贺 (U)贺词", "english": "congratulation /kən,ɡrætʃu'leɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "祝贺...！", "english": "Congratulations on sth.!", "type": "短语", "keyWords": ["congratulation"] },
    { "chinese": "贺信", "english": "a letter of congratulation", "type": "短语", "keyWords": ["congratulation"] },
    { "chinese": "n.(C)代表大会；立法机关；(the C-)美国国会", "english": "congress /'kɒŋɡres/", "type": "单词", "keyWords": [] },
    { "chinese": "v./vi.连接（常与to,with连用）；联系；接通电话", "english": "connect /kə'nekt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)连接；联系", "english": "connection", "type": "单词", "keyWords": ["connect"] },
    { "chinese": "这管子和一根较小的管子连通着。", "english": "This pipe connects with a smaller one.", "type": "句子", "keyWords": ["connect"] },
    { "chinese": "与·..有关系/联系", "english": "be connected with...", "type": "短语", "keyWords": ["connect"] },
    { "chinese": "那个老头被怀疑与犯罪事件有关。", "english": "That old man was suspected to be connected with the crime.", "type": "句子", "keyWords": ["connect"] },
    { "chinese": "vt.击败，攻克；征服；克服（困难等）", "english": "conquer /'kɒŋkə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)征服", "english": "conquest", "type": "单词", "keyWords": ["conquer"] },
    { "chinese": "n.(C)征服者，胜利者", "english": "conqueror /'kɒŋkərə/", "type": "单词", "keyWords": ["conquer"] },
    { "chinese": "人能战胜自然。", "english": "Man can conquer nature.", "type": "句子", "keyWords": ["conquer"] },
    { "chinese": "被征服者，失败者", "english": "the conquered", "type": "短语", "keyWords": ["conquer"] },
    { "chinese": "n.(C)良心", "english": "conscience /'kɒnʃəns/", "type": "单词", "keyWords": [] },
    { "chinese": "问心有愧", "english": "have a bad/ guilty conscience", "type": "短语", "keyWords": ["conscience"] },
    { "chinese": "问心无愧；无愧于心", "english": "have a good/ clear conscience", "type": "短语", "keyWords": ["conscience"] },
    { "chinese": "a.意识到的，有意识的；有知觉的，神志清醒的", "english": "conscious /'kɒnʃəs/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)知觉；意识", "english": "consciousness", "type": "单词", "keyWords": ["conscious"] },
    { "chinese": "意识到", "english": "be conscious/aware of", "type": "短语", "keyWords": ["conscious"] },
    { "chinese": "失去/恢复知觉", "english": "lose/ regain/ recover one's consciousness", "type": "短语", "keyWords": ["consciousness"] },
    { "chinese": "n.(C)结果，后果 (U)重要（性）", "english": "consequence /'kɒnsɪkwəns/", "type": "单词", "keyWords": [] },
    { "chinese": "a.随之发生的", "english": "consequent", "type": "单词", "keyWords": ["consequence"] },
    { "chinese": "ad.结果；因此", "english": "consequently (=in consequence/ thus)", "type": "单词", "keyWords": ["consequence"] },
    { "chinese": "考虑后果", "english": "consider the consequences", "type": "短语", "keyWords": ["consequence"] },
    { "chinese": "要人", "english": "a man of consequence", "type": "短语", "keyWords": ["consequence"] },
    { "chinese": "a.保守的；守旧的", "english": "conservative /kən'sɜ:vətɪv/", "type": "单词", "keyWords": [] },
    { "chinese": "（英国的）保守党", "english": "the Conservative Party", "type": "短语", "keyWords": ["conservative"] },
    { "chinese": "vt.认为（+ sb./sth. to be），考虑，细想，思量，斟酌（+ doing sth.）", "english": "consider /kən'sɪdə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)考虑；体谅，照顾，关心", "english": "consideration", "type": "单词", "keyWords": ["consider"] },
    { "chinese": "把某人看作；认为某人已经...", "english": "consider sb. (to be/ to have done sth.)...", "type": "短语", "keyWords": ["consider"] },
    { "chinese": "我正在考虑换工作。", "english": "I am considering changing my job.", "type": "句子", "keyWords": ["consider"] },
    { "chinese": "考虑到...（近concerning, with regard to, as for）", "english": "Considering...", "type": "短语", "keyWords": ["consider"] },
    { "chinese": "加以考虑；予以原谅", "english": "take... into consideration/ account", "type": "短语", "keyWords": ["consideration"] },
    { "chinese": "考虑中，研究中", "english": "(be) under consideration", "type": "短语", "keyWords": ["consideration"] },
    { "chinese": "a.相当大（重、长）的；值得考虑的；重大的；重要的", "english": "considerable /kən'sɪdərəbl/", "type": "单词", "keyWords": [] },
    { "chinese": "大量的", "english": "a considerable amount of", "type": "短语", "keyWords": ["considerable"] },
    { "chinese": "a.体谅的；考虑周到的", "english": "considerate /kən'sɪdərɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "能体谅别人的", "english": "be considerate of others", "type": "短语", "keyWords": ["considerate"] },
    { "chinese": "vi.由...组成；构成（of）；存在于（in）", "english": "consist /kən'sɪst/", "type": "单词", "keyWords": [] },
    { "chinese": "在于", "english": "consist/ lie in", "type": "短语", "keyWords": ["consist"] },
    { "chinese": "幸福在于知足。", "english": "Happiness consists in contentment.", "type": "句子", "keyWords": ["consist"] },
    { "chinese": "由...组成（近be composed of, be made up of）", "english": "consist of", "type": "短语", "keyWords": ["consist"] },
    { "chinese": "那本书共有八章。", "english": "The book consists of eight chapters.", "type": "句子", "keyWords": ["consist"] },
    { "chinese": "a.经常的，连续发生的，不断的，一再重复的（有稳定不变的、反复的含义）；恒定不变的，持久不变的，固定的，稳定的", "english": "constant /'kɒnstənt/", "type": "单词", "keyWords": [] },
    { "chinese": "ad.经常不断地；一再重复地", "english": "constantly", "type": "单词", "keyWords": ["constant"] },
    { "chinese": "对爱情忠贞不渝", "english": "be constant in love", "type": "短语", "keyWords": ["constant"] },
    { "chinese": "两天接连下雨", "english": "two days of constant rain", "type": "短语", "keyWords": ["constant"] },
    { "chinese": "v.建造；构建（通过装配或组合部件而构成）；构成；创立", "english": "construct /kən'strʌkt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)建筑，建造；结构；创立 (C)建筑物", "english": "construction /kən'strʌkʃn/", "type": "单词", "keyWords": ["construct"] },
    { "chinese": "a.建设性的", "english": "constructive", "type": "单词", "keyWords": ["construct"] },
    { "chinese": "建设中", "english": "under construction", "type": "短语", "keyWords": ["construction"] },
    { "chinese": "建筑工地", "english": "construction site", "type": "短语", "keyWords": ["construction"] },
    { "chinese": "建设性的批评", "english": "constructive criticism", "type": "短语", "keyWords": ["constructive"] },
    { "chinese": "v.请教；查阅", "english": "consult /kən'sʌlt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)顾问（on）", "english": "consultant", "type": "单词", "keyWords": ["consult"] },
    { "chinese": "n.(U)咨询 (C)咨询会", "english": "consultation", "type": "单词", "keyWords": ["consult"] },
    { "chinese": "查词典", "english": "consult a dictionary", "type": "短语", "keyWords": ["consult"] },
    { "chinese": "找医生诊治", "english": "consult a doctor", "type": "短语", "keyWords": ["consult"] },
    { "chinese": "vt.消耗；消费；耗尽；吃完；喝光；烧毁；vi.耗尽", "english": "consume /kən'sju:m/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)消费者；顾客；用户", "english": "consumer /kən'sju:mə/", "type": "单词", "keyWords": ["consume"] },
    { "chinese": "n.(U)（可加a）消耗；消费", "english": "consumption", "type": "单词", "keyWords": ["consume"] },
    { "chinese": "v./n.(U)接触；联系（多用于商业上，非亲密的朋友之间）(C)熟人", "english": "contact /'kɒntækt/", "type": "单词", "keyWords": [] },
    { "chinese": "需进一步信息的话请和我们联系。", "english": "Contact us for further information.", "type": "句子", "keyWords": ["contact"] },
    { "chinese": "同...接触；跟..保持联系", "english": "keep/be in contact with....", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "跟...有/失去联系", "english": "have/ lose contact with...", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "使...和....接触", "english": "bring .. into contact with...", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "和...接触", "english": "come/ get into contact with...", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "交际广（门路多）的人", "english": "a man of many contacts", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "v.包括；含有，包含；能容纳", "english": "contain /kən'teɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)容器；集装箱", "english": "container", "type": "单词", "keyWords": ["contain"] },
    { "chinese": "a.当代的；发生/存在于同一时代的 n.(C)同时代的人", "english": "contemporary /kən'temprəri/", "type": "单词", "keyWords": [] },
    { "chinese": "和莎士比亚同时代", "english": "be contemporary with Shakespeare", "type": "短语", "keyWords": ["contemporary"] },
    { "chinese": "n.(U)容积；内容；满足，满意 (pl)（书、包等）内含物；（书刊）目录 v.使满意，使满足 a.（只作表语用）满足的，甘心的", "english": "content /'kɒntent/", "type": "单词", "keyWords": [] },
    { "chinese": "目录", "english": "a table of contents", "type": "短语", "keyWords": ["content"] },
    { "chinese": "尽情，尽量", "english": "to one's heart's content", "type": "短语", "keyWords": ["content"] },
    { "chinese": "对...满意", "english": "be content with/ be contented with/ be satisfied with...", "type": "短语", "keyWords": ["content"] },
    { "chinese": "内容上和形式上", "english": "in content and form", "type": "短语", "keyWords": ["content"] },
    { "chinese": "满意的微笑", "english": "a contented smile", "type": "短语", "keyWords": ["content"] },
    { "chinese": "v./n.(C)竞赛，比赛；争夺；竞争", "english": "contest /kən'test/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)参赛者", "english": "contestant", "type": "单词", "keyWords": ["contest"] },
    { "chinese": "n.(C)(U)上下文；语境；背景，环境", "english": "context /'kɒntekst/", "type": "单词", "keyWords": [] },
    { "chinese": "在上下文", "english": "in context", "type": "短语", "keyWords": ["context"] },
    { "chinese": "在...情况下", "english": "in the context of", "type": "短语", "keyWords": ["context"] },
    { "chinese": "n.(C)洲；大陆", "english": "continent /'kɒntɪnənt/", "type": "单词", "keyWords": [] },
    { "chinese": "a.大陆的", "english": "continental /,kɒntɪ'nentl/", "type": "单词", "keyWords": ["continent"] },
    { "chinese": "欧洲大陆；（美）北美洲大陆", "english": "the Continent", "type": "短语", "keyWords": ["continent"] },
    { "chinese": "v./vi.继续；连续；延续", "english": "continue /kən'tɪnju:/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)连续（性）", "english": "continuity", "type": "单词", "keyWords": ["continue"] },
    { "chinese": "a.无间断的；连续的，继续的", "english": "continuous", "type": "单词", "keyWords": ["continue"] },
    { "chinese": "a.连续的；频繁的", "english": "continual", "type": "单词", "keyWords": ["continue"] },
    { "chinese": "继续工作", "english": "continue (with) one's work", "type": "短语", "keyWords": ["continue"] },
    { "chinese": "待续；未完", "english": "to be continued", "type": "短语", "keyWords": ["continue"] },
    { "chinese": "恒（直）流电", "english": "a continuous current", "type": "短语", "keyWords": ["continuous"] },
    { "chinese": "连续射击", "english": "continuous fire", "type": "短语", "keyWords": ["continuous"] },
    { "chinese": "连续的掌声/下不停的雨/持续的担心", "english": "continual applause/ rain/worry", "type": "短语", "keyWords": ["continual"] },
    { "chinese": "n.(C)契约，合同 v.订（契约），订（合同）", "english": "contract /'kɒntrækt/", "type": "单词", "keyWords": [] },
    { "chinese": "与...订约", "english": "enter into/ make a contract with", "type": "短语", "keyWords": ["contract"] },
    { "chinese": "履行合约", "english": "fulfil a contract", "type": "短语", "keyWords": ["contract"] },
    { "chinese": "n.(the)相反；反面 a.反对的，相反的；格格不入的（强调极度的不同）", "english": "contrary /'kɒntrəri/", "type": "单词", "keyWords": [] },
    { "chinese": "是冷的反义", "english": "be the contrary of cold", "type": "短语", "keyWords": ["contrary"] },
    { "chinese": "出乎意外", "english": "be contrary to one's expectations", "type": "短语", "keyWords": ["contrary"] },
    { "chinese": "相反/正相反，我非常喜欢。", "english": "On the contrary, I like it very much.", "type": "句子", "keyWords": ["contrary"] },
    { "chinese": "不知道任何与之相反的情况", "english": "know nothing to the contrary", "type": "短语", "keyWords": ["contrary"] },
    { "chinese": "没有反证。", "english": "There is no evidence to the contrary.", "type": "句子", "keyWords": ["contrary"] },
    { "chinese": "n.(U)对照；比较 (C)对照；差别；形成对照的人或事物（to） v.（使用）成对比；（使）成对照", "english": "contrast /'kɒntrɑ:st/", "type": "单词", "keyWords": [] },
    { "chinese": "对比之下", "english": "by contrast", "type": "短语", "keyWords": ["contrast"] },
    { "chinese": "和...成对比；和...大不相同", "english": "in contrast with/to...", "type": "短语", "keyWords": ["contrast"] },
    { "chinese": "与旧的明显差别", "english": "a sharp contrast to the old one", "type": "短语", "keyWords": ["contrast"] }
];
