const qgl65_72 = [
    { "chinese": "和...的明显差别", "english": "a striking contrast between ...and....", "type": "短语", "keyWords": ["contrast"] },
    { "chinese": "n. 贡献者，捐助者，投稿人", "english": "contributor", "type": "单词", "keyWords": [] },
    { "chinese": "贡献；捐献；捐助；稿件（n.）", "english": "contribution", "type": "单词", "keyWords": [] },
    { "chinese": "作贡献；有助于；促使；捐款", "english": "contribute to= make (great) contributions to", "type": "短语", "keyWords": ["contribute", "contribution"] },
    { "chinese": "vi. 贡献；捐（款等）；投（稿），撰（稿）(to)", "english": "contribute", "type": "单词", "keyWords": [] },
    { "chinese": "宋朝为世界文明贡献了三大发明。", "english": "The Song Dynasty contributed three great inventions to world civilization.", "type": "句子", "keyWords": ["contribute"] },
    { "chinese": "v. 控制；支配（n. 控制；支配；控制装置（器））", "english": "control", "type": "单词", "keyWords": [] },
    { "chinese": "生育控制，节制生育", "english": "birth control", "type": "短语", "keyWords": ["control"] },
    { "chinese": "控制不住...", "english": "lose control of...", "type": "短语", "keyWords": ["control"] },
    { "chinese": "处于失控状态中", "english": "out of/ beyond control", "type": "短语", "keyWords": ["control"] },
    { "chinese": "控制着，管理", "english": "in control of", "type": "短语", "keyWords": ["control"] },
    { "chinese": "受...管制（管理、支配），在...管辖下的", "english": "under/in the control of...", "type": "短语", "keyWords": ["control"] },
    { "chinese": "抑制，治理（水患），控制（火灾）", "english": "get/bring.. under control", "type": "短语", "keyWords": ["control"] },
    { "chinese": "（机场等）指挥（调度）塔台", "english": "control tower", "type": "短语", "keyWords": ["control"] },
    { "chinese": "控制，统制", "english": "take/ have/ hold/ gain control of", "type": "短语", "keyWords": ["control"] },
    { "chinese": "n. 方便；生活上的便利设备（a. 方便的；（提供）便利的；近处的；合适的）", "english": "convenience/ convenient", "type": "单词", "keyWords": [] },
    { "chinese": "为了便利起见", "english": "for convenience", "type": "短语", "keyWords": ["convenience"] },
    { "chinese": "顺便；方便的时候", "english": "at one's convenience", "type": "短语", "keyWords": ["convenience"] },
    { "chinese": "为了...的方便起见", "english": "for the convenience of", "type": "短语", "keyWords": ["convenience"] },
    { "chinese": "你方便的话...", "english": "whenever it is convenient to/ for you", "type": "短语", "keyWords": ["convenient"] },
    { "chinese": "n. 谈话；会话；一次谈话；一次会话（a. 谈话的）", "english": "conversation/ conversational", "type": "单词", "keyWords": [] },
    { "chinese": "与某人交谈", "english": "in conversation with sb.", "type": "短语", "keyWords": ["conversation"] },
    { "chinese": "vt. 传达；表达；传导/送/递；运送，搬运（n. 传达；运输）", "english": "convey/ conveyance", "type": "单词", "keyWords": [] },
    { "chinese": "把....传达给...；把...运输给...", "english": "convey..to...", "type": "短语", "keyWords": ["convey"] },
    { "chinese": "大使亲自向总理转达了总统的问候。", "english": "The ambassador personally conveyed the president's message to the premier.", "type": "句子", "keyWords": ["convey"] },
    { "chinese": "vt. 说服；使...相信/确信（a. 有说服力的；ad. 令人信服地）", "english": "convince/ convincing/ convincingly", "type": "单词", "keyWords": [] },
    { "chinese": "使某人相信...", "english": "convince sb.of/that...", "type": "短语", "keyWords": ["convince"] },
    { "chinese": "n. 厨师，炊事员（vt. 烹调；n. 烹调）", "english": "cook/ cooking", "type": "单词", "keyWords": [] },
    { "chinese": "n. 炊具（n. 烹调术）", "english": "cooker/ cookery", "type": "单词", "keyWords": [] },
    { "chinese": "a. 凉的；凉爽的，凉快的；冷静的，无所顾虑的；淡漠的；[口]绝妙的（vi./vt. （使）变凉；（使）冷静(down)）", "english": "cool", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 合作；协作；配合（a. 合作的，协力的；n. 合作；协作；配合；n. 合作者）", "english": "cooperate/ cooperative/ cooperation/ cooperator", "type": "单词", "keyWords": [] },
    { "chinese": "与·..合作", "english": "cooperate with sb.", "type": "短语", "keyWords": ["cooperate"] },
    { "chinese": "（在）与...合作（下）", "english": "in cooperation with sb.", "type": "短语", "keyWords": ["cooperation"] },
    { "chinese": "vi. （成功）应付；（善于）处理，对付；竞争，争斗", "english": "cope", "type": "单词", "keyWords": [] },
    { "chinese": "同..较量；同...对抗；应付；对付", "english": "cope with", "type": "短语", "keyWords": ["cope"] },
    { "chinese": "n. 铜", "english": "copper", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 抄写；拷贝；复印；模仿；抄袭（n. 复制品；副本；拷贝；模仿；（报、书）一份（册））", "english": "copy", "type": "单词", "keyWords": [] },
    { "chinese": "抄下", "english": "copy... down", "type": "短语", "keyWords": ["copy"] },
    { "chinese": "n. 玉米；谷物；[医]鸡眼", "english": "corn", "type": "单词", "keyWords": [] },
    { "chinese": "n. （屋）角；（街道）拐角；困境（vt. 把...逼入角落；将...逼入困境）", "english": "corner", "type": "单词", "keyWords": [] },
    { "chinese": "在拐角处", "english": "at/on the corner of", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "在...的角落里", "english": "in the corner of", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "在拐角处；就在眼前", "english": "round the corner", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "将窃贼逼入角落并擒住他们", "english": "corner the thieves and capture them", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "将...逼入困境", "english": "drive/ put/ force sb. into a corner", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "n. [律]社团，法人；公司，企业；[美]有限公司", "english": "corporation", "type": "单词", "keyWords": [] },
    { "chinese": "v. 改正；纠正（a. 正确的；得体的；恰当的；端正的；n. 改正，修正；n. 正确性）", "english": "correct/ correction/ correctness", "type": "单词", "keyWords": [] },
    { "chinese": "n. 走廊；室外过道；回廊", "english": "corridor", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 相符；一致；通信（n. 信件，函件（尤指公函或商业信函）；n. 记者）", "english": "correspond/ correspondence/ correspondent", "type": "单词", "keyWords": [] },
    { "chinese": "a. 化妆用的；美发用的（n. 化妆品；美容术）", "english": "cosmetic", "type": "单词", "keyWords": [] },
    { "chinese": "v. 值（多少钱）；（使）花费（金钱），（使）付出（生命，健康等）代价（n. 费用；成本；代价）", "english": "cost", "type": "单词", "keyWords": [] },
    { "chinese": "这值（花了他们）十美元。", "english": "It cost(them) ten dollars.", "type": "句子", "keyWords": ["cost"] },
    { "chinese": "这错误使他失去了工作/生命。", "english": "The mistake cost him his job/ his life.", "type": "句子", "keyWords": ["cost"] },
    { "chinese": "以付出健康/生命为代价", "english": "at the cost of his health/ his life", "type": "短语", "keyWords": ["cost"] },
    { "chinese": "不惜一切代价", "english": "at all costs/ at any cost", "type": "短语", "keyWords": ["cost"] },
    { "chinese": "生活费", "english": "the cost of living", "type": "短语", "keyWords": ["cost"] },
    { "chinese": "a. 昂贵的，贵重的", "english": "costly", "type": "单词", "keyWords": [] },
    { "chinese": "n. 棉花", "english": "cotton", "type": "单词", "keyWords": [] },
    { "chinese": "n. （演出、化装舞会的）服装（一种流行的穿着样式，或指有某国家、时期或民众特点的衣着样式，通常在戏剧表演或化装舞会上穿）", "english": "costume", "type": "单词", "keyWords": [] },
    { "chinese": "n. 农舍；小房子；（农舍式的）别墅", "english": "cottage", "type": "单词", "keyWords": [] },
    { "chinese": "n. 长沙发", "english": "couch", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. 咳嗽", "english": "cough", "type": "单词", "keyWords": [] },
    { "chinese": "v. 能够（can的过去式）", "english": "could", "type": "单词", "keyWords": [] },
    { "chinese": "他目前可能躲在什么地方。", "english": "He could be anywhere.", "type": "句子", "keyWords": ["could"] },
    { "chinese": "你本可以更慎重些。", "english": "You could have been more considerate.", "type": "句子", "keyWords": ["could"] },
    { "chinese": "vt./vi. 数，清点；把...算在内；vi. 重要，有价值；指望，依赖(on/upon)", "english": "count", "type": "单词", "keyWords": [] },
    { "chinese": "把我算进去。", "english": "Count me in.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "事事都不可疏忽。/要事事都办妥帖。", "english": "See that everything counts.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "每秒钟都很重要。（分秒必争）", "english": "Every second counts.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "指望某人做某事", "english": "count on/upon sb. to do ..", "type": "短语", "keyWords": ["count"] },
    { "chinese": "指望（某人）做某事", "english": "count on/ upon (sb.) doing..", "type": "短语", "keyWords": ["count"] },
    { "chinese": "你可以依赖我的帮助。", "english": "You can count on my help.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "你们不能指望天晴。", "english": "You can't count upon the weather being fine.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "他们期待获得加薪。", "english": "They counted on getting a rise.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "他凡事都指望姐姐。", "english": "He counted upon/ on his sister for everything.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "a. 可计算的；可数的", "english": "countable", "type": "单词", "keyWords": [] },
    { "chinese": "n. 柜台；柜台式长桌；计算器，计数器，计算者；adv./prep. 相反（地）", "english": "counter", "type": "单词", "keyWords": [] },
    { "chinese": "在...柜台", "english": "at the..counter", "type": "短语", "keyWords": ["counter"] },
    { "chinese": "逆时针方向", "english": "counter-clockwise", "type": "短语", "keyWords": ["counter"] },
    { "chinese": "n. 国家；乡下（a. 乡下的，乡村的；[方]祖国的；故乡的）", "english": "country", "type": "单词", "keyWords": [] },
    { "chinese": "在乡下", "english": "in the country/countryside", "type": "短语", "keyWords": ["country"] },
    { "chinese": "全国", "english": "throughout the country", "type": "短语", "keyWords": ["country"] },
    { "chinese": "农村生活", "english": "country life", "type": "短语", "keyWords": ["country"] },
    { "chinese": "n. 郡（英国最大的地方行政区）；（美国、中国等）县", "english": "county", "type": "单词", "keyWords": [] },
    { "chinese": "n. （一）对；夫妻；情侣；一双（不一定成对）；（非正式用语）数个；几个（v. 连接，结合；使成对；把...联系起来）", "english": "couple", "type": "单词", "keyWords": [] },
    { "chinese": "几个苹果", "english": "a couple of apples", "type": "短语", "keyWords": ["couple"] },
    { "chinese": "几天", "english": "a couple of days", "type": "短语", "keyWords": ["couple"] },
    { "chinese": "年轻夫妇", "english": "a young couple (is/ are..)", "type": "短语", "keyWords": ["couple"] },
    { "chinese": "伴有", "english": "be coupled with", "type": "短语", "keyWords": ["couple"] },
    { "chinese": "n. 勇气；勇敢（a. 勇敢的，英勇的）", "english": "courage/ courageous", "type": "单词", "keyWords": [] },
    { "chinese": "鼓起勇气", "english": "screw up one's courage", "type": "短语", "keyWords": ["courage"] },
    { "chinese": "不泄气，不丧胆，不气馁", "english": "keep up one's courage", "type": "短语", "keyWords": ["courage"] },
    { "chinese": "n. 过程；课程；一道菜；（运动物体）行进路线，河（航）道；所经之路", "english": "course", "type": "单词", "keyWords": [] },
    { "chinese": "人生的过程", "english": "the course of life", "type": "短语", "keyWords": ["course"] },
    { "chinese": "选...课程", "english": "take the course in/on...", "type": "短语", "keyWords": ["course"] },
    { "chinese": "在...过程中", "english": "in/ during the course of", "type": "短语", "keyWords": ["course"] },
    { "chinese": "五道菜的一餐饭", "english": "a dinner of five courses", "type": "短语", "keyWords": ["course"] },
    { "chinese": "标有主要河流航道的地图", "english": "a map that shows the courses of the chief rivers", "type": "短语", "keyWords": ["course"] },
    { "chinese": "他们向北行进。", "english": "They took a northern course.", "type": "句子", "keyWords": ["course"] },
    { "chinese": "n. 球场；庭院；短街；陈列区，馆；法院；（the）宫廷", "english": "court", "type": "单词", "keyWords": [] },
    { "chinese": "美食街", "english": "food court", "type": "短语", "keyWords": ["court"] },
    { "chinese": "朝见君主；上法院；打官司", "english": "go to court", "type": "短语", "keyWords": ["court"] },
    { "chinese": "n. 堂（或表）兄弟；堂（或表）姐妹", "english": "cousin", "type": "单词", "keyWords": [] },
    { "chinese": "n. 盖子；封面；藏身处（vt. 覆盖；掩饰；掩护；包括；行过（路程）；报道；走完；看完）", "english": "cover", "type": "单词", "keyWords": [] },
    { "chinese": "躲藏；躲避；避难", "english": "take cover/shelter", "type": "短语", "keyWords": ["cover"] },
    { "chinese": "我想在天黑之前走完100英里。", "english": "I want to cover 100 miles by dark.", "type": "句子", "keyWords": ["cover"] },
    { "chinese": "我想每天读完20页。", "english": "I want to cover 20 pages a day.", "type": "句子", "keyWords": ["cover"] },
    { "chinese": "他的研究涉及广大范围。", "english": "His studies covered a wide field.", "type": "句子", "keyWords": ["cover"] },
    { "chinese": "我的收入刚刚够用。（抵消花费）", "english": "My income barely covers my expenses.", "type": "句子", "keyWords": ["cover"] },
    { "chinese": "被派去负责报道这场战争/这则新闻", "english": "be sent to cover the war/news", "type": "短语", "keyWords": ["cover"] },
    { "chinese": "用...覆盖...", "english": "cover..with...", "type": "短语", "keyWords": ["cover"] },
    { "chinese": "n. 母牛，奶牛（n. 牛仔）", "english": "cow/ cowboy", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]裂缝，裂口；爆裂声；噼啪声 v.（使）破/爆裂；（使）发出爆裂声", "english": "crack", "type": "单词", "keyWords": [] },
    { "chinese": "n. 摇篮；（文化等的）发源地(of)", "english": "cradle", "type": "单词", "keyWords": [] },
    { "chinese": "n. 工艺；手艺；需要手艺的行业；小船；轮船；飞机（n. 手艺人）", "english": "craft/ craftsman", "type": "单词", "keyWords": [] },
    { "chinese": "工艺学校", "english": "a school for arts and crafts", "type": "短语", "keyWords": ["craft"] },
    { "chinese": "工艺美术", "english": "art and craft", "type": "短语", "keyWords": ["craft"] },
    { "chinese": "n. 碰撞；坠落，坠毁；撞击声（v. 碰撞；坠落，坠毁；（指公司、政府等）破产，垮台）", "english": "crash", "type": "单词", "keyWords": [] },
    { "chinese": "汽车撞车的事故", "english": "a car crash", "type": "短语", "keyWords": ["crash"] },
    { "chinese": "飞机坠毁事故", "english": "an air crash/ a plane crash", "type": "短语", "keyWords": ["crash"] },
    { "chinese": "他们的车撞上护栏。", "english": "Their car crashed into a guardrail.", "type": "句子", "keyWords": ["crash"] },
    { "chinese": "vi./n. 爬，爬行；蠕动，徐徐行进；匍匐前进", "english": "crawl", "type": "单词", "keyWords": [] },
    { "chinese": "a. 发疯的；疯狂的；狂热的；不切实际的；荒唐的；急切的", "english": "crazy", "type": "单词", "keyWords": [] },
    { "chinese": "发疯地；拼命地；猛烈地", "english": "like crazy", "type": "短语", "keyWords": ["crazy"] },
    { "chinese": "热衷于；醉心于；迷恋", "english": "be crazy about", "type": "短语", "keyWords": ["crazy"] },
    { "chinese": "n. 奶油（食品）；奶油色", "english": "cream", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 创造；产生（n. 创造）", "english": "create/ creation", "type": "单词", "keyWords": [] },
    { "chinese": "提供就业机会", "english": "create jobs", "type": "短语", "keyWords": ["create"] },
    { "chinese": "发言引起一阵骚动。", "english": "That remark created a stir.", "type": "句子", "keyWords": ["create"] },
    { "chinese": "a. 有创造力的；创造（性）的（n. 创造性）", "english": "creative/ creativity", "type": "单词", "keyWords": [] },
    { "chinese": "n. 生物（动物或人）", "english": "creature", "type": "单词", "keyWords": [] },
    { "chinese": "n. 信用；信贷；赊欠；声望，荣誉；赞扬，称许；[财务]贷方，银行存款（a. 难以置信的）", "english": "credit/ incredible", "type": "单词", "keyWords": [] },
    { "chinese": "赊购/赊售东西", "english": "buy/ sell sth. on credit", "type": "短语", "keyWords": ["credit"] },
    { "chinese": "信用卡", "english": "credit card", "type": "短语", "keyWords": ["credit"] },
    { "chinese": "极有名望的人", "english": "a man of high credit", "type": "短语", "keyWords": ["credit"] },
    { "chinese": "信任某人；称赞某人", "english": "give credit to sb.", "type": "短语", "keyWords": ["credit"] },
    { "chinese": "为什么他受到了所有人的赞扬？", "english": "Why should he get all the credit?", "type": "句子", "keyWords": ["credit"] },
    { "chinese": "他的成功使全家增光。", "english": "His success brings credit to his family.", "type": "句子", "keyWords": ["credit"] },
    { "chinese": "n. 支流，溪流；小河", "english": "creek", "type": "单词", "keyWords": [] },
    { "chinese": "n. （车、船、飞机上）（全体）工作人员", "english": "crew", "type": "单词", "keyWords": [] },
    { "chinese": "船上的工作人员有偿工作。", "english": "The crew are paid to do all the work on the ship.", "type": "句子", "keyWords": ["crew"] },
    { "chinese": "海盗船船员有78人。", "english": "The pirate crew was made up of 78 people.", "type": "句子", "keyWords": ["crew"] },
    { "chinese": "n. 犯罪行为；罪恶；罪行", "english": "crime", "type": "单词", "keyWords": [] },
    { "chinese": "犯罪", "english": "commit a crime", "type": "短语", "keyWords": ["crime"] },
    { "chinese": "n. 罪犯（a. 刑事的；犯罪的）", "english": "criminal", "type": "单词", "keyWords": [] },
    { "chinese": "刑法", "english": "criminal law", "type": "短语", "keyWords": ["criminal"] },
    { "chinese": "n. 决定性时刻；危机；转折点", "english": "crisis", "type": "单词", "keyWords": [] },
    { "chinese": "经济危机", "english": "an economic crisis", "type": "短语", "keyWords": ["crisis"] },
    { "chinese": "信任危机", "english": "a crisis of confidence", "type": "短语", "keyWords": ["crisis"] },
    { "chinese": "处于危机中", "english": "in crisis", "type": "短语", "keyWords": ["crisis"] },
    { "chinese": "n. （批评、判断的）标准，准据，规范", "english": "criterion", "type": "单词", "keyWords": [] },
    { "chinese": "n. 批评家；评论家（n. 批评；批判；v. 批评；批判；指责，非难）", "english": "critic/ criticism/ criticize", "type": "单词", "keyWords": [] },
    { "chinese": "因为某事批评某人", "english": "criticize sb. for (doing) sth.", "type": "短语", "keyWords": ["criticize"] },
    { "chinese": "a. 批判/评（性）的；挑剔的；严重的，危险的", "english": "critical", "type": "单词", "keyWords": [] },
    { "chinese": "处于危险期的疾病", "english": "an illness at the critical stage", "type": "短语", "keyWords": ["critical"] },
    { "chinese": "紧要关头，关键时刻", "english": "critical moment", "type": "短语", "keyWords": ["critical"] },
    { "chinese": "n. 作物；庄稼", "english": "crop", "type": "单词", "keyWords": [] },
    { "chinese": "n. 十字形，交叉，十字架，十字形物（v. 使交叉；横过，越过；勾画；a. 生气的，脾气不好的，易怒的；交叉的）", "english": "cross", "type": "单词", "keyWords": [] },
    { "chinese": "红十字会", "english": "the Red Cross", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "相声", "english": "cross talk", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "划去，注销", "english": "cross...out", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "把...从（名单等上）划掉", "english": "cross...off (..)", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "（对...）生气，发脾气", "english": "be cross with (=be angry with)", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "越野赛跑", "english": "a cross-country race", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "n. 十字路口", "english": "crossroads", "type": "单词", "keyWords": [] },
    { "chinese": "在十字路口；面临抉择的关头；处于（人生的）重要转折点", "english": "at the crossroads", "type": "短语", "keyWords": ["crossroads"] },
    { "chinese": "n. 乌鸦", "english": "crow", "type": "单词", "keyWords": [] },
    { "chinese": "n. 群；人群（v. （使）挤满；挤；群集；a. 拥挤的；满座的）", "english": "crowd/ crowded", "type": "单词", "keyWords": [] },
    { "chinese": "把衣服塞进衣柜中（有不顾整齐之意）", "english": "crowd the clothes into the closet", "type": "短语", "keyWords": ["crowd"] },
    { "chinese": "挤进了我的房间", "english": "crowd into my room", "type": "短语", "keyWords": ["crowd"] },
    { "chinese": "挤满了；拥塞", "english": "be crowded with sb./sth.", "type": "短语", "keyWords": ["crowded"] },
    { "chinese": "n. 王冠；国王；王位（v. 加冕；授...（以荣誉等）(with)）", "english": "crown", "type": "单词", "keyWords": [] },
    { "chinese": "a. 残忍的；残酷的（n. 残忍；残酷行为）", "english": "cruel/ cruelty", "type": "单词", "keyWords": [] },
    { "chinese": "对...残忍", "english": "be cruel to sb.", "type": "短语", "keyWords": ["cruel"] },
    { "chinese": "v. 压碎；压倒；压垮", "english": "crush", "type": "单词", "keyWords": [] },
    { "chinese": "粉碎/碾碎", "english": "crush...(in) to pieces", "type": "短语", "keyWords": ["crush"] },
    { "chinese": "v. 叫喊；哭（n. 哭泣；哭声；叫喊，喊声）", "english": "cry", "type": "单词", "keyWords": [] },
    { "chinese": "哭得伤心极了", "english": "cry one's eyes (heart) out", "type": "短语", "keyWords": ["cry"] },
    { "chinese": "大叫，对...大声反对(against)", "english": "cry out", "type": "短语", "keyWords": ["cry"] },
    { "chinese": "牛奶打泼，哭也无用。", "english": "It is no use crying over spilt milk.", "type": "句子", "keyWords": ["cry"] },
    { "chinese": "n. 水晶；结晶体（a. 清澈透明的；晶体的；a. 完全透明的；[喻]极其明白，十分清楚）", "english": "crystal/ crystal clear", "type": "单词", "keyWords": [] },
    { "chinese": "n. 黄瓜", "english": "cucumber", "type": "单词", "keyWords": [] },
    { "chinese": "泰然自若，极为冷静", "english": "(as) cool as a cucumber", "type": "短语", "keyWords": ["cucumber"] },
    { "chinese": "海参", "english": "sea cucumber", "type": "短语", "keyWords": ["cucumber"] },
    { "chinese": "v. 耕作，培植；培养（n. 耕作，培植；培养；a. 有修养/教养的，文雅的）", "english": "cultivate/ cultivation/ cultivated", "type": "单词", "keyWords": [] },
    { "chinese": "培育新一代", "english": "cultivate a new generation", "type": "短语", "keyWords": ["cultivate"] },
    { "chinese": "培养对艺术的热爱", "english": "cultivate a love of art", "type": "短语", "keyWords": ["cultivate"] },
    { "chinese": "养成分析的习惯", "english": "cultivate the habit of analysis", "type": "短语", "keyWords": ["cultivate"] },
    { "chinese": "a. 文化（上）的（n. 文化；文明；教养；修养；a. 有教养的）", "english": "cultural/ culture/ cultured", "type": "单词", "keyWords": [] },
    { "chinese": "文化冲击", "english": "culture shock", "type": "短语", "keyWords": ["culture"] },
    { "chinese": "有教养的人，文化人", "english": "a cultured man/ a man of culture", "type": "短语", "keyWords": ["cultured", "culture"] },
    { "chinese": "a. 决定性的，关键性的，至关重要的；严酷的；[口]极好的", "english": "crucial", "type": "单词", "keyWords": [] },
    { "chinese": "n. 橱，食橱；柜子；碗柜", "english": "cupboard", "type": "单词", "keyWords": [] },
    { "chinese": "n. 治愈，痊愈；治疗；疗法；有治愈疗效的药(for)（v. 治愈，治疗）", "english": "cure", "type": "单词", "keyWords": [] },
    { "chinese": "治疗某人疾病", "english": "cure sb. of a disease", "type": "短语", "keyWords": ["cure"] },
    { "chinese": "矫正某人不良习惯", "english": "cure a person of a bad habit", "type": "短语", "keyWords": ["cure"] },
    { "chinese": "止咳良药", "english": "the best cure for a cough", "type": "短语", "keyWords": ["cure"] },
    { "chinese": "n. 卷曲，卷缩；（烟等）缭绕，袅袅上升（v. 使卷曲，使成螺旋状；弄卷（毛发））", "english": "curl", "type": "单词", "keyWords": [] },
    { "chinese": "a. 好奇的；稀奇的（n. 好奇心）", "english": "curious/ curiosity", "type": "单词", "keyWords": [] },
    { "chinese": "很想做某事", "english": "be curious to do sth.", "type": "短语", "keyWords": ["curious"] },
    { "chinese": "对...感到好奇", "english": "be curious about", "type": "短语", "keyWords": ["curious"] },
    { "chinese": "出于好奇", "english": "out of curiosity", "type": "短语", "keyWords": ["curiosity"] },
    { "chinese": "好奇地", "english": "with curiosity", "type": "短语", "keyWords": ["curiosity"] },
    { "chinese": "a. 通用的，流行的；现时的；最近的（n. （水、气、电）流；潮流；思潮；ad. 现在；当前）", "english": "current/ currently", "type": "单词", "keyWords": [] },
    { "chinese": "现代英语；日常英语", "english": "current English", "type": "短语", "keyWords": ["current"] },
    { "chinese": "时事", "english": "current events", "type": "短语", "keyWords": ["current"] },
    { "chinese": "活期存款账户", "english": "current account", "type": "短语", "keyWords": ["current"] },
    { "chinese": "直/交流电", "english": "direct/ alternating current", "type": "短语", "keyWords": ["current"] },
    { "chinese": "n. 流通；（一国中实际通用的）货币", "english": "currency", "type": "单词", "keyWords": [] },
    { "chinese": "外汇，外币", "english": "foreign currencies", "type": "短语", "keyWords": ["currency"] },
    { "chinese": "n. 课程", "english": "curriculum", "type": "单词", "keyWords": [] },
    { "chinese": "n. 窗帘；（舞台的）幕", "english": "curtain", "type": "单词", "keyWords": [] },
    { "chinese": "开/闭幕", "english": "rise/ drop the curtain", "type": "短语", "keyWords": ["curtain"] },
    { "chinese": "上窗帘（开/闭幕）拉幕", "english": "draw the curtain", "type": "短语", "keyWords": ["curtain"] },
    { "chinese": "n. 曲线；弧线；弯曲；曲线状物；弯曲部分（v. 弯，使弯曲；vi. 成曲弯形）", "english": "curve", "type": "单词", "keyWords": [] },
    { "chinese": "n. 垫子；气垫；软垫；衬垫", "english": "cushion", "type": "单词", "keyWords": [] },
    { "chinese": "n. 习惯；风俗；惯例；（pl.）海关（a. 习惯性的；照惯例的）", "english": "custom/ customary", "type": "单词", "keyWords": [] },
    { "chinese": "海关", "english": "the Customs", "type": "短语", "keyWords": ["custom"] },
    { "chinese": "关税", "english": "customs duties", "type": "短语", "keyWords": ["custom"] },
    { "chinese": "n. 顾客；主顾", "english": "customer", "type": "单词", "keyWords": [] },
    { "chinese": "v. 切，割，削（n. 切，割；裂口；削减，删节）", "english": "cut", "type": "单词", "keyWords": [] },
    { "chinese": "削减预算/我们的开支", "english": "cut a budget/ our expenses", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "减半价", "english": "cut the price by half", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "切碎；使难过", "english": "cut..up", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "穿过田野", "english": "cut across a field", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "抄近路走过；刺穿", "english": "cut through", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "砍掉老树枝", "english": "cut away the old branches", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "砍倒（树木）；裁减（经费）(on)；减少(on)", "english": "cut down (on)", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "你抽烟太多，应该减少。", "english": "You smoke too much - you should try to cut down.", "type": "句子", "keyWords": ["cut"] },
    { "chinese": "插话；插入（进入一排人或事物）", "english": "cut in", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "删去；截断；中断（电话、讲话、供应等）；隔离（从其他物体中分离出来）", "english": "cut out", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "抄近路", "english": "take a short cut", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "减薪", "english": "a cut in salary", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "恶语伤人胜过利剑", "english": "Words cut more than swords.", "type": "句子", "keyWords": ["cut"] },
    { "chinese": "a. 漂亮的；娇小可爱的；精巧的", "english": "cute", "type": "单词", "keyWords": [] },
    { "chinese": "n. （报纸等的）剪辑；切下的东西（a. 像刀割似的；刺骨的；尖酸刻薄的）", "english": "cutting", "type": "单词", "keyWords": [] },
    { "chinese": "刺骨的寒风", "english": "a cutting wind", "type": "短语", "keyWords": ["cutting"] },
    { "chinese": "尖刻的话", "english": "a cutting remark", "type": "短语", "keyWords": ["cutting"] },
    { "chinese": "n. 周期；循环；自行车（v. 循环；使轮转；vi. 循环；轮转；骑自行车）", "english": "cycle", "type": "单词", "keyWords": [] },
    { "chinese": "四季的周而复始", "english": "the cycle of the seasons", "type": "短语", "keyWords": ["cycle"] },
    { "chinese": "生命周期", "english": "a life cycle", "type": "短语", "keyWords": ["cycle"] },
    { "chinese": "n. 骑自行车的人", "english": "cyclist", "type": "单词", "keyWords": [] },
    { "chinese": "n. 骑脚踏车兜风，骑脚踏车消遣", "english": "cycling", "type": "单词", "keyWords": [] },
    { "chinese": "[口]爸爸（n.）", "english": "dad/ daddy", "type": "单词", "keyWords": [] },
    { "chinese": "每日的；日常的（a.）；每天（ad.）；日报（n.）", "english": "daily", "type": "单词", "keyWords": [] },
    { "chinese": "在日常生活中", "english": "in our daily life", "type": "短语", "keyWords": ["daily"] },
    { "chinese": "《人民日报》", "english": "People's Daily", "type": "短语", "keyWords": ["daily"] },
    { "chinese": "牛奶坊/公司；乳品店（n.）；牛奶（制品）的；乳品的（a.）", "english": "dairy", "type": "单词", "keyWords": [] },
    { "chinese": "水闸；坝（n.）；筑坝（vt.）", "english": "dam", "type": "单词", "keyWords": [] },
    { "chinese": "损坏；损害；[口]伤害，毁坏（v.）；毁坏；赔偿费（n.）", "english": "damage", "type": "单词", "keyWords": [] },
    { "chinese": "毁坏某人的名声", "english": "damage one's name", "type": "短语", "keyWords": ["damage"] },
    { "chinese": "给...造成很大损害", "english": "do/ cause great damage to...", "type": "短语", "keyWords": ["damage"] },
    { "chinese": "潮湿（n.）；潮湿的（a.）；使潮湿；给...泼冷水（vt.）", "english": "damp", "type": "单词", "keyWords": [] },
    { "chinese": "跳舞，舞蹈；跳动；（旗等）飘扬（n.）；跳舞（v.）；跳动的（a.）；跳舞（n.）", "english": "dance/ dancing", "type": "单词", "keyWords": [] },
    { "chinese": "树叶迎风飘舞。", "english": "The leaves were dancing in the wind.", "type": "句子", "keyWords": ["dance"] },
    { "chinese": "危险；危险物（n.）；危险的；不安全的（a.）；危险地（ad.）", "english": "danger/ dangerous/ dangerously", "type": "单词", "keyWords": [] },
    { "chinese": "在...危险之中", "english": "in danger", "type": "短语", "keyWords": ["danger"] },
    { "chinese": "脱离危险", "english": "out of danger", "type": "短语", "keyWords": ["danger"] },
    { "chinese": "敢；胆敢；竟敢（v.）；大胆的（a.）", "english": "dare/ daring", "type": "单词", "keyWords": [] },
    { "chinese": "她不敢做那件事。", "english": "She dared not do it.", "type": "句子", "keyWords": ["dare"] },
    { "chinese": "他竟敢攻击多少世纪以来人们所持有的信仰和观念！", "english": "How dared he attack the beliefs and ideas which had been held for centuries!", "type": "句子", "keyWords": ["dare"] },
    { "chinese": "我想，大概，可能，或许...", "english": "I dare say..", "type": "短语", "keyWords": ["dare"] },
    { "chinese": "一位大胆的工人/一件大胆的事", "english": "a daring workman/ thing", "type": "短语", "keyWords": ["daring"] },
    { "chinese": "黑暗的；暗的（a.）；夜，黄昏；黑暗，暗处（n.）；（使）变暗，（使）变黑（v.）", "english": "dark/ darken", "type": "单词", "keyWords": [] },
    { "chinese": "坐在黑暗里", "english": "sit in the dark", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "黄昏时", "english": "at dark", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "黄昏前（后）", "english": "before/ after dark", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "一匹黑马；爆出冷门", "english": "a dark horse", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "对...全然不知", "english": "be in the dark about/ as to..", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "我对他们的计划一无所知。", "english": "They kept me in the dark about their plans.", "type": "句子", "keyWords": ["dark"] },
    { "chinese": "黑暗；漆黑；阴暗（n.）", "english": "darkness", "type": "单词", "keyWords": [] },
    { "chinese": "处于黑暗中", "english": "in darkness", "type": "短语", "keyWords": ["darkness"] },
    { "chinese": "心爱的人；宠物；[口]亲爱的（n.）；心爱的；宠爱的；亲爱的（a.）", "english": "darling", "type": "单词", "keyWords": [] },
    { "chinese": "短跑；冲撞；猛冲；[体]短跑；破折号；草的一笔（或一画）（n.）；冲；冲撞（v.）", "english": "dash", "type": "单词", "keyWords": [] },
    { "chinese": "猛冲到出口", "english": "make a dash for the exit", "type": "短语", "keyWords": ["dash"] },
    { "chinese": "论据；数据，资料（n.）；数据库（n.）", "english": "data/ database", "type": "单词", "keyWords": [] },
    { "chinese": "日期；（男女间）约会（n.）；约会；定日期；注...的日期；追溯（v./vi.）", "english": "date", "type": "单词", "keyWords": [] },
    { "chinese": "和某人有个约会", "english": "have a date with", "type": "短语", "keyWords": ["date"] },
    { "chinese": "和某人约会", "english": "date sb./ make a date with sb.", "type": "短语", "keyWords": ["date"] },
    { "chinese": "直到最近的，新式的，现代的", "english": "up to date", "type": "短语", "keyWords": ["date"] },
    { "chinese": "不合时宜的；过时的", "english": "out of date", "type": "短语", "keyWords": ["date"] },
    { "chinese": "追溯到", "english": "date back to/ date from/ go back to", "type": "短语", "keyWords": ["date"] },
    { "chinese": "女儿（n.）；儿媳妇（n.）", "english": "daughter/ daughter-in-law", "type": "单词", "keyWords": [] },
    { "chinese": "黎明，天亮，拂晓（n.）；破晓；被理解，被领悟（on sb.）（v.）", "english": "dawn", "type": "单词", "keyWords": [] },
    { "chinese": "拂晓时", "english": "at dawn", "type": "短语", "keyWords": ["dawn"] },
    { "chinese": "胜利的曙光", "english": "the dawn of victory", "type": "短语", "keyWords": ["dawn"] },
    { "chinese": "文明的开端", "english": "the dawn of civilization", "type": "短语", "keyWords": ["dawn"] },
    { "chinese": "后来我们才恍然大悟，原来从来没有补给物资顺这条路运送下来过。", "english": "Only gradually did it dawn on us that no supplies ever came down the road.", "type": "句子", "keyWords": ["dawn"] },
    { "chinese": "一天，日子；白天；节日，重要日子（n.）", "english": "day", "type": "单词", "keyWords": [] },
    { "chinese": "将来", "english": "in the days to come", "type": "短语", "keyWords": ["day"] },
    { "chinese": "至今", "english": "to this day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "当代的", "english": "of the day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "日夜不停地", "english": "day and night", "type": "短语", "keyWords": ["day"] },
    { "chinese": "（日后）总有一天", "english": "some day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "当时，那时候", "english": "in those days", "type": "短语", "keyWords": ["day"] },
    { "chinese": "不再干了；停业（某活动）", "english": "call it a day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "逐日", "english": "day by day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "按日计", "english": "by the day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "整天", "english": "all day long", "type": "短语", "keyWords": ["day"] },
    { "chinese": "每隔一天", "english": "every other day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "每隔几天", "english": "every few days", "type": "短语", "keyWords": ["day"] },
    { "chinese": "每隔一天，每两天", "english": "every two days", "type": "短语", "keyWords": ["day"] },
    { "chinese": "休假一天", "english": "have a day off", "type": "短语", "keyWords": ["day"] },
    { "chinese": "美好的往日，当年", "english": "good old days", "type": "短语", "keyWords": ["day"] },
    { "chinese": "前些天", "english": "the other day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "日复一日", "english": "day after day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "凡人皆有得意之日。/三十年河东，三十年河西。", "english": "Every dog has its day.", "type": "句子", "keyWords": ["day"] },
    { "chinese": "白天；日光（n.）", "english": "daylight", "type": "单词", "keyWords": [] },
    { "chinese": "夏令时间", "english": "daylight-saving time", "type": "短语", "keyWords": ["daylight"] },
    { "chinese": "黎明的时候", "english": "at daylight", "type": "短语", "keyWords": ["daylight"] },
    { "chinese": "白天，白昼（n.）；白天的（a.）", "english": "daytime", "type": "单词", "keyWords": [] },
    { "chinese": "在白天", "english": "in the daytime", "type": "短语", "keyWords": ["daytime"] },
    { "chinese": "表示“去除；相反；贬；离开”", "english": "de-", "type": "前缀", "keyWords": [] },
    { "chinese": "除霜", "english": "defrost", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "非国有化", "english": "denationalize", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "贬值", "english": "devalue", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "使变形", "english": "deform", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "降级", "english": "degrade", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "解码", "english": "decode", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "死（亡）的；死一般的（a.）；极其（ad.）", "english": "dead", "type": "单词", "keyWords": [] },
    { "chinese": "他（喝得）烂醉。", "english": "He's dead drunk.", "type": "句子", "keyWords": ["dead"] },
    { "chinese": "致命的；死气沉沉的（a.）", "english": "deadly", "type": "单词", "keyWords": [] },
    { "chinese": "致命的武器", "english": "deadly weapons", "type": "短语", "keyWords": ["deadly"] },
    { "chinese": "最后期限；截止时间（n.）", "english": "deadline", "type": "单词", "keyWords": [] },
    { "chinese": "错过..的最后期限", "english": "miss the deadline for sth.", "type": "短语", "keyWords": ["deadline"] },
    { "chinese": "聋的（a.）；使聋（vt.）；变聋（vi.）；震耳欲聋的（a.）", "english": "deaf/ deafen/ deafening", "type": "单词", "keyWords": [] }
];
