const qgl73_80 = [
    { "chinese": "不听劝告", "english": "be deaf to advice", "type": "短语", "keyWords": ["deaf"] },
    { "chinese": "不肯倾听别人意见的人是最聋的人。", "english": "None (are) so deaf as those who won't hear.", "type": "句子", "keyWords": ["deaf"] },
    { "chinese": "置若罔闻", "english": "turn a deaf ear to...", "type": "短语", "keyWords": ["deaf"] },
    { "chinese": "n. 交易；数量；协议", "english": "deal", "type": "单词", "keyWords": [] },
    { "chinese": "v. 发牌", "english": "deal the cards", "type": "短语", "keyWords": ["deal"] },
    { "chinese": "处理；涉及；论及；对付", "english": "deal with", "type": "短语", "keyWords": ["deal"] },
    { "chinese": "就这么办，一言为定", "english": "That's/It's a deal", "type": "句子", "keyWords": ["deal"] },
    { "chinese": "大量（+不可数名词）", "english": "a good/great deal (of)", "type": "短语", "keyWords": ["deal"] },
    { "chinese": "a. 亲爱的；昂贵的；interj. 天啊！天哪！", "english": "dear", "type": "单词", "keyWords": [] },
    { "chinese": "n. 死；死亡；伤亡人数", "english": "death", "type": "单词", "keyWords": [] },
    { "chinese": "决一死战；一决雌雄", "english": "fight to the death", "type": "短语", "keyWords": ["death"] },
    { "chinese": "射死/饿死某人", "english": "shoot/starve sb. to death", "type": "短语", "keyWords": ["death"] },
    { "chinese": "导致100人死亡", "english": "cause 100 deaths", "type": "短语", "keyWords": ["death"] },
    { "chinese": "v. /n. 辩论；争论", "english": "debate", "type": "单词", "keyWords": [] },
    { "chinese": "辩论；争论", "english": "debate on/upon sth.", "type": "短语", "keyWords": ["debate"] },
    { "chinese": "n. 欠债，债务；人情债；负债状态", "english": "debt", "type": "单词", "keyWords": [] },
    { "chinese": "偿付债款", "english": "pay one's debts", "type": "短语", "keyWords": ["debt"] },
    { "chinese": "还清债务", "english": "pay off one's debts", "type": "短语", "keyWords": ["debt"] },
    { "chinese": "欠债（短暂性动作）", "english": "run/get into debt", "type": "短语", "keyWords": ["debt"] },
    { "chinese": "欠债（可接时间段状语）", "english": "be in debt", "type": "短语", "keyWords": ["debt"] },
    { "chinese": "n. 十年", "english": "decade", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使腐烂/朽，使蛀蚀；vi. 腐烂，蛀蚀；衰减/败/退；n. 腐烂，蛀蚀", "english": "decay", "type": "单词", "keyWords": [] },
    { "chinese": "v. 欺骗，蒙骗", "english": "deceive", "type": "单词", "keyWords": [] },
    { "chinese": "n. 欺骗，蒙骗", "english": "deception", "type": "单词", "keyWords": [] },
    { "chinese": "a. 欺骗性的", "english": "deceptive", "type": "单词", "keyWords": [] },
    { "chinese": "骗某人买某物", "english": "deceive sb. into buying...", "type": "短语", "keyWords": ["deceive"] },
    { "chinese": "a. 得体的；适当的；正派的；过得去的，尚可的", "english": "decent", "type": "单词", "keyWords": [] },
    { "chinese": "v. 决定；判决，裁定，判定", "english": "decide", "type": "单词", "keyWords": [] },
    { "chinese": "a. 明确的；肯定的；果断的", "english": "decided", "type": "单词", "keyWords": [] },
    { "chinese": "明显的变化", "english": "a decided change", "type": "短语", "keyWords": ["decided"] },
    { "chinese": "对某事作出决定", "english": "decide on (sth.)", "type": "短语", "keyWords": ["decide"] },
    { "chinese": "n. 决定；判决；决心；决断；a. 有决定性的", "english": "decision/decisive", "type": "单词", "keyWords": [] },
    { "chinese": "作出决定", "english": "come to/arrive at/reach a decision", "type": "短语", "keyWords": ["decision"] },
    { "chinese": "由...来决定（某事）", "english": "leave... to the decision of", "type": "短语", "keyWords": ["decision"] },
    { "chinese": "决定下来，作出决定；下决心", "english": "make a decision", "type": "短语", "keyWords": ["decision"] },
    { "chinese": "有决断力的人", "english": "a man of decision", "type": "短语", "keyWords": ["decision"] },
    { "chinese": "决定性的一票", "english": "the decisive vote", "type": "短语", "keyWords": ["decisive"] },
    { "chinese": "决战", "english": "a decisive battle", "type": "短语", "keyWords": ["decisive"] },
    { "chinese": "n. 甲板，舱面", "english": "deck", "type": "单词", "keyWords": [] },
    { "chinese": "在上/下甲板上", "english": "on the upper/lower deck", "type": "短语", "keyWords": ["deck"] },
    { "chinese": "v. 断言；宣称；宣布；宣告；声明；（向海关）申报", "english": "declare", "type": "单词", "keyWords": [] },
    { "chinese": "n. 宣告，宣布", "english": "declaration", "type": "单词", "keyWords": [] },
    { "chinese": "宣布某人无罪", "english": "declare sb. (to be) innocent", "type": "短语", "keyWords": ["declare"] },
    { "chinese": "你有东西要申报吗？（指应纳税的东西）", "english": "Have you anything to declare?", "type": "句子", "keyWords": ["declare"] },
    { "chinese": "宣布和平", "english": "declare peace", "type": "短语", "keyWords": ["declare"] },
    { "chinese": "宣布他当选", "english": "declare him elected", "type": "短语", "keyWords": ["declare"] },
    { "chinese": "（美）独立宣言（1776年7月4日）", "english": "the Declaration of Independence", "type": "短语", "keyWords": ["declaration"] },
    { "chinese": "向...宣战", "english": "declare war on...", "type": "短语", "keyWords": ["declare"] },
    { "chinese": "联合声明", "english": "Joint declaration", "type": "短语", "keyWords": ["declaration"] },
    { "chinese": "n. 下降；减少；衰落；v. /vi. 婉言拒绝；下降；衰落", "english": "decline", "type": "单词", "keyWords": [] },
    { "chinese": "在下跌/上升", "english": "on the decline (decrease)/increase", "type": "短语", "keyWords": ["decline"] },
    { "chinese": "物价下跌", "english": "a decline in price", "type": "短语", "keyWords": ["decline"] },
    { "chinese": "拒绝回答", "english": "decline to answer", "type": "短语", "keyWords": ["decline"] },
    { "chinese": "拒绝一个提议", "english": "decline an offer", "type": "短语", "keyWords": ["decline"] },
    { "chinese": "v. 装饰；装潢；n. 装饰；装潢；装饰品；a. 装饰的；装潢的", "english": "decorate/decoration/decorative", "type": "单词", "keyWords": [] },
    { "chinese": "装饰美术", "english": "decorative art", "type": "短语", "keyWords": ["decorative"] },
    { "chinese": "v. /vi. /n. 减少；减小", "english": "decrease", "type": "单词", "keyWords": [] },
    { "chinese": "数目减少", "english": "decrease in number/a decrease in number", "type": "短语", "keyWords": ["decrease"] },
    { "chinese": "n. 事情；行为", "english": "deed", "type": "单词", "keyWords": [] },
    { "chinese": "做好事", "english": "do a good deed", "type": "短语", "keyWords": ["deed"] },
    { "chinese": "在行动上", "english": "in deed", "type": "短语", "keyWords": ["deed"] },
    { "chinese": "a. 深的；埋头于...中，热衷于（in）；ad. 深深地；n. 深处", "english": "deep", "type": "单词", "keyWords": [] },
    { "chinese": "低沉的声音", "english": "a deep voice", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "挖得深", "english": "dig deep", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "深夜", "english": "deep/far into the night", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "在沉思中", "english": "in deep thought", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "埋头苦读", "english": "be deep in a book", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "熟睡", "english": "be in a deep sleep = be deep in sleep", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "工作直至深夜", "english": "work deep into the night", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "在齐膝深的水里", "english": "in knee-deep water", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "淹死在海里", "english": "drown in the deep", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "走入丛林深处", "english": "go deep into the jungle", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "ad. 深深地；强烈地；深刻地", "english": "deeply", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使...深；加深，深化", "english": "deepen", "type": "单词", "keyWords": [] },
    { "chinese": "n. 纵深；深（度）；深处，深渊", "english": "depth", "type": "单词", "keyWords": [] },
    { "chinese": "潜入水下30英尺处", "english": "dive to a depth of 30 feet", "type": "短语", "keyWords": ["depth"] },
    { "chinese": "密林深处", "english": "in the depths of the forest", "type": "短语", "keyWords": ["depth"] },
    { "chinese": "n. 鹿（单复同）", "english": "deer", "type": "单词", "keyWords": [] },
    { "chinese": "v. 击败；n. 击败；失败", "english": "defeat", "type": "单词", "keyWords": [] },
    { "chinese": "以失败告终", "english": "end in defeat", "type": "短语", "keyWords": ["defeat"] },
    { "chinese": "v. 防御；保卫；守卫；辩护；n. 被告；a. 辩护的", "english": "defend/defendant", "type": "单词", "keyWords": [] },
    { "chinese": "保卫祖国", "english": "defend one's country", "type": "短语", "keyWords": ["defend"] },
    { "chinese": "防御", "english": "defend against", "type": "短语", "keyWords": ["defend"] },
    { "chinese": "自卫", "english": "defend oneself", "type": "短语", "keyWords": ["defend"] },
    { "chinese": "（球赛中）守门", "english": "defend the goal", "type": "短语", "keyWords": ["defend"] },
    { "chinese": "n. 防御；保卫；辩护；a. 防御用的，自卫的", "english": "defence/defensive（英）/defense（美）", "type": "单词", "keyWords": [] },
    { "chinese": "保卫；捍卫；为...辩护", "english": "in defence of", "type": "短语", "keyWords": ["defence"] },
    { "chinese": "v. 给...下定义；使明确；规定（义务、权利）；n. 定义；限定", "english": "define/definition", "type": "单词", "keyWords": [] },
    { "chinese": "a. 明确的；确定的；一定的", "english": "definite", "type": "单词", "keyWords": [] },
    { "chinese": "明确的答复", "english": "a definite answer", "type": "短语", "keyWords": ["definite"] },
    { "chinese": "n. 学位；学衔；度数；程度；等级；[数学]次；幂；[音乐]阶，度", "english": "degree", "type": "单词", "keyWords": [] },
    { "chinese": "到什么程度", "english": "to what degree", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "三度烧伤", "english": "a third-degree burn", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "渐渐", "english": "by degrees", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "取得学位", "english": "take a degree", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "在一定程度上，有几分", "english": "to a certain degree/extent", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "（摄氏）零度以上/下", "english": "above/below zero degrees centigrade/Celsius", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "接受文学学士学位", "english": "receive the Bachelor of Arts degree", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "v. 推迟；耽搁；使延期；vi. 耽搁；延误；n. 推迟；延期；耽搁", "english": "delay", "type": "单词", "keyWords": [] },
    { "chinese": "立刻", "english": "without delay", "type": "短语", "keyWords": ["delay"] },
    { "chinese": "耽搁/延误两天", "english": "a delay of two days", "type": "短语", "keyWords": ["delay"] },
    { "chinese": "推迟（做）某事", "english": "delay (doing) sth.", "type": "短语", "keyWords": ["delay"] },
    { "chinese": "这次火车事故使这封信耽搁了三天。", "english": "The letter was delayed three days by the train accident.", "type": "句子", "keyWords": ["delay"] },
    { "chinese": "我们要把会期延迟两周。", "english": "We'll delay the meeting for two weeks.", "type": "句子", "keyWords": ["delay"] },
    { "chinese": "n. 代表；n. 代表团；U. 授权，委托", "english": "delegate/delegation", "type": "单词", "keyWords": [] },
    { "chinese": "赴会的代表", "english": "a delegate to a conference", "type": "短语", "keyWords": ["delegate"] },
    { "chinese": "a. 深思熟虑的；蓄意的；ad. 蓄意地（近on purpose）", "english": "deliberate/deliberately", "type": "单词", "keyWords": [] },
    { "chinese": "v. 擦去，删除；n. 删除；删除部分", "english": "delete/deletion", "type": "单词", "keyWords": [] },
    { "chinese": "a. 纤细的；雅致的；微妙的；精巧的，精致的；脆弱的，易碎的；n. 精美；雅致；纤细；脆弱", "english": "delicate/delicacy", "type": "单词", "keyWords": [] },
    { "chinese": "a. 美味的；可口的", "english": "delicious", "type": "单词", "keyWords": [] },
    { "chinese": "n. 快乐（的事）；高兴；v. 使高兴；使愉快；a. 让人高兴的；ad. 欣喜地，快乐地", "english": "delight/delightful/delightfully", "type": "单词", "keyWords": [] },
    { "chinese": "对...感到高兴", "english": "be delighted at sth.", "type": "短语", "keyWords": ["delight"] },
    { "chinese": "高兴做某事", "english": "be delighted to do sth.", "type": "短语", "keyWords": ["delight"] },
    { "chinese": "喜欢做某事", "english": "delight in doing sth.", "type": "短语", "keyWords": ["delight"] },
    { "chinese": "他喜爱远距离散步。", "english": "He delights in taking long walks.", "type": "句子", "keyWords": ["delight"] },
    { "chinese": "让某人很高兴的是", "english": "much to one's delight", "type": "短语", "keyWords": ["delight"] },
    { "chinese": "以...为乐；喜爱（近take/have (an) interest in sth.）", "english": "take/have/find (a) delight in sth.", "type": "短语", "keyWords": ["delight"] },
    { "chinese": "v. 投递，分送；发表；给予（打击等）；n. 投递，分送；传送", "english": "deliver/delivery", "type": "单词", "keyWords": [] },
    { "chinese": "把...交给", "english": "deliver sth. to...", "type": "短语", "keyWords": ["deliver"] },
    { "chinese": "传话/讲话", "english": "deliver a message/a speech", "type": "短语", "keyWords": ["deliver"] },
    { "chinese": "v. 要求；需要；要求知道，查问；n. 要求；需要", "english": "demand", "type": "单词", "keyWords": [] },
    { "chinese": "向某人要求某物（近require, request, expect, ask）", "english": "demand sth. of sb.", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "要求（一般不用demand sb. to do sth.）", "english": "demand that ...(should)...", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "要求做某事", "english": "demand to do sth.", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "警察要求他说出姓名。", "english": "The policeman demanded to know his name.", "type": "句子", "keyWords": ["demand"] },
    { "chinese": "供求规律", "english": "the law of supply and demand", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "需求量很大；许多人都需要", "english": "in (great) demand", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "满足某人的需要或要求", "english": "meet/satisfy one's demands/needs", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "这种书需求量很大。", "english": "There is a great demand/need for such books.", "type": "句子", "keyWords": ["demand"] },
    { "chinese": "a. 费事/力的；要仔细对待的；过分要求的，要求高的", "english": "demanding", "type": "单词", "keyWords": [] },
    { "chinese": "那是一件劳神的工作。", "english": "It's demanding work.", "type": "句子", "keyWords": ["demanding"] },
    { "chinese": "有过分要求的孩子", "english": "a demanding child", "type": "短语", "keyWords": ["demanding"] },
    { "chinese": "n. 民主；a. 民主的，民主政体的", "english": "democracy/democratic", "type": "单词", "keyWords": [] },
    { "chinese": "v. 示范，举例/用实验说明；证明，论证；显示；vi. 游行示威；n. 示范；实证", "english": "demonstrate/demonstration", "type": "单词", "keyWords": [] },
    { "chinese": "售货员演示了如何使用这种洗衣机。", "english": "The salesman demonstrated (~ showed) how to use the washing-machine.", "type": "句子", "keyWords": ["demonstrate"] },
    { "chinese": "a. 稠密的；密集的；ad. 稠密地；n. 密度；浓密", "english": "dense/densely/density", "type": "单词", "keyWords": [] },
    { "chinese": "密林", "english": "a dense forest", "type": "短语", "keyWords": ["dense"] },
    { "chinese": "人口密度", "english": "the density of the population", "type": "短语", "keyWords": ["density"] },
    { "chinese": "n. 牙医；a. 与牙有关的", "english": "dentist/dental", "type": "单词", "keyWords": [] },
    { "chinese": "在牙科诊所", "english": "at the dentist's", "type": "短语", "keyWords": ["dentist"] },
    { "chinese": "v. 否认；拒绝（允许、给予、接受或相信）（可接双宾）；n. 否认，否定；谢绝，拒绝", "english": "deny/denial", "type": "单词", "keyWords": [] },
    { "chinese": "不给犯人食物和水", "english": "deny the prisoner food or water", "type": "短语", "keyWords": ["deny"] },
    { "chinese": "否认做过某事", "english": "deny doing sth.", "type": "短语", "keyWords": ["deny"] },
    { "chinese": "不可否认的是...（书面语）", "english": "There's no denying the fact that...", "type": "句子", "keyWords": ["deny"] },
    { "chinese": "...是不可否认的", "english": "It cannot be denied that...", "type": "句子", "keyWords": ["deny"] },
    { "chinese": "vi. 离开；出发（正式用语）；n. 离开；背离", "english": "depart/departure", "type": "单词", "keyWords": [] },
    { "chinese": "去某地（比leave for a place正式）", "english": "depart for somewhere", "type": "短语", "keyWords": ["depart"] },
    { "chinese": "飞机的离港与进港", "english": "departures and arrivals of planes", "type": "短语", "keyWords": ["departure"] },
    { "chinese": "n. 部门；局，处，科，系，学部", "english": "department", "type": "单词", "keyWords": [] },
    { "chinese": "人事部门", "english": "the personnel department", "type": "短语", "keyWords": ["department"] },
    { "chinese": "（州）教育厅/部；教育系", "english": "the education department", "type": "短语", "keyWords": ["department"] },
    { "chinese": "物理系", "english": "the physics department", "type": "短语", "keyWords": ["department"] },
    { "chinese": "百货商店", "english": "a department store", "type": "短语", "keyWords": ["department"] },
    { "chinese": "vi. 视...而定；依靠；依赖；a. 可靠的；依靠的，依赖的；n. 依靠；独立，自主", "english": "depend/dependable/dependent/dependence/independence", "type": "单词", "keyWords": [] },
    { "chinese": "依靠/依赖/信赖某人做某事", "english": "depend on/upon sb. + to do sth./for sth.", "type": "短语", "keyWords": ["depend"] },
    { "chinese": "孩子们靠父母提供衣食。", "english": "Children depend on their parents for food and clothing./Children depend on their parents to provide them with food and clothing.", "type": "句子", "keyWords": ["depend"] },
    { "chinese": "看情况吧。", "english": "It all depends.", "type": "句子", "keyWords": ["depend"] },
    { "chinese": "依靠；依赖", "english": "be dependent on sth. or sb.", "type": "短语", "keyWords": ["dependent"] },
    { "chinese": "不依靠，不依赖", "english": "be independent of sth. or sb.", "type": "短语", "keyWords": ["independent"] },
    { "chinese": "v. /vi. （使）沉淀；付（定金）；存放；储蓄；n. 沉积（物）；存款；定金", "english": "deposit", "type": "单词", "keyWords": [] },
    { "chinese": "有价值的矿藏", "english": "valuable mineral deposits", "type": "短语", "keyWords": ["deposit"] },
    { "chinese": "活期存款", "english": "current deposit", "type": "短语", "keyWords": ["deposit"] },
    { "chinese": "她把钱存在银行里。", "english": "She deposited her money in the bank.", "type": "句子", "keyWords": ["deposit"] },
    { "chinese": "v. 使沮丧，使消沉，使抑郁；使不景气；按下，压下；n. 沮丧；抑郁；萧条；a. 感到/使人沮丧的", "english": "depress/depression/depressed/depressing", "type": "单词", "keyWords": [] },
    { "chinese": "大萧条", "english": "the Great Depression", "type": "短语", "keyWords": ["depression"] },
    { "chinese": "vi. 走（落、传）下来；v. 从...下来", "english": "descend", "type": "单词", "keyWords": [] },
    { "chinese": "下山", "english": "descend the mountain", "type": "短语", "keyWords": ["descend"] },
    { "chinese": "v. 描述；叙述；形容；n. 描述，形容；a. 描述性的", "english": "describe/description/descriptive", "type": "单词", "keyWords": [] },
    { "chinese": "把...描述成；把...说成是（称作）（近refer to, label）", "english": "describe... as（可接形容词）", "type": "短语", "keyWords": ["describe"] },
    { "chinese": "描述；形容", "english": "give a description of = describe", "type": "短语", "keyWords": ["describe/description"] },
    { "chinese": "无法形容", "english": "beyond description", "type": "短语", "keyWords": ["description"] },
    { "chinese": "n. 沙漠；荒芜之地，荒漠；a. 沙漠的；不毛的，荒凉的", "english": "desert¹", "type": "单词", "keyWords": [] },
    { "chinese": "文化荒原", "english": "a cultural desert", "type": "短语", "keyWords": ["desert¹"] },
    { "chinese": "荒凉的岛", "english": "a desert island", "type": "短语", "keyWords": ["desert¹"] },
    { "chinese": "v. 离开；抛弃，遗弃，离弃（尤指不负责任或义务而远离）；a. 荒废的，为人所弃的", "english": "desert²/deserted", "type": "单词", "keyWords": [] },
    { "chinese": "冷寂的大街", "english": "deserted street", "type": "短语", "keyWords": ["deserted"] },
    { "chinese": "她抛弃了急需帮助的朋友。", "english": "She deserted her friend in a time of need.", "type": "句子", "keyWords": ["desert²"] },
    { "chinese": "街上行人绝迹。", "english": "The streets were deserted.", "type": "句子", "keyWords": ["deserted"] },
    { "chinese": "v. 应该得到；应受；值得", "english": "deserve", "type": "单词", "keyWords": [] },
    { "chinese": "应受处分", "english": "deserve a punishment/deserve to be punished/deserve punishing", "type": "短语", "keyWords": ["deserve"] },
    { "chinese": "这是你应得的。/你罪有应得。/你活该。（意义褒贬根据上下文）", "english": "You deserve it.", "type": "句子", "keyWords": ["deserve"] },
    { "chinese": "v. 设计；n. 设计；图案；n. 设计师，制图师", "english": "design/designer", "type": "单词", "keyWords": [] },
    { "chinese": "v. 愿望；渴望；请求；n. 愿望；请求；渴望；a. 渴望的，想得到的", "english": "desire/desired", "type": "单词", "keyWords": [] },
    { "chinese": "渴望得到和平", "english": "desire peace = have a desire for peace", "type": "短语", "keyWords": ["desire"] },
    { "chinese": "急切地想做某事", "english": "have a strong desire to do sth.", "type": "短语", "keyWords": ["desire"] },
    { "chinese": "很想做某事", "english": "desire to do", "type": "短语", "keyWords": ["desire"] },
    { "chinese": "想要某人做某事", "english": "desire sb. to do sth.", "type": "短语", "keyWords": ["desire"] },
    { "chinese": "她希望他立刻去。（虚拟语气）", "english": "She desired that he (should) go at once.", "type": "句子", "keyWords": ["desire"] },
    { "chinese": "产生期望的结果/达到预期的效果", "english": "produce/achieve the desired results", "type": "短语", "keyWords": ["desired"] },
    { "chinese": "n. 书桌；办公桌", "english": "desk", "type": "单词", "keyWords": [] },
    { "chinese": "坐在桌旁", "english": "sit at one's desk", "type": "短语", "keyWords": ["desk"] },
    { "chinese": "adj. （电脑等）台式的；n. 桌面；台式电脑；（计）桌面", "english": "desktop", "type": "单词", "keyWords": [] },
    { "chinese": "n. 绝望；沮丧（强调完全没有希望，暗示“无能的，听任摆布”的意思）", "english": "despair", "type": "单词", "keyWords": [] },
    { "chinese": "他绝望地放弃尝试。", "english": "He gave up the attempt in despair.", "type": "句子", "keyWords": ["despair"] },
    { "chinese": "a. 不顾一切的，绝望的；n. 绝望", "english": "desperate/desperation", "type": "单词", "keyWords": [] },
    { "chinese": "绝望的呼救声", "english": "a desperate cry for help", "type": "短语", "keyWords": ["desperate"] },
    { "chinese": "拼死；不顾死活地", "english": "in desperation", "type": "短语", "keyWords": ["desperation"] },
    { "chinese": "prep. 不管，尽管，不论（近in spite of，注意后面不直接跟that从句）", "english": "despite", "type": "单词", "keyWords": [] },
    { "chinese": "n. 餐后甜点；甜点心", "english": "dessert", "type": "单词", "keyWords": [] },
    { "chinese": "n. 目的地，终点；目标，目的", "english": "destination", "type": "单词", "keyWords": [] },
    { "chinese": "主要的游客目的地", "english": "a major tourist destination", "type": "短语", "keyWords": ["destination"] },
    { "chinese": "v. 破坏；拆毁；消灭（指剧烈地破坏，使之不存在或使之失去效能）；n. 驱逐舰", "english": "destroy/destroyer", "type": "单词", "keyWords": [] },
    { "chinese": "n. 破坏；毁灭；a. 破坏（性）的；毁灭性的", "english": "destruction/destructive", "type": "单词", "keyWords": [] },
    { "chinese": "n. 细节；v. 详述；a. 详细的", "english": "detail/detailed", "type": "单词", "keyWords": [] },
    { "chinese": "详细地", "english": "in detail", "type": "短语", "keyWords": ["detail"] },
    { "chinese": "详述，逐一细说", "english": "go into detail (about sth.)", "type": "短语", "keyWords": ["detail"] },
    { "chinese": "a. 侦探的；n. 侦探；v. 发现；n. 探测器", "english": "detective/detect/detector", "type": "单词", "keyWords": [] },
    { "chinese": "n. 决心；确定；顽强；果断，坚定", "english": "determination", "type": "单词", "keyWords": [] },
    { "chinese": "v. 确定；决定；裁决；使下决心；vi. 下决心；决定（on）；a. 决意的；坚决的", "english": "determine/determined", "type": "单词", "keyWords": [] },
    { "chinese": "需求决定生产。", "english": "Demand determines (=decides) production.", "type": "句子", "keyWords": ["determine"] },
    { "chinese": "陪审团将对这些指控的真伪作出裁决。", "english": "A jury will determine whether the charges are true or false.", "type": "句子", "keyWords": ["determine"] },
    { "chinese": "他决心立刻就走。", "english": "He determined to go/that he (should) go at once.", "type": "句子", "keyWords": ["determine"] },
    { "chinese": "他们决定早些出发。", "english": "They determined (=decided) on an early start.", "type": "句子", "keyWords": ["determine"] },
    { "chinese": "下定决心要做某事", "english": "be determined to do...", "type": "短语", "keyWords": ["determined"] },
    { "chinese": "决然", "english": "in a determined manner", "type": "短语", "keyWords": ["determined"] },
    { "chinese": "v. 发展；发育；开发（资源等）；形成，培养；研制；使显影，冲印；n. 发展；开发（资源等）；研制；a. 发展中的；发达的", "english": "develop/development/developing/developed", "type": "单词", "keyWords": [] },
    { "chinese": "使孩子身体发育", "english": "develop a child's body", "type": "短语", "keyWords": ["develop"] },
    { "chinese": "冲洗底片", "english": "develop a film", "type": "短语", "keyWords": ["develop"] },
    { "chinese": "成为植物/领袖", "english": "develop into a plant/a leader", "type": "短语", "keyWords": ["develop"] },
    { "chinese": "培养兴趣/阅读能力/做某事的习惯", "english": "develop an interest/reading skills/the habit of doing sth.", "type": "短语", "keyWords": ["develop"] },
    { "chinese": "随着...的发展", "english": "with the development of", "type": "短语", "keyWords": ["development"] },
    { "chinese": "对外贸易方面的新进展", "english": "the latest developments in foreign trade", "type": "短语", "keyWords": ["development"] },
    { "chinese": "n. 设计；装置（为特定目的的设计或发明，或指改装的机器）", "english": "device", "type": "单词", "keyWords": [] },
    { "chinese": "v. 奉献；把...专用（于）（to）；a. 忠实的；投入的；ad. 忠实地；n. 热爱，投入（to sth.）", "english": "devote/devoted/devotedly/devotion", "type": "单词", "keyWords": [] },
    { "chinese": "致力于", "english": "be devoted to (doing) sth.", "type": "短语", "keyWords": ["devoted"] },
    { "chinese": "我们的大多数会议都用来讨论住房问题。", "english": "Most of our meetings were devoted to discussing the housing problems.", "type": "句子", "keyWords": ["devoted"] },
    { "chinese": "献身于", "english": "devote one's time/life/energy to (doing) sth.", "type": "短语", "keyWords": ["devote"] },
    { "chinese": "我的一个忠实的朋友", "english": "a devoted friend of mine", "type": "短语", "keyWords": ["devoted"] },
    { "chinese": "忠于职守", "english": "one's devotion to duty", "type": "短语", "keyWords": ["devotion"] },
    { "chinese": "他对教育事业的热爱/忠诚", "english": "his devotion to the cause of education", "type": "短语", "keyWords": ["devotion"] },
    { "chinese": "把时间用于科研", "english": "the devotion of one's time to scientific research", "type": "短语", "keyWords": ["devotion"] },
    { "chinese": "v. 诊断（疾病）；对（问题等）原因（或性质）下结论；n. 诊断；判断", "english": "diagnose/diagnosis", "type": "单词", "keyWords": [] },
    { "chinese": "n. 图表；图示；图解", "english": "diagram", "type": "单词", "keyWords": [] },
    { "chinese": "v. 拨（电话号码）；n. 刻度盘；钟面；转盘；（自动电话）拨号盘", "english": "dial", "type": "单词", "keyWords": [] },
    { "chinese": "n. 方言；行话；语调", "english": "dialect", "type": "单词", "keyWords": [] },
    { "chinese": "n. 对话；对白", "english": "dialog(ue)", "type": "单词", "keyWords": [] },
    { "chinese": "n. 钻石；金刚石；（扑克牌）方块；菱形（物）", "english": "diamond", "type": "单词", "keyWords": [] },
    { "chinese": "n. 日记；日志", "english": "diary", "type": "单词", "keyWords": [] },
    { "chinese": "记日记", "english": "keep a diary", "type": "短语", "keyWords": ["diary"] },
    { "chinese": "n. 听写；口授；v. 口授；发号施令；使听写", "english": "dictation/dictate", "type": "单词", "keyWords": [] },
    { "chinese": "进行听写", "english": "have a dictation", "type": "短语", "keyWords": ["dictation"] },
    { "chinese": "n. 词典；字典", "english": "dictionary", "type": "单词", "keyWords": [] },
    { "chinese": "v. 死；枯萎；vi. 遭受（某种死亡形式）（接同源宾语death）；a. 垂死的", "english": "die/dying", "type": "单词", "keyWords": [] },
    { "chinese": "寿终/夭折", "english": "die old/young", "type": "短语", "keyWords": ["die"] },
    { "chinese": "完全消失；灭绝", "english": "die out", "type": "短语", "keyWords": ["die"] },
    { "chinese": "因伤/患癌致死", "english": "die from wounds/cancer", "type": "短语", "keyWords": ["die"] },
    { "chinese": "因病而死", "english": "die of a disease", "type": "短语", "keyWords": ["die"] },
    { "chinese": "英勇就义；死得英雄", "english": "die a hero/a heroic death", "type": "短语", "keyWords": ["die"] },
    { "chinese": "逐渐停止；逐渐消失", "english": "die away", "type": "短语", "keyWords": ["die"] },
    { "chinese": "摩托车的噪音消失了。", "english": "The noise of the motorcar died away.", "type": "句子", "keyWords": ["die"] },
    { "chinese": "逐渐减弱；逐渐模糊", "english": "die down", "type": "短语", "keyWords": ["die"] },
    { "chinese": "等听众激动的情绪平息后演讲人又开始演讲。", "english": "After the excitement of the audience died down, the speaker restarted his speech.", "type": "句子", "keyWords": ["die"] },
    { "chinese": "相继死去", "english": "die off", "type": "短语", "keyWords": ["die"] },
    { "chinese": "这个寡妇还在中年时，她的亲属就先后离开了人世。", "english": "As the widow was still middle-aged, her relatives all died off.", "type": "句子", "keyWords": ["die"] },
    { "chinese": "（口）渴望；极想", "english": "be dying to do sth./for sth.", "type": "短语", "keyWords": ["dying"] },
    { "chinese": "救死扶伤", "english": "heal the wounded and rescue the dying", "type": "短语", "keyWords": ["dying"] },
    { "chinese": "n. 日常饮食；规定饮食", "english": "diet", "type": "单词", "keyWords": [] },
    { "chinese": "节食", "english": "be/go on a diet", "type": "短语", "keyWords": ["diet"] },
    { "chinese": "vi. 不同，有区别；（意见）发生分歧（from）", "english": "differ", "type": "单词", "keyWords": [] },
    { "chinese": "与...很不同", "english": "differ sharply/greatly from", "type": "短语", "keyWords": ["differ"] },
    { "chinese": "在...方面与...不同", "english": "differ in sth. from", "type": "短语", "keyWords": ["differ"] },
    { "chinese": "n. 差别；不同；a. 不同的；ad. 不同地", "english": "difference/different/differently", "type": "单词", "keyWords": [] },
    { "chinese": "有作用，有影响", "english": "make a difference", "type": "短语", "keyWords": ["difference"] },
    { "chinese": "这对我来说有什么区别么？", "english": "What difference does it make to me?", "type": "句子", "keyWords": ["difference"] },
    { "chinese": "你留下还是离开都不重要。", "english": "It does not make much difference whether you go or stay.", "type": "句子", "keyWords": ["difference"] },
    { "chinese": "我在不在场没什么关系。", "english": "It doesn't make a slight difference my being there.", "type": "句子", "keyWords": ["difference"] },
    { "chinese": "说出A和B在...方面不同", "english": "tell the difference between A and B in sth.", "type": "短语", "keyWords": ["difference"] },
    { "chinese": "在...方面（很/迥然）不同", "english": "be (totally/quite) different from... in...", "type": "短语", "keyWords": ["different"] },
    { "chinese": "失之毫厘，谬以千里。", "english": "One false step will make a great difference.", "type": "句子", "keyWords": ["difference"] },
    { "chinese": "a. 困难的；艰难的；n. 困难", "english": "difficult/difficulty", "type": "单词", "keyWords": [] },
    { "chinese": "困难地", "english": "with difficulty", "type": "短语", "keyWords": ["difficulty"] },
    { "chinese": "克服困难", "english": "overcome difficulties", "type": "短语", "keyWords": ["difficulty"] },
    { "chinese": "觉得某事有困难", "english": "have difficulty (in) doing sth./with sth.", "type": "短语", "keyWords": ["difficulty"] },
    { "chinese": "v. 挖掘", "english": "dig", "type": "单词", "keyWords": [] },
    { "chinese": "v. 消化；吸收；n. 摘要；文摘；n. 消化力，领悟", "english": "digest/digestion", "type": "单词", "keyWords": [] },
    { "chinese": "理解一本书", "english": "digest a book", "type": "短语", "keyWords": ["digest"] },
    { "chinese": "《读者文摘》", "english": "Reader's Digest", "type": "短语", "keyWords": ["digest"] },
    { "chinese": "n. 数字；数位", "english": "digit", "type": "单词", "keyWords": [] },
    { "chinese": "数字410是个三位数。", "english": "The number 410 contains three digits.", "type": "句子", "keyWords": ["digit"] },
    { "chinese": "a. 数码的；数字的；数字显示的；（使用）电脑技术的", "english": "digital", "type": "单词", "keyWords": [] },
    { "chinese": "n. 尊严；v. 使有尊严；a. 有尊严的", "english": "dignity/dignify/dignified", "type": "单词", "keyWords": [] },
    { "chinese": "庄重地；体面地", "english": "with dignity", "type": "短语", "keyWords": ["dignity"] },
    { "chinese": "a. 勤勉的；勤奋的；n. 勤勉", "english": "diligent/diligence", "type": "单词", "keyWords": [] },
    { "chinese": "工作努力", "english": "be diligent in one's work", "type": "短语", "keyWords": ["diligent"] },
    { "chinese": "努力追求自己的目标", "english": "pursue his aims with diligence", "type": "短语", "keyWords": ["diligence"] },
    { "chinese": "a. 昏暗的；模糊不清的", "english": "dim", "type": "单词", "keyWords": [] },
    { "chinese": "对过去的模糊记忆", "english": "a dim memory of the past", "type": "短语", "keyWords": ["dim"] },
    { "chinese": "房屋的模糊轮廓", "english": "the dim outline of a building", "type": "短语", "keyWords": ["dim"] },
    { "chinese": "远处模糊的人影", "english": "a dim figure in the distance", "type": "短语", "keyWords": ["dim"] },
    { "chinese": "v. 进正餐；出外吃饭（在朋友家或餐馆）", "english": "dine/dine out", "type": "单词", "keyWords": [] },
    { "chinese": "n. 正餐，主餐；晚餐", "english": "dinner", "type": "单词", "keyWords": [] },
    { "chinese": "正餐吃...", "english": "have sth. for dinner", "type": "短语", "keyWords": ["dinner"] },
    { "chinese": "n. 恐龙", "english": "dinosaur", "type": "单词", "keyWords": [] },
    { "chinese": "n. 二氧化物", "english": "dioxide", "type": "单词", "keyWords": [] },
    { "chinese": "vi. /n. 浸；蘸；浏览，翻阅", "english": "dip", "type": "单词", "keyWords": [] },
    { "chinese": "我在口袋里掏几枚硬币。", "english": "I dipped into my pocket for some coins.", "type": "句子", "keyWords": ["dip"] },
    { "chinese": "把头潜入水中", "english": "dip one's head into water", "type": "短语", "keyWords": ["dip"] },
    { "chinese": "价格急降", "english": "a dip in prices", "type": "短语", "keyWords": ["dip"] },
    { "chinese": "随便翻阅乔叟的作品/涉猎心理学/浏览书籍", "english": "dip into Chaucer/psychology/books", "type": "短语", "keyWords": ["dip"] },
    { "chinese": "n. 奖状；毕业文凭，学位证书", "english": "diploma", "type": "单词", "keyWords": [] },
    { "chinese": "n. 外交家；外交官；有外交手腕的人；a. 外交的；圆滑的；策略的", "english": "diplomat/diplomatic", "type": "单词", "keyWords": [] },
    { "chinese": "v. 指点，指导；指挥；命令；给...指路；导演；a. /ad. 直（的）；径直（的）；直接的；笔直的", "english": "direct", "type": "单词", "keyWords": [] },
    { "chinese": "直达列车", "english": "a direct train", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "直接的回答", "english": "a direct response", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "指挥某人去某地", "english": "direct sb. to a place", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "指点某人做某事", "english": "direct sb. to do sth.", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "将他们火力对准目标", "english": "direct their fire at the target", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "我们直接从北京到上海。", "english": "We went direct from Beijing to Shanghai.", "type": "句子", "keyWords": ["direct"] },
    { "chinese": "n. 方向；（常pl）指引，说明（instructions）；U. 指导；导演", "english": "direction", "type": "单词", "keyWords": [] },
    { "chinese": "四面八方", "english": "in all directions", "type": "短语", "keyWords": ["direction"] },
    { "chinese": "朝着某个方向", "english": "in the direction of...", "type": "短语", "keyWords": ["direction"] },
    { "chinese": "来自那个方向", "english": "come from that direction", "type": "短语", "keyWords": ["direction"] },
    { "chinese": "予以用法说明/指导", "english": "give directions for use", "type": "短语", "keyWords": ["direction"] },
    { "chinese": "ad. 直接；马上；一.....就（immediately, instantly, the minute...）", "english": "directly", "type": "单词", "keyWords": [] },
    { "chinese": "我们一做完就来。", "english": "We'll come directly/instantly/immediately/the moment we have finished.", "type": "句子", "keyWords": ["directly"] },
    { "chinese": "n. 主管；董事；经理；厂长；导演", "english": "director", "type": "单词", "keyWords": [] },
    { "chinese": "n. 污物；灰尘", "english": "dirt", "type": "单词", "keyWords": [] },
    { "chinese": "泥路", "english": "dirt road", "type": "短语", "keyWords": ["dirt"] },
    { "chinese": "a. 脏的；卑鄙的，下流的；v. 弄脏", "english": "dirty", "type": "单词", "keyWords": [] },
    { "chinese": "下流人/话", "english": "a dirty fellow/talk", "type": "短语", "keyWords": ["dirty"] },
    { "chinese": "弄脏自己的手脚", "english": "dirty one's hands", "type": "短语", "keyWords": ["dirty"] },
    { "chinese": "a. 丧失（劳动）能力的，残疾的；v. 使残废，使失去（劳动）能力", "english": "disabled/disable", "type": "单词", "keyWords": [] },
    { "chinese": "残疾人", "english": "the disabled", "type": "短语", "keyWords": ["disabled"] },
    { "chinese": "n. 不利地位；不利条件；劣势；v. 使处于不利地位；损害，危害；a. 处于不利地位的", "english": "disadvantage/disadvantaged", "type": "单词", "keyWords": [] },
    { "chinese": "处于不利地位", "english": "at a disadvantage", "type": "短语", "keyWords": ["disadvantage"] },
    { "chinese": "对某人不利，使某人吃亏", "english": "to sb.'s disadvantage", "type": "短语", "keyWords": ["disadvantage"] },
    { "chinese": "弱势/处于不利地位的群体", "english": "the disadvantaged", "type": "短语", "keyWords": ["disadvantaged"] },
    { "chinese": "vi. 不一致，不适宜", "english": "disagree", "type": "单词", "keyWords": [] },
    { "chinese": "我不宜吃苹果。", "english": "Apples disagree with me.", "type": "句子", "keyWords": ["disagree"] },
    { "chinese": "置若罔闻", "english": "turn a deaf ear to...", "type": "短语", "keyWords": ["deaf"] },
    { "chinese": "不听劝告", "english": "be deaf to advice", "type": "短语", "keyWords": ["deaf"] },
    { "chinese": "不肯倾听别人意见的人是最聋的人。", "english": "None (are) so deaf as those who won't hear.", "type": "句子", "keyWords": ["deaf"] },
    { "chinese": "关于西非的一本书", "english": "a book dealing with West Africa", "type": "短语", "keyWords": ["deal"] },
    { "chinese": "同这家店做茶叶生意已经有20年了。", "english": "I've dealt with this shop for tea for 20 years.", "type": "句子", "keyWords": ["deal"] },
    { "chinese": "他很难打交道。", "english": "He is hard to deal with.", "type": "句子", "keyWords": ["deal"] },
    { "chinese": "他抽许多烟。", "english": "He smokes a great deal (=a lot).", "type": "句子", "keyWords": ["deal"] }
];
