const qgl89_96 = [
    { "chinese": "缓解局势/困难/冲突/化解他们的烦心事", "english": "ease the situation/ difficulties/ conflict/ their troubled minds", "type": "短语", "keyWords": ["ease"] },
    { "chinese": "解除他的痛苦", "english": "ease him of his pain", "type": "短语", "keyWords": ["ease"] },
    { "chinese": "a. 容易的；舒服的，安逸的；从容的；随和的", "english": "easy", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 容易地；舒适地", "english": "easily", "type": "单词", "keyWords": [] },
    { "chinese": "别紧张；放轻松", "english": "take it easy/ take things easy", "type": "短语", "keyWords": ["easy"] },
    { "chinese": "说时容易做时难。/知易行难。", "english": "(It's) easier said than done.", "type": "句子", "keyWords": ["easy"] },
    { "chinese": "（人）容易接近；（物）容易得到；（地方）交通方便", "english": "easy of access", "type": "短语", "keyWords": ["easy"] },
    { "chinese": "a. 随和的", "english": "easy-going", "type": "单词", "keyWords": [] },
    { "chinese": "他为人很随和。", "english": "He is easy-going with people.", "type": "句子", "keyWords": ["easy-going"] },
    { "chinese": "非常容易，轻而易举，非常简单", "english": "be as easy as ABC", "type": "短语", "keyWords": ["easy"] },
    { "chinese": "[口]慢慢来；小心点", "english": "Easy does it.", "type": "句子", "keyWords": ["easy"] },
    { "chinese": "来得容易去得快；易得易失。", "english": "Easy come, easy go.", "type": "句子", "keyWords": ["easy"] },
    { "chinese": "n. (the) 东；东方", "english": "east", "type": "单词", "keyWords": [] },
    { "chinese": "a. 东方的；从东面来的；朝东的", "english": "east a.", "type": "短语", "keyWords": ["east"] },
    { "chinese": "ad. 在东方，向东方，朝东方", "english": "east ad.", "type": "短语", "keyWords": ["east"] },
    { "chinese": "从东到西", "english": "from east to west", "type": "短语", "keyWords": ["east"] },
    { "chinese": "远/中/近东", "english": "the Far/ Middle/ Near East", "type": "短语", "keyWords": ["east"] },
    { "chinese": "东方", "english": "the East", "type": "短语", "keyWords": ["east"] },
    { "chinese": "向东走", "english": "go east (ad.)= go to the east (n.)", "type": "短语", "keyWords": ["east"] },
    { "chinese": "来自东边太平洋", "english": "from the Pacific on the east", "type": "短语", "keyWords": ["east"] },
    { "chinese": "...之东", "english": "to the east of...", "type": "短语", "keyWords": ["east"] },
    { "chinese": "位于南京以东15千米", "english": "lie 15km (to the) east of Nanjing", "type": "短语", "keyWords": ["east"] },
    { "chinese": "n. 复活节", "english": "Easter", "type": "单词", "keyWords": [] },
    { "chinese": "在复活节", "english": "at Easter", "type": "短语", "keyWords": ["Easter"] },
    { "chinese": "a. 东部的", "english": "eastern", "type": "单词", "keyWords": [] },
    { "chinese": "a./ad. 向东方，朝东面", "english": "eastward", "type": "单词", "keyWords": [] },
    { "chinese": "v. 吃；侵蚀；毁坏", "english": "eat", "type": "单词", "keyWords": [] },
    { "chinese": "上馆子吃饭", "english": "eat/dine out", "type": "短语", "keyWords": ["eat"] },
    { "chinese": "n. [C] 电子书籍", "english": "e-book", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (pl. echoes) 回声，回音；回波", "english": "echo", "type": "单词", "keyWords": [] },
    { "chinese": "v. 发回声；随声附和", "english": "echo v.", "type": "短语", "keyWords": ["echo"] },
    { "chinese": "表示“环境、生态、生态学的”", "english": "eco-", "type": "前缀", "keyWords": [] },
    { "chinese": "n. (U) 生态学", "english": "ecology", "type": "单词", "keyWords": ["eco-"] },
    { "chinese": "a. 生态的；环保的；生态学的", "english": "ecological", "type": "单词", "keyWords": ["eco-"] },
    { "chinese": "a. 经济（上）的；经济学的", "english": "economic", "type": "单词", "keyWords": [] },
    { "chinese": "经济危机", "english": "an economic crisis", "type": "短语", "keyWords": ["economic"] },
    { "chinese": "n. (U) 经济学", "english": "economics", "type": "单词", "keyWords": [] },
    { "chinese": "a. 节约的，节俭的", "english": "economical", "type": "单词", "keyWords": [] },
    { "chinese": "经济情况；(C) （某国）经济；经济制度；n. (C) 节约（措施），经济（舱等）", "english": "economy", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 节约，节省", "english": "economize", "type": "单词", "keyWords": [] },
    { "chinese": "节约电和燃料", "english": "economize on electricity and fuel", "type": "短语", "keyWords": ["economize"] },
    { "chinese": "（客机之）经济舱位，二等舱位", "english": "economy class", "type": "短语", "keyWords": ["economy"] },
    { "chinese": "n. (C) 生态系统", "english": "ecosystem", "type": "单词", "keyWords": ["eco-"] },
    { "chinese": "n. (C) 边缘；刀口，利刃，锋；优势", "english": "edge", "type": "单词", "keyWords": [] },
    { "chinese": "在死亡的边缘", "english": "on the edge of death", "type": "短语", "keyWords": ["edge"] },
    { "chinese": "a. 可食用的", "english": "edible", "type": "单词", "keyWords": [] },
    { "chinese": "燕窝", "english": "edible bird's nest", "type": "短语", "keyWords": ["edible"] },
    { "chinese": "海带", "english": "edible seaweeds", "type": "短语", "keyWords": ["edible"] },
    { "chinese": "vt. 编辑；修改；删除，删节", "english": "edit", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 版本；版（次）", "english": "edition", "type": "单词", "keyWords": [] },
    { "chinese": "廉价本", "english": "a cheap edition", "type": "短语", "keyWords": ["edition"] },
    { "chinese": "n. (C) 编辑，编者", "english": "editor", "type": "单词", "keyWords": [] },
    { "chinese": "主编；总编辑", "english": "a chief editor/ an editor-in-chief", "type": "短语", "keyWords": ["editor"] },
    { "chinese": "a. 编辑的；社论的", "english": "editorial", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 社论", "english": "editorial n.", "type": "短语", "keyWords": ["editorial"] },
    { "chinese": "vt. 教育；培养；训练", "english": "educate", "type": "单词", "keyWords": [] },
    { "chinese": "教育某人做某事", "english": "educate sb. to do sth.", "type": "短语", "keyWords": ["educate"] },
    { "chinese": "a. 受过教育的，有教养的", "english": "educated", "type": "单词", "keyWords": [] },
    { "chinese": "受过良好教育的人", "english": "well-educated people", "type": "短语", "keyWords": ["educated"] },
    { "chinese": "n. (C) 教育家", "english": "educator", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 教育", "english": "education", "type": "单词", "keyWords": [] },
    { "chinese": "一个受过教育的人", "english": "a man of education", "type": "短语", "keyWords": ["education"] },
    { "chinese": "接受良好的教育（表示接受一段时间或某种教育）", "english": "have/ receive a good education", "type": "短语", "keyWords": ["education"] },
    { "chinese": "n. (C) (U) 效果；效力；作用；结果；影响", "english": "effect", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有效的；生效的", "english": "effective", "type": "单词", "keyWords": ["effect"] },
    { "chinese": "n. (U) 有效", "english": "effectiveness", "type": "单词", "keyWords": ["effect"] },
    { "chinese": "对某人无效", "english": "(be) of no effect to sb.", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "开始生效；开始实行", "english": "come into effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "对...有影响", "english": "have (an) effect/ impact on", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "开始实行；开始生效", "english": "take effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "无副作用", "english": "without any side effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "实行，实施；使生效", "english": "put/ bring...into effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "（规律、法律等）生效，有效；在实行中", "english": "be in effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "采取有效措施", "english": "take effective measures", "type": "短语", "keyWords": ["effective"] },
    { "chinese": "药很快见效了。", "english": "The medicine quickly took effect.", "type": "句子", "keyWords": ["effect"] },
    { "chinese": "a. 高效的；有能力的", "english": "efficient", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 高效", "english": "efficiency", "type": "单词", "keyWords": ["efficient"] },
    { "chinese": "工作效率高", "english": "be efficient in one's work", "type": "短语", "keyWords": ["efficient"] },
    { "chinese": "n. (C) (U) 努力", "english": "effort", "type": "单词", "keyWords": [] },
    { "chinese": "努力做", "english": "make an effort/ every effort to do sth.", "type": "短语", "keyWords": ["effort"] },
    { "chinese": "毫不费力", "english": "without effort", "type": "短语", "keyWords": ["effort"] },
    { "chinese": "不遗余力，极力", "english": "spare no effort to do sth.", "type": "短语", "keyWords": ["effort"] },
    { "chinese": "例如（同for example）", "english": "e.g. (exempli gratia)", "type": "短语", "keyWords": [] },
    { "chinese": "n. (C) （鸟类的）蛋；鸡蛋；（鱼、昆虫等的）卵", "english": "egg", "type": "单词", "keyWords": [] },
    { "chinese": "茄子", "english": "eggplant", "type": "单词", "keyWords": ["egg"] },
    { "chinese": "下蛋", "english": "lay eggs", "type": "短语", "keyWords": ["egg"] },
    { "chinese": "杀鸡取卵；因贪得无厌而坏事", "english": "kill the goose that laid the golden eggs", "type": "短语", "keyWords": ["egg"] },
    { "chinese": "n. 埃及", "english": "Egypt", "type": "单词", "keyWords": [] },
    { "chinese": "a. 埃及的，埃及人的", "english": "Egyptian", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 埃及人", "english": "Egyptian n.", "type": "短语", "keyWords": ["Egyptian"] },
    { "chinese": "interj. 啊；嗯", "english": "eh", "type": "单词", "keyWords": [] },
    { "chinese": "num. 八", "english": "eight", "type": "单词", "keyWords": [] },
    { "chinese": "第八；八分之一", "english": "eighth", "type": "单词", "keyWords": [] },
    { "chinese": "第十八；十八分之一", "english": "eighteenth", "type": "单词", "keyWords": [] },
    { "chinese": "第八十；八十分之一", "english": "eightieth", "type": "单词", "keyWords": [] },
    { "chinese": "n. 爱因斯坦", "english": "Einstein", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 也（用于否定句或否定词组后加强语气）", "english": "either", "type": "单词", "keyWords": [] },
    { "chinese": "a. （两者之中的）任一的", "english": "either a.", "type": "短语", "keyWords": ["either"] },
    { "chinese": "pron. 两者中任一者", "english": "either pron.", "type": "短语", "keyWords": ["either"] },
    { "chinese": "在街道两旁", "english": "on either side/ both sides of the street", "type": "短语", "keyWords": ["either"] },
    { "chinese": "不是...就是...；或者...或者...", "english": "either...or...", "type": "短语", "keyWords": ["either"] },
    { "chinese": "你爸来还是你来？", "english": "Is either your father or you coming?", "type": "句子", "keyWords": ["either"] },
    { "chinese": "v. （时间）过去，消逝", "english": "elapse", "type": "单词", "keyWords": [] },
    { "chinese": "a. 弹性的；有弹性的", "english": "elastic", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 肘", "english": "elbow", "type": "单词", "keyWords": [] },
    { "chinese": "a. 年龄较大的；年长的", "english": "elder", "type": "单词", "keyWords": [] },
    { "chinese": "哥哥", "english": "elder brother", "type": "短语", "keyWords": ["elder"] },
    { "chinese": "a. 过了中年的，年老的；晚年的", "english": "elderly", "type": "单词", "keyWords": [] },
    { "chinese": "老年人", "english": "the elderly", "type": "短语", "keyWords": ["elderly"] },
    { "chinese": "v. 选举", "english": "elect", "type": "单词", "keyWords": [] },
    { "chinese": "选举某人当...", "english": "elect sb. to be sth.", "type": "短语", "keyWords": ["elect"] },
    { "chinese": "里根被选为美国第四十任总统。", "english": "Reagan was elected (as) the fortieth President of the United States.", "type": "句子", "keyWords": ["elect"] },
    { "chinese": "n. (C) 选举", "english": "election", "type": "单词", "keyWords": [] },
    { "chinese": "大选，普选", "english": "a general election", "type": "短语", "keyWords": ["election"] },
    { "chinese": "a. 电的（由电操纵的或由电产生的）", "english": "electric", "type": "单词", "keyWords": [] },
    { "chinese": "电流", "english": "electric current", "type": "短语", "keyWords": ["electric"] },
    { "chinese": "电灯", "english": "electric lights", "type": "短语", "keyWords": ["electric"] },
    { "chinese": "电击/触电", "english": "electric shock", "type": "短语", "keyWords": ["electric"] },
    { "chinese": "a. 电的；与（用）电有关的；电气的", "english": "electrical", "type": "单词", "keyWords": [] },
    { "chinese": "电气工程师", "english": "an electrical engineer", "type": "短语", "keyWords": ["electrical"] },
    { "chinese": "电路故障", "english": "electrical fault", "type": "短语", "keyWords": ["electrical"] },
    { "chinese": "n. (C) 电机师，电机技术员；电气专家；电工", "english": "electrician", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 电", "english": "electricity", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 电子", "english": "electron", "type": "单词", "keyWords": [] },
    { "chinese": "a. 电子的", "english": "electronic", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 电子学", "english": "electronics", "type": "单词", "keyWords": [] },
    { "chinese": "a. （举止、服饰等）优美的，文雅的；（文体、语言等）典雅的", "english": "elegant", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) （可和不定冠词连用）优美，文雅；（文体、语言等）典雅", "english": "elegance", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 成分；元素；要素", "english": "element", "type": "单词", "keyWords": [] },
    { "chinese": "基本元素", "english": "simple or basic element", "type": "短语", "keyWords": ["element"] },
    { "chinese": "a. 初级的；基本的", "english": "elementary", "type": "单词", "keyWords": [] },
    { "chinese": "小学", "english": "elementary school", "type": "短语", "keyWords": ["elementary"] },
    { "chinese": "n. (C) 大象", "english": "elephant", "type": "单词", "keyWords": [] },
    { "chinese": "v. 举起；提拔；振奋", "english": "elevate", "type": "单词", "keyWords": [] },
    { "chinese": "高架路", "english": "elevated highway", "type": "短语", "keyWords": ["elevate"] },
    { "chinese": "n. (C) 电梯", "english": "elevator", "type": "单词", "keyWords": [] },
    { "chinese": "v. 消除，根除；排除；淘汰", "english": "eliminate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 淘汰；淘汰赛；除", "english": "elimination", "type": "单词", "keyWords": [] },
    { "chinese": "a./ad. 其他的；别的（常用于who, someone, somewhere等疑问代词或不定代词之后）", "english": "else", "type": "单词", "keyWords": [] },
    { "chinese": "别的什么东西/人", "english": "anything/ someone else", "type": "短语", "keyWords": ["else"] },
    { "chinese": "别的什么人/其他什么地方", "english": "who/ where else", "type": "短语", "keyWords": ["else"] },
    { "chinese": "这究竟是谁的书？", "english": "Who else's book is it?", "type": "句子", "keyWords": ["else"] },
    { "chinese": "否则；要不", "english": "or else", "type": "短语", "keyWords": ["else"] },
    { "chinese": "你必须付一万元，否则就得去坐牢。", "english": "You must pay ¥10,000 or else go to prison.", "type": "句子", "keyWords": ["else"] },
    { "chinese": "ad. 在别处；到别处", "english": "elsewhere", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 电子邮件", "english": "email", "type": "单词", "keyWords": [] },
    { "chinese": "给...发电子邮件", "english": "email vt.", "type": "短语", "keyWords": ["email"] },
    { "chinese": "v. 使局促不安；使为难，使尴尬", "english": "embarrass", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 困窘，难堪", "english": "embarrassment", "type": "单词", "keyWords": [] },
    { "chinese": "使人/感到难堪的", "english": "embarrassing/ embarrassed", "type": "短语", "keyWords": ["embarrass"] },
    { "chinese": "n. (C) 大使馆", "english": "embassy", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 大使，使节", "english": "ambassador", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 显现，浮现；（问题等）暴露", "english": "emerge", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 浮现，露出；出现", "english": "emergence", "type": "单词", "keyWords": [] },
    { "chinese": "船从雾里露了出来。", "english": "The ship emerged from behind the fog.", "type": "句子", "keyWords": ["emerge"] },
    { "chinese": "a. 紧急的；突然出现的", "english": "emergent", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 急诊；紧急情况", "english": "emergency", "type": "单词", "keyWords": [] },
    { "chinese": "紧急会议", "english": "emergency meeting", "type": "短语", "keyWords": ["emergency"] },
    { "chinese": "应急出口", "english": "emergency exit", "type": "短语", "keyWords": ["emergency"] },
    { "chinese": "急救室", "english": "emergency room", "type": "短语", "keyWords": ["emergency"] },
    { "chinese": "在紧急情况下", "english": "in an emergency/ in case of emergency", "type": "短语", "keyWords": ["emergency"] },
    { "chinese": "vt./vi. （使）永久移居国外", "english": "emigrate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 移居国外", "english": "emigration", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 移居外国者；移民", "english": "emigrant", "type": "单词", "keyWords": [] },
    { "chinese": "v. 发出，射出，散发（光、热、电波、声音、液体、气味等）", "english": "emit", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) (C) 发出，射出，散发；(C) 散发（或发射）物", "english": "emission", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 情感；激动", "english": "emotion", "type": "单词", "keyWords": [] },
    { "chinese": "a. 感情的；易动感情的", "english": "emotional", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 激动地；情绪化地", "english": "emotionally", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 皇帝；（帝国的）君主", "english": "emperor", "type": "单词", "keyWords": [] },
    { "chinese": "n. (pl. emphases) (C) (U) 强调，着重；重点", "english": "emphasis", "type": "单词", "keyWords": [] },
    { "chinese": "着重于", "english": "place/ put/ lay emphasis on (doing) sth.", "type": "短语", "keyWords": ["emphasis"] },
    { "chinese": "v. 强调，着重；加强...的语气", "english": "emphasize", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 帝国", "english": "empire", "type": "单词", "keyWords": [] },
    { "chinese": "v. 雇用；采/利/使用", "english": "employ", "type": "单词", "keyWords": [] },
    { "chinese": "你们为何不采用那个新方法？", "english": "Why didn't you employ the new method?", "type": "句子", "keyWords": ["employ"] },
    { "chinese": "n. (C) 雇员", "english": "employee", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 雇主", "english": "employer", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 雇用；就业；受雇", "english": "employment", "type": "单词", "keyWords": [] },
    { "chinese": "就业", "english": "get employment", "type": "短语", "keyWords": ["employment"] },
    { "chinese": "失业", "english": "be out of employment", "type": "短语", "keyWords": ["employment"] },
    { "chinese": "a. 空的；空洞的；空虚的", "english": "empty", "type": "单词", "keyWords": [] },
    { "chinese": "倒空；使空；成为空的；使排出；流出", "english": "empty v.", "type": "短语", "keyWords": ["empty"] },
    { "chinese": "空话/空洞的诺言", "english": "empty words/ promises", "type": "短语", "keyWords": ["empty"] },
    { "chinese": "流向大海", "english": "empty (itself) into the sea", "type": "短语", "keyWords": ["empty"] },
    { "chinese": "倒空口袋/盒子", "english": "empty out the pocket/ the boxes", "type": "短语", "keyWords": ["empty"] },
    { "chinese": "v. 使能够", "english": "enable", "type": "单词", "keyWords": [] },
    { "chinese": "使某人能够做某事", "english": "enable sb. to do sth.", "type": "短语", "keyWords": ["enable"] },
    { "chinese": "v. 把...包（围）在里面；围住，包住；把..装入信封，随信寄；封入，附入；装有", "english": "enclose", "type": "单词", "keyWords": [] },
    { "chinese": "随函附上", "english": "enclose sth. with the letter", "type": "短语", "keyWords": ["enclose"] },
    { "chinese": "在一个密闭的空间里", "english": "in an enclosed space", "type": "短语", "keyWords": ["enclose"] },
    { "chinese": "n. 围场；围栏；（信中）附件，装入物", "english": "enclosure", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. (C) 遭遇，遇到；意外遇见；与..邂逅", "english": "encounter", "type": "单词", "keyWords": [] },
    { "chinese": "v. 鼓励，激励", "english": "encourage", "type": "单词", "keyWords": [] },
    { "chinese": "鼓励做...", "english": "encourage doing sth.", "type": "短语", "keyWords": ["encourage"] },
    { "chinese": "鼓励某人做某事", "english": "encourage sb. to do sth.", "type": "短语", "keyWords": ["encourage"] },
    { "chinese": "n. (U) 鼓励，激励", "english": "encouragement", "type": "单词", "keyWords": [] },
    { "chinese": "使人/感到激励的", "english": "encouraging/ encouraged", "type": "短语", "keyWords": ["encourage"] },
    { "chinese": "n. (C) 百科全书", "english": "encyclop(a)edia", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 结束；末尾，尽头；末日", "english": "end", "type": "单词", "keyWords": [] },
    { "chinese": "v. 结束；终止", "english": "end v.", "type": "短语", "keyWords": ["end"] },
    { "chinese": "在...尽头/末尾", "english": "at the end of", "type": "短语", "keyWords": ["end"] },
    { "chinese": "把...结束", "english": "bring ... to an end", "type": "短语", "keyWords": ["end"] },
    { "chinese": "最后", "english": "in the end", "type": "短语", "keyWords": ["end"] },
    { "chinese": "从头至尾", "english": "from beginning to end", "type": "短语", "keyWords": ["end"] },
    { "chinese": "结束", "english": "come to an end", "type": "短语", "keyWords": ["end"] },
    { "chinese": "使收支平衡", "english": "make (both) ends meet", "type": "短语", "keyWords": ["end"] },
    { "chinese": "使终结，使结束", "english": "put an end to (sth.)", "type": "短语", "keyWords": ["end"] },
    { "chinese": "我决心要制止所有这些谣言。", "english": "I am determined to put an end to all these rumours.", "type": "句子", "keyWords": ["end"] },
    { "chinese": "以...告终/结束", "english": "end in sth.", "type": "短语", "keyWords": ["end"] },
    { "chinese": "以平局告终", "english": "end in a draw", "type": "短语", "keyWords": ["end"] },
    { "chinese": "结果打了起来", "english": "end in a fight", "type": "短语", "keyWords": ["end"] },
    { "chinese": "以...告终/结束", "english": "end up (with sth./ by doing sth.)", "type": "短语", "keyWords": ["end"] },
    { "chinese": "最后蹲了监狱", "english": "end up in prison", "type": "短语", "keyWords": ["end"] },
    { "chinese": "结果成了医生", "english": "end up as a doctor", "type": "短语", "keyWords": ["end"] },
    { "chinese": "以死亡告终", "english": "end up dead", "type": "短语", "keyWords": ["end"] },
    { "chinese": "在歌声中结束", "english": "end up with a song", "type": "短语", "keyWords": ["end"] },
    { "chinese": "我们一开始不喜欢它，但我们最后却为之欢呼。", "english": "We didn't like it at first, but we ended up cheering.", "type": "句子", "keyWords": ["end"] },
    { "chinese": "过分耗费精力", "english": "burn the candle at both ends", "type": "短语", "keyWords": ["end"] },
    { "chinese": "n. (C) （故事等）结尾（结局）", "english": "ending", "type": "单词", "keyWords": [] },
    { "chinese": "a. 无限的，无穷的；无止境的", "english": "endless", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 不断地，无穷尽地", "english": "endlessly", "type": "单词", "keyWords": [] },
    { "chinese": "v. 忍受，忍耐（指“忍受较长期、较严重的痛苦、困难等的能力”）；vi. 持久；持续；忍受，忍耐", "english": "endure", "type": "单词", "keyWords": [] },
    { "chinese": "忍受痛苦/苦难/艰苦", "english": "endure pain/suffering/hardship", "type": "短语", "keyWords": ["endure"] },
    { "chinese": "忍无可忍", "english": "beyond endurance", "type": "短语", "keyWords": ["endure"] },
    { "chinese": "a. 持久的，不朽的", "english": "enduring", "type": "单词", "keyWords": [] },
    { "chinese": "持久和平", "english": "an enduring peace", "type": "短语", "keyWords": ["enduring"] },
    { "chinese": "n. (U) 持久（力）；耐久（性）；忍耐（力）", "english": "endurance", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可忍受的，能忍耐的", "english": "endurable", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 敌人；（用作单或复）仇敌（集合名词）", "english": "enemy", "type": "单词", "keyWords": [] },
    { "chinese": "a. 精力充沛的", "english": "energetic", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 精力充沛地", "english": "energetically", "type": "单词", "keyWords": [] },
    { "chinese": "v. 供给...能量；使有活力", "english": "energize", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)C 能量；活力；精力（有时用复数）", "english": "energy", "type": "单词", "keyWords": [] },
    { "chinese": "精力充沛", "english": "be full of energy", "type": "短语", "keyWords": ["energy"] },
    { "chinese": "vi./vt. （使）忙碌，（使）从事于，（使）参加；vt. 使订婚；雇，聘；吸引；占用（时间、精力等）", "english": "engage", "type": "单词", "keyWords": [] },
    { "chinese": "从事，参加", "english": "engage in (doing) sth.", "type": "短语", "keyWords": ["engage"] },
    { "chinese": "乔治很快便参与到运动中。", "english": "George soon engaged in the sport.", "type": "句子", "keyWords": ["engage"] },
    { "chinese": "忙着做某事", "english": "be engaged in sth.", "type": "短语", "keyWords": ["engage"] },
    { "chinese": "他正忙着写作业。", "english": "He is engaged in his homework just now.", "type": "句子", "keyWords": ["engage"] },
    { "chinese": "和某人订婚", "english": "be engaged to sb.", "type": "短语", "keyWords": ["engage"] },
    { "chinese": "汤姆已与安妮订婚。", "english": "Tom is engaged to Anne.", "type": "句子", "keyWords": ["engage"] },
    { "chinese": "占线。/线路忙。", "english": "The line is engaged.", "type": "句子", "keyWords": ["engage"] },
    { "chinese": "n. (U) 参与；(C) 订婚；约会", "english": "engagement", "type": "单词", "keyWords": [] },
    { "chinese": "a. 已订婚的；占线；在使用中", "english": "engaged", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 引擎；发动机", "english": "engine", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 工程师；技师", "english": "engineer", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 工程学", "english": "engineering", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 英格兰；英国", "english": "England", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 英语", "english": "English", "type": "单词", "keyWords": [] },
    { "chinese": "a. 英文的；英国人的；英格兰的", "english": "English a.", "type": "短语", "keyWords": ["English"] },
    { "chinese": "英语晚会", "english": "English Evening", "type": "短语", "keyWords": ["English"] },
    { "chinese": "（总称）英吉利人；英国人；英军", "english": "the English", "type": "短语", "keyWords": ["English"] },
    { "chinese": "n. (C) 英格兰男/女人", "english": "Englishman/ Englishwoman", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 增强；增加（在价值、美、声望上增强）", "english": "enhance", "type": "单词", "keyWords": [] },
    { "chinese": "v. 喜欢，喜爱；享受...乐趣；欣赏", "english": "enjoy", "type": "单词", "keyWords": [] },
    { "chinese": "喜欢做某事", "english": "enjoy doing sth.", "type": "短语", "keyWords": ["enjoy"] },
    { "chinese": "过得快乐", "english": "enjoy oneself", "type": "短语", "keyWords": ["enjoy"] },
    { "chinese": "n. (U) 享乐", "english": "enjoyment", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有乐趣的；令人快乐的", "english": "enjoyable", "type": "单词", "keyWords": [] },
    { "chinese": "令人愉快的夜晚", "english": "an enjoyable evening", "type": "短语", "keyWords": ["enjoyable"] },
    { "chinese": "vt. 扩大", "english": "enlarge", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 扩大", "english": "enlargement", "type": "单词", "keyWords": [] },
    { "chinese": "a. 巨大的", "english": "enormous", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 巨大；暴行", "english": "enormity", "type": "单词", "keyWords": [] },
    { "chinese": "a./pron./ad. 足够", "english": "enough", "type": "单词", "keyWords": [] },
    { "chinese": "够了！", "english": "enough interj.", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "太多", "english": "more than enough", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "够了！不要再说了！", "english": "Enough of that!", "type": "句子", "keyWords": ["enough"] },
    { "chinese": "适可而止。", "english": "Enough is enough.", "type": "句子", "keyWords": ["enough"] },
    { "chinese": "果真，果然；的的确确", "english": "sure enough", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "足够的...来做", "english": "a./adv.+enough to do sth.", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "无论怎样…都不够", "english": "cannot...enough", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "我对你感恩不尽。", "english": "I cannot thank you enough.", "type": "句子", "keyWords": ["enough"] },
    { "chinese": "对于你的无礼/那些废话，我已经受够了。", "english": "I have had enough of your rudeness/ the nonsense.", "type": "句子", "keyWords": ["enough"] },
    { "chinese": "v. 招（生）；吸收（成员）；vi. 入学；参加", "english": "enrol(l)", "type": "单词", "keyWords": [] },
    { "chinese": "把他吸收为俱乐部成员", "english": "enroll (vt.) him as a member of the club", "type": "短语", "keyWords": ["enrol(l)"] },
    { "chinese": "在大学注册上英语课", "english": "enroll (vi.) for English classes at college", "type": "短语", "keyWords": ["enrol(l)"] },
    { "chinese": "n. (U) 登记，入学；(C) 注册人数", "english": "enrolment", "type": "单词", "keyWords": [] },
    { "chinese": "v. 保证；担保，确保；使安全；保证得到", "english": "ensure", "type": "单词", "keyWords": [] },
    { "chinese": "我们可以保证把工作做好。", "english": "We can ensure that the work shall be done in the right way.", "type": "句子", "keyWords": ["ensure"] },
    { "chinese": "凭一封介绍信准保会接待你。", "english": "A letter of introduction will ensure you an interview.", "type": "句子", "keyWords": ["ensure"] },
    { "chinese": "v. 进入；参加", "english": "enter", "type": "单词", "keyWords": [] },
    { "chinese": "（替...）报名参加", "english": "enter sb. for...", "type": "短语", "keyWords": ["enter"] },
    { "chinese": "报名参加", "english": "enter for (exams/ races/ the competition)", "type": "短语", "keyWords": ["enter"] },
    { "chinese": "n. (C) 企业，公司；事业心", "english": "enterprise", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有事业心的，有进取心的", "english": "enterprising", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使快乐；给...娱乐，招待", "english": "entertain", "type": "单词", "keyWords": [] },
    { "chinese": "用...款待某人", "english": "entertain sb. with sth.", "type": "短语", "keyWords": ["entertain"] },
    { "chinese": "a. 引起乐趣的", "english": "entertaining", "type": "单词", "keyWords": [] },
    { "chinese": "一个有趣的故事", "english": "an entertaining story", "type": "短语", "keyWords": ["entertaining"] },
    { "chinese": "街头表演者", "english": "street entertainer", "type": "短语", "keyWords": ["entertain"] },
    { "chinese": "n. (U) 娱乐；招待；(C) 演出", "english": "entertainment", "type": "单词", "keyWords": [] },
    { "chinese": "音乐演奏会", "english": "a musical entertainment", "type": "短语", "keyWords": ["entertainment"] },
    { "chinese": "我感到最有趣（的是）...", "english": "much to my entertainment", "type": "短语", "keyWords": ["entertainment"] },
    { "chinese": "n. (C) 表演者；款待者", "english": "entertainer", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 热情，热心", "english": "enthusiasm", "type": "单词", "keyWords": [] },
    { "chinese": "a. 热心的，满腔热情的", "english": "enthusiastic", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 热心地，满腔热情地", "english": "enthusiastically", "type": "单词", "keyWords": [] },
    { "chinese": "a. 整个的；全部的", "english": "entire", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 完全地，全然地，一概地", "english": "entirely", "type": "单词", "keyWords": [] },
    { "chinese": "v. 给...权利（或资格）；给（书、文章等）题名；给...称号，冠名", "english": "entitle", "type": "单词", "keyWords": [] },
    { "chinese": "每个公民都有权依法受同等保护。", "english": "Every citizen is entitled to (prep.) equal protection under the law.", "type": "句子", "keyWords": ["entitle"] },
    { "chinese": "你没有资格乘坐头等（车厢、舱位等）。", "english": "You are not entitled to travel first class.", "type": "句子", "keyWords": ["entitle"] },
    { "chinese": "这篇社论的题目是《...》。", "english": 'The editorial is entitled "...".', "type": "句子", "keyWords": ["entitle"] },
    { "chinese": "n. (C) 进入；入口（处）；门口；入学（或入会、入场）", "english": "entrance", "type": "单词", "keyWords": [] },
    { "chinese": "在...入口", "english": "at the entrance to", "type": "短语", "keyWords": ["entrance"] },
    { "chinese": "大学入学考试", "english": "college entrance examination", "type": "短语", "keyWords": ["entrance"] },
    { "chinese": "n. (C) 登录；词目；进入（许可）；入口", "english": "entry", "type": "单词", "keyWords": [] },
    { "chinese": "（词典中的）词条", "english": "word entry", "type": "短语", "keyWords": ["entry"] },
    { "chinese": "他们的参战改变了整个局势。", "english": "Their entry into the war changed the whole situation.", "type": "句子", "keyWords": ["entry"] },
    { "chinese": "n. (C) 信封；封套", "english": "envelope", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 环境", "english": "environment", "type": "单词", "keyWords": [] },
    { "chinese": "a. 周围的，环境的", "english": "environmental", "type": "单词", "keyWords": [] },
    { "chinese": "环境友善的，无损于环境的", "english": "environment-friendly", "type": "短语", "keyWords": ["environment"] },
    { "chinese": "v. 羡慕，嫉妒", "english": "envy", "type": "单词", "keyWords": [] },
    { "chinese": "n. U 羡慕；(the) 妒忌的对象", "english": "envy n.", "type": "短语", "keyWords": ["envy"] },
    { "chinese": "成为...的羡慕目标", "english": "be the envy of sb.", "type": "短语", "keyWords": ["envy"] },
    { "chinese": "出于嫉妒或羡慕", "english": "out of envy", "type": "短语", "keyWords": ["envy"] },
    { "chinese": "羡慕某人某物", "english": "envy sb. sth.", "type": "短语", "keyWords": ["envy"] },
    { "chinese": "我真是羡慕你的才能哟！", "english": "How I envy you your talent!", "type": "句子", "keyWords": ["envy"] },
    { "chinese": "a. 流行的；传染的", "english": "epidemic", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) （风尚等的）流行；流行病", "english": "epidemic n.", "type": "短语", "keyWords": ["epidemic"] },
    { "chinese": "a. 相等的；平等的", "english": "equal", "type": "单词", "keyWords": [] },
    { "chinese": "v. 等于，跟...相同；比得上", "english": "equal v.", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "n. (C) 等同的事物（或量）；对手；匹敌；同辈", "english": "equal n.", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "ad. 相等地，平等地", "english": "equally", "type": "单词", "keyWords": [] },
    { "chinese": "和...相等的，等同的；胜任...", "english": "be equal to...", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "他有足够的能力管理这个部门。", "english": "He is quite equal to the task of running the office.", "type": "句子", "keyWords": ["equal"] },
    { "chinese": "他和我力气相等，但智力不同。", "english": "He equals me in strength but not in intelligence.", "type": "句子", "keyWords": ["equal"] },
    { "chinese": "与那些和你差不多或比你更好的人交往", "english": "mix with one's equals and betters", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "在音乐方面没有人比得上", "english": "have no equal in music", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "n. (U) 等同性，同等；平等，相等", "english": "equality", "type": "单词", "keyWords": [] },
    { "chinese": "n. (the) 赤道", "english": "equator", "type": "单词", "keyWords": [] },
    { "chinese": "v. 配备；使有准备", "english": "equip", "type": "单词", "keyWords": [] },
    { "chinese": "供给某人某物", "english": "equip sb. with sth.", "type": "短语", "keyWords": ["equip"] },
    { "chinese": "我们使孩子们受到良好的教育。", "english": "We equip our children with a good education.", "type": "句子", "keyWords": ["equip"] },
    { "chinese": "装有自动计时器的照相机", "english": "a camera equipped with a self-timer", "type": "短语", "keyWords": ["equip"] },
    { "chinese": "准备做某事", "english": "be equipped to do sth.", "type": "短语", "keyWords": ["equip"] },
    { "chinese": "我有充分的准备去处理局势。", "english": "I was well equipped to deal with the situation.", "type": "句子", "keyWords": ["equip"] },
    { "chinese": "设备完善的；充分准备的", "english": "well/ fully-equipped", "type": "短语", "keyWords": ["equip"] },
    { "chinese": "n. (U) 装备；设备", "english": "equipment", "type": "单词", "keyWords": [] },
    { "chinese": "办公设备", "english": "office equipment", "type": "短语", "keyWords": ["equipment"] },
    { "chinese": "a. （价值、效果、意义等）相当的；对等的", "english": "equivalent", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 相等物；等价物；等量物；对应词", "english": "equivalent n.", "type": "短语", "keyWords": ["equivalent"] },
    { "chinese": "同等学历", "english": "equivalent education", "type": "短语", "keyWords": ["equivalent"] },
    { "chinese": "沉默有时等于同意。", "english": "Silence is sometimes equivalent to agreement.", "type": "句子", "keyWords": ["equivalent"] },
    { "chinese": "你能找出与那个词相对应的汉语吗？", "english": "Could you find a Chinese equivalent for that word?", "type": "句子", "keyWords": ["equivalent"] },
    { "chinese": "interj. 呃；嗯", "english": "er", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 时代，纪元", "english": "era", "type": "单词", "keyWords": [] },
    { "chinese": "一个新的和平时代来临。", "english": "A new era of peace began.", "type": "句子", "keyWords": ["era"] },
    { "chinese": "n. (C) 擦除器（尤指墨水消除剂、黑板擦、橡皮、刮字刀等）", "english": "eraser", "type": "单词", "keyWords": [] },
    { "chinese": "v. 抹去；擦掉；消磁；[计]清除", "english": "erase", "type": "单词", "keyWords": [] },
    { "chinese": "v. 建造；树立", "english": "erect", "type": "单词", "keyWords": [] },
    { "chinese": "a. 直立的，挺直的；竖起的；垂直的", "english": "erect a.", "type": "短语", "keyWords": ["erect"] },
    { "chinese": "建造一座摩天大厦", "english": "erect a skyscraper", "type": "短语", "keyWords": ["erect"] },
    { "chinese": "建立一种哲学体系", "english": "erect a philosophical system", "type": "短语", "keyWords": ["erect"] },
    { "chinese": "n. (C) 错误；差错", "english": "error", "type": "单词", "keyWords": [] },
    { "chinese": "v. 喷出；vi. （火山等）爆发；喷发", "english": "erupt", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 喷发", "english": "eruption", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 自动扶梯", "english": "escalator", "type": "单词", "keyWords": [] },
    { "chinese": "v. 逃避；避免；被忘掉", "english": "escape", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 逃脱；溜走；（气体等）泄漏，逸出", "english": "escape vi.", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "n. (C) 逃跑；泄漏；出口", "english": "escape n.", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "避免做某事；逃避/逃脱某事", "english": "escape doing sth.", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "他九死一生。", "english": "He narrowly escaped death.", "type": "句子", "keyWords": ["escape"] },
    { "chinese": "逃过某人的注意", "english": "escape one's attention/ notice", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "（从监狱等地方）逃跑；逃脱", "english": "escape/ make one's escape from (prison...)", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "我不记得他的名字了。/他的名字被我忘掉了。", "english": "His name escaped me./ His name escaped my memory.", "type": "句子", "keyWords": ["escape"] },
    { "chinese": "九死一生，幸免于难", "english": "a narrow escape", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "一个在逃犯", "english": "an escaped prisoner", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "a. 特别的，特殊的（尤指优于、高于、超出于）", "english": "especial", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 尤其；特别", "english": "especially", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 短文，论说文；散文；小品文，随笔", "english": "essay", "type": "单词", "keyWords": [] },
    { "chinese": "a. 绝对必要的（侧重指不可缺少）；基本的，实质的", "english": "essential", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 必要地；实质上；从根本上说", "english": "essentially", "type": "单词", "keyWords": [] },
    { "chinese": "对...必要的；必不可少的", "english": "be essential to...", "type": "短语", "keyWords": ["essential"] },
    { "chinese": "n. (U) 基本，本质；精髓", "english": "essence", "type": "单词", "keyWords": [] },
    { "chinese": "v. （稳固地）建立；确定/立；使立足", "english": "establish", "type": "单词", "keyWords": [] },
    { "chinese": "一个建立了他的声望的发现", "english": "a discovery that established his reputation", "type": "短语", "keyWords": ["establish"] },
    { "chinese": "确立了自己/某人（律师）的地位", "english": "establish oneself/ sb. as (a lawyer)", "type": "短语", "keyWords": ["establish"] },
    { "chinese": "建立联系", "english": "establish a link/ connection", "type": "短语", "keyWords": ["establish"] },
    { "chinese": "a. 已制定的，确定的", "english": "established", "type": "单词", "keyWords": [] },
    { "chinese": "既定事实", "english": "an established fact", "type": "短语", "keyWords": ["established"] },
    { "chinese": "成规", "english": "an established rule", "type": "短语", "keyWords": ["established"] },
    { "chinese": "n. (U) 建立，设立；(C) 已建立的机构", "english": "establishment", "type": "单词", "keyWords": [] },
    { "chinese": "v. 估计；评价；判断（只是猜测，甚至只是一种想法）", "english": "estimate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 估计；判断", "english": "estimation", "type": "单词", "keyWords": [] },
    { "chinese": "v. 低估；看轻", "english": "underestimate", "type": "单词", "keyWords": [] }
];
