const qgl137_144 = [
    { "chinese": "vt. 设想；想象", "english": "imagine", "type": "单词", "keyWords": [] },
    { "chinese": "设想某人做某事", "english": "imagine sb. doing", "type": "短语", "keyWords": ["imagine"] },
    { "chinese": "设想某人是/已经…", "english": "imagine sb. to be/imagine sb. to have done sth.", "type": "短语", "keyWords": ["imagine"] },
    { "chinese": "设想你住在荒岛上", "english": "imagine yourself to be/living on a desert island", "type": "短语", "keyWords": ["imagine"] },
    { "chinese": "vt. 模仿；仿效", "english": "imitate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]模仿；仿效", "english": "imitation", "type": "单词", "keyWords": [] },
    { "chinese": "a. 即刻的；直接的；紧接的", "english": "immediate", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 立即；直接地；conj. 一…就…", "english": "immediately", "type": "单词", "keyWords": [] },
    { "chinese": "a. 无限的，无穷尽的；巨大的，广大的", "english": "immense", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]移民，侨民", "english": "immigrant", "type": "单词", "keyWords": [] },
    { "chinese": "vi./vt. (使)作为移民入境定居", "english": "immigrate", "type": "单词", "keyWords": [] },
    { "chinese": "a. 未成年的/未成熟的", "english": "immature", "type": "单词", "keyWords": [] },
    { "chinese": "a. 不道德的", "english": "immoral", "type": "单词", "keyWords": [] },
    { "chinese": "a. 不礼貌的", "english": "impolite", "type": "单词", "keyWords": [] },
    { "chinese": "a. 不谦虚的", "english": "immodest", "type": "单词", "keyWords": [] },
    { "chinese": "n. 不耐烦/焦急", "english": "impatience", "type": "单词", "keyWords": [] },
    { "chinese": "a. 免疫(性)的；有免疫力的(from)", "english": "immune", "type": "单词", "keyWords": [] },
    { "chinese": "不受天/花感染", "english": "be immune from smallpox", "type": "短语", "keyWords": ["immune"] },
    { "chinese": "n. [U](可加a/an)(较强烈的)影响，作用；冲击；撞击；v. 冲击；撞击；影响", "english": "impact", "type": "单词", "keyWords": [] },
    { "chinese": "对…产生影响", "english": "have a/an...impact/effect on", "type": "短语", "keyWords": ["impact"] },
    { "chinese": "a. 不耐烦的", "english": "impatient", "type": "单词", "keyWords": [] },
    { "chinese": "对某人不耐烦", "english": "be impatient with sb.", "type": "短语", "keyWords": ["impatient"] },
    { "chinese": "a. 帝国的", "english": "imperial", "type": "单词", "keyWords": [] },
    { "chinese": "御花园", "english": "imperial gardens", "type": "短语", "keyWords": ["imperial"] },
    { "chinese": "帝国饭店", "english": "Imperial Hotel", "type": "短语", "keyWords": ["imperial"] },
    { "chinese": "a. 非个人的；没有人情味的", "english": "impersonal", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 非个人地；没有人情味地", "english": "impersonally", "type": "单词", "keyWords": [] },
    { "chinese": "非人力", "english": "impersonal forces", "type": "短语", "keyWords": ["impersonal"] },
    { "chinese": "非人称代词", "english": "impersonal pronouns", "type": "短语", "keyWords": ["impersonal"] },
    { "chinese": "n. [C]工具；用具；v. 执行，履行(契约)；落实(政策)；贯彻", "english": "implement", "type": "单词", "keyWords": [] },
    { "chinese": "园艺工具", "english": "a gardening implement", "type": "短语", "keyWords": ["implement"] },
    { "chinese": "执行公司规章制度", "english": "implement company policies", "type": "短语", "keyWords": ["implement"] },
    { "chinese": "vt. 暗示；含···的意思", "english": "imply", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]含意；暗示", "english": "implication", "type": "单词", "keyWords": [] },
    { "chinese": "你那话暗指什么?", "english": "What do you imply by that?", "type": "句子", "keyWords": ["imply"] },
    { "chinese": "n. (常pl.)进口物；进口产品；n. [U]进口；v. 输入；进口", "english": "import", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]重要(性)", "english": "importance", "type": "单词", "keyWords": [] },
    { "chinese": "a. 重要的", "english": "important", "type": "单词", "keyWords": [] },
    { "chinese": "重视", "english": "attach importance to...", "type": "短语", "keyWords": ["importance"] },
    { "chinese": "无关紧要的事", "english": "a matter of no importance", "type": "短语", "keyWords": ["importance"] },
    { "chinese": "对于…说是重要的", "english": "(be) of great importance to sb./sth.=(be) important to sb./sth.", "type": "短语", "keyWords": ["importance", "important"] },
    { "chinese": "v. 征收(税等)；把….盈加给(on/ upon)；欺骗；施加影响；利用，占便宜；强加于(on/upon)(常指施加不当的压力)", "english": "impose", "type": "单词", "keyWords": [] },
    { "chinese": "对酒类征收新税", "english": "impose new duties on wines", "type": "短语", "keyWords": ["impose"] },
    { "chinese": "自己不想要的事物,不要强加给别人。", "english": "Don't impose on others what you do not desire yourself.", "type": "句子", "keyWords": ["impose"] },
    { "chinese": "你利用了他的忠厚。", "english": "You have imposed on his good nature.", "type": "句子", "keyWords": ["impose"] },
    { "chinese": "a. 壮观的；不凡的", "english": "imposing", "type": "单词", "keyWords": [] },
    { "chinese": "仪表堂堂", "english": "an imposing appearance", "type": "短语", "keyWords": ["imposing"] },
    { "chinese": "a. 不可能的", "english": "impossible", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]不可能；n. [C]不可能的事", "english": "impossibility", "type": "单词", "keyWords": [] },
    { "chinese": "某人做某事是不可能的/必要的/重要的", "english": "It is impossible/necessary/important for sb. to do sth.", "type": "句子", "keyWords": ["impossible", "necessary", "important"] },
    { "chinese": "做办不到的事", "english": "do the impossible", "type": "短语", "keyWords": ["impossible"] },
    { "chinese": "vt. 在·打上记号；给·深刻的印象", "english": "impress", "type": "单词", "keyWords": [] },
    { "chinese": "a. 给人印象深刻的", "english": "impressive", "type": "单词", "keyWords": [] },
    { "chinese": "在表面上打记号", "english": "impress sth. (up) on/upon sth.", "type": "短语", "keyWords": ["impress"] },
    { "chinese": "把…铭记在心", "english": "impress sth. in one's memory/upon one's mind/on sb.", "type": "短语", "keyWords": ["impress"] },
    { "chinese": "我父亲让我铭记艰苦劳动的价值。", "english": "My father impressed on me the value of hard work.", "type": "句子", "keyWords": ["impress"] },
    { "chinese": "他给我的印象是他非常粗鲁。", "english": "He impressed/struck me as (being) very rude.", "type": "句子", "keyWords": ["impress"] },
    { "chinese": "被…所感动", "english": "be impressed by/with/at...", "type": "短语", "keyWords": ["impress"] },
    { "chinese": "n. [C]印象；压印/痕；印记", "english": "impression", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]印象派艺术家；a. 印象主义的，印象派的", "english": "impressionist", "type": "单词", "keyWords": [] },
    { "chinese": "给人留下好/坏印象", "english": "give a person a good/bad impression", "type": "短语", "keyWords": ["impression"] },
    { "chinese": "给某人留下印象；给人…以影响", "english": "produce/make/leave a (deep) impression on sb.", "type": "短语", "keyWords": ["impression"] },
    { "chinese": "你对他的第一印象如何?/他给你的第一印象怎样?", "english": "What's your first impression of him?", "type": "句子", "keyWords": ["impression"] },
    { "chinese": "prep.在…内（里面、中）；（表示时间）在…之内，在…之后；（表示状态、情况）处在…中；在…方面；在…过程中；按照…；ad.朝里，向内；在家", "english": "in", "type": "单词", "keyWords": [] },
    { "chinese": "在远处", "english": "in the distance", "type": "短语", "keyWords": ["in"] },
    { "chinese": "立刻，一会儿后", "english": "in a minute", "type": "短语", "keyWords": ["in"] },
    { "chinese": "立刻", "english": "in no time", "type": "短语", "keyWords": ["in"] },
    { "chinese": "在进行中", "english": "in progress", "type": "短语", "keyWords": ["in"] },
    { "chinese": "画油画", "english": "paint in oils", "type": "短语", "keyWords": ["in"] },
    { "chinese": "围成圆圈", "english": "in a circle", "type": "短语", "keyWords": ["in"] },
    { "chinese": "戴着镣铐", "english": "in irons", "type": "短语", "keyWords": ["in"] },
    { "chinese": "在20世纪80年代", "english": "in the 1980s/1980°s", "type": "短语", "keyWords": ["in"] },
    { "chinese": "十之八九", "english": "nine in ten", "type": "短语", "keyWords": ["in"] },
    { "chinese": "披着羊皮的狼", "english": "a wolf in sheep's skin", "type": "短语", "keyWords": ["in"] },
    { "chinese": "三言两语，简而言之", "english": "in a few words", "type": "短语", "keyWords": ["in"] },
    { "chinese": "符合人民利益", "english": "in the interests of the people", "type": "短语", "keyWords": ["in"] },
    { "chinese": "在某人快60岁时", "english": "in one's late fifties", "type": "短语", "keyWords": ["in"] },
    { "chinese": "a.不充分的；不适当的", "english": "inadequate", "type": "单词", "keyWords": [] },
    { "chinese": "a.达不到的；难办的；不可接近的；进不去的；难得到的", "english": "inaccessible", "type": "单词", "keyWords": [] },
    { "chinese": "对于…来说，某事/某物是不可接近的", "english": "sth. is inaccessible to...", "type": "短语", "keyWords": ["inaccessible"] },
    { "chinese": "大雪使车辆到不了那个山村。", "english": "Heavy snow made the mountain village inaccessible to traffic.", "type": "句子", "keyWords": ["inaccessible"] },
    { "chinese": "n.[C]英寸", "english": "inch", "type": "单词", "keyWords": [] },
    { "chinese": "得寸进尺。", "english": "Give him an inch and he'll take a mile.", "type": "句子", "keyWords": ["inch"] },
    { "chinese": "n.[C]事变；事件；（政治性）事故；偶发事件；事件的附随事件，小事件", "english": "incident", "type": "单词", "keyWords": [] },
    { "chinese": "v.使（某人）倾向于", "english": "incline", "type": "单词", "keyWords": [] },
    { "chinese": "倾向于；爱做某事；想要做某事（近tend to do sth.）", "english": "be inclined to do sth.", "type": "短语", "keyWords": ["incline"] },
    { "chinese": "v.包括", "english": "include", "type": "单词", "keyWords": [] },
    { "chinese": "a.包括在内的", "english": "included", "type": "单词", "keyWords": [] },
    { "chinese": "价格14.90美元，邮资包括在内。", "english": "Price $14.90, postage included.", "type": "句子", "keyWords": ["include", "included"] },
    { "chinese": "他事事调查，巨细无遗。", "english": "He includes everything in his survey.", "type": "句子", "keyWords": ["include"] },
    { "chinese": "prep.包括，包含（=inclusive of）", "english": "including", "type": "单词", "keyWords": [] },
    { "chinese": "我们全体，包括我在内", "english": "all of us including me(=me included)", "type": "短语", "keyWords": ["including", "included"] },
    { "chinese": "n.[C]收入，所得；收益", "english": "income", "type": "单词", "keyWords": [] },
    { "chinese": "每月有一小笔/大笔收入", "english": "have a small/large income a month", "type": "短语", "keyWords": ["income"] },
    { "chinese": "a.无可比拟的", "english": "incomparable", "type": "单词", "keyWords": [] },
    { "chinese": "a.不完全的，不完整的", "english": "incomplete", "type": "单词", "keyWords": [] },
    { "chinese": "a.不称职的；不适当的，不胜任的；无能的", "english": "incompetent", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]不称职；无能", "english": "incompetence", "type": "单词", "keyWords": [] },
    { "chinese": "a.不方便的(o sb.)", "english": "inconvenient", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]不方便；n.[C]为难之处，麻烦事", "english": "inconvenience", "type": "单词", "keyWords": [] },
    { "chinese": "我不方便做某事", "english": "It is inconvenient for me to do sth.", "type": "句子", "keyWords": ["inconvenient"] },
    { "chinese": "vt./vi./n.[C]增加；增长", "english": "increase", "type": "单词", "keyWords": [] },
    { "chinese": "a.已增长的/正在增长的", "english": "increased/increasing", "type": "单词", "keyWords": [] },
    { "chinese": "ad.越来越…", "english": "increasingly", "type": "单词", "keyWords": [] },
    { "chinese": "不断增长的需求", "english": "the increasing demand", "type": "短语", "keyWords": ["increase", "increasing"] },
    { "chinese": "不断增长；正在增加（反on the decrease）", "english": "be on the increase/rise", "type": "短语", "keyWords": ["increase"] },
    { "chinese": "重要性增加", "english": "increase in importance", "type": "短语", "keyWords": ["increase"] },
    { "chinese": "已涨的价格", "english": "the increased prices", "type": "短语", "keyWords": ["increase", "increased"] },
    { "chinese": "升值/涨价", "english": "increase in value/price", "type": "短语", "keyWords": ["increase"] },
    { "chinese": "adj.不可信的；难以置信的，不可思议的；[口]妙极的", "english": "incredible", "type": "单词", "keyWords": [] },
    { "chinese": "ad.的确，真正", "english": "indeed", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]独立；自主", "english": "independence", "type": "单词", "keyWords": [] },
    { "chinese": "宣告独立", "english": "declare independence", "type": "短语", "keyWords": ["independence"] },
    { "chinese": "a.独立的；自主的；ad.独立地", "english": "independent", "type": "单词", "keyWords": [] },
    { "chinese": "不依赖别人的；（经济上）独立的；有独立见解的", "english": "be independent of", "type": "短语", "keyWords": ["independent"] },
    { "chinese": "她在经济上不依赖家庭而自立。", "english": "She is financially independent of her family.", "type": "句子", "keyWords": ["independent"] },
    { "chinese": "a.印度的；印度人的；印第安人的；印第安文化的；西印度群岛的", "english": "Indian", "type": "单词", "keyWords": [] },
    { "chinese": "vt.表示；象征", "english": "indicate", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]迹象；n.[U]表明；说明", "english": "indication", "type": "单词", "keyWords": [] },
    { "chinese": "a.个人的；个体的；个性的；个别的；单独的；n.[C]个人；个体", "english": "individual", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]个性；特点", "english": "individuality", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]个人主义", "english": "individualism", "type": "单词", "keyWords": [] },
    { "chinese": "个人/集体体育运动项目", "english": "individual/collective sports", "type": "短语", "keyWords": ["individual"] },
    { "chinese": "ad.在室内（反outdoors）", "english": "indoors", "type": "单词", "keyWords": [] },
    { "chinese": "a.室内的（反outdoor）", "english": "indoor", "type": "单词", "keyWords": [] },
    { "chinese": "a.工业的；产业的", "english": "industrial", "type": "单词", "keyWords": [] },
    { "chinese": "v.使工业化；vi.实现工业化", "english": "industrialize", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]（总称）工业；n.[C]某类工业；行业", "english": "industry", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]勤奋；勤劳", "english": "industry", "type": "单词", "keyWords": [] },
    { "chinese": "a.勤恳的，刻苦的", "english": "industrious", "type": "单词", "keyWords": [] },
    { "chinese": "a.不可避免的；不可逃避的；必然（发生）的（近unavoidable）", "english": "inevitable", "type": "单词", "keyWords": [] },
    { "chinese": "a.不精确的；不准确的", "english": "inexact", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]婴幼儿；幼儿；a.幼儿的；幼小的，幼稚的；初期的", "english": "infant", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]幼年时候；初期", "english": "infancy", "type": "单词", "keyWords": [] },
    { "chinese": "a.非正式的", "english": "informal", "type": "单词", "keyWords": [] },
    { "chinese": "非正式语体", "english": "an informal style", "type": "短语", "keyWords": ["informal"] },
    { "chinese": "非正式访问", "english": "an informal visit", "type": "短语", "keyWords": ["informal"] },
    { "chinese": "a.提供消息的", "english": "informative", "type": "单词", "keyWords": [] },
    { "chinese": "资料丰富的书", "english": "an informative book", "type": "短语", "keyWords": ["informative"] },
    { "chinese": "n.[C]（混合物的）组成部分，成分；（烹调的）原料", "english": "ingredient", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]居民", "english": "inhabitant", "type": "单词", "keyWords": [] },
    { "chinese": "vt.居住于；栖息", "english": "inhabit", "type": "单词", "keyWords": [] },
    { "chinese": "a.适于居住的", "english": "inhabitable", "type": "单词", "keyWords": [] },
    { "chinese": "住在城市", "english": "inhabit a city", "type": "短语", "keyWords": ["inhabit"] },
    { "chinese": "沙漠中的居住者", "english": "inhabitants of the desert", "type": "短语", "keyWords": ["inhabitant"] },
    { "chinese": "v.继承；经遗传得到", "english": "inherit", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]遗传；继承；n.[C]遗产；继承物", "english": "inheritance", "type": "单词", "keyWords": [] },
    { "chinese": "从…处继承", "english": "inherit sth. from sb.", "type": "短语", "keyWords": ["inherit"] },
    { "chinese": "a.开始的；最初的", "english": "initial", "type": "单词", "keyWords": [] },
    { "chinese": "v.开始（实施）；发起；创始", "english": "initiate", "type": "单词", "keyWords": [] },
    { "chinese": "在初期，在开始阶段", "english": "in the initial stage", "type": "短语", "keyWords": ["initial"] },
    { "chinese": "着手改革/开始攻击", "english": "initiate a reform/an attack", "type": "短语", "keyWords": ["initiate"] },
    { "chinese": "n.[U]主动的行动；倡议；进取心；首创精神；主动性", "english": "initiative", "type": "单词", "keyWords": [] },
    { "chinese": "缺少首创精神", "english": "lack initiative", "type": "短语", "keyWords": ["initiative"] },
    { "chinese": "v.注射", "english": "inject", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](U)注射；n.[C]注射剂，注射液；针药", "english": "injection", "type": "单词", "keyWords": [] },
    { "chinese": "把青霉素注入血液", "english": "inject penicillin into the bloodstream", "type": "短语", "keyWords": ["inject"] },
    { "chinese": "给党注入新的活力", "english": "inject some new life into the Party", "type": "短语", "keyWords": ["inject"] },
    { "chinese": "v.伤害；损伤", "english": "injure", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]伤害；n.[C]损伤；受伤处", "english": "injury", "type": "单词", "keyWords": [] },
    { "chinese": "受了重伤", "english": "be badly injured", "type": "短语", "keyWords": ["injure"] },
    { "chinese": "伤害某人的自尊心", "english": "injure one's pride", "type": "短语", "keyWords": ["injure"] },
    { "chinese": "n.[U]不公正，不公平；非正义；n.[C]不公正的行为", "english": "injustice", "type": "单词", "keyWords": [] },
    { "chinese": "v.推论；推断(from)", "english": "infer", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]推理，推论；推断；n.[C]推断的结果；结论", "english": "inference", "type": "单词", "keyWords": [] },
    { "chinese": "a.（身份）低下的，下级的；（质量等）低劣的，次的（反superior）；n.[C]（身份）低于他人者；下级；次品", "english": "inferior", "type": "单词", "keyWords": [] },
    { "chinese": "不及某人（近be senior/junior to...）", "english": "be inferior to sb.", "type": "短语", "keyWords": ["inferior"] },
    { "chinese": "n.[U]下级；次级，低级，劣等；自卑感", "english": "inferiority", "type": "单词", "keyWords": [] },
    { "chinese": "v.影响；n.[C](U]影响（力）；n.[C]有影响的人物/事物", "english": "influence", "type": "单词", "keyWords": [] },
    { "chinese": "对…有影响", "english": "have an influence/effect/impact on", "type": "短语", "keyWords": ["influence"] },
    { "chinese": "在…的影响下", "english": "under the influence of...", "type": "短语", "keyWords": ["influence"] },
    { "chinese": "天气对作物的影响", "english": "the influence of the climate on crops", "type": "短语", "keyWords": ["influence"] },
    { "chinese": "a.有影响力的", "english": "influential", "type": "单词", "keyWords": [] },
    { "chinese": "v.通知；告知", "english": "inform", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]信息；情报；资料", "english": "information", "type": "单词", "keyWords": [] },
    { "chinese": "把某事通知某人", "english": "inform sb. of sth.", "type": "短语", "keyWords": ["inform"] },
    { "chinese": "我知道这项决定时，已经太迟了。", "english": "I wasn't informed of the decision until too late.", "type": "句子", "keyWords": ["inform"] },
    { "chinese": "使某人及时得到通知；及时通知某人", "english": "keep sb. informed (of...", "type": "短语", "keyWords": ["inform"] },
    { "chinese": "a.清白的；无罪的；无辜的", "english": "innocent", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]无罪；清白；单纯，天真无邪", "english": "innocence", "type": "单词", "keyWords": [] },
    { "chinese": "装出无辜受牵连的样子", "english": "put on an air of injured innocence", "type": "短语", "keyWords": ["innocent", "innocence"] },
    { "chinese": "n.[C]/[U]创新，革新；改革；新方法", "english": "innovation", "type": "单词", "keyWords": [] },
    { "chinese": "vi.革新，改革；vt.创始", "english": "innovate", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]放入物；投入的资金，成本；n.[U]输入；v.（计算机）输入", "english": "input", "type": "单词", "keyWords": [] },
    { "chinese": "vi./vt.询问；打听；查究", "english": "inquire", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]询问；打听；调查", "english": "inquiry", "type": "单词", "keyWords": [] },
    { "chinese": "询问；查究；打听（价格）（近ask about）", "english": "inquire about (prices)", "type": "短语", "keyWords": ["inquire"] },
    { "chinese": "问候（健康或状况）（近ask after）", "english": "inquire after sb.", "type": "短语", "keyWords": ["inquire"] },
    { "chinese": "她问候了你母亲。", "english": "She inquired after your mother/your mother's health.", "type": "句子", "keyWords": ["inquire"] },
    { "chinese": "调查腐败的程度（近look into）", "english": "inquire into the extent of the corruption", "type": "短语", "keyWords": ["inquire"] },
    { "chinese": "询问某事（近inquire about）", "english": "make inquiries about sth.", "type": "短语", "keyWords": ["inquire"] },
    { "chinese": "vt. 插入，嵌入；插(话等)；添加", "english": "insert", "type": "单词", "keyWords": [] },
    { "chinese": "把钥匙插到锁里", "english": "insert the key in the lock", "type": "短语", "keyWords": ["insert"] },
    { "chinese": "在文本中插入一幅插图", "english": "insert an illustration into a text", "type": "短语", "keyWords": ["insert"] },
    { "chinese": "prep. 在…里面；在…之内；a. 内部的；ad. 在里面；往里面；n. [C]里面，内部", "english": "inside", "type": "单词", "keyWords": [] },
    { "chinese": "里面翻到外面", "english": "inside out(ad)", "type": "短语", "keyWords": ["inside"] },
    { "chinese": "把衬衫反过来穿", "english": "wear the shirt inside out", "type": "短语", "keyWords": ["inside"] },
    { "chinese": "v./vi. 坚持；坚决认为(或主张)(on, upon)", "english": "insist", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]坚持，坚决主张", "english": "insistence", "type": "单词", "keyWords": [] },
    { "chinese": "坚持认为；坚持要求", "english": "insist on sth./ doing sth.", "type": "短语", "keyWords": ["insist"] },
    { "chinese": "我坚持要求他和我们一起来。", "english": "I insisted on his coming with us.", "type": "句子", "keyWords": ["insist"] },
    { "chinese": "他坚持每个人应该参加晚会。", "english": "He insisted that everyone should come to the party.", "type": "句子", "keyWords": ["insist"] },
    { "chinese": "他坚持认为他是对的。", "english": "He insisted that he was right.", "type": "句子", "keyWords": ["insist"] },
    { "chinese": "v./vi. 检查；检阅；视察", "english": "inspect", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]检查；检阅；视察", "english": "inspection", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 鼓舞；激发；使生灵感，使感悟", "english": "inspire", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]（诗人的）灵感；鼓舞，激励", "english": "inspiration", "type": "单词", "keyWords": [] },
    { "chinese": "a. 使人/感到鼓舞的", "english": "inspiring/inspired", "type": "单词", "keyWords": [] },
    { "chinese": "鼓励某人做某事(近encourage sb. to do sth.)", "english": "inspire sb. to do sth.", "type": "短语", "keyWords": ["inspire"] },
    { "chinese": "v. 安装", "english": "install", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]例子", "english": "instance", "type": "单词", "keyWords": [] },
    { "chinese": "例如；比如", "english": "for instance", "type": "短语", "keyWords": ["instance"] },
    { "chinese": "n. [C]时刻；瞬息，瞬间；a. 立刻的；速食的；速溶的；紧急的", "english": "instant", "type": "单词", "keyWords": [] },
    { "chinese": "立刻，马上", "english": "in an instant = in a moment", "type": "短语", "keyWords": ["instant"] },
    { "chinese": "我一时答不上来。", "english": "I couldn't answer for an instant/ for a moment.", "type": "句子", "keyWords": ["instant"] },
    { "chinese": "一…就…", "english": "the instant(the moment/the minute/immediately/instantly/directly)", "type": "短语", "keyWords": ["instant"] },
    { "chinese": "我们一听到警报就立即采取行动。", "english": "The instant we heard the alarm, we took action.", "type": "句子", "keyWords": ["instant"] },
    { "chinese": "ad. 作为替代，顶替；反而", "english": "instead", "type": "单词", "keyWords": [] },
    { "chinese": "代替，而不是…(近take the place of, in place of, replace)", "english": "instead of", "type": "短语", "keyWords": ["instead"] },
    { "chinese": "n. [U]本能；天性；直觉", "english": "instinct", "type": "单词", "keyWords": [] },
    { "chinese": "a. 生来的，天生的；本能的", "english": "instinctive", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 本能地", "english": "instinctively", "type": "单词", "keyWords": [] },
    { "chinese": "有求知的本能", "english": "have an instinct for knowledge", "type": "短语", "keyWords": ["instinct"] },
    { "chinese": "鸟学飞是出于本能。", "english": "Birds learn to fly by instinct.", "type": "句子", "keyWords": ["instinct"] },
    { "chinese": "n. [C]（学院附设的）研究所；学院；协会，学会；专科大学", "english": "institute", "type": "单词", "keyWords": [] },
    { "chinese": "v. 教；教授；讲授；指示；嘱咐；向…说明(侧重“指示；嘱咐”)", "english": "instruct", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]教导者，教员", "english": "instructor", "type": "单词", "keyWords": [] },
    { "chinese": "指导某人做某事", "english": "instruct sb. to do sth. in sth./", "type": "短语", "keyWords": ["instruct"] },
    { "chinese": "n. [U]教学；n. [C]指示；（计算机）指令；（常pl.）用法说明", "english": "instruction", "type": "单词", "keyWords": [] },
    { "chinese": "维护说明", "english": "maintenance instructions", "type": "短语", "keyWords": ["instruction"] },
    { "chinese": "装配玩具的说明", "english": "instructions for assembling the toy", "type": "短语", "keyWords": ["instruction"] },
    { "chinese": "a. 有教育意义的；有启发的；有益的", "english": "instructive", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]仪器；乐器", "english": "instrument", "type": "单词", "keyWords": [] },
    { "chinese": "v. 侮辱；辱骂；危害；n. [C]侮辱；辱骂", "english": "insult", "type": "单词", "keyWords": [] },
    { "chinese": "忍气吞声", "english": "swallow an insult", "type": "短语", "keyWords": ["insult"] },
    { "chinese": "n. [C][U]保险", "english": "insurance", "type": "单词", "keyWords": [] },
    { "chinese": "火灾保险", "english": "fire insurance", "type": "短语", "keyWords": ["insurance"] },
    { "chinese": "人寿保险", "english": "life insurance", "type": "短语", "keyWords": ["insurance"] },
    { "chinese": "vt. 给…保险；给…提供保证；vi.（保户）投保；(保险业者)承保", "english": "insure", "type": "单词", "keyWords": [] },
    { "chinese": "给某物办海上保险", "english": "Insure sth. against loss at sea", "type": "短语", "keyWords": ["insure"] },
    { "chinese": "v. 使成一体，使结合(with, into)；使完整；vi. 成为一体", "english": "integrate", "type": "单词", "keyWords": [] },
    { "chinese": "这些程序能和你的已有的软件整合成一体。", "english": "These programs can be integrated with your existing software.", "type": "句子", "keyWords": ["integrate"] },
    { "chinese": "他解释说：“随着新的观测数据的收集，它们必须被整合到网络中。”", "english": "“As new observations are collected,” he explains, “they must be integrated into the web.”", "type": "句子", "keyWords": ["integrate"] },
    { "chinese": "n.[C][U]智力；n.[C]明智者，有才智的人", "english": "intellect", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]才智；情报；谍报；情报机构", "english": "intelligence", "type": "单词", "keyWords": [] },
    { "chinese": "智商(略作IQ.)", "english": "intelligence quotient", "type": "短语", "keyWords": ["intelligence"] },
    { "chinese": "智力测验", "english": "an intelligence test", "type": "短语", "keyWords": ["intelligence"] },
    { "chinese": "情报所，情报中心", "english": "intelligence centre", "type": "短语", "keyWords": ["intelligence"] },
    { "chinese": "情报人员", "english": "intelligence agent", "type": "短语", "keyWords": ["intelligence"] },
    { "chinese": "a.聪颖的；有才智的(侧重理解力强的，思路清楚且判断准确)", "english": "intelligent", "type": "单词", "keyWords": [] },
    { "chinese": "v.打算；计划(近mean句型)", "english": "intend", "type": "单词", "keyWords": [] },
    { "chinese": "打算做某事", "english": "intend/ mean to do sth.", "type": "短语", "keyWords": ["intend"] },
    { "chinese": "想要某人成为/做某事", "english": "intend/ mean sb. to be/ to do sth.", "type": "短语", "keyWords": ["intend"] },
    { "chinese": "本打算帮忙但是…", "english": "intended to have helped him but... / had intended to help him but...", "type": "短语", "keyWords": ["intend"] },
    { "chinese": "为…准备的；供…用", "english": "be intended/ meant for...", "type": "短语", "keyWords": ["intend"] },
    { "chinese": "本书是为初学者编写的。", "english": "The book is intended for beginners. This is a book which is) intended for beginners.", "type": "句子", "keyWords": ["intend"] },
    { "chinese": "n.[C]意图，目的", "english": "intention", "type": "单词", "keyWords": [] },
    { "chinese": "a.有目的的；故意的", "english": "intentional", "type": "单词", "keyWords": [] },
    { "chinese": "没有意图做某事", "english": "have no intention of doing sth./to do sth.", "type": "短语", "keyWords": ["intention"] },
    { "chinese": "a.强烈的；紧张的；热情的，认真的", "english": "intense", "type": "单词", "keyWords": [] },
    { "chinese": "剧痛", "english": "intense pain", "type": "短语", "keyWords": ["intense"] },
    { "chinese": "酷热", "english": "intense heat", "type": "短语", "keyWords": ["intense"] },
    { "chinese": "a.集中的；深入细致的", "english": "intensive", "type": "单词", "keyWords": [] },
    { "chinese": "精读(反extensive reading泛读)", "english": "intensive reading", "type": "短语", "keyWords": ["intensive"] },
    { "chinese": "n.[C][U]相互作用/影响", "english": "interaction", "type": "单词", "keyWords": [] },
    { "chinese": "vi.相互作用/影响(with)", "english": "interact", "type": "单词", "keyWords": [] },
    { "chinese": "v.使感兴趣；n.[C][U]兴趣；n.[U]利息；n.[C](常pl.)利益", "english": "interest", "type": "单词", "keyWords": [] },
    { "chinese": "津津有味地听", "english": "hear it with great interest", "type": "短语", "keyWords": ["interest"] },
    { "chinese": "无息的", "english": "interest-free", "type": "短语", "keyWords": ["interest"] },
    { "chinese": "对…感兴趣", "english": "show/express/take(an) interest in...", "type": "短语", "keyWords": ["interest"] },
    { "chinese": "在...方面没有兴趣", "english": "have no interest in", "type": "短语", "keyWords": ["interest"] },
    { "chinese": "为了…的利益", "english": "in the interest(s) of sb.", "type": "短语", "keyWords": ["interest"] },
    { "chinese": "(对某人)有/没有/有些兴趣", "english": "(be) of no/little/some interest to sb.", "type": "短语", "keyWords": ["interest"] },
    { "chinese": "我对他们没兴趣。", "english": "They're of no interest to me.", "type": "句子", "keyWords": ["interest"] },
    { "chinese": "今天的报纸上有有趣的内容吗?", "english": "Is there anything of interest in the papers today?", "type": "句子", "keyWords": ["interest"] },
    { "chinese": "a.感兴趣的", "english": "interested", "type": "单词", "keyWords": [] },
    { "chinese": "a.有趣的", "english": "interesting", "type": "单词", "keyWords": [] },
    { "chinese": "表示“在…间；相互”", "english": "inter-", "type": "词缀", "keyWords": [] },
    { "chinese": "a.中等程度的；中间的；(课程等)中级的", "english": "intermediate", "type": "单词", "keyWords": [] },
    { "chinese": "a.内部的；内心的；内在的", "english": "internal", "type": "单词", "keyWords": [] },
    { "chinese": "事物的内部联系", "english": "the internal relations of things", "type": "短语", "keyWords": ["internal"] },
    { "chinese": "n.(the)因特网", "english": "Internet", "type": "单词", "keyWords": [] },
    { "chinese": "v.解释；口译，翻译；阐述；说明", "english": "interpret", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]译员；口译者", "english": "interpreter", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]解释；阐述；口译", "english": "interpretation", "type": "单词", "keyWords": [] },
    { "chinese": "阐明人生的意义", "english": "interpret life", "type": "短语", "keyWords": ["interpret"] },
    { "chinese": "我们认为他的沉默就是拒绝。", "english": "We interpreted his silence as refusal.", "type": "句子", "keyWords": ["interpret"] },
    { "chinese": "同一事实的不同解释", "english": "different interpretations of the same fact", "type": "短语", "keyWords": ["interpret"] },
    { "chinese": "v.打断；打扰", "english": "interrupt", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]中断；遮断；打断；干扰", "english": "interruption", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]间隔；幕间休息", "english": "interval", "type": "单词", "keyWords": [] },
    { "chinese": "每隔一段时间；每隔一段距离", "english": "at intervals", "type": "短语", "keyWords": ["interval"] },
    { "chinese": "他总是间隔一定时间(15天)来看我一次。", "english": "He visits me at regular intervals (of 15 days).", "type": "句子", "keyWords": ["interval"] },
    { "chinese": "v./n.[C]采访；访问；接见；面试", "english": "interview", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]采访者", "english": "interviewer", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]/n.被采访者", "english": "interviewee", "type": "单词", "keyWords": [] },
    { "chinese": "会见某人", "english": "have an interview with sb.", "type": "短语", "keyWords": ["interview"] },
    { "chinese": "亲密朋友", "english": "intimate friends", "type": "短语", "keyWords": ["intimate"] },
    { "chinese": "a.亲密的", "english": "intimate", "type": "单词", "keyWords": [] },
    { "chinese": "a.不宽容的，偏狭的；无法忍受的，难耐的", "english": "intolerant", "type": "单词", "keyWords": [] },
    { "chinese": "v.忍受，容忍", "english": "tolerate", "type": "单词", "keyWords": [] },
    { "chinese": "无法容忍被打断", "english": "be intolerant of interruptions →Interruptions are intolerable.", "type": "句子", "keyWords": ["intolerant"] },
    { "chinese": "prep.到…里；(表示变化、状态、结果)转入，变成", "english": "into", "type": "单词", "keyWords": [] },
    { "chinese": "vt.介绍；引进；提出", "english": "introduce", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](U]介绍；传入；初步；导言", "english": "introduction", "type": "单词", "keyWords": [] },
    { "chinese": "把…介绍给…", "english": "introduce...to...", "type": "短语", "keyWords": ["introduce"] },
    { "chinese": "采用新技术", "english": "introduce new techniques", "type": "短语", "keyWords": ["introduce"] },
    { "chinese": "把…引进；传入；把…列入", "english": "introduce...into...", "type": "短语", "keyWords": ["introduce"] },
    { "chinese": "自我介绍", "english": "introduce oneself", "type": "短语", "keyWords": ["introduce"] },
    { "chinese": "输入外资，引进外资", "english": "introduction of foreign capital", "type": "短语", "keyWords": ["introduction"] },
    { "chinese": "教育导论", "english": "an introduction to education", "type": "短语", "keyWords": ["introduction"] },
    { "chinese": "n.[C]侵入者；闯入者", "english": "intruder", "type": "单词", "keyWords": [] },
    { "chinese": "v.侵入", "english": "intrude", "type": "单词", "keyWords": [] },
    { "chinese": "侵犯隐私", "english": "intrude upon our privacy", "type": "短语", "keyWords": ["intrude"] },
    { "chinese": "v. 侵入；侵略", "english": "invade", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]/[U]入侵", "english": "invasion", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]侵略者；入侵者", "english": "invader", "type": "单词", "keyWords": [] },
    { "chinese": "侵犯某国", "english": "invade a country", "type": "短语", "keyWords": ["invade"] },
    { "chinese": "病菌侵入了机体。", "english": "Germs invaded the organism.", "type": "句子", "keyWords": ["invade"] },
    { "chinese": "a. 无效的；站不住脚的", "english": "invalid", "type": "单词", "keyWords": [] },
    { "chinese": "作废的/无效的执照", "english": "an invalid license", "type": "短语", "keyWords": ["invalid"] },
    { "chinese": "v. 发明；创造", "english": "invent", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]/[U]发明", "english": "invention", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]发明家；发明者", "english": "inventor", "type": "单词", "keyWords": [] },
    { "chinese": "a. 相反的；逆的；翻转的，倒转的", "english": "inverse", "type": "单词", "keyWords": [] },
    { "chinese": "n. [语法]倒装法", "english": "inversion", "type": "单词", "keyWords": [] },
    { "chinese": "v. 投(资)；投入(时间和精力)(in)；vi. 投资(in sth.)", "english": "invest", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]/[U]投资", "english": "investment", "type": "单词", "keyWords": [] },
    { "chinese": "a. 珍贵的；价值无法衡量的", "english": "invaluable", "type": "单词", "keyWords": [] },
    { "chinese": "v. 调查；审查；v. 调查(into)", "english": "investigate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]/[U]调查", "english": "investigation", "type": "单词", "keyWords": [] },
    { "chinese": "在调查中", "english": "be under investigation", "type": "短语", "keyWords": ["investigation"] },
    { "chinese": "进行调查研究(近look/investigate into sth.)", "english": "carry on/conduct an investigation into sth.", "type": "短语", "keyWords": ["investigation"] },
    { "chinese": "a. 看不见的，无形的", "english": "invisible", "type": "单词", "keyWords": [] },
    { "chinese": "肉眼看不见的", "english": "be invisible to the naked eye", "type": "短语", "keyWords": ["invisible"] },
    { "chinese": "某人看不见什么东西", "english": "be invisible to sb.", "type": "短语", "keyWords": ["invisible"] },
    { "chinese": "n. [C]请帖；n. [U]邀请", "english": "invitation", "type": "单词", "keyWords": [] },
    { "chinese": "接受/婉言拒绝(去…的)邀请", "english": "accept/decline an invitation (for sth.)", "type": "短语", "keyWords": ["invitation"] },
    { "chinese": "凭请帖入场。", "english": "Admission is by invitation only.", "type": "句子", "keyWords": ["invitation"] },
    { "chinese": "因我的邀请而来", "english": "come at my invitation/request", "type": "短语", "keyWords": ["invitation"] },
    { "chinese": "未经邀请，没有邀请", "english": "without invitation", "type": "短语", "keyWords": ["invitation"] },
    { "chinese": "v. 邀请", "english": "invite", "type": "单词", "keyWords": [] },
    { "chinese": "a. 吸引人的；诱人的", "english": "inviting", "type": "单词", "keyWords": [] },
    { "chinese": "邀请某人去某处/做某事", "english": "invite sb. to+n./to do sth.", "type": "短语", "keyWords": ["invite"] },
    { "chinese": "邀请作家出席一个会议", "english": "invite writers to a conference", "type": "短语", "keyWords": ["invite"] },
    { "chinese": "桌上的食物看上去令人垂涎。", "english": "The food on the table looks inviting.", "type": "句子", "keyWords": ["invite", "inviting"] },
    { "chinese": "v. 牵扯；包含", "english": "involve", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]/[U]包含，含有；牵连的事务，复杂的情况", "english": "involvement", "type": "单词", "keyWords": [] },
    { "chinese": "需要，包含", "english": "involve doing", "type": "短语", "keyWords": ["involve"] },
    { "chinese": "这工作需要每年去国外两个月。", "english": "The job involves traveling abroad for two months each year.", "type": "句子", "keyWords": ["involve"] },
    { "chinese": "使某人介入/卷入/参加某事(→be/get involved in介入，卷入)", "english": "involve sb. in sth.", "type": "短语", "keyWords": ["involve"] },
    { "chinese": "有关人员", "english": "the people involved", "type": "短语", "keyWords": ["involve"] },
    { "chinese": "复杂的表情", "english": "an involved expression", "type": "短语", "keyWords": ["involve"] },
    { "chinese": "表示“不，非”，用于以r开始的单词", "english": "ir-", "type": "词缀", "keyWords": [] },
    { "chinese": "a. 不负责任的/不可靠的", "english": "irresponsible", "type": "单词", "keyWords": [] },
    { "chinese": "a. 不可逆的/不能翻转的", "english": "irreversible", "type": "单词", "keyWords": [] },
    { "chinese": "a. 不可抗拒的/压制不了的", "english": "irresistible", "type": "单词", "keyWords": [] },
    { "chinese": "a. 非理性的；失去理性的", "english": "irrational", "type": "单词", "keyWords": [] },
    { "chinese": "a. 不相关的", "english": "irrelevant", "type": "单词", "keyWords": [] },
    { "chinese": "与…无关", "english": "be irrelevant to(=have nothing to do with...", "type": "短语", "keyWords": ["irrelevant"] },
    { "chinese": "a. 不规则的；无规律的", "english": "irregular", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 不规则地", "english": "irregularly", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]不规则", "english": "irregularity", "type": "单词", "keyWords": [] },
    { "chinese": "v. 灌溉；vi. 进行灌溉", "english": "irrigate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]灌溉", "english": "irrigation", "type": "单词", "keyWords": [] },
    { "chinese": "表示“国家的（Irish）”，或“具有某特征”", "english": "-ish", "type": "词缀", "keyWords": [] },
    { "chinese": "a. 愚蠢的；爱尔兰的；孩子气的；微红的", "english": "foolish, Irish, childish, reddish", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]岛", "english": "island", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]岛上居民", "english": "islander", "type": "单词", "keyWords": [] },
    { "chinese": "表示“行动”", "english": "-ism①", "type": "词缀", "keyWords": [] },
    { "chinese": "表示“主义”", "english": "-ism②", "type": "词缀", "keyWords": [] },
    { "chinese": "n. 批评；批判；指责", "english": "criticism", "type": "单词", "keyWords": [] },
    { "chinese": "n. 共产主义；社会主义；资本主义；唯物主义；人文主义；英雄主义", "english": "communism, socialism, capitalism, materialism, humanism, heroism", "type": "单词", "keyWords": [] },
    { "chinese": "表示“主义者”", "english": "-ist①", "type": "词缀", "keyWords": [] },
    { "chinese": "表示“从事某职业的人”", "english": "-ist②", "type": "词缀", "keyWords": [] },
    { "chinese": "表示“…主义的”", "english": "-ist③", "type": "词缀", "keyWords": [] },
    { "chinese": "n. 社会主义者；资本家", "english": "socialist, capitalist", "type": "单词", "keyWords": [] },
    { "chinese": "n. 牙医；化学家", "english": "dentist, chemist", "type": "单词", "keyWords": [] },
    { "chinese": "a. 共产主义的", "english": "communist", "type": "单词", "keyWords": [] } 
];
const qgl145_152 = [
    { "chinese": "v.使隔离；使孤立", "english": "isolate", "type": "单词", "keyWords": [] },
    { "chinese": "adj.隔离的，孤立的，单独的", "english": "isolated", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]隔离；孤立", "english": "isolation", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]问题；争论点；发行；颁布；(书刊的)期号；v.出版；发行；颁布", "english": "issue", "type": "单词", "keyWords": [] },
    { "chinese": "斜体的；n.(常pl.)斜体字", "english": "italic", "type": "单词", "keyWords": [] },
    { "chinese": "v.印作斜体", "english": "italicize", "type": "单词", "keyWords": [] },
    { "chinese": "用斜体", "english": "in italics", "type": "短语", "keyWords": ["italic"] },
    { "chinese": "vi.发痒", "english": "itch", "type": "单词", "keyWords": [] },
    { "chinese": "原来如此；就这么多；就这样!", "english": "That's it!", "type": "句子", "keyWords": ["it"] },
    { "chinese": "据说", "english": "Legend has it that...", "type": "句子", "keyWords": ["it"] },
    { "chinese": "pron.它(主格，宾格)", "english": "it", "type": "单词", "keyWords": [] },
    { "chinese": "报纸上说…", "english": "It says in the newspaper that...", "type": "句子", "keyWords": ["it"] },
    { "chinese": "n.[C]项目；项；(消息、情报、新闻等)一则，一条；节目；条款", "english": "item", "type": "单词", "keyWords": [] },
    { "chinese": "pron.它自己", "english": "itself", "type": "单词", "keyWords": [] },
    { "chinese": "本身", "english": "in itself", "type": "短语", "keyWords": ["itself"] },
    { "chinese": "靠自己；单独", "english": "by itself", "type": "短语", "keyWords": ["itself"] },
    { "chinese": "自行；自动", "english": "of itself", "type": "短语", "keyWords": ["itself"] },
    { "chinese": "n.（pl.）万事通；博而不精的人", "english": "jack of all trades", "type": "短语", "keyWords": [] },
    { "chinese": "n.[C]短上衣；夹克衫", "english": "jacket", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]监狱；看守所；vt.监禁；拘留", "english": "jail", "type": "单词", "keyWords": [] },
    { "chinese": "vi./vt.（把…）挤进，塞满；（使）挤紧；（使）阻塞；n.[C]阻塞；n.[U]果酱", "english": "jam", "type": "单词", "keyWords": [] },
    { "chinese": "n.一月(略作Jan.)", "english": "January", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]罐子；广口瓶", "english": "jar", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](U)茉莉", "english": "jasmine", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][解]颚，颌；(夹)爪；钳口；(pl.)嘴巴", "english": "jaw", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]爵士乐", "english": "jazz", "type": "单词", "keyWords": [] },
    { "chinese": "adj.羡慕的，妒忌的", "english": "jealous", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]妒忌；羡慕", "english": "jealousy", "type": "单词", "keyWords": [] },
    { "chinese": "羡慕，妒忌", "english": "be jealous of (sb.'ability)", "type": "短语", "keyWords": ["jealous"] },
    { "chinese": "n.(pl.)牛仔裤；紧身工作裤", "english": "jeans", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]吉普车", "english": "jeep", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]果冻；[U]胶冻，胶状物", "english": "jelly", "type": "单词", "keyWords": [] },
    { "chinese": "n.(单复数同形)海蜇，水母", "english": "jellyfish", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]喷射；喷流；喷气式飞机(或发动机)；adj.喷气式飞机的；喷气(发动机)推进的", "english": "jet", "type": "单词", "keyWords": [] },
    { "chinese": "一股喷出的水", "english": "a jet of water", "type": "短语", "keyWords": ["jet"] },
    { "chinese": "喷气式飞机", "english": "jet aircraft = jet plane", "type": "短语", "keyWords": ["jet", "aircraft", "plane"] },
    { "chinese": "倒时差", "english": "get over the jet lag", "type": "短语", "keyWords": ["jet", "lag"] },
    { "chinese": "有时差症", "english": "get the jet lag", "type": "短语", "keyWords": ["jet", "lag"] },
    { "chinese": "n.[C]宝石；首饰", "english": "jewel", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]珠宝", "english": "jewellery", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]珠宝商", "english": "jeweller(y)", "type": "单词", "keyWords": [] },
    { "chinese": "adj.犹太人的", "english": "Jewish", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]犹太人", "english": "Jew", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]工作；零工", "english": "job", "type": "单词", "keyWords": [] },
    { "chinese": "非全日性的工作", "english": "a part-time job", "type": "短语", "keyWords": ["job"] },
    { "chinese": "全日性的工作", "english": "a full-time job", "type": "短语", "keyWords": ["job"] },
    { "chinese": "失业", "english": "be out of a job(=out of work=out of employment)", "type": "短语", "keyWords": ["job"] },
    { "chinese": "vi./n.[U](健身锻炼)慢跑", "english": "jog", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]慢跑", "english": "jogging", "type": "单词", "keyWords": [] },
    { "chinese": "慢跑", "english": "go for a jog/ do some jogging", "type": "短语", "keyWords": ["jog", "jogging"] },
    { "chinese": "v.连接，结合；参加，加入，与…一起做；vi.参加；汇合", "english": "join", "type": "单词", "keyWords": [] },
    { "chinese": "把电线接起来", "english": "join the wires up", "type": "短语", "keyWords": ["join", "wires"] },
    { "chinese": "用钉子把两块板钉在一起", "english": "join two boards with nails", "type": "短语", "keyWords": ["join", "boards", "nails"] },
    { "chinese": "小溪与河流的交汇处", "english": "the point where the creek joins the river", "type": "短语", "keyWords": ["join", "creek", "river"] },
    { "chinese": "排队(等候)", "english": "join a queue/ row/line", "type": "短语", "keyWords": ["join", "queue", "row", "line"] },
    { "chinese": "手拉手围成圈", "english": "join hands in a circle", "type": "短语", "keyWords": ["join", "hands", "circle"] },
    { "chinese": "加入(组织)；成为成员", "english": "join sth.", "type": "短语", "keyWords": ["join"] },
    { "chinese": "成为俱乐部的会员", "english": "join a club", "type": "短语", "keyWords": ["join", "club"] },
    { "chinese": "参军", "english": "join the army", "type": "短语", "keyWords": ["join", "army"] },
    { "chinese": "加入某人(一起做某事)", "english": "join sb. in doing", "type": "短语", "keyWords": ["join"] },
    { "chinese": "委员会和我一起欢迎你。", "english": "The committee keeps me in welcoming you.", "type": "句子", "keyWords": ["committee", "welcome"] },
    { "chinese": "连接到", "english": "join to", "type": "短语", "keyWords": ["join"] },
    { "chinese": "这房子和隔壁那间房子的墙壁相连。", "english": "The house is joined to the one next door by a wall.", "type": "句子", "keyWords": ["house", "join", "wall"] },
    { "chinese": "两块骨头的接合处", "english": "the point where the two bones join", "type": "短语", "keyWords": ["join", "bones"] },
    { "chinese": "参加；加入进来(join可用作副词，后面可以不接sth；而participate in，take part in则不同，in是介词，需接名词)", "english": "join in", "type": "短语", "keyWords": ["join"] },
    { "chinese": "他加入了游戏/谈话。", "english": "He joined in (the game/ conversation).", "type": "句子", "keyWords": ["join", "game", "conversation"] },
    { "chinese": "他们的邻居也一起来搜寻失踪男孩。", "english": "Their neighbours joined in the search for the lost boy.", "type": "句子", "keyWords": ["neighbours", "join", "search", "lost", "boy"] },
    { "chinese": "n.[C]接合处；关节；adj.共同的；联合的；连接的", "english": "joint", "type": "单词", "keyWords": [] },
    { "chinese": "adv.共同地", "english": "jointly", "type": "单词", "keyWords": [] },
    { "chinese": "共同努力", "english": "take joint efforts", "type": "短语", "keyWords": ["joint", "efforts"] },
    { "chinese": "合资企业", "english": "joint venture", "type": "短语", "keyWords": ["joint", "venture"] },
    { "chinese": "合资企业", "english": "joint enterprise", "type": "短语", "keyWords": ["joint", "enterprise"] },
    { "chinese": "n.[C]笑话；玩笑；vi.开玩笑", "english": "joke", "type": "单词", "keyWords": [] },
    { "chinese": "adv.开玩笑地，打趣地", "english": "jokingly", "type": "单词", "keyWords": [] },
    { "chinese": "开玩笑", "english": "make a joke", "type": "短语", "keyWords": ["joke"] },
    { "chinese": "讲笑话", "english": "tell a joke", "type": "短语", "keyWords": ["joke"] },
    { "chinese": "恶作剧", "english": "a practical joke", "type": "短语", "keyWords": ["joke"] },
    { "chinese": "汤姆是开玩笑说的。", "english": "Tom said in joke/jokingly.", "type": "句子", "keyWords": ["Tom", "joke", "jokingly"] },
    { "chinese": "跟某人开玩笑", "english": "play a joke on sb.", "type": "短语", "keyWords": ["joke"] },
    { "chinese": "他假装把票弄丢了，跟我开了个玩笑。", "english": "He played a joke on me by pretending he'd lost the tickets.", "type": "句子", "keyWords": ["joke", "pretend", "lost", "tickets"] },
    { "chinese": "开(有关于)…的笑话", "english": "joke about...", "type": "短语", "keyWords": ["joke"] },
    { "chinese": "n.[C]杂志；期刊；日记；日志；航海日志", "english": "journal", "type": "单词", "keyWords": [] },
    { "chinese": "写日记", "english": "keep a diary/journal", "type": "短语", "keyWords": ["diary", "journal"] },
    { "chinese": "n.[C]新闻记者，从事新闻业的人", "english": "journalist", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](尤指远程的)旅行；旅程；行路；行程(辨析见tour)；vi.旅行(to)", "english": "journey", "type": "单词", "keyWords": [] },
    { "chinese": "他在长途旅行。", "english": "He's going on a long journey.=He's making/ taking a long journey.", "type": "句子", "keyWords": ["journey"] },
    { "chinese": "人生就是从出生到死亡的一段艰难曲折的旅程。人生无坦途。", "english": "Life is but a hard and tortuous journey from birth to death.", "type": "句子", "keyWords": ["life", "journey", "birth", "death"] },
    { "chinese": "n.[U]欢乐；高兴；n.[C]乐事", "english": "joy", "type": "单词", "keyWords": [] },
    { "chinese": "adj.快乐的；令人欢欣的", "english": "joyful", "type": "单词", "keyWords": [] },
    { "chinese": "让某人大为高兴的是", "english": "to one's great joy", "type": "短语", "keyWords": ["joy"] },
    { "chinese": "同甘苦，共患难", "english": "share joys and sorrows", "type": "短语", "keyWords": ["joy", "sorrow"] },
    { "chinese": "v.审判；评判；断定，认为；n.[C]法官；审判员；裁判", "english": "judge", "type": "单词", "keyWords": [] },
    { "chinese": "从…判断", "english": "judge(...from/by", "type": "短语", "keyWords": ["judge"] },
    { "chinese": "认为某人是好的", "english": "judge sb.(to be) good", "type": "短语", "keyWords": ["judge"] },
    { "chinese": "听他的口音，他一定是河南人。", "english": "Judging from/ by his accent, he must be from Henan.", "type": "句子", "keyWords": ["judge", "accent", "Henan"] },
    { "chinese": "不要以貌取人。", "english": "Don't judge a book by its cover.", "type": "句子", "keyWords": ["judge"] },
    { "chinese": "n.[C](U)审判；判决；n.[U]判断力", "english": "judg(e)ment", "type": "单词", "keyWords": [] },
    { "chinese": "对…作出宣判", "english": "pass a judgment on sb.", "type": "短语", "keyWords": ["judgment"] },
    { "chinese": "n.[U]果汁；汁", "english": "juice", "type": "单词", "keyWords": [] },
    { "chinese": "adj.多汁的", "english": "juicy", "type": "单词", "keyWords": [] },
    { "chinese": "n.七月(略作Jul.)", "english": "July", "type": "单词", "keyWords": [] },
    { "chinese": "v.跳；跳跃；vt.跳过；使跳过；n.[C]跳跃；跳跃运动", "english": "jump", "type": "单词", "keyWords": [] },
    { "chinese": "纵马跃过篱笆", "english": "jump a horse over a fence", "type": "短语", "keyWords": ["jump", "horse", "fence"] },
    { "chinese": "跃过篱笆", "english": "jump a fence", "type": "短语", "keyWords": ["jump", "fence"] },
    { "chinese": "草率下结论", "english": "jump to conclusions", "type": "短语", "keyWords": ["jump", "conclusions"] },
    { "chinese": "一跃而起", "english": "jump to his feet", "type": "短语", "keyWords": ["jump", "feet"] },
    { "chinese": "跳高", "english": "high jump", "type": "短语", "keyWords": ["jump"] },
    { "chinese": "跳远", "english": "long jump", "type": "短语", "keyWords": ["jump"] },
    { "chinese": "7英尺远的一跳", "english": "a jump of seven feet", "type": "短语", "keyWords": ["jump", "feet"] },
    { "chinese": "n.六月(略作Jun.)", "english": "June", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]热带丛林；丛林，密林", "english": "jungle", "type": "单词", "keyWords": [] },
    { "chinese": "丛林法则；弱肉强食的原则", "english": "the law of the jungle", "type": "短语", "keyWords": ["jungle", "law"] },
    { "chinese": "adj.较年轻/幼的；地位/等级较低的；n.[C]年少者；晚辈；下级；年龄/职位等较低者；年资较浅者；(大学或中学)三年级学生", "english": "junior", "type": "单词", "keyWords": [] },
    { "chinese": "比…年龄小/地位低(反senior，类似inferior/superior)", "english": "be junior to", "type": "短语", "keyWords": ["junior"] },
    { "chinese": "尽管他年长一些，但职位比我低。", "english": "He is junior to me, though he is older.", "type": "句子", "keyWords": ["junior", "older"] },
    { "chinese": "小约翰·史密斯", "english": "John Smith, Junior/Jr/Jr.", "type": "短语", "keyWords": ["junior"] },
    { "chinese": "他比她小三岁。", "english": "He is her junior by three years.=He is junior to her by three years.", "type": "句子", "keyWords": ["junior"] },
    { "chinese": "n. 破烂；废旧杂物；蹩脚货", "english": "junk", "type": "单词", "keyWords": [] },
    { "chinese": "（无太多营养价值的）填肚子食品", "english": "junk food", "type": "短语", "keyWords": ["junk", "food"] },
    { "chinese": "n. 木星", "english": "Jupiter", "type": "单词", "keyWords": [] },
    { "chinese": "n. 陪审团；评判委员会", "english": "jury", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 正好，恰好；方才，刚刚；只不过；仅仅；adj. 公正的，正义的；正直的", "english": "just", "type": "单词", "keyWords": [] },
    { "chinese": "（表示建议）还是…… 的好", "english": "might just as well", "type": "短语", "keyWords": ["might", "as well"] },
    { "chinese": "既然没有活儿干，我们不如回家吧。", "english": "Since there is no more work to do, we might just as well go home.", "type": "句子", "keyWords": ["work", "go home"] },
    { "chinese": "n. 公正；公平；正义", "english": "justice", "type": "单词", "keyWords": [] },
    { "chinese": "n. 不公平；不讲道义", "english": "injustice", "type": "单词", "keyWords": [] },
    { "chinese": "秉公对待每个人", "english": "treat all men with justice", "type": "短语", "keyWords": ["treat", "justice"] },
    { "chinese": "正义得到了伸张。", "english": "Justice has been done.", "type": "句子", "keyWords": ["justice", "done"] },
    { "chinese": "vt. 证明（…… 有理、正当、无罪等）；为…… 辩护", "english": "justify", "type": "单词", "keyWords": [] },
    { "chinese": "证明……", "english": "This is to justify that...", "type": "句子", "keyWords": ["justify"] },
    { "chinese": "n. 袋鼠", "english": "kangaroo", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 渴望的；敏锐的；精明的", "english": "keen", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 急切地", "english": "keenly", "type": "单词", "keyWords": [] },
    { "chinese": "n. 渴望；敏锐", "english": "keenness", "type": "单词", "keyWords": [] },
    { "chinese": "对…… 有极大的兴趣", "english": "take a keen interest in...", "type": "短语", "keyWords": ["keen", "interest"] },
    { "chinese": "喜爱；对…… 着迷", "english": "be keen on (doing) sth.", "type": "短语", "keyWords": ["keen", "on"] },
    { "chinese": "记账", "english": "keep books/account", "type": "短语", "keyWords": ["keep", "books", "account"] },
    { "chinese": "守规则", "english": "keep the rules", "type": "短语", "keyWords": ["keep", "rules"] },
    { "chinese": "开店", "english": "keep a shop", "type": "短语", "keyWords": ["keep", "shop"] },
    { "chinese": "保持；保管，保留；使…… 保持着（某种状态）（后加宾语和宾补）；饲养，抚养；制止，防止（from）；履行，遵守（诺言）；vi. 保持，维持（后加 doing）", "english": "keep", "type": "单词", "keyWords": [] },
    { "chinese": "记日记", "english": "keep a diary", "type": "短语", "keyWords": ["keep", "diary"] },
    { "chinese": "遵守诺言", "english": "keep one's word", "type": "短语", "keyWords": ["keep", "word"] },
    { "chinese": "忍住眼泪", "english": "keep back one's tears", "type": "短语", "keyWords": ["keep", "back", "tears"] },
    { "chinese": "要养家", "english": "have a wife and family to keep", "type": "短语", "keyWords": ["wife", "family", "keep"] },
    { "chinese": "养猪", "english": "keep/raise a pig", "type": "短语", "keyWords": ["keep", "raise", "pig"] },
    { "chinese": "让孩子离火远一点", "english": "keep a child away from the fire", "type": "短语", "keyWords": ["keep", "child", "fire"] },
    { "chinese": "不断做某事（近 go on doing sth., go on with sth.）", "english": "keep doing sth.", "type": "短语", "keyWords": ["keep", "doing"] },
    { "chinese": "不断反复做某事", "english": "keep on doing", "type": "短语", "keyWords": ["keep", "on", "doing"] },
    { "chinese": "一直在擦鼻子", "english": "keep on blowing one's nose", "type": "短语", "keyWords": ["keep", "on", "blowing", "nose"] },
    { "chinese": "避开草地。", "english": "Keep off the grass.", "type": "句子", "keyWords": ["keep", "off", "grass"] },
    { "chinese": "不让马靠近草地", "english": "keep the horse off the grass", "type": "短语", "keyWords": ["keep", "horse", "grass"] },
    { "chinese": "阻止 / 克制某人做某事", "english": "keep sb. from doing sth.", "type": "短语", "keyWords": ["keep", "sb.", "from", "doing"] },
    { "chinese": "信守；保持，坚持（近 stick to, persist in, persevere in, hold on, insist on, adhere to, cling to）", "english": "keep to", "type": "短语", "keyWords": ["keep", "to"] },
    { "chinese": "敏捷的头脑", "english": "a keen mind", "type": "短语", "keyWords": ["keen", "mind"] },
    { "chinese": "急于想做某事", "english": "be keen to do sth.", "type": "短语", "keyWords": ["keen", "to do"] },
    { "chinese": "英国车辆一律靠左行驶。", "english": "Traffic in Britain keeps to the left.", "type": "句子", "keyWords": ["traffic", "Britain", "left"] },
    { "chinese": "跟上（人或潮流）(with sb/sth)；v. 保持；继续", "english": "keep up with", "type": "短语", "keyWords": ["keep", "up", "with"] },
    { "chinese": "这种（下雨）天气持续了几天。", "english": "The weather rain kept up for days.", "type": "句子", "keyWords": ["weather", "keep up", "days"] },
    { "chinese": "坚持下去", "english": "keep up his work/his spirits/the attack/the price...", "type": "短语", "keyWords": ["keep", "up"] },
    { "chinese": "(使) 不进入；(使) 远离", "english": "keep...out", "type": "短语", "keyWords": ["keep", "out"] },
    { "chinese": "暖和的衣服可以御寒。", "english": "Warm clothing can keep out the cold.", "type": "句子", "keyWords": ["clothing", "keep out", "cold"] },
    { "chinese": "n. 看守人；保管人", "english": "keeper", "type": "单词", "keyWords": [] },
    { "chinese": "n. 水壶", "english": "kettle", "type": "单词", "keyWords": [] },
    { "chinese": "看着的水壶永不开（性急也没用）", "english": "A watched kettle never boils.", "type": "句子", "keyWords": ["kettle", "boils"] },
    { "chinese": "n. 钥匙；答案，解答；关键；（打字机等的）键；[音乐] 键；adj. 主要的；vt. 用钥匙锁上；插上（栓、销子等）；为（演说、文章等）定基调；使协调；用电子键盘输入（信息等）", "english": "key", "type": "单词", "keyWords": [] },
    { "chinese": "主要工业，基本工业", "english": "the key industries", "type": "短语", "keyWords": ["key", "industries"] },
    { "chinese": "要点", "english": "a key point", "type": "短语", "keyWords": ["key", "point"] },
    { "chinese": "…… 的解答，答案，线索；关键（类似 the monument to sb., the approach to）", "english": "the key to...", "type": "短语", "keyWords": ["key"] },
    { "chinese": "他在表演前将小提琴所有的弦都调好了。", "english": "He keyed up all the strings of his violin before his performance.", "type": "句子", "keyWords": ["keyed up", "violin", "performance"] },
    { "chinese": "布赖恩键入了他的个人密码。", "english": "Brian keyed in his personal code.", "type": "句子", "keyWords": ["keyed in", "personal code"] },
    { "chinese": "n. 键盘", "english": "keyboard", "type": "单词", "keyWords": [] },
    { "chinese": "v. 踢；n. 踢", "english": "kick", "type": "单词", "keyWords": [] },
    { "chinese": "n. 小孩；小山羊；v. 欺骗；戏弄；n. 欺骗，哄骗", "english": "kid", "type": "单词", "keyWords": [] },
    { "chinese": "骗人！", "english": "You are kidding (me)!", "type": "句子", "keyWords": ["kidding"] },
    { "chinese": "vt.（kidnapped, kidnapped）诱拐（小孩）；绑架，勒索", "english": "kidnap", "type": "单词", "keyWords": [] },
    { "chinese": "n. 绑架者", "english": "kidnapper", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 杀死；消磨（时间）；n. 谋杀；屠杀；n. 杀手，凶手", "english": "kill", "type": "单词", "keyWords": [] },
    { "chinese": "一石二鸟 / 一箭双雕。", "english": "Kill two birds with one stone.", "type": "句子", "keyWords": ["kill", "birds", "stone"] },
    { "chinese": "n. 公斤，千克（缩写成 kg 时单复同）", "english": "kilogram", "type": "单词", "keyWords": [] },
    { "chinese": "n. 公里，千米（缩写成 km 时单复同）", "english": "kilometer", "type": "单词", "keyWords": [] },
    { "chinese": "n. 种类", "english": "kind", "type": "单词", "keyWords": [] },
    { "chinese": "同一类", "english": "of a kind", "type": "短语", "keyWords": ["kind"] },
    { "chinese": "有点，有些", "english": "kind of", "type": "短语", "keyWords": ["kind", "of"] },
    { "chinese": "感到有点儿累", "english": "feel kind of tired", "type": "短语", "keyWords": ["kind of", "tired"] },
    { "chinese": "她有点希望……", "english": "She kind of hoped that...", "type": "句子", "keyWords": ["kind of", "hoped"] },
    { "chinese": "这种书（注意 book 前不用冠词）", "english": "Books of this kind are.../This kind of book/book is...", "type": "短语", "keyWords": ["kind", "book"] },
    { "chinese": "物以类聚，人以群分。", "english": "Things of a kind come together.", "type": "句子", "keyWords": ["kind", "come together"] },
    { "chinese": "adj. 和蔼的；仁慈的；n. 仁慈；n. 好心肠的", "english": "kind", "type": "单词", "keyWords": [] },
    { "chinese": "n. 仁慈", "english": "kindness", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 仁慈的；好心肠的", "english": "kind - hearted", "type": "单词", "keyWords": [] },
    { "chinese": "您费心…… 好吗？", "english": "Would you be so kind as to do sth./kind enough to do sth.?", "type": "句子", "keyWords": ["kind", "do sth"] },
    { "chinese": "n. 幼儿园", "english": "kindergarten", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 和蔼的；可亲的；亲切的；adv. 厚道地，亲切地；有同情心地，体贴地", "english": "kindly", "type": "单词", "keyWords": [] },
    { "chinese": "n. 国王", "english": "king", "type": "单词", "keyWords": [] },
    { "chinese": "n. 王国；界（指自然三界之一）", "english": "kingdom", "type": "单词", "keyWords": [] },
    { "chinese": "动 / 植 / 矿物界", "english": "the animal/vegetable/mineral kingdom", "type": "短语", "keyWords": ["kingdom", "animal", "vegetable", "mineral"] },
    { "chinese": "n. 吻；v. 吻；以吻表示；（微风等）轻拂；轻触", "english": "kiss", "type": "单词", "keyWords": [] },
    { "chinese": "向某人飞吻", "english": "throw/blow a kiss at/to sb.", "type": "短语", "keyWords": ["kiss", "throw", "blow"] },
    { "chinese": "和某人吻别 / 晚安", "english": "kiss sb. goodbye/good night", "type": "短语", "keyWords": ["kiss", "goodbye", "good night"] },
    { "chinese": "轻风拂面。", "english": "The breeze kissed her face.", "type": "句子", "keyWords": ["breeze", "kissed", "face"] },
    { "chinese": "n. 厨房", "english": "kitchen", "type": "单词", "keyWords": [] },
    { "chinese": "n. 风筝", "english": "kite", "type": "单词", "keyWords": [] },
    { "chinese": "n. 小猫", "english": "kitten", "type": "单词", "keyWords": [] },
    { "chinese": "n. 猫咪", "english": "kity", "type": "单词", "keyWords": [] },
    { "chinese": "n. 技能；本领", "english": "knack", "type": "单词", "keyWords": [] },
    { "chinese": "无论去哪里，他都能交到朋友。", "english": "He has a knack of making friends wherever he goes.", "type": "句子", "keyWords": ["knack", "making friends", "wherever"] },
    { "chinese": "n. 膝；膝盖", "english": "knee", "type": "单词", "keyWords": [] },
    { "chinese": "单（双）膝跪着", "english": "be on one's knee (s)", "type": "短语", "keyWords": ["knee"] },
    { "chinese": "单（双）膝", "english": "go/get down on one's knee (s)", "type": "短语", "keyWords": ["knee"] },
    { "chinese": "vi. 跪着；跪下", "english": "kneel", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 跪着；跪下", "english": "kneel", "type": "单词", "keyWords": [] },
    { "chinese": "跪在地板上", "english": "kneel down on the floor", "type": "短语", "keyWords": ["kneel", "floor"] },
    { "chinese": "n. 小刀；餐刀；外科手术刀", "english": "knife", "type": "单词", "keyWords": [] },
    { "chinese": "(吃西餐用的) 一副刀叉", "english": "a knife and fork", "type": "短语", "keyWords": ["knife", "fork"] },
    { "chinese": "n.[英] 爵士 (需用 Sir 的称号)；(欧洲中世纪的) 骑士；勇士", "english": "knight", "type": "单词", "keyWords": [] },
    { "chinese": "v. 编织；n. 编织；针织品", "english": "knit", "type": "单词", "keyWords": [] },
    { "chinese": "v. 敲；使碰撞；碰撞；凿打 (洞等)；n. 敲，打击；(狠狠) 一击；敲门 (声)", "english": "knock", "type": "单词", "keyWords": [] },
    { "chinese": "在墙上凿一个洞", "english": "knock a hole in a wall", "type": "短语", "keyWords": ["knock", "hole", "wall"] },
    { "chinese": "以头撞门", "english": "knock one's head against the door", "type": "短语", "keyWords": ["knock", "head", "door"] },
    { "chinese": "打翻 / 撞倒；击倒", "english": "knock...over", "type": "短语", "keyWords": ["knock", "over"] },
    { "chinese": "拆毁 (建筑物、桥梁、机器等)；(开车) 把…… 撞倒；击倒", "english": "knock...down", "type": "短语", "keyWords": ["knock", "down"] },
    { "chinese": "我们的房子正在被拆掉，以便修建一条新公路。", "english": "Our house is being knocked down to make way for a new road.", "type": "句子", "keyWords": ["house", "knock down", "new road"] },
    { "chinese": "找错了门路", "english": "knock at the wrong door", "type": "短语", "keyWords": ["knock", "wrong door"] },
    { "chinese": "敲出；把…… 击昏，击倒；使惊得目瞪口呆", "english": "knock...out", "type": "短语", "keyWords": ["knock", "out"] },
    { "chinese": "把钉子钉进木头", "english": "knock a nail into the wood", "type": "短语", "keyWords": ["knock", "nail", "wood"] },
    { "chinese": "(卖主) 从价钱中减去；下班", "english": "knock...off", "type": "短语", "keyWords": ["knock", "off"] },
    { "chinese": "v. 知道，了解；懂得；熟悉；精通，通晓 (语言等)；能识别，认出", "english": "know", "type": "单词", "keyWords": [] },
    { "chinese": "分辨是非", "english": "know right from wrong", "type": "短语", "keyWords": ["know", "right", "wrong"] },
    { "chinese": "我们都知道他是诚实的。", "english": "We all knew him to be honest.", "type": "句子", "keyWords": ["knew", "honest"] },
    { "chinese": "只知道某人的名字", "english": "know sb. by name", "type": "短语", "keyWords": ["know", "name"] },
    { "chinese": "我知道点 / 听说过他的情况，但不认识他。", "english": "I know of/about him, but I don't know him personally.", "type": "句子", "keyWords": ["know of/about", "personally"] },
    { "chinese": "不可能知道……", "english": "There is no knowing/telling...", "type": "句子", "keyWords": ["knowing/telling"] },
    { "chinese": "众所周知", "english": "As we know,.../ As is known to all.../ It is known that...", "type": "句子", "keyWords": ["know", "known"] },
    { "chinese": "他过过好日子。", "english": "He has known better days.", "type": "句子", "keyWords": ["known", "better days"] },
    { "chinese": "天晓得！谁知道！", "english": "God knows!", "type": "句子", "keyWords": ["God", "knows"] },
    { "chinese": "adj. 已知的；大家知道的；知名的 (to sb. for sth.)", "english": "known", "type": "单词", "keyWords": [] },
    { "chinese": "作为…… 而出名", "english": "be known as (a writer)", "type": "短语", "keyWords": ["known", "as"] },
    { "chinese": "发表，公布", "english": "make...known (to sb.)/make known (to sb.)", "type": "短语", "keyWords": ["make", "known"] },
    { "chinese": "以…… 闻名", "english": "be known/famous for", "type": "短语", "keyWords": ["known", "famous", "for"] },
    { "chinese": "n. 知识；了解；知晓；熟悉", "english": "knowledge", "type": "单词", "keyWords": [] },
    { "chinese": "很了解；熟知", "english": "have a good knowledge of...", "type": "短语", "keyWords": ["knowledge", "good"] },
    { "chinese": "英语好将有助于增加你们的就业机会。", "english": "A good knowledge of English will improve your chances of employment.", "type": "句子", "keyWords": ["knowledge", "English", "employment"] },
    { "chinese": "知识就是力量。", "english": "Knowledge is power.", "type": "句子", "keyWords": ["Knowledge", "power"] },
    { "chinese": "adj. 知识渊博的", "english": "knowledgeable", "type": "单词", "keyWords": [] },
    { "chinese": "n. 韩国人 / 朝鲜人；n. 韩语 / 朝鲜语；adj. 韩国人 / 朝鲜人的，韩语 / 朝鲜语的", "english": "Korean", "type": "单词", "keyWords": [] },
    { "chinese": "n.(laboratory 的缩略) 实验室；语言实验室", "english": "lab", "type": "单词", "keyWords": [] },
    { "chinese": "n. 标签；标注，标记；v. 给…… 贴上标签；把…… 归类", "english": "label", "type": "单词", "keyWords": [] },
    { "chinese": "把…… 称作……(describe/refer to/define...as...)", "english": "label...as...", "type": "短语", "keyWords": ["label", "as"] },
    { "chinese": "n.[(体力) 劳动；努力，工作；vi. 干苦活；费力地去干；n. 劳动者", "english": "labo (u) r", "type": "单词", "keyWords": [] },
    { "chinese": "(公司或国家的) 劳动力", "english": "labour force", "type": "短语", "keyWords": ["labour", "force"] },
    { "chinese": "劳动力市场", "english": "labour market", "type": "短语", "keyWords": ["labour", "market"] },
    { "chinese": "n.(U)(可和 a 连用) 缺乏；v. 缺乏；没有 (强调必需品的缺乏或其供应的不足)", "english": "lack", "type": "单词", "keyWords": [] },
    { "chinese": "缺乏信心", "english": "lack confidence", "type": "短语", "keyWords": ["lack", "confidence"] },
    { "chinese": "由于缺乏", "english": "for lack of", "type": "短语", "keyWords": ["lack", "for"] },
    { "chinese": "植物由于缺水而死亡。", "english": "The plants died for lack of water.", "type": "句子", "keyWords": ["plants", "died", "water"] },
    { "chinese": "缺少…… 的", "english": "be lacking in", "type": "短语", "keyWords": ["lacking", "in"] },
    { "chinese": "你将得到我的帮助。", "english": "You will not be lacking in support from me.", "type": "句子", "keyWords": ["lacking", "support"] },
    { "chinese": "他表现出明显的兴趣不足。", "english": "He showed a marked lack of interest.", "type": "句子", "keyWords": ["showed", "lack", "interest"] },
    { "chinese": "n. 梯子；他爬上了上层社会。", "english": "ladder", "type": "单词", "keyWords": [] },
    { "chinese": "n. 小姐；女士；夫人", "english": "lady", "type": "单词", "keyWords": [] },
    { "chinese": "n. 瓢虫", "english": "ladybird", "type": "单词", "keyWords": [] },
    { "chinese": "n. 湖", "english": "lake", "type": "单词", "keyWords": [] },
    { "chinese": "n. 羔羊，小羊；n. 羊羔肉", "english": "lamb", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 跛足的；瘸的；残废的", "english": "lame", "type": "单词", "keyWords": [] },
    { "chinese": "左腿瘸的", "english": "be lame in the left leg", "type": "短语", "keyWords": ["lame", "left leg"] },
    { "chinese": "n. 灯", "english": "lamp", "type": "单词", "keyWords": [] },
    { "chinese": "n. 陆地；土地；国土；(书面语) 国家；v.(使) 着陆；(使) 上岸", "english": "land", "type": "单词", "keyWords": [] },
    { "chinese": "n. 着陆；上岸", "english": "landing", "type": "单词", "keyWords": [] },
    { "chinese": "n. 地标；地界标；里程碑", "english": "landmark", "type": "单词", "keyWords": [] },
    { "chinese": "由陆路", "english": "by land", "type": "短语", "keyWords": ["land", "by"] },
    { "chinese": "在陆上", "english": "on land", "type": "短语", "keyWords": ["land", "on"] },
    { "chinese": "祖国", "english": "one's native land", "type": "短语", "keyWords": ["land", "native"] },
    { "chinese": "飞机安全地紧急着陆。", "english": "The plane made a safe emergency landing.", "type": "句子", "keyWords": ["plane", "landing", "safe"] },
    { "chinese": "n. 地主；房东；(客栈等的) 店主", "english": "landlord", "type": "单词", "keyWords": [] },
    { "chinese": "n. 景色；风景 / 山水画；地形 (辨析见 scene)", "english": "landscape", "type": "单词", "keyWords": [] },
    { "chinese": "n. 车道；里弄；小巷", "english": "lane", "type": "单词", "keyWords": [] },
    { "chinese": "快车道", "english": "the fast lane", "type": "短语", "keyWords": ["lane", "fast"] },
    { "chinese": "四车道高速公路", "english": "a four - lane motorway", "type": "短语", "keyWords": ["lane", "motorway"] },
    { "chinese": "n. 语言；[U](运用语言的) 方式；能力；风格", "english": "language", "type": "单词", "keyWords": [] }
];

qgl137_144.sort(() => Math.random() - 0.5);
qgl145_152.sort(() => Math.random() - 0.5);