const qgl106_120 = [
    { "chinese": "真想不到又见到你了", "english": "Fancy meeting you again!", "type": "句子", "keyWords": ["fancy"] },
    { "chinese": "(化装舞会等)化装服装", "english": "fancy dress", "type": "短语", "keyWords": ["fancy"] },
    { "chinese": "a.幻想的，只存在于想象中的；奇异的；[口]极妙的，了不起的", "english": "fantastic", "type": "单词", "keyWords": [] },
    { "chinese": "a.(空间、时间上)远的，遥远的；远离的；ad.很；极；远；久远", "english": "far", "type": "单词", "keyWords": [] },
    { "chinese": "远东", "english": "the Far East", "type": "短语", "keyWords": ["far"] },
    { "chinese": "深远的(影响)；伸至远处的", "english": "far-reaching (influence)", "type": "短语", "keyWords": ["far"] },
    { "chinese": "迄今为止", "english": "so far", "type": "短语", "keyWords": ["far"] },
    { "chinese": "追溯到18世纪", "english": "go far back to the 18th century", "type": "短语", "keyWords": ["far"] },
    { "chinese": "好得多", "english": "far better", "type": "短语", "keyWords": ["far"] },
    { "chinese": "学习/工作到深夜", "english": "study/ work far into the night", "type": "短语", "keyWords": ["far"] },
    { "chinese": "远远落后", "english": "fall far behind", "type": "短语", "keyWords": ["far"] },
    { "chinese": "远非我力所能及", "english": "far beyond my powers", "type": "短语", "keyWords": ["far"] },
    { "chinese": "行为过于出格", "english": "go too far", "type": "短语", "keyWords": ["far"] },
    { "chinese": "到目前为止一切顺利", "english": "So far, so good.", "type": "句子", "keyWords": ["far"] },
    { "chinese": "远离；完全不", "english": "far from", "type": "短语", "keyWords": ["far"] },
    { "chinese": "你这书法写得很不到家", "english": "Your calligraphy is far from perfect.", "type": "句子", "keyWords": ["far"] },
    { "chinese": "远到，到...为止；至于，就...而言", "english": "as far as", "type": "短语", "keyWords": ["far"] },
    { "chinese": "就我们目前所知，他们将在九点钟到", "english": "They will arrive at nine, as far as we know.", "type": "句子", "keyWords": ["far"] },
    { "chinese": "公司中最为优秀的经理", "english": "by far the best executive in the company", "type": "短语", "keyWords": ["far"] },
    { "chinese": "a.遥远的；远方的；很久以前的；恍惚的，出神的", "english": "faraway", "type": "单词", "keyWords": ["far"] },
    { "chinese": "他眼中的恍惚神情", "english": "a faraway look in his eyes", "type": "短语", "keyWords": ["faraway"] },
    { "chinese": "n.[C]车费；船费；飞机票价", "english": "fare", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]a.辞别(的)，再见(的)", "english": "farewell", "type": "单词", "keyWords": [] },
    { "chinese": "告别演说", "english": "a farewell address/ speech", "type": "短语", "keyWords": ["farewell"] },
    { "chinese": "告别晚会/饯行宴会", "english": "a farewell party/ dinner", "type": "短语", "keyWords": ["farewell"] },
    { "chinese": "n.[C]农场，农庄；农田；v.耕种；饲养(家畜等)；vi.务农；经营农场；从事畜牧业", "english": "farm", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]农舍", "english": "farmhouse", "type": "单词", "keyWords": ["farm"] },
    { "chinese": "n.[U]农田", "english": "farmland", "type": "单词", "keyWords": ["farm"] },
    { "chinese": "n.[C]雇农", "english": "farmhand", "type": "单词", "keyWords": ["farm"] },
    { "chinese": "n.[U]农业，农事；耕作；畜牧", "english": "farming", "type": "单词", "keyWords": ["farm"] },
    { "chinese": "农业生产", "english": "farming industry", "type": "短语", "keyWords": ["farming"] },
    { "chinese": "n.[C]农夫，百姓；农场主，承包主，牧场主", "english": "farmer", "type": "单词", "keyWords": ["farm"] },
    { "chinese": "vt.强烈吸引住；迷住", "english": "fascinate", "type": "单词", "keyWords": [] },
    { "chinese": "a.迷人的，吸引人的", "english": "fascinating", "type": "单词", "keyWords": ["fascinate"] },
    { "chinese": "a.着迷的，极感兴趣的", "english": "fascinated", "type": "单词", "keyWords": ["fascinate"] },
    { "chinese": "对...着了迷", "english": "be fascinated with/by sth.", "type": "短语", "keyWords": ["fascinated"] },
    { "chinese": "n.[C][U]魔力；入迷；魅力；迷恋", "english": "fascination", "type": "单词", "keyWords": ["fascinate"] },
    { "chinese": "那宫殿对他具有一种很特殊的魅力", "english": "The palace had a peculiar fascination for him.", "type": "句子", "keyWords": ["fascination"] },
    { "chinese": "n.[C]时髦；方式；样子；n.[C][U](服装等)流行式样；时尚", "english": "fashion", "type": "单词", "keyWords": [] },
    { "chinese": "开始流行", "english": "come into fashion", "type": "短语", "keyWords": ["fashion"] },
    { "chinese": "时髦的，流行的/过时了，不时髦的", "english": "be in/ out fashion", "type": "短语", "keyWords": ["fashion"] },
    { "chinese": "a.受时髦人物欢迎的，符合时尚的；流行的；(赶)时髦的", "english": "fashionable", "type": "单词", "keyWords": ["fashion"] },
    { "chinese": "a.快，快速的；钟快了；紧的，牢的；ad.很快地；牢固地，紧紧地；vi.绝食，斋戒", "english": "fast", "type": "单词", "keyWords": [] },
    { "chinese": "快五分钟", "english": "five minutes fast", "type": "短语", "keyWords": ["fast"] },
    { "chinese": "睡得香", "english": "fast/ sound asleep", "type": "短语", "keyWords": ["fast"] },
    { "chinese": "快速移动的", "english": "fast-moving", "type": "短语", "keyWords": ["fast"] },
    { "chinese": "紧紧地抓住她的钱包", "english": "keep a fast hold on her purse", "type": "短语", "keyWords": ["fast"] },
    { "chinese": "紧紧地抓住绳子", "english": "hold fast to the rope", "type": "短语", "keyWords": ["fast"] },
    { "chinese": "他们在某些日子斋戒", "english": "They fast on certain days.", "type": "句子", "keyWords": ["fast"] },
    { "chinese": "v.扎牢；系牢", "english": "fasten", "type": "单词", "keyWords": [] },
    { "chinese": "系好你的安全带", "english": "Fasten your seat belt.", "type": "句子", "keyWords": ["fasten"] },
    { "chinese": "a.肥胖的；n.[U]脂肪；n.[C][U]肥肉", "english": "fat", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]肥胖；油腻", "english": "fatness", "type": "单词", "keyWords": ["fat"] },
    { "chinese": "v.养肥", "english": "fatten", "type": "单词", "keyWords": ["fat"] },
    { "chinese": "(美俚)富有而有权势的人，大亨", "english": "fat cat", "type": "短语", "keyWords": ["fat"] },
    { "chinese": "a.致命的；毁灭性的；命运注定的", "english": "fatal", "type": "单词", "keyWords": [] },
    { "chinese": "钱都亏损了，把我的计划也毁灭了", "english": "The loss of all my money was fatal to my plan.", "type": "句子", "keyWords": ["fatal"] },
    { "chinese": "n.[C]命运", "english": "fate", "type": "单词", "keyWords": [] },
    { "chinese": "决定某人的命运", "english": "decide one's fate", "type": "短语", "keyWords": ["fate"] },
    { "chinese": "死；送死", "english": "meet one's fate", "type": "短语", "keyWords": ["fate"] },
    { "chinese": "自趋灭亡", "english": "go to one's fate", "type": "短语", "keyWords": ["fate"] },
    { "chinese": "n.[C]父亲；创始者", "english": "father", "type": "单词", "keyWords": [] },
    { "chinese": "父亲节", "english": "Father's Day", "type": "短语", "keyWords": ["father"] },
    { "chinese": "圣诞老人", "english": "Father Christmas", "type": "短语", "keyWords": ["father"] },
    { "chinese": "有其父必有其子", "english": "Like father, like son.", "type": "句子", "keyWords": ["father"] },
    { "chinese": "岳父", "english": "father-in-law", "type": "单词", "keyWords": ["father"] },
    { "chinese": "科学之父", "english": "the father of science", "type": "短语", "keyWords": ["father"] },
    { "chinese": "a.像父亲一样的", "english": "fatherly", "type": "单词", "keyWords": ["father"] },
    { "chinese": "n.[C]缺点；错误；过错；(对错误所负的)责任", "english": "fault", "type": "单词", "keyWords": [] },
    { "chinese": "a.没错的；无辜的", "english": "faultless", "type": "单词", "keyWords": ["fault"] },
    { "chinese": "是某人的错", "english": "It is sb.'s fault that...", "type": "短语", "keyWords": ["fault"] },
    { "chinese": "a.有错误的；有毛病的；不完善的", "english": "faulty", "type": "单词", "keyWords": ["fault"] },
    { "chinese": "n.[C]恩惠；帮助；善意；n.[U]喜爱；vt.有利于；恩宠，偏爱(袒)；支持，赞成", "english": "favour", "type": "单词", "keyWords": [] },
    { "chinese": "失宠(于某人)", "english": "be out of favour (with sb.)", "type": "短语", "keyWords": ["favour"] },
    { "chinese": "请某人帮忙", "english": "ask a favour of sb.", "type": "短语", "keyWords": ["favour"] },
    { "chinese": "支持；赞成", "english": "be in favour of", "type": "短语", "keyWords": ["favour"] },
    { "chinese": "得人欢心；得宠于某人", "english": "gain/win one's favour", "type": "短语", "keyWords": ["favour"] },
    { "chinese": "对…吹毛求疵；挑剔", "english": "find fault with", "type": "短语", "keyWords": ["fault"] },
    { "chinese": "失宠；失利", "english": "lose favour", "type": "短语", "keyWords": ["favour"] },
    { "chinese": "偏爱他的想法", "english": "favor his ideas", "type": "短语", "keyWords": ["favour"] },
    { "chinese": "对某人有利", "english": "in one's favour", "type": "短语", "keyWords": ["favour"] },
    { "chinese": "帮某人的忙", "english": "do sb. a favour by doing sth.", "type": "短语", "keyWords": ["favour"] },
    { "chinese": "顺风", "english": "favourable winds", "type": "短语", "keyWords": ["favourable"] },
    { "chinese": "a.特别受喜爱的；n.[C]特别受喜爱的东西或人", "english": "favourite", "type": "单词", "keyWords": ["favour"] },
    { "chinese": "a.有利的；良好的；可喜的", "english": "favourable", "type": "单词", "keyWords": ["favour"] },
    { "chinese": "有利条件", "english": "favourable conditions", "type": "短语", "keyWords": ["favourable"] },
    { "chinese": "n.[C]传真机；n.[U]传真；vt.传真；传输", "english": "fax", "type": "单词", "keyWords": [] },
    { "chinese": "传真某东西", "english": "send sth. by fax", "type": "短语", "keyWords": ["fax"] },
    { "chinese": "n.[C]害怕，恐惧；vt.害怕，畏惧；为...担心", "english": "fear", "type": "单词", "keyWords": [] },
    { "chinese": "a.勇敢的，无畏的", "english": "fearless", "type": "单词", "keyWords": ["fear"] },
    { "chinese": "a.可怕的，吓人的", "english": "fearful", "type": "单词", "keyWords": ["fear"] },
    { "chinese": "一直生活在...的恐惧中", "english": "live in fear of...", "type": "短语", "keyWords": ["fear"] },
    { "chinese": "我不敢去，怕他看到我", "english": "I dare not go there for fear of him seeing me/ that he will see me.", "type": "句子", "keyWords": ["fear"] },
    { "chinese": "唯恐，就怕", "english": "for fear of sth./ for fear that...", "type": "短语", "keyWords": ["fear"] },
    { "chinese": "a.行得通的；可行的", "english": "feasible", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]宴会", "english": "feast", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]羽毛", "english": "feather", "type": "单词", "keyWords": [] },
    { "chinese": "物以类聚", "english": "Birds of a feather flock together.", "type": "句子", "keyWords": ["feather"] },
    { "chinese": "v.以...为特色；是...的特色；给...以重要地位；n.[C]特写；特征", "english": "feature", "type": "单词", "keyWords": [] },
    { "chinese": "故事片", "english": "feature films", "type": "短语", "keyWords": ["feature"] },
    { "chinese": "一个地区的地理特征", "english": "the geographical features of a district", "type": "短语", "keyWords": ["feature"] },
    { "chinese": "一篇特写", "english": "a feature article", "type": "短语", "keyWords": ["feature"] },
    { "chinese": "她的眼睛是她的容貌最漂亮的部分", "english": "Her eyes were her best feature.", "type": "句子", "keyWords": ["feature"] },
    { "chinese": "报纸以显著地位报道了那个事件", "english": "The newspaper featured the story of the event.", "type": "句子", "keyWords": ["feature"] },
    { "chinese": "n.[C]二月(略作 Feb.)", "english": "February", "type": "单词", "keyWords": [] },
    { "chinese": "a.联邦(制)的；联合的", "english": "federal", "type": "单词", "keyWords": [] },
    { "chinese": "[美]联邦调查局(FBI)", "english": "Federal Bureau of Investigation", "type": "短语", "keyWords": ["federal"] },
    { "chinese": "n.[C](会费、入场费等)费；酬金；小费", "english": "fee", "type": "单词", "keyWords": [] },
    { "chinese": "学费", "english": "tuition fees", "type": "短语", "keyWords": ["fee"] },
    { "chinese": "入会费", "english": "admission fee", "type": "短语", "keyWords": ["fee"] },
    { "chinese": "v.喂(养)；输入；投入；放入", "english": "feed", "type": "单词", "keyWords": [] },
    { "chinese": "用...来喂养...", "english": "feed...on/ with...", "type": "短语", "keyWords": ["feed"] },
    { "chinese": "我们用新鲜肉喂狗", "english": "We feed our dogs on fresh meat.", "type": "句子", "keyWords": ["feed"] },
    { "chinese": "吃；以...为食", "english": "feed on", "type": "短语", "keyWords": ["feed"] },
    { "chinese": "牛以草为食", "english": "Cows feed on grass.", "type": "句子", "keyWords": ["feed"] },
    { "chinese": "吃得过饱；(对...)极其厌倦", "english": "be fed up with", "type": "短语", "keyWords": ["feed"] },
    { "chinese": "我受够你的谎言了", "english": "I am fed up with your lies.", "type": "句子", "keyWords": ["feed"] },
    { "chinese": "把...喂给...吃", "english": "feed sth. to sb.", "type": "短语", "keyWords": ["feed"] },
    { "chinese": "把数据输入电脑", "english": "feed data into the computer", "type": "短语", "keyWords": ["feed"] },
    { "chinese": "此信息反馈给了他们", "english": "This information was fed back to them.", "type": "句子", "keyWords": ["feed"] },
    { "chinese": "n.[U](信息等的)返回；反馈的信息；反应", "english": "feedback", "type": "单词", "keyWords": ["feed"] },
    { "chinese": "v.摸，触；摸索，感觉，觉得，以为；vi.(人)有某种感觉；感受到；(东西)摸起来...", "english": "feel", "type": "单词", "keyWords": [] },
    { "chinese": "感觉似乎", "english": "feel as if", "type": "短语", "keyWords": ["feel"] },
    { "chinese": "随意做某事(常用于祈使句)", "english": "feel free to do", "type": "短语", "keyWords": ["feel"] },
    { "chinese": "想要做某事", "english": "feel like doing sth.", "type": "短语", "keyWords": ["feel"] },
    { "chinese": "某东西摸起来很柔软", "english": "sth. feels soft", "type": "句子", "keyWords": ["feel"] },
    { "chinese": "摸着找他的钥匙", "english": "feel for his keys", "type": "短语", "keyWords": ["feel"] },
    { "chinese": "摸着朝门走去", "english": "feel his way to the door", "type": "短语", "keyWords": ["feel"] },
    { "chinese": "感觉某人或某物在...", "english": "feel sb./sth. do sth./doing sth.", "type": "短语", "keyWords": ["feel"] },
    { "chinese": "我认为这样做是我的责任", "english": "I feel it my duty to do so.", "type": "句子", "keyWords": ["feel"] },
    { "chinese": "n.[C]感觉；感情；复杂的情绪或情感", "english": "feeling", "type": "单词", "keyWords": ["feel"] },
    { "chinese": "伤某人的感情", "english": "hurt one's feelings", "type": "短语", "keyWords": ["feeling"] },
    { "chinese": "预感到", "english": "have a feeling that...", "type": "短语", "keyWords": ["feeling"] },
    { "chinese": "n.[C]家伙；小伙子；伙伴，朋友；a.同伴的，同事的", "english": "fellow", "type": "单词", "keyWords": [] },
    { "chinese": "同事", "english": "fellow workers", "type": "短语", "keyWords": ["fellow"] },
    { "chinese": "n.[C]女子；雌性动植物；a.女性的，女子的，妇女的，雌的", "english": "female", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]栅栏，篱笆；围墙；n.[U]击剑术；v.用篱笆围住", "english": "fence", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]渡船；渡口；v.渡运；渡过；摆渡", "english": "ferry", "type": "单词", "keyWords": [] },
    { "chinese": "乘渡船", "english": "by ferry", "type": "短语", "keyWords": ["ferry"] },
    { "chinese": "a.肥沃的；丰富的", "english": "fertile", "type": "单词", "keyWords": [] },
    { "chinese": "肥沃的土壤", "english": "fertile soil", "type": "短语", "keyWords": ["fertile"] },
    { "chinese": "n.[C]肥料", "english": "fertilizer", "type": "单词", "keyWords": ["fertile"] },
    { "chinese": "v.施肥，使丰饶", "english": "fertilize", "type": "单词", "keyWords": ["fertile"] },
    { "chinese": "n.[U]施肥", "english": "fertilization", "type": "单词", "keyWords": ["fertile"] },
    { "chinese": "n.[C]节日；(音乐、戏剧等)活动节期间", "english": "festival", "type": "单词", "keyWords": [] },
    { "chinese": "v.(去)拿来", "english": "fetch", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]发烧；一时的狂热，激动，兴奋", "english": "fever", "type": "单词", "keyWords": [] },
    { "chinese": "a.发烧的；狂热的", "english": "feverish", "type": "单词", "keyWords": ["fever"] },
    { "chinese": "疯狂的活动", "english": "feverish activities", "type": "短语", "keyWords": ["feverish"] },
    { "chinese": "发烧", "english": "run a fever", "type": "短语", "keyWords": ["fever"] },
    { "chinese": "发高烧", "english": "have a high fever", "type": "短语", "keyWords": ["fever"] },
    { "chinese": "黄热病", "english": "yellow fever", "type": "短语", "keyWords": ["fever"] },
    { "chinese": "所有人都兴奋之极", "english": "Everyone was in a fever of excitement.", "type": "句子", "keyWords": ["fever"] },
    { "chinese": "a.很少的；几乎没有的", "english": "few", "type": "单词", "keyWords": [] },
    { "chinese": "一些", "english": "a few", "type": "短语", "keyWords": ["few"] },
    { "chinese": "只有几个", "english": "only a few", "type": "短语", "keyWords": ["few"] },
    { "chinese": "相当多；不少", "english": "quite a few", "type": "短语", "keyWords": ["few"] },
    { "chinese": "再一些", "english": "a few more", "type": "短语", "keyWords": ["few"] },
    { "chinese": "极少数", "english": "a very few", "type": "短语", "keyWords": ["few"] },
    { "chinese": "少数；少数人", "english": "the few", "type": "短语", "keyWords": ["few"] },
    { "chinese": "在过去的几年/几个星期里", "english": "in the last/past few years/weeks", "type": "短语", "keyWords": ["few"] },
    { "chinese": "一个话少的男人", "english": "a man of few words", "type": "短语", "keyWords": ["few"] },
    { "chinese": "(插入语)(仅)举几个为例", "english": "to name (only) a few", "type": "短语", "keyWords": ["few"] },
    { "chinese": "几乎没人来", "english": "Few have come.", "type": "句子", "keyWords": ["few"] },
    { "chinese": "n.[C]纤维", "english": "fibre", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][总称]小说；虚构的故事", "english": "fiction", "type": "单词", "keyWords": [] },
    { "chinese": "科幻小说", "english": "science fiction", "type": "短语", "keyWords": ["fiction"] },
    { "chinese": "n.[C]旷野；(一块)田；场地；战场；实地；野外；领域；专业", "english": "field", "type": "单词", "keyWords": [] },
    { "chinese": "田赛", "english": "field sports/ events", "type": "短语", "keyWords": ["field"] },
    { "chinese": "科学领域", "english": "(in) the field of science", "type": "短语", "keyWords": ["field"] },
    { "chinese": "不属于某人的专长", "english": "outside one's field", "type": "短语", "keyWords": ["field"] },
    { "chinese": "在棒球场/足球场", "english": "on the baseball/ soccer field", "type": "短语", "keyWords": ["field"] },
    { "chinese": "a.凶猛的；激烈的", "english": "fierce", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]强烈；凶猛；猛烈", "english": "fierceness", "type": "单词", "keyWords": ["fierce"] },
    { "chinese": "v.与...打仗；反对(通过议案等)；vi.战斗；打仗；奋斗；斗争；n.[C]斗争；打架", "english": "fight", "type": "单词", "keyWords": [] },
    { "chinese": "与困难作斗争", "english": "fight (against) difficulties", "type": "短语", "keyWords": ["fight"] },
    { "chinese": "奋力前进；艰苦奋斗；打出生路", "english": "fight one's way", "type": "短语", "keyWords": ["fight"] },
    { "chinese": "和某人斗争", "english": "fight with sb.", "type": "短语", "keyWords": ["fight"] },
    { "chinese": "为了...而战斗", "english": "fight for (better pay)", "type": "短语", "keyWords": ["fight"] },
    { "chinese": "n.[C]斗士，战士；战斗机，歼击机", "english": "fighter", "type": "单词", "keyWords": ["fight"] },
    { "chinese": "n.[C]数字；外形；轮廓；人影；人物；图形；v.计算；弄清；用图表(或图画)描述，描绘；塑造", "english": "figure", "type": "单词", "keyWords": [] },
    { "chinese": "保持身段", "english": "keep your figure", "type": "短语", "keyWords": ["figure"] },
    { "chinese": "算出；弄清楚", "english": "figure out", "type": "短语", "keyWords": ["figure"] },
    { "chinese": "合计", "english": "figure...up", "type": "短语", "keyWords": ["figure"] },
    { "chinese": "算出总费用", "english": "figure out the total cost", "type": "短语", "keyWords": ["figure"] },
    { "chinese": "查找引起楼顶火灾的原因", "english": "figure out what caused the rooftop fire", "type": "短语", "keyWords": ["figure"] },
    { "chinese": "你能找到谜底吗", "english": "Can you figure out this puzzle?", "type": "句子", "keyWords": ["figure"] },
    { "chinese": "让我们来找出帮助的办法吧", "english": "Let's figure out a way to help.", "type": "句子", "keyWords": ["figure"] },
    { "chinese": "n.[C]文件夹；档案；vt.把...归档", "english": "file", "type": "单词", "keyWords": [] },
    { "chinese": "v.装满；使充满；vi.充满(with)", "english": "fill", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]填充物；n.[C][U]填充；填料；馅", "english": "filling", "type": "单词", "keyWords": ["fill"] },
    { "chinese": "装满", "english": "be filled with", "type": "短语", "keyWords": ["fill"] },
    { "chinese": "填空", "english": "fill in the blanks", "type": "短语", "keyWords": ["fill"] },
    { "chinese": "填表", "english": "fill (in/ out) a form", "type": "短语", "keyWords": ["fill"] },
    { "chinese": "满足需求", "english": "fill a need/ demand", "type": "短语", "keyWords": ["fill"] },
    { "chinese": "充任；填补职位的空缺", "english": "fill a post/a job", "type": "短语", "keyWords": ["fill"] },
    { "chinese": "开支票", "english": "fill (out) a cheque", "type": "短语", "keyWords": ["fill"] },
    { "chinese": "n.[C]影片，电影；n.[C]胶片；薄膜/层；v.拍摄(影)", "english": "film", "type": "单词", "keyWords": [] },
    { "chinese": "爱上电影院的人，爱看电影的人", "english": "film goer", "type": "短语", "keyWords": ["film"] },
    { "chinese": "拍电影", "english": "make a film", "type": "短语", "keyWords": ["film"] },
    { "chinese": "电影制作", "english": "film-making", "type": "短语", "keyWords": ["film"] },
    { "chinese": "电影制作人", "english": "film-maker", "type": "短语", "keyWords": ["film"] },
    { "chinese": "把舞剧拍摄成电影", "english": "film a dance drama", "type": "短语", "keyWords": ["film"] },
    { "chinese": "洗一下这个胶卷", "english": "develop this film", "type": "短语", "keyWords": ["film"] },
    { "chinese": "钢琴上一层尘土", "english": "a film of dust on the piano", "type": "短语", "keyWords": ["film"] },
    { "chinese": "a.最终的，决定性的；n.[C](常pl.)决赛", "english": "final", "type": "单词", "keyWords": [] },
    { "chinese": "ad.最终地", "english": "finally", "type": "单词", "keyWords": ["final"] },
    { "chinese": "董事会有最高的决策权", "english": "The Board of Directors has the final say in all management matters.", "type": "句子", "keyWords": ["final"] },
    { "chinese": "n.[U]财政，金融；资金；v.提供资金给", "english": "finance", "type": "单词", "keyWords": [] },
    { "chinese": "a.财政的，金融的", "english": "financial", "type": "单词", "keyWords": ["finance"] },
    { "chinese": "n.[C]金融家", "english": "financier", "type": "单词", "keyWords": ["finance"] },
    { "chinese": "v.找到；发现", "english": "find", "type": "单词", "keyWords": [] },
    { "chinese": "n.(pl)发现的情况；发现物", "english": "findings", "type": "单词", "keyWords": ["find"] },
    { "chinese": "觉得某事容易", "english": "find sth. easy", "type": "短语", "keyWords": ["find"] },
    { "chinese": "觉得做某事容易", "english": "find it easy to do sth.", "type": "短语", "keyWords": ["find"] },
    { "chinese": "发现...正在做...", "english": "find sb./sth. doing sth.", "type": "短语", "keyWords": ["find"] },
    { "chinese": "找出；查明，弄清楚", "english": "find out", "type": "短语", "keyWords": ["find"] },
    { "chinese": "替我找本书", "english": "find me a book = find a book for me", "type": "短语", "keyWords": ["find"] },
    { "chinese": "发现...是/已...", "english": "find sb./sth. to be./to have done sth.", "type": "短语", "keyWords": ["find"] },
    { "chinese": "n.[C]罚款；vt.处...以罚金；a.好的；细[微)的；纤细的；精制的；ad.[口]很好", "english": "fine", "type": "单词", "keyWords": [] },
    { "chinese": "一场细雨", "english": "a fine rain", "type": "短语", "keyWords": ["fine"] },
    { "chinese": "他干得很出色", "english": "He's doing fine.", "type": "句子", "keyWords": ["fine"] },
    { "chinese": "受重罚", "english": "get a heavy fine", "type": "短语", "keyWords": ["fine"] },
    { "chinese": "微尘", "english": "fine dust", "type": "短语", "keyWords": ["fine"] },
    { "chinese": "付违章停车的罚款", "english": "pay a parking fine", "type": "短语", "keyWords": ["fine"] },
    { "chinese": "他因违反交通规则被罚200美元", "english": "He was fined 200 dollars for violation of traffic regulations.", "type": "句子", "keyWords": ["fine"] },
    { "chinese": "n.[C]手指", "english": "finger", "type": "单词", "keyWords": [] },
    { "chinese": "手势语", "english": "finger alphabet", "type": "短语", "keyWords": ["finger"] },
    { "chinese": "他笨手笨脚", "english": "His fingers are all thumbs.", "type": "句子", "keyWords": ["finger"] },
    { "chinese": "n.[C]指纹", "english": "fingerprint", "type": "单词", "keyWords": ["finger"] },
    { "chinese": "无名指", "english": "the ring finger", "type": "短语", "keyWords": ["finger"] },
    { "chinese": "v.完成；结束；使送命，完蛋", "english": "finish", "type": "单词", "keyWords": [] },
    { "chinese": "a.完成了的；完蛋了", "english": "finished", "type": "单词", "keyWords": ["finish"] },
    { "chinese": "完成做某事", "english": "finish doing", "type": "短语", "keyWords": ["finish"] },
    { "chinese": "结束；完成；用完；吃完；[口]干掉；毁掉", "english": "finish...off", "type": "短语", "keyWords": ["finish"] },
    { "chinese": "把桌上的东西统统吃掉", "english": "Finish off everything on the table.", "type": "句子", "keyWords": ["finish"] },
    { "chinese": "(赛跑的)终点线", "english": "finish(ing) line", "type": "短语", "keyWords": ["finish"] },
    { "chinese": "结束，(以...)告终", "english": "finish up (with..)", "type": "短语", "keyWords": ["finish"] },
    { "chinese": "那次惊吓几乎让他送命", "english": "That shock almost finished him.", "type": "句子", "keyWords": ["finish"] },
    { "chinese": "成品，产品", "english": "finished products", "type": "短语", "keyWords": ["finished"] },
    { "chinese": "我准备完了。/我累坏了。/我完蛋了", "english": "I am finished.", "type": "句子", "keyWords": ["finished"] },
    { "chinese": "我们之间的一切都结束了", "english": "Everything is finished between us!", "type": "句子", "keyWords": ["finished"] },
    { "chinese": "n.[U]火；n.[C]炉火；火灾；一堆火；v.开火；vt.使燃烧；开枪；[口]解雇；猛烈发出质问等", "english": "fire", "type": "单词", "keyWords": [] },
    { "chinese": "着火", "english": "catch fire", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "着火", "english": "be on fire", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "灭火", "english": "put out a fire", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "开火", "english": "open fire", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "点火", "english": "light a fire", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "被解雇了", "english": "be fired", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "耐火的，耐热的", "english": "fireproof", "type": "单词", "keyWords": ["fire"] },
    { "chinese": "生火", "english": "make a fire", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "火灾保险", "english": "fire-insurance", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "烧房子", "english": "set a house on fire= set fire to a house", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "向...射击", "english": "fire at", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "向我提出一连串问题", "english": "fire questions at me", "type": "短语", "keyWords": ["fire"] },
    { "chinese": "有烟必有火。/无风不起浪", "english": "There's no smoke without a fire.", "type": "句子", "keyWords": ["fire"] },
    { "chinese": "水火是忠仆，用之不慎成灾主", "english": "Fire and water are good servants, but bad masters.", "type": "句子", "keyWords": ["fire"] },
    { "chinese": "n.(pl)烟花，礼花", "english": "fireworks", "type": "单词", "keyWords": ["fire"] },
    { "chinese": "n.[C]公司；(合伙)商号，商行；a.坚定的；坚固的；ad.稳固地，坚定地", "english": "firm", "type": "单词", "keyWords": [] },
    { "chinese": "坚如磐石", "english": "as firm as a rock", "type": "短语", "keyWords": ["firm"] },
    { "chinese": "坚定他的信仰", "english": "hold firm to his beliefs", "type": "短语", "keyWords": ["firm"] },
    { "chinese": "ad.坚定地，稳固地", "english": "firmly", "type": "单词", "keyWords": ["firm"] },
    { "chinese": "n.[U]坚定，稳固", "english": "firmness", "type": "单词", "keyWords": ["firm"] },
    { "chinese": "站稳立场；坚定地站立", "english": "stand firm", "type": "短语", "keyWords": ["firm"] },
    { "chinese": "num./a./ad.第一(的)", "english": "first", "type": "单词", "keyWords": [] },
    { "chinese": "急救", "english": "first aid", "type": "短语", "keyWords": ["first"] },
    { "chinese": "首先", "english": "first of all", "type": "短语", "keyWords": ["first"] },
    { "chinese": "最初", "english": "at first", "type": "短语", "keyWords": ["first"] },
    { "chinese": "乍一看", "english": "at first sight", "type": "短语", "keyWords": ["first"] },
    { "chinese": "安全第一", "english": "safety first", "type": "短语", "keyWords": ["first"] },
    { "chinese": "头两天", "english": "the first two days", "type": "短语", "keyWords": ["first"] },
    { "chinese": "第一次...时(引导时间状语从句)", "english": "the first time+从句", "type": "短语", "keyWords": ["first"] },
    { "chinese": "第一次见到她我就爱上了她", "english": "I loved her the first time I saw her.", "type": "句子", "keyWords": ["first"] },
    { "chinese": "先到的先招待。/先到先得", "english": "First come, first served.", "type": "句子", "keyWords": ["first"] },
    { "chinese": "第一个做.../第一个来", "english": "be the first to (do..)/ be the first to come", "type": "短语", "keyWords": ["first"] },
    { "chinese": "第一次(直接作状语)", "english": "for the first time", "type": "短语", "keyWords": ["first"] },
    { "chinese": "最好的，第一流的，优秀的；头等舱的", "english": "first-class", "type": "短语", "keyWords": ["first"] },
    { "chinese": "第一流的，最上等的，极好的", "english": "first-rate", "type": "短语", "keyWords": ["first"] },
    { "chinese": "赢，获胜；考第一名", "english": "come out first/ come in first", "type": "短语", "keyWords": ["first"] },
    { "chinese": "首要的是，首先", "english": "first and foremost", "type": "短语", "keyWords": ["first"] },
    { "chinese": "a.第一手的；直接的；亲自得到的", "english": "firsthand", "type": "单词", "keyWords": ["first"] },
    { "chinese": "vi.捕鱼，钓鱼；vt.钓(鱼)；n.[C](pl.fish或fishes)鱼；n.[U]鱼肉", "english": "fish", "type": "单词", "keyWords": [] },
    { "chinese": "浑水摸鱼", "english": "fish in troubled waters", "type": "短语", "keyWords": ["fish"] },
    { "chinese": "酗酒，牛饮", "english": "drink like a fish", "type": "短语", "keyWords": ["fish"] },
    { "chinese": "不要教鱼游泳。/不要班门弄斧", "english": "Never offer to teach fish to swim.", "type": "句子", "keyWords": ["fish"] },
    { "chinese": "好鱼常在水底游。/珍贵的东西不会轻易得到", "english": "The best fish swim near the bottom.", "type": "句子", "keyWords": ["fish"] },
    { "chinese": "天涯何处无芳草", "english": "There are plenty more fish in the sea.", "type": "句子", "keyWords": ["fish"] },
    { "chinese": "n.[C]渔夫，捕鱼人", "english": "fisherman", "type": "单词", "keyWords": ["fish"] },
    { "chinese": "n.[C]拳；拳头", "english": "fist", "type": "单词", "keyWords": [] },
    { "chinese": "握拳", "english": "clench one's fist", "type": "短语", "keyWords": ["fist"] },
    { "chinese": "vt.(使)适合；安装；合...的身；使适配；vi.适配，符合；合身；a.适合的；健康的；n.[C]合身(的衣服)", "english": "fit", "type": "单词", "keyWords": [] },
    { "chinese": "这些鞋很合适(我穿)", "english": "These shoes fit (me).", "type": "句子", "keyWords": ["fit"] },
    { "chinese": "专门的训练使她适应这项工作", "english": "Specialized training fitted her for the job.", "type": "句子", "keyWords": ["fit"] },
    { "chinese": "这辆车有收音机吗", "english": "Is the car fitted with a radio?", "type": "句子", "keyWords": ["fit"] },
    { "chinese": "试穿", "english": "fit..on", "type": "短语", "keyWords": ["fit"] },
    { "chinese": "保持健康", "english": "keep fit", "type": "短语", "keyWords": ["fit"] },
    { "chinese": "跟...相适应", "english": "fit in with", "type": "短语", "keyWords": ["fit"] },
    { "chinese": "给门安上一个把手", "english": "fit a handle on a door", "type": "短语", "keyWords": ["fit"] },
    { "chinese": "适合(做)...", "english": "be fit for sth./ to do sth.", "type": "短语", "keyWords": ["fit"] },
    { "chinese": "他与这些人格格不入", "english": "He doesn't fit in with these people.", "type": "句子", "keyWords": ["fit"] },
    { "chinese": "这件衣服非常合身", "english": "This garment is an excellent fit.", "type": "句子", "keyWords": ["fit"] },
    { "chinese": "vt.使固定；修理；安装；确定，决定", "english": "fix", "type": "单词", "keyWords": [] },
    { "chinese": "a.固定的；确定的", "english": "fixed", "type": "单词", "keyWords": ["fix"] },
    { "chinese": "注视", "english": "fix one's eyes on/ upon", "type": "短语", "keyWords": ["fix"] },
    { "chinese": "把图画固定在墙上", "english": "fix the picture on the wall", "type": "短语", "keyWords": ["fix"] },
    { "chinese": "确定开会日期", "english": "fix the date for the meeting", "type": "短语", "keyWords": ["fix"] },
    { "chinese": "把足球赛安排在星期六下午", "english": "fix the football game for Saturday afternoon", "type": "短语", "keyWords": ["fix"] },
    { "chinese": "在某一固定时间", "english": "at a fixed time", "type": "短语", "keyWords": ["fixed"] },
    { "chinese": "修汽车", "english": "fix a car", "type": "短语", "keyWords": ["fix"] },
    { "chinese": "n.[C]旗", "english": "flag", "type": "单词", "keyWords": [] },
    { "chinese": "国旗", "english": "the national flag", "type": "短语", "keyWords": ["flag"] },
    { "chinese": "升旗", "english": "lift/ raise a flag", "type": "短语", "keyWords": ["flag"] },
    { "chinese": "n.[C]薄片", "english": "flake", "type": "单词", "keyWords": [] },
    { "chinese": "雪片", "english": "snow flakes", "type": "短语", "keyWords": ["flake"] },
    { "chinese": "n.[C][U]火焰", "english": "flame", "type": "单词", "keyWords": [] },
    { "chinese": "燃烧起来", "english": "burst into flame", "type": "短语", "keyWords": ["flame"] },
    { "chinese": "燃烧着", "english": "in flames", "type": "短语", "keyWords": ["flame"] },
    { "chinese": "n.[C]闪光；闪现；一瞬间；v./vi.闪(光)；(使)闪光；一闪而过", "english": "flash", "type": "单词", "keyWords": [] },
    { "chinese": "追叙", "english": "flash back to", "type": "短语", "keyWords": ["flash"] },
    { "chinese": "一瞬间；马上", "english": "in a flash", "type": "短语", "keyWords": ["flash"] },
    { "chinese": "一线希望", "english": "a flash of hope", "type": "短语", "keyWords": ["flash"] },
    { "chinese": "影像/图像闪现在荧光屏上", "english": "The image flashed onto the screen.", "type": "句子", "keyWords": ["flash"] },
    { "chinese": "他们把那个影像/图像闪现在荧光屏上", "english": "They flashed the image onto the screen.", "type": "句子", "keyWords": ["flash"] },
    { "chinese": "n.[C]套房，公寓；a.平的；平坦的；扁平的；ad.平直，仰卧", "english": "flat", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]平坦", "english": "flatness", "type": "单词", "keyWords": ["flat"] },
    { "chinese": "瘪气轮胎", "english": "a flat tyre", "type": "短语", "keyWords": ["flat"] },
    { "chinese": "平卧", "english": "lie flat", "type": "短语", "keyWords": ["flat"] },
    { "chinese": "n.[C][U]滋味；香味；风味；[美]调味品；特点，特色；气味", "english": "flavour", "type": "单词", "keyWords": [] },
    { "chinese": "vi.(fled, fled)逃跑(from)；vt.逃避", "english": "flee", "type": "单词", "keyWords": [] },
    { "chinese": "逃离祖国", "english": "flee one's country", "type": "短语", "keyWords": ["flee"] },
    { "chinese": "n.[U]肌肉；果肉", "english": "flesh", "type": "单词", "keyWords": [] },
    { "chinese": "肉体；血肉之躯", "english": "flesh and blood", "type": "短语", "keyWords": ["flesh"] },
    { "chinese": "食肉动物", "english": "flesh-eating animals", "type": "短语", "keyWords": ["flesh"] },
    { "chinese": "a.易弯曲的，柔韧的；灵活的", "english": "flexible", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]易弯曲，柔韧；灵活，机动性", "english": "flexibility", "type": "单词", "keyWords": ["flexible"] },
    { "chinese": "n.[C]航班；飞行；逃走；一段楼梯", "english": "flight", "type": "单词", "keyWords": [] },
    { "chinese": "上四段楼梯", "english": "climb four flights of stairs", "type": "短语", "keyWords": ["flight"] },
    { "chinese": "在飞行中", "english": "in flight", "type": "短语", "keyWords": ["flight"] },
    { "chinese": "战还是逃", "english": "Fight or flight?", "type": "句子", "keyWords": ["flight"] },
    { "chinese": "vi.浮游；漂浮；漂流；vt.使漂浮", "english": "float", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]洪水；vt.淹没；vi.溢出；涌进；泛滥", "english": "flood", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]泛滥", "english": "flooding", "type": "单词", "keyWords": ["flood"] },
    { "chinese": "淹没地区", "english": "flooded areas", "type": "短语", "keyWords": ["flood"] },
    { "chinese": "大批信件", "english": "a flood of letters", "type": "短语", "keyWords": ["flood"] },
    { "chinese": "涌进城", "english": "flood into the city", "type": "短语", "keyWords": ["flood"] },
    { "chinese": "n.[C](桥梁等的)面；地板；(楼房的)层；海底；(室内的)场地", "english": "floor", "type": "单词", "keyWords": [] },
    { "chinese": "在底楼；[英]在二楼", "english": "on the first floor", "type": "短语", "keyWords": ["floor"] },
    { "chinese": "n.[C]泛光灯；强力照明；vt.用泛光灯照亮", "english": "floodlight", "type": "单词", "keyWords": ["flood"] },
    { "chinese": "n.[U]面粉", "english": "flour", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]流动；流程；vi.(液体等)流动，涌流；川流不息", "english": "flow", "type": "单词", "keyWords": [] },
    { "chinese": "川流不息的交通", "english": "the flow of traffic", "type": "短语", "keyWords": ["flow"] },
    { "chinese": "n.[C]花", "english": "flower", "type": "单词", "keyWords": [] },
    { "chinese": "a.花开着的，用花装饰的", "english": "flowered", "type": "单词", "keyWords": ["flower"] },
    { "chinese": "开着花", "english": "be in (full) flower", "type": "短语", "keyWords": ["flower"] },
    { "chinese": "开始开花", "english": "come into flower", "type": "短语", "keyWords": ["flower"] },
    { "chinese": "花衬衫", "english": "a flowered blouse", "type": "短语", "keyWords": ["flowered"] },
    { "chinese": "n.[U]流行性感冒", "english": "flu", "type": "单词", "keyWords": [] },
    { "chinese": "a.流利的；(文体)流畅的", "english": "fluent", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]流利", "english": "fluency", "type": "单词", "keyWords": ["fluent"] },
    { "chinese": "ad.流利地", "english": "fluently", "type": "单词", "keyWords": ["fluent"] },
    { "chinese": "vi.动；(鸟等)振翼；使飘动；(振)翼", "english": "flutter", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]脸红(可和a连用)；vi.脸红", "english": "flush", "type": "单词", "keyWords": [] },
    { "chinese": "气得满脸通红", "english": "flush with anger", "type": "短语", "keyWords": ["flush"] },
    { "chinese": "v.驾驶(飞机等)；使飞；空运；vi.乘或驾驶飞机；飞翔，飘扬；飞逝；n.[C]苍蝇", "english": "fly", "type": "单词", "keyWords": [] },
    { "chinese": "a.会飞的；飞行的；飘扬的", "english": "flying", "type": "单词", "keyWords": ["fly"] },
    { "chinese": "放风筝", "english": "fly a kite", "type": "短语", "keyWords": ["fly"] },
    { "chinese": "时光飞逝", "english": "Time flies!", "type": "句子", "keyWords": ["fly"] },
    { "chinese": "乘飞机去/飞往达拉斯", "english": "fly to Dallas", "type": "短语", "keyWords": ["fly"] },
    { "chinese": "给受灾地区空运救急物资", "english": "fly emergency supplies to a stricken area", "type": "短语", "keyWords": ["fly"] },
    { "chinese": "n.[C]飞行器，航空器", "english": "flyer", "type": "单词", "keyWords": ["fly"] },
    { "chinese": "vi/vt.集中；聚焦；n.[C](兴趣活动等的)中心，集中点；焦点；焦距", "english": "focus", "type": "单词", "keyWords": [] },
    { "chinese": "集中...在...上", "english": "focus... on...", "type": "短语", "keyWords": ["focus"] },
    { "chinese": "大家的目光都集中在发言人身上", "english": "All eyes were focused on the speaker.", "type": "句子", "keyWords": ["focus"] },
    { "chinese": "使...成关注中心", "english": "bring ...into focus", "type": "短语", "keyWords": ["focus"] },
    { "chinese": "n.[C]雾", "english": "fog", "type": "单词", "keyWords": [] },
    { "chinese": "a.有雾的", "english": "foggy", "type": "单词", "keyWords": ["fog"] },
    { "chinese": "v.折叠；n.[C]褶子", "english": "fold", "type": "单词", "keyWords": [] },
    { "chinese": "对折", "english": "fold sth. in two/half", "type": "短语", "keyWords": ["fold"] },
    { "chinese": "交叉腿/双臂", "english": "fold your legs/arms", "type": "短语", "keyWords": ["fold"] },
    { "chinese": "折叠床/椅/门", "english": "a folding bed/ chair/ door", "type": "短语", "keyWords": ["fold"] },
    { "chinese": "n.[C][口]人们；a.民间的", "english": "folk", "type": "单词", "keyWords": [] },
    { "chinese": "民间音乐", "english": "folk music", "type": "短语", "keyWords": ["folk"] },
    { "chinese": "老人们", "english": "the old folk(s)", "type": "短语", "keyWords": ["folk"] },
    { "chinese": "vt/vi.跟随；遵循；听懂", "english": "follow", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]跟随者", "english": "follower", "type": "单词", "keyWords": ["follow"] },
    { "chinese": "a.下列的；接着的", "english": "following", "type": "单词", "keyWords": ["follow"] },
    { "chinese": "学某人", "english": "follow the example of sb.", "type": "短语", "keyWords": ["follow"] },
    { "chinese": "跟随某人/听懂某人的话", "english": "follow sb.", "type": "短语", "keyWords": ["follow"] },
    { "chinese": "效仿别人", "english": "follow suit", "type": "短语", "keyWords": ["follow"] },
    { "chinese": "遵从某人的愿望/听从命令", "english": "follow one's wishes/ orders", "type": "短语", "keyWords": ["follow"] },
    { "chinese": "在接下去的几天里", "english": "in the days that follow/ come; in the following/ coming days; in the days to follow/ come", "type": "短语", "keyWords": ["follow","following"] },
    { "chinese": "在接下去的几天里请继续收听我们更多的详细报道", "english": "Stay tuned for more details in the days to follow.", "type": "句子", "keyWords": ["follow"] },
    { "chinese": "如下", "english": "as follows", "type": "短语", "keyWords": ["follow"] },
    { "chinese": "具体措施如下", "english": "Concrete measures are as follows.", "type": "句子", "keyWords": ["follow"] },
    { "chinese": "其结果当然是...", "english": "It follows that...", "type": "短语", "keyWords": ["follow"] },
    { "chinese": "a.喜爱的（只作表语）", "english": "fond", "type": "单词", "keyWords": [] },
    { "chinese": "爱好；喜欢", "english": "be fond of", "type": "短语", "keyWords": ["fond"] },
    { "chinese": "n.[U]食物", "english": "food", "type": "单词", "keyWords": [] },
    { "chinese": "各种食物", "english": "foods", "type": "短语", "keyWords": ["food"] },
    { "chinese": "食物链", "english": "food chain", "type": "短语", "keyWords": ["food"] },
    { "chinese": "食品添加剂", "english": "food additives", "type": "短语", "keyWords": ["food"] },
    { "chinese": "n.[C]蠢人 vt.欺骗，愚弄", "english": "fool", "type": "单词", "keyWords": [] },
    { "chinese": "a.愚蠢的，荒谬的", "english": "foolish", "type": "单词", "keyWords": [] },
    { "chinese": "嘲弄，欺骗", "english": "make a fool of...", "type": "短语", "keyWords": ["fool"] },
    { "chinese": "傻到做某事", "english": "be fool enough to do sth.", "type": "短语", "keyWords": ["fool"] },
    { "chinese": "某人做某事是愚蠢的", "english": "It's foolish/ stupid/ silly of sb. to do sth.", "type": "句子", "keyWords": ["foolish"] },
    { "chinese": "n.[C]脚；（山）麓；英尺", "english": "foot", "type": "单词", "keyWords": [] },
    { "chinese": "脚注，补充", "english": "foot-note", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "脚印", "english": "footprint", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "站着", "english": "be on one's feet", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "步行", "english": "on foot", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "（挣扎着）站起来", "english": "struggle to one's feet", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "失足；踏空", "english": "miss one's foot", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "站起来", "english": "rise to get on one's feet", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "突然站起，跳起", "english": "jump/ spring to one's feet", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "在山脚下，在山的下部", "english": "at the foot of the mountain", "type": "短语", "keyWords": ["foot"] },
    { "chinese": "n.[C]脚步；脚步声；一步跨出去的距离", "english": "footstep", "type": "单词", "keyWords": [] },
    { "chinese": "prep.为了；因为；至于；适合于；对...支持；等值，等量；达；计 conj.因为", "english": "for", "type": "单词", "keyWords": [] },
    { "chinese": "赞成，支持", "english": "be for", "type": "短语", "keyWords": ["for"] },
    { "chinese": "毫无疑问，肯定地，有把握", "english": "for sure/certain", "type": "短语", "keyWords": ["for"] },
    { "chinese": "暂时；目前", "english": "for the time being", "type": "短语", "keyWords": ["for"] },
    { "chinese": "出售，待售", "english": "for sale", "type": "短语", "keyWords": ["for"] },
    { "chinese": "为了...（起见/缘故）", "english": "for the sake of...", "type": "短语", "keyWords": ["for"] },
    { "chinese": "永远", "english": "for good", "type": "短语", "keyWords": ["for"] },
    { "chinese": "把...视为当然", "english": "take ... for granted", "type": "短语", "keyWords": ["for"] },
    { "chinese": "不收费；白白地", "english": "for nothing", "type": "短语", "keyWords": ["for"] },
    { "chinese": "每前进三步后退一步", "english": "take a step back for every three steps forward", "type": "句子", "keyWords": ["for"] },
    { "chinese": "儿童图书", "english": "books (meant/ intended) for children", "type": "短语", "keyWords": ["for"] },
    { "chinese": "第一/一则，...再说/再则...", "english": "For one thing,...and for another,...", "type": "句子", "keyWords": ["for"] },
    { "chinese": "就他的年龄而言，他是个高个子", "english": "He is tall for his age.", "type": "句子", "keyWords": ["for"] },
    { "chinese": "要不是某人的话", "english": "If it were not for sb.,...", "type": "句子", "keyWords": ["for"] },
    { "chinese": "尽管", "english": "for all...", "type": "短语", "keyWords": ["for"] },
    { "chinese": "尽管还存在许多问题，这仍不失为一次宝贵的经历", "english": "For all the problems, it was a valuable experience.", "type": "句子", "keyWords": ["for"] },
    { "chinese": "尽管你这样说，我还是喜欢他", "english": "For all you say,I still like him.", "type": "句子", "keyWords": ["for"] },
    { "chinese": "vt.禁止，不许", "english": "forbid", "type": "单词", "keyWords": [] },
    { "chinese": "a.禁止的，严禁的", "english": "forbidden", "type": "单词", "keyWords": ["forbid"] },
    { "chinese": "禁止某人...", "english": "forbid sb. sth.", "type": "短语", "keyWords": ["forbid"] },
    { "chinese": "他的父母不准他喝酒", "english": "His parents forbid him wine.", "type": "句子", "keyWords": ["forbid"] },
    { "chinese": "禁止某人去做某事", "english": "forbid sb. to do sth.", "type": "短语", "keyWords": ["forbid"] },
    { "chinese": "大多数父母都同意禁止自己的孩子抽烟", "english": "Most of the parents agree to forbid their children to smoke.", "type": "句子", "keyWords": ["forbid"] },
    { "chinese": "禁止做某事", "english": "forbid doing sth.", "type": "短语", "keyWords": ["forbid"] },
    { "chinese": "火车上禁止吸烟", "english": "forbid smoking on trains", "type": "句子", "keyWords": ["forbid"] },
    { "chinese": "禁区", "english": "forbidden zone", "type": "短语", "keyWords": ["forbidden"] },
    { "chinese": "紫禁城", "english": "Forbidden City", "type": "短语", "keyWords": ["forbidden"] },
    { "chinese": "n.[U]力，力量；暴力；气势 [C]势力；军队，兵力 vt./n.逼迫；强加；强取", "english": "force", "type": "单词", "keyWords": [] },
    { "chinese": "地心引力的力量", "english": "the force of gravity", "type": "短语", "keyWords": ["force"] },
    { "chinese": "强颜欢笑，苦笑", "english": "a forced smile", "type": "短语", "keyWords": ["force"] },
    { "chinese": "开始实施，生效", "english": "come/go into force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "强颜欢笑，苦笑", "english": "force a smile", "type": "短语", "keyWords": ["force"] },
    { "chinese": "使生效，实施", "english": "put/ bring ...into force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "逼迫某人做某事", "english": "force sb. to do/into doing sth.", "type": "短语", "keyWords": ["force"] },
    { "chinese": "把他的意见强加给别人", "english": "force his ideas upon others", "type": "句子", "keyWords": ["force"] },
    { "chinese": "用暴力", "english": "by force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "武力侵占", "english": "take.. by force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "生效，有效", "english": "be in force", "type": "短语", "keyWords": ["force"] },
    { "chinese": "强行进入", "english": "force an entry", "type": "短语", "keyWords": ["force"] },
    { "chinese": "强行穿过人群", "english": "force our way through the crowd", "type": "句子", "keyWords": ["force"] },
    { "chinese": "a.有力的；有说服力的", "english": "forceful", "type": "单词", "keyWords": ["force"] },
    { "chinese": "ad.强有力地，激烈地", "english": "forcefully", "type": "单词", "keyWords": ["forceful"] },
    { "chinese": "前臂", "english": "forearm", "type": "单词", "keyWords": [] },
    { "chinese": "祖先", "english": "forefather", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]预测；预报", "english": "forecast", "type": "单词", "keyWords": [] },
    { "chinese": "天气预报", "english": "the weather forecast", "type": "短语", "keyWords": ["forecast"] },
    { "chinese": "n.[C]额；前额", "english": "forehead", "type": "单词", "keyWords": [] },
    { "chinese": "a.外国的；对外的", "english": "foreign", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]外国人", "english": "foreigner", "type": "单词", "keyWords": ["foreign"] },
    { "chinese": "无关；不适宜的", "english": "be foreign to sb.", "type": "短语", "keyWords": ["foreign"] },
    { "chinese": "你的争辩与本问题无关", "english": "Your argument is foreign to the question.", "type": "句子", "keyWords": ["foreign"] },
    { "chinese": "a.最先的，最初的；最重要的", "english": "foremost", "type": "单词", "keyWords": [] },
    { "chinese": "首先，第一", "english": "first and foremost", "type": "短语", "keyWords": ["foremost"] },
    { "chinese": "vt.预见；预知", "english": "foresee", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]林区；森林", "english": "forest", "type": "单词", "keyWords": [] },
    { "chinese": "雨林", "english": "rain forest", "type": "短语", "keyWords": ["forest"] },
    { "chinese": "禁伐区；森林保护区", "english": "a forest reserve", "type": "短语", "keyWords": ["forest"] },
    { "chinese": "ad.永远", "english": "forever", "type": "单词", "keyWords": [] },
    { "chinese": "vt./vi.忘记", "english": "forget", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]健忘", "english": "forgetfulness", "type": "单词", "keyWords": ["forget"] },
    { "chinese": "忘了已经做过某事", "english": "forget doing...", "type": "短语", "keyWords": ["forget"] },
    { "chinese": "忘了去做某事", "english": "forget to do...", "type": "短语", "keyWords": ["forget"] },
    { "chinese": "噢，别再提了！", "english": "Oh,forget (about) it.", "type": "句子", "keyWords": ["forget"] },
    { "chinese": "关于某事不记得什么了", "english": "forget (all) about sth.", "type": "短语", "keyWords": ["forget"] },
    { "chinese": "别忘记代我问候你的父母亲", "english": "Don't forget me to your parents.", "type": "句子", "keyWords": ["forget"] },
    { "chinese": "让我们不念旧恶/摒弃前嫌/捐弃前嫌", "english": "Let's forgive and forget.", "type": "句子", "keyWords": ["forget"] },
    { "chinese": "a.容易被忘的；可忘记的", "english": "forgettable", "type": "单词", "keyWords": ["forget"] },
    { "chinese": "vt.宽恕，原谅", "english": "forgive", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]宽恕，宽仁之心", "english": "forgiveness", "type": "单词", "keyWords": ["forgive"] },
    { "chinese": "原谅某事", "english": "forgive doing sth.", "type": "短语", "keyWords": ["forgive"] },
    { "chinese": "原谅某人做某事", "english": "forgive sb. for doing sth.", "type": "短语", "keyWords": ["forgive"] },
    { "chinese": "n.[C]餐叉；（树、路的）分支 v.（使）成叉状；分岔", "english": "fork", "type": "单词", "keyWords": [] },
    { "chinese": "（吃西餐用的）一副刀叉", "english": "a knife and fork", "type": "短语", "keyWords": ["fork"] },
    { "chinese": "n.[C]形式；方式；外形；表格 v.形成；构成；组成，建立 v.成形", "english": "form", "type": "单词", "keyWords": [] },
    { "chinese": "填写表格", "english": "fill (in/ out) a form", "type": "短语", "keyWords": ["form"] },
    { "chinese": "形式与内容", "english": "form and content", "type": "短语", "keyWords": ["form"] },
    { "chinese": "以...的形式", "english": "in the form of", "type": "短语", "keyWords": ["form"] },
    { "chinese": "a.正式的", "english": "formal", "type": "单词", "keyWords": ["form"] },
    { "chinese": "a.非正式的", "english": "informal", "type": "单词", "keyWords": ["formal"] },
    { "chinese": "a.在前的；以前的；（两者中）前面的", "english": "former", "type": "单词", "keyWords": [] },
    { "chinese": "前任总统/以前的学生/前妻", "english": "former president/student/wife", "type": "短语", "keyWords": ["former"] },
    { "chinese": "前者是…后者是…", "english": "The former is...and the latter...", "type": "句子", "keyWords": ["former"] },
    { "chinese": "ad.向前", "english": "forth", "type": "单词", "keyWords": [] },
    { "chinese": "提出；产生", "english": "bring/put... forth", "type": "短语", "keyWords": ["forth"] },
    { "chinese": "来来往往地，来回地", "english": "back and forth", "type": "短语", "keyWords": ["forth"] },
    { "chinese": "num.四十", "english": "forty", "type": "单词", "keyWords": [] },
    { "chinese": "num.第四十；四十分之一", "english": "fortieth", "type": "单词", "keyWords": ["forty"] },
    { "chinese": "在他们四十几岁时", "english": "in their forties", "type": "短语", "keyWords": ["forty"] },
    { "chinese": "在20世纪40年代早期", "english": "in the early nineteen forties = in the early 1940's/ 1940s", "type": "句子", "keyWords": ["forty"] },
    { "chinese": "a.幸运的，侥幸的；吉利的；幸福的", "english": "fortunate", "type": "单词", "keyWords": [] },
    { "chinese": "ad.幸运地；幸亏", "english": "fortunately", "type": "单词", "keyWords": ["fortunate"] },
    { "chinese": "幸运的是我避开了飓风", "english": "Fortunately, I missed the hurricane.", "type": "句子", "keyWords": ["fortunately"] },
    { "chinese": "n.[C]财富 [C][U]（好）运气", "english": "fortune", "type": "单词", "keyWords": [] },
    { "chinese": "一小/一大笔钱", "english": "a small/ large fortune", "type": "短语", "keyWords": ["fortune"] },
    { "chinese": "发财", "english": "make a fortune", "type": "短语", "keyWords": ["fortune"] },
    { "chinese": "碰碰运气", "english": "try one's fortune", "type": "短语", "keyWords": ["fortune"] },
    { "chinese": "算命者", "english": "fortune teller", "type": "短语", "keyWords": ["fortune"] },
    { "chinese": "a.向前的；前进的 ad.向前；前进 v.促进；转变；发送", "english": "forward", "type": "单词", "keyWords": [] },
    { "chinese": "ad.向前；前进", "english": "forwards", "type": "单词", "keyWords": ["forward"] },
    { "chinese": "向前运动", "english": "a forward movement", "type": "短语", "keyWords": ["forward"] },
    { "chinese": "提出建议", "english": "put forward a proposal", "type": "短语", "keyWords": ["forward"] },
    { "chinese": "期盼；等待", "english": "look forward to (doing) sth.", "type": "短语", "keyWords": ["forward"] },
    { "chinese": "客户的申请转发给银行员工进行审核", "english": "The customer's application is forwarded to a bank employee for review.", "type": "句子", "keyWords": ["forward"] },
    { "chinese": "v.创立；创建", "english": "found", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]基金（会）；基础 [U]创建", "english": "foundation", "type": "单词", "keyWords": ["found"] },
    { "chinese": "n.[C]创建者", "english": "founder", "type": "单词", "keyWords": ["found"] },
    { "chinese": "为...打下坚实的基础", "english": "lay a solid foundation for", "type": "短语", "keyWords": ["foundation"] },
    { "chinese": "n.[C]泉水；人造喷泉；源泉", "english": "fountain", "type": "单词", "keyWords": [] },
    { "chinese": "智慧的源泉", "english": "a fountain/ source of wisdom", "type": "短语", "keyWords": ["fountain"] },
    { "chinese": "n.[C]狐狸", "english": "fox", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]框架，构架；窗框；镜框 v.给...装框；构筑；制定，拟定", "english": "frame", "type": "单词", "keyWords": [] },
    { "chinese": "为画装上框", "english": "frame a painting", "type": "短语", "keyWords": ["frame"] },
    { "chinese": "a.坦白的，直率的；真诚的", "english": "frank", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]坦白，直率；真诚", "english": "frankness", "type": "单词", "keyWords": ["frank"] },
    { "chinese": "坦白地说，...", "english": "To be frank (with you),...", "type": "句子", "keyWords": ["frank"] },
    { "chinese": "a.免费的；自由的；空闲的 v.使自由，释放，解放；使摆脱；清除 ad.免费", "english": "free", "type": "单词", "keyWords": [] },
    { "chinese": "释放某人", "english": "set sb. free=free sb.", "type": "短语", "keyWords": ["free"] },
    { "chinese": "无息贷款", "english": "an interest-free loan", "type": "短语", "keyWords": ["free"] },
    { "chinese": "不冻港", "english": "an ice-free harbor", "type": "短语", "keyWords": ["free"] },
    { "chinese": "禁烟室", "english": "a smoke-free room", "type": "短语", "keyWords": ["free"] },
    { "chinese": "免费", "english": "for free", "type": "短语", "keyWords": ["free"] },
    { "chinese": "绳的没有固定住的那一端", "english": "the free end of a rope", "type": "短语", "keyWords": ["free"] },
    { "chinese": "没有...的；免除的", "english": "be free of/from", "type": "短语", "keyWords": ["free"] },
    { "chinese": "免费", "english": "free of charge", "type": "短语", "keyWords": ["free"] },
    { "chinese": "老妇人一直在受苦", "english": "The old lady is never free from pain.", "type": "句子", "keyWords": ["free"] },
    { "chinese": "免税的那部分收入", "english": "the income that is free of all taxes", "type": "短语", "keyWords": ["free"] },
    { "chinese": "n.[U]自由", "english": "freedom", "type": "单词", "keyWords": ["free"] },
    { "chinese": "vi.结冰，凝固；变得极度寒冷；惊呆住，愣住 vt.使冷冻，使结冰", "english": "freeze", "type": "单词", "keyWords": [] },
    { "chinese": "我简直冻僵了", "english": "I'm freezing (to death).", "type": "句子", "keyWords": ["freeze"] },
    { "chinese": "冻死", "english": "freeze to death", "type": "短语", "keyWords": ["freeze"] },
    { "chinese": "吓得浑身冰冷", "english": "make one's blood freeze", "type": "短语", "keyWords": ["freeze"] },
    { "chinese": "吓得呆住了", "english": "freeze with fear", "type": "短语", "keyWords": ["freeze"] },
    { "chinese": "他们脸上的笑容僵住了", "english": "Smiles froze on their faces.", "type": "句子", "keyWords": ["freeze"] },
    { "chinese": "a.冻结的，极冷的 n.[U]冻结；冰点", "english": "freezing", "type": "单词", "keyWords": ["freeze"] },
    { "chinese": "a.冰冻的", "english": "frozen", "type": "单词", "keyWords": ["freeze"] },
    { "chinese": "冰点", "english": "freezing point", "type": "短语", "keyWords": ["freezing"] },
    { "chinese": "极冷的", "english": "freezing cold", "type": "短语", "keyWords": ["freezing"] },
    { "chinese": "冻肉", "english": "frozen meat", "type": "短语", "keyWords": ["frozen"] },
    { "chinese": "n.[U]法语 a.法国的；法国人的；法语的", "english": "French", "type": "单词", "keyWords": [] },
    { "chinese": "法国人", "english": "the French", "type": "短语", "keyWords": ["French"] },
    { "chinese": "a.时常发生的，频繁的", "english": "frequent", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]经常；频繁 [C]频率", "english": "frequency", "type": "单词", "keyWords": ["frequent"] },
    { "chinese": "ad.时常地；频繁地", "english": "frequently", "type": "单词", "keyWords": ["frequent"] },
    { "chinese": "a.新鲜的", "english": "fresh", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]气味清新，精神饱满", "english": "freshness", "type": "单词", "keyWords": ["fresh"] },
    { "chinese": "清新的空气", "english": "fresh air", "type": "短语", "keyWords": ["fresh"] },
    { "chinese": "新生，大学一年级学生", "english": "freshman", "type": "单词", "keyWords": ["fresh"] },
    { "chinese": "新鲜的食物", "english": "fresh food", "type": "短语", "keyWords": ["fresh"] },
    { "chinese": "淡水", "english": "fresh water", "type": "短语", "keyWords": ["fresh"] },
    { "chinese": "n.[C]星期五", "english": "Friday", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]冰箱", "english": "fridge", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]朋友", "english": "friend", "type": "单词", "keyWords": [] },
    { "chinese": "a.友好的；朋友（般）的", "english": "friendly", "type": "单词", "keyWords": ["friend"] },
    { "chinese": "n.[U]友好", "english": "friendliness", "type": "单词", "keyWords": ["friendly"] },
    { "chinese": "与...交朋友", "english": "make/be friends with", "type": "短语", "keyWords": ["friend"] },
    { "chinese": "心腹之交，密友，知己", "english": "close friends", "type": "短语", "keyWords": ["friend"] },
    { "chinese": "友好地", "english": "in a friendly way", "type": "短语", "keyWords": ["friendly"] },
    { "chinese": "与…友好", "english": "be friendly to sb.", "type": "短语", "keyWords": ["friendly"] },
    { "chinese": "陈酒味醇，老友情深", "english": "Old friends and old wine are best.", "type": "句子", "keyWords": ["friend"] },
    { "chinese": "n.[C][U]友谊；友好", "english": "friendship", "type": "单词", "keyWords": ["friend"] },
    { "chinese": "50年的友情", "english": "a friendship of 50years", "type": "短语", "keyWords": ["friendship"] },
    { "chinese": "促进友谊", "english": "promote friendship", "type": "短语", "keyWords": ["friendship"] },
    { "chinese": "vt.使..惊恐", "english": "frighten", "type": "单词", "keyWords": [] },
    { "chinese": "a.受惊吓的", "english": "frightened", "type": "单词", "keyWords": ["frighten"] },
    { "chinese": "a.令人惊恐的", "english": "frightening", "type": "单词", "keyWords": ["frighten"] },
    { "chinese": "n.[C][U]惊骇，吃惊", "english": "fright", "type": "单词", "keyWords": ["frighten"] },
    { "chinese": "a.可怕的；非常的", "english": "frightful", "type": "单词", "keyWords": ["fright"] },
    { "chinese": "处于惊恐状态", "english": "in fright", "type": "短语", "keyWords": ["fright"] },
    { "chinese": "吓跑，吓走", "english": "frighten...away", "type": "短语", "keyWords": ["frighten"] },
    { "chinese": "用恐吓手段迫使某人做/不做某事", "english": "frighten sb. into/out of doing sth.", "type": "短语", "keyWords": ["frighten"] },
    { "chinese": "害怕做某事", "english": "be frightened to do sth.", "type": "短语", "keyWords": ["frightened"] },
    { "chinese": "害怕某事", "english": "be frightened of sth.", "type": "短语", "keyWords": ["frightened"] },
    { "chinese": "使某人受惊；吓某人一跳", "english": "give sb. a fright", "type": "短语", "keyWords": ["fright"] },
    { "chinese": "把某人吓死", "english": "frighten sb. to death", "type": "短语", "keyWords": ["frighten"] },
    { "chinese": "因...受惊", "english": "be frightened at sth.", "type": "短语", "keyWords": ["frightened"] },
    { "chinese": "n.[C]蛙", "english": "frog", "type": "单词", "keyWords": [] },
    { "chinese": "prep.从；（表来源）来自于；离开（脱离）；由于", "english": "from", "type": "单词", "keyWords": [] },
    { "chinese": "挨家挨户", "english": "from house to house", "type": "短语", "keyWords": ["from"] },
    { "chinese": "从桌下", "english": "from under the table", "type": "短语", "keyWords": ["from"] },
    { "chinese": "从我的观点看", "english": "from my point of view", "type": "短语", "keyWords": ["from"] },
    { "chinese": "愈来愈坏，每况愈下", "english": "from bad to worse", "type": "短语", "keyWords": ["from"] },
    { "chinese": "从那时起", "english": "from then on", "type": "短语", "keyWords": ["from"] },
    { "chinese": "饿昏了", "english": "faint from hunger", "type": "句子", "keyWords": ["from"] },
    { "chinese": "辨别是非", "english": "know right from wrong", "type": "短语", "keyWords": ["from"] },
    { "chinese": "n.[C]（the）前线；前面", "english": "front", "type": "单词", "keyWords": [] },
    { "chinese": "标题版，头版", "english": "front page", "type": "短语", "keyWords": ["front"] },
    { "chinese": "在...前面（外）", "english": "in front of", "type": "短语", "keyWords": ["front"] },
    { "chinese": "在...前部（内）", "english": "in the front of", "type": "短语", "keyWords": ["front"] },
    { "chinese": "n.[U]水果 [C]水果种类；产物；成果", "english": "fruit", "type": "单词", "keyWords": [] },
    { "chinese": "a.不结果实的；没结果的", "english": "fruitless", "type": "单词", "keyWords": ["fruit"] },
    { "chinese": "a.果实结得多的，多产的；富有成效的", "english": "fruitful", "type": "单词", "keyWords": ["fruit"] },
    { "chinese": "结果实；产生效果", "english": "bear fruit", "type": "短语", "keyWords": ["fruit"] },
    { "chinese": "v.挫败，阻挠（计划、企图等）；使感到灰心；使受挫", "english": "frustrate", "type": "单词", "keyWords": [] },
    { "chinese": "a.感到/使人灰心的", "english": "frustrated/frustrating", "type": "单词", "keyWords": ["frustrate"] },
    { "chinese": "n.[U]挫败，挫折", "english": "frustration", "type": "单词", "keyWords": ["frustrate"] },
    { "chinese": "警察挫败了恐怖分子抢劫银行的企图", "english": "The police frustrated the terrorists' attempt to rob the bank.", "type": "句子", "keyWords": ["frustrate"] },
    { "chinese": "vt.油煎；油炒；油炸", "english": "fry", "type": "单词", "keyWords": [] },
    { "chinese": "a.油炸的", "english": "fried", "type": "单词", "keyWords": ["fry"] },
    { "chinese": "煎锅，长柄平锅", "english": "frying pan", "type": "短语", "keyWords": ["fry"] },
    { "chinese": "n.[U][C]燃料，燃烧剂 v.给...加燃料，供以燃料 v.加燃料", "english": "fuel", "type": "单词", "keyWords": [] },
    { "chinese": "v.履行；实现；满足", "english": "fulfil(l)", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]履行，实行", "english": "fulfillment", "type": "单词", "keyWords": ["fulfil(l)"] },
    { "chinese": "完成任务/履行职责/履行合同/实现梦想/实现愿望", "english": "fulfil the task/ one's duty, a contract/ one's dream/ one's desire", "type": "短语", "keyWords": ["fulfil(l)"] },
    { "chinese": "a.（充）满的", "english": "full", "type": "单词", "keyWords": [] },
    { "chinese": "满月", "english": "a full moon", "type": "短语", "keyWords": ["full"] },
    { "chinese": "a.（牛奶等）全脂的", "english": "full-fat", "type": "单词", "keyWords": ["full"] },
    { "chinese": "充满的；有很多的", "english": "be full of", "type": "短语", "keyWords": ["full"] },
    { "chinese": "充分（享受）；彻底（享受）", "english": "(enjoy it) to the full", "type": "短语", "keyWords": ["full"] },
    { "chinese": "n.[C]（常用复数）烟雾；气味", "english": "fume", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]乐趣", "english": "fun", "type": "单词", "keyWords": [] },
    { "chinese": "多有趣！", "english": "What fun!", "type": "句子", "keyWords": ["fun"] },
    { "chinese": "为了消遣", "english": "for fun", "type": "短语", "keyWords": ["fun"] },
    { "chinese": "开玩笑", "english": "make fun of", "type": "短语", "keyWords": ["fun"] },
    { "chinese": "a.滑稽可笑的；逗人发笑的；奇异的，古怪的", "english": "funny", "type": "单词", "keyWords": ["fun"] },
    { "chinese": "vi.（器官等）活动；（机器等）运行；起作用 n.[C]作用，功能；机能；[数]函数", "english": "function", "type": "单词", "keyWords": [] },
    { "chinese": "那电池没用了", "english": "The battery doesn't function.", "type": "句子", "keyWords": ["function"] },
    { "chinese": "行政职能", "english": "administrative function", "type": "短语", "keyWords": ["function"] },
    { "chinese": "n.[C]基金；(pl)资金，现款 v.资助，投资；为..提供经费", "english": "fund", "type": "单词", "keyWords": [] },
    { "chinese": "建立基金", "english": "set up a fund", "type": "短语", "keyWords": ["fund"] },
    { "chinese": "募集资金", "english": "raise a fund", "type": "短语", "keyWords": ["fund"] },
    { "chinese": "为该项目提供经费", "english": "fund the project", "type": "句子", "keyWords": ["fund"] },
    { "chinese": "adj.基本的；基础的；主要的", "english": "fundamental", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]葬礼", "english": "funeral", "type": "单词", "keyWords": [] },
    { "chinese": "在葬礼/追悼会上", "english": "at the funeral", "type": "短语", "keyWords": ["funeral"] },
    { "chinese": "n.[U]（熊等的）软毛，柔毛 [C]毛皮衣服，毛皮制品；裘", "english": "fur", "type": "单词", "keyWords": [] },
    { "chinese": "穿着裘皮大衣的妇女", "english": "the woman in furs=the woman in a fur coat", "type": "句子", "keyWords": ["fur"] },
    { "chinese": "vt.装设备于；供应；为（房间）配备家具", "english": "furnish", "type": "单词", "keyWords": [] },
    { "chinese": "给某人以食物/真相/他所需要的东西", "english": "furnish/ equip/ supply sb. with food/ facts/ what he needs = furnish food/ facts/ what he needs to sb.", "type": "句子", "keyWords": ["furnish"] },
    { "chinese": "这房屋室内布置得很好", "english": "The house is well furnished.", "type": "句子", "keyWords": ["furnish"] },
    { "chinese": "n.[U]（总称）家具", "english": "furniture", "type": "单词", "keyWords": ["furnish"] },
    { "chinese": "一件家具", "english": "a piece of furniture", "type": "短语", "keyWords": ["furniture"] },
    { "chinese": "a.更多的；另外的；深一层的 ad.更远地；更大程度上地；进一步 v.促进", "english": "further", "type": "单词", "keyWords": [] },
    { "chinese": "ad.此外", "english": "furthermore", "type": "单词", "keyWords": ["further"] },
    { "chinese": "进一步研究，深造", "english": "further study", "type": "短语", "keyWords": ["further"] },
    { "chinese": "继续教育", "english": "further education", "type": "短语", "keyWords": ["further"] },
    { "chinese": "得到更多信息", "english": "get further information", "type": "短语", "keyWords": ["further"] },
    { "chinese": "太累而无法走得更远", "english": "too tired to walk any further", "type": "句子", "keyWords": ["further"] },
    { "chinese": "还有多少路？", "english": "How much further is it?", "type": "句子", "keyWords": ["further"] },
    { "chinese": "我没有别的话要说了", "english": "I have nothing further to say.", "type": "句子", "keyWords": ["further"] },
    { "chinese": "攻读工商管理硕士学位", "english": "further his study for MBA", "type": "句子", "keyWords": ["further"] },
    { "chinese": "n.[C]未来；将来 a.未来的，将来的", "english": "future", "type": "单词", "keyWords": [] },
    { "chinese": "将来", "english": "in (the) future", "type": "短语", "keyWords": ["future"] },
    { "chinese": "在不久/久远的将来", "english": "in the near/distant future", "type": "短语", "keyWords": ["future"] },
    { "chinese": "他的未婚妻", "english": "his future wife", "type": "短语", "keyWords": ["future"] },
    { "chinese": "没有前途/前途远大", "english": "have no/a great future", "type": "短语", "keyWords": ["future"] },
    { "chinese": "未来未知。/前途未卜", "english": "One's future is uncertain.", "type": "句子", "keyWords": ["future"] },
    { "chinese": "n.[U]获得；(pl)收益 v.获得，赢得，赚到；增进；(表)走快，变快 vi.获利；增加", "english": "gain", "type": "单词", "keyWords": [] },
    { "chinese": "获得...经验/支持/名声/对...的控制权", "english": "gain experience/support/a reputation/ control of sth.", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "他使自己落下一个办事不公的名声", "english": "He has gained himself a reputation for unfairness.", "type": "句子", "keyWords": ["gain"] },
    { "chinese": "(手表等)一天快/慢20秒", "english": "gain/ lose twenty seconds a day", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "渐渐增加体重/速度/高度/时间", "english": "gain weight/ speed/height/time", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "这部车下山时速度加快了", "english": "The car gained speed as it went down the hill.", "type": "句子", "keyWords": ["gain"] },
    { "chinese": "(把某人)从敌对的一方争取过来", "english": "gain/win sb.over", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "从..中获得...", "english": "gain...from...", "type": "短语", "keyWords": ["gain"] },
    { "chinese": "没有辛苦就没有收获。/不劳则无获", "english": "No pains,no gains.", "type": "句子", "keyWords": ["gain"] },
    { "chinese": "n.[C]走廊；(艺术品)陈列馆(或室)；画廊", "english": "gallery", "type": "单词", "keyWords": [] },
    { "chinese": "vi.赌博(on) v.赌掉，输光 n.[C]赌博；冒险", "english": "gamble", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]赌博；投机", "english": "gambling", "type": "单词", "keyWords": ["gamble"] },
    { "chinese": "n.[C]赌徒", "english": "gambler", "type": "单词", "keyWords": ["gamble"] },
    { "chinese": "输光他的全部财产", "english": "gamble away all his wealth", "type": "句子", "keyWords": ["gamble"] },
    { "chinese": "n.[C]游戏；运动；比赛；(总称)猎物", "english": "game", "type": "单词", "keyWords": [] },
    { "chinese": "一头猎物", "english": "a head of game", "type": "短语", "keyWords": ["game"] },
    { "chinese": "敷衍塞责；耍花腔", "english": "play games", "type": "短语", "keyWords": ["game"] },
    { "chinese": "n.[C](一)伙；(歹徒等的)一帮", "english": "gang", "type": "单词", "keyWords": [] },
    { "chinese": "(一)伙，(一)帮", "english": "a gang of", "type": "短语", "keyWords": ["gang"] },
    { "chinese": "n.[C]豁缝，缺口；隔阂；差距", "english": "gap", "type": "单词", "keyWords": [] },
    { "chinese": "填补空白/缩短差距", "english": "fill in/close the gaps", "type": "短语", "keyWords": ["gap"] },
    { "chinese": "n.[C]车库；汽车修理处；加油站", "english": "garage", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]垃圾", "english": "garbage", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]花园", "english": "garden", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]园丁", "english": "gardener", "type": "单词", "keyWords": ["garden"] },
    { "chinese": "n.[U]园艺；园林工人的工作", "english": "gardening", "type": "单词", "keyWords": ["garden"] },
    { "chinese": "n.[U]大蒜；蒜头", "english": "garlic", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]衣服；外衣(书面语，多用于文学作品)", "english": "garment", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]气态；气体 n.[U]煤气；天然气；可燃气体；[口]汽油", "english": "gas", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U][美]汽油[英]petrol", "english": "gasoline", "type": "单词", "keyWords": ["gas"] },
    { "chinese": "n.[C]/vi.喘息，气喘", "english": "gasp", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]大门；*事件；丑闻", "english": "gate", "type": "单词", "keyWords": [] },
    { "chinese": "伊朗门事件", "english": "Irangate", "type": "短语", "keyWords": ["gate"] },
    { "chinese": "水门事件", "english": "Watergate", "type": "短语", "keyWords": ["gate"] },
    { "chinese": "vi.(使)集合；(使)聚集；收集；搜集；集合；聚集 v.收割", "english": "gather", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]集合", "english": "gathering", "type": "单词", "keyWords": ["gather"] },
    { "chinese": "把...围住；聚拢来", "english": "gather around", "type": "短语", "keyWords": ["gather"] },
    { "chinese": "聚会；聚集；收集", "english": "gather together", "type": "短语", "keyWords": ["gather"] },
    { "chinese": "收割庄稼", "english": "gather/get in crops", "type": "短语", "keyWords": ["gather"] },
    { "chinese": "搜集情报", "english": "gather information", "type": "短语", "keyWords": ["gather"] },
    { "chinese": "a.快乐的；色彩鲜艳的", "english": "gay", "type": "单词", "keyWords": [] },
    { "chinese": "vi./n.[C]盯着看，凝视", "english": "gaze", "type": "单词", "keyWords": [] },
    { "chinese": "注视；凝视", "english": "gaze at", "type": "短语", "keyWords": ["gaze"] },
    { "chinese": "国内生产总值", "english": "GDP", "type": "短语", "keyWords": [] },
    { "chinese": "n.[C][U][语法]性；[口]性别；性", "english": "gender", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][遗传]基因", "english": "gene", "type": "单词", "keyWords": [] },
    { "chinese": "a.遗传的", "english": "genetic", "type": "单词", "keyWords": ["gene"] },
    { "chinese": "a.一般的，普通的；综合的，概括的；大体的；总的(级别最高的) n.[C]将军 v.归纳", "english": "general", "type": "单词", "keyWords": [] },
    { "chinese": "一般概念；大意", "english": "general idea", "type": "短语", "keyWords": ["general"] },
    { "chinese": "大选；普选", "english": "general election", "type": "短语", "keyWords": ["general"] },
    { "chinese": "一般，大体上", "english": "in general", "type": "短语", "keyWords": ["general"] },
    { "chinese": "人们一般都喜欢她", "english": "In general,people like her.", "type": "句子", "keyWords": ["general"] },
    { "chinese": "原则上；一般地说", "english": "as a general rule", "type": "短语", "keyWords": ["general"] },
    { "chinese": "通常我不接受采访，但这一次算是例外", "english": "I don't give interviews as a general rule, but in this case I'll make an exception.", "type": "句子", "keyWords": ["general"] },
    { "chinese": "一般说来", "english": "generally speaking", "type": "短语", "keyWords": ["general"] },
    { "chinese": "一般说来，你为立体声设备花钱越多，设备就越好", "english": "Generally speaking, the more you pay for stereo equipment, the better the system (is).", "type": "句子", "keyWords": ["general"] },
    { "chinese": "n.[C]一代(人)", "english": "generation", "type": "单词", "keyWords": [] },
    { "chinese": "代沟", "english": "generation gap", "type": "短语", "keyWords": ["generation"] },
    { "chinese": "一代又一代", "english": "from generation to generation/ generation after generation", "type": "短语", "keyWords": ["generation"] },
    { "chinese": "a.慷慨的，大方的", "english": "generous", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]慷慨，大方", "english": "generosity", "type": "单词", "keyWords": ["generous"] },
    { "chinese": "他花钱大方", "english": "He is generous with his money.", "type": "句子", "keyWords": ["generous"] },
    { "chinese": "n.[C](pl geniuses或genii)天才；天赋", "english": "genius", "type": "单词", "keyWords": [] },
    { "chinese": "有音乐天赋", "english": "have a genius/ talent/ gift for music", "type": "短语", "keyWords": ["genius"] },
    { "chinese": "a.柔和的；温和的；文雅的", "english": "gentle", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]柔和；文雅", "english": "gentleness", "type": "单词", "keyWords": ["gentle"] },
    { "chinese": "对待...很温和", "english": "be gentle with", "type": "短语", "keyWords": ["gentle"] },
    { "chinese": "n.[C]有教养的人；绅士；先生", "english": "gentleman", "type": "单词", "keyWords": [] },
    { "chinese": "a.真的；非人造的；非伪造的；真诚的", "english": "genuine", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]地理", "english": "geography", "type": "单词", "keyWords": [] },
    { "chinese": "a.地理学的，地理的", "english": "geographical", "type": "单词", "keyWords": ["geography"] },
    { "chinese": "n.[U]地质学", "english": "geology", "type": "单词", "keyWords": [] },
    { "chinese": "a.地质学的，地质的", "english": "geological", "type": "单词", "keyWords": ["geology"] },
    { "chinese": "n.[U]几何学", "english": "geometry", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]病菌，细菌", "english": "germ", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]手势；示意动作；姿态，表示 v.打手势；用动作示意", "english": "gesture", "type": "单词", "keyWords": [] },
    { "chinese": "打手势让我停下来", "english": "gesture for me to stop = make me stop with gestures", "type": "句子", "keyWords": ["gesture"] },
    { "chinese": "v.得到；达到；收获；使得；变得；成为", "english": "get", "type": "单词", "keyWords": [] },
    { "chinese": "开始做某事", "english": "get doing sth.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "我们不久就谈了起来", "english": "We soon got talking.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "让某人开始做某事", "english": "get sb.doing sth.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "让钟走起来", "english": "get the clock going", "type": "短语", "keyWords": ["get"] },
    { "chinese": "把工作开展起来", "english": "get things moving", "type": "短语", "keyWords": ["get"] },
    { "chinese": "逐渐知道/意识到/明白/爱上..", "english": "get come to know/realize/ understand/ love..", "type": "短语", "keyWords": ["get"] },
    { "chinese": "让某人去做某事", "english": "get sb. to do sth.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "让别人或自己把某事做了", "english": "get sth.done", "type": "短语", "keyWords": ["get"] },
    { "chinese": "使某人理解....", "english": "get...across to sb.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "横过；穿过", "english": "get across", "type": "短语", "keyWords": ["get"] },
    { "chinese": "努力使他们理解我的意思", "english": "try to get my idea across to them", "type": "句子", "keyWords": ["get"] },
    { "chinese": "生活；相处；进展；前进", "english": "get along (with sb/sth.)", "type": "短语", "keyWords": ["get"] },
    { "chinese": "你和姑母相处得好吗？", "english": "Do you get along well with your aunt?", "type": "句子", "keyWords": ["get"] },
    { "chinese": "即使没有任何助手，我们也要进行下去", "english": "We must get along somehow without any assistant.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "开始认真对待", "english": "get down to (sth/doing sth.)", "type": "短语", "keyWords": ["get"] },
    { "chinese": "度过了愉快的假期后很难一下子认真投入工作", "english": "It's hard to get down to work after a nice holiday.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "克服/战胜困难；从(疾病、震惊等)中恢复", "english": "get over", "type": "短语", "keyWords": ["get"] },
    { "chinese": "他刚刚痊愈", "english": "He is just getting over an illness.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "做完；(使)通过(考试等)；打通(电话)", "english": "get through", "type": "短语", "keyWords": ["get"] },
    { "chinese": "请你给我接通人事部", "english": "Please get me through to the Personnel Department.", "type": "句子", "keyWords": ["get"] },
    { "chinese": "听到你(考试)及格时，我们很高兴", "english": "We were delighted when we heard you'd got through (your exam).", "type": "句子", "keyWords": ["get"] },
    { "chinese": "到处走动，传开", "english": "get around", "type": "短语", "keyWords": ["get"] },
    { "chinese": "收割庄稼", "english": "get in crops", "type": "短语", "keyWords": ["get"] },
    { "chinese": "下车；动身", "english": "get off", "type": "短语", "keyWords": ["get"] },
    { "chinese": "做了坏事未受惩处", "english": "get away with sth.", "type": "短语", "keyWords": ["get"] },
    { "chinese": "为...做准备", "english": "get ready for", "type": "短语", "keyWords": ["get"] },
    { "chinese": "起床；起立", "english": "get up", "type": "短语", "keyWords": ["get"] },
    { "chinese": "使起床；使起立", "english": "get...up", "type": "短语", "keyWords": ["get"] },
    { "chinese": "逃跑", "english": "get away", "type": "短语", "keyWords": ["get"] },
    { "chinese": "到达", "english": "get to", "type": "短语", "keyWords": ["get"] },
    { "chinese": "n.[C]聚会", "english": "get-together", "type": "单词", "keyWords": ["get"] },
    { "chinese": "n.[C]鬼，幽灵", "english": "ghost", "type": "单词", "keyWords": [] },
    { "chinese": "a.像鬼般的", "english": "ghostly", "type": "单词", "keyWords": ["ghost"] },
    { "chinese": "a.巨大的 n.[C]伟人；巨人；大力士", "english": "giant", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]礼物，赠品；天赋", "english": "gift", "type": "单词", "keyWords": [] },
    { "chinese": "在某方面有天赋", "english": "have a gift/talent for", "type": "短语", "keyWords": ["gift"] },
    { "chinese": "她有学语言的天赋", "english": "She has a gift for learning languages.", "type": "句子", "keyWords": ["gift"] },
    { "chinese": "a.有天赋的；有天才的", "english": "gifted", "type": "单词", "keyWords": ["gift"] },
    { "chinese": "一个有天赋的钢琴家", "english": "a talented/ gifted pianist", "type": "短语", "keyWords": ["gifted"] },
    { "chinese": "n.[U]生姜", "english": "ginger", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]女孩", "english": "girl", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]少女时代", "english": "girlhood", "type": "单词", "keyWords": ["girl"] },
    { "chinese": "n.[C]女朋友", "english": "girlfriend", "type": "单词", "keyWords": ["girl"] },
    { "chinese": "v.给；赠送 a.赠予的；特定的；假设的", "english": "give", "type": "单词", "keyWords": [] },
    { "chinese": "屈服，让位", "english": "give way (to sb)", "type": "短语", "keyWords": ["give"] },
    { "chinese": "散发出(蒸汽、光等)", "english": "give off", "type": "短语", "keyWords": ["give"] },
    { "chinese": "在设定期间内", "english": "within a given time", "type": "短语", "keyWords": ["give"] },
    { "chinese": "发出警告", "english": "give a warning", "type": "短语", "keyWords": ["give"] },
    { "chinese": "投降；屈服；上交", "english": "give in", "type": "短语", "keyWords": ["give"] },
    { "chinese": "引起反对意见", "english": "give rise to (=cause) objections", "type": "短语", "keyWords": ["give"] },
    { "chinese": "放弃", "english": "give up", "type": "短语", "keyWords": ["give"] },
    { "chinese": "考虑这个问题", "english": "give thought to(=consider) the problem", "type": "短语", "keyWords": ["give"] },
    { "chinese": "发出(热、气味等)；分发；(供给等)用完；筋疲力尽", "english": "give out", "type": "短语", "keyWords": ["give"] },
    { "chinese": "油用光了", "english": "The oil gave out.", "type": "句子", "keyWords": ["give"] },
    { "chinese": "跑完十圈后他精疲力尽了", "english": "He (His leg) gave out after ten laps.", "type": "句子", "keyWords": ["give"] },
    { "chinese": "赠送；分发；放弃(机会)；泄露(秘密等)；出卖", "english": "give..away", "type": "短语", "keyWords": ["give"] },
    { "chinese": "出卖他", "english": "give him away", "type": "短语", "keyWords": ["give"] },
    { "chinese": "把财产送给别人", "english": "give away his fortune", "type": "短语", "keyWords": ["give"] },
    { "chinese": "泄露我的秘密", "english": "give away my secret", "type": "短语", "keyWords": ["give"] }
];
