const qgl166_180 = [
    { "chinese": "每种物质，不管是什么，都由原子构成。", "english": "Each substance, whatever it is, is made up of atoms.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "补偿；弥补", "english": "make up for sth.", "type": "短语", "keyWords": ["make"] },
    { "chinese": "补回损失的时间", "english": "make up for lost time", "type": "短语", "keyWords": ["make"] },
    { "chinese": "弥补损失", "english": "make up for a loss", "type": "短语", "keyWords": ["make"] },
    { "chinese": "这是完全捏造的故事。", "english": "It's all a made-up story.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "(家具、衣服等) 定制的，定做的", "english": "made-to-measure", "type": "短语", "keyWords": ["make"] },
    { "chinese": "这是什么牌子的汽车？", "english": "What make of car is this?", "type": "句子", "keyWords": ["make"] },
    { "chinese": "趁晴晒草。勿失良机。", "english": "Make hay while the sun shines.", "type": "句子", "keyWords": ["make"] },
    { "chinese": "n. 疟疾", "english": "malaria", "type": "单词", "keyWords": [] },
    { "chinese": "a. 男性的；阳性的；[植]雄性的；n. [C]男子；雄性动物；[植]雄性植物", "english": "male", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]林荫路；步行街；[美]购物中心，商场", "english": "mall", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]人；男人；男子汉；n. [U]人类（不带冠词，同mankind）；v. 给··配置兵员", "english": "man", "type": "单词", "keyWords": [] },
    { "chinese": "他父亲死后，他就变得像个大人了。", "english": "His father's death has made a man of him.", "type": "句子", "keyWords": ["man"] },
    { "chinese": "他有足够的勇气来接受挑战吗？", "english": "Was he man enough to take the challenge?", "type": "句子", "keyWords": ["man"] },
    { "chinese": "v. 设法做到；管理；经营；操纵，开动；vi. 处理，设法对付；管理；经营", "english": "manage", "type": "单词", "keyWords": [] },
    { "chinese": "成功地做成某事（近try to do sth./try one's best to do sth.尽力办成某事）", "english": "manage to do sth.", "type": "短语", "keyWords": ["manage"] },
    { "chinese": "你能再吃一片蛋糕吗？", "english": "Can you manage another slice of cake?", "type": "句子", "keyWords": ["manage"] },
    { "chinese": "我能办成。", "english": "I can manage(it).", "type": "句子", "keyWords": ["manage"] },
    { "chinese": "n. [C]经理", "english": "manager", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]处理；管理，经营", "english": "management", "type": "单词", "keyWords": [] },
    { "chinese": "a. 易处理的，易办的；易管理的；易掌控的", "english": "manageable", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]芒果；芒果树", "english": "mango", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]人类", "english": "mankind", "type": "单词", "keyWords": [] },
    { "chinese": "a. 人造的；人为的（比较machine-made机制的）", "english": "man-made", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]方式；态度；举止（侧重指具有个人特色的行为，办事方式）；(pl)礼貌；规矩", "english": "manner", "type": "单词", "keyWords": [] },
    { "chinese": "餐桌礼仪", "english": "table manners", "type": "短语", "keyWords": ["manner"] },
    { "chinese": "……（没）有礼貌的", "english": "It's bad/good manners to do sth....", "type": "句子", "keyWords": ["manner"] },
    { "chinese": "以……方式（近by...means）", "english": "in a...manner/way/mode", "type": "短语", "keyWords": ["manner"] },
    { "chinese": "n. [C]大厦；大楼", "english": "mansion", "type": "单词", "keyWords": [] },
    { "chinese": "a. 手工的；体力的；n. [C]手册", "english": "manual", "type": "单词", "keyWords": [] },
    { "chinese": "体力活", "english": "manual work", "type": "短语", "keyWords": ["manual"] },
    { "chinese": "家用维修手册", "english": "a manual of home repairs", "type": "短语", "keyWords": ["manual"] },
    { "chinese": "v. [T]（指大量）制造；生产；manufacturer n. [C]制造商", "english": "manufacture", "type": "单词", "keyWords": [] },
    { "chinese": "a. 许多；pron. 许多人/物", "english": "many", "type": "单词", "keyWords": [] },
    { "chinese": "许多（用法同many）", "english": "a good/great many", "type": "短语", "keyWords": ["many"] },
    { "chinese": "许多学生获得了这样的机会。", "english": "Many a student has got such an opportunity.", "type": "句子", "keyWords": ["many"] },
    { "chinese": "来多少就可以接纳多少。", "english": "They admit as many as come.", "type": "句子", "keyWords": ["many"] },
    { "chinese": "n. [C]地图；v. (mapped, mapping)绘制……的地图", "english": "map", "type": "单词", "keyWords": [] },
    { "chinese": "科学家绘制了月球表面的地图。", "english": "The scientists mapped the surface of the moon.", "type": "句子", "keyWords": ["map"] },
    { "chinese": "仔细规划她的将来", "english": "map out her future", "type": "短语", "keyWords": ["map"] },
    { "chinese": "n. [C]马拉松赛跑（全程约26英里或42公里）", "english": "marathon", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]三月（略作Mar.）", "english": "March", "type": "单词", "keyWords": [] },
    { "chinese": "v. 行军；行进；v. 使行军；使行进；n. [C]行军；行进；[音]进行曲", "english": "march", "type": "单词", "keyWords": [] },
    { "chinese": "在进行中", "english": "on the march", "type": "短语", "keyWords": ["march"] },
    { "chinese": "长征", "english": "the Long March", "type": "短语", "keyWords": ["march"] },
    { "chinese": "n. [C]页边的空白，(湖、池等的)边缘；marginal a. 边的，边缘的；在外的", "english": "margin", "type": "单词", "keyWords": [] },
    { "chinese": "在页边作记号表示有遗漏", "english": "put a mark in the margin to show the omission", "type": "短语", "keyWords": ["margin"] },
    { "chinese": "那老人已濒临死亡。", "english": "The old man was on the margin of death.", "type": "句子", "keyWords": ["margin"] },
    { "chinese": "a. 海(洋)的；航海的；海军的；marine life海洋生物", "english": "marine", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](考试等)分数；记号；痕迹；*德国马克(币)；v. 给…打分；做记号；*注意；标志", "english": "mark", "type": "单词", "keyWords": [] },
    { "chinese": "给某人高（低）分", "english": "give sb.a good/high/bad/poor/zero mark", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "赞赏某人（做）某事", "english": "give sb.full marks for (doing)sth.", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "英语得80分/满分", "english": "get 80 marks/full marks for English", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "在有疑问的地方做一个记号。", "english": "Make a mark where you have any doubts or questions.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "在……方面成功；成名（近make a name for oneself）", "english": "make one's/a mark(on)", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "他想在历史上留名。", "english": "He wants to make his mark on history.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "注意听。", "english": "Mark my words.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "豹身上有黑斑纹。", "english": "The leopard's skin is marked with black spots.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "留有足迹的泥路", "english": "a muddy road (which was) marked with footprints", "type": "短语", "keyWords": ["mark"] },
    { "chinese": "他的死标志着一个时代的结束。", "english": "His death marked the end of an era.", "type": "句子", "keyWords": ["mark"] },
    { "chinese": "n. [C]市场；v. 在市场上进行交易；销售；*marketing n. [U]销售；销售学", "english": "market", "type": "单词", "keyWords": [] },
    { "chinese": "上市；出售", "english": "on the market", "type": "短语", "keyWords": ["market"] },
    { "chinese": "他们在市场上出售他们的房子。", "english": "They've put their houses on the market.", "type": "句子", "keyWords": ["market"] },
    { "chinese": "某东西需求量很大。", "english": "There is a big market for sth.", "type": "句子", "keyWords": ["market"] },
    { "chinese": "销售体系", "english": "*marketing system", "type": "短语", "keyWords": ["market"] },
    { "chinese": "n. [C](U)结婚；婚姻", "english": "marriage", "type": "单词", "keyWords": [] },
    { "chinese": "v. 娶；嫁；与……结婚；把…嫁出；使…娶亲；vi. 结婚", "english": "marry", "type": "单词", "keyWords": [] },
    { "chinese": "使……与……结婚", "english": "marry sb.to sb.", "type": "短语", "keyWords": ["marry"] },
    { "chinese": "与……结了婚", "english": "be married to sb.", "type": "短语", "keyWords": ["marry"] },
    { "chinese": "他把女儿嫁给了一个农民。", "english": "He married his daughter to a farmer.", "type": "句子", "keyWords": ["marry"] },
    { "chinese": "去年他的女儿嫁给了一个农民。", "english": "His daughter got married to a farmer last year.", "type": "句子", "keyWords": ["marry"] },
    { "chinese": "他的女儿嫁给了一个农民。", "english": "His daughter was married to a farmer.", "type": "句子", "keyWords": ["marry"] },
    { "chinese": "a. 已婚的；a married man已婚男子，有配偶的男人", "english": "married", "type": "单词", "keyWords": [] },
    { "chinese": "n. 火星", "english": "Mars", "type": "单词", "keyWords": [] },
    { "chinese": "a. 令人惊奇的；奇特的；奇迹般的；绝妙的", "english": "marvel(I)ous", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]面具；口罩；*v. 在(脸)上戴假面具", "english": "mask", "type": "单词", "keyWords": [] },
    { "chinese": "戴假面具，掩盖真面目", "english": "put on/wear the mask", "type": "短语", "keyWords": ["mask"] },
    { "chinese": "戴了面具的强盗", "english": "a masked robber", "type": "短语", "keyWords": ["mask"] },
    { "chinese": "n. (C]大量；团；块；(the masses)群众，民众；massive a. 巨大的；大规模的", "english": "mass", "type": "单词", "keyWords": [] },
    { "chinese": "一大块泥土", "english": "a mass of earth", "type": "短语", "keyWords": ["mass"] },
    { "chinese": "一大堆信件", "english": "a mass of letters", "type": "短语", "keyWords": ["mass"] },
    { "chinese": "人民群众有无限的创造力。", "english": "The masses have boundless creative power.", "type": "句子", "keyWords": ["mass"] },
    { "chinese": "v. 精通，掌握；n. [C]主人；雇主；名家，大师；船长；名家作品；硕士；[英]男教师", "english": "master", "type": "单词", "keyWords": [] },
    { "chinese": "独立自主，不受别人牵制", "english": "be one's own master", "type": "短语", "keyWords": ["master"] },
    { "chinese": "精通英文", "english": "master English", "type": "短语", "keyWords": ["master"] },
    { "chinese": "n. [C]杰作", "english": "masterpiece", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]比赛；竞赛；对手；相配的人或物；火柴；v. 和……相配；使相配；和……匹敌；vi. 相配；相适合（辨析见fit）", "english": "match", "type": "单词", "keyWords": [] },
    { "chinese": "棋逢对手", "english": "meet in one's match", "type": "短语", "keyWords": ["match"] },
    { "chinese": "拳击者遇到了他的对手。", "english": "The boxer met his match.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "餐巾和桌布相配得很好。", "english": "The napkins were nice and matched for the tablecloth.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "这两种颜色很相配。", "english": "The colors were a close match.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "外衣和裙子很相配。", "english": "The coat matches the dress.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "衬衫的颜色与上衣的颜色不相配。", "english": "The color of the shirt does not match that of the coat.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "与……相匹配", "english": "match sth. with sth.", "type": "短语", "keyWords": ["match"] },
    { "chinese": "我们应该像他们一样慷慨大方。", "english": "We should match their generosity with our own.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "窗帘与室内装潢不相配。", "english": "The curtains do not match with the decoration.", "type": "句子", "keyWords": ["match"] },
    { "chinese": "n. [C]一对中的一个；配偶；伙伴；同事", "english": "mate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](U]材料；资料；物资；n. [U](写书用的)素材；*.物质上的；重要的", "english": "material", "type": "单词", "keyWords": [] },
    { "chinese": "物质世界", "english": "the material world", "type": "短语", "keyWords": ["material"] },
    { "chinese": "建筑材料/教材", "english": "building/ teaching materials", "type": "短语", "keyWords": ["material"] },
    { "chinese": "收集写作素材", "english": "gather material for an article", "type": "短语", "keyWords": ["material"] },
    { "chinese": "n. [U]唯物主义；(贬义)物质(中心)主义", "english": "*materialism", "type": "单词", "keyWords": [] },
    { "chinese": "a. 唯物论的；唯物主义的", "english": "*materialistic", "type": "单词", "keyWords": [] },
    { "chinese": "a. 数学的", "english": "mathematical", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]数学（常略作math或maths）", "english": "mathematics", "type": "单词", "keyWords": [] },
    { "chinese": "n. (the)麻烦事；n. [C]事情；问题；n. [U]物质（近substance n. (C])；vi. (多用在否定句、疑问句和条件句中)要紧；有重大关系", "english": "matter", "type": "单词", "keyWords": [] },
    { "chinese": "事实上", "english": "as a matter of fact", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "……怎么了？", "english": "What's the matter with sb./sth.?", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "生死攸关的事", "english": "a matter of life and death", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "这对他们来说是生死攸关的问题。", "english": "It was a matter of life and death for them.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "不是闹着玩的事", "english": "no laughing matter", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "不管怎样/什么/何时（近however, whatever, whenever...，注意no matter不单独用作连词）", "english": "No matter how/what/when", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "令事情更糟糕的是（常作插入语用）", "english": "to make matters worse/ what makes matters worse", "type": "短语", "keyWords": ["matter"] },
    { "chinese": "情况就是这样。", "english": "That's how matters stand.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "物质以三种状态存在：固态、液态和气态。", "english": "Matter exists in three states: solid, liquid and gas.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "你留下来还是和他们一起去对他们来说无所谓。", "english": "It doesn't matter to them whether you stay or go with them.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "最重要的是你所关注的东西。", "english": "What matters most is what you focus on.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "“那有什么关系呢？”她带着一种傲慢的神情问道。", "english": "\"What does that matter?\" she asked, with a proud air.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "重要的不是身材的高矮，而是心胸的宽窄。", "english": "It is not the size of a man but the size of his heart that matters.", "type": "句子", "keyWords": ["matter"] },
    { "chinese": "a. (成)熟的，成年人的；到期的；明白事理的，稳重的；慎重的；v. 使成熟；使长成；vi. 成熟，到期", "english": "mature", "type": "单词", "keyWords": [] },
    { "chinese": "经过深思熟虑的计划", "english": "a mature plan", "type": "短语", "keyWords": ["mature"] },
    { "chinese": "n. [U]成熟；(计划等)完备；(票据等)到期", "english": "maturity", "type": "单词", "keyWords": [] },
    { "chinese": "a. 最大的，最高的", "english": "maximal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl.maximums/maxima)最大量；最大限度；最大限", "english": "maximum", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]五月；on May Day在五一劳动节", "english": "May", "type": "单词", "keyWords": [] },
    { "chinese": "aux. 可以（表许可或用于请求许可）；或许（常用于肯定句、否定句中）；祝", "english": "may", "type": "单词", "keyWords": [] },
    { "chinese": "祝你快乐！", "english": "May you be happy!", "type": "句子", "keyWords": ["may"] },
    { "chinese": "或许……做过", "english": "may/might have done sth.", "type": "短语", "keyWords": ["may"] },
    { "chinese": "还是……好；倒不如", "english": "may/might as well do sth.", "type": "短语", "keyWords": ["may"] },
    { "chinese": "ad. 大概，或许", "english": "maybe", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]市长；be elected mayor被选为市长", "english": "mayor", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]膳食；一餐", "english": "meal", "type": "单词", "keyWords": [] },
    { "chinese": "v. 意思是；意指；意味着，即是；意欲，打算；a. 卑鄙的；吝啬的；中间的；中等的；普通的；平均的；*meanness n. 卑鄙，吝啬", "english": "mean", "type": "单词", "keyWords": [] },
    { "chinese": "对……极其/很/不重要", "english": "mean a great deal/a lot/nothing to sb.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "她视金钱如粪土。", "english": "Money means nothing to her.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "意味着", "english": "mean(doing) sth.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "充分利用时间并不意味着从早到晚不停地看书。", "english": "Making the best of time doesn't mean keeping on reading from morning till night.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "我不是有心的。我不是故意的。", "english": "I did not mean it.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "本意为；打算（比较want, intend, plan, hope, wish等用法）", "english": "mean to do sth.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "我没有侮辱你的意思。", "english": "I don't mean to insult you.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "对不起。我不是有意伤你感情的。", "english": "I'm sorry. I did not mean to hurt you/your feeling.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "本来想做某事（但没做成）", "english": "meant to have done.../had meant to do...", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "我本想告诉你的，可是我忘记了。", "english": "I meant to have told you about it, but forgot to do so.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "你那样说是什么意思？", "english": "What do you mean by (saying) that?", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "他提到的“他们”是指谁？", "english": "Whom did he mean by \"they\"?", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "所谓四个保证，就是指这四件事情。", "english": "These are what we mean by the four guarantees.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "为某人准备……；用于；为……准备的；预定", "english": "mean sth. for sb./be meant for...", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "他准备把这栋房子给女儿。", "english": "He meant this house for his daughter.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "这就是笑话。", "english": "This was meant for a joke.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "本来是准备把他培养成为医生的。", "english": "He was meant for/to be a doctor.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "要某人做某事；被认为/期望做某事；应该做某事（be expected/supposed to do）", "english": "mean sb. to do sth./be meant to do sth.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "不要靠吃药过生活。", "english": "Medicines are not meant to live on.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "你不该在这里抽烟。", "english": "You are not meant to smoke here.", "type": "句子", "keyWords": ["mean"] },
    { "chinese": "a. 卑鄙的动机", "english": "a mean motive", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "一毛不拔", "english": "be mean with one's money", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "简陋的房子", "english": "a mean cottage", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "在……方面很小气/吝啬", "english": "be mean about/over sth.", "type": "短语", "keyWords": ["mean"] },
    { "chinese": "n. [C](U)意义；意思；meaningful a. 意味深长的；meaningless a. 无意义的", "english": "meaning", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]（单复同）方法；手段；工具（指为达到目的而采取的手段，也可指交通工具）", "english": "means", "type": "单词", "keyWords": [] },
    { "chinese": "生产手段，生产工具，生产资料", "english": "means of production", "type": "短语", "keyWords": ["means"] },
    { "chinese": "千方百计", "english": "try many/every means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "运输工具；交通设施；运输方式", "english": "means of transportation", "type": "短语", "keyWords": ["means"] },
    { "chinese": "(表示同意)当然可以，没问题；无论如何，不惜一切地，千方百计地", "english": "by all means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "想个办法；以某种方法（近in one way or another）", "english": "by some means(or other)", "type": "短语", "keyWords": ["means"] },
    { "chinese": "通过；用；借助于", "english": "by means of", "type": "短语", "keyWords": ["means"] },
    { "chinese": "用这种方法", "english": "by this means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "怎样", "english": "by what means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "[口]用一切可能的方法或手段", "english": "by any means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "不，一点也不（见account）", "english": "by no means", "type": "短语", "keyWords": ["means"] },
    { "chinese": "要满足每一个人绝非易事。（倒装）", "english": "By no means is it easy to satisfy everyone.", "type": "句子", "keyWords": ["means"] },
    { "chinese": "n. 间隔时间；同时；期间", "english": "meantime", "type": "单词", "keyWords": [] },
    { "chinese": "(与此)同时", "english": "in the meantime", "type": "短语", "keyWords": ["meantime"] },
    { "chinese": "n. 间隔时间；同时；期间", "english": "meanwhile", "type": "单词", "keyWords": [] },
    { "chinese": "(与此)同时", "english": "in the meanwhile", "type": "短语", "keyWords": ["meanwhile"] },
    { "chinese": "警察马上就来，在此期间，你应该保持冷静。", "english": "The police will be here soon. Meanwhile/Meantime/in the meanwhile/in the meantime you should stay calm.", "type": "句子", "keyWords": ["meantime", "meanwhile"] },
    { "chinese": "v. 量，测量；vi. (测)量；可测量；尺寸是；n. [C]措施；n. [C](U)度量，尺寸，量", "english": "measure", "type": "单词", "keyWords": [] },
    { "chinese": "量身裁衣", "english": "make clothes to my measure", "type": "短语", "keyWords": ["measure"] },
    { "chinese": "桌子宽55厘米。", "english": "The desk measures 55cm across.", "type": "句子", "keyWords": ["measure"] },
    { "chinese": "桌子长98厘米，宽55厘米。", "english": "The desk measures 98x55cm(98 by 55cm).", "type": "句子", "keyWords": ["measure"] },
    { "chinese": "采取措施做某事", "english": "take measures/steps to do sth.", "type": "短语", "keyWords": ["measure"] },
    { "chinese": "裁缝量了我的尺寸准备帮我做新衣服。", "english": "The tailor took my measure for a new suit.", "type": "句子", "keyWords": ["measure"] },
    { "chinese": "n. [U]肉", "english": "meat", "type": "单词", "keyWords": [] },
    { "chinese": "利于甲者未必利于乙。", "english": "One man's meat is another man's poison.", "type": "句子", "keyWords": ["meat"] },
    { "chinese": "n. [C]技工；机械工人；*mechanics n. (单数用)力学；机械学", "english": "mechanic", "type": "单词", "keyWords": [] },
    { "chinese": "a. 机械的；mechanically ad. 机械地；无意识地", "english": "mechanical", "type": "单词", "keyWords": [] },
    { "chinese": "机械能", "english": "mechanical energy", "type": "短语", "keyWords": ["mechanical"] },
    { "chinese": "n. [C]奖牌；纪念章", "english": "medal", "type": "单词", "keyWords": [] },
    { "chinese": "a. 医学的；医疗的；内科的（反surgical）", "english": "medical", "type": "单词", "keyWords": [] },
    { "chinese": "进行体格检查", "english": "have a medical examination", "type": "短语", "keyWords": ["medical"] },
    { "chinese": "n. [U]医学；内科(治疗)（反surgery）；n. [C](U)药", "english": "medicine", "type": "单词", "keyWords": [] },
    { "chinese": "感冒良药", "english": "a good medicine for a cold", "type": "短语", "keyWords": ["medicine"] },
    { "chinese": "吃药", "english": "take medicine", "type": "短语", "keyWords": ["medicine"] },
    { "chinese": "n. [C]媒介物；(常用pl.media)新闻媒体，传媒；a. 中间的；中等的；适度的（以-um结尾的词：bacterium, memorandum, datum, maximum, minimum, gymnasium, stadium, curriculum）", "english": "medium", "type": "单词", "keyWords": [] },
    { "chinese": "v. 遇见；会见；满足；相遇；(路、河流等)相合；vi. 相遇；(路、河流等)相合", "english": "meet", "type": "单词", "keyWords": [] },
    { "chinese": "她的目光和我的相遇。", "english": "Hereyes met mine.", "type": "句子", "keyWords": ["meet"] },
    { "chinese": "符合某人的需要/需求/要求/希望", "english": "meet one's needs/demands/requirements/expenses/one's hopes", "type": "短语", "keyWords": ["meet"] },
    { "chinese": "偶然遇到；遭遇（近run/bump into，come across，*chance upon）", "english": "meet with", "type": "短语", "keyWords": ["meet"] },
    { "chinese": "n. [C]会议；会合；聚集", "english": "meeting", "type": "单词", "keyWords": [] },
    { "chinese": "解散会议，闭会", "english": "break up a meeting", "type": "短语", "keyWords": ["meeting"] },
    { "chinese": "召集大会", "english": "call a meeting", "type": "短语", "keyWords": ["meeting"] },
    { "chinese": "n. [C]瓜(尤指甜瓜、西瓜等)", "english": "melon", "type": "单词", "keyWords": [] },
    { "chinese": "西瓜", "english": "water melon", "type": "短语", "keyWords": ["melon"] },
    { "chinese": "v. 使熔化；使融化；使溶解；vi. 熔化；融化；溶解", "english": "melt", "type": "单词", "keyWords": [] },
    { "chinese": "熔点，融点", "english": "melting point", "type": "短语", "keyWords": ["melt"] },
    { "chinese": "n. [C]成员；会员；*membership n. [U]成员资格；成员身份", "english": "member", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl.memos)[口]备忘录(=memorandum)", "english": "memo", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl.memorandums或memoranda)备忘录", "english": "memorandum", "type": "单词", "keyWords": [] },
    { "chinese": "a. 值得纪念的", "english": "memorable", "type": "单词", "keyWords": [] },
    { "chinese": "a. 纪念性的；追悼的；n. [C]纪念碑(to sb.)", "english": "memorial", "type": "单词", "keyWords": [] },
    { "chinese": "为……立的纪念碑；作为……的纪念物", "english": "a memorial to sb.", "type": "短语", "keyWords": ["memorial"] },
    { "chinese": "教堂的礼拜仪式是为纪念死于战争中的人而举行的。", "english": "The church service is a memorial to those killed in the war.", "type": "句子", "keyWords": ["memorial"] },
    { "chinese": "v. 记住；熟记", "english": "memorize", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](U)记忆(力)；n. [C]回忆；留在记忆中的人或物；[计]存储器；n. [U]纪念", "english": "memory", "type": "单词", "keyWords": [] },
    { "chinese": "对某事的记忆力很好/差", "english": "have a good/bad/poor memory for sth.", "type": "短语", "keyWords": ["memory"] },
    { "chinese": "记着，没有忘记", "english": "bear/have/keep...in memory/mind", "type": "短语", "keyWords": ["memory"] },
    { "chinese": "凭记忆(发言)", "english": "(make a speech) from memory", "type": "短语", "keyWords": ["memory"] },
    { "chinese": "那不过是我的校园生活/学生时代的一个美好回忆而已。", "english": "It is but a good memory of my schooldays.", "type": "句子", "keyWords": ["memory"] },
    { "chinese": "以纪念（近in honour of，in celebration of，in search of）", "english": "in memory of", "type": "短语", "keyWords": ["memory"] },
    { "chinese": "他们为了纪念那位科学家种了一棵树。", "english": "They planted a tree in memory of the scientist.", "type": "句子", "keyWords": ["memory"] },
    { "chinese": "有很多东西要记", "english": "have a lot of memory work to do", "type": "句子", "keyWords": ["memory"] },
    { "chinese": "v. 修理，修补；弥补，改善", "english": "mend", "type": "单词", "keyWords": [] },
    { "chinese": "a. 精神的；智力的；内心的；mentally ad. 智力上地；精神上地；*mentality n. [U]智力；mental disorder精神错乱；mental hospital精神病院", "english": "mental", "type": "单词", "keyWords": [] },
    { "chinese": "v. 提到，说起；make mention of...；n. [U]说到，提及", "english": "mention", "type": "单词", "keyWords": [] },
    { "chinese": "提及做某事", "english": "mention doing sth.", "type": "短语", "keyWords": ["mention"] },
    { "chinese": "不用谢；不用客气。", "english": "Don't mention it.", "type": "句子", "keyWords": ["mention"] },
    { "chinese": "更不用说，此外（let alone）", "english": "not to mention", "type": "短语", "keyWords": ["mention"] },
    { "chinese": "已发现的就有1000万片，更不用说还有埋在地底下没有动过的。", "english": "The discovered pieces have amounted to ten million not to mention those lying untouched underground.", "type": "句子", "keyWords": ["mention"] },
    { "chinese": "说起（近at the sight/thought/command of）", "english": "at the mention of...", "type": "短语", "keyWords": ["mention"] },
    { "chinese": "n. [C]菜单；[计]菜单", "english": "menu", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]商人", "english": "merchant", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](U)慈悲；宽容；merciful a. 慈悲的；merciless a. 无情的，残忍的", "english": "mercy", "type": "单词", "keyWords": [] },
    { "chinese": "任……的摆布 = (be) left to the mercy/mercies of...", "english": "at the mercy of", "type": "短语", "keyWords": ["mercy"] },
    { "chinese": "农民是靠天吃饭的。", "english": "Farmers are at the mercy of the weather.", "type": "句子", "keyWords": ["mercy"] },
    { "chinese": "怜悯某人；可怜某人", "english": "show mercy to sb. = have mercy on sb.", "type": "短语", "keyWords": ["mercy"] },
    { "chinese": "冷酷无情地", "english": "without mercy = mercilessly", "type": "短语", "keyWords": ["mercy"] },
    { "chinese": "n. [C][U]安乐死", "english": "*mercy killing", "type": "单词", "keyWords": [] },
    { "chinese": "a. 仅仅的；merely ad. 仅仅，只不过(=only)；纯粹；全然", "english": "mere", "type": "单词", "keyWords": [] },
    { "chinese": "仅仅是个孩子", "english": "a mere child", "type": "短语", "keyWords": ["mere"] },
    { "chinese": "只有100米", "english": "a mere 100 metres", "type": "短语", "keyWords": ["mere"] },
    { "chinese": "完全是一个形式问题。", "english": "This is merely a matter of form.", "type": "句子", "keyWords": ["mere"] },
    { "chinese": "n. [C]优点(常pl.merits)", "english": "*merit", "type": "单词", "keyWords": [] },
    { "chinese": "a. 欢乐的；轻快的；merrily ad. 欢乐地；*meriment n. [U]欢乐", "english": "merry", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](常与a连用)凌乱状态；混乱局面；困境；vt. 弄脏；弄乱；messy a. 凌乱的；脏的(近in a mess肮脏；混乱)", "english": "mess", "type": "单词", "keyWords": [] },
    { "chinese": "(计划等事情)弄糟；把……弄得脏乱不堪", "english": "mess...up = make a mess of", "type": "短语", "keyWords": ["mess"] },
    { "chinese": "n. [C](口头、书面或用信号传达的)信息；消息，音信；留言；电报", "english": "message", "type": "单词", "keyWords": [] },
    { "chinese": "给某人带个信", "english": "give sb.a message", "type": "短语", "keyWords": ["message"] },
    { "chinese": "给某人留个信/条", "english": "leave a message for sb.", "type": "短语", "keyWords": ["message"] },
    { "chinese": "我能为你传个话吗？", "english": "Can I take a message for you?", "type": "句子", "keyWords": ["message"] },
    { "chinese": "n. [C]送信者；通信员", "english": "messenger", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]金属；metallic a. 金属(质)的；金属性的", "english": "metal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]米(公制长度单位)；measure the road by the metre以米为单位量路的长度", "english": "meter/mètre", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]测量仪表；计量器；an electric meter电表；a water meter水表", "english": "meter", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]方法；办法(系统的、有步骤的方法，侧重指做事方法的科学性、系统性)", "english": "method", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](U)地下铁道；地铁；travel on the metro/by metro乘地铁旅行", "english": "metro", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]扩音器；话筒", "english": "microphone", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]微波；a. 微波的；a microwave oven微波炉", "english": "microwave", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]中午；at midday在正午", "english": "midday", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]中间；中部；腰部；a. 中间的；middle-aged a. 中年的；middle class中产阶级；in the Middle East在中东；in the middle of...在……中间(近in the midst of, in the centre of)", "english": "middle", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]午夜；半夜；at midnight在午夜；after midnight午夜后", "english": "midnight", "type": "单词", "keyWords": [] },
    { "chinese": "v. (尤指)移居海外；迁移；(鸟等)迁往", "english": "*migrate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]候鸟；移栖动物；移居者；a. 迁移的；migrant workers外出务工人员", "english": "*migrant", "type": "单词", "keyWords": [] },
    { "chinese": "aux. 可以(表示许可或用于请求许可)；或许，可能(常用于肯定句、否定句中)；n. [U]力；力气；力量；*mighty a. 强大的；巨/浩大的；[口]非常的", "english": "might", "type": "单词", "keyWords": [] },
    { "chinese": "a. 和缓的；温和的；温暖的；*mildness n. [U]和缓；温和；温暖", "english": "mild", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]英里", "english": "mile", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]里程碑；a milestone in human history人类历史上划时代事件", "english": "milestone", "type": "单词", "keyWords": [] },
    { "chinese": "a. 军事的；军用的", "english": "military", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]牛奶；奶；v. 挤……的奶；*milky a. 乳白色的；乳状的；milk the cow挤母牛的奶；*the Milky Way银河系", "english": "milk", "type": "单词", "keyWords": [] },
    { "chinese": "对无法挽回的事哭也没用。", "english": "It's/There's no good/use crying over spilt milk.", "type": "句子", "keyWords": ["milk"] },
    { "chinese": "n. [C]磨坊；工场；工厂；a paper mill造纸厂", "english": "mill", "type": "单词", "keyWords": [] },
    { "chinese": "num. 百万；(pl.)许多；无数；数百万", "english": "million", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]百万富翁；大富翁", "english": "millionaire", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]理智；意向；头脑；具……头脑的人；vt./vi. 介意，反对；注意；留心", "english": "mind", "type": "单词", "keyWords": [] },
    { "chinese": "牢记某事", "english": "bear/keep sth. in mind (bear/keep in mind that...", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "想起", "english": "bring...back to mind = call...to mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "思想开放；愿意听取意见", "english": "have an open mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "浮现在某人的脑海中；想到", "english": "come into sb.'s mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "如释重负；搬掉某人心中的一块石头", "english": "take a load/weight off sb.'s mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "改变主意", "english": "change/alter one's mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "被忘却；发疯", "english": "go/be out of one's mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "看出……的心事", "english": "read one's mind", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "拿定主意做某事", "english": "make up one's mind to do sth.", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "当代有才智的人(们)", "english": "the great mind(s) of the time", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "在乎……", "english": "mind doing sth.", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "别管闲事", "english": "mind one's own business", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "请注意；你听着", "english": "mind you", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "要是你不反对/不介意", "english": "if you don't mind...", "type": "短语", "keyWords": ["mind"] },
    { "chinese": "当心脚下。", "english": "Mind the step.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "记住我的话。", "english": "Mind what I say!", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "别担心；不要紧。", "english": "Never mind.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "健全的精神寓于强壮的体格。", "english": "A sound mind in a sound body.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "毕竟，健康身体加上健康头脑才是最好的状态。", "english": "After all, a sound mind in a sound body is the best state to be in.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "眼不见，心不想。离久情疏。", "english": "Out of sight, out of mind.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "英雄所见略同。", "english": "Great minds think alike.", "type": "句子", "keyWords": ["mind"] },
    { "chinese": "pron. 我的(所有物)", "english": "mine", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]矿(山)；矿井；地雷；v. 采(矿)；布雷；mining n. [U]采矿业；矿业；mine coal采煤；*lay mines布雷", "english": "mine", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]矿物；a. 矿物的", "english": "mineral", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]超短裙/衣服，迷你裙(=miniskirt)；小型的东西；a. (裙等)超短的；小型的", "english": "mini", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl.minima或minimums)最低量；最低限度；*a. 最低量的；最低(限度)的；*minimal a. 最小的；极小的；最低(限度)的", "english": "minimum", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](政府的)部；Ministry全体部长(或阁员)；全体牧师", "english": "ministry", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]牧师；部长；the Prime Minister首相；行政院长；总理", "english": "minister", "type": "单词", "keyWords": [] },
    { "chinese": "a. 较次要的；较小的，不严重的(反major)；a minor injury轻伤", "english": "minor", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]少数；少数民族；a minority of the...少数……；The minority is/are against...少数反对……", "english": "minority", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 减去；a. 负(的)；减的；零下的(反plus)；Seven minus four is three.七减四等于三。；minus twenty degrees Celsius摄氏零下二十度", "english": "minus", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]分钟；in a minute马上，立刻；just a minute稍等片刻；the minute/the moment/immediately/directly/instantly...一……就……", "english": "minute", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]奇迹；miraculous a. 令人惊奇的；神奇的；不可思议的", "english": "miracle", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]镜子；v. 反射；反映；映照；look in the mirror照镜子；mirror public opinion quite well充分地反映了公众的意见", "english": "mirror", "type": "单词", "keyWords": [] },
    { "chinese": "表示“错；误；失”，如：misspell拼写错误，misprint印刷错误，misunderstand误解，mislead误导，misuse错用", "english": "mis-", "type": "前缀", "keyWords": [] },
    { "chinese": "n. [C]印刷错误；v. 印刷错误", "english": "misprint", "type": "单词", "keyWords": [] },
    { "chinese": "n.痛苦；悲惨的境遇；不幸；苦痛", "english": "misery", "type": "单词", "keyWords": [] },
    { "chinese": "a.痛苦的；悲惨的", "english": "miserable", "type": "单词", "keyWords": [] },
    { "chinese": "vt.错过；未赶上；缺（课等）；惦念；未击中；没抓住；没理解", "english": "miss", "type": "单词", "keyWords": [] },
    { "chinese": "失足", "english": "miss one's footing step", "type": "短语", "keyWords": ["miss"] },
    { "chinese": "错过某事", "english": "miss doing sth.", "type": "短语", "keyWords": ["miss"] },
    { "chinese": "不懂（俏皮话等的）妙处/要领", "english": "miss the point of sth.", "type": "短语", "keyWords": ["miss"] },
    { "chinese": "险些丧命", "english": "barely miss being killed", "type": "短语", "keyWords": ["miss"] },
    { "chinese": "房子在下一个拐角处。你不会看不到的。", "english": "The house is at the next corner. You can't miss it.", "type": "句子", "keyWords": ["miss"] },
    { "chinese": "n.小姐（用于对未婚妇女的称呼）", "english": "Miss", "type": "单词", "keyWords": [] },
    { "chinese": "a.失踪的；（页、单词等）缺掉的", "english": "missing", "type": "单词", "keyWords": [] },
    { "chinese": "n.（外交）使团；使命；任务；[美]使馆", "english": "mission", "type": "单词", "keyWords": [] },
    { "chinese": "执行秘密使命", "english": "carry out a secret mission", "type": "短语", "keyWords": ["mission"] },
    { "chinese": "被带有使命派出去", "english": "be sent on a mission", "type": "短语", "keyWords": ["mission"] },
    { "chinese": "n.（由于有缺陷的判断、知识不足或粗心造成的）错误；vt.弄错；把…错认；误解", "english": "mistake", "type": "单词", "keyWords": [] },
    { "chinese": "犯错误，做错；想错，误解", "english": "make a mistake (about sth.)", "type": "短语", "keyWords": ["mistake"] },
    { "chinese": "错误地", "english": "by mistake", "type": "短语", "keyWords": ["mistake"] },
    { "chinese": "我错拿了你的手提包，还以为是我的呢。", "english": "I took your bag instead of mine by mistake.", "type": "句子", "keyWords": ["mistake"] },
    { "chinese": "把…误认为…", "english": "mistake...for...", "type": "短语", "keyWords": ["mistake"] },
    { "chinese": "他把那根棍子错看成蛇了。", "english": "He mistook that stick for a snake.", "type": "句子", "keyWords": ["mistake"] },
    { "chinese": "误解；误会", "english": "be mistaken about sth./ sb.", "type": "短语", "keyWords": ["mistake"] },
    { "chinese": "你弄错了。", "english": "You are mistaken.", "type": "句子", "keyWords": ["mistake"] },
    { "chinese": "n.先生", "english": "mister", "type": "单词", "keyWords": [] },
    { "chinese": "n.主妇；女主人", "english": "mistress", "type": "单词", "keyWords": [] },
    { "chinese": "vt.误解；误会", "english": "misunderstand", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（U]误解；误会；分歧；曲解", "english": "misunderstanding", "type": "单词", "keyWords": [] },
    { "chinese": "vt.使混合；拌和；（with）", "english": "mix", "type": "单词", "keyWords": [] },
    { "chinese": "a.混合的，混杂的", "english": "mixed", "type": "单词", "keyWords": [] },
    { "chinese": "男女同学的学校", "english": "a mixed school", "type": "短语", "keyWords": ["mixed"] },
    { "chinese": "把…与…混合（be mixed with...与…混合）", "english": "mix sth. with sth.", "type": "短语", "keyWords": ["mix"] },
    { "chinese": "使弄不清；使混乱", "english": "mix...up", "type": "短语", "keyWords": ["mix"] },
    { "chinese": "悲（惊）喜交集", "english": "have mixed feelings", "type": "短语", "keyWords": ["mixed"] },
    { "chinese": "n.[U]混合，拌和；混合状态；n.[C]混合物；混合剂", "english": "mixture", "type": "单词", "keyWords": [] },
    { "chinese": "a.（用车拖载）流动的，机动的；活动的；可动的；n.[C][口]汽车（=automobile）", "english": "mobile", "type": "单词", "keyWords": [] },
    { "chinese": "流动图书馆", "english": "a mobile library", "type": "短语", "keyWords": ["mobile"] },
    { "chinese": "巡回医疗队", "english": "a mobile medical team", "type": "短语", "keyWords": ["mobile"] },
    { "chinese": "n.[C]方法；方式；形式；（服饰等的）式样；风尚；（电子设备或相机等的）模式，状态", "english": "mode", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]模型；典范；型；模特儿；a.模型的；模范的", "english": "model", "type": "单词", "keyWords": [] },
    { "chinese": "a.有节制的；中等的；适度的；温和的；（价格）公道的；花费不多的", "english": "moderate", "type": "单词", "keyWords": [] },
    { "chinese": "饮酒适量", "english": "be moderate in drinking", "type": "短语", "keyWords": ["moderate"] },
    { "chinese": "公道的价格", "english": "moderate prices", "type": "短语", "keyWords": ["moderate"] },
    { "chinese": "中等的收入", "english": "a moderate income", "type": "短语", "keyWords": ["moderate"] },
    { "chinese": "以中等速度", "english": "at a moderate speed", "type": "短语", "keyWords": ["moderate"] },
    { "chinese": "a.现代的；现代化的", "english": "modern", "type": "单词", "keyWords": [] },
    { "chinese": "v.（使）现代化", "english": "modernize", "type": "单词", "keyWords": [] },
    { "chinese": "a.现代化的", "english": "modernized", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（U）现代化", "english": "modernization", "type": "单词", "keyWords": [] },
    { "chinese": "四个现代化", "english": "four modernizations", "type": "短语", "keyWords": ["modernization"] },
    { "chinese": "a.谦虚的（about sth.）", "english": "modest", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]谦虚", "english": "modesty", "type": "单词", "keyWords": [] },
    { "chinese": "vt.修改；[语]修饰", "english": "modify", "type": "单词", "keyWords": [] },
    { "chinese": "a.润湿的，潮湿的；多雨的", "english": "moist", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]湿气；水分；潮湿；湿度", "english": "moisture", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]片刻；瞬间；a.瞬息间的，片刻的；暂时的", "english": "moment", "type": "单词", "keyWords": [] },
    { "chinese": "一……就……", "english": "the moment；the minute", "type": "短语", "keyWords": ["moment", "minute"] },
    { "chinese": "马上；立刻", "english": "in a moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "随时，无论什么时候", "english": "at any moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "暂时；目前", "english": "for the moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "此刻，目前；那时，当时", "english": "at the moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "片刻，一会儿", "english": "for a moment", "type": "短语", "keyWords": ["moment"] },
    { "chinese": "刻不容缓。", "english": "There is not a moment to be lost.", "type": "句子", "keyWords": ["moment"] },
    { "chinese": "n.[C]（U）星期一（略作Mon.）", "english": "Monday", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]钱；货币；a.货币的", "english": "money", "type": "单词", "keyWords": [] },
    { "chinese": "赚钱", "english": "make money", "type": "短语", "keyWords": ["money"] },
    { "chinese": "集资", "english": "raise/collect money", "type": "短语", "keyWords": ["money"] },
    { "chinese": "纸币", "english": "paper money", "type": "短语", "keyWords": ["money"] },
    { "chinese": "赚钱的", "english": "moneymaking", "type": "单词", "keyWords": ["money"] },
    { "chinese": "放贷者", "english": "moneylender", "type": "单词", "keyWords": ["money"] },
    { "chinese": "省钱的", "english": "moneysaving", "type": "单词", "keyWords": ["money"] },
    { "chinese": "金钱万能。", "english": "Money talks.", "type": "句子", "keyWords": ["money"] },
    { "chinese": "金钱是罪恶之源。", "english": "Money is the root of all evil.", "type": "句子", "keyWords": ["money"] },
    { "chinese": "n.[C]班长；监视器；[计]显示器；vt.监控；监测；监视，密切注视", "english": "monitor", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]猴子", "english": "monkey", "type": "单词", "keyWords": [] },
    { "chinese": "a.每月的；每月一次的；按月的；ad.每月一次；每月；按月；n.[C]月刊", "english": "monthly", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]纪念碑（to）（近a memorial to sb.）", "english": "monument", "type": "单词", "keyWords": [] },
    { "chinese": "亡者纪念碑", "english": "a monument to the dead", "type": "短语", "keyWords": ["monument"] },
    { "chinese": "人民英雄纪念碑", "english": "the Monument to the People's Heroes", "type": "短语", "keyWords": ["monument"] },
    { "chinese": "n.[C]心情；情绪；a.脾气不好的；喜怒无常的", "english": "mood", "type": "单词", "keyWords": [] },
    { "chinese": "心情好/坏", "english": "in a good/bright/bad mood", "type": "短语", "keyWords": ["mood"] },
    { "chinese": "(没)有心情做某事", "english": "be in no/in the mood for (doing sth./to do sth.)", "type": "短语", "keyWords": ["mood"] },
    { "chinese": "n.[C]月亮；月球", "english": "moon", "type": "单词", "keyWords": [] },
    { "chinese": "一轮弦/满/新月", "english": "a crescent/full/new moon", "type": "短语", "keyWords": ["moon"] },
    { "chinese": "在一个没月光的晚上", "english": "on a moonless night", "type": "短语", "keyWords": ["moon"] },
    { "chinese": "n.[U]月光；在月光下", "english": "moonlight", "type": "单词", "keyWords": [] },
    { "chinese": "vt.用拖把拖洗；vi.用拖把拖地", "english": "mop", "type": "单词", "keyWords": [] },
    { "chinese": "a.道德上的；有道德的；a.没有道德的；n.[U]道德（规范）", "english": "moral", "type": "单词", "keyWords": [] },
    { "chinese": "过着合乎道德的生活", "english": "lead a moral life", "type": "短语", "keyWords": ["moral"] },
    { "chinese": "道德教训", "english": "a moral lesson", "type": "短语", "keyWords": ["moral"] },
    { "chinese": "道德标准", "english": "moral standards", "type": "短语", "keyWords": ["moral"] },
    { "chinese": "商业道德", "english": "commercial morality", "type": "短语", "keyWords": ["moral"] },
    { "chinese": "a.更多的，较多的（many，much的比较级）；附加的；ad.更（用于构成形容词或副词比较级）；更多地，更大程度地（much的比较级）；pron.更多的量", "english": "more", "type": "单词", "keyWords": [] },
    { "chinese": "比起玛丽来他更该受责备。", "english": "He is more to blame than Mary.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "越来越……", "english": "more and more (beautiful/interesting)", "type": "短语", "keyWords": ["more"] },
    { "chinese": "①差不多；几乎；②或多或少；大约", "english": "more or less", "type": "短语", "keyWords": ["more"] },
    { "chinese": "我们的说明会或多或少有些帮助。", "english": "Our explanation will prove more or less helpful.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "我猜他和这件事或多或少有点牵连。", "english": "I suspect that he is more or less involved in the affair.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "越……越……", "english": "the more...，the more...", "type": "短语", "keyWords": ["more"] },
    { "chinese": "他越讲越不着边际。", "english": "The more he talked，the further he strayed from the point.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "离岸越远，视野越宽。", "english": "The further away I am off shore，the more far-sighted I will be.=I will be more far-sighted，the further away I am off shore.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "超过，多于；非常；不仅仅是", "english": "more than", "type": "短语", "keyWords": ["more"] },
    { "chinese": "非常乐意做某事", "english": "be more than happy/glad/willing to do sth.", "type": "短语", "keyWords": ["more"] },
    { "chinese": "冬眠不仅仅是睡眠，而是一种沉睡。", "english": "Hibernation is more than sleep.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "与其说……不如说……；而不是……", "english": "more...than...", "type": "短语", "keyWords": ["more"] },
    { "chinese": "与其说我气恼倒不如说受惊不小。", "english": "I was more surprised than annoyed.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "他有勇无谋。", "english": "He is more brave than wise.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "不再（近not any more）", "english": "no more", "type": "短语", "keyWords": ["more"] },
    { "chinese": "不再听到响声了。", "english": "No more sound was heard.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "只有，只不过是；也不，和……一样不", "english": "no more(..than)", "type": "短语", "keyWords": ["more"] },
    { "chinese": "我的房子跟棚子差不多。", "english": "My house is no more than a shelter.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "他和我一样不称职。", "english": "He is no more fit than I am.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "正如马不是鱼一样，鲸也不是鱼。", "english": "A whale is no more a fish than a horse is.", "type": "句子", "keyWords": ["more"] },
    { "chinese": "另外；更重要的是（近besides）", "english": "(and) what is more", "type": "短语", "keyWords": ["more"] },
    { "chinese": "ad.而且；此外", "english": "moreover", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]早晨", "english": "morning", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]蚊子", "english": "mosquito", "type": "单词", "keyWords": [] },
    { "chinese": "a.最多的（many和much的最高级）；大多数的，大部分的；ad.最（much的最高级；用于构成最高级）；最大程度上；pron.大多数；大部分；最大量", "english": "most", "type": "单词", "keyWords": [] },
    { "chinese": "大部分时间", "english": "most of the time/day", "type": "短语", "keyWords": ["most"] },
    { "chinese": "至多", "english": "at (the) most", "type": "短语", "keyWords": ["most"] },
    { "chinese": "一般说来，大部分", "english": "for the most part", "type": "短语", "keyWords": ["most"] },
    { "chinese": "充分利用", "english": "make the most of", "type": "短语", "keyWords": ["most"] },
    { "chinese": "一篇给人印象很深的文章", "english": "a most impressive piece of writing", "type": "短语", "keyWords": ["most"] },
    { "chinese": "ad.主要地；几乎全部地，大部分（比较most ad.最；最大程度上）", "english": "mostly", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]汽车旅馆", "english": "motel", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]蛾", "english": "moth", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]母亲；a.母亲般的；慈母般的；慈祥的", "english": "mother", "type": "单词", "keyWords": [] },
    { "chinese": "母语", "english": "mother tongue", "type": "短语", "keyWords": ["mother"] },
    { "chinese": "婆母；岳母", "english": "mother(s)-in-law", "type": "单词", "keyWords": ["mother"] },
    { "chinese": "孕妇；准妈妈", "english": "mother(s)-to-be", "type": "单词", "keyWords": ["mother"] },
    { "chinese": "失败是成功之母。", "english": "Failure is the mother of success.", "type": "句子", "keyWords": ["mother"] },
    { "chinese": "n.[U]（移）动；运动（与“静止”相对）；n.[C]示意动作；动议，提议；v.（向…）做手势；（向…）点（或摇）头示意；a.静止不动的", "english": "motion", "type": "单词", "keyWords": [] },
    { "chinese": "电影", "english": "motion picture", "type": "短语", "keyWords": ["motion"] },
    { "chinese": "用手示意；提议，动议", "english": "make a motion", "type": "短语", "keyWords": ["motion"] },
    { "chinese": "在开动中，在运转中", "english": "in motion", "type": "短语", "keyWords": ["motion"] },
    { "chinese": "汽车行驶的时候千万不能下车。", "english": "You must not get out of the car when it is in motion.", "type": "句子", "keyWords": ["motion"] },
    { "chinese": "vt.使产生动机；激起行动；激发…的积极性；促使；n.[C]动机", "english": "motivate", "type": "单词", "keyWords": [] },
    { "chinese": "调动某人做某事的积极性", "english": "motivate sb. to do sth.", "type": "短语", "keyWords": ["motivate"] },
    { "chinese": "杀人动机", "english": "a motive for the murder", "type": "短语", "keyWords": ["motive"] },
    { "chinese": "n.[C]电动机，马达；汽车；高速公路", "english": "motor", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]摩托车（=motorbike）；n.[C]骑摩托车的人", "english": "motorcycle", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]座右铭，格言", "english": "motto", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]山；峰；vt.爬上；使上马", "english": "mount", "type": "单词", "keyWords": [] },
    { "chinese": "峨眉山", "english": "Mount Emei", "type": "短语", "keyWords": ["mount"] },
    { "chinese": "骑警", "english": "mounted police", "type": "短语", "keyWords": ["mount"] },
    { "chinese": "n.[C]山；a.有山的；多山的；n.[C]登山运动员；vi.登山；n.[U]登山运动", "english": "mountain", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（pl.mice）老鼠；（计算机）鼠标", "english": "mouse", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]口，嘴；n.[C]一口，满口", "english": "mouth", "type": "单词", "keyWords": [] },
    { "chinese": "保持缄默", "english": "keep one's mouth shut", "type": "短语", "keyWords": ["mouth"] },
    { "chinese": "在河口处", "english": "at the river mouth", "type": "短语", "keyWords": ["mouth"] },
    { "chinese": "吃了一口食物", "english": "take a mouthful of food", "type": "短语", "keyWords": ["mouth"] },
    { "chinese": "勉强糊口；勉强过活", "english": "live from hand to mouth", "type": "短语", "keyWords": ["mouth"] },
    { "chinese": "消息通过口头流传。", "english": "The news got round by word of mouth.", "type": "句子", "keyWords": ["mouth"] },
    { "chinese": "vt.移动；搬家；运转；vi.移动；搬（家）；开动（机器）；使感动（辨析见affect）；n.[C]动；移动（指位置的变化）；搬（家）；a.感人的；动人的；a.被感动了的；a.可移动的，活动的", "english": "move", "type": "单词", "keyWords": [] },
    { "chinese": "走一步；搬家；开始行动", "english": "make a move", "type": "短语", "keyWords": ["move"] },
    { "chinese": "在忙碌", "english": "on the move/go", "type": "短语", "keyWords": ["move"] },
    { "chinese": "n.[C]运动；活动（侧重指具体的动作，也可指政治运动）", "english": "movement", "type": "单词", "keyWords": [] },
    { "chinese": "(美)民权运动", "english": "Civil Rights Movement", "type": "短语", "keyWords": ["movement"] },
    { "chinese": "民族解放运动", "english": "national liberation movement", "type": "短语", "keyWords": ["movement"] },
    { "chinese": "n.[C]电影", "english": "movie", "type": "单词", "keyWords": [] },
    { "chinese": "去看电影", "english": "go to the movies", "type": "短语", "keyWords": ["movie"] },
    { "chinese": "制片者", "english": "moviemaker", "type": "单词", "keyWords": ["movie"] },
    { "chinese": "常看电影的人", "english": "movie-goer", "type": "单词", "keyWords": ["movie"] },
    { "chinese": "vt.割（草、麦等）", "english": "mow", "type": "单词", "keyWords": [] },
    { "chinese": "割草坪", "english": "mow the lawn", "type": "短语", "keyWords": ["mow"] },
    { "chinese": "割草的人；割草机", "english": "(lawn) mower", "type": "单词", "keyWords": ["mow"] },
    { "chinese": "每小时英里数（=miles per hour）", "english": "m.p.h.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]先生（用于男子姓、姓名前）", "english": "Mr/Mr./'msta/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]夫人（用于已婚妇女姓名前）", "english": "Mrs/Mrs./msiz/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]女士（用于婚姻状况不明或不愿提及婚姻状况的女子姓、姓名前）", "english": "Ms/Ms./mrz/", "type": "单词", "keyWords": [] },
    { "chinese": "a.许多的；大量的；ad.非常，很多；更加；pron.许多；大量", "english": "much", "type": "单词", "keyWords": [] },
    { "chinese": "程度高；频率高（常用于否定句或疑问句中）", "english": "much of", "type": "短语", "keyWords": ["much"] },
    { "chinese": "他不是什么了不起的学者。", "english": "He isn't much of a scholar.", "type": "句子", "keyWords": ["much"] },
    { "chinese": "我不大见到他。", "english": "I don't see much of him.", "type": "句子", "keyWords": ["much"] },
    { "chinese": "同样多；同样程度", "english": "as much", "type": "短语", "keyWords": ["much"] },
    { "chinese": "几乎一样", "english": "much the same", "type": "短语", "keyWords": ["much"] },
    { "chinese": "太甜了", "english": "be much too sweet", "type": "短语", "keyWords": ["much"] },
    { "chinese": "这/那么多，这/那么些", "english": "this/that much", "type": "短语", "keyWords": ["much"] },
    { "chinese": "非力所能及；干不了；受不了，应付不了；过分了", "english": "This is too much for me.[俗]", "type": "句子", "keyWords": ["much"] },
    { "chinese": "就说这么多。", "english": "So much for today/the story.", "type": "句子", "keyWords": ["much"] },
    { "chinese": "n.[U]泥；泥浆；a.泥泞的", "english": "mud", "type": "单词", "keyWords": [] },
    { "chinese": "表示“多，一个以上”", "english": "multi-", "type": "单词", "keyWords": [] },
    { "chinese": "a.多个（或多种、多部分等）的；许多的；n.[C]倍数", "english": "multiple", "type": "单词", "keyWords": [] },
    { "chinese": "多项选择的", "english": "multiple-choice", "type": "单词", "keyWords": ["multiple"] },
    { "chinese": "多项选择问题", "english": "a multiple-choice question", "type": "短语", "keyWords": ["multiple"] },
    { "chinese": "多元文化共存", "english": "coexistence of multiple cultures", "type": "短语", "keyWords": ["multiple"] },
    { "chinese": "7乘以5等于35，所以35是7的倍数。", "english": "7x5 = 35, so 35 is a multiple of 7.", "type": "句子", "keyWords": ["multiple"] },
    { "chinese": "vt.乘；使相乘；vi.做乘法；增多", "english": "multiply", "type": "单词", "keyWords": [] },
    { "chinese": "以3乘5", "english": "multiply five by three", "type": "短语", "keyWords": ["multiply"] },
    { "chinese": "5乘以3等于15。", "english": "5 multiplied by 3 is 15.", "type": "句子", "keyWords": ["multiply"] },
    { "chinese": "n.[C]妈妈；n.[C][儿语]妈咪，[口]妈妈；n.[C]木乃伊，干瘪的人", "english": "mum/mummy", "type": "单词", "keyWords": [] },
    { "chinese": "vt./n.[C][U]谋杀", "english": "murder", "type": "单词", "keyWords": [] },
    { "chinese": "杀人犯，凶手", "english": "murderer", "type": "单词", "keyWords": ["murder"] },
    { "chinese": "凶杀案", "english": "a case of murder", "type": "短语", "keyWords": ["murder"] },
    { "chinese": "vt.喃喃地说；咕哝；嘀咕", "english": "murmur", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]肌肉；n.[U]体力", "english": "muscle", "type": "单词", "keyWords": [] },
    { "chinese": "a.肌肉的；肌肉发达的；强健的", "english": "muscular", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]博物馆", "english": "museum", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]蘑菇", "english": "mushroom", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]音乐；勇于承担责任；临危不惧", "english": "music", "type": "单词", "keyWords": [] },
    { "chinese": "a.音乐的；和谐的；悦耳的；n.[C]音乐片；音乐舞台剧", "english": "musical", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]音乐家；作曲家；乐师", "english": "musician", "type": "单词", "keyWords": [] },
    { "chinese": "aux.v.（指义务、命令）必须；一定，肯定（只用于肯定推测）；偏要，硬要；n.[C]必须做的事", "english": "must", "type": "单词", "keyWords": [] },
    { "chinese": "詹姆森夫人的流感一定是完全好了，因为昨天我看见她外出了。", "english": "Mrs. Jameson must have got over her flu, for I saw her go out yesterday.", "type": "句子", "keyWords": ["must"] },
    { "chinese": "为什么你偏要这么固执？", "english": "Why must you be so stubborn?", "type": "句子", "keyWords": ["must"] },
    { "chinese": "住山里必须备有保暖衣服。", "english": "Warm clothes are a must in the mountains.", "type": "句子", "keyWords": ["must"] },
    { "chinese": "a.哑的；不说话的；静音的", "english": "mute", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]羊肉", "english": "mutton", "type": "单词", "keyWords": [] },
    { "chinese": "a.互相的", "english": "mutual", "type": "单词", "keyWords": [] },
    { "chinese": "相互间的尊敬", "english": "mutual respect", "type": "短语", "keyWords": ["mutual"] },
    { "chinese": "互相谅解", "english": "mutual understanding", "type": "短语", "keyWords": ["mutual"] },
    { "chinese": "a.神秘的；难以理解的", "english": "mysterious", "type": "单词", "keyWords": [] },
    { "chinese": "神秘的符号", "english": "mysterious symbols", "type": "短语", "keyWords": ["mysterious"] },
    { "chinese": "n.[C]神秘的事物；难以理解的事物；n.[U]奥秘；神秘性", "english": "mystery", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]神话；谎言；虚构的观点或理论等", "english": "myth", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]钉子；指甲；vt.钉；使固定", "english": "nail", "type": "单词", "keyWords": [] },
    { "chinese": "a.天真的", "english": "naive", "type": "单词", "keyWords": [] },
    { "chinese": "幼稚的话", "english": "a naive remark", "type": "短语", "keyWords": ["naive"] },
    { "chinese": "天真的女孩", "english": "a naive girl", "type": "短语", "keyWords": ["naive"] },
    { "chinese": "a.裸体的；无遮盖的", "english": "naked", "type": "单词", "keyWords": [] },
    { "chinese": "肉眼能看见", "english": "be visible to the naked eye", "type": "短语", "keyWords": ["naked"] },
    { "chinese": "n.[C]姓名；名义；名声；vt.给…取名字，为…命名；列举；说出某物的名称", "english": "name", "type": "单词", "keyWords": [] },
    { "chinese": "坏名声", "english": "a bad/an ill name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "笔名", "english": "a pen name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "姓", "english": "a family name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "一个叫汤姆的男子", "english": "a man named Tom/ by the name of Tom", "type": "短语", "keyWords": ["name"] },
    { "chinese": "以…的名义，代表（近on behalf of）；凭…的权威", "english": "in the name of", "type": "短语", "keyWords": ["name"] },
    { "chinese": "（表惊奇感叹语）上帝啊！（起誓用语）上帝作证，苍天在上", "english": "in the name of God", "type": "短语", "keyWords": ["name"] },
    { "chinese": "我代表她家人发言。", "english": "I speak in the name of her family.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "凭借法律的权威", "english": "in the name of the law", "type": "短语", "keyWords": ["name"] },
    { "chinese": "出名，成名", "english": "make a name for oneself", "type": "短语", "keyWords": ["name"] },
    { "chinese": "他以交响乐钢琴演奏家成名。", "english": "He made a name for himself as a concert pianist.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "以…名字；以…为笔名", "english": "under the name of...", "type": "短语", "keyWords": ["name"] },
    { "chinese": "他以真名发表了他的新作。", "english": "He published his new book under his real name.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "（以别人、别物的名字）命名", "english": "name...after/for...", "type": "短语", "keyWords": ["name"] },
    { "chinese": "这孩子取名于他祖父母的名字。", "english": "The child was named after both his grandparents.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "名叫；只在名字上", "english": "by name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "我在那里碰到了一个名叫约翰的警察。", "english": "I met a policeman there, John by name.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "仅仅知道某人的名字（没有见过面）", "english": "know sb. by name", "type": "短语", "keyWords": ["name"] },
    { "chinese": "您尊姓大名？", "english": "May I ask/have your name?", "type": "句子", "keyWords": ["name"] },
    { "chinese": "骂某人", "english": "call sb. names", "type": "短语", "keyWords": ["name"] },
    { "chinese": "他们有毒品问题、酗酒问题、枪支问题--应有尽有（你能想得到的/你能说得出的，他们都有）。", "english": "They've had drug problems, alcohol problems, gun problems - you name it, they've got it.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "美名难得而易失。", "english": "A good name is sooner lost than won.", "type": "句子", "keyWords": ["name"] },
    { "chinese": "ad.即，也就是（=that is to say）", "english": "namely", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]/vi.小睡", "english": "nap", "type": "单词", "keyWords": [] },
    { "chinese": "打个盹儿", "english": "take/have a nap", "type": "短语", "keyWords": ["nap"] },
    { "chinese": "n.[C]餐巾；小毛巾；[英]尿布", "english": "napkin", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]水仙花", "english": "narcissus", "type": "单词", "keyWords": [] },
    { "chinese": "vt.叙述，讲述；a.叙述性的；n.[C]讲述者，叙述者", "english": "narrate", "type": "单词", "keyWords": [] },
    { "chinese": "a.狭窄的；有局限的；狭隘的；勉强的；v.（使）变窄；（使）变狭隘；（使）有局限；（使）缩小；n.[U]狭窄，狭小；偏狭，气量小；ad.狭窄地；仅仅，勉强；a.气量小的，小心眼的", "english": "narrow", "type": "单词", "keyWords": [] },
    { "chinese": "在狭义上", "english": "in a narrow sense", "type": "短语", "keyWords": ["narrow"] },
    { "chinese": "勉强逃脱；九死一生", "english": "a narrow escape", "type": "短语", "keyWords": ["narrow"] },
    { "chinese": "他们把可能性减至三个。", "english": "They narrowed the possibilities down to three.", "type": "句子", "keyWords": ["narrow"] },
    { "chinese": "居住在偏僻的乡下使他眼光变窄了。", "english": "Living in the remote countryside has narrowed him.", "type": "句子", "keyWords": ["narrow"] },
    { "chinese": "差一点被淹死", "english": "narrowly escape being drowned", "type": "短语", "keyWords": ["narrow"] },
    { "chinese": "a.污秽的，肮脏的；引人作呕的；令人厌恶的", "english": "nasty", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]国家；民族；a.全国性的；在全国范围内的", "english": "nation", "type": "单词", "keyWords": [] },
    { "chinese": "a.国家的；国民的；民族的", "english": "national", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]民族；国籍", "english": "nationality", "type": "单词", "keyWords": [] },
    { "chinese": "a.本土的；本国的；出生地的；土产的；土著的；n.[C]本地人；本国人", "english": "native", "type": "单词", "keyWords": [] },
    { "chinese": "某人的母语", "english": "one's native language", "type": "短语", "keyWords": ["native"] },
    { "chinese": "北京本地人", "english": "a native of Beijing", "type": "短语", "keyWords": ["native"] },
    { "chinese": "原产于", "english": "be native to", "type": "短语", "keyWords": ["native"] },
    { "chinese": "亚洲原产的植物", "english": "a plant native to Asia", "type": "短语", "keyWords": ["native"] },
    { "chinese": "香蕉是台湾的土（特）产。", "english": "Banana is native to Taiwan.", "type": "句子", "keyWords": ["native"] },
    { "chinese": "a.自然界的；自然的；合乎自然规律的；ad.自然地", "english": "natural", "type": "单词", "keyWords": [] },
    { "chinese": "……是自然的/天生的/人之常情", "english": "It's natural that...(should) do...; It's natural for sb. to do sth.", "type": "短语", "keyWords": ["natural"] },
    { "chinese": "n.[C]博物学家；自然主义者", "english": "naturalist", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]大自然，自然界；自然状态；本性，天性", "english": "nature", "type": "单词", "keyWords": [] },
    { "chinese": "在自然界；实际上，事实上", "english": "in nature", "type": "短语", "keyWords": ["nature"] },
    { "chinese": "心地善良/不良的", "english": "good/ill-natured", "type": "单词", "keyWords": ["nature"] },
    { "chinese": "违反自然/人性；不自然地", "english": "against nature", "type": "短语", "keyWords": ["nature"] },
    { "chinese": "天生地；天性地", "english": "by nature", "type": "短语", "keyWords": ["nature"] },
    { "chinese": "a.顽皮的；不听话的；n.[U]顽皮，不听话", "english": "naughty", "type": "单词", "keyWords": [] },
    { "chinese": "a.海军的", "english": "naval", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]海军", "english": "navy", "type": "单词", "keyWords": [] },
    { "chinese": "参加海军", "english": "join the navy", "type": "短语", "keyWords": ["navy"] },
    { "chinese": "prep.在…附近；a.近的；靠近的，接近的；在附近的；ad.近；在附近", "english": "near", "type": "单词", "keyWords": [] },
    { "chinese": "差点丧命", "english": "near/close to killing himself", "type": "短语", "keyWords": ["near"] },
    { "chinese": "靠近", "english": "be near to", "type": "短语", "keyWords": ["near"] },
    { "chinese": "到处（近here and there）", "english": "far and near", "type": "短语", "keyWords": ["near"] },
    { "chinese": "近亲", "english": "a near relative", "type": "短语", "keyWords": ["near"] },
    { "chinese": "a.附近的；邻近的；ad.在附近；prep.在…附近", "english": "nearby", "type": "单词", "keyWords": [] },
    { "chinese": "在附近的商场里", "english": "in the mall nearby/in the nearby mall", "type": "短语", "keyWords": ["nearby"] },
    { "chinese": "ad.几乎；差不多", "english": "nearly", "type": "单词", "keyWords": [] },
    { "chinese": "绝不，相差甚远，远非", "english": "not nearly", "type": "短语", "keyWords": ["nearly"] },
    { "chinese": "远不及以前漂亮。", "english": "It is not nearly so pretty as it was before.", "type": "句子", "keyWords": ["nearly"] },
    { "chinese": "a.整洁的；简洁的；n.[U]整洁；简洁", "english": "neat", "type": "单词", "keyWords": [] },
    { "chinese": "a.必要的；必需的；ad.必要地；必需地，不可避免地", "english": "necessary", "type": "单词", "keyWords": [] },
    { "chinese": "不一定（如此）", "english": "not necessarily(so)", "type": "短语", "keyWords": ["necessary"] },
    { "chinese": "你不一定要出席。", "english": "You don't necessarily have to attend it.", "type": "句子", "keyWords": ["necessary"] },
    { "chinese": "……是必要的", "english": "It is necessary that...(should) do...; It is necessary for sb. to do sth.", "type": "短语", "keyWords": ["necessary"] },
    { "chinese": "如果有必要", "english": "(it is)necessary", "type": "短语", "keyWords": ["necessary"] },
    { "chinese": "n.[U]必要性；需要；n.[C]必需品", "english": "necessity", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]颈；脖子；n.[C]项链；项圈", "english": "neck", "type": "单词", "keyWords": [] },
    { "chinese": "aux.v.必要，必须；必定（用于疑问句和否定句）；v.需要；须要，一定要；n.[C]（U）需要（物）；必要；缺乏，欠缺；a.不需要的，不必要的", "english": "need", "type": "单词", "keyWords": [] },
    { "chinese": "本不必做某事（做了不必做的事）", "english": "needn't have done sth.", "type": "短语", "keyWords": ["need"] },
    { "chinese": "非常需要某物", "english": "need sth. badly", "type": "短语", "keyWords": ["need"] },
    { "chinese": "需要修理（近want，require，deserve）", "english": "need mending=need to be mended=need repairs(n.)", "type": "短语", "keyWords": ["need"] },
    { "chinese": "满足某人的需要", "english": "satisfy/meet/answer one's needs", "type": "短语", "keyWords": ["need"] },
    { "chinese": "需要/不需要某物/做某事", "english": "there is a great need/no need for sth./to do sth.", "type": "短语", "keyWords": ["need"] },
    { "chinese": "不用着急。", "english": "There is no need for hurrying.=There is no need to hurry.", "type": "句子", "keyWords": ["need"] },
    { "chinese": "没必要担忧。", "english": "There's no need to be concerned.", "type": "句子", "keyWords": ["need"] },
    { "chinese": "需要", "english": "be in need/demand (of sth./sb.)", "type": "短语", "keyWords": ["need"] },
    { "chinese": "患难之交才是真正的朋友。", "english": "A friend in need is a friend indeed.", "type": "句子", "keyWords": ["need"] },
    { "chinese": "不用说，他又像往常一样迟到了。", "english": "Needless to say, he came late as usual.", "type": "句子", "keyWords": ["need"] },
    { "chinese": "n.[C]针；缝衣针", "english": "needle", "type": "单词", "keyWords": [] },
    { "chinese": "针和线", "english": "a needle and thread", "type": "短语", "keyWords": ["needle"] },
    { "chinese": "n.[U]缝纫活", "english": "needlework", "type": "单词", "keyWords": ["needle"] },
    { "chinese": "a.否定的；消极的；负的；反的；反面的，负面的（反positive）", "english": "negative", "type": "单词", "keyWords": [] },
    { "chinese": "vt./n.[U]疏忽；忽略（一般指因粗心等原因而没有重视）", "english": "neglect", "type": "单词", "keyWords": [] },
    { "chinese": "忘了锁门", "english": "neglect to lock the door=neglect locking the door", "type": "短语", "keyWords": ["neglect"] },
    { "chinese": "玩忽职守", "english": "neglect one's duty", "type": "短语", "keyWords": ["neglect"] },
    { "chinese": "疏于职守", "english": "the neglect of duty", "type": "短语", "keyWords": ["neglect"] },
    { "chinese": "vt.谈判；协商；洽谈（with sb. about sth.）；vi.商定；通过谈判达成或解决", "english": "negotiate", "type": "单词", "keyWords": [] },
    { "chinese": "协商合同", "english": "negotiate a contract", "type": "短语", "keyWords": ["negotiate"] },
    { "chinese": "n.[C](U]谈判；协商", "english": "negotiation", "type": "单词", "keyWords": ["negotiate"] },
    { "chinese": "n.[C](Negroes)黑人（目前带有贬义，一般用black）；a.黑（种）人的", "english": "Negro", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]邻居；紧挨着；a.附近的，毗邻的", "english": "neighbo(ur)", "type": "单词", "keyWords": [] },
    { "chinese": "隔壁邻居", "english": "next-door neighbours", "type": "短语", "keyWords": ["neighbo(ur)"] },
    { "chinese": "邻村/邻国", "english": "neighbouring villages/countries", "type": "短语", "keyWords": ["neighbo(ur)"] },
    { "chinese": "n.[C]邻近地区；街坊；住宅区，居民点", "english": "neighbourhood", "type": "单词", "keyWords": ["neighbo(ur)"] },
    { "chinese": "在……附近", "english": "in the neighbourhood (of...)", "type": "短语", "keyWords": ["neighbourhood"] },
    { "chinese": "a.两者都不；pron.两者中的无一个；ad.也不", "english": "neither", "type": "单词", "keyWords": [] },
    { "chinese": "双方都不", "english": "neither side is...；neither of the two sides is...；neither is...", "type": "短语", "keyWords": ["neither"] },
    { "chinese": "既不……也不……", "english": "neither...nor...", "type": "短语", "keyWords": ["neither"] },
    { "chinese": "你，我，其他任何人都不知道答案。", "english": "Neither you nor I, nor anybody else knows the answer.", "type": "句子", "keyWords": ["neither"] },
    { "chinese": "理论没有实践不行，实践没有理论也不行。", "english": "Neither could theory do without practice, nor could practice do without theory.", "type": "句子", "keyWords": ["neither"] },
    { "chinese": "n.[C]侄子；外甥", "english": "nephew", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]神经；(pl.)紧张；[U]勇气；胆量", "english": "nerve", "type": "单词", "keyWords": [] },
    { "chinese": "刺激某人的神经；使某人心烦意乱/发脾气", "english": "get on sb.'s nerves", "type": "短语", "keyWords": ["nerve"] },
    { "chinese": "a.神经的；神经紧张的；n.[U]神经过敏", "english": "nervous", "type": "单词", "keyWords": [] },
    { "chinese": "神经系统", "english": "nervous system", "type": "短语", "keyWords": ["nervous"] },
    { "chinese": "对……神经紧张", "english": "be nervous about", "type": "短语", "keyWords": ["nervous"] },
    { "chinese": "常加在形容词后面构成名词，表示“性质，状态，程度”", "english": "-ness", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]巢", "english": "nest", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]网；网状物；a.纯的；净的", "english": "net", "type": "单词", "keyWords": [] },
    { "chinese": "净重", "english": "net weight", "type": "短语", "keyWords": ["net"] },
    { "chinese": "净利润", "english": "net profit", "type": "短语", "keyWords": ["net"] },
    { "chinese": "n.[C]网状组织；网络", "english": "network", "type": "单词", "keyWords": [] } 
];
