const qgl16_30 = [
    { "chinese": "n.脚踝", "english": "ankle", "type": "单词", "keyWords": [] },
    { "chinese": "n.周年纪念（日）", "english": "anniversary", "type": "单词", "keyWords": [] },
    { "chinese": "婚周年纪念", "english": "a wedding anniversary", "type": "短语", "keyWords": ["anniversary"] },
    { "chinese": "周年纪念礼物", "english": "an anniversary gift", "type": "短语", "keyWords": ["anniversary"] },
    { "chinese": "v.宣布，通告；预告；显示", "english": "announce", "type": "单词", "keyWords": [] },
    { "chinese": "向某人通告…", "english": "announce to sb. that...", "type": "短语", "keyWords": ["announce"] },
    { "chinese": "乌云聚集预示着暴风雨的来临。", "english": "Gathering clouds announced the oncoming storm.", "type": "句子", "keyWords": ["announce"] },
    { "chinese": "n.通告，布告，宣告，预告", "english": "announcement", "type": "单词", "keyWords": [] },
    { "chinese": "发布通告", "english": "make an announcement", "type": "短语", "keyWords": ["announcement"] },
    { "chinese": "n.广播员；宣告者；节目播报员", "english": "announcer", "type": "单词", "keyWords": [] },
    { "chinese": "v.使烦恼；使恼怒；打扰；a.使人/感到烦恼的", "english": "annoy", "type": "单词", "keyWords": [] },
    { "chinese": "因…对…感到心烦", "english": "be annoyed about sth./with sb.", "type": "短语", "keyWords": ["annoy"] },
    { "chinese": "他母亲因为他对邻居如此粗暴无礼而恼火。", "english": "His mother was annoyed with him for being so rude to their neighbors.", "type": "句子", "keyWords": ["annoy"] },
    { "chinese": "n.烦恼", "english": "annoyance", "type": "单词", "keyWords": [] },
    { "chinese": "a.每年的；n.年刊", "english": "annual", "type": "单词", "keyWords": [] },
    { "chinese": "a.另一，再一；另外的；pron.另一件东西，另一个人；再一个", "english": "another", "type": "单词", "keyWords": [] },
    { "chinese": "互相", "english": "one another", "type": "短语", "keyWords": ["another"] },
    { "chinese": "设法，无论如何", "english": "in one way or another", "type": "短语", "keyWords": ["another"] },
    { "chinese": "又给了三天时间", "english": "be given another three days", "type": "短语", "keyWords": ["another"] },
    { "chinese": "一个接一个地；接连地", "english": "one after another", "type": "短语", "keyWords": ["another"] },
    { "chinese": "刨根究底", "english": "raise one question after another/raise questions one after another", "type": "短语", "keyWords": ["another"] },
    { "chinese": "v.回答；n.回答", "english": "answer", "type": "单词", "keyWords": [] },
    { "chinese": "为答复/应答；响应", "english": "in answer/ reply/ response to", "type": "短语", "keyWords": ["answer"] },
    { "chinese": "玛丽以笑声作为对老师问题的回答。", "english": "Mary laughed in answer to the teacher's question.", "type": "句子", "keyWords": ["answer"] },
    { "chinese": "万事通；老世故", "english": "one who knows all the answers", "type": "短语", "keyWords": ["answer"] },
    { "chinese": "应门", "english": "answer the door (bell)", "type": "短语", "keyWords": ["answer"] },
    { "chinese": "为…负责", "english": "answer for...", "type": "短语", "keyWords": ["answer"] },
    { "chinese": "你要就这件事的处理（对委员会）负责。", "english": "You will have to answer (to the committee) for your conduct of the affair.", "type": "句子", "keyWords": ["answer"] },
    { "chinese": "我将对我的错误（向你）负责。", "english": "I'll answer (to you) for my wrong doings.", "type": "句子", "keyWords": ["answer"] },
    { "chinese": "n.蚂蚁", "english": "ant", "type": "单词", "keyWords": [] },
    { "chinese": "a.南极（地区）的；n.南极洲", "english": "Antarctic", "type": "单词", "keyWords": [] },
    { "chinese": "n.南极洲", "english": "Antarctica", "type": "单词", "keyWords": [] },
    { "chinese": "n.反污染；防止（环境）污染", "english": "antipollution", "type": "单词", "keyWords": [] },
    { "chinese": "a.焦虑的；发愁的；急切的；渴望的；n.焦虑；adv.焦虑地", "english": "anxious", "type": "单词", "keyWords": [] },
    { "chinese": "为…担心，焦急", "english": "be anxious about sth./sb.", "type": "短语", "keyWords": ["anxious"] },
    { "chinese": "渴望得到；为…担心", "english": "be anxious for sth.", "type": "短语", "keyWords": ["anxious"] },
    { "chinese": "a.什么，一些，一点；任何的；随便哪一个；一般的，普通的；pron.无论哪个，任何，（无论）多少；adv.一些，少许，略微", "english": "any", "type": "单词", "keyWords": [] },
    { "chinese": "几乎没有，少有", "english": "hardly/scarccly any...", "type": "短语", "keyWords": ["any"] },
    { "chinese": "好一点（用于否定句或疑问句中）", "english": "any better", "type": "短语", "keyWords": ["any"] },
    { "chinese": "沙漠的空气几乎不含水分。", "english": "The desert air contains hardly any moisture.", "type": "句子", "keyWords": ["any"] },
    { "chinese": "你感觉好点了吗？", "english": "Are you feeling any better?", "type": "句子", "keyWords": ["any"] },
    { "chinese": "pron. 任何人；有声名的人，重要人物", "english": "anybody", "type": "单词", "keyWords": [] },
    { "chinese": "他是个重要人物吗？", "english": "Is he anybody?", "type": "句子", "keyWords": ["anybody"] },
    { "chinese": "pron. 任何人", "english": "anyone", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 不管怎么说，无论如何；反正", "english": "anyhow", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 而今再（也不）；（不）再（用于含有否定意义的结构）", "english": "anymore", "type": "单词", "keyWords": [] },
    { "chinese": "pron. 任何人；有声名的人，重要人物", "english": "anybody", "type": "单词", "keyWords": [] },
    { "chinese": "pron. 任何人", "english": "anyone", "type": "单词", "keyWords": [] },
    { "chinese": "根本不，决不，一点也不", "english": "anything but", "type": "短语", "keyWords": ["anything"] },
    { "chinese": "pron. 任何事；任何东西", "english": "anything", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 不管怎么说，无论如何", "english": "anyway", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 在（或往）任何地方", "english": "anywhere", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 分开，成零碎；分隔开，相隔开；（留置）于一旁；拆开", "english": "apart", "type": "单词", "keyWords": [] },
    { "chinese": "且莫说，除了...以外", "english": "apart from", "type": "短语", "keyWords": ["apart"] },
    { "chinese": "崩溃", "english": "fall apart", "type": "短语", "keyWords": ["apart"] },
    { "chinese": "区分", "english": "know/ tell ... apart", "type": "短语", "keyWords": ["apart"] },
    { "chinese": "把（机器）拆开", "english": "take (the machine) apart", "type": "短语", "keyWords": ["apart"] },
    { "chinese": "n. [C] [美]公寓房间 [英] flat", "english": "apartment", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 类人猿；模仿者 vt. 仿效", "english": "ape", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 道歉，认错", "english": "apologize", "type": "单词", "keyWords": [] },
    { "chinese": "为某事向某人道歉", "english": "apologize to sb. for sth.", "type": "短语", "keyWords": ["apologize"] },
    { "chinese": "n. (C)(U) 道歉，认错", "english": "apology", "type": "单词", "keyWords": [] },
    { "chinese": "道歉信", "english": "a letter of apology", "type": "短语", "keyWords": ["apology"] },
    { "chinese": "得向某人道歉", "english": "owe someone an apology", "type": "短语", "keyWords": ["apology"] },
    { "chinese": "为某事向某人道歉", "english": "make an apology to sb. for sth.", "type": "短语", "keyWords": ["apology"] },
    { "chinese": "我道歉！", "english": "My apologies!", "type": "句子", "keyWords": ["apology"] },
    { "chinese": "我为我说的话道歉。", "english": "I made an apology for what I had said.", "type": "句子", "keyWords": ["apology"] },
    { "chinese": "n. (C)（下载到智能手机或平板电脑等设备上使用的）应用软件；应用程序（application 的省略）", "english": "app", "type": "单词", "keyWords": [] },
    { "chinese": "a. 显然的；易看见的", "english": "apparent", "type": "单词", "keyWords": [] },
    { "chinese": "adv. 显然地", "english": "apparently", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 呼吁（to sb. for sth.）；有吸引力（to sb.）；控诉，上诉；诉诸，向...求助（to）n. (C) 呼吁；吸引力；起诉，上诉", "english": "appeal", "type": "单词", "keyWords": [] },
    { "chinese": "a. 恳求的；有感染力的，吸引人的", "english": "appealing", "type": "单词", "keyWords": [] },
    { "chinese": "请求（我）帮忙；呼吁（我）帮忙", "english": "appeal (to me) for help", "type": "短语", "keyWords": ["appeal"] },
    { "chinese": "恳求我帮他", "english": "appeal to me to give him help", "type": "短语", "keyWords": ["appeal"] },
    { "chinese": "对裁定提出上诉", "english": "appeal against a decision", "type": "短语", "keyWords": ["appeal"] },
    { "chinese": "（作出）向公众求援的呼吁", "english": "(make) an appeal for help to the public", "type": "短语", "keyWords": ["appeal"] },
    { "chinese": "这个主意对我毫无吸引力。", "english": "This idea didn't appeal to me at all.", "type": "句子", "keyWords": ["appeal"] },
    { "chinese": "这不合我意。/ 我不欣赏。", "english": "It has no appeal for me.", "type": "句子", "keyWords": ["appeal"] },
    { "chinese": "vi. 出现（turn, show, come up）v. 显得；好像（近 seem）", "english": "appear", "type": "单词", "keyWords": [] },
    { "chinese": "好像很年轻", "english": "appear young", "type": "短语", "keyWords": ["appear"] },
    { "chinese": "（某人觉得）好像，似乎", "english": "It appears (to sb.) that...", "type": "短语", "keyWords": ["appear"] },
    { "chinese": "好像（似乎/碰巧/假装）在/已经...", "english": "appear (seem/ happen/ pretend) to be doing sth./ to have done sth.", "type": "短语", "keyWords": ["appear"] },
    { "chinese": "我觉得你们全搞错了。", "english": "It appears to me that you are all mistaken. = You all appear to be mistaken.", "type": "句子", "keyWords": ["appear"] },
    { "chinese": "我们的黄油好像都吃光了。", "english": "We appear to have run out of butter.", "type": "句子", "keyWords": ["appear"] },
    { "chinese": "n. (C)(U) 出现；外观，外表", "english": "appearance", "type": "单词", "keyWords": [] },
    { "chinese": "外貌；外表", "english": "physical appearances", "type": "短语", "keyWords": ["appearance"] },
    { "chinese": "从外表判断", "english": "judge by one's appearance", "type": "短语", "keyWords": ["appearance"] },
    { "chinese": "在外貌上；看起来", "english": "in appearance", "type": "短语", "keyWords": ["appearance"] },
    { "chinese": "出现；登台", "english": "make one's appearance", "type": "短语", "keyWords": ["appearance"] },
    { "chinese": "初次/末次登台", "english": "make one's first/ last appearance on the stage", "type": "短语", "keyWords": ["appearance"] },
    { "chinese": "n. (U)(C) 食欲（常和a/an用）n. (C) 欲望（for）；爱好（for）", "english": "appetite", "type": "单词", "keyWords": [] },
    { "chinese": "食欲不振", "english": "lose one's appetite", "type": "短语", "keyWords": ["appetite"] },
    { "chinese": "有...的欲望", "english": "have an appetite for", "type": "短语", "keyWords": ["appetite"] },
    { "chinese": "胃口好/坏", "english": "have a good/ bad appetite (for dinner)", "type": "短语", "keyWords": ["appetite"] },
    { "chinese": "他出奇地喜爱艰巨的工作。", "english": "He has an amazing appetite for hard work.", "type": "句子", "keyWords": ["appetite"] },
    { "chinese": "v. 向..鼓掌；鼓掌欢迎/喝彩，称赞 v. 鼓掌（for）", "english": "applaud", "type": "单词", "keyWords": [] },
    { "chinese": "为他鼓掌", "english": "applaud him", "type": "短语", "keyWords": ["applaud"] },
    { "chinese": "称赞他们满意的东西", "english": "applaud anything that pleased them", "type": "短语", "keyWords": ["applaud"] },
    { "chinese": "n. [U] 鼓掌，掌声；欢呼，喝彩", "english": "applause", "type": "单词", "keyWords": [] },
    { "chinese": "博得喝彩，受到赞扬", "english": "win applause", "type": "短语", "keyWords": ["applause"] },
    { "chinese": "n. [C] 苹果", "english": "apple", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 苹果馅饼", "english": "apple pie", "type": "短语", "keyWords": ["apple"] },
    { "chinese": "口] 纽约市", "english": "the Apple", "type": "短语", "keyWords": ["apple"] },
    { "chinese": "n. (C) 器具", "english": "appliance", "type": "单词", "keyWords": [] },
    { "chinese": "家用器具", "english": "household appliances", "type": "短语", "keyWords": ["appliance"] },
    { "chinese": "电器/电气设备", "english": "electrical appliances", "type": "短语", "keyWords": ["appliance"] },
    { "chinese": "n. (C) 申请人", "english": "applicant", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可适用的，可应用的", "english": "applicable", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C)(U) 应用；申请 n. (C) 申请表", "english": "application", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 申请 v.vi. 应用；适用", "english": "apply", "type": "单词", "keyWords": [] },
    { "chinese": "a. 应用的，实用的", "english": "applied", "type": "单词", "keyWords": [] },
    { "chinese": "请假", "english": "apply for leave", "type": "短语", "keyWords": ["apply"] },
    { "chinese": "向...求职", "english": "apply to sb. for a job", "type": "短语", "keyWords": ["apply"] },
    { "chinese": "专心于（近devote oneself to）", "english": "apply oneself to...", "type": "短语", "keyWords": ["apply"] },
    { "chinese": "应用......，适用于", "english": "apply(...) to...", "type": "短语", "keyWords": ["apply"] },
    { "chinese": "应用科学/应用物理", "english": "applied science/ physics", "type": "短语", "keyWords": ["applied"] },
    { "chinese": "她不能全力以赴地去安排自己的婚礼。", "english": "She could not entirely apply herself to the arrangements for her wedding.", "type": "句子", "keyWords": ["apply"] },
    { "chinese": "这些条例适用于你们所有人。", "english": "The rules apply (vi.) to you all.", "type": "句子", "keyWords": ["apply"] },
    { "chinese": "把科学发现应用于工业生产", "english": "apply (vt.) scientific discoveries to the industrial production", "type": "短语", "keyWords": ["apply"] },
    { "chinese": "v. 任命；委任（dismiss）；约定；指定", "english": "appoint", "type": "单词", "keyWords": [] },
    { "chinese": "派某人担任某职", "english": "appoint sb. to a post", "type": "短语", "keyWords": ["appoint"] },
    { "chinese": "任命某人为会长", "english": "appoint sb. as chairman", "type": "短语", "keyWords": ["appoint"] },
    { "chinese": "任命某人为院长", "english": "appoint sb. (to be) director", "type": "短语", "keyWords": ["appoint"] },
    { "chinese": "定野餐日期（近fix the date for...）", "english": "appoint the date for the picnic", "type": "短语", "keyWords": ["appoint"] },
    { "chinese": "n. (C) 约会；职位 n. (U) 任命", "english": "appointment", "type": "单词", "keyWords": [] },
    { "chinese": "就任", "english": "take up an appointment", "type": "短语", "keyWords": ["appointment"] },
    { "chinese": "和某人定下约会时间", "english": "make an appointment with sb.", "type": "短语", "keyWords": ["appointment"] },
    { "chinese": "vt. 对...表示感激；重视；欣赏，赏识；体会，懂得", "english": "appreciate", "type": "单词", "keyWords": [] },
    { "chinese": "欣赏做某事", "english": "appreciate doing sth.", "type": "短语", "keyWords": ["appreciate"] },
    { "chinese": "欣赏...；感谢...", "english": "appreciate sth.", "type": "短语", "keyWords": ["appreciate"] },
    { "chinese": "感谢你...的好意", "english": "appreciate your kindness in doing sth...", "type": "短语", "keyWords": ["appreciate"] },
    { "chinese": "如果...我会很感激", "english": "I would very much appreciate it if you could...", "type": "短语", "keyWords": ["appreciate"] },
    { "chinese": "我们恭候佳音。", "english": "We shall appreciate hearing from you again.", "type": "句子", "keyWords": ["appreciate"] },
    { "chinese": "许多大作家在世时，他们的作品没有得到人们的充分赞赏。", "english": "Many great writers were not appreciated fully while they were alive.", "type": "句子", "keyWords": ["appreciate"] },
    { "chinese": "如能寄一份给我，我将万分感激。", "english": "I would appreciate it very much if you could send me a copy.", "type": "句子", "keyWords": ["appreciate"] },
    { "chinese": "n. (U) 感激；重视；赏识，欣赏；理解（常和a连用）", "english": "appreciation", "type": "单词", "keyWords": [] },
    { "chinese": "欣赏；了解", "english": "have an appreciation of sth.", "type": "短语", "keyWords": ["appreciation"] },
    { "chinese": "她对于美术和音乐有了解。", "english": "She has an appreciation of art and music.", "type": "句子", "keyWords": ["appreciation"] },
    { "chinese": "vt. 接近vi. 临近n. (U)接近n. [C] 看法，观点；处理方法（侧重指学习或研究问题的方法）；入门；途径；接近的路（近access）", "english": "approach", "type": "单词", "keyWords": [] },
    { "chinese": "adj. 可进入的；易接近的；易交谈的，平易近人的", "english": "approachable", "type": "单词", "keyWords": ["approach"] },
    { "chinese": "敌人/假日的来临", "english": "the approach of the enemy/the holiday", "type": "短语", "keyWords": ["approach"] },
    { "chinese": "去...的路；做...的方法", "english": "approach to", "type": "短语", "keyWords": ["approach"] },
    { "chinese": "学物理没有捷径。", "english": "There is no easy approach to physics.", "type": "句子", "keyWords": ["approach"] },
    { "chinese": "所有通往宫殿的路都被封了。", "english": "All the approaches to the palace were blocked.", "type": "句子", "keyWords": ["approach"] },
    { "chinese": "a. 合适的，适当的（适合特定的人/条件/事件/地点）", "english": "appropriate", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 大约", "english": "approximately", "type": "单词", "keyWords": [] },
    { "chinese": "vt/vi. 批准；赞成", "english": "approve", "type": "单词", "keyWords": [] },
    { "chinese": "赞成做某事", "english": "approve of (doing) sth.", "type": "短语", "keyWords": ["approve"] },
    { "chinese": "国会批准了该项法案。", "english": "Congress approved the bill.", "type": "句子", "keyWords": ["approve"] },
    { "chinese": "我们的父亲不赞成为运动而牺牲学业。", "english": "Our father won't approve of any sacrifice of studies to sports.", "type": "句子", "keyWords": ["approve"] },
    { "chinese": "n. (U) 批准；赞成", "english": "approval", "type": "单词", "keyWords": [] },
    { "chinese": "他笑了一下表示赞成。", "english": "He showed his approval by smiling.", "type": "句子", "keyWords": ["approval"] },
    { "chinese": "n. [C] 阿拉伯人a. 阿拉伯的；阿拉伯人的", "english": "Arab", "type": "单词", "keyWords": [] },
    { "chinese": "n. 阿拉伯语a. 阿拉伯人/语的；阿拉伯的", "english": "Arabic", "type": "单词", "keyWords": [] },
    { "chinese": "阿拉伯数字", "english": "Arabic figures/ numerals", "type": "短语", "keyWords": ["Arabic"] },
    { "chinese": "n. [C] 建筑师", "english": "architect", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)建筑学；建筑（样式、风格、工程）", "english": "architecture", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 拱道", "english": "archway", "type": "单词", "keyWords": [] },
    { "chinese": "a. 北极的 n. 北极；北极圈", "english": "Arctic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 地区；领域；面积", "english": "area", "type": "单词", "keyWords": [] },
    { "chinese": "面积为16平方米", "english": "16 square metres in area", "type": "短语", "keyWords": ["area"] },
    { "chinese": "v. 争辩，争论", "english": "argue", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C)(U) 争辩，争论 n. (C) 论据，论点", "english": "argument", "type": "单词", "keyWords": ["argue"] },
    { "chinese": "和某人就某事争辩", "english": "argue with sb. about sth.", "type": "短语", "keyWords": ["argue"] },
    { "chinese": "说服某人做/不做某事", "english": "argue sb. into/ out of doing sth.", "type": "短语", "keyWords": ["argue"] },
    { "chinese": "他说服我加入那个俱乐部。", "english": "He argued me into joining the club.", "type": "句子", "keyWords": ["argue"] },
    { "chinese": "vi. (arose, arisen) 起身，起立；出现；产生；（太阳等）上升", "english": "arise", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 计算；算术", "english": "arithmetic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]臂，前肢；（一件）武器；(pl)（总称）武器，军火v. 以武器装备；配备", "english": "arm", "type": "单词", "keyWords": [] },
    { "chinese": "臂挽着臂", "english": "arm in arm", "type": "短语", "keyWords": ["arm"] },
    { "chinese": "伸开双手，真心诚意地（欢迎）", "english": "with open arms", "type": "短语", "keyWords": ["arm"] },
    { "chinese": "疏远，不使接近", "english": "hold/ keep sb. or sth. at one's arm's length", "type": "短语", "keyWords": ["arm"] },
    { "chinese": "美军正持续加强它的武装部队。", "english": "The US is continually building up its armed forces.", "type": "句子", "keyWords": ["arm"] },
    { "chinese": "数千拿着弓箭的士兵摆下了阵势。", "english": "Thousands of soldiers, armed with bows and arrows, ranged themselves in order of battle.", "type": "句子", "keyWords": ["arm"] },
    { "chinese": "n. [C] 军队，陆军；一大批", "english": "army", "type": "单词", "keyWords": [] },
    { "chinese": "失业大军", "english": "the army of the unemployed", "type": "短语", "keyWords": ["army"] },
    { "chinese": "一大群蚂蚁", "english": "an army of ants", "type": "短语", "keyWords": ["army"] },
    { "chinese": "prep. 在周围；环绕ad. 在周围；大约；在附近，存在着", "english": "around", "type": "单词", "keyWords": [] },
    { "chinese": "东张西望", "english": "look around", "type": "短语", "keyWords": ["around"] },
    { "chinese": "带领（某人）参观（某处）", "english": "show sb. around", "type": "短语", "keyWords": ["around"] },
    { "chinese": "传播；足够分配", "english": "go around", "type": "短语", "keyWords": ["around"] },
    { "chinese": "目前重感冒正在流行。", "english": "There are a lot of bad colds going around at the moment.", "type": "句子", "keyWords": ["around"] },
    { "chinese": "我们有面包，够大家吃的。", "english": "We have enough bread to go around.", "type": "句子", "keyWords": ["around"] },
    { "chinese": "她最近不活跃了/不到这里来了。", "english": "She hasn't been around lately.", "type": "句子", "keyWords": ["around"] },
    { "chinese": "vt. 唤醒；鼓励，引起", "english": "arouse", "type": "单词", "keyWords": [] },
    { "chinese": "没引起我的兴趣", "english": "arouse no interest in me", "type": "短语", "keyWords": ["arouse"] },
    { "chinese": "激起我的同情心", "english": "arouse my pity", "type": "短语", "keyWords": ["arouse"] },
    { "chinese": "vt/vi. 安排，整理", "english": "arrange", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 安排", "english": "arrangement", "type": "单词", "keyWords": ["arrange"] },
    { "chinese": "整理书籍", "english": "arrange books", "type": "短语", "keyWords": ["arrange"] },
    { "chinese": "筹备会议", "english": "arrange a meeting", "type": "短语", "keyWords": ["arrange"] },
    { "chinese": "安排...做某事（近wait/ long for sb. to do...）", "english": "arrange for sb. to do sth.", "type": "短语", "keyWords": ["arrange"] },
    { "chinese": "切实安排好他们的就业和生活", "english": "make proper arrangements for their employment and life", "type": "短语", "keyWords": ["arrangement"] },
    { "chinese": "我已经安排好一位顾问来和他谈。", "english": "I've arranged for a counselor to see him.", "type": "句子", "keyWords": ["arrange"] },
    { "chinese": "会议安排在星期六下午。", "english": "The meeting is arranged for Saturday afternoon.", "type": "句子", "keyWords": ["arrange"] },
    { "chinese": "v. 拘捕，逮捕；拘留n. (C)(U) 逮捕", "english": "arrest", "type": "单词", "keyWords": [] },
    { "chinese": "因为某事而拘捕某人", "english": "arrest sb. for sth.", "type": "短语", "keyWords": ["arrest"] },
    { "chinese": "拘捕一名犯罪疑犯", "english": "the arrest of a criminal suspect", "type": "短语", "keyWords": ["arrest"] },
    { "chinese": "vi. 来到，到达（at/ in）", "english": "arrive", "type": "单词", "keyWords": [] },
    { "chinese": "得出结论", "english": "arrive at a conclusion", "type": "短语", "keyWords": ["arrive"] },
    { "chinese": "n. (C)(U) 到达 n. [C] 到的人/物", "english": "arrival", "type": "单词", "keyWords": ["arrive"] },
    { "chinese": "当我到达上海时...", "english": "On my arrival in Shanghai...", "type": "短语", "keyWords": ["arrival"] },
    { "chinese": "新出生的是个男孩。", "english": "The new arrival is a boy.", "type": "句子", "keyWords": ["arrival"] },
    { "chinese": "n. [C] 箭；箭头符号", "english": "arrow", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 美术；艺术；（一门）人文科学(pl) 文科 n. (C) 技术；技艺a. 美术（品）的；艺术（品）的", "english": "art", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 艺术家", "english": "artist", "type": "单词", "keyWords": ["art"] },
    { "chinese": "a. 艺术的，有美感的，风雅的", "english": "artistic", "type": "单词", "keyWords": ["art"] },
    { "chinese": "艺术品", "english": "a work of art", "type": "短语", "keyWords": ["art"] },
    { "chinese": "工艺美术", "english": "industrial arts", "type": "短语", "keyWords": ["art"] },
    { "chinese": "（总称）美术", "english": "the fine arts", "type": "短语", "keyWords": ["art"] },
    { "chinese": "艺术界", "english": "the artistic community", "type": "短语", "keyWords": ["artistic"] },
    { "chinese": "n. [C] 论文，文章；商品，物品；项目，条款；冠词", "english": "article", "type": "单词", "keyWords": [] },
    { "chinese": "一种食品", "english": "an article of food", "type": "短语", "keyWords": ["article"] },
    { "chinese": "一件衣服", "english": "an article of clothing", "type": "短语", "keyWords": ["article"] },
    { "chinese": "日用品", "english": "articles of daily use", "type": "短语", "keyWords": ["article"] },
    { "chinese": "战争条款", "english": "articles of war", "type": "短语", "keyWords": ["article"] },
    { "chinese": "a. 仿真的；做作的；人造的", "english": "artificial", "type": "单词", "keyWords": [] },
    { "chinese": "假笑；不自然的微笑", "english": "an artificial smile", "type": "短语", "keyWords": ["artificial"] },
    { "chinese": "人工降雨", "english": "artificial rain", "type": "短语", "keyWords": ["artificial"] },
    { "chinese": "conj. 正当...的时候；像...一样（表示比较、方式，引导某些定语从句）；由于；尽管（注意用倒装语序）prep. 作为；以...身份", "english": "as", "type": "单词", "keyWords": [] },
    { "chinese": "也，又", "english": "as well", "type": "短语", "keyWords": ["as"] },
    { "chinese": "（除某事/人外）还", "english": "as well as", "type": "短语", "keyWords": ["as"] },
    { "chinese": "同...一样", "english": "as...as...", "type": "短语", "keyWords": ["as"] },
    { "chinese": "不如...那样", "english": "not as/ so...as...", "type": "短语", "keyWords": ["as"] },
    { "chinese": "跟...相同", "english": "the same...as", "type": "短语", "keyWords": ["as"] },
    { "chinese": "诸如...类的", "english": "such(...)as...", "type": "短语", "keyWords": ["as"] },
    { "chinese": "一般来说", "english": "as a rule", "type": "短语", "keyWords": ["as"] },
    { "chinese": "整个地；整个说来", "english": "as a whole", "type": "短语", "keyWords": ["as"] },
    { "chinese": "如下", "english": "as follows", "type": "短语", "keyWords": ["as"] },
    { "chinese": "根据现状，就以现状", "english": "as it is", "type": "短语", "keyWords": ["as"] },
    { "chinese": "一...（就）...", "english": "as soon as/ the moment/ hardly ... when .../ no sooner.. than ...", "type": "短语", "keyWords": ["as"] },
    { "chinese": "尽管/虽然她还是个孩子,...（注意不用冠词）", "english": "Child as she is,...", "type": "短语", "keyWords": ["as"] },
    { "chinese": "讲到，至于", "english": "as for ../regarding/ concerning/ with (in) regard to/ with (in) respect to/ with (in) reference to", "type": "短语", "keyWords": ["as"] },
    { "chinese": "至于，关于", "english": "as to", "type": "短语", "keyWords": ["as"] },
    { "chinese": "如此...以致/以便；竟然到...的地步，甚至...（比较so...that+句子）", "english": "so...as to...", "type": "短语", "keyWords": ["as"] },
    { "chinese": "好像...似的（后接虚拟语气）", "english": "as if(=as though)", "type": "短语", "keyWords": ["as"] },
    { "chinese": "远至；就...来说，就...而言", "english": "as far as", "type": "短语", "keyWords": ["as"] },
    { "chinese": "据我所知（= so far as）", "english": "as far as I know", "type": "短语", "keyWords": ["as"] },
    { "chinese": "只要，假如，如果", "english": "as long as", "type": "短语", "keyWords": ["as"] },
    { "chinese": "如此...以至于...", "english": "such+n.+as to do...", "type": "短语", "keyWords": ["as"] },
    { "chinese": "几乎", "english": "as good as", "type": "短语", "keyWords": ["as"] },
    { "chinese": "还是...好", "english": "may/ might as well do sth.", "type": "短语", "keyWords": ["as"] },
    { "chinese": "入乡随俗。", "english": "When in Rome, do as the Romans do.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "他们如此隐秘，似乎不可能被外人了解。", "english": "They were so deeply private as to seem inaccessible to outsiders.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "请...（好吗？）", "english": "Would you be so kind as to (carry the box upstairs for her)?", "type": "句子", "keyWords": ["as"] },
    { "chinese": "现在仿佛是秋天似的。", "english": "It seems as if it were autumn.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "我们到终点了。（≠so far as）", "english": "This is as far as we go.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "来吧，你愿待多久就待多久。", "english": "Come and stay as long as you please.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "只要这种病存在，所有儿童都有危险。", "english": "As long as this disease exists, all children are at risk.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "我们不是那样的蠢人，竟会相信他。", "english": "We are not such fools as to believe him. = We are not so foolish as to believe him.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "她的病还不至于令人焦虑。", "english": "Her illness is not such as to cause anxiety.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "差不多解决了。", "english": "It's as good as settled.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "他们在费用上没有什么可抱怨的。", "english": "As for the cost,they had nothing to complain of.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "至于内包装，必须具有吸引力，以促进销售。", "english": "As to the inner packing, it must be attractive and helpful to the sales.", "type": "句子", "keyWords": ["as"] },
    { "chinese": "vt/vi. 攀登；上升", "english": "ascend", "type": "单词", "keyWords": [] },
    { "chinese": "梯子呈优美的弧线型向上盘旋。", "english": "The stairs ascended in a graceful curve.", "type": "句子", "keyWords": ["ascend"] },
    { "chinese": "v. 确定；弄清；查明（近make certain/ sure that...）", "english": "ascertain", "type": "单词", "keyWords": [] },
    { "chinese": "我断定他已经死了。", "english": "I ascertained that he was dead.", "type": "句子", "keyWords": ["ascertain"] },
    { "chinese": "n. (U) 灰(pl) 灰烬，灰堆；骨灰", "english": "ash", "type": "单词", "keyWords": [] },
    { "chinese": "把...化为灰，烧成灰烬", "english": "be burnt/reduced to ashes", "type": "短语", "keyWords": ["ash"] },
    { "chinese": "a. 惭愧的；羞耻的；难为情的；因怕羞而不愿的", "english": "ashamed", "type": "单词", "keyWords": [] },
    { "chinese": "对...感到惭愧", "english": "be ashamed of doing/ to do sth.", "type": "短语", "keyWords": ["ashamed"] },
    { "chinese": "耻于问者耻于学。", "english": "He who is ashamed of asking is ashamed of learning.", "type": "句子", "keyWords": ["ashamed"] },
    { "chinese": "你竟想隐瞒自己的错误，真该感到羞耻。", "english": "You ought to be ashamed of trying (= to try) to cover up your mistakes.", "type": "句子", "keyWords": ["ashamed"] },
    { "chinese": "ad. 在旁边；到/向一边", "english": "aside", "type": "单词", "keyWords": [] },
    { "chinese": "搁置；积蓄", "english": "lay aside (¥100 a month)", "type": "短语", "keyWords": ["aside"] },
    { "chinese": "留出，存蓄", "english": "set...aside", "type": "短语", "keyWords": ["aside"] },
    { "chinese": "取消决定", "english": "set aside the decision", "type": "短语", "keyWords": ["aside"] },
    { "chinese": "留出时间给（学生）问问题", "english": "set aside time for (students to ask) questions", "type": "短语", "keyWords": ["aside"] },
    { "chinese": "vz. 问；请求；祈求", "english": "ask", "type": "单词", "keyWords": [] },
    { "chinese": "自找苦吃", "english": "ask for trouble", "type": "短语", "keyWords": ["ask"] },
    { "chinese": "问路", "english": "ask the way", "type": "短语", "keyWords": ["ask"] },
    { "chinese": "查问；打听", "english": "ask about", "type": "短语", "keyWords": ["ask"] },
    { "chinese": "请求，寻求（帮助）", "english": "ask for help", "type": "短语", "keyWords": ["ask"] },
    { "chinese": "请求（虚拟语气）", "english": "ask that...(should)", "type": "短语", "keyWords": ["ask"] },
    { "chinese": "探问某人的健康状况", "english": "ask after sb.'s health", "type": "短语", "keyWords": ["ask"] },
    { "chinese": "请假", "english": "ask for leave", "type": "短语", "keyWords": ["ask"] },
    { "chinese": "我可以问一下薪水多少吗？", "english": "May I ask about the pay?", "type": "句子", "keyWords": ["ask"] },
    { "chinese": "a. 睡着的（作表语用）", "english": "asleep", "type": "单词", "keyWords": [] },
    { "chinese": "睡得很熟", "english": "be fast/ sound asleep", "type": "短语", "keyWords": ["asleep"] },
    { "chinese": "睡着，熟睡", "english": "fall asleep", "type": "短语", "keyWords": ["asleep"] },
    { "chinese": "n. [C] 方面", "english": "aspect", "type": "单词", "keyWords": [] },
    { "chinese": "在各方面", "english": "in every aspect", "type": "短语", "keyWords": ["aspect"] },
    { "chinese": "在这方面", "english": "in this aspect (=in this respect)", "type": "短语", "keyWords": ["aspect"] },
    { "chinese": "在这方面，法语与英语不同。", "english": "In this aspect, French differs from English.", "type": "句子", "keyWords": ["aspect"] },
    { "chinese": "n. [C] 阿司匹林（药片）", "english": "aspirin", "type": "单词", "keyWords": [] },
    { "chinese": "v. 暗杀，行刺", "english": "assassinate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)C) 暗杀，行刺", "english": "assassination", "type": "单词", "keyWords": ["assassinate"] },
    { "chinese": "v. 集合，召集；装配", "english": "assemble", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 集合，召集；装配", "english": "assembly", "type": "单词", "keyWords": ["assemble"] },
    { "chinese": "装配手表", "english": "assemble a watch", "type": "短语", "keyWords": ["assemble"] },
    { "chinese": "流水线", "english": "the assembly line", "type": "短语", "keyWords": ["assembly"] },
    { "chinese": "工人们在大厅集合开会。", "english": "The workers were assembled in the hall.", "type": "句子", "keyWords": ["assemble"] },
    { "chinese": "vt.（权威地对物品）估价；评价；评论", "english": "assess", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 评价；评估", "english": "assessment", "type": "单词", "keyWords": ["assess"] },
    { "chinese": "估计房价为一百万元人民币", "english": "assess/ value the house at RMB1,000,000", "type": "短语", "keyWords": ["assess"] },
    { "chinese": "v. 分配；布置；指派，选定", "english": "assign", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 任务，工作；（课外）作业n. (U) 委派", "english": "assignment", "type": "单词", "keyWords": ["assign"] },
    { "chinese": "布置某人某事；分配某人某物", "english": "assign sb. sth.", "type": "短语", "keyWords": ["assign"] },
    { "chinese": "没给我布置家庭作业", "english": "assign me nothing for homework", "type": "短语", "keyWords": ["assign"] },
    { "chinese": "这些房间被分配给了工人。", "english": "The rooms were assigned to the workers.", "type": "句子", "keyWords": ["assign"] },
    { "chinese": "布置某人做某事", "english": "assign sb. to do sth.", "type": "短语", "keyWords": ["assign"] },
    { "chinese": "给学生留作业", "english": "give students assignments", "type": "短语", "keyWords": ["assignment"] },
    { "chinese": "老师给我们布置了什么家庭作业？", "english": "What did the teacher assign us to do at home?", "type": "句子", "keyWords": ["assign"] },
    { "chinese": "他去中东赴任。", "english": "He left for his assignment in the Middle East.", "type": "句子", "keyWords": ["assignment"] },
    { "chinese": "v. 协助，帮助", "english": "assist", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 助手a. 辅助的", "english": "assistant", "type": "单词", "keyWords": ["assist"] },
    { "chinese": "n. (U) 援助，帮助", "english": "assistance", "type": "单词", "keyWords": ["assist"] },
    { "chinese": "帮助我做工作", "english": "assist me in my work", "type": "短语", "keyWords": ["assist"] },
    { "chinese": "对某人有帮助", "english": "be of assistance/ help to sb.", "type": "短语", "keyWords": ["assistance"] },
    { "chinese": "给以援助", "english": "give/ render assistance (to sb.)", "type": "短语", "keyWords": ["assistance"] },
    { "chinese": "助理教授", "english": "assistant professor", "type": "短语", "keyWords": ["assistant"] },
    { "chinese": "v. 结合在一起；把...同...联系起来（with）", "english": "associate", "type": "单词", "keyWords": [] },
    { "chinese": "a. 联合的，关联的", "english": "associated", "type": "单词", "keyWords": ["associate"] },
    { "chinese": "与...联系在一起", "english": "be associated with...", "type": "短语", "keyWords": ["associate"] },
    { "chinese": "这个科学家不愿与这个计划有任何瓜葛，因而离开了。", "english": "The scientist didn't want to be associated with the project, and left.", "type": "句子", "keyWords": ["associate"] },
    { "chinese": "n. (C)(U) 联合；联盟；协会；社团", "english": "association", "type": "单词", "keyWords": ["associate"] },
    { "chinese": "v. 假定，想当然地认为；承担；呈现；假装", "english": "assume", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 假定，设想n. (U) 承担", "english": "assumption", "type": "单词", "keyWords": ["assume"] },
    { "chinese": "认为...", "english": "assume that...", "type": "短语", "keyWords": ["assume"] },
    { "chinese": "对...负责", "english": "assume the responsibility for sth.", "type": "短语", "keyWords": ["assume"] },
    { "chinese": "假定...；若...", "english": "Assuming/ Supposing/ Suppose/ Provided/ Providing that...,", "type": "短语", "keyWords": ["assume"] },
    { "chinese": "vt. 使（某人）相信；确保", "english": "assure", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 保证", "english": "assurance", "type": "单词", "keyWords": ["assure"] },
    { "chinese": "向...保证，使某人确信某事", "english": "assure sb. of sth. = assure sb. that...", "type": "短语", "keyWords": ["assure"] },
    { "chinese": "他向我们保证他有能力解决这个问题/他会尽全力支持我们。", "english": "He assured us of his ability to solve the problem/ of his full support. = He assured us that he had the ability to solve the problem/ he'd give his full support.", "type": "句子", "keyWords": ["assure"] },
    { "chinese": "vt. 使惊讶（见amaze ）", "english": "astonish", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 惊讶", "english": "astonishment", "type": "单词", "keyWords": ["astonish"] },
    { "chinese": "a. 感到/使人惊讶的", "english": "astonished/astonishing", "type": "单词", "keyWords": ["astonish"] },
    { "chinese": "对...惊讶", "english": "be astonished at/ by sth.", "type": "短语", "keyWords": ["astonish"] },
    { "chinese": "使某人大为惊讶的是", "english": "to one's great astonishment = much to one's astonishment", "type": "短语", "keyWords": ["astonishment"] },
    { "chinese": "使我们大为惊讶的是，这大大增加了我们进口商品的成本。", "english": "Much to our astonishment, this added much to the cost of our imports.", "type": "句子", "keyWords": ["astonishment"] },
    { "chinese": "n. [C] 宇航员", "english": "astronaut", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 航天学", "english": "astronautics", "type": "单词", "keyWords": ["astronaut"] },
    { "chinese": "n. [C] 天文学家", "english": "astronomer", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 天文学", "english": "astronomy", "type": "单词", "keyWords": ["astronomer"] },
    { "chinese": "prep. 在...里（上、旁、时刻）", "english": "at", "type": "单词", "keyWords": [] },
    { "chinese": "在...会上/在聚会上/在婚礼上", "english": "at the conference/ the party/ the wedding", "type": "短语", "keyWords": ["at"] },
    { "chinese": "n. [C] 运动员；[英]田径运动员", "english": "athlete", "type": "单词", "keyWords": [] },
    { "chinese": "a. 运动员的；运动的；体育的", "english": "athletic", "type": "单词", "keyWords": ["athlete"] },
    { "chinese": "a. 大西洋的 n. (the) 大西洋", "english": "Atlantic", "type": "单词", "keyWords": [] },
    { "chinese": "大西洋", "english": "the Atlantic (Ocean)", "type": "短语", "keyWords": ["Atlantic"] },
    { "chinese": "n. (与the连用) 大气；(可与不定冠词连用) 气氛", "english": "atmosphere", "type": "单词", "keyWords": [] },
    { "chinese": "会场中的紧张气氛", "english": "a tense atmosphere at the meeting", "type": "短语", "keyWords": ["atmosphere"] },
    { "chinese": "n. [C] 原子", "english": "atom", "type": "单词", "keyWords": [] },
    { "chinese": "a. 原子（能）的", "english": "atomic", "type": "单词", "keyWords": ["atom"] },
    { "chinese": "原子弹", "english": "atomic bomb", "type": "短语", "keyWords": ["atomic"] },
    { "chinese": "原子能", "english": "atomic energy", "type": "短语", "keyWords": ["atomic"] },
    { "chinese": "v. 连接；使依附（to） vi. 附属（to）", "english": "attach", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 依附（物）", "english": "attachment", "type": "单词", "keyWords": ["attach"] },
    { "chinese": "非常重视", "english": "attach great importance to sth.", "type": "短语", "keyWords": ["attach"] },
    { "chinese": "依附...", "english": "be attached to ...", "type": "短语", "keyWords": ["attach"] },
    { "chinese": "他的行为无可非议。", "english": "No blame is attached to his act.", "type": "句子", "keyWords": ["attach"] },
    { "chinese": "vt/i./n. [C](U) 攻击；进攻；侵害", "english": "attack", "type": "单词", "keyWords": [] },
    { "chinese": "进攻敌人", "english": "attack the enemy", "type": "短语", "keyWords": ["attack"] },
    { "chinese": "受疾病的折磨", "english": "be attacked with a disease", "type": "短语", "keyWords": ["attack"] },
    { "chinese": "攻击", "english": "make an attack on", "type": "短语", "keyWords": ["attack"] },
    { "chinese": "心脏病发作", "english": "a heart attack", "type": "短语", "keyWords": ["attack"] },
    { "chinese": "进攻是最好的防御。", "english": "Attack is the best defense.", "type": "句子", "keyWords": ["attack"] },
    { "chinese": "他们发现自己处于被动挨打的局面。", "english": "They found themselves in a passive position under attack.", "type": "句子", "keyWords": ["attack"] },
    { "chinese": "v./n. (C) 企图，试图，尝试", "english": "attempt", "type": "单词", "keyWords": [] },
    { "chinese": "a. 未遂的", "english": "attempted", "type": "单词", "keyWords": ["attempt"] },
    { "chinese": "想完成一件艰难工作", "english": "attempt a difficult task", "type": "短语", "keyWords": ["attempt"] },
    { "chinese": "企图逃跑", "english": "attempt to escape", "type": "短语", "keyWords": ["attempt"] },
    { "chinese": "试着做某事", "english": "make an attempt to do sth./at (doing) sth.", "type": "短语", "keyWords": ["attempt"] },
    { "chinese": "谋杀未遂", "english": "attempted murder", "type": "短语", "keyWords": ["attempted"] },
    { "chinese": "vi. 出席，参加；服侍；看护，照料", "english": "attend", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 出席；服侍；看护", "english": "attendance", "type": "单词", "keyWords": ["attend"] },
    { "chinese": "参加典礼", "english": "attend a ceremony", "type": "短语", "keyWords": ["attend"] },
    { "chinese": "上学", "english": "attend school", "type": "短语", "keyWords": ["attend"] },
    { "chinese": "看护", "english": "attend on", "type": "短语", "keyWords": ["attend"] },
    { "chinese": "注意，专心；处理；照料", "english": "attend to", "type": "短语", "keyWords": ["attend"] },
    { "chinese": "此病人有三个护士看护着。", "english": "The patient had three nurses attending (on/ upon) him.", "type": "句子", "keyWords": ["attend"] },
    { "chinese": "注意听我的话", "english": "attend to what I'm saying", "type": "句子", "keyWords": ["attend"] },
    { "chinese": "a. 出席的；伴随的n. [C] 侍从，随从；服务员；出席人", "english": "attendant", "type": "单词", "keyWords": ["attend"] },
    { "chinese": "n. (U) 注意；注意力；照料", "english": "attention", "type": "单词", "keyWords": [] },
    { "chinese": "a. 注意的，留心的", "english": "attentive", "type": "单词", "keyWords": ["attention"] },
    { "chinese": "ad. 注意地，留意地", "english": "attentively", "type": "单词", "keyWords": ["attention"] },
    { "chinese": "留心地，注意地", "english": "with attention", "type": "短语", "keyWords": ["attention"] },
    { "chinese": "注意", "english": "pay attention to", "type": "短语", "keyWords": ["attention"] },
    { "chinese": "使某人注意某事", "english": "bring sth. to sb's attention", "type": "短语", "keyWords": ["attention"] },
    { "chinese": "引起某人的注意", "english": "catch sb.'s attention", "type": "短语", "keyWords": ["attention"] },
    { "chinese": "促使某人注意某事", "english": "draw sb.'s attention to sth.", "type": "短语", "keyWords": ["attention"] },
    { "chinese": "认真听某人讲话", "english": "listen to sb. attentively", "type": "短语", "keyWords": ["attentively"] },
    { "chinese": "n. [C] 态度，看法（to/ towards）", "english": "attitude", "type": "单词", "keyWords": [] },
    { "chinese": "对...的态度/看法", "english": "one's attitude towards", "type": "短语", "keyWords": ["attitude"] },
    { "chinese": "你对这个问题怎么看？", "english": "What's your attitude towards this issue?", "type": "句子", "keyWords": ["attitude"] },
    { "chinese": "v. 吸引；引起", "english": "attract", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 吸引力n. [C] 具有吸引力的事物", "english": "attraction", "type": "单词", "keyWords": ["attract"] },
    { "chinese": "引起某人的注意", "english": "attract sb.'s attention", "type": "短语", "keyWords": ["attract"] },
    { "chinese": "风景点", "english": "tourist attractions/ scenic spots/ places of interest", "type": "短语", "keyWords": ["attraction"] },
    { "chinese": "a. 吸引人的；引起注意的（近inviting, appealing, charming）", "english": "attractive", "type": "单词", "keyWords": ["attract"] },
    { "chinese": "n. [C] 听众；观众（集合名词）", "english": "audience", "type": "单词", "keyWords": [] },
    { "chinese": "人数众多/为数不多的听众或观众", "english": "a large/ small audience", "type": "短语", "keyWords": ["audience"] },
    { "chinese": "a. 视听的", "english": "audio-visual", "type": "单词", "keyWords": [] },
    { "chinese": "a. 音频的，声频的，声音的", "english": "audio", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 会堂，礼堂", "english": "auditorium", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C)(U) 八月", "english": "August", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 姨；姑；婶母；舅母", "english": "aunt", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 对aunt的亲热称呼", "english": "auntie", "type": "单词", "keyWords": ["aunt"] },
    { "chinese": "n. 澳大利亚", "english": "Australia", "type": "单词", "keyWords": [] },
    { "chinese": "a. 澳洲的；澳大利亚（人）的", "english": "Australian", "type": "单词", "keyWords": ["Australia"] },
    { "chinese": "n. 奥地利", "english": "Austria", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 奥地利人a. 奥地利（人）的", "english": "Austrian", "type": "单词", "keyWords": ["Austria"] },
    { "chinese": "n. [C] 作者，著作者", "english": "author", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 权力；权威；职权 n. [C] 权威人士(pl) 当局，官方", "english": "authority", "type": "单词", "keyWords": [] },
    { "chinese": "学术权威", "english": "an academic authority", "type": "短语", "keyWords": ["authority"] },
    { "chinese": "地方当局", "english": "the local authorities", "type": "短语", "keyWords": ["authority"] },
    { "chinese": "a. 官方的；权威性的；专断的", "english": "authoritative", "type": "单词", "keyWords": ["authority"] },
    { "chinese": "vt. 授权", "english": "authorize", "type": "单词", "keyWords": ["authority"] },
    { "chinese": "官方消息", "english": "authoritative information", "type": "短语", "keyWords": ["authoritative"] },
    { "chinese": "表示'自身；自动'，例如：autobiography自传，automated自动化的，autobike摩托车", "english": "auto-", "type": "词根", "keyWords": [] },
    { "chinese": "n. [C] 汽车（automobile的缩略）", "english": "auto", "type": "单词", "keyWords": [] },
    { "chinese": "a. 自动的", "english": "automatic", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 自动地", "english": "automatically", "type": "单词", "keyWords": ["automatic"] },
    { "chinese": "n. (C)(U) 秋天；秋季", "english": "autumn", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可获得的，可采用的；可以买到的；有用的", "english": "available", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 可用性，实用性", "english": "availability", "type": "单词", "keyWords": ["available"] },
    { "chinese": "经理在不在？", "english": "Is the manager available?", "type": "句子", "keyWords": ["available"] },
    
    { "chinese": "中国可供出口的商品种类繁多。", "english": "Chinese commodities available for export are varied.", "type": "句子", "keyWords": ["available"] },
    { "chinese": "可取得的；可采用的", "english": "(sth.) is available to sb.", "type": "短语", "keyWords": ["available"] },
    { "chinese": "这些商品只供会员购买。", "english": "These goods are available to members only.", "type": "句子", "keyWords": ["available"] },
    { "chinese": "n. 林萌道；（南北向的）大街", "english": "avenue", "type": "单词", "keyWords": [] },
    { "chinese": "a. 中等的；平常的；平均的 n.（C）（U）平均，平均数；一般水平，中等水平；平均标准 v. 均分；算出...平均数 vi. 平均数为", "english": "average", "type": "单词", "keyWords": [] },
    { "chinese": "平均以上/以下", "english": "above/ below average", "type": "短语", "keyWords": ["average"] },
    { "chinese": "普通智力的", "english": "of average intelligence", "type": "短语", "keyWords": ["average"] },
    { "chinese": "平均，平均来说", "english": "on (the/an) average", "type": "短语", "keyWords": ["average"] },
    { "chinese": "在三月至七月期间，房地产价格平均下跌大约44%。", "english": "Property prices fell on average by about 44 per cent between March and July.", "type": "句子", "keyWords": ["average"] },
    { "chinese": "4和6平均得5。", "english": "If you average 4 and 6, you get 5.", "type": "句子", "keyWords": ["average"] },
    { "chinese": "v. 避免（+doing...）", "english": "avoid", "type": "单词", "keyWords": [] },
    { "chinese": "a. 能避免的", "english": "avoidable", "type": "单词", "keyWords": [] },
    { "chinese": "不应有的损失", "english": "avoidable losses", "type": "短语", "keyWords": ["avoidable"] },
    { "chinese": "我不能避而不见她。", "english": "I cannot avoid seeing her.", "type": "句子", "keyWords": ["avoid"] },
    { "chinese": "尽量避免人身攻击。", "english": "Try to avoid making personal comments.", "type": "句子", "keyWords": ["avoid"] },
    { "chinese": "v. 等待（强调满怀期望地等待；暗含肯定性）（wait for）", "english": "await", "type": "单词", "keyWords": [] },
    { "chinese": "我们必须等待事态的进一步发展。", "english": "We must await further developments.", "type": "句子", "keyWords": ["await"] },
    { "chinese": "a. 醒着的；意识到的；认识到的（to）v.（awoke, awoken/awaked）唤醒；（使）觉醒（辨析见wake）", "english": "awake", "type": "单词", "keyWords": [] },
    { "chinese": "知晓，觉察", "english": "be awake to", "type": "短语", "keyWords": ["awake"] },
    { "chinese": "醒着躺在床上", "english": "lie (wide) awake in bed", "type": "短语", "keyWords": ["awake"] },
    { "chinese": "他深知危险。", "english": "He's awake to the danger.", "type": "句子", "keyWords": ["awake"] },
    { "chinese": "一个巨大的响声把孩子吵醒了。", "english": "A great noise awoke the baby.", "type": "句子", "keyWords": ["awake"] },
    { "chinese": "v.（过去式/过去分词+ed）唤醒；使意识到；使认识到（to）（辨析见wake）", "english": "awaken", "type": "单词", "keyWords": [] },
    { "chinese": "请于六点叫醒我。", "english": "Please awaken me at six.", "type": "句子", "keyWords": ["awaken"] },
    { "chinese": "唤起某人的同情心", "english": "awaken sb.'s sympathy", "type": "短语", "keyWords": ["awaken"] },
    { "chinese": "觉醒了的人民", "english": "the awakened people", "type": "短语", "keyWords": ["awaken"] },
    { "chinese": "一定要唤醒人们，让他们清楚地认识到这些化学武器的危险性。", "english": "People must be awakened to the danger of these chemical weapons.", "type": "句子", "keyWords": ["awaken"] },
    { "chinese": "vt. 授予（奖品等）；给予报酬 n.（C）奖；奖品；奖状（for sth.）", "english": "award", "type": "单词", "keyWords": [] },
    { "chinese": "授予某人某物", "english": "award sb. sth.", "type": "短语", "keyWords": ["award"] },
    { "chinese": "授奖品给某人", "english": "award a prize to sb.", "type": "短语", "keyWords": ["award"] },
    { "chinese": "授予他一等奖", "english": "award him the first prize", "type": "短语", "keyWords": ["award"] },
    { "chinese": "a. 意识到的（近conscious）", "english": "aware", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）意识；感悟能力（前可加不定词）", "english": "awareness", "type": "单词", "keyWords": [] },
    { "chinese": "文化意识", "english": "cultural awareness", "type": "短语", "keyWords": ["awareness"] },
    { "chinese": "意识到（反be unaware of...没意识到）", "english": "be/ become aware of sth./that....", "type": "短语", "keyWords": ["aware"] },
    { "chinese": "ad. 远离；向不同方向；...去掉（与v.连用，表示损失、减少、变弱、耗尽）", "english": "away", "type": "单词", "keyWords": [] },
    { "chinese": "废除（某种制度等）；干掉", "english": "do away with", "type": "短语", "keyWords": ["away"] },
    { "chinese": "放弃", "english": "give ... away", "type": "短语", "keyWords": ["away"] },
    { "chinese": "收拾好，整理好；放在一边", "english": "put/ lay .. away", "type": "短语", "keyWords": ["away"] },
    { "chinese": "离...很远", "english": "be far away from...", "type": "短语", "keyWords": ["away"] },
    { "chinese": "别靠近火。", "english": "Keep away from the fire.", "type": "句子", "keyWords": ["away"] },
    { "chinese": "声音逐渐消逝了。", "english": "The sounds died away.", "type": "句子", "keyWords": ["away"] },
    { "chinese": "a. [口]非常的；糟透了的；可怕的；不舒服的 *awe n.（U）/v.（使）敬畏", "english": "awful", "type": "单词", "keyWords": [] },
    { "chinese": "a. 笨拙的；难对付的，使用不便的；尴尬的", "english": "awkward", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）尴尬，不便", "english": "awkwardness", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 尴尬地", "english": "awkwardly", "type": "单词", "keyWords": [] },
    { "chinese": "觉得局促不安，真尴尬，真别扭", "english": "feel awkward", "type": "短语", "keyWords": ["awkward"] },
    { "chinese": "难对付的顾客", "english": "awkward customer", "type": "短语", "keyWords": ["awkward"] },
    { "chinese": "处境困难", "english": "be in an awkward situation", "type": "短语", "keyWords": ["awkward"] },
    { "chinese": "n.（C）婴孩", "english": "baby", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）（代人临时）照看婴儿的人", "english": "baby-sitter", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）单身汉；学士", "english": "bachelor", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）背部；背面；后部，后面 a. 后面的；背后的；向后动的 ad. 向后；回；往回 v. 给...做后援，支持；倒（车等）；（使）倒/后退", "english": "back", "type": "单词", "keyWords": [] },
    { "chinese": "房屋背后", "english": "at the back of a house", "type": "短语", "keyWords": ["back"] },
    { "chinese": "仰卧", "english": "lie on one's back", "type": "短语", "keyWords": ["back"] },
    { "chinese": "偏僻街道", "english": "a back street", "type": "短语", "keyWords": ["back"] },
    { "chinese": "后门", "english": "a back door", "type": "短语", "keyWords": ["back"] },
    { "chinese": "逆流", "english": "a back current", "type": "短语", "keyWords": ["back"] },
    { "chinese": "来来回回", "english": "back and forth", "type": "短语", "keyWords": ["back"] },
    { "chinese": "隐瞒真相", "english": "keep back the truth", "type": "短语", "keyWords": ["back"] },
    { "chinese": "回顾", "english": "look back to/ on", "type": "短语", "keyWords": ["back"] },
    { "chinese": "在某人背后，背着某人", "english": "behind one's back", "type": "短语", "keyWords": ["back"] },
    { "chinese": "别过脸去不理；背弃，抛弃", "english": "turn one's back on/ upon", "type": "短语", "keyWords": ["back"] },
    { "chinese": "在我来的中国/家乡情况也是如此。", "english": "It's the same back in China/ in my hometown.", "type": "句子", "keyWords": ["back"] },
    { "chinese": "阻止向前；忍住；扣下；隐瞒", "english": "keep (sth.) back", "type": "短语", "keyWords": ["back"] },
    { "chinese": "支持...；备份（文件等）", "english": "back...up", "type": "短语", "keyWords": ["back"] },
    { "chinese": "把车倒入车库", "english": "back the car into the garage", "type": "短语", "keyWords": ["back"] },
    { "chinese": "a. 非常辛劳的（工作）", "english": "backbreaking (work)", "type": "短语", "keyWords": ["back"] },
    { "chinese": "n.（C）背景；隐蔽的（不引人注目的）地位；幕后", "english": "background", "type": "单词", "keyWords": [] },
    { "chinese": "她在艺术上的阅历让人印象深刻。", "english": "Her background in the arts is impressive.", "type": "句子", "keyWords": ["background"] },
    { "chinese": "a. 向后的；落后的 ad. 向后", "english": "backward", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 向后；倒逆", "english": "backwards", "type": "单词", "keyWords": [] },
    { "chinese": "n.（pl）细菌（单bacterium）", "english": "bacteria", "type": "单词", "keyWords": [] },
    { "chinese": "a. 细菌的", "english": "bacterial", "type": "单词", "keyWords": [] },
    { "chinese": "a. 坏的；腐败的；臭的；不道德的；有害的", "english": "bad", "type": "单词", "keyWords": [] },
    { "chinese": "剧痛", "english": "bad pains", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "越来越坏，每况愈下", "english": "go from bad to worse", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "不善于", "english": "be bad at...", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "对...是有害的；对...不好", "english": "be bad for...", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "为...感到懊悔，为...感到遗憾", "english": "feel bad about", "type": "短语", "keyWords": ["bad"] },
    { "chinese": "那太糟了。/那太可惜了。/那真过意不去。", "english": "That's too bad.", "type": "句子", "keyWords": ["bad"] },
    { "chinese": "ad. 严重地；厉害地 a. [口]健康状况不好的；有病的；情绪低落的", "english": "badly", "type": "单词", "keyWords": [] },
    { "chinese": "他的脚伤得厉害。", "english": "His foot was badly hurt.", "type": "句子", "keyWords": ["badly"] },
    { "chinese": "n.（U）羽毛球运动", "english": "badminton", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）钱包；袋；袋状物，书包", "english": "bag", "type": "单词", "keyWords": [] },
    { "chinese": "泄露机密（无意）", "english": "let the cat out of the bag", "type": "短语", "keyWords": ["bag"] },
    { "chinese": "a. 宽松的；宽松下垂的", "english": "baggy", "type": "单词", "keyWords": [] },
    { "chinese": "肥大的裤子", "english": "baggy trousers", "type": "短语", "keyWords": ["baggy"] },
    { "chinese": "n.（U）[美]行李 [英]luggage", "english": "baggage", "type": "单词", "keyWords": [] },
    { "chinese": "v. 烘烤", "english": "bake", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）面包店（见-ery）", "english": "bakery", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）平衡（C）天平（=scales）；[商]收支差额；结存（常用单数形式）v. 使均等，使平衡；权衡", "english": "balance", "type": "单词", "keyWords": [] },
    { "chinese": "身体失去平衡，摔倒；慌乱", "english": "lose one's balance", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "天平；秤", "english": "a pair of balances", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "保持（身体）平衡", "english": "keep one's balance", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "均衡的饮食", "english": "a balanced diet", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "保持自然平衡", "english": "keep the balance of nature", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "使收支平衡；结账", "english": "balance accounts", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "贸易顺/逆差", "english": "a favorable/ an unfavorable balance of trade", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "支付结欠的50元", "english": "pay a balance of 50 yuan", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "银行里有结存50元", "english": "have a balance of 50 yuan in the bank", "type": "短语", "keyWords": ["balance"] },
    { "chinese": "n.（C）露台，阳台；（戏院）楼厅", "english": "balcony", "type": "单词", "keyWords": [] },
    { "chinese": "a. 秃（头）的；无毛的；无叶的；无树的", "english": "bald", "type": "单词", "keyWords": [] },
    { "chinese": "秃顶", "english": "go bald", "type": "短语", "keyWords": ["bald"] },
    { "chinese": "n.（C）（盛大且正式的）舞会；球", "english": "ball", "type": "单词", "keyWords": [] },
    { "chinese": "化装舞会", "english": "a fancy ball", "type": "短语", "keyWords": ["ball"] },
    { "chinese": "n.（U）芭蕾舞（C）芭蕾舞剧", "english": "ballet", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）气球", "english": "balloon", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）竹；竹子", "english": "bamboo", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）竹笋", "english": "bamboo shoot", "type": "短语", "keyWords": ["bamboo"] },
    { "chinese": "v. 禁止；取缔；查禁 n.（C）禁止，禁令", "english": "ban", "type": "单词", "keyWords": [] },
    { "chinese": "禁止他销售烟（近forbid sb. to do sth. forbid doing sth.禁止某人做某事）", "english": "ban/ prohibit him from selling cigarettes", "type": "短语", "keyWords": ["ban"] },
    { "chinese": "禁止...", "english": "place/ put ... under a ban", "type": "短语", "keyWords": ["ban"] },
    { "chinese": "被禁止", "english": "be under a ban", "type": "短语", "keyWords": ["ban"] },
    { "chinese": "n.（C）香蕉", "english": "banana", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）乐队；一帮，一伙，一群；带状物；带子", "english": "band", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）绷带 v. 用绷带扎缚", "english": "bandage", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）银行；岸", "english": "bank", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）银行家", "english": "banker", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）银行业", "english": "banking", "type": "单词", "keyWords": [] },
    { "chinese": "a. 破产了的 n.（C）破产者 v. 使破产", "english": "bankrupt", "type": "单词", "keyWords": [] },
    { "chinese": "破产", "english": "go bankrupt", "type": "短语", "keyWords": ["bankrupt"] },
    { "chinese": "n.（C）棒，杆；闩；栅栏；酒吧间；售酒、食物或饮料的柜台 vt. 阻挡，拦住", "english": "bar", "type": "单词", "keyWords": [] },
    { "chinese": "一块肥皂", "english": "a bar of soap", "type": "短语", "keyWords": ["bar"] },
    { "chinese": "快餐店，小吃店", "english": "a snack bar", "type": "短语", "keyWords": ["bar"] },
    { "chinese": "结果被关在监狱/禁闭室中", "english": "end up behind (the) bars", "type": "短语", "keyWords": ["bar"] },
    { "chinese": "把他关起来", "english": "bar him in (=keep him in)", "type": "短语", "keyWords": ["bar"] },
    { "chinese": "n.（C）[美]（吃烧烤的）野外大宴会，户外烤肉餐；野餐烤肉架 v.（尤指户外）烤（肉类）", "english": "barbecue", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）理发师", "english": "barber", "type": "单词", "keyWords": [] },
    { "chinese": "去理发店", "english": "go to the barber's", "type": "短语", "keyWords": ["barber"] },
    { "chinese": "a. 无遮盖的，赤裸的；光秃的；极少的，勉勉强强的，刚刚够的", "english": "bare", "type": "单词", "keyWords": [] },
    { "chinese": "赤手空拳", "english": "bare hands", "type": "短语", "keyWords": ["bare"] },
    { "chinese": "光秃秃的树", "english": "bare trees", "type": "短语", "keyWords": ["bare"] },
    { "chinese": "光着脚的", "english": "bare-footed", "type": "短语", "keyWords": ["bare"] },
    { "chinese": "光着头的", "english": "bare-headed", "type": "短语", "keyWords": ["bare"] },
    { "chinese": "ad. 几乎不；刚刚，勉强", "english": "barely", "type": "单词", "keyWords": [] },
    { "chinese": "他好不容易才退了出来。", "english": "He barely escaped.", "type": "句子", "keyWords": ["barely"] },
    { "chinese": "刚..就....（近be about to...when...正要...这时...）", "english": "barely/scarcely...when...", "type": "短语", "keyWords": ["barely"] },
    { "chinese": "他刚到又得走了。", "english": "Barely had he arrived when he had to leave again.", "type": "句子", "keyWords": ["barely"] },
    { "chinese": "n.（C）交易，买卖；特价商品，便宜货；（通过讨价还价）成交的商品 vi. 谈判；讲价；[口]讨价还价", "english": "bargain", "type": "单词", "keyWords": [] },
    { "chinese": "买得不合算/合算", "english": "a bad/ good bargain", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "买便宜货", "english": "buy a bargain", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "（非正式）真便宜。", "english": "It's a real bargain.", "type": "句子", "keyWords": ["bargain"] },
    { "chinese": "特价日", "english": "a bargain day", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "那就这样定了。", "english": "It's a bargain. (=I agree.)", "type": "句子", "keyWords": ["bargain"] },
    { "chinese": "讨价还价", "english": "bargain over the price", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "和汤姆就鞋子讨价还价", "english": "bargain/ make a bargain with Tom about the shoes", "type": "短语", "keyWords": ["bargain"] },
    { "chinese": "n.（U）树皮（C）（狗、狐等）吠声，叫声 v.（狗、狐等）吠，叫 v. 厉声叫喊出", "english": "bark", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）障碍（物）；栅栏", "english": "barrier", "type": "单词", "keyWords": [] },
    { "chinese": "进步的障碍", "english": "a barrier to progress", "type": "短语", "keyWords": ["barrier"] },
    { "chinese": "n.（C）基，底；（纪念碑等的）底座；基地；基础 v. 把..基于；把基地设在", "english": "base", "type": "单词", "keyWords": [] },
    { "chinese": "空军基地", "english": "an air base", "type": "短语", "keyWords": ["base"] },
    { "chinese": "基于，以...为基础", "english": "base...on...", "type": "短语", "keyWords": ["base"] },
    { "chinese": "纪念碑基部/底座", "english": "the base of the monument", "type": "短语", "keyWords": ["base"] },
    { "chinese": "以事实作论辩根据", "english": "base one's arguments upon facts", "type": "短语", "keyWords": ["base"] },
    { "chinese": "该影片改编自D.H.劳伦斯的小说。", "english": "It's a film based on a novel by D. H. Lawrance.", "type": "句子", "keyWords": ["base"] },
    { "chinese": "n.（C）棒球（U）棒球运动", "english": "baseball", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）地下室；地下楼层", "english": "basement", "type": "单词", "keyWords": [] },
    { "chinese": "a. 基础的，基本的，根本的", "english": "basic", "type": "单词", "keyWords": [] },
    { "chinese": "基础工业", "english": "basic industry", "type": "短语", "keyWords": ["basic"] },
    { "chinese": "基础英语", "english": "basic English", "type": "短语", "keyWords": ["basic"] },
    { "chinese": "ad. 基本上，主要地", "english": "basically", "type": "单词", "keyWords": [] },
    { "chinese": "基本原理", "english": "a basic principle", "type": "短语", "keyWords": ["basic"] },
    { "chinese": "n.（C）盆；洗脸盆；盆地；*流域", "english": "basin", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）（pl.bases）基础（辨析见base）；根据；（fig.）前提", "english": "basis", "type": "单词", "keyWords": [] },
    { "chinese": "论据", "english": "the basis of argument", "type": "短语", "keyWords": ["basis"] },
    { "chinese": "在...基础上；根据", "english": "on the basis of", "type": "短语", "keyWords": ["basis"] },
    { "chinese": "评估标准", "english": "the basis of assessment", "type": "短语", "keyWords": ["basis"] },
    { "chinese": "根据一次测验来预测结果可靠吗？", "english": "Is it safe to predict the result on the basis of one test?", "type": "句子", "keyWords": ["basis"] },
    { "chinese": "n.（C）篮子；笼，篓，筐", "english": "basket", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）篮球（U）篮球运动", "english": "basketball", "type": "单词", "keyWords": [] },
    { "chinese": "v. 打，击；击球 n.（C）蝙蝠；（棒球等的）球棒，（乒乓球、网球等的）球拍", "english": "bat", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）洗澡；浴缸；澡盆；浴室", "english": "bath", "type": "单词", "keyWords": [] },
    { "chinese": "日光浴", "english": "sun bath", "type": "短语", "keyWords": ["bath"] },
    { "chinese": "vi. 游泳；洗澡 v. 把..浸泡在液体中；使沐浴", "english": "bathe", "type": "单词", "keyWords": [] },
    { "chinese": "他满脸是汗/泪流满面。", "english": "His face was bathed in sweat/ tears.", "type": "句子", "keyWords": ["bathe"] },
    { "chinese": "沐浴在日光中", "english": "be bathed in the sun", "type": "短语", "keyWords": ["bathe"] },
    { "chinese": "游泳衣/帽", "english": "bathing suit/ dress/ cap", "type": "短语", "keyWords": ["bathe"] },
    { "chinese": "n.（C）浴室；盥洗室", "english": "bathroom", "type": "单词", "keyWords": [] },
    { "chinese": "v. 连续地猛打/捶/捣", "english": "batter", "type": "单词", "keyWords": [] },
    { "chinese": "严重撞坏了的汽车", "english": "a badly battered car", "type": "短语", "keyWords": ["batter"] },
    { "chinese": "n.（C）电池（组）", "english": "battery", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）战役，战斗，搏斗 v. 和..作战，和...斗争", "english": "battle", "type": "单词", "keyWords": [] },
    { "chinese": "战舰", "english": "battle ship", "type": "短语", "keyWords": ["battle"] },
    { "chinese": "战场", "english": "battle field", "type": "短语", "keyWords": ["battle"] },
    { "chinese": "争取平等权利/反对污染的斗争", "english": "a battle for equal rights/ against pollution", "type": "短语", "keyWords": ["battle"] },
    { "chinese": "n.（C）湾（比gulf小），海湾（常为河流的出海口）", "english": "bay", "type": "单词", "keyWords": [] },
    { "chinese": "公元前（=Before Christ的缩写）", "english": "B.C.=BC", "type": "短语", "keyWords": [] },
    { "chinese": "公元前44年", "english": "44 BC", "type": "短语", "keyWords": [] },
    { "chinese": "v. 是", "english": "be", "type": "单词", "keyWords": [] },
    { "chinese": "以...而出名", "english": "be famous for", "type": "短语", "keyWords": ["be"] },
    { "chinese": "对...满意", "english": "be pleased with", "type": "短语", "keyWords": ["be"] },
    { "chinese": "习惯于", "english": "be used/ accustomed to", "type": "短语", "keyWords": ["be"] },
    { "chinese": "目前", "english": "for the time being", "type": "短语", "keyWords": ["be"] },
    { "chinese": "将要，应该（表示约定、计划、职责、义务、愿望、可能、命运等）", "english": "be to do sth.", "type": "短语", "keyWords": ["be"] },
    { "chinese": "新书即将出版。", "english": "The new book is to come.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "他们预定在五月结婚。", "english": "They are to be married in May.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "你不该做那件事。（相当于must/ have to/ should）", "english": "You are not to do that.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "听不到任何声音。（相当于can/ may ）", "english": "Not a sound was to be heard.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "他此后就再没有和妻子见面了。（多用过去式）", "english": "He was never to see his wife again.", "type": "句子", "keyWords": ["be"] },
    { "chinese": "如果要出席宴会，你会穿什么？", "english": "If you are to attend the banquet, what will you wear?", "type": "句子", "keyWords": ["be"] },
    { "chinese": "n.（C）海滨；海滩；湖滨；江滨", "english": "beach", "type": "单词", "keyWords": [] },
    { "chinese": "海水浴场", "english": "a bathing beach", "type": "短语", "keyWords": ["beach"] },
    { "chinese": "在海滩上", "english": "on the beach", "type": "短语", "keyWords": ["beach"] },
    { "chinese": "n.（C）豆；蚕豆；菜豆属植物", "english": "bean", "type": "单词", "keyWords": [] },
    { "chinese": "刀豆", "english": "sword bean", "type": "短语", "keyWords": ["bean"] },
    { "chinese": "豇豆", "english": "string bean", "type": "短语", "keyWords": ["bean"] },
    { "chinese": "大豆", "english": "soy(a) bean", "type": "短语", "keyWords": ["bean"] },
    { "chinese": "n.（U）豆腐", "english": "bean curd", "type": "短语", "keyWords": ["bean"] },
    { "chinese": "n.（C）熊 vt.（bore, bore）忍受；标有，刻有；承受；怀有；（bore, born）生育", "english": "bear", "type": "单词", "keyWords": [] },
    { "chinese": "a. 难堪的，不能忍受的", "english": "unbearable", "type": "单词", "keyWords": ["bear"] },
    { "chinese": "我受不了了。", "english": "This is more than I can bear.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "这布料很耐洗。", "english": "This cloth will bear washing.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "她脸上有泪痕。", "english": "Her face bears the marks/ signs of tears.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "这封信没注明日期。", "english": "The letter bears no date.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "这棵树不结果。", "english": "This tree has borne no fruit.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "承受上面楼层的重量", "english": "bear the weight of the upper floors", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "我心里谁也不恨。", "english": "I bear no hatred towards anybody./I bear hatred against no man.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "承担...的费用/责任", "english": "bear the cost of/ responsibility for...", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "你须负起养育孩子的责任。", "english": "You have to bear the responsibility for bringing up your child.", "type": "句子", "keyWords": ["bear"] },
    { "chinese": "受不了", "english": "can't bear (sb.) doing sth.", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "生来平等", "english": "be born equal", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "牢记...", "english": "bear/ keep sth. in mind; bear/ keep in mind that...", "type": "短语", "keyWords": ["bear"] },
    { "chinese": "n.（C）胡须", "english": "beard", "type": "单词", "keyWords": [] },
    { "chinese": "下巴上留着胡子", "english": "wear/ grow a beard", "type": "短语", "keyWords": ["beard"] },
    { "chinese": "有胡须的人", "english": "a bearded man", "type": "短语", "keyWords": ["beard"] },
    { "chinese": "n.（C）野兽；走兽；*凶残的人；举止粗野的人", "english": "beast", "type": "单词", "keyWords": [] },
    { "chinese": "v. 连续打，击；打败 vi.（心脏）跳动；连打 n.（C）跳动；（音乐）拍子，节拍", "english": "beat", "type": "单词", "keyWords": [] },
    { "chinese": "把他打晕", "english": "beat him unconscious", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "击鼓", "english": "beat a drum", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "把人打得青一块紫一块", "english": "beat a man black and blue", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "在象棋上打败某人", "english": "beat sb. at chess", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "波浪拍岸。", "english": "The waves were beating against the shore.", "type": "句子", "keyWords": ["beat"] },
    { "chinese": "拨打草丛搜索猎物；旁敲侧击地刺探人意", "english": "beat about the bush", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "狠狠打了他一顿", "english": "give him a good beating", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "用脚打拍子", "english": "beat time with his foot", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "被打了一顿", "english": "get a beating", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "走成一条路", "english": "beat a path", "type": "短语", "keyWords": ["beat"] },
    { "chinese": "a. 美丽的；出色的，极好的", "english": "beautiful", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 美丽地；出色地；完美地", "english": "beautifully", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）美丽（C）美人；美景", "english": "beauty", "type": "单词", "keyWords": [] },
    { "chinese": "美貌只是外表。/人不可以貌相。", "english": "Beauty is but skin-deep.", "type": "句子", "keyWords": ["beauty"] },
    { "chinese": "v. 美化", "english": "beautify", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）美化；装饰", "english": "beautification", "type": "单词", "keyWords": [] },
    { "chinese": "conj. 因为", "english": "because", "type": "单词", "keyWords": [] },
    { "chinese": "因为，由于", "english": "because of", "type": "短语", "keyWords": ["because"] },
    { "chinese": "是因为·..才...", "english": "It is because..that...", "type": "短语", "keyWords": ["because"] },
    { "chinese": "不因...便...", "english": "not...because...", "type": "短语", "keyWords": ["because"] },
    { "chinese": "他并不是因为受到邀请才来的。", "english": "He didn't come because he was invited.", "type": "句子", "keyWords": ["because"] },
    { "chinese": "vi. 变成，开始变得", "english": "become", "type": "单词", "keyWords": [] },
    { "chinese": "发生；降临（近happen to）", "english": "become of", "type": "短语", "keyWords": ["become"] },
    { "chinese": "他/他的书怎么了？他/他的书下落如何？", "english": "What has become of him/his book?", "type": "句子", "keyWords": ["become"] },
    { "chinese": "n.（C）床；*河/海床；地基", "english": "bed", "type": "单词", "keyWords": [] },
    { "chinese": "单/双人床", "english": "a single/ double bed", "type": "短语", "keyWords": ["bed"] },
    { "chinese": "收拾床铺；铺床", "english": "make the bed", "type": "短语", "keyWords": ["bed"] },
    { "chinese": "让（孩子等）睡觉", "english": "put (the child) to bed", "type": "短语", "keyWords": ["bed"] },
    { "chinese": "花坛/海床", "english": "flower/sea bed", "type": "短语", "keyWords": ["bed"] },
    { "chinese": "n.（C）床上用品", "english": "bedding", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）卧室", "english": "bedroom", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）就寝时间 a. 适用于临睡前的", "english": "bedtime", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）蜜蜂", "english": "bee", "type": "单词", "keyWords": [] },
    { "chinese": "n.（多用作不可数）牛肉", "english": "beef", "type": "单词", "keyWords": [] },
    { "chinese": "n.（U）啤酒（C）某种啤酒；一杯或一瓶啤酒", "english": "beer", "type": "单词", "keyWords": [] },
    { "chinese": "两杯啤酒", "english": "two beers=two glasses of beer", "type": "短语", "keyWords": ["beer"] },
    { "chinese": "prep. 在...以前；当着..的面 conj. 在...之前 ad. 在前，以前", "english": "before", "type": "单词", "keyWords": [] },
    { "chinese": "我还没来得及插话他就冲了出去。（不等...就....）", "english": "Before I could get in a word, he had rushed out.", "type": "句子", "keyWords": ["before"] },
    { "chinese": "还要过很长时间我们才能再见面。", "english": "It'll be a long time before we meet again.", "type": "句子", "keyWords": ["before"] },
    { "chinese": '不久就...（对比It is...since+过去式，"...已发生了一段时间")', "english": "It wasn't long before...", "type": "短语", "keyWords": ["before"] },
    { "chinese": "好久以前", "english": "long before/ ago", "type": "短语", "keyWords": ["before"] },
    { "chinese": "不久", "english": "before long", "type": "短语", "keyWords": ["before"] },
    { "chinese": "当着某人的面", "english": "before sb.'s very eyes", "type": "短语", "keyWords": ["before"] },
    { "chinese": "前天晚上", "english": "the night before last", "type": "短语", "keyWords": ["before"] },
    { "chinese": "本末倒置。", "english": "Put the cart before the horse.", "type": "句子", "keyWords": ["before"] },
    { "chinese": "骄者必败。", "english": "Pride goes before a fall.", "type": "句子", "keyWords": ["before"] },
    { "chinese": "三思而后行。", "english": "Look before you leap.", "type": "句子", "keyWords": ["before"] },
    { "chinese": "ad. 事先，预先（近ahead of time, in advance）", "english": "beforehand", "type": "单词", "keyWords": [] },
    { "chinese": "vt./vi. 乞求；恳求", "english": "beg", "type": "单词", "keyWords": [] },
    { "chinese": "n.（C）乞丐（比较liar, scholar, burglar）", "english": "beggar", "type": "单词", "keyWords": [] },
    { "chinese": "讨钱", "english": "beg (sb.) for money", "type": "短语", "keyWords": ["beg"] },
    { "chinese": "恳求某人做某事", "english": "beg sb. to do sth.", "type": "短语", "keyWords": ["beg"] },
    { "chinese": "（对不起）请再说一遍=pardon (me)", "english": "beg your pardon", "type": "短语", "keyWords": ["beg"] },
    { "chinese": "v. 开始", "english": "begin", "type": "单词", "keyWords": [] }
];
