const qgl181_195 = [
    { "chinese": "a.中立的;不确定的", "english": "neutral", "type": "单词", "keyWords": [] },
    { "chinese": "中立国", "english": "a neutral nation", "type": "短语", "keyWords": ["neutral"] },
    { "chinese": "保持中立", "english": "be/remain neutral", "type": "短语", "keyWords": ["neutral"] },
    { "chinese": "ad.永不;从来没有", "english": "never", "type": "单词", "keyWords": [] },
    { "chinese": "a.永远不会遗忘的", "english": "never-to-be-forgotten", "type": "单词", "keyWords": [] },
    { "chinese": "ad.不过;仍然;然而", "english": "nevertheless", "type": "单词", "keyWords": [] },
    { "chinese": "a.新的", "english": "new", "type": "单词", "keyWords": [] },
    { "chinese": "在元旦", "english": "on New Year's Day", "type": "短语", "keyWords": ["new"] },
    { "chinese": "在除夕", "english": "on New Year's Eve", "type": "短语", "keyWords": ["new"] },
    { "chinese": "对(工作)不熟悉", "english": "be new to (the job)", "type": "短语", "keyWords": ["new"] },
    { "chinese": "新生的(婴儿)", "english": "new-born (baby)", "type": "短语", "keyWords": ["new"] },
    { "chinese": "n.[C]新来的人", "english": "newcomer", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]新闻;消息", "english": "news", "type": "单词", "keyWords": [] },
    { "chinese": "重要新闻,头版新闻", "english": "front-page news", "type": "短语", "keyWords": ["news"] },
    { "chinese": "向某人透露消息,向某人说出实情", "english": "break the news to sb.", "type": "短语", "keyWords": ["news"] },
    { "chinese": "好事不出门,恶事传千里", "english": "Bad news travels quickly.", "type": "句子", "keyWords": ["news"] },
    { "chinese": "没有消息就是好消息", "english": "No news is good news.", "type": "句子", "keyWords": ["news"] },
    { "chinese": "n.[C]报刊经销人", "english": "newsagent", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]报纸", "english": "newspaper", "type": "单词", "keyWords": [] },
    { "chinese": "a.紧邻的;紧接在后的,下一个的;其次的ad.下一次;其次", "english": "next", "type": "单词", "keyWords": [] },
    { "chinese": "邻居", "english": "a neighbor next door = a next-door neighbor", "type": "短语", "keyWords": ["next"] },
    { "chinese": "隔壁第二家", "english": "next door but one", "type": "短语", "keyWords": ["next"] },
    { "chinese": "住隔壁", "english": "live next door", "type": "短语", "keyWords": ["next"] },
    { "chinese": "与······相邻,贴近;仅次于;几乎", "english": "next to", "type": "短语", "keyWords": ["next"] },
    { "chinese": "几乎不可能/几乎等于没有", "english": "next to impossible/nothing/none", "type": "短语", "keyWords": ["next"] },
    { "chinese": "a.美好的;好的;使人高兴的", "english": "nice", "type": "单词", "keyWords": [] },
    { "chinese": "ad.令人满意地;令人愉快地;很好地", "english": "nicely", "type": "单词", "keyWords": [] },
    { "chinese": "好看的", "english": "nice-looking", "type": "短语", "keyWords": ["nice"] },
    { "chinese": "非常(凉快)", "english": "nice and (cool)", "type": "短语", "keyWords": ["nice"] },
    { "chinese": "n.[C]浑号,绰号;昵称", "english": "nickname", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]侄女;外甥女", "english": "niece", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]夜晚", "english": "night", "type": "单词", "keyWords": [] },
    { "chinese": "夜总会", "english": "nightclub", "type": "单词", "keyWords": [] },
    { "chinese": "梦魇,噩梦", "english": "nightmare", "type": "单词", "keyWords": [] },
    { "chinese": "在一个雨夜", "english": "on a rainy night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "在深夜", "english": "late at night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "一夜未眠", "english": "have a restless night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "走夜路", "english": "travel by night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "夜以继日地工作", "english": "work day and night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "漆黑", "english": "as black as night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "讨论到深夜", "english": "discuss into the night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "在夜里,晚上", "english": "at night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "消逝在夜色中", "english": "disappear into the night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "一夜又一夜地;一连好几夜地", "english": "night after night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "从早到晚地工作", "english": "work from morning to night", "type": "短语", "keyWords": ["night"] },
    { "chinese": "若要人不知,除非己莫为", "english": "What is done by night appears by day.", "type": "句子", "keyWords": ["night"] },
    { "chinese": "num.九十", "english": "ninety", "type": "单词", "keyWords": [] },
    { "chinese": "num.第九十;九十分之一", "english": "ninetieth", "type": "单词", "keyWords": [] },
    { "chinese": "num.第九;九分之一", "english": "ninth", "type": "单词", "keyWords": [] },
    { "chinese": "ad.不,不是;毫不,根本不(用于比较级前)a.没有的;远非的;不许的,禁止的n.不,没有;否定,拒绝;反对", "english": "no", "type": "单词", "keyWords": [] },
    { "chinese": "他一点也没有感到好转", "english": "He is feeling no better.", "type": "句子", "keyWords": ["no"] },
    { "chinese": "汤姆和你一样穷", "english": "Tom is no richer than you are. (=Tom is as poor as you are.)", "type": "句子", "keyWords": ["no"] },
    { "chinese": "他很精明", "english": "He is no fool.", "type": "句子", "keyWords": ["no"] },
    { "chinese": "他根本不是(一个)学者", "english": "He is no scholar.", "type": "句子", "keyWords": ["no"] },
    { "chinese": "他不是一个学者", "english": "He is not a scholar.", "type": "句子", "keyWords": ["no"] },
    { "chinese": "不可能/简直没办法知道/说清······", "english": "There's no knowing/saying/telling...", "type": "句子", "keyWords": ["no"] },
    { "chinese": "他这人很怪,人们无法知道他下一步要干什么", "english": "He is such a strange person that there's no knowing what he'll do next.", "type": "句子", "keyWords": ["no"] },
    { "chinese": "不是别的,正是", "english": "no other than", "type": "短语", "keyWords": ["no"] },
    { "chinese": "这位不是别人,正是我的老朋友约翰", "english": "This is no other than my old friend, John.", "type": "句子", "keyWords": ["no"] },
    { "chinese": "只有在英国人们才能在一天之内经历到四个季节", "english": "In no country other than England can one experience four seasons in a single day.", "type": "句子", "keyWords": ["no"] },
    { "chinese": "a.高尚的;宏伟的;贵族的,显贵的n.[C]贵族;出身高贵的人", "english": "noble", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]高贵,高尚", "english": "nobility", "type": "单词", "keyWords": [] },
    { "chinese": "高尚的;气量大的", "english": "noble-minded", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]贵族", "english": "nobleman", "type": "单词", "keyWords": [] },
    { "chinese": "pron.没有人n.[C]小人物,无名小卒", "english": "nobody", "type": "单词", "keyWords": [] },
    { "chinese": "v.点(头);点头表示v.点头同意(或示意);打盹n.[C]点头同意(或招呼);打盹,瞌睡", "english": "nod", "type": "单词", "keyWords": [] },
    { "chinese": "他点头表示同意", "english": "He nodded his agreement.", "type": "句子", "keyWords": ["nod"] },
    { "chinese": "向某人点头", "english": "nod to/at sb.", "type": "短语", "keyWords": ["nod"] },
    { "chinese": "我在会上打瞌睡了", "english": "I nodded off at the meeting.", "type": "句子", "keyWords": ["nod"] },
    { "chinese": "树在风中摇曳", "english": "Trees nod in the wind.", "type": "句子", "keyWords": ["nod"] },
    { "chinese": "他点头向我打招呼", "english": "He greeted me with a nod.", "type": "句子", "keyWords": ["nod"] },
    { "chinese": "n.[C](U]噪声;杂声;不正常的声音", "english": "noise", "type": "单词", "keyWords": [] },
    { "chinese": "a.嘈杂的;喧闹的", "english": "noisy", "type": "单词", "keyWords": [] },
    { "chinese": "吵吵嚷嚷", "english": "make a/much noise", "type": "短语", "keyWords": ["noise"] },
    { "chinese": "表示“非,无,不(是)”", "english": "non-", "type": "前缀", "keyWords": [] },
    { "chinese": "pron.没有人;没有任何东西;没有一点儿", "english": "none", "type": "单词", "keyWords": [] },
    { "chinese": "有些错误我们任何人都不能避免", "english": "There are faults from which none of us is/are free.", "type": "句子", "keyWords": ["none"] },
    { "chinese": "拒绝参加;不接受", "english": "have none of", "type": "短语", "keyWords": ["none"] },
    { "chinese": "我才不接受你那愚蠢的意见", "english": "I'll have none of your stupid ideas!", "type": "句子", "keyWords": ["none"] },
    { "chinese": "只有", "english": "none but", "type": "短语", "keyWords": ["none"] },
    { "chinese": "他们只选最好的", "english": "They choose none but the best.", "type": "句子", "keyWords": ["none"] },
    { "chinese": "不是别的,正是(表示惊奇)", "english": "none other than", "type": "短语", "keyWords": ["none"] },
    { "chinese": "是汤姆!我们以为你还在非洲", "english": "It's none other than Tom! We thought you were in Africa!", "type": "句子", "keyWords": ["none"] },
    { "chinese": "天真的许仙,聪明与能言善道的许仕林都是由叶童这个具有天赋的女演员所扮演的", "english": "The naive Xu Xian and the clever and witty Xu Shilin are both played by none other than the gifted actress Cecilia Yip.", "type": "句子", "keyWords": ["none"] },
    { "chinese": "n.[U]非小说类(写实)文学作品", "english": "nonfiction", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]胡说,废话", "english": "nonsense", "type": "单词", "keyWords": [] },
    { "chinese": "胡说八道", "english": "talk nonsense", "type": "短语", "keyWords": ["nonsense"] },
    { "chinese": "别胡说", "english": "None of your nonsense!", "type": "句子", "keyWords": ["nonsense"] },
    { "chinese": "a.中途不停的;(列车、飞机等)直达的", "english": "non-stop", "type": "单词", "keyWords": [] },
    { "chinese": "直达飞行/航班", "english": "a non-stop flight", "type": "短语", "keyWords": ["non-stop"] },
    { "chinese": "n.[C](常pl.)面条", "english": "noodle", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]中午", "english": "noon", "type": "单词", "keyWords": [] },
    { "chinese": "在中午", "english": "at noon", "type": "短语", "keyWords": ["noon"] },
    { "chinese": "conj.,ad.也不;也没有", "english": "nor", "type": "单词", "keyWords": [] },
    { "chinese": "a.正常的;正规的;标准的n.[U]正常状态", "english": "normal", "type": "单词", "keyWords": [] },
    { "chinese": "ad.正常地;正规地", "english": "normally", "type": "单词", "keyWords": [] },
    { "chinese": "a.反常的,变态的", "english": "abnormal", "type": "单词", "keyWords": [] },
    { "chinese": "正常体温", "english": "normal body temperature", "type": "短语", "keyWords": ["normal"] },
    { "chinese": "师范教育", "english": "normal education", "type": "短语", "keyWords": ["normal"] },
    { "chinese": "标准以上/下", "english": "above/below normal", "type": "短语", "keyWords": ["normal"] },
    { "chinese": "水灾过后一切恢复了正常", "english": "Everything returned to normal after the flood.", "type": "句子", "keyWords": ["normal"] },
    { "chinese": "n.(the)北方a.北;北方的ad.在北方;向北方", "english": "north", "type": "单词", "keyWords": [] },
    { "chinese": "北风", "english": "a north wind", "type": "短语", "keyWords": ["north"] },
    { "chinese": "北极", "english": "the North Pole", "type": "短语", "keyWords": ["north"] },
    { "chinese": "向北航行", "english": "sail north", "type": "短语", "keyWords": ["north"] },
    { "chinese": "在······北(不接壤)", "english": "to the north of...", "type": "短语", "keyWords": ["north"] },
    { "chinese": "在······的北侧/北面(接壤)", "english": "on the north of...", "type": "短语", "keyWords": ["north"] },
    { "chinese": "在北京以北88千米处", "english": "be 88km north of Beijing", "type": "短语", "keyWords": ["north"] },
    { "chinese": "苏州以北9千米处有······(倒装)", "english": "9 km north of Suzhou lies a...", "type": "句子", "keyWords": ["north"] },
    { "chinese": "n.(the)东北；东北方；a.东北的；东北方(的)；ad.在东北方；向东北方", "english": "northeast", "type": "单词", "keyWords": [] },
    { "chinese": "a.北方的；北部的；在北方的；向北方的；来自北方的", "english": "northern", "type": "单词", "keyWords": [] },
    { "chinese": "n.(the)西北；西北方；a.西北的；西北方的；ad.在西北方；向西北方", "english": "northwest", "type": "单词", "keyWords": [] },
    { "chinese": "a.向北方的；ad.向北方", "english": "northward", "type": "单词", "keyWords": [] },
    { "chinese": "ad.向北方", "english": "northwards", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]鼻子；v.闻出；探出(out)", "english": "nose", "type": "单词", "keyWords": [] },
    { "chinese": "控制某人，牵着某人的鼻子走", "english": "lead sb. by the nose", "type": "短语", "keyWords": ["nose"] },
    { "chinese": "不要干涉我的事", "english": "Keep your nose out of my business.", "type": "句子", "keyWords": ["nose"] },
    { "chinese": "ad.不；没；不是(与each、both、all、many、much、always、totally、completely、everywhere等连用，表示部分否定)", "english": "not", "type": "单词", "keyWords": [] },
    { "chinese": "我并非他们两个都认识。(只认识其中之一)", "english": "I don't know both of them.", "type": "句子", "keyWords": ["not"] },
    { "chinese": "他会来吗？可能不会。", "english": "Is he coming? Perhaps not.", "type": "句子", "keyWords": ["not"] },
    { "chinese": "一个也不(全部否定)", "english": "not a = not one", "type": "短语", "keyWords": ["not"] },
    { "chinese": "车祸中无人死亡", "english": "Not a man was killed in the accident.", "type": "句子", "keyWords": ["not"] },
    { "chinese": "不是……而是……", "english": "not...but...", "type": "短语", "keyWords": ["not"] },
    { "chinese": "重要的是你的表现而不是你的话", "english": "It is not your words but your performances that count.", "type": "句子", "keyWords": ["not"] },
    { "chinese": "不是(因为)……而是(因为)……", "english": "not that...but that...", "type": "短语", "keyWords": ["not"] },
    { "chinese": "不但……而且……(前半部分可以使用部分倒装形式)", "english": "not only...but also...", "type": "短语", "keyWords": ["not"] },
    { "chinese": "不少", "english": "not a few", "type": "短语", "keyWords": ["not"] },
    { "chinese": "不少", "english": "not a little", "type": "短语", "keyWords": ["not"] },
    { "chinese": "n.[C]笔记；便条；纸币；注解，注释；音符；语调；v.记录，记下；注意(到)；表明", "english": "note", "type": "单词", "keyWords": [] },
    { "chinese": "把……记录下来，把……做成笔记或札记", "english": "take/make a note/notes of = note...down", "type": "短语", "keyWords": ["note"] },
    { "chinese": "请注意账单必须在10天之内付清", "english": "Please note that this bill most be paid within 10 days.", "type": "句子", "keyWords": ["note"] },
    { "chinese": "我们注意到随着我们往里面加更多的料，其温度不断上升", "english": "It was noted that the temperature rose as we added more into it.", "type": "句子", "keyWords": ["note"] },
    { "chinese": "n.[C]笔记本", "english": "notebook", "type": "单词", "keyWords": [] },
    { "chinese": "pron.没有东西；n.[C]无关紧要之事；无足轻重的人；[数]零", "english": "nothing", "type": "单词", "keyWords": [] },
    { "chinese": "免费；无缘无故地；白白地", "english": "for nothing", "type": "短语", "keyWords": ["nothing"] },
    { "chinese": "他工作没有报酬", "english": "He worked for nothing.", "type": "句子", "keyWords": ["nothing"] },
    { "chinese": "他们无缘无故地争吵了起来", "english": "They quarreled for nothing.", "type": "句子", "keyWords": ["nothing"] },
    { "chinese": "除了……以外什么也不；只有，不过", "english": "nothing but", "type": "短语", "keyWords": ["nothing"] },
    { "chinese": "他只吃了色拉", "english": "He ate nothing but salad.", "type": "句子", "keyWords": ["nothing"] },
    { "chinese": "不把……放在心里；觉得……没什么了不起", "english": "think nothing of", "type": "短语", "keyWords": ["nothing"] },
    { "chinese": "与……无关/不往来", "english": "have nothing to do with...", "type": "短语", "keyWords": ["nothing"] },
    { "chinese": "这没什么了不起", "english": "It's nothing serious.", "type": "句子", "keyWords": ["nothing"] },
    { "chinese": "只不过", "english": "nothing more than", "type": "短语", "keyWords": ["nothing"] },
    { "chinese": "爆炸只不过是非常急速的燃烧而已", "english": "An explosion is nothing more than a very rapid burning.", "type": "句子", "keyWords": ["nothing"] },
    { "chinese": "(人)所理解赞赏；引不起(某人的)兴趣", "english": "be nothing to sb.", "type": "短语", "keyWords": ["nothing"] },
    { "chinese": "他是个货真价实的小人物", "english": "He is a real nothing.", "type": "句子", "keyWords": ["nothing"] },
    { "chinese": "差不多什么都没有", "english": "next to nothing", "type": "短语", "keyWords": ["nothing"] },
    { "chinese": "我对文学几乎一无所知", "english": "I know next to nothing about literature.", "type": "句子", "keyWords": ["nothing"] },
    { "chinese": "丝毫不像；一点也不", "english": "nothing like", "type": "短语", "keyWords": ["nothing"] },
    { "chinese": "她一点也不像她母亲", "english": "She is nothing like her mother.", "type": "句子", "keyWords": ["nothing"] },
    { "chinese": "他一点也算不上是个诗人", "english": "He is nothing of a poet.", "type": "句子", "keyWords": ["nothing"] },
    { "chinese": "n.[U]注意；关注；正式警告或告知；n.[C](书面)通知；布告，启事；vt.注意到；关注；通知；vi.(引起)注意；adj. noticeable显而易见的；值得注意的", "english": "notice", "type": "单词", "keyWords": [] },
    { "chinese": "(有意)注意", "english": "take notice of", "type": "短语", "keyWords": ["notice"] },
    { "chinese": "布告栏", "english": "notice board", "type": "短语", "keyWords": ["notice"] },
    { "chinese": "没注意到(逃过某人的注意；被某人疏忽)", "english": "escape one's notice", "type": "短语", "keyWords": ["notice"] },
    { "chinese": "不注意/理会；不采取应有措施", "english": "take no notice of", "type": "短语", "keyWords": ["notice"] },
    { "chinese": "不预先通知；不另行通知；擅自", "english": "without notice", "type": "短语", "keyWords": ["notice"] },
    { "chinese": "说明书如有变动不另行通知", "english": "Specifications are subject to change without notice.", "type": "句子", "keyWords": ["notice"] },
    { "chinese": "通知，通告；预先通知(解雇、辞职等)", "english": "give notice", "type": "短语", "keyWords": ["notice"] },
    { "chinese": "通知雇员一个月后离职", "english": "give one's employee a month's notice", "type": "句子", "keyWords": ["notice"] },
    { "chinese": "使某人注意到某事", "english": "bring sth. to one's notice (draw one's attention to sth.)", "type": "短语", "keyWords": ["notice"] },
    { "chinese": "注意到某人做了/正在做某事", "english": "notice sb. do/doing sth.", "type": "短语", "keyWords": ["notice"] },
    { "chinese": "n.[C]名词；名词词性", "english": "noun", "type": "单词", "keyWords": [] },
    { "chinese": "vt.滋养，使健壮；提供营养", "english": "nourish", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]食物，营养品(=nourishing food)", "english": "nourishment", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](长篇)小说；a.新奇的，新颖的", "english": "novel", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](长篇)小说家", "english": "novelist", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]十一月(略作Nov.)", "english": "November", "type": "单词", "keyWords": [] },
    { "chinese": "ad.现今，现在；立刻，马上；conj.既然(now that)", "english": "now", "type": "单词", "keyWords": [] },
    { "chinese": "立刻，马上", "english": "right now", "type": "短语", "keyWords": ["now"] },
    { "chinese": "既然，由于", "english": "now that", "type": "短语", "keyWords": ["now"] },
    { "chinese": "刚才，方才；眼下，现在；马上", "english": "just now", "type": "短语", "keyWords": ["now"] },
    { "chinese": "从现在起，今后", "english": "from now on", "type": "短语", "keyWords": ["now"] },
    { "chinese": "到现在为止，迄今", "english": "up to/till now (by now)", "type": "短语", "keyWords": ["now"] },
    { "chinese": "不时，时而；偶尔", "english": "now and then (近now and again, once in a while, at times, on occasions, from time to time)", "type": "短语", "keyWords": ["now"] },
    { "chinese": "机不可失，时不再来！", "english": "Now or never!", "type": "句子", "keyWords": ["now"] },
    { "chinese": "现在该你啦!(全倒装结构)", "english": "Now comes your turn!", "type": "句子", "keyWords": ["now"] },
    { "chinese": "现在我们谈价格问题", "english": "Now comes the question of price.", "type": "句子", "keyWords": ["now"] },
    { "chinese": "ad.现今；现在(常用于将现在的风俗习惯同过去相比较时)", "english": "nowadays", "type": "单词", "keyWords": [] },
    { "chinese": "ad.任何地方都不", "english": "nowhere", "type": "单词", "keyWords": [] },
    { "chinese": "任何地方都见不着他", "english": "He's nowhere to be seen.", "type": "句子", "keyWords": ["nowhere"] },
    { "chinese": "不知道从哪里冒出来；突然出现", "english": "come from/out of nowhere", "type": "短语", "keyWords": ["nowhere"] },
    { "chinese": "最后时刻突然出现一个个子很矮的人赢得了比赛的胜利", "english": "At the last moment, a short man appeared out of nowhere to win the race.", "type": "句子", "keyWords": ["nowhere"] },
    { "chinese": "一辆警车突然出现并把他拦住了", "english": "A police car appeared from nowhere and stopped him.", "type": "句子", "keyWords": ["nowhere"] },
    { "chinese": "一事无成，毫无进展", "english": "get nowhere", "type": "短语", "keyWords": ["nowhere"] },
    { "chinese": "那样做不会成功的。/那会使你一事无成", "english": "That will likely get you nowhere.", "type": "句子", "keyWords": ["nowhere"] },
    { "chinese": "a.核的；(使用)核能的；(拥有)核武器的；核心的", "english": "nuclear", "type": "单词", "keyWords": [] },
    { "chinese": "核武器", "english": "nuclear weapons", "type": "短语", "keyWords": ["nuclear"] },
    { "chinese": "(仅由父母及子女组成的)核心家庭", "english": "nuclear family", "type": "短语", "keyWords": ["nuclear"] },
    { "chinese": "无核的", "english": "nuclear-free", "type": "单词", "keyWords": ["nuclear"] },
    { "chinese": "核动力的", "english": "nuclear-driven/nuclear-powered", "type": "单词", "keyWords": ["nuclear"] },
    { "chinese": "n.[C]号码；数字；v.把……编号，给……标号码；把……算在内；数", "english": "number", "type": "单词", "keyWords": [] },
    { "chinese": "住在四川路85号", "english": "live at(No.)85, Sichuan Road", "type": "短语", "keyWords": ["number"] },
    { "chinese": "许多(后接可数名词复数)", "english": "a large/good number of", "type": "短语", "keyWords": ["number"] },
    { "chinese": "头等的，第一流的", "english": "number one (=No.1)", "type": "短语", "keyWords": ["number"] },
    { "chinese": "在数量上，在数字上；总共", "english": "in number", "type": "短语", "keyWords": ["number"] },
    { "chinese": "数量日益增加", "english": "increase in number day by day", "type": "短语", "keyWords": ["number"] },
    { "chinese": "大量，为数众多", "english": "in numbers", "type": "短语", "keyWords": ["number"] },
    { "chinese": "鸟儿一群群地聚在河边", "english": "Birds gather in large numbers beside the river.", "type": "句子", "keyWords": ["number"] },
    { "chinese": "编了号的公路", "english": "a numbered road", "type": "短语", "keyWords": ["number"] },
    { "chinese": "这本书的页码是从1编到268的", "english": "The pages of the book were numbered 1 to 268.", "type": "句子", "keyWords": ["number"] },
    { "chinese": "有两页编号都为25", "english": "There are two pages numbered 25.", "type": "句子", "keyWords": ["number"] },
    { "chinese": "偶/奇数", "english": "an even/odd number", "type": "短语", "keyWords": ["number"] },
    { "chinese": "他被列入失踪者的名单", "english": "He was numbered among the lost.", "type": "句子", "keyWords": ["number"] },
    { "chinese": "我们的日子屈指可数", "english": "Our days are numbered.", "type": "句子", "keyWords": ["number"] },
    { "chinese": "a.许多的(后接可数名词复数)", "english": "numerous", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]护士；保育员；v.护理，看护", "english": "nurse", "type": "单词", "keyWords": [] },
    { "chinese": "照顾病人", "english": "nurse a sick person", "type": "短语", "keyWords": ["nurse"] },
    { "chinese": "n.[C]托儿所；苗圃", "english": "nursery", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U] 护理专业；护士职责；看护；养育", "english": "nursing", "type": "单词", "keyWords": [] },
    { "chinese": "私人疗养所", "english": "nursing home", "type": "短语", "keyWords": ["nursing"] },
    { "chinese": "n.[C] 干果；坚果", "english": "nut", "type": "单词", "keyWords": [] },
    { "chinese": "是难题；是难事；是难对付的人", "english": "be a hard nut to crack", "type": "短语", "keyWords": ["nut"] },
    { "chinese": "n.[C] 营养物；滋养物；营养成分；a. 营养的", "english": "nutrient", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U] 营养；营养学", "english": "nutrition", "type": "单词", "keyWords": [] },
    { "chinese": "a. 富有营养的；滋养的", "english": "nutritious", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl. oases)(沙漠中)绿洲", "english": "oasis", "type": "单词", "keyWords": [] },
    { "chinese": "v.服从；听从", "english": "obey", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]服从；顺从", "english": "obedience", "type": "单词", "keyWords": [] },
    { "chinese": "服从命令", "english": "obey orders", "type": "短语", "keyWords": ["obey"] },
    { "chinese": "a.肥胖的，肥大的", "english": "obese", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]肥胖", "english": "obesity", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]物体；目标，宗旨；宾语", "english": "object", "type": "单词", "keyWords": [] },
    { "chinese": "vi.不赞成；反对；v.提······作为反对的理由", "english": "object", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]反对的理由；[U](C]反对", "english": "objection", "type": "单词", "keyWords": [] },
    { "chinese": "反对某人/(做)某事", "english": "raise an objection；object to sb./doing sth.", "type": "短语", "keyWords": ["object", "objection"] },
    { "chinese": "a.客观存在的；客观的(反subjective)；如实的；目的的，目标的；n.[C]目的；目标(辨析见aim)", "english": "objective", "type": "单词", "keyWords": [] },
    { "chinese": "(通过体力、法律、社会或道义)迫使；(使)感谢", "english": "oblige", "type": "单词", "keyWords": [] },
    { "chinese": "强迫某人做某事", "english": "oblige sb. to do sth. (force sb. to do sth.)；be obliged to do sth.", "type": "短语", "keyWords": ["oblige"] },
    { "chinese": "形势逼人，迫使我们进一步改革开放", "english": "Pressing circumstances oblige us to deepen the reform and open wider to the outside world.", "type": "句子", "keyWords": ["oblige"] },
    { "chinese": "发生了那样一次不愉快的争吵之后，他觉得必须离开那里了", "english": "He felt obliged to leave after such an unpleasant quarrel.", "type": "句子", "keyWords": ["oblige"] },
    { "chinese": "因某事感谢某人", "english": "be obliged to sb. for doing sth. = be grateful/thankful to sb. for doing sth.", "type": "短语", "keyWords": ["oblige"] },
    { "chinese": "我非常感谢你帮忙", "english": "I'm very much obliged to you for your help.", "type": "句子", "keyWords": ["oblige"] },
    { "chinese": "n.[C]义务", "english": "obligation", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](U]观察；观测；注意；监视；n.[U]观察力；n.[C]观察到的东西", "english": "observation", "type": "单词", "keyWords": [] },
    { "chinese": "v.观察；留心到；遵守；庆祝，过(节)(辨析见see)", "english": "observe", "type": "单词", "keyWords": [] },
    { "chinese": "我看见他出去了", "english": "I observed him going out.", "type": "句子", "keyWords": ["observe"] },
    { "chinese": "遵守规则/履行合同条款", "english": "observe a rule/the terms of a contract", "type": "短语", "keyWords": ["observe"] },
    { "chinese": "庆祝某人的生日", "english": "observe a person's birthday", "type": "短语", "keyWords": ["observe"] },
    { "chinese": "v.迷，使困扰", "english": "obsess", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](U]着迷(之事)", "english": "obsession", "type": "单词", "keyWords": [] },
    { "chinese": "被……缠住、迷住心窍(近be addicted to sth.)", "english": "be obsessed with...", "type": "短语", "keyWords": ["obsess"] },
    { "chinese": "n.[C]障碍(物)", "english": "obstacle", "type": "单词", "keyWords": [] },
    { "chinese": "(进步)的障碍", "english": "an obstacle to (progress)", "type": "短语", "keyWords": ["obstacle"] },
    { "chinese": "v.取得；获得(经过计划或努力成功地获得)", "english": "obtain", "type": "单词", "keyWords": [] },
    { "chinese": "a.可以得到的", "english": "obtainable", "type": "单词", "keyWords": [] },
    { "chinese": "a.明显的，显而易见的(近apparent, clear)", "english": "obvious", "type": "单词", "keyWords": [] },
    { "chinese": "ad.明显地，显然", "english": "obviously", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]场合；特殊时刻", "english": "occasion", "type": "单词", "keyWords": [] },
    { "chinese": "在重大场合/盛典时期", "english": "on great occasions", "type": "短语", "keyWords": ["occasion"] },
    { "chinese": "在······的时候", "english": "on the occasion of", "type": "短语", "keyWords": ["occasion"] },
    { "chinese": "他还曾着陆在一个废弃的停车场", "english": "On another occasion, he landed in a deserted car park.", "type": "句子", "keyWords": ["occasion"] },
    { "chinese": "a.偶尔的；不经常的", "english": "occasional", "type": "单词", "keyWords": [] },
    { "chinese": "ad.偶尔", "english": "occasionally", "type": "单词", "keyWords": [] },
    { "chinese": "偶尔去探望某人/游览某地", "english": "pay occasional visits to sb./a place", "type": "短语", "keyWords": ["occasional"] },
    { "chinese": "n.[C]工作；职业；n.[U]占领；占有", "english": "occupation", "type": "单词", "keyWords": [] },
    { "chinese": "v.占据；占有；占用(时间、空间等)；使忙碌；使从事", "english": "occupy", "type": "单词", "keyWords": [] },
    { "chinese": "占空间/占位置/占时间(近take up)", "english": "occupy space/a position/time", "type": "短语", "keyWords": ["occupy"] },
    { "chinese": "忙于做某事(近be engaged in doing sth.)", "english": "be occupied (in) doing sth./with doing sth.", "type": "短语", "keyWords": ["occupy"] },
    { "chinese": "v.(occurred)发生；被想起(to sb.)", "english": "occur", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](日常)发生的事；n.[U]发生", "english": "occurrence", "type": "单词", "keyWords": [] },
    { "chinese": "如果发生什么事情的话······", "english": "If anything should occur,...", "type": "句子", "keyWords": ["occur"] },
    { "chinese": "我万万没有想到", "english": "This idea never occurred to me(=struck me).", "type": "句子", "keyWords": ["occur"] },
    { "chinese": "某人突然想起什么", "english": "It occurs to sb. that.../to do sth.", "type": "短语", "keyWords": ["occur"] },
    { "chinese": "我突然想到他是在极力隐瞒什么", "english": "It occurred to me that he was trying to conceal something.", "type": "句子", "keyWords": ["occur"] },
    { "chinese": "我从没有想到过要占他的便宜", "english": "It never occurred to me to take advantage of him.", "type": "句子", "keyWords": ["occur"] },
    { "chinese": "n.[C]洋，海洋", "english": "ocean", "type": "单词", "keyWords": [] },
    { "chinese": "远洋货轮", "english": "ocean - going ships", "type": "短语", "keyWords": ["ocean"] },
    { "chinese": "n.[C]······点钟", "english": "o'clock", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]十月(略作Oct.)", "english": "October", "type": "单词", "keyWords": [] },
    { "chinese": "a.古怪的；奇特的；奇(数)；a.剩余的；······以上的(通常用于构成复合词)；单只的；临时的", "english": "odd", "type": "单词", "keyWords": [] },
    { "chinese": "三十多年", "english": "30 - odd years", "type": "短语", "keyWords": ["odd"] },
    { "chinese": "打零工", "english": "do odd jobs", "type": "短语", "keyWords": ["odd"] },
    { "chinese": "奇数", "english": "odd numbers", "type": "短语", "keyWords": ["odd"] },
    { "chinese": "off，adv.下(走)开；离开；隔开；(表示某事物)中断；不工作，休息；prep.离开", "english": "off", "type": "单词", "keyWords": [] },
    { "chinese": "休假一天", "english": "take/have a day off", "type": "短语", "keyWords": ["off"] },
    { "chinese": "沿海有无数岛屿", "english": "There are numerous islands off the coast.", "type": "句子", "keyWords": ["off"] },
    { "chinese": "经济宽裕/穷困，景况不佳(近better off, worse off)", "english": "(be) well/badly off", "type": "短语", "keyWords": ["off"] },
    { "chinese": "v.冒犯；得罪；vi.违反；offensive a.讨厌的；无礼的；攻击性的", "english": "offend", "type": "单词", "keyWords": [] },
    { "chinese": "犯法", "english": "offend (be against) the law", "type": "短语", "keyWords": ["offend"] },
    { "chinese": "一句冒犯性的话/刺鼻的气味", "english": "an offensive remark/smell", "type": "短语", "keyWords": ["offend"] },
    { "chinese": "他被我的话激怒了", "english": "He was offended by my remarks.", "type": "句子", "keyWords": ["offend"] },
    { "chinese": "n.[C]犯法(行为)；过错；讨厌的东西；n.[U]冒犯，得罪；过错", "english": "offence", "type": "单词", "keyWords": [] },
    { "chinese": "破坏(法律、风俗)", "english": "commit an offence against...", "type": "短语", "keyWords": ["offence"] },
    { "chinese": "看见这条狗就很讨厌", "english": "The dog is an offence to the eye.", "type": "句子", "keyWords": ["offence"] },
    { "chinese": "不触怒/冒犯人", "english": "without offence", "type": "短语", "keyWords": ["offence"] },
    { "chinese": "因······而生气，见怪", "english": "take offence at...", "type": "短语", "keyWords": ["offence"] },
    { "chinese": "(主动)给予；提供(辨析见afford)；提议；提出；开(价)；n.[C]提供；提议；开价，报价", "english": "offer", "type": "单词", "keyWords": [] },
    { "chinese": "提供某人某物；向某人开价或报价", "english": "offer sb. sth./offer sth. to sb.", "type": "短语", "keyWords": ["offer"] },
    { "chinese": "他出300美元向我买那台电视机", "english": "He offered me 300 dollars for that television.", "type": "句子", "keyWords": ["offer"] },
    { "chinese": "主动提议做某事(give无此用法)", "english": "offer to do sth.", "type": "短语", "keyWords": ["offer"] },
    { "chinese": "感谢你提供的帮助", "english": "Thank you for your offer of help.", "type": "句子", "keyWords": ["offer"] },
    { "chinese": "提供/得到/接受/拒绝······", "english": "make/receive/accept/decline an offer of sth.", "type": "短语", "keyWords": ["offer"] },
    { "chinese": "n.[C]办公室；处，局，所，办事处；[U]公职，职务", "english": "office", "type": "单词", "keyWords": [] },
    { "chinese": "办公时间", "english": "office hours", "type": "短语", "keyWords": ["office"] },
    { "chinese": "办公楼", "english": "office building", "type": "短语", "keyWords": ["office"] },
    { "chinese": "担任公职", "english": "hold office", "type": "短语", "keyWords": ["office"] },
    { "chinese": "就职", "english": "take office", "type": "短语", "keyWords": ["office"] },
    { "chinese": "总部，总行", "english": "head office", "type": "短语", "keyWords": ["office"] },
    { "chinese": "在位，当权/下野，不执政", "english": "in/out of office", "type": "短语", "keyWords": ["office"] },
    { "chinese": "n.[C]军官；警官", "english": "officer", "type": "单词", "keyWords": [] },
    { "chinese": "a.官方的；正式的；职务上的，公务的；n.[C](在公共职能部门中服务的)官员", "english": "official", "type": "单词", "keyWords": [] },
    { "chinese": "ad.常常", "english": "often", "type": "单词", "keyWords": [] },
    { "chinese": "在多数情况下；往往", "english": "more often than not", "type": "短语", "keyWords": ["often"] },
    { "chinese": "interj.哎呀", "english": "oh", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)油；燃料油；v.给(机器等)加油，使润滑；oily a.油状的；油多的；油腻的", "english": "oil", "type": "单词", "keyWords": [] },
    { "chinese": "据说那车需要每三个月上一次润滑油，你会记得按时去上油吗？", "english": "Supposedly, the car needs oiling every three months. How likely will you remember to do so?", "type": "句子", "keyWords": ["oil"] },
    { "chinese": "a./ad./interj.可以；行(=Okay/Okey)", "english": "O.K.", "type": "单词", "keyWords": [] },
    { "chinese": "a.旧的；旧时的；陈旧的；年老的；(指年龄)······岁的", "english": "old", "type": "单词", "keyWords": [] },
    { "chinese": "美好的往昔", "english": "good old days", "type": "短语", "keyWords": ["old"] },
    { "chinese": "a.奥林匹克运动会的", "english": "Olympic", "type": "单词", "keyWords": [] },
    { "chinese": "奥林匹克运动会", "english": "the Olympic Games", "type": "短语", "keyWords": ["Olympic"] },
    { "chinese": "n.[C](the)奥林匹克运动会", "english": "Olympics", "type": "单词", "keyWords": [] },
    { "chinese": "夏季奥运会和冬季奥运会都是每四年举行一次", "english": "Both the Summer and Winter Olympics are held every four years.", "type": "句子", "keyWords": ["Olympics"] },
    { "chinese": "v.省略；遗漏", "english": "omit", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U] 省略；遗漏；n.[C] 省略 / 遗漏的东西", "english": "omission", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 在… 上；在… 时间；关于；以… 方式，靠；一…(就…); 是… 的成员；a. 处于或进入执行、运行或工作中 (反 off);ad. 继续；向前", "english": "on", "type": "单词", "keyWords": [] },
    { "chinese": "仰卧 / 俯卧", "english": "lie on one's back/stomach", "type": "短语", "keyWords": ["on"] },
    { "chinese": "倒立", "english": "stand on his head", "type": "短语", "keyWords": ["on"] },
    { "chinese": "依靠… 变得富有 (近 live/feed/rely/count/calculate/depend on)", "english": "grow rich on...", "type": "短语", "keyWords": ["on"] },
    { "chinese": "无间断地；连续不断地", "english": "(talk...) on and on", "type": "短语", "keyWords": ["on"] },
    { "chinese": "担任委员 / 是《中国日报》编辑 / 是中国队队员 / 是董事", "english": "be on the committee/China Daily/the Chinese team/the Board", "type": "短语", "keyWords": ["on"] },
    { "chinese": "伦敦在泰晤士河边", "english": "London lies on the River Thames.", "type": "句子", "keyWords": ["on"] },
    { "chinese": "电视机是开着的", "english": "The television is on.", "type": "句子", "keyWords": ["on"] },
    { "chinese": "一听到那消息，她就坐立不安", "english": "On hearing the news, she was on pins and needles.", "type": "句子", "keyWords": ["on"] },
    { "chinese": "我一到家就发现家中被盗", "english": "On my arrival home/On arriving home I discovered the burglary.", "type": "句子", "keyWords": ["on"] },
    { "chinese": "n. & adv. 一次；conj. 一旦；一……就", "english": "once", "type": "单词", "keyWords": [] },
    { "chinese": "突然", "english": "all at once(= all of a sudden)", "type": "短语", "keyWords": ["once"] },
    { "chinese": "立刻；同时", "english": "at once", "type": "短语", "keyWords": ["once"] },
    { "chinese": "偶尔", "english": "(every) once in a while", "type": "短语", "keyWords": ["once"] },
    { "chinese": "再次", "english": "once more (= once again)", "type": "短语", "keyWords": ["once"] },
    { "chinese": "几次；一两次", "english": "once or twice", "type": "短语", "keyWords": ["once"] },
    { "chinese": "从前", "english": "once upon a time", "type": "短语", "keyWords": ["once"] },
    { "chinese": "每天(或每周等)一次", "english": "once a day(a week, etc.)", "type": "短语", "keyWords": ["once"] },
    { "chinese": "一劳永逸地；最后一次(以后不再)", "english": "once(and) for all", "type": "短语", "keyWords": ["once"] },
    { "chinese": "一旦出版，这本词典将会非常畅销！", "english": "Once printed, this dictionary will be very popular!", "type": "句子", "keyWords": ["once"] },
    { "chinese": "一朝被蛇咬，十年怕井绳。一次被咬，下次胆小。", "english": "Once bitten, twice shy.", "type": "句子", "keyWords": ["once"] },
    { "chinese": "num. 一；pron. (任何)一个人；(人或物的)一分子(指代提到的名词)；a. 一；某一；同一", "english": "one", "type": "单词", "keyWords": [] },
    { "chinese": "(十)分之一", "english": "one in / out of(ten)", "type": "短语", "keyWords": ["one"] },
    { "chinese": "一则；一个例子是…", "english": "for one thing", "type": "短语", "keyWords": ["one"] },
    { "chinese": "一次一个", "english": "one at a time", "type": "短语", "keyWords": ["one"] },
    { "chinese": "多半；十之八九", "english": "ten to one", "type": "短语", "keyWords": ["one"] },
    { "chinese": "一个一个地，依次", "english": "one by one", "type": "短语", "keyWords": ["one"] },
    { "chinese": "一个一个地，接连", "english": "one after another", "type": "短语", "keyWords": ["one"] },
    { "chinese": "单行道", "english": "a one-way street", "type": "短语", "keyWords": ["one"] },
    { "chinese": "独幕剧", "english": "a one-act play", "type": "短语", "keyWords": ["one"] },
    { "chinese": "pron. 自己；亲自(见itself)", "english": "oneself", "type": "单词", "keyWords": [] },
    { "chinese": "独自(没别人帮助)", "english": "(all) by oneself", "type": "短语", "keyWords": ["oneself"] },
    { "chinese": "为自己；代表自己；独立地，亲自地", "english": "for oneself", "type": "短语", "keyWords": ["oneself"] },
    { "chinese": "处于正常的身体或精神状态", "english": "look oneself", "type": "短语", "keyWords": ["oneself"] },
    { "chinese": "片面的；单方面的；只有一边的", "english": "one-sided", "type": "单词", "keyWords": [] },
    { "chinese": "片面的看法/论据", "english": "a one-sided view/ argument", "type": "短语", "keyWords": ["one-sided"] },
    { "chinese": "n. (C)(U]洋葱", "english": "onion", "type": "单词", "keyWords": [] },
    { "chinese": "a. [计]联机的；在线式的，因特网上的；ad. 联机；在线式", "english": "online", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 仅仅；只有；a. 唯一的；仅有的；(子、女)独生的；最合适的", "english": "only", "type": "单词", "keyWords": [] },
    { "chinese": "我从家里一路跑到图书馆，不料发现图书馆已经关门了。", "english": "I ran all the way from home to the library, only to find it closed.", "type": "句子", "keyWords": ["only"] },
    { "chinese": "极想；实在", "english": "only/but/ all too...", "type": "短语", "keyWords": ["only"] },
    { "chinese": "他极愿为朋友效劳。", "english": "He is only too willing to serve friends.", "type": "句子", "keyWords": ["only"] },
    { "chinese": "……多好啊；真希望…(常用虚拟语气)", "english": "If only...", "type": "短语", "keyWords": ["only"] },
    { "chinese": "但愿天气赶快放晴。", "english": "If only it would clear up soon!", "type": "句子", "keyWords": ["only"] },
    { "chinese": "只有……才……", "english": "only if", "type": "短语", "keyWords": ["only"] },
    { "chinese": "只有在你真正想喝的情况下，才接受一杯。", "english": "Accept a drink only if you really want one.", "type": "句子", "keyWords": ["only"] },
    { "chinese": "prep. 到…上", "english": "onto", "type": "单词", "keyWords": [] },
    { "chinese": "跳到台上", "english": "jump onto the stage", "type": "短语", "keyWords": ["onto"] },
    { "chinese": "a. 坦率的；公开的；开放的；开着的；v. 开，打开；开业；(the)户外，野外", "english": "open", "type": "单词", "keyWords": [] },
    { "chinese": "对…开放；乐于接受某事物；愿意考虑", "english": "be open to (suggestions...", "type": "短语", "keyWords": ["open"] },
    { "chinese": "热情地", "english": "with open arms", "type": "短语", "keyWords": ["open"] },
    { "chinese": "在户外/在空旷的农村", "english": "in the open air/ countryside", "type": "短语", "keyWords": ["open"] },
    { "chinese": "让我们彼此坦诚相见吧。", "english": "Let's be open with each other about it.", "type": "句子", "keyWords": ["open"] },
    { "chinese": "他的书放在桌子上，打开着。", "english": "His book lay open on the desk.", "type": "句子", "keyWords": ["open"] },
    { "chinese": "开火，开始射击", "english": "open fire", "type": "短语", "keyWords": ["open"] },
    { "chinese": "向…敞开心扉；乐于接受(意见、批评等)", "english": "open one's mind to", "type": "短语", "keyWords": ["open"] },
    { "chinese": "开放；开辟，开拓、开发(市场/新线路)", "english": "open(..)up(a market/a new route)", "type": "短语", "keyWords": ["open"] },
    { "chinese": "通向；对着", "english": "open into/ onto/to..", "type": "短语", "keyWords": ["open"] },
    { "chinese": "...对公众开放", "english": "open sth. to the public", "type": "短语", "keyWords": ["open"] },
    { "chinese": "n. [C]开启者；开启工具", "english": "opener", "type": "单词", "keyWords": [] },
    { "chinese": "a. 开始的，开幕的；n. [C]开口处，口子；空地；开幕式；开端", "english": "opening", "type": "单词", "keyWords": [] },
    { "chinese": "墙上一个在功能上类似窗户的开口", "english": "an opening in the wall that resembles a window in function", "type": "短语", "keyWords": ["opening"] },
    { "chinese": "n. (C)歌剧", "english": "opera", "type": "单词", "keyWords": [] },
    { "chinese": "歌剧院，剧场", "english": "opera house", "type": "短语", "keyWords": ["opera"] },
    { "chinese": "v. 操作(机器等)；操作；经营，管理；vi. 工作，运转；起作用；做手术；开刀", "english": "operate", "type": "单词", "keyWords": [] },
    { "chinese": "为某人动手术", "english": "operate on sb.", "type": "短语", "keyWords": ["operate"] },
    { "chinese": "操作系统", "english": "operating system", "type": "短语", "keyWords": ["operate"] },
    { "chinese": "[医]手术室", "english": "operating room", "type": "短语", "keyWords": ["operate"] },
    { "chinese": "手术台", "english": "operating table", "type": "短语", "keyWords": ["operate"] },
    { "chinese": "操作机器/经营工厂", "english": "operate a machine/ a factory", "type": "短语", "keyWords": ["operate"] },
    { "chinese": "多数网络工作得很好/运行正常。", "english": "Most networks operate well.", "type": "句子", "keyWords": ["operate"] },
    { "chinese": "n. [U]操作；经营；n. [C]手术；(业务等)活动；作战", "english": "operation", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]操作员；报务员", "english": "operator", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]意见；看法(析见idea)；n. [U]舆论", "english": "opinion", "type": "单词", "keyWords": [] },
    { "chinese": "舆论", "english": "public opinion", "type": "短语", "keyWords": ["opinion"] },
    { "chinese": "依照某人的看法(近from one's point of view)", "english": "in one's opinion/ view", "type": "短语", "keyWords": ["opinion"] },
    { "chinese": "对某人/某事评价很高/不好", "english": "have a(n) good/ high/ill/ low opinion of sb./sth.", "type": "短语", "keyWords": ["opinion"] },
    { "chinese": "n. [C]对手；反对者", "english": "opponent", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](U]机会", "english": "opportunity", "type": "单词", "keyWords": [] },
    { "chinese": "(失去)机会", "english": "seek/seize/miss/step an opportunity to...", "type": "短语", "keyWords": ["opportunity"] },
    { "chinese": "我趁此机会感谢你们所有人。", "english": "I take this opportunity to thank you all.", "type": "句子", "keyWords": ["opportunity"] },
    { "chinese": "机不可失，时不再来。", "english": "Opportunity knocks at the door only once.", "type": "句子", "keyWords": ["opportunity"] },
    { "chinese": "v. 反对；反抗", "english": "oppose", "type": "单词", "keyWords": [] },
    { "chinese": "反对的；敌对的", "english": "opposed", "type": "单词", "keyWords": [] },
    { "chinese": "反对某事 (近object to sth., be opposite to, be against)", "english": "oppose sth.= *be opposed to sth.", "type": "短语", "keyWords": ["oppose"] },
    { "chinese": "n. [U]反对，反抗", "english": "opposition", "type": "单词", "keyWords": [] },
    { "chinese": "反对某事", "english": "be in opposition to..", "type": "短语", "keyWords": ["opposition"] },
    { "chinese": "n. [C]对立面；对立物；a. 对立的；反对的；对面的；ad. 在对面，对过", "english": "opposite", "type": "单词", "keyWords": [] },
    { "chinese": "高是低的对立面。", "english": "High is the opposite of low.", "type": "句子", "keyWords": ["opposite"] },
    { "chinese": "朝相反的方向", "english": "in opposite/ reverse directions", "type": "短语", "keyWords": ["opposite"] },
    { "chinese": "在…对面；与…相反", "english": "be opposite to", "type": "短语", "keyWords": ["opposite"] },
    { "chinese": "她的房子在我的房子对面。", "english": "Her house is opposite to mine.", "type": "句子", "keyWords": ["opposite"] },
    { "chinese": "他站在对面。", "english": "He stood opposite.", "type": "句子", "keyWords": ["opposite"] },
    { "chinese": "a. 乐观的", "english": "optimistic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]乐天派，乐观者", "english": "optimist", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]选择权；n. [C]选项；(供)选择的事物；选修课", "english": "option", "type": "单词", "keyWords": [] },
    { "chinese": "选修课", "english": "optional courses", "type": "短语", "keyWords": ["option"] },
    { "chinese": "v. 压迫；压制", "english": "oppress", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]压迫；压抑", "english": "oppression", "type": "单词", "keyWords": [] },
    { "chinese": "被压迫的人", "english": "the oppressed", "type": "短语", "keyWords": ["oppress"] },
    { "chinese": "压迫/压抑感", "english": "a feeling of oppression", "type": "短语", "keyWords": ["oppress"] },
    { "chinese": "conj. 或者；否则，不然的话(=or(else)otherwise)；…or so…左右；or something或类似的东西", "english": "or", "type": "单词", "keyWords": [] },
    { "chinese": "a. 口头的；口述的；口的", "english": "oral", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]柑；橘；橙子；n. [U]橙黄色；a. 橘黄色的，橙色的", "english": "orange", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][天文]运行轨道；v. 绕…轨道而行；vi. 环行(around)", "english": "orbit", "type": "单词", "keyWords": [] },
    { "chinese": "进入轨道", "english": "go into orbit", "type": "短语", "keyWords": ["orbit"] },
    { "chinese": "绕月球运行", "english": "orbit(around) the moon", "type": "短语", "keyWords": ["orbit"] },
    { "chinese": "n. [C]管弦乐队", "english": "orchestra", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]兰花；n. [U]淡紫色；a. 淡紫色的", "english": "orchid", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]顺序；整齐；秩序；n. [C]命令；定购；vt. 叫(菜、饭等)；命令；整理", "english": "order", "type": "单词", "keyWords": [] },
    { "chinese": "你可以点菜了吗?", "english": "May I take your order?", "type": "句子", "keyWords": ["order"] },
    { "chinese": "混乱；发生故障", "english": "be out of order", "type": "短语", "keyWords": ["order"] },
    { "chinese": "按顺序", "english": "in order", "type": "短语", "keyWords": ["order"] },
    { "chinese": "维持秩序", "english": "keep order", "type": "短语", "keyWords": ["order"] },
    { "chinese": "订购某物", "english": "place an order for sth.", "type": "短语", "keyWords": ["order"] },
    { "chinese": "按时间/尺寸大小的顺序", "english": "in order of time/size", "type": "短语", "keyWords": ["order"] },
    { "chinese": "命令某人做某事", "english": "order sb. to do sth.", "type": "短语", "keyWords": ["order"] },
    { "chinese": "a. 整齐的；有秩序的(反disorderly)", "english": "orderly", "type": "单词", "keyWords": [] },
    { "chinese": "a. 平常的；平庸的(强调平凡，无特别之处和例外)", "english": "ordinary", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]器官；机构；管风琴；a. 有机的；器官的", "english": "organ", "type": "单词", "keyWords": [] },
    { "chinese": "n. 组织", "english": "organization", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 组织；建立；vi. 组织起来；建立组织", "english": "organize", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有组织的", "english": "organized", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 使适应；给…定向；以…为方向、目的(to, towards)", "english": "orient", "type": "单词", "keyWords": [] },
    { "chinese": "使自己适应新思维方式", "english": "orient yourself to the new way of thinking", "type": "短语", "keyWords": ["orient"] },
    { "chinese": "a. 东方的；亚洲的；中国的", "english": "oriental", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]起源；来源；根源；n. [U]出身", "english": "origin", "type": "单词", "keyWords": [] },
    { "chinese": "v. 起源于(from)", "english": "originate", "type": "单词", "keyWords": [] },
    { "chinese": "文明的发源/争吵的原因", "english": "the origin of civilization/a quarrel", "type": "短语", "keyWords": ["origin"] },
    { "chinese": "a. 最初的；原先的；原始的；原创的；独创的；n. [C]原文，原作；原物；最早的一个", "english": "original", "type": "单词", "keyWords": [] },
    { "chinese": "留手稿但给出版商一份复印件", "english": "keep the original but send a copy to his publisher", "type": "句子", "keyWords": ["original"] },
    { "chinese": "n. [C]孤儿；a. 孤儿的", "english": "orphan", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]孤儿院", "english": "orphanage", "type": "单词", "keyWords": [] },
    { "chinese": "a. 别的；其他的", "english": "other", "type": "单词", "keyWords": [] },
    { "chinese": "其余人或物", "english": "the other.../the others", "type": "短语", "keyWords": ["other"] },
    { "chinese": "换言之", "english": "In other words", "type": "短语", "keyWords": ["other"] },
    { "chinese": "别无去处", "english": "have no other place to go", "type": "短语", "keyWords": ["other"] },
    { "chinese": "几天前", "english": "the other day", "type": "短语", "keyWords": ["other"] },
    { "chinese": "每隔一天/年", "english": "every other day/ year..", "type": "短语", "keyWords": ["other"] },
    { "chinese": "另外两个/许多…", "english": "two/ many other...", "type": "短语", "keyWords": ["other"] },
    { "chinese": "除了", "english": "other than", "type": "短语", "keyWords": ["other"] },
    { "chinese": "正是；就是(近no other than, none but, none except, nothing but)", "english": "none other than", "type": "短语", "keyWords": ["other"] },
    { "chinese": "conj. 否则；不然；ad. 不是这样；除此之外", "english": "otherwise", "type": "单词", "keyWords": [] },
    { "chinese": "我们原打算踢足球，可是天很热，我们就决定干别的了。", "english": "We were going to play football, but it was so hot that we decided to do otherwise.", "type": "句子", "keyWords": ["otherwise"] },
    { "chinese": "aux. v. 应当；应该", "english": "ought", "type": "单词", "keyWords": [] },
    { "chinese": "应该做某事", "english": "ought to do sth.", "type": "短语", "keyWords": ["ought"] },
    { "chinese": "n. [C]盎司(英制重量单位，约28.35克)；一点点；少量", "english": "ounce", "type": "单词", "keyWords": [] },
    { "chinese": "pron. 我们的", "english": "ours", "type": "单词", "keyWords": [] },
    { "chinese": "pron. 我们自己", "english": "ourselves", "type": "单词", "keyWords": [] },
    { "chinese": "只限于咱俩之间(不得外传)", "english": "between ourselves(=between you and me)", "type": "短语", "keyWords": ["ourselves"] },
    { "chinese": "ad. 出；向外；在外；彻底地，完全地；a. [口]过时的；下台的；不在家", "english": "out", "type": "单词", "keyWords": [] },
    { "chinese": "缺乏；没有；从…出来；由于，出于；在…范围外；用…制成", "english": "out of", "type": "短语", "keyWords": ["out"] },
    { "chinese": "六票中有五票", "english": "five out of six votes", "type": "短语", "keyWords": ["out"] },
    { "chinese": "出于习惯/同情", "english": "out of habit/ pity", "type": "短语", "keyWords": ["out"] },
    { "chinese": "失控", "english": "out of control", "type": "短语", "keyWords": ["out"] },
    { "chinese": "用木头制成", "english": "be made out of wood", "type": "短语", "keyWords": ["out"] },
    { "chinese": "过时的", "english": "out-of-date", "type": "短语", "keyWords": ["out"] },
    { "chinese": "n. [C]结果(比较come out)", "english": "outcome", "type": "单词", "keyWords": [] },
    { "chinese": "a. 户外的；露天的；野外的", "english": "outdoor", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 在户外；在露天；在野外", "english": "outdoors", "type": "单词", "keyWords": [] },
    { "chinese": "在野外干活", "english": "work outdoors", "type": "短语", "keyWords": ["outdoors"] },
    { "chinese": "a. 外面的；外部的", "english": "outer", "type": "单词", "keyWords": [] },
    { "chinese": "外墙", "english": "outer walls", "type": "短语", "keyWords": ["outer"] },
    { "chinese": "a. 热情友好的；开朗的", "english": "outgoing", "type": "单词", "keyWords": [] },
    { "chinese": "开朗的性格", "english": "an outgoing personality", "type": "短语", "keyWords": ["outgoing"] },
    { "chinese": "n. [C]郊游；外出，旅行", "english": "outing", "type": "单词", "keyWords": [] },
    { "chinese": "外出短途旅行", "english": "go on an outing", "type": "短语", "keyWords": ["outing"] },
    { "chinese": "n. [C]概述；提纲；要点；轮廓；外形；vt. 概述；概括", "english": "outline", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]观点，看法；景色，视野；前景，展望", "english": "outlook", "type": "单词", "keyWords": [] },
    { "chinese": "一种积极的人生观", "english": "a positive outlook on life", "type": "短语", "keyWords": ["outlook"] },
    { "chinese": "悦人的景色", "english": "a pleasant outlook", "type": "短语", "keyWords": ["outlook"] },
    { "chinese": "经济发展的长期展望", "english": "the long-term outlook for economic growth", "type": "短语", "keyWords": ["outlook"] },
    { "chinese": "n. [U](the)产量；输出(比较put out)", "english": "output", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](the)外面；外部；a. 外面的；prep. 在…外边；ad. 在外面", "english": "outside", "type": "单词", "keyWords": [] },
    { "chinese": "房子的外观", "english": "the outside of the house", "type": "短语", "keyWords": ["outside"] },
    { "chinese": "局外人", "english": "outsider", "type": "单词", "keyWords": [] },
    { "chinese": "a. 突出的；出众的(比较stand out)", "english": "outstanding", "type": "单词", "keyWords": [] },
    { "chinese": "a. 向外的；ad. 向外(=outwards, 反inward/ inwards)", "english": "outward", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]烤箱，烤炉，灶", "english": "oven", "type": "单词", "keyWords": [] },
    { "chinese": "微波炉", "english": "a microwave oven", "type": "短语", "keyWords": ["oven"] },
    { "chinese": "ad. 结束；越过；翻转；prep. 在(时间)；度过；对于(某事)；在…上方；超过", "english": "over", "type": "单词", "keyWords": [] },
    { "chinese": "到处", "english": "all over(...)", "type": "短语", "keyWords": ["over"] },
    { "chinese": "翻页", "english": "turn the paper over", "type": "短语", "keyWords": ["over"] },
    { "chinese": "一再地，再三地", "english": "over and over", "type": "短语", "keyWords": ["over"] },
    { "chinese": "再次", "english": "(all) over again(= once more)", "type": "短语", "keyWords": ["over"] },
    { "chinese": "跌落山崖", "english": "fall over the cliff", "type": "短语", "keyWords": ["over"] },
    { "chinese": "他正走过来。", "english": "He's coming over.", "type": "句子", "keyWords": ["over"] },
    { "chinese": "他通过电话跟我说话。", "english": "He spoke to me over the telephone.", "type": "句子", "keyWords": ["over"] },
    { "chinese": "喝咖啡边谈某事", "english": "talk about sth. over a cup of coffee", "type": "短语", "keyWords": ["over"] },
    { "chinese": "周末进城", "english": "come to town over the weekend", "type": "短语", "keyWords": ["over"] },
    { "chinese": "多年来，这些年来", "english": "over the years", "type": "短语", "keyWords": ["over"] },
    { "chinese": "在未来几年里", "english": "over the next few years", "type": "短语", "keyWords": ["over"] },
    { "chinese": "表示“越过，超过；过分，太多”，例如：overland, overcrowded, overdo, overland, overgrown, overhear, overcook, oversensitive, overwork, overestimate, oversleep", "english": "over-", "type": "前缀", "keyWords": [] },
    { "chinese": "ad. 总的；综合的；包括一切的", "english": "overall", "type": "单词", "keyWords": [] },
    { "chinese": "医疗保健的总花销", "english": "the overall costs of medical care", "type": "短语", "keyWords": ["overall"] },
    { "chinese": "n. [C]外套；大衣", "english": "overcoat", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 克服", "english": "overcome", "type": "单词", "keyWords": [] },
    { "chinese": "克服困难/弱点/恐惧/缺点", "english": "overcome a difficulty/weakness/ one's fear/faults", "type": "短语", "keyWords": ["overcome"] },
    { "chinese": "v. 泛滥；溢出；(使)充溢；n. [U]泛滥；溢出", "english": "overflow", "type": "单词", "keyWords": [] },
    { "chinese": "a. 在头顶上的；上面的；高架的；ad. 在头顶上；在上面", "english": "overhead", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 忽视；眺望，俯瞰；不计较，放任", "english": "overlook", "type": "单词", "keyWords": [] },
    { "chinese": "宽容过失", "english": "overlook a fault", "type": "短语", "keyWords": ["overlook"] },
    { "chinese": "俯瞰全市的塔楼", "english": "a tower overlooking the city", "type": "短语", "keyWords": ["overlook"] },
    { "chinese": "ad. 在整个夜里；一夜之间；a. 一整夜的；一夜间的，突然的", "english": "overnight", "type": "单词", "keyWords": [] },
    { "chinese": "突然间成名", "english": "become famous overnight", "type": "短语", "keyWords": ["overnight"] },
    { "chinese": "突如其来的成功", "english": "an overnight success", "type": "短语", "keyWords": ["overnight"] },
    { "chinese": "n. [C]立交桥，高架桥", "english": "overpass", "type": "单词", "keyWords": [] },
    { "chinese": "a. 在国外的；在海外的；ad. 在/向国外；在/向海外", "english": "overseas", "type": "单词", "keyWords": [] },
    { "chinese": "海外贸易", "english": "overseas trade", "type": "短语", "keyWords": ["overseas"] },
    { "chinese": "住在国外", "english": "live overseas", "type": "短语", "keyWords": ["overseas"] },
    { "chinese": "归国华侨", "english": "returned overseas Chinese", "type": "短语", "keyWords": ["overseas"] },
    { "chinese": "vt. 超(车)；赶上，超过", "english": "overtake", "type": "单词", "keyWords": [] },
    { "chinese": "超过另一辆车", "english": "overtake another car", "type": "短语", "keyWords": ["overtake"] },
    { "chinese": "vt. 欠(钱、人情债)；应该把…归功于；应感激", "english": "owe", "type": "单词", "keyWords": [] },
    { "chinese": "他欠我五美元。", "english": "He owes me five dollars. = He owes five dollars to me.", "type": "句子", "keyWords": ["owe"] },
    { "chinese": "我应向他们道个歉。", "english": "I owe them an apology.", "type": "句子", "keyWords": ["owe"] },
    { "chinese": "非常感激…", "english": "owe a great deal/ a lot to sb.", "type": "短语", "keyWords": ["owe"] },
    { "chinese": "我能有今天要感谢我的伯父。", "english": "I owe what I am to my uncle.", "type": "句子", "keyWords": ["owe"] },
    { "chinese": "归功于…", "english": "owe...to...", "type": "短语", "keyWords": ["owe"] },
    { "chinese": "我的成功归功于你的帮助。", "english": "I owe my success to your assistance.", "type": "句子", "keyWords": ["owe"] },
    { "chinese": "万有引力原理的发现应归功于牛顿。", "english": "We owe the principle of gravitation to Newton.", "type": "句子", "keyWords": ["owe"] },
    { "chinese": "多亏你我才大难不死。", "english": "I owe it to you that I survived the catastrophe.", "type": "句子", "keyWords": ["owe"] },
    { "chinese": "由于(多作状语)(辨析见account；近on account of, due to, thanks to)", "english": "owing to", "type": "短语", "keyWords": ["owe"] },
    { "chinese": "他有浪漫主义倾向是由于缺乏经验。", "english": "He tends to be romantic owing to lack of experience.", "type": "句子", "keyWords": ["owe"] },
    { "chinese": "a. 自己的(用于所有格后面)；pron. 属于自己的东西；vt. 拥有；有", "english": "own", "type": "单词", "keyWords": [] },
    { "chinese": "属于某人自己的房子", "english": "a house of one's own = one's own house", "type": "短语", "keyWords": ["own"] },
    { "chinese": "靠自己；单独地；孤立无援地(生活/走路)(近by oneself)", "english": "(live/walk...) on one's own", "type": "短语", "keyWords": ["own"] },
    { "chinese": "n. [C]物主；业主；所有人", "english": "owner", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]拥有；所有权；所有制", "english": "ownership", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl. oxen)公牛", "english": "ox", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]氧化物", "english": "oxide", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]氧；氧气", "english": "oxygen", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]臭氧", "english": "ozone", "type": "单词", "keyWords": [] },
    { "chinese": "臭氧层(距地球表面20 - 40英里，为同温层的外缘)", "english": "ozone layer", "type": "短语", "keyWords": ["ozone"] },
    { "chinese": "n.(一)步；n.[U]步速；v.踱；来回走；v.为...定步速", "english": "pace", "type": "单词", "keyWords": [] },
    { "chinese": "紧跟上所有的最新发展", "english": "keep pace with all the latest developments", "type": "短语", "keyWords": ["pace"] },
    { "chinese": "定速度；树立榜样", "english": "set the pace", "type": "短语", "keyWords": ["pace"] },
    { "chinese": "a.太平洋的", "english": "Pacific", "type": "单词", "keyWords": [] },
    { "chinese": "太平洋", "english": "the Pacific (Ocean)", "type": "短语", "keyWords": ["Pacific"] },
    { "chinese": "n.[C]背包；一小包/盒/箱/袋；一伙，一帮；一群；大量；v.包装；把...打包(或装箱)；塞满；挤满；整理；vi.打包；装箱", "english": "pack", "type": "单词", "keyWords": [] },
    { "chinese": "一群狼", "english": "a pack of wolves", "type": "短语", "keyWords": ["pack"] },
    { "chinese": "一副牌/一包烟", "english": "a pack of cards/ cigarettes", "type": "短语", "keyWords": ["pack"] },
    { "chinese": "收拾行李", "english": "pack up", "type": "短语", "keyWords": ["pack"] },
    { "chinese": "把衣服装进手提箱", "english": "pack her clothes into the suitcase", "type": "短语", "keyWords": ["pack"] },
    { "chinese": "用...塞满...", "english": "pack ... with sth.", "type": "短语", "keyWords": ["pack"] },
    { "chinese": "挤满...", "english": "...be packed with sb./ sth.", "type": "短语", "keyWords": ["pack"] },
    { "chinese": "把他们的船装满价值25万美元的鱼", "english": "pack their boat with a quarter million dollars worth of fish", "type": "句子", "keyWords": ["pack"] },
    { "chinese": "一艘装满价值25万美元的鱼的船", "english": "a boat packed with a quarter million dollars worth of fish", "type": "短语", "keyWords": ["pack"] },
    { "chinese": "n.[C]中小型的包/包裹；一揽子交易(或计划等)；v.把...打包/装箱(up)", "english": "package", "type": "单词", "keyWords": [] },
    { "chinese": "打开包裹", "english": "undo the package", "type": "短语", "keyWords": ["package"] },
    { "chinese": "真空包装", "english": "vacuum packaging", "type": "短语", "keyWords": ["package"] },
    { "chinese": "（旅行社安排一切的）包价旅游", "english": "a package tour", "type": "短语", "keyWords": ["package"] },
    { "chinese": "封装工艺", "english": "packaging technology", "type": "短语", "keyWords": ["package"] },
    { "chinese": "n.[C]小包/盒/捆/袋；[机]数据包", "english": "packet", "type": "单词", "keyWords": [] },
    { "chinese": "一捆信件", "english": "a packet of letters", "type": "短语", "keyWords": ["packet"] },
    { "chinese": "n.[C]页", "english": "page", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]疼痛，痛；内心的痛苦；(pl)功夫，努力；vt.使疼痛；使痛苦", "english": "pain", "type": "单词", "keyWords": [] },
    { "chinese": "头痛", "english": "have a pain in the head", "type": "短语", "keyWords": ["pain"] },
    { "chinese": "痛得直叫", "english": "cry with pain", "type": "短语", "keyWords": ["pain"] },
    { "chinese": "下功夫的工作", "english": "painstaking work", "type": "短语", "keyWords": ["pain"] },
    { "chinese": "煞费苦心，设法做某事", "english": "take (great) pains to do sth./ with sth.", "type": "短语", "keyWords": ["pain"] },
    { "chinese": "痛苦，疼痛", "english": "be in pain", "type": "短语", "keyWords": ["pain"] },
    { "chinese": "讨厌的家伙/任务", "english": "a pain in the neck", "type": "短语", "keyWords": ["pain"] },
    { "chinese": "n.[C]止痛药", "english": "painkiller", "type": "单词", "keyWords": [] },
    { "chinese": "不劳则无获", "english": "No pains, no gains.", "type": "句子", "keyWords": ["pain"] },
    { "chinese": "n.[U]油漆；涂料；颜料；v.用(颜料等)画；涂油漆", "english": "paint", "type": "单词", "keyWords": [] },
    { "chinese": "把某物漆成...色", "english": "paint sth.+colour", "type": "短语", "keyWords": ["paint"] },
    { "chinese": "油漆未干", "english": "Wet paint!", "type": "句子", "keyWords": ["paint"] },
    { "chinese": "n.[C]绘画作品；n.[U]绘画；绘画艺术", "english": "painting", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]一双；一对；v.配对；vi.成对；配合合作", "english": "pair", "type": "单词", "keyWords": [] },
    { "chinese": "一双；一对", "english": "a pair of", "type": "短语", "keyWords": ["pair"] },
    { "chinese": "成对", "english": "make a pair", "type": "短语", "keyWords": ["pair"] },
    { "chinese": "两人一组讨论/成对出售", "english": "talk/sell in pairs", "type": "短语", "keyWords": ["pair"] },
    { "chinese": "中国各地都很流行麻辣小龙虾配上啤酒作夜宵", "english": "Spicy crayfish dishes are popular across the country to pair with beer on summer nights.", "type": "句子", "keyWords": ["pair"] },
    { "chinese": "n.[C]宫；宫殿", "english": "palace", "type": "单词", "keyWords": [] },
    { "chinese": "颐和园", "english": "the Summer Palace", "type": "短语", "keyWords": ["palace"] },
    { "chinese": "a.苍白的；灰白的；v.变苍白；变得暗淡；显得逊色；vt.使变得苍白；使变得暗淡", "english": "pale", "type": "单词", "keyWords": [] },
    { "chinese": "听到消息大惊失色", "english": "turn pale with fright at the news", "type": "短语", "keyWords": ["pale"] },
    { "chinese": "n.[C]手掌(心)；棕榈树", "english": "palm", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]平底锅/盘/盆；盘状器皿；盆地；洼地", "english": "pan", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]薄烤饼", "english": "pancake", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]熊猫", "english": "panda", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]恐慌；惊慌；v.(panicked, panicking)惊恐", "english": "panic", "type": "单词", "keyWords": [] },
    { "chinese": "在惊恐中", "english": "be in (a) panic", "type": "短语", "keyWords": ["panic"] },
    { "chinese": "惊慌失措", "english": "be seized with a panic", "type": "短语", "keyWords": ["panic"] },
    { "chinese": "人们听到枪声感到惊慌", "english": "The crowd panicked at the sound of the guns.", "type": "句子", "keyWords": ["panic"] },
    { "chinese": "n.[C]【美】裤子", "english": "pants", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]纸；n.[C]报纸；考卷；文件；论文", "english": "paper", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]游行；队列；阅兵；v.游行；列队行进(或接受检阅)", "english": "parade", "type": "单词", "keyWords": [] },
    { "chinese": "举行游行", "english": "hold a parade", "type": "短语", "keyWords": ["parade"] },
    { "chinese": "在游行", "english": "be on parade", "type": "短语", "keyWords": ["parade"] },
    { "chinese": "n.[C]段落", "english": "paragraph", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]平行线(或曲线或面)；可相比拟的事物；v.使平行；与...平行；a.平行的；ad.平行地", "english": "parallel", "type": "单词", "keyWords": [] },
    { "chinese": "双杠", "english": "parallel bars", "type": "短语", "keyWords": ["parallel"] },
    { "chinese": "美国足球和欧洲足球没有什么相似之处", "english": "There are few parallels between American football and European football.", "type": "句子", "keyWords": ["parallel"] },
    { "chinese": "平行于公路挖沟渠", "english": "parallel the ditch to the highway", "type": "短语", "keyWords": ["parallel"] },
    { "chinese": "这条小河与那条道平行数英里", "english": "The stream parallels the road for several miles.", "type": "句子", "keyWords": ["parallel"] },
    { "chinese": "与...平行的；类似的", "english": "be parallel to/with...", "type": "短语", "keyWords": ["parallel"] },
    { "chinese": "铁路线和那条公路平行", "english": "The railway line runs parallel with/ to the highway.", "type": "句子", "keyWords": ["parallel"] },
    { "chinese": "v.使麻痹，使瘫痪", "english": "paralyse (=paralyze)", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]包裹；小包", "english": "parcel", "type": "单词", "keyWords": [] },
    { "chinese": "vt.原谅；宽恕；n.[U]原谅；宽恕", "english": "pardon", "type": "单词", "keyWords": [] },
    { "chinese": "原谅某人某事", "english": "pardon sb. sth.", "type": "短语", "keyWords": ["pardon"] },
    { "chinese": "原谅我的过错", "english": "pardon me my faults", "type": "短语", "keyWords": ["pardon"] },
    { "chinese": "原谅某人做某事", "english": "pardon sb. for doing sth. = pardon one's doing sth.", "type": "短语", "keyWords": ["pardon"] },
    { "chinese": "对不起；请原谅/请再说一遍", "english": "I beg your pardon.", "type": "句子", "keyWords": ["pardon"] },
    { "chinese": "对不起；请原谅", "english": "Pardon me.", "type": "句子", "keyWords": ["pardon"] },
    { "chinese": "请再说一遍", "english": "Pardon?", "type": "句子", "keyWords": ["pardon"] },
    { "chinese": "n.[C]父亲；母亲；a.父亲(似)的；母亲(似)的；父母(似)的；母公司的", "english": "parent", "type": "单词", "keyWords": [] },
    { "chinese": "每家单位，包括母公司，都有自己的地方管理层", "english": "Each unit including the parent company has its own, local management.", "type": "句子", "keyWords": ["parent"] },
    { "chinese": "n.[U]对孩子的养育", "english": "parenting", "type": "单词", "keyWords": [] },
    { "chinese": "一个冷静、守规矩的孩子对某种不同的育儿方式的反应可能会好过其弟弟妹妹", "english": "A calm, rule-following child might respond better to a different sort of parenting than, for example, a younger sibling.", "type": "句子", "keyWords": ["parenting"] },
    { "chinese": "n.[C]公园；停车场；vt.停放(车辆等)", "english": "park", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]停车；车位；停车场地", "english": "parking", "type": "单词", "keyWords": [] }
];
