const qgl196_210 = [
    { "chinese": "禁止停车", "english": "No Parking!", "type": "句子", "keyWords": ["parking"] },
    { "chinese": "停车场", "english": "parking area/ lot/ place/ space", "type": "短语", "keyWords": ["parking"] },
    { "chinese": "停车计时计费器", "english": "parking meter", "type": "短语", "keyWords": ["parking"] },
    { "chinese": "(路上)停车道", "english": "parking lane", "type": "短语", "keyWords": ["parking"] },
    { "chinese": "n.[C]鹦鹉", "english": "parrot", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]部分；角色；地区；零件；vi.分开；分成几个部分；分手；vt.使分开", "english": "part", "type": "单词", "keyWords": [] },
    { "chinese": "...的一部分", "english": "part of", "type": "短语", "keyWords": ["part"] },
    { "chinese": "(在...中)起作用；扮演角色", "english": "play a part(in..)", "type": "短语", "keyWords": ["part"] },
    { "chinese": "部分地", "english": "in part (=partially)", "type": "短语", "keyWords": ["part"] },
    { "chinese": "(在戏中)扮演...", "english": "play the part of", "type": "短语", "keyWords": ["part"] },
    { "chinese": "汽车零配件", "english": "spare parts for cars", "type": "短语", "keyWords": ["part"] },
    { "chinese": "参加", "english": "take part (in sth.)", "type": "短语", "keyWords": ["part"] },
    { "chinese": "多半；大部分时间；在很大程度上", "english": "for the most part", "type": "短语", "keyWords": ["part"] },
    { "chinese": "至于我；对我来说", "english": "for my part", "type": "短语", "keyWords": ["part"] },
    { "chinese": "窗帘从中间分开", "english": "The curtain parted in the middle.", "type": "句子", "keyWords": ["part"] },
    { "chinese": "谁也不能把这两个朋友分开", "english": "No one could part the two friends.", "type": "句子", "keyWords": ["part"] },
    { "chinese": "跟...分手，放弃，丧失，卖掉", "english": "part with", "type": "短语", "keyWords": ["part"] },
    { "chinese": "友好地分手", "english": "part as friends", "type": "短语", "keyWords": ["part"] },
    { "chinese": "那守财奴拒绝花钱", "english": "The miser rejected parting with his money.", "type": "句子", "keyWords": ["part"] },
    { "chinese": "vi.参与，参加；*分享", "english": "participate", "type": "单词", "keyWords": [] },
    { "chinese": "参与；参加", "english": "participate in sth.", "type": "短语", "keyWords": ["participate"] },
    { "chinese": "殖民者参与了工程设计", "english": "The colonists participated in designing the project.", "type": "句子", "keyWords": ["participate"] },
    { "chinese": "n.[U]参与；参加；分享", "english": "participation", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]参加者(in sth.)", "english": "participant", "type": "单词", "keyWords": [] },
    { "chinese": "a.特定的；特殊的；独特的；*(pl)细节；particularly ad.特别；尤其", "english": "particular", "type": "单词", "keyWords": [] },
    { "chinese": "特别地", "english": "in particular", "type": "短语", "keyWords": ["particular"] },
    { "chinese": "尝试限制特别是在城市中心的停车", "english": "attempt to restrict parking in the city centre in particular", "type": "句子", "keyWords": ["particular"] },
    { "chinese": "(过于)讲究的；挑剔的；吹毛求疵的", "english": "be particular about sth.", "type": "短语", "keyWords": ["particular"] },
    { "chinese": "我不怎么讲究我的着装", "english": "I'm not particular about my clothes.", "type": "句子", "keyWords": ["particular"] },
    { "chinese": "n.[C]合伙人；搭档；同伴", "english": "partner", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]社交聚会；政党；(一)方；队，组", "english": "party", "type": "单词", "keyWords": [] },
    { "chinese": "双方", "english": "both parties", "type": "短语", "keyWords": ["party"] },
    { "chinese": "vt.传递；度过；经过；通过(考试、议案等)；vi.经过(by)；穿过(through)；n.[C]通行证", "english": "pass", "type": "单词", "keyWords": [] },
    { "chinese": "去世", "english": "pass away", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "昏过去", "english": "pass out", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "路过那家店", "english": "pass(by) the shop", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "对他置之不理", "english": "pass him by", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "无视；忽略；对...置之不理", "english": "pass sb./sth.by/over", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "继续；传递；传授", "english": "pass.. down/ on (to sb)", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "把消息转给有关的人", "english": "Pass the message on/ down to those who are concerned.", "type": "句子", "keyWords": ["pass"] },
    { "chinese": "将传统传给下一代", "english": "pass the traditions on/ down to the next generation", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "穿过；经历，遭受", "english": "pass through", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "(河流、汽车等)穿过村庄", "english": "pass through the village", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "经历了一段痛苦的时间", "english": "pass through a difficult period", "type": "短语", "keyWords": ["pass"] },
    { "chinese": "n.[C]过路人；路人", "english": "passer-by", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]经过；通过；n.[C]过道；通道；航道；(文章的)一节，一段", "english": "passage", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]乘客，旅客", "english": "passenger", "type": "单词", "keyWords": [] },
    { "chinese": "旅客列车", "english": "a passenger train", "type": "短语", "keyWords": ["passenger"] },
    { "chinese": "n.[U]热情；激情；passionate a.充满热情的", "english": "passion", "type": "单词", "keyWords": [] },
    { "chinese": "充满激情地(说…)", "english": "speak with passion", "type": "短语", "keyWords": ["passion"] },
    { "chinese": "热爱…", "english": "have a passion for...", "type": "短语", "keyWords": ["passion"] },
    { "chinese": "a. 消极的；被动的(反active)", "english": "passive", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]护照", "english": "passport", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]口令；密码", "english": "password", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 超过；经过；n. (the)过去，以前，旧时；往事；a. 以前的，过去的；ad. (从旁)过去", "english": "past", "type": "单词", "keyWords": [] },
    { "chinese": "他快六十了。", "english": "He is well past fifty.", "type": "句子", "keyWords": ["past"] },
    { "chinese": "在过去，从前", "english": "in the past", "type": "短语", "keyWords": ["past"] },
    { "chinese": "在过去的几年里（与完成时连用）", "english": "in the past few years + 完成时", "type": "短语", "keyWords": ["past"] },
    { "chinese": "往事", "english": "memories of the past", "type": "短语", "keyWords": ["past"] },
    { "chinese": "他走过(我身旁)时挥了挥手。", "english": "He waved as he walked past (me).", "type": "句子", "keyWords": ["past"] },
    { "chinese": "vt. 轻拍，轻打；n. [C]拍打", "english": "pat", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]专利；专利权；专利发明；a. 专利权的；受专利权保护的；vt. 得到(发明等)的专利权；给…特许状(或专利证)", "english": "patent", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]路，小道，小径；(物体运动的)路径", "english": "path", "type": "单词", "keyWords": [] },
    { "chinese": "通向成功的道路", "english": "the path to success", "type": "短语", "keyWords": ["path"] },
    { "chinese": "n. 忍耐；耐心", "english": "patience", "type": "单词", "keyWords": [] },
    { "chinese": "对(某人)有耐心", "english": "have patience with sb.", "type": "短语", "keyWords": ["patience"] },
    { "chinese": "耐心地", "english": "with patience", "type": "短语", "keyWords": ["patience"] },
    { "chinese": "n. 病人；a. 有耐心的", "english": "patient", "type": "单词", "keyWords": [] },
    { "chinese": "对(某人)有耐心", "english": "be patient with sb.", "type": "短语", "keyWords": ["patient"] },
    { "chinese": "a. 爱国的", "english": "patriotic", "type": "单词", "keyWords": [] },
    { "chinese": "n. 爱国者", "english": "patriot", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]爱国心，爱国主义", "english": "patriotism", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]图案，花样；模范，典范；样式，模式", "english": "pattern", "type": "单词", "keyWords": [] },
    { "chinese": "花的图案，印花的式样", "english": "a pattern of flowers", "type": "短语", "keyWords": ["pattern"] },
    { "chinese": "文化模式", "english": "cultural pattern", "type": "短语", "keyWords": ["pattern"] },
    { "chinese": "句型", "english": "a sentence pattern", "type": "短语", "keyWords": ["pattern"] },
    { "chinese": "服装式样", "english": "a dress pattern", "type": "短语", "keyWords": ["pattern"] },
    { "chinese": "vi./vt. 暂停；中止；n. [C]暂停；中止；停顿", "english": "pause", "type": "单词", "keyWords": [] },
    { "chinese": "中止，暂停", "english": "make a pause", "type": "短语", "keyWords": ["pause"] },
    { "chinese": "短暂的停顿后", "english": "after a pause", "type": "短语", "keyWords": ["pause"] },
    { "chinese": "停顿片刻", "english": "pause for a while", "type": "短语", "keyWords": ["pause"] },
    { "chinese": "vt. 铺路；为…做准备", "english": "pave", "type": "单词", "keyWords": [] },
    { "chinese": "为将来的研究工作铺平道路的实验", "english": "experiments that paved the way for future research", "type": "短语", "keyWords": ["pave"] },
    { "chinese": "n. [C][英]人行道；[美]sidewalk", "english": "pavement", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 支付；付钱给…报酬；vi. 付款；n. [C]报酬；工资", "english": "pay", "type": "单词", "keyWords": [] },
    { "chinese": "偿还(欠款)；报答；报仇", "english": "pay sb. back", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "买票才能进", "english": "have to pay to go in", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "还清(债款)", "english": "pay off (one's debts)", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "花钱买", "english": "pay sb. some money for sth.", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "为他的愚蠢付出代价", "english": "pay for his stupidity", "type": "短语", "keyWords": ["pay"] },
    { "chinese": "计划成功了。", "english": "The plan paid off.", "type": "句子", "keyWords": ["pay"] },
    { "chinese": "n. [U]支付；n. [C]支付的一笔钱", "english": "payment", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]和平；安宁", "english": "peace", "type": "单词", "keyWords": [] },
    { "chinese": "a. 和平的；安宁的", "english": "peaceful", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 和平地", "english": "peacefully", "type": "单词", "keyWords": [] },
    { "chinese": "和…讲和", "english": "make peace with", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "破坏治安", "english": "break the peace", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "和平地", "english": "in peace(=peacefully)", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "维护和平", "english": "maintain peace", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "处于和平/和睦/平静状态；安息，长眠", "english": "at peace", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "与某人和解；同某人言归于好", "english": "make one's peace with...", "type": "短语", "keyWords": ["peace"] },
    { "chinese": "n. [C]桃子", "english": "peach", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]孔雀", "english": "peacock", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]山峰；顶点；vi. 到达最大值；到达高峰", "english": "peak", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]花生；花生米", "english": "peanut", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]梨", "english": "pear", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]珍珠", "english": "pearl", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]农民", "english": "peasant", "type": "单词", "keyWords": [] },
    { "chinese": "a. 古怪的；独特的", "english": "peculiar", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]特性，怪癖", "english": "peculiarity", "type": "单词", "keyWords": [] },
    { "chinese": "某人/某地特有的", "english": "be peculiar to sb./a place", "type": "短语", "keyWords": ["peculiar"] },
    { "chinese": "这个地区所特有的物种", "english": "a species(which is) peculiar to this area", "type": "短语", "keyWords": ["peculiar"] },
    { "chinese": "n. [C]行人；a. 徒步的，步行的；行人的", "english": "pedestrian", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 剥…的皮", "english": "peel", "type": "单词", "keyWords": [] },
    { "chinese": "v. 偷看(at)", "english": "peep", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]同辈，同等的人；(才能、学识等)相匹配的人", "english": "peer", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]钢笔", "english": "pen", "type": "单词", "keyWords": [] },
    { "chinese": "用钢笔", "english": "in pen=with a pen", "type": "短语", "keyWords": ["pen"] },
    { "chinese": "n. [C]处罚；刑罚；罚球", "english": "penalty", "type": "单词", "keyWords": [] },
    { "chinese": "(足球)罚球区", "english": "penalty area", "type": "短语", "keyWords": ["penalty"] },
    { "chinese": "死刑", "english": "the death penalty", "type": "短语", "keyWords": ["penalty"] },
    { "chinese": "n. [C]铅笔", "english": "pencil", "type": "单词", "keyWords": [] },
    { "chinese": "用铅笔", "english": "in pencil=with a pencil", "type": "短语", "keyWords": ["pencil"] },
    { "chinese": "n. [C]便士(两种复数形式：pence强调面值，pennies强调硬币数量)", "english": "penny", "type": "单词", "keyWords": [] },
    { "chinese": "请给我把这个十便士的硬币换成十个一便士的硬币。", "english": "Please give me ten pennies for this tenpence.", "type": "句子", "keyWords": ["penny"] },
    { "chinese": "省一文等于挣一文。", "english": "A penny saved is a penny gained.", "type": "句子", "keyWords": ["penny"] },
    { "chinese": "n. [C]养老金；退休金；抚恤金；vt. 给某人发养老金或抚恤金等", "english": "pension", "type": "单词", "keyWords": [] },
    { "chinese": "n. (pl.)人，人们；(the)人民；n. [C]民族", "english": "people", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]胡椒粉；n. [C]辣椒", "english": "pepper", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 每，每一", "english": "per", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]百分之一；百分率；a. 百分之…的", "english": "percent", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]百分比；百分率；(全部中的)所占比例", "english": "percentage", "type": "单词", "keyWords": [] },
    { "chinese": "现在大部分教科书有插图。", "english": "A large/great percentage of school books now have pictures.", "type": "句子", "keyWords": ["percentage"] },
    { "chinese": "a. 完美的；十足的；熟练的；vt. 使完美；改善；提高", "english": "perfect", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 完美地；极佳地", "english": "perfectly", "type": "单词", "keyWords": [] },
    { "chinese": "熟能生巧。", "english": "Practice makes perfect.", "type": "句子", "keyWords": ["perfect"] },
    { "chinese": "vt. 演出；进行；做；执行；vi. 表演；表现", "english": "perform", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]表演者；执行者", "english": "performer", "type": "单词", "keyWords": [] },
    { "chinese": "做手术/履行义务/尽责任", "english": "perform the operation/obligations/one's duties", "type": "短语", "keyWords": ["perform"] },
    { "chinese": "n. [C]表演；n. [U]进行；执行，履行；表现，性能", "english": "performance", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 也许，可能", "english": "perhaps", "type": "单词", "keyWords": [] },
    { "chinese": "n. (一段)时间；句号", "english": "period", "type": "单词", "keyWords": [] },
    { "chinese": "a. 周期的，定期的", "english": "periodic", "type": "单词", "keyWords": [] },
    { "chinese": "a. 长久的；永久的；长期不变的", "english": "permanent", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]长久", "english": "permanence", "type": "单词", "keyWords": [] },
    { "chinese": "某人的永久地址", "english": "one's permanent address", "type": "短语", "keyWords": ["permanent"] },
    { "chinese": "n. [U]允许；准许", "english": "permission", "type": "单词", "keyWords": [] },
    { "chinese": "经(某人)容许", "english": "with (one's) permission", "type": "短语", "keyWords": ["permission"] },
    { "chinese": "请求许可", "english": "ask for permission", "type": "短语", "keyWords": ["permission"] },
    { "chinese": "未经许可，擅自", "english": "without permission", "type": "短语", "keyWords": ["permission"] },
    { "chinese": "vt. 允许，许可；vi. (常用否定)容许(of)；n. [C]许可证", "english": "permit", "type": "单词", "keyWords": [] },
    { "chinese": "允许做某事", "english": "permit doing sth.", "type": "短语", "keyWords": ["permit"] },
    { "chinese": "允许某人做某事", "english": "permit sb. to do sth.", "type": "短语", "keyWords": ["permit"] },
    { "chinese": "情势刻不容缓。", "english": "The situation doesn't permit of any delay.", "type": "句子", "keyWords": ["permit"] },
    { "chinese": "旅游签证/工作许可证", "english": "a travel/work permit", "type": "短语", "keyWords": ["permit"] },
    { "chinese": "vt. 坚持(做)(in/with sth., in doing sth.)", "english": "persevere", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]百折不挠", "english": "perseverance", "type": "单词", "keyWords": [] },
    { "chinese": "a. 不屈不挠的", "english": "persevering", "type": "单词", "keyWords": [] },
    { "chinese": "坚持改革开放", "english": "persevere in the reform and opening-up policy", "type": "短语", "keyWords": ["persevere"] },
    { "chinese": "vi. 固执；坚持不懈(in sth./doing sth.)", "english": "persist", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]执意，坚持", "english": "persistence", "type": "单词", "keyWords": [] },
    { "chinese": "a. 执意的，坚持的", "english": "persistent", "type": "单词", "keyWords": [] },
    { "chinese": "(固执地)坚持", "english": "persist in doing sth.", "type": "短语", "keyWords": ["persist"] },
    { "chinese": "n. [C]人", "english": "person", "type": "单词", "keyWords": [] },
    { "chinese": "a. 个人的；私人的；亲自的", "english": "personal", "type": "单词", "keyWords": [] },
    { "chinese": "亲自", "english": "in person", "type": "短语", "keyWords": ["personal"] },
    { "chinese": "n. [C]/[U]个性", "english": "personality", "type": "单词", "keyWords": [] },
    { "chinese": "n. (用作单或复)全体员工；人事部门", "english": "personnel", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]透视画法；透视图；[C]远景；景观；视角；观点；想法", "english": "perspective", "type": "单词", "keyWords": [] },
    { "chinese": "从不同的角度来看这个问题", "english": "see the issue from a different perspective", "type": "短语", "keyWords": ["perspective"] },
    { "chinese": "正确地，合理地；符合透视法地", "english": "in perspective", "type": "短语", "keyWords": ["perspective"] },
    { "chinese": "合理地评价某人的作用", "english": "judge sb.'s role in perspective", "type": "短语", "keyWords": ["perspective"] },
    { "chinese": "vt. 说服，劝服；a. 有说服力的", "english": "persuade；persuasive", "type": "单词", "keyWords": [] },
    { "chinese": "说服某人做某事", "english": "persuade sb. to do...；be able to advise sb. to do...", "type": "短语", "keyWords": ["persuade"] },
    { "chinese": "设法说服他干这个工作", "english": "try to persuade him to take the job", "type": "短语", "keyWords": ["persuade"] },
    { "chinese": "说服某人做/别做某事", "english": "persuade sb. into/out of doing sth.", "type": "短语", "keyWords": ["persuade"] },
    { "chinese": "她父亲说服了她嫁给约翰。", "english": "Her father persuaded her into marrying John.", "type": "句子", "keyWords": ["persuade"] },
    { "chinese": "a. 悲观的；悲观主义的", "english": "pessimistic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]/[U]杀虫剂；农药(近insecticide)", "english": "pesticide", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]宠物；玩赏动物；vt. 宠爱，溺爱", "english": "pet", "type": "单词", "keyWords": [] },
    { "chinese": "养宠物", "english": "keep/raise a pet", "type": "短语", "keyWords": ["pet"] },
    { "chinese": "n. [U]汽油", "english": "petrol", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](pl. phenomena)现象；奇迹；杰出的人才", "english": "phenomenon", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]哲学；人生观；(学科等的)基本原理；a. 哲学的", "english": "philosophy；philosophical", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]电话；vt. 给……打电话", "english": "phone", "type": "单词", "keyWords": [] },
    { "chinese": "给……打电话", "english": "phone sb.；call sb. up；ring sb. up；make a phone call to sb.；give sb. a ring", "type": "短语", "keyWords": ["phone"] },
    { "chinese": "在打电话；在接电话", "english": "on the phone", "type": "短语", "keyWords": ["phone"] },
    { "chinese": "有人要你接电话。", "english": "You are wanted on the phone.", "type": "句子", "keyWords": ["phone"] },
    { "chinese": "在电话里和某人讲话", "english": "talk to sb. over/on the phone", "type": "短语", "keyWords": ["phone"] },
    { "chinese": "挂断/接电话", "english": "hang up/answer the phone", "type": "短语", "keyWords": ["phone"] },
    { "chinese": "n. [C]照片(=photograph)；vt. 复印", "english": "photo；photocopy", "type": "单词", "keyWords": [] },
    { "chinese": "和某人合影", "english": "have a photo taken with sb.", "type": "短语", "keyWords": ["photo"] },
    { "chinese": "n. [C]摄影者", "english": "photographer", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]摄影术；摄影", "english": "photography", "type": "单词", "keyWords": [] },
    { "chinese": "a. 摄影的；摄影般的；逼真的", "english": "photographic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]短语，词组；习语", "english": "phrase", "type": "单词", "keyWords": [] },
    { "chinese": "a. 物理的；自然的；身体的；物质的；有形的；实物的", "english": "physical", "type": "单词", "keyWords": [] },
    { "chinese": "体育锻炼", "english": "physical training", "type": "短语", "keyWords": ["physical"] },
    { "chinese": "物理变化", "english": "a physical change", "type": "短语", "keyWords": ["physical"] },
    { "chinese": "n. [C][内科]医生(反surgeon外科医生)", "english": "physician", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]物理学家", "english": "physicist", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]物理学", "english": "physics", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]生理学；n. [C]生理学家", "english": "physiology；physiologist", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]钢琴；n. [C]钢琴家，钢琴演奏家", "english": "piano；pianist", "type": "单词", "keyWords": [] },
    { "chinese": "弹钢琴", "english": "play (on) the piano", "type": "短语", "keyWords": ["piano"] },
    { "chinese": "vt. 采摘；摘；拾；捡；vi. (被)采摘；n. [C]扒手", "english": "pick；pick - pocket", "type": "单词", "keyWords": [] },
    { "chinese": "他们在采棉花。", "english": "They were picking cotton.", "type": "句子", "keyWords": ["pick"] },
    { "chinese": "我的口袋被扒了。", "english": "My pocket was picked.", "type": "句子", "keyWords": ["pick"] },
    { "chinese": "分辨出，挑出；选出", "english": "pick out", "type": "短语", "keyWords": ["pick"] },
    { "chinese": "把汤姆从人群中认出来。", "english": "Pick out Tom from the crowd.", "type": "句子", "keyWords": ["pick"] },
    { "chinese": "①拾起；②加快速度；③获得；学会；买到；④取物，(用车、船)接人；救起；⑤(借助仪器)看到/收听到/侦察到；听到(谣传)；⑥染上(病)；形成(习惯)", "english": "pick up", "type": "短语", "keyWords": ["pick"] },
    { "chinese": "把帽子拾起来", "english": "pick up the hat", "type": "短语", "keyWords": ["pick up"] },
    { "chinese": "加速", "english": "pick up speed", "type": "短语", "keyWords": ["pick up"] },
    { "chinese": "小孩子学外语相当快。", "english": "Young children pick up a foreign language fairly quickly.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "她喜欢在旧货店买些有趣的旧货。", "english": "She likes to pick up some interesting junk in junk shops.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "每隔一天我得去学校接孩子们。", "english": "I have to pick up children from school every other day.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "汽车停下来搭乘客。", "english": "The bus stopped to pick up passengers.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "水手们被路过的客轮救起。", "english": "The sailors were picked up by a passing liner.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "我的收音机可收听BBC广播。", "english": "My radio can pick up the BBC.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "你从哪里听说的?", "english": "Where did you pick that up?", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "蚊子在感染了疟疾的人身上吸血时得疟疾。", "english": "Mosquitoes pick up malaria by sucking blood from an infected person.", "type": "句子", "keyWords": ["pick up"] },
    { "chinese": "n. [C]野餐；vi. (picnicked,picnicking)去野餐；参加野餐", "english": "picnic", "type": "单词", "keyWords": [] },
    { "chinese": "去野餐", "english": "go for/have a picnic；go out on a picnic", "type": "短语", "keyWords": ["picnic"] },
    { "chinese": "n. [C]图片；描写；记忆，情景；vt. 绘，画；描绘；构想；想象", "english": "picture", "type": "单词", "keyWords": [] },
    { "chinese": "清楚地了解", "english": "get a clear picture of", "type": "短语", "keyWords": ["picture"] },
    { "chinese": "生动地描述", "english": "give a vivid picture of", "type": "短语", "keyWords": ["picture"] },
    { "chinese": "去看电影", "english": "go to the pictures", "type": "短语", "keyWords": ["picture"] },
    { "chinese": "她的情况有很大差异。", "english": "The picture varies considerably from place to place.", "type": "句子", "keyWords": ["picture"] },
    { "chinese": "n. [C]/[U]馅饼", "english": "pie", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]块，片，段(表示不可数名词的量)；vt. 拼凑；缝合；修补", "english": "piece", "type": "单词", "keyWords": [] },
    { "chinese": "破碎，碎裂", "english": "go to pieces", "type": "短语", "keyWords": ["piece"] },
    { "chinese": "拼凑一则故事", "english": "piece together a story", "type": "短语", "keyWords": ["piece"] },
    { "chinese": "n. [C]猪", "english": "pig", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]鸽子", "english": "pigeon", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]堆，积，叠；vt. 堆积", "english": "pile", "type": "单词", "keyWords": [] },
    { "chinese": "堆积，累积", "english": "pile...up", "type": "短语", "keyWords": ["pile"] },
    { "chinese": "一堆(麻烦、报纸等)", "english": "a pile of (trouble,newspapers..)", "type": "短语", "keyWords": ["pile"] },
    { "chinese": "一大堆，好多", "english": "piles of", "type": "短语", "keyWords": ["pile"] },
    { "chinese": "n. [C]药丸；药片", "english": "pill", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]立柱", "english": "pillar", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]枕头", "english": "pillow", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]飞行员；领航员；vt. (为船舶)引航；驾驶(飞机等)；带领；引导；试用，试验；a. 引航员的；指引的；实验性的，试点的", "english": "pilot", "type": "单词", "keyWords": [] },
    { "chinese": "他以高超的技术把这条船引进了那个小港湾。", "english": "With great skill, he piloted the boat into the little harbour.", "type": "句子", "keyWords": ["pilot"] },
    { "chinese": "世界银行的贷款可以被用于基础建设和一个“全方位电动车生态系统”的试点项目，这将包括投资建立电瓶站和电池研发。", "english": "World Bank loans could help finance infrastructure and a \"comprehensive electric vehicle ecosystem\" pilot project that would include investment in battery stations and batteries.", "type": "句子", "keyWords": ["pilot"] },
    { "chinese": "n. [C]别针；发夹；vt. 用别针别起来；钉住", "english": "pin", "type": "单词", "keyWords": [] },
    { "chinese": "安全别针", "english": "a safety pin", "type": "短语", "keyWords": ["pin"] },
    { "chinese": "把布告钉在墙上", "english": "pin a notice on the wall", "type": "短语", "keyWords": ["pin"] },
    { "chinese": "n. [C]松树", "english": "pine", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]菠萝", "english": "pineapple", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]粉红色；a. 粉红色的", "english": "pink", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](容量单位)品脱", "english": "pint", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]先锋；开拓者；创立者，创办者；vt. 开拓，开发；为…开始；开创；vi. 当先驱，当先锋", "english": "pioneer", "type": "单词", "keyWords": [] },
    { "chinese": "少先队(员)", "english": "the Young Pioneer", "type": "短语", "keyWords": ["pioneer"] },
    { "chinese": "n. [C]管子；烟斗；导管", "english": "pipe", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]海盗；vt. 盗版", "english": "pirate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]同情；可怜；n. [C](只用单)遗憾；vt. 同情；a. 值得同情的；a. 可怜的", "english": "pity；pitable；pitiful", "type": "单词", "keyWords": [] },
    { "chinese": "同情/可怜某人", "english": "have/take pity on sb.", "type": "短语", "keyWords": ["pity"] },
    { "chinese": "真遗憾她竟然没在大会上发表她的意见。", "english": "It's a pity that she should not set out her idea at the conference.", "type": "句子", "keyWords": ["pity"] },
    { "chinese": "未受过正规教育的人应该得到同情而不是责备。", "english": "The uneducated are more to be pitied than blamed.", "type": "句子", "keyWords": ["pity"] },
    { "chinese": "n. [C]/[U]比萨饼", "english": "pizza", "type": "单词", "keyWords": [] },
    { "chinese": "n. 人民解放军", "english": "PLA (the People's Liberation Army缩略)", "type": "单词", "keyWords": [] },
    { "chinese": "一个人民解放军战士", "english": "a PLA man", "type": "短语", "keyWords": ["PLA"] },
    { "chinese": "vt. (小心)放置；安置；n. [C]地方；场所，地点；名次；地位", "english": "place", "type": "单词", "keyWords": [] },
    { "chinese": "首先", "english": "in the first place", "type": "短语", "keyWords": ["place"] },
    { "chinese": "在适当的位置上(反out of place合适的)", "english": "in place", "type": "短语", "keyWords": ["place"] },
    { "chinese": "代替(近instead of)", "english": "in place of", "type": "短语", "keyWords": ["place"] },
    { "chinese": "发生，举行", "english": "take place", "type": "短语", "keyWords": ["place"] },
    { "chinese": "代替，取代(近replace)", "english": "take the place of", "type": "短语", "keyWords": ["place"] },
    { "chinese": "①代替(=take the place of)；②就位", "english": "take one's place", "type": "短语", "keyWords": ["place"] },
    { "chinese": "n. [C]平原；a. 明白的，简明的；简易的；简朴的", "english": "plain", "type": "单词", "keyWords": [] },
    { "chinese": "以简明的语言", "english": "in plain language", "type": "短语", "keyWords": ["plain"] },
    { "chinese": "浅显的道理", "english": "a plain truth", "type": "短语", "keyWords": ["plain"] },
    { "chinese": "v. 计划，安排；n. [C]计划；平面图", "english": "plan", "type": "单词", "keyWords": [] },
    { "chinese": "计划做某事", "english": "plan to do sth.", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "按计划", "english": "as planned", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "该项目正按计划进行。", "english": "The project is progressing as planned.", "type": "句子", "keyWords": ["plan"] },
    { "chinese": "五年计划", "english": "a five-year plan", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "实施计划", "english": "carry out a plan", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "为……制订计划", "english": "work out/make plans for", "type": "短语", "keyWords": ["plan"] },
    { "chinese": "n. [C]飞机", "english": "plane", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]行星", "english": "planet", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]植物；工厂(重工业为主)；v. 种植，栽种", "english": "plant", "type": "单词", "keyWords": [] },
    { "chinese": "发电厂", "english": "power plant", "type": "短语", "keyWords": ["plant"] },
    { "chinese": "炼钢厂", "english": "steel plant", "type": "短语", "keyWords": ["plant"] },
    { "chinese": "n. [C]种植园", "english": "plantation", "type": "单词", "keyWords": [] },
    { "chinese": "咖啡种植园", "english": "coffee plantation", "type": "短语", "keyWords": ["plantation"] },
    { "chinese": "橡胶种植园", "english": "rubber plantation", "type": "短语", "keyWords": ["plantation"] },
    { "chinese": "a. 塑料(制)的；可塑的；(pl.)塑料；塑料制品；*(作单数)塑料学", "english": "plastic", "type": "单词", "keyWords": [] },
    { "chinese": "塑料杯", "english": "plastic cups", "type": "短语", "keyWords": ["plastic"] },
    { "chinese": "由塑料制成", "english": "be made of plastic(s)", "type": "短语", "keyWords": ["plastic"] },
    { "chinese": "n. [C]盘子，碟子；金属板；(汽车等的)牌照", "english": "plate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]站台，月台；讲台；平台", "english": "platform", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]剧本；戏剧；游戏；玩耍；v. 玩，打(球)；比赛；演出", "english": "play", "type": "单词", "keyWords": [] },
    { "chinese": "与我下棋", "english": "play me at chess/play chess with me", "type": "短语", "keyWords": ["play"] },
    { "chinese": "玩火，冒险", "english": "play with fire", "type": "短语", "keyWords": ["play"] },
    { "chinese": "与某人比赛", "english": "play(against)sb.", "type": "短语", "keyWords": ["play"] },
    { "chinese": "在玩，在游戏(反at work)", "english": "at play", "type": "短语", "keyWords": ["play"] },
    { "chinese": "公正合理；公平的比赛；光明正大的行动", "english": "fair play", "type": "短语", "keyWords": ["play"] },
    { "chinese": "n. [C]比赛者；运动员；游戏的人(玩耍、打牌、下棋)", "english": "player", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]操场", "english": "playground", "type": "单词", "keyWords": [] },
    { "chinese": "a. 令人愉快的；和蔼可亲的", "english": "pleasant", "type": "单词", "keyWords": [] },
    { "chinese": "悦耳的声音", "english": "a pleasant voice", "type": "短语", "keyWords": ["pleasant"] },
    { "chinese": "悦耳", "english": "be pleasant to the ear", "type": "短语", "keyWords": ["pleasant"] },
    { "chinese": "宜人的天气", "english": "pleasant weather", "type": "短语", "keyWords": ["pleasant"] },
    { "chinese": "愉快地度过时光", "english": "have a pleasant time", "type": "短语", "keyWords": ["pleasant"] },
    { "chinese": "v. 请(if you please的略语)；v. 使满意；使高兴", "english": "please", "type": "单词", "keyWords": [] },
    { "chinese": "(if you)please,...请；请听我说；对不起(礼貌地请求某人注意)", "english": "(if you)please,...", "type": "短语", "keyWords": ["please"] },
    { "chinese": "众口难调。", "english": "It is difficult to please everybody.", "type": "句子", "keyWords": ["please"] },
    { "chinese": "一幅悦目的图画", "english": "a picture that pleases the eye", "type": "短语", "keyWords": ["please"] },
    { "chinese": "你想去那里就去那里。", "english": "Go there as you please.", "type": "句子", "keyWords": ["please"] },
    { "chinese": "你爱怎么着就怎么着!", "english": "Do what you please!", "type": "句子", "keyWords": ["please"] },
    { "chinese": "要面面俱到者，面面不到。", "english": "Please all and you please none.", "type": "句子", "keyWords": ["please"] },
    { "chinese": "a. 高兴的；喜欢的(意指给人满意的感觉)", "english": "pleased", "type": "单词", "keyWords": [] },
    { "chinese": "对某事感到满意", "english": "be pleased at/about sth.", "type": "短语", "keyWords": ["pleased"] },
    { "chinese": "对某人/物感到满意", "english": "be pleased with sb./sth.", "type": "短语", "keyWords": ["pleased"] },
    { "chinese": "n. [U]愉快，高兴；n. [C]乐趣；乐事", "english": "pleasure", "type": "单词", "keyWords": [] },
    { "chinese": "为了享受，作为消遣", "english": "for pleasure", "type": "短语", "keyWords": ["pleasure"] },
    { "chinese": "喜欢……；以……为乐(=take delight/interest in)", "english": "take(a)pleasure in...", "type": "短语", "keyWords": ["pleasure"] },
    { "chinese": "很荣幸地；很高兴地；(多用于回答)没问题", "english": "with pleasure", "type": "短语", "keyWords": ["pleasure"] },
    { "chinese": "不客气。", "english": "It's a pleasure.=My pleasure.", "type": "句子", "keyWords": ["pleasure"] },
    { "chinese": "很乐意做某事。", "english": "It's a pleasure to do sth.", "type": "句子", "keyWords": ["pleasure"] },
    { "chinese": "n. [U]充足；大量；a. 充足的；多的", "english": "plenty；plentiful", "type": "单词", "keyWords": [] },
    { "chinese": "大量的；充足的(注意前面不用a)", "english": "plenty of", "type": "短语", "keyWords": ["plenty"] },
    { "chinese": "我家里还有很多。", "english": "I have plenty more at home.", "type": "句子", "keyWords": ["plenty"] },
    { "chinese": "n. [C]犁；v. 耕，犁", "english": "plough", "type": "单词", "keyWords": [] },
    { "chinese": "犁地", "english": "plough a field", "type": "短语", "keyWords": ["plough"] },
    { "chinese": "n. [C]插头；塞子；v. 给……通电", "english": "plug", "type": "单词", "keyWords": [] },
    { "chinese": "即插即用", "english": "plug and play", "type": "短语", "keyWords": ["plug"] },
    { "chinese": "插上(电视机的)插头", "english": "plug in (the TV set)", "type": "短语", "keyWords": ["plug"] },
    { "chinese": "v. 纵身跳入；陷入；投身；v. 把……投入；将……插入", "english": "plunge", "type": "单词", "keyWords": [] },
    { "chinese": "我们跳进冰冷的山间湖中。", "english": "We plunged into the icy mountain lake.", "type": "句子", "keyWords": ["plunge"] },
    { "chinese": "他将手插入水中。", "english": "He plunged his hand into the water.", "type": "句子", "keyWords": ["plunge"] },
    { "chinese": "她陷入了绝望的深渊。", "english": "She was plunged into the depth of despair.", "type": "句子", "keyWords": ["plunge"] },
    { "chinese": "prep. 加，加上；a. 正的；加的", "english": "plus", "type": "单词", "keyWords": [] },
    { "chinese": "8加7等于15。", "english": "Eight plus seven equals fifteen.", "type": "句子", "keyWords": ["plus"] },
    { "chinese": "她的成绩是B+。", "english": "She got a grade of B plus.", "type": "句子", "keyWords": ["plus"] },
    { "chinese": "n. [C]衣袋；a. 袖珍的", "english": "pocket", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]诗；诗篇；诗体文", "english": "poem", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]诗人；a. 诗的；有诗意的", "english": "poet；poetic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U](总称)诗；诗篇", "english": "poetry", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]点；小数点；尖(端)；观点；道理；v. 指；指出，指明", "english": "point", "type": "单词", "keyWords": [] },
    { "chinese": "持不同的观点", "english": "take/form a different point of view", "type": "短语", "keyWords": ["point"] },
    { "chinese": "转折点，转向处", "english": "a turning point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "在(临死…)之时", "english": "at the point of (death)", "type": "短语", "keyWords": ["point"] },
    { "chinese": "比尔把乔未讲完的故事接着往下讲。", "english": "Bill took up the story at the point where Joe had left off.", "type": "句子", "keyWords": ["point"] },
    { "chinese": "这时(=at this moment)", "english": "at this point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "要……时……；正要做某事时……", "english": "be on the point of doing sth. when...；be going/about to do sth. when...", "type": "短语", "keyWords": ["point"] },
    { "chinese": "没听清；不得要领；不懂妙处", "english": "miss the point of(his joke)", "type": "短语", "keyWords": ["point"] },
    { "chinese": "做某事没有意义", "english": "there's no point/sense in doing sth.", "type": "短语", "keyWords": ["point"] },
    { "chinese": "我不明白/理解让他自行其是有什么道理。", "english": "I didn't see the point of/any point in letting him have his own way.", "type": "句子", "keyWords": ["point"] },
    { "chinese": "离题", "english": "beside/off the point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "中肯；恰到好处", "english": "to the point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "说到要点；到正题上来", "english": "come to the point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "提出论点", "english": "make a point", "type": "短语", "keyWords": ["point"] },
    { "chinese": "指着", "english": "point at", "type": "短语", "keyWords": ["point"] },
    { "chinese": "指向", "english": "point to", "type": "短语", "keyWords": ["point"] },
    { "chinese": "指出", "english": "point out", "type": "短语", "keyWords": ["point"] },
    { "chinese": "这件事再讨论下去有什么意义呢?", "english": "What is the point of discussing this issue further?", "type": "句子", "keyWords": ["point"] },
    { "chinese": "a. 尖的", "english": "pointed", "type": "单词", "keyWords": [] },
    { "chinese": "有尖头的棍子", "english": "a pointed stick", "type": "短语", "keyWords": ["pointed"] },
    { "chinese": "n. [C]/[U]毒物；毒药；v. 毒死；使中毒；投毒于；vi. 下毒", "english": "poison", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有毒的；恶毒的，有恶意的", "english": "poisonous", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]极(点)；地极(区域)；电极；杆，电线杆", "english": "pole", "type": "单词", "keyWords": [] },
    { "chinese": "北/南极", "english": "the North/South Pole", "type": "短语", "keyWords": ["pole"] },
    { "chinese": "a. 两极的；极地的", "english": "polar", "type": "单词", "keyWords": [] },
    { "chinese": "北极熊", "english": "polar bear", "type": "短语", "keyWords": ["polar"] },
    { "chinese": "n. (作复数用)(the)警察，警方；警察部门", "english": "police", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]警察", "english": "policeman", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]政策；方针", "english": "policy", "type": "单词", "keyWords": [] },
    { "chinese": "开放政策", "english": "the open-door policy", "type": "短语", "keyWords": ["policy"] },
    { "chinese": "诚实才是上策。", "english": "Honesty is the best policy.", "type": "句子", "keyWords": ["policy"] },
    { "chinese": "v. 磨光；擦亮；润色，使完美；vi. 变得平滑、光亮", "english": "polish", "type": "单词", "keyWords": [] },
    { "chinese": "擦鞋", "english": "polish shoes", "type": "短语", "keyWords": ["polish"] },
    { "chinese": "修改润色文章", "english": "polish an article", "type": "短语", "keyWords": ["polish"] },
    { "chinese": "v. 磨光；擦亮；润色，使完美；vi. 变得平滑、光亮", "english": "polish", "type": "单词", "keyWords": [] },
    { "chinese": "擦鞋", "english": "polish shoes", "type": "短语", "keyWords": ["polish"] },
    { "chinese": "修改润色文章", "english": "polish an article", "type": "短语", "keyWords": ["polish"] },
    { "chinese": "用这块特殊的布能很容易把银器擦亮。", "english": "Silver polishes easily with this special cloth.", "type": "句子", "keyWords": ["polish"] },
    { "chinese": "a. 有礼貌的；有教养的；n. [U]有礼貌", "english": "polite；politeness", "type": "单词", "keyWords": [] },
    { "chinese": "a. 政治的", "english": "political", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]政治家；[贬]政客", "english": "politician", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]政治；(pl.)政治活动；*政治见解", "english": "politics", "type": "单词", "keyWords": [] },
    { "chinese": "进入政界", "english": "go into politics", "type": "短语", "keyWords": ["politics"] },
    { "chinese": "你的政见如何?", "english": "What are your politics?", "type": "句子", "keyWords": ["politics"] },
    { "chinese": "vt. 污染；弄脏；a. 被污染的；n. [U]污染", "english": "pollute；polluted；pollution", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]池塘", "english": "pond", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]水池；水塘；*一摊，一片", "english": "pool", "type": "单词", "keyWords": [] },
    { "chinese": "游泳池", "english": "a swimming pool", "type": "短语", "keyWords": ["pool"] },
    { "chinese": "一摊鲜血", "english": "a pool of blood", "type": "短语", "keyWords": ["pool"] },
    { "chinese": "a. 可怜的；贫穷的；差劲的", "english": "poor", "type": "单词", "keyWords": [] },
    { "chinese": "缺乏(反be rich in, be high in)", "english": "be poor in", "type": "短语", "keyWords": ["poor"] },
    { "chinese": "这个国家矿物不丰富。", "english": "The country is poor in minerals.", "type": "句子", "keyWords": ["poor"] },
    { "chinese": "不善于(反be good at, be clever at)", "english": "be poor at", "type": "短语", "keyWords": ["poor"] },
    { "chinese": "a. 大众的；流行的；通俗的；n. [U]流行音乐/歌曲；通俗艺术", "english": "pop", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]爆玉米花", "english": "popcorn", "type": "单词", "keyWords": [] },
    { "chinese": "a. 大众化的；流行的；广受欢迎的；n. [U]普及；流行", "english": "popular；popularity", "type": "单词", "keyWords": [] },
    { "chinese": "科普读物", "english": "popular science readings", "type": "短语", "keyWords": ["popular"] },
    { "chinese": "受……的欢迎", "english": "be popular with sb.", "type": "短语", "keyWords": ["popular"] },
    { "chinese": "n. [C]人口(数字)；(the)居住于某一地区的(全体)居民", "english": "population", "type": "单词", "keyWords": [] },
    { "chinese": "这个城市的人口是多少?", "english": "What is the population of this city?", "type": "句子", "keyWords": ["population"] },
    { "chinese": "全村的人都以旅游业为生。", "english": "The whole population of the village lives on tourism.", "type": "句子", "keyWords": ["population"] },
    { "chinese": "有……的人口", "english": "have a large/small population of...", "type": "短语", "keyWords": ["population"] },
    { "chinese": "vt. 居住于，聚居于…中", "english": "populate", "type": "单词", "keyWords": [] },
    { "chinese": "生活于大洋洋底的生物", "english": "creatures that populate the ocean depths", "type": "短语", "keyWords": ["populate"] },
    { "chinese": "n. [U]猪肉", "english": "pork", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]港口", "english": "port", "type": "单词", "keyWords": [] },
    { "chinese": "a. 便于携带的；轻便的", "english": "portable", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]门卫；搬运工", "english": "porter", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]一部分；(从整体上分离出来的)一份", "english": "portion", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]肖像；画像", "english": "portrait", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]位置；方位；职位；地位；处境；姿势", "english": "position", "type": "单词", "keyWords": [] },
    { "chinese": "处于适当的位置(近in place)", "english": "in position", "type": "短语", "keyWords": ["position"] },
    { "chinese": "在不适当的位置，不得其所(近out of place)", "english": "out of position", "type": "短语", "keyWords": ["position"] },
    { "chinese": "处于有利地位", "english": "in a favorable position", "type": "短语", "keyWords": ["position"] },
    { "chinese": "使…处于尴尬的境地", "english": "put...in a ridiculous position", "type": "短语", "keyWords": ["position"] },
    { "chinese": "(没)有权利或能力做某事", "english": "in a/no position to do sth.", "type": "短语", "keyWords": ["position"] },
    { "chinese": "我不能借钱给你。", "english": "I'm not in a position to lend you money.", "type": "句子", "keyWords": ["position"] },
    { "chinese": "a. 积极的；明确的；确实的；肯定的；正的", "english": "positive", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 占有，拥有；具有(品质等)；*(也常用于被动)控制，主宰", "english": "possess", "type": "单词", "keyWords": [] },
    { "chinese": "他整天就想着发财。", "english": "The thought of getting rich possessed him.", "type": "句子", "keyWords": ["possess"] },
    { "chinese": "他整天就想着发财。", "english": "He was possessed by the thought of getting rich.", "type": "句子", "keyWords": ["possess"] },
    { "chinese": "n. [U]占有；拥有；n. [C](常pl.)财产", "english": "possession", "type": "单词", "keyWords": [] },
    { "chinese": "获得/占有/购得某物", "english": "be in possession of sth.", "type": "短语", "keyWords": ["possession"] },
    { "chinese": "被某人占有；某物落入某人手中", "english": "be in the possession of sb.", "type": "短语", "keyWords": ["possession"] },
    { "chinese": "物落入某人手中", "english": "sth. comes into the possession of sb.", "type": "短语", "keyWords": ["possession"] },
    { "chinese": "某人得到/占有某物", "english": "sb. comes into possession of sth.", "type": "短语", "keyWords": ["possession"] },
    { "chinese": "a. 可能的", "english": "possible", "type": "单词", "keyWords": [] },
    { "chinese": "尽可能好的方法", "english": "the best possible method = the best method possible", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "尽可能早/快地", "english": "as soon as possible", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "如果可能的话", "english": "if (it is) possible", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "(某人)有可能做某事", "english": "It is possible (for sb.) to do sth.", "type": "句子", "keyWords": ["possible"] },
    { "chinese": "即使不见得会发生，至少是可能的", "english": "possible, if not probable", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "使……成为可能（宾语较长时后置）", "english": "make sth. possible (make possible sth.)", "type": "短语", "keyWords": ["possible"] },
    { "chinese": "n. [U] 可能（性）；[C] 可能发生的事物", "english": "possibility", "type": "单词", "keyWords": [] },
    { "chinese": "他不可能来的。", "english": "There is no possibility/ chance/ hope of his coming.", "type": "句子", "keyWords": ["possibility"] },
    { "chinese": "n. [C] 柱；标杆；职务，职位；（军警）岗位，哨位；[U] 邮政；vt. 张贴（布告等）；邮寄，投寄", "english": "post", "type": "单词", "keyWords": [] },
    { "chinese": "表示“在…之后”，例如：postgraduate 研究生，postwar 战后的", "english": "post-（前缀）", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 邮费，邮资", "english": "postage", "type": "单词", "keyWords": [] },
    { "chinese": "邮资已付", "english": "postage paid", "type": "短语", "keyWords": ["postage"] },
    { "chinese": "免付邮费", "english": "postage free", "type": "短语", "keyWords": ["postage"] },
    { "chinese": "a. 邮政的；邮局的", "english": "postal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 明信片", "english": "postcard", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [英] 邮政编码", "english": "postcode", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 海报，招贴；布告", "english": "poster", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 邮递员", "english": "postman", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 邮政局（或所）长", "english": "postmaster", "type": "单词", "keyWords": [] },
    { "chinese": "v. 推迟；使延期", "english": "postpone", "type": "单词", "keyWords": [] },
    { "chinese": "推迟做某事", "english": "postpone/ put off doing sth.", "type": "短语", "keyWords": ["postpone"] },
    { "chinese": "暂缓答复", "english": "postpone/ put off sending an answer", "type": "短语", "keyWords": ["postpone"] },
    { "chinese": "n. [C] 罐；壶", "english": "pot", "type": "单词", "keyWords": [] },
    { "chinese": "熔化锅；大熔炉，各种民族融合的国家/地方", "english": "a melting pot", "type": "短语", "keyWords": ["pot"] },
    { "chinese": "心急喝不了热粥。", "english": "A watched pot never boils.", "type": "句子", "keyWords": ["pot"] },
    { "chinese": "n. [C] (pl. potatoes) 土豆", "english": "potato", "type": "单词", "keyWords": [] },
    { "chinese": "红薯", "english": "a sweet potato", "type": "短语", "keyWords": ["potato"] },
    { "chinese": "沙发上的土豆；花过多时间坐着或躺着的人（常为看电视）", "english": "a couch potato", "type": "短语", "keyWords": ["potato"] },
    { "chinese": "棘手的问题，烫手的山芋；难对付的人", "english": "a hot potato", "type": "短语", "keyWords": ["potato"] },
    { "chinese": "a. 可能的；潜在的；n. [U] 可能性；潜在性；潜能", "english": "potential", "type": "单词", "keyWords": [] },
    { "chinese": "潜在的问题/危险", "english": "a potential problem/ danger", "type": "短语", "keyWords": ["potential"] },
    { "chinese": "n. [C] 英镑（符号）；磅", "english": "pound", "type": "单词", "keyWords": [] },
    { "chinese": "v. 倒；不断流出；吐出，倾诉；vi. 倒；下倾盆大雨；涌出/入", "english": "pour", "type": "单词", "keyWords": [] },
    { "chinese": "对（想法、计划）泼冷水", "english": "pour cold water on...", "type": "短语", "keyWords": ["pour"] },
    { "chinese": "吐出一肚子的苦水", "english": "pour out all one's bitternes", "type": "短语", "keyWords": ["pour"] },
    { "chinese": "涌入/出大厅", "english": "pour into/ out of the hall", "type": "短语", "keyWords": ["pour"] },
    { "chinese": "火上浇油；煽动情绪", "english": "pour oil on the flames", "type": "短语", "keyWords": ["pour"] },
    { "chinese": "不雨则已，一雨倾盆。祸不单行。", "english": "It never rains but it pours.", "type": "句子", "keyWords": ["pour"] },
    { "chinese": "n. [U] 贫穷，穷困；贫乏，不足", "english": "poverty", "type": "单词", "keyWords": [] },
    { "chinese": "过穷日子", "english": "live in poverty", "type": "短语", "keyWords": ["poverty"] },
    { "chinese": "n. [U] 粉末；火药；v. 给…搽粉；使成粉末", "english": "powder", "type": "单词", "keyWords": [] },
    { "chinese": "搽粉", "english": "powder one's face", "type": "短语", "keyWords": ["powder"] },
    { "chinese": "速溶奶粉", "english": "instant powdered milk", "type": "短语", "keyWords": ["powder"] },
    { "chinese": "n. [U] 力；电力；能力；权力；政权；[C] 强国；有势力的人；幂；vt. 给…提供动力，使开动", "english": "power", "type": "单词", "keyWords": [] },
    { "chinese": "上台；执政", "english": "come to power", "type": "短语", "keyWords": ["power"] },
    { "chinese": "在执政；在掌权", "english": "in power", "type": "短语", "keyWords": ["power"] },
    { "chinese": "有宣战的权力", "english": "have the power to declare war", "type": "短语", "keyWords": ["power"] },
    { "chinese": "我不能以更低的价格出售。", "english": "It is beyond my power to sell it cheaper.", "type": "句子", "keyWords": ["power"] },
    { "chinese": "核潜艇", "english": "a nuclear-powered submarine", "type": "短语", "keyWords": ["power"] },
    { "chinese": "100 的四次幂", "english": "the fourth power of 100", "type": "短语", "keyWords": ["power"] },
    { "chinese": "a. 强有力的；大功率的", "english": "powerful", "type": "单词", "keyWords": [] },
    { "chinese": "a. 无能为力的；无权力的", "english": "powerless", "type": "单词", "keyWords": [] },
    { "chinese": "a. 实践的；实用的；实际的", "english": "practical", "type": "单词", "keyWords": [] },
    { "chinese": "恶作剧", "english": "a practical joke", "type": "短语", "keyWords": ["practical"] },
    { "chinese": "a. 不切实际的；无用的", "english": "impractical", "type": "单词", "keyWords": [] },
    { "chinese": "理论上的", "english": "theoretical", "type": "单词", "keyWords": [] },
    { "chinese": "v. 练习；经常做；实习；实践；（医生、律师）开业", "english": "practise（英式）/ practice（美式）", "type": "单词", "keyWords": [] },
    { "chinese": "练习/常做某事", "english": "practise/ practice (doing) sth.", "type": "短语", "keyWords": ["practise"] },
    { "chinese": "我从前开业当律师/开业行医，但现在我教英文。", "english": "I used to practice law/ medicine, but now I teach English.", "type": "句子", "keyWords": ["practise"] },
    { "chinese": "n. [U] 练习；实践；[C] 习惯（做法）；习俗；（医生、律师、会计）开业", "english": "practice", "type": "单词", "keyWords": [] },
    { "chinese": "社会实践", "english": "social practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "在实践中；实际上；在不断练习中", "english": "in practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "将…付诸实施", "english": "put (a plan, a theory...) into practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "一个难以付诸实践的理论", "english": "a theory that is difficult to put into practice", "type": "句子", "keyWords": ["practice"] },
    { "chinese": "风俗，习惯", "english": "a common practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "按照国际惯例", "english": "according to the international practice", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "从事律师业", "english": "the practice of law", "type": "短语", "keyWords": ["practice"] },
    { "chinese": "v. 赞扬，表扬；n. [U] 赞扬，表扬；(pl.) 赞词，赞美之辞", "english": "praise", "type": "单词", "keyWords": [] },
    { "chinese": "因为某事表扬某人", "english": "praise sb. for sth.", "type": "短语", "keyWords": ["praise"] },
    { "chinese": "高度赞扬某人", "english": "sing sb's praises", "type": "短语", "keyWords": ["praise"] },
    { "chinese": "v. 祈祷；祈求；vt. 请求，恳求；[宗] 祈祷；n. 祷辞；祈望；[U] 祈祷", "english": "pray", "type": "单词", "keyWords": [] },
    { "chinese": "祈求做某事", "english": "pray to do sth.", "type": "短语", "keyWords": ["pray"] },
    { "chinese": "为了某事而祈祷", "english": "pray (to God) for sth.", "type": "短语", "keyWords": ["pray"] },
    { "chinese": "祈求某事", "english": "pray that...", "type": "短语", "keyWords": ["pray"] },
    { "chinese": "做祷告", "english": "say one's prayers", "type": "短语", "keyWords": ["pray"] },
    { "chinese": "表示“在…前；预先；前面”，如：prefix 前缀；prehistoric 史前的", "english": "pre-（前缀）", "type": "单词", "keyWords": [] },
    { "chinese": "a. 珍贵的；贵重的", "english": "precious", "type": "单词", "keyWords": [] },
    { "chinese": "宝石，钻石", "english": "precious stones", "type": "短语", "keyWords": ["precious"] },
    { "chinese": "a. 精确的；准确的", "english": "precise", "type": "单词", "keyWords": [] },
    { "chinese": "v. 预言；预报；n. [C]/[U] 预言", "english": "predict", "type": "单词", "keyWords": [] },
    { "chinese": "v. 宁可；更喜欢；n. 偏爱；[C] 更喜欢的东西", "english": "prefer", "type": "单词", "keyWords": [] },
    { "chinese": "n. 偏爱", "english": "preference", "type": "单词", "keyWords": [] },
    { "chinese": "偏爱某物", "english": "have a preference for sth.", "type": "短语", "keyWords": ["preference"] },
    { "chinese": "比起 B 来更喜欢 A", "english": "prefer (doing) A to (doing) B", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "宁愿…也不…", "english": "(would) prefer to do sth. rather than do sth. else = would rather do sth. than do sth. else", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "宁愿…", "english": "(would) prefer that... (do...)", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "我希望房间里有中央空调。", "english": "I prefer that the room (should) be fitted with central air conditioning.", "type": "句子", "keyWords": ["prefer"] },
    { "chinese": "宁愿；情愿", "english": "prefer doing/to do sth.", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "宁愿；情愿", "english": "would prefer to do sth.", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "宁愿；情愿", "english": "would prefer sb. to do...", "type": "短语", "keyWords": ["prefer"] },
    { "chinese": "A 比 B 好；A 比 B 更可取。", "english": "A is preferable to B.", "type": "句子", "keyWords": ["prefer"] },
    { "chinese": "a. 怀孕的，妊娠的；n. [U] 怀孕", "english": "pregnant", "type": "单词", "keyWords": [] },
    { "chinese": "怀着孩子/新思想", "english": "be pregnant with a child/ new ideas", "type": "短语", "keyWords": ["pregnant"] },
    { "chinese": "n. [U]/[C] 偏见，成见", "english": "prejudice", "type": "单词", "keyWords": [] },
    { "chinese": "对…抱有偏见", "english": "have a prejudice against...", "type": "短语", "keyWords": ["prejudice"] },
    { "chinese": "n. [U] 准备；预备；[C] 准备工作", "english": "preparation", "type": "单词", "keyWords": [] },
    { "chinese": "为某事做准备", "english": "make preparations for sth.", "type": "短语", "keyWords": ["preparation"] },
    { "chinese": "准备中", "english": "in preparation (for...)", "type": "短语", "keyWords": ["preparation"] },
    { "chinese": "v. 准备；预备", "english": "prepare", "type": "单词", "keyWords": [] },
    { "chinese": "(使某人)为…准备", "english": "prepare (sb.) for sth.", "type": "短语", "keyWords": ["prepare"] },
    { "chinese": "为…做好准备", "english": "be prepared for sth.", "type": "短语", "keyWords": ["prepare"] },
    { "chinese": "你还是做好最坏的打算。", "english": "Prepare yourself for the worst.", "type": "句子", "keyWords": ["prepare"] },
    { "chinese": "乐于/愿意做某事", "english": "be prepared/ ready to do sth.", "type": "短语", "keyWords": ["prepare"] },
    { "chinese": "n. [U] 在场；出席", "english": "presence", "type": "单词", "keyWords": [] },
    { "chinese": "请你务必出席。", "english": "Your presence is urgently required.", "type": "句子", "keyWords": ["presence"] },
    { "chinese": "在…面前", "english": "in the presence of sb./sth. (in sb's presence)", "type": "短语", "keyWords": ["presence"] },
    { "chinese": "她在生人/困难面前感到很不安。", "english": "She was ill at ease in the presence of strangers/ difficulties.", "type": "句子", "keyWords": ["presence"] },
    { "chinese": "n. [C] 礼物；(the present) 现在，目前；a. 现在的，目前的；存在的；出席的（作定语时后置）；vt. /prɪˈzent/ 赠送；授予；提供；呈现；描述", "english": "present", "type": "单词", "keyWords": [] },
    { "chinese": "现在，目前", "english": "at present (n.) = at the present time (a.)", "type": "短语", "keyWords": ["present"] },
    { "chinese": "眼前；暂时", "english": "for the present moment", "type": "短语", "keyWords": ["present"] },
    { "chinese": "现政府", "english": "the present government", "type": "短语", "keyWords": ["present"] },
    { "chinese": "出席", "english": "be present at...", "type": "短语", "keyWords": ["present"] },
    { "chinese": "目前的状况关系到所有在场的学生。", "english": "The present situation concerns all the students present.（后置定语）", "type": "句子", "keyWords": ["present"] },
    { "chinese": "赠送；提供", "english": "present sth. to sb. / present (provide) sb. with sth.", "type": "短语", "keyWords": ["present"] },
    { "chinese": "这份计划呈送给了艾登。", "english": "The plan was presented to Eden.", "type": "句子", "keyWords": ["present"] },
    { "chinese": "n. [U] 呈现；授课；赠送；上演；[C] 演示；介绍；陈述", "english": "presentation", "type": "单词", "keyWords": [] },
    { "chinese": "对…作陈述/演示", "english": "give a presentation of...", "type": "短语", "keyWords": ["presentation"] },
    { "chinese": "ad. 不久；即刻", "english": "presently", "type": "单词", "keyWords": [] },
    { "chinese": "v. 保护；保存（食品等）", "english": "preserve", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 保存", "english": "preservation", "type": "单词", "keyWords": ["preserve"] },
    { "chinese": "保存参考资料", "english": "preserve reference materials", "type": "短语", "keyWords": ["preserve"] },
    { "chinese": "维护秩序", "english": "preserve order (=keep order)", "type": "短语", "keyWords": ["preserve"] },
    { "chinese": "咸蛋；皮蛋", "english": "a preserved egg", "type": "短语", "keyWords": ["preserve"] },
    { "chinese": "n. [C] 总统；（公司等的）总裁，董事长", "english": "president", "type": "单词", "keyWords": [] },
    { "chinese": "a. 总统的", "english": "presidential", "type": "单词", "keyWords": ["president"] },
    { "chinese": "v. 压；压平；使贴紧；催促；n. [C] 压；印刷业；(the press) 新闻界，报业，报刊", "english": "press", "type": "单词", "keyWords": [] },
    { "chinese": "不要逼迫他们高谈科学和民主。", "english": "Don't press them to talk about science and democracy.", "type": "句子", "keyWords": ["press"] },
    { "chinese": "他向新闻界透露了那消息。", "english": "He leaked the news to the press.", "type": "句子", "keyWords": ["press"] },
    { "chinese": "记者招待会", "english": "a press/ news conference", "type": "短语", "keyWords": ["press"] },
    { "chinese": "(书报等) 付印", "english": "go to press", "type": "短语", "keyWords": ["press"] },
    { "chinese": "n. [U] 压；[C]/[U] 压力", "english": "pressure", "type": "单词", "keyWords": [] },
    { "chinese": "给…施压", "english": "put pressure on sb. or sth.", "type": "短语", "keyWords": ["pressure"] },
    { "chinese": "压力锅，高压锅", "english": "pressure cooker", "type": "短语", "keyWords": ["pressure"] },
    { "chinese": "在…的压力下", "english": "under the pressure of...", "type": "短语", "keyWords": ["pressure"] },
    { "chinese": "气/血压", "english": "air/ blood pressure", "type": "短语", "keyWords": ["pressure"] },
    { "chinese": "v. 假装", "english": "pretend", "type": "单词", "keyWords": [] },
    { "chinese": "假装做某事/在做某事/已做某事", "english": "pretend to do sth./ to be doing sth./ to have done sth.", "type": "短语", "keyWords": ["pretend"] },
    { "chinese": "a. 漂亮的，美丽的；可爱的，机灵的；ad. 相当；颇", "english": "pretty", "type": "单词", "keyWords": [] },
    { "chinese": "v. 阻止；妨碍（被动句中不省略 from）", "english": "prevent", "type": "单词", "keyWords": [] },
    { "chinese": "阻止某人/某物做某事", "english": "prevent sb./sth. (from) doing sth.", "type": "短语", "keyWords": ["prevent"] },
    { "chinese": "（近 stop/keep/hold back/ban/prohibit sb. from doing sth.；这些动词需要跟带 to 的不定式：forbid/permit/allow sb. to do sth.）", "english": "(近 stop/keep/hold back/ban/prohibit sb. from doing sth.；这些动词需要跟带 to 的不定式：forbid/permit/allow sb. to do sth.)", "type": "句子", "keyWords": ["prevent"] },
    { "chinese": "n. [U] 阻止；预防（可和 a 连用）；a. 预防性的", "english": "prevention", "type": "单词", "keyWords": ["prevent"] },
    { "chinese": "治病不如防病。", "english": "Prevention is better than cure.", "type": "句子", "keyWords": ["prevention"] },
    { "chinese": "v. 预习；预演；试映；预展", "english": "preview", "type": "单词", "keyWords": [] },
    { "chinese": "a. 前的", "english": "previous", "type": "单词", "keyWords": [] },
    { "chinese": "代表大会于我们访问的前一天召开。", "english": "The congress had assembled on the day previous to our visit.", "type": "句子", "keyWords": ["previous"] },
    { "chinese": "n. [U] 猎物，捕获物；捕食；vi. 捕食", "english": "prey", "type": "单词", "keyWords": [] },
    { "chinese": "捕食斑马", "english": "prey on zebras", "type": "短语", "keyWords": ["prey"] },
    { "chinese": "鹿被狮子捕食了。（比较：fall victim to）", "english": "The deer fell prey to the lion.", "type": "句子", "keyWords": ["prey"] },
    { "chinese": "n. [C] 价格；代价；vt. 给…定价或标价", "english": "price", "type": "单词", "keyWords": [] },
    { "chinese": "a. 无价的，极贵重的", "english": "priceless", "type": "单词", "keyWords": ["price"] },
    { "chinese": "无论花多大代价；无论如何", "english": "at any price", "type": "短语", "keyWords": ["price"] },
    { "chinese": "他决心不惜任何代价达到他的目的。", "english": "He will accomplish his purpose at any price.", "type": "句子", "keyWords": ["price"] },
    { "chinese": "自己不想要的东西，再便宜都觉得贵。", "english": "A thing you do not want is dear at any price.", "type": "句子", "keyWords": ["price"] },
    { "chinese": "以…价格", "english": "at the price of...", "type": "短语", "keyWords": ["price"] },
    { "chinese": "他们牺牲了很多人才赢得了战役的胜利。", "english": "They won the battle at the price of many lives.", "type": "句子", "keyWords": ["price"] },
    { "chinese": "每张票定价 200 元。", "english": "The tickets are priced at 200 yuan each.", "type": "句子", "keyWords": ["price"] },
    { "chinese": "n. [U] 自豪；骄傲；v. [pride oneself on/upon] 以…自豪；vi. 自豪；骄傲；得意", "english": "pride", "type": "单词", "keyWords": [] },
    { "chinese": "直到最近，该大学还以其友好的形象而自豪。", "english": "Until recently the university prided itself on its friendly image.", "type": "句子", "keyWords": ["pride"] },
    { "chinese": "伤害某人的自尊心", "english": "wound sb's pride", "type": "短语", "keyWords": ["pride"] },
    { "chinese": "为…感到自豪", "english": "take pride in...", "type": "短语", "keyWords": ["pride"] },
    { "chinese": "骄者必败。", "english": "Pride goes before a fall.", "type": "句子", "keyWords": ["pride"] },
    { "chinese": "a. 最初的；初等的；主要的；基本的", "english": "primary", "type": "单词", "keyWords": [] },
    { "chinese": "词的原义", "english": "primary meaning of a word", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "初等教育，小学教育", "english": "primary education", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "（指红、黄、蓝）基色，原色", "english": "primary colour", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "头等重要的事情", "english": "a matter of primary importance", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "首相；总理", "english": "prime minister", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "(广播或电视的) 黄金时段", "english": "prime time", "type": "短语", "keyWords": ["primary"] },
    { "chinese": "n. [C] 王子", "english": "prince", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 公主", "english": "princess", "type": "单词", "keyWords": ["prince"] },
    { "chinese": "a. 最重要的；主要的；n. [C] 为首者；校长", "english": "principal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 原理；原则", "english": "principle", "type": "单词", "keyWords": [] },
    { "chinese": "原则上", "english": "in principle", "type": "短语", "keyWords": ["principle"] },
    { "chinese": "根据既定的原则，按照规定/习惯", "english": "on principle", "type": "短语", "keyWords": ["principle"] },
    { "chinese": "v. 印刷；[计] 打印；打上（印记等）；铭记", "english": "print", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 印刷，印刷术；[C] 一次印刷", "english": "printing", "type": "单词", "keyWords": ["print"] },
    { "chinese": "n. [U]（时间、顺序上的）先，前；优先，重点；优先权；[C] 优先考虑的事", "english": "priority", "type": "单词", "keyWords": [] },
    { "chinese": "a. 优先的；在前/先的（to）", "english": "prior", "type": "单词", "keyWords": [] },
    { "chinese": "给予…优先权", "english": "give (first) priority to...", "type": "短语", "keyWords": ["priority"] },
    { "chinese": "在…方面比…享有优先权", "english": "have/enjoy priority over sb. in sth.", "type": "短语", "keyWords": ["priority"] },
    { "chinese": "予以最优先考虑的事", "english": "a first priority", "type": "短语", "keyWords": ["priority"] },
    { "chinese": "准备函数的上传工作要先于结束计算的过程。", "english": "The functions are available for uploading prior to finishing computation.", "type": "句子", "keyWords": ["priority"] },
    { "chinese": "n. [C]/[U] 监狱；监禁", "english": "prison", "type": "单词", "keyWords": [] },
    { "chinese": "v. 监禁", "english": "imprison", "type": "单词", "keyWords": ["prison"] },
    { "chinese": "在坐牢", "english": "be in prison", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "去坐牢", "english": "go to prison", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "战俘集中营", "english": "a prison camp", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "把某人关进监狱", "english": "throw sb. into prison/ put sb. in prison", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "(近 bar sb. in)", "english": "(近 bar sb. in)", "type": "句子", "keyWords": ["prison"] },
    { "chinese": "把某人关进监狱", "english": "send/take sb. to prison", "type": "短语", "keyWords": ["prison"] },
    { "chinese": "n. [C] 囚犯；俘虏", "english": "prisoner", "type": "单词", "keyWords": [] },
    { "chinese": "战俘（略作 P.O.W. 或 POW）", "english": "prisoner(s) of war", "type": "短语", "keyWords": ["prisoner"] },
    { "chinese": "被俘（只用单数，无冠词）", "english": "be taken prisoner", "type": "短语", "keyWords": ["prisoner"] },
    { "chinese": "除了当俘虏之外，唯一的选择就是战死。", "english": "The only alternative to being taken prisoner was to die fighting.", "type": "句子", "keyWords": ["prisoner"] },
    { "chinese": "a. 私人（用）的；私有的", "english": "private", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 隐私", "english": "privacy", "type": "单词", "keyWords": ["private"] },
    { "chinese": "秘密地；私下地", "english": "in private", "type": "短语", "keyWords": ["private"] },
    { "chinese": "n. [C] 奖品；奖赏；adj. 作为奖品的；vt. 重视，珍视；估价，评价", "english": "prize", "type": "单词", "keyWords": [] },
    { "chinese": "赢得头奖", "english": "win first prize", "type": "短语", "keyWords": ["prize"] },
    { "chinese": "莫言，真名管漠业，获2012年诺贝尔文学奖。", "english": "Mo Yan, whose real name is Guan Moye, won the 2012 Nobel Prize in Literature.", "type": "句子", "keyWords": ["prize"] },
    { "chinese": "n. [C] 赞成的观点", "english": "pro", "type": "单词", "keyWords": [] },
    { "chinese": "权衡正反两方面的意见", "english": "weigh the pros and cons", "type": "短语", "keyWords": ["pro"] },
    { "chinese": "a. 很可能发生的；大概的", "english": "probable", "type": "单词", "keyWords": [] },
    { "chinese": "成功是有可能的，但不一定。", "english": "Success is possible but hardly probable.", "type": "句子", "keyWords": ["probable"] },
    { "chinese": "极有可能…", "english": "It is probable to do sth./ that...", "type": "短语", "keyWords": ["probable"] },
    { "chinese": "ad. 大概；很可能，极有可能；或许", "english": "probably", "type": "单词", "keyWords": ["probable"] },
    { "chinese": "n. [C] 问题；习题", "english": "problem", "type": "单词", "keyWords": [] },
    { "chinese": "(表示乐意帮忙) 没问题；(回答感谢) 没关系", "english": "no problem", "type": "短语", "keyWords": ["problem"] },
    { "chinese": "n. [C] 程序；手续；(为完成某事采取的一系列) 步骤", "english": "procedure", "type": "单词", "keyWords": [] },
    { "chinese": "v. 继续进行（近 go on，后接 to sth./to do sth. 指做另一件事，接 with 则指开始做或继续做同一件事）；向前走（近 go, advance；后接 to a place）", "english": "proceed", "type": "单词", "keyWords": [] },
    { "chinese": "着手另一工作", "english": "proceed to the next business", "type": "短语", "keyWords": ["proceed"] },
    { "chinese": "v. 处理；加工；n. [C] 过程；(尤指工业上的) 生产过程，方法；程序", "english": "process", "type": "单词", "keyWords": [] },
    { "chinese": "数据处理", "english": "data processing", "type": "短语", "keyWords": ["process"] },
    { "chinese": "在进行中", "english": "in process", "type": "短语", "keyWords": ["process"] },
    { "chinese": "在…期间/过程中", "english": "in (the) process of...", "type": "短语", "keyWords": ["process"] },
    { "chinese": "v. 制造；生产；引起；拿出，出示；n. /ˈprɒdjuːs/ [U] 农产品", "english": "produce", "type": "单词", "keyWords": [] },
    { "chinese": "监制一出舞台剧", "english": "produce a stage play", "type": "短语", "keyWords": ["produce"] },
    { "chinese": "提出证据", "english": "produce evidence", "type": "短语", "keyWords": ["produce"] },
    { "chinese": "手伸进口袋，拿出了一盒火柴", "english": "reach into a pocket and produce a packet of matches", "type": "句子", "keyWords": ["produce"] },
    { "chinese": "土特产（品）", "english": "the native produce", "type": "短语", "keyWords": ["produce"] },
    { "chinese": "n. [C] 产品", "english": "product", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 生产；产量；出示", "english": "production", "type": "单词", "keyWords": ["product"] },
    { "chinese": "a. 生产的；富有成效的；多产的", "english": "productive", "type": "单词", "keyWords": ["product"] },
    { "chinese": "多产作家/高产的农场", "english": "a productive writer/ farm", "type": "短语", "keyWords": ["productive"] },
    { "chinese": "n. [C] 职业", "english": "profession", "type": "单词", "keyWords": [] },
    { "chinese": "职业是…", "english": "by profession", "type": "短语", "keyWords": ["profession"] },
    { "chinese": "他职业是电气技师。", "english": "He is an electrical engineer by profession.", "type": "句子", "keyWords": ["profession"] },
    { "chinese": "n. [C] 专业人员；a. 职业（性）的，专业的；内行的", "english": "professional", "type": "单词", "keyWords": [] },
    { "chinese": "v. (使) 职业化", "english": "professionalize", "type": "单词", "keyWords": ["professional"] },
    { "chinese": "n. [C] 大学教授", "english": "professor", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 利润；收益；n. [U] 好处；益处；v. (使) 得益；(使) 赚钱", "english": "profit", "type": "单词", "keyWords": [] },
    { "chinese": "出售某物而获利", "english": "sell sth. at a profit", "type": "短语", "keyWords": ["profit"] },
    { "chinese": "从…中获利…", "english": "make a profit of $,000 from...", "type": "短语", "keyWords": ["profit"] },
    { "chinese": "受益于（他的忠告）", "english": "profit from (his advice)", "type": "短语", "keyWords": ["profit"] },
    { "chinese": "a. 有利的；有赢利的", "english": "profitable", "type": "单词", "keyWords": ["profit"] },
    { "chinese": "n. [C] 节目，节目单；计划，方案；程序；v. 为…安排节目或制定计划；使按预定计划或步骤工作；[计] 为…编制程序", "english": "program(me)", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] [计] 编程；(广播等) 节目编排", "english": "programming", "type": "单词", "keyWords": ["program"] },
    { "chinese": "n. [U] 进步；进展；前进，行进；vi. /prəˈgres/ 前进；进展", "english": "progress", "type": "单词", "keyWords": [] },
    { "chinese": "a. 进步的；前进的", "english": "progressive", "type": "单词", "keyWords": ["progress"] },
    { "chinese": "在（英语）方面取得进步", "english": "make progress in (his English)", "type": "短语", "keyWords": ["progress"] },
    { "chinese": "在进展中", "english": "in progress", "type": "短语", "keyWords": ["progress"] },
    { "chinese": "v. 禁止；阻止（辨析见 ban）", "english": "prohibit", "type": "单词", "keyWords": [] },
    { "chinese": "妨碍/阻止某事", "english": "prohibit (doing) sth.", "type": "短语", "keyWords": ["prohibit"] },
    { "chinese": "阻止某人做某事", "english": "prohibit sb. from doing sth.", "type": "短语", "keyWords": ["prohibit"] },
    { "chinese": "(近 keep/hold back/prevent/ban/stop sb. from doing sth.，这些动词需要跟带 to 的不定式：forbid/permit/allow sb. to do sth.)", "english": "(近 keep/hold back/prevent/ban/stop sb. from doing sth.，这些动词需要跟带 to 的不定式：forbid/permit/allow sb. to do sth.)", "type": "句子", "keyWords": ["prohibit"] },
    { "chinese": "n. [C] 计划，规划，方案；工程，企业；科研项目；(学校的) 课题；作业；v. /prəˈdʒekt/ 计划，规划；放映，投射；提出", "english": "project", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 放映机；投影仪", "english": "projector", "type": "单词", "keyWords": ["project"] },
    { "chinese": "推出一个更好的系统", "english": "project a better system", "type": "短语", "keyWords": ["project"] },
    { "chinese": "将一束光投射到墙上", "english": "project a beam of light on the wall", "type": "短语", "keyWords": ["project"] },
    { "chinese": "n. [C] 允诺；诺言；v. /ˈprɒmɪs/ [U] 有希望；可能会；a. 有希望的，有前途的", "english": "promise", "type": "单词", "keyWords": [] },
    { "chinese": "许诺某人某物", "english": "promise sb. sth.", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "答应去做某事", "english": "promise to do sth.", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "答应某人要去做某事", "english": "promise sb. to do sth.", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "答应（某人）某事", "english": "promise (sb.) that...", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "我保证不久你就会见到他们。", "english": "I promise you shall see them again before long.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "我敢肯定。说句老实话。我警告你。", "english": "I promise you.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "晴朗的天空预示好天气。", "english": "The clear sky promises fine weather.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "明天有希望是个好天。", "english": "It promises to be fine tomorrow.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "云预示着有可能下雨。", "english": "The clouds promise rain.", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "一定有发展的企业", "english": "an enterprise that promises well", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "违背诺言", "english": "break a promise", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "履行诺言", "english": "carry out one's promise", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "许下诺言", "english": "make/give a promise", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "守约", "english": "stick to/keep one's promise/word", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "大有希望的，前程远大的", "english": "of (great) promise", "type": "短语", "keyWords": ["promise"] },
    { "chinese": "一个很有前途的年轻演员（=a promising young player）", "english": "a young player of great promise", "type": "句子", "keyWords": ["promise"] },
    { "chinese": "v. 提升（to）；使（学生）升级；促进；促销（产品）", "english": "promote", "type": "单词", "keyWords": [] }
];
