const qgl1_15 = [
    { "chinese": "art. 一(个、件…);同一(个…);任何一(个…);每一(个…);某一", "english": "a", "type": "单词", "keyWords": [] },
    { "chinese": "art. 一(个、件…);同一(个…);任何一(个…);每一(个…);某一", "english": "an", "type": "单词", "keyWords": [] },
    { "chinese": "一张8英镑的优惠券", "english": "an 8-pound coupon", "type": "短语", "keyWords": ["an"] },
    { "chinese": "一轮新月", "english": "a new moon", "type": "短语", "keyWords": ["a"] },
    { "chinese": "一年两次", "english": "twice a year", "type": "短语", "keyWords": ["a"] },
    { "chinese": "一天5美元", "english": "$5 a day (=per day)", "type": "短语", "keyWords": ["a"] },
    { "chinese": "多么（接单数名词）", "english": "such/what a/a.n.../", "type": "短语", "keyWords": ["a"] },
    { "chinese": "这样一个物品/人", "english": "such a thing/ man", "type": "短语", "keyWords": ["a"] },
    { "chinese": "有些/非常难管的孩子（接单数名词）", "english": "rather/ quite a difficult child", "type": "短语", "keyWords": ["a"] },
    { "chinese": "许多父母…（注意many a后面接单数名词，并且与单数动词连用）", "english": "Many a parent is...", "type": "句子", "keyWords": ["a"] },
    { "chinese": "苏格拉底式的智慧", "english": "the wisdom of a Socrates", "type": "短语", "keyWords": ["a"] },
    { "chinese": "特朗普的搞笑视频", "english": "videos of a funny Trump", "type": "短语", "keyWords": ["a"] },
    { "chinese": "一两年", "english": "a year or two (= one or two years)", "type": "短语", "keyWords": ["a"] },
    { "chinese": "他们是同龄人。", "english": "They are of an age.", "type": "句子", "keyWords": ["an"] },
    { "chinese": "志趣相投的人", "english": "birds of a feather", "type": "短语", "keyWords": ["a"] },
    { "chinese": "请一次给我两个。", "english": "Please give me two at a time.", "type": "句子", "keyWords": ["a"] },
    { "chinese": "连续第五个年份的干旱预计将对加利福尼亚州的经济产生巨大影响。", "english": "A fifth year of drought is expected to have dramatic effects on California's economy.", "type": "句子", "keyWords": ["a"] },
    { "chinese": "v. 放弃；抛弃；遗弃", "english": "abandon", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 放弃；抛弃", "english": "abandonment", "type": "单词", "keyWords": ["abandon"] },
    { "chinese": "放弃沉船/尝试/希望/构思", "english": "abandon the sinking ship/ the attempt/ the hope/ the design", "type": "短语", "keyWords": ["abandon"] },
    { "chinese": "那个木匠遗弃了他的妻子和孩子。", "english": "The carpenter abandoned his wife and child.", "type": "句子", "keyWords": ["abandon"] },
    { "chinese": "n. [C][U] 能力；本领", "english": "ability", "type": "单词", "keyWords": [] },
    { "chinese": "有才干的人", "english": "a man of ability", "type": "短语", "keyWords": ["ability"] },
    { "chinese": "能…", "english": "have the ability to do sth.", "type": "短语", "keyWords": ["ability"] },
    { "chinese": "对多目标的分辨能力", "english": "an ability to distinguish between multiple targets", "type": "短语", "keyWords": ["ability"] },
    { "chinese": "附在动词或名词后构成形容词：①表示“可…的；能…的”；②表示“易…的；倾向于…的”；③表示“提供…的；与…有关的”", "english": "able", "type": "单词", "keyWords": [] },
    { "chinese": "有能力的，聪明能干的", "english": "able", "type": "单词", "keyWords": [] },
    { "chinese": "能干的人们", "english": "able men", "type": "短语", "keyWords": ["able"] },
    { "chinese": "成功地做成某事", "english": "was/ were able to do sth.", "type": "短语", "keyWords": ["able"] },
    { "chinese": "a. 反常的；异常的", "english": "abnormal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U] 反常；异常；畸形", "english": "abnormality", "type": "单词", "keyWords": ["abnormal"] },
    { "chinese": "我们一直都认为这样的反常现象不会持续很久。", "english": "Never do we think such an abnormal phenomenon will last long.", "type": "句子", "keyWords": ["abnormal"] },
    { "chinese": "prep. 在车（船、飞机）上；ad. 上车（船、飞机等）；在车（船、飞机）上", "english": "aboard", "type": "单词", "keyWords": [] },
    { "chinese": "她上了飞机。", "english": "She went aboard the plane.", "type": "句子", "keyWords": ["aboard"] },
    { "chinese": "欢迎登机。", "english": "(You are) Welcome aboard.", "type": "句子", "keyWords": ["aboard"] },
    { "chinese": "他已上车/船/飞机了。", "english": "He has gone aboard.", "type": "句子", "keyWords": ["aboard"] },
    { "chinese": "请大家上船/登机。", "english": "All aboard.", "type": "句子", "keyWords": ["aboard"] },
    { "chinese": "ad. 附近；大约；转向；周围，四周，到处；prep. 关于；大约；在…周围（无固定方向）；在…附近", "english": "about", "type": "单词", "keyWords": [] },
    { "chinese": "四处漂泊，无处可去", "english": "wander about with no place to go", "type": "短语", "keyWords": ["about"] },
    { "chinese": "他把书扔得到处都是。", "english": "He left books lying about/ dropped books about.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "这消息正在传开。", "english": "The news is going about.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "工作差不多要完成了。", "english": "The job is about done.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "…怎么样？/怎么办？", "english": "What/ How about (doing) sth.?", "type": "短语", "keyWords": ["about"] },
    { "chinese": "准备；将要；正打算", "english": "be about to do sth.", "type": "短语", "keyWords": ["about"] },
    { "chinese": "我正想说话，奥巴马就插嘴了。", "english": "I was about to speak when Obama cut in.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "…的时候了（表虚拟语气，也可用should）", "english": "It's about/ high time (+过去时分句).", "type": "短语", "keyWords": ["about"] },
    { "chinese": "该是你去找更有效治疗深度烧伤疗法的时候了。", "english": "It's about time you found/ should find a more effective therapy for deep burns.", "type": "句子", "keyWords": ["about"] },
    { "chinese": "prep. 在…上面；a. 在…上面；ad. 在上面；向上面；n. [U] 上文", "english": "above", "type": "单词", "keyWords": [] },
    { "chinese": "看前面例子。", "english": "See the examples given above.", "type": "句子", "keyWords": ["above"] },
    { "chinese": "战士应该把荣誉看得高于生命。", "english": "A soldier should value honour above his life.", "type": "句子", "keyWords": ["above"] },
    { "chinese": "这个我理解不了。", "english": "It is above my comprehension/ understanding.", "type": "句子", "keyWords": ["above"] },
    { "chinese": "最重要的是，首先；尤其是", "english": "above all", "type": "短语", "keyWords": ["above"] },
    { "chinese": "海平面以上", "english": "above the sea level", "type": "短语", "keyWords": ["above"] },
    { "chinese": "以上提到的问题", "english": "the above-mentioned problems", "type": "短语", "keyWords": ["above"] },
    { "chinese": "由于上述原因", "english": "for the above reasons", "type": "短语", "keyWords": ["above"] },
    { "chinese": "比一般的要好，中上", "english": "above the average", "type": "短语", "keyWords": ["above"] },
    { "chinese": "ad. 在国外；往国外", "english": "abroad", "type": "单词", "keyWords": [] },
    { "chinese": "国内外新闻", "english": "the news at home and abroad", "type": "短语", "keyWords": ["abroad"] },
    { "chinese": "出国/去国外旅游", "english": "go/ get/ travel abroad", "type": "短语", "keyWords": ["abroad"] },
    { "chinese": "去国外留学", "english": "study abroad", "type": "短语", "keyWords": ["abroad"] },
    { "chinese": "n. [U]（可和of连用）不在，缺席；缺乏，没有，不存在", "english": "absence", "type": "单词", "keyWords": [] },
    { "chinese": "黑暗就是没有光亮。", "english": "Darkness is the absence of light.", "type": "句子", "keyWords": ["absence"] },
    { "chinese": "当他不在此地而在意大利的时候", "english": "in/ during his absence in Italy", "type": "短语", "keyWords": ["absence"] },
    { "chinese": "汤姆离开公司三个礼拜后，终于回来了。", "english": "Tom finally returned after an absence of three weeks from the company.", "type": "句子", "keyWords": ["absence"] },
    { "chinese": "a. 缺席的；不在场的；缺乏的", "english": "absent", "type": "单词", "keyWords": [] },
    { "chinese": "a. 茫然的；心不在焉的", "english": "absent-minded", "type": "单词", "keyWords": ["absent"] },
    { "chinese": "缺席，不在", "english": "be absent from", "type": "短语", "keyWords": ["absent"] },
    { "chinese": "那个代表没有出席年度大会。", "english": "The representative was absent from the annual conference.", "type": "句子", "keyWords": ["absent"] },
    { "chinese": "a. 完全的；不容置疑的；绝对的", "english": "absolute", "type": "单词", "keyWords": [] },
    { "chinese": "完全无知", "english": "absolute ignorance", "type": "短语", "keyWords": ["absolute"] },
    { "chinese": "ad. 完全地；极其；[美俚]（用于答话）是，当然是，正是如此", "english": "absolutely", "type": "单词", "keyWords": ["absolute"] },
    { "chinese": "这绝对不可能。", "english": "It's absolutely impossible.", "type": "句子", "keyWords": ["absolutely"] },
    { "chinese": "“你是这样想的吗？”“当然是。”", "english": '"Do you think so?" "Absolutely."', "type": "句子", "keyWords": ["absolutely"] },
    { "chinese": "v. 吸收；吸引…的注意力；接受", "english": "absorb", "type": "单词", "keyWords": [] },
    { "chinese": "吸引某人的注意力", "english": "absorb one's attention", "type": "短语", "keyWords": ["absorb"] },
    { "chinese": "从空气中吸收水分", "english": "absorb moisture from the air", "type": "短语", "keyWords": ["absorb"] },
    { "chinese": "专心致志于", "english": "be absorbed in", "type": "短语", "keyWords": ["absorb"] },
    { "chinese": "他专心读书。", "english": "He is absorbed in his study.", "type": "句子", "keyWords": ["absorb"] },
    { "chinese": "他专心致志工作，到了废寝忘食的地步。", "english": "Absorbed in the work, he neglected food and sleep.", "type": "句子", "keyWords": ["absorb"] },
    { "chinese": "n. [U] 吸收；专心致志（in）", "english": "absorption", "type": "单词", "keyWords": ["absorb"] },
    { "chinese": "显而易见，他专心于研究。", "english": "His complete absorption in study can be clearly seen.", "type": "句子", "keyWords": ["absorption"] },
    { "chinese": "a. 抽象的；n. [C] 摘要，梗概；v. 摘要；提炼；抽象化", "english": "abstract", "type": "单词", "keyWords": [] },
    { "chinese": "科技文摘，科学文摘", "english": "science abstract", "type": "短语", "keyWords": ["abstract"] },
    { "chinese": "从矿砂中提炼金属", "english": "abstract metal from ore", "type": "短语", "keyWords": ["abstract"] },
    { "chinese": "a. 大量的，充足的；丰富的，充裕的", "english": "abundant", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 丰富，充裕", "english": "abundance", "type": "单词", "keyWords": ["abundant"] },
    { "chinese": "a. 学院的；学术的，理论的", "english": "academic", "type": "单词", "keyWords": [] },
    { "chinese": "学年", "english": "academic year", "type": "短语", "keyWords": ["academic"] },
    { "chinese": "学术研究", "english": "academic research", "type": "短语", "keyWords": ["academic"] },
    { "chinese": "n. [C]（高等）专科院校，研究院，学会，学术团体，学院", "english": "academy", "type": "单词", "keyWords": ["academic"] },
    { "chinese": "n. [C] 重音；口音，腔调；重音符", "english": "accent", "type": "单词", "keyWords": [] },
    { "chinese": "爱尔兰腔调", "english": "an Irish accent", "type": "短语", "keyWords": ["accent"] },
    { "chinese": "v. 接受；认可", "english": "accept", "type": "单词", "keyWords": [] },
    { "chinese": "a. 公认的", "english": "accepted", "type": "单词", "keyWords": ["accept"] },
    { "chinese": "承受某人的命运", "english": "accept one's fate", "type": "短语", "keyWords": ["accept"] },
    { "chinese": "从…接受…", "english": "accept sth. from sb.", "type": "短语", "keyWords": ["accept"] },
    { "chinese": "他们接收我为俱乐部新成员。", "english": "They accepted me as a new member of the club.", "type": "句子", "keyWords": ["accept"] },
    { "chinese": "这样的风俗被普遍认同。", "english": "Such customs are widely accepted.", "type": "句子", "keyWords": ["accept"] },
    { "chinese": "人们普遍认为…", "english": "It is widely accepted that...", "type": "短语", "keyWords": ["accept"] },
    { "chinese": "作为公认的事实", "english": "an accepted fact", "type": "短语", "keyWords": ["accepted"] },
    { "chinese": "a. 可接受的", "english": "acceptable", "type": "单词", "keyWords": ["accept"] },
    { "chinese": "a. 不可接受的", "english": "unacceptable", "type": "单词", "keyWords": ["accept"] },
    { "chinese": "n. [C][U] 接受；承诺；容忍；赞同；相信", "english": "acceptance", "type": "单词", "keyWords": ["accept"] },
    { "chinese": "n. [U] 接近/进入的机会；享用权；通路；访问，入门；vt. [计] 存取；接近", "english": "access", "type": "单词", "keyWords": [] },
    { "chinese": "到镇上唯一的通路是经过这座桥。", "english": "The only access to the town is the bridge.", "type": "句子", "keyWords": ["access"] },
    { "chinese": "接近…的机会，进入…的权利", "english": "have/ get/ gain access to", "type": "短语", "keyWords": ["access"] },
    { "chinese": "5岁孩童中只有40%能享受学前教育。", "english": "Only 40% of 5-year-olds have access to preschool education.", "type": "句子", "keyWords": ["access"] },
    { "chinese": "市民可以免费使用图书馆。", "english": "Citizens may have free access to the library.", "type": "句子", "keyWords": ["access"] },
    { "chinese": "易于接近的人，平易近人的人", "english": "a man of easy access (=an accessible man)", "type": "短语", "keyWords": ["access"] },
    { "chinese": "容易/难接近", "english": "be easy/ hard of access", "type": "短语", "keyWords": ["access"] },
    { "chinese": "a. 容易达到的；易接近的", "english": "accessible", "type": "单词", "keyWords": ["access"] },
    { "chinese": "地区通邮率超过95%。", "english": "Over 95% of the district is accessible to postal services.", "type": "句子", "keyWords": ["accessible"] },
    { "chinese": "n. [C] 意外事件；事故", "english": "accident", "type": "单词", "keyWords": [] },
    { "chinese": "碰上/遭遇车祸/交通事故", "english": "meet with/ have a car/ traffic accident", "type": "短语", "keyWords": ["accident"] },
    { "chinese": "意外地", "english": "by accident/ chance (=accidentally)", "type": "短语", "keyWords": ["accident"] },
    { "chinese": "a. 偶然的；意外的", "english": "accidental", "type": "单词", "keyWords": ["accident"] },
    { "chinese": "v. 供给…住宿（或膳宿）；容纳", "english": "accommodate", "type": "单词", "keyWords": [] },
    { "chinese": "客人们受到很好的招待。", "english": "The guests are well accommodated.", "type": "句子", "keyWords": ["accommodate"] },
    { "chinese": "留（某人）住一夜", "english": "accommodate (sb.) for the night", "type": "短语", "keyWords": ["accommodate"] },
    { "chinese": "n. [U] 住处；膳宿；方便设施", "english": "accommodation", "type": "单词", "keyWords": ["accommodate"] },
    { "chinese": "我们会给您提供免费住宿。", "english": "We will offer you free accommodation.", "type": "句子", "keyWords": ["accommodation"] },
    { "chinese": "您的食宿将由我们来负责。", "english": "We will be responsible for your meals and accommodation.", "type": "句子", "keyWords": ["accommodation"] },
    { "chinese": "v. 陪伴，陪同；为…伴奏/伴唱；伴随；vi. 伴奏；伴唱", "english": "accompany", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 伴奏，伴随；陪伴物", "english": "accompaniment", "type": "单词", "keyWords": ["accompany"] },
    { "chinese": "伴随着打雷的闪电", "english": "lightning accompanied with thunder", "type": "短语", "keyWords": ["accompany"] },
    { "chinese": "给歌手伴奏", "english": "accompany the singer", "type": "短语", "keyWords": ["accompany"] },
    { "chinese": "他陪朋友去看电影。", "english": "He accompanied his friend to the film.", "type": "句子", "keyWords": ["accompany"] },
    { "chinese": "疾病常随饥荒而来。", "english": "Disease is often an accompaniment of famine.", "type": "句子", "keyWords": ["accompaniment"] },
    { "chinese": "v. 完成；达到；实现", "english": "accomplish", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U][C] 完成；成就", "english": "accomplishment", "type": "单词", "keyWords": ["accomplish"] },
    { "chinese": "实现目标/完成使命", "english": "accomplish one's purpose/ a goal/ one's mission", "type": "短语", "keyWords": ["accomplish"] },
    { "chinese": "一事无成/完成了一件任务", "english": "accomplish nothing/ a task", "type": "短语", "keyWords": ["accomplish"] },
    { "chinese": "a. 相符的，相应的", "english": "according", "type": "单词", "keyWords": [] },
    { "chinese": "根据…", "english": "according to", "type": "短语", "keyWords": ["according"] },
    { "chinese": "ad. 于是，因此；相应地", "english": "accordingly", "type": "单词", "keyWords": ["according"] },
    { "chinese": "n. [U] 一致，和谐；符合", "english": "accordance", "type": "单词", "keyWords": ["according"] },
    { "chinese": "根据条例行事", "english": "act in accordance with the rules", "type": "短语", "keyWords": ["accordance"] },
    { "chinese": "v. 说明，提出理由（for）；报账；（在数量、比例方面）占（for）；vt. 把…视作；把…归因于（to）；n. [C] 说明，陈述；理由；账户；计算，估计", "english": "account", "type": "单词", "keyWords": [] },
    { "chinese": "对…作出（满意的）解释；占", "english": "account for", "type": "短语", "keyWords": ["account"] },
    { "chinese": "延期那么久是因为坏天气。", "english": "Bad weather accounted for the long delay.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "他因为生病而缺席。", "english": "His illness accounted for his absence.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "电脑占了这个国家商业用电的5%。", "english": "Computers account for 5% of the country's commercial electricity consumption.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "认为自己是个成功人士", "english": "account oneself (to be) a success", "type": "短语", "keyWords": ["account"] },
    { "chinese": "把…归结于，把…归因于…", "english": "account sth. to...", "type": "短语", "keyWords": ["account"] },
    { "chinese": "归结到那个英雄身上的许多美德", "english": "the many virtues accounted to that hero", "type": "短语", "keyWords": ["account"] },
    { "chinese": "在银行开户", "english": "open/ get an account with the bank", "type": "短语", "keyWords": ["account"] },
    { "chinese": "你是何时在我们银行开账户的？", "english": "When did you get an account with us?", "type": "句子", "keyWords": ["account"] },
    { "chinese": "说明，叙述", "english": "give an account of (=describe)", "type": "短语", "keyWords": ["account"] },
    { "chinese": "因为，由于", "english": "on account of/ due to/ owing to/ because of/ as a result of/ thanks to", "type": "短语", "keyWords": ["account"] },
    { "chinese": "由于天气原因，比赛延期进行。", "english": "The match was postponed on account of the weather.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "决不可以，切勿", "english": "on no account/ by no means/ in no case/ under no condition/ on no occasion/ under no circumstances/ in no way", "type": "短语", "keyWords": ["account"] },
    { "chinese": "你绝不可以怀疑他撒谎。", "english": "On no account must you suspect him of lying.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "考虑进去", "english": "take...into account/ consideration", "type": "短语", "keyWords": ["account"] },
    { "chinese": "我们应该考虑父母的建议，反之亦然。", "english": "We should take into account the proposals of our parents and vice versa.", "type": "句子", "keyWords": ["account"] },
    { "chinese": "n. [C] 会计人员", "english": "accountant", "type": "单词", "keyWords": ["account"] },
    { "chinese": "n. [U] 会计学；清算账目", "english": "accounting", "type": "单词", "keyWords": ["account"] },
    { "chinese": "a. 准确的（与事实、标准没出入）；精确的；正确无误的", "english": "accurate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 准确性；精确性", "english": "accuracy", "type": "单词", "keyWords": ["accurate"] },
    { "chinese": "准确地", "english": "with accuracy", "type": "短语", "keyWords": ["accuracy"] },
    { "chinese": "v. 指责；控告", "english": "accuse", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U][C] 指责", "english": "accusation", "type": "单词", "keyWords": ["accuse"] },
    { "chinese": "指责/控告某人某事", "english": "accuse sb. of sth. (=charge sb. with sth.)", "type": "短语", "keyWords": ["accuse"] },
    { "chinese": "他们控告他受贿。", "english": "They accused him of taking bribes.", "type": "句子", "keyWords": ["accuse"] },
    { "chinese": "被告，被控诉者", "english": "the accused", "type": "短语", "keyWords": ["accuse"] },
    { "chinese": "控告者，指责者", "english": "the accuser", "type": "短语", "keyWords": ["accuse"] },
    { "chinese": "被告人不承认所控之罪。", "english": "The accused (man) denied the charge.", "type": "句子", "keyWords": ["accuse"] },
    { "chinese": "v. 使习惯于", "english": "accustom", "type": "单词", "keyWords": [] },
    { "chinese": "使自己习惯于（做）某事", "english": "accustom oneself to (doing) sth.", "type": "短语", "keyWords": ["accustom"] },
    { "chinese": "我已习惯于长时间工作。", "english": "I have accustomed myself to working long hours.", "type": "句子", "keyWords": ["accustom"] },
    { "chinese": "a. 适应了的；习惯的", "english": "accustomed", "type": "单词", "keyWords": ["accustom"] },
    { "chinese": "习惯于", "english": "be/ become/ grow/ get accustomed to (doing) sth.", "type": "短语", "keyWords": ["accustomed"] },
    { "chinese": "我的眼睛很快适应了黑暗。", "english": "My eyes soon grew accustomed to the darkness.", "type": "句子", "keyWords": ["accustomed"] },
    { "chinese": "v. （持续而隐隐地）作痛；n. [C] 疼痛；酸痛", "english": "ache", "type": "单词", "keyWords": [] },
    { "chinese": "我全身骨头都痛了。", "english": "My bones ache.", "type": "句子", "keyWords": ["ache"] },
    { "chinese": "她感到肩膀隐隐作痛。", "english": "She felt an ache in her shoulder.", "type": "句子", "keyWords": ["ache"] },
    { "chinese": "v. （常强调通过努力）完成，实现；达到，得到", "english": "achieve", "type": "单词", "keyWords": [] },
    { "chinese": "一事无成/达到目的/取得成功", "english": "achieve nothing/ one's purpose/ success", "type": "短语", "keyWords": ["achieve"] },
    { "chinese": "n. [U][C] 成就；成绩", "english": "achievement", "type": "单词", "keyWords": ["achieve"] },
    { "chinese": "达到目的", "english": "the achievement of one's object", "type": "短语", "keyWords": ["achievement"] },
    { "chinese": "学业成绩；学术成就", "english": "academic achievements", "type": "短语", "keyWords": ["achievement"] },
    { "chinese": "a. 酸的；n. [U][C] [化] 酸", "english": "acid", "type": "单词", "keyWords": [] },
    { "chinese": "酸雨", "english": "acid rain", "type": "短语", "keyWords": ["acid"] },
    { "chinese": "v. 承认；告知/确认收到（信等）；对…表示感谢", "english": "acknowledge", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U][C] 承认，确认", "english": "acknowledgement", "type": "单词", "keyWords": ["acknowledge"] },
    { "chinese": "承认失败", "english": "acknowledge one's defeat", "type": "短语", "keyWords": ["acknowledge"] },
    { "chinese": "确认收到他的来信", "english": "acknowledge his letter", "type": "短语", "keyWords": ["acknowledge"] },
    { "chinese": "大家公认…", "english": "It is universally acknowledged that...", "type": "短语", "keyWords": ["acknowledge"] },
    { "chinese": "v. （通过自己的努力）取得，获得；学得", "english": "acquire", "type": "单词", "keyWords": [] },
    { "chinese": "精通", "english": "acquire a good knowledge of...", "type": "短语", "keyWords": ["acquire"] },
    { "chinese": "获得好名声", "english": "acquire a good reputation", "type": "短语", "keyWords": ["acquire"] },
    { "chinese": "a. 已获得的，通过自己后天努力得到的", "english": "acquired", "type": "单词", "keyWords": ["acquire"] },
    { "chinese": "n. [U][C] 获得", "english": "acquisition", "type": "单词", "keyWords": ["acquire"] },
    { "chinese": "信息采集/获取", "english": "information acquisition", "type": "短语", "keyWords": ["acquisition"] },
    { "chinese": "语言习得/掌握", "english": "language acquisition", "type": "短语", "keyWords": ["acquisition"] },
    { "chinese": "ad. 横过（从一边到另一边）；交叉地；在对面；prep. 横过；越过；交叉；在…的另一边；在…对面", "english": "across", "type": "单词", "keyWords": [] },
    { "chinese": "在纸上画交叉线", "english": "draw lines across the paper", "type": "短语", "keyWords": ["across"] },
    { "chinese": "抱臂坐着", "english": "be seated with arms across/ with arms crossed", "type": "短语", "keyWords": ["across"] },
    { "chinese": "他的办公室就在街对面。", "english": "His office is just across the street.", "type": "句子", "keyWords": ["across"] },
    { "chinese": "他在大厅的那一头和我说话。", "english": "He addressed me from across the hall.", "type": "句子", "keyWords": ["across"] },
    { "chinese": "vi. 行动；做事；表演；起作用；v. 扮演；n. [C] 行为，动作；法令；条例；（剧）幕", "english": "act", "type": "单词", "keyWords": [] },
    { "chinese": "他在作弊时被当场抓住。", "english": "He was caught in the (very) act of cheating.", "type": "句子", "keyWords": ["act"] },
    { "chinese": "独幕剧", "english": "a one-act play", "type": "短语", "keyWords": ["act"] },
    { "chinese": "代理经理", "english": "acting manager", "type": "短语", "keyWords": ["act"] },
    { "chinese": "表演", "english": "act...out", "type": "短语", "keyWords": ["act"] },
    { "chinese": "担当；充当", "english": "act as", "type": "短语", "keyWords": ["act"] },
    { "chinese": "这片森林将起到防御沙漠尘土的作用。", "english": "The forest will act as a defence against desert dust.", "type": "句子", "keyWords": ["act"] },
    { "chinese": "作用于心脏/移动的物体", "english": "act upon the heart/ the moving object", "type": "短语", "keyWords": ["act"] },
    { "chinese": "n. [U]（复杂抽象的）行动；动作；作用；战斗；n. [C] 行为", "english": "action", "type": "单词", "keyWords": ["act"] },
    { "chinese": "一个能干的妇女", "english": "a woman of action", "type": "短语", "keyWords": ["action"] },
    { "chinese": "阵亡", "english": "be killed in action", "type": "短语", "keyWords": ["action"] },
    { "chinese": "采取行动", "english": "take action/ put it into action/ take measures/ take steps", "type": "短语", "keyWords": ["action"] },
    { "chinese": "行动胜于空谈。", "english": "Actions speak louder than words.", "type": "句子", "keyWords": ["action"] },
    { "chinese": "a. 积极的；主动的；活跃的；勤奋的", "english": "active", "type": "单词", "keyWords": ["act"] },
    { "chinese": "ad. 积极地；勤奋地", "english": "actively", "type": "单词", "keyWords": ["active"] },
    { "chinese": "在政界相当活跃", "english": "be active in politics", "type": "短语", "keyWords": ["active"] },
    { "chinese": "积极参加", "english": "take an active part in", "type": "短语", "keyWords": ["active"] },
    { "chinese": "v. 刺激，使活动", "english": "activate", "type": "单词", "keyWords": ["active"] },
    { "chinese": "他的崇高精神大大激励了别人。", "english": "His lofty spirit has greatly activated others.", "type": "句子", "keyWords": ["activate"] },
    { "chinese": "n. [C] 活动", "english": "activity", "type": "单词", "keyWords": ["active"] },
    { "chinese": "社交活动，社会活动", "english": "social activities", "type": "短语", "keyWords": ["activity"] },
    { "chinese": "n. [C] 男演员", "english": "actor", "type": "单词", "keyWords": ["act"] },
    { "chinese": "n. [C] 女演员", "english": "actress", "type": "单词", "keyWords": ["act"] },
    { "chinese": "a. 事实上的；真实的；实际的", "english": "actual", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 事实上；实际上", "english": "actually", "type": "单词", "keyWords": ["actual"] },
    { "chinese": "事实上；实际上", "english": "in actual fact/ as a matter of fact/ actually", "type": "短语", "keyWords": ["actual"] },
    { "chinese": "v. （使）适应；（使）适合（为达到新要求而做出巨大改变）；改编", "english": "adapt", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 适应，改编；n. [C] 改写本", "english": "adaptation", "type": "单词", "keyWords": ["adapt"] },
    { "chinese": "随遇而安", "english": "adapt yourself to new customs", "type": "短语", "keyWords": ["adapt"] },
    { "chinese": "他很快就适应了高山气候。", "english": "He quickly adapted to the climate in the high mountains.", "type": "句子", "keyWords": ["adapt"] },
    { "chinese": "这部电影是由小说改编的。", "english": "The movie was adapted from a novel.", "type": "句子", "keyWords": ["adapt"] },
    { "chinese": "因地制宜的原则", "english": "the principle of adaptation to local conditions", "type": "短语", "keyWords": ["adaptation"] },
    { "chinese": "v. 增加，添加；计算…总和；补充说，又说；vi. 加，加起来；增添", "english": "add", "type": "单词", "keyWords": [] },
    { "chinese": "往…里加…", "english": "add...to...", "type": "短语", "keyWords": ["add"] },
    { "chinese": "火上浇油", "english": "add fuel to the flame", "type": "短语", "keyWords": ["add"] },
    { "chinese": "再往名单上加几个名字", "english": "add a few more names to the list", "type": "短语", "keyWords": ["add"] },
    { "chinese": "雪上加霜；进一步伤人感情", "english": "add insult to injury", "type": "短语", "keyWords": ["add"] },
    { "chinese": "40加50等于90。", "english": "Forty added to/ plus fifty makes ninety.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "增加；对…起增添作用", "english": "add to", "type": "短语", "keyWords": ["add"] },
    { "chinese": "食品开销的上涨增加了我们的困难。", "english": "The rise in food costs has added to our difficulties.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "实际上，这使得经济更加稳定。", "english": "Indeed, this should add to economic stability.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "把…全加起来", "english": "add (all the numbers) up", "type": "短语", "keyWords": ["add"] },
    { "chinese": "总计达；[口] 总括起来；意味着", "english": "add up to", "type": "短语", "keyWords": ["add"] },
    { "chinese": "三角形的三个角总和是180度。", "english": "The three angles of a triangle add up to 180.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "我认为这些事实不说明任何问题。", "english": "I do not think these facts will add up to anything.", "type": "句子", "keyWords": ["add"] },
    { "chinese": "n. [U] 加；增加，加法；n. [C] 增加物；增加的人", "english": "addition", "type": "单词", "keyWords": ["add"] },
    { "chinese": "除了…之外，另外", "english": "in addition to", "type": "短语", "keyWords": ["addition"] },
    { "chinese": "除了伤亡之外，还有许多人失踪。", "english": "In addition to the dead and wounded, many were missing.", "type": "句子", "keyWords": ["addition"] },
    { "chinese": "a. 附加的；额外的", "english": "additional", "type": "单词", "keyWords": ["addition"] },
    { "chinese": "阻止额外热量的散失至关重要。", "english": "Preventing additional heat loss is of great importance.", "type": "句子", "keyWords": ["additional"] },
    { "chinese": "v. 使沉溺，使入迷；使成瘾；使（某人）染上（某些恶习）；n. 入迷的人；有瘾的人", "english": "addict", "type": "单词", "keyWords": [] },
    { "chinese": "a. 成瘾的；沉迷的", "english": "addicted", "type": "单词", "keyWords": ["addict"] },
    { "chinese": "沉迷在…中", "english": "be addicted to", "type": "短语", "keyWords": ["addict"] },
    { "chinese": "a. 附加的，添加的；n. [C] 添加剂", "english": "additive", "type": "单词", "keyWords": ["add"] },
    { "chinese": "食品添加剂", "english": "food additives", "type": "短语", "keyWords": ["additive"] },
    { "chinese": "食用色素添加剂", "english": "color food additive", "type": "短语", "keyWords": ["additive"] },
    { "chinese": "n. [C] 讲话；称呼；演讲；地址；住址；v. 向…讲话；给…写上姓名和地址；忙着做，处理", "english": "address", "type": "单词", "keyWords": [] },
    { "chinese": "信中的称呼形式", "english": "form of address in the letter", "type": "短语", "keyWords": ["address"] },
    { "chinese": "致开幕词/闭幕词", "english": "deliver an opening/ a closing address", "type": "短语", "keyWords": ["address"] },
    { "chinese": "（话）讲给…；把（信）写给…", "english": "address...to...", "type": "短语", "keyWords": ["address"] },
    { "chinese": "向大会/国民发表演说", "english": "address the meeting/ the nation", "type": "短语", "keyWords": ["address"] },
    { "chinese": "给信写上地址", "english": "address the letter", "type": "短语", "keyWords": ["address"] },
    { "chinese": "处理问题", "english": "address an issue", "type": "短语", "keyWords": ["address"] },
    { "chinese": "我应当怎样称呼您呢？", "english": "How shall I address you?", "type": "句子", "keyWords": ["address"] },
    { "chinese": "a. 足够的；适当的", "english": "adequate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 足够", "english": "adequacy", "type": "单词", "keyWords": ["adequate"] },
    { "chinese": "给城市居民供给充足的水源已经成为所有政府不能掉以轻心的问题。", "english": "An adequate water supply for city people is already a problem no government can take lightly.", "type": "句子", "keyWords": ["adequate"] },
    { "chinese": "v. 调整；调节（1.把人或东西调整到准确的位置或状态 2.纠正；校准）", "english": "adjust", "type": "单词", "keyWords": [] },
    { "chinese": "调整手表/望远镜/室温", "english": "adjust one's watch/ the telescope/ the temperature of the house", "type": "短语", "keyWords": ["adjust"] },
    { "chinese": "调整自己以适应新环境", "english": "adjust yourself to new conditions", "type": "短语", "keyWords": ["adjust"] },
    { "chinese": "a. 可调整的", "english": "adjustable", "type": "单词", "keyWords": ["adjust"] },
    { "chinese": "n. [U][C] 调整，调节，调节器", "english": "adjustment", "type": "单词", "keyWords": ["adjust"] },
    { "chinese": "v. 管理；经营；支配", "english": "administrate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 管理；经营；n. [C] 管理部门，行政机关", "english": "administration", "type": "单词", "keyWords": ["administrate"] },
    { "chinese": "a. 管理的；行政的", "english": "administrative", "type": "单词", "keyWords": ["administration"] },
    { "chinese": "（高等学校）教务处；学术行政", "english": "academic administration", "type": "短语", "keyWords": ["administration"] },
    { "chinese": "美国联邦航空管理局", "english": "Federal Aviation Administration", "type": "短语", "keyWords": ["administration"] },
    { "chinese": "管理/经营才能", "english": "administrative ability", "type": "短语", "keyWords": ["administrative"] },
    { "chinese": "行政单位", "english": "an administrative unit", "type": "短语", "keyWords": ["administrative"] },
    { "chinese": "v. 赞赏，钦佩，羡慕", "english": "admire", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 钦佩地，羡慕地", "english": "admiringly", "type": "单词", "keyWords": ["admire"] },
    { "chinese": "n. [C] 赞赏者，敬慕者", "english": "admirer", "type": "单词", "keyWords": ["admire"] },
    { "chinese": "钦佩某人的…", "english": "admire sb. for...", "type": "短语", "keyWords": ["admire"] },
    { "chinese": "所有在场者都佩服她良好的记忆力和出色的表演。", "english": "Everybody present admired her for her good memory and performance.", "type": "句子", "keyWords": ["admire"] },
    { "chinese": "赞赏地看了他一眼", "english": "give him an admiring glance", "type": "短语", "keyWords": ["admiringly"] },
    { "chinese": "v. 承认；准许…进入/加入；录用；vi. 容许，给…留有余地（of）", "english": "admit", "type": "单词", "keyWords": [] },
    { "chinese": "承认做某事", "english": "admit doing sth.", "type": "短语", "keyWords": ["admit"] },
    { "chinese": "她承认偷了文件。", "english": "She admitted stealing/ having stolen the document.", "type": "句子", "keyWords": ["admit"] },
    { "chinese": "被那所大学录取", "english": "be admitted into/ to the university", "type": "短语", "keyWords": ["admit"] },
    { "chinese": "n. [U][C] 许可入场/入学/入会；录用；承认；入场费", "english": "admission", "type": "单词", "keyWords": ["admit"] },
    { "chinese": "认罪", "english": "an admission of guilt", "type": "短语", "keyWords": ["admission"] },
    { "chinese": "获准进入", "english": "gain/ obtain admission to/ into", "type": "短语", "keyWords": ["admission"] },
    { "chinese": "只能凭考试成绩进入这所大学。", "english": "Admission to the college is by examination only.", "type": "句子", "keyWords": ["admission"] },
    { "chinese": "a. 青春期的；青少年的；n. [C]（尤指16岁以下的）青少年", "english": "adolescent", "type": "单词", "keyWords": [] },
    { "chinese": "v. 采纳；通过，批准；收养", "english": "adopt", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U][C] 采纳；批准；收养", "english": "adoption", "type": "单词", "keyWords": ["adopt"] },
    { "chinese": "一名领养儿童", "english": "an adopted child", "type": "短语", "keyWords": ["adopt"] },
    { "chinese": "采纳的解决方案（后置定语）", "english": "the solution adopted/ chosen", "type": "短语", "keyWords": ["adopt"] },
    { "chinese": "v. 崇拜，敬爱，爱慕；[口] 极度喜爱", "english": "adore", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可爱的", "english": "adorable", "type": "单词", "keyWords": ["adore"] },
    { "chinese": "n. [U] 崇拜，敬爱", "english": "adoration", "type": "单词", "keyWords": ["adore"] },
    { "chinese": "姐妹俩很喜欢看电影。", "english": "The two sisters adored (going to) the cinema.", "type": "句子", "keyWords": ["adore"] },
    { "chinese": "n. [C] 成年人；a. 成年的", "english": "adult", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 成年", "english": "adulthood", "type": "单词", "keyWords": ["adult"] },
    { "chinese": "n. [U][C] 前进；提升；vi. 前进，向前移动；v. 使向前移动；促进；提前；提出", "english": "advance", "type": "单词", "keyWords": [] },
    { "chinese": "职务晋升", "english": "an advance in rank", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "预先，提前", "english": "in advance", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "我们不得不提前两周交付租金。", "english": "We had to pay the rent two weeks in advance.", "type": "句子", "keyWords": ["advance"] },
    { "chinese": "预付（收）", "english": "pay/ receive in advance", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "超越了他的时代", "english": "in advance of his time", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "随着冬天的来临，白天变短了。", "english": "With the advance of winter the days grow shorter.", "type": "句子", "keyWords": ["advance"] },
    { "chinese": "努力发展生产", "english": "advance production energetically", "type": "短语", "keyWords": ["advance"] },
    { "chinese": "一个月过去了，但工作无任何进展。", "english": "A month has passed and the work has not advanced.", "type": "句子", "keyWords": ["advance"] },
    { "chinese": "a. 先进的，高级的；年迈的", "english": "advanced", "type": "单词", "keyWords": ["advance"] },
    { "chinese": "n. [U] 进步，进展（指比喻意义上的进步或提高）", "english": "advancement", "type": "单词", "keyWords": ["advance"] },
    { "chinese": "先进的工业国家", "english": "the advanced industrial nations", "type": "短语", "keyWords": ["advanced"] },
    { "chinese": "他年事已高。", "english": "He is advanced in years.", "type": "句子", "keyWords": ["advanced"] },
    { "chinese": "学业/知识/科学上的进步", "english": "advancement of learning/ knowledge/ science", "type": "短语", "keyWords": ["advancement"] },
    { "chinese": "n. [C] 优越性，有利方面；n. [U] 优势，有利条件，利益", "english": "advantage", "type": "单词", "keyWords": [] },
    { "chinese": "明智地投资对你很有利。", "english": "It is to your advantage to invest wisely.", "type": "句子", "keyWords": ["advantage"] },
    { "chinese": "利用；占…的便宜", "english": "take advantage of", "type": "短语", "keyWords": ["advantage"] },
    { "chinese": "你应当抓住每一次赔钱的机会，提高你对市场行为的了解。", "english": "You should take advantage of every loss to prove your knowledge of market action.", "type": "句子", "keyWords": ["advantage"] },
    { "chinese": "你应该对他们的过失加以利用。", "english": "You should take advantage of their mistakes.", "type": "句子", "keyWords": ["advantage"] },
    { "chinese": "占/获得/赢得优势", "english": "have/ gain/ win an advantage over", "type": "短语", "keyWords": ["advantage"] },
    { "chinese": "陶器的优点在于比木器更容易保持清洁。", "english": "Earthenware has an advantage over wood in being more easily kept clean.", "type": "句子", "keyWords": ["advantage"] },
    { "chinese": "a.有利的", "english": "advantageous", "type": "单词", "keyWords": [] },
    { "chinese": "n.激动人心的活动/经历；冒险；v.冒险；担风险", "english": "adventure", "type": "单词", "keyWords": [] },
    { "chinese": "n.冒险家", "english": "adventurer", "type": "单词", "keyWords": [] },
    { "chinese": "a.喜欢冒险的，敢作敢为的，充满危险的", "english": "adventurous", "type": "单词", "keyWords": [] },
    { "chinese": "v.登广告；为…做广告", "english": "advertise", "type": "单词", "keyWords": [] },
    { "chinese": "为房子打广告", "english": "advertise for a house", "type": "短语", "keyWords": ["advertise"] },
    { "chinese": "为商品做广告", "english": "advertise the goods", "type": "短语", "keyWords": ["advertise"] },
    { "chinese": "n.登广告者；广告客户", "english": "advertiser", "type": "单词", "keyWords": [] },
    { "chinese": "n.广告业，广告；a.广告的", "english": "advertising", "type": "单词", "keyWords": [] },
    { "chinese": "广告商，广告公司", "english": "advertising agency", "type": "短语", "keyWords": ["advertising"] },
    { "chinese": "n.广告", "english": "advertisement", "type": "单词", "keyWords": [] },
    { "chinese": "在报纸上登广告", "english": "put an advertisement in the newspaper", "type": "短语", "keyWords": ["advertisement"] },
    { "chinese": "n.劝告，忠告；意见", "english": "advice", "type": "单词", "keyWords": [] },
    { "chinese": "听某人的忠告", "english": "follow/ take/ seek one's advice", "type": "短语", "keyWords": ["advice"] },
    { "chinese": "给…一些忠告", "english": "give some advice on sth.", "type": "短语", "keyWords": ["advice"] },
    { "chinese": "你能给我们一些让我们冬训更有效的建议吗？", "english": "Could you give us some advice on how to make our winter training more effective?", "type": "句子", "keyWords": ["advice"] },
    { "chinese": "遵照…的意见", "english": "on sb.'s advice/ recommendation", "type": "短语", "keyWords": ["advice"] },
    { "chinese": "遵照医生的意见，我决定戒酒。", "english": "On the doctor's advice, I decided to give up drinking.", "type": "句子", "keyWords": ["advice"] },
    { "chinese": "v.劝告；建议；n.（学生的）指导教师", "english": "advise", "type": "单词", "keyWords": [] },
    { "chinese": "劝告某人做某事", "english": "advise doing sth./advise sb. to do sth.", "type": "短语", "keyWords": ["advise"] },
    { "chinese": "当时我建议等到适当的时候。", "english": "I advised waiting till the proper time.", "type": "句子", "keyWords": ["advise"] },
    { "chinese": "我建议她等到适当的时候。", "english": "I advised her to wait till the proper time.", "type": "句子", "keyWords": ["advise"] },
    { "chinese": "我建议她应该等到适当的时候。", "english": "I advised she (should) wait till the proper time.", "type": "句子", "keyWords": ["advise"] },
    { "chinese": "劝告某人不要做某事", "english": "advise sb. against (doing) sth.=advise sb. not to do sth.", "type": "短语", "keyWords": ["advise"] },
    { "chinese": "医生建议我不要再服药了。", "english": "The doctor advised me against taking more medicine.", "type": "句子", "keyWords": ["advise"] },
    { "chinese": "医生建议我不要再服药了。", "english": "The doctor advised me not to take more medicine.", "type": "句子", "keyWords": ["advise"] },
    { "chinese": "就某事向某人提建议", "english": "advise (sb.) on/about sth.", "type": "短语", "keyWords": ["advise"] },
    { "chinese": "有人向你建议过学英语的最佳方法吗？", "english": "Have you ever been advised on the best way of learning English?", "type": "句子", "keyWords": ["advise"] },
    { "chinese": "v.拥护；提倡；主张；n.拥护者；提倡者；辩护者", "english": "advocate", "type": "单词", "keyWords": [] },
    { "chinese": "提倡做…，主张做…", "english": "advocate (doing) sth./that sb. should do sth.", "type": "短语", "keyWords": ["advocate"] },
    { "chinese": "n.飞机", "english": "aeroplane", "type": "单词", "keyWords": [] },
    { "chinese": "n.伊索（希腊寓言作家）", "english": "Aesop", "type": "单词", "keyWords": [] },
    { "chinese": "《伊索寓言》", "english": "Aesop's Fables", "type": "短语", "keyWords": ["Aesop"] },
    { "chinese": "n.事务；事件；私事", "english": "affair", "type": "单词", "keyWords": [] },
    { "chinese": "国际事务", "english": "international affairs", "type": "短语", "keyWords": ["affair"] },
    { "chinese": "形势，事态", "english": "the state of affairs", "type": "短语", "keyWords": ["affair"] },
    { "chinese": "少管闲事", "english": "mind one's own affairs(=mind one's own business)", "type": "短语", "keyWords": ["affair"] },
    { "chinese": "民政事务", "english": "civil affairs", "type": "短语", "keyWords": ["affair"] },
    { "chinese": "国事，政务", "english": "the affairs of state", "type": "短语", "keyWords": ["affair"] },
    { "chinese": "v.影响；感动；侵袭", "english": "affect", "type": "单词", "keyWords": [] },
    { "chinese": "通货膨胀影响美元的购买力。", "english": "Inflation affects the buying power of the dollar.", "type": "句子", "keyWords": ["affect"] },
    { "chinese": "中暑/着凉", "english": "be affected by heat/ cold", "type": "短语", "keyWords": ["affect"] },
    { "chinese": "n.喜爱，慈爱；影响；疾病，感染", "english": "affection", "type": "单词", "keyWords": [] },
    { "chinese": "喉疾", "english": "an affection of the throat", "type": "短语", "keyWords": ["affection"] },
    { "chinese": "a.充满深情的，有感情的，慈爱的", "english": "affectionate", "type": "单词", "keyWords": [] },
    { "chinese": "adv.慈爱地", "english": "affectionately", "type": "单词", "keyWords": [] },
    { "chinese": "你最亲爱的（英美人写家信时结尾用语）", "english": "Yours affectionately,", "type": "短语", "keyWords": ["affectionately"] },
    { "chinese": "v.提供；买得起；能做或担负得起", "english": "afford", "type": "单词", "keyWords": [] },
    { "chinese": "有足够的金钱做某事，承受得起做某事", "english": "can afford sth./afford to do sth.", "type": "短语", "keyWords": ["afford"] },
    { "chinese": "我买得起这新房子。", "english": "I can afford (to buy) this new house.", "type": "句子", "keyWords": ["afford"] },
    { "chinese": "我可以抽出一小时吃午饭。", "english": "I can afford an hour for lunch.", "type": "句子", "keyWords": ["afford"] },
    { "chinese": "承担不起做某事", "english": "can't afford to do sth.", "type": "短语", "keyWords": ["afford"] },
    { "chinese": "我惹不起他。", "english": "I can't afford to offend him.", "type": "句子", "keyWords": ["afford"] },
    { "chinese": "a.怕的，害怕的；恐怕；遗憾的", "english": "afraid", "type": "单词", "keyWords": [] },
    { "chinese": "由于害怕而不敢做某事", "english": "be afraid to do sth.", "type": "短语", "keyWords": ["afraid"] },
    { "chinese": "害怕做某事", "english": "be (very much) afraid of (doing) sth.", "type": "短语", "keyWords": ["afraid"] },
    { "chinese": "不要怕那条蛇/艰苦的工作。", "english": "Don't be afraid of the snake/hard work.", "type": "句子", "keyWords": ["afraid"] },
    { "chinese": "恐怕不行。", "english": "I'm afraid not.", "type": "句子", "keyWords": ["afraid"] },
    { "chinese": "n.非洲；a.非洲的；n.非洲人", "english": "Africa", "type": "单词", "keyWords": [] },
    { "chinese": "prep.在…之后；adv.…之后；conj.…之后", "english": "after", "type": "单词", "keyWords": [] },
    { "chinese": "你先走。你先请。", "english": "After you, please.", "type": "句子", "keyWords": ["after"] },
    { "chinese": "请随手关门。", "english": "Shut the door after you.", "type": "句子", "keyWords": ["after"] },
    { "chinese": "他是以其父亲的名字命名的。", "english": "He was named after his father.", "type": "句子", "keyWords": ["after"] },
    { "chinese": "a.售后的（服务）", "english": "after-sales (service)", "type": "短语", "keyWords": ["after"] },
    { "chinese": "毕竟；终究", "english": "after all", "type": "短语", "keyWords": ["after"] },
    { "chinese": "这男孩最终变得很有出息。", "english": "The boy turned out successful after all.", "type": "句子", "keyWords": ["after"] },
    { "chinese": "搜寻，寻找；追求", "english": "go/ run/ chase/ seek after", "type": "短语", "keyWords": ["after"] },
    { "chinese": "警察在追捕一名越狱犯。", "english": "The policemen are (running) after an escaped prisoner.", "type": "句子", "keyWords": ["after"] },
    { "chinese": "追求名誉地位", "english": "seek after fame and position", "type": "短语", "keyWords": ["after"] },
    { "chinese": "向…问好；询问情况", "english": "ask after", "type": "短语", "keyWords": ["after"] },
    { "chinese": "你叔父询问了你的情况。", "english": "Your uncle asked after you.", "type": "句子", "keyWords": ["after"] },
    { "chinese": "不久以后", "english": "shortly after(=shortly/ soon afterwards)", "type": "短语", "keyWords": ["after"] },
    { "chinese": "他们不久就离开了。", "english": "They departed shortly after.", "type": "句子", "keyWords": ["after"] },
    { "chinese": "在…之后", "english": "soon after (conj.)", "type": "短语", "keyWords": ["after"] },
    { "chinese": "幸好火势刚起就立即被发现了。", "english": "Fortunately, the fire was discovered soon after it had started.", "type": "句子", "keyWords": ["after"] },
    { "chinese": "n.下午；a.下午的", "english": "afternoon", "type": "单词", "keyWords": [] },
    { "chinese": "在一个下着雨的下午", "english": "on a rainy afternoon", "type": "短语", "keyWords": ["afternoon"] },
    { "chinese": "adv.然后，后来", "english": "afterwards", "type": "单词", "keyWords": [] },
    { "chinese": "adv.再一次，又", "english": "again", "type": "单词", "keyWords": [] },
    { "chinese": "再三地，反复地", "english": "again and again/ time and (time) again", "type": "短语", "keyWords": ["again"] },
    { "chinese": "有时", "english": "now and again/ now and then/ from time to time/ at times/ occasionally", "type": "短语", "keyWords": ["again"] },
    { "chinese": "prep.反对；逆着；靠/倚着；以…为背景/衬托", "english": "against", "type": "单词", "keyWords": [] },
    { "chinese": "反对，不赞成", "english": "be against", "type": "短语", "keyWords": ["against"] },
    { "chinese": "他们极力反对举行罢工。", "english": "They are strongly against going on strike.", "type": "句子", "keyWords": ["against"] },
    { "chinese": "他违心做了此事。", "english": "He did it against his own will.", "type": "句子", "keyWords": ["against"] },
    { "chinese": "他倚在一根柱子上。", "english": "He was leaning against a post.", "type": "句子", "keyWords": ["against"] },
    { "chinese": "在清晨天空的映照下，那些松树呈黑色。", "english": "The pine trees were black against the early morning sky.", "type": "句子", "keyWords": ["against"] },
    { "chinese": "n.年龄；时代；成年；v.变老，上年纪；成熟", "english": "age", "type": "单词", "keyWords": [] },
    { "chinese": "在…岁时", "english": "at the age of...", "type": "短语", "keyWords": ["age"] },
    { "chinese": "同龄", "english": "be of an age", "type": "短语", "keyWords": ["age"] },
    { "chinese": "同龄人", "english": "people of an age", "type": "短语", "keyWords": ["age"] },
    { "chinese": "未到成年", "english": "be under age", "type": "短语", "keyWords": ["age"] },
    { "chinese": "石器时代", "english": "the Stone Age", "type": "短语", "keyWords": ["age"] },
    { "chinese": "他所处的历史阶段的产物", "english": "a product of his age", "type": "短语", "keyWords": ["age"] },
    { "chinese": "以…的年龄来说", "english": "for one's age", "type": "短语", "keyWords": ["age"] },
    { "chinese": "以他的年龄来说，他个子稍矮了些。", "english": "He is a little bit short for his age.", "type": "句子", "keyWords": ["age"] },
    { "chinese": "在你那样年龄的时候", "english": "be (of) your age", "type": "短语", "keyWords": ["age"] },
    { "chinese": "在你这个年龄的时候…", "english": "When I was (of) your age...", "type": "句子", "keyWords": ["age"] },
    { "chinese": "自从…以来已经很久了", "english": "It is ages since...", "type": "短语", "keyWords": ["age"] },
    { "chinese": "他老得很快。", "english": "He is aging rapidly.", "type": "句子", "keyWords": ["age"] },
    { "chinese": "忧伤催人老。", "english": "Grief ages us.", "type": "句子", "keyWords": ["age"] },
    { "chinese": "a.年老的；旧的；…岁的", "english": "aged", "type": "单词", "keyWords": [] },
    { "chinese": "陈酒/老翁", "english": "aged wine/ man", "type": "短语", "keyWords": ["aged"] },
    { "chinese": "一名33岁的男子", "english": "a man aged 33=a man 33 years of age", "type": "短语", "keyWords": ["aged"] },
    { "chinese": "n.代理处；代理", "english": "agency", "type": "单词", "keyWords": [] },
    { "chinese": "通讯社/旅行社", "english": "a news/ travel agency", "type": "短语", "keyWords": ["agency"] },
    { "chinese": "n.议事日程；日常工作事项", "english": "agenda", "type": "单词", "keyWords": [] },
    { "chinese": "议程的下一项是什么？", "english": "What's the next item on the agenda?", "type": "句子", "keyWords": ["agenda"] },
    { "chinese": "n.代理人；代理商", "english": "agent", "type": "单词", "keyWords": [] },
    { "chinese": "a.好斗的，侵略性的；敢作敢为的，积极进取的", "english": "aggressive", "type": "单词", "keyWords": [] },
    { "chinese": "n.侵犯，进取", "english": "aggressiveness", "type": "单词", "keyWords": [] },
    { "chinese": "一个侵略性的外交政策", "english": "an aggressive foreign policy", "type": "短语", "keyWords": ["aggressive"] },
    { "chinese": "adv.以前", "english": "ago", "type": "单词", "keyWords": [] },
    { "chinese": "v.同意，赞成；与…一致/相符，适合", "english": "agree", "type": "单词", "keyWords": [] },
    { "chinese": "我非常同意。", "english": "I couldn't agree more.", "type": "句子", "keyWords": ["agree"] },
    { "chinese": "同意某事；答应做某事", "english": "agree to sth.；agree to do sth.", "type": "短语", "keyWords": ["agree"] },
    { "chinese": "同意我的计划", "english": "agree to my plan", "type": "短语", "keyWords": ["agree"] },
    { "chinese": "就某事达成一致意见", "english": "agree on sth.", "type": "短语", "keyWords": ["agree"] },
    { "chinese": "同意；适合；一致；符合", "english": "agree with", "type": "短语", "keyWords": ["agree"] },
    { "chinese": "我同意你的说法，这太迟了。", "english": "I agree with you that it is too late.", "type": "句子", "keyWords": ["agree"] },
    { "chinese": "复印件和原件一致。", "english": "The copy agrees with the original.", "type": "句子", "keyWords": ["agree"] },
    { "chinese": "辣食物不合我的胃口。", "english": "Spicy food does not agree with me.", "type": "句子", "keyWords": ["agree"] },
    { "chinese": "a.令人愉快的；惬意的", "english": "agreeable", "type": "单词", "keyWords": [] },
    { "chinese": "悦耳的声音", "english": "agreeable voice", "type": "短语", "keyWords": ["agreeable"] },
    { "chinese": "悦耳；听起来舒服", "english": "agreeable to the ear", "type": "短语", "keyWords": ["agreeable"] },
    { "chinese": "味道好", "english": "agreeable to the taste", "type": "短语", "keyWords": ["agreeable"] },
    { "chinese": "宜人的天气", "english": "agreeable weather", "type": "短语", "keyWords": ["agreeable"] },
    { "chinese": "n.同意，一致；协定，协议", "english": "agreement", "type": "单词", "keyWords": [] },
    { "chinese": "达成协议；取得一致意见", "english": "arrive at/ come to/ reach an agreement", "type": "短语", "keyWords": ["agreement"] },
    { "chinese": "符合…，照…，同意，与…一致", "english": "in agreement with", "type": "短语", "keyWords": ["agreement"] },
    { "chinese": "n.农业；农艺", "english": "agriculture", "type": "单词", "keyWords": [] },
    { "chinese": "a.农业的；农艺的", "english": "agricultural", "type": "单词", "keyWords": [] },
    { "chinese": "adv.在前面；向前", "english": "ahead", "type": "单词", "keyWords": [] },
    { "chinese": "前进；进展", "english": "go ahead (with sth.)", "type": "短语", "keyWords": ["ahead"] },
    { "chinese": "看前面；考虑未来", "english": "look ahead", "type": "短语", "keyWords": ["ahead"] },
    { "chinese": "在…前头，先于", "english": "ahead of", "type": "短语", "keyWords": ["ahead"] },
    { "chinese": "提前", "english": "ahead of time/ beforehand/ in advance", "type": "短语", "keyWords": ["ahead"] },
    { "chinese": "他的眼睛直盯着前方。", "english": "His eyes stared straight ahead.", "type": "句子", "keyWords": ["ahead"] },
    { "chinese": "n.帮助，援助；帮助者；有帮助的事物；v.资助，援助，帮助", "english": "aid", "type": "单词", "keyWords": [] },
    { "chinese": "急救", "english": "first aid", "type": "短语", "keyWords": ["aid"] },
    { "chinese": "去（来）帮助某人", "english": "go/ come to one's aid/ help", "type": "短语", "keyWords": ["aid"] },
    { "chinese": "助听器", "english": "a hearing aid", "type": "短语", "keyWords": ["aid"] },
    { "chinese": "艾滋病", "english": "AIDS/ Aids", "type": "单词", "keyWords": [] },
    { "chinese": "n.目标，目的；瞄准；v.瞄准；打算，目的在于", "english": "aim", "type": "单词", "keyWords": [] },
    { "chinese": "目的在于做某事", "english": "aim at (doing) sth./to do sth.", "type": "短语", "keyWords": ["aim"] },
    { "chinese": "把枪瞄准敌人", "english": "aim one's gun at the enemy", "type": "短语", "keyWords": ["aim"] },
    { "chinese": "瞄准", "english": "take aim (at sth.)", "type": "短语", "keyWords": ["aim"] },
    { "chinese": "他瞄准靶子。", "english": "He took aim at the target./He aimed at the target.", "type": "句子", "keyWords": ["aim"] },
    { "chinese": "n.空气，天空，空中；神态；气氛；v.晾干，使通风；夸耀；显示", "english": "air", "type": "单词", "keyWords": [] },
    { "chinese": "在户外", "english": "in the open air", "type": "短语", "keyWords": ["air"] },
    { "chinese": "摆架子；装腔作势", "english": "put on airs", "type": "短语", "keyWords": ["air"] },
    { "chinese": "他以饱学而自傲。", "english": "He put on high airs with his learning.", "type": "句子", "keyWords": ["air"] },
    { "chinese": "（开始/在）广播，播送", "english": "(go/be) on (the) air", "type": "短语", "keyWords": ["air"] },
    { "chinese": "给房间通风", "english": "air the room", "type": "短语", "keyWords": ["air"] },
    { "chinese": "每到周日我们就把衣服拿到外面晾一晾。", "english": "We always air our clothes on Sundays.", "type": "句子", "keyWords": ["air"] },
    { "chinese": "a.装有空调设备的（房间）", "english": "air-conditioned (room)", "type": "短语", "keyWords": ["air"] },
    { "chinese": "调节空气", "english": "air-conditioning", "type": "短语", "keyWords": ["air"] },
    { "chinese": "n.空乘女服务员", "english": "air hostess", "type": "短语", "keyWords": ["air"] },
    { "chinese": "n.飞机；飞艇；航空器", "english": "aircraft", "type": "单词", "keyWords": [] },
    { "chinese": "n.（飞机）定期航线；航空公司；a.（飞机）航线的；航空公司的", "english": "airline", "type": "单词", "keyWords": [] },
    { "chinese": "n.客机；定期班机", "english": "airliner", "type": "单词", "keyWords": [] },
    { "chinese": "n.航空邮件；用航空邮寄", "english": "airmail", "type": "单词", "keyWords": [] },
    { "chinese": "用航空邮寄", "english": "by airmail", "type": "短语", "keyWords": ["airmail"] },
    { "chinese": "n.机场", "english": "airport", "type": "单词", "keyWords": [] },
    { "chinese": "n.惊慌；警报，闹铃，警报器；v.使惊恐；向…报警", "english": "alarm", "type": "单词", "keyWords": [] },
    { "chinese": "鸣警报", "english": "give/ sound the alarm", "type": "短语", "keyWords": ["alarm"] },
    { "chinese": "惊恐地跳了起来", "english": "jump in alarm", "type": "短语", "keyWords": ["alarm"] },
    { "chinese": "闹钟/警铃", "english": "an alarm clock/bell", "type": "短语", "keyWords": ["alarm"] },
    { "chinese": "n.照相本；集邮本；唱片集；签名纪念册", "english": "album", "type": "单词", "keyWords": [] },
    { "chinese": "n.含酒精饮料；酒精；酒；乙醇", "english": "alcohol", "type": "单词", "keyWords": [] },
    { "chinese": "a.酒精的；含酒精的饮料", "english": "alcoholic", "type": "单词", "keyWords": [] },
    { "chinese": "含酒精的饮料", "english": "alcoholic drinks", "type": "短语", "keyWords": ["alcoholic"] },
    { "chinese": "n.警戒；警报；a.警觉的；警惕的；v.向…报警；使警觉；使警惕", "english": "alert", "type": "单词", "keyWords": [] },
    { "chinese": "n.警戒；机敏", "english": "alertness", "type": "单词", "keyWords": [] },
    { "chinese": "处于警惕状态", "english": "be on the alert", "type": "短语", "keyWords": ["alert"] },
    { "chinese": "他回答我的问题时很机警。", "english": "He was alert in answering my questions.", "type": "句子", "keyWords": ["alert"] },
    { "chinese": "部队在待命中。", "english": "The troops were alerted.", "type": "句子", "keyWords": ["alert"] },
    { "chinese": "adv.一样地；相似地；a.同样的；相像的", "english": "alike", "type": "单词", "keyWords": [] },
    { "chinese": "我们想法一样。", "english": "We think alike.", "type": "句子", "keyWords": ["alike"] },
    { "chinese": "a.活着的；活动的，活泼的，精神抖擞的", "english": "alive", "type": "单词", "keyWords": [] },
    { "chinese": "被活捉/活埋", "english": "be caught/ buried alive", "type": "短语", "keyWords": ["alive"] },
    { "chinese": "世上最幸福的人", "english": "the happiest man alive", "type": "短语", "keyWords": ["alive"] },
    { "chinese": "n.所有的一切；全体；a.全部的；一切的，所有的；adv.完全；非常", "english": "all", "type": "单词", "keyWords": [] },
    { "chinese": "整天", "english": "all day (long)", "type": "短语", "keyWords": ["all"] },
    { "chinese": "一路上；一直", "english": "all the way", "type": "短语", "keyWords": ["all"] },
    { "chinese": "毕竟，到底", "english": "after all", "type": "短语", "keyWords": ["all"] },
    { "chinese": "突然", "english": "all at once=all of a sudden", "type": "短语", "keyWords": ["all"] },
    { "chinese": "总计", "english": "in all", "type": "短语", "keyWords": ["all"] },
    { "chinese": "满面笑容/喜气洋洋/喜形于色", "english": "She is all smiles.", "type": "句子", "keyWords": ["all"] },
    { "chinese": "完全，全然", "english": "(not) at all", "type": "短语", "keyWords": ["all"] },
    { "chinese": "一点也不", "english": "not at all=not a bit=no in the least=not nearly", "type": "短语", "keyWords": ["all"] },
    { "chinese": "反而更（好），却更…", "english": "all the better/ more...", "type": "短语", "keyWords": ["all"] },
    { "chinese": "全力以赴", "english": "go all out (to do sth.)", "type": "短语", "keyWords": ["all"] },
    { "chinese": "仍然；（虽然…）还是", "english": "all the same", "type": "短语", "keyWords": ["all"] },
    { "chinese": "总的来说，总之", "english": "all in all", "type": "短语", "keyWords": ["all"] },
    { "chinese": "总之", "english": "at all events", "type": "短语", "keyWords": ["all"] },
    { "chinese": "最糟糕的是", "english": "worst of all", "type": "短语", "keyWords": ["all"] },
    { "chinese": "开窗反而更热。", "english": "Opening the windows made it all the hotter.", "type": "句子", "keyWords": ["all"] },
    { "chinese": "尽管；虽然", "english": "for all...", "type": "短语", "keyWords": ["all"] },
    { "chinese": "虽然我全力指点，她还是一窍不通。", "english": "For all my advice she was never the wiser.", "type": "句子", "keyWords": ["all"] },
    { "chinese": "未必都是…", "english": "all...not...", "type": "短语", "keyWords": ["all"] },
    { "chinese": "结果好就一切都好。", "english": "All's well that ends well!", "type": "句子", "keyWords": ["all"] },
    { "chinese": "发光的并不都是金子。", "english": "All is not gold that glitters.", "type": "句子", "keyWords": ["all"] },
    { "chinese": "v.允许；准许；允给；承认；v.容许", "english": "allow", "type": "单词", "keyWords": [] },
    { "chinese": "n.补贴；津贴", "english": "allowance", "type": "单词", "keyWords": [] },
    { "chinese": "a.允许的，正当的", "english": "allowable", "type": "单词", "keyWords": [] },
    { "chinese": "允许…做某事；…被允许去做某事", "english": "allow sb. to do sth....be allowed to do...", "type": "短语", "keyWords": ["allow"] },
    { "chinese": "请允许我自我介绍一下。", "english": "Allow me to introduce myself.", "type": "句子", "keyWords": ["allow"] },
    { "chinese": "这里不许随地吐痰。", "english": "Spitting is not allowed here.", "type": "句子", "keyWords": ["allow"] },
    { "chinese": "允许做某事", "english": "allow doing sth.", "type": "短语", "keyWords": ["allow"] },
    { "chinese": "一星期给他100美元零用", "english": "allow him $100 a week", "type": "短语", "keyWords": ["allow"] },
    { "chinese": "不许找借口/不许有耽搁/无争论余地", "english": "allow of no excuse/no delay/ no dispute", "type": "短语", "keyWords": ["allow"] },
    { "chinese": "adv.几乎，差不多", "english": "almost", "type": "单词", "keyWords": [] },
    { "chinese": "几乎所有/没什么/肯定/每个", "english": "almost all/ nothing/ certainly/ every", "type": "短语", "keyWords": ["almost"] },
    { "chinese": "a.单独的；adv.单独；仅仅", "english": "alone", "type": "单词", "keyWords": [] },
    { "chinese": "很孤单的，独个的，独立的", "english": "all/ much alone", "type": "短语", "keyWords": ["alone"] },
    { "chinese": "听任", "english": "leave sb. alone =let sb. alone", "type": "短语", "keyWords": ["alone"] },
    { "chinese": "莫说；不在话下；更不用说", "english": "let alone...", "type": "短语", "keyWords": ["alone"] },
    { "chinese": "我们没有时间，更不必提费用了。", "english": "We cannot afford the time, let alone the expenses.", "type": "句子", "keyWords": ["alone"] },
    { "chinese": "仅中国就买了10000双。", "english": "China alone bought 10,000 pairs.", "type": "句子", "keyWords": ["alone"] },
    { "chinese": "prep.沿…的边；在…边；adv.上前，向前；一块儿，一道（去）", "english": "along", "type": "单词", "keyWords": [] },
    { "chinese": "一道", "english": "come along", "type": "短语", "keyWords": ["along"] },
    { "chinese": "一直，始终", "english": "all along=all the time=all the way", "type": "短语", "keyWords": ["along"] },
    { "chinese": "与…相处很好，进展很好", "english": "get along/on well with sb./sth.", "type": "短语", "keyWords": ["along"] },
    { "chinese": "a.旁边；prep.在…边", "english": "alongside", "type": "单词", "keyWords": [] },
    { "chinese": "adv.大声地；出声地", "english": "aloud", "type": "单词", "keyWords": [] },
    { "chinese": "诵读/说出声来/自言自语，边想边说出", "english": "read/ speak/ think aloud", "type": "短语", "keyWords": ["aloud"] },
    { "chinese": "n.字母表", "english": "alphabet", "type": "单词", "keyWords": [] },
    { "chinese": "a.按字母顺序的；按字母顺序", "english": "alphabetic(al)", "type": "单词", "keyWords": [] },
    { "chinese": "按字母顺序", "english": "in alphabetical order", "type": "短语", "keyWords": ["alphabetic(al)"] },
    { "chinese": "adv.已经", "english": "already", "type": "单词", "keyWords": [] },
    { "chinese": "adv.而且（也）；此外还", "english": "also", "type": "单词", "keyWords": [] },
    { "chinese": "v.变更；改变，改换；改建，改做", "english": "alter", "type": "单词", "keyWords": [] },
    { "chinese": "将房子改成谷仓", "english": "alter a house into a barn", "type": "短语", "keyWords": ["alter"] },
    { "chinese": "a.选择的；二中择一的；n.二挑一；可供选择的东西；供替代的选择", "english": "alternative", "type": "单词", "keyWords": [] },
    { "chinese": "听录音磁带是一种很好的选择。", "english": "Audiotapes are a good alternative (way).", "type": "句子", "keyWords": ["alternative"] },
    { "chinese": "别无选择，只得…", "english": "have no alternative but to do...", "type": "短语", "keyWords": ["alternative"] },
    { "chinese": "conj.虽然；尽管", "english": "although", "type": "单词", "keyWords": [] },
    { "chinese": "n.高，高度；海拔（高度）", "english": "altitude", "type": "单词", "keyWords": [] },
    { "chinese": "adv.总共；全部地；全然，完全", "english": "altogether", "type": "单词", "keyWords": [] },
    { "chinese": "adv.总是", "english": "always", "type": "单词", "keyWords": [] },
    { "chinese": "他总/老是为小事打扰我。", "english": "He is always bothering me with small things.", "type": "句子", "keyWords": ["always"] },
    { "chinese": "上午", "english": "a.m.", "type": "单词", "keyWords": [] },
    { "chinese": "n.业余爱好者；a.业余爱好的", "english": "amateur", "type": "单词", "keyWords": [] },
    { "chinese": "v.使惊异，使大为惊奇；a.感到/使人惊奇的；n.惊异，惊奇", "english": "amaze", "type": "单词", "keyWords": [] },
    { "chinese": "对…感到惊异", "english": "be amazed at sth./to see/ to find...", "type": "短语", "keyWords": ["amaze"] },
    { "chinese": "n.强烈愿望；志向；雄心", "english": "ambition", "type": "单词", "keyWords": [] },
    { "chinese": "a.有雄心的，野心勃勃的", "english": "ambitious", "type": "单词", "keyWords": [] },
    { "chinese": "渴望出名", "english": "have an ambition for fame", "type": "短语", "keyWords": ["ambition"] },
    { "chinese": "n.救护车", "english": "ambulance", "type": "单词", "keyWords": [] },
    { "chinese": "n.美国；美洲；a.美国的；美洲的；n.美国人；美洲人", "english": "America", "type": "单词", "keyWords": [] },
    { "chinese": "prep.在…中间，在…之中", "english": "among", "type": "单词", "keyWords": [] },
    { "chinese": "一位老人也在失踪者之列。", "english": "Among the missing was an old man.", "type": "句子", "keyWords": ["among"] },
    { "chinese": "n.数量；vi.总计，共计；等同；接近", "english": "amount", "type": "单词", "keyWords": [] },
    { "chinese": "一大笔钱", "english": "a large amount of money", "type": "短语", "keyWords": ["amount"] },
    { "chinese": "建造这座桥花费了大笔的钱款。", "english": "A large amount of money was spent on the bridge.", "type": "句子", "keyWords": ["amount"] },
    { "chinese": "建造这座桥花费了大笔的钱款。", "english": "Large amounts of money were spent on the bridge.", "type": "句子", "keyWords": ["amount"] },
    { "chinese": "总计，合计；等同；接近", "english": "amount to", "type": "短语", "keyWords": ["amount"] },
    { "chinese": "他的话接近于威胁。", "english": "His words amounted to a threat.", "type": "句子", "keyWords": ["amount"] },
    { "chinese": "v.逗…乐，逗…笑；给…提供娱乐或消遣；a.感到好笑的/使人发笑的；n.娱乐活动；乐趣", "english": "amuse", "type": "单词", "keyWords": [] },
    { "chinese": "通过…来逗乐…", "english": "amuse sb. by doing sth.", "type": "短语", "keyWords": ["amuse"] },
    { "chinese": "拿…来消遣…", "english": "amuse sb. with sth.", "type": "短语", "keyWords": ["amuse"] },
    { "chinese": "n.分析", "english": "analysis", "type": "单词", "keyWords": [] },
    { "chinese": "临床分析", "english": "clinical analysis", "type": "短语", "keyWords": ["analysis"] },
    { "chinese": "v.分析；a.分析的，分解的；善于分析的", "english": "analyze", "type": "单词", "keyWords": [] },
    { "chinese": "分析我们失败的原因/调查数据/化学混合物", "english": "analyze the cause of our failure/ research data/ a chemical compound", "type": "短语", "keyWords": ["analyze"] },
    { "chinese": "n.祖先；n.血统", "english": "ancestor", "type": "单词", "keyWords": [] },
    { "chinese": "a.古代的；n.古人", "english": "ancient", "type": "单词", "keyWords": [] },
    { "chinese": "conj.和", "english": "and", "type": "单词", "keyWords": [] },
    { "chinese": "等等", "english": "and so on(and so forth)", "type": "短语", "keyWords": ["and"] },
    { "chinese": "可是，然而", "english": "and yet(=but)", "type": "短语", "keyWords": ["and"] },
    { "chinese": "那个艺术家兼作家…", "english": "The artist and writer is...", "type": "句子", "keyWords": ["and"] },
    { "chinese": "再说话我就把你轰出去。", "english": "One more word and I'll get you out.", "type": "句子", "keyWords": ["and"] },
    { "chinese": "n.怒；愤怒；v.激怒，触怒，使发怒", "english": "anger", "type": "单词", "keyWords": [] },
    { "chinese": "气得脸都发白了", "english": "turn pale with anger", "type": "短语", "keyWords": ["anger"] },
    { "chinese": "愤怒地撕毁了他的信", "english": "tear up his letter in anger", "type": "短语", "keyWords": ["anger"] },
    { "chinese": "a.发怒的，生气的；adv.气愤地", "english": "angry", "type": "单词", "keyWords": [] },
    { "chinese": "因…而发怒", "english": "be angry at/ about sth.", "type": "短语", "keyWords": ["angry"] },
    { "chinese": "总督对这种拖延感到非常气愤。", "english": "The governor was extremely angry at the delay.", "type": "句子", "keyWords": ["angry"] },
    { "chinese": "因…做…而生气", "english": "be angry with sb. for sth.", "type": "短语", "keyWords": ["angry"] },
    { "chinese": "由于你没有早点告诉我，我很生气。", "english": "I'm pretty angry with you for not telling me earlier.", "type": "句子", "keyWords": ["angry"] },
    { "chinese": "n.角度", "english": "angle", "type": "单词", "keyWords": [] },
    { "chinese": "从不同的角度", "english": "from a different angle", "type": "短语", "keyWords": ["angle"] },
    { "chinese": "n.动物", "english": "animal", "type": "单词", "keyWords": [] },
    { "chinese": "家畜", "english": "domestic animals", "type": "短语", "keyWords": ["animal"] },
    { "chinese": "野生动物", "english": "wild animals", "type": "短语", "keyWords": ["animal"] }  
];
