const qgl211_225 = [
    { "chinese": "提升为上尉", "english": "be promoted to the rank of captain", "type": "短语", "keyWords": ["promote"] },
    { "chinese": "促进增长/理解", "english": "promote growth/understanding", "type": "短语", "keyWords": ["promote"] },
    { "chinese": "促销新产品", "english": "promote a new product", "type": "短语", "keyWords": ["promote"] },
    { "chinese": "n. [C]/[U] 促进；提拔；宣传，推销", "english": "promotion", "type": "单词", "keyWords": ["promote"] },
    { "chinese": "v. 发音；宣布；宣称", "english": "pronounce", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 发音；[C] 发音法", "english": "pronunciation", "type": "单词", "keyWords": ["pronounce"] },
    { "chinese": "n. [U] 证明；[C] 证据；a. 耐…的；能防…的", "english": "proof", "type": "单词", "keyWords": [] },
    { "chinese": "防水的", "english": "water-proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "防弹的", "english": "bullet-proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "防火的", "english": "fire-proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "抗震的", "english": "shock-proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "缩水的织物", "english": "a fabric (which is) proof against shrinkage", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "出示凭据", "english": "give proof", "type": "短语", "keyWords": ["proof"] },
    { "chinese": "a. 适当的，正当的（反 improper）", "english": "proper", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 财产；[C]/[U]（房）地产；[C] 性能；特性，属性", "english": "property", "type": "单词", "keyWords": [] },
    { "chinese": "公共财产", "english": "public property", "type": "短语", "keyWords": ["property"] },
    { "chinese": "金属性能", "english": "the metal properties", "type": "短语", "keyWords": ["property"] },
    { "chinese": "他有一小块房地产。", "english": "He has a small property.", "type": "句子", "keyWords": ["property"] },
    { "chinese": "n. [C]（整体内各部分之间和谐的）比例；部分", "english": "proportion", "type": "单词", "keyWords": [] },
    { "chinese": "调味时油和醋的适当比例", "english": "the proper proportion between oil and vinegar in the dressing", "type": "短语", "keyWords": ["proportion"] },
    { "chinese": "成比例地；相应地", "english": "in proportion (to sth.)", "type": "短语", "keyWords": ["proportion"] },
    { "chinese": "一般而言，上述各数之间存在一定的反比例关系。", "english": "In general, the figures mentioned above are to some extent in inverse proportion.", "type": "句子", "keyWords": ["proportion"] },
    { "chinese": "要注意使你的支出与收入一定相称。", "english": "See to it that your expenditure is in fixed proportion to your income.", "type": "句子", "keyWords": ["proportion"] },
    { "chinese": "n. [C] 提议；建议", "english": "proposal", "type": "单词", "keyWords": [] },
    { "chinese": "提议", "english": "present/ put forward/ put forth/ make a proposal", "type": "短语", "keyWords": ["proposal"] },
    { "chinese": "v. 提议，建议（+doing）；计划，打算（+to do）", "english": "propose", "type": "单词", "keyWords": [] },
    { "chinese": "提议早点出发", "english": "propose an early start = propose we (should) start early = propose starting early", "type": "短语", "keyWords": ["propose"] },
    { "chinese": "打算做某事", "english": "propose to do sth.", "type": "短语", "keyWords": ["propose"] },
    { "chinese": "我打算每月还贷20美元。", "english": "I propose to repay the loan at $20 a month.", "type": "句子", "keyWords": ["propose"] },
    { "chinese": "向某人求婚", "english": "*propose to sb.", "type": "短语", "keyWords": ["propose"] },
    { "chinese": "n. [C] 预期；景色；前景；v. /prəˈspekt/ 勘探；勘察（for）", "english": "prospect", "type": "单词", "keyWords": [] },
    { "chinese": "前途乐观；前景美好。", "english": "The prospect is cheerful.", "type": "句子", "keyWords": ["prospect"] },
    { "chinese": "破产的危险正逐渐加大。", "english": "The prospect of bankruptcy is getting greater.", "type": "句子", "keyWords": ["prospect"] },
    { "chinese": "勘探石油", "english": "prospect for oil", "type": "短语", "keyWords": ["prospect"] },
    { "chinese": "v. 保护；防护（辨析见 defend）", "english": "protect", "type": "单词", "keyWords": [] },
    { "chinese": "保护某人免受…的侵害", "english": "protect... from/against sth.", "type": "短语", "keyWords": ["protect"] },
    { "chinese": "保护儿童免受暴力侵犯", "english": "protect children from violence", "type": "短语", "keyWords": ["protect"] },
    { "chinese": "保护你的眼睛免受太阳光的伤害", "english": "protect your eyes from sunshine", "type": "短语", "keyWords": ["protect"] },
    { "chinese": "n. [U] 保护，防护；[C] 保护物（from/against）", "english": "protection", "type": "单词", "keyWords": ["protect"] },
    { "chinese": "a. 保护性的，防护性的", "english": "protective", "type": "单词", "keyWords": ["protect"] },
    { "chinese": "n. [C] 保护者；保护物；[器] 保护装置", "english": "protector", "type": "单词", "keyWords": ["protect"] },
    { "chinese": "n. [C]/[U] 蛋白质", "english": "protein", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 抗议；异议，反对；v. /prəˈtest/ 抗议；（对-）提出异议", "english": "protest", "type": "单词", "keyWords": [] },
    { "chinese": "抗议；提出异议", "english": "(make a) protest about/against/at...", "type": "短语", "keyWords": ["protest"] },
    { "chinese": "人们对新税种提出抗议。", "english": "The people protested/ made a protest against the new tax.", "type": "句子", "keyWords": ["protest"] },
    { "chinese": "抗议游行", "english": "protest march", "type": "短语", "keyWords": ["protest"] },
    { "chinese": "乖乖地；心甘情愿地", "english": "without protest", "type": "短语", "keyWords": ["protest"] },
    { "chinese": "a. 自豪的，骄傲的", "english": "proud", "type": "单词", "keyWords": [] },
    { "chinese": "为…而感到自豪", "english": "be proud of...", "type": "短语", "keyWords": ["proud"] },
    { "chinese": "v. 证明；证实；vi. 证明是；结果是，原来是", "english": "prove", "type": "单词", "keyWords": [] },
    { "chinese": "这将向世人证明这幅画是赝品。", "english": "This will prove to the world that the painting is a fake.", "type": "句子", "keyWords": ["prove"] },
    { "chinese": "她证明自己无罪了吗？", "english": "Did she prove herself (to be) innocent?", "type": "句子", "keyWords": ["prove"] },
    { "chinese": "证明是；结果是，原来是", "english": "prove/ turn out (to be) + adj.", "type": "短语", "keyWords": ["prove"] },
    { "chinese": "谣言结果并不总是事实。", "english": "A rumour doesn't always prove (to be) a fact.", "type": "句子", "keyWords": ["prove"] },
    { "chinese": "他原来是个医生。", "english": "He proved (to be) a doctor.", "type": "句子", "keyWords": ["prove"] },
    { "chinese": "n. [C] 谚语；常言；格言", "english": "proverb", "type": "单词", "keyWords": [] },
    { "chinese": "俗话说…", "english": "As the proverb goes/says...", "type": "短语", "keyWords": ["proverb"] },
    { "chinese": "俗话说，一个萝卜一个坑儿。", "english": "Every pot, as the proverb has it, finds its cover.", "type": "句子", "keyWords": ["proverb"] },
    { "chinese": "v. 供给；提供（辨析见 afford）", "english": "provide", "type": "单词", "keyWords": [] },
    { "chinese": "n. [pl.] 供应品；[U] 供给；供应", "english": "provision", "type": "单词", "keyWords": ["provide"] },
    { "chinese": "为某人提供某物", "english": "provide/equip/supply sb. with sth.", "type": "短语", "keyWords": ["provide"] },
    { "chinese": "他们的食品不足。", "english": "They are ill provided with food.", "type": "句子", "keyWords": ["provide"] },
    { "chinese": "为某人提供某物", "english": "provide sth. for sb.", "type": "短语", "keyWords": ["provide"] },
    { "chinese": "如果；在…条件下（if）", "english": "provided (that)/providing (that)", "type": "短语", "keyWords": ["provide"] },
    { "chinese": "只要双方共同努力，中日关系的前景一定是光明的。", "english": "Provided that China and Japan make joint efforts, the Sino-Japanese relations must have a bright future.", "type": "句子", "keyWords": ["provide"] },
    { "chinese": "n. [C] 省；行政区", "english": "province", "type": "单词", "keyWords": [] },
    { "chinese": "a. 省的", "english": "provincial", "type": "单词", "keyWords": ["province"] },
    { "chinese": "n. [C] 心理学", "english": "psychology", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 心理学家", "english": "psychologist", "type": "单词", "keyWords": ["psychology"] },
    { "chinese": "a. 心理（学）的", "english": "psychological", "type": "单词", "keyWords": ["psychology"] },
    { "chinese": "n. [C] 酒馆，客栈；酒吧", "english": "pub", "type": "单词", "keyWords": [] },
    { "chinese": "a. 大众的，公共的；公开的", "english": "public", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 宣传；推广；广告", "english": "publicity", "type": "单词", "keyWords": ["public"] },
    { "chinese": "v. （尤指用广告）宣传；引人注意", "english": "publicize", "type": "单词", "keyWords": ["public"] },
    { "chinese": "ad. 公开地", "english": "publicly", "type": "单词", "keyWords": ["public"] },
    { "chinese": "当众，公开地", "english": "in public (=publicly)", "type": "短语", "keyWords": ["public"] },
    { "chinese": "（用作单或复数）公众", "english": "the public", "type": "短语", "keyWords": ["public"] },
    { "chinese": "民意，舆论", "english": "public opinion", "type": "短语", "keyWords": ["public"] },
    { "chinese": "公共交通工具", "english": "public transport", "type": "短语", "keyWords": ["public"] },
    { "chinese": "公开…", "english": "make... public", "type": "短语", "keyWords": ["public"] },
    { "chinese": "对公众开放", "english": "be open to the public", "type": "短语", "keyWords": ["public"] },
    { "chinese": "n. [U] 出版；发行；[C] 出版物", "english": "publication", "type": "单词", "keyWords": ["public"] },
    { "chinese": "v. 出版；发行；发表，公布", "english": "publish", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 出版者，发行人", "english": "publisher", "type": "单词", "keyWords": ["publish"] },
    { "chinese": "出版社", "english": "a publishing house", "type": "短语", "keyWords": ["publish"] },
    { "chinese": "n. [C]/[U] 布丁（西餐中最后上的一道松软甜食）", "english": "pudding", "type": "单词", "keyWords": [] },
    { "chinese": "v. 拉，拖；n. [U]（可加 a）拉，扯；（吸）引力", "english": "pull", "type": "单词", "keyWords": [] },
    { "chinese": "做鬼脸", "english": "pull a face", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "愁眉苦脸", "english": "pull a long face", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "拉扯…", "english": "pull at...", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "然后那猫用尖利的爪子拉扯自己的毛。", "english": "Then the cat pulled at its own fur with its sharp claws.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "(车辆) 驶离（路边）；离开；后退；(v.) 拉走", "english": "pull (away)", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "她企图从抓着她的那个男人挣脱出来。", "english": "She tried to pull away from the man who was holding her.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "(火车) 进站；(车辆等) 驶向路边停车", "english": "pull in", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "汽车开到车库停住了。", "english": "The car pulled in at the garage.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "快车一到，乘客们蜂拥而上抢座位。", "english": "As soon as the express pulled in, all the passengers rushed to get seats.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "(火车)离站；(船)划出；拔出；拉出", "english": "pull out", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "船离开了港口。", "english": "The ship pulled out of harbor.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "停住；使停住；拔起", "english": "pull up", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "他在入口处将车停了下来。", "english": "He pulled up his car at the entrance.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "公共汽车停了，因为前面是红灯。", "english": "The bus pulled up because the lights were red.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "拆除(房子)；把…拉倒/下来", "english": "pull (the house ...) down", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "(常指匆忙时)穿上，戴上", "english": "pull ... on", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "她匆匆穿上一件羊毛衫迅速离开了。", "english": "She pulled on a sweater and left quickly.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "(使车、船)驶向/到路边或岸边", "english": " pull over", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "我们停下车看日落。", "english": "We pulled over to watch the sunset.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "(使)恢复健康或度过危机", "english": "pull through", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "他们希望他能逃过这场大病。", "english": "They hoped that he would pull through (the serious illness).", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "我们最终设法渡过了难关。", "english": "We managed to pull through at length.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "精心的护理使他恢复了健康。", "english": "Good nursing pulled him through.", "type": "句子", "keyWords": ["pull"] },
    { "chinese": "拉一下绳子", "english": "give a pull at the rope", "type": "短语", "keyWords": ["pull"] },
    { "chinese": "n.(C)(毛线)套衫", "english": "pullover", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]脉搏;有节奏的搏动", "english": "pulse", "type": "单词", "keyWords": [] },
    { "chinese": "给某人诊脉", "english": "feel sb's pulse", "type": "短语", "keyWords": ["pulse"] },
    { "chinese": "n.[C]泵;v.(用泵)抽(水);用打气筒打(气)(up)", "english": "pump", "type": "单词", "keyWords": [] },
    { "chinese": "往轮胎里打气", "english": "pump air into a tyre = pump up a tire", "type": "短语", "keyWords": ["pump"] },
    { "chinese": "为经济注入新生命", "english": "pump new life into the economy", "type": "短语", "keyWords": ["pump"] },
    { "chinese": "心脏使血液循环", "english": "The heart pumps blood.", "type": "句子", "keyWords": ["pump"] },
    { "chinese": "n.[C]南瓜", "english": "pumpkin", "type": "单词", "keyWords": [] },
    { "chinese": "a.守时的;准时的", "english": "punctual", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)标点(符号)", "english": "punctuation", "type": "单词", "keyWords": [] },
    { "chinese": "一个标点符号", "english": "a punctuation mark", "type": "短语", "keyWords": ["punctuation"] },
    { "chinese": "v.惩罚,处罚", "english": "punish", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C][U]惩罚,处罚", "english": "punishment", "type": "单词", "keyWords": [] },
    { "chinese": "因某事通过某方式惩罚某人", "english": "punish sb.for (doing) sth.by doing sth.", "type": "短语", "keyWords": ["punish"] },
    { "chinese": "n.[C]小学生;学生;n.[C]瞳孔", "english": "pupil", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]小狗", "english": "puppy", "type": "单词", "keyWords": [] },
    { "chinese": "vt/n.(U)采购;购买;n.(C)所购物", "english": "purchase", "type": "单词", "keyWords": [] },
    { "chinese": "购买", "english": "make purchases", "type": "短语", "keyWords": ["purchase"] },
    { "chinese": "购买力", "english": "purchasing power", "type": "短语", "keyWords": ["purchase"] },
    { "chinese": "a.纯的;完美的;十足的,完全的", "english": "pure", "type": "单词", "keyWords": [] },
    { "chinese": "v.使纯净;净化", "english": "purify", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)纯净,纯洁,纯度", "english": "purity", "type": "单词", "keyWords": [] },
    { "chinese": "十足的浪费时间", "english": "a pure waste of time", "type": "短语", "keyWords": ["pure"] },
    { "chinese": "n.(U)紫色;a.紫色的", "english": "purple", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)目的;意图", "english": "purpose", "type": "单词", "keyWords": [] },
    { "chinese": "a.有目的的", "english": "purposeful", "type": "单词", "keyWords": [] },
    { "chinese": "故意地;有意地", "english": "on purpose", "type": "短语", "keyWords": ["purpose"] },
    { "chinese": "为的是;为了...的目的", "english": "for the purpose of...", "type": "短语", "keyWords": ["purpose"] },
    { "chinese": "n.[C]钱包;女用小包", "english": "purse", "type": "单词", "keyWords": [] },
    { "chinese": "v.追逐,追捕;继续;从事", "english": "pursue", "type": "单词", "keyWords": [] },
    { "chinese": "追击敌人", "english": "pursue the enemy", "type": "短语", "keyWords": ["pursue"] },
    { "chinese": "从事研究", "english": "pursue one's studies", "type": "短语", "keyWords": ["pursue"] },
    { "chinese": "寻欢作乐", "english": "pursue pleasure", "type": "短语", "keyWords": ["pursue"] },
    { "chinese": "继续讨论", "english": "pursue a discussion", "type": "短语", "keyWords": ["pursue"] },
    { "chinese": "对世界人民我们一贯奉行友好政策", "english": "We have always pursued a friendly policy towards the people all over the world.", "type": "句子", "keyWords": ["pursue"] },
    { "chinese": "n.[U)追捕;追求;n.[C]爱好", "english": "pursuit", "type": "单词", "keyWords": [] },
    { "chinese": "追求,寻求", "english": "in pursuit of", "type": "短语", "keyWords": ["pursuit"] },
    { "chinese": "v.推,推动;敦促;n.(C)推,推动;奋发", "english": "push", "type": "单词", "keyWords": [] },
    { "chinese": "推开门", "english": "push a door open", "type": "短语", "keyWords": ["push"] },
    { "chinese": "从人群中挤出", "english": "push one's way through a crowd", "type": "短语", "keyWords": ["push"] },
    { "chinese": "推动某人去做某事", "english": "push sb. to do sth.=push sb. into doing sth.", "type": "短语", "keyWords": ["push"] },
    { "chinese": "鞭策这孩子更努力地学习", "english": "push a child to study harder", "type": "短语", "keyWords": ["push"] },
    { "chinese": "向前推进,奋力前进", "english": "push on", "type": "短语", "keyWords": ["push"] },
    { "chinese": "我在大雪中努力前进", "english": "I pushed on through the snow.", "type": "句子", "keyWords": ["push"] },
    { "chinese": "坚决进行(下去),继续(进行)", "english": "push on/ahead with", "type": "短语", "keyWords": ["push"] },
    { "chinese": "继续贯彻这个计划", "english": "push ahead with the plan", "type": "短语", "keyWords": ["push"] },
    { "chinese": "她使劲一推,门开了", "english": "She gave the door a hard push, and it opened.", "type": "句子", "keyWords": ["push"] },
    { "chinese": "v.放;表达,说;使处于某状态", "english": "put", "type": "单词", "keyWords": [] },
    { "chinese": "把...收起,放好;存储", "english": "put...away", "type": "短语", "keyWords": ["put"] },
    { "chinese": "请你把餐具擦干,收拾好", "english": "Please dry the dishes and put them away.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "她存了不少钱", "english": "She has a nice sum of money put away.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "放下;记下;镇压", "english": "put...down", "type": "短语", "keyWords": ["put"] },
    { "chinese": "制止流言", "english": "put down rumors", "type": "短语", "keyWords": ["put"] },
    { "chinese": "扫平叛乱", "english": "put down a rebellion", "type": "短语", "keyWords": ["put"] },
    { "chinese": "提出;建议;把(钟表指针)前拔", "english": "put forward", "type": "短语", "keyWords": ["put"] },
    { "chinese": "关掉,熄灭;脱掉;推迟;让...下车;使讨厌", "english": "put...off", "type": "短语", "keyWords": ["put"] },
    { "chinese": "你想在哪儿下车?", "english": "Where do you want to be put off(the bus)?", "type": "句子", "keyWords": ["put"] },
    { "chinese": "他出言不逊使她很反感", "english": "She has been put off by his offensive remarks.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "穿上;上演;开(灯、收音机等);装出", "english": "put...on", "type": "短语", "keyWords": ["put"] },
    { "chinese": "穿鞋/上演戏剧", "english": "put on shoes/a play", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他交了个百万富翁朋友后就学会了装腔作势", "english": "He put on airs after making friends with a millionaire.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "熄灭;出版;公布;伸出;生产", "english": "put... out", "type": "短语", "keyWords": ["put"] },
    { "chinese": "关灯/灭火/熄掉烟", "english": "put out the lights/ the fire/ the cigarette", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他们已经出版了一种新的期刊", "english": "They have already put out a new periodical.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "伸出某人的舌头/手", "english": "put out one's tongue/ one'shand", "type": "短语", "keyWords": ["put"] },
    { "chinese": "把头伸出窗外", "english": "put/ stick your head out of the window", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他们生产了几台高级发动机", "english": "They put out/ tum out some motors of high standards.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "举起;搭建;张贴;提出(计划等);留宿", "english": "put...up", "type": "短语", "keyWords": ["put"] },
    { "chinese": "把手举起来!", "english": "Put up your hands!", "type": "句子", "keyWords": ["put"] },
    { "chinese": "张贴启事/海报", "english": "put up a notice/ posters", "type": "短语", "keyWords": ["put"] },
    { "chinese": "搭起帐蓬/ 盖楼", "english": "put up the tent/ buildings", "type": "短语", "keyWords": ["put"] },
    { "chinese": "我们在农舍投宿了一夜", "english": "We put up for the night at a farmhouse.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "无论你们何时进城,我们都很乐意为你们提供食宿", "english": "We shall be happy to put you up whenever you come to town.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "容忍", "english": "put up with..", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他们接受对方的要求并容忍对方的缺点", "english": "They accept demands and put up with shortcomings.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "她得忍受十个孩子的吵闹", "english": "She had ten children to put up with.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "使...睡觉;把...放或送到床上", "english": "put/send...to bed", "type": "短语", "keyWords": ["put"] },
    { "chinese": "母亲要洗碗碟又要哄孩子睡觉,以致开会迟到", "english": "With dishes to wash and children to put to bed, Mother was late for the meeting.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "纠正", "english": "put sth.right", "type": "短语", "keyWords": ["put"] },
    { "chinese": "小错误必须很快得到纠正", "english": "Minor mistakes must be quickly put right.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "那使得我有点气喘吁吁", "english": "That put me a little out of breath.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "我不知道该怎么表达", "english": "I don't know how toput/ express it.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "她,该怎么说呢,并不真胖,但就她年龄而言她是比较壮实了一些", "english": "She is - how shall I put it? - not exactly fat, but rather well-built for her age.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "制止;终结", "english": "put an end to...", "type": "短语", "keyWords": ["put"] },
    { "chinese": "人类必须消灭战争,否则战争将消灭人类", "english": "Mankind must put an end to war or war will put an end to mankind.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "放一边;存储", "english": "put...aside", "type": "短语", "keyWords": ["put"] },
    { "chinese": "他们决定暂且抛开彼此的分歧", "english": "They decided to put aside their differences for amoment.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "使穿过;接通(电话);使经受;使完成", "english": "put... through (to...)", "type": "短语", "keyWords": ["put"] },
    { "chinese": "请把电话接进来", "english": "Put him through, please.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "请您转马丁先生", "english": "Please put me through to Mr. Martin.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "他使我遇到许多麻烦", "english": "He put me through a lot of trouble.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "尼克靠父亲遗留下来的钱念完了大学", "english": "Nick was put through university with the money left by his father.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "他在周末做成了一笔重要的生意", "english": "He put through an important business deal over the weekend.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "考验;检验", "english": "put ... to a/ the test", "type": "短语", "keyWords": ["put"] },
    { "chinese": "理论必须通过实践来检验", "english": "Theories must be put to the test of practice.", "type": "句子", "keyWords": ["put"] },
    { "chinese": "实施、贯彻等", "english": "put .. into force/ effect/ use/ practice/ operation", "type": "短语", "keyWords": ["put"] },
    { "chinese": "体重增加", "english": "put on weight", "type": "短语", "keyWords": ["put"] },
    { "chinese": "v.(使)迷惑;(使)为难;n.(C)难题;费解之事,迷惑;谜", "english": "puzzle", "type": "单词", "keyWords": [] },
    { "chinese": "a.使迷惑的,使莫名其妙的", "english": "puzzling", "type": "单词", "keyWords": [] },
    { "chinese": "a.困惑的", "english": "puzzled", "type": "单词", "keyWords": [] },
    { "chinese": "(对听到或看到的事)感到困惑", "english": "be puzzled at", "type": "短语", "keyWords": ["puzzle"] },
    { "chinese": "他不愿意帮忙让我有点困惑", "english": "I was somewhat puzzled at his unwillingness to help.", "type": "句子", "keyWords": ["puzzle"] },
    { "chinese": "听了这话我感到有些迷惑不解", "english": "I felt rather puzzled at the words.", "type": "句子", "keyWords": ["puzzle"] },
    { "chinese": "对...感到迷惑", "english": "be puzzled over/about", "type": "短语", "keyWords": ["puzzle"] },
    { "chinese": "他完全不知道接下去该怎么办", "english": "He was quitc puzzled about what to do next.", "type": "句子", "keyWords": ["puzzle"] },
    { "chinese": "苦思冥想", "english": "puzzle over/ about...", "type": "短语", "keyWords": ["puzzle"] },
    { "chinese": "n.(pl)睡衣", "english": "pyjamas", "type": "单词", "keyWords": [] },
    { "chinese": "一套睡衣", "english": "a pair of pyjamas", "type": "短语", "keyWords": ["pyjamas"] },
    { "chinese": "n.[C]金字塔;角锥状物", "english": "pyramid", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C] 地震 vi. 震动；摇动；颤动 (辨析见 shake)", "english": "quake /kweɪk/n.[C] vi.", "type": "单词", "keyWords": [] },
    { "chinese": "n.C资格；资格 (证明)","english":"qualification /ˌkwɒlɪfɪ'keɪʃn/n.[C]","type":" 单词 ","keyWords": [] },
    { "chinese": "adj. 合格的，有资格的；胜任的 (反 unqualified)", "english": "qualified /'kwɒlɪfaɪd/adj.", "type": "单词", "keyWords": [] },
    { "chinese": "胜任做某事", "english": "be qualified/fit for sth./to do sth.", "type": "短语", "keyWords": ["qualified"] },
    { "chinese": "v. 使具有资格；使胜任 vi. 取得资格；胜任", "english": "qualify /'kwɒlɪfaɪ/vt. vi.", "type": "单词", "keyWords": [] },
    { "chinese": "使… 有… 资格", "english": "qualify (sb.) for sth./as...", "type": "短语", "keyWords": ["qualify"] },
    { "chinese": "你具备获得联邦政府贷款项目的资格吗？", "english": "Do you qualify for any of the federal loan programs?", "type": "句子", "keyWords": ["qualify"] },
    { "chinese": "约翰逊没有通过当医生的资格考试，决定从事绘画工作。", "english": "Johnson, having failed to qualify as a doctor, decided to take up painting.", "type": "句子", "keyWords": ["qualify"] },
    { "chinese": "他的技术使他能胜任这份工作。", "english": "His skill qualifies him for the job.", "type": "句子", "keyWords": ["qualify"] },
    { "chinese": "你必须使自己具备担任这一工作的资格。", "english": "You must qualify yourself for the post.", "type": "句子", "keyWords": ["qualify"] },
    { "chinese": "n.[U] 品质；品级；质量 n.[C] 特点，特性，性质", "english": "quality /'kwɒlətɪ/n.[U] n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "质量好 / 低劣", "english": "be of good/high/low/poor quality", "type": "短语", "keyWords": ["quality"] },
    { "chinese": "在质量或大小上都属下等的", "english": "be inferior in quality or size", "type": "短语", "keyWords": ["quality"] },
    { "chinese": "n.[C][U] 量；数量；总量 (近 amount)", "english": "quantity /'kwɒntətɪ/n.[C][U]", "type": "单词", "keyWords": [] },
    { "chinese": "大 / 小量的", "english": "large/small quantities of = a large/small quantity of", "type": "短语", "keyWords": ["quantity"] },
    { "chinese": "大 / 少量销售煤炭", "english": "sell coal in large/small quantities", "type": "短语", "keyWords": ["quantity"] },
    { "chinese": "桌上有大量食物。", "english": "Quantities of food are on the table. = A large quantity of food is on the table.", "type": "句子", "keyWords": ["quantity"] },
    { "chinese": "桌上有大量报纸。", "english": "Quantities of newspapers are on the table. = A large quantity of newspapers are on the table.", "type": "句子", "keyWords": ["quantity"] },
    { "chinese": "我重质量胜过数量。", "english": "I prefer quality to quantity.", "type": "句子", "keyWords": ["quantity"] },
    { "chinese": "v./n.[C] 争吵；吵嘴；失和", "english": "quarrel /'kwɒrəl/v./n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "因某事同某人吵架", "english": "(have a) quarrel with sb. about sth.", "type": "短语", "keyWords": ["quarrel"] },
    { "chinese": "n.[C] 一刻钟；四分之一；季度；城市的特定地区；(美、加) 两角五分的辅币；(pl)(尤指佣人或军人) 住所；军营 (近 headquarters 军队司令部，大本营)", "english": "quarter /'kwɔːtə/n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "法国人特区", "english": "the French Quarter", "type": "短语", "keyWords": ["quarter"] },
    { "chinese": "您有一些 25 分的硬币吗？", "english": "Have you got some quarters?", "type": "句子", "keyWords": ["quarter"] },
    { "chinese": "我们必须在天黑之前找到住处。", "english": "We must find quarters before night falls.", "type": "句子", "keyWords": ["quarter"] },
    { "chinese": "n.[C] 女王；王后", "english": "queen /kwiːn/n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]问题 n.[U]怀疑 v.询问；审问；怀疑", "english": "question /'kwestʃən/ n.[C] n.[U] v.", "type": "单词", "keyWords": [] },
    { "chinese": "不是钱财问题", "english": "be not a question of money", "type": "短语", "keyWords": ["question"] },
    { "chinese": "它的消失只是一个时间问题。", "english": "Its extinction is just a question of time.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "我们取得这些商品的进口许可证是不成问题的。", "english": "There is no question about/as to our getting the import license for these articles.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "没问题(近beyond doubt)", "english": "beyond/out of/without question", "type": "短语", "keyWords": ["question"] },
    { "chinese": "受盘问(类under consideration/ repair/ discussion/way/attack/ construction)", "english": "*under question", "type": "短语", "keyWords": ["question"] },
    { "chinese": "正被讨论；在讨论中", "english": "*in question", "type": "短语", "keyWords": ["question"] },
    { "chinese": "那不是要考虑的要点。", "english": "That is not the point in question.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "关于是否存在全球变暖的问题，仍在讨论中。", "english": "The existence of global warming is in question.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "不可能", "english": "*out of the question", "type": "短语", "keyWords": ["question"] },
    { "chinese": "从头开始是不可能的。", "english": "Starting over is out of the question.", "type": "句子", "keyWords": ["question"] },
    { "chinese": "n.[C](等候的人或车的)长队，队列 v.排队(等候)", "english": "queue /kjuː/ n.[C] v.", "type": "单词", "keyWords": [] },
    { "chinese": "插队；抢先", "english": "jump the queue", "type": "短语", "keyWords": ["queue"] },
    { "chinese": "他们排队等候出租汽车。", "english": "They queued(up) for a taxi.", "type": "句子", "keyWords": ["queue"] },
    { "chinese": "adj.快的；迅速的；敏锐(捷)的，聪明的，脑子反应快的(辨析见fast) quickness n.[U]迅速，敏捷 quicken vt.加快 quickly ad.快地，迅速地", "english": "quick /kwɪk/ adj. quickness n.[U] quicken vt. quickly ad.", "type": "单词", "keyWords": [] },
    { "chinese": "有敏捷的头脑", "english": "have a quick mind", "type": "短语", "keyWords": ["quick"] },
    { "chinese": "学某事学得快", "english": "be quick to learn sth.", "type": "短语", "keyWords": ["quick"] },
    { "chinese": "在(做)某事方面迅速(近 be clever/good at 反 be clumsy at)", "english": "be quick at (doing) sth.", "type": "短语", "keyWords": ["quick"] },
    { "chinese": "adj.安静的；平静的；轻声的 v.(使)平静 quietly ad.安静地 quietness n.(U)", "english": "quiet /'kwaɪət/ adj. v. quietly ad. quietness n.(U)", "type": "单词", "keyWords": [] },
    { "chinese": "对某事保守秘密，隐瞒某事", "english": "keep quiet about sth.", "type": "短语", "keyWords": ["quiet"] },
    { "chinese": "非常安静，不声不响", "english": "*be as quiet as a mouse", "type": "短语", "keyWords": ["quiet"] },
    { "chinese": "辨析：still, quiet, silent, calm still指没有运动或骚扰，常表示静止不动或平静，通常这种情况是暂时的；quiet指没有噪音、混乱、骚乱、烦扰、波澜，有时隐含有永久的味道；silent指没有声音或噪音，并不一定和动作有关；calm主要指天气或大海的平静，也指心态不受激动、急躁等的干扰而显得平静、镇静。", "english": "辨析:still, quiet, silent, calm still指没有运动或骚扰，常表示静止不动或平静，通常这种情况是暂时的；quiet指没有噪音、混乱、骚乱、烦扰、波澜，有时隐含有永久的味道；silent指没有声音或噪音，并不一定和动作有关；calm主要指天气或大海的平静，也指心态不受激动、急躁等的干扰而显得平静、镇静。", "type": "句子", "keyWords": ["quiet"] },
    { "chinese": "n.[C]被子", "english": "quilt /kwɪlt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "v.停止；放弃；离开；离职，辞职", "english": "quit /kwɪt/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "辞去工作", "english": "quit a job", "type": "短语", "keyWords": ["quit"] },
    { "chinese": "停止说话", "english": "quit talking", "type": "短语", "keyWords": ["quit"] },
    { "chinese": "adv.很，十分；完全，彻底(辨析见fairly)", "english": "quite /kwaɪt/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "很不同的一种语言", "english": "quite a different language", "type": "短语", "keyWords": ["quite"] },
    { "chinese": "非常多(的人)(近quite a few)", "english": "quite a lot(of people)", "type": "短语", "keyWords": ["quite"] },
    { "chinese": "和…完全一样…(用于同级比较结构前)", "english": "quite as...as...", "type": "短语", "keyWords": ["quite"] },
    { "chinese": "极不可能的/不同的/合理的/完美的/正确的/确定的(用于无比较级的形容词或副词前)", "english": "quite impossible/different/reasonable/perfect/right/certain", "type": "短语", "keyWords": ["quite"] },
    { "chinese": "我并不完全理解你。", "english": "I don't quite follow you.", "type": "句子", "keyWords": ["quite"] },
    { "chinese": "这已过时。", "english": "It's quite out of fashion.", "type": "句子", "keyWords": ["quite"] },
    { "chinese": "n.[C](pl.quizzes)(短的口头或书面)测试；(电视中的)问答比赛", "english": "quiz /kwɪz/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "v.引用；援引(from) quotation n.[C](U)引语；引文；语录", "english": "quote /kwəʊt/ v. quotation n.[C](U)", "type": "单词", "keyWords": [] },
    { "chinese": "作者经常引用莎士比亚作品里的话。", "english": "The author frequently quoted Shakespeare.", "type": "句子", "keyWords": ["quote"] },
    { "chinese": "这位牧师引用了《圣经》里的话。", "english": "The minister quoted from the Bible.", "type": "句子", "keyWords": ["quote"] },
    { "chinese": "n.[C]兔子", "english": "rabbit /'ræbɪt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "v.和…赛速度；和…竞赛 n.[C]赛跑；竞赛；人种；种族", "english": "race /reɪs/ v. n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "及时冲回家", "english": "race home in time", "type": "短语", "keyWords": ["race"] },
    { "chinese": "和汤姆赛跑", "english": "run a race with Tom", "type": "短语", "keyWords": ["race"] },
    { "chinese": "和时间赛跑", "english": "a race against time", "type": "短语", "keyWords": ["race"] },
    { "chinese": "种族歧视/种族冲突", "english": "racial discrimination/conflict", "type": "短语", "keyWords": ["race"] },
    { "chinese": "人类", "english": "the human race", "type": "短语", "keyWords": ["race"] },
    { "chinese": "adj.种族的", "english": "racial /'reɪʃəl/ adj.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]雷达", "english": "radar /'reɪdɑː/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]辐射 *n.[C][U]辐射物 *radiate v.发光，辐射；放射", "english": "radiation /ˌreɪdɪ'eɪʃn/ n.[U] *n.[C][U] *radiate v.", "type": "单词", "keyWords": [] },
    { "chinese": "adj.激进的 n.[C]激进分子", "english": "radical /'rædɪkl/ adj. n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]收音机 n.[U]无线电；无线电台；无线通信", "english": "radio /'reɪdɪəʊ/ n.[C] n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "通过无线电", "english": "by radio", "type": "短语", "keyWords": ["radio"] },
    { "chinese": "作广播讲话", "english": "speak on the radio", "type": "短语", "keyWords": ["radio"] },
    { "chinese": "n.[U]放射性", "english": "radioactivity /'reɪdɪəʊæk'tɪvəti/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.放射性的", "english": "radioactive adj.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]镭", "english": "radium /'reɪdiəm/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]破布；抹布", "english": "rag /ræg/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "衣衫褴褛", "english": "(be dressed) in rags", "type": "短语", "keyWords": ["rag"] },
    { "chinese": "被撕碎", "english": "be torn to rags", "type": "短语", "keyWords": ["rag"] },
    { "chinese": "n.[C]提杆；栏杆；(常pl)铁路；铁轨", "english": "rail /reɪl/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "靠在栏杆上", "english": "lean over the rail", "type": "短语", "keyWords": ["rail"] },
    { "chinese": "n.[C]铁路[美]railroad", "english": "railway /'reɪlweɪ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "火车站", "english": "railway station", "type": "短语", "keyWords": ["railway"] },
    { "chinese": "v.下(雨)；(使)如雨下 n.[U](可与a连用)雨；下雨；如雨般降落", "english": "rain /reɪn/ v. n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.有雨的；多雨的", "english": "rainy a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]雨量", "english": "rainfall n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]雨滴，雨点", "english": "raindrop n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "弹如雨下", "english": "a rain of bullets", "type": "短语", "keyWords": ["rain"] },
    { "chinese": "看来要下雨", "english": "look like rain", "type": "短语", "keyWords": ["rain"] },
    { "chinese": "n.[C]雨衣", "english": "raincoat n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]热带雨林", "english": "rainforest n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "下倾盆大雨", "english": "rain cats and dogs", "type": "短语", "keyWords": ["rain"] },
    { "chinese": "一阵大/小/细雨", "english": "a heavy/light/fine rain", "type": "短语", "keyWords": ["rain"] },
    { "chinese": "雨过天晴；否极泰来。", "english": "After rain comes fair weather.", "type": "句子", "keyWords": ["rain"] },
    { "chinese": "不下则已，一下倾盆。不来则已，一来便接踵而至(尤指坏事)", "english": "It never rains but it pours.", "type": "句子", "keyWords": ["rain"] },
    { "chinese": "n.[C]彩虹", "english": "rainbow /'reɪnbəʊ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.防雨的；防水的", "english": "rainproof /'reɪnpruːf/ adj.", "type": "单词", "keyWords": [] },
    { "chinese": "v.举起；使升高；筹集；招募；种植；养育", "english": "raise /reɪz/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "抬起头/提高嗓门", "english": "raise one's head/one's voice", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "对……表示钦佩", "english": "raise one's hat to sb.", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "扬起一片尘土", "english": "raise a cloud of dust", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "提出一个问题", "english": "raise a question/an issue", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "养育孩子/养牛/种植小麦", "english": "raise children/cattle/wheat", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "声音大得能把死人吵醒", "english": "noise that would raise the dead", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "为一个慈善组织筹款", "english": "raise money/funds for a charity", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "凸起的点/高出周围地面的站台", "english": "raised dots/platform", "type": "短语", "keyWords": ["raise"] },
    { "chinese": "n.[U]随意行动；随机(只用于at random) adj.任意(选取)的；随机的", "english": "random /'rændəm/ n.[U] adj.", "type": "单词", "keyWords": [] },
    { "chinese": "随便地，胡乱地，漫无目的地", "english": "at random", "type": "短语", "keyWords": ["random"] },
    { "chinese": "n.[C]排；行；走向；山脉；等级；幅度；范围；射程 v.排列；把…分类 vi.(在某范围内)变动，变化；绵亘，延伸", "english": "range /reɪndʒ/ n.[C] v. vi.", "type": "单词", "keyWords": [] },
    { "chinese": "一排楼房", "english": "a range of buildings", "type": "短语", "keyWords": ["range"] },
    { "chinese": "视觉范围", "english": "the range of vision", "type": "短语", "keyWords": ["range"] },
    { "chinese": "每年的温度变化范围", "english": "the annual range of temperature", "type": "短语", "keyWords": ["range"] },
    { "chinese": "广博的知识", "english": "a wide range of knowledge", "type": "短语", "keyWords": ["range"] },
    { "chinese": "把书排列在书架上", "english": "range books on the shelf", "type": "短语", "keyWords": ["range"] },
    { "chinese": "在…到…之间变化；绵亘", "english": "range from...to.../between...and...", "type": "短语", "keyWords": ["range"] },
    { "chinese": "两岁至五岁年龄段", "english": "ages that ranged from two to five", "type": "短语", "keyWords": ["range"] },
    { "chinese": "价格自五美元至十美元不等。", "english": "Prices ranged from 5 dollars to 10.", "type": "句子", "keyWords": ["range"] },
    { "chinese": "从A地延伸到B地的边界", "english": "a boundary that ranges from A to B", "type": "短语", "keyWords": ["range"] },
    { "chinese": "这炮的射程可达五英里多。", "english": "The gun ranges over five miles.", "type": "句子", "keyWords": ["range"] },
    { "chinese": "在射程外", "english": "out of/beyond range", "type": "短语", "keyWords": ["range"] },
    { "chinese": "航程", "english": "flying range", "type": "短语", "keyWords": ["range"] },
    { "chinese": "能力达不到的；知识以外的", "english": "out of one's range", "type": "短语", "keyWords": ["range"] },
    { "chinese": "v.(给…)分等；把…排成行 n.[C]排；行，列；队列；地位；军衔；等级", "english": "rank /ræŋk/ v. n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "名单上位居第一", "english": "rank first on the list", "type": "短语", "keyWords": ["rank"] },
    { "chinese": "(是)一流的", "english": "(be) of (the) first rank", "type": "短语", "keyWords": ["rank"] },
    { "chinese": "各阶层的人们", "english": "*people of all ranks", "type": "短语", "keyWords": ["rank"] },
    { "chinese": "adj.快的；迅速的 rapidly ad.迅速地", "english": "rapid /'ræpɪd/ adj. rapidly ad.", "type": "单词", "keyWords": [] },
    { "chinese": "adj.稀有的；罕见的，难得的；珍奇的 rarely ad. *rarity /'reərəti/ n.[U]稀有 [C]稀有物", "english": "rare /reə/ adj. rarely ad. *rarity /'reərəti/ n.[U] [C]", "type": "单词", "keyWords": [] },
    { "chinese": "难得地", "english": "on rare occasions", "type": "短语", "keyWords": ["rare"] },
    { "chinese": "珍禽", "english": "a rare bird", "type": "短语", "keyWords": ["rare"] },
    { "chinese": "辨析：rare, scarce rare指本来世界上就少见；scarce指一时供不应求而少见。", "english": "辨析:rare, scarce rare指本来世界上就少见；scarce指一时供不应求而少见。", "type": "句子", "keyWords": ["rare"] },
    { "chinese": "n.[C]大老鼠", "english": "rat /ræt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]率，比率；等级", "english": "rate /reɪt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "以…的比率/速度", "english": "at the/a rate of", "type": "短语", "keyWords": ["rate"] },
    { "chinese": "目前每年利率是1%。", "english": "Interest is paid at the rate of 1% per year at present.", "type": "句子", "keyWords": ["rate"] },
    { "chinese": "以每公斤3元/特别折扣价…", "english": "(at the speed/the price/the expense/the cost) 3 yuan a kilo/a special discount...", "type": "短语", "keyWords": ["rate"] },
    { "chinese": "不管怎样", "english": "at any rate", "type": "短语", "keyWords": ["rate"] },
    { "chinese": "不管怎样，大家相信情况就是这样。", "english": "At any rate, that is believed to be the case.", "type": "句子", "keyWords": ["rate"] },
    { "chinese": "照这/那样下去", "english": "at this/that rate", "type": "短语", "keyWords": ["rate"] },
    { "chinese": "照这种形势看来，我们就无法度假了。", "english": "At this rate we will be unable to have a holiday.", "type": "句子", "keyWords": ["rate"] },
    { "chinese": "adv.相当，颇(辨析见fairly)；宁愿，宁可；更确切地(说)", "english": "rather /'rɑːðə/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "非常热的一天", "english": "rather (quite) a hot day/ a rather hot day", "type": "短语", "keyWords": ["rather"] },
    { "chinese": "更糟糕/太差(可修饰比较级和too短语)", "english": "rather worse/ rather too bad", "type": "短语", "keyWords": ["rather"] },
    { "chinese": "更确切地说", "english": "or rather", "type": "单词", "keyWords": [] },
    { "chinese": "宁愿做某事也不做某事", "english": "would do sth. rather than(do) sth.", "type": "短语", "keyWords": ["rather"] },
    { "chinese": "宁愿做某事也不做某事", "english": "would rather do sth. than do sth.", "type": "短语", "keyWords": ["rather"] },
    { "chinese": "某人宁愿做某事也不做某事", "english": "sb. would prefer to do sth. rather than do sth.", "type": "短语", "keyWords": ["rather"] },
    { "chinese": "而不", "english": "rather than", "type": "短语", "keyWords": ["rather"] },
    { "chinese": "我倒认为他会做的。", "english": "I rather thought that he would do that.", "type": "句子", "keyWords": ["rather"] },
    { "chinese": "他昨夜回家很晚，或者更确切地说，已是今天凌晨。", "english": "He came home very late last night, or rather very early this morning.", "type": "句子", "keyWords": ["rather"] },
    { "chinese": "不愿引起麻烦，他走开了。", "english": "Rather than cause trouble, he left.", "type": "句子", "keyWords": ["rather than"] },
    { "chinese": "他们宁愿饿死也不妥协。", "english": "They would rather starve than give way.", "type": "句子", "keyWords": ["would rather do sth. than do sth."] },
    { "chinese": "那是为他而不是为你。", "english": "This is rather for him than for you.", "type": "句子", "keyWords": ["rather than"] },
    { "chinese": "但愿他明天不来。", "english": "I'd rather he didn't come tomorrow.", "type": "句子", "keyWords": ["rather"] },
    { "chinese": "我们本想早点走，但那个时候没有公交车。", "english": "We would rather have left early, but there were no buses then.", "type": "句子", "keyWords": ["rather"] },
    { "chinese": "a. 生的；未加工的，自然状态的", "english": "raw", "type": "单词", "keyWords": [] },
    { "chinese": "原料", "english": "raw materials", "type": "短语", "keyWords": ["raw"] },
    { "chinese": "生肉", "english": "raw meat", "type": "短语", "keyWords": ["raw"] },
    { "chinese": "n. [C] 射线；光线；一线，一点点（希望）", "english": "ray", "type": "单词", "keyWords": [] },
    { "chinese": "连一线希望也没有了。", "english": "There wasn't a ray of hope left.", "type": "句子", "keyWords": ["ray"] },
    { "chinese": "表示“又，再，重新”", "english": "re-", "type": "单词", "keyWords": [] },
    { "chinese": "v. 抵达，到达；达到；伸出（肢体等）；联系上 vi. 到达；延伸；伸手拿（for） n. [C] 所及距离或范围", "english": "reach", "type": "单词", "keyWords": [] },
    { "chinese": "帮我伸手拿牛奶", "english": "reach me the milk", "type": "短语", "keyWords": ["reach"] },
    { "chinese": "伸手（去拿）", "english": "reach (one's hand or arm out)(for sth)", "type": "短语", "keyWords": ["reach"] },
    { "chinese": "达成协议/得出结论", "english": "reach an agreement/a conclusion", "type": "短语", "keyWords": ["reach"] },
    { "chinese": "怎么联系你？", "english": "How can I reach you?", "type": "句子", "keyWords": ["reach"] },
    { "chinese": "他们通过电话找到了我们。", "english": "They reached us by telephone.", "type": "句子", "keyWords": ["reach"] },
    { "chinese": "这个梯子够不到屋顶。", "english": "This ladder won't reach the roof.", "type": "句子", "keyWords": ["reach"] },
    { "chinese": "小男孩够不着书架。", "english": "The little boy couldn't reach the shelf.", "type": "句子", "keyWords": ["reach"] },
    { "chinese": "这块地一直延伸到河边。", "english": "The land reaches as far as the river.", "type": "句子", "keyWords": ["reach"] },
    { "chinese": "在可及的范围外/不能理解", "english": "beyond/out of one's reach", "type": "短语", "keyWords": ["reach"] },
    { "chinese": "这出乎我的想象。", "english": "It's out of the reach of my imagination.", "type": "句子", "keyWords": ["reach"] },
    { "chinese": "深远的影响", "english": "far-reaching effects", "type": "短语", "keyWords": ["reach"] },
    { "chinese": "在可及的范围内", "english": "within one's reach", "type": "短语", "keyWords": ["reach"] },
    { "chinese": "一大片草原", "english": "a reach of grassland", "type": "短语", "keyWords": ["reach"] },
    { "chinese": "vi. 作出反应；起作用；产生化学反应", "english": "react", "type": "单词", "keyWords": [] },
    { "chinese": "反抗；反对", "english": "react against", "type": "短语", "keyWords": ["react"] },
    { "chinese": "作出反应；回应", "english": "react to", "type": "短语", "keyWords": ["react"] },
    { "chinese": "眼睛对光有反应。", "english": "The eye reacts to light.", "type": "句子", "keyWords": ["react"] },
    { "chinese": "n. [C] [U] 反应；[物] 反作用力", "english": "reaction", "type": "单词", "keyWords": [] },
    { "chinese": "化学反应", "english": "chemical reaction", "type": "短语", "keyWords": ["reaction"] },
    { "chinese": "他对你的建议有什么反应？", "english": "What is his reaction to your proposal?", "type": "句子", "keyWords": ["reaction"] },
    { "chinese": "v. （阅）读；读起来；应读作，标明；读数为；钻研；看出（懂）", "english": "read", "type": "单词", "keyWords": [] },
    { "chinese": "大声朗读", "english": "read aloud", "type": "短语", "keyWords": ["read"] },
    { "chinese": "看出某人的心思", "english": "read one's mind/thoughts", "type": "短语", "keyWords": ["read"] },
    { "chinese": "大声念出名单上的名字。", "english": "read out the names on the list.", "type": "句子", "keyWords": ["read"] },
    { "chinese": "读出字里行间的意思", "english": "read between the lines", "type": "短语", "keyWords": ["read"] },
    { "chinese": "电压表的读数为10伏。", "english": "The voltmeter reads 10 volts.", "type": "句子", "keyWords": ["read"] },
    { "chinese": "通读；从头到尾细读一遍", "english": "read...through", "type": "短语", "keyWords": ["read"] },
    { "chinese": "我们一直看到末尾，但看不懂是什么意思。", "english": "We read it through but could make no sense of it.", "type": "句子", "keyWords": ["read"] },
    { "chinese": "n. [U] 阅读（能力）；朗读 [C] 读物；选读", "english": "reading", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 读者；读物；读卡机", "english": "reader", "type": "单词", "keyWords": [] },
    { "chinese": "a. 准备好的；愿意的", "english": "ready", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 乐意地，欣然地；迅速地", "english": "readily", "type": "单词", "keyWords": [] },
    { "chinese": "现成的（衣服）", "english": "ready-made (clothes)", "type": "短语", "keyWords": ["ready"] },
    { "chinese": "为……做好准备", "english": "get ready for", "type": "短语", "keyWords": ["ready"] },
    { "chinese": "老爱提建议", "english": "be too ready to give advice/with advice", "type": "短语", "keyWords": ["ready"] },
    { "chinese": "准备好做某事；乐于做某事", "english": "be ready to do", "type": "短语", "keyWords": ["ready"] },
    { "chinese": "把……准备好", "english": "get sth. ready", "type": "短语", "keyWords": ["ready"] },
    { "chinese": "a. 真的，真正的", "english": "real", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 确实；真实地；很", "english": "really", "type": "单词", "keyWords": [] },
    { "chinese": "a. 现实（主义）的，逼真的", "english": "realistic", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 现实；真实 [C] 事实", "english": "reality", "type": "单词", "keyWords": [] },
    { "chinese": "实际上", "english": "in reality = in fact", "type": "短语", "keyWords": ["reality"] },
    { "chinese": "把……变成现实", "english": "turn...into reality", "type": "短语", "keyWords": ["reality"] },
    { "chinese": "v. 认识到；体会到；明白；领悟；实现", "english": "realize", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 认识；明白；领悟；实现", "english": "realization", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 后部 a. 后面的；背面的；后方的", "english": "rear", "type": "单词", "keyWords": [] },
    { "chinese": "在房子的后部（房子的一部分）", "english": "in the rear (=back) of the house", "type": "短语", "keyWords": ["rear"] },
    { "chinese": "在房子的后面（不是房子的一部分）", "english": "at the rear (=back) of the house", "type": "短语", "keyWords": ["rear"] },
    { "chinese": "后门/后视镜/后轮/尾灯", "english": "the rear door/mirror/wheels/lights", "type": "短语", "keyWords": ["rear"] },
    { "chinese": "n. [C] 理由；原因 [U] 推理力；理智；道理 v. 推理；讲道理 vt. 推断；说服", "english": "reason", "type": "单词", "keyWords": [] },
    { "chinese": "a. 合理的；公道的；讲道理的", "english": "reasonable", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 推理；讲理", "english": "reasoning", "type": "单词", "keyWords": [] },
    { "chinese": "由于某种原因", "english": "for some reason", "type": "短语", "keyWords": ["reason"] },
    { "chinese": "由于某些原因", "english": "for some reasons", "type": "短语", "keyWords": ["reason"] },
    { "chinese": "……的原因", "english": "the reason for (doing) sth.", "type": "短语", "keyWords": ["reason"] },
    { "chinese": "他提出的缺席理由显然是瞎编的。", "english": "The reason he gave for his absence was obviously fictional.", "type": "句子", "keyWords": ["reason"] },
    { "chinese": "说服某人做/不做某事", "english": "reason sb. into/out of (doing) sth.", "type": "短语", "keyWords": ["reason"] },
    { "chinese": "为说服某人而与之理论", "english": "reason with sb.", "type": "短语", "keyWords": ["reason"] },
    { "chinese": "有充分的理由（做某事）", "english": "there is every reason (to do sth.)", "type": "短语", "keyWords": ["reason"] },
    { "chinese": "vi. 反叛/抗；造反（against） n. [C] 反叛者", "english": "rebel", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [U] 反叛；造反", "english": "rebellion", "type": "单词", "keyWords": [] },
    { "chinese": "a. 反叛的", "english": "rebellious", "type": "单词", "keyWords": [] },
    { "chinese": "v. 重建", "english": "rebuild", "type": "单词", "keyWords": [] },
    { "chinese": "v. 回忆，回想；召回（大使等）；回收", "english": "recall", "type": "单词", "keyWords": [] },
    { "chinese": "回想在哪里见过他", "english": "recall seeing him somewhere", "type": "短语", "keyWords": ["recall"] },
    { "chinese": "召回解雇了的工人", "english": "recall the workers who had been laid off", "type": "短语", "keyWords": ["recall"] },
    { "chinese": "vt. 收到，接到；接见；接待；遭受", "english": "receive", "type": "单词", "keyWords": [] },
    { "chinese": "n. 收受者；（电话）听筒", "english": "receiver", "type": "单词", "keyWords": [] },
    { "chinese": "在门口迎接客人", "english": "receive guests at the door", "type": "短语", "keyWords": ["receive"] },
    { "chinese": "（书、节目等）很受欢迎", "english": "be well received", "type": "短语", "keyWords": ["receive"] },
    { "chinese": "a. 被普遍接受的；公认的", "english": "received", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 收到 [C] 发票，收据", "english": "receipt", "type": "单词", "keyWords": [] },
    { "chinese": "a. 新近的，近来的", "english": "recent", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 最近；新近", "english": "recently", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [U]（可与a连用）接受；接收 [C] 招待会", "english": "reception", "type": "单词", "keyWords": [] },
    { "chinese": "服务台", "english": "reception desk", "type": "短语", "keyWords": ["reception"] },
    { "chinese": "客厅，接待室", "english": "reception room", "type": "短语", "keyWords": ["reception"] },
    { "chinese": "n. [C] 烹饪法；配方；[医] 处方", "english": "recipe", "type": "单词", "keyWords": [] },
    { "chinese": "蛋糕的制作法", "english": "a recipe for a cake", "type": "短语", "keyWords": ["recipe"] },
    { "chinese": "v. 背诵；朗诵", "english": "recite", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [U] 背诵；朗诵", "english": "recitation", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 认出，识别；承认", "english": "recognize", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 认出，识别", "english": "recognition", "type": "单词", "keyWords": [] },
    { "chinese": "承认……是……", "english": "recognize...as...", "type": "短语", "keyWords": ["recognize"] },
    { "chinese": "我们承认这个说法是真实的。", "english": "We recognize the statement as (being) true.", "type": "句子", "keyWords": ["recognize"] },
    { "chinese": "v. 推荐；介绍；建议（近advise的用法）", "english": "recommend", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 推荐 [C] 建议；介绍信", "english": "recommendation", "type": "单词", "keyWords": [] },
    { "chinese": "建议做某事", "english": "recommend/advise doing sth.", "type": "短语", "keyWords": ["recommend"] },
    { "chinese": "我们建议试验一个不同的位置。", "english": "We recommended trying a different location.", "type": "句子", "keyWords": ["recommend"] },
    { "chinese": "建议某人做某事", "english": "recommend/advise sb. to do sth.", "type": "短语", "keyWords": ["recommend"] },
    { "chinese": "她建议我们避免找麻烦。", "english": "She recommended us to avoid giving offense. = She recommended/ advised that we avoid giving offense.", "type": "句子", "keyWords": ["recommend"] },
    { "chinese": "推荐他做那项工作", "english": "recommend him for the job", "type": "短语", "keyWords": ["recommend"] },
    { "chinese": "n. [C] 记录；唱片；录了音的磁带 v. 记录；将（声、图像等）录下", "english": "record", "type": "单词", "keyWords": [] },
    { "chinese": "v. 记录；录音", "english": "record", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 录音机", "english": "recorder", "type": "单词", "keyWords": [] },
    { "chinese": "把……记录下来", "english": "keep a record/ records of sth.", "type": "短语", "keyWords": ["record"] },
    { "chinese": "创新纪录", "english": "set(up) a new record", "type": "短语", "keyWords": ["record"] },
    { "chinese": "打破纪录", "english": "break a record", "type": "短语", "keyWords": ["record"] },
    { "chinese": "a. 打破纪录的", "english": "record-breaking", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]（电）唱机", "english": "record-player", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使康复；使（身体）复原；重新获得；寻回 vi. 痊愈；恢复（原状）", "english": "recover", "type": "单词", "keyWords": [] },
    { "chinese": "康复", "english": "recover from one's illness", "type": "短语", "keyWords": ["recover"] },
    { "chinese": "康复", "english": "recover one's health", "type": "短语", "keyWords": ["recover"] },
    { "chinese": "苏醒过来", "english": "recover one's senses/ consciousness", "type": "短语", "keyWords": ["recover"] },
    { "chinese": "寻回遗失的钢笔", "english": "recover one's lost pen", "type": "短语", "keyWords": ["recover"] },
    { "chinese": "n. [U]（可加a）恢复；寻回", "english": "recovery", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 消遣；娱乐；游戏 vt. 使得到娱乐", "english": "recreate", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 娱乐 [C] 娱乐活动", "english": "recreation", "type": "单词", "keyWords": [] },
    { "chinese": "a. 娱乐的；消遣的", "english": "recreational", "type": "单词", "keyWords": [] },
    { "chinese": "游乐场", "english": "recreation ground", "type": "短语", "keyWords": ["recreation"] },
    { "chinese": "娱乐室", "english": "recreation room", "type": "短语", "keyWords": ["recreation"] },
    { "chinese": "v./n. [U] 回收利用；（使）再循环", "english": "recycle", "type": "单词", "keyWords": [] },
    { "chinese": "a. 红色的 n. [U] 红色", "english": "red", "type": "单词", "keyWords": [] },
    { "chinese": "气得满脸通红", "english": "go red with anger", "type": "短语", "keyWords": ["red"] },
    { "chinese": "负债；亏损", "english": "in the red", "type": "短语", "keyWords": ["red"] },
    { "chinese": "闯红灯", "english": "jump a light/ the lights", "type": "短语", "keyWords": ["red"] },
    { "chinese": "v. 减少；缩小；使变为；使沦为", "english": "reduce", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [U] 缩小，减少", "english": "reduction", "type": "单词", "keyWords": [] },
    { "chinese": "使某人/物陷入某种状况中", "english": "reduce sb./sth. (from sth.) to sth.", "type": "短语", "keyWords": ["reduce"] },
    { "chinese": "大萧条使许多人沦落到街头乞讨。", "english": "The Depression reduced many to being on street corners.", "type": "句子", "keyWords": ["reduce"] },
    { "chinese": "陷入绝望", "english": "be reduced to despair", "type": "短语", "keyWords": ["reduce"] },
    { "chinese": "v.（referred, referring）谈到；参考；有关 vt. 把……递交……", "english": "refer", "type": "单词", "keyWords": [] },
    { "chinese": "提到；说起；指（近speak of, mean）", "english": "refer to", "type": "短语", "keyWords": ["refer"] },
    { "chinese": "所谈到的问题", "english": "the question (which has been) referred to", "type": "短语", "keyWords": ["refer"] },
    { "chinese": "我不知道她指什么。", "english": "I had no idea what she referred to.", "type": "句子", "keyWords": ["refer"] },
    { "chinese": "参考；查阅（近turn to）", "english": "refer to", "type": "短语", "keyWords": ["refer"] },
    { "chinese": "他向我打听消息。", "english": "He referred to me for information.", "type": "句子", "keyWords": ["refer"] },
    { "chinese": "那个讲演的人不时地看发言稿。", "english": "The speaker often referred to his notes.", "type": "句子", "keyWords": ["refer"] },
    { "chinese": "有关；针对（apply to, be related, be relevant）", "english": "refer to", "type": "短语", "keyWords": ["refer"] },
    { "chinese": "我要说的话涉及你们大家。", "english": "What I have to say refers to all of you.", "type": "句子", "keyWords": ["refer"] },
    { "chinese": "提交给（某人或机构）处理", "english": "refer sb./sth. to sb...", "type": "短语", "keyWords": ["refer"] },
    { "chinese": "把问题提交给专家（处理）", "english": "refer a question to an expert", "type": "短语", "keyWords": ["refer"] },
    { "chinese": "把……称作……", "english": "refer to s.b. as...", "type": "短语", "keyWords": ["refer"] },
    { "chinese": "于是它被称为白矮星。", "english": "It is then referred to as a White Dwarf.", "type": "句子", "keyWords": ["refer"] },
    { "chinese": "这个，我称之为“发现”。", "english": 'This, I referred to as "discovery".', "type": "句子", "keyWords": ["refer"] },
    { "chinese": "n. [U] 参考；查阅；谈及 [C] 介绍信；参考书", "english": "reference", "type": "单词", "keyWords": [] },
    { "chinese": "仅供你们参考。", "english": "This is for your reference only.", "type": "句子", "keyWords": ["reference"] },
    { "chinese": "提到；说起", "english": "make reference to s.b.= refer to s.b.", "type": "短语", "keyWords": ["reference"] },
    { "chinese": "关于；就……而论（近as for）", "english": "in/with reference to", "type": "短语", "keyWords": ["reference"] },
    { "chinese": "n. [C]（足球等）裁判员；仲裁人，调解人", "english": "referee", "type": "单词", "keyWords": [] },
    { "chinese": "v. 反射；反映 vi.（很冷静、认真、反复地思考）深思", "english": "reflect", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 反射；反省 [C] 映象，倒影", "english": "reflection", "type": "单词", "keyWords": [] },
    { "chinese": "反思/深思（过去）", "english": "reflect upon/on (the past)", "type": "短语", "keyWords": ["reflect"] },
    { "chinese": "v./n. [C] [U] 改革", "english": "reform", "type": "单词", "keyWords": [] },
    { "chinese": "坚持改革开放", "english": "persevere in the reform and open policy", "type": "短语", "keyWords": ["reform"] },
    { "chinese": "我们应该推进资本市场的改革开放和稳定发展。", "english": "We should go ahead with the reform, opening up, stability and development of the capital market.", "type": "句子", "keyWords": ["reform"] },
    { "chinese": "vt. 使恢复活力；使振作精神", "english": "refresh", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 点心，精力恢复", "english": "refreshment", "type": "单词", "keyWords": [] },
    { "chinese": "喝杯茶提神", "english": "refresh oneself with a cup of tea", "type": "短语", "keyWords": ["refresh"] },
    { "chinese": "在湖中游了一会儿泳后约翰感到精神振奋。", "english": "John felt refreshed after a quick plunge in the lake.", "type": "句子", "keyWords": ["refresh"] },
    { "chinese": "使想起", "english": "refresh one's memory of/about", "type": "短语", "keyWords": ["refresh"] },
    { "chinese": "n. [C] 冰箱；冷库", "english": "refrigerator", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 难民，避难者；流亡者", "english": "refugee", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. [C] 退还；退（款）；偿还", "english": "refund", "type": "单词", "keyWords": [] },
    { "chinese": "（给我们）全额退款", "english": "refund (us) the money in full", "type": "短语", "keyWords": ["refund"] },
    { "chinese": "对不满意的货品要求退款", "english": "demand a refund on unsatisfactory goods", "type": "短语", "keyWords": ["refund"] },
    { "chinese": "vt. 拒绝；拒不", "english": "refuse", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [U] 拒绝", "english": "refusal", "type": "单词", "keyWords": [] },
    { "chinese": "拒绝给某人签证", "english": "refuse sb. a visa/ refuse to give sb. a visa", "type": "短语", "keyWords": ["refuse"] },
    { "chinese": "v. 看待；把……当作 n. [U] 尊敬，尊重（pl）问候；致意", "english": "regard", "type": "单词", "keyWords": [] },
    { "chinese": "把……当作……", "english": "regard...as...", "type": "短语", "keyWords": ["regard"] },
    { "chinese": "他被认为不成熟或不重要。", "english": "He was regarded as (being) immature or insignificant.", "type": "句子", "keyWords": ["regard"] },
    { "chinese": "向某人问好", "english": "send/give one's regards to sb.", "type": "短语", "keyWords": ["regard"] },
    { "chinese": "请向您父母转达我最诚挚的祝愿。", "english": "Please give your parents my warmest/best regards.", "type": "句子", "keyWords": ["regard"] },
    { "chinese": "关于；就……而论（近as for）", "english": "in/with regard to", "type": "短语", "keyWords": ["regard"] },
    { "chinese": "关于他的工作，我们没有什么可指责的。", "english": "Regarding his work, we have no complaints.", "type": "句子", "keyWords": ["regard"] },
    { "chinese": "在这点上，在这方面", "english": "in regard to= in this respect/aspect", "type": "短语", "keyWords": ["regard"] },
    { "chinese": "prep. 关于；就……而论（近as for）", "english": "regarding", "type": "单词", "keyWords": [] },
    { "chinese": "对于计算机，他是一窍不通。", "english": "Regarding computers, he is totally ignorant.", "type": "句子", "keyWords": ["regarding"] },
    { "chinese": "a. 不管；不顾；毫不顾及的", "english": "regardless", "type": "单词", "keyWords": [] },
    { "chinese": "不顾（个人得失）", "english": "regardless of (personal gain or loss)", "type": "短语", "keyWords": ["regardless"] },
    { "chinese": "n. [C] 地区；地带；（特定的）行政区", "english": "region", "type": "单词", "keyWords": [] },
    { "chinese": "a. 地区的", "english": "regional", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 注册，登记；名单 v. 注册；登记；挂号（邮件）", "english": "register", "type": "单词", "keyWords": [] },
    { "chinese": "就业人员花名册", "english": "an employment register", "type": "短语", "keyWords": ["register"] },
    { "chinese": "出生、结婚及死亡市政记录", "english": "a municipal register of birth, marriages, and deaths", "type": "短语", "keyWords": ["register"] },
    { "chinese": "挂号信", "english": "a registered letter", "type": "短语", "keyWords": ["register"] },
    { "chinese": "登记孩子的出生日期", "english": "register the birth of the child", "type": "短语", "keyWords": ["register"] },
    { "chinese": "n. [U] 遗憾；抱歉 [C] 遗憾事 v. 对……感到遗憾", "english": "regret", "type": "单词", "keyWords": [] },
    { "chinese": "使人遗憾的是……；真可惜……", "english": "It is to be regretted that...", "type": "短语", "keyWords": ["regret"] },
    { "chinese": "他竟然这么粗心，实在令人惋惜。", "english": "It is to be regretted that he should have made such a careless mistake.", "type": "句子", "keyWords": ["regret"] },
    { "chinese": "我很遗憾……；很抱歉……", "english": "I regret (to say) that...", "type": "短语", "keyWords": ["regret"] },
    { "chinese": "对做过某事感到遗憾", "english": "regret doing sth./ having done sth.", "type": "短语", "keyWords": ["regret"] },
    { "chinese": "这句话刚说出口我就后悔了。", "english": "No sooner had the word come out than I regretted saying it.", "type": "句子", "keyWords": ["regret"] },
    { "chinese": "他死了，大家深感痛惜。", "english": "He died regretted by all.", "type": "句子", "keyWords": ["regret"] },
    { "chinese": "a. 惋惜的，遗憾的（for sth）", "english": "regretful", "type": "单词", "keyWords": [] },
    { "chinese": "a. 常规的；固定的；定时的；有规律的；匀称的", "english": "regular", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 规律性，规则性；整齐，匀称", "english": "regularity", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 规则；规章；规定；管理；调整", "english": "regulation", "type": "单词", "keyWords": [] },
    { "chinese": "遵守校规/交规", "english": "meet/ observe the school/ traffic regulations", "type": "短语", "keyWords": ["regulation"] },
    { "chinese": "法令", "english": "laws and regulations", "type": "短语", "keyWords": ["regulation"] },
    { "chinese": "vt. 拒绝（相信、考虑、接受、录取等）；摒弃（近turn down，辨析见decline）", "english": "reject", "type": "单词", "keyWords": [] },
    { "chinese": "拒做某事（近refuse to do sth.）", "english": "reject doing sth.", "type": "短语", "keyWords": ["reject"] },
    { "chinese": "丹麦人在2000年拒绝采用欧元。", "english": "Danes rejected adopting the euro currency in 2000.", "type": "句子", "keyWords": ["reject"] },
    { "chinese": "vt. 讲述，讲；使互有关联 vi. 有关联", "english": "relate", "type": "单词", "keyWords": [] },
    { "chinese": "探险者叙述其冒险经历。", "english": "The explorer related his adventures.", "type": "句子", "keyWords": ["relate"] },
    { "chinese": "使互有关联", "english": "relate...to (with)...", "type": "短语", "keyWords": ["relate"] },
    { "chinese": "我没法把他做的和说的联系起来。", "english": "I can't relate what he does with/ to what he says.", "type": "句子", "keyWords": ["relate"] }
];
