const qgl226_240 = [
    { "chinese": "a. 有关的；相关的；有亲戚关系的", "english": "related", "type": "单词", "keyWords": [] },
    { "chinese": "与……有关；有亲戚关系（主要用被动）", "english": "be related to...", "type": "短语", "keyWords": ["related"] },
    { "chinese": "这两个事件相互有密切联系。", "english": "These two events were closely related to each other.", "type": "句子", "keyWords": ["related"] },
    { "chinese": "他们彼此之间有亲戚关系。", "english": "They are related to each other.", "type": "句子", "keyWords": ["related"] },
    { "chinese": "n. [U]（可加a）（逻辑或自然的）联系或关联 [C] 亲戚（pl）国/人之间的交往；叙述", "english": "relation", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 关系；联系；亲戚关系", "english": "relationship", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 亲属；亲戚 a. 相对的；相关的（to）", "english": "relative", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 相对而言", "english": "relatively", "type": "单词", "keyWords": [] },
    { "chinese": "相对稳定时期", "english": "the period of relative stability", "type": "短语", "keyWords": ["relative"] },
    { "chinese": "所有与正在讨论的事情有关的细节", "english": "all the details relative to the discussion", "type": "短语", "keyWords": ["relative"] },
    { "chinese": "相对较小问题", "english": "a relatively minor problem", "type": "短语", "keyWords": ["relatively"] },
    { "chinese": "相对来说，富的愈来愈富，穷的愈来愈穷。", "english": "Relatively speaking, the rich are getting richer and the poor poorer.", "type": "句子", "keyWords": ["relatively"] },
    { "chinese": "n. [C] 相对性；相关性；[物] 相对论", "english": "relativity", "type": "单词", "keyWords": [] },
    { "chinese": "广义/狭义相对论", "english": "the general/special theory of relativity", "type": "短语", "keyWords": ["relativity"] },
    { "chinese": "(使)放松；(使)松弛；(使)休息", "english": "relax", "type": "单词", "keyWords": [] },
    { "chinese": "a. 使人/感到放松的", "english": "relaxing/relaxed", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 放松，松弛 [C] 消遣；娱乐", "english": "relaxation", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 接力赛 v. 转播", "english": "relay", "type": "单词", "keyWords": [] },
    { "chinese": "接力赛", "english": "a relay race", "type": "短语", "keyWords": ["relay"] },
    { "chinese": "vt./n. [U] 放生；松开；释放；发泄；发布（新闻）；发行（电影）", "english": "release", "type": "单词", "keyWords": [] },
    { "chinese": "释放囚犯/放走气球", "english": "release the prisoners/ the balloons", "type": "短语", "keyWords": ["release"] },
    { "chinese": "新发行的电影", "english": "a recently released film", "type": "短语", "keyWords": ["release"] },
    { "chinese": "如何进行新闻发布？", "english": "How should I do a press release?", "type": "句子", "keyWords": ["release"] },
    { "chinese": "a.（常与to连用）有关的；切题的", "english": "relevant", "type": "单词", "keyWords": [] },
    { "chinese": "有关的细节（反irrelevant details无关的细节）", "english": "relevant details", "type": "短语", "keyWords": ["relevant"] },
    { "chinese": "所有与这个事故有关的事实都要包括在内。", "english": "All of the facts relevant to the accident are to be included.", "type": "句子", "keyWords": ["relevant"] },
    { "chinese": "a. 可靠的", "english": "reliable", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 可靠性", "english": "reliability", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 减轻；解除；救济，补助；感到宽慰的情况", "english": "relief", "type": "单词", "keyWords": [] },
    { "chinese": "宽慰地叹了一口气", "english": "sigh with relief", "type": "短语", "keyWords": ["relief"] },
    { "chinese": "令某人感到宽慰的是", "english": "to one's relief", "type": "短语", "keyWords": ["relief"] },
    { "chinese": "他发出如释重负的轻叹。", "english": "He breathed a sigh of relief.", "type": "句子", "keyWords": ["relief"] },
    { "chinese": "靠救济生活", "english": "survive on relief", "type": "短语", "keyWords": ["relief"] },
    { "chinese": "这真让人感到松了口气。", "english": "It's a great relief.", "type": "句子", "keyWords": ["relief"] },
    { "chinese": "vt. 减轻；解除；救济；使松口气；使感到宽慰", "english": "relieve", "type": "单词", "keyWords": [] },
    { "chinese": "减轻（负担等）；解除（有时表示“使失掉”）", "english": "relieve sb. of sth.", "type": "短语", "keyWords": ["relieve"] },
    { "chinese": "你来了，省去我要写封长信的麻烦了。", "english": "Your coming relieved me of the bother of writing a long letter.", "type": "句子", "keyWords": ["relieve"] },
    { "chinese": "扒手偷了他的钱。", "english": "Pickpockets relieved him of his money.", "type": "句子", "keyWords": ["relieve"] },
    { "chinese": "不久他被免职了。", "english": "He was soon relieved of his post.", "type": "句子", "keyWords": ["relieve"] },
    { "chinese": "n. [C] 宗教 [U] 宗教信仰", "english": "religion", "type": "单词", "keyWords": [] },
    { "chinese": "a. 宗教的；虔诚的", "english": "religious", "type": "单词", "keyWords": [] },
    { "chinese": "宗教习俗", "english": "religious practices", "type": "短语", "keyWords": ["religious"] },
    { "chinese": "a. 不情愿的；勉强的", "english": "reluctant", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 不情愿地", "english": "reluctantly", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 不情愿", "english": "reluctance", "type": "单词", "keyWords": [] },
    { "chinese": "不愿做某事", "english": "be reluctant to do sth.", "type": "短语", "keyWords": ["reluctant"] },
    { "chinese": "vi. 依靠，依赖（on/upon）", "english": "rely", "type": "单词", "keyWords": [] },
    { "chinese": "指望；信赖（近calculate/depend/count on, look to）", "english": "rely on/upon", "type": "短语", "keyWords": ["rely"] },
    { "chinese": "我相信到期时可以收回我的钱。", "english": "I rely on getting my money back in due time.", "type": "句子", "keyWords": ["rely"] },
    { "chinese": "您的订单我们将立即处理，请放心。", "english": "You can rely on us to give your order immediate attention.", "type": "句子", "keyWords": ["rely"] },
    { "chinese": "vi. 留下；仍然是；保持不变；剩余；尚待（后接to do）", "english": "remain", "type": "单词", "keyWords": [] },
    { "chinese": "仍然活着/是朋友/未完成", "english": "remain alive/friends/unfinished", "type": "短语", "keyWords": ["remain"] },
    { "chinese": "有待解决/评定/证明", "english": "remain to be solved/seen/proved", "type": "短语", "keyWords": ["remain"] },
    { "chinese": "原来建筑物的残迹遗留下来的很少。", "english": "Very little remained of the original building.", "type": "句子", "keyWords": ["remain"] },
    { "chinese": "处理遗留问题（remaining作前置定语，left作后置定语）", "english": "settle the remaining problems = settle the problems left", "type": "短语", "keyWords": ["remain"] },
    { "chinese": "剩余部分，其余的人（the rest）；余数", "english": "the remainder", "type": "短语", "keyWords": ["remain"] },
    { "chinese": "残余，遗迹，遗体", "english": "remains", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 谈起，评论（on/upon） vt. 说 n. [C] 评论，话语", "english": "remark", "type": "单词", "keyWords": [] },
    { "chinese": "评述", "english": "remark (up)on", "type": "短语", "keyWords": ["remark"] },
    { "chinese": "a. 显著的；非凡的；引人注目的；卓越的", "english": "remarkable", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 药物；治疗法；补救办法（for）", "english": "remedy", "type": "单词", "keyWords": [] },
    { "chinese": "v. 记得；记住", "english": "remember", "type": "单词", "keyWords": [] },
    { "chinese": "我自问没有什么对不起他的地方。", "english": "I don't remember ever doing him wrong.", "type": "句子", "keyWords": ["remember"] },
    { "chinese": "别忘了给我打电话。", "english": "Remember to phone me.", "type": "句子", "keyWords": ["remember"] },
    { "chinese": "代我向你的家人问好。", "english": "Remember me to your family.", "type": "句子", "keyWords": ["remember"] },
    { "chinese": "她现在多苗条啊！我记得她那时可比现在胖。", "english": "How thin she is! I remember her as fatter than that.", "type": "句子", "keyWords": ["remember"] },
    { "chinese": "vt. 提醒；使想起", "english": "remind", "type": "单词", "keyWords": [] },
    { "chinese": "使想起；提醒某人某事", "english": "remind sb. of sth. (=remind sb. that...)", "type": "短语", "keyWords": ["remind"] },
    { "chinese": "提醒某人做某事", "english": "remind sb. to do sth.", "type": "短语", "keyWords": ["remind"] },
    { "chinese": "n. [C] 起提醒作用的事物；提醒者", "english": "reminder", "type": "单词", "keyWords": [] },
    { "chinese": "a. 遥远的；偏僻的；时间上久远的（近faraway）", "english": "remote", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 拿开；除去；去掉（from）", "english": "remove", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [U] 移开，除去", "english": "removal", "type": "单词", "keyWords": [] },
    { "chinese": "v. 重新开始；更新；续借（书）", "english": "renew", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [U] 更新，重新开始", "english": "renewal", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 租金 v. 租借；出租（房、土地）；租或出租（车辆等）", "english": "rent", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. [U] 修补；（常pl）修理；修理/补工作", "english": "repair", "type": "单词", "keyWords": [] },
    { "chinese": "在维修中", "english": "under repair", "type": "短语", "keyWords": ["repair"] },
    { "chinese": "v./n. [U] 修补；（常pl）修理；修理/补工作", "english": "repair", "type": "单词", "keyWords": [] },
    { "chinese": "在维修中", "english": "under repair", "type": "短语", "keyWords": ["repair"] },
    { "chinese": "维修良好/失修", "english": "in good/bad repair", "type": "短语", "keyWords": ["repair"] },
    { "chinese": "无法修理", "english": "beyond repair", "type": "短语", "keyWords": ["repair"] },
    { "chinese": "修补；修理", "english": "make repairs", "type": "短语", "keyWords": ["repair"] },
    { "chinese": "v. 重复；复述；重演；重读", "english": "repeat", "type": "单词", "keyWords": [] },
    { "chinese": "a. 重复的，再三的；屡次的", "english": "repeated", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] [U] 重复", "english": "repetition", "type": "单词", "keyWords": [] },
    { "chinese": "历史不会重演。", "english": "History will not repeat itself.", "type": "句子", "keyWords": ["repeat"] },
    { "chinese": "ad. 重复多次地", "english": "repeatedly", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 取代（=take the place of）；放回原处", "english": "replace", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 取代", "english": "replacement", "type": "单词", "keyWords": [] },
    { "chinese": "用B来代替A", "english": "replace A with/by B", "type": "短语", "keyWords": ["replace"] },
    { "chinese": "n. [C] 代替者", "english": "replacement", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. [C] 回答；答复；作出反应", "english": "reply", "type": "单词", "keyWords": [] },
    { "chinese": "回答；答复；对……作出反应", "english": "reply to", "type": "短语", "keyWords": ["reply"] },
    { "chinese": "她安静地走出房间，以此作为对他们气冲冲提问的回答。", "english": "She replied to their angry question by calmly walking out of the room.", "type": "句子", "keyWords": ["reply"] },
    { "chinese": "为响应；答复", "english": "in reply/answer/response to", "type": "短语", "keyWords": ["reply"] },
    { "chinese": "我提出与他较量，他作何反应？", "english": "What did he do in reply to my challenge?", "type": "句子", "keyWords": ["reply"] },
    { "chinese": "v. 报告，汇报；报道；告发 n. [C] 报告；成绩单；报道", "english": "report", "type": "单词", "keyWords": [] },
    { "chinese": "向某人报告；叙述", "english": "report (on) sth. to sb.", "type": "短语", "keyWords": ["report"] },
    { "chinese": "汤姆汇报说看见过偷窃行为。", "english": "Tom reported having seen the theft.", "type": "句子", "keyWords": ["report"] },
    { "chinese": "向校长告发了他们", "english": "report them to the principal", "type": "短语", "keyWords": ["report"] },
    { "chinese": "据说……，据传……", "english": "It is reported that...", "type": "短语", "keyWords": ["report"] },
    { "chinese": "报道说……", "english": "The report goes that...", "type": "短语", "keyWords": ["report"] },
    { "chinese": "n. [C] 记者", "english": "reporter", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 代表；（符号）表示（近stand for）", "english": "represent", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 代表；代理人 a. 代表（性）的", "english": "representative", "type": "单词", "keyWords": [] },
    { "chinese": "（美国及日本的）众议院", "english": "the House of Representatives", "type": "短语", "keyWords": ["representative"] },
    { "chinese": "代表人民", "english": "be representative of the people", "type": "短语", "keyWords": ["representative"] },
    { "chinese": "n. [C] 共和国", "english": "republic", "type": "单词", "keyWords": [] },
    { "chinese": "中华人民共和国", "english": "the People's Republic of China", "type": "短语", "keyWords": ["republic"] },
    { "chinese": "n. [C] 声誉；名气", "english": "reputation", "type": "单词", "keyWords": [] },
    { "chinese": "享有盛誉", "english": "enjoy a high reputation", "type": "短语", "keyWords": ["reputation"] },
    { "chinese": "名实相符", "english": "live up to one's reputation", "type": "短语", "keyWords": ["reputation"] },
    { "chinese": "名声好/坏", "english": "have a good/bad reputation", "type": "短语", "keyWords": ["reputation"] },
    { "chinese": "n. [C]/v. 请求（比ask正式，比demand客气）", "english": "request", "type": "单词", "keyWords": [] },
    { "chinese": "请求某人……", "english": "request sth. of sb.", "type": "短语", "keyWords": ["request"] },
    { "chinese": "我对你的唯一请求是你要准时。", "english": "All I request of you is that you should be punctual.", "type": "句子", "keyWords": ["request"] },
    { "chinese": "请求某人做……", "english": "request sb. to do sth.", "type": "短语", "keyWords": ["request"] },
    { "chinese": "根据某人的请求", "english": "do sth. at the request of sb.", "type": "短语", "keyWords": ["request"] },
    { "chinese": "v. 要求；需求", "english": "require", "type": "单词", "keyWords": [] },
    { "chinese": "要求某人做……", "english": "require sb. to do sth.", "type": "短语", "keyWords": ["require"] },
    { "chinese": "需要被……", "english": "require doing/ to be done", "type": "短语", "keyWords": ["require"] },
    { "chinese": "要求某人某事", "english": "require sth. of sb.", "type": "短语", "keyWords": ["require"] },
    { "chinese": "n. [C] 规定；要求；必需品；需要", "english": "requirement", "type": "单词", "keyWords": [] },
    { "chinese": "满足某人的要求", "english": "meet/satisfy/fulfil one's requirements", "type": "短语", "keyWords": ["requirement"] },
    { "chinese": "vt./n. [C] [U] 营救；救援；搭救", "english": "rescue", "type": "单词", "keyWords": [] },
    { "chinese": "营救某人", "english": "come/go to one's rescue", "type": "短语", "keyWords": ["rescue"] },
    { "chinese": "n. [U] 研究；调查；探索（into/on）", "english": "research", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 研究；调查；探索（into/on）", "english": "research", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 一项研究", "english": "research", "type": "单词", "keyWords": [] },
    { "chinese": "研究；探索", "english": "research into/on sth. (vi.) = research sth. (vt.)", "type": "单词", "keyWords": ["research"] },
    { "chinese": "对…做调查/研究", "english": "carry out/do/make/conduct some research into/on sth.", "type": "短语", "keyWords": ["research"] },
    { "chinese": "n. 研究人员", "english": "researcher", "type": "单词", "keyWords": [] },
    { "chinese": "v. 与…相似，像", "english": "resemble", "type": "单词", "keyWords": [] },
    { "chinese": "n. 相似处", "english": "resemblance", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 保留；储备；预订 n. 储备；自然保护区", "english": "reserve", "type": "单词", "keyWords": [] },
    { "chinese": "所有名字与标志是其拥有者的财产，将保留一切权利。", "english": "All names and logos are the property of their respective owners and all rights are reserved.", "type": "句子", "keyWords": ["reserve"] },
    { "chinese": "这些座位是为特别的来宾保留的。", "english": "These seats are reserved for special guests.", "type": "句子", "keyWords": ["reserve"] },
    { "chinese": "他们已预订了旅馆房间。", "english": "They have reserved rooms at a hotel.", "type": "句子", "keyWords": ["reserve"] },
    { "chinese": "预定的座位", "english": "reserved seats", "type": "短语", "keyWords": ["reserve"] },
    { "chinese": "探明储量", "english": "proved reserves", "type": "短语", "keyWords": ["reserve"] },
    { "chinese": "自然保护区", "english": "a nature reserve", "type": "短语", "keyWords": ["reserve"] },
    { "chinese": "n. 保留意见；预订", "english": "reservation", "type": "单词", "keyWords": [] },
    { "chinese": "你跟餐馆订好两桌酒席了吗？", "english": "Did you make reservations for two tables at the restaurant?", "type": "句子", "keyWords": ["reservation"] },
    { "chinese": "n. 水库", "english": "reservoir", "type": "单词", "keyWords": [] },
    { "chinese": "n. 居住；住处", "english": "residence", "type": "单词", "keyWords": [] },
    { "chinese": "n. 居民", "english": "resident", "type": "单词", "keyWords": [] },
    { "chinese": "a. 居民的；居住的；住所的", "english": "residential", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 居住，定居", "english": "reside", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 辞职 vt. 放弃；辞去", "english": "resign", "type": "单词", "keyWords": [] },
    { "chinese": "辞职", "english": "resign (from) his post", "type": "短语", "keyWords": ["resign"] },
    { "chinese": "放弃董事职务", "english": "resign his directorship", "type": "短语", "keyWords": ["resign"] },
    { "chinese": "n. 辞职；辞职书", "english": "resignation", "type": "单词", "keyWords": [] },
    { "chinese": "v. 抵抗；忍住，按捺；抗，耐 vi. 抵抗", "english": "resist", "type": "单词", "keyWords": [] },
    { "chinese": "抑制（做）某事", "english": "resist (doing) sth.", "type": "短语", "keyWords": ["resist"] },
    { "chinese": "真玉摸起来有凉的感觉并且不怕金属刮划。", "english": "Jade is always cool to touch and will resist scratching with metal.", "type": "句子", "keyWords": ["resist"] },
    { "chinese": "我无法抵制糖的诱惑。", "english": "I couldn't resist the temptation to eat sweets.", "type": "句子", "keyWords": ["resist"] },
    { "chinese": "a. 抵抗的，耐…的", "english": "resistant", "type": "单词", "keyWords": [] },
    { "chinese": "n. 抵抗", "english": "resistance", "type": "单词", "keyWords": [] },
    { "chinese": "反对变革/耐化学品的", "english": "be resistant to change/chemicals", "type": "短语", "keyWords": ["resistant"] },
    { "chinese": "n. 决心；决议；坚决；解决", "english": "resolution", "type": "单词", "keyWords": [] },
    { "chinese": "v. 决定，决意；解决；分解", "english": "resolve", "type": "单词", "keyWords": [] },
    { "chinese": "解决冲突", "english": "resolve a conflict", "type": "短语", "keyWords": ["resolve"] },
    { "chinese": "她决定早早出发。", "english": "She resolved on making an early start.", "type": "句子", "keyWords": ["resolve"] },
    { "chinese": "水可以分解成氧和氢。", "english": "Water may be resolved into oxygen and hydrogen.", "type": "句子", "keyWords": ["resolve"] },
    { "chinese": "n. 常去的热闹地方；胜地 vi. 凭借，采用", "english": "resort", "type": "单词", "keyWords": [] },
    { "chinese": "假日游乐场", "english": "a holiday resort", "type": "短语", "keyWords": ["resort"] },
    { "chinese": "避暑/避寒胜地", "english": "a summer/winter resort", "type": "短语", "keyWords": ["resort"] },
    { "chinese": "使用（武力），诉诸（武力）", "english": "resort to (armed force)", "type": "短语", "keyWords": ["resort"] },
    { "chinese": "不使用（武力）", "english": "without resorting to (force)", "type": "短语", "keyWords": ["resort"] },
    { "chinese": "n. 资源", "english": "resource", "type": "单词", "keyWords": [] },
    { "chinese": "自然资源", "english": "natural resources", "type": "短语", "keyWords": ["resource"] },
    { "chinese": "n. 尊重；重视；关系；方面；敬意 v. 尊重", "english": "respect", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可敬的", "english": "respected", "type": "单词", "keyWords": [] },
    { "chinese": "a. 尊重人的，有礼貌的", "english": "respectful", "type": "单词", "keyWords": [] },
    { "chinese": "a. 分别的，各自的", "english": "respective", "type": "单词", "keyWords": [] },
    { "chinese": "a. 值得尊敬的；体面的", "english": "respectable", "type": "单词", "keyWords": [] },
    { "chinese": "可敬的老师", "english": "a respectable teacher", "type": "短语", "keyWords": ["respectable"] },
    { "chinese": "尊重", "english": "have/show respect for (=be respectful to/towards)", "type": "短语", "keyWords": ["respect"] },
    { "chinese": "问候", "english": "send one's respects to", "type": "短语", "keyWords": ["respect"] },
    { "chinese": "我觉得你各方面都错了。", "english": "I think you are wrong in every respect.", "type": "句子", "keyWords": ["respect"] },
    { "chinese": "关于；就…而论", "english": "in respect of sth. = with respect to sth.", "type": "短语", "keyWords": ["respect"] },
    { "chinese": "涉及/关于某事物", "english": "with respect to sth.", "type": "短语", "keyWords": ["respect"] },
    { "chinese": "尊敬的主席先生", "english": "respected Mr. Chairman", "type": "短语", "keyWords": ["respected"] },
    { "chinese": "各人有各人的职责。", "english": "All men have their respective duties.", "type": "句子", "keyWords": ["respective"] },
    { "chinese": "v. 回答；答复；作出反应；响应", "english": "respond", "type": "单词", "keyWords": [] },
    { "chinese": "回答；对…作出反应", "english": "respond/reply to sb./sth.", "type": "短语", "keyWords": ["respond"] },
    { "chinese": "n. 回答；答复；反应；响应", "english": "response", "type": "单词", "keyWords": [] },
    { "chinese": "应号召", "english": "in response/answer/reply to a call", "type": "短语", "keyWords": ["response"] },
    { "chinese": "他没回答。", "english": "He said nothing in response. = He made no response.", "type": "句子", "keyWords": ["response"] },
    { "chinese": "他们很快答复了我的询问。", "english": "They make a quick response to my inquiry.", "type": "句子", "keyWords": ["response"] },
    { "chinese": "n. 责任", "english": "responsibility", "type": "单词", "keyWords": [] },
    { "chinese": "对…（全）负责", "english": "take/shoulder/bear (full) responsibility for", "type": "短语", "keyWords": ["responsibility"] },
    { "chinese": "a. 负责任的；有责任感的，可靠的", "english": "responsible", "type": "单词", "keyWords": [] },
    { "chinese": "对…负责；是…的原因", "english": "be responsible for", "type": "短语", "keyWords": ["responsible"] },
    { "chinese": "这损失是暴风雨造成的。", "english": "The storm was responsible for the damage.", "type": "句子", "keyWords": ["responsible"] },
    { "chinese": "v./vi. （使）休息；停留；依靠 n. 休息；睡眠；其余", "english": "rest", "type": "单词", "keyWords": [] },
    { "chinese": "a. 焦躁不安的；得不到休息的；不平静的", "english": "restless", "type": "单词", "keyWords": [] },
    { "chinese": "（被）支撑，（使）倚靠", "english": "rest (sth) on/against sth.", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "他的目光落在一个奇怪的物体上。", "english": "His gaze rested on a strange object.", "type": "句子", "keyWords": ["rest"] },
    { "chinese": "机器安装在宽钢板底座上。", "english": "The machine rests on a wide base of steel.", "type": "句子", "keyWords": ["rest"] },
    { "chinese": "她朝我看并微笑。", "english": "She rested her eyes on me and smiled.", "type": "句子", "keyWords": ["rest"] },
    { "chinese": "在休息中；静止，不动；处于安宁状态；安息", "english": "at rest", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "在有生之年", "english": "for the rest of one's life", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "其他时间", "english": "The rest of the time is...", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "我们其他人", "english": "The rest of us are...", "type": "短语", "keyWords": ["rest"] },
    { "chinese": "度过了一个不眠之夜", "english": "spend a restless night", "type": "短语", "keyWords": ["restless"] },
    { "chinese": "n. 餐馆，饭店", "english": "restaurant", "type": "单词", "keyWords": [] },
    { "chinese": "v. 恢复；使恢复健康；修复", "english": "restore", "type": "单词", "keyWords": [] },
    { "chinese": "n. 恢复", "english": "restoration", "type": "单词", "keyWords": [] },
    { "chinese": "使某人苏醒过来", "english": "restore sb. to life", "type": "短语", "keyWords": ["restore"] },
    { "chinese": "使某人复职", "english": "restore sb. to his old post", "type": "短语", "keyWords": ["restore"] },
    { "chinese": "使某人恢复知觉", "english": "restore sb. to consciousness", "type": "短语", "keyWords": ["restore"] },
    { "chinese": "把书放回书架", "english": "restore the book to the shelf", "type": "短语", "keyWords": ["restore"] },
    { "chinese": "v. 限制，约束", "english": "restrict", "type": "单词", "keyWords": [] },
    { "chinese": "n. 限制", "english": "restriction", "type": "单词", "keyWords": [] },
    { "chinese": "这些文件仍仅限公务员使用。", "english": "Access to the documents remains restricted to civil servants only.", "type": "句子", "keyWords": ["restrict"] },
    { "chinese": "a. 严格的，受严控的", "english": "restricted", "type": "单词", "keyWords": [] },
    { "chinese": "禁区", "english": "a restricted area", "type": "短语", "keyWords": ["restricted"] },
    { "chinese": "a. 限制性的", "english": "restrictive", "type": "单词", "keyWords": [] },
    { "chinese": "工业方面的限制性措施", "english": "restrictive practices in industry", "type": "短语", "keyWords": ["restrictive"] },
    { "chinese": "n. 结果；成果；成绩 vi. 作为结果发生；产生", "english": "result", "type": "单词", "keyWords": [] },
    { "chinese": "作为结果，因此", "english": "as a result", "type": "短语", "keyWords": ["result"] },
    { "chinese": "由…导致", "english": "result from", "type": "短语", "keyWords": ["result"] },
    { "chinese": "由于", "english": "as a result of", "type": "短语", "keyWords": ["result"] },
    { "chinese": "导致", "english": "result in", "type": "短语", "keyWords": ["result"] },
    { "chinese": "n. 摘要，概略；[美]（求职者等的）简历，履历", "english": "resume", "type": "单词", "keyWords": [] },
    { "chinese": "v. （使）退休/职；退隐", "english": "retire", "type": "单词", "keyWords": [] },
    { "chinese": "n. 退休；退隐", "english": "retirement", "type": "单词", "keyWords": [] },
    { "chinese": "离群索居；退隐；隐居", "english": "retire from the world", "type": "短语", "keyWords": ["retire"] },
    { "chinese": "一个退休工人", "english": "a retired worker", "type": "短语", "keyWords": ["retired"] },
    { "chinese": "v. 返回；归还；回答 n. 返回；归还；回访；报答", "english": "return", "type": "单词", "keyWords": [] },
    { "chinese": "作为…的交换；作为…的回报", "english": "in return (for)", "type": "短语", "keyWords": ["return"] },
    { "chinese": "他回送了她一些玫瑰（以答谢她的好意）。", "english": "He gave her some roses in return (for her kindness).", "type": "句子", "keyWords": ["return"] },
    { "chinese": "他刚从乡下回来就认真工作起来。", "english": "On his return from the countryside, he set to work in earnest.", "type": "句子", "keyWords": ["return"] },
    { "chinese": "福寿无疆！长命百岁！", "english": "Many happy returns (of the day)!", "type": "句子", "keyWords": ["return"] },
    { "chinese": "v. 重新统一；（使）重新结合/联合；（使）重聚", "english": "reunite", "type": "单词", "keyWords": [] },
    { "chinese": "n. 聚会；团聚", "english": "reunion", "type": "单词", "keyWords": [] },
    { "chinese": "v. 揭示，揭露；泄露；暴露；展现", "english": "reveal", "type": "单词", "keyWords": [] },
    { "chinese": "揭示身份", "english": "reveal one's identity", "type": "短语", "keyWords": ["reveal"] },
    { "chinese": "他们向我透露实验失败了。", "english": "They revealed to me that the experiment had failed.", "type": "句子", "keyWords": ["reveal"] },
    { "chinese": "他切开长筒靴后发现被藏的珠宝。", "english": "His cut in the boot revealed the hidden jewels.", "type": "句子", "keyWords": ["reveal"] },
    { "chinese": "vi./n. 报仇，复仇 v. 替…报仇；报…之仇", "english": "revenge", "type": "单词", "keyWords": [] },
    { "chinese": "因某事报复某人", "english": "get/have/take one's revenge on sb. for sth.", "type": "短语", "keyWords": ["revenge"] },
    { "chinese": "（为…）报复性地/出于报复做某事", "english": "do sth. out of revenge/in revenge (for sth.)", "type": "短语", "keyWords": ["revenge"] },
    { "chinese": "哈姆雷特向凶手报了杀父之仇。", "english": "Hamlet revenged his dead father (on the murderer).", "type": "句子", "keyWords": ["revenge"] },
    { "chinese": "对不正义采取报复", "english": "revenge an injustice", "type": "短语", "keyWords": ["revenge"] },
    { "chinese": "a. 逆向的；倒退的；颠倒的 n. 相反情况；反面；背面；逆转；挫折 v. 颠倒；（使）倒退", "english": "reverse", "type": "单词", "keyWords": [] },
    { "chinese": "次序颠倒地", "english": "in reverse order", "type": "短语", "keyWords": ["reverse"] },
    { "chinese": "做违背别人期望的事", "english": "do the reverse of what one is expected to do", "type": "短语", "keyWords": ["reverse"] },
    { "chinese": "硬币的反面压印的是一只鹰。", "english": "The reverse of the coin is stamped with an eagle.", "type": "句子", "keyWords": ["reverse"] },
    { "chinese": "遭受财政困难", "english": "suffer financial reverses", "type": "短语", "keyWords": ["reverse"] },
    { "chinese": "把车倒进", "english": "reverse one's car (into...)", "type": "短语", "keyWords": ["reverse"] },
    { "chinese": "v./n. 复习；审核；回顾；检阅；评论", "english": "review", "type": "单词", "keyWords": [] },
    { "chinese": "观察形势", "english": "review the situation", "type": "短语", "keyWords": ["review"] },
    { "chinese": "回顾过去", "english": "review the past", "type": "短语", "keyWords": ["review"] },
    { "chinese": "检阅仪仗队", "english": "review the guard of honour", "type": "短语", "keyWords": ["review"] },
    { "chinese": "给一本新出版的小说写书评", "english": "review a new novel", "type": "短语", "keyWords": ["review"] },
    { "chinese": "v. 复习；修订；校订；修正", "english": "revise", "type": "单词", "keyWords": [] },
    { "chinese": "我已重新考虑了对他的意见。", "english": "I have revised my opinion of him.", "type": "句子", "keyWords": ["revise"] },
    { "chinese": "n. 复习，修正；修订稿/本", "english": "revision", "type": "单词", "keyWords": [] },
    { "chinese": "经过四次修订", "english": "after four revisions", "type": "短语", "keyWords": ["revision"] },
    { "chinese": "n. 革命；大变革；旋转；绕转", "english": "revolution", "type": "单词", "keyWords": [] },
    { "chinese": "v. 发动革命", "english": "revolutionize", "type": "单词", "keyWords": [] },
    { "chinese": "美国独立战争", "english": "American Revolution (1775-1783)", "type": "短语", "keyWords": ["revolution"] },
    { "chinese": "在现代物理学领域中实现大变革", "english": "bring about a revolution in modern physics", "type": "短语", "keyWords": ["revolution"] },
    { "chinese": "a. 革命的；旋转的；绕转的 n. 革命者", "english": "revolutionary", "type": "单词", "keyWords": [] },
    { "chinese": "vt./n. 报答；奖赏", "english": "reward", "type": "单词", "keyWords": [] },
    { "chinese": "(因…)而(用…)来酬谢某人", "english": "reward sb. (with sth.) (for sth.)", "type": "短语", "keyWords": ["reward"] },
    { "chinese": "(因某事)没获得任何报酬", "english": "get nothing in reward (for sth.)", "type": "短语", "keyWords": ["reward"] },
    { "chinese": "a. 值得的；有益的；有回报的", "english": "rewarding", "type": "单词", "keyWords": [] },
    { "chinese": "有利可图的商业冒险", "english": "a rewarding business venture", "type": "短语", "keyWords": ["rewarding"] },
    { "chinese": "v. 重写；改写", "english": "rewrite", "type": "单词", "keyWords": [] },
    { "chinese": "n. 节奏，韵律", "english": "rhythm", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有节奏的", "english": "rhythmic", "type": "单词", "keyWords": [] },
    { "chinese": "n. 肋骨", "english": "rib", "type": "单词", "keyWords": [] },
    { "chinese": "n. 稻；米饭", "english": "rice", "type": "单词", "keyWords": [] },
    { "chinese": "a. （丰）富的；富饶的，盛产的；肥沃的；充足的", "english": "rich", "type": "单词", "keyWords": [] },
    { "chinese": "n. 富有", "english": "richness", "type": "单词", "keyWords": [] },
    { "chinese": "在…方面很丰富", "english": "be rich in (oil, fat...)", "type": "短语", "keyWords": ["rich"] },
    { "chinese": "v. 摆脱", "english": "rid", "type": "单词", "keyWords": [] },
    { "chinese": "摆脱；除去", "english": "get/be rid of (him/the pain/the toothache)", "type": "短语", "keyWords": ["rid"] },
    { "chinese": "v./n. 骑；骑马；乘车旅行", "english": "ride", "type": "单词", "keyWords": [] },
    { "chinese": "骑自行车", "english": "ride (on) a bicycle", "type": "短语", "keyWords": ["ride"] },
    { "chinese": "乘车", "english": "ride on a bus", "type": "短语", "keyWords": ["ride"] },
    { "chinese": "n. 骑马（或其他牲口、自行车）者；滑水/冲浪运动员", "english": "rider", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可笑的；荒谬的", "english": "ridiculous", "type": "单词", "keyWords": [] },
    { "chinese": "n. 嘲笑", "english": "ridicule", "type": "单词", "keyWords": [] },
    { "chinese": "n. 来复枪；步枪", "english": "rifle", "type": "单词", "keyWords": [] },
    { "chinese": "a. 正确的；右边的；合适的；正当的；健康的 ad. 就，恰好；正确；直接，完全；向上；往右 n. 右边，右面；正确；权利", "english": "right", "type": "单词", "keyWords": [] },
    { "chinese": "修好；纠正", "english": "put...right", "type": "短语", "keyWords": ["right"] },
    { "chinese": "把事情办好", "english": "put things right", "type": "短语", "keyWords": ["right"] },
    { "chinese": "学会在适当的时候说适当的话。", "english": "Learn to say the right thing at the right time.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "他是做这份工作最合适的人选。", "english": "He is the right man for the job.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "感觉一切都好吗（就身体而言）？", "english": "Do you feel all right?", "type": "句子", "keyWords": ["right"] },
    { "chinese": "立刻；马上", "english": "right away/off", "type": "短语", "keyWords": ["right"] },
    { "chinese": "他饭后立刻给我打了电话。", "english": "He called me right after dinner.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "事故正好发生在那里。", "english": "The accident happened right over there.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "把它放在正中间。", "english": "Put it right in the middle.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "习惯用右手的人", "english": "right-handed people", "type": "短语", "keyWords": ["right"] },
    { "chinese": "在某人的右面", "english": "on one's right (side)", "type": "短语", "keyWords": ["right"] },
    { "chinese": "明辨是非", "english": "know the difference between right and wrong", "type": "短语", "keyWords": ["right"] },
    { "chinese": "这本书的版权", "english": "the right to the book", "type": "短语", "keyWords": ["right"] },
    { "chinese": "(成)直角", "english": "(at) a right angle", "type": "短语", "keyWords": ["right"] },
    { "chinese": "(他)罪有应得。活该。", "english": "It serves (him) right.", "type": "句子", "keyWords": ["right"] },
    { "chinese": "n. 戒指；圈；环 v. 按（铃），打电话给 vi. 鸣；（铃等）响；按铃；打电话", "english": "ring", "type": "单词", "keyWords": [] },
    { "chinese": "回某人电话", "english": "ring (you) back", "type": "短语", "keyWords": ["ring"] },
    { "chinese": "挂断电话", "english": "ring off", "type": "短语", "keyWords": ["ring"] },
    { "chinese": "打他电话", "english": "ring him up/give him a ring", "type": "短语", "keyWords": ["ring"] },
    { "chinese": "我会按铃叫护士。", "english": "I'll ring for the nurse.", "type": "句子", "keyWords": ["ring"] },
    { "chinese": "爆炸的声音使我的耳朵嗡嗡作响。", "english": "My ears were ringing from the sound of the blast.", "type": "句子", "keyWords": ["ring"] },
    { "chinese": "a. 成熟的", "english": "ripe", "type": "单词", "keyWords": [] },
    { "chinese": "v. （使）成熟", "english": "ripen", "type": "单词", "keyWords": [] },
    { "chinese": "革命的时机已经成熟", "english": "be ripe for revolution", "type": "短语", "keyWords": ["ripe"] },
    { "chinese": "n. 升起；上升；上涨；增长，增加；兴起 vi. 升起；上升；起立，起床；起义", "english": "rise", "type": "单词", "keyWords": [] },
    { "chinese": "在上涨/增长", "english": "on the rise", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "引起", "english": "give rise to (doing) sth.", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "使人对她的动机产生怀疑的事实", "english": "facts that give rise to doubts about her motives", "type": "句子", "keyWords": ["rise"] },
    { "chinese": "站起来", "english": "rise to his feet", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "天亮时就起床", "english": "rise at dawn", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "高40英尺", "english": "rise 40 feet", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "起义；起来", "english": "rise up", "type": "短语", "keyWords": ["rise"] },
    { "chinese": "n. 危险，风险 vt. 冒…的危险；使（生命、财产等）遭受危险", "english": "risk", "type": "单词", "keyWords": [] },
    { "chinese": "a. 危险的，有风险的", "english": "risky", "type": "单词", "keyWords": [] },
    { "chinese": "在（高度）危险中", "english": "at (high) risk", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "地中海沿岸地区有90%的土地被认为处于高危状态。", "english": "More than 90% of land bordering the Mediterranean is identified as being at high risk.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "留有…的危险；使…冒有危险", "english": "at a risk of (doing) sth.", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "他冒着生命危险救了我的命。", "english": "He saved my life at the risk of his own.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "尽管可能会使读者感到无聊，我还是要再加上几个实例。", "english": "At the risk of being dull, I must add a few more illustrations.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "冒险做某事；冒…的危险", "english": "risk doing sth. = run/take the risk of doing sth.", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "冒遭遇风暴之险", "english": "risk getting caught in a storm", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "那些观点有煽动暴力的危险。", "english": "Those ideas risked encouraging violence.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "冒着生命危险", "english": "risk one's life", "type": "短语", "keyWords": ["risk"] },
    { "chinese": "他冒着生命危险救那个溺水儿童。", "english": "He risked his life (in) saving the drowning child.", "type": "句子", "keyWords": ["risk"] },
    { "chinese": "n. 江，河", "english": "river", "type": "单词", "keyWords": [] },
    { "chinese": "n. 河床", "english": "riverbed", "type": "单词", "keyWords": [] },
    { "chinese": "n. 路；道路，公路；街道", "english": "road", "type": "单词", "keyWords": [] },
    { "chinese": "成功之路", "english": "the roads to success", "type": "短语", "keyWords": ["road"] },
    { "chinese": "路标", "english": "road sign", "type": "短语", "keyWords": ["road"] },
    { "chinese": "v. （狮等）叫；发出隆隆声；大声叫喊 v. 呼喊；大声喊出 n. 吼叫，怒号；狂笑", "english": "roar", "type": "单词", "keyWords": [] },
    { "chinese": "虎啸", "english": "the roars of a tiger", "type": "短语", "keyWords": ["roar"] },
    { "chinese": "大炮的轰鸣声", "english": "the roars of guns", "type": "短语", "keyWords": ["roar"] },
    { "chinese": "听了我的笑话而哄堂大笑", "english": "roar with laughter at my joke", "type": "短语", "keyWords": ["roar"] },
    { "chinese": "v. 烤，炙，烘 a. 烤过的", "english": "roast", "type": "单词", "keyWords": [] },
    { "chinese": "v. 抢劫；（非法）剥夺；使丧失", "english": "rob", "type": "单词", "keyWords": [] },
    { "chinese": "n. 强盗", "english": "robber", "type": "单词", "keyWords": [] },
    { "chinese": "n. 抢劫；抢劫案", "english": "robbery", "type": "单词", "keyWords": [] },
    { "chinese": "抢劫某人/某地某物", "english": "rob sb./sw. of sth.", "type": "短语", "keyWords": ["rob"] },
    { "chinese": "n. 机器人", "english": "robot", "type": "单词", "keyWords": [] },
    { "chinese": "n. 摇滚乐/舞；岩石；岩块；巨石 v. （使）摇动", "english": "rock", "type": "单词", "keyWords": [] },
    { "chinese": "坚如磐石", "english": "as solid/firm as a rock", "type": "短语", "keyWords": ["rock"] },
    { "chinese": "摇椅", "english": "rocking chair", "type": "短语", "keyWords": ["rock"] },
    { "chinese": "n. 火箭 vi. 迅速上升或猛涨", "english": "rocket", "type": "单词", "keyWords": [] },
    { "chinese": "宇宙火箭", "english": "a space rocket", "type": "短语", "keyWords": ["rocket"] },
    { "chinese": "n. 杆；竿", "english": "rod", "type": "单词", "keyWords": [] },
    { "chinese": "n. 角色；作用", "english": "role", "type": "单词", "keyWords": [] },
    { "chinese": "在…中起重要作用", "english": "play an important/leading part/role in (doing) sth.", "type": "短语", "keyWords": ["role"] },
    { "chinese": "v. 滚动；转动；滚落；被卷起；（云、浪等）翻滚 v. 使滚动；卷；绕 n. 名单，花名册；（一）卷；滚动", "english": "roll", "type": "单词", "keyWords": [] },
    { "chinese": "点名", "english": "call the roll", "type": "短语", "keyWords": ["roll"] },
    { "chinese": "一卷磁带", "english": "a roll of tape", "type": "短语", "keyWords": ["roll"] },
    { "chinese": "滚滚浓烟", "english": "the rolling smoke", "type": "短语", "keyWords": ["roll"] },
    { "chinese": "波涛滚滚的大海", "english": "the rolling sea", "type": "短语", "keyWords": ["roll"] },
    { "chinese": "山羊翻了一个身，死了。", "english": "The goat rolled over, dead.", "type": "句子", "keyWords": ["roll"] },
    { "chinese": "n. 浪漫故事/作品；浪漫，传奇性", "english": "romance", "type": "单词", "keyWords": [] },
    { "chinese": "a. 浪漫的；传奇（式）的；有浪漫色彩的 n. 浪漫的人", "english": "romantic", "type": "单词", "keyWords": [] },
    { "chinese": "n. 浪漫精神；浪漫主义", "english": "romanticism", "type": "单词", "keyWords": [] },
    { "chinese": "n. 屋顶", "english": "roof", "type": "单词", "keyWords": [] },
    { "chinese": "同住一屋", "english": "live under the same roof", "type": "短语", "keyWords": ["roof"] },
    { "chinese": "喧闹不休，（在屋内）吵翻天", "english": "raise the roof", "type": "短语", "keyWords": ["roof"] },
    { "chinese": "n. 房间；室；空间；空位子；余地", "english": "room", "type": "单词", "keyWords": [] },
    { "chinese": "为…留下空间", "english": "leave room for", "type": "短语", "keyWords": ["room"] },
    { "chinese": "给…腾出地方", "english": "make room for", "type": "短语", "keyWords": ["room"] },
    { "chinese": "（没）有…余地", "english": "There's (no) room for...", "type": "短语", "keyWords": ["room"] },
    { "chinese": "你的工作还有改进的余地。", "english": "There's room for improvement in your work.", "type": "句子", "keyWords": ["room"] },
    { "chinese": "n. 根；根茎；词根；根源 v. （使）生/扎根；（使）牢固树立", "english": "root", "type": "单词", "keyWords": [] },
    { "chinese": "生（扎）根", "english": "take root", "type": "短语", "keyWords": ["root"] },
    { "chinese": "平方根", "english": "square root", "type": "短语", "keyWords": ["root"] },
    { "chinese": "连根拔起；根除，肃清", "english": "root up (the trees)", "type": "短语", "keyWords": ["root"] },
    { "chinese": "这种现象根源于国人的重理轻文。", "english": "This phenomenon is rooted in the Chinese thoughts that value sciences and neglect humanities.", "type": "句子", "keyWords": ["root"] },
    { "chinese": "n. 绳索；粗绳", "english": "rope", "type": "单词", "keyWords": [] },
    { "chinese": "n. 玫瑰", "english": "rose", "type": "单词", "keyWords": [] },
    { "chinese": "不尽人意", "english": "be not all roses", "type": "短语", "keyWords": ["rose"] },
    { "chinese": "人生绝非事事如意。", "english": "Life is not all roses by any means.", "type": "句子", "keyWords": ["rose"] },
    { "chinese": "没有十全十美。", "english": "There's no rose without a thorn.", "type": "句子", "keyWords": ["rose"] },
    { "chinese": "vi. 腐烂，腐败 v. 使腐烂；使腐朽", "english": "rot", "type": "单词", "keyWords": [] },
    { "chinese": "a. 腐烂的；腐臭的；腐败的；堕落的", "english": "rotten", "type": "单词", "keyWords": [] },
    { "chinese": "a. 粗糙的；粗制的；崎岖的；狂暴的；粗鲁的；粗略的；有暴风雨的", "english": "rough", "type": "单词", "keyWords": [] },
    { "chinese": "崎岖的小路", "english": "a rough road", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "狂风暴雨的天气", "english": "rough weather", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "在波涛汹涌的海上", "english": "in/on the rough sea", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "粗略地了解", "english": "get a rough idea of", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "（未切边的）毛边书", "english": "a book with rough edges", "type": "短语", "keyWords": ["rough"] },
    { "chinese": "a. 圆的；环形的；十足的 prep. 围（绕）着；在…各处；在…一带/四周；大约 ad. 转过来；围绕 n. 一轮回，一回合", "english": "round", "type": "单词", "keyWords": [] },
    { "chinese": "来回的旅行", "english": "a round trip", "type": "短语", "keyWords": ["round"] },
    { "chinese": "十足的谎话", "english": "a round lie", "type": "短语", "keyWords": ["round"] },
    { "chinese": "另一轮的外交谈判", "english": "another round of diplomatic talks", "type": "短语", "keyWords": ["round"] },
    { "chinese": "正好相反；用正好相反的方法", "english": "be/go the other way round", "type": "短语", "keyWords": ["round"] },
    { "chinese": "(就)在拐弯处；即将到来", "english": "round the corner", "type": "短语", "keyWords": ["round"] },
    { "chinese": "就在街角拐弯处。", "english": "It's just round the corner of the street.", "type": "句子", "keyWords": ["round"] },
    { "chinese": "复活节就要来了。", "english": "Easter is round the corner.", "type": "句子", "keyWords": ["round"] },
    { "chinese": "全天候营业商店", "english": "a round-the-clock shop", "type": "短语", "keyWords": ["round"] },
    { "chinese": "把…聚集在一起；包围", "english": "round...up", "type": "短语", "keyWords": ["round"] },
    { "chinese": "将奶牛圈在一处挤奶", "english": "round up the cows for milking", "type": "短语", "keyWords": ["round"] },
    { "chinese": "n. （道）路；路/航线；途径 v. 给…规定路线/次序/程序", "english": "route", "type": "单词", "keyWords": [] },
    { "chinese": "去欧洲最快的路线", "english": "the quickest route to take to Europe", "type": "短语", "keyWords": ["route"] },
    { "chinese": "n. 例行公事；惯例 a. 例行的；常规的", "english": "routine", "type": "单词", "keyWords": [] },
    { "chinese": "v. 划（船） v. 使成行/排 n. （一）排；（一）行", "english": "row", "type": "单词", "keyWords": [] },
    { "chinese": "坐成一排", "english": "sit in a row", "type": "短语", "keyWords": ["row"] },
    { "chinese": "a. 国王的；女王的；王室的", "english": "royal", "type": "单词", "keyWords": [] },
    { "chinese": "v. 擦；摩擦", "english": "rub", "type": "单词", "keyWords": [] },
    { "chinese": "木炭块同玻璃棒一摩擦棒上就带电。", "english": "No sooner had the pieces of charcoal been rubbed against the glass rod than electricity appeared on the rod.", "type": "句子", "keyWords": ["rub"] },
    { "chinese": "n. 橡胶；橡皮", "english": "rubber", "type": "单词", "keyWords": [] },
    { "chinese": "n. 垃圾，废物", "english": "rubbish", "type": "单词", "keyWords": [] },
    { "chinese": "说废话", "english": "talk rubbish", "type": "短语", "keyWords": ["rubbish"] },
    { "chinese": "a. 粗鲁的；粗糙的；猛烈的；简单的", "english": "rude", "type": "单词", "keyWords": [] },
    { "chinese": "n. 粗鲁，粗暴", "english": "rudeness", "type": "单词", "keyWords": [] },
    { "chinese": "草图，简图", "english": "a rude drawing", "type": "短语", "keyWords": ["rude"] },
    { "chinese": "对某人粗暴无礼", "english": "be rude to sb.", "type": "短语", "keyWords": ["rude"] },
    { "chinese": "v./n. 毁坏；毁灭；毁掉（前途）；使破产；废墟", "english": "ruin", "type": "单词", "keyWords": [] },
    { "chinese": "坏掉；毁灭，灭亡；崩溃", "english": "go/come/fall to ruin", "type": "短语", "keyWords": ["ruin"] },
    { "chinese": "成为废墟", "english": "be in ruins", "type": "短语", "keyWords": ["ruin"] },
    { "chinese": "n. 规则，规章；惯例，准则；统治，治理；控制；支配", "english": "rule", "type": "单词", "keyWords": [] },
    { "chinese": "v. 统治，治理", "english": "rule", "type": "单词", "keyWords": [] },
    { "chinese": "按规定，按规则，依照规则；机械地", "english": "by rule", "type": "短语", "keyWords": ["rule"] },
    { "chinese": "通常；总体上", "english": "as a rule", "type": "短语", "keyWords": ["rule"] },
    { "chinese": "养成习惯；规定…", "english": "make it a rule to do sth.", "type": "短语", "keyWords": ["rule"] },
    { "chinese": "有规则必有例外。", "english": "There is no rule without an exception.", "type": "句子", "keyWords": ["rule"] },
    { "chinese": "n. 直尺；统治者，管理者", "english": "ruler", "type": "单词", "keyWords": [] },
    { "chinese": "v. 跑；奔；竞选；（机器等）运转；流淌；（织物上染料）渗化或渗色；变（成） v. 使跑；使奔；在…上跑；经营，管理", "english": "run", "type": "单词", "keyWords": [] },
    { "chinese": "偶然遇见；撞上；陷入（困境等）", "english": "run/bump into", "type": "短语", "keyWords": ["run"] },
    { "chinese": "我们开始负债了。", "english": "We ran into debt.", "type": "句子", "keyWords": ["run"] },
    { "chinese": "汽车撞倒并碾过他的身体。", "english": "The car ran over him.", "type": "句子", "keyWords": ["run"] },
    { "chinese": "用完，耗尽（主动）", "english": "(sb.) run out of sth.", "type": "短语", "keyWords": ["run"] },
    { "chinese": "被耗尽/变松（被动）", "english": "run out/loose", "type": "短语", "keyWords": ["run"] },
    { "chinese": "(因耗尽而)缺少", "english": "(sb.) run short of sth.", "type": "短语", "keyWords": ["run"] },
    { "chinese": "变冷/干涸/被用完", "english": "run cold/dry/short", "type": "短语", "keyWords": ["run"] },
    { "chinese": "颜色褪色。", "english": "The color runs.", "type": "句子", "keyWords": ["run"] },
    { "chinese": "偶遇，不期而遇", "english": "run/come across", "type": "短语", "keyWords": ["run"] },
    { "chinese": "赶快去求救", "english": "run for help", "type": "短语", "keyWords": ["run"] },
    { "chinese": "到处跑，跑来跑去", "english": "run about", "type": "短语", "keyWords": ["run"] },
    { "chinese": "竞选市长", "english": "run for mayor", "type": "短语", "keyWords": ["run"] },
    { "chinese": "追赶；追捕；跟踪", "english": "run after", "type": "短语", "keyWords": ["run"] },
    { "chinese": "忙碌", "english": "be on the run", "type": "短语", "keyWords": ["run"] },
    { "chinese": "从长远来看；终究", "english": "in the long run", "type": "短语", "keyWords": ["run"] },
    { "chinese": "发高烧；说胡话", "english": "run a high fever", "type": "短语", "keyWords": ["run"] },
    { "chinese": "流鼻涕", "english": "have a running nose", "type": "短语", "keyWords": ["run"] },
    { "chinese": "这个剧连演了六个月。", "english": "The play ran for six months.", "type": "句子", "keyWords": ["run"] },
    { "chinese": "n. 跑步的人；赛跑的人（或马等）", "english": "runner", "type": "单词", "keyWords": [] },
    { "chinese": "a. 农村的；乡下的，田园的，乡村风味的", "english": "rural", "type": "单词", "keyWords": [] },
    { "chinese": "v. 冲；奔；猛攻 v. 急冲；逼；催促；猛攻；急送", "english": "rush", "type": "单词", "keyWords": [] },
    { "chinese": "n. 冲；奔；匆忙；（交通、事务等）繁忙；猛攻", "english": "rush", "type": "单词", "keyWords": [] },
    { "chinese": "把他急匆匆地送到医院", "english": "rush him to a hospital", "type": "短语", "keyWords": ["rush"] },
    { "chinese": "为什么这样急急忙忙的？", "english": "Why all this rush?", "type": "句子", "keyWords": ["rush"] },
    { "chinese": "猛然冲向（出口处）", "english": "make a rush for (the exit)", "type": "短语", "keyWords": ["rush"] },
    { "chinese": "这本小说是以1849年加利福尼亚州淘金热为背景的。", "english": "This novel is set in the 1849 California gold rush.", "type": "句子", "keyWords": ["rush"] },
    { "chinese": "在交通高峰期", "english": "in the rush hour", "type": "短语", "keyWords": ["rush"] },
    { "chinese": "急速地", "english": "in a rush", "type": "短语", "keyWords": ["rush"] },
    { "chinese": "v.（使）生锈", "english": "rust", "type": "单词", "keyWords": [] },
    { "chinese": "a. 生锈的；迟钝的；腐蚀了的", "english": "rusty", "type": "单词", "keyWords": [] },
    { "chinese": "n. 麻袋；包；（一）大袋；纸袋；[口]解雇", "english": "sack", "type": "单词", "keyWords": [] },
    { "chinese": "被解雇", "english": "get the sack", "type": "短语", "keyWords": ["sack"] },
    { "chinese": "解雇某人", "english": "give sb. the sack", "type": "短语", "keyWords": ["sack"] },
    { "chinese": "n. 献身，牺牲；祭献；祭品；供奉 v. 牺牲；祭献；献出", "english": "sacrifice", "type": "单词", "keyWords": [] },
    { "chinese": "宰羊作为供品", "english": "kill sheep as a sacrifice", "type": "短语", "keyWords": ["sacrifice"] },
    { "chinese": "亏本/蚀本出售", "english": "sell sth. at a sacrifice", "type": "短语", "keyWords": ["sacrifice"] },
    { "chinese": "我绝没想到要你作出这样的牺牲。", "english": "I would never dream of asking you to make such a sacrifice.", "type": "句子", "keyWords": ["sacrifice"] },
    { "chinese": "他为拯救落水的孩子而献出自己的生命。", "english": "He sacrificed his life to save the drowning child.", "type": "句子", "keyWords": ["sacrifice"] },
    { "chinese": "为…而献身", "english": "sacrifice/lose one's life for (one's motherland)", "type": "短语", "keyWords": ["sacrifice"] },
    { "chinese": "a. 伤心的；难过的；令人悲伤的", "english": "sad", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 伤心地，难过地", "english": "sadly", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使悲伤；使伤心", "english": "sadden", "type": "单词", "keyWords": [] },
    { "chinese": "n. 悲伤，伤心", "english": "sadness", "type": "单词", "keyWords": [] },
    { "chinese": "a. 安全的；平安的；谨慎的", "english": "safe", "type": "单词", "keyWords": [] },
    { "chinese": "n. 保险箱；冷藏柜/室", "english": "safe", "type": "单词", "keyWords": [] },
    { "chinese": "平安无事地归来", "english": "return safe and sound", "type": "短语", "keyWords": ["safe"] },
    { "chinese": "没…危险的，安全的", "english": "be safe from...", "type": "短语", "keyWords": ["safe"] },
    { "chinese": "他安全到达。", "english": "He arrived safe.", "type": "句子", "keyWords": ["safe"] },
    { "chinese": "n. 安全；平安；安全地点", "english": "safety", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 安全地，平安地", "english": "safely", "type": "单词", "keyWords": [] },
    { "chinese": "把某人带到安全地带", "english": "carry sb. to safety", "type": "短语", "keyWords": ["safety"] },
    { "chinese": "安全带", "english": "safety belt", "type": "短语", "keyWords": ["safety"] },
    { "chinese": "安全别针", "english": "safety pin", "type": "短语", "keyWords": ["safety"] },
    { "chinese": "vi. 航行 v. 航行于；驾驶（船）", "english": "sail", "type": "单词", "keyWords": [] },
    { "chinese": "n. 帆", "english": "sail", "type": "单词", "keyWords": [] },
    { "chinese": "n. 海员，水手", "english": "sailor", "type": "单词", "keyWords": [] },
    { "chinese": "起航去某地", "english": "set sail for... / sail for...", "type": "短语", "keyWords": ["sail"] },
    { "chinese": "横渡太平洋", "english": "sail the Pacific", "type": "短语", "keyWords": ["sail"] },
    { "chinese": "n. 缘故；利益", "english": "sake", "type": "单词", "keyWords": [] },
    { "chinese": "为了…的利益/缘故，为了…", "english": "for the sake of sb. = for sb.'s sake", "type": "短语", "keyWords": ["sake"] },
    { "chinese": "看在上帝的份上", "english": "for God's/goodness/heaven's sake", "type": "短语", "keyWords": ["sake"] },
    { "chinese": "n. 色拉；凉拌菜", "english": "salad", "type": "单词", "keyWords": [] },
    { "chinese": "色拉用调料", "english": "salad dressing", "type": "短语", "keyWords": ["salad"] },
    { "chinese": "n. 薪水", "english": "salary", "type": "单词", "keyWords": [] },
    { "chinese": "薪水微薄/丰厚", "english": "a small/good/high/handsome salary", "type": "短语", "keyWords": ["salary"] },
    { "chinese": "n. 出售；廉价出售；销量；销售额", "english": "sale", "type": "单词", "keyWords": [] },
    { "chinese": "有售；上市；廉价出售", "english": "on sale", "type": "短语", "keyWords": ["sale"] },
    { "chinese": "供出售；待售", "english": "for sale", "type": "短语", "keyWords": ["sale"] },
    { "chinese": "销货损益", "english": "sales profit and loss", "type": "短语", "keyWords": ["sales"] },
    { "chinese": "营业部", "english": "sales department", "type": "短语", "keyWords": ["sales"] },
    { "chinese": "n. 推销员", "english": "salesman", "type": "单词", "keyWords": [] },
    { "chinese": "n. 盐 v. 在…中/上加盐；腌", "english": "salt", "type": "单词", "keyWords": [] },
    { "chinese": "a. 含盐的；咸的", "english": "salty", "type": "单词", "keyWords": [] },
    { "chinese": "a.相同的;同样的(常与the连用)", "english": "same", "type": "单词", "keyWords": [] },
    { "chinese": "仍然;还是;完全一样,无所谓", "english": "all just the same (to sb.or sth.)", "type": "短语", "keyWords": ["same"] },
    { "chinese": "差不多完全一样,几乎一样;大同小异", "english": "about/much the same", "type": "短语", "keyWords": ["same"] },
    { "chinese": "有点两样", "english": "not quite the same", "type": "短语", "keyWords": ["same"] },
    { "chinese": "和...一样", "english": "the same ...as/ that...", "type": "短语", "keyWords": ["same"] },
    { "chinese": "[口]我也这样祝愿你!", "english": "The same to you!", "type": "句子", "keyWords": ["same"] },
    { "chinese": "...一样", "english": "It is the same with.../ So it is with...", "type": "短语", "keyWords": ["same"] },
    { "chinese": "...也是如此", "english": "The same is true of...", "type": "短语", "keyWords": ["same"] },
    { "chinese": "n.[C]样品;试样;实例 vt.抽样检查;品尝(食品)", "english": "sample", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]沙;(pl.)沙滩;大片沙地", "english": "sand", "type": "单词", "keyWords": [] },
    { "chinese": "a.沙地的,多沙的", "english": "sandy", "type": "单词", "keyWords": [] },
    { "chinese": "不切实际;不稳固的;不稳妥的", "english": "be built on sand", "type": "短语", "keyWords": ["sand"] },
    { "chinese": "n.[C]三明治 vt.把..夹在中间;插入,夹入", "english": "sandwich", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]卫星", "english": "satellite", "type": "单词", "keyWords": [] },
    { "chinese": "卫星城市", "english": "a satellite city", "type": "短语", "keyWords": ["satellite"] },
    { "chinese": "n.[C/U]满意,满足 n.[C]令人满意的事物", "english": "satisfaction", "type": "单词", "keyWords": [] },
    { "chinese": "对...表示满意", "english": "express one's satisfaction at/ with", "type": "短语", "keyWords": ["satisfaction"] },
    { "chinese": "满意地", "english": "with satisfaction", "type": "短语", "keyWords": ["satisfaction"] },
    { "chinese": "达到使某人满意的程度", "english": "to sb's satisfaction", "type": "短语", "keyWords": ["satisfaction"] },
    { "chinese": "a.令人满意的;可喜的", "english": "satisfactory", "type": "单词", "keyWords": [] },
    { "chinese": "很不令人满意", "english": "be anything but satisfactory", "type": "短语", "keyWords": ["satisfactory"] },
    { "chinese": "完全不令人满意", "english": "be far from satisfactory", "type": "短语", "keyWords": ["satisfactory"] },
    { "chinese": "vt.使满意;满足(需要);达到(要求),符合(条件)", "english": "satisfy", "type": "单词", "keyWords": [] },
    { "chinese": "对...感到满意", "english": "be satisfied with", "type": "短语", "keyWords": ["satisfy"] },
    { "chinese": "满意的神情", "english": "a satisfied look", "type": "短语", "keyWords": ["satisfy"] },
    { "chinese": "令人满意的结局", "english": "a satisfying ending", "type": "短语", "keyWords": ["satisfy"] },
    { "chinese": "n.[C]星期六(缩)Sat.", "english": "Saturday", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]沙司,调味汁", "english": "sauce", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]茶碟;碟状物", "english": "saucer", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]香肠,腊肠", "english": "sausage", "type": "单词", "keyWords": [] },
    { "chinese": "vt.搭救;节省;储蓄(up) vi.节省(on)", "english": "save", "type": "单词", "keyWords": [] },
    { "chinese": "搭救..;使...免于...", "english": "save...from...", "type": "短语", "keyWords": ["save"] },
    { "chinese": "节约用电/节约用气", "english": "save/ economize on electricity/ gas", "type": "短语", "keyWords": ["save"] },
    { "chinese": "n.[C]节省;救助;(pl.)储蓄(金);存款", "english": "saving", "type": "单词", "keyWords": [] },
    { "chinese": "v.说话;讲话 v.说;讲;假定;比如说;显示;写着 n.[C]发言权", "english": "say", "type": "单词", "keyWords": [] },
    { "chinese": "自言自语", "english": "say sth. to oneself", "type": "短语", "keyWords": ["say"] },
    { "chinese": "我想,大概", "english": "I dare say", "type": "短语", "keyWords": ["say"] },
    { "chinese": "据说在.../已经...", "english": "be said to be doing/ to have done", "type": "短语", "keyWords": ["say"] },
    { "chinese": "现在时间是两点半。", "english": "The clock says half past two.", "type": "句子", "keyWords": ["say"] },
    { "chinese": "不用说,不言而喻,理所当然", "english": "It goes without saying that...", "type": "短语", "keyWords": ["say"] },
    { "chinese": "很难说;没法知道;没法预料", "english": "There is no saying...", "type": "短语", "keyWords": ["say"] },
    { "chinese": "更不用说(近let alone, not to mention)", "english": "to say nothing of", "type": "短语", "keyWords": ["say"] },
    { "chinese": "报上说", "english": "It says in the newspaper that...", "type": "短语", "keyWords": ["say"] },
    { "chinese": "即,换句话说(无过去式)", "english": "that is (to say) (=in other words)", "type": "短语", "keyWords": ["say"] },
    { "chinese": "否定,拒绝,反对/肯定,赞成,同意", "english": "say no/ yes to (doing) sth.", "type": "短语", "keyWords": ["say"] },
    { "chinese": "[口]你对某事有什么意见?你赞成不赞成做某事?", "english": "What do/ would you say to doing sth.?", "type": "句子", "keyWords": ["say"] },
    { "chinese": "余下的数目不大,姑且说,只有十个吧。", "english": "The number left was not great, say, only ten.", "type": "句子", "keyWords": ["say"] },
    { "chinese": "对此事父亲有最后的决定权。", "english": "The father had the final say in the matter.", "type": "句子", "keyWords": ["say"] },
    { "chinese": "说起来容易做起来难。", "english": "Easier said than done.", "type": "句子", "keyWords": ["say"] },
    { "chinese": "n.[C]谚语,俗语;格言", "english": "saying", "type": "单词", "keyWords": [] },
    { "chinese": "俗话说;常言道", "english": "As the saying goes (As the proverb says)....", "type": "短语", "keyWords": ["saying"] },
    { "chinese": "俗话说:常言道", "english": "A saying goes that...", "type": "短语", "keyWords": ["saying"] },
    { "chinese": "n.[C]等级(表);刻度;比例;规模;范围;鳞片;(pl.)天平;(磅)秤 v.量(为)(近weigh)(被)过称", "english": "scale", "type": "单词", "keyWords": [] },
    { "chinese": "罗盘标度", "english": "compass scale", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "折尺", "english": "a folding scale", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "大规模地", "english": "on a big/large scale", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "按...比例;按...规模", "english": "on the/ a scale of", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "在磅秤上称体重", "english": "weigh sth. on the scales", "type": "短语", "keyWords": ["scale"] },
    { "chinese": "v.快读;扫描", "english": "scan", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]扫描仪;扫描器", "english": "scanner", "type": "单词", "keyWords": [] },
    { "chinese": "a.缺乏的;稀有的", "english": "scarce", "type": "单词", "keyWords": [] },
    { "chinese": "ad.几乎不;刚刚;才", "english": "scarcely", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U](可与a连用)稀缺资源", "english": "scarcity", "type": "单词", "keyWords": [] },
    { "chinese": "稀缺资源", "english": "scarce resources", "type": "短语", "keyWords": ["scarce"] },
    { "chinese": "一...就....", "english": "scarcely/hardly ... when ...", "type": "短语", "keyWords": ["scarcely"] },
    { "chinese": "他刚刚到达就不得不又离开。", "english": "Scarcely had he arrived when he had to leave again.", "type": "句子", "keyWords": ["scarcely"] },
    { "chinese": "v.使惊恐,使害怕 n.[U]惊恐,恐慌", "english": "scare", "type": "单词", "keyWords": [] },
    { "chinese": "把...吓跑", "english": "scare ...away", "type": "短语", "keyWords": ["scare"] },
    { "chinese": "吓得要死", "english": "be scared to death", "type": "短语", "keyWords": ["scare"] },
    { "chinese": "害怕...", "english": "be scared/ afraid/ frightened of", "type": "短语", "keyWords": ["scare"] },
    { "chinese": "吓得做/不敢做某事", "english": "be scared into/ out of doing sth.", "type": "短语", "keyWords": ["scare"] },
    { "chinese": "n.[C]围巾;(肩)巾", "english": "scarf", "type": "单词", "keyWords": [] },
    { "chinese": "vt.撒;分散;驱散 vi.散开", "english": "scatter", "type": "单词", "keyWords": [] },
    { "chinese": "把种子撒播在地里", "english": "scatter the fields with seeds = scatter seeds on the fields", "type": "短语", "keyWords": ["scatter"] },
    { "chinese": "稀疏的人口", "english": "a thinly scattered population", "type": "短语", "keyWords": ["scatter"] },
    { "chinese": "n.[C]景色;布景,场景;地点;现场", "english": "scene", "type": "单词", "keyWords": [] },
    { "chinese": "a.风景优美的,舞台的", "english": "scenic", "type": "单词", "keyWords": [] },
    { "chinese": "一派繁荣景象", "english": "a scene of prosperity", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "第一幕第二场", "english": "Act I Scene II", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "在现场;到现场", "english": "on the scene/spot", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "犯罪/车祸现场", "english": "the scene of the crime/ a traffic accident", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "景点(近tourist attractions, places of interest)", "english": "scenic spots", "type": "短语", "keyWords": ["scene"] },
    { "chinese": "n.[U]风景,景色", "english": "scenery", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]时间表;计划(表);日程安排(表);进度表 v.将....列入时间表中,排定(在某时间做某事)", "english": "schedule", "type": "单词", "keyWords": [] },
    { "chinese": "定期航班", "english": "a scheduled flight", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "晚了", "english": "behind schedule", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "提前(近ahead of time, beforehand )", "english": "ahead of schedule", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "准时:按照时间表(近according to schedule)", "english": "on schedule", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "下周工作时间进度表", "english": "time schedule for next week", "type": "短语", "keyWords": ["schedule"] },
    { "chinese": "罢工计划在黎明开始实施。", "english": "The strike was scheduled to begin at dawn.", "type": "句子", "keyWords": ["schedule"] },
    { "chinese": "n.[C]计划;方案:规划;阴谋,诡计 v.搞阴谋;兼划;密谋", "english": "scheme", "type": "单词", "keyWords": [] },
    { "chinese": "想出筹钱的方法", "english": "work out a scheme for raising money", "type": "短语", "keyWords": ["scheme"] },
    { "chinese": "n.[C]学者", "english": "scholar", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]奖学金 n.[U]学问", "english": "scholarship", "type": "单词", "keyWords": [] },
    { "chinese": "获奖学金", "english": "win a scholarship", "type": "短语", "keyWords": ["scholarship"] },
    { "chinese": "n.[C]学校;流派,学派;(鱼)群 n.[U]上学,在学习", "english": "school", "type": "单词", "keyWords": [] },
    { "chinese": "上学", "english": "at school", "type": "短语", "keyWords": ["school"] },
    { "chinese": "毕业", "english": "leave/ finish school", "type": "短语", "keyWords": ["school"] },
    { "chinese": "入学", "english": "start school", "type": "短语", "keyWords": ["school"] },
    { "chinese": "学生时代", "english": "school days", "type": "短语", "keyWords": ["school"] },
    { "chinese": "一群鲸", "english": "a school of whales", "type": "短语", "keyWords": ["school"] },
    { "chinese": "校舍", "english": "schoolhouse", "type": "单词", "keyWords": [] },
    { "chinese": "新分析法学派", "english": "new analytical school of law", "type": "短语", "keyWords": ["school"] },
    { "chinese": "n.[U]学校教育", "english": "schooling", "type": "单词", "keyWords": [] },
    { "chinese": "他们没受过什么学校教育。", "english": "They have little schooling.", "type": "句子", "keyWords": ["schooling"] },
    { "chinese": "n.[U]科学;自然科学 n.[C]一门(科学的)学科", "english": "science", "type": "单词", "keyWords": [] },
    { "chinese": "科学技术,科技", "english": "science and technology", "type": "短语", "keyWords": ["science"] },
    { "chinese": "天文学是一个非常复杂的学科。", "english": "Astronomy is a very complicated science.", "type": "句子", "keyWords": ["science"] },
    { "chinese": "a.科学(上)的;科学性的", "english": "scientific", "type": "单词", "keyWords": [] },
    { "chinese": "ad.科学地", "english": "scientifically", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]科学家", "english": "scientist", "type": "单词", "keyWords": [] },
    { "chinese": "n.(作pl.)剪刀", "english": "scissors", "type": "单词", "keyWords": [] },
    { "chinese": "一把剪刀", "english": "a pair of scissors", "type": "短语", "keyWords": ["scissors"] },
    { "chinese": "v.责骂;谩骂;叱责", "english": "scold", "type": "单词", "keyWords": [] },
    { "chinese": "因某事而责备某人", "english": "scold sb. for (doing) sth.", "type": "短语", "keyWords": ["scold"] },
    { "chinese": "(因某事)挨一顿大骂", "english": "get/ receive a good scolding (for sth.)", "type": "短语", "keyWords": ["scold"] },
    { "chinese": "把某人大骂一顿", "english": "give sb. a good scolding", "type": "短语", "keyWords": ["scold"] },
    { "chinese": "n.[C](比赛中)得分,比分;(测验中)成绩,分数;二十个(单复同) vt.得 (分);记(分);赢得 vi.得分;得胜", "english": "score", "type": "单词", "keyWords": [] },
    { "chinese": "踢进一个球", "english": "score a goal", "type": "短语", "keyWords": ["score"] },
    { "chinese": "得一分", "english": "score a point", "type": "短语", "keyWords": ["score"] },
    { "chinese": "70个人", "english": "three score and ten people", "type": "短语", "keyWords": ["score"] },
    { "chinese": "许多年", "english": "scores of years", "type": "短语", "keyWords": ["score"] },
    { "chinese": "40个鸡蛋", "english": "two score of eggs", "type": "短语", "keyWords": ["score"] },
    { "chinese": "vt.抓;划伤 n.[C]抓痕;搔", "english": "scratch", "type": "单词", "keyWords": [] },
    { "chinese": "vi.(因恐惧、痛苦等)尖声喊叫;惊叫 n.[C]尖叫声", "english": "scream", "type": "单词", "keyWords": [] },
    { "chinese": "放声大笑", "english": "scream with laughter", "type": "短语", "keyWords": ["scream"] },
    { "chinese": "大叫", "english": "scream out", "type": "短语", "keyWords": ["scream"] },
    { "chinese": "n.[C]屏;幕;银幕 vt.遮蔽;掩护", "english": "screen", "type": "单词", "keyWords": [] },
    { "chinese": "vt.用力擦洗;擦净", "english": "scrub", "type": "单词", "keyWords": [] },
    { "chinese": "擦洗地板", "english": "scrub the floor", "type": "短语", "keyWords": ["scrub"] },
    { "chinese": "n.[U]雕刻,雕塑 n.[C]雕刻品,雕塑品 v.雕塑", "english": "sculpture", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]海,海洋;大量", "english": "sea", "type": "单词", "keyWords": [] },
    { "chinese": "(住)在海外", "english": "(live) beyond the sea(s)", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "一大片,大量...", "english": "a sea of (flowers/ troubles...)", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "去当海员", "english": "go to sea", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "到海边去", "english": "go to the sea", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "在海上(= on the sea);不知所措,茫然(=at a loss)", "english": "at sea", "type": "短语", "keyWords": ["sea"] },
    { "chinese": "这艘船驶向大海。", "english": "The ship headed out to sea.", "type": "句子", "keyWords": ["sea"] },
    { "chinese": "n.[U]海产食品;海味,海鲜", "english": "seafood", "type": "单词", "keyWords": [] },
    { "chinese": "海鸥", "english": "sea gull", "type": "单词", "keyWords": [] },
    { "chinese": "海马", "english": "sea horse", "type": "单词", "keyWords": [] },
    { "chinese": "海贝壳", "english": "seashell", "type": "单词", "keyWords": [] },
    { "chinese": "海岸", "english": "seashore", "type": "单词", "keyWords": [] },
    { "chinese": "晕船的", "english": "seasick", "type": "单词", "keyWords": [] },
    { "chinese": "海藻,海草", "english": "seaweed", "type": "单词", "keyWords": [] },
    { "chinese": "海平面", "english": "sea level", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]印章/记;图章;封印/蜡/条/铅;批准;海豹 v.盖章于;(密)封;批准", "english": "seal", "type": "单词", "keyWords": [] },
    { "chinese": "在箱子上贴上封条", "english": "put a seal on the box", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "在合同上盖章", "english": "seal a contract", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封信封", "english": "seal an envelope", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封锁大楼", "english": "seal off the building", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封在罐子里", "english": "seal...in a can", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封好口的信", "english": "a sealed letter", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "封,火漆", "english": "sealing wax", "type": "短语", "keyWords": ["seal"] },
    { "chinese": "n.[C]搜寻,搜查 v.搜查;细查;在...中搜寻 vi.搜寻,搜查;追/探求", "english": "search", "type": "单词", "keyWords": [] },
    { "chinese": "仔细打量我;盘诘性地看我", "english": "give me a searching look", "type": "短语", "keyWords": ["search"] },
    { "chinese": "搜索水下的那个运动目标是一个较难的问题。", "english": "The search for the moving target under water was a tough problem.", "type": "句子", "keyWords": ["search"] },
    { "chinese": "在搜查房子时发现了两支没注册登记的枪。", "english": "The search of the house produced two unregistered guns.", "type": "句子", "keyWords": ["search"] },
    { "chinese": "搜寻、寻找", "english": "search...for...", "type": "短语", "keyWords": ["search"] },
    { "chinese": "警察在住宅内搜查藏匿的武器。", "english": "The police search a house for a hidden weapon.", "type": "句子", "keyWords": ["search"] },
    { "chinese": "(为了)寻找(常用作状语或表语)", "english": "in search of/ for", "type": "短语", "keyWords": ["search"] },
    { "chinese": "他们出发去寻找走失的孩子。", "english": "They set off in search of the lost child.", "type": "句子", "keyWords": ["search"] },
    { "chinese": "n.[C]海边;海滨 a.海边的;海滨的", "english": "seaside", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]时节,旺季;季(节);(体育、文艺、社交或商业季)活跃季节 v.调味,给...加调味料", "english": "season", "type": "单词", "keyWords": [] },
    { "chinese": "a.季节(性)的", "english": "seasonal", "type": "单词", "keyWords": [] },
    { "chinese": "上市", "english": "come into season", "type": "短语", "keyWords": ["season"] },
    { "chinese": "上市;当令;在旺季;在度假旺季", "english": "in season", "type": "短语", "keyWords": ["season"] },
    { "chinese": "不上市;不当令;不在旺季;在度假淡季", "english": "out of season", "type": "短语", "keyWords": ["season"] },
    { "chinese": "用盐和胡椒来调味", "english": "season the dish with salt and pepper", "type": "短语", "keyWords": ["season"] },
    { "chinese": "a.调过味的", "english": "seasoned", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]调味品,调料", "english": "seasoning", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]座位 v.使坐下,使就座;能容纳", "english": "seat", "type": "单词", "keyWords": [] },
    { "chinese": "就座(近take one's place就座;代替)", "english": "take one's seat", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "坐下", "english": "take/ have a seat", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "容纳200人", "english": "seat/ hold 200 people", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "就座", "english": "seat oneself", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "请坐。", "english": "Please be/ get seated.", "type": "句子", "keyWords": ["seat"] },
    { "chinese": "发现他独自坐在房间里", "english": "find him seated/ sitting alone in the room", "type": "短语", "keyWords": ["seat"] },
    { "chinese": "a.第二的 ad.第二,其次地 n.[C]秒;片刻;第二", "english": "second", "type": "单词", "keyWords": [] },
    { "chinese": "仅次于", "english": "(be) second only to...", "type": "短语", "keyWords": ["second"] },
    { "chinese": "[口]比谁都好;首屈一指", "english": "(be) second to none", "type": "短语", "keyWords": ["second"] },
    { "chinese": "你还需要一双。", "english": "You need a second pair.", "type": "句子", "keyWords": ["second"] },
    { "chinese": "获第二", "english": "come (in) second", "type": "短语", "keyWords": ["second"] },
    { "chinese": "再经考虑我会接受那个报价的。", "english": "On second thoughts I will accept the offer.", "type": "句子", "keyWords": ["second"] },
    { "chinese": "第一/二个离开(不用leaving)", "english": "(be) the frst/ second to leave", "type": "短语", "keyWords": ["second"] },
    { "chinese": "a.(教育、学校等)中等的;第二的", "english": "secondary", "type": "单词", "keyWords": [] },
    { "chinese": "a.用过的;旧的;间接的;(第)二手的", "english": "secondhand", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]秘密;秘诀(of) a.秘密的;暗中的", "english": "secret", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C/U]秘密,保密", "english": "secrecy", "type": "单词", "keyWords": [] },
    { "chinese": "公开的秘密", "english": "an open secret", "type": "短语", "keyWords": ["secret"] },
    { "chinese": "秘密地(=secretly)", "english": "in secret", "type": "短语", "keyWords": ["secret"] },
    { "chinese": "不把某事告诉某人", "english": "keep sth. (a) secret (from sb.)", "type": "短语", "keyWords": ["secret"] },
    { "chinese": "n.[C]秘书;书记", "english": "secretary", "type": "单词", "keyWords": [] },
    { "chinese": "总书记", "english": "secretary general", "type": "短语", "keyWords": ["secretary"] },
    { "chinese": "n.[C]部分;(文章等)段,节;(部门)处,科,股;地段;切面", "english": "section", "type": "单词", "keyWords": [] },
    { "chinese": "a.安全可靠的,有保障的;牢固的;安心的;无忧虑的 v.使安全;保卫;妥善保管;获得", "english": "secure", "type": "单词", "keyWords": [] },
    { "chinese": "不致受到危害", "english": "be secure/safe from harm", "type": "短语", "keyWords": ["secure"] }
];
