const qgl256_270 = [
    { "chinese": "n.[C]说话者，演讲者；扬声器，喇叭", "english": "speaker /'spi:kə/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.特殊的；专门的", "english": "special /'speʃl/", "type": "单词", "keyWords": [] },
    { "chinese": "adv.特别地", "english": "specially", "type": "单词", "keyWords": ["special"] },
    { "chinese": "n.[C]专家", "english": "specialist", "type": "单词", "keyWords": ["special"] },
    { "chinese": "特别地区，特区", "english": "special area", "type": "短语", "keyWords": ["special"] },
    { "chinese": "专列", "english": "special train", "type": "短语", "keyWords": ["special"] },
    { "chinese": "她女儿特地来探望", "english": "a special visit from her daughter", "type": "短语", "keyWords": ["special"] },
    { "chinese": "我个人专用的椅子", "english": "my own special chair", "type": "短语", "keyWords": ["special"] },
    { "chinese": "计算机的专有特性", "english": "the special features of a computer", "type": "短语", "keyWords": ["special"] },
    { "chinese": "adj.特殊的；专门的；专科的(in)", "english": "specialized /'speʃəlaɪzd/", "type": "单词", "keyWords": [] },
    { "chinese": "专攻(in)（近major, expert, be experienced in）", "english": "specialize in", "type": "短语", "keyWords": ["specialized"] },
    { "chinese": "专门机构，专业机构", "english": "specialized agencies", "type": "短语", "keyWords": ["specialized"] },
    { "chinese": "本公司是专业生产各类织物的厂家。", "english": "Our company is specialized in all kinds of fabrics.", "type": "句子", "keyWords": ["specialized"] },
    { "chinese": "她专门从事室内设计。", "english": "She specializes in interior design.", "type": "句子", "keyWords": ["specialized"] },
    { "chinese": "n.[C]（单复同）种类；物种（类似means, series）", "english": "species /'spi:ʃi:z/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.明确的；详细而精确的；特定的；具体的", "english": "specific /spə'sɪfɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "明确的到货时间", "english": "specific time of arrival", "type": "短语", "keyWords": ["specific"] },
    { "chinese": "明确指令，详细指导", "english": "specific instructions", "type": "短语", "keyWords": ["specific"] },
    { "chinese": "n.[C]（比赛等的）观众；旁观者", "english": "spectator /spek'teɪtə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]讲话 n.[C]演讲", "english": "speech /spi:tʃ/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.一时说不出话的", "english": "speechless", "type": "单词", "keyWords": ["speech"] },
    { "chinese": "发表演说", "english": "deliver/ make/ give a speech", "type": "短语", "keyWords": ["speech"] },
    { "chinese": "n.[C][U]速度 adj.快的，迅速的", "english": "speed /spi:d/", "type": "单词", "keyWords": [] },
    { "chinese": "快速地，迅速地", "english": "at high/ full top speed= with great/ all speed", "type": "短语", "keyWords": ["speed"] },
    { "chinese": "以…的速度", "english": "at the speed of...", "type": "短语", "keyWords": ["speed"] },
    { "chinese": "（使）加快速度（近pick up speed）", "english": "speed(...) up", "type": "短语", "keyWords": ["speed"] },
    { "chinese": "v.写；用字母拼 vi.拼写", "english": "spell /spel/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]拼写 n.[C]拼法", "english": "spelling", "type": "单词", "keyWords": ["spell"] },
    { "chinese": "v.花（钱）；花费；度过，花（时间等）", "english": "spend /spend/", "type": "单词", "keyWords": [] },
    { "chinese": "在作业上花很多时间", "english": "spend a lot of time on his homework", "type": "短语", "keyWords": ["spend"] },
    { "chinese": "花很多时间做家庭作业", "english": "spend a lot of time (in) doing his homework", "type": "短语", "keyWords": ["spend"] },
    { "chinese": "n.[C]蜘蛛", "english": "spider /'spaɪdə/", "type": "单词", "keyWords": [] },
    { "chinese": "v.（使）溢出；（使）泼出；（使）洒落", "english": "spill /spɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "溢出", "english": "spill over", "type": "短语", "keyWords": ["spill"] },
    { "chinese": "v.纺；（蜘蛛）结网；编造（故事等）；旋转", "english": "spin /spɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "纺棉线", "english": "spin cotton into thread", "type": "短语", "keyWords": ["spin"] },
    { "chinese": "结网", "english": "spin webs", "type": "短语", "keyWords": ["spin"] },
    { "chinese": "旋转盘", "english": "a spinning disk", "type": "短语", "keyWords": ["spin"] },
    { "chinese": "n.[U]精神 n.[C]灵魂，精灵；(pl.)情绪；心境；活力；勇气", "english": "spirit /'spɪrɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.精神的，灵魂的", "english": "spiritual", "type": "单词", "keyWords": ["spirit"] },
    { "chinese": "在精神上", "english": "in spirit", "type": "短语", "keyWords": ["spirit"] },
    { "chinese": "精神生活", "english": "spiritual life", "type": "短语", "keyWords": ["spirit"] },
    { "chinese": "他是天国的精灵之一。", "english": "He was one of the spirits in heaven.", "type": "句子", "keyWords": ["spirit"] },
    { "chinese": "情绪极佳/心情不好", "english": "in high/ great/ low/ poor spirits", "type": "短语", "keyWords": ["spirit"] },
    { "chinese": "v.吐痰，吐唾液 v.吐出（唾液等） n.[U]唾液，唾沫", "english": "spit /spɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "吐出；厉声说出", "english": "spit...out", "type": "短语", "keyWords": ["spit"] },
    { "chinese": "突然口出恶语", "english": "spit out an insult", "type": "短语", "keyWords": ["spit"] },
    { "chinese": "n.[U]怨恨", "english": "spite /spaɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "不顾；不管（近despite）", "english": "in spite of", "type": "短语", "keyWords": ["spite"] },
    { "chinese": "尽管，虽然（比较Although...）", "english": "In spite of the fact that...", "type": "短语", "keyWords": ["spite"] },
    { "chinese": "adj.光彩的；壮丽的，辉煌的；[口]极好的", "english": "splendid /'splendɪd/", "type": "单词", "keyWords": [] },
    { "chinese": "v.劈开；切开；使破裂 vi.被劈开；裂开 n.[C]/a.裂开（的）", "english": "split /splɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "v.损坏；糟蹋；宠坏 vi.（食物）变质（辨析见damage）", "english": "spoil /spɔɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "破坏聚会/糟蹋假日/宠坏孩子", "english": "spoil a party/ holiday/ child", "type": "短语", "keyWords": ["spoil"] },
    { "chinese": "惜了棍棒害了儿。/孩子不打不成器。", "english": "Spare the rod and spoil the child.", "type": "句子", "keyWords": ["spoil"] },
    { "chinese": "adj.口头的；口语的", "english": "spoken /'spəʊkən/", "type": "单词", "keyWords": [] },
    { "chinese": "v.主办；资助 n.[C]发起人；主办者；赞助者", "english": "sponsor /'spɒnsə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]匙，调羹", "english": "spoon /spu:n/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]一满匙", "english": "spoonful", "type": "单词", "keyWords": ["spoon"] },
    { "chinese": "n.[U]游戏；娱乐 n.[C]运动", "english": "sport /spɔ:t/", "type": "单词", "keyWords": [] },
    { "chinese": "田赛", "english": "field sports", "type": "短语", "keyWords": ["sport"] },
    { "chinese": "个人运动", "english": "individual sports", "type": "短语", "keyWords": ["sport"] },
    { "chinese": "团体运动", "english": "team sports", "type": "短语", "keyWords": ["sport"] },
    { "chinese": "运动设备", "english": "sports equipment", "type": "短语", "keyWords": ["sport"] },
    { "chinese": "n.[C]运动员", "english": "sportsman /'spɔ:tsmən/", "type": "单词", "keyWords": ["sport"] },
    { "chinese": "n.[U]运动员精神；运动员品格", "english": "sportsmanship /'spɔ:tsmənʃɪp/", "type": "单词", "keyWords": ["sport"] },
    { "chinese": "n.[C]点；地点，场所；斑点；污渍 v.认出，发现（辨析见see）；玷污", "english": "spot /spɒt/", "type": "单词", "keyWords": [] },
    { "chinese": "污斑", "english": "a dirty spot", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "在/到现场", "english": "on the spot/ scene", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "风景胜地", "english": "a scenic spot", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "古迹", "english": "a historic spot", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "在人群中认出一个朋友", "english": "spot a friend in the crowd", "type": "短语", "keyWords": ["spot"] },
    { "chinese": "n.[C]配偶（指夫或妻）", "english": "spouse /spaʊs/", "type": "单词", "keyWords": [] },
    { "chinese": "v.喷酒；喷溅", "english": "spray /spreɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "v.伸展；传开；蔓延；涂，抹；铺开", "english": "spread /spred/", "type": "单词", "keyWords": [] },
    { "chinese": "传播消息/疾病/知识", "english": "spread news/ disease/ knowledge", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "在面包上涂黄油", "english": "spread butter on the bread= spread the bread with butter", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "像野火一样迅速蔓延/传播", "english": "spread like wildfire", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "摊开地图", "english": "spread out a map", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "教育的普及", "english": "the spread of education", "type": "短语", "keyWords": ["spread"] },
    { "chinese": "n.[C][U]春天，春季 n.[C]泉；弹簧 n.[U]弹性 vi.跃；涌现", "english": "spring /sprɪŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "跳板", "english": "spring board", "type": "短语", "keyWords": ["spring"] },
    { "chinese": "温泉", "english": "a hot spring", "type": "短语", "keyWords": ["spring"] },
    { "chinese": "他一跃而起。", "english": "He sprang to his feet.", "type": "句子", "keyWords": ["spring"] },
    { "chinese": "新兴商业迅速涌现。", "english": "New businesses were springing up rapidly.", "type": "句子", "keyWords": ["spring"] },
    { "chinese": "n.[C]间谍；密探；暗中监视者 v.当间谍；暗中监视(on)", "english": "spy /spaɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "暗中监视某人", "english": "spy on/upon sb.", "type": "短语", "keyWords": ["spy"] },
    { "chinese": "窥探别人的事务", "english": "spy into other people's activities", "type": "短语", "keyWords": ["spy"] },
    { "chinese": "n.[C]正方形；方形物；广场；平方 a.方的；平方的", "english": "square /skweə/", "type": "单词", "keyWords": [] },
    { "chinese": "3平方米", "english": "3 square meters", "type": "短语", "keyWords": ["square"] },
    { "chinese": "5米见方。", "english": "It's 5m square.", "type": "句子", "keyWords": ["square"] },
    { "chinese": "v.榨取；挤取；挤压 vi.挤", "english": "squeeze /skwi:z/", "type": "单词", "keyWords": [] },
    { "chinese": "adj.稳定的，稳固的 *stabilize v.使稳定 *stability n.[U]稳定性", "english": "stable /'steɪbl/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl.stadiums或stadia)(设有看台的)露天体育场", "english": "stadium /'steɪdiəm/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]全体职员；全体雇员(用作单或复) v.为……配备职员；担任……的职员", "english": "staff /stɑ:f/", "type": "单词", "keyWords": [] },
    { "chinese": "是在职，在编", "english": "be on the staff", "type": "短语", "keyWords": ["staff"] },
    { "chinese": "全体职员是……", "english": "The staff is/ are...", "type": "句子", "keyWords": ["staff"] },
    { "chinese": "n.[C]舞台；发展阶段，发展时期；(火箭的)级", "english": "stage /steɪdʒ/", "type": "单词", "keyWords": [] },
    { "chinese": "当演员", "english": "go/ be on the stage", "type": "短语", "keyWords": ["stage"] },
    { "chinese": "舞台效果", "english": "stage effect", "type": "短语", "keyWords": ["stage"] },
    { "chinese": "三级火箭 目前；眼下(近at present)", "english": "*a three-stage rocket at this stage", "type": "短语", "keyWords": ["stage"] },
    { "chinese": "n.[C]楼梯；梯级 *staircase n.[C]楼梯(间)", "english": "stair /steə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]货摊，摊位；书亭(近stand)", "english": "stall /stɔ:l/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]邮票；印，图章 v.盖印于……(近seal)；贴邮票于；跺脚；踩踏", "english": "stamp /stæmp/", "type": "单词", "keyWords": [] },
    { "chinese": "v.站，立；起立；保持不动；处于某种状态/境地 v.使站立；竖放；忍受 n.[C]站立；停留；售货处；摊位(尤指报摊)；(常用pl.)看台", "english": "stand /stænd/", "type": "单词", "keyWords": [] },
    { "chinese": "靠自己", "english": "stand on one's own", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "站住，不许动！", "english": "Stand still!", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "倒立", "english": "stand on one's head/ hands", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "代表，象征", "english": "stand for", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "站着不动", "english": "stand still/firm", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "站起来", "english": "stand up", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "使某人毛发悚然", "english": "make sb.'s hair stand on end", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "站在一边；袖手旁观；支持，忠于", "english": "stand by", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "作某人的后盾", "english": "stand behind sb.(=support sb./back sb.up)", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "(在天空的映衬下显得)突出；出色", "english": "stand out (against the sky)", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "使孩子站立/倒立", "english": "stand the child on his feet/his head", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "忍受(某人做)某事", "english": "stand/ bear/ endure (one's) doing sth.", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "再等下去我可受不了啦。", "english": "I cannot stand waiting any longer.", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "我对此事的立场与三年前无异。", "english": "*My stand on this is just the same as it was three years ago.", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "某物或某人六英尺高。", "english": "*Sth./Sb. stands six feet tall", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "按照现在情况，事实是这样", "english": "*as it stands", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "常委", "english": "*standing committee", "type": "短语", "keyWords": ["stand"] },
    { "chinese": "实际情况就那样。", "english": "*That's how matters stand.", "type": "句子", "keyWords": ["stand"] },
    { "chinese": "n.[C]标准；水平；规范；准则 a.标准的", "english": "standard /'stændəd/", "type": "单词", "keyWords": [] },
    { "chinese": "生活水平", "english": "the standard of living", "type": "短语", "keyWords": ["standard"] },
    { "chinese": "普通话", "english": "standard Chinese", "type": "短语", "keyWords": ["standard"] },
    { "chinese": "n.[C]星星；明星；主角；星号，星形物 v.使担任主角；使成为明星；用星号/星形物标出 vi.当明星；主演", "english": "star /stɑ:/", "type": "单词", "keyWords": [] },
    { "chinese": "他曾主演过许多部影片。", "english": "He has starred in many pictures.", "type": "句子", "keyWords": ["star"] },
    { "chinese": "他将主演一部新片。", "english": "He is to be starred in a new film.", "type": "句子", "keyWords": ["star"] },
    { "chinese": "我已把该读的重要文章都打上了星号。", "english": "I have starred the important articles to read.", "type": "句子", "keyWords": ["star"] },
    { "chinese": "vi./n.[C]凝视，注视(at) *vt.凝视，注视", "english": "stare /steə/", "type": "单词", "keyWords": [] },
    { "chinese": "凝视远方", "english": "stare into the distance", "type": "短语", "keyWords": ["stare"] },
    { "chinese": "盯着某人的眼睛", "english": "*stare sb. in the eyes", "type": "短语", "keyWords": ["stare"] },
    { "chinese": "冷冷地盯着", "english": "look at sb. with a cold stare = stare at sb. coldly", "type": "短语", "keyWords": ["stare"] },
    { "chinese": "v.出发，开始；(机器等)发动；惊起 v.发动(机器等)；开始；使开始；惊动；使吓一跳 n.[C]惊跳；出发；开始", "english": "start /stɑ:t/", "type": "单词", "keyWords": [] },
    { "chinese": "开始明白/意识到", "english": "start to see/ realize", "type": "短语", "keyWords": ["start"] },
    { "chinese": "创业/点火/发动汽车/发动战争", "english": "start a business/ a fire/ a car/ a war", "type": "短语", "keyWords": ["start"] },
    { "chinese": "起程旅行", "english": "start on a journey", "type": "短语", "keyWords": ["start"] },
    { "chinese": "以……开始", "english": "start with", "type": "短语", "keyWords": ["start"] },
    { "chinese": "知识始于实践。", "english": "Knowledge starts with practice.", "type": "句子", "keyWords": ["start"] },
    { "chinese": "烟呛得他咳嗽。", "english": "*Smoke started him coughing.", "type": "句子", "keyWords": ["start"] },
    { "chinese": "他被那响亮的吵闹声吓了一跳。", "english": "He started at the loud noise.", "type": "句子", "keyWords": ["start"] },
    { "chinese": "引擎发动不起来。", "english": "The engine won't start.", "type": "句子", "keyWords": ["start"] },
    { "chinese": "得到一个好机会而开始自己的事业", "english": "get a good start in life", "type": "短语", "keyWords": ["start"] },
    { "chinese": "提供某人开始自立的机会", "english": "give sb. a start in life", "type": "短语", "keyWords": ["start"] },
    { "chinese": "早点动身", "english": "make an early start", "type": "短语", "keyWords": ["start"] },
    { "chinese": "突然惊醒", "english": "awake with a start", "type": "短语", "keyWords": ["start"] },
    { "chinese": "n.[U]饥饿；饿死", "english": "starvation /stɑ:'veɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "vi.挨饿；饿死 v.使挨饿；使饿死", "english": "starve /stɑ:v/", "type": "单词", "keyWords": [] },
    { "chinese": "他饿死了。", "english": "He (was) starved to death.", "type": "句子", "keyWords": ["starve"] },
    { "chinese": "我要饿死了！", "english": "I'm starving!", "type": "句子", "keyWords": ["starve"] },
    { "chinese": "渴望得到某物", "english": "starve for sth.", "type": "短语", "keyWords": ["starve"] },
    { "chinese": "孩子渴望得到疼爱。", "english": "Children starve for affection.", "type": "句子", "keyWords": ["starve"] },
    { "chinese": "使某人饿得非做某事不可", "english": "starve sb. into (doing) sth.", "type": "短语", "keyWords": ["starve"] },
    { "chinese": "n.[C]国家；(美国的)州，邦；状态 v.陈述；声明", "english": "state /steɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "处于混乱的状况", "english": "in a state of confusion", "type": "短语", "keyWords": ["state"] },
    { "chinese": "心境，心情；思想(精神)状态/事态", "english": "the state of mind/affairs", "type": "短语", "keyWords": ["state"] },
    { "chinese": "如上所述", "english": "as stated above", "type": "短语", "keyWords": ["state"] },
    { "chinese": "事实", "english": "the stated facts", "type": "短语", "keyWords": ["state"] },
    { "chinese": "n.[C]陈述；声明", "english": "statement /'steɪtmənt/", "type": "单词", "keyWords": [] },
    { "chinese": "作出陈述；发表声明", "english": "make/ issue a statement", "type": "短语", "keyWords": ["statement"] },
    { "chinese": "n.[C]车站 *vt.安置；派驻；驻扎", "english": "station /'steɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "把士兵们驻扎在柏林", "english": "*station the soldiers at Berlin", "type": "短语", "keyWords": ["station"] },
    { "chinese": "n.[U]文具", "english": "stationery /'steɪʃənri/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]雕像；塑像", "english": "statue /'stætʃu:/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]身份；地位；情形；状态，状况", "english": "status /'steɪtəs/", "type": "单词", "keyWords": [] },
    { "chinese": "社会地位", "english": "social status", "type": "短语", "keyWords": ["status"] },
    { "chinese": "vi.停留，暂住；保持，继续是 n.[C]逗留，停留；逗留时间", "english": "stay /steɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "保持单身，不结婚", "english": "stay single", "type": "短语", "keyWords": ["stay"] },
    { "chinese": "呆在外面，不在家", "english": "stay out", "type": "短语", "keyWords": ["stay"] },
    { "chinese": "留下来(近be left behind)", "english": "stay behind", "type": "短语", "keyWords": ["stay"] },
    { "chinese": "你为什么不上学？", "english": "Why did you stay away from school?", "type": "句子", "keyWords": ["stay"] },
    { "chinese": "不睡觉，熬夜(近sit up)；没倒塌", "english": "stay up", "type": "短语", "keyWords": ["stay"] },
    { "chinese": "洪水过后，房屋仍在。", "english": "The house stayed up even after the flood.", "type": "句子", "keyWords": ["stay"] },
    { "chinese": "adj.稳的，稳定的(反unsteady/unstable)", "english": "steady /'stedi/", "type": "单词", "keyWords": [] },
    { "chinese": "稳如磐石", "english": "as steady as a rock", "type": "短语", "keyWords": ["steady"] },
    { "chinese": "踏实的人", "english": "a steady man", "type": "短语", "keyWords": ["steady"] },
    { "chinese": "n.[U]牛排；猪排", "english": "steak /steɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "v.偷，偷窃；剽窃 vi.偷偷地溜", "english": "steal /sti:l/", "type": "单词", "keyWords": [] },
    { "chinese": "溜入房间", "english": "steal into her room", "type": "短语", "keyWords": ["steal"] },
    { "chinese": "偷看一眼", "english": "steal a glance at...", "type": "短语", "keyWords": ["steal"] },
    { "chinese": "从…偷东西", "english": "steal sth. from sb./ sth.", "type": "短语", "keyWords": ["steal"] },
    { "chinese": "n.[U]水蒸气；水汽 vi.冒热气 v.蒸", "english": "steam /sti:m/", "type": "单词", "keyWords": [] },
    { "chinese": "馒头", "english": "steamed bread", "type": "短语", "keyWords": ["steam"] },
    { "chinese": "蒸汽机", "english": "steam engine", "type": "短语", "keyWords": ["steam"] },
    { "chinese": "蒸汽带动的", "english": "steam-driven", "type": "短语", "keyWords": ["steam"] },
    { "chinese": "n.[C]汽船", "english": "steamship /'sti:mʃɪp/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]钢", "english": "steel /sti:l/", "type": "单词", "keyWords": [] },
    { "chinese": "炼钢工人", "english": "steelworker", "type": "单词", "keyWords": ["steel"] },
    { "chinese": "钢珠", "english": "steel ball", "type": "短语", "keyWords": ["steel"] },
    { "chinese": "adj.陡峭的，险峻的", "english": "steep /sti:p/", "type": "单词", "keyWords": [] },
    { "chinese": "v.为(船舶)操舵；驾驶(车、船、飞机等)；指导；引导", "english": "steer /stɪə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]茎；干 vi.起源于；基于，由…造成(from)", "english": "stem /stem/", "type": "单词", "keyWords": [] },
    { "chinese": "如果让其自然生长，主干会长到12英尺左右。", "english": "The main stem will extend to around 12 feet if left to grow naturally.", "type": "句子", "keyWords": ["stem"] },
    { "chinese": "北欧渐进的农业革命源于人口增长时期对粮食供应的担忧。", "english": "A gradual agricultural revolution in northern Europe stemmed from concerns over food supplies at a time of rising populations.", "type": "句子", "keyWords": ["stem"] },
    { "chinese": "n.[C](脚)步(声)；台阶；步骤；措施 vi.跨步；踩；行走", "english": "step /step/", "type": "单词", "keyWords": [] },
    { "chinese": "与…步调一致/不一致", "english": "in/ out of step with", "type": "短语", "keyWords": ["step"] },
    { "chinese": "与…步调一致", "english": "keep step with...= keep pace with...", "type": "短语", "keyWords": ["step"] },
    { "chinese": "当心脚下；做事谨慎", "english": "mind/watch one's step", "type": "短语", "keyWords": ["step"] },
    { "chinese": "采取措施做某事", "english": "take steps/ measures/ action to do sth.", "type": "短语", "keyWords": ["step"] },
    { "chinese": "逐渐地(近bit by bit, little by little)", "english": "step by step", "type": "短语", "keyWords": ["step"] },
    { "chinese": "走到一旁；避到一旁让给别人；让位", "english": "step aside", "type": "短语", "keyWords": ["step"] },
    { "chinese": "后退，后退一步", "english": "step back", "type": "短语", "keyWords": ["step"] },
    { "chinese": "进入新阶段", "english": "step into a new stage", "type": "短语", "keyWords": ["step"] },
    { "chinese": "万事开头难。", "english": "It is the first step that costs.", "type": "句子", "keyWords": ["step"] },
    { "chinese": "n.[C]棍，棒；枝条，柴枝；手杖 vi.坚持；被刺入；被粘贴 vt.刺；粘贴 *sticky a.粘的，粘性的", "english": "stick /stɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "把手伸进口袋", "english": "stick his hands in his pocket", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "将叉刺进鱼里", "english": "stick the fork into the fish", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "陷在雪里/卡在喉咙里", "english": "be/get stuck in the snow/ throat", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "坚持基本原则(近keep to, hold out, persist in, persevere in, insist on, adhere to, cling to)", "english": "stick to basic principles", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "(使)突出，(使)伸出", "english": "stick(...) out", "type": "短语", "keyWords": ["stick"] },
    { "chinese": "ad.还；仍旧；更(接比较级) a.静止的；寂静的(辨析见quiet)", "english": "still /stɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "v.激励；刺激 *stimulation n.[U] stimulus /'stɪmjʊləs/(pl. stimuli /'stɪmjʊlaɪ/)n.[C]刺激(物)，促进(因素)", "english": "stimulate /'stɪmjuleɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "激励某人作更大的努力", "english": "stimulate sb. into greater effort= stimulate sb. to make greater efforts", "type": "短语", "keyWords": ["stimulate"] },
    { "chinese": "v.搅动，搅拌；使…激动；使…不安；激发 n.[C](用单数)微动；惊动；轰动；搅动；骚乱", "english": "stir /stɜ:/", "type": "单词", "keyWords": [] },
    { "chinese": "喝汤之前先搅一搅", "english": "stir the soup before tasting it", "type": "短语", "keyWords": ["stir"] },
    { "chinese": "激动人心的演说", "english": "a stirring speech", "type": "短语", "keyWords": ["stir"] },
    { "chinese": "激起某人的想象", "english": "stir one's imagination", "type": "短语", "keyWords": ["stir"] },
    { "chinese": "v.给…备货；储备；供应 n.[C]树，根茎；库存(物)，存货；股票，股份；证券 n.[U](总)牲畜，家畜", "english": "stock /stɒk/", "type": "单词", "keyWords": [] },
    { "chinese": "家畜(总称)", "english": "live stock", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "证券交易所", "english": "stock exchange", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "黄金储备", "english": "the gold stock", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "股票市场", "english": "stock market", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "大批玩具存货", "english": "a large stock of toys", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "股东", "english": "stockholder", "type": "单词", "keyWords": ["stock"] },
    { "chinese": "没有现货，脱销", "english": "out of stock", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "在库存里，备有现货，有现货可卖", "english": "have/keep in stock", "type": "短语", "keyWords": ["stock"] },
    { "chinese": "他的头脑里主意很多。", "english": "His head is well stocked with ideas.", "type": "句子", "keyWords": ["stock"] },
    { "chinese": "n.[C]长筒袜", "english": "stocking /'stɒkɪŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl. stomachs)胃；腹部", "english": "stomach /'stʌmək/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]胃痛，肚子痛", "english": "stomachache", "type": "单词", "keyWords": ["stomach"] },
    { "chinese": "n.[U]石(料)；石头 n.[C]石块；石子；宝石", "english": "stone /stəʊn/", "type": "单词", "keyWords": [] },
    { "chinese": "宝石", "english": "a precious stone", "type": "短语", "keyWords": ["stone"] },
    { "chinese": "一箭之遥，在附近", "english": "within a stone's throw", "type": "短语", "keyWords": ["stone"] },
    { "chinese": "垫脚石；跳板；进身之阶", "english": "a stepping stone", "type": "短语", "keyWords": ["stone"] },
    { "chinese": "一石二鸟。", "english": "Kill two birds with one stone.", "type": "句子", "keyWords": ["stone"] },
    { "chinese": "滚石不生苔，转行不成材。", "english": "A rolling stone gathers no moss.", "type": "句子", "keyWords": ["stone"] },
    { "chinese": "v.堵塞；阻塞；停止，停下；停留；阻止；拦截 n.[C]停车站；停止", "english": "stop /stɒp/", "type": "单词", "keyWords": [] },
    { "chinese": "用一块布堵住漏洞", "english": "stop a leak with a piece of cloth", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "阻止某人做某事(近prevent, ban, prohibit, hold back, keep...from, forbid sb. to do sth.)", "english": "stop sb. (from) doing sth.", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "停止做某事", "english": "stop/cease doing sth.= cease to do sth.", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "停下来(原来在做的事)而去做某事", "english": "stop to do sth.", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "停止(近come to an end)", "english": "come to a stop", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "使…停止(近put an end to sth.)", "english": "bring sth. to a stop", "type": "短语", "keyWords": ["stop"] },
    { "chinese": "v.贮存，贮藏 n.[C]贮存，贮藏；(美)店 n.[U]贮存，贮藏", "english": "store /stɔ:/", "type": "单词", "keyWords": [] },
    { "chinese": "贮存，贮藏某物(近reserve, stock)", "english": "keep/have sth. in store", "type": "短语", "keyWords": ["store"] },
    { "chinese": "n.[C]零售商；零售店店主", "english": "storekeeper /'stɔ:ki:pə/", "type": "单词", "keyWords": ["store"] },
    { "chinese": "n. [C]楼层；层[美]story", "english": "storey /'stɔːri/", "type": "单词", "keyWords": [] },
    { "chinese": "一幢十层的楼房", "english": "a 10-storeyed/10-storied building", "type": "短语", "keyWords": ["storey"] },
    { "chinese": "n. [C]暴(风)雨；暴(风)雪 vi. 起风暴；暴怒，猛冲；猛攻 vt. 强击；猛攻；猛烈抨击", "english": "storm /stɔːm/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]故事；小说(尤指短篇小说)；(对所发生的事的)叙述，真情，详情；楼层", "english": "story /'stɔːri/", "type": "单词", "keyWords": [] },
    { "chinese": "讲自己的身世/经历", "english": "tell one's story", "type": "短语", "keyWords": ["story"] },
    { "chinese": "虚构，捏造", "english": "make up a story", "type": "短语", "keyWords": ["story"] },
    { "chinese": "告诉某人详情/始末", "english": "tell sb. the whole story", "type": "短语", "keyWords": ["story"] },
    { "chinese": "在这名称背后还有一个美丽的故事呢。", "english": "There is a beautiful story behind this name.", "type": "句子", "keyWords": ["story"] },
    { "chinese": "据说", "english": "As the story goes,...; The story goes/runs that...", "type": "短语", "keyWords": ["story"] },
    { "chinese": "n. [C]讲故事者", "english": "storyteller /'stɔːritelə/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]炉子；火炉", "english": "stove /stəʊv/", "type": "单词", "keyWords": [] },
    { "chinese": "a. (笔)直的；正直的；直率的 ad. (不用straightly)直地；直接地；直率地；立刻，马上", "english": "straight /streɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "立即，马上", "english": "straight away", "type": "短语", "keyWords": ["straight"] },
    { "chinese": "笔直向前走", "english": "go straight ahead", "type": "短语", "keyWords": ["straight"] },
    { "chinese": "率直的解释", "english": "a straightforward explanation", "type": "短语", "keyWords": ["straight"] },
    { "chinese": "vt. 使搁浅；使处于困境 *vi. 搁浅；处于困境", "english": "strand /strænd/", "type": "单词", "keyWords": [] },
    { "chinese": "被困于(近be trapped in, be stuck in)", "english": "be stranded in...", "type": "短语", "keyWords": ["strand"] },
    { "chinese": "a. 怪的；陌生的(辨析见odd)", "english": "strange /streɪndʒ/", "type": "单词", "keyWords": [] },
    { "chinese": "觉得不太舒服；感到很不自在", "english": "feel strange", "type": "短语", "keyWords": ["strange"] },
    { "chinese": "很奇怪……竟然……(虚拟语气)", "english": "It is strange that...should...", "type": "句子", "keyWords": ["strange"] },
    { "chinese": "n. [C]陌生人；异乡人；新来者；门外汉", "english": "stranger /'streɪndʒə/", "type": "单词", "keyWords": [] },
    { "chinese": "他不懂拉丁文。", "english": "He is a stranger to Latin.", "type": "句子", "keyWords": ["stranger"] },
    { "chinese": "n. [U]战略(学) [C][U]策略；计谋；行动计划；对策", "english": "strategy /'strætədʒi/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 战略(上)的", "english": "strategic", "type": "单词", "keyWords": ["strategy"] },
    { "chinese": "n. [U]稻草 n. [C]一根麦秆；(喝饮料用的)麦秆吸管", "english": "straw /strɔː/", "type": "单词", "keyWords": [] },
    { "chinese": "捞救命稻草", "english": "catch/grasp at a straw", "type": "短语", "keyWords": ["straw"] },
    { "chinese": "毫无价值", "english": "not worth a straw", "type": "短语", "keyWords": ["straw"] },
    { "chinese": "最后的一根稻草压断了骆驼的背脊。", "english": "It is the last straw that breaks the camel's back.", "type": "句子", "keyWords": ["straw"] },
    { "chinese": "n. [C]草莓", "english": "strawberry /'strɔːbəri/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]河；溪；一连串；趋势；潮流；数据流 v. 流，淌；涌出/入；[计]流播", "english": "stream /striːm/", "type": "单词", "keyWords": [] },
    { "chinese": "一连串的侮辱", "english": "a stream of insults", "type": "短语", "keyWords": ["stream"] },
    { "chinese": "逆流，违反时势，反潮流", "english": "go against the stream", "type": "短语", "keyWords": ["stream"] },
    { "chinese": "随波逐流，随大流，顺应时势", "english": "go with the stream", "type": "短语", "keyWords": ["stream"] },
    { "chinese": "他们涌出电影院。", "english": "They streamed out of the cinema.", "type": "句子", "keyWords": ["stream"] },
    { "chinese": "n. [C]街；街道", "english": "street /striːt/", "type": "单词", "keyWords": [] },
    { "chinese": "后街；偏僻的街道/巷子", "english": "back street", "type": "短语", "keyWords": ["street"] },
    { "chinese": "住在街对面453号", "english": "live at 453 across the street", "type": "短语", "keyWords": ["street"] },
    { "chinese": "n. [U]力；力量；活力；实力；兵力；强度 n. [C]长处", "english": "strength /streŋθ/", "type": "单词", "keyWords": [] },
    { "chinese": "增强体力/实力", "english": "build up one's strength", "type": "短语", "keyWords": ["strength"] },
    { "chinese": "尽力", "english": "with all one's strength", "type": "短语", "keyWords": ["strength"] },
    { "chinese": "v. 加强；巩固；使坚强 vi. 变强(类似lengthen)", "english": "strengthen /'streŋθən/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]压力；紧张；重音；强调 v. 重读；强调；加压力于；使紧张", "english": "stress /stres/", "type": "单词", "keyWords": [] },
    { "chinese": "在贫困的压力下，迫于贫困", "english": "under the stress/pressure of poverty", "type": "短语", "keyWords": ["stress"] },
    { "chinese": "强调某事(近lay/put/place emphasis on, emphasize, attach importance to)", "english": "lay/pat/place stress on sth.", "type": "短语", "keyWords": ["stress"] },
    { "chinese": "v. 伸展；铺开；舒展 vi. 伸展；被拉长 *n. [C]伸展；连绵", "english": "stretch /stretʃ/", "type": "单词", "keyWords": [] },
    { "chinese": "一片旷野", "english": "a stretch of open country", "type": "短语", "keyWords": ["stretch"] },
    { "chinese": "伸长腿；出去逛逛", "english": "stretch one's legs", "type": "短语", "keyWords": ["stretch"] },
    { "chinese": "a. 严格的；严密的；严谨的；精确的", "english": "strict /strɪkt/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]严格；严密；严谨；精确", "english": "strictness", "type": "单词", "keyWords": ["strict"] },
    { "chinese": "对某人在某方面要求严格", "english": "be strict with sb. in sth.", "type": "短语", "keyWords": ["strict"] },
    { "chinese": "v. 敲；打，击；感动，给人印象(辨析见affect)；*进攻；(生病等不愉快事)发生，侵袭 n. [C]罢工；打击；袭击", "english": "strike /straɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 显著的，惊人的", "english": "striking", "type": "单词", "keyWords": ["strike"] },
    { "chinese": "a. 受打击的；受灾的", "english": "stricken", "type": "单词", "keyWords": ["strike"] },
    { "chinese": "打击致死", "english": "strike...dead", "type": "短语", "keyWords": ["strike"] },
    { "chinese": "划火柴", "english": "strike a match", "type": "短语", "keyWords": ["strike"] },
    { "chinese": "罢工", "english": "be on strike", "type": "短语", "keyWords": ["strike"] },
    { "chinese": "罢工", "english": "go on strike", "type": "短语", "keyWords": ["strike"] },
    { "chinese": "打动某人；迷住某人", "english": "sth. strikes sb.", "type": "短语", "keyWords": ["strike"] },
    { "chinese": "为美景/貌所迷住", "english": "be struck by the beauty", "type": "短语", "keyWords": ["strike"] },
    { "chinese": "鲜明的对照", "english": "a striking contrast", "type": "短语", "keyWords": ["strike"] },
    { "chinese": "灾区", "english": "a stricken area", "type": "短语", "keyWords": ["strike"] },
    { "chinese": "愁苦的脸", "english": "a stricken face", "type": "短语", "keyWords": ["strike"] },
    { "chinese": "趁热打铁。", "english": "Strike while the iron is hot.", "type": "句子", "keyWords": ["strike"] },
    { "chinese": "钟点响了。", "english": "The hour has struck.", "type": "句子", "keyWords": ["strike"] },
    { "chinese": "他们将在拂晓时进攻。", "english": "They will strike at dawn.", "type": "句子", "keyWords": ["strike"] },
    { "chinese": "钟敲九点。(不用hit, knock, beat等)", "english": "The clock struck nine.", "type": "句子", "keyWords": ["strike"] },
    { "chinese": "我忽然想出一个好主意。(近A good idea suddenly occurred to me.)", "english": "A good idea suddenly struck me.", "type": "句子", "keyWords": ["strike"] },
    { "chinese": "你认为这计划怎么样？", "english": "How does the plan strike you?", "type": "句子", "keyWords": ["strike"] },
    { "chinese": "我感觉她是个聪明的女孩。", "english": "She struck me as (a) clever (girl).", "type": "句子", "keyWords": ["strike"] },
    { "chinese": '辨析：hit, beat, knock, strike hit表示“有目标地打”，着重“打击”某一点，击中，如：He hit him on the face. beat表示“连续地打或拍”，有“殴打、击败”之意，如：That man was beaten until he was black and blue. 另外，beat还可表示心脏或脉搏等“跳动”。knock表示“敲、打、撞击”之意，常与at/on连用，如：Who is knocking at/on the door? strike表示用手或器械突然地、多为一次性地“打、击”，如：She was struck dead by lightning.", "english": "辨析:hit, beat, knock, strike hit表示"有目标地打",着重"打击"某一点,击中,如:He hit him on the face. beat表示"连续地打或拍",有"殴打、击败"之意,如:That man was beaten unti he was black and blue.另外,beat还可表示心脏或脉搏等"跳动"。knock表示"敲、打、撞击"之意,常与at/on连用,如:Who is knocking at/ on the doo? strike表示用手或器械突然地、多为一次性地"打、击",如:She was struck dead by lightning.', "type": "句子", "keyWords": ["strike"] },
    { "chinese": "n. [C][U]细绳；(一)串", "english": "string /strɪŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]条；带状物 v. 剪(或撕)成条状", "english": "strip /strɪp/", "type": "单词", "keyWords": [] },
    { "chinese": "金属条", "english": "metal strip", "type": "短语", "keyWords": ["strip"] },
    { "chinese": "v. 努力，奋斗，力争，力求(用法类似：hope, wish, long, be eager, have a desire)", "english": "strive /straɪv/", "type": "单词", "keyWords": [] },
    { "chinese": "争取某物", "english": "strive for sth.", "type": "短语", "keyWords": ["strive"] },
    { "chinese": "拼搏做某事", "english": "strive to do sth.", "type": "短语", "keyWords": ["strive"] },
    { "chinese": "a. 强壮的；强烈的；有力的；坚决的", "english": "strong /strɒŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 强壮地；强烈地；有力地；坚决地", "english": "strongly", "type": "单词", "keyWords": ["strong"] },
    { "chinese": "n. [C][U]结构；构造 n. [C]建筑物 v. 建造；构成；建立；组织", "english": "structure /'strʌktʃə/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]/vi. 斗争，奋斗；挣扎；艰难地行进；努力", "english": "struggle /'strʌɡl/", "type": "单词", "keyWords": [] },
    { "chinese": "争夺权力/为生活而挣扎", "english": "struggle for power/ a living", "type": "短语", "keyWords": ["struggle"] },
    { "chinese": "挣扎着站起来", "english": "struggle to one's feet", "type": "短语", "keyWords": ["struggle"] },
    { "chinese": "冒着暴风雪前进", "english": "struggle through the snowstorm", "type": "短语", "keyWords": ["struggle"] },
    { "chinese": "为独立而斗争是长期而艰苦的。", "english": "The struggle for independence was long and hard.", "type": "句子", "keyWords": ["struggle"] },
    { "chinese": "你死我活的斗争", "english": "a life-and-death struggle", "type": "短语", "keyWords": ["struggle"] },
    { "chinese": "n. [C]学生", "english": "student /'stjuːdnt/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](画家等的)工作室；电影制片厂；(电台等的)播音室，演播室", "english": "studio /'stjuːdiəʊ/", "type": "单词", "keyWords": [] },
    { "chinese": "美术工作室", "english": "art studio", "type": "短语", "keyWords": ["studio"] },
    { "chinese": "新闻演播室", "english": "news studio", "type": "短语", "keyWords": ["studio"] },
    { "chinese": "n. [C][U]学习；研究 [C]攻读；探讨；学科；课题；书房 vi. 学习 v. 学习；研究；攻读；仔细看，打量", "english": "study /'stʌdi/", "type": "单词", "keyWords": [] },
    { "chinese": "研究", "english": "make a study of", "type": "短语", "keyWords": ["study"] },
    { "chinese": "她饶有兴趣地打量着他的面孔。", "english": "She studied his face with interest.", "type": "句子", "keyWords": ["study"] },
    { "chinese": "n. 原料；材料；素材资料；物品 v. 使塞满，填满", "english": "stuff /stʌf/", "type": "单词", "keyWords": [] },
    { "chinese": "食品", "english": "food stuff", "type": "短语", "keyWords": ["stuff"] },
    { "chinese": "石料", "english": "stone stuff", "type": "短语", "keyWords": ["stuff"] },
    { "chinese": "所有没用的物品都应该扔掉。", "english": "All the unwanted stuff should be got rid of.", "type": "句子", "keyWords": ["stuff"] },
    { "chinese": "把袋子装满东西", "english": "stuff a bag with things", "type": "短语", "keyWords": ["stuff"] },
    { "chinese": "满脑子塞满…", "english": "stuff one's head with...", "type": "短语", "keyWords": ["stuff"] },
    { "chinese": "a. 愚蠢的；迟钝的(辨析见foolish)", "english": "stupid /'stjuːpɪd/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]风格 n. [C]式样；方式", "english": "style /staɪl/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]产品形象设计师", "english": "stylist", "type": "单词", "keyWords": ["style"] },
    { "chinese": "(不)时髦的，(不)时新的(近in/out of fashion)", "english": "in/out of style", "type": "短语", "keyWords": ["style"] },
    { "chinese": "表示“下，在底下，低，次，副；”，例如：subtitle标题，subtropical亚热带的，*subcontinent次大陆", "english": "sub", "type": "单词", "keyWords": [] },
    { "chinese": "a. 潜意识的；意识不清的", "english": "subconscious /ˌsʌb'kɒnʃəs/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]学科；科目；主题；题材；*实验对象 a. 从属的；易受…的；受…支配的(to)", "english": "subject /'sʌbdʒɪkt/", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使服从；使经受；使易受(to)", "english": "subject /səb'dʒekt/", "type": "单词", "keyWords": [] },
    { "chinese": "顺从于；受…支配；易遭(近object to)", "english": "be subject to", "type": "短语", "keyWords": ["subject"] },
    { "chinese": "这个国家的全体公民都必须服从法律。", "english": "All citizens in this nation are subject to the law.", "type": "句子", "keyWords": ["subject"] },
    { "chinese": "价格有可能变动。", "english": "The prices are subject to change.", "type": "句子", "keyWords": ["subject"] },
    { "chinese": "v. 认捐；捐助，赞助；签(名)，署(名) vi. 认捐；捐赠(to)；订阅(报刊等)(for)；认购(for)", "english": "subscribe /səb'skraɪb/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]物质，材料(matter)；[U]* n. [U]实质", "english": "substance /'sʌbstəns/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 实质的；重要的", "english": "substantial /səb'stænʃl/", "type": "单词", "keyWords": ["substance"] },
    { "chinese": "重要的论证", "english": "a substantial argument", "type": "短语", "keyWords": ["substantial"] },
    { "chinese": "实际存在的东西", "english": "substantial things", "type": "短语", "keyWords": ["substantial"] },
    { "chinese": "n. [C]替代人/物；替补队员 v. 代替", "english": "substitute /'sʌbstɪtjuːt/", "type": "单词", "keyWords": [] },
    { "chinese": "用塑料作钢的代用品", "english": "use plastics as a substitute for steel", "type": "短语", "keyWords": ["substitute"] },
    { "chinese": "(用A)替代B", "english": "substitute (A) for B", "type": "短语", "keyWords": ["substitute"] },
    { "chinese": "代替一位教师", "english": "substitute for a teacher", "type": "短语", "keyWords": ["substitute"] },
    { "chinese": "客观审视代替主观经验", "english": "substitute an objective attitude for subjective experience", "type": "短语", "keyWords": ["substitute"] },
    { "chinese": "n. [C]市郊", "english": "suburb /'sʌbɜːb/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 郊区的", "english": "suburban /sə'bɜːbən/", "type": "单词", "keyWords": ["suburb"] },
    { "chinese": "n. [C]地道；地铁", "english": "subway /'sʌbweɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 成功，达到目的(in) vt./vi. 继任；继承", "english": "succeed /sək'siːd/", "type": "单词", "keyWords": [] },
    { "chinese": "做成功某事", "english": "succeed in (doing) sth. = be successful in (doing) sth. = have success in (doing) sth.", "type": "短语", "keyWords": ["succeed"] },
    { "chinese": "他接替约翰任书记。", "english": "He succeeded John as secretary.", "type": "句子", "keyWords": ["succeed"] },
    { "chinese": "他没有儿子继承他。", "english": "He had no son to succeed him.", "type": "句子", "keyWords": ["succeed"] },
    { "chinese": "继承大笔遗产(vi)", "english": "succeed to a fortune", "type": "短语", "keyWords": ["succeed"] },
    { "chinese": "n. [U]成功，成就，胜利 n. [C]成功的人(或事物)", "english": "success /sək'ses/", "type": "单词", "keyWords": [] },
    { "chinese": "胜利属于不屈不挠的人。", "english": "Success belongs to the persevering.", "type": "句子", "keyWords": ["success"] },
    { "chinese": "大会开得很成功。", "english": "The conference was a success.", "type": "句子", "keyWords": ["success"] },
    { "chinese": "多么成功啊！", "english": "What a great success!", "type": "句子", "keyWords": ["success"] },
    { "chinese": "就作州长而言，他不是一个成功者。", "english": "He was not a success as a governor.", "type": "句子", "keyWords": ["success"] },
    { "chinese": "失败是成功之母。", "english": "Failure is the mother of success.", "type": "句子", "keyWords": ["success"] },
    { "chinese": "a. 这样的，如此的 pron. 这样的人或事物", "english": "such /sʌtʃ/", "type": "单词", "keyWords": [] },
    { "chinese": "例如，诸如……之类(比较as such照此，像这样)", "english": "such as", "type": "短语", "keyWords": ["such"] },
    { "chinese": "它们与例如信号之类的能发出警报的东西有关。", "english": "They're relevant to something, such as a signal, that warns.", "type": "句子", "keyWords": ["such"] },
    { "chinese": "这样的士兵值得尊敬。", "english": "Soldiers, as such, deserve respect.", "type": "句子", "keyWords": ["such"] },
    { "chinese": "如……之类的", "english": "such...as...", "type": "短语", "keyWords": ["such"] },
    { "chinese": "我们需要铁、银和金这一类东西。", "english": "We needed such things as iron, silver and gold.", "type": "句子", "keyWords": ["such"] },
    { "chinese": "她吓得昏了过去。", "english": "She had such a fright that she fainted.", "type": "句子", "keyWords": ["such"] },
    { "chinese": "该大学的名望如此之大，以至目前在校的有来自超过100个国家的学生。", "english": "Its reputation is such/ Such is its reputation (倒装) that the current enrollment of the university includes students from over 100 countries.", "type": "句子", "keyWords": ["such"] },
    { "chinese": "我们没有傻到会去相信他的地步。", "english": "We are not such fools as to believe him.", "type": "句子", "keyWords": ["such"] },
    { "chinese": "一件那样的事情/没有那样的事情(注意不和a一起用)", "english": "one/ no such thing", "type": "短语", "keyWords": ["such"] },
    { "chinese": "这样的字典有一本就够了。", "english": "One such dictionary is enough.", "type": "句子", "keyWords": ["such"] },
    { "chinese": "人生不过如此！", "english": "Such is life!", "type": "句子", "keyWords": ["such"] },
    { "chinese": "v. 吸，吮 *n. [U](可与a连用)吸，吮", "english": "suck /sʌk/", "type": "单词", "keyWords": [] },
    { "chinese": "吸一口", "english": "take a suck (at)", "type": "短语", "keyWords": ["suck"] },
    { "chinese": "a. 突然的，意外的", "english": "sudden /'sʌdn/", "type": "单词", "keyWords": [] },
    { "chinese": "附加的载荷", "english": "a sudden load", "type": "短语", "keyWords": ["sudden"] },
    { "chinese": "突然，冷不防", "english": "all of a sudden = suddenly", "type": "短语", "keyWords": ["sudden"] },
    { "chinese": "v. 遭受 vi. 受痛苦；受损；患病(from)", "english": "suffer /'sʌfə/", "type": "单词", "keyWords": [] },
    { "chinese": "受痛苦/批评", "english": "suffer pain/ criticism", "type": "短语", "keyWords": ["suffer"] },
    { "chinese": "遭受水灾", "english": "suffer from floods", "type": "短语", "keyWords": ["suffer"] },
    { "chinese": "饥寒交迫", "english": "suffer cold and hunger", "type": "短语", "keyWords": ["suffer"] },
    { "chinese": "得了麻疹", "english": "suffer from measles", "type": "短语", "keyWords": ["suffer"] },
    { "chinese": "n. [U]受苦，受难 n. [C](pl.)苦难经历 a. 受苦/难的", "english": "suffering /'sʌfərɪŋ/", "type": "单词", "keyWords": ["suffer"] },
    { "chinese": "a. 充足的，足够的(多用于书面语)", "english": "sufficient /sə'fɪʃnt/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]充足；足量 *(反insufficiency)", "english": "sufficiency /sə'fɪʃnsi/", "type": "单词", "keyWords": ["sufficient"] },
    { "chinese": "n. [U]糖 *n. [U]甘蔗", "english": "sugar /'ʃʊɡə/; sugar cane", "type": "单词", "keyWords": [] },
    { "chinese": "v. 建议，推荐；表明，暗示，使人想到", "english": "suggest /sə'dʒest/", "type": "单词", "keyWords": [] },
    { "chinese": "建议(做)某(事)", "english": "suggest (doing) sth. / that...should...", "type": "短语", "keyWords": ["suggest"] },
    { "chinese": "他向我们建议把规程修订一下。", "english": "He suggested to us that the regulations should be revised.", "type": "句子", "keyWords": ["suggest"] },
    { "chinese": "有人建议", "english": "It is suggested/ proposed that...should...", "type": "短语", "keyWords": ["suggest"] },
    { "chinese": "你是在暗示他有罪吗？", "english": "Are you suggesting that he is guilty?", "type": "句子", "keyWords": ["suggest"] },
    { "chinese": "一朵让人想到蘑菇的云", "english": "a cloud that suggests a mushroom", "type": "短语", "keyWords": ["suggest"] },
    { "chinese": "n. [C]建议，提议，意见；暗示", "english": "suggestion /sə'dʒestʃən/", "type": "单词", "keyWords": ["suggest"] },
    { "chinese": "n. [U]自杀，自毁 *n. [C]自杀者", "english": "suicide /'suːɪsaɪd/", "type": "单词", "keyWords": [] },
    { "chinese": "自杀，自尽", "english": "commit suicide", "type": "短语", "keyWords": ["suicide"] },
    { "chinese": "v. 适合(辨析见fit) n. [C](一套)衣服", "english": "suit /suːt/", "type": "单词", "keyWords": [] },
    { "chinese": "潜水服", "english": "a diving suit", "type": "短语", "keyWords": ["suit"] },
    { "chinese": "一套(衣服等)", "english": "a suit of", "type": "短语", "keyWords": ["suit"] },
    { "chinese": "使某物适合某人/物", "english": "suit sth. to sb. / sth.", "type": "短语", "keyWords": ["suit"] },
    { "chinese": "你的笔调应大众化。", "english": "Suit your style of writing to the masses.", "type": "句子", "keyWords": ["suit"] },
    { "chinese": "哪个日期最合适？", "english": "Which date suits (you) best?", "type": "句子", "keyWords": ["suit"] },
    { "chinese": "跟牌；仿效别人", "english": "follow suit", "type": "短语", "keyWords": ["suit"] },
    { "chinese": "a. 适合的，相配的(反unsuitable不适合的)", "english": "suitable /'suːtəbl/", "type": "单词", "keyWords": ["suit"] },
    { "chinese": "适合", "english": "be suitable for", "type": "短语", "keyWords": ["suitable"] },
    { "chinese": "n. [C]手提箱", "english": "suitcase /'suːtkeɪs/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C](金)额；总数；概要，要点 v. 计算……总额；总结，概述", "english": "sum /sʌm/", "type": "单词", "keyWords": [] },
    { "chinese": "长于算术", "english": "be good at sums", "type": "短语", "keyWords": ["sum"] },
    { "chinese": "做算术(题)", "english": "do sums", "type": "短语", "keyWords": ["sum"] },
    { "chinese": "一笔巨款", "english": "a large sum of money", "type": "短语", "keyWords": ["sum"] },
    { "chinese": "总计；概括，总结", "english": "sum up", "type": "短语", "keyWords": ["sum"] },
    { "chinese": "计算某物的总成本费", "english": "sum (up) the costs of sth.", "type": "短语", "keyWords": ["sum"] },
    { "chinese": "v. 概括，总结", "english": "summarize /'sʌməraɪz/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]摘要，概要 a. 概括的，总结性的", "english": "summary /'sʌməri/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]夏季，夏天", "english": "summer /'sʌmə/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]顶点；最高级会议，峰会", "english": "summit /'sʌmɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 召集(会议)；召唤；唤起，振作", "english": "summon /'sʌmən/", "type": "单词", "keyWords": [] },
    { "chinese": "n. (the)太阳(光)", "english": "sun /sʌn/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 阳光充足的；照耀的；快乐的", "english": "sunny", "type": "单词", "keyWords": ["sun"] },
    { "chinese": "在阳光下", "english": "in the sun", "type": "短语", "keyWords": ["sun"] },
    { "chinese": "温和的微笑", "english": "a sunny smile", "type": "短语", "keyWords": ["sunny"] },
    { "chinese": "vi. 沐日光浴", "english": "sunbathe /'sʌnbeɪð/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]星期日", "english": "Sunday /'sʌndeɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "每逢星期日", "english": "on Sundays", "type": "短语", "keyWords": ["Sunday"] },
    { "chinese": "在星期日(夜里)", "english": "on Sunday (night)", "type": "短语", "keyWords": ["Sunday"] },
    { "chinese": "a. 沉没的；凹陷的", "english": "sunken /'sʌŋkən/", "type": "单词", "keyWords": [] },
    { "chinese": "沉船", "english": "a sunken ship", "type": "短语", "keyWords": ["sunken"] },
    { "chinese": "n. [U]日光，阳光", "english": "sunlight /'sʌnlaɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]日出，拂晓", "english": "sunrise /'sʌnraɪz/", "type": "单词", "keyWords": [] },
    { "chinese": "在拂晓", "english": "at sunrise/ dawn", "type": "短语", "keyWords": ["sunrise"] },
    { "chinese": "n. [U]日落", "english": "sunset /'sʌnset/", "type": "单词", "keyWords": [] },
    { "chinese": "在日落时(近at dusk)", "english": "at sunset", "type": "短语", "keyWords": ["sunset"] },
    { "chinese": "n. [U]日光，日照；欢乐，幸福", "english": "sunshine /'sʌnʃaɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 超级的；极好的；特级的", "english": "super /'suːpə/", "type": "单词", "keyWords": [] },
    { "chinese": "超模", "english": "supermodel", "type": "单词", "keyWords": ["super"] },
    { "chinese": "超级大国", "english": "superpower", "type": "单词", "keyWords": ["super"] },
    { "chinese": "巨星", "english": "superstar", "type": "单词", "keyWords": ["super"] },
    { "chinese": "超人", "english": "superman", "type": "单词", "keyWords": ["super"] },
    { "chinese": "超自然的", "english": "supernatural", "type": "单词", "keyWords": ["super"] },
    { "chinese": "超导体", "english": "superconductor", "type": "单词", "keyWords": ["super"] },
    { "chinese": "a. [口]壮丽的；极好的；非常的", "english": "superb /suː'pɜːb/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 优秀的，上级的 n. [C]上级，长官；较好的人/物", "english": "superior /suː'pɪəriə/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]优越性；优等", "english": "superiority /suːˌpɪəri'ɒrəti/", "type": "单词", "keyWords": ["superior"] },
    { "chinese": "（地位）高于；（品质）优于(反be inferior to)", "english": "be superior to...", "type": "短语", "keyWords": ["superior"] },
    { "chinese": "上级法院；高等法院", "english": "a superior court", "type": "短语", "keyWords": ["superior"] },
    { "chinese": "n. [C]超级市场", "english": "supermarket /'suːpəmɑːkɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "v. 监督，管理；指导", "english": "supervise /'suːpəvaɪz/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]监督人，管理人", "english": "supervisor", "type": "单词", "keyWords": ["supervise"] },
    { "chinese": "n. [U]监督，管理；指导", "english": "supervision", "type": "单词", "keyWords": ["supervise"] },
    { "chinese": "监督选举", "english": "supervise an election", "type": "短语", "keyWords": ["supervise"] },
    { "chinese": "受有指导性实践训练", "english": "undergo supervised practical training", "type": "短语", "keyWords": ["supervise"] },
    { "chinese": "这房子是在一位建筑师的细心监督下建造的。", "english": "The house was built under the careful supervision of an architect.", "type": "句子", "keyWords": ["supervision"] },
    { "chinese": "n. [C][U]晚饭", "english": "supper /'sʌpə/", "type": "单词", "keyWords": [] },
    { "chinese": "一顿丰盛的晚饭", "english": "a rich supper", "type": "短语", "keyWords": ["supper"] },
    { "chinese": "n. [U]供应 n. [C]供应物，补给(品) vt. 供给，供应(辨析见afford)", "english": "supply /sə'plaɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "医疗用品", "english": "medical supplies", "type": "短语", "keyWords": ["supply"] },
    { "chinese": "供求", "english": "supply and demand", "type": "短语", "keyWords": ["supply"] },
    { "chinese": "有许多……", "english": "have a good supply of...", "type": "短语", "keyWords": ["supply"] },
    { "chinese": "目前银根吃紧。", "english": "Money is in short supply for the moment.", "type": "句子", "keyWords": ["supply"] },
    { "chinese": "向……提供……", "english": "supply sb. with sth. = supply sth. to sb.", "type": "短语", "keyWords": ["supply"] },
    { "chinese": "向市场供应新商品", "english": "supply the market with new commodities", "type": "短语", "keyWords": ["supply"] },
    { "chinese": "向市场供应新商品", "english": "supply new commodities to the market", "type": "短语", "keyWords": ["supply"] },
    { "chinese": "他们让我们源源不断地获得燃料。", "english": "They kept us supplied with fuel.", "type": "句子", "keyWords": ["supply"] },
    { "chinese": "v. 支撑；支持；供养 n. [U]支持；援助", "english": "support /sə'pɔːt/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]支持者，拥护者", "english": "supporter", "type": "单词", "keyWords": ["support"] },
    { "chinese": "a. 支持的，支撑的", "english": "supporting", "type": "单词", "keyWords": ["support"] },
    { "chinese": "搀扶他的母亲", "english": "support his mother", "type": "短语", "keyWords": ["support"] },
    { "chinese": "给予道义上的支持", "english": "give moral support to sb.", "type": "短语", "keyWords": ["support"] },
    { "chinese": "养活一家人，自谋生计", "english": "support a family/ oneself", "type": "短语", "keyWords": ["support"] },
    { "chinese": "证实文件", "english": "supporting document", "type": "短语", "keyWords": ["supporting"] },
    { "chinese": "支承结构；固定架", "english": "supporting structure", "type": "短语", "keyWords": ["supporting"] },
    { "chinese": "墙壁支撑屋顶。", "english": "Walls support the roof.", "type": "句子", "keyWords": ["support"] },
    { "chinese": "v. 假定；猜想，认为 *n. [C][U]假设", "english": "suppose /sə'pəʊz/", "type": "单词", "keyWords": [] },
    { "chinese": "我想是的/我想不是的。", "english": "I suppose so/ not.", "type": "句子", "keyWords": ["suppose"] },
    { "chinese": "你认为那是什么舞？", "english": "What do you suppose the dance is?", "type": "句子", "keyWords": ["suppose"] },
    { "chinese": "假设老板现在看到了你，你会怎么说？(虚拟语气)", "english": "Suppose/ Supposing/ Providing/ Provided the boss saw you now, what would you say?", "type": "句子", "keyWords": ["suppose"] },
    { "chinese": "被认为应该（正/已）做某事", "english": "be supposed to do/ be doing/ have done sth.", "type": "短语", "keyWords": ["suppose"] },
    { "chinese": "我怎么知道呀？", "english": "How was I supposed to know?", "type": "句子", "keyWords": ["suppose"] },
    { "chinese": "缺乏严格的监管应该是造成这种情况的原因。", "english": "The lack of strict supervision is supposed to have given rise to it.", "type": "句子", "keyWords": ["suppose"] },
    { "chinese": "你不可以提前动身。", "english": "You are not supposed to leave early.", "type": "句子", "keyWords": ["suppose"] },
    { "chinese": "a. 确信的；可靠的；有把握的(辨析见certain) ad. 的确，当然", "english": "sure /ʃʊə/", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 当然，无疑", "english": "surely", "type": "单词", "keyWords": ["sure"] },
    { "chinese": "我不能十分确定是否以前见过他。(比较I'm sure that...)", "english": "I'm not quite sure whether I've met him before.", "type": "句子", "keyWords": ["sure"] },
    { "chinese": "坚信，确信", "english": "be sure of/ about", "type": "短语", "keyWords": ["sure"] },
    { "chinese": "不打无把握之仗。", "english": "Fight no battle you are not sure of winning.", "type": "句子", "keyWords": ["sure"] },
    { "chinese": "自信；满怀信心", "english": "feel sure of oneself", "type": "短语", "keyWords": ["sure"] },
    { "chinese": "查明；设法确保", "english": "make sure that...; make sure of...", "type": "短语", "keyWords": ["sure"] },
    { "chinese": "让他一定记下来。", "english": "Make sure that he writes it down.", "type": "句子", "keyWords": ["sure"] },
    { "chinese": "务必……", "english": "Be sure to do sth.", "type": "短语", "keyWords": ["sure"] },
    { "chinese": "千万不要忘记呀。", "english": "Be sure not to forget it.", "type": "句子", "keyWords": ["sure"] },
    { "chinese": "肯定……(表示推测)", "english": "be sure to do sth.", "type": "短语", "keyWords": ["sure"] },
    { "chinese": "他一定会想当然的。", "english": "He is sure to take it for granted.", "type": "句子", "keyWords": ["sure"] },
    { "chinese": "确信", "english": "for sure", "type": "短语", "keyWords": ["sure"] },
    { "chinese": "我们肯定会获胜。", "english": "We'll win for sure.", "type": "句子", "keyWords": ["sure"] },
    { "chinese": "我不十分确切知道。", "english": "I don't know for sure.", "type": "句子", "keyWords": ["sure"] },
    { "chinese": "那是肯定的。", "english": "That's for sure.", "type": "句子", "keyWords": ["sure"] },
    { "chinese": "果然", "english": "sure enough", "type": "短语", "keyWords": ["sure"] },
    { "chinese": "n. [U] v. （在……上）浏览，做网上冲浪；（在……）做冲浪（运动）", "english": "surf /sɜːf/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]表面；外表", "english": "surface /'sɜːfɪs/", "type": "单词", "keyWords": [] },
    { "chinese": "在表面上，在外表上", "english": "on the surface", "type": "短语", "keyWords": ["surface"] },
    { "chinese": "n. [C]外科医生", "english": "surgeon /'sɜːdʒən/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]外科；外科手术", "english": "surgery /'sɜːdʒəri/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 外科的，手术上的", "english": "surgical", "type": "单词", "keyWords": ["surgery"] },
    { "chinese": "n. [C]姓；别号，外号", "english": "surname /'sɜːneɪm/", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使惊奇(辨析见amaze)；*奇袭 n. [C][U]惊奇；意想不到的事物(如消息、礼物等)", "english": "surprise /sə'praɪz/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 感到/使人惊讶的", "english": "surprised/ surprising", "type": "单词", "keyWords": ["surprise"] },
    { "chinese": "ad. 令人惊讶地", "english": "surprisingly", "type": "单词", "keyWords": ["surprise"] },
    { "chinese": "出其不意，袭击", "english": "take...by surprise", "type": "短语", "keyWords": ["surprise"] },
    { "chinese": "我得说结果让我大吃一惊。", "english": "I must say the result has taken me completely by surprise.", "type": "句子", "keyWords": ["surprise"] },
    { "chinese": "冷不防地当场抓住了某人", "english": "surprise sb. in the act", "type": "短语", "keyWords": ["surprise"] },
    { "chinese": "你吓了我一跳！", "english": "You surprise me!", "type": "句子", "keyWords": ["surprise"] },
    { "chinese": "我真想不到会在那里见到他。", "english": "I was surprised to see (= at seeing) him there.", "type": "句子", "keyWords": ["surprise"] },
    { "chinese": "多么令人吃惊的事！", "english": "What a surprise!", "type": "句子", "keyWords": ["surprise"] },
    { "chinese": "惊奇地", "english": "in surprise", "type": "短语", "keyWords": ["surprise"] },
    { "chinese": "令某人非常惊讶的是", "english": "much to one's surprise = to one's great surprise", "type": "短语", "keyWords": ["surprise"] },
    { "chinese": "vt. 包围；环绕", "english": "surround /sə'raʊnd/", "type": "单词", "keyWords": [] },
    { "chinese": "n. (pl.)周围的事物；环境 a. 周围的，环绕的", "english": "surrounding", "type": "单词", "keyWords": ["surround"] },
    { "chinese": "被……环绕", "english": "be surrounded with/ by", "type": "短语", "keyWords": ["surround"] },
    { "chinese": "v. 勘测；调查 /n. [C]勘测；调查", "english": "survey /sə'veɪ/ /'sɜːveɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "进行调查/勘测", "english": "make/ conduct/ carry out/ do a survey", "type": "短语", "keyWords": ["survey"] },
    { "chinese": "v. 幸免于，从……中逃生；经历……后继续存在；比……活得长 vi. 幸存", "english": "survive /sə'vaɪv/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C][U]幸存(者/物)", "english": "survival", "type": "单词", "keyWords": ["survive"] },
    { "chinese": "n. [C]幸存者", "english": "survivor", "type": "单词", "keyWords": ["survive"] },
    { "chinese": "经过暴风雨袭击，这所房屋并未倒塌。", "english": "The house survived the storm.", "type": "句子", "keyWords": ["survive"] },
    { "chinese": "她比她丈夫多活了五年。", "english": "She survived her husband by five years.", "type": "句子", "keyWords": ["survive"] },
    { "chinese": "适者生存", "english": "the survival of the fittest", "type": "短语", "keyWords": ["survival"] },
    { "chinese": "古代遗物/遗风", "english": "a survival from ancient times", "type": "短语", "keyWords": ["survival"] },
    { "chinese": "v. 怀疑，猜疑，推测；对……疑心/察觉有某情况 /n. [C]嫌疑犯", "english": "suspect /sə'spekt/ /'sʌspekt/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可疑的，多疑的", "english": "suspicious", "type": "单词", "keyWords": ["suspect"] },
    { "chinese": "n. [C][U]怀疑，疑心", "english": "suspicion", "type": "单词", "keyWords": ["suspect"] },
    { "chinese": "疑心某人干某事", "english": "suspect sb. of sth.", "type": "短语", "keyWords": ["suspect"] },
    { "chinese": "怀疑他提供假情报", "english": "suspect him of giving false information", "type": "短语", "keyWords": ["suspect"] },
    { "chinese": "警察怀疑她犯了谋杀罪。", "english": "The police suspected her of murder.", "type": "句子", "keyWords": ["suspect"] },
    { "chinese": "猜想他病了(近think, believe, consider)", "english": "suspect him to be ill", "type": "短语", "keyWords": ["suspect"] },
    { "chinese": "我们揣想他们会晚来一会儿。", "english": "We suspect they'll be a little late.", "type": "句子", "keyWords": ["suspect"] },
    { "chinese": "起疑心(近be doubtful of)", "english": "be suspicious of/ about sb./ sth.", "type": "短语", "keyWords": ["suspicious"] },
    { "chinese": "v. 悬，挂，吊，（使）悬浮；*中止，暂时禁止参加活动", "english": "suspend /sə'spend/", "type": "单词", "keyWords": [] },
    { "chinese": "中止谈判", "english": "suspend talks", "type": "短语", "keyWords": ["suspend"] },
    { "chinese": "把灯从天花板挂下", "english": "suspend a lamp from the ceiling", "type": "短语", "keyWords": ["suspend"] },
    { "chinese": "汤姆因为行为不端被停学一周。", "english": "Tom is suspended from school for a week for bad conduct.", "type": "句子", "keyWords": ["suspend"] },
    { "chinese": "n. [U]悬，挂，吊，悬浮；*中止", "english": "suspension /sə'spenʃn/", "type": "单词", "keyWords": ["suspend"] },
    { "chinese": "悬索桥，吊桥", "english": "suspension bridge", "type": "短语", "keyWords": ["suspension"] },
    { "chinese": "a. 可以忍受的，足可支撑的；能持续的；能保持的", "english": "sustainable /sə'steɪnəbl/", "type": "单词", "keyWords": [] },
    { "chinese": "可持续发展战略", "english": "the strategy of sustainable development", "type": "短语", "keyWords": ["sustainable"] },
    { "chinese": "n. [C]燕子 v. 吞下，咽下(p; 吞并；*轻易接受，轻信", "english": "swallow /'swɒləʊ/", "type": "单词", "keyWords": [] },
    { "chinese": "囫囵吞枣", "english": "swallow sth. whole", "type": "短语", "keyWords": ["swallow"] },
    { "chinese": "一燕不成夏。", "english": "One swallow does not make a summer.", "type": "句子", "keyWords": ["swallow"] },
    { "chinese": "v. （使）摇摆，（使）摇动(辨析见swing)", "english": "sway /sweɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "v. 宣(誓)；发(誓) *vi. 诅咒(at)；发誓", "english": "swear /sweə/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U]汗；(可与a连用)出汗 vi. 出汗", "english": "sweat /swet/", "type": "单词", "keyWords": [] },
    { "chinese": "苦尽才能甘来。/先苦后甜。", "english": "No sweet without sweat.", "type": "句子", "keyWords": ["sweat"] },
    { "chinese": "n. [C]厚运动衫；针织套衫，毛线衫，羊毛衫", "english": "sweater /'swetə/", "type": "单词", "keyWords": [] },
    { "chinese": "v. 扫，打扫；席卷，扫过 vi. 打扫地板或房间等；*掠过，席卷", "english": "sweep /swiːp/", "type": "单词", "keyWords": [] },
    { "chinese": "扫去垃圾", "english": "sweep away the rubbish", "type": "短语", "keyWords": ["sweep"] },
    { "chinese": "暴风雪横扫全国。", "english": "A snowstorm swept the country.", "type": "句子", "keyWords": ["sweep"] },
    { "chinese": "他从右到左扫视了一下。", "english": "His glance swept from right to left.", "type": "句子", "keyWords": ["sweep"] },
    { "chinese": "n. (C)(常pl.)糖果 a. 甜的；香的；*可爱的，讨人喜欢的", "english": "sweet /swiːt/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 快速的，敏捷的；立刻做出的", "english": "swift /swɪft/", "type": "单词", "keyWords": [] },
    { "chinese": "vi./n. [C]游泳", "english": "swim /swɪm/", "type": "单词", "keyWords": [] },
    { "chinese": "去游泳", "english": "go for a swim", "type": "短语", "keyWords": ["swim"] },
    { "chinese": "v. （使）摆动；（使）摇摆；悬；挂；（使）剧变 n. [C]摆动；震动；秋千", "english": "swing /swɪŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "门开了。", "english": "The door swung open.", "type": "句子", "keyWords": ["swing"] },
    { "chinese": "她转喜为悲。", "english": "She swung from happiness to tears.", "type": "句子", "keyWords": ["swing"] },
    { "chinese": "荡秋千", "english": "play on a swing", "type": "短语", "keyWords": ["swing"] },
    { "chinese": "摆幅为3英寸的钟摆", "english": "a pendulum with a 3-inch swing", "type": "短语", "keyWords": ["swing"] },
    { "chinese": "辨析：swing, sway swing常指上端固定另一端悬空的物体作弧形的运动；sway一般表示人或物的下端固定，上端摇动，摆动速度通常比swing慢，例：Branches swayed gently in the wind.树枝在风中微微摇动。", "english": "辨析:swing, sway swing 常指上端固定另一端悬空的物体作弧形的运动;sway一般表示人或物的下端固定,上端摇动,摆动速度通常比swing慢,例:Branches swayed gently in the wind.树枝在风中微微摇动。", "type": "句子", "keyWords": ["swing", "sway"] },
    { "chinese": "vi./n. [C]开关；转换，转变 *n. 配电盘；接线总机", "english": "switch /swɪtʃ/", "type": "单词", "keyWords": [] },
    { "chinese": "打开/关掉", "english": "switch...on/ off", "type": "短语", "keyWords": ["switch"] },
    { "chinese": "把话题转移到一个更轻松的话题", "english": "switch the conversation to a lighter subject", "type": "短语", "keyWords": ["switch"] },
    { "chinese": "我过去用电烧饭，但现已换成用煤气了。", "english": "I used to cook on electricity, but I've switched to (using) gas.", "type": "句子", "keyWords": ["switch"] },
    { "chinese": "转投另一候选人的票", "english": "a switch of vote to another candidate", "type": "短语", "keyWords": ["switch"] },
    { "chinese": "n. [C]剑", "english": "sword /sɔːd/", "type": "单词", "keyWords": [] },
    { "chinese": "拔剑", "english": "draw the sword", "type": "短语", "keyWords": ["sword"] },
    { "chinese": "n. [C]象征；符号；标志", "english": "symbol /'sɪmbl/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 象征的；符号的", "english": "symbolic /sɪm'bɒlɪk/", "type": "单词", "keyWords": ["symbol"] },
    { "chinese": "化学符号", "english": "a chemical symbol", "type": "短语", "keyWords": ["symbol"] },
    { "chinese": "抽象符号", "english": "abstract symbol", "type": "短语", "keyWords": ["symbol"] },
    { "chinese": "白色是纯洁的象征。", "english": "White is the symbol of purity.", "type": "句子", "keyWords": ["symbol"] },
    { "chinese": "多重象征意义", "english": "the multiple symbolic meanings", "type": "短语", "keyWords": ["symbolic"] },
    { "chinese": "象征和平、爱和宽恕", "english": "symbolize peace, love and forgiveness", "type": "短语", "keyWords": ["symbolize"] },
    { "chinese": "n. [U]同情(心)", "english": "sympathy /'sɪmpəθi/", "type": "单词", "keyWords": [] },
    { "chinese": "对病人抱有同情", "english": "have sympathy with the sick", "type": "短语", "keyWords": ["sympathy"] },
    { "chinese": "同情；赞成；和(近in agreement with)", "english": "in sympathy with", "type": "短语", "keyWords": ["sympathy"] },
    { "chinese": "（对……表示）慰问", "english": "express sympathy for", "type": "短语", "keyWords": ["sympathy"] },
    { "chinese": "同情", "english": "feel sympathy for", "type": "短语", "keyWords": ["sympathy"] },
    { "chinese": "a. 有同情心的(to/ towards)；赞成的", "english": "sympathetic /ˌsɪmpə'θetɪk/", "type": "单词", "keyWords": ["sympathy"] },
    { "chinese": "n. [C]交响曲", "english": "symphony /'sɪmfəni/", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C]症状，征兆", "english": "symptom /'sɪmptəm/", "type": "单词", "keyWords": [] },
    { "chinese": "临床症状", "english": "clinical symptoms", "type": "短语", "keyWords": ["symptom"] },
    { "chinese": "a. 人工制造的，合成的(常指使用化学反应来产生)", "english": "synthetic /sɪn'θetɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "人造皮革", "english": "synthetic leather", "type": "短语", "keyWords": ["synthetic"] },
    { "chinese": "n. [C]系统，体系；制度", "english": "system /'sɪstəm/", "type": "单词", "keyWords": [] },
    { "chinese": "a. 系统的，体系的", "english": "systematic /ˌsɪstə'mætɪk/", "type": "单词", "keyWords": ["system"] },
    { "chinese": "n.[C]桌子；工作台；表格", "english": "table", "type": "单词", "keyWords": [] },
    { "chinese": "在吃饭（期间）", "english": "at table", "type": "短语", "keyWords": ["table"] },
    { "chinese": "预定一桌位", "english": "book a table", "type": "短语", "keyWords": ["table"] },
    { "chinese": "摆餐具准备吃饭", "english": "lay/ set the table", "type": "短语", "keyWords": ["table"] },
    { "chinese": "乒乓", "english": "table tennis", "type": "短语", "keyWords": ["table"] },
    { "chinese": "在座的人都听到了他的话。", "english": "The whole table heard what he said.", "type": "句子", "keyWords": ["table"] },
    { "chinese": "如上表所示，误差可能会高达20%。", "english": "The error may be as much as 20%, as shown in the above table.", "type": "句子", "keyWords": ["table"] },
    { "chinese": "n.[C]药片；平板电脑", "english": "tablet", "type": "单词", "keyWords": [] },
    { "chinese": "v.品尝；vi.尝起来；有……味道(of)；n.[C](U)味，味道；喜欢；鉴赏力", "english": "taste", "type": "单词", "keyWords": [] },
    { "chinese": "adj.好吃的，可口的", "english": "tasty", "type": "单词", "keyWords": ["taste"] },
    { "chinese": "adj.无味的", "english": "tasteless", "type": "单词", "keyWords": ["taste"] },
    { "chinese": "尝一尝这种茶", "english": "have/ take a taste of this tea", "type": "短语", "keyWords": ["taste"] },
    { "chinese": "合某人的意图/口味", "english": "to one's taste", "type": "短语", "keyWords": ["taste"] },
    { "chinese": "体会幸福生活的欢乐", "english": "taste the joys of the happy life", "type": "短语", "keyWords": ["taste"] },
    { "chinese": "爱好音乐", "english": "have a taste for music", "type": "短语", "keyWords": ["taste"] },
    { "chinese": "这饮料有柠檬味儿。", "english": "The drink tastes of lemon.", "type": "句子", "keyWords": ["taste"] },
    { "chinese": "n.[C](U)税；v.对……征税", "english": "tax", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]征税", "english": "taxation", "type": "单词", "keyWords": ["tax"] },
    { "chinese": "adj.免税的", "english": "tax-free", "type": "单词", "keyWords": ["tax"] },
    { "chinese": "缴税", "english": "pay one's taxes", "type": "短语", "keyWords": ["tax"] },
    { "chinese": "免税", "english": "free of tax", "type": "短语", "keyWords": ["tax"] },
    { "chinese": "对酒类课重税", "english": "impose a heavy tax upon wines(tax wines heavily)", "type": "短语", "keyWords": ["tax"] },
    { "chinese": "n.[C]出租汽车", "english": "taxi", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]标签；标牌，铭牌", "english": "tag", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]尾巴；尾状物", "english": "tail", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]裁缝；v.剪裁，缝制（衣服）；使适应特定需要，适合(to)", "english": "tailor", "type": "单词", "keyWords": [] },
    { "chinese": "在裁缝店", "english": "at the tailor's", "type": "短语", "keyWords": ["tailor"] },
    { "chinese": "你应该量入为出。", "english": "You should tailor your spending to your income.", "type": "句子", "keyWords": ["tailor"] },
    { "chinese": "这是一本为迎合大众口味而创作的小说。", "english": "This is a novel tailored to popular taste.", "type": "句子", "keyWords": ["tailor"] },
    { "chinese": "佛靠金装，人靠衣装。", "english": "The tailor makes the man.", "type": "句子", "keyWords": ["tailor"] },
    { "chinese": "n.[C](U)才能；天资；才干；n.[C](U)人才", "english": "talent", "type": "单词", "keyWords": [] },
    { "chinese": "adj.天才的；有才干的（近gifted）", "english": "talented", "type": "单词", "keyWords": ["talent"] },
    { "chinese": "我妹妹有音乐才能。", "english": "My sister has a talent/ gift/ genius for music.", "type": "句子", "keyWords": ["talent"] },
    { "chinese": "n.[C]故事；传说；假话", "english": "tale", "type": "单词", "keyWords": [] },
    { "chinese": "神话故事", "english": "a fairy tale", "type": "短语", "keyWords": ["tale"] }
];
