const qgl271_285 = [
    { "chinese": "n.[C]谈话，说话，话语；商讨；n.(U)流言蜚语", "english": "talk", "type": "单词", "keyWords": [] },
    { "chinese": "adj.爱说话的；多嘴的", "english": "talkative", "type": "单词", "keyWords": ["talk"] },
    { "chinese": "和谈", "english": "peace talks", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "脱口秀", "english": "talk show", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "谈到；谈论", "english": "talk about", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "谈及，说到", "english": "talk of", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "吹牛；说大话", "english": "talk big", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "胡说八道", "english": "talk nonsense", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "顶嘴；反驳", "english": "talk back", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "背后议论某人", "english": "talk behind sb.'s back", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "说到某人/某事", "english": "talking of sb./ sth.", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "谈到运动，我最喜欢高尔夫球了。", "english": "Talking of sports, I like golf best.", "type": "句子", "keyWords": ["talk"] },
    { "chinese": "在谈话中度过了傍晚的时光", "english": "talk the evening away", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "说服某人做/不做某事", "english": "talk sb. into/ out of (doing) sth.", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "他说服了他父亲把车借给他。", "english": "He talked his father into lending him the car.", "type": "句子", "keyWords": ["talk"] },
    { "chinese": "有传闻说要破产。", "english": "There is talk of bankruptcy.", "type": "句子", "keyWords": ["talk"] },
    { "chinese": "成为镇上人们议论的话题的一部歌舞片", "english": "a musical that is the talk of the town", "type": "短语", "keyWords": ["talk"] },
    { "chinese": "有钱能使鬼推磨。", "english": "Money talks.", "type": "句子", "keyWords": ["talk"] },
    { "chinese": "adj.（人）高的；（树、建筑物等）高大的", "english": "tall", "type": "单词", "keyWords": [] },
    { "chinese": "adj.（动物）驯化的，驯服的；温顺的；v.驯服，驯化", "english": "tame", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]温顺，驯服", "english": "tameness", "type": "单词", "keyWords": ["tame"] },
    { "chinese": "n.[C]（盛液体、气体的大容器）桶，箱；坦克", "english": "tank", "type": "单词", "keyWords": [] },
    { "chinese": "油箱", "english": "a petrol tank", "type": "短语", "keyWords": ["tank"] },
    { "chinese": "油船，油轮", "english": "tankship(= *tanker)", "type": "短语", "keyWords": ["tank"] },
    { "chinese": "v.[C]轻拍，轻叩；[美]选择；指定；n.[C]水龙头；阀门", "english": "tap", "type": "单词", "keyWords": [] },
    { "chinese": "轻拍某人的肩膀", "english": "tap sb. on the shoulder", "type": "短语", "keyWords": ["tap"] },
    { "chinese": "敲打出一种节奏", "english": "tap out a rhythm", "type": "短语", "keyWords": ["tap"] },
    { "chinese": "n.[C]磁带；带子；卷尺；胶布；v.用带子（将包裹等）捆起来", "english": "tape", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]靶子；目标；对象；v.把……作为目标；瞄准；规定……的指标", "english": "target", "type": "单词", "keyWords": [] },
    { "chinese": "达到指标；射中靶子", "english": "hit a target", "type": "短语", "keyWords": ["target"] },
    { "chinese": "未射中靶子；未完成指标", "english": "miss the target", "type": "短语", "keyWords": ["target"] },
    { "chinese": "目标客户", "english": "targeted customers", "type": "短语", "keyWords": ["target"] },
    { "chinese": "目标语言", "english": "target language", "type": "短语", "keyWords": ["target"] },
    { "chinese": "这些游戏的主要顾客是青少年。", "english": "The games are targeted on teenagers.", "type": "句子", "keyWords": ["target"] },
    { "chinese": "指标定为", "english": "be targeted for", "type": "短语", "keyWords": ["target"] },
    { "chinese": "钢产量去年指标定为六万吨。", "english": "Steel production was targeted for 60,000 tons last year.", "type": "句子", "keyWords": ["target"] },
    { "chinese": "n.[C]任务；工作", "english": "task", "type": "单词", "keyWords": [] },
    { "chinese": "分派某人一项任务", "english": "assign sb. a task", "type": "短语", "keyWords": ["task"] },
    { "chinese": "adj.技术的，工艺的", "english": "technical", "type": "单词", "keyWords": [] },
    { "chinese": "专门名词，术语", "english": "technical terms", "type": "短语", "keyWords": ["technical"] },
    { "chinese": "n.[C]技师，技术员", "english": "technician", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]技术；技能；工艺；方法", "english": "technique", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]技术", "english": "technology", "type": "单词", "keyWords": [] },
    { "chinese": "adj.技术的", "english": "technological", "type": "单词", "keyWords": ["technology"] },
    { "chinese": "科学和技术", "english": "science and technology", "type": "短语", "keyWords": ["technology"] },
    { "chinese": "n.[C]（13至19岁）少年", "english": "teenager", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]电报；电文", "english": "telegram", "type": "单词", "keyWords": [] },
    { "chinese": "发急电", "english": "send an express telegram", "type": "短语", "keyWords": ["telegram"] },
    { "chinese": "n.[C]电报机；n.[U]电报（指通讯方式）；v.发电报给", "english": "telegraph", "type": "单词", "keyWords": [] },
    { "chinese": "v.打电话给；vi.打电话，通电话；n.[C](U)电话；电话机", "english": "telephone", "type": "单词", "keyWords": [] },
    { "chinese": "通过电话", "english": "by telephone", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "接电话", "english": "answer the telephone", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "有某人的电话", "english": "be wanted on the (telephone)", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "打（某人）电话", "english": "make a telephone call (to sb.)", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "n.[C]望远镜", "english": "telescope", "type": "单词", "keyWords": [] },
    { "chinese": "用望远镜", "english": "through telescope", "type": "短语", "keyWords": ["telescope"] },
    { "chinese": "v.用电视播放", "english": "televise", "type": "单词", "keyWords": [] },
    { "chinese": "用电视直播", "english": "televise sth. live", "type": "短语", "keyWords": ["televise"] },
    { "chinese": "（略作TV）n.[U]电视（节目）；n.[C]电视机（TV set）", "english": "television", "type": "单词", "keyWords": [] },
    { "chinese": "v.教；教导；训练；讲授（侧重传授知识和技能）", "english": "teach", "type": "单词", "keyWords": [] },
    { "chinese": "教某人做某事", "english": "teach sb. to do sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "自学……", "english": "teach oneself sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "给……一个教训", "english": "teach sb. a lesson = teach a lesson to sb.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "教某人如何做某事", "english": "teach sb. how to do sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "n.[C]教师；老师；导师", "english": "teacher", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]教学；（常用pl.）教义", "english": "teaching", "type": "单词", "keyWords": ["teacher"] },
    { "chinese": "有其师必有其徒。", "english": "Like teacher, like pupil.", "type": "句子", "keyWords": ["teacher"] },
    { "chinese": "n.[C]队；组", "english": "team", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]配合，协同工作；小组作业", "english": "teamwork", "type": "单词", "keyWords": ["team"] },
    { "chinese": "他是那个队的成员吗？", "english": "Is he on that team?", "type": "句子", "keyWords": ["team"] },
    { "chinese": "n.[C]（常用pl.）眼泪；v.流泪；含泪；/teə/ v.撕，撕裂；vi.被撕破", "english": "tear", "type": "单词", "keyWords": [] },
    { "chinese": "adj.流泪的", "english": "tearful", "type": "单词", "keyWords": ["tear"] },
    { "chinese": "忍住眼泪", "english": "keep back one's tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "感动得流泪", "english": "be moved to tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "突然哭起来", "english": "burst into tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "流着泪", "english": "in tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "流泪", "english": "tears come into/ to one's eyes", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "伤心/辛酸泪", "english": "bitter tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "鳄鱼的眼泪；伪善的眼泪，假哭", "english": "crocodile tears", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "为他的死而假哭了一场", "english": "shed crocodile tears over his death", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "这种料子很容易（被）撕破。", "english": "This material tears easily.", "type": "句子", "keyWords": ["tear"] },
    { "chinese": "把……撕得粉碎", "english": "tear sth. into pieces(tear sth. up)", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "（互相用指甲）猛力去抓或扯，撕扯", "english": "tear at (each other with their nails)", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "拆毁（房屋等）", "english": "tear...down", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "泪眼", "english": "tearful eyes", "type": "短语", "keyWords": ["tear"] },
    { "chinese": "v.取笑，逗恼，戏弄；挑逗", "english": "tease", "type": "单词", "keyWords": [] },
    { "chinese": "adj.技术的，工艺的", "english": "technical", "type": "单词", "keyWords": [] },
    { "chinese": "专门名词，术语", "english": "technical terms", "type": "短语", "keyWords": ["technical"] },
    { "chinese": "n.[C]技师，技术员", "english": "technician", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]技术；技能；工艺；方法", "english": "technique", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]技术", "english": "technology", "type": "单词", "keyWords": [] },
    { "chinese": "adj.技术的", "english": "technological", "type": "单词", "keyWords": ["technology"] },
    { "chinese": "科学和技术", "english": "science and technology", "type": "短语", "keyWords": ["technology"] },
    { "chinese": "n.[C]（13至19岁）少年", "english": "teenager", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]电报；电文", "english": "telegram", "type": "单词", "keyWords": [] },
    { "chinese": "发急电", "english": "send an express telegram", "type": "短语", "keyWords": ["telegram"] },
    { "chinese": "n.[C]电报机；n.[U]电报（指通讯方式）；v.发电报给", "english": "telegraph", "type": "单词", "keyWords": [] },
    { "chinese": "v.打电话给；vi.打电话，通电话；n.[C](U)电话；电话机", "english": "telephone", "type": "单词", "keyWords": [] },
    { "chinese": "通过电话", "english": "by telephone", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "接电话", "english": "answer the telephone", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "有某人的电话", "english": "be wanted on the (telephone)", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "打（某人）电话", "english": "make a telephone call (to sb.)", "type": "短语", "keyWords": ["telephone"] },
    { "chinese": "n.[C]望远镜", "english": "telescope", "type": "单词", "keyWords": [] },
    { "chinese": "用望远镜", "english": "through telescope", "type": "短语", "keyWords": ["telescope"] },
    { "chinese": "v.用电视播放", "english": "televise", "type": "单词", "keyWords": [] },
    { "chinese": "用电视直播", "english": "televise sth. live", "type": "短语", "keyWords": ["televise"] },
    { "chinese": "（略作TV）n.[U]电视（节目）；n.[C]电视机（TV set）", "english": "television", "type": "单词", "keyWords": [] },
    { "chinese": "v.教；教导；训练；讲授（侧重传授知识和技能）", "english": "teach", "type": "单词", "keyWords": [] },
    { "chinese": "教某人做某事", "english": "teach sb. to do sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "自学……", "english": "teach oneself sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "给……一个教训", "english": "teach sb. a lesson = teach a lesson to sb.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "教某人如何做某事", "english": "teach sb. how to do sth.", "type": "短语", "keyWords": ["teach"] },
    { "chinese": "n.[C]教师；老师；导师", "english": "teacher", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]教学；（常用pl.）教义", "english": "teaching", "type": "单词", "keyWords": ["teacher"] },
    { "chinese": "有其师必有其徒。", "english": "Like teacher, like pupil.", "type": "句子", "keyWords": ["teacher"] },
    { "chinese": "n.[C]队；组", "english": "team", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]配合，协同工作；小组作业", "english": "teamwork", "type": "单词", "keyWords": ["team"] },
    { "chinese": "他是那个队的成员吗？", "english": "Is he on that team?", "type": "句子", "keyWords": ["team"] },
    { "chinese": "v.告诉；讲述；吩咐；分辨；判断；vi.确定地说出", "english": "tell", "type": "单词", "keyWords": [] },
    { "chinese": "说谎", "english": "tell a lie", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "算命", "english": "tell one's fortune", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "报时", "english": "tell the time", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "区分；辨别", "english": "tell...from...", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "区分；辨别", "english": "tell them apart", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "讲述", "english": "tell of/ about", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "要某人去做某事", "english": "tell sb. to do sth.", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "说出，判断出", "english": "can tell", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "说实话", "english": "tell the truth", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "他判断不出是哪一栋房子。", "english": "He couldn't tell which house it was.", "type": "句子", "keyWords": ["tell"] },
    { "chinese": "不可能知道；难以预料", "english": "There's no telling/ knowing...", "type": "短语", "keyWords": ["tell"] },
    { "chinese": "（谁也）不可能知道会发生什么事。", "english": "There's no telling what may happen.", "type": "句子", "keyWords": ["tell"] },
    { "chinese": "n.[C]（常与a连用）心情，脾气", "english": "temper", "type": "单词", "keyWords": [] },
    { "chinese": "脾气（不）好的", "english": "bad/ good-tempered", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "心情不好", "english": "be in a temper", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "发脾气", "english": "be in a bad temper", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "发脾气", "english": "lose one's temper", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "发脾气", "english": "get into a temper", "type": "短语", "keyWords": ["temper"] },
    { "chinese": "adj.温带的；温和的", "english": "temperate", "type": "单词", "keyWords": [] },
    { "chinese": "在吃喝上自我克制", "english": "be temperate in eating and drinking", "type": "短语", "keyWords": ["temperate"] },
    { "chinese": "温和的批评", "english": "temperate criticism", "type": "短语", "keyWords": ["temperate"] },
    { "chinese": "温和的气候", "english": "temperate climate", "type": "短语", "keyWords": ["temperate"] },
    { "chinese": "n.[C]温度；体温", "english": "temperature", "type": "单词", "keyWords": [] },
    { "chinese": "量体温", "english": "take one's temperature", "type": "短语", "keyWords": ["temperature"] },
    { "chinese": "正常体温", "english": "normal temperature", "type": "短语", "keyWords": ["temperature"] },
    { "chinese": "n.[C]庙宇，寺院", "english": "temple", "type": "单词", "keyWords": [] },
    { "chinese": "adj.临时的，暂时的", "english": "temporary", "type": "单词", "keyWords": [] },
    { "chinese": "adv.暂时地", "english": "temporarily", "type": "单词", "keyWords": ["temporary"] },
    { "chinese": "v.吸引；引诱", "english": "tempt", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]诱惑；n.[C]诱惑物", "english": "temptation", "type": "单词", "keyWords": ["tempt"] },
    { "chinese": "吸引人的提议", "english": "a tempting offer", "type": "短语", "keyWords": ["tempt"] },
    { "chinese": "诱人的气味", "english": "a tempting smell", "type": "短语", "keyWords": ["tempt"] },
    { "chinese": "诱惑某人做某事", "english": "tempt sb. to do sth.", "type": "短语", "keyWords": ["tempt"] },
    { "chinese": "诱惑某人做某事", "english": "tempt sb. into doing sth.", "type": "短语", "keyWords": ["tempt"] },
    { "chinese": "抵制……的诱惑", "english": "resist the temptation to do...", "type": "短语", "keyWords": ["temptation"] },
    { "chinese": "num.十", "english": "ten", "type": "单词", "keyWords": [] },
    { "chinese": "十有八九他会赢。", "english": "Ten to one he will win.", "type": "句子", "keyWords": ["ten"] },
    { "chinese": "n.[C]租户；房客；佃户", "english": "tenant", "type": "单词", "keyWords": [] },
    { "chinese": "v.照管，护理（近attend to, look after）；vi.易于，趋向；倾向", "english": "tend", "type": "单词", "keyWords": [] },
    { "chinese": "照料伤员", "english": "tend the wounded", "type": "短语", "keyWords": ["tend"] },
    { "chinese": "经营酒吧", "english": "tend a bar", "type": "短语", "keyWords": ["tend"] },
    { "chinese": "易于/趋向做某事；往往会（=be inclined to do sth）", "english": "tend to do sth.", "type": "短语", "keyWords": ["tend"] },
    { "chinese": "一个人的处境是苦是乐常是主观的。", "english": "People tend to judge their lives subjectively.", "type": "句子", "keyWords": ["tend"] },
    { "chinese": "冬天蔬菜往往较贵。", "english": "Vegetables tend to be more expensive in winter.", "type": "句子", "keyWords": ["tend"] },
    { "chinese": "n.[C]趋势；趋向；（性格、性质或作品）倾向(to)", "english": "tendency", "type": "单词", "keyWords": [] },
    { "chinese": "倾向/喜欢……", "english": "have a tendency to do...", "type": "短语", "keyWords": ["tendency"] },
    { "chinese": "adj.嫩的；温柔的；亲切的", "english": "tender", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]亲切，柔和", "english": "tenderness", "type": "单词", "keyWords": ["tender"] },
    { "chinese": "adv.温和地，体贴地", "english": "tenderly", "type": "单词", "keyWords": ["tender"] },
    { "chinese": "慈母", "english": "a tender mother", "type": "短语", "keyWords": ["tender"] },
    { "chinese": "嫩肉", "english": "tender meat", "type": "短语", "keyWords": ["tender"] },
    { "chinese": "n.[U]网球（运动）", "english": "tennis", "type": "单词", "keyWords": [] },
    { "chinese": "打网球", "english": "play tennis", "type": "短语", "keyWords": ["tennis"] },
    { "chinese": "adj.绷紧的；紧张的；n.[C]时态；v.（使）拉紧/紧张", "english": "tense", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]张力，拉力", "english": "tension", "type": "单词", "keyWords": ["tense"] },
    { "chinese": "绷紧的肌肉", "english": "tense muscles", "type": "短语", "keyWords": ["tense"] },
    { "chinese": "队员们在比赛开始时很紧张。", "english": "The players were tense at the start of the game.", "type": "句子", "keyWords": ["tense"] },
    { "chinese": "n.[C]帐篷", "english": "tent", "type": "单词", "keyWords": [] },
    { "chinese": "搭帐篷", "english": "put up a tent", "type": "短语", "keyWords": ["tent"] },
    { "chinese": "拆帐篷", "english": "take down a tent", "type": "短语", "keyWords": ["tent"] },
    { "chinese": "n.[C]学期；名称，术语；任期，限期", "english": "term", "type": "单词", "keyWords": [] },
    { "chinese": "专门名词，术语", "english": "technical terms", "type": "短语", "keyWords": ["term"] },
    { "chinese": "科学术语", "english": "scientific terms", "type": "短语", "keyWords": ["term"] },
    { "chinese": "他即将开始他的四年总统任期。", "english": "He is about to begin his four-year term as President.", "type": "句子", "keyWords": ["term"] },
    { "chinese": "就长远/中期/短期而言", "english": "in the long/ medium/ short term", "type": "短语", "keyWords": ["term"] },
    { "chinese": "短期内我们会赔钱，但从长远看，利润将会是丰厚的。", "english": "In the short term we will lose money, but in the long term the profits will be very large.", "type": "句子", "keyWords": ["term"] },
    { "chinese": "关于；至于；从...角度来讲", "english": "in terms of/ in...terms", "type": "短语", "keyWords": ["term"] },
    { "chinese": "我们现在的生产技术水平是什么状况？", "english": "Where do we stand in terms of production technology?", "type": "句子", "keyWords": ["term"] },
    { "chinese": "n.[C]末端；终点；[计]终端(设备)；航站(楼)；a.末端的；定期的", "english": "terminal", "type": "单词", "keyWords": [] },
    { "chinese": "adj.很糟的；可怕的", "english": "terrible", "type": "单词", "keyWords": [] },
    { "chinese": "adv.(口)极；非常；很", "english": "terribly", "type": "单词", "keyWords": ["terrible"] },
    { "chinese": "adj.可怕的，吓人的；(口)非常好的；(美)了不起的；极好的", "english": "terrific", "type": "单词", "keyWords": [] },
    { "chinese": "以高速度开车", "english": "drive at a terrific speed", "type": "短语", "keyWords": ["terrific"] },
    { "chinese": "妙极啦！", "english": "It's terrific!", "type": "句子", "keyWords": ["terrific"] },
    { "chinese": "v.使恐怖，恐吓", "english": "terrify", "type": "单词", "keyWords": [] },
    { "chinese": "adj.使/感到惊恐", "english": "terrifying/ terrified", "type": "单词", "keyWords": ["terrify"] },
    { "chinese": "对...感到惊恐（近be afraid/ scared/ frightened of）", "english": "be terrified of", "type": "短语", "keyWords": ["terrify"] },
    { "chinese": "被...吓了一跳（近be frightened at）", "english": "be terrified at", "type": "短语", "keyWords": ["terrify"] },
    { "chinese": "多么可怕的经历啊！", "english": "What a terrifying experience!", "type": "句子", "keyWords": ["terrify"] },
    { "chinese": "n.[U]恐怖；n.[C]令人恐怖的人或事", "english": "terror", "type": "单词", "keyWords": [] },
    { "chinese": "惊恐地", "english": "in terror", "type": "短语", "keyWords": ["terror"] },
    { "chinese": "n.[U]恐怖主义(手段或政治)", "english": "terrorism", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]恐怖分子", "english": "terrorist", "type": "单词", "keyWords": ["terrorism"] },
    { "chinese": "n.[C](U]领土；版图；领地；地区", "english": "territory", "type": "单词", "keyWords": [] },
    { "chinese": "这个岛是我国领土。", "english": "This island is our territory.", "type": "句子", "keyWords": ["territory"] },
    { "chinese": "进入他们的领地", "english": "enter their territory", "type": "短语", "keyWords": ["territory"] },
    { "chinese": "无人居住区", "english": "uninhabited territory", "type": "短语", "keyWords": ["territory"] },
    { "chinese": "n.[C]/v.测试，测验；试验；考验；化验（辨析见check）", "english": "test", "type": "单词", "keyWords": [] },
    { "chinese": "使经受考验，检验", "english": "put...to the test", "type": "短语", "keyWords": ["test"] },
    { "chinese": "经得起...的考验", "english": "stand the test of...", "type": "短语", "keyWords": ["test"] },
    { "chinese": "n.[C]课文；文本；(手机)短信；v.向…发送短信息", "english": "text", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]教科书；课本", "english": "textbook", "type": "单词", "keyWords": ["text"] },
    { "chinese": "conj.比", "english": "than", "type": "单词", "keyWords": [] },
    { "chinese": "事情进行得比预料的要顺利。", "english": "Things went better than (had been) expected.", "type": "句子", "keyWords": ["than"] },
    { "chinese": "v.感谢；谢谢；n.(pl.)感谢；谢意", "english": "thank", "type": "单词", "keyWords": [] },
    { "chinese": "adj.感谢的", "english": "thankful", "type": "单词", "keyWords": ["thank"] },
    { "chinese": "因…而感谢…（近appreciate sth.）", "english": "thank sb. for sth.", "type": "短语", "keyWords": ["thank"] },
    { "chinese": "多谢。", "english": "Many thanks/ Thanks a lot.", "type": "句子", "keyWords": ["thank"] },
    { "chinese": "因某事而感谢某人（近be grateful/ obliged to sb. for sth.）", "english": "be thankful to sb. for sth.", "type": "短语", "keyWords": ["thank"] },
    { "chinese": "多亏/由于（辨析见account）", "english": "thanks to...", "type": "短语", "keyWords": ["thank"] },
    { "chinese": "求你安静点。（埋怨口气）", "english": "I will thank you to be quiet.", "type": "句子", "keyWords": ["thank"] },
    { "chinese": "pron./a.那，那个；ad.（与形容词或副词连用）那样；那么；conj.引导名词性从句或状语从句", "english": "that", "type": "单词", "keyWords": [] },
    { "chinese": "就是说；即", "english": "that is (to say)", "type": "短语", "keyWords": ["that"] },
    { "chinese": "因为", "english": "in that (because)", "type": "短语", "keyWords": ["that"] },
    { "chinese": "既然（~since）", "english": "now that", "type": "短语", "keyWords": ["that"] },
    { "chinese": "强调句型", "english": "It is/ was...that/ who...", "type": "句式", "keyWords": ["that"] },
    { "chinese": "（表示厌烦、不满或赞赏等感情色彩）", "english": "that...of sb.'s", "type": "短语", "keyWords": ["that"] },
    { "chinese": "我很不喜欢他的那个儿子。", "english": "I don't like that son of his.", "type": "句子", "keyWords": ["that"] },
    { "chinese": "主要问题是成本问题。", "english": "The main question is that of cost (=the cost question).", "type": "句子", "keyWords": ["that"] },
    { "chinese": "我无法走那么远。（近so）", "english": "I cannot walk that far.", "type": "句子", "keyWords": ["that"] },
    { "chinese": "有大约那么高吗？", "english": "Is it about that high?", "type": "句子", "keyWords": ["that"] },
    { "chinese": "不是（因为）…而是（因为）…", "english": "not that...but that...", "type": "句式", "keyWords": ["that"] },
    { "chinese": "不是我不满意，而是我还有很多事情要做。", "english": "Not that I am dissatisfied, but that I have my own business to tend to.", "type": "句子", "keyWords": ["that"] },
    { "chinese": "art.（定冠词）这（那）个；这（那）些", "english": "the", "type": "单词", "keyWords": [] },
    { "chinese": "两个中高的那个", "english": "the taller of the two", "type": "短语", "keyWords": ["the"] },
    { "chinese": "我们4个人", "english": "the four of us", "type": "短语", "keyWords": ["the"] },
    { "chinese": "我们中4个人", "english": "four of us", "type": "短语", "keyWords": ["the"] },
    { "chinese": "怀特一家人（比较at White's/ at the Whites' 在怀特家）", "english": "the Whites", "type": "短语", "keyWords": ["the"] },
    { "chinese": "巴西总统贾伊尔·波索纳罗有时被称为“热带地区的特朗普式人物”。", "english": "Brazilian President Jair Bolsonaro is sometimes called the 'Trump of the Tropics'.", "type": "句子", "keyWords": ["the"] },
    { "chinese": "越早越好。", "english": "The sooner, the better.", "type": "句子", "keyWords": ["the"] },
    { "chinese": "计时付酬", "english": "be paid by the hour", "type": "短语", "keyWords": ["the"] },
    { "chinese": "在（20世纪）60年代", "english": "in the sixties/ in the 1960's/ in the 60s", "type": "短语", "keyWords": ["the"] },
    { "chinese": "穷人/伤员/下列（表示一个类别，用作单或复）", "english": "the poor/ the wounded/ the following", "type": "短语", "keyWords": ["the"] },
    { "chinese": "只会更好/糟/…", "english": "all the better/ worse/...", "type": "短语", "keyWords": ["the"] },
    { "chinese": "她衣衫褴褛，却显得更美丽了。", "english": "She is all the more beautiful in her shabby clothing.", "type": "句子", "keyWords": ["the"] },
    { "chinese": "n.[C]戏院", "english": "theatre", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]经常看戏的人", "english": "theatregoer", "type": "单词", "keyWords": ["theatre"] },
    { "chinese": "n.[C](U]偷窃；失窃；偷盗罪", "english": "theft", "type": "单词", "keyWords": [] },
    { "chinese": "偷窃", "english": "commit a theft", "type": "短语", "keyWords": ["theft"] },
    { "chinese": "他因为偷窃被关进监狱。", "english": "He was put in prison for theft.", "type": "句子", "keyWords": ["theft"] },
    { "chinese": "pron.他/她/它们的", "english": "their", "type": "单词", "keyWords": [] },
    { "chinese": "pron.他/她/它们的（名词性物主代词）", "english": "theirs", "type": "单词", "keyWords": [] },
    { "chinese": "这是他们的一种习惯。", "english": "It's a habit of theirs.", "type": "句子", "keyWords": ["theirs"] },
    { "chinese": "pron.他（她、它）们自己", "english": "themselves", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（谈话、写作或讨论等的）题目，主题；vt.赋予…主题", "english": "theme", "type": "单词", "keyWords": [] },
    { "chinese": "adv.那时；（常与and,but连用）接着；（常用于句首或句尾）那么", "english": "then", "type": "单词", "keyWords": [] },
    { "chinese": "从那时起", "english": "from then on", "type": "短语", "keyWords": ["then"] },
    { "chinese": "从那时以来（到现在）", "english": "since then", "type": "短语", "keyWords": ["then"] },
    { "chinese": "间或；不时地", "english": "now and then", "type": "短语", "keyWords": ["then"] },
    { "chinese": "一直到那时，到那时为止", "english": "till then", "type": "短语", "keyWords": ["then"] },
    { "chinese": "接着到了考试的日子。（倒装）", "english": "Then came the day of the exams.", "type": "句子", "keyWords": ["then"] },
    { "chinese": "如果交通拥挤，那就允许超时。", "english": "If traffic is heavy, then extra time will be allowed.", "type": "句子", "keyWords": ["then"] },
    { "chinese": "当时，当场", "english": "then and there", "type": "短语", "keyWords": ["then"] },
    { "chinese": "他当场拒绝了他们的建议。", "english": "He turned down their proposal then and there.", "type": "句子", "keyWords": ["then"] },
    { "chinese": "n.[C](U]理论；学说；论说", "english": "theory", "type": "单词", "keyWords": [] },
    { "chinese": "adj.理论的；理论上的", "english": "theoretical", "type": "单词", "keyWords": ["theory"] },
    { "chinese": "在/从理论上；按理论", "english": "in theory", "type": "短语", "keyWords": ["theory"] },
    { "chinese": "n.[C](U]疗法；治疗", "english": "therapy", "type": "单词", "keyWords": [] },
    { "chinese": "adv.（在）那里；往那儿；（作引导词，与be等动词连用）有，存在", "english": "there", "type": "单词", "keyWords": [] },
    { "chinese": "喂！你听得见吗？（打电话用语）", "english": "Are you there?", "type": "句子", "keyWords": ["there"] },
    { "chinese": "好像/碰巧/据说/以前/一定有…", "english": "There seems/ appears/ happens/ is said/ used/ is sure to be ...", "type": "句式", "keyWords": ["there"] },
    { "chinese": "普遍认为在新几内亚这种物种现存有60种。", "english": "There are thought to be sixty species of this class alive in New Guinea.", "type": "句子", "keyWords": ["there"] },
    { "chinese": "（某地）有…（存在）", "english": "There lived/ stands/ remains a...", "type": "句式", "keyWords": ["there"] },
    { "chinese": "公共汽车来了。", "english": "There comes the bus.", "type": "句子", "keyWords": ["there"] },
    { "chinese": "不可能知道；难以预料", "english": "There is no telling/ knowing...", "type": "句式", "keyWords": ["there"] },
    { "chinese": "过去曾…", "english": "There was a time when...", "type": "句式", "keyWords": ["there"] },
    { "chinese": "我倒是有很多次想，你没有干过演员怎么能做这份工作。", "english": "There were times when I wondered how you could do this job without having been an actor.", "type": "句子", "keyWords": ["there"] },
    { "chinese": "没有做某事的必要", "english": "there is no need to do sth.", "type": "句式", "keyWords": ["there"] },
    { "chinese": "adv.（可与and连用）因此，以此，以这种方式", "english": "thereby", "type": "单词", "keyWords": [] },
    { "chinese": "他成了公民，因此取得了投票权。", "english": "He became a citizen, thereby gaining the right to vote.", "type": "句子", "keyWords": ["thereby"] },
    { "chinese": "adv.因此；所以（可与and连用，比so正式）", "english": "therefore", "type": "单词", "keyWords": [] },
    { "chinese": "pron./a.这些", "english": "these", "type": "单词", "keyWords": [] },
    { "chinese": "pron.他/她/它们（主格）", "english": "they", "type": "单词", "keyWords": [] },
    { "chinese": "adj.厚的；粗的；浓的；密的", "english": "thick", "type": "单词", "keyWords": [] },
    { "chinese": "v./vi.使变厚", "english": "thicken", "type": "单词", "keyWords": ["thick"] },
    { "chinese": "n.[U]厚度，浓度", "english": "thickness", "type": "单词", "keyWords": ["thick"] },
    { "chinese": "空气中浓烟弥漫。", "english": "The air was thick with smoke.", "type": "句子", "keyWords": ["thick"] },
    { "chinese": "n.[C]贼，小偷；偷窃犯", "english": "thief", "type": "单词", "keyWords": [] },
    { "chinese": "捉贼！", "english": "Stop thief!", "type": "句子", "keyWords": ["thief"] },
    { "chinese": "adj.薄的；瘦的；细的；稀疏的；v./vi.（使）变薄；（使）变细", "english": "thin", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]事情；东西；事（物）；(pl)情况", "english": "thing", "type": "单词", "keyWords": [] },
    { "chinese": "情况在好转。", "english": "Things are getting better now.", "type": "句子", "keyWords": ["thing"] },
    { "chinese": "[口]近况如何？", "english": "How are things?", "type": "句子", "keyWords": ["thing"] },
    { "chinese": "（说明理由）首先…，其次…", "english": "for one thing...for another...", "type": "短语", "keyWords": ["thing"] },
    { "chinese": "知道是一回事，会教又完全是另一回事。（学者未必是良师。）", "english": "To know is one thing, to teach is quite another.", "type": "句子", "keyWords": ["thing"] },
    { "chinese": "随遇而安，安于现状，对一切事情处之泰然", "english": "take things as they are", "type": "短语", "keyWords": ["thing"] },
    { "chinese": "万事开头难。/凡事总是由难而易。", "english": "All things are difficult before they are easy.", "type": "句子", "keyWords": ["thing"] },
    { "chinese": "v.想；认为", "english": "think", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]想法；思考；a.理性的；爱思考的", "english": "thinking", "type": "单词", "keyWords": ["think"] },
    { "chinese": "认为…是……（比较think of...as）", "english": "think sb./sth./it (to be) +n./a.", "type": "短语", "keyWords": ["think"] },
    { "chinese": "这个计划被认为是行不通的。", "english": "The plan was thought to be unfeasible.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "这个计划被认为是行不通的。", "english": "The plan was thought of as (being) unfeasible.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "再等一会儿你看好不好？", "english": "Do you think it (to be) advisable to wait a little longer?", "type": "句子", "keyWords": ["think"] },
    { "chinese": "（经…）认为/相信/觉得某人/某物…", "english": "think/ consider/ believe/ suppose sb. to have/ be sth.", "type": "短语", "keyWords": ["think"] },
    { "chinese": "巴斯曼找到了据信已在20年前死去的兄弟。", "english": "Bussman found a brother who was thought to have been killed twenty years before.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "你看我们在哪儿能搞到这种机器？（复杂特殊疑问句）", "english": "Where do you think we can get this machine?", "type": "句子", "keyWords": ["think"] },
    { "chinese": "我想/我估计（你的方法是不正确的。）", "english": "I should/ would think (your approach is incorrect.)", "type": "句子", "keyWords": ["think"] },
    { "chinese": "自言自语", "english": "think aloud", "type": "短语", "keyWords": ["think"] },
    { "chinese": "考虑；思考", "english": "think about...", "type": "短语", "keyWords": ["think"] },
    { "chinese": "想出（计划等）", "english": "think out", "type": "短语", "keyWords": ["think"] },
    { "chinese": "心中想，自忖", "english": "think to oneself", "type": "短语", "keyWords": ["think"] },
    { "chinese": "仔细考虑", "english": "think...over", "type": "短语", "keyWords": ["think"] },
    { "chinese": "再三考虑，三思", "english": "think twice", "type": "短语", "keyWords": ["think"] },
    { "chinese": "考虑（=think about）；想起，想到（某人、事）；对…有某种看法", "english": "think of", "type": "短语", "keyWords": ["think"] },
    { "chinese": "我知道你指的是谁，但是我一时想不起他的名字。", "english": "I know the person you refer to, but I cannot think of his name at the moment.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "你认为…怎么样？", "english": "What do you think of...?", "type": "句子", "keyWords": ["think"] },
    { "chinese": "轻视；认为没什么了不起；不放在眼里", "english": "think nothing/ little/ poorly of", "type": "短语", "keyWords": ["think"] },
    { "chinese": "看重；器重；评价极高；赞美", "english": "think well/ much/ highly of", "type": "短语", "keyWords": ["think"] },
    { "chinese": "他在整个地区评价很高。", "english": "He was very well thought of all over the district.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "独立思考", "english": "independent thinking", "type": "短语", "keyWords": ["think"] },
    { "chinese": "不假思索", "english": "without thinking", "type": "短语", "keyWords": ["think"] },
    { "chinese": "我们是理性的动物。", "english": "We are thinking animals.", "type": "句子", "keyWords": ["think"] },
    { "chinese": "num.第三；三分之一；第三名", "english": "third", "type": "单词", "keyWords": [] },
    { "chinese": "三分之二", "english": "two thirds", "type": "短语", "keyWords": ["third"] },
    { "chinese": "第三世界", "english": "the Third World", "type": "短语", "keyWords": ["third"] },
    { "chinese": "第三方", "english": "the third party", "type": "短语", "keyWords": ["third"] },
    { "chinese": "第三人称", "english": "the third person", "type": "短语", "keyWords": ["third"] },
    { "chinese": "adj.口渴的；干旱的；渴望的(for)；n.[U]口渴，渴望", "english": "thirsty /ˈθɜːsti/ a.；thirst n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "他渴望得到知识。", "english": "He is thirsty for knowledge.=He has a thirst for knowledge.", "type": "句子", "keyWords": ["thirsty", "thirst"] },
    { "chinese": "pron./adj.这；这个；以上或以下所述；adv.这么；这样（比较that）", "english": "this /ðɪs/ a. pron.；ad.", "type": "单词", "keyWords": [] },
    { "chinese": "这/那就是为什么我坚持这样。", "english": "This/ That is why I insisted on this.", "type": "句子", "keyWords": ["this", "that"] },
    { "chinese": "理由如下。（that一般只能承接上文）", "english": "The reason is this. (that一般只能承接上文)", "type": "句子", "keyWords": ["this", "that"] },
    { "chinese": "我从来没在外面待到这么晚。", "english": "I've never been out this late before.", "type": "句子", "keyWords": ["this"] },
    { "chinese": "尽管如此，（见for）", "english": "For all this,... (见for)", "type": "短语", "keyWords": ["this"] },
    { "chinese": "adj.彻底的，完全的；周密的；adv.彻底地；n.[U]完全，彻底", "english": "thorough /ˈθʌrə/ a.；thoroughly ad.；thoroughness n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "pron./adj.那些", "english": "those /ðəʊz/ pron./a.", "type": "单词", "keyWords": [] },
    { "chinese": "conj.虽然，尽管；adv.但（用于句中或句末）", "english": "though /ðəʊ/ conj.；ad.", "type": "单词", "keyWords": [] },
    { "chinese": "恰如，好像", "english": "as though(=as if)", "type": "短语", "keyWords": ["though"] },
    { "chinese": "即使，纵然", "english": "even though(=even if)", "type": "短语", "keyWords": ["though"] },
    { "chinese": "这是件艰难的工作，可是我还是挺喜欢的。", "english": "It's hard work. I enjoy it, though.", "type": "句子", "keyWords": ["though"] },
    { "chinese": "n.[C]打算；想法；意图（见idea）；n.[U]思考（能力），思维；思想，（特定的）思想方法；关心，着想（think的过去式和过去分词）", "english": "thought /θɔːt/ n.[C]；n.[U] (think的过去式和过去分词)", "type": "单词", "keyWords": [] },
    { "chinese": "她把视线转向别处，陷入沉思，然后毫无怨言地离开了。", "english": "She looked away for a moment, deep/ lost in thought, and then left without a word of complaint.", "type": "句子", "keyWords": ["thought"] },
    { "chinese": "他不在乎她说什么。", "english": "He didn't give much thought to what she said.", "type": "句子", "keyWords": ["thought"] },
    { "chinese": "不为……着想", "english": "have no thought for/ without thought for", "type": "短语", "keyWords": ["thought"] },
    { "chinese": "一想到……", "english": "at the thought of...", "type": "短语", "keyWords": ["thought"] },
    { "chinese": "一想到再也见不到他了，我们两眼充满泪水。", "english": "Tears fled our eyes at the thought of never seeing him again.", "type": "句子", "keyWords": ["thought"] },
    { "chinese": "又一想，再三考虑后", "english": "on a second thought/on second thoughts", "type": "短语", "keyWords": ["thought"] },
    { "chinese": "他本来想去，但进一步考虑后，打消了这个念头。", "english": "He had intended to go, but on second thoughts, he gave up the idea.", "type": "句子", "keyWords": ["thought"] },
    { "chinese": "adj.思考的，深思的；有思想的，表达思想的；考虑周到的", "english": "thoughtful /ˈθɔːtfl/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "沉思的表情", "english": "thoughtful looks", "type": "短语", "keyWords": ["thoughtful"] },
    { "chinese": "富有思想的书", "english": "a thoughtful book", "type": "短语", "keyWords": ["thoughtful"] },
    { "chinese": "你带花来真是考虑周全。", "english": "It was thoughtful of you to bring flowers.", "type": "句子", "keyWords": ["thoughtful"] },
    { "chinese": "num.千", "english": "thousand /ˈθaʊznd/ num.", "type": "单词", "keyWords": [] },
    { "chinese": "数千", "english": "thousands of...", "type": "短语", "keyWords": ["thousand"] },
    { "chinese": "大批地，成千上万地", "english": "by the thousands", "type": "短语", "keyWords": ["thousand"] },
    { "chinese": "以万计的……", "english": "tens of thousands of...", "type": "短语", "keyWords": ["thousand"] },
    { "chinese": "数以万计（的……）", "english": "thousands upon thousands (of...)", "type": "短语", "keyWords": ["thousand"] },
    { "chinese": "n.[C]线；vt.穿（针、线）等", "english": "thread /θred/ n.[C]；vt.", "type": "单词", "keyWords": [] },
    { "chinese": "穿针引线", "english": "thread a needle", "type": "短语", "keyWords": ["thread"] },
    { "chinese": "针线在抽屉里。", "english": "The needle and thread is in the drawer.", "type": "句子", "keyWords": ["thread"] },
    { "chinese": "n.[C]威胁；构成威胁的人或事物", "english": "threat /θret/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "洪水对村庄的威胁解除了。", "english": "The threat of the flood to the village has been relieved.", "type": "句子", "keyWords": ["threat"] },
    { "chinese": "v.威胁；预示（多表示预示着不希望发生的事）", "english": "threaten /ˈθretn/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "威胁要做某事", "english": "threaten to do...", "type": "短语", "keyWords": ["threaten"] },
    { "chinese": "男孩的父亲威胁说如果他再偷东西的话，就要揍他。", "english": "His father threatened to beat the boy if he stole again.", "type": "句子", "keyWords": ["threaten"] },
    { "chinese": "用……恐吓某人", "english": "threaten sb. with sth.", "type": "短语", "keyWords": ["threaten"] },
    { "chinese": "受到……的威胁", "english": "be threatened with...", "type": "短语", "keyWords": ["threaten"] },
    { "chinese": "乌云预示有雨。", "english": "Black clouds threaten to rain.", "type": "句子", "keyWords": ["threaten"] },
    { "chinese": "v./vi.（使）激动，（使）兴奋；（因突然兴奋或激动而）（使）颤抖；adj.毛骨悚然的；惊心动魄的，使人感动的；使人发抖的，震颤的", "english": "thrill /θrɪl/ vt./vi.；thrilling a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]咽喉，喉咙", "english": "throat /θrəʊt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "清清喉咙", "english": "clear one's throat", "type": "短语", "keyWords": ["throat"] },
    { "chinese": "掐住咽喉", "english": "catch/ hold/ seize/ take sb. by the throat", "type": "短语", "keyWords": ["throat"] },
    { "chinese": "梗在某人喉头", "english": "stick in sb.'s throat", "type": "短语", "keyWords": ["throat"] },
    { "chinese": "prep.通过；穿过；adv.贯穿地，从头到尾，自始至终", "english": "through /θruː/ prep.；ad.", "type": "单词", "keyWords": [] },
    { "chinese": "法国各地之旅", "english": "a tour through France", "type": "短语", "keyWords": ["through"] },
    { "chinese": "贯穿整个……", "english": "all through (the year, one's life)", "type": "短语", "keyWords": ["through"] },
    { "chinese": "请帮我接通琼斯先生的电话。", "english": "Can you put me through to Mr Jones?", "type": "句子", "keyWords": ["through"] },
    { "chinese": "你看完信了吗？", "english": "Have you read the letter through?", "type": "句子", "keyWords": ["through"] },
    { "chinese": "做好，结束（工作等）", "english": "be through with", "type": "短语", "keyWords": ["through"] },
    { "chinese": "她完成了这个项目。", "english": "She was through with the project.", "type": "句子", "keyWords": ["through"] },
    { "chinese": "prep.遍及；贯穿（时间或地区）（近all through）", "english": "throughout /θruːˈaʊt/ prep.", "type": "单词", "keyWords": [] },
    { "chinese": "全年", "english": "throughout the year/ all the year round/ the whole year", "type": "短语", "keyWords": ["throughout"] },
    { "chinese": "全世界", "english": "throughout the world/ all over the world/ the world over", "type": "短语", "keyWords": ["throughout"] },
    { "chinese": "v.投；掷；抛；扔；n.[C]投掷（距离或高度）", "english": "throw /θrəʊ/ v.；n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "匆忙地穿衣或脱衣", "english": "throw...on/off", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "丢回；掷回", "english": "throw...back", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "朝……扔……（恶意用at，善意用to）", "english": "throw...at(恶意)/to(善意)sb.", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "呕吐", "english": "throw...up", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "扔掉，抛弃；浪费（钱、时间等）；错过（机会等）", "english": "throw...away", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "投掷70米远", "english": "a throw of 70 meters", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "投石可及的距离，附近；一箭之地", "english": "a stone's throw(from...)", "type": "短语", "keyWords": ["throw"] },
    { "chinese": "n.[C]拇指", "english": "thumb /θʌm/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "笨手笨脚", "english": "be all thumbs", "type": "短语", "keyWords": ["thumb"] },
    { "chinese": "n.[U]雷；雷声；雷鸣般的响声；轰隆声；vi.打雷", "english": "thunder /ˈθʌndə/ n.[U]；vi.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]雷暴", "english": "thunderstorm /ˈθʌndəstɔːm/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]星期四", "english": "Thursday /ˈθɜːzdeɪ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adv.如此，这样；因而", "english": "thus /ðʌs/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "原文就是这样的。", "english": "The text runs thus.", "type": "句子", "keyWords": ["thus"] },
    { "chinese": "n.[C]（车、戏等）票，票证，入场券；（给违反交通规则者的）传票", "english": "ticket /ˈtɪkɪt/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "超速违章通知单/星期五的票", "english": "a ticket for speeding/ Friday", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "来回票", "english": "a return ticket", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "入场票", "english": "an admission ticket", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "单程票", "english": "a one-way ticket", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "季票，定期票", "english": "season ticket", "type": "短语", "keyWords": ["ticket"] },
    { "chinese": "n.[C]潮（汐）；潮水；潮流，趋势；浪潮；v.（使）随潮水漂流", "english": "tide /taɪd/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "倒行逆施", "english": "attempt to go against the tide of history", "type": "短语", "keyWords": ["tide"] },
    { "chinese": "顺应潮流；随波逐流", "english": "go/ swim with the tide", "type": "短语", "keyWords": ["tide"] },
    { "chinese": "岁月不等人。/时不我待。", "english": "Time and tide wait for no man.", "type": "句子", "keyWords": ["tide"] },
    { "chinese": "adj.整齐的，整洁的（反untidy）；v.使整洁（可加up）", "english": "tidy /ˈtaɪdi/ a.；v.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]领带；领结；平局；联系，纽带；v.拴，扎，系上", "english": "tie /taɪ/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "血缘关系", "english": "a blood tie", "type": "短语", "keyWords": ["tie"] },
    { "chinese": "把风筝拴到柱子上", "english": "tie the kite to a post", "type": "短语", "keyWords": ["tie"] },
    { "chinese": "这场比赛打成平局。", "english": "The game ended in a tie.", "type": "句子", "keyWords": ["tie"] },
    { "chinese": "n.[C]老虎", "english": "tiger /ˈtaɪɡə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.紧的；紧身的；拉紧的；adv.紧紧地；v.使……紧；紧缩银根", "english": "tight /taɪt/ a.；ad.；tighten v.；tight money", "type": "单词", "keyWords": [] },
    { "chinese": "把它紧紧握住", "english": "hold it tight", "type": "短语", "keyWords": ["tight"] },
    { "chinese": "conj./prep.直到……（一般不位于句首）", "english": "till /tɪl/ conj./prep.", "type": "单词", "keyWords": [] },
    { "chinese": "从早到晚", "english": "from morning till night", "type": "短语", "keyWords": ["till"] },
    { "chinese": "n.[C]次；回；[U]时间；(pl.)时期；v.测时间；安排……的时间；adj.及时（的）；适时（发生）的；n.[C]时刻表；课程表", "english": "time /taɪm/ n.[C]/[U]/(pl.)；v.；time a.；timetable n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "提前", "english": "ahead of time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "暂时", "english": "for the time being", "type": "短语", "keyWords": ["time"] },
    { "chinese": "一度，暂时", "english": "for a time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "从前", "english": "once upon a time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "曾经；一度", "english": "at one time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "一次一个", "english": "one at a time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "同时", "english": "at the same time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "一次又一次；重复地", "english": "time and again", "type": "短语", "keyWords": ["time"] },
    { "chinese": "过时；落后", "english": "behind the times", "type": "短语", "keyWords": ["time"] },
    { "chinese": "有时，不时地", "english": "from time to time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "……的时候", "english": "by the time...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "及时；最终（经过适当时候）", "english": "in time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "与时俱进", "english": "change with the times", "type": "短语", "keyWords": ["time"] },
    { "chinese": "时间才会给出答案。", "english": "Only time will tell.", "type": "句子", "keyWords": ["time"] },
    { "chinese": "耗费时间的", "english": "time-consuming", "type": "短语", "keyWords": ["time"] },
    { "chinese": "有时间做某事", "english": "have the time for...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "一直；始终", "english": "all the time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "有时", "english": "at times", "type": "短语", "keyWords": ["time"] },
    { "chinese": "立刻；很快", "english": "in no time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "准时", "english": "on time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "定时炸弹", "english": "a time bomb", "type": "短语", "keyWords": ["time"] },
    { "chinese": "光阴似箭！", "english": "Time flies!", "type": "句子", "keyWords": ["time"] },
    { "chinese": "节约时间的", "english": "time-saving", "type": "短语", "keyWords": ["time"] },
    { "chinese": "常常；多次", "english": "many a time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "在其他时候；在另外场合", "english": "at other times", "type": "短语", "keyWords": ["time"] },
    { "chinese": "（钟、表）走时准", "english": "keep good time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "消磨时间，打发时间", "english": "kill time = pass the time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "做某事时碰到困难", "english": "have a hard time (in) doing sth.", "type": "短语", "keyWords": ["time"] },
    { "chinese": "抓紧时间做某事", "english": "lose no time in doing sth.", "type": "短语", "keyWords": ["time"] },
    { "chinese": "（祝你）过（或玩）得愉快", "english": "have a good time", "type": "短语", "keyWords": ["time"] },
    { "chinese": "短时间内，一度", "english": "for a time/ while/ moment", "type": "短语", "keyWords": ["time"] },
    { "chinese": "他深思了一会儿。", "english": "He remained thoughtful for a time.", "type": "句子", "keyWords": ["time", "thoughtful"] },
    { "chinese": "随着时间的推移", "english": "As time goes on...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "当……（近each time, next time, the first time 引导句子）", "english": "every time...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "来得及做某事", "english": "...in time (to do sth.)", "type": "短语", "keyWords": ["time"] },
    { "chinese": "她到得正是时候，刚好赶上参加考试。", "english": "She arrived just in time to take the exam.", "type": "句子", "keyWords": ["time"] },
    { "chinese": "应该立刻做某事的时候（虚拟语气）", "english": "It's about/high time (that)...", "type": "短语", "keyWords": ["time"] },
    { "chinese": "你们该起来了。", "english": "It's high time you were all up.", "type": "句子", "keyWords": ["time"] },
    { "chinese": "adj.胆怯的；羞怯的；n.[U]胆怯", "english": "timid /ˈtɪmɪd/ a.；timidity n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]罐头；v.把……保存或装在罐头中；罐头食品", "english": "tin /tɪn/ n.[C]；v.；tinned food", "type": "单词", "keyWords": [] },
    { "chinese": "adj.微小的；极小的", "english": "tiny /ˈtaɪni/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]顶端，尖端；小费；倾斜，倾侧；告诫，指点；v.给……小费；（使）倾斜；（使）翻倒；（使）倾翻；n.[C]脚趾尖；vi.踮着脚走；蹑手蹑脚地走", "english": "tip /tɪp/ n.[C]；v.；tiptoe /ˈtɪptəʊ/ n.[C]；vi.", "type": "单词", "keyWords": [] },
    { "chinese": "差点说出", "english": "on the tip of one's tongue", "type": "短语", "keyWords": ["tip"] },
    { "chinese": "她的名字就在我嘴边却说不出来。", "english": "I have her name on the tip of my tongue.", "type": "句子", "keyWords": ["tip"] },
    { "chinese": "用脚尖走", "english": "on tiptoe", "type": "短语", "keyWords": ["tiptoe"] },
    { "chinese": "v.使疲劳；使厌倦；n.[C]轮胎", "english": "tire /ˈtaɪə/ v.；n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "使……十分疲劳", "english": "tire...out", "type": "短语", "keyWords": ["tire"] },
    { "chinese": "adj.累的，疲劳的；厌倦的(of)；n.[U]疲劳；adj.累人的", "english": "tired /ˈtaɪəd/ a.；tiredness n.[U]；tiring a.", "type": "单词", "keyWords": [] },
    { "chinese": "对……厌倦", "english": "be tired of", "type": "短语", "keyWords": ["tired"] },
    { "chinese": "累得要死，累极了", "english": "be tired out = be worn out", "type": "短语", "keyWords": ["tired"] },
    { "chinese": "adj.令人厌烦的；讨厌的", "english": "tiresome /ˈtaɪəsəm/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][生]组织；薄的织物；手巾纸；卫生纸；[U]棉纸，薄纸", "english": "tissue /ˈtɪʃuː/ n.[C]；tissue paper n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "肌肉组织", "english": "the muscular tissue", "type": "短语", "keyWords": ["tissue"] },
    { "chinese": "n.[C]标题；题目；称号；职称；头衔；(常pl.)字幕；adj.有头衔的", "english": "title /ˈtaɪtl/ n.[C]；titled a.", "type": "单词", "keyWords": [] },
    { "chinese": "prep.（表示方向）到，向，往；（表示间接关系）给……，于……", "english": "to /tuː, tə, tu/ prep.", "type": "单词", "keyWords": [] },
    { "chinese": "中肯", "english": "to the point", "type": "短语", "keyWords": ["to"] },
    { "chinese": "在一定程度上", "english": "to some extent", "type": "短语", "keyWords": ["to"] },
    { "chinese": "为……干杯", "english": "drink to", "type": "短语", "keyWords": ["to"] },
    { "chinese": "来回地，来来往往地", "english": "to and fro", "type": "短语", "keyWords": ["to"] },
    { "chinese": "村庄位于树林的东面。", "english": "The village is to the east of the woods.", "type": "句子", "keyWords": ["to"] },
    { "chinese": "这把锁的钥匙", "english": "the key to the lock", "type": "短语", "keyWords": ["to"] },
    { "chinese": "部长的私人秘书", "english": "a private secretary to the minister", "type": "短语", "keyWords": ["to"] },
    { "chinese": "是他国家的光荣", "english": "be an honor to his country", "type": "短语", "keyWords": ["to"] },
    { "chinese": "随着曲子起舞/唱歌", "english": "sing/dance to the tune", "type": "短语", "keyWords": ["to"] },
    { "chinese": "这画栩栩如生。如果你想去的话就去吧。", "english": "The picture is true to life. Go if you want to.", "type": "句子", "keyWords": ["to", "true"] },
    { "chinese": "n.[C]祝酒；干杯；烤，烘；吐司；v.向……祝酒；v.烤，烘；n.烤箱", "english": "toast /təʊst/ n.[C]；v.；toaster n.", "type": "单词", "keyWords": [] },
    { "chinese": "为……干杯", "english": "drink a toast to sb./ sth. = drink to sb./ sth. = toast sb./ sth.", "type": "短语", "keyWords": ["toast"] },
    { "chinese": "我们为新娘新郎干杯。", "english": "We toasted the bride and bridegroom.", "type": "句子", "keyWords": ["toast"] },
    { "chinese": "n.[U]烟草", "english": "tobacco /təˈbækəʊ/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.（常用在名词后构成复合词）未来的，即将的", "english": "to-be /ˈtuːbi/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "未来的新娘", "english": "a bride-to-be", "type": "短语", "keyWords": ["to-be"] },
    { "chinese": "某人的未婚妻", "english": "sb.'s wife-to-be", "type": "短语", "keyWords": ["to-be"] },
    { "chinese": "adv.今天", "english": "today /təˈdeɪ/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]脚趾，足尖；（鞋袜等的）足尖部", "english": "toe /təʊ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adv.一起", "english": "together /təˈɡeðə/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]厕所；卫生间；盥洗室；抽水马桶", "english": "toilet /ˈtɔɪlət/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "vt.忍受，容忍", "english": "tolerate /ˈtɒləreɪt/ vt.", "type": "单词", "keyWords": [] },
    { "chinese": "adj.容忍的；宽恕的(of)", "english": "tolerant /ˈtɒlərənt/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](pl.tomatoes)西红柿，番茄", "english": "tomato /təˈmɑːtəʊ/ n.[C](pl.tomatoes)", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]坟墓；冢；葬身之地", "english": "tomb /tuːm/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "ad.[U]明天", "english": "tomorrow /təˈmɒrəʊ/ ad.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "未来世界将和现在大不相同。", "english": "The world of tomorrow will be quite different from the world of today.", "type": "句子", "keyWords": ["tomorrow", "today"] },
    { "chinese": "今日事今日毕。", "english": "Never put off till tomorrow what you can do today.", "type": "句子", "keyWords": ["tomorrow", "today", "till"] },
    { "chinese": "切莫依赖明天。", "english": "Tomorrow never comes.", "type": "句子", "keyWords": ["tomorrow"] },
    { "chinese": "n.[C]吨；n.[C]公吨", "english": "ton /tʌn/ n.[C]；tonne /tʌn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]语气；音调；音质", "english": "tone /təʊn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "优美的声音", "english": "sweet tone", "type": "短语", "keyWords": ["tone"] },
    { "chinese": "带着怒气说话", "english": "speak in an angry tone", "type": "短语", "keyWords": ["tone"] },
    { "chinese": "用升→降→升调", "english": "in the rise-fall-rise tone", "type": "短语", "keyWords": ["tone"] },
    { "chinese": "n.[C]舌头；语言；方言，土语", "english": "tongue /tʌŋ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "本国语", "english": "mother/ native tongue", "type": "短语", "keyWords": ["tongue"] },
    { "chinese": "绕口令", "english": "tongue twister", "type": "短语", "keyWords": ["tongue"] },
    { "chinese": "一言不发，保持安静；（用于祈使句中）住嘴", "english": "hold one's tongue", "type": "短语", "keyWords": ["tongue"] },
    { "chinese": "失声；（由于震惊等）失去说话的能力", "english": "lose one's tongue", "type": "短语", "keyWords": ["tongue"] },
    { "chinese": "adv.今夜，今晚；n.[U]今夜，今晚", "english": "tonight /təˈnaɪt/ ad.；n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "adv.也（否定句中用either）；太", "english": "too /tuː/ ad.", "type": "单词", "keyWords": [] },
    { "chinese": "太……，远过于（后接形容词/副词）", "english": "far too + a./ad.", "type": "短语", "keyWords": ["too"] },
    { "chinese": "有些太（后接形容词/副词）", "english": "rather too + a./ad.", "type": "短语", "keyWords": ["too"] },
    { "chinese": "太……（后接形容词/副词）", "english": "much too + a./ad.", "type": "短语", "keyWords": ["too"] },
    { "chinese": "实在太（快/早等）", "english": "all too (quickly/ soon)", "type": "短语", "keyWords": ["too"] },
    { "chinese": "我也到过纽约。", "english": "I, too, have been to New York.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "此事的确了结得太快了！", "english": "It was over all too soon!", "type": "句子", "keyWords": ["too"] },
    { "chinese": "对我们别太厉害了。", "english": "Don't be too hard on us.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "（对于……说）对付不了，过分；无法承受（后接不可数名词）", "english": "too much (+n.(U)) (for...)", "type": "短语", "keyWords": ["too"] },
    { "chinese": "全天工作她恐怕吃不消。", "english": "A full-time job may be too much for her.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "太……（表肯定）", "english": "only/but all too...", "type": "短语", "keyWords": ["too"] },
    { "chinese": "他非常愿意帮助你。", "english": "He's only too willing to help you.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "他很细心，不会不注意到这点的。", "english": "He is too careful not to have noticed it.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "……也不过分", "english": "can't...too...", "type": "短语", "keyWords": ["too"] },
    { "chinese": "在这种问题上再怎么小心都不为过。", "english": "One can't be too careful in matters like this.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "我们再怎么强调保护眼睛的重要性也不为过。", "english": "We cannot emphasize the importance of protecting our eyes too much.", "type": "句子", "keyWords": ["too"] },
    { "chinese": "n.[C]工具；器具；器械；手段", "english": "tool /tuːl/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.(pl.teeth)齿；n.[C]牙刷；n.[U]牙膏；n.[U]牙痛（可与a连用）", "english": "tooth /tuːθ/ n.(pl.teeth)；toothbrush n.[C]；toothpaste n.[U]；toothache n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "武装到牙齿", "english": "be armed to the teeth", "type": "短语", "keyWords": ["tooth"] },
    { "chinese": "张牙舞爪；作威胁状", "english": "show one's teeth", "type": "短语", "keyWords": ["tooth"] },
    { "chinese": "n.[C]顶部，顶点，顶端；上部/端/面；最高点；最高地位；adj.最好的；最上面的；最优良的；最重要的；vt.高过；胜过；成……之冠/首；给……加盖（或顶）", "english": "top /tɒp/ n.[C]；a.；vt.", "type": "单词", "keyWords": [] },
    { "chinese": "在……顶上/上面", "english": "on top of", "type": "短语", "keyWords": ["top"] },
    { "chinese": "优等生，尖子学生", "english": "top student", "type": "短语", "keyWords": ["top"] },
    { "chinese": "最高级的", "english": "top-class", "type": "短语", "keyWords": ["top"] },
    { "chinese": "最高级别的", "english": "top-level", "type": "短语", "keyWords": ["top"] },
    { "chinese": "绝密的", "english": "top secret", "type": "短语", "keyWords": ["top"] },
    { "chinese": "在……顶部/上（反at the bottom of）", "english": "at the top of", "type": "短语", "keyWords": ["top"] },
    { "chinese": "非常愉快或自豪", "english": "feel on top of the world", "type": "短语", "keyWords": ["top"] },
    { "chinese": "他比他父亲高出半头。", "english": "He tops his father by half a head.", "type": "句子", "keyWords": ["top"] },
    { "chinese": "她在班里排名第一。", "english": "She topped her class.", "type": "句子", "keyWords": ["top"] },
    { "chinese": "n.[C]题目；话题，主题", "english": "topic /ˈtɒpɪk/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]火把，火炬；（英）手电筒", "english": "torch /tɔːtʃ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]龙卷风；旋风；飓风", "english": "tornado /tɔːˈneɪdəʊ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "adj.总（计）的；全部的；完全的；n.[C]总数，总计；v.合计；计算……的总和；adv.完全；彻底地", "english": "total /ˈtəʊtl/ a.；n.[C]；v.；totally ad.", "type": "单词", "keyWords": [] },
    { "chinese": "彻头彻尾的傻瓜", "english": "a total fool", "type": "短语", "keyWords": ["total"] },
    { "chinese": "彻底的失败", "english": "a total failure", "type": "短语", "keyWords": ["total"] },
    { "chinese": "总计（近in all）", "english": "in total", "type": "短语", "keyWords": ["total"] },
    { "chinese": "总产量", "english": "total output", "type": "短语", "keyWords": ["total"] },
    { "chinese": "总计30美元（近add up to, amount to, come to）", "english": "total (1) 30", "type": "短语", "keyWords": ["total"] },
    { "chinese": "我完全同意。", "english": "I totally agree.", "type": "句子", "keyWords": ["totally"] },
    { "chinese": "v.触摸；接触；涉及；感动（见affect）；adj.令人感动的；adj.受感动的", "english": "touch /tʌtʃ/ v.；touching a.；touched a.", "type": "单词", "keyWords": [] },
    { "chinese": "与……有/无联系；了解/不了解", "english": "be in/out of touch with...", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "使A与B取得联系", "english": "bring A into touch with B", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "与……取得联系", "english": "get in touch with...", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "与……保持联系", "english": "keep in touch with...", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "与……失去联系", "english": "lose touch with...", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "一碰就倒", "english": "fall at a touch", "type": "短语", "keyWords": ["touch"] },
    { "chinese": "adj.坚韧的；能吃苦耐劳的；难做的；固执的；顽强的；强硬的；蛮横的；v.使……坚韧", "english": "tough /tʌf/ a.；toughen v.", "type": "单词", "keyWords": [] },
    { "chinese": "嚼不动的肉", "english": "tough meat", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "棘手的工作", "english": "a tough job", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "一个严冬", "english": "a tough winter", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "难伺候的顾客", "english": "a tough customer", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "无赖", "english": "a tough guy", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "意志坚强的人", "english": "a tough-minded person", "type": "短语", "keyWords": ["tough"] },
    { "chinese": "n.[C]/v.旅行；参观；游览；观光；游历；巡回演出/比赛", "english": "tour /tʊə/ n.[C]/v.", "type": "单词", "keyWords": [] },
    { "chinese": "环球旅行", "english": "a round-the-world tour", "type": "短语", "keyWords": ["tour"] },
    { "chinese": "巡回音乐会", "english": "a concert tour", "type": "短语", "keyWords": ["tour"] },
    { "chinese": "漫游；巡回；周游世界", "english": "go on/take a tour of the world", "type": "短语", "keyWords": ["tour"] },
    { "chinese": "周游（世界）", "english": "make a tour of (the world)", "type": "短语", "keyWords": ["tour"] },
    { "chinese": "n.[C]旅游的（人）；游览的（人）；观光的（人）；n.[U]旅游；旅游业", "english": "tourist /ˈtʊərɪst/ n.[C]；tourism n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "prep.朝，向", "english": "toward(s) /təˈwɔːd(z)/ prep.", "type": "单词", "keyWords": [] },
    { "chinese": "将近晚上时天开始下雨了。", "english": "Towards evening, it began to rain.", "type": "句子", "keyWords": ["toward(s)"] },
    { "chinese": "n.[C]毛巾", "english": "towel /ˈtaʊəl/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]塔；塔楼；（机场的）塔台", "english": "tower /ˈtaʊə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "瞭望楼；机场指挥塔", "english": "a watch tower；the airport control tower", "type": "短语", "keyWords": ["tower"] },
    { "chinese": "万丈高楼平地起。", "english": "The highest towers begin from the ground.", "type": "句子", "keyWords": ["tower"] },
    { "chinese": "n.[C]城镇；（不用冠词）市（商业）中心，城区", "english": "town /taʊn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "进城", "english": "go to town", "type": "短语", "keyWords": ["town"] },
    { "chinese": "在城里", "english": "in town", "type": "短语", "keyWords": ["town"] },
    { "chinese": "不在城里，在乡下", "english": "out of town", "type": "短语", "keyWords": ["town"] },
    { "chinese": "全体市民都很愤慨。", "english": "The whole town was angry.", "type": "句子", "keyWords": ["town"] },
    { "chinese": "n.[C]镇民；市民", "english": "townsman /ˈtaʊnzmən/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]玩具；无价值的东西", "english": "toy /tɔɪ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "玩具车", "english": "a toy car", "type": "短语", "keyWords": ["toy"] },
    { "chinese": "n.[C]痕迹，踪迹；足迹；小径，小路；少量；v.跟踪；追踪；追溯(back)", "english": "trace /treɪs/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "岁月在她脸上留下了痕迹。", "english": "Age has left its traces on her face.", "type": "句子", "keyWords": ["trace"] },
    { "chinese": "一丝笑意", "english": "a mere trace of a smile", "type": "短语", "keyWords": ["trace"] },
    { "chinese": "追查谣言的根源", "english": "trace a rumour to its source", "type": "短语", "keyWords": ["trace"] },
    { "chinese": "n.[C]路径，轨迹；足迹；车辙；小道；跑道；轨道；田径运动；v.跟踪", "english": "track /træk/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "径赛项目", "english": "track events=tracks", "type": "短语", "keyWords": ["track"] },
    { "chinese": "风暴的路径", "english": "the track of a storm", "type": "短语", "keyWords": ["track"] },
    { "chinese": "跟踪雪地里的足迹", "english": "follow the tracks in the snow", "type": "短语", "keyWords": ["track"] },
    { "chinese": "n.[C]拖拉机；牵引车", "english": "tractor /ˈtræktə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]贸易，商业；n.[C]行业；v.互相交换，与……进行交换；vi.从事贸易，进行交易；adj.贸易的，交易的；n.[C]商人", "english": "trade /treɪd/ n.[U]/[C]；v.；vi.；a.；trader n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "工会", "english": "trade union", "type": "短语", "keyWords": ["trade"] },
    { "chinese": "贸易谈判", "english": "trade talks", "type": "短语", "keyWords": ["trade"] },
    { "chinese": "用A换取B", "english": "trade A for B", "type": "短语", "keyWords": ["trade"] },
    { "chinese": "和某人做……生意", "english": "trade with sb. in sth.", "type": "短语", "keyWords": ["trade"] },
    { "chinese": "n.[C]商标", "english": "trademark /ˈtreɪdmɑːk/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]传统；adj.传统的；习俗的；惯例的", "english": "tradition /trəˈdɪʃn/ n.[C][U]；traditional a.", "type": "单词", "keyWords": [] },
    { "chinese": "按照传统", "english": "by tradition", "type": "短语", "keyWords": ["tradition"] },
    { "chinese": "中医", "english": "traditional Chinese medicine", "type": "短语", "keyWords": ["traditional"] },
    { "chinese": "n.[U]交通（量）；通行，往来；空中交通", "english": "traffic /ˈtræfɪk/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "交通指示灯", "english": "traffic lights", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "交通规则", "english": "traffic regulations/ rules", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "交通堵塞", "english": "a traffic jam", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "通车", "english": "be open to traffic", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "出交通事故", "english": "have traffic accidents", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "交通繁忙", "english": "full of heavy/much traffic", "type": "短语", "keyWords": ["traffic"] },
    { "chinese": "n.[C][U]悲剧；灾难，惨事；adj.悲剧的；悲惨的", "english": "tragedy /ˈtrædʒədi/ n.[C][U]；tragic a.", "type": "单词", "keyWords": [] },
    { "chinese": "某人的巨大不幸", "english": "a tragedy to sb.", "type": "短语", "keyWords": ["tragedy"] },
    { "chinese": "以惨祸而告终", "english": "end in tragedy", "type": "短语", "keyWords": ["tragedy"] },
    { "chinese": "v.训练；培养；锻炼；n.[C]火车，列车；一连串，一系列", "english": "train /treɪn/ v.；n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "为田径赛训练（运动员）", "english": "train (athletes) for track-and-field competitions", "type": "短语", "keyWords": ["train"] },
    { "chinese": "她在学习护理。", "english": "She is training to be a nurse.", "type": "句子", "keyWords": ["train"] },
    { "chinese": "在……换乘火车", "english": "change trains at...", "type": "短语", "keyWords": ["train"] },
    { "chinese": "一列快车", "english": "an express train", "type": "短语", "keyWords": ["train"] },
    { "chinese": "训练某人做某事", "english": "train sb. to do sth.", "type": "短语", "keyWords": ["train"] },
    { "chinese": "一连串事件", "english": "a train of events", "type": "短语", "keyWords": ["train"] },
    { "chinese": "n.[U]训练；锻炼；培养；n.[C]教练员；驯兽师", "english": "training /ˈtreɪnɪŋ/ n.[U]；trainer n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "表示“横穿，变化，转移”（前缀）", "english": "trans-（前缀）", "type": "单词", "keyWords": [] },
    { "chinese": "v.搬授；转移；转换；调动(to)", "english": "transfer /trænsˈfɜː/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "被调职", "english": "be transferred to another post", "type": "短语", "keyWords": ["transfer"] },
    { "chinese": "转让财产给某人", "english": "transfer property to a person", "type": "短语", "keyWords": ["transfer"] },
    { "chinese": "他已被从北京调到了上海。", "english": "He has been transferred from Beijing to Shanghai.", "type": "句子", "keyWords": ["transfer"] },
    { "chinese": "v.改造；改革；（使）彻底改变（形式、外表、性质、机能等）", "english": "transform /trænsˈfɔːm/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "v.译；转换；n.[U]翻译；n.[C]译文；v.把……翻译成……；把……变成……", "english": "translate /trænsˈleɪt/ v.；translation n.[U]/[C]；translate...into...", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]译员；翻译者；译码机", "english": "translator /trænsˈleɪtə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "vt.传送，输送；播送；遗传；vi.播送（或发射）信号；流传下来；n.[C][U]（无线电、电视等信号的）播送，发送；（电台或电视等）信息，广播；传递，传播，传染；n.[C]发射机，发射台；传播者，传递媒介", "english": "transmit /trænsˈmɪt/ vt.；vi.；transmission n.[C][U]；transmitter n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "数码相机拍摄、处理、传输图像的速度惊人。", "english": "The speed with which digital cameras can take, process, and transmit an image is great.", "type": "句子", "keyWords": ["transmit"] },
    { "chinese": "在一项长达12年的研究中，利亚布克和列兹尼科娃发现了蚂蚁可以传递非常复杂信息的证据。", "english": "In a twelve-year programme of work, Ryabko and Reznikova have found evidence that ants can transmit very complex messages.", "type": "句子", "keyWords": ["transmit"] },
    { "chinese": "v.（尤指）移植（植物、组织或器官等）", "english": "transplant /trænsˈplɑːnt/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "v.运输；运送；输送；n.[U]运输", "english": "transport /trænsˈpɔːt/ v.；/ˈtrænspɔːt/ n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]运输（系统）；公共交通（网）；客运；货运；[美]运输工具", "english": "transportation /ˌtrænspɔːˈteɪʃn/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]陷阱，圈套，诡计；夹子；v.设圈套；诱骗某人；使陷于困境", "english": "trap /træp/ n.[C]；v.", "type": "单词", "keyWords": [] },
    { "chinese": "陷入；被困在（近be stranded in）", "english": "be trapped in (a burning house)", "type": "短语", "keyWords": ["trap"] },
    { "chinese": "诱捕小偷", "english": "set a trap for the thieves (trap the thieves)", "type": "短语", "keyWords": ["trap"] },
    { "chinese": "v.旅行；（光、物）移动、走、行进（辨析见tour）；n.[U]旅行", "english": "travel /ˈtrævl/ v.；n.[U]", "type": "单词", "keyWords": [] },
    { "chinese": "周游世界", "english": "travel round the world", "type": "短语", "keyWords": ["travel"] },
    { "chinese": "旅行社；旅行包", "english": "travel agency；a travelling bag", "type": "短语", "keyWords": ["travel"] },
    { "chinese": "光比声音传得快。", "english": "Light travels faster than sound.", "type": "句子", "keyWords": ["travel"] },
    { "chinese": "n.[C]旅客；旅行者，游客", "english": "travel(l)er /ˈtrævlə/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]托盘", "english": "tray /treɪ/ n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]（或pl.）宝物；金银财宝；财富；珍品；v.珍惜；珍爱", "english": "treasure /ˈtreʒə/ n.[U](或pl.)；v.", "type": "单词", "keyWords": [] },
    { "chinese": "近来，找到失去的财宝的梦想几乎变成了现实。", "english": "Dreams of finding lost treasure almost came true recently.", "type": "句子", "keyWords": ["treasure"] },
    { "chinese": "他珍爱母亲送给他的表。", "english": "He treasures the watch his mother gave him.", "type": "句子", "keyWords": ["treasure"] },
    { "chinese": "v.对待，视为，看待；医治，医疗；处理；请客；n.[C]请客，款待；乐事", "english": "treat /triːt/ v.；n.[C]", "type": "单词", "keyWords": [] },
    { "chinese": "把某物/某人看作……；像对待……一样对待……", "english": "treat sth./sb. as...；treat...like...", "type": "短语", "keyWords": ["treat"] },
    { "chinese": "此产品不是用于治疗、治愈或预防任何疾病的。", "english": "This product is not intended to treat, cure or prevent any disease.", "type": "句子", "keyWords": ["treat"] },
    { "chinese": "给某人/自己用……来款待；舍得（吃、穿等）", "english": "treat sb./ oneself to...", "type": "短语", "keyWords": ["treat"] },
    { "chinese": "请某人吃一杯冰淇淋", "english": "treat sb. to an ice-cream", "type": "短语", "keyWords": ["treat"] },
    { "chinese": "她花了一天时间在乡间游玩。", "english": "She treated herself to a day in the country.", "type": "句子", "keyWords": ["treat"] },
    { "chinese": "这次我请客。", "english": "It's my treat this time.", "type": "句子", "keyWords": ["treat"] },
    { "chinese": "对一个生活在城市里的人来说，在乡下待上一天真是一件乐事。", "english": "A day in the country is a real treat for a city dweller.", "type": "句子", "keyWords": ["treat"] },
    { "chinese": "n.[U]对待；待遇；n.[C]治疗；疗法；疗程；n.[C][U]处理", "english": "treatment /ˈtriːtmənt/ n.[U]/[C]", "type": "单词", "keyWords": [] },
    { "chinese": "在治疗中", "english": "under treatment", "type": "短语", "keyWords": ["treatment"] },
    { "chinese": "流感新疗法", "english": "a new treatment for flu", "type": "短语", "keyWords": ["treatment"] },
    { "chinese": "n.[C]树；家谱，世系图", "english": "tree /triː/ n.[C]；a family tree", "type": "单词", "keyWords": [] },
    { "chinese": "谚：树倒在何处，就躺在何处。（指事物有其必然的规律）", "english": "谚：As a tree falls, so shall it lie.", "type": "句子", "keyWords": ["tree"] },
    { "chinese": "谚：观其果而知其树；观其行而知其人。", "english": "谚：A tree is known by its fruit.", "type": "句子", "keyWords": ["tree"] },
    { "chinese": "v.抖动，摇动，颤抖（辨析见shake）", "english": "tremble /ˈtrembl/ v.", "type": "单词", "keyWords": [] },
    { "chinese": "因寒冷/愤怒/害怕而颤抖", "english": "tremble with cold/ anger/ fear", "type": "短语", "keyWords": ["tremble"] },
    { "chinese": "我一想到这件事就不寒而栗。", "english": "I tremble at the very thought of it.", "type": "句子", "keyWords": ["tremble", "thought"] },
    { "chinese": "颤抖的手", "english": "trembling hand", "type": "短语", "keyWords": ["tremble"] },
    { "chinese": "用颤抖的声音", "english": "in a trembling voice", "type": "短语", "keyWords": ["tremble"] },
    { "chinese": "adj.极大的，巨大的（近enormous, immense, huge, gigantic, colossal, vast）", "english": "tremendous /trəˈmendəs/ a.", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（路、河流等）走向；倾向；趋势；时尚；vi.倾向，趋向", "english": "trend /trend/ n.[C]；vi.", "type": "单词", "keyWords": [] },
    { "chinese": "海岸线的走向", "english": "the trend of a coast-line", "type": "短语", "keyWords": ["trend"] },
    { "chinese": "现代生活的趋势", "english": "the trend of modern living", "type": "短语", "keyWords": ["trend"] },
    { "chinese": "n.趋势；趋向", "english": "trend", "type": "单词", "keyWords": [] },
    { "chinese": "家庭逐渐缩小的趋向", "english": "the trend to/towards smaller families", "type": "短语", "keyWords": ["trend"] },
    { "chinese": "服装界最新潮流", "english": "the latest trend in fashion", "type": "短语", "keyWords": ["trend"] },
    { "chinese": "创新风；领导新潮流", "english": "set a/the trend", "type": "短语", "keyWords": ["trend"] },
    { "chinese": "n.诡计；戏法；技巧 v.欺诈", "english": "trick", "type": "单词", "keyWords": [] },
    { "chinese": "adj.诡计多端的", "english": "tricky", "type": "单词", "keyWords": [] },
    { "chinese": "我会玩魔术。", "english": "I can do magic tricks.", "type": "句子", "keyWords": ["trick"] },
    { "chinese": "学这行生意的诀窍", "english": "learn the tricks of the trade", "type": "短语", "keyWords": ["trick"] },
    { "chinese": "用计诱使某人（做）某事", "english": "trick/trap sb. into (doing) sth.", "type": "短语", "keyWords": ["trick"] },
    { "chinese": "他哄骗我给了他钱。", "english": "He tricked me into giving him the money.", "type": "句子", "keyWords": ["trick"] },
    { "chinese": "骗走某人某物", "english": "trick sb. out of sth.", "type": "短语", "keyWords": ["trick"] },
    { "chinese": "捉弄某人；开某人玩笑", "english": "play a trick on sb.", "type": "短语", "keyWords": ["trick"] },
    { "chinese": "n.旅行；旅程 vi.旅行；出行；轻捷地走；绊；倾斜；失误 vt.将…绊倒；使犯错误；意外触动", "english": "trip", "type": "单词", "keyWords": [] },
    { "chinese": "她说了声再见就连蹦带跳地沿路走了。", "english": "She said goodbye and tripped off along the road.", "type": "句子", "keyWords": ["trip"] },
    { "chinese": "她绊了一跤，膝盖磕在桌子上。", "english": "She tripped and banged her knee on the desk.", "type": "句子", "keyWords": ["trip"] },
    { "chinese": "这道难题我们答错了。", "english": "The difficult question tripped us.", "type": "句子", "keyWords": ["trip"] },
    { "chinese": "在去…的旅途中", "english": "on a trip to...", "type": "短语", "keyWords": ["trip"] },
    { "chinese": "去…旅行", "english": "make/go on/take a trip to...", "type": "短语", "keyWords": ["trip"] },
    { "chinese": "n.手推车；电车", "english": "trolley", "type": "单词", "keyWords": [] },
    { "chinese": "n.无轨电车", "english": "trolleybus", "type": "单词", "keyWords": [] },
    { "chinese": "n.军队，部队；一群，一队 vi.成群结队地走，排队前进", "english": "troop", "type": "单词", "keyWords": [] },
    { "chinese": "学生们列队走入礼堂。", "english": "The students trooped into the hall.", "type": "句子", "keyWords": ["troop"] },
    { "chinese": "adj.热带的", "english": "tropical", "type": "单词", "keyWords": [] },
    { "chinese": "热带植物", "english": "tropical plant", "type": "短语", "keyWords": ["tropical"] },
    { "chinese": "热带", "english": "tropical zone", "type": "短语", "keyWords": ["tropical"] },
    { "chinese": "n.麻烦；烦恼；困难；纷争；故障 v.（使）麻烦；（使）苦恼", "english": "trouble", "type": "单词", "keyWords": [] },
    { "chinese": "处于困境", "english": "be in trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "（使某人）陷入困境", "english": "get (sb.) into trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "心脏疾病", "english": "heart trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "制造麻烦，捣乱", "english": "make trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "自寻烦恼", "english": "ask for/look for trouble", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "在（做）某事上有困难", "english": "have trouble/difficulty (in) doing/with sth.", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "麻烦某人去做某事", "english": "trouble sb. to do sth.", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "我能麻烦你把衬衫烫一下吗？", "english": "Can I trouble you to iron the shirt?", "type": "句子", "keyWords": ["trouble"] },
    { "chinese": "麻烦某人（做某事）", "english": "put sb. to the trouble (of doing sth.)", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "很抱歉，给你添了这么多麻烦。", "english": "I'm sorry to have put you to so much trouble.", "type": "句子", "keyWords": ["trouble"] },
    { "chinese": "不辞辛苦地做某事", "english": "take trouble to do sth.", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "多谢你费力相助。", "english": "Thank you for all the trouble you have taken to help me.", "type": "句子", "keyWords": ["trouble"] },
    { "chinese": "浑水摸鱼，趁机取利", "english": "fish in troubled waters", "type": "短语", "keyWords": ["trouble"] },
    { "chinese": "麻烦没来找你，就别去自找麻烦。", "english": "Never trouble trouble until trouble troubles you.", "type": "句子", "keyWords": ["trouble"] },
    { "chinese": "adj.令人讨厌的，令人烦恼的", "english": "troublesome", "type": "单词", "keyWords": [] },
    { "chinese": "n.长裤（复数）", "english": "trousers", "type": "单词", "keyWords": [] },
    { "chinese": "两条长裤", "english": "two pairs of trousers", "type": "短语", "keyWords": ["trousers"] },
    { "chinese": "n.卡车", "english": "truck", "type": "单词", "keyWords": [] },
    { "chinese": "adj.真的，真实的", "english": "true", "type": "单词", "keyWords": [] },
    { "chinese": "ad.真实地，不假", "english": "truly", "type": "单词", "keyWords": [] },
    { "chinese": "实现", "english": "come true", "type": "短语", "keyWords": ["true"] },
    { "chinese": "真实的；自然的", "english": "be true to life", "type": "短语", "keyWords": ["true"] },
    { "chinese": "逼真", "english": "be true to nature", "type": "短语", "keyWords": ["true"] },
    { "chinese": "信守诺言", "english": "be true to one's word", "type": "短语", "keyWords": ["true"] },
    { "chinese": "不到长城非好汉。", "english": "He who doesn't reach the Great Wall is not a true man.", "type": "句子", "keyWords": ["true"] },
    { "chinese": "符合于…，…适用", "english": "be true of", "type": "短语", "keyWords": ["true"] }
];
