const qgl286_300 = [
    { "chinese": "吃的东西很好，服务质量也不错。", "english": "The food is good and the same is true of the service.", "type": "句子", "keyWords": ["true"] },
    { "chinese": "n.真理；真相，实情", "english": "truth", "type": "单词", "keyWords": [] },
    { "chinese": "说实在话，老实说", "english": "to tell the truth", "type": "短语", "keyWords": ["truth"] },
    { "chinese": "n.树干；皮箱；行李箱；大旅行箱；象鼻", "english": "trunk", "type": "单词", "keyWords": [] },
    { "chinese": "n.信任；信心；受托；托拉斯 v.信任，信赖；托付", "english": "trust", "type": "单词", "keyWords": [] },
    { "chinese": "他们建立了托拉斯，意图实现垄断。", "english": "They set up the trust in the hope of gaining a monopoly.", "type": "句子", "keyWords": ["trust"] },
    { "chinese": "v.尝试；努力；试图；试验；考验；审问；审判 n.尝试", "english": "try", "type": "单词", "keyWords": [] },
    { "chinese": "试穿", "english": "try...on", "type": "短语", "keyWords": ["try"] },
    { "chinese": "碰运气", "english": "try one's luck", "type": "短语", "keyWords": ["try"] },
    { "chinese": "值得一试", "english": "be worth a try", "type": "短语", "keyWords": ["try"] },
    { "chinese": "试试看，尝试一下", "english": "have a try", "type": "短语", "keyWords": ["try"] },
    { "chinese": "别逼得我忍无可忍。", "english": "Don't try my patience.", "type": "句子", "keyWords": ["try"] },
    { "chinese": "他们的案子将在下个月开审。", "english": "Their case will be tried in court next month.", "type": "句子", "keyWords": ["try"] },
    { "chinese": "尝试一下做某事", "english": "try doing", "type": "短语", "keyWords": ["try"] },
    { "chinese": "设法做成某事", "english": "try (one's best) to do", "type": "短语", "keyWords": ["try"] },
    { "chinese": "试用，试验…", "english": "try out (this method, a new car...)", "type": "短语", "keyWords": ["try"] },
    { "chinese": "第一次试着（滑雪）", "english": "try one's hand at (skiing...)", "type": "短语", "keyWords": ["try"] },
    { "chinese": "n.管子；软管；[英]地铁", "english": "tube", "type": "单词", "keyWords": [] },
    { "chinese": "试管", "english": "a test tube", "type": "短语", "keyWords": ["tube"] },
    { "chinese": "一管牙膏", "english": "a tube of toothpaste", "type": "短语", "keyWords": ["tube"] },
    { "chinese": "n.星期二", "english": "Tuesday", "type": "单词", "keyWords": [] },
    { "chinese": "n.学费；教学；讲授", "english": "tuition", "type": "单词", "keyWords": [] },
    { "chinese": "学费", "english": "tuition fee", "type": "短语", "keyWords": ["tuition"] },
    { "chinese": "n.曲子，曲调 v.调音，调整", "english": "tune", "type": "单词", "keyWords": [] },
    { "chinese": "调子准；入调", "english": "in tune", "type": "短语", "keyWords": ["tune"] },
    { "chinese": "走调", "english": "out of tune", "type": "短语", "keyWords": ["tune"] },
    { "chinese": "n.隧道，地道", "english": "tunnel", "type": "单词", "keyWords": [] },
    { "chinese": "n.轮替；交流；变化；转动；转弯 v.使转动；使转向；使变得", "english": "turn", "type": "单词", "keyWords": [] },
    { "chinese": "那位作家成为一名演员。", "english": "The writer turned actor.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "关掉", "english": "turn...off", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "使变成；翻译", "english": "turn...into...", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "开；打开", "english": "turn...on", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "转向；求助于；查阅（字典等）", "english": "turn to...", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "依次", "english": "in turn", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "转过去，转身", "english": "turn around (=turn round)", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "轮流；交替", "english": "by turns", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "在世纪之交", "english": "at the turn of the century", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "上交；拐弯进入", "english": "turn (...in)", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "转过脸不再看某人某物", "english": "turn away (from sb./sth.)", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "拒绝帮助某人；不准许某人进入", "english": "turn (sb.) away (from...)", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "医生是不能见死不救的。", "english": "A doctor cannot turn away a dying man.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "（把音量）调低；拒绝", "english": "turn...down", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "拒绝了我的帮助", "english": "turn down my offer/turn me down", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "关掉；生产，制造；原来（是）；最后证明是", "english": "turn...out", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "关掉了灯", "english": "turn out the lights", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "生产100000台电脑", "english": "turn out 100,000 computers", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "这项计划结果归于失败。", "english": "The plan turned out (to be) a failure.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "结果谈判真的是谈了两年。", "english": "It turned out that the negotiations did take two years.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "移交；仔细考虑；翻阅；翻身", "english": "turn...over", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "改过自新", "english": "turn over a new leaf", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "交出了非法资金", "english": "turn over the illegal funds", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "仔细考虑这个问题", "english": "turn over the problem in her mind", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "开大，调大；出现；查阅；卷起", "english": "turn up", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "文件迟早会找到的。", "english": "The papers will turn up sooner or later.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "出席会议", "english": "turn up at the meeting", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "在字典里查生词", "english": "turn/look up the new word in the dictionary", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "她的袖子卷起来了。", "english": "Her sleeves were turned up.", "type": "句子", "keyWords": ["turn"] },
    { "chinese": "轮流做某事", "english": "take turns at doing sth.", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "拐错弯", "english": "take the wrong turning", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "标志我们历史的一个转折点", "english": "mark a turning point in our history", "type": "短语", "keyWords": ["turn"] },
    { "chinese": "n.家庭教师；（大学）导师 v.当…的教师；辅导，指导", "english": "tutor", "type": "单词", "keyWords": [] },
    { "chinese": "adj.私人教师的；大学导师的", "english": "tutorial", "type": "单词", "keyWords": [] },
    { "chinese": "ad.两次；两倍", "english": "twice", "type": "单词", "keyWords": [] },
    { "chinese": "有两倍之多", "english": "have twice as many", "type": "短语", "keyWords": ["twice"] },
    { "chinese": "n.双胞胎之一 adj.双胞胎的", "english": "twin", "type": "单词", "keyWords": [] },
    { "chinese": "v.旋转，转动；扭；搓；蜿蜒曲折地走；盘绕 n.拐弯；曲折；扭，拧", "english": "twist", "type": "单词", "keyWords": [] },
    { "chinese": "这条小路盘绕在小山上。", "english": "The path twisted up the hill.", "type": "句子", "keyWords": ["twist"] },
    { "chinese": "弯弯曲曲的路", "english": "a road full of twists and turns", "type": "短语", "keyWords": ["twist"] },
    { "chinese": "num.二 n.两个", "english": "two", "type": "单词", "keyWords": [] },
    { "chinese": "三三两两地，零星地", "english": "in twos and threes", "type": "短语", "keyWords": ["two"] },
    { "chinese": "（分成）两半", "english": "in two", "type": "短语", "keyWords": ["two"] },
    { "chinese": "一两（天…）", "english": "a (day) or two = one or two (days)", "type": "短语", "keyWords": ["two"] },
    { "chinese": "二人成伴，三人不欢。", "english": "Two is company, but three is none.", "type": "句子", "keyWords": ["two"] },
    { "chinese": "孤掌难鸣。", "english": "It takes two to make a quarrel.", "type": "句子", "keyWords": ["two"] },
    { "chinese": "n.类型；品种；典型 v.用打字机打 vi.打字", "english": "type", "type": "单词", "keyWords": [] },
    { "chinese": "n.打字机", "english": "typewriter", "type": "单词", "keyWords": [] },
    { "chinese": "n.打字", "english": "typing", "type": "单词", "keyWords": [] },
    { "chinese": "n.打字员", "english": "typist", "type": "单词", "keyWords": [] },
    { "chinese": "n.台风", "english": "typhoon", "type": "单词", "keyWords": [] },
    { "chinese": "adj.典型的，有代表性的；模范的；特有的；象征性的", "english": "typical", "type": "单词", "keyWords": [] },
    { "chinese": "一个有代表性的学生/例子", "english": "a typical pupil/example", "type": "短语", "keyWords": ["typical"] },
    { "chinese": "代表；象征", "english": "be typical of...", "type": "短语", "keyWords": ["typical"] },
    { "chinese": "他才会作出那样具有讽刺意味的回答。", "english": "That sarcastic reply is typical of him.", "type": "句子", "keyWords": ["typical"] },
    { "chinese": "典型的巴洛克时期的作品", "english": "a composition typical of the baroque period", "type": "短语", "keyWords": ["typical"] },
    { "chinese": "n.轮胎", "english": "tyre", "type": "单词", "keyWords": [] },
    { "chinese": "轮胎没气了", "english": "have got a flat tyre", "type": "短语", "keyWords": ["tyre"] },
    { "chinese": "n.不明飞行物，飞碟", "english": "UFO", "type": "单词", "keyWords": [] },
    { "chinese": "adj.难看的；丑陋的；令人不愉快的；丑恶的", "english": "ugly", "type": "单词", "keyWords": [] },
    { "chinese": "n.伞", "english": "umbrella", "type": "单词", "keyWords": [] },
    { "chinese": "在联合国的保护下", "english": "under the umbrella of the UN", "type": "短语", "keyWords": ["umbrella"] },
    { "chinese": "前缀“不；相反；除去”", "english": "un-", "type": "单词", "keyWords": [] },
    { "chinese": "adj.不能的；不会的", "english": "unable", "type": "单词", "keyWords": [] },
    { "chinese": "他想来，但他不能来，是吗？", "english": "He wanted to come but he was unable to, wasn't he?", "type": "句子", "keyWords": ["unable"] },
    { "chinese": "adj.未意识到的", "english": "unaware", "type": "单词", "keyWords": [] },
    { "chinese": "adj.难以置信的", "english": "unbelievable", "type": "单词", "keyWords": [] },
    { "chinese": "adj.失去知觉的；未发觉的", "english": "unconscious", "type": "单词", "keyWords": [] },
    { "chinese": "n.伯父；叔叔；叔父；舅舅；姨丈", "english": "uncle", "type": "单词", "keyWords": [] },
    { "chinese": "山姆大叔（美国、美国政府或美国人的绰号）", "english": "Uncle Sam", "type": "短语", "keyWords": ["uncle"] },
    { "chinese": "前缀“在…以下；不足的；次于”", "english": "under-", "type": "单词", "keyWords": [] },
    { "chinese": "prep.在…下面；低于", "english": "under", "type": "单词", "keyWords": [] },
    { "chinese": "在讨论/建设/考虑/调查/修理中/在进行中；在航行中", "english": "under discussion/construction/consideration/investigation/repair/way", "type": "短语", "keyWords": ["under"] },
    { "chinese": "在治疗中", "english": "under medical treatment", "type": "短语", "keyWords": ["under"] },
    { "chinese": "用假名", "english": "under a false name", "type": "短语", "keyWords": ["under"] },
    { "chinese": "v.经受；经历；遭受", "english": "undergo", "type": "单词", "keyWords": [] },
    { "chinese": "遭受巨大苦难", "english": "undergo great hardship", "type": "短语", "keyWords": ["undergo"] },
    { "chinese": "adj.地下的；秘密的 ad.在地下；秘密地", "english": "underground", "type": "单词", "keyWords": [] },
    { "chinese": "地铁", "english": "the underground", "type": "短语", "keyWords": ["underground"] },
    { "chinese": "地铁", "english": "the underground railway", "type": "短语", "keyWords": ["underground"] },
    { "chinese": "v.在…下面画线；强调", "english": "underline", "type": "单词", "keyWords": [] },
    { "chinese": "v.理解；懂；熟知；通晓；认为；推断", "english": "understand", "type": "单词", "keyWords": [] },
    { "chinese": "理解为什么做某事", "english": "understand doing sth.", "type": "短语", "keyWords": ["understand"] },
    { "chinese": "说明白自己的意思；使别人理解自己的意思", "english": "make oneself understood", "type": "短语", "keyWords": ["understand"] },
    { "chinese": "使某人理解某人或某事", "english": "make sb. understand sb./sth.", "type": "短语", "keyWords": ["understand"] },
    { "chinese": "adj.有理解能力的；通情达理的 n.理解（力）；同情，谅解", "english": "understanding", "type": "单词", "keyWords": [] },
    { "chinese": "达成协议；取得谅解", "english": "come to/arrive at/reach an understanding", "type": "短语", "keyWords": ["understanding"] },
    { "chinese": "会心的微笑", "english": "an understanding smile", "type": "短语", "keyWords": ["understanding"] },
    { "chinese": "通情达理的人；聪明的人", "english": "an understanding man", "type": "短语", "keyWords": ["understanding"] },
    { "chinese": "v.接受，着手；承担；答应，同意", "english": "undertake", "type": "单词", "keyWords": [] },
    { "chinese": "接受任务", "english": "undertake a task", "type": "短语", "keyWords": ["undertake"] },
    { "chinese": "答应再勘探", "english": "undertake to prospect again", "type": "短语", "keyWords": ["undertake"] },
    { "chinese": "自己承担照顾年长的亲戚", "english": "undertake oneself to care for an elderly relative", "type": "短语", "keyWords": ["undertake"] },
    { "chinese": "v.解开，松开；取消，废除", "english": "undo", "type": "单词", "keyWords": [] },
    { "chinese": "覆水难收。事已定局，无可挽回。", "english": "What is done cannot be undone.", "type": "句子", "keyWords": ["undo"] },
    { "chinese": "adj.不幸的；令人遗憾的", "english": "unfortunate", "type": "单词", "keyWords": [] },
    { "chinese": "ad.不幸地", "english": "unfortunately", "type": "单词", "keyWords": [] },
    { "chinese": "n.制服；军服 adj.一致的，一式的", "english": "uniform", "type": "单词", "keyWords": [] },
    { "chinese": "穿着校服的学生", "english": "students dressed in school uniforms", "type": "短语", "keyWords": ["uniform"] },
    { "chinese": "大小和形状一样的东西", "english": "things of uniform size and shape", "type": "短语", "keyWords": ["uniform"] },
    { "chinese": "n.协会；联盟；团结；联合，合并", "english": "union", "type": "单词", "keyWords": [] },
    { "chinese": "中国作家协会", "english": "the Union of Chinese Writers", "type": "短语", "keyWords": ["union"] },
    { "chinese": "美满的婚姻", "english": "a happy union", "type": "短语", "keyWords": ["union"] },
    { "chinese": "工会", "english": "a trade union", "type": "短语", "keyWords": ["union"] },
    { "chinese": "学生会", "english": "student union", "type": "短语", "keyWords": ["union"] },
    { "chinese": "团结就是力量。", "english": "Union is strength.", "type": "句子", "keyWords": ["union"] },
    { "chinese": "adj.（同类中）独特的；唯一的", "english": "unique", "type": "单词", "keyWords": [] },
    { "chinese": "只有海岸区域才有的问题", "english": "a problem unique to coastal areas", "type": "短语", "keyWords": ["unique"] },
    { "chinese": "n.单元；单位", "english": "unit", "type": "单词", "keyWords": [] },
    { "chinese": "英镑是英国货币的标准单位。", "english": "The pound is the standard unit of money in Britain.", "type": "句子", "keyWords": ["unit"] },
    { "chinese": "v.联合；结合", "english": "unite", "type": "单词", "keyWords": [] },
    { "chinese": "adj.联合的；统一的；共同的", "english": "united", "type": "单词", "keyWords": [] },
    { "chinese": "作出共同努力", "english": "make united/joint efforts", "type": "短语", "keyWords": ["united"] },
    { "chinese": "联合；统一团结", "english": "unite...with...", "type": "短语", "keyWords": ["unite"] },
    { "chinese": "合即立，分即垮。", "english": "United we stand, divided we fall.", "type": "句子", "keyWords": ["united"] },
    { "chinese": "n.团结；统一（性），一致，协调", "english": "unity", "type": "单词", "keyWords": [] },
    { "chinese": "adj.普遍的；全世界的，宇宙的", "english": "universal", "type": "单词", "keyWords": [] },
    { "chinese": "ad.普遍地；到处", "english": "universally", "type": "单词", "keyWords": [] },
    { "chinese": "n.宇宙；世界", "english": "universe", "type": "单词", "keyWords": [] },
    { "chinese": "n.（综合性）大学", "english": "university", "type": "单词", "keyWords": [] },
    { "chinese": "adj.未知的；默默无闻的 n.未知的事物或人", "english": "unknown", "type": "单词", "keyWords": [] },
    { "chinese": "conj.除非", "english": "unless", "type": "单词", "keyWords": [] },
    { "chinese": "prep.不像，和…不同 adj.不同的，不相似的", "english": "unlike", "type": "单词", "keyWords": [] },
    { "chinese": "不打电话过来对他来说是不多见的。", "english": "It's unlike him not to call.", "type": "句子", "keyWords": ["unlike"] },
    { "chinese": "prep./conj.直到…为止", "english": "until", "type": "单词", "keyWords": [] },
    { "chinese": "在前些日子，我对这事一无所知/直到最近我才得知此事。", "english": "Until quite recently, I knew nothing at all about it.", "type": "句子", "keyWords": ["until"] },
    { "chinese": "一直到几年后瑞士人才凭着新型的斯沃奇系列表追赶上来，重新获得市场领先地位。", "english": "It was not until years later that the Swiss caught up and regained their leading position in the marketplace with the creation of Swatch watches.", "type": "句子", "keyWords": ["until"] },
    { "chinese": "Not until…+倒装结构", "english": "Not until...+inversion", "type": "短语", "keyWords": ["until"] },
    { "chinese": "直到1996年，奥斯陆和平协议创造了可能性，他才重返巴勒斯坦。", "english": "Not until 1996, after the Oslo peace agreement made it possible, did he return to Palestine.", "type": "句子", "keyWords": ["until"] },
    { "chinese": "ad.向上；向高处；直立；向北；完全；成碎片 prep.往…较高处；沿着", "english": "up", "type": "单词", "keyWords": [] },
    { "chinese": "举起手来！", "english": "Hands up!", "type": "句子", "keyWords": ["up"] },
    { "chinese": "时间到了。", "english": "Time's up.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "到伦敦去", "english": "up to London", "type": "短语", "keyWords": ["up"] },
    { "chinese": "怎么了？", "english": "What's up?", "type": "句子", "keyWords": ["up"] },
    { "chinese": "一直到", "english": "up until...", "type": "短语", "keyWords": ["up"] },
    { "chinese": "在床上坐起来", "english": "sit up in bed", "type": "短语", "keyWords": ["up"] },
    { "chinese": "到我这边来", "english": "come up to me", "type": "短语", "keyWords": ["up"] },
    { "chinese": "上上下下；来回地", "english": "up and down", "type": "短语", "keyWords": ["up"] },
    { "chinese": "在山的高处", "english": "high up in the mountains", "type": "短语", "keyWords": ["up"] },
    { "chinese": "已起床（状态）", "english": "be up", "type": "短语", "keyWords": ["up"] },
    { "chinese": "她已经起床半天了。", "english": "She has been up for hours.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "多达；直到；从事；取决于", "english": "up to", "type": "短语", "keyWords": ["up"] },
    { "chinese": "他可以在假期工作达四个月。", "english": "He can work for up to four months during his school break.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "直到现在为止，地球和它的卫星之间还没有建立任何直接联系。", "english": "Up to the present day no bond exists between the earth and its satellite.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "你昨天干什么去了？我打电话给你，但你家里没人。", "english": "What were you up to yesterday? I called you, but there wasn't anybody home.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "从清单上你确实能看到职位的价值有多大是由雇主决定的。", "english": "The list does show you that determining a job's value is up to the employer.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "因此，我的旅行到底是容易的还是困难的都是由你决定的。", "english": "So it is up to you to decide how easy or difficult you want my journey to be.", "type": "句子", "keyWords": ["up"] },
    { "chinese": "adj.即将来临的", "english": "upcoming", "type": "单词", "keyWords": [] },
    { "chinese": "v.使现代化；更新", "english": "update", "type": "单词", "keyWords": [] },
    { "chinese": "prep.在…上（较正式，口语用on）", "english": "upon", "type": "单词", "keyWords": [] },
    { "chinese": "adj.较高的，上层的，上部的", "english": "upper", "type": "单词", "keyWords": [] },
    { "chinese": "上流社会", "english": "the upper class", "type": "短语", "keyWords": ["upper"] },
    { "chinese": "上唇", "english": "the upper lip", "type": "短语", "keyWords": ["upper"] },
    { "chinese": "尼罗河上游地区", "english": "the upper Nile", "type": "短语", "keyWords": ["upper"] },
    { "chinese": "高地地区", "english": "upper regions", "type": "短语", "keyWords": ["upper"] },
    { "chinese": "adj.最高的；最主要的", "english": "uppermost", "type": "单词", "keyWords": [] },
    { "chinese": "adj.竖直的；挺直的；正直的 ad.笔直，竖立着", "english": "upright", "type": "单词", "keyWords": [] },
    { "chinese": "坐直", "english": "hold yourself upright", "type": "短语", "keyWords": ["upright"] },
    { "chinese": "v.弄翻；打乱；打扰，使心烦意乱 adj.弄翻的；心烦的", "english": "upset", "type": "单词", "keyWords": [] },
    { "chinese": "打乱我们的计划/会议", "english": "upset our plan/the meeting", "type": "短语", "keyWords": ["upset"] },
    { "chinese": "弄翻一杯牛奶", "english": "upset a glass of milk", "type": "短语", "keyWords": ["upset"] },
    { "chinese": "感到不安", "english": "feel upset about sth.", "type": "短语", "keyWords": ["upset"] },
    { "chinese": "ad.在楼上；往楼上", "english": "upstairs", "type": "单词", "keyWords": [] },
    { "chinese": "adj.现代的；最新的", "english": "up-to-date", "type": "单词", "keyWords": [] },
    { "chinese": "adj.向上的 ad.向上", "english": "upward", "type": "单词", "keyWords": [] },
    { "chinese": "ad.向上", "english": "upwards", "type": "单词", "keyWords": [] },
    { "chinese": "n.铀", "english": "uranium", "type": "单词", "keyWords": [] },
    { "chinese": "adj.城市的；市内的", "english": "urban", "type": "单词", "keyWords": [] },
    { "chinese": "v.催促；推进，鼓励", "english": "urge", "type": "单词", "keyWords": [] },
    { "chinese": "赶马往前跑", "english": "urge a horse on", "type": "短语", "keyWords": ["urge"] },
    { "chinese": "他催促她休息。", "english": "He urged her to rest.", "type": "句子", "keyWords": ["urge"] },
    { "chinese": "adj.急迫的；紧要的", "english": "urgent", "type": "单词", "keyWords": [] },
    { "chinese": "n.紧急，紧迫", "english": "urgency", "type": "单词", "keyWords": [] },
    { "chinese": "pron.（宾格）我们", "english": "us", "type": "单词", "keyWords": [] },
    { "chinese": "n.使用；用法；惯用法；习语", "english": "usage", "type": "单词", "keyWords": [] },
    { "chinese": "n.使用；用处，好处；用途 v.使用", "english": "use", "type": "单词", "keyWords": [] },
    { "chinese": "开始被使用", "english": "come into use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "使用着", "english": "in use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "停止被使用", "english": "go out of use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "不再使用了", "english": "out of use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "开始使用", "english": "put sth. to use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "开始使用（某物）", "english": "bring sth. into use", "type": "短语", "keyWords": ["use"] },
    { "chinese": "（充分）利用", "english": "make (full/good) use of = make the most of", "type": "短语", "keyWords": ["use"] },
    { "chinese": "有用", "english": "be of (no, little...) use to sb./sth.", "type": "短语", "keyWords": ["use"] },
    { "chinese": "做某事是无济于事的", "english": "It's no use/good doing sth.", "type": "短语", "keyWords": ["use"] },
    { "chinese": "（被）用于", "english": "be used to do sth./for (doing) sth.", "type": "短语", "keyWords": ["use"] },
    { "chinese": "用尽", "english": "use...up", "type": "短语", "keyWords": ["use"] },
    { "chinese": "v.惯常（仅用过去时，后接不定式）", "english": "used", "type": "单词", "keyWords": [] },
    { "chinese": "adj.已适应，已习惯（to doing sth.）；用旧了的", "english": "used", "type": "单词", "keyWords": [] },
    { "chinese": "过去常常做", "english": "used to do sth.", "type": "短语", "keyWords": ["used"] },
    { "chinese": "习惯于（做）某事", "english": "be/get/become used/accustomed to (doing) sth.", "type": "短语", "keyWords": ["used"] },
    { "chinese": "出售旧汽车", "english": "sell used cars", "type": "短语", "keyWords": ["used"] },
    { "chinese": "adj.有用的；有益的", "english": "useful", "type": "单词", "keyWords": [] },
    { "chinese": "n.有用；有益", "english": "usefulness", "type": "单词", "keyWords": [] },
    { "chinese": "adj.无用的；无益的；无价值的", "english": "useless", "type": "单词", "keyWords": [] },
    { "chinese": "n.无用；无益", "english": "uselessness", "type": "单词", "keyWords": [] },
    { "chinese": "adj.通常的", "english": "usual", "type": "单词", "keyWords": [] },
    { "chinese": "ad.通常", "english": "usually", "type": "单词", "keyWords": [] },
    { "chinese": "像往常一样", "english": "as usual", "type": "短语", "keyWords": ["usual"] },
    { "chinese": "比往常", "english": "than usual", "type": "短语", "keyWords": ["usual"] },
    { "chinese": "n.空；空白；（职位）空缺；没表情，失神", "english": "vacancy", "type": "单词", "keyWords": [] },
    { "chinese": "对不起，职员的空缺已有人补上。", "english": "Sorry, the vacancy in the office has been filled.", "type": "句子", "keyWords": ["vacancy"] },
    { "chinese": "脸上茫然若失的神情", "english": "a look of vacancy on his face", "type": "短语", "keyWords": ["vacancy"] },
    { "chinese": "adj.空（闲）的；空白的；（职位）空缺的；没表情的，失神的", "english": "vacant", "type": "单词", "keyWords": [] },
    { "chinese": "空缺职位", "english": "a vacant position", "type": "短语", "keyWords": ["vacant"] },
    { "chinese": "茫然的凝视", "english": "a vacant stare", "type": "短语", "keyWords": ["vacant"] },
    { "chinese": "这家旅馆有空房间吗？", "english": "Are there any rooms vacant in this hotel?", "type": "句子", "keyWords": ["vacant"] },
    { "chinese": "n.休假；假期", "english": "vacation", "type": "单词", "keyWords": [] },
    { "chinese": "在休假", "english": "on vacation", "type": "短语", "keyWords": ["vacation"] },
    { "chinese": "adj.含糊的；不明确的", "english": "vague", "type": "单词", "keyWords": [] },
    { "chinese": "徒劳，徒然，枉然", "english": "in vain", "type": "短语", "keyWords": [] },
    { "chinese": "n.山谷；溪谷；流域", "english": "valley", "type": "单词", "keyWords": [] },
    { "chinese": "长江流域", "english": "the Yangtze valley", "type": "短语", "keyWords": ["valley"] },
    { "chinese": "adj.有效的；具有法律效力的", "english": "valid", "type": "单词", "keyWords": [] },
    { "chinese": "三个月有效", "english": "be valid for three months", "type": "短语", "keyWords": ["valid"] },
    { "chinese": "adj.有价值的；很有用的", "english": "valuable", "type": "单词", "keyWords": [] },
    { "chinese": "n.价值；重要性；面值；价值观 v.给…估价；重视，珍视", "english": "value", "type": "单词", "keyWords": [] },
    { "chinese": "对某人有很大价值", "english": "be of great value to sb.", "type": "短语", "keyWords": ["value"] },
    { "chinese": "我们基本的价值观和利益", "english": "our basic values and interests", "type": "短语", "keyWords": ["value"] },
    { "chinese": "他估计这枚戒指价值800美元。", "english": "He valued the ring at $800.", "type": "句子", "keyWords": ["value"] },
    { "chinese": "我很看重你的劝告。", "english": "I value your advice.", "type": "句子", "keyWords": ["value"] },
    { "chinese": "评价不高；不怎么重视", "english": "put little value on/upon...", "type": "短语", "keyWords": ["value"] },
    { "chinese": "井干方知水可贵。", "english": "We never know the value of water till the well is dry.", "type": "句子", "keyWords": ["value"] },
    { "chinese": "adj.没有价值的；毫无用处的", "english": "valueless", "type": "单词", "keyWords": [] },
    { "chinese": "n.有篷载重卡车，运货车", "english": "van", "type": "单词", "keyWords": [] },
    { "chinese": "n.蒸气，水汽；雾", "english": "vapour", "type": "单词", "keyWords": [] },
    { "chinese": "n.品种，种类；各种，种种；变化，多样化", "english": "variety", "type": "单词", "keyWords": [] },
    { "chinese": "各种各样的，种类繁多的", "english": "a considerable/great/wide variety of", "type": "短语", "keyWords": ["variety"] },
    { "chinese": "adj.不同的；各种各样的；多方面的", "english": "various", "type": "单词", "keyWords": [] },
    { "chinese": "v.使不同；改变；使多样化；呈差异；变化，有不同", "english": "vary", "type": "单词", "keyWords": [] },
    { "chinese": "使某人的饮食多样化", "english": "vary one's diet", "type": "短语", "keyWords": ["vary"] },
    { "chinese": "天气一天天不同。", "english": "The weather varies from day to day.", "type": "句子", "keyWords": ["vary"] },
    { "chinese": "n.[C]花瓶", "english": "vase /vɑːz/", "type": "单词", "keyWords": [] },
    { "chinese": "a.巨大的；广阔的，辽阔的；广大的；广泛的", "english": "vast /vɑːst/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]蔬菜", "english": "vegetable /ˈvedʒtəbl/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]素食（主义）者；a.吃素的；素食者的", "english": "vegetarian /ˌvedʒəˈteəriən/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]（总称）植物", "english": "vegetation /ˌvedʒtˈeɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]车辆；交通工具；飞行器；（运载）航天火箭", "english": "vehicle /ˈviːəkl/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]冒险行动；投机活动；冒险（事业）；v.冒险；（使）有风险", "english": "venture /ˈventʃə/", "type": "单词", "keyWords": [] },
    { "chinese": "合资/合营企业", "english": "a joint venture", "type": "短语", "keyWords": ["venture"] },
    { "chinese": "投资资本", "english": "venture capital", "type": "短语", "keyWords": ["venture"] },
    { "chinese": "冒险进入荒野", "english": "venture into the wilderness", "type": "短语", "keyWords": ["venture"] },
    { "chinese": "没有人敢打断他的话。", "english": "Nobody ventured to interrupt him.", "type": "句子", "keyWords": ["venture"] },
    { "chinese": "不入虎穴，焉得虎子。", "english": "Nothing ventured, nothing gained.", "type": "句子", "keyWords": ["venture"] },
    { "chinese": "n.（罗马神话中美的女神）维纳斯；[天]金星", "english": "Venus /ˈviːnəs/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][语]动词", "english": "verb /vɜːb/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]说法；译文，译本；版本；软件版本", "english": "version /ˈvɜːʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "一部小说的中文版戏剧改编本", "english": "the dramatic Chinese version of a novel", "type": "短语", "keyWords": ["version"] },
    { "chinese": "我已听到这个事故的两种说法了。", "english": "I've heard two versions of the accident.", "type": "句子", "keyWords": ["version"] },
    { "chinese": "prep.（指在诉讼、比赛等中）对，与…相对（缩vs.）", "english": "versus /ˈvɜːsəs/", "type": "单词", "keyWords": [] },
    { "chinese": "中国队对意大利队", "english": "China versus/ vs. Italy", "type": "短语", "keyWords": ["versus"] },
    { "chinese": "ad.很；颇；非常（辨析见fairly）；a.正是的；恰好是的", "english": "very /ˈveri/", "type": "单词", "keyWords": [] },
    { "chinese": "非常（常修饰动词、过去分词、介词短语、比较级等）", "english": "very much", "type": "短语", "keyWords": ["very"] },
    { "chinese": "最好的建议", "english": "the very best advice", "type": "短语", "keyWords": ["very"] },
    { "chinese": "城镇的中心", "english": "the very centre of town", "type": "短语", "keyWords": ["very"] },
    { "chinese": "正在行窃时被擒住", "english": "be caught in the very act of stealing", "type": "短语", "keyWords": ["very"] },
    { "chinese": "就在那时", "english": "at that very moment= just at that moment", "type": "短语", "keyWords": ["very"] },
    { "chinese": "我一定尽最大的努力去做。", "english": "I will do the very best I can.", "type": "句子", "keyWords": ["very"] },
    { "chinese": "光是想到此事就令人害怕。", "english": "The very thought of it is frightening.", "type": "句子", "keyWords": ["very"] },
    { "chinese": "n.[C]背心，马甲", "english": "vest /vest/", "type": "单词", "keyWords": [] },
    { "chinese": "ad.反过来也一样；反之亦然（...and vice versa）", "english": "vice versa /ˌvaɪs ˈvɜːsə/", "type": "短语", "keyWords": [] },
    { "chinese": "n.[C]受害者，受骗者，牺牲者，牺牲品", "english": "victim /ˈvɪktɪm/", "type": "单词", "keyWords": [] },
    { "chinese": "成为…的受害者/牺牲品（近be/ fall/ become prey to）", "english": "fall victim to", "type": "短语", "keyWords": ["victim"] },
    { "chinese": "n.[C][U]胜利；战绩；成功；victorious /vɪkˈtɔːriəs/ a.胜利的", "english": "victory /ˈvɪktəri/", "type": "单词", "keyWords": [] },
    { "chinese": "战胜；击败", "english": "win/ have/ gain/ obtain a victory over", "type": "短语", "keyWords": ["victory"] },
    { "chinese": "n.[C][U]电视；录像；a.电视的；录像的，影像的，视频的", "english": "video /ˈvɪdiəʊ/", "type": "单词", "keyWords": [] },
    { "chinese": "摄影机", "english": "video camera", "type": "短语", "keyWords": ["video"] },
    { "chinese": "影碟", "english": "video disc", "type": "短语", "keyWords": ["video"] },
    { "chinese": "电子游戏", "english": "video game", "type": "短语", "keyWords": ["video"] },
    { "chinese": "n.[C]录像磁带", "english": "videotape /ˈvɪdiəʊteɪp/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]视域；景色（辨析见scene）；视力；观看，看；看得见的地方；看法（辨析见idea）；vt.看待；查看", "english": "view /vjuː/", "type": "单词", "keyWords": [] },
    { "chinese": "呈现在眼前", "english": "come into view/ sight", "type": "短语", "keyWords": ["view"] },
    { "chinese": "出现在眼前，可以被看得见", "english": "come into view/ sight", "type": "短语", "keyWords": ["view"] },
    { "chinese": "使看得见", "english": "bring...into view/ sight", "type": "短语", "keyWords": ["view"] },
    { "chinese": "在视野内消逝", "english": "go out of view/ sight", "type": "短语", "keyWords": ["view"] },
    { "chinese": "持…的观点", "english": "hold the view that...", "type": "短语", "keyWords": ["view"] },
    { "chinese": "鸟瞰；俯视", "english": "(have) a bird's eye view of sth.", "type": "短语", "keyWords": ["view"] },
    { "chinese": "照个人的见解（=in one's opinion/from one's point of view）", "english": "in one's view", "type": "短语", "keyWords": ["view"] },
    { "chinese": "有关于…的观点", "english": "the views on sth.", "type": "短语", "keyWords": ["view"] },
    { "chinese": "观点", "english": "a point of view= viewpoint", "type": "短语", "keyWords": ["view"] },
    { "chinese": "把…看作…（=regard...as）", "english": "view...as...", "type": "短语", "keyWords": ["view"] },
    { "chinese": "大致介绍一下", "english": "give a view of", "type": "短语", "keyWords": ["view"] },
    { "chinese": "在被…完全看得见的地方", "english": "in full view of", "type": "短语", "keyWords": ["view"] },
    { "chinese": "我们站在人群可以看得一清二楚的地方。", "english": "We stood in full view of the crowd.", "type": "句子", "keyWords": ["view"] },
    { "chinese": "鉴于；考虑到", "english": "in view of sth.", "type": "短语", "keyWords": ["view"] },
    { "chinese": "n.[U]体力；精力；活力，生机；（动植物的）茁壮，气势", "english": "vigour /ˈvɪɡə/", "type": "单词", "keyWords": [] },
    { "chinese": "茁壮地，充满生机地；精力充沛地（=vigorously）", "english": "with vigour", "type": "短语", "keyWords": ["vigour"] },
    { "chinese": "n.[C]别墅", "english": "villa /ˈvɪlə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]村庄；villager n.[C]村民", "english": "village /ˈvɪlɪdʒ/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]藤本植物，蔓藤；攀缘植物；葡萄藤", "english": "vine /vaɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]醋", "english": "vinegar /ˈvɪnɪɡə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]猛烈，强烈；暴力（行为），暴虐；强暴（行为）", "english": "violence /ˈvaɪələns/", "type": "单词", "keyWords": [] },
    { "chinese": "暴力行为", "english": "an act of violence", "type": "短语", "keyWords": ["violence"] },
    { "chinese": "用暴力，动武", "english": "resort to violence", "type": "短语", "keyWords": ["violence"] },
    { "chinese": "猛力地；用暴力（=violently）", "english": "with violence", "type": "短语", "keyWords": ["violence"] },
    { "chinese": "a.猛烈的，强烈的，剧烈的；猛力的；（使用）暴力的", "english": "violent /ˈvaɪələnt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]小提琴；violinist n.[C]小提琴手", "english": "violin /ˌvaɪəˈlɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]正直的品性，德行；n.[C]德行，美德；优点", "english": "virtue /ˈvɜːtʃuː/", "type": "单词", "keyWords": [] },
    { "chinese": "a.实质上（起作用）的，实际上的；[计]虚拟的，[物]虚的", "english": "virtual /ˈvɜːtʃuəl/", "type": "单词", "keyWords": [] },
    { "chinese": "实际上的总统", "english": "the virtual president", "type": "短语", "keyWords": ["virtual"] },
    { "chinese": "虚拟现实", "english": "virtual reality", "type": "短语", "keyWords": ["virtual"] },
    { "chinese": "n.[C]病毒；毒害；[计]病毒", "english": "virus /ˈvaɪrəs/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]（护照等的）签证，背签；v.签发", "english": "visa /ˈviːzə/", "type": "单词", "keyWords": [] },
    { "chinese": "入境签证", "english": "entry visa", "type": "短语", "keyWords": ["visa"] },
    { "chinese": "a.看得见的，可见的（to sb）（反invisible）", "english": "visible /ˈvɪzəbl/", "type": "单词", "keyWords": [] },
    { "chinese": "某人看得见某物", "english": "sth. is visible to sb.", "type": "短语", "keyWords": ["visible"] },
    { "chinese": "明显的变化", "english": "a visible change", "type": "短语", "keyWords": ["visible"] },
    { "chinese": "肉眼看得见的星星", "english": "stars visible to the naked eye", "type": "短语", "keyWords": ["visible"] },
    { "chinese": "n.[C]幻想；[U]视力；视觉；眼力；远见；v.幻见；梦见；想象；显现", "english": "vision /ˈvɪʒn/", "type": "单词", "keyWords": [] },
    { "chinese": "因目光短浅", "english": "for lack of vision", "type": "短语", "keyWords": ["vision"] },
    { "chinese": "视力差", "english": "poor vision", "type": "短语", "keyWords": ["vision"] },
    { "chinese": "n.[C]；v.访问；参观；游览；visitor n.[C]访问者，参观者；游客", "english": "visit /ˈvɪzɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "参观；游览；访问", "english": "pay a visit to sb./ a place= pay sb./a place a visit", "type": "短语", "keyWords": ["visit"] },
    { "chinese": "他们从纽约来上海参观。", "english": "They are on a visit to Shanghai from New York.", "type": "句子", "keyWords": ["visit"] },
    { "chinese": "饥荒侵袭/降临了这一地区。", "english": "Famine visited this region.", "type": "句子", "keyWords": ["visit"] },
    { "chinese": "a.来访的", "english": "visiting /ˈvɪzɪtɪŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "访问学者", "english": "a visiting scholar", "type": "短语", "keyWords": ["visiting"] },
    { "chinese": "a.充满生机的，有生命的；至关重要的，必不可少的（for/ to）", "english": "vital /ˈvaɪtl/", "type": "单词", "keyWords": [] },
    { "chinese": "致命伤", "english": "a vital wound", "type": "短语", "keyWords": ["vital"] },
    { "chinese": "在生死存亡的时刻", "english": "at the vital moment", "type": "短语", "keyWords": ["vital"] },
    { "chinese": "空气对动物来说是必不可少的。", "english": "Air is vital to animals.", "type": "句子", "keyWords": ["vital"] },
    { "chinese": "n.[U]活力，生命力，生机，活力", "english": "vitality /vaɪˈtæləti/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]维生素", "english": "vitamin /ˈvɪtəmɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "a.逼真的；生动的；生气勃勃的；vividly ad.生动地；vividness n.[U]生动", "english": "vivid /ˈvɪvɪd/", "type": "单词", "keyWords": [] },
    { "chinese": "她向孩子们生动地描述了这个故事。", "english": "She gave the children a vivid description of the story.", "type": "句子", "keyWords": ["vivid"] },
    { "chinese": "这事我还记得很清楚。", "english": "It is still vivid in my memory.", "type": "句子", "keyWords": ["vivid"] },
    { "chinese": "n.[C]（某方面全部）词汇；词汇表；n.[U]（可与a连用）词汇量", "english": "vocabulary /vəˈkæbjələri/", "type": "单词", "keyWords": [] },
    { "chinese": "他的词汇量很丰富/少。", "english": "He has a very large/small vocabulary.", "type": "句子", "keyWords": ["vocabulary"] },
    { "chinese": "n.[C]（常指赖以为生的）职业，行业；n.[U]才能，素质", "english": "vocation /vəʊˈkeɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "教书是我的职业。", "english": "Teaching is my vocation.", "type": "句子", "keyWords": ["vocation"] },
    { "chinese": "不大适合搞文艺（近gift, talent）", "english": "have no/ little vocation for arts", "type": "短语", "keyWords": ["vocation"] },
    { "chinese": "n.[C]嗓音；表达；语态；v.（用语言）表达（出）", "english": "voice /vɔɪs/", "type": "单词", "keyWords": [] },
    { "chinese": "提高嗓门/压低嗓子", "english": "raise/ lower one's voice", "type": "短语", "keyWords": ["voice"] },
    { "chinese": "以最大的嗓音", "english": "at the top of one's voice", "type": "短语", "keyWords": ["voice"] },
    { "chinese": "异口同声地，一致地", "english": "with one voice", "type": "短语", "keyWords": ["voice"] },
    { "chinese": "低声/低沉/高声/柔声地", "english": "in a low/ deep/ loud/ soft voice", "type": "短语", "keyWords": ["voice"] },
    { "chinese": "在会议上表达他们的感觉（=voice v.）", "english": "give voice to their feelings at the meeting", "type": "短语", "keyWords": ["voice"] },
    { "chinese": "然而，从那时起国内外的人对此一直发表不同的看法。", "english": "Yet, ever since then, people at home and abroad have voiced different opinions about it.", "type": "句子", "keyWords": ["voice"] },
    { "chinese": "n.[C]火山；*volcanic /vɒlˈkænɪk/ a.火山的", "english": "volcano /vɒlˈkeɪnəʊ/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]排球；n.[C]排球运动", "english": "volleyball /ˈvɒlibɔːl/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C][U]容积；量；n.[C]卷，册；n.[U]音量", "english": "volume /ˈvɒljuːm/", "type": "单词", "keyWords": [] },
    { "chinese": "这容器的容积是两立方米。", "english": "The volume of this container is two cubic meters.", "type": "句子", "keyWords": ["volume"] },
    { "chinese": "关小/开大音量", "english": "turn down/up the volume", "type": "短语", "keyWords": ["volume"] },
    { "chinese": "a.自愿的；n.[C]志愿者；v.志愿（做）；*voluntary a.自愿的，志愿的", "english": "volunteer /ˌvɒlənˈtɪə/", "type": "单词", "keyWords": [] },
    { "chinese": "自愿地或无偿地给予（for sth.）", "english": "volunteer for sth.", "type": "短语", "keyWords": ["volunteer"] },
    { "chinese": "志愿提供服务", "english": "volunteer their services", "type": "短语", "keyWords": ["volunteer"] },
    { "chinese": "自愿做某事", "english": "volunteer to do sth.", "type": "短语", "keyWords": ["volunteer"] },
    { "chinese": "自愿献血", "english": "volunteer to donate blood", "type": "短语", "keyWords": ["volunteer"] },
    { "chinese": "自愿参加社区活动", "english": "volunteer for community activities", "type": "短语", "keyWords": ["volunteer"] },
    { "chinese": "义务做些社区工作", "english": "do some voluntary community work", "type": "短语", "keyWords": ["voluntary"] },
    { "chinese": "n.[C]投票；选举；选票；v.投票；选举；表决；v.投票决定，投票选举", "english": "vote /vəʊt/", "type": "单词", "keyWords": [] },
    { "chinese": "投…的票（for...）= vote for...", "english": "cast a vote for...= vote for...", "type": "短语", "keyWords": ["vote"] },
    { "chinese": "投票支持/反对", "english": "vote for/against sb. or sth.", "type": "短语", "keyWords": ["vote"] },
    { "chinese": "n.[C]航海；航行；旅行（辨析见tour）", "english": "voyage /ˈvɔɪɪdʒ/", "type": "单词", "keyWords": [] },
    { "chinese": "通过水路（去…）", "english": "go on/ make/ take a voyage (to...)", "type": "短语", "keyWords": ["voyage"] },
    { "chinese": "n.[C](常pl.)(尤指按小时、天数、周或按工作量给的)工资", "english": "wage /weɪdʒ/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]腰;腰部;腰围", "english": "waist /weɪst/", "type": "单词", "keyWords": [] },
    { "chinese": "她腰围70厘米。", "english": "She measures 70 centimeters round the waist.", "type": "句子", "keyWords": ["waist"] },
    { "chinese": "v.等，等候;伺候进餐，当侍者(见expect)", "english": "wait /weɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "等候，等待", "english": "wait for", "type": "短语", "keyWords": ["wait"] },
    { "chinese": "伺候(近attend on)", "english": "wait on", "type": "短语", "keyWords": ["wait"] },
    { "chinese": "等着瞧", "english": "wait and see", "type": "短语", "keyWords": ["wait"] },
    { "chinese": "让某人等着", "english": "keep sb. waiting", "type": "短语", "keyWords": ["wait"] },
    { "chinese": "等待某人做某事(近long, arrange)", "english": "wait for sb. to do sth.", "type": "短语", "keyWords": ["wait"] },
    { "chinese": "迫不及待做某事", "english": "can't wait to do sth.", "type": "短语", "keyWords": ["wait"] },
    { "chinese": "n.[C]女侍者;女服务员;waiter n.[C](男)侍者;(男)服务员", "english": "waitress /ˈweɪtrəs/", "type": "单词", "keyWords": [] },
    { "chinese": "vi.醒来;vt.唤醒", "english": "wake /weɪk/", "type": "单词", "keyWords": [] },
    { "chinese": "醒来", "english": "wake up", "type": "短语", "keyWords": ["wake"] },
    { "chinese": "唤醒", "english": "wake...up", "type": "短语", "keyWords": ["wake"] },
    { "chinese": "vi.醒来;vt.唤醒", "english": "waken /ˈweɪkən/", "type": "单词", "keyWords": [] },
    { "chinese": "vi./n.[C]走，步行，散步;n.[C]行业;v.陪同走路;步行护送;遛(动物)", "english": "walk /wɔːk/", "type": "单词", "keyWords": [] },
    { "chinese": "去散散步", "english": "go for a walk", "type": "短语", "keyWords": ["walk"] },
    { "chinese": "闲逛;走来走去", "english": "walk about", "type": "短语", "keyWords": ["walk"] },
    { "chinese": "从这里走20分钟的路程", "english": "a 20-minute/20 minutes' walk from here", "type": "短语", "keyWords": ["walk"] },
    { "chinese": "每天步行一小时三英里", "english": "walk one hour 3 miles a day", "type": "短语", "keyWords": ["walk"] },
    { "chinese": "遛狗", "english": "walk a dog", "type": "短语", "keyWords": ["walk"] },
    { "chinese": "护送我走出大厅", "english": "walk me down the hall", "type": "短语", "keyWords": ["walk"] },
    { "chinese": "我送她回家。", "english": "I walked her home.", "type": "句子", "keyWords": ["walk"] },
    { "chinese": "各行各业的人", "english": "men in/from all walks of life", "type": "短语", "keyWords": ["walk"] },
    { "chinese": "活字典(指词汇量极大的人)", "english": "a walking dictionary", "type": "短语", "keyWords": ["walk"] },
    { "chinese": "n.[C]随身听", "english": "Walkman /ˈwɔːkmən/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]墙，壁;似墙之物", "english": "wall /wɔːl/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C](放纸币、证件等的)皮夹子，钱夹", "english": "wallet /ˈwɒlɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]华尔兹舞(曲)，圆舞曲;跳华尔兹舞", "english": "waltz /wɔːlts/", "type": "单词", "keyWords": [] },
    { "chinese": "v.漫无目的地走，闲逛;漫游;徘徊;走神;迷失方向，离题", "english": "wander /ˈwɒndə/", "type": "单词", "keyWords": [] },
    { "chinese": "漫游世界", "english": "wander about the world", "type": "短语", "keyWords": ["wander"] },
    { "chinese": "离题", "english": "wander from the subject/point", "type": "短语", "keyWords": ["wander"] },
    { "chinese": "他心不在焉。", "english": "His mind is wandering.", "type": "句子", "keyWords": ["wander"] },
    { "chinese": "v.要，想要;需要;n.[C]需要;短缺", "english": "want /wɒnt/", "type": "单词", "keyWords": [] },
    { "chinese": "想要(某人)去做某事", "english": "want (sb.) to do sth.", "type": "短语", "keyWords": ["want"] },
    { "chinese": "这个房间需要打扫。(近require, need)", "english": "This room wants cleaning/to be cleaned.", "type": "句子", "keyWords": ["want"] },
    { "chinese": "逃犯已被警方通缉。", "english": "The escaped prisoner is wanted by the police.", "type": "句子", "keyWords": ["want"] },
    { "chinese": "这个东西你卖多少钱?", "english": "How much do you want for that?", "type": "句子", "keyWords": ["want"] },
    { "chinese": "招工", "english": "hands wanted", "type": "短语", "keyWords": ["want"] },
    { "chinese": "缺少，缺乏，需要(金钱、食物等)", "english": "want for (money, food)", "type": "短语", "keyWords": ["want"] },
    { "chinese": "他是个清心寡欲的人。", "english": "He is a man of few wants.", "type": "句子", "keyWords": ["want"] },
    { "chinese": "n.[C][U]战争(状态或时期);斗争;对抗;与…交战", "english": "war /wɔː/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]病房;监护室;(英)牢房", "english": "ward /wɔːd/", "type": "单词", "keyWords": [] },
    { "chinese": "表示“物品，器皿”，如：五金器具/计算机硬件，软件，家居用品，银器", "english": "ware", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]战争;作战;竞争;冲突", "english": "warfare /ˈwɔːfeə/", "type": "单词", "keyWords": [] },
    { "chinese": "a.温暖的，暖和的;热情的，热心的;v.使温暖，弄热;使兴奋;vi.变温暖;warmly ad.热情地，温暖地", "english": "warm /wɔːm/", "type": "单词", "keyWords": [] },
    { "chinese": "热身;加温;预热;使兴奋", "english": "warm (...) up", "type": "短语", "keyWords": ["warm"] },
    { "chinese": "a.热情的;富于同情心的", "english": "warm-hearted /ˌwɔːm ˈhɑːtɪd/", "type": "单词", "keyWords": [] },
    { "chinese": "a.热情的;[动]温血的，恒温的(反cold-blooded)", "english": "warm-blooded /ˌwɔːm ˈblʌdɪd/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U](可与a连用)暖和，温暖;热心", "english": "warmth /wɔːmθ/", "type": "单词", "keyWords": [] },
    { "chinese": "v.警告;告诫;提醒;vi.发出警告;warning n.[C][U]/a.", "english": "warn /wɔːn/", "type": "单词", "keyWords": [] },
    { "chinese": "警告/提醒/告诫某人某事(可能发生)", "english": "warn sb. of/about sth.", "type": "短语", "keyWords": ["warn"] },
    { "chinese": "我曾经提醒过她那要花很多钱。", "english": "I warned her of the high cost.", "type": "句子", "keyWords": ["warn"] },
    { "chinese": "我曾经提醒过她那要花很多钱。", "english": "I warned her that it would cost a lot.", "type": "句子", "keyWords": ["warn"] },
    { "chinese": "警告某人别做/提防某事", "english": "warn sb. not to do./warn sb. against doing...", "type": "短语", "keyWords": ["warn"] },
    { "chinese": "发出警告", "english": "give sb. a warning", "type": "短语", "keyWords": ["warn"] },
    { "chinese": "突然;不经招呼", "english": "without warning", "type": "短语", "keyWords": ["warn"] },
    { "chinese": "n.[C]军舰，战舰", "english": "warship /ˈwɔːʃɪp/", "type": "单词", "keyWords": [] },
    { "chinese": "v.洗，洗涤，冲洗;washing n.[U]洗涤，冲洗", "english": "wash /wɒʃ/", "type": "单词", "keyWords": [] },
    { "chinese": "这料子经洗吗?", "english": "Will this material wash?", "type": "句子", "keyWords": ["wash"] },
    { "chinese": "这衣服经得起洗/很耐洗。", "english": "The dress washes well.", "type": "句子", "keyWords": ["wash"] },
    { "chinese": "洗掉;冲走;卷走", "english": "wash...away", "type": "短语", "keyWords": ["wash"] },
    { "chinese": "洗(餐具);将某物冲到岸边", "english": "wash...up", "type": "短语", "keyWords": ["wash"] },
    { "chinese": "洗餐具", "english": "do the washing-up", "type": "短语", "keyWords": ["wash"] },
    { "chinese": "n.[U](可与a连用)浪费;n.[U]废弃物;a.废弃的;v.浪费", "english": "waste /weɪst/", "type": "单词", "keyWords": [] },
    { "chinese": "被浪费(近go to ruin)", "english": "go/run to waste", "type": "短语", "keyWords": ["waste"] },
    { "chinese": "做某事是浪费时间", "english": "It is a waste of time doing sth.", "type": "短语", "keyWords": ["waste"] },
    { "chinese": "废纸/水", "english": "waste paper/water", "type": "短语", "keyWords": ["waste"] },
    { "chinese": "赶紧做某事", "english": "waste/lose no time (in) doing sth.", "type": "短语", "keyWords": ["waste"] },
    { "chinese": "(在…上)浪费;滥用", "english": "waste sth. on sb./sth.", "type": "短语", "keyWords": ["waste"] },
    { "chinese": "医生及时挽救了那个受伤的男孩。", "english": "The doctors wasted no time saving the injured boy.", "type": "句子", "keyWords": ["waste"] },
    { "chinese": "不浪费就不缺乏。(俭以防匮)", "english": "Waste not, want not.", "type": "句子", "keyWords": ["waste"] },
    { "chinese": "v.观看(见see);注视;看守;留心;注意;监视;n.[U]观看;注视;看守;注意;监视;观察;n.[C]手表", "english": "watch /wɒtʃ/", "type": "单词", "keyWords": [] },
    { "chinese": "制表业", "english": "watchmaking", "type": "短语", "keyWords": ["watch"] },
    { "chinese": "n.[C]巡夜者，看守人", "english": "watchman", "type": "单词", "keyWords": ["watch"] },
    { "chinese": "n.[C]瞭望塔", "english": "watchtower", "type": "单词", "keyWords": ["watch"] },
    { "chinese": "留意时间", "english": "watch the time", "type": "短语", "keyWords": ["watch"] },
    { "chinese": "照顾某人;监视某人", "english": "watch sb.", "type": "短语", "keyWords": ["watch"] },
    { "chinese": "小心，留神(近look out)", "english": "watch out (for sth.)", "type": "短语", "keyWords": ["watch"] },
    { "chinese": "注意你在往哪里走!", "english": "Watch where you are going!", "type": "句子", "keyWords": ["watch"] },
    { "chinese": "当心脚下;谨慎从事", "english": "watch one's step", "type": "短语", "keyWords": ["watch"] },
    { "chinese": "值夜", "english": "keep watch at night", "type": "短语", "keyWords": ["watch"] },
    { "chinese": "密切注意", "english": "keep (a) close watch on...", "type": "短语", "keyWords": ["watch"] },
    { "chinese": "值班(比较on duty)", "english": "on watch", "type": "短语", "keyWords": ["watch"] },
    { "chinese": "将表对准", "english": "set a watch", "type": "短语", "keyWords": ["watch"] },
    { "chinese": "n.[U]水;(pl.)大片水域;海/河水;v.浇水;vi.流口水;充满泪水", "english": "water /ˈwɔːtə/", "type": "单词", "keyWords": [] },
    { "chinese": "淡水", "english": "fresh water", "type": "短语", "keyWords": ["water"] },
    { "chinese": "自来水;活水", "english": "running water", "type": "短语", "keyWords": ["water"] },
    { "chinese": "n.[C]瀑布", "english": "waterfall", "type": "单词", "keyWords": ["water"] },
    { "chinese": "远海海域", "english": "the distant waters", "type": "短语", "keyWords": ["water"] },
    { "chinese": "黄河水域", "english": "the waters of the Huanghe River", "type": "短语", "keyWords": ["water"] },
    { "chinese": "(论据、理由等)成立，站得住，合情合理(常用于否定)", "english": "hold water", "type": "短语", "keyWords": ["water"] },
    { "chinese": "浇花园", "english": "water the garden", "type": "短语", "keyWords": ["water"] },
    { "chinese": "想吃葡萄而流口水", "english": "water for the grapes", "type": "短语", "keyWords": ["water"] },
    { "chinese": "静水流深;沉默者深谋;大智若愚。", "english": "Still waters run deep.", "type": "句子", "keyWords": ["water"] },
    { "chinese": "a.防水的(=water-resistant, watertight)", "english": "waterproof /ˈwɔːtəpruːf/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]波浪，波涛;(手等)挥动;vi.挥手示意;(水)波动，起伏;vt.挥手示意;挥动;使波动", "english": "wave /weɪv/", "type": "单词", "keyWords": [] },
    { "chinese": "挥手", "english": "a wave of the hand", "type": "短语", "keyWords": ["wave"] },
    { "chinese": "声波", "english": "a sound wave", "type": "短语", "keyWords": ["wave"] },
    { "chinese": "风中麦浪滚滚", "english": "waves of wheat in the wind", "type": "短语", "keyWords": ["wave"] },
    { "chinese": "一阵阵，一批批", "english": "in waves", "type": "短语", "keyWords": ["wave"] },
    { "chinese": "挥手示意汽车继续向前开", "english": "wave the cars on", "type": "短语", "keyWords": ["wave"] },
    { "chinese": "挥手向我们告别", "english": "wave us goodbye", "type": "短语", "keyWords": ["wave"] },
    { "chinese": "他挥手叫我们停住。(近sign)", "english": "He waved (to) us to stop.", "type": "句子", "keyWords": ["wave"] },
    { "chinese": "n.[C]路，道路;方法，手段;方向;路途;路线;方面", "english": "way /weɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "(向车站)一路上/自始至终(一直跑)", "english": "(run) all the way (to the station)", "type": "短语", "keyWords": ["way"] },
    { "chinese": "以这种或那种方式;在某方面", "english": "in one way or another", "type": "短语", "keyWords": ["way"] },
    { "chinese": "处事方式", "english": "the way to do sth./of doing sth.", "type": "短语", "keyWords": ["way"] },
    { "chinese": "某人的世界观", "english": "the way (that/in which) one looks at the world", "type": "短语", "keyWords": ["way"] },
    { "chinese": "我像他以前那样做。", "english": "I'm doing it the way he did it.", "type": "句子", "keyWords": ["way"] },
    { "chinese": "在某种程度上", "english": "in a way/in one way/in some ways", "type": "短语", "keyWords": ["way"] },
    { "chinese": "这样/那样/决不，一点也不", "english": "in this/that/no way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "单行道/双向道", "english": "a one-way/two-way street", "type": "短语", "keyWords": ["way"] },
    { "chinese": "带路", "english": "lead the way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "为某人引路", "english": "show sb. the way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "迷路", "english": "lose one's way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "故意朝别处看", "english": "look the other way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "挤/设法/摸索着前进", "english": "make/force/arm/push/fight/feel one's way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "在去…的途中;在进行中;即将到来", "english": "on the/one's way to", "type": "短语", "keyWords": ["way"] },
    { "chinese": "冬天就要来到了。", "english": "Winter is on the way.", "type": "句子", "keyWords": ["way"] },
    { "chinese": "按自己的意愿行事(尤指不听劝告)", "english": "go one's own way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "恰恰相反;相反地", "english": "be the other way round, be very much/quite the other way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "在进行中;在行进", "english": "under way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "给…让路;让位", "english": "make way for", "type": "短语", "keyWords": ["way"] },
    { "chinese": "随便说", "english": "by the way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "让位给…;向…屈服", "english": "give way to...", "type": "短语", "keyWords": ["way"] },
    { "chinese": "断裂;倒塌", "english": "give way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "为所欲为", "english": "get/have one's own way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "经由，取道", "english": "by way of", "type": "短语", "keyWords": ["way"] },
    { "chinese": "造成不便或挡路", "english": "in the/one's way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "不挡道", "english": "out of the way", "type": "短语", "keyWords": ["way"] },
    { "chinese": "pron.我们(主格)", "english": "we /wiː/", "type": "单词", "keyWords": [] },
    { "chinese": "a.弱的;能力差的(in/at sth);虚弱的;薄弱的;软弱的;weakness n.[U]虚弱;软弱;n.[C]弱点/缺点", "english": "weak /wiːk/", "type": "单词", "keyWords": [] },
    { "chinese": "v.(使)变弱;(使)减弱;削弱", "english": "weaken /ˈwiːkən/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]财富，财产;富有", "english": "wealth /welθ/", "type": "单词", "keyWords": [] },
    { "chinese": "a.富的(近well-off, well-to-do富裕的)", "english": "wealthy /ˈwelθi/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]武器，兵器", "english": "weapon /ˈwepən/", "type": "单词", "keyWords": [] },
    { "chinese": "核武器", "english": "nuclear weapons", "type": "短语", "keyWords": ["weapon"] },
    { "chinese": "v.穿着，穿戴;戴;穿破;磨损;vi.穿破;磨损;耐用;耐穿;worn a.用旧的;疲惫的，憔悴的", "english": "wear /weə/", "type": "单词", "keyWords": [] },
    { "chinese": "面无表情", "english": "wear a blank look", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "留短胡须", "english": "wear a short beard", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "面带微笑", "english": "wear a smile", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "佩剑", "english": "wear a sword", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "磨坏或耗尽", "english": "wear sth. out", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "磨损掉", "english": "wear (the rocks) away", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "使筋疲力尽(=tire sb. out)", "english": "wear sb. out", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "使我失去了耐心", "english": "wear my patience", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "在石阶上磨出了洞", "english": "wear holes in the stone steps", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "这些鞋很耐穿。", "english": "These shoes wear long/well.", "type": "句子", "keyWords": ["wear"] },
    { "chinese": "滴水石穿，绳锯木断。做事贵坚持。", "english": "Constant dripping wears away a stone.", "type": "句子", "keyWords": ["wear"] },
    { "chinese": "穿坏了;累极了", "english": "be worn out", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "旧外套", "english": "a worn coat", "type": "短语", "keyWords": ["wear"] },
    { "chinese": "a.疲倦的;累人的", "english": "weary /ˈwɪəri/", "type": "单词", "keyWords": [] },
    { "chinese": "令人困乏的旅程", "english": "a weary journey", "type": "短语", "keyWords": ["weary"] },
    { "chinese": "倦容", "english": "a weary look", "type": "短语", "keyWords": ["weary"] },
    { "chinese": "n.[U]天气;气象;天气预报", "english": "weather /ˈweðə/", "type": "单词", "keyWords": [] },
    { "chinese": "不论天气如何;风雨无阻", "english": "in all weathers", "type": "短语", "keyWords": ["weather"] },
    { "chinese": "n.[C]天气预报员", "english": "weatherman /ˈweðəmæn/", "type": "单词", "keyWords": ["weather"] },
    { "chinese": "v.编织，织布;编造(谎言、情节);weaver n.[C]织布者，织工", "english": "weave /wiːv/", "type": "单词", "keyWords": [] },
    { "chinese": "编篮子", "english": "weave a basket", "type": "短语", "keyWords": ["weave"] },
    { "chinese": "编造一个故事", "english": "weave a tale", "type": "短语", "keyWords": ["weave"] },
    { "chinese": "将棉线织成布", "english": "weave cotton thread into cloth", "type": "短语", "keyWords": ["weave"] },
    { "chinese": "n.[C]蜘蛛网;网状物", "english": "web /web/", "type": "单词", "keyWords": [] },
    { "chinese": "蜘蛛网", "english": "a spider's web", "type": "短语", "keyWords": ["web"] },
    { "chinese": "电话线网", "english": "a web of telephone wires", "type": "短语", "keyWords": ["web"] },
    { "chinese": "n.[C]网站", "english": "website /ˈwebsaɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]结婚;婚礼", "english": "wedding /ˈwedɪŋ/", "type": "单词", "keyWords": [] },
    { "chinese": "在银婚婚礼上", "english": "at the silver wedding", "type": "短语", "keyWords": ["wedding"] },
    { "chinese": "n.[C]星期三", "english": "Wednesday /ˈwenzdeɪ, ˈwenzdi/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]周，星期", "english": "week /wiːk/", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]平常日;工作日", "english": "weekday /ˈwiːkdeɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "在工作日", "english": "on weekdays", "type": "短语", "keyWords": ["weekday"] },
    { "chinese": "n.[C]周末;在周末", "english": "weekend /ˌwiːkˈend/", "type": "单词", "keyWords": [] },
    { "chinese": "他们整个周末都在日夜工作。", "english": "They worked around the clock and over the entire weekend.", "type": "句子", "keyWords": ["weekend"] },
    { "chinese": "a.每周的;每周一次的;ad.每周(一次)地;n.[C]周报，周刊", "english": "weekly /ˈwiːkli/", "type": "单词", "keyWords": [] },
    { "chinese": "v.哭泣;流泪;为死者哀哭", "english": "weep /wiːp/", "type": "单词", "keyWords": [] },
    { "chinese": "因听到悲痛的消息而哭起来", "english": "weep at the sad news", "type": "短语", "keyWords": ["weep"] },
    { "chinese": "v.称…的重量;掂量，权衡，斟酌;vi.重若干;称得重量", "english": "weigh /weɪ/", "type": "单词", "keyWords": [] },
    { "chinese": "它重12千克。(weighty a.重的)", "english": "It weighs 12 kilos. = It is 12 kilos in weight. = It is 12 Kg weighty.", "type": "句子", "keyWords": ["weigh"] },
    { "chinese": "衡器", "english": "a weighing machine", "type": "短语", "keyWords": ["weigh"] },
    { "chinese": "斟酌词句", "english": "weigh one's words", "type": "短语", "keyWords": ["weigh"] },
    { "chinese": "使负重;压倒;把压垮，压弯", "english": "weigh sb./sth. down", "type": "短语", "keyWords": ["weigh"] },
    { "chinese": "n.[U]体重;重量;n.[C]压东西的重物;秤，砝码", "english": "weight /weɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "a.没有重量的;失重的", "english": "weightless /ˈweɪtləs/", "type": "单词", "keyWords": ["weight"] },
    { "chinese": "举重", "english": "weight-lifting", "type": "短语", "keyWords": ["weight"] },
    { "chinese": "发胖", "english": "gain/put on weight", "type": "短语", "keyWords": ["weight"] },
    { "chinese": "减肥", "english": "lose weight", "type": "短语", "keyWords": ["weight"] },
    { "chinese": "按重量计算", "english": "by weight", "type": "短语", "keyWords": ["weight"] },
    { "chinese": "镇纸", "english": "a paper weight", "type": "短语", "keyWords": ["weight"] },
    { "chinese": "a.怪异的，奇怪的，怪诞的", "english": "weird /wɪəd/", "type": "单词", "keyWords": [] },
    { "chinese": "v./n.[C]欢迎;a.受欢迎的;被允许的;不必感谢的", "english": "welcome /ˈwelkəm/", "type": "单词", "keyWords": [] },
    { "chinese": "对那陌生人很不友好的欢迎", "english": "give the stranger an unfriendly welcome", "type": "短语", "keyWords": ["welcome"] },
    { "chinese": "可随意…(一般不说welcome sb. to do sth.)", "english": "be welcome to do sth.", "type": "短语", "keyWords": ["welcome"] },
    { "chinese": "我们非常欢迎你加入我们。", "english": "You are welcome to join us.", "type": "句子", "keyWords": ["welcome"] },
    { "chinese": "可以自由取用某物", "english": "be welcome to sth.", "type": "短语", "keyWords": ["welcome"] },
    { "chinese": "我书房里所有的书你尽管用。", "english": "You are welcome to any book in my study.", "type": "句子", "keyWords": ["welcome"] },
    { "chinese": "欢迎(你们)回到中国!", "english": "Welcome back to China!", "type": "句子", "keyWords": ["welcome"] },
    { "chinese": "不用客气，不用谢。", "english": "You're welcome.", "type": "句子", "keyWords": ["welcome"] },
    { "chinese": "n.[U]福利(事业)", "english": "welfare /ˈwelfeə/", "type": "单词", "keyWords": [] },
    { "chinese": "福利基金", "english": "a welfare fund", "type": "短语", "keyWords": ["welfare"] },
    { "chinese": "社会福利", "english": "social welfare", "type": "短语", "keyWords": ["welfare"] },
    { "chinese": "ad.好;完全;很，相当;a.健康的;令人满意的;n.[C]井，水井;油(或气)井", "english": "well /wel/", "type": "单词", "keyWords": [] },
    { "chinese": "除…之外(还);和…一样好", "english": "as well as", "type": "短语", "keyWords": ["well"] },
    { "chinese": "也，又", "english": "as well", "type": "短语", "keyWords": ["well"] },
    { "chinese": "n.[U]康乐;健康;幸福", "english": "well-being", "type": "单词", "keyWords": ["well"] },
    { "chinese": "a.小康的，富裕的", "english": "well-to-do", "type": "单词", "keyWords": ["well"] },
    { "chinese": "a.富裕的;处境好的", "english": "well off", "type": "短语", "keyWords": ["well"] },
    { "chinese": "他家比我家富裕得多。", "english": "His family is much better off than mine.", "type": "句子", "keyWords": ["well"] },
    { "chinese": "人数大大超过20万。", "english": "They numbered well over 200,000.", "type": "句子", "keyWords": ["well"] },
    { "chinese": "他一定大大超过五十岁了。", "english": "He must be well over fifty.", "type": "句子", "keyWords": ["well"] },
    { "chinese": "很值得一看", "english": "be well worth seeing", "type": "短语", "keyWords": ["well"] },
    { "chinese": "赞扬;对…评价好", "english": "speak/think well of", "type": "短语", "keyWords": ["well"] },
    { "chinese": "做某事倒也无妨;最好，倒不如", "english": "may/might (just) as well do sth.", "type": "短语", "keyWords": ["well"] },
    { "chinese": "谚：结果好，万事好。", "english": "All is well that ends well.", "type": "句子", "keyWords": ["well"] },
    { "chinese": "谚：良好的开端，成功的一半。", "english": "Well begun is half done.", "type": "句子", "keyWords": ["well"] },
    { "chinese": "a.有名的;众所周知的(to sb., for sth., as...)", "english": "well-known /ˌwel ˈnəʊn/", "type": "单词", "keyWords": ["well"] },
    { "chinese": "n.[C]/a.西，西方(的);ad.向西方", "english": "west /west/", "type": "单词", "keyWords": [] },
    { "chinese": "城西有个大公园。", "english": "West of the city lies a large park.", "type": "句子", "keyWords": ["west"] }
];
