const qgl61_75 = [
    { "chinese": "n.(U)专心；集中（注意力）", "english": "concentration /,kɒnsn'treɪʃn/", "type": "单词", "keyWords": ["concentrate"] },
    { "chinese": "n.(C)概念；理论；观念，想法，思想", "english": "concept /'kɒnsept/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)有关的事；关心；忧虑 v.与..有关；使关心；使担心", "english": "concern /kən'sɜ:n/", "type": "单词", "keyWords": [] },
    { "chinese": "prep.关于，论及，就...说（其他见as for）", "english": "concerning", "type": "单词", "keyWords": ["concern"] },
    { "chinese": "关心此事", "english": "have concern about the matter", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "这不关你的事。", "english": "It is no concern of yours.", "type": "句子", "keyWords": ["concern"] },
    { "chinese": "那与我无关。", "english": "That doesn't concern me.", "type": "句子", "keyWords": ["concern"] },
    { "chinese": "关心（近be worried about）", "english": "be concerned about..", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "与...有关（近be connected/ associated with, have something to do with）", "english": "be concerned with...", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "就我个人来说", "english": "as/ so far as I am concerned", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "有关的（近associated）（作前置定语）担忧的（近worried）", "english": "concerned(作后置定语)", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "与凶杀案有牵连的人都已查明。", "english": "Everyone concerned in the murder case has been identified.", "type": "句子", "keyWords": ["concern"] },
    { "chinese": "一副担忧的表情", "english": "a concerned look", "type": "短语", "keyWords": ["concern"] },
    { "chinese": "n.(C)音乐会", "english": "concert /'kɒnsət/", "type": "单词", "keyWords": [] },
    { "chinese": "vt.推断出；缔结 vi.结束，终结", "english": "conclude /kən'klu:d/", "type": "单词", "keyWords": [] },
    { "chinese": "结束段/结束语", "english": "the concluding paragraph/ remarks", "type": "短语", "keyWords": ["conclude"] },
    { "chinese": "n.(C)结论，推论；结束，结尾，结局；缔结", "english": "conclusion /kən'klu:ʒn/", "type": "单词", "keyWords": [] },
    { "chinese": "a.结论性的；确凿的", "english": "conclusive", "type": "单词", "keyWords": ["conclusion"] },
    { "chinese": "所得的结论是", "english": "arrive at/ reach/ draw/ come to the conclusion that...", "type": "短语", "keyWords": ["conclusion"] },
    { "chinese": "匆忙得出...的结论", "english": "jump to the conclusion that...", "type": "短语", "keyWords": ["conclusion"] },
    { "chinese": "确凿的证据", "english": "a conclusive proof", "type": "短语", "keyWords": ["conclusive"] },
    { "chinese": "n.(U)混凝土 a.混凝土（制）的；具体的；实在的 v.用混凝土浇筑（或涂于）", "english": "concrete /'kɒŋkri:t/", "type": "单词", "keyWords": [] },
    { "chinese": "具体的事实/想法/证据", "english": "concrete facts/ thoughts/ evidence", "type": "短语", "keyWords": ["concrete"] },
    { "chinese": "v.谴责；判处", "english": "condemn /kən'dem/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)状况 (C)条件 (pl)环境", "english": "condition /kən'dɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "a.有条件的", "english": "conditional", "type": "单词", "keyWords": ["condition"] },
    { "chinese": "n.(C)（冷/暖）空气调节器；护发剂", "english": "conditioner /kən'dɪʃənə/", "type": "单词", "keyWords": ["condition"] },
    { "chinese": "健康正常；保存得好", "english": "in good condition", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "在目前情况下", "english": "in/ under existing conditions", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "只要，在...条件下", "english": "on condition that...", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "空调房", "english": "an air-conditioned room", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "绝不", "english": "in/ under no condition", "type": "短语", "keyWords": ["condition"] },
    { "chinese": "只要你不乱花钱，我就让你去。", "english": "I'll let you go on condition that you never waste money.", "type": "句子", "keyWords": ["condition"] },
    { "chinese": "vt.进行；传导（电、热）；引领（近lead）；控制，管理（近control, manage） n.(U)行为，举止；管理（近behaviour）", "english": "conduct /kən'dʌkt/", "type": "单词", "keyWords": [] },
    { "chinese": "引导我们游览城市", "english": "conduct us around the city", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "进行会议/调查", "english": "conduct a meeting/survey", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "优良/不良的品行", "english": "good/ bad conduct", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "有导游陪同的旅行", "english": "a conducted tour", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "表现；为人", "english": "conduct oneself", "type": "短语", "keyWords": ["conduct"] },
    { "chinese": "n.(C)公交车等的）售票员；列车员；（乐队的）指挥；导体", "english": "conductor /kən'dʌktə/", "type": "单词", "keyWords": ["conduct"] },
    { "chinese": "n.(C)（正式的）会议；讨论会，协商会", "english": "conference /'kɒnfərəns/", "type": "单词", "keyWords": [] },
    { "chinese": "（在）记者招待会/新闻发布会（上）", "english": "(at)a press/ news conference", "type": "短语", "keyWords": ["conference"] },
    { "chinese": "vt.vi.承认；坦白（辨析见admit）", "english": "confess /kən'fes/", "type": "单词", "keyWords": [] },
    { "chinese": "承认偷了....", "english": "confess (to) having stolen...", "type": "短语", "keyWords": ["confess"] },
    { "chinese": "向某人承认", "english": "confess to sb. that...", "type": "短语", "keyWords": ["confess"] },
    { "chinese": "承认错误", "english": "confess oneself to be in the wrong", "type": "短语", "keyWords": ["confess"] },
    { "chinese": "n.(C)(U)供词；认罪；坦白；承认", "english": "confession /kən'feʃn/", "type": "单词", "keyWords": ["confess"] },
    { "chinese": "承认错误；供认罪行；交代", "english": "make a confession", "type": "短语", "keyWords": ["confession"] },
    { "chinese": "n.(U)信任；信心", "english": "confidence /'kɒnfɪdəns/", "type": "单词", "keyWords": [] },
    { "chinese": "a.有信心的；自信的", "english": "confident", "type": "单词", "keyWords": ["confidence"] },
    { "chinese": "对...缺乏/有信心", "english": "lack/ have confidence in", "type": "短语", "keyWords": ["confidence"] },
    { "chinese": "满怀信心地；有把握地", "english": "with confidence", "type": "短语", "keyWords": ["confidence"] },
    { "chinese": "对...有信心的（近be sure of）", "english": "be confident of...", "type": "短语", "keyWords": ["confident"] },
    { "chinese": "vt.（进一步）证实；确认；使更坚固（坚定、坚强）", "english": "confirm /kən'fɜ:m/", "type": "单词", "keyWords": [] },
    { "chinese": "a.可确定的；能证实的", "english": "confirmable", "type": "单词", "keyWords": ["confirm"] },
    { "chinese": "n.(C)(U)证实；确认", "english": "confirmation", "type": "单词", "keyWords": ["confirm"] },
    { "chinese": "还待确认。", "english": "It wants yet to be confirmed.", "type": "句子", "keyWords": ["confirm"] },
    { "chinese": "你所告诉我的有关里奥的事证实了我对他打妻子的怀疑。", "english": "What you had told me about Leo confirmed me in my suspicion (= confirmed my suspicion) that he beat his wife.", "type": "句子", "keyWords": ["confirm"] },
    { "chinese": "vi./n.(C)(U)争论；战斗；冲突，矛盾，抵触（with）", "english": "conflict /'kɒnflɪkt/", "type": "单词", "keyWords": [] },
    { "chinese": "意见的冲突", "english": "a conflict of opinions/views", "type": "短语", "keyWords": ["conflict"] },
    { "chinese": "相互矛盾的证据", "english": "conflicting evidence", "type": "短语", "keyWords": ["conflict"] },
    { "chinese": "和...冲突", "english": "come into conflict with/ be in conflict with/ conflict with", "type": "短语", "keyWords": ["conflict"] },
    { "chinese": "v.使..混乱；使..慌乱；使...困惑", "english": "confuse /kən'fju:z/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)困惑；糊涂", "english": "confusion /kən'fju:ʒn/", "type": "单词", "keyWords": ["confuse"] },
    { "chinese": "感到/使人困惑的", "english": "confused/ confusing", "type": "单词", "keyWords": ["confuse"] },
    { "chinese": "被...弄迷糊/弄得发慌", "english": "feel/ be confused (with/at/ about sth.)", "type": "短语", "keyWords": ["confuse"] },
    { "chinese": "他脸上困惑的表情", "english": "a confused expression on his face", "type": "短语", "keyWords": ["confuse"] },
    { "chinese": "n.(U)挤满；拥塞；充血", "english": "congestion /kən'dʒestʃən/", "type": "单词", "keyWords": [] },
    { "chinese": "vt.祝贺，向...道喜", "english": "congratulate /kən'ɡrætʃuleɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "向某人祝贺某事", "english": "congratulate sb. on sth.", "type": "短语", "keyWords": ["congratulate"] },
    { "chinese": "n.(pl)祝贺，道贺 (U)贺词", "english": "congratulation /kən,ɡrætʃu'leɪʃn/", "type": "单词", "keyWords": [] },
    { "chinese": "祝贺...！", "english": "Congratulations on sth.!", "type": "短语", "keyWords": ["congratulation"] },
    { "chinese": "贺信", "english": "a letter of congratulation", "type": "短语", "keyWords": ["congratulation"] },
    { "chinese": "n.(C)代表大会；立法机关；(the C-)美国国会", "english": "congress /'kɒŋɡres/", "type": "单词", "keyWords": [] },
    { "chinese": "v./vi.连接（常与to,with连用）；联系；接通电话", "english": "connect /kə'nekt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)(U)连接；联系", "english": "connection", "type": "单词", "keyWords": ["connect"] },
    { "chinese": "这管子和一根较小的管子连通着。", "english": "This pipe connects with a smaller one.", "type": "句子", "keyWords": ["connect"] },
    { "chinese": "与·..有关系/联系", "english": "be connected with...", "type": "短语", "keyWords": ["connect"] },
    { "chinese": "那个老头被怀疑与犯罪事件有关。", "english": "That old man was suspected to be connected with the crime.", "type": "句子", "keyWords": ["connect"] },
    { "chinese": "vt.击败，攻克；征服；克服（困难等）", "english": "conquer /'kɒŋkə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)征服", "english": "conquest", "type": "单词", "keyWords": ["conquer"] },
    { "chinese": "n.(C)征服者，胜利者", "english": "conqueror /'kɒŋkərə/", "type": "单词", "keyWords": ["conquer"] },
    { "chinese": "人能战胜自然。", "english": "Man can conquer nature.", "type": "句子", "keyWords": ["conquer"] },
    { "chinese": "被征服者，失败者", "english": "the conquered", "type": "短语", "keyWords": ["conquer"] },
    { "chinese": "n.(C)良心", "english": "conscience /'kɒnʃəns/", "type": "单词", "keyWords": [] },
    { "chinese": "问心有愧", "english": "have a bad/ guilty conscience", "type": "短语", "keyWords": ["conscience"] },
    { "chinese": "问心无愧；无愧于心", "english": "have a good/ clear conscience", "type": "短语", "keyWords": ["conscience"] },
    { "chinese": "a.意识到的，有意识的；有知觉的，神志清醒的", "english": "conscious /'kɒnʃəs/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)知觉；意识", "english": "consciousness", "type": "单词", "keyWords": ["conscious"] },
    { "chinese": "意识到", "english": "be conscious/aware of", "type": "短语", "keyWords": ["conscious"] },
    { "chinese": "失去/恢复知觉", "english": "lose/ regain/ recover one's consciousness", "type": "短语", "keyWords": ["consciousness"] },
    { "chinese": "n.(C)结果，后果 (U)重要（性）", "english": "consequence /'kɒnsɪkwəns/", "type": "单词", "keyWords": [] },
    { "chinese": "a.随之发生的", "english": "consequent", "type": "单词", "keyWords": ["consequence"] },
    { "chinese": "ad.结果；因此", "english": "consequently (=in consequence/ thus)", "type": "单词", "keyWords": ["consequence"] },
    { "chinese": "考虑后果", "english": "consider the consequences", "type": "短语", "keyWords": ["consequence"] },
    { "chinese": "要人", "english": "a man of consequence", "type": "短语", "keyWords": ["consequence"] },
    { "chinese": "a.保守的；守旧的", "english": "conservative /kən'sɜ:vətɪv/", "type": "单词", "keyWords": [] },
    { "chinese": "（英国的）保守党", "english": "the Conservative Party", "type": "短语", "keyWords": ["conservative"] },
    { "chinese": "vt.认为（+ sb./sth. to be），考虑，细想，思量，斟酌（+ doing sth.）", "english": "consider /kən'sɪdə/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)考虑；体谅，照顾，关心", "english": "consideration", "type": "单词", "keyWords": ["consider"] },
    { "chinese": "把某人看作；认为某人已经...", "english": "consider sb. (to be/ to have done sth.)...", "type": "短语", "keyWords": ["consider"] },
    { "chinese": "我正在考虑换工作。", "english": "I am considering changing my job.", "type": "句子", "keyWords": ["consider"] },
    { "chinese": "考虑到...（近concerning, with regard to, as for）", "english": "Considering...", "type": "短语", "keyWords": ["consider"] },
    { "chinese": "加以考虑；予以原谅", "english": "take... into consideration/ account", "type": "短语", "keyWords": ["consideration"] },
    { "chinese": "考虑中，研究中", "english": "(be) under consideration", "type": "短语", "keyWords": ["consideration"] },
    { "chinese": "a.相当大（重、长）的；值得考虑的；重大的；重要的", "english": "considerable /kən'sɪdərəbl/", "type": "单词", "keyWords": [] },
    { "chinese": "大量的", "english": "a considerable amount of", "type": "短语", "keyWords": ["considerable"] },
    { "chinese": "a.体谅的；考虑周到的", "english": "considerate /kən'sɪdərɪt/", "type": "单词", "keyWords": [] },
    { "chinese": "能体谅别人的", "english": "be considerate of others", "type": "短语", "keyWords": ["considerate"] },
    { "chinese": "vi.由...组成；构成（of）；存在于（in）", "english": "consist /kən'sɪst/", "type": "单词", "keyWords": [] },
    { "chinese": "在于", "english": "consist/ lie in", "type": "短语", "keyWords": ["consist"] },
    { "chinese": "幸福在于知足。", "english": "Happiness consists in contentment.", "type": "句子", "keyWords": ["consist"] },
    { "chinese": "由...组成（近be composed of, be made up of）", "english": "consist of", "type": "短语", "keyWords": ["consist"] },
    { "chinese": "那本书共有八章。", "english": "The book consists of eight chapters.", "type": "句子", "keyWords": ["consist"] },
    { "chinese": "a.经常的，连续发生的，不断的，一再重复的（有稳定不变的、反复的含义）；恒定不变的，持久不变的，固定的，稳定的", "english": "constant /'kɒnstənt/", "type": "单词", "keyWords": [] },
    { "chinese": "ad.经常不断地；一再重复地", "english": "constantly", "type": "单词", "keyWords": ["constant"] },
    { "chinese": "对爱情忠贞不渝", "english": "be constant in love", "type": "短语", "keyWords": ["constant"] },
    { "chinese": "两天接连下雨", "english": "two days of constant rain", "type": "短语", "keyWords": ["constant"] },
    { "chinese": "v.建造；构建（通过装配或组合部件而构成）；构成；创立", "english": "construct /kən'strʌkt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)建筑，建造；结构；创立 (C)建筑物", "english": "construction /kən'strʌkʃn/", "type": "单词", "keyWords": ["construct"] },
    { "chinese": "a.建设性的", "english": "constructive", "type": "单词", "keyWords": ["construct"] },
    { "chinese": "建设中", "english": "under construction", "type": "短语", "keyWords": ["construction"] },
    { "chinese": "建筑工地", "english": "construction site", "type": "短语", "keyWords": ["construction"] },
    { "chinese": "建设性的批评", "english": "constructive criticism", "type": "短语", "keyWords": ["constructive"] },
    { "chinese": "v.请教；查阅", "english": "consult /kən'sʌlt/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)顾问（on）", "english": "consultant", "type": "单词", "keyWords": ["consult"] },
    { "chinese": "n.(U)咨询 (C)咨询会", "english": "consultation", "type": "单词", "keyWords": ["consult"] },
    { "chinese": "查词典", "english": "consult a dictionary", "type": "短语", "keyWords": ["consult"] },
    { "chinese": "找医生诊治", "english": "consult a doctor", "type": "短语", "keyWords": ["consult"] },
    { "chinese": "vt.消耗；消费；耗尽；吃完；喝光；烧毁；vi.耗尽", "english": "consume /kən'sju:m/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)消费者；顾客；用户", "english": "consumer /kən'sju:mə/", "type": "单词", "keyWords": ["consume"] },
    { "chinese": "n.(U)（可加a）消耗；消费", "english": "consumption", "type": "单词", "keyWords": ["consume"] },
    { "chinese": "v./n.(U)接触；联系（多用于商业上，非亲密的朋友之间）(C)熟人", "english": "contact /'kɒntækt/", "type": "单词", "keyWords": [] },
    { "chinese": "需进一步信息的话请和我们联系。", "english": "Contact us for further information.", "type": "句子", "keyWords": ["contact"] },
    { "chinese": "同...接触；跟..保持联系", "english": "keep/be in contact with....", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "跟...有/失去联系", "english": "have/ lose contact with...", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "使...和....接触", "english": "bring .. into contact with...", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "和...接触", "english": "come/ get into contact with...", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "交际广（门路多）的人", "english": "a man of many contacts", "type": "短语", "keyWords": ["contact"] },
    { "chinese": "v.包括；含有，包含；能容纳", "english": "contain /kən'teɪn/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)容器；集装箱", "english": "container", "type": "单词", "keyWords": ["contain"] },
    { "chinese": "a.当代的；发生/存在于同一时代的 n.(C)同时代的人", "english": "contemporary /kən'temprəri/", "type": "单词", "keyWords": [] },
    { "chinese": "和莎士比亚同时代", "english": "be contemporary with Shakespeare", "type": "短语", "keyWords": ["contemporary"] },
    { "chinese": "n.(U)容积；内容；满足，满意 (pl)（书、包等）内含物；（书刊）目录 v.使满意，使满足 a.（只作表语用）满足的，甘心的", "english": "content /'kɒntent/", "type": "单词", "keyWords": [] },
    { "chinese": "目录", "english": "a table of contents", "type": "短语", "keyWords": ["content"] },
    { "chinese": "尽情，尽量", "english": "to one's heart's content", "type": "短语", "keyWords": ["content"] },
    { "chinese": "对...满意", "english": "be content with/ be contented with/ be satisfied with...", "type": "短语", "keyWords": ["content"] },
    { "chinese": "内容上和形式上", "english": "in content and form", "type": "短语", "keyWords": ["content"] },
    { "chinese": "满意的微笑", "english": "a contented smile", "type": "短语", "keyWords": ["content"] },
    { "chinese": "v./n.(C)竞赛，比赛；争夺；竞争", "english": "contest /kən'test/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(C)参赛者", "english": "contestant", "type": "单词", "keyWords": ["contest"] },
    { "chinese": "n.(C)(U)上下文；语境；背景，环境", "english": "context /'kɒntekst/", "type": "单词", "keyWords": [] },
    { "chinese": "在上下文", "english": "in context", "type": "短语", "keyWords": ["context"] },
    { "chinese": "在...情况下", "english": "in the context of", "type": "短语", "keyWords": ["context"] },
    { "chinese": "n.(C)洲；大陆", "english": "continent /'kɒntɪnənt/", "type": "单词", "keyWords": [] },
    { "chinese": "a.大陆的", "english": "continental /,kɒntɪ'nentl/", "type": "单词", "keyWords": ["continent"] },
    { "chinese": "欧洲大陆；（美）北美洲大陆", "english": "the Continent", "type": "短语", "keyWords": ["continent"] },
    { "chinese": "v./vi.继续；连续；延续", "english": "continue /kən'tɪnju:/", "type": "单词", "keyWords": [] },
    { "chinese": "n.(U)连续（性）", "english": "continuity", "type": "单词", "keyWords": ["continue"] },
    { "chinese": "a.无间断的；连续的，继续的", "english": "continuous", "type": "单词", "keyWords": ["continue"] },
    { "chinese": "a.连续的；频繁的", "english": "continual", "type": "单词", "keyWords": ["continue"] },
    { "chinese": "继续工作", "english": "continue (with) one's work", "type": "短语", "keyWords": ["continue"] },
    { "chinese": "待续；未完", "english": "to be continued", "type": "短语", "keyWords": ["continue"] },
    { "chinese": "恒（直）流电", "english": "a continuous current", "type": "短语", "keyWords": ["continuous"] },
    { "chinese": "连续射击", "english": "continuous fire", "type": "短语", "keyWords": ["continuous"] },
    { "chinese": "连续的掌声/下不停的雨/持续的担心", "english": "continual applause/ rain/worry", "type": "短语", "keyWords": ["continual"] },
    { "chinese": "n.(C)契约，合同 v.订（契约），订（合同）", "english": "contract /'kɒntrækt/", "type": "单词", "keyWords": [] },
    { "chinese": "与...订约", "english": "enter into/ make a contract with", "type": "短语", "keyWords": ["contract"] },
    { "chinese": "履行合约", "english": "fulfil a contract", "type": "短语", "keyWords": ["contract"] },
    { "chinese": "n.(the)相反；反面 a.反对的，相反的；格格不入的（强调极度的不同）", "english": "contrary /'kɒntrəri/", "type": "单词", "keyWords": [] },
    { "chinese": "是冷的反义", "english": "be the contrary of cold", "type": "短语", "keyWords": ["contrary"] },
    { "chinese": "出乎意外", "english": "be contrary to one's expectations", "type": "短语", "keyWords": ["contrary"] },
    { "chinese": "相反/正相反，我非常喜欢。", "english": "On the contrary, I like it very much.", "type": "句子", "keyWords": ["contrary"] },
    { "chinese": "不知道任何与之相反的情况", "english": "know nothing to the contrary", "type": "短语", "keyWords": ["contrary"] },
    { "chinese": "没有反证。", "english": "There is no evidence to the contrary.", "type": "句子", "keyWords": ["contrary"] },
    { "chinese": "n.(U)对照；比较 (C)对照；差别；形成对照的人或事物（to） v.（使用）成对比；（使）成对照", "english": "contrast /'kɒntrɑ:st/", "type": "单词", "keyWords": [] },
    { "chinese": "对比之下", "english": "by contrast", "type": "短语", "keyWords": ["contrast"] },
    { "chinese": "和...成对比；和...大不相同", "english": "in contrast with/to...", "type": "短语", "keyWords": ["contrast"] },
    { "chinese": "与旧的明显差别", "english": "a sharp contrast to the old one", "type": "短语", "keyWords": ["contrast"] },
    { "chinese": "和...的明显差别", "english": "a striking contrast between ...and....", "type": "短语", "keyWords": ["contrast"] },
    { "chinese": "n. 贡献者，捐助者，投稿人", "english": "contributor", "type": "单词", "keyWords": [] },
    { "chinese": "贡献；捐献；捐助；稿件（n.）", "english": "contribution", "type": "单词", "keyWords": [] },
    { "chinese": "作贡献；有助于；促使；捐款", "english": "contribute to= make (great) contributions to", "type": "短语", "keyWords": ["contribute", "contribution"] },
    { "chinese": "vi. 贡献；捐（款等）；投（稿），撰（稿）(to)", "english": "contribute", "type": "单词", "keyWords": [] },
    { "chinese": "宋朝为世界文明贡献了三大发明。", "english": "The Song Dynasty contributed three great inventions to world civilization.", "type": "句子", "keyWords": ["contribute"] },
    { "chinese": "v. 控制；支配（n. 控制；支配；控制装置（器））", "english": "control", "type": "单词", "keyWords": [] },
    { "chinese": "生育控制，节制生育", "english": "birth control", "type": "短语", "keyWords": ["control"] },
    { "chinese": "控制不住...", "english": "lose control of...", "type": "短语", "keyWords": ["control"] },
    { "chinese": "处于失控状态中", "english": "out of/ beyond control", "type": "短语", "keyWords": ["control"] },
    { "chinese": "控制着，管理", "english": "in control of", "type": "短语", "keyWords": ["control"] },
    { "chinese": "受...管制（管理、支配），在...管辖下的", "english": "under/in the control of...", "type": "短语", "keyWords": ["control"] },
    { "chinese": "抑制，治理（水患），控制（火灾）", "english": "get/bring.. under control", "type": "短语", "keyWords": ["control"] },
    { "chinese": "（机场等）指挥（调度）塔台", "english": "control tower", "type": "短语", "keyWords": ["control"] },
    { "chinese": "控制，统制", "english": "take/ have/ hold/ gain control of", "type": "短语", "keyWords": ["control"] },
    { "chinese": "n. 方便；生活上的便利设备（a. 方便的；（提供）便利的；近处的；合适的）", "english": "convenience/ convenient", "type": "单词", "keyWords": [] },
    { "chinese": "为了便利起见", "english": "for convenience", "type": "短语", "keyWords": ["convenience"] },
    { "chinese": "顺便；方便的时候", "english": "at one's convenience", "type": "短语", "keyWords": ["convenience"] },
    { "chinese": "为了...的方便起见", "english": "for the convenience of", "type": "短语", "keyWords": ["convenience"] },
    { "chinese": "你方便的话...", "english": "whenever it is convenient to/ for you", "type": "短语", "keyWords": ["convenient"] },
    { "chinese": "n. 谈话；会话；一次谈话；一次会话（a. 谈话的）", "english": "conversation/ conversational", "type": "单词", "keyWords": [] },
    { "chinese": "与某人交谈", "english": "in conversation with sb.", "type": "短语", "keyWords": ["conversation"] },
    { "chinese": "vt. 传达；表达；传导/送/递；运送，搬运（n. 传达；运输）", "english": "convey/ conveyance", "type": "单词", "keyWords": [] },
    { "chinese": "把....传达给...；把...运输给...", "english": "convey..to...", "type": "短语", "keyWords": ["convey"] },
    { "chinese": "大使亲自向总理转达了总统的问候。", "english": "The ambassador personally conveyed the president's message to the premier.", "type": "句子", "keyWords": ["convey"] },
    { "chinese": "vt. 说服；使...相信/确信（a. 有说服力的；ad. 令人信服地）", "english": "convince/ convincing/ convincingly", "type": "单词", "keyWords": [] },
    { "chinese": "使某人相信...", "english": "convince sb.of/that...", "type": "短语", "keyWords": ["convince"] },
    { "chinese": "n. 厨师，炊事员（vt. 烹调；n. 烹调）", "english": "cook/ cooking", "type": "单词", "keyWords": [] },
    { "chinese": "n. 炊具（n. 烹调术）", "english": "cooker/ cookery", "type": "单词", "keyWords": [] },
    { "chinese": "a. 凉的；凉爽的，凉快的；冷静的，无所顾虑的；淡漠的；[口]绝妙的（vi./vt. （使）变凉；（使）冷静(down)）", "english": "cool", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 合作；协作；配合（a. 合作的，协力的；n. 合作；协作；配合；n. 合作者）", "english": "cooperate/ cooperative/ cooperation/ cooperator", "type": "单词", "keyWords": [] },
    { "chinese": "与·..合作", "english": "cooperate with sb.", "type": "短语", "keyWords": ["cooperate"] },
    { "chinese": "（在）与...合作（下）", "english": "in cooperation with sb.", "type": "短语", "keyWords": ["cooperation"] },
    { "chinese": "vi. （成功）应付；（善于）处理，对付；竞争，争斗", "english": "cope", "type": "单词", "keyWords": [] },
    { "chinese": "同..较量；同...对抗；应付；对付", "english": "cope with", "type": "短语", "keyWords": ["cope"] },
    { "chinese": "n. 铜", "english": "copper", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 抄写；拷贝；复印；模仿；抄袭（n. 复制品；副本；拷贝；模仿；（报、书）一份（册））", "english": "copy", "type": "单词", "keyWords": [] },
    { "chinese": "抄下", "english": "copy... down", "type": "短语", "keyWords": ["copy"] },
    { "chinese": "n. 玉米；谷物；[医]鸡眼", "english": "corn", "type": "单词", "keyWords": [] },
    { "chinese": "n. （屋）角；（街道）拐角；困境（vt. 把...逼入角落；将...逼入困境）", "english": "corner", "type": "单词", "keyWords": [] },
    { "chinese": "在拐角处", "english": "at/on the corner of", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "在...的角落里", "english": "in the corner of", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "在拐角处；就在眼前", "english": "round the corner", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "将窃贼逼入角落并擒住他们", "english": "corner the thieves and capture them", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "将...逼入困境", "english": "drive/ put/ force sb. into a corner", "type": "短语", "keyWords": ["corner"] },
    { "chinese": "n. [律]社团，法人；公司，企业；[美]有限公司", "english": "corporation", "type": "单词", "keyWords": [] },
    { "chinese": "v. 改正；纠正（a. 正确的；得体的；恰当的；端正的；n. 改正，修正；n. 正确性）", "english": "correct/ correction/ correctness", "type": "单词", "keyWords": [] },
    { "chinese": "n. 走廊；室外过道；回廊", "english": "corridor", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 相符；一致；通信（n. 信件，函件（尤指公函或商业信函）；n. 记者）", "english": "correspond/ correspondence/ correspondent", "type": "单词", "keyWords": [] },
    { "chinese": "a. 化妆用的；美发用的（n. 化妆品；美容术）", "english": "cosmetic", "type": "单词", "keyWords": [] },
    { "chinese": "v. 值（多少钱）；（使）花费（金钱），（使）付出（生命，健康等）代价（n. 费用；成本；代价）", "english": "cost", "type": "单词", "keyWords": [] },
    { "chinese": "这值（花了他们）十美元。", "english": "It cost(them) ten dollars.", "type": "句子", "keyWords": ["cost"] },
    { "chinese": "这错误使他失去了工作/生命。", "english": "The mistake cost him his job/ his life.", "type": "句子", "keyWords": ["cost"] },
    { "chinese": "以付出健康/生命为代价", "english": "at the cost of his health/ his life", "type": "短语", "keyWords": ["cost"] },
    { "chinese": "不惜一切代价", "english": "at all costs/ at any cost", "type": "短语", "keyWords": ["cost"] },
    { "chinese": "生活费", "english": "the cost of living", "type": "短语", "keyWords": ["cost"] },
    { "chinese": "a. 昂贵的，贵重的", "english": "costly", "type": "单词", "keyWords": [] },
    { "chinese": "n. 棉花", "english": "cotton", "type": "单词", "keyWords": [] },
    { "chinese": "n. （演出、化装舞会的）服装（一种流行的穿着样式，或指有某国家、时期或民众特点的衣着样式，通常在戏剧表演或化装舞会上穿）", "english": "costume", "type": "单词", "keyWords": [] },
    { "chinese": "n. 农舍；小房子；（农舍式的）别墅", "english": "cottage", "type": "单词", "keyWords": [] },
    { "chinese": "n. 长沙发", "english": "couch", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. 咳嗽", "english": "cough", "type": "单词", "keyWords": [] },
    { "chinese": "v. 能够（can的过去式）", "english": "could", "type": "单词", "keyWords": [] },
    { "chinese": "他目前可能躲在什么地方。", "english": "He could be anywhere.", "type": "句子", "keyWords": ["could"] },
    { "chinese": "你本可以更慎重些。", "english": "You could have been more considerate.", "type": "句子", "keyWords": ["could"] },
    { "chinese": "vt./vi. 数，清点；把...算在内；vi. 重要，有价值；指望，依赖(on/upon)", "english": "count", "type": "单词", "keyWords": [] },
    { "chinese": "把我算进去。", "english": "Count me in.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "事事都不可疏忽。/要事事都办妥帖。", "english": "See that everything counts.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "每秒钟都很重要。（分秒必争）", "english": "Every second counts.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "指望某人做某事", "english": "count on/upon sb. to do ..", "type": "短语", "keyWords": ["count"] },
    { "chinese": "指望（某人）做某事", "english": "count on/ upon (sb.) doing..", "type": "短语", "keyWords": ["count"] },
    { "chinese": "你可以依赖我的帮助。", "english": "You can count on my help.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "你们不能指望天晴。", "english": "You can't count upon the weather being fine.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "他们期待获得加薪。", "english": "They counted on getting a rise.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "他凡事都指望姐姐。", "english": "He counted upon/ on his sister for everything.", "type": "句子", "keyWords": ["count"] },
    { "chinese": "a. 可计算的；可数的", "english": "countable", "type": "单词", "keyWords": [] },
    { "chinese": "n. 柜台；柜台式长桌；计算器，计数器，计算者；adv./prep. 相反（地）", "english": "counter", "type": "单词", "keyWords": [] },
    { "chinese": "在...柜台", "english": "at the..counter", "type": "短语", "keyWords": ["counter"] },
    { "chinese": "逆时针方向", "english": "counter-clockwise", "type": "短语", "keyWords": ["counter"] },
    { "chinese": "n. 国家；乡下（a. 乡下的，乡村的；[方]祖国的；故乡的）", "english": "country", "type": "单词", "keyWords": [] },
    { "chinese": "在乡下", "english": "in the country/countryside", "type": "短语", "keyWords": ["country"] },
    { "chinese": "全国", "english": "throughout the country", "type": "短语", "keyWords": ["country"] },
    { "chinese": "农村生活", "english": "country life", "type": "短语", "keyWords": ["country"] },
    { "chinese": "n. 郡（英国最大的地方行政区）；（美国、中国等）县", "english": "county", "type": "单词", "keyWords": [] },
    { "chinese": "n. （一）对；夫妻；情侣；一双（不一定成对）；（非正式用语）数个；几个（v. 连接，结合；使成对；把...联系起来）", "english": "couple", "type": "单词", "keyWords": [] },
    { "chinese": "几个苹果", "english": "a couple of apples", "type": "短语", "keyWords": ["couple"] },
    { "chinese": "几天", "english": "a couple of days", "type": "短语", "keyWords": ["couple"] },
    { "chinese": "年轻夫妇", "english": "a young couple (is/ are..)", "type": "短语", "keyWords": ["couple"] },
    { "chinese": "伴有", "english": "be coupled with", "type": "短语", "keyWords": ["couple"] },
    { "chinese": "n. 勇气；勇敢（a. 勇敢的，英勇的）", "english": "courage/ courageous", "type": "单词", "keyWords": [] },
    { "chinese": "鼓起勇气", "english": "screw up one's courage", "type": "短语", "keyWords": ["courage"] },
    { "chinese": "不泄气，不丧胆，不气馁", "english": "keep up one's courage", "type": "短语", "keyWords": ["courage"] },
    { "chinese": "n. 过程；课程；一道菜；（运动物体）行进路线，河（航）道；所经之路", "english": "course", "type": "单词", "keyWords": [] },
    { "chinese": "人生的过程", "english": "the course of life", "type": "短语", "keyWords": ["course"] },
    { "chinese": "选...课程", "english": "take the course in/on...", "type": "短语", "keyWords": ["course"] },
    { "chinese": "在...过程中", "english": "in/ during the course of", "type": "短语", "keyWords": ["course"] },
    { "chinese": "五道菜的一餐饭", "english": "a dinner of five courses", "type": "短语", "keyWords": ["course"] },
    { "chinese": "标有主要河流航道的地图", "english": "a map that shows the courses of the chief rivers", "type": "短语", "keyWords": ["course"] },
    { "chinese": "他们向北行进。", "english": "They took a northern course.", "type": "句子", "keyWords": ["course"] },
    { "chinese": "n. 球场；庭院；短街；陈列区，馆；法院；（the）宫廷", "english": "court", "type": "单词", "keyWords": [] },
    { "chinese": "美食街", "english": "food court", "type": "短语", "keyWords": ["court"] },
    { "chinese": "朝见君主；上法院；打官司", "english": "go to court", "type": "短语", "keyWords": ["court"] },
    { "chinese": "n. 堂（或表）兄弟；堂（或表）姐妹", "english": "cousin", "type": "单词", "keyWords": [] },
    { "chinese": "n. 盖子；封面；藏身处（vt. 覆盖；掩饰；掩护；包括；行过（路程）；报道；走完；看完）", "english": "cover", "type": "单词", "keyWords": [] },
    { "chinese": "躲藏；躲避；避难", "english": "take cover/shelter", "type": "短语", "keyWords": ["cover"] },
    { "chinese": "我想在天黑之前走完100英里。", "english": "I want to cover 100 miles by dark.", "type": "句子", "keyWords": ["cover"] },
    { "chinese": "我想每天读完20页。", "english": "I want to cover 20 pages a day.", "type": "句子", "keyWords": ["cover"] },
    { "chinese": "他的研究涉及广大范围。", "english": "His studies covered a wide field.", "type": "句子", "keyWords": ["cover"] },
    { "chinese": "我的收入刚刚够用。（抵消花费）", "english": "My income barely covers my expenses.", "type": "句子", "keyWords": ["cover"] },
    { "chinese": "被派去负责报道这场战争/这则新闻", "english": "be sent to cover the war/news", "type": "短语", "keyWords": ["cover"] },
    { "chinese": "用...覆盖...", "english": "cover..with...", "type": "短语", "keyWords": ["cover"] },
    { "chinese": "n. 母牛，奶牛（n. 牛仔）", "english": "cow/ cowboy", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]裂缝，裂口；爆裂声；噼啪声 v.（使）破/爆裂；（使）发出爆裂声", "english": "crack", "type": "单词", "keyWords": [] },
    { "chinese": "n. 摇篮；（文化等的）发源地(of)", "english": "cradle", "type": "单词", "keyWords": [] },
    { "chinese": "n. 工艺；手艺；需要手艺的行业；小船；轮船；飞机（n. 手艺人）", "english": "craft/ craftsman", "type": "单词", "keyWords": [] },
    { "chinese": "工艺学校", "english": "a school for arts and crafts", "type": "短语", "keyWords": ["craft"] },
    { "chinese": "工艺美术", "english": "art and craft", "type": "短语", "keyWords": ["craft"] },
    { "chinese": "n. 碰撞；坠落，坠毁；撞击声（v. 碰撞；坠落，坠毁；（指公司、政府等）破产，垮台）", "english": "crash", "type": "单词", "keyWords": [] },
    { "chinese": "汽车撞车的事故", "english": "a car crash", "type": "短语", "keyWords": ["crash"] },
    { "chinese": "飞机坠毁事故", "english": "an air crash/ a plane crash", "type": "短语", "keyWords": ["crash"] },
    { "chinese": "他们的车撞上护栏。", "english": "Their car crashed into a guardrail.", "type": "句子", "keyWords": ["crash"] },
    { "chinese": "vi./n. 爬，爬行；蠕动，徐徐行进；匍匐前进", "english": "crawl", "type": "单词", "keyWords": [] },
    { "chinese": "a. 发疯的；疯狂的；狂热的；不切实际的；荒唐的；急切的", "english": "crazy", "type": "单词", "keyWords": [] },
    { "chinese": "发疯地；拼命地；猛烈地", "english": "like crazy", "type": "短语", "keyWords": ["crazy"] },
    { "chinese": "热衷于；醉心于；迷恋", "english": "be crazy about", "type": "短语", "keyWords": ["crazy"] },
    { "chinese": "n. 奶油（食品）；奶油色", "english": "cream", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 创造；产生（n. 创造）", "english": "create/ creation", "type": "单词", "keyWords": [] },
    { "chinese": "提供就业机会", "english": "create jobs", "type": "短语", "keyWords": ["create"] },
    { "chinese": "发言引起一阵骚动。", "english": "That remark created a stir.", "type": "句子", "keyWords": ["create"] },
    { "chinese": "a. 有创造力的；创造（性）的（n. 创造性）", "english": "creative/ creativity", "type": "单词", "keyWords": [] },
    { "chinese": "n. 生物（动物或人）", "english": "creature", "type": "单词", "keyWords": [] },
    { "chinese": "n. 信用；信贷；赊欠；声望，荣誉；赞扬，称许；[财务]贷方，银行存款（a. 难以置信的）", "english": "credit/ incredible", "type": "单词", "keyWords": [] },
    { "chinese": "赊购/赊售东西", "english": "buy/ sell sth. on credit", "type": "短语", "keyWords": ["credit"] },
    { "chinese": "信用卡", "english": "credit card", "type": "短语", "keyWords": ["credit"] },
    { "chinese": "极有名望的人", "english": "a man of high credit", "type": "短语", "keyWords": ["credit"] },
    { "chinese": "信任某人；称赞某人", "english": "give credit to sb.", "type": "短语", "keyWords": ["credit"] },
    { "chinese": "为什么他受到了所有人的赞扬？", "english": "Why should he get all the credit?", "type": "句子", "keyWords": ["credit"] },
    { "chinese": "他的成功使全家增光。", "english": "His success brings credit to his family.", "type": "句子", "keyWords": ["credit"] },
    { "chinese": "n. 支流，溪流；小河", "english": "creek", "type": "单词", "keyWords": [] },
    { "chinese": "n. （车、船、飞机上）（全体）工作人员", "english": "crew", "type": "单词", "keyWords": [] },
    { "chinese": "船上的工作人员有偿工作。", "english": "The crew are paid to do all the work on the ship.", "type": "句子", "keyWords": ["crew"] },
    { "chinese": "海盗船船员有78人。", "english": "The pirate crew was made up of 78 people.", "type": "句子", "keyWords": ["crew"] },
    { "chinese": "n. 犯罪行为；罪恶；罪行", "english": "crime", "type": "单词", "keyWords": [] },
    { "chinese": "犯罪", "english": "commit a crime", "type": "短语", "keyWords": ["crime"] },
    { "chinese": "n. 罪犯（a. 刑事的；犯罪的）", "english": "criminal", "type": "单词", "keyWords": [] },
    { "chinese": "刑法", "english": "criminal law", "type": "短语", "keyWords": ["criminal"] },
    { "chinese": "n. 决定性时刻；危机；转折点", "english": "crisis", "type": "单词", "keyWords": [] },
    { "chinese": "经济危机", "english": "an economic crisis", "type": "短语", "keyWords": ["crisis"] },
    { "chinese": "信任危机", "english": "a crisis of confidence", "type": "短语", "keyWords": ["crisis"] },
    { "chinese": "处于危机中", "english": "in crisis", "type": "短语", "keyWords": ["crisis"] },
    { "chinese": "n. （批评、判断的）标准，准据，规范", "english": "criterion", "type": "单词", "keyWords": [] },
    { "chinese": "n. 批评家；评论家（n. 批评；批判；v. 批评；批判；指责，非难）", "english": "critic/ criticism/ criticize", "type": "单词", "keyWords": [] },
    { "chinese": "因为某事批评某人", "english": "criticize sb. for (doing) sth.", "type": "短语", "keyWords": ["criticize"] },
    { "chinese": "a. 批判/评（性）的；挑剔的；严重的，危险的", "english": "critical", "type": "单词", "keyWords": [] },
    { "chinese": "处于危险期的疾病", "english": "an illness at the critical stage", "type": "短语", "keyWords": ["critical"] },
    { "chinese": "紧要关头，关键时刻", "english": "critical moment", "type": "短语", "keyWords": ["critical"] },
    { "chinese": "n. 作物；庄稼", "english": "crop", "type": "单词", "keyWords": [] },
    { "chinese": "n. 十字形，交叉，十字架，十字形物（v. 使交叉；横过，越过；勾画；a. 生气的，脾气不好的，易怒的；交叉的）", "english": "cross", "type": "单词", "keyWords": [] },
    { "chinese": "红十字会", "english": "the Red Cross", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "相声", "english": "cross talk", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "划去，注销", "english": "cross...out", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "把...从（名单等上）划掉", "english": "cross...off (..)", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "（对...）生气，发脾气", "english": "be cross with (=be angry with)", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "越野赛跑", "english": "a cross-country race", "type": "短语", "keyWords": ["cross"] },
    { "chinese": "n. 十字路口", "english": "crossroads", "type": "单词", "keyWords": [] },
    { "chinese": "在十字路口；面临抉择的关头；处于（人生的）重要转折点", "english": "at the crossroads", "type": "短语", "keyWords": ["crossroads"] },
    { "chinese": "n. 乌鸦", "english": "crow", "type": "单词", "keyWords": [] },
    { "chinese": "n. 群；人群（v. （使）挤满；挤；群集；a. 拥挤的；满座的）", "english": "crowd/ crowded", "type": "单词", "keyWords": [] },
    { "chinese": "把衣服塞进衣柜中（有不顾整齐之意）", "english": "crowd the clothes into the closet", "type": "短语", "keyWords": ["crowd"] },
    { "chinese": "挤进了我的房间", "english": "crowd into my room", "type": "短语", "keyWords": ["crowd"] },
    { "chinese": "挤满了；拥塞", "english": "be crowded with sb./sth.", "type": "短语", "keyWords": ["crowded"] },
    { "chinese": "n. 王冠；国王；王位（v. 加冕；授...（以荣誉等）(with)）", "english": "crown", "type": "单词", "keyWords": [] },
    { "chinese": "a. 残忍的；残酷的（n. 残忍；残酷行为）", "english": "cruel/ cruelty", "type": "单词", "keyWords": [] },
    { "chinese": "对...残忍", "english": "be cruel to sb.", "type": "短语", "keyWords": ["cruel"] },
    { "chinese": "v. 压碎；压倒；压垮", "english": "crush", "type": "单词", "keyWords": [] },
    { "chinese": "粉碎/碾碎", "english": "crush...(in) to pieces", "type": "短语", "keyWords": ["crush"] },
    { "chinese": "v. 叫喊；哭（n. 哭泣；哭声；叫喊，喊声）", "english": "cry", "type": "单词", "keyWords": [] },
    { "chinese": "哭得伤心极了", "english": "cry one's eyes (heart) out", "type": "短语", "keyWords": ["cry"] },
    { "chinese": "大叫，对...大声反对(against)", "english": "cry out", "type": "短语", "keyWords": ["cry"] },
    { "chinese": "牛奶打泼，哭也无用。", "english": "It is no use crying over spilt milk.", "type": "句子", "keyWords": ["cry"] },
    { "chinese": "n. 水晶；结晶体（a. 清澈透明的；晶体的；a. 完全透明的；[喻]极其明白，十分清楚）", "english": "crystal/ crystal clear", "type": "单词", "keyWords": [] },
    { "chinese": "n. 黄瓜", "english": "cucumber", "type": "单词", "keyWords": [] },
    { "chinese": "泰然自若，极为冷静", "english": "(as) cool as a cucumber", "type": "短语", "keyWords": ["cucumber"] },
    { "chinese": "海参", "english": "sea cucumber", "type": "短语", "keyWords": ["cucumber"] },
    { "chinese": "v. 耕作，培植；培养（n. 耕作，培植；培养；a. 有修养/教养的，文雅的）", "english": "cultivate/ cultivation/ cultivated", "type": "单词", "keyWords": [] },
    { "chinese": "培育新一代", "english": "cultivate a new generation", "type": "短语", "keyWords": ["cultivate"] },
    { "chinese": "培养对艺术的热爱", "english": "cultivate a love of art", "type": "短语", "keyWords": ["cultivate"] },
    { "chinese": "养成分析的习惯", "english": "cultivate the habit of analysis", "type": "短语", "keyWords": ["cultivate"] },
    { "chinese": "a. 文化（上）的（n. 文化；文明；教养；修养；a. 有教养的）", "english": "cultural/ culture/ cultured", "type": "单词", "keyWords": [] },
    { "chinese": "文化冲击", "english": "culture shock", "type": "短语", "keyWords": ["culture"] },
    { "chinese": "有教养的人，文化人", "english": "a cultured man/ a man of culture", "type": "短语", "keyWords": ["cultured", "culture"] },
    { "chinese": "a. 决定性的，关键性的，至关重要的；严酷的；[口]极好的", "english": "crucial", "type": "单词", "keyWords": [] },
    { "chinese": "n. 橱，食橱；柜子；碗柜", "english": "cupboard", "type": "单词", "keyWords": [] },
    { "chinese": "n. 治愈，痊愈；治疗；疗法；有治愈疗效的药(for)（v. 治愈，治疗）", "english": "cure", "type": "单词", "keyWords": [] },
    { "chinese": "治疗某人疾病", "english": "cure sb. of a disease", "type": "短语", "keyWords": ["cure"] },
    { "chinese": "矫正某人不良习惯", "english": "cure a person of a bad habit", "type": "短语", "keyWords": ["cure"] },
    { "chinese": "止咳良药", "english": "the best cure for a cough", "type": "短语", "keyWords": ["cure"] },
    { "chinese": "n. 卷曲，卷缩；（烟等）缭绕，袅袅上升（v. 使卷曲，使成螺旋状；弄卷（毛发））", "english": "curl", "type": "单词", "keyWords": [] },
    { "chinese": "a. 好奇的；稀奇的（n. 好奇心）", "english": "curious/ curiosity", "type": "单词", "keyWords": [] },
    { "chinese": "很想做某事", "english": "be curious to do sth.", "type": "短语", "keyWords": ["curious"] },
    { "chinese": "对...感到好奇", "english": "be curious about", "type": "短语", "keyWords": ["curious"] },
    { "chinese": "出于好奇", "english": "out of curiosity", "type": "短语", "keyWords": ["curiosity"] },
    { "chinese": "好奇地", "english": "with curiosity", "type": "短语", "keyWords": ["curiosity"] },
    { "chinese": "a. 通用的，流行的；现时的；最近的（n. （水、气、电）流；潮流；思潮；ad. 现在；当前）", "english": "current/ currently", "type": "单词", "keyWords": [] },
    { "chinese": "现代英语；日常英语", "english": "current English", "type": "短语", "keyWords": ["current"] },
    { "chinese": "时事", "english": "current events", "type": "短语", "keyWords": ["current"] },
    { "chinese": "活期存款账户", "english": "current account", "type": "短语", "keyWords": ["current"] },
    { "chinese": "直/交流电", "english": "direct/ alternating current", "type": "短语", "keyWords": ["current"] },
    { "chinese": "n. 流通；（一国中实际通用的）货币", "english": "currency", "type": "单词", "keyWords": [] },
    { "chinese": "外汇，外币", "english": "foreign currencies", "type": "短语", "keyWords": ["currency"] },
    { "chinese": "n. 课程", "english": "curriculum", "type": "单词", "keyWords": [] },
    { "chinese": "n. 窗帘；（舞台的）幕", "english": "curtain", "type": "单词", "keyWords": [] },
    { "chinese": "开/闭幕", "english": "rise/ drop the curtain", "type": "短语", "keyWords": ["curtain"] },
    { "chinese": "上窗帘（开/闭幕）拉幕", "english": "draw the curtain", "type": "短语", "keyWords": ["curtain"] },
    { "chinese": "n. 曲线；弧线；弯曲；曲线状物；弯曲部分（v. 弯，使弯曲；vi. 成曲弯形）", "english": "curve", "type": "单词", "keyWords": [] },
    { "chinese": "n. 垫子；气垫；软垫；衬垫", "english": "cushion", "type": "单词", "keyWords": [] },
    { "chinese": "n. 习惯；风俗；惯例；（pl.）海关（a. 习惯性的；照惯例的）", "english": "custom/ customary", "type": "单词", "keyWords": [] },
    { "chinese": "海关", "english": "the Customs", "type": "短语", "keyWords": ["custom"] },
    { "chinese": "关税", "english": "customs duties", "type": "短语", "keyWords": ["custom"] },
    { "chinese": "n. 顾客；主顾", "english": "customer", "type": "单词", "keyWords": [] },
    { "chinese": "v. 切，割，削（n. 切，割；裂口；削减，删节）", "english": "cut", "type": "单词", "keyWords": [] },
    { "chinese": "削减预算/我们的开支", "english": "cut a budget/ our expenses", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "减半价", "english": "cut the price by half", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "切碎；使难过", "english": "cut..up", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "穿过田野", "english": "cut across a field", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "抄近路走过；刺穿", "english": "cut through", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "砍掉老树枝", "english": "cut away the old branches", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "砍倒（树木）；裁减（经费）(on)；减少(on)", "english": "cut down (on)", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "你抽烟太多，应该减少。", "english": "You smoke too much - you should try to cut down.", "type": "句子", "keyWords": ["cut"] },
    { "chinese": "插话；插入（进入一排人或事物）", "english": "cut in", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "删去；截断；中断（电话、讲话、供应等）；隔离（从其他物体中分离出来）", "english": "cut out", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "抄近路", "english": "take a short cut", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "减薪", "english": "a cut in salary", "type": "短语", "keyWords": ["cut"] },
    { "chinese": "恶语伤人胜过利剑", "english": "Words cut more than swords.", "type": "句子", "keyWords": ["cut"] },
    { "chinese": "a. 漂亮的；娇小可爱的；精巧的", "english": "cute", "type": "单词", "keyWords": [] },
    { "chinese": "n. （报纸等的）剪辑；切下的东西（a. 像刀割似的；刺骨的；尖酸刻薄的）", "english": "cutting", "type": "单词", "keyWords": [] },
    { "chinese": "刺骨的寒风", "english": "a cutting wind", "type": "短语", "keyWords": ["cutting"] },
    { "chinese": "尖刻的话", "english": "a cutting remark", "type": "短语", "keyWords": ["cutting"] },
    { "chinese": "n. 周期；循环；自行车（v. 循环；使轮转；vi. 循环；轮转；骑自行车）", "english": "cycle", "type": "单词", "keyWords": [] },
    { "chinese": "四季的周而复始", "english": "the cycle of the seasons", "type": "短语", "keyWords": ["cycle"] },
    { "chinese": "生命周期", "english": "a life cycle", "type": "短语", "keyWords": ["cycle"] },
    { "chinese": "n. 骑自行车的人", "english": "cyclist", "type": "单词", "keyWords": [] },
    { "chinese": "n. 骑脚踏车兜风，骑脚踏车消遣", "english": "cycling", "type": "单词", "keyWords": [] },
    { "chinese": "[口]爸爸（n.）", "english": "dad/ daddy", "type": "单词", "keyWords": [] },
    { "chinese": "每日的；日常的（a.）；每天（ad.）；日报（n.）", "english": "daily", "type": "单词", "keyWords": [] },
    { "chinese": "在日常生活中", "english": "in our daily life", "type": "短语", "keyWords": ["daily"] },
    { "chinese": "《人民日报》", "english": "People's Daily", "type": "短语", "keyWords": ["daily"] },
    { "chinese": "牛奶坊/公司；乳品店（n.）；牛奶（制品）的；乳品的（a.）", "english": "dairy", "type": "单词", "keyWords": [] },
    { "chinese": "水闸；坝（n.）；筑坝（vt.）", "english": "dam", "type": "单词", "keyWords": [] },
    { "chinese": "损坏；损害；[口]伤害，毁坏（v.）；毁坏；赔偿费（n.）", "english": "damage", "type": "单词", "keyWords": [] },
    { "chinese": "毁坏某人的名声", "english": "damage one's name", "type": "短语", "keyWords": ["damage"] },
    { "chinese": "给...造成很大损害", "english": "do/ cause great damage to...", "type": "短语", "keyWords": ["damage"] },
    { "chinese": "潮湿（n.）；潮湿的（a.）；使潮湿；给...泼冷水（vt.）", "english": "damp", "type": "单词", "keyWords": [] },
    { "chinese": "跳舞，舞蹈；跳动；（旗等）飘扬（n.）；跳舞（v.）；跳动的（a.）；跳舞（n.）", "english": "dance/ dancing", "type": "单词", "keyWords": [] },
    { "chinese": "树叶迎风飘舞。", "english": "The leaves were dancing in the wind.", "type": "句子", "keyWords": ["dance"] },
    { "chinese": "危险；危险物（n.）；危险的；不安全的（a.）；危险地（ad.）", "english": "danger/ dangerous/ dangerously", "type": "单词", "keyWords": [] },
    { "chinese": "在...危险之中", "english": "in danger", "type": "短语", "keyWords": ["danger"] },
    { "chinese": "脱离危险", "english": "out of danger", "type": "短语", "keyWords": ["danger"] },
    { "chinese": "敢；胆敢；竟敢（v.）；大胆的（a.）", "english": "dare/ daring", "type": "单词", "keyWords": [] },
    { "chinese": "她不敢做那件事。", "english": "She dared not do it.", "type": "句子", "keyWords": ["dare"] },
    { "chinese": "他竟敢攻击多少世纪以来人们所持有的信仰和观念！", "english": "How dared he attack the beliefs and ideas which had been held for centuries!", "type": "句子", "keyWords": ["dare"] },
    { "chinese": "我想，大概，可能，或许...", "english": "I dare say..", "type": "短语", "keyWords": ["dare"] },
    { "chinese": "一位大胆的工人/一件大胆的事", "english": "a daring workman/ thing", "type": "短语", "keyWords": ["daring"] },
    { "chinese": "黑暗的；暗的（a.）；夜，黄昏；黑暗，暗处（n.）；（使）变暗，（使）变黑（v.）", "english": "dark/ darken", "type": "单词", "keyWords": [] },
    { "chinese": "坐在黑暗里", "english": "sit in the dark", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "黄昏时", "english": "at dark", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "黄昏前（后）", "english": "before/ after dark", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "一匹黑马；爆出冷门", "english": "a dark horse", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "对...全然不知", "english": "be in the dark about/ as to..", "type": "短语", "keyWords": ["dark"] },
    { "chinese": "我对他们的计划一无所知。", "english": "They kept me in the dark about their plans.", "type": "句子", "keyWords": ["dark"] },
    { "chinese": "黑暗；漆黑；阴暗（n.）", "english": "darkness", "type": "单词", "keyWords": [] },
    { "chinese": "处于黑暗中", "english": "in darkness", "type": "短语", "keyWords": ["darkness"] },
    { "chinese": "心爱的人；宠物；[口]亲爱的（n.）；心爱的；宠爱的；亲爱的（a.）", "english": "darling", "type": "单词", "keyWords": [] },
    { "chinese": "短跑；冲撞；猛冲；[体]短跑；破折号；草的一笔（或一画）（n.）；冲；冲撞（v.）", "english": "dash", "type": "单词", "keyWords": [] },
    { "chinese": "猛冲到出口", "english": "make a dash for the exit", "type": "短语", "keyWords": ["dash"] },
    { "chinese": "论据；数据，资料（n.）；数据库（n.）", "english": "data/ database", "type": "单词", "keyWords": [] },
    { "chinese": "日期；（男女间）约会（n.）；约会；定日期；注...的日期；追溯（v./vi.）", "english": "date", "type": "单词", "keyWords": [] },
    { "chinese": "和某人有个约会", "english": "have a date with", "type": "短语", "keyWords": ["date"] },
    { "chinese": "和某人约会", "english": "date sb./ make a date with sb.", "type": "短语", "keyWords": ["date"] },
    { "chinese": "直到最近的，新式的，现代的", "english": "up to date", "type": "短语", "keyWords": ["date"] },
    { "chinese": "不合时宜的；过时的", "english": "out of date", "type": "短语", "keyWords": ["date"] },
    { "chinese": "追溯到", "english": "date back to/ date from/ go back to", "type": "短语", "keyWords": ["date"] },
    { "chinese": "女儿（n.）；儿媳妇（n.）", "english": "daughter/ daughter-in-law", "type": "单词", "keyWords": [] },
    { "chinese": "黎明，天亮，拂晓（n.）；破晓；被理解，被领悟（on sb.）（v.）", "english": "dawn", "type": "单词", "keyWords": [] },
    { "chinese": "拂晓时", "english": "at dawn", "type": "短语", "keyWords": ["dawn"] },
    { "chinese": "胜利的曙光", "english": "the dawn of victory", "type": "短语", "keyWords": ["dawn"] },
    { "chinese": "文明的开端", "english": "the dawn of civilization", "type": "短语", "keyWords": ["dawn"] },
    { "chinese": "后来我们才恍然大悟，原来从来没有补给物资顺这条路运送下来过。", "english": "Only gradually did it dawn on us that no supplies ever came down the road.", "type": "句子", "keyWords": ["dawn"] },
    { "chinese": "一天，日子；白天；节日，重要日子（n.）", "english": "day", "type": "单词", "keyWords": [] },
    { "chinese": "将来", "english": "in the days to come", "type": "短语", "keyWords": ["day"] },
    { "chinese": "至今", "english": "to this day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "当代的", "english": "of the day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "日夜不停地", "english": "day and night", "type": "短语", "keyWords": ["day"] },
    { "chinese": "（日后）总有一天", "english": "some day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "当时，那时候", "english": "in those days", "type": "短语", "keyWords": ["day"] },
    { "chinese": "不再干了；停业（某活动）", "english": "call it a day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "逐日", "english": "day by day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "按日计", "english": "by the day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "整天", "english": "all day long", "type": "短语", "keyWords": ["day"] },
    { "chinese": "每隔一天", "english": "every other day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "每隔几天", "english": "every few days", "type": "短语", "keyWords": ["day"] },
    { "chinese": "每隔一天，每两天", "english": "every two days", "type": "短语", "keyWords": ["day"] },
    { "chinese": "休假一天", "english": "have a day off", "type": "短语", "keyWords": ["day"] },
    { "chinese": "美好的往日，当年", "english": "good old days", "type": "短语", "keyWords": ["day"] },
    { "chinese": "前些天", "english": "the other day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "日复一日", "english": "day after day", "type": "短语", "keyWords": ["day"] },
    { "chinese": "凡人皆有得意之日。/三十年河东，三十年河西。", "english": "Every dog has its day.", "type": "句子", "keyWords": ["day"] },
    { "chinese": "白天；日光（n.）", "english": "daylight", "type": "单词", "keyWords": [] },
    { "chinese": "夏令时间", "english": "daylight-saving time", "type": "短语", "keyWords": ["daylight"] },
    { "chinese": "黎明的时候", "english": "at daylight", "type": "短语", "keyWords": ["daylight"] },
    { "chinese": "白天，白昼（n.）；白天的（a.）", "english": "daytime", "type": "单词", "keyWords": [] },
    { "chinese": "在白天", "english": "in the daytime", "type": "短语", "keyWords": ["daytime"] },
    { "chinese": "表示“去除；相反；贬；离开”", "english": "de-", "type": "前缀", "keyWords": [] },
    { "chinese": "除霜", "english": "defrost", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "非国有化", "english": "denationalize", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "贬值", "english": "devalue", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "使变形", "english": "deform", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "降级", "english": "degrade", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "解码", "english": "decode", "type": "单词", "keyWords": ["de-"] },
    { "chinese": "死（亡）的；死一般的（a.）；极其（ad.）", "english": "dead", "type": "单词", "keyWords": [] },
    { "chinese": "他（喝得）烂醉。", "english": "He's dead drunk.", "type": "句子", "keyWords": ["dead"] },
    { "chinese": "致命的；死气沉沉的（a.）", "english": "deadly", "type": "单词", "keyWords": [] },
    { "chinese": "致命的武器", "english": "deadly weapons", "type": "短语", "keyWords": ["deadly"] },
    { "chinese": "最后期限；截止时间（n.）", "english": "deadline", "type": "单词", "keyWords": [] },
    { "chinese": "错过..的最后期限", "english": "miss the deadline for sth.", "type": "短语", "keyWords": ["deadline"] },
    { "chinese": "聋的（a.）；使聋（vt.）；变聋（vi.）；震耳欲聋的（a.）", "english": "deaf/ deafen/ deafening", "type": "单词", "keyWords": [] },
    { "chinese": "不听劝告", "english": "be deaf to advice", "type": "短语", "keyWords": ["deaf"] },
    { "chinese": "不肯倾听别人意见的人是最聋的人。", "english": "None (are) so deaf as those who won't hear.", "type": "句子", "keyWords": ["deaf"] },
    { "chinese": "置若罔闻", "english": "turn a deaf ear to...", "type": "短语", "keyWords": ["deaf"] },
    { "chinese": "n. 交易；数量；协议", "english": "deal", "type": "单词", "keyWords": [] },
    { "chinese": "v. 发牌", "english": "deal the cards", "type": "短语", "keyWords": ["deal"] },
    { "chinese": "处理；涉及；论及；对付", "english": "deal with", "type": "短语", "keyWords": ["deal"] },
    { "chinese": "就这么办，一言为定", "english": "That's/It's a deal", "type": "句子", "keyWords": ["deal"] },
    { "chinese": "大量（+不可数名词）", "english": "a good/great deal (of)", "type": "短语", "keyWords": ["deal"] },
    { "chinese": "a. 亲爱的；昂贵的；interj. 天啊！天哪！", "english": "dear", "type": "单词", "keyWords": [] },
    { "chinese": "n. 死；死亡；伤亡人数", "english": "death", "type": "单词", "keyWords": [] },
    { "chinese": "决一死战；一决雌雄", "english": "fight to the death", "type": "短语", "keyWords": ["death"] },
    { "chinese": "射死/饿死某人", "english": "shoot/starve sb. to death", "type": "短语", "keyWords": ["death"] },
    { "chinese": "导致100人死亡", "english": "cause 100 deaths", "type": "短语", "keyWords": ["death"] },
    { "chinese": "v. /n. 辩论；争论", "english": "debate", "type": "单词", "keyWords": [] },
    { "chinese": "辩论；争论", "english": "debate on/upon sth.", "type": "短语", "keyWords": ["debate"] },
    { "chinese": "n. 欠债，债务；人情债；负债状态", "english": "debt", "type": "单词", "keyWords": [] },
    { "chinese": "偿付债款", "english": "pay one's debts", "type": "短语", "keyWords": ["debt"] },
    { "chinese": "还清债务", "english": "pay off one's debts", "type": "短语", "keyWords": ["debt"] },
    { "chinese": "欠债（短暂性动作）", "english": "run/get into debt", "type": "短语", "keyWords": ["debt"] },
    { "chinese": "欠债（可接时间段状语）", "english": "be in debt", "type": "短语", "keyWords": ["debt"] },
    { "chinese": "n. 十年", "english": "decade", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使腐烂/朽，使蛀蚀；vi. 腐烂，蛀蚀；衰减/败/退；n. 腐烂，蛀蚀", "english": "decay", "type": "单词", "keyWords": [] },
    { "chinese": "v. 欺骗，蒙骗", "english": "deceive", "type": "单词", "keyWords": [] },
    { "chinese": "n. 欺骗，蒙骗", "english": "deception", "type": "单词", "keyWords": [] },
    { "chinese": "a. 欺骗性的", "english": "deceptive", "type": "单词", "keyWords": [] },
    { "chinese": "骗某人买某物", "english": "deceive sb. into buying...", "type": "短语", "keyWords": ["deceive"] },
    { "chinese": "a. 得体的；适当的；正派的；过得去的，尚可的", "english": "decent", "type": "单词", "keyWords": [] },
    { "chinese": "v. 决定；判决，裁定，判定", "english": "decide", "type": "单词", "keyWords": [] },
    { "chinese": "a. 明确的；肯定的；果断的", "english": "decided", "type": "单词", "keyWords": [] },
    { "chinese": "明显的变化", "english": "a decided change", "type": "短语", "keyWords": ["decided"] },
    { "chinese": "对某事作出决定", "english": "decide on (sth.)", "type": "短语", "keyWords": ["decide"] },
    { "chinese": "n. 决定；判决；决心；决断；a. 有决定性的", "english": "decision/decisive", "type": "单词", "keyWords": [] },
    { "chinese": "作出决定", "english": "come to/arrive at/reach a decision", "type": "短语", "keyWords": ["decision"] },
    { "chinese": "由...来决定（某事）", "english": "leave... to the decision of", "type": "短语", "keyWords": ["decision"] },
    { "chinese": "决定下来，作出决定；下决心", "english": "make a decision", "type": "短语", "keyWords": ["decision"] },
    { "chinese": "有决断力的人", "english": "a man of decision", "type": "短语", "keyWords": ["decision"] },
    { "chinese": "决定性的一票", "english": "the decisive vote", "type": "短语", "keyWords": ["decisive"] },
    { "chinese": "决战", "english": "a decisive battle", "type": "短语", "keyWords": ["decisive"] },
    { "chinese": "n. 甲板，舱面", "english": "deck", "type": "单词", "keyWords": [] },
    { "chinese": "在上/下甲板上", "english": "on the upper/lower deck", "type": "短语", "keyWords": ["deck"] },
    { "chinese": "v. 断言；宣称；宣布；宣告；声明；（向海关）申报", "english": "declare", "type": "单词", "keyWords": [] },
    { "chinese": "n. 宣告，宣布", "english": "declaration", "type": "单词", "keyWords": [] },
    { "chinese": "宣布某人无罪", "english": "declare sb. (to be) innocent", "type": "短语", "keyWords": ["declare"] },
    { "chinese": "你有东西要申报吗？（指应纳税的东西）", "english": "Have you anything to declare?", "type": "句子", "keyWords": ["declare"] },
    { "chinese": "宣布和平", "english": "declare peace", "type": "短语", "keyWords": ["declare"] },
    { "chinese": "宣布他当选", "english": "declare him elected", "type": "短语", "keyWords": ["declare"] },
    { "chinese": "（美）独立宣言（1776年7月4日）", "english": "the Declaration of Independence", "type": "短语", "keyWords": ["declaration"] },
    { "chinese": "向...宣战", "english": "declare war on...", "type": "短语", "keyWords": ["declare"] },
    { "chinese": "联合声明", "english": "Joint declaration", "type": "短语", "keyWords": ["declaration"] },
    { "chinese": "n. 下降；减少；衰落；v. /vi. 婉言拒绝；下降；衰落", "english": "decline", "type": "单词", "keyWords": [] },
    { "chinese": "在下跌/上升", "english": "on the decline (decrease)/increase", "type": "短语", "keyWords": ["decline"] },
    { "chinese": "物价下跌", "english": "a decline in price", "type": "短语", "keyWords": ["decline"] },
    { "chinese": "拒绝回答", "english": "decline to answer", "type": "短语", "keyWords": ["decline"] },
    { "chinese": "拒绝一个提议", "english": "decline an offer", "type": "短语", "keyWords": ["decline"] },
    { "chinese": "v. 装饰；装潢；n. 装饰；装潢；装饰品；a. 装饰的；装潢的", "english": "decorate/decoration/decorative", "type": "单词", "keyWords": [] },
    { "chinese": "装饰美术", "english": "decorative art", "type": "短语", "keyWords": ["decorative"] },
    { "chinese": "v. /vi. /n. 减少；减小", "english": "decrease", "type": "单词", "keyWords": [] },
    { "chinese": "数目减少", "english": "decrease in number/a decrease in number", "type": "短语", "keyWords": ["decrease"] },
    { "chinese": "n. 事情；行为", "english": "deed", "type": "单词", "keyWords": [] },
    { "chinese": "做好事", "english": "do a good deed", "type": "短语", "keyWords": ["deed"] },
    { "chinese": "在行动上", "english": "in deed", "type": "短语", "keyWords": ["deed"] },
    { "chinese": "a. 深的；埋头于...中，热衷于（in）；ad. 深深地；n. 深处", "english": "deep", "type": "单词", "keyWords": [] },
    { "chinese": "低沉的声音", "english": "a deep voice", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "挖得深", "english": "dig deep", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "深夜", "english": "deep/far into the night", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "在沉思中", "english": "in deep thought", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "埋头苦读", "english": "be deep in a book", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "熟睡", "english": "be in a deep sleep = be deep in sleep", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "工作直至深夜", "english": "work deep into the night", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "在齐膝深的水里", "english": "in knee-deep water", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "淹死在海里", "english": "drown in the deep", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "走入丛林深处", "english": "go deep into the jungle", "type": "短语", "keyWords": ["deep"] },
    { "chinese": "ad. 深深地；强烈地；深刻地", "english": "deeply", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使...深；加深，深化", "english": "deepen", "type": "单词", "keyWords": [] },
    { "chinese": "n. 纵深；深（度）；深处，深渊", "english": "depth", "type": "单词", "keyWords": [] },
    { "chinese": "潜入水下30英尺处", "english": "dive to a depth of 30 feet", "type": "短语", "keyWords": ["depth"] },
    { "chinese": "密林深处", "english": "in the depths of the forest", "type": "短语", "keyWords": ["depth"] },
    { "chinese": "n. 鹿（单复同）", "english": "deer", "type": "单词", "keyWords": [] },
    { "chinese": "v. 击败；n. 击败；失败", "english": "defeat", "type": "单词", "keyWords": [] },
    { "chinese": "以失败告终", "english": "end in defeat", "type": "短语", "keyWords": ["defeat"] },
    { "chinese": "v. 防御；保卫；守卫；辩护；n. 被告；a. 辩护的", "english": "defend/defendant", "type": "单词", "keyWords": [] },
    { "chinese": "保卫祖国", "english": "defend one's country", "type": "短语", "keyWords": ["defend"] },
    { "chinese": "防御", "english": "defend against", "type": "短语", "keyWords": ["defend"] },
    { "chinese": "自卫", "english": "defend oneself", "type": "短语", "keyWords": ["defend"] },
    { "chinese": "（球赛中）守门", "english": "defend the goal", "type": "短语", "keyWords": ["defend"] },
    { "chinese": "n. 防御；保卫；辩护；a. 防御用的，自卫的", "english": "defence/defensive（英）/defense（美）", "type": "单词", "keyWords": [] },
    { "chinese": "保卫；捍卫；为...辩护", "english": "in defence of", "type": "短语", "keyWords": ["defence"] },
    { "chinese": "v. 给...下定义；使明确；规定（义务、权利）；n. 定义；限定", "english": "define/definition", "type": "单词", "keyWords": [] },
    { "chinese": "a. 明确的；确定的；一定的", "english": "definite", "type": "单词", "keyWords": [] },
    { "chinese": "明确的答复", "english": "a definite answer", "type": "短语", "keyWords": ["definite"] },
    { "chinese": "n. 学位；学衔；度数；程度；等级；[数学]次；幂；[音乐]阶，度", "english": "degree", "type": "单词", "keyWords": [] },
    { "chinese": "到什么程度", "english": "to what degree", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "三度烧伤", "english": "a third-degree burn", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "渐渐", "english": "by degrees", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "取得学位", "english": "take a degree", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "在一定程度上，有几分", "english": "to a certain degree/extent", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "（摄氏）零度以上/下", "english": "above/below zero degrees centigrade/Celsius", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "接受文学学士学位", "english": "receive the Bachelor of Arts degree", "type": "短语", "keyWords": ["degree"] },
    { "chinese": "v. 推迟；耽搁；使延期；vi. 耽搁；延误；n. 推迟；延期；耽搁", "english": "delay", "type": "单词", "keyWords": [] },
    { "chinese": "立刻", "english": "without delay", "type": "短语", "keyWords": ["delay"] },
    { "chinese": "耽搁/延误两天", "english": "a delay of two days", "type": "短语", "keyWords": ["delay"] },
    { "chinese": "推迟（做）某事", "english": "delay (doing) sth.", "type": "短语", "keyWords": ["delay"] },
    { "chinese": "这次火车事故使这封信耽搁了三天。", "english": "The letter was delayed three days by the train accident.", "type": "句子", "keyWords": ["delay"] },
    { "chinese": "我们要把会期延迟两周。", "english": "We'll delay the meeting for two weeks.", "type": "句子", "keyWords": ["delay"] },
    { "chinese": "n. 代表；n. 代表团；U. 授权，委托", "english": "delegate/delegation", "type": "单词", "keyWords": [] },
    { "chinese": "赴会的代表", "english": "a delegate to a conference", "type": "短语", "keyWords": ["delegate"] },
    { "chinese": "a. 深思熟虑的；蓄意的；ad. 蓄意地（近on purpose）", "english": "deliberate/deliberately", "type": "单词", "keyWords": [] },
    { "chinese": "v. 擦去，删除；n. 删除；删除部分", "english": "delete/deletion", "type": "单词", "keyWords": [] },
    { "chinese": "a. 纤细的；雅致的；微妙的；精巧的，精致的；脆弱的，易碎的；n. 精美；雅致；纤细；脆弱", "english": "delicate/delicacy", "type": "单词", "keyWords": [] },
    { "chinese": "a. 美味的；可口的", "english": "delicious", "type": "单词", "keyWords": [] },
    { "chinese": "n. 快乐（的事）；高兴；v. 使高兴；使愉快；a. 让人高兴的；ad. 欣喜地，快乐地", "english": "delight/delightful/delightfully", "type": "单词", "keyWords": [] },
    { "chinese": "对...感到高兴", "english": "be delighted at sth.", "type": "短语", "keyWords": ["delight"] },
    { "chinese": "高兴做某事", "english": "be delighted to do sth.", "type": "短语", "keyWords": ["delight"] },
    { "chinese": "喜欢做某事", "english": "delight in doing sth.", "type": "短语", "keyWords": ["delight"] },
    { "chinese": "他喜爱远距离散步。", "english": "He delights in taking long walks.", "type": "句子", "keyWords": ["delight"] },
    { "chinese": "让某人很高兴的是", "english": "much to one's delight", "type": "短语", "keyWords": ["delight"] },
    { "chinese": "以...为乐；喜爱（近take/have (an) interest in sth.）", "english": "take/have/find (a) delight in sth.", "type": "短语", "keyWords": ["delight"] }
];
