const qgl76_90 = [
    { "chinese": "v. 投递，分送；发表；给予（打击等）；n. 投递，分送；传送", "english": "deliver/delivery", "type": "单词", "keyWords": [] },
    { "chinese": "把...交给", "english": "deliver sth. to...", "type": "短语", "keyWords": ["deliver"] },
    { "chinese": "传话/讲话", "english": "deliver a message/a speech", "type": "短语", "keyWords": ["deliver"] },
    { "chinese": "v. 要求；需要；要求知道，查问；n. 要求；需要", "english": "demand", "type": "单词", "keyWords": [] },
    { "chinese": "向某人要求某物（近require, request, expect, ask）", "english": "demand sth. of sb.", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "要求（一般不用demand sb. to do sth.）", "english": "demand that ...(should)...", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "要求做某事", "english": "demand to do sth.", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "警察要求他说出姓名。", "english": "The policeman demanded to know his name.", "type": "句子", "keyWords": ["demand"] },
    { "chinese": "供求规律", "english": "the law of supply and demand", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "需求量很大；许多人都需要", "english": "in (great) demand", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "满足某人的需要或要求", "english": "meet/satisfy one's demands/needs", "type": "短语", "keyWords": ["demand"] },
    { "chinese": "这种书需求量很大。", "english": "There is a great demand/need for such books.", "type": "句子", "keyWords": ["demand"] },
    { "chinese": "a. 费事/力的；要仔细对待的；过分要求的，要求高的", "english": "demanding", "type": "单词", "keyWords": [] },
    { "chinese": "那是一件劳神的工作。", "english": "It's demanding work.", "type": "句子", "keyWords": ["demanding"] },
    { "chinese": "有过分要求的孩子", "english": "a demanding child", "type": "短语", "keyWords": ["demanding"] },
    { "chinese": "n. 民主；a. 民主的，民主政体的", "english": "democracy/democratic", "type": "单词", "keyWords": [] },
    { "chinese": "v. 示范，举例/用实验说明；证明，论证；显示；vi. 游行示威；n. 示范；实证", "english": "demonstrate/demonstration", "type": "单词", "keyWords": [] },
    { "chinese": "售货员演示了如何使用这种洗衣机。", "english": "The salesman demonstrated (~ showed) how to use the washing-machine.", "type": "句子", "keyWords": ["demonstrate"] },
    { "chinese": "a. 稠密的；密集的；ad. 稠密地；n. 密度；浓密", "english": "dense/densely/density", "type": "单词", "keyWords": [] },
    { "chinese": "密林", "english": "a dense forest", "type": "短语", "keyWords": ["dense"] },
    { "chinese": "人口密度", "english": "the density of the population", "type": "短语", "keyWords": ["density"] },
    { "chinese": "n. 牙医；a. 与牙有关的", "english": "dentist/dental", "type": "单词", "keyWords": [] },
    { "chinese": "在牙科诊所", "english": "at the dentist's", "type": "短语", "keyWords": ["dentist"] },
    { "chinese": "v. 否认；拒绝（允许、给予、接受或相信）（可接双宾）；n. 否认，否定；谢绝，拒绝", "english": "deny/denial", "type": "单词", "keyWords": [] },
    { "chinese": "不给犯人食物和水", "english": "deny the prisoner food or water", "type": "短语", "keyWords": ["deny"] },
    { "chinese": "否认做过某事", "english": "deny doing sth.", "type": "短语", "keyWords": ["deny"] },
    { "chinese": "不可否认的是...（书面语）", "english": "There's no denying the fact that...", "type": "句子", "keyWords": ["deny"] },
    { "chinese": "...是不可否认的", "english": "It cannot be denied that...", "type": "句子", "keyWords": ["deny"] },
    { "chinese": "vi. 离开；出发（正式用语）；n. 离开；背离", "english": "depart/departure", "type": "单词", "keyWords": [] },
    { "chinese": "去某地（比leave for a place正式）", "english": "depart for somewhere", "type": "短语", "keyWords": ["depart"] },
    { "chinese": "飞机的离港与进港", "english": "departures and arrivals of planes", "type": "短语", "keyWords": ["departure"] },
    { "chinese": "n. 部门；局，处，科，系，学部", "english": "department", "type": "单词", "keyWords": [] },
    { "chinese": "人事部门", "english": "the personnel department", "type": "短语", "keyWords": ["department"] },
    { "chinese": "（州）教育厅/部；教育系", "english": "the education department", "type": "短语", "keyWords": ["department"] },
    { "chinese": "物理系", "english": "the physics department", "type": "短语", "keyWords": ["department"] },
    { "chinese": "百货商店", "english": "a department store", "type": "短语", "keyWords": ["department"] },
    { "chinese": "vi. 视...而定；依靠；依赖；a. 可靠的；依靠的，依赖的；n. 依靠；独立，自主", "english": "depend/dependable/dependent/dependence/independence", "type": "单词", "keyWords": [] },
    { "chinese": "依靠/依赖/信赖某人做某事", "english": "depend on/upon sb. + to do sth./for sth.", "type": "短语", "keyWords": ["depend"] },
    { "chinese": "孩子们靠父母提供衣食。", "english": "Children depend on their parents for food and clothing./Children depend on their parents to provide them with food and clothing.", "type": "句子", "keyWords": ["depend"] },
    { "chinese": "看情况吧。", "english": "It all depends.", "type": "句子", "keyWords": ["depend"] },
    { "chinese": "依靠；依赖", "english": "be dependent on sth. or sb.", "type": "短语", "keyWords": ["dependent"] },
    { "chinese": "不依靠，不依赖", "english": "be independent of sth. or sb.", "type": "短语", "keyWords": ["independent"] },
    { "chinese": "v. /vi. （使）沉淀；付（定金）；存放；储蓄；n. 沉积（物）；存款；定金", "english": "deposit", "type": "单词", "keyWords": [] },
    { "chinese": "有价值的矿藏", "english": "valuable mineral deposits", "type": "短语", "keyWords": ["deposit"] },
    { "chinese": "活期存款", "english": "current deposit", "type": "短语", "keyWords": ["deposit"] },
    { "chinese": "她把钱存在银行里。", "english": "She deposited her money in the bank.", "type": "句子", "keyWords": ["deposit"] },
    { "chinese": "v. 使沮丧，使消沉，使抑郁；使不景气；按下，压下；n. 沮丧；抑郁；萧条；a. 感到/使人沮丧的", "english": "depress/depression/depressed/depressing", "type": "单词", "keyWords": [] },
    { "chinese": "大萧条", "english": "the Great Depression", "type": "短语", "keyWords": ["depression"] },
    { "chinese": "vi. 走（落、传）下来；v. 从...下来", "english": "descend", "type": "单词", "keyWords": [] },
    { "chinese": "下山", "english": "descend the mountain", "type": "短语", "keyWords": ["descend"] },
    { "chinese": "v. 描述；叙述；形容；n. 描述，形容；a. 描述性的", "english": "describe/description/descriptive", "type": "单词", "keyWords": [] },
    { "chinese": "把...描述成；把...说成是（称作）（近refer to, label）", "english": "describe... as（可接形容词）", "type": "短语", "keyWords": ["describe"] },
    { "chinese": "描述；形容", "english": "give a description of = describe", "type": "短语", "keyWords": ["describe/description"] },
    { "chinese": "无法形容", "english": "beyond description", "type": "短语", "keyWords": ["description"] },
    { "chinese": "n. 沙漠；荒芜之地，荒漠；a. 沙漠的；不毛的，荒凉的", "english": "desert¹", "type": "单词", "keyWords": [] },
    { "chinese": "文化荒原", "english": "a cultural desert", "type": "短语", "keyWords": ["desert¹"] },
    { "chinese": "荒凉的岛", "english": "a desert island", "type": "短语", "keyWords": ["desert¹"] },
    { "chinese": "v. 离开；抛弃，遗弃，离弃（尤指不负责任或义务而远离）；a. 荒废的，为人所弃的", "english": "desert²/deserted", "type": "单词", "keyWords": [] },
    { "chinese": "冷寂的大街", "english": "deserted street", "type": "短语", "keyWords": ["deserted"] },
    { "chinese": "她抛弃了急需帮助的朋友。", "english": "She deserted her friend in a time of need.", "type": "句子", "keyWords": ["desert²"] },
    { "chinese": "街上行人绝迹。", "english": "The streets were deserted.", "type": "句子", "keyWords": ["deserted"] },
    { "chinese": "v. 应该得到；应受；值得", "english": "deserve", "type": "单词", "keyWords": [] },
    { "chinese": "应受处分", "english": "deserve a punishment/deserve to be punished/deserve punishing", "type": "短语", "keyWords": ["deserve"] },
    { "chinese": "这是你应得的。/你罪有应得。/你活该。（意义褒贬根据上下文）", "english": "You deserve it.", "type": "句子", "keyWords": ["deserve"] },
    { "chinese": "v. 设计；n. 设计；图案；n. 设计师，制图师", "english": "design/designer", "type": "单词", "keyWords": [] },
    { "chinese": "v. 愿望；渴望；请求；n. 愿望；请求；渴望；a. 渴望的，想得到的", "english": "desire/desired", "type": "单词", "keyWords": [] },
    { "chinese": "渴望得到和平", "english": "desire peace = have a desire for peace", "type": "短语", "keyWords": ["desire"] },
    { "chinese": "急切地想做某事", "english": "have a strong desire to do sth.", "type": "短语", "keyWords": ["desire"] },
    { "chinese": "很想做某事", "english": "desire to do", "type": "短语", "keyWords": ["desire"] },
    { "chinese": "想要某人做某事", "english": "desire sb. to do sth.", "type": "短语", "keyWords": ["desire"] },
    { "chinese": "她希望他立刻去。（虚拟语气）", "english": "She desired that he (should) go at once.", "type": "句子", "keyWords": ["desire"] },
    { "chinese": "产生期望的结果/达到预期的效果", "english": "produce/achieve the desired results", "type": "短语", "keyWords": ["desired"] },
    { "chinese": "n. 书桌；办公桌", "english": "desk", "type": "单词", "keyWords": [] },
    { "chinese": "坐在桌旁", "english": "sit at one's desk", "type": "短语", "keyWords": ["desk"] },
    { "chinese": "adj. （电脑等）台式的；n. 桌面；台式电脑；（计）桌面", "english": "desktop", "type": "单词", "keyWords": [] },
    { "chinese": "n. 绝望；沮丧（强调完全没有希望，暗示“无能的，听任摆布”的意思）", "english": "despair", "type": "单词", "keyWords": [] },
    { "chinese": "他绝望地放弃尝试。", "english": "He gave up the attempt in despair.", "type": "句子", "keyWords": ["despair"] },
    { "chinese": "a. 不顾一切的，绝望的；n. 绝望", "english": "desperate/desperation", "type": "单词", "keyWords": [] },
    { "chinese": "绝望的呼救声", "english": "a desperate cry for help", "type": "短语", "keyWords": ["desperate"] },
    { "chinese": "拼死；不顾死活地", "english": "in desperation", "type": "短语", "keyWords": ["desperation"] },
    { "chinese": "prep. 不管，尽管，不论（近in spite of，注意后面不直接跟that从句）", "english": "despite", "type": "单词", "keyWords": [] },
    { "chinese": "n. 餐后甜点；甜点心", "english": "dessert", "type": "单词", "keyWords": [] },
    { "chinese": "n. 目的地，终点；目标，目的", "english": "destination", "type": "单词", "keyWords": [] },
    { "chinese": "主要的游客目的地", "english": "a major tourist destination", "type": "短语", "keyWords": ["destination"] },
    { "chinese": "v. 破坏；拆毁；消灭（指剧烈地破坏，使之不存在或使之失去效能）；n. 驱逐舰", "english": "destroy/destroyer", "type": "单词", "keyWords": [] },
    { "chinese": "n. 破坏；毁灭；a. 破坏（性）的；毁灭性的", "english": "destruction/destructive", "type": "单词", "keyWords": [] },
    { "chinese": "n. 细节；v. 详述；a. 详细的", "english": "detail/detailed", "type": "单词", "keyWords": [] },
    { "chinese": "详细地", "english": "in detail", "type": "短语", "keyWords": ["detail"] },
    { "chinese": "详述，逐一细说", "english": "go into detail (about sth.)", "type": "短语", "keyWords": ["detail"] },
    { "chinese": "a. 侦探的；n. 侦探；v. 发现；n. 探测器", "english": "detective/detect/detector", "type": "单词", "keyWords": [] },
    { "chinese": "n. 决心；确定；顽强；果断，坚定", "english": "determination", "type": "单词", "keyWords": [] },
    { "chinese": "v. 确定；决定；裁决；使下决心；vi. 下决心；决定（on）；a. 决意的；坚决的", "english": "determine/determined", "type": "单词", "keyWords": [] },
    { "chinese": "需求决定生产。", "english": "Demand determines (=decides) production.", "type": "句子", "keyWords": ["determine"] },
    { "chinese": "陪审团将对这些指控的真伪作出裁决。", "english": "A jury will determine whether the charges are true or false.", "type": "句子", "keyWords": ["determine"] },
    { "chinese": "他决心立刻就走。", "english": "He determined to go/that he (should) go at once.", "type": "句子", "keyWords": ["determine"] },
    { "chinese": "他们决定早些出发。", "english": "They determined (=decided) on an early start.", "type": "句子", "keyWords": ["determine"] },
    { "chinese": "下定决心要做某事", "english": "be determined to do...", "type": "短语", "keyWords": ["determined"] },
    { "chinese": "决然", "english": "in a determined manner", "type": "短语", "keyWords": ["determined"] },
    { "chinese": "v. 发展；发育；开发（资源等）；形成，培养；研制；使显影，冲印；n. 发展；开发（资源等）；研制；a. 发展中的；发达的", "english": "develop/development/developing/developed", "type": "单词", "keyWords": [] },
    { "chinese": "使孩子身体发育", "english": "develop a child's body", "type": "短语", "keyWords": ["develop"] },
    { "chinese": "冲洗底片", "english": "develop a film", "type": "短语", "keyWords": ["develop"] },
    { "chinese": "成为植物/领袖", "english": "develop into a plant/a leader", "type": "短语", "keyWords": ["develop"] },
    { "chinese": "培养兴趣/阅读能力/做某事的习惯", "english": "develop an interest/reading skills/the habit of doing sth.", "type": "短语", "keyWords": ["develop"] },
    { "chinese": "随着...的发展", "english": "with the development of", "type": "短语", "keyWords": ["development"] },
    { "chinese": "对外贸易方面的新进展", "english": "the latest developments in foreign trade", "type": "短语", "keyWords": ["development"] },
    { "chinese": "n. 设计；装置（为特定目的的设计或发明，或指改装的机器）", "english": "device", "type": "单词", "keyWords": [] },
    { "chinese": "v. 奉献；把...专用（于）（to）；a. 忠实的；投入的；ad. 忠实地；n. 热爱，投入（to sth.）", "english": "devote/devoted/devotedly/devotion", "type": "单词", "keyWords": [] },
    { "chinese": "致力于", "english": "be devoted to (doing) sth.", "type": "短语", "keyWords": ["devoted"] },
    { "chinese": "我们的大多数会议都用来讨论住房问题。", "english": "Most of our meetings were devoted to discussing the housing problems.", "type": "句子", "keyWords": ["devoted"] },
    { "chinese": "献身于", "english": "devote one's time/life/energy to (doing) sth.", "type": "短语", "keyWords": ["devote"] },
    { "chinese": "我的一个忠实的朋友", "english": "a devoted friend of mine", "type": "短语", "keyWords": ["devoted"] },
    { "chinese": "忠于职守", "english": "one's devotion to duty", "type": "短语", "keyWords": ["devotion"] },
    { "chinese": "他对教育事业的热爱/忠诚", "english": "his devotion to the cause of education", "type": "短语", "keyWords": ["devotion"] },
    { "chinese": "把时间用于科研", "english": "the devotion of one's time to scientific research", "type": "短语", "keyWords": ["devotion"] },
    { "chinese": "v. 诊断（疾病）；对（问题等）原因（或性质）下结论；n. 诊断；判断", "english": "diagnose/diagnosis", "type": "单词", "keyWords": [] },
    { "chinese": "n. 图表；图示；图解", "english": "diagram", "type": "单词", "keyWords": [] },
    { "chinese": "v. 拨（电话号码）；n. 刻度盘；钟面；转盘；（自动电话）拨号盘", "english": "dial", "type": "单词", "keyWords": [] },
    { "chinese": "n. 方言；行话；语调", "english": "dialect", "type": "单词", "keyWords": [] },
    { "chinese": "n. 对话；对白", "english": "dialog(ue)", "type": "单词", "keyWords": [] },
    { "chinese": "n. 钻石；金刚石；（扑克牌）方块；菱形（物）", "english": "diamond", "type": "单词", "keyWords": [] },
    { "chinese": "n. 日记；日志", "english": "diary", "type": "单词", "keyWords": [] },
    { "chinese": "记日记", "english": "keep a diary", "type": "短语", "keyWords": ["diary"] },
    { "chinese": "n. 听写；口授；v. 口授；发号施令；使听写", "english": "dictation/dictate", "type": "单词", "keyWords": [] },
    { "chinese": "进行听写", "english": "have a dictation", "type": "短语", "keyWords": ["dictation"] },
    { "chinese": "n. 词典；字典", "english": "dictionary", "type": "单词", "keyWords": [] },
    { "chinese": "v. 死；枯萎；vi. 遭受（某种死亡形式）（接同源宾语death）；a. 垂死的", "english": "die/dying", "type": "单词", "keyWords": [] },
    { "chinese": "寿终/夭折", "english": "die old/young", "type": "短语", "keyWords": ["die"] },
    { "chinese": "完全消失；灭绝", "english": "die out", "type": "短语", "keyWords": ["die"] },
    { "chinese": "因伤/患癌致死", "english": "die from wounds/cancer", "type": "短语", "keyWords": ["die"] },
    { "chinese": "因病而死", "english": "die of a disease", "type": "短语", "keyWords": ["die"] },
    { "chinese": "英勇就义；死得英雄", "english": "die a hero/a heroic death", "type": "短语", "keyWords": ["die"] },
    { "chinese": "逐渐停止；逐渐消失", "english": "die away", "type": "短语", "keyWords": ["die"] },
    { "chinese": "摩托车的噪音消失了。", "english": "The noise of the motorcar died away.", "type": "句子", "keyWords": ["die"] },
    { "chinese": "逐渐减弱；逐渐模糊", "english": "die down", "type": "短语", "keyWords": ["die"] },
    { "chinese": "等听众激动的情绪平息后演讲人又开始演讲。", "english": "After the excitement of the audience died down, the speaker restarted his speech.", "type": "句子", "keyWords": ["die"] },
    { "chinese": "相继死去", "english": "die off", "type": "短语", "keyWords": ["die"] },
    { "chinese": "这个寡妇还在中年时，她的亲属就先后离开了人世。", "english": "As the widow was still middle-aged, her relatives all died off.", "type": "句子", "keyWords": ["die"] },
    { "chinese": "（口）渴望；极想", "english": "be dying to do sth./for sth.", "type": "短语", "keyWords": ["dying"] },
    { "chinese": "救死扶伤", "english": "heal the wounded and rescue the dying", "type": "短语", "keyWords": ["dying"] },
    { "chinese": "n. 日常饮食；规定饮食", "english": "diet", "type": "单词", "keyWords": [] },
    { "chinese": "节食", "english": "be/go on a diet", "type": "短语", "keyWords": ["diet"] },
    { "chinese": "vi. 不同，有区别；（意见）发生分歧（from）", "english": "differ", "type": "单词", "keyWords": [] },
    { "chinese": "与...很不同", "english": "differ sharply/greatly from", "type": "短语", "keyWords": ["differ"] },
    { "chinese": "在...方面与...不同", "english": "differ in sth. from", "type": "短语", "keyWords": ["differ"] },
    { "chinese": "n. 差别；不同；a. 不同的；ad. 不同地", "english": "difference/different/differently", "type": "单词", "keyWords": [] },
    { "chinese": "有作用，有影响", "english": "make a difference", "type": "短语", "keyWords": ["difference"] },
    { "chinese": "这对我来说有什么区别么？", "english": "What difference does it make to me?", "type": "句子", "keyWords": ["difference"] },
    { "chinese": "你留下还是离开都不重要。", "english": "It does not make much difference whether you go or stay.", "type": "句子", "keyWords": ["difference"] },
    { "chinese": "我在不在场没什么关系。", "english": "It doesn't make a slight difference my being there.", "type": "句子", "keyWords": ["difference"] },
    { "chinese": "说出A和B在...方面不同", "english": "tell the difference between A and B in sth.", "type": "短语", "keyWords": ["difference"] },
    { "chinese": "在...方面（很/迥然）不同", "english": "be (totally/quite) different from... in...", "type": "短语", "keyWords": ["different"] },
    { "chinese": "失之毫厘，谬以千里。", "english": "One false step will make a great difference.", "type": "句子", "keyWords": ["difference"] },
    { "chinese": "a. 困难的；艰难的；n. 困难", "english": "difficult/difficulty", "type": "单词", "keyWords": [] },
    { "chinese": "困难地", "english": "with difficulty", "type": "短语", "keyWords": ["difficulty"] },
    { "chinese": "克服困难", "english": "overcome difficulties", "type": "短语", "keyWords": ["difficulty"] },
    { "chinese": "觉得某事有困难", "english": "have difficulty (in) doing sth./with sth.", "type": "短语", "keyWords": ["difficulty"] },
    { "chinese": "v. 挖掘", "english": "dig", "type": "单词", "keyWords": [] },
    { "chinese": "v. 消化；吸收；n. 摘要；文摘；n. 消化力，领悟", "english": "digest/digestion", "type": "单词", "keyWords": [] },
    { "chinese": "理解一本书", "english": "digest a book", "type": "短语", "keyWords": ["digest"] },
    { "chinese": "《读者文摘》", "english": "Reader's Digest", "type": "短语", "keyWords": ["digest"] },
    { "chinese": "n. 数字；数位", "english": "digit", "type": "单词", "keyWords": [] },
    { "chinese": "数字410是个三位数。", "english": "The number 410 contains three digits.", "type": "句子", "keyWords": ["digit"] },
    { "chinese": "a. 数码的；数字的；数字显示的；（使用）电脑技术的", "english": "digital", "type": "单词", "keyWords": [] },
    { "chinese": "n. 尊严；v. 使有尊严；a. 有尊严的", "english": "dignity/dignify/dignified", "type": "单词", "keyWords": [] },
    { "chinese": "庄重地；体面地", "english": "with dignity", "type": "短语", "keyWords": ["dignity"] },
    { "chinese": "a. 勤勉的；勤奋的；n. 勤勉", "english": "diligent/diligence", "type": "单词", "keyWords": [] },
    { "chinese": "工作努力", "english": "be diligent in one's work", "type": "短语", "keyWords": ["diligent"] },
    { "chinese": "努力追求自己的目标", "english": "pursue his aims with diligence", "type": "短语", "keyWords": ["diligence"] },
    { "chinese": "a. 昏暗的；模糊不清的", "english": "dim", "type": "单词", "keyWords": [] },
    { "chinese": "对过去的模糊记忆", "english": "a dim memory of the past", "type": "短语", "keyWords": ["dim"] },
    { "chinese": "房屋的模糊轮廓", "english": "the dim outline of a building", "type": "短语", "keyWords": ["dim"] },
    { "chinese": "远处模糊的人影", "english": "a dim figure in the distance", "type": "短语", "keyWords": ["dim"] },
    { "chinese": "v. 进正餐；出外吃饭（在朋友家或餐馆）", "english": "dine/dine out", "type": "单词", "keyWords": [] },
    { "chinese": "n. 正餐，主餐；晚餐", "english": "dinner", "type": "单词", "keyWords": [] },
    { "chinese": "正餐吃...", "english": "have sth. for dinner", "type": "短语", "keyWords": ["dinner"] },
    { "chinese": "n. 恐龙", "english": "dinosaur", "type": "单词", "keyWords": [] },
    { "chinese": "n. 二氧化物", "english": "dioxide", "type": "单词", "keyWords": [] },
    { "chinese": "vi. /n. 浸；蘸；浏览，翻阅", "english": "dip", "type": "单词", "keyWords": [] },
    { "chinese": "我在口袋里掏几枚硬币。", "english": "I dipped into my pocket for some coins.", "type": "句子", "keyWords": ["dip"] },
    { "chinese": "把头潜入水中", "english": "dip one's head into water", "type": "短语", "keyWords": ["dip"] },
    { "chinese": "价格急降", "english": "a dip in prices", "type": "短语", "keyWords": ["dip"] },
    { "chinese": "随便翻阅乔叟的作品/涉猎心理学/浏览书籍", "english": "dip into Chaucer/psychology/books", "type": "短语", "keyWords": ["dip"] },
    { "chinese": "n. 奖状；毕业文凭，学位证书", "english": "diploma", "type": "单词", "keyWords": [] },
    { "chinese": "n. 外交家；外交官；有外交手腕的人；a. 外交的；圆滑的；策略的", "english": "diplomat/diplomatic", "type": "单词", "keyWords": [] },
    { "chinese": "v. 指点，指导；指挥；命令；给...指路；导演；a. /ad. 直（的）；径直（的）；直接的；笔直的", "english": "direct", "type": "单词", "keyWords": [] },
    { "chinese": "直达列车", "english": "a direct train", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "直接的回答", "english": "a direct response", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "指挥某人去某地", "english": "direct sb. to a place", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "指点某人做某事", "english": "direct sb. to do sth.", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "将他们火力对准目标", "english": "direct their fire at the target", "type": "短语", "keyWords": ["direct"] },
    { "chinese": "我们直接从北京到上海。", "english": "We went direct from Beijing to Shanghai.", "type": "句子", "keyWords": ["direct"] },
    { "chinese": "n. 方向；（常pl）指引，说明（instructions）；U. 指导；导演", "english": "direction", "type": "单词", "keyWords": [] },
    { "chinese": "四面八方", "english": "in all directions", "type": "短语", "keyWords": ["direction"] },
    { "chinese": "朝着某个方向", "english": "in the direction of...", "type": "短语", "keyWords": ["direction"] },
    { "chinese": "来自那个方向", "english": "come from that direction", "type": "短语", "keyWords": ["direction"] },
    { "chinese": "予以用法说明/指导", "english": "give directions for use", "type": "短语", "keyWords": ["direction"] },
    { "chinese": "ad. 直接；马上；一.....就（immediately, instantly, the minute...）", "english": "directly", "type": "单词", "keyWords": [] },
    { "chinese": "我们一做完就来。", "english": "We'll come directly/instantly/immediately/the moment we have finished.", "type": "句子", "keyWords": ["directly"] },
    { "chinese": "n. 主管；董事；经理；厂长；导演", "english": "director", "type": "单词", "keyWords": [] },
    { "chinese": "n. 污物；灰尘", "english": "dirt", "type": "单词", "keyWords": [] },
    { "chinese": "泥路", "english": "dirt road", "type": "短语", "keyWords": ["dirt"] },
    { "chinese": "a. 脏的；卑鄙的，下流的；v. 弄脏", "english": "dirty", "type": "单词", "keyWords": [] },
    { "chinese": "下流人/话", "english": "a dirty fellow/talk", "type": "短语", "keyWords": ["dirty"] },
    { "chinese": "弄脏自己的手脚", "english": "dirty one's hands", "type": "短语", "keyWords": ["dirty"] },
    { "chinese": "a. 丧失（劳动）能力的，残疾的；v. 使残废，使失去（劳动）能力", "english": "disabled/disable", "type": "单词", "keyWords": [] },
    { "chinese": "残疾人", "english": "the disabled", "type": "短语", "keyWords": ["disabled"] },
    { "chinese": "n. 不利地位；不利条件；劣势；v. 使处于不利地位；损害，危害；a. 处于不利地位的", "english": "disadvantage/disadvantaged", "type": "单词", "keyWords": [] },
    { "chinese": "处于不利地位", "english": "at a disadvantage", "type": "短语", "keyWords": ["disadvantage"] },
    { "chinese": "对某人不利，使某人吃亏", "english": "to sb.'s disadvantage", "type": "短语", "keyWords": ["disadvantage"] },
    { "chinese": "弱势/处于不利地位的群体", "english": "the disadvantaged", "type": "短语", "keyWords": ["disadvantaged"] },
    { "chinese": "vi. 不一致，不适宜", "english": "disagree", "type": "单词", "keyWords": [] },
    { "chinese": "我不宜吃苹果。", "english": "Apples disagree with me.", "type": "句子", "keyWords": ["disagree"] },
    { "chinese": "就某事不同意某人", "english": "disagree with sb. on/ about sth.", "type": "短语", "keyWords": ["disagree"] },
    { "chinese": "就我个人而言，那件事我倾向于不同意您的意见。", "english": "Personally, I'm inclined to disagree with you on that.", "type": "句子", "keyWords": ["disagree"] },
    { "chinese": "a. 不合意的；令人不快的；不讨人喜欢的，厌恶的", "english": "disagreeable", "type": "单词", "keyWords": ["disagree"] },
    { "chinese": "不合意的", "english": "be disagreeable to", "type": "短语", "keyWords": ["disagreeable"] },
    { "chinese": "食物可能不合口味。", "english": "Food may be disagreeable to the taste.", "type": "句子", "keyWords": ["disagreeable"] },
    { "chinese": "n. (U)(C) 意见不同，不调和，争执", "english": "disagreement", "type": "单词", "keyWords": ["disagree"] },
    { "chinese": "vi. 消失，不见；消散", "english": "disappear", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 使失望", "english": "disappoint", "type": "单词", "keyWords": [] },
    { "chinese": "a. 使人失望的", "english": "disappointing", "type": "单词", "keyWords": ["disappoint"] },
    { "chinese": "a. 感到失望的", "english": "disappointed", "type": "单词", "keyWords": ["disappoint"] },
    { "chinese": "n. (U)(C) 失望", "english": "disappointment", "type": "单词", "keyWords": ["disappoint"] },
    { "chinese": "令人（非常）失望的是", "english": "(much) to one's disappointment", "type": "短语", "keyWords": ["disappointment"] },
    { "chinese": "对...感到失望", "english": "be disappointed at sth.", "type": "短语", "keyWords": ["disappointed"] },
    { "chinese": "n. (U) 不赞成；非难", "english": "disapproval", "type": "单词", "keyWords": [] },
    { "chinese": "摇头表示不赞成", "english": "shake one's head in disapproval", "type": "短语", "keyWords": ["disapproval"] },
    { "chinese": "不赞成某人的行为", "english": "speak with disapproval of one's behavior", "type": "短语", "keyWords": ["disapproval"] },
    { "chinese": "v. 不赞成；不同意(of)", "english": "disapprove", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 不赞成地；不以为然地", "english": "disapprovingly", "type": "单词", "keyWords": ["disapprove"] },
    { "chinese": "不赞成（小孩子抽烟）", "english": "disapprove of (children's smoking)", "type": "短语", "keyWords": ["disapprove"] },
    { "chinese": "n. (C)(U) 灾难；大祸", "english": "disaster", "type": "单词", "keyWords": [] },
    { "chinese": "a. 损失惨重的；灾难性的", "english": "disastrous", "type": "单词", "keyWords": ["disaster"] },
    { "chinese": "灾区人民", "english": "the people of the disaster-stricken areas", "type": "短语", "keyWords": ["disaster"] },
    { "chinese": "n. (C) 圆盘物；唱片；磁盘", "english": "disc", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 纪律；v. 训练；惩罚", "english": "discipline", "type": "单词", "keyWords": [] },
    { "chinese": "a. 受过训练的，遵守纪律的", "english": "disciplined", "type": "单词", "keyWords": ["discipline"] },
    { "chinese": "守纪", "english": "maintain/ have/ keep/ show discipline", "type": "短语", "keyWords": ["discipline"] },
    { "chinese": "vt. 揭露，透露", "english": "disclose", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 迪斯科舞（曲）", "english": "disco", "type": "单词", "keyWords": [] },
    { "chinese": "v. 打折买或卖；从价格中打去（若干）折扣；n. (C)(U) 折扣", "english": "discount", "type": "单词", "keyWords": [] },
    { "chinese": "打八五折", "english": "at a 15% discount", "type": "短语", "keyWords": ["discount"] },
    { "chinese": "该店服装全部减价出售。", "english": "The store discounted all clothing.", "type": "句子", "keyWords": ["discount"] },
    { "chinese": "v. 阻止；阻拦", "english": "discourage", "type": "单词", "keyWords": [] },
    { "chinese": "a. 使人沮丧的", "english": "discouraging", "type": "单词", "keyWords": ["discourage"] },
    { "chinese": "a. 感到沮丧的", "english": "discouraged", "type": "单词", "keyWords": ["discourage"] },
    { "chinese": "n. (U)(C) 气馁，挫折，劝阻", "english": "discouragement", "type": "单词", "keyWords": ["discourage"] },
    { "chinese": "阻止某人做某事", "english": "discourage/ prohibit / ban/ stop/ keep sb. from doing...", "type": "短语", "keyWords": ["discourage"] },
    { "chinese": "v. 发现；找到；看出", "english": "discover", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 发现；被发现的事物", "english": "discovery", "type": "单词", "keyWords": ["discover"] },
    { "chinese": "vt. 歧视；区别", "english": "discriminate", "type": "单词", "keyWords": [] },
    { "chinese": "区分好书和坏书", "english": "discriminate good books from bad ones", "type": "短语", "keyWords": ["discriminate"] },
    { "chinese": "n. (U) 区别；识别力；辨别力；歧视", "english": "discrimination", "type": "单词", "keyWords": ["discriminate"] },
    { "chinese": "种族歧视", "english": "racial discrimination", "type": "短语", "keyWords": ["discrimination"] },
    { "chinese": "n. (C) 铁饼", "english": "discus", "type": "单词", "keyWords": [] },
    { "chinese": "掷铁饼", "english": "throw a discus", "type": "短语", "keyWords": ["discus"] },
    { "chinese": "v. 讨论", "english": "discuss", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C)(U) 讨论；一次讨论", "english": "discussion", "type": "单词", "keyWords": ["discuss"] },
    { "chinese": "与某人商讨某事", "english": "discuss sth. with sb.", "type": "短语", "keyWords": ["discuss"] },
    { "chinese": "对...进行讨论", "english": "have a discussion about/ on sth. = discuss sth.", "type": "短语", "keyWords": ["discuss", "discussion"] },
    { "chinese": "还在讨论中", "english": "under discussion", "type": "短语", "keyWords": ["discussion"] },
    { "chinese": "n. (C) 疾病；(U)（泛指）疾病；v. 使生病", "english": "disease", "type": "单词", "keyWords": [] },
    { "chinese": "a. 害病的", "english": "diseased", "type": "单词", "keyWords": ["disease"] },
    { "chinese": "害病的植物", "english": "a diseased plant", "type": "短语", "keyWords": ["diseased"] },
    { "chinese": "v. 使厌恶；n. (U) 厌恶", "english": "disgust", "type": "单词", "keyWords": [] },
    { "chinese": "a. 使人厌恶的", "english": "disgusting", "type": "单词", "keyWords": ["disgust"] },
    { "chinese": "a. 感到厌恶的", "english": "disgusted", "type": "单词", "keyWords": ["disgust"] },
    { "chinese": "对...感到厌恶", "english": "be disgusted at sth./ with sb.", "type": "短语", "keyWords": ["disgusted"] },
    { "chinese": "n. (C) 菜肴；盘；碟", "english": "dish", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 洗碗机；洗碟机；洗碟工", "english": "dishwasher", "type": "单词", "keyWords": ["dish"] },
    { "chinese": "a. 不诚实的", "english": "dishonest", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. (C) 不喜爱；厌恶", "english": "dislike", "type": "单词", "keyWords": [] },
    { "chinese": "厌恶某事；不喜爱某事", "english": "have a dislike for/of sth.", "type": "短语", "keyWords": ["dislike"] },
    { "chinese": "vt. 解散；开除，解雇；下课；不再考虑；vi. 解散", "english": "dismiss", "type": "单词", "keyWords": [] },
    { "chinese": "vt./vi. 不服从；违抗", "english": "disobey", "type": "单词", "keyWords": [] },
    { "chinese": "n. (常C) 混乱，无序；（身心机能）失调，紊乱", "english": "disorder", "type": "单词", "keyWords": [] },
    { "chinese": "混乱；乱糟糟", "english": "in disorder", "type": "短语", "keyWords": ["disorder"] },
    { "chinese": "a. 杂乱的；无秩序的；目无法纪的；骚乱的；任性的", "english": "disorderly", "type": "单词", "keyWords": ["disorder"] },
    { "chinese": "n. (常C) 展览（强调陈列之意）；显示器；v. 展示；显示", "english": "display", "type": "单词", "keyWords": [] },
    { "chinese": "在展览中", "english": "on display", "type": "短语", "keyWords": ["display"] },
    { "chinese": "vt. 使不快，使（人）生气，冒犯，惹怒", "english": "displease", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 使感觉不满，不满足", "english": "dissatisfy", "type": "单词", "keyWords": [] },
    { "chinese": "a. 不满意的，不高兴的(with)", "english": "dissatisfied", "type": "单词", "keyWords": ["dissatisfy"] },
    { "chinese": "n. (U) 不满意(with, at)", "english": "dissatisfaction", "type": "单词", "keyWords": ["dissatisfy"] },
    { "chinese": "令人不满意（的是...）", "english": "to one's dissatisfaction", "type": "短语", "keyWords": ["dissatisfaction"] },
    { "chinese": "vi./vt.（使）溶解；（使）融化", "english": "dissolve", "type": "单词", "keyWords": [] },
    { "chinese": "溶解在水里", "english": "dissolve in water", "type": "短语", "keyWords": ["dissolve"] },
    { "chinese": "n. (常C) 距离；间距；远处；v. 使远离；使疏远", "english": "distance", "type": "单词", "keyWords": [] },
    { "chinese": "a. 远的", "english": "distant", "type": "单词", "keyWords": ["distance"] },
    { "chinese": "隔开一些；稍远一些", "english": "at a distance", "type": "短语", "keyWords": ["distance"] },
    { "chinese": "从远处/从一定距离", "english": "from a distance", "type": "短语", "keyWords": ["distance"] },
    { "chinese": "在远处", "english": "in the distance", "type": "短语", "keyWords": ["distance"] },
    { "chinese": "长途电话", "english": "a long-distance call", "type": "短语", "keyWords": ["distance"] },
    { "chinese": "和某人保持一定距离，不亲密", "english": "keep sb. at a distance", "type": "短语", "keyWords": ["distance"] },
    { "chinese": "他家离医院只有几步路。", "english": "His house is within walking distance of the hospital.", "type": "句子", "keyWords": ["distance"] },
    { "chinese": "与前总统特朗普保持距离", "english": "distance themselves from former President Trump", "type": "短语", "keyWords": ["distance"] },
    { "chinese": "久远的过去", "english": "the distant past", "type": "短语", "keyWords": ["distant"] },
    { "chinese": "远房堂兄弟", "english": "a distant cousin", "type": "短语", "keyWords": ["distant"] },
    { "chinese": "a. 有区别的，不同的；明显的，清楚的，易于被感觉或察觉的", "english": "distinct", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 清楚地，显然", "english": "distinctly", "type": "单词", "keyWords": ["distinct"] },
    { "chinese": "n. (C)(U) 区别；差别；（与他物不同的）特性", "english": "distinction", "type": "单词", "keyWords": ["distinct"] },
    { "chinese": "a. 卓越的；杰出的", "english": "distinguished", "type": "单词", "keyWords": [] },
    { "chinese": "v. 区别；辨别；（~oneself）使杰出；认出", "english": "distinguish", "type": "单词", "keyWords": [] },
    { "chinese": "贵宾", "english": "distinguished guest", "type": "短语", "keyWords": ["distinguished"] },
    { "chinese": "明辨是非", "english": "distinguish right from wrong", "type": "短语", "keyWords": ["distinguish"] },
    { "chinese": "v. 使转向；转移（注意力）；使分心(from)", "english": "distract", "type": "单词", "keyWords": [] },
    { "chinese": "父亲走后，无论什么都不能分散掉我的失落感。", "english": "After my father went away, nothing could distract me from my sense of loss.", "type": "句子", "keyWords": ["distract"] },
    { "chinese": "n. (常C) 痛苦；不幸；v. 使痛苦；使不幸", "english": "distress", "type": "单词", "keyWords": [] },
    { "chinese": "a. 使人忧伤的", "english": "distressing", "type": "单词", "keyWords": ["distress"] },
    { "chinese": "a. 感到忧伤的", "english": "distressed", "type": "单词", "keyWords": ["distress"] },
    { "chinese": "使某人大为忧伤", "english": "be a distress to sb.", "type": "短语", "keyWords": ["distress"] },
    { "chinese": "为...而忧伤", "english": "be distressed about/ over", "type": "短语", "keyWords": ["distressed"] },
    { "chinese": "v. 分发；分配；散布", "english": "distribute", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 地区；地域；区域", "english": "district", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)/vt. 不信任；怀疑", "english": "distrust", "type": "单词", "keyWords": [] },
    { "chinese": "不信任地", "english": "in/ with distrust", "type": "短语", "keyWords": ["distrust"] },
    { "chinese": "v. 扰乱；使心神不安", "english": "disturb", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)(C) 打扰；扰乱", "english": "disturbance", "type": "单词", "keyWords": ["disturb"] },
    { "chinese": "对不起，打扰你了，我有个问题请教。", "english": "I'm sorry to disturb you with this question.", "type": "句子", "keyWords": ["disturb"] },
    { "chinese": "扰乱治安", "english": "disturb public order", "type": "短语", "keyWords": ["disturb"] },
    { "chinese": "骚乱；骚动", "english": "cause a disturbance", "type": "短语", "keyWords": ["disturbance"] },
    { "chinese": "n. (C) 沟；沟渠；壕沟", "english": "ditch", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. (C) 潜水；跳水；俯冲", "english": "dive", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 潜水员；跳水员", "english": "diver", "type": "单词", "keyWords": ["dive"] },
    { "chinese": "扑向某物；潜水寻找", "english": "dive for sth.", "type": "短语", "keyWords": ["dive"] },
    { "chinese": "向…冲去", "english": "make a dive for", "type": "短语", "keyWords": ["dive"] },
    { "chinese": "跳入水中/埋头读书", "english": "dive into water/ books", "type": "短语", "keyWords": ["dive"] },
    { "chinese": "adj. 不同的，相异的；多种多样的", "english": "diverse", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)（可以和不定冠词连用）多样性，多样化；不同，差异", "english": "diversity", "type": "单词", "keyWords": ["diverse"] },
    { "chinese": "vt. 使多样化", "english": "diversify", "type": "单词", "keyWords": ["diverse"] },
    { "chinese": "一个多元化的感到被包容的员工队伍会让你的员工有不同的观点，这将有助于做出更好的决策和更快地解决问题。", "english": "A diverse workforce that feels included will bring your workforce a variety of different perspectives that will contribute to better decision-making and faster problem-solving.", "type": "句子", "keyWords": ["diverse"] },
    { "chinese": "v. 分开；分隔；划开；[数学]除", "english": "divide", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 区分；划分；除法；(C) 部门（如处、科、系）；组", "english": "division", "type": "单词", "keyWords": ["divide"] },
    { "chinese": "把东西分成两半", "english": "divide a thing in two", "type": "短语", "keyWords": ["divide"] },
    { "chinese": "分成", "english": "divide...into...", "type": "短语", "keyWords": ["divide"] },
    { "chinese": "6被2除得3。", "english": "Six divided by 2 is 3.", "type": "句子", "keyWords": ["divide"] },
    { "chinese": "分界线", "english": "dividing line", "type": "短语", "keyWords": ["divide"] },
    { "chinese": "n. (C)/vi. 离婚；v. 与…离婚；判…离婚", "english": "divorce", "type": "单词", "keyWords": [] },
    { "chinese": "a. 离婚了的", "english": "divorced", "type": "单词", "keyWords": ["divorce"] },
    { "chinese": "与某人离婚", "english": "divorce sb.", "type": "短语", "keyWords": ["divorce"] },
    { "chinese": "离婚", "english": "get divorced", "type": "短语", "keyWords": ["divorce"] },
    { "chinese": "a. 头晕目眩的", "english": "dizzy", "type": "单词", "keyWords": [] },
    { "chinese": "v. 做；干；情况；行；产生；整理", "english": "do", "type": "单词", "keyWords": [] },
    { "chinese": "除去；废除（奴隶制）", "english": "do away with (slavery)", "type": "短语", "keyWords": ["do"] },
    { "chinese": "整理；粉刷；包扎", "english": "do...", "type": "短语", "keyWords": ["do"] },
    { "chinese": "对某人有益/害", "english": "do good/ harm/ wrong/ damage to sb.", "type": "短语", "keyWords": ["do"] },
    { "chinese": "该做的事", "english": "do's/ dos", "type": "短语", "keyWords": ["do"] },
    { "chinese": "尽力", "english": "do one's best/ bit", "type": "短语", "keyWords": ["do"] },
    { "chinese": "处置；对待", "english": "do with", "type": "短语", "keyWords": ["do"] },
    { "chinese": "做得好；成绩好", "english": "do well in", "type": "短语", "keyWords": ["do"] },
    { "chinese": "同…有些/很有/没有关系", "english": "have something much/ nothing to do with", "type": "短语", "keyWords": ["do"] },
    { "chinese": "用不着；没有···也行", "english": "do without", "type": "短语", "keyWords": ["do"] },
    { "chinese": "我们不能没有知识，不是吗？", "english": "We can't do without knowledge, can we?", "type": "句子", "keyWords": ["do"] },
    { "chinese": "列出的能做和不能做的管理条例", "english": "a list of the dos and don'ts of management", "type": "短语", "keyWords": ["do"] },
    { "chinese": "n. (C) [美]码头，船坞", "english": "dock", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 医生；博士", "english": "doctor", "type": "单词", "keyWords": [] },
    { "chinese": "去诊所", "english": "go to the doctor's", "type": "短语", "keyWords": ["doctor"] },
    { "chinese": "n. (C) 文件；证件；v. 用文件（或文献等）证明；用纪实材料构成（影片、小说等）；纪实性地描述", "english": "document", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 纪录片；a. 文件的", "english": "documentary", "type": "单词", "keyWords": ["document"] },
    { "chinese": "n. (C) 狗", "english": "dog", "type": "单词", "keyWords": [] },
    { "chinese": "（书面）折角的；（书）翻旧了的", "english": "dog-eared", "type": "单词", "keyWords": ["dog"] },
    { "chinese": "过着牛马生活；过着永无宁日的悲惨生活", "english": "lead/ live a dog's life", "type": "短语", "keyWords": ["dog"] },
    { "chinese": "n. (C) 玩具娃娃", "english": "doll", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 元（美国、加拿大等国的货币单位）", "english": "dollar", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 海豚", "english": "dolphin", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 圆屋顶", "english": "dome", "type": "单词", "keyWords": [] },
    { "chinese": "a. 家庭的；驯养的；国内的", "english": "domestic", "type": "单词", "keyWords": [] },
    { "chinese": "国内经济/家庭经济", "english": "domestic economy", "type": "短语", "keyWords": ["domestic"] },
    { "chinese": "家畜", "english": "domestic animals", "type": "短语", "keyWords": ["domestic"] },
    { "chinese": "a. 占优势的；支配的", "english": "dominant", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 优势，统治(over)", "english": "dominance", "type": "单词", "keyWords": ["dominant"] },
    { "chinese": "v. 支配，控制；管辖，统治；操纵；vi. 处于支配地位，拥有优势", "english": "dominate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (pl. dominoes) 骨牌，多米诺骨牌", "english": "domino", "type": "单词", "keyWords": [] },
    { "chinese": "v. 捐赠", "english": "donate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)(C) 捐赠；捐赠品，捐款", "english": "donation", "type": "单词", "keyWords": ["donate"] },
    { "chinese": "n. (C) 捐赠者", "english": "donor", "type": "单词", "keyWords": ["donate"] },
    { "chinese": "n. (C) 驴；笨蛋，蠢驴", "english": "donkey", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 厄运，毁灭；v. 注定", "english": "doom", "type": "单词", "keyWords": [] },
    { "chinese": "注定/一定…", "english": "be doomed/ bound/ sure/certain to do sth.", "type": "短语", "keyWords": ["doom"] },
    { "chinese": "n. (C) 门", "english": "door", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 门口", "english": "doorway", "type": "单词", "keyWords": ["door"] },
    { "chinese": "n. (C)（放于门前的）擦鞋垫", "english": "doormat", "type": "单词", "keyWords": ["door"] },
    { "chinese": "挨家挨户", "english": "from door to door", "type": "短语", "keyWords": ["door"] },
    { "chinese": "在户外", "english": "out of doors", "type": "短语", "keyWords": ["door"] },
    { "chinese": "随手关门", "english": "close the door behind sb.", "type": "短语", "keyWords": ["door"] },
    { "chinese": "成功之道", "english": "a door to success", "type": "短语", "keyWords": ["door"] },
    { "chinese": "应门；去开门", "english": "answer the door", "type": "短语", "keyWords": ["door"] },
    { "chinese": "社会将他拒之门外。", "english": "Society shuts the door in his face.", "type": "句子", "keyWords": ["door"] },
    { "chinese": "n. (C) 集体宿舍；寝室", "english": "dormitory", "type": "单词", "keyWords": [] },
    { "chinese": "宿舍大楼", "english": "dormitory building", "type": "短语", "keyWords": ["dormitory"] },
    { "chinese": "n. (C) 点；v. 点缀", "english": "dot", "type": "单词", "keyWords": [] },
    { "chinese": "虚线", "english": "a dotted line", "type": "短语", "keyWords": ["dot"] },
    { "chinese": "星星点点布满船只的湖", "english": "a lake (which was) dotted with boats", "type": "短语", "keyWords": ["dot"] },
    { "chinese": "a. 两倍的；双重的；ad. 双倍地；v.（使）增一倍；n. (C) 两倍", "english": "double", "type": "单词", "keyWords": [] },
    { "chinese": "做双份工作", "english": "do double work", "type": "短语", "keyWords": ["double"] },
    { "chinese": "双人床", "english": "a double bed", "type": "短语", "keyWords": ["double"] },
    { "chinese": "10是5的双倍。", "english": "Ten is the double of five.", "type": "句子", "keyWords": ["double"] },
    { "chinese": "他的收入一年中增加了一倍多。", "english": "His income more than doubled in one year.", "type": "句子", "keyWords": ["double"] },
    { "chinese": "n. (C)(U) 怀疑；不相信；v.（不用被动语态）怀疑；不相信", "english": "doubt", "type": "单词", "keyWords": [] },
    { "chinese": "a. 怀疑的，可疑的，值得怀疑的", "english": "doubtful", "type": "单词", "keyWords": ["doubt"] },
    { "chinese": "大有/有几分可疑。", "english": "There is much/ some doubt.", "type": "句子", "keyWords": ["doubt"] },
    { "chinese": "他有没有这样做过，是大可怀疑（可以怀疑）的。", "english": "There is great doubt/ a doubt (as to) whether he did so or not.", "type": "句子", "keyWords": ["doubt"] },
    { "chinese": "毫无疑问地", "english": "no doubt → without/ beyond (any) doubt", "type": "短语", "keyWords": ["doubt"] },
    { "chinese": "毫无疑问他已经这样做过。", "english": "(There is) no doubt (that) he did so.", "type": "句子", "keyWords": ["doubt"] },
    { "chinese": "这无疑是困难的。", "english": "It is no doubt difficult.", "type": "句子", "keyWords": ["doubt"] },
    { "chinese": "对…怀疑", "english": "doubt about", "type": "短语", "keyWords": ["doubt"] },
    { "chinese": "n. (C) 炸面圈", "english": "doughnut", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 向下；在下；病倒；情绪低沉；prep. 沿着往下；沿着", "english": "down", "type": "单词", "keyWords": [] },
    { "chinese": "让人失望", "english": "let sb. down", "type": "短语", "keyWords": ["down"] },
    { "chinese": "由于··病倒了", "english": "be down with", "type": "短语", "keyWords": ["down"] },
    { "chinese": "颠倒；混乱", "english": "upside down", "type": "短语", "keyWords": ["down"] },
    { "chinese": "下跪", "english": "go/ get down on one's knees", "type": "短语", "keyWords": ["down"] },
    { "chinese": "上下地，到处，前前后后，来来往往", "english": "up and down", "type": "短语", "keyWords": ["down"] },
    { "chinese": "开始认真做...", "english": "get down to (sth/doing sth.)", "type": "短语", "keyWords": ["down"] },
    { "chinese": "v./n. (C)（计算机）下载", "english": "download", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 倾盆大雨", "english": "downpour", "type": "单词", "keyWords": [] },
    { "chinese": "（伦敦）唐宁街（英国首相官邸及若干政府主要部门所在地）", "english": "Downing Street", "type": "短语", "keyWords": [] },
    { "chinese": "a./ad. 往楼下（的）；在楼下（的）", "english": "downstairs", "type": "单词", "keyWords": [] },
    { "chinese": "a. 楼下的", "english": "downstair", "type": "单词", "keyWords": ["downstairs"] },
    { "chinese": "a. 商业区的；ad. 往市中心；在城市商业区", "english": "downtown", "type": "单词", "keyWords": [] },
    { "chinese": "城市商业区", "english": "the downtown (area)", "type": "短语", "keyWords": ["downtown"] },
    { "chinese": "ad. 向下", "english": "downward(s)", "type": "单词", "keyWords": [] },
    { "chinese": "a. 向下的", "english": "downward", "type": "单词", "keyWords": ["downward(s)"] },
    { "chinese": "v./n. (C) 打盹", "english": "doze", "type": "单词", "keyWords": [] },
    { "chinese": "在昏昏欲睡中度过下午", "english": "doze away the afternoon", "type": "短语", "keyWords": ["doze"] },
    { "chinese": "n. (pl. dozens) (C) 一打，十二个", "english": "dozen", "type": "单词", "keyWords": [] },
    { "chinese": "几打练习本", "english": "several dozen exercise-books", "type": "短语", "keyWords": ["dozen"] },
    { "chinese": "许多...", "english": "dozens of...", "type": "短语", "keyWords": ["dozen"] },
    { "chinese": "博士；医生（Doctor的缩略形式）", "english": "Dr.", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 草稿；草案；v. 起草", "english": "draft", "type": "单词", "keyWords": [] },
    { "chinese": "拟作文草稿", "english": "write out a draft for his essay", "type": "短语", "keyWords": ["draft"] },
    { "chinese": "草拟计划", "english": "draft out a plan", "type": "短语", "keyWords": ["draft"] },
    { "chinese": "vt.（费力、沉重或缓慢地）拖；沿表面拖动；慢吞吞地进行，拖沓地进行；vi. 疲惫地移动；n. (C) 拖拉", "english": "drag", "type": "单词", "keyWords": [] },
    { "chinese": "会议拖得很长。", "english": "The meeting dragged on.", "type": "句子", "keyWords": ["drag"] },
    { "chinese": "n. (C) 龙", "english": "dragon", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 耗竭(on)；消耗(on)；下水管道，排水沟；v.（使）慢慢排去，流掉；消耗", "english": "drain", "type": "单词", "keyWords": [] },
    { "chinese": "需要某人花钱", "english": "be a drain on one's money", "type": "短语", "keyWords": ["drain"] },
    { "chinese": "排去（水等液体）；（水等）流掉", "english": "drain away (the water)", "type": "短语", "keyWords": ["drain"] },
    { "chinese": "n. (C) 剧本；戏剧", "english": "drama", "type": "单词", "keyWords": [] },
    { "chinese": "a. 戏剧（性）的；给人深刻印象的", "english": "dramatic", "type": "单词", "keyWords": ["drama"] },
    { "chinese": "ad. 戏剧性地；鲜明地；显著地（上升、下降等）", "english": "dramatically", "type": "单词", "keyWords": ["dramatic"] },
    { "chinese": "v. 画；吸引；拉；拖；拔（牙）；提取（钱款）；n. (C) 平局，和局", "english": "draw", "type": "单词", "keyWords": [] },
    { "chinese": "从...取钱", "english": "draw money from...", "type": "短语", "keyWords": ["draw"] },
    { "chinese": "退却，缩回", "english": "draw back", "type": "短语", "keyWords": ["draw"] },
    { "chinese": "拉窗帘", "english": "draw the curtains", "type": "短语", "keyWords": ["draw"] },
    { "chinese": "抓阄", "english": "draw lots", "type": "短语", "keyWords": ["draw"] },
    { "chinese": "（汽车/节日）接近，临近（指空间、时间等）", "english": "(the car/festival) draw near", "type": "短语", "keyWords": ["draw"] },
    { "chinese": "引起警察的注意", "english": "draw the attention of the police", "type": "短语", "keyWords": ["draw"] },
    { "chinese": "把他向他父母拉近", "english": "draw him close to his parents", "type": "短语", "keyWords": ["draw"] },
    { "chinese": "从柜台下拔出一支枪", "english": "draw a gun from beneath the counter", "type": "短语", "keyWords": ["draw"] },
    { "chinese": "比赛以平局结束。", "english": "The game ended in a draw.", "type": "句子", "keyWords": ["draw"] },
    { "chinese": "n. (C) 抽屉", "english": "drawer", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 图画；素描画；(U) 素描术；绘图术", "english": "drawing", "type": "单词", "keyWords": ["draw"] },
    { "chinese": "a. 可怕的", "english": "dreadful", "type": "单词", "keyWords": [] },
    { "chinese": "v./vi./n. (C) 做梦；梦想", "english": "dream", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 做梦的人，梦想家", "english": "dreamer", "type": "单词", "keyWords": ["dream"] },
    { "chinese": "a. 梦一般的，朦胧的", "english": "dreamlike", "type": "单词", "keyWords": ["dream"] },
    { "chinese": "做了个甜蜜的梦", "english": "dream a sweet dream", "type": "短语", "keyWords": ["dream"] },
    { "chinese": "梦一般地过一辈子", "english": "live in a dream", "type": "短语", "keyWords": ["dream"] },
    { "chinese": "梦想；梦见", "english": "dream of/ about", "type": "短语", "keyWords": ["dream"] },
    { "chinese": "实现梦想", "english": "realize one's dream", "type": "短语", "keyWords": ["dream"] },
    { "chinese": "a. 梦幻般的；喜做白日梦的，爱空想的", "english": "dreamy", "type": "单词", "keyWords": ["dream"] },
    { "chinese": "n. (C) 白日梦；vi. 做白日梦", "english": "daydream", "type": "单词", "keyWords": ["dream"] },
    { "chinese": "n. (C) 女服，连衣裙；（外穿的）服装；礼服，盛装；v. 给...穿衣；整理；装饰", "english": "dress", "type": "单词", "keyWords": [] },
    { "chinese": "穿着...", "english": "be dressed in", "type": "短语", "keyWords": ["dress"] },
    { "chinese": "给伤口包扎", "english": "dress the wound", "type": "短语", "keyWords": ["dress"] },
    { "chinese": "n. (C) 更衣室，（尤指后台）化妆室", "english": "dressing room", "type": "单词", "keyWords": ["dress"] },
    { "chinese": "梳妆台", "english": "dressing table", "type": "短语", "keyWords": ["dress"] },
    { "chinese": "穿着盛装；化妆", "english": "dress up", "type": "短语", "keyWords": ["dress"] },
    { "chinese": "v./vi.（使）漂流；n. (U)(C) 漂流；无目的的游逛", "english": "drift", "type": "单词", "keyWords": [] },
    { "chinese": "v./vi. 钻（孔）；操练；n. (C)(U) 训练，操练；(C) 钻头", "english": "drill", "type": "单词", "keyWords": [] },
    { "chinese": "训练学生学习语法", "english": "drill pupils in grammar", "type": "短语", "keyWords": ["drill"] },
    { "chinese": "n. (C) 饮料；v. 喝，饮", "english": "drink", "type": "单词", "keyWords": [] },
    { "chinese": "a.（用作表语）喝醉了的", "english": "drunk", "type": "单词", "keyWords": ["drink"] },
    { "chinese": "a.（仅作定语）喝醉了的", "english": "drunken", "type": "单词", "keyWords": ["drink"] },
    { "chinese": "一口气喝完", "english": "drink up", "type": "短语", "keyWords": ["drink"] },
    { "chinese": "为··干杯", "english": "drink...to sb./sth.", "type": "短语", "keyWords": ["drink"] },
    { "chinese": "牛饮", "english": "drink like a fish", "type": "短语", "keyWords": ["drink"] },
    { "chinese": "饮用水", "english": "drinking water", "type": "短语", "keyWords": ["drink"] },
    { "chinese": "n. (C) 水滴；滴下的水；v.（使）滴下", "english": "drip", "type": "单词", "keyWords": [] },
    { "chinese": "v./vi. 开车；用车辆运输；驱使；迫使；驱动；驱赶；推动；n. (C) 驾车；驱车旅游；私人车道；紧迫；冲动；干劲；运动；驱动器；推进力", "english": "drive", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 司机，驾驶员", "english": "driver", "type": "单词", "keyWords": ["drive"] },
    { "chinese": "n. (C) 免下车餐馆/电影院等（顾客可坐在自己车上购物、进餐、看电影等）；a. 免下车的", "english": "drive-in", "type": "单词", "keyWords": ["drive"] },
    { "chinese": "使某人发疯", "english": "drive sb. mad", "type": "短语", "keyWords": ["drive"] },
    { "chinese": "把钉子敲进墙里", "english": "drive the nail into the wall", "type": "短语", "keyWords": ["drive"] },
    { "chinese": "逼某人做某事", "english": "drive sb. to do sth.", "type": "短语", "keyWords": ["drive"] },
    { "chinese": "贫困和饥饿逼得他们去偷窃。", "english": "Poverty and hunger drove them to steal.", "type": "句子", "keyWords": ["drive"] },
    { "chinese": "蒸汽驱动引擎。", "english": "Steam drives the engine.", "type": "句子", "keyWords": ["drive"] },
    { "chinese": "n. (C) 无人机", "english": "drone", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 滴；v./vi.（使）滴下；（有意或无意）（使）落下；（使价格等）下降", "english": "drop", "type": "单词", "keyWords": [] },
    { "chinese": "顺道访问某地", "english": "drop in at some place", "type": "短语", "keyWords": ["drop"] },
    { "chinese": "顺道拜访某人", "english": "drop in on sb.", "type": "短语", "keyWords": ["drop"] },
    { "chinese": "随时可以访问", "english": "drop by/ around any time", "type": "短语", "keyWords": ["drop"] },
    { "chinese": "物价的下跌", "english": "(a) drop in prices", "type": "短语", "keyWords": ["drop"] },
    { "chinese": "漏掉一个字母/省去一个字母", "english": "drop a letter", "type": "短语", "keyWords": ["drop"] },
    { "chinese": "滴眼剂，眼药水", "english": "eye drops", "type": "短语", "keyWords": ["drop"] },
    { "chinese": "退学；不参加；掉队", "english": "drop out (of high school)", "type": "短语", "keyWords": ["drop"] },
    { "chinese": "一滴又一滴", "english": "drop by drop", "type": "短语", "keyWords": ["drop"] },
    { "chinese": "写封短信给我/给我个提示", "english": "drop me a line/hint= drop a line/hint to me", "type": "短语", "keyWords": ["drop"] },
    { "chinese": "你能在车站放我下来吗？", "english": "Can you drop me at the station?", "type": "句子", "keyWords": ["drop"] },
    { "chinese": "n. (C) 旱灾", "english": "drought", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 溺水，淹死；v. 淹没；使淹死", "english": "drown", "type": "单词", "keyWords": [] },
    { "chinese": "被经过的火车淹没的尖叫声", "english": "screams that were drowned out by the passing train", "type": "短语", "keyWords": ["drown"] },
    { "chinese": "捞救命稻草。（在危难中）做毫无成功希望的努力。", "english": "A drowning man will catch at a straw.", "type": "句子", "keyWords": ["drown"] },
    { "chinese": "n. (C) 药物；麻醉品；毒品；v. 用药麻醉；吸毒", "english": "drug", "type": "单词", "keyWords": [] },
    { "chinese": "贩毒者", "english": "drug dealer", "type": "短语", "keyWords": ["drug"] },
    { "chinese": "n. (C) 药房；杂货店", "english": "drugstore", "type": "单词", "keyWords": ["drug"] },
    { "chinese": "n. (C) 鼓；鼓声", "english": "drum", "type": "单词", "keyWords": [] },
    { "chinese": "敲鼓", "english": "beat the drum", "type": "短语", "keyWords": ["drum"] },
    { "chinese": "v. 使变干；vi. 变干；a. 干的", "english": "dry", "type": "单词", "keyWords": [] },
    { "chinese": "河流已干涸。", "english": "The river has run dry.", "type": "句子", "keyWords": ["dry"] },
    { "chinese": "干起来容易", "english": "dry easily", "type": "短语", "keyWords": ["dry"] },
    { "chinese": "n. (C) 鸭；(U) 鸭肉", "english": "duck", "type": "单词", "keyWords": [] },
    { "chinese": "唐老鸭", "english": "Donald Duck", "type": "短语", "keyWords": ["duck"] },
    { "chinese": "a. 应得的；应给的；到期的；定于", "english": "due", "type": "单词", "keyWords": [] },
    { "chinese": "这张票据要到期了。", "english": "This note will fall/ become due.", "type": "句子", "keyWords": ["due"] },
    { "chinese": "他们的飞机预定在15分钟后到达。", "english": "Their plane is due in 15 minutes.", "type": "句子", "keyWords": ["due"] },
    { "chinese": "按约定玛丽4点到。", "english": "Mary is due (to arrive) here at 4.", "type": "句子", "keyWords": ["due"] },
    { "chinese": "由于；应属于", "english": "be due to", "type": "短语", "keyWords": ["due"] },
    { "chinese": "他的成功完全是他努力的结果。", "english": "His success is entirely due to his hard work.", "type": "句子", "keyWords": ["due"] },
    { "chinese": "这笔钱应该属于你。", "english": "The sum of the money is due to you.", "type": "句子", "keyWords": ["due"] },
    { "chinese": "vi./n. (C) 决斗", "english": "duel", "type": "单词", "keyWords": [] },
    { "chinese": "a. 乏味的；理解迟钝的；无趣的；呆滞的；（色彩）无光泽的，不鲜艳的", "english": "dull", "type": "单词", "keyWords": [] },
    { "chinese": "只工作不玩耍，聪明的孩子也变傻。", "english": "All work and no play makes Jack a dull boy.", "type": "句子", "keyWords": ["dull"] },
    { "chinese": "a. 哑的；不说话的，无声音的", "english": "dumb", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 倾倒（垃圾等）；（向国外）倾销；n. (C) 无秩序的一堆", "english": "dump", "type": "单词", "keyWords": [] },
    { "chinese": "垃圾场", "english": "a garbage dump", "type": "短语", "keyWords": ["dump"] },
    { "chinese": "n. (C) 汤团，团子；饺子", "english": "dumpling", "type": "单词", "keyWords": [] },
    { "chinese": "prep. 在...期间（注意不可以直接带that等宾语从句）", "english": "during", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 黄昏", "english": "dusk", "type": "单词", "keyWords": [] },
    { "chinese": "在黄昏时刻", "english": "at dusk", "type": "短语", "keyWords": ["dusk"] },
    { "chinese": "黄昏就要降临。", "english": "Dusk was falling.", "type": "句子", "keyWords": ["dusk"] },
    { "chinese": "n. (U) 灰尘，尘土；v. 掸掉...上的灰尘", "english": "dust", "type": "单词", "keyWords": [] },
    { "chinese": "a. 多尘的；灰尘覆盖的", "english": "dusty", "type": "单词", "keyWords": ["dust"] },
    { "chinese": "除去家具上的灰尘", "english": "dust the furniture", "type": "短语", "keyWords": ["dust"] },
    { "chinese": "n. (C) 垃圾箱", "english": "dustbin", "type": "单词", "keyWords": ["dust"] },
    { "chinese": "n. (C)（因地位、社会习惯、法律或宗教的需要而产生的）责任，义务；关税", "english": "duty", "type": "单词", "keyWords": [] },
    { "chinese": "尽职；尽本分", "english": "do/ perform one's duty", "type": "短语", "keyWords": ["duty"] },
    { "chinese": "（不）上班；（不）值班/勤", "english": "on/ off duty", "type": "短语", "keyWords": ["duty"] },
    { "chinese": "a. 免关税的", "english": "duty-free", "type": "单词", "keyWords": ["duty"] },
    { "chinese": "（机场等的）免税店", "english": "a duty-free shop", "type": "短语", "keyWords": ["duty-free"] },
    { "chinese": "v. 居住", "english": "dwell", "type": "单词", "keyWords": [] },
    { "chinese": "在伦敦居住10年", "english": "dwell in London for 10 years", "type": "短语", "keyWords": ["dwell"] },
    { "chinese": "n. (C) 矮子", "english": "dwarf", "type": "单词", "keyWords": [] },
    { "chinese": "vt./vi. (dyed, dyeing) 染，染色；n. (C) 染料，染色", "english": "dye", "type": "单词", "keyWords": [] },
    { "chinese": "把布染成红色", "english": "dye the cloth red", "type": "短语", "keyWords": ["dye"] },
    { "chinese": "把衬衫染成红色", "english": "have the shirt dyed red", "type": "短语", "keyWords": ["dye"] },
    { "chinese": "n. (U) 炸药", "english": "dynamite", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 朝代，王朝", "english": "dynasty", "type": "单词", "keyWords": [] },
    { "chinese": "a./pron. 各，各自，每个（指一定数目中的每一个，“个别”意义较重）；ad. 每个", "english": "each", "type": "单词", "keyWords": [] },
    { "chinese": "我们每个人赢了50美元。", "english": "Each of us has won $50. = We each have won $50.", "type": "句子", "keyWords": ["each"] },
    { "chinese": "互相；彼此", "english": "each other", "type": "短语", "keyWords": ["each"] },
    { "chinese": "a. 热切的；渴望的（表示浓厚的兴趣和迫不及待的期望）", "english": "eager", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 热切地", "english": "eagerly", "type": "单词", "keyWords": ["eager"] },
    { "chinese": "n. (U) 渴望", "english": "eagerness", "type": "单词", "keyWords": ["eager"] },
    { "chinese": "急于做某事", "english": "be eager/ anxious to do sth.", "type": "短语", "keyWords": ["eager"] },
    { "chinese": "渴望得到某物", "english": "be eager/ anxious/ hungry/ dying for sth.", "type": "短语", "keyWords": ["eager"] },
    { "chinese": "渴望那天的到来", "english": "look forward to the day with painful eagerness", "type": "短语", "keyWords": ["eagerness"] },
    { "chinese": "n. (C) 耳朵", "english": "ear", "type": "单词", "keyWords": [] },
    { "chinese": "一只耳朵进，一只耳朵出", "english": "go in (at) one ear and out (at) the other", "type": "短语", "keyWords": ["ear"] },
    { "chinese": "对....置若罔闻", "english": "turn a deaf ear to...", "type": "短语", "keyWords": ["ear"] },
    { "chinese": "（非正式用语）我们全神贯注地听/洗耳恭听。", "english": "We are all ears.", "type": "句子", "keyWords": ["ear"] },
    { "chinese": "隔墙有耳。", "english": "Walls have ears.", "type": "句子", "keyWords": ["ear"] },
    { "chinese": "a. 早的；早期的；远古的；ad. 在早期；早；从前", "english": "early", "type": "单词", "keyWords": [] },
    { "chinese": "早在9世纪", "english": "as early as the 9th century", "type": "短语", "keyWords": ["early"] },
    { "chinese": "早了一个月", "english": "a month earlier", "type": "短语", "keyWords": ["early"] },
    { "chinese": "在某人的早年", "english": "in one's early years", "type": "短语", "keyWords": ["early"] },
    { "chinese": "早起的鸟儿有虫吃。捷足先登。", "english": "The early bird catches the worm.", "type": "句子", "keyWords": ["early"] },
    { "chinese": "v. 赚；（通过努力、贡献）挣得；获得", "english": "earn", "type": "单词", "keyWords": [] },
    { "chinese": "n. (pl.) 收入；收益；赚得的钱", "english": "earnings", "type": "单词", "keyWords": ["earn"] },
    { "chinese": "以写作/做…谋生", "english": "earn one's living as a writer/ by doing sth.", "type": "短语", "keyWords": ["earn"] },
    { "chinese": "赢得名望", "english": "earn sb. fame", "type": "短语", "keyWords": ["earn"] },
    { "chinese": "他的成绩使他赢得了声誉。", "english": "His achievement earned him fame.", "type": "句子", "keyWords": ["earn"] },
    { "chinese": "a. 认真的，热切的，诚挚的", "english": "earnest", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 认真地，诚挚地", "english": "earnestly", "type": "单词", "keyWords": ["earnest"] },
    { "chinese": "n. (U) 认真，诚挚", "english": "earnestness", "type": "单词", "keyWords": ["earnest"] },
    { "chinese": "n. (the) 地球；(U) 土地，泥土；陆地；vt. 用土掩盖(up)", "english": "earth", "type": "单词", "keyWords": [] },
    { "chinese": "世界上；究竟，到底；一点儿也（强调否定）", "english": "on earth", "type": "短语", "keyWords": ["earth"] },
    { "chinese": "你究竟为什么要说谎？", "english": "Why on earth did you tell a lie?", "type": "句子", "keyWords": ["earth"] },
    { "chinese": "在地球上", "english": "on the earth", "type": "短语", "keyWords": ["earth"] },
    { "chinese": "用土把根埋起来", "english": "earth up the roots", "type": "短语", "keyWords": ["earth"] },
    { "chinese": "n. (C) 地震", "english": "earthquake", "type": "单词", "keyWords": ["earth"] },
    { "chinese": "n. (U) 容易，不费力；安逸，悠闲；安详；v. 减轻/解除··的痛苦或负担等；使平静", "english": "ease", "type": "单词", "keyWords": [] },
    { "chinese": "感到/显得心安理得", "english": "feel/ appear at ease", "type": "短语", "keyWords": ["ease"] },
    { "chinese": "熟练地，轻而易举地", "english": "with ease", "type": "短语", "keyWords": ["ease"] },
    { "chinese": "缓解局势/困难/冲突/化解他们的烦心事", "english": "ease the situation/ difficulties/ conflict/ their troubled minds", "type": "短语", "keyWords": ["ease"] },
    { "chinese": "解除他的痛苦", "english": "ease him of his pain", "type": "短语", "keyWords": ["ease"] },
    { "chinese": "a. 容易的；舒服的，安逸的；从容的；随和的", "english": "easy", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 容易地；舒适地", "english": "easily", "type": "单词", "keyWords": [] },
    { "chinese": "别紧张；放轻松", "english": "take it easy/ take things easy", "type": "短语", "keyWords": ["easy"] },
    { "chinese": "说时容易做时难。/知易行难。", "english": "(It's) easier said than done.", "type": "句子", "keyWords": ["easy"] },
    { "chinese": "（人）容易接近；（物）容易得到；（地方）交通方便", "english": "easy of access", "type": "短语", "keyWords": ["easy"] },
    { "chinese": "a. 随和的", "english": "easy-going", "type": "单词", "keyWords": [] },
    { "chinese": "他为人很随和。", "english": "He is easy-going with people.", "type": "句子", "keyWords": ["easy-going"] },
    { "chinese": "非常容易，轻而易举，非常简单", "english": "be as easy as ABC", "type": "短语", "keyWords": ["easy"] },
    { "chinese": "[口]慢慢来；小心点", "english": "Easy does it.", "type": "句子", "keyWords": ["easy"] },
    { "chinese": "来得容易去得快；易得易失。", "english": "Easy come, easy go.", "type": "句子", "keyWords": ["easy"] },
    { "chinese": "n. (the) 东；东方", "english": "east", "type": "单词", "keyWords": [] },
    { "chinese": "a. 东方的；从东面来的；朝东的", "english": "east a.", "type": "短语", "keyWords": ["east"] },
    { "chinese": "ad. 在东方，向东方，朝东方", "english": "east ad.", "type": "短语", "keyWords": ["east"] },
    { "chinese": "从东到西", "english": "from east to west", "type": "短语", "keyWords": ["east"] },
    { "chinese": "远/中/近东", "english": "the Far/ Middle/ Near East", "type": "短语", "keyWords": ["east"] },
    { "chinese": "东方", "english": "the East", "type": "短语", "keyWords": ["east"] },
    { "chinese": "向东走", "english": "go east (ad.)= go to the east (n.)", "type": "短语", "keyWords": ["east"] },
    { "chinese": "来自东边太平洋", "english": "from the Pacific on the east", "type": "短语", "keyWords": ["east"] },
    { "chinese": "...之东", "english": "to the east of...", "type": "短语", "keyWords": ["east"] },
    { "chinese": "位于南京以东15千米", "english": "lie 15km (to the) east of Nanjing", "type": "短语", "keyWords": ["east"] },
    { "chinese": "n. 复活节", "english": "Easter", "type": "单词", "keyWords": [] },
    { "chinese": "在复活节", "english": "at Easter", "type": "短语", "keyWords": ["Easter"] },
    { "chinese": "a. 东部的", "english": "eastern", "type": "单词", "keyWords": [] },
    { "chinese": "a./ad. 向东方，朝东面", "english": "eastward", "type": "单词", "keyWords": [] },
    { "chinese": "v. 吃；侵蚀；毁坏", "english": "eat", "type": "单词", "keyWords": [] },
    { "chinese": "上馆子吃饭", "english": "eat/dine out", "type": "短语", "keyWords": ["eat"] },
    { "chinese": "n. [C] 电子书籍", "english": "e-book", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (pl. echoes) 回声，回音；回波", "english": "echo", "type": "单词", "keyWords": [] },
    { "chinese": "v. 发回声；随声附和", "english": "echo v.", "type": "短语", "keyWords": ["echo"] },
    { "chinese": "表示“环境、生态、生态学的”", "english": "eco-", "type": "前缀", "keyWords": [] },
    { "chinese": "n. (U) 生态学", "english": "ecology", "type": "单词", "keyWords": ["eco-"] },
    { "chinese": "a. 生态的；环保的；生态学的", "english": "ecological", "type": "单词", "keyWords": ["eco-"] },
    { "chinese": "a. 经济（上）的；经济学的", "english": "economic", "type": "单词", "keyWords": [] },
    { "chinese": "经济危机", "english": "an economic crisis", "type": "短语", "keyWords": ["economic"] },
    { "chinese": "n. (U) 经济学", "english": "economics", "type": "单词", "keyWords": [] },
    { "chinese": "a. 节约的，节俭的", "english": "economical", "type": "单词", "keyWords": [] },
    { "chinese": "经济情况；(C) （某国）经济；经济制度；n. (C) 节约（措施），经济（舱等）", "english": "economy", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 节约，节省", "english": "economize", "type": "单词", "keyWords": [] },
    { "chinese": "节约电和燃料", "english": "economize on electricity and fuel", "type": "短语", "keyWords": ["economize"] },
    { "chinese": "（客机之）经济舱位，二等舱位", "english": "economy class", "type": "短语", "keyWords": ["economy"] },
    { "chinese": "n. (C) 生态系统", "english": "ecosystem", "type": "单词", "keyWords": ["eco-"] },
    { "chinese": "n. (C) 边缘；刀口，利刃，锋；优势", "english": "edge", "type": "单词", "keyWords": [] },
    { "chinese": "在死亡的边缘", "english": "on the edge of death", "type": "短语", "keyWords": ["edge"] },
    { "chinese": "a. 可食用的", "english": "edible", "type": "单词", "keyWords": [] },
    { "chinese": "燕窝", "english": "edible bird's nest", "type": "短语", "keyWords": ["edible"] },
    { "chinese": "海带", "english": "edible seaweeds", "type": "短语", "keyWords": ["edible"] },
    { "chinese": "vt. 编辑；修改；删除，删节", "english": "edit", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 版本；版（次）", "english": "edition", "type": "单词", "keyWords": [] },
    { "chinese": "廉价本", "english": "a cheap edition", "type": "短语", "keyWords": ["edition"] },
    { "chinese": "n. (C) 编辑，编者", "english": "editor", "type": "单词", "keyWords": [] },
    { "chinese": "主编；总编辑", "english": "a chief editor/ an editor-in-chief", "type": "短语", "keyWords": ["editor"] },
    { "chinese": "a. 编辑的；社论的", "english": "editorial", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 社论", "english": "editorial n.", "type": "短语", "keyWords": ["editorial"] },
    { "chinese": "vt. 教育；培养；训练", "english": "educate", "type": "单词", "keyWords": [] },
    { "chinese": "教育某人做某事", "english": "educate sb. to do sth.", "type": "短语", "keyWords": ["educate"] },
    { "chinese": "a. 受过教育的，有教养的", "english": "educated", "type": "单词", "keyWords": [] },
    { "chinese": "受过良好教育的人", "english": "well-educated people", "type": "短语", "keyWords": ["educated"] },
    { "chinese": "n. (C) 教育家", "english": "educator", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 教育", "english": "education", "type": "单词", "keyWords": [] },
    { "chinese": "一个受过教育的人", "english": "a man of education", "type": "短语", "keyWords": ["education"] },
    { "chinese": "接受良好的教育（表示接受一段时间或某种教育）", "english": "have/ receive a good education", "type": "短语", "keyWords": ["education"] },
    { "chinese": "n. (C) (U) 效果；效力；作用；结果；影响", "english": "effect", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有效的；生效的", "english": "effective", "type": "单词", "keyWords": ["effect"] },
    { "chinese": "n. (U) 有效", "english": "effectiveness", "type": "单词", "keyWords": ["effect"] },
    { "chinese": "对某人无效", "english": "(be) of no effect to sb.", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "开始生效；开始实行", "english": "come into effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "对...有影响", "english": "have (an) effect/ impact on", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "开始实行；开始生效", "english": "take effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "无副作用", "english": "without any side effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "实行，实施；使生效", "english": "put/ bring...into effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "（规律、法律等）生效，有效；在实行中", "english": "be in effect", "type": "短语", "keyWords": ["effect"] },
    { "chinese": "采取有效措施", "english": "take effective measures", "type": "短语", "keyWords": ["effective"] },
    { "chinese": "药很快见效了。", "english": "The medicine quickly took effect.", "type": "句子", "keyWords": ["effect"] },
    { "chinese": "a. 高效的；有能力的", "english": "efficient", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 高效", "english": "efficiency", "type": "单词", "keyWords": ["efficient"] },
    { "chinese": "工作效率高", "english": "be efficient in one's work", "type": "短语", "keyWords": ["efficient"] },
    { "chinese": "n. (C) (U) 努力", "english": "effort", "type": "单词", "keyWords": [] },
    { "chinese": "努力做", "english": "make an effort/ every effort to do sth.", "type": "短语", "keyWords": ["effort"] },
    { "chinese": "毫不费力", "english": "without effort", "type": "短语", "keyWords": ["effort"] },
    { "chinese": "不遗余力，极力", "english": "spare no effort to do sth.", "type": "短语", "keyWords": ["effort"] },
    { "chinese": "例如（同for example）", "english": "e.g. (exempli gratia)", "type": "短语", "keyWords": [] },
    { "chinese": "n. (C) （鸟类的）蛋；鸡蛋；（鱼、昆虫等的）卵", "english": "egg", "type": "单词", "keyWords": [] },
    { "chinese": "茄子", "english": "eggplant", "type": "单词", "keyWords": ["egg"] },
    { "chinese": "下蛋", "english": "lay eggs", "type": "短语", "keyWords": ["egg"] },
    { "chinese": "杀鸡取卵；因贪得无厌而坏事", "english": "kill the goose that laid the golden eggs", "type": "短语", "keyWords": ["egg"] },
    { "chinese": "n. 埃及", "english": "Egypt", "type": "单词", "keyWords": [] },
    { "chinese": "a. 埃及的，埃及人的", "english": "Egyptian", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 埃及人", "english": "Egyptian n.", "type": "短语", "keyWords": ["Egyptian"] },
    { "chinese": "interj. 啊；嗯", "english": "eh", "type": "单词", "keyWords": [] },
    { "chinese": "num. 八", "english": "eight", "type": "单词", "keyWords": [] },
    { "chinese": "第八；八分之一", "english": "eighth", "type": "单词", "keyWords": [] },
    { "chinese": "第十八；十八分之一", "english": "eighteenth", "type": "单词", "keyWords": [] },
    { "chinese": "第八十；八十分之一", "english": "eightieth", "type": "单词", "keyWords": [] },
    { "chinese": "n. 爱因斯坦", "english": "Einstein", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 也（用于否定句或否定词组后加强语气）", "english": "either", "type": "单词", "keyWords": [] },
    { "chinese": "a. （两者之中的）任一的", "english": "either a.", "type": "短语", "keyWords": ["either"] },
    { "chinese": "pron. 两者中任一者", "english": "either pron.", "type": "短语", "keyWords": ["either"] },
    { "chinese": "在街道两旁", "english": "on either side/ both sides of the street", "type": "短语", "keyWords": ["either"] },
    { "chinese": "不是...就是...；或者...或者...", "english": "either...or...", "type": "短语", "keyWords": ["either"] },
    { "chinese": "你爸来还是你来？", "english": "Is either your father or you coming?", "type": "句子", "keyWords": ["either"] },
    { "chinese": "v. （时间）过去，消逝", "english": "elapse", "type": "单词", "keyWords": [] },
    { "chinese": "a. 弹性的；有弹性的", "english": "elastic", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 肘", "english": "elbow", "type": "单词", "keyWords": [] },
    { "chinese": "a. 年龄较大的；年长的", "english": "elder", "type": "单词", "keyWords": [] },
    { "chinese": "哥哥", "english": "elder brother", "type": "短语", "keyWords": ["elder"] },
    { "chinese": "a. 过了中年的，年老的；晚年的", "english": "elderly", "type": "单词", "keyWords": [] },
    { "chinese": "老年人", "english": "the elderly", "type": "短语", "keyWords": ["elderly"] },
    { "chinese": "v. 选举", "english": "elect", "type": "单词", "keyWords": [] },
    { "chinese": "选举某人当...", "english": "elect sb. to be sth.", "type": "短语", "keyWords": ["elect"] },
    { "chinese": "里根被选为美国第四十任总统。", "english": "Reagan was elected (as) the fortieth President of the United States.", "type": "句子", "keyWords": ["elect"] },
    { "chinese": "n. (C) 选举", "english": "election", "type": "单词", "keyWords": [] },
    { "chinese": "大选，普选", "english": "a general election", "type": "短语", "keyWords": ["election"] },
    { "chinese": "a. 电的（由电操纵的或由电产生的）", "english": "electric", "type": "单词", "keyWords": [] },
    { "chinese": "电流", "english": "electric current", "type": "短语", "keyWords": ["electric"] },
    { "chinese": "电灯", "english": "electric lights", "type": "短语", "keyWords": ["electric"] },
    { "chinese": "电击/触电", "english": "electric shock", "type": "短语", "keyWords": ["electric"] },
    { "chinese": "a. 电的；与（用）电有关的；电气的", "english": "electrical", "type": "单词", "keyWords": [] }
];
