const qgl91_105 = [
    { "chinese": "电气工程师", "english": "an electrical engineer", "type": "短语", "keyWords": ["electrical"] },
    { "chinese": "电路故障", "english": "electrical fault", "type": "短语", "keyWords": ["electrical"] },
    { "chinese": "n. (C) 电机师，电机技术员；电气专家；电工", "english": "electrician", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 电", "english": "electricity", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 电子", "english": "electron", "type": "单词", "keyWords": [] },
    { "chinese": "a. 电子的", "english": "electronic", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 电子学", "english": "electronics", "type": "单词", "keyWords": [] },
    { "chinese": "a. （举止、服饰等）优美的，文雅的；（文体、语言等）典雅的", "english": "elegant", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) （可和不定冠词连用）优美，文雅；（文体、语言等）典雅", "english": "elegance", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 成分；元素；要素", "english": "element", "type": "单词", "keyWords": [] },
    { "chinese": "基本元素", "english": "simple or basic element", "type": "短语", "keyWords": ["element"] },
    { "chinese": "a. 初级的；基本的", "english": "elementary", "type": "单词", "keyWords": [] },
    { "chinese": "小学", "english": "elementary school", "type": "短语", "keyWords": ["elementary"] },
    { "chinese": "n. (C) 大象", "english": "elephant", "type": "单词", "keyWords": [] },
    { "chinese": "v. 举起；提拔；振奋", "english": "elevate", "type": "单词", "keyWords": [] },
    { "chinese": "高架路", "english": "elevated highway", "type": "短语", "keyWords": ["elevate"] },
    { "chinese": "n. (C) 电梯", "english": "elevator", "type": "单词", "keyWords": [] },
    { "chinese": "v. 消除，根除；排除；淘汰", "english": "eliminate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 淘汰；淘汰赛；除", "english": "elimination", "type": "单词", "keyWords": [] },
    { "chinese": "a./ad. 其他的；别的（常用于who, someone, somewhere等疑问代词或不定代词之后）", "english": "else", "type": "单词", "keyWords": [] },
    { "chinese": "别的什么东西/人", "english": "anything/ someone else", "type": "短语", "keyWords": ["else"] },
    { "chinese": "别的什么人/其他什么地方", "english": "who/ where else", "type": "短语", "keyWords": ["else"] },
    { "chinese": "这究竟是谁的书？", "english": "Who else's book is it?", "type": "句子", "keyWords": ["else"] },
    { "chinese": "否则；要不", "english": "or else", "type": "短语", "keyWords": ["else"] },
    { "chinese": "你必须付一万元，否则就得去坐牢。", "english": "You must pay ¥10,000 or else go to prison.", "type": "句子", "keyWords": ["else"] },
    { "chinese": "ad. 在别处；到别处", "english": "elsewhere", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 电子邮件", "english": "email", "type": "单词", "keyWords": [] },
    { "chinese": "给...发电子邮件", "english": "email vt.", "type": "短语", "keyWords": ["email"] },
    { "chinese": "v. 使局促不安；使为难，使尴尬", "english": "embarrass", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 困窘，难堪", "english": "embarrassment", "type": "单词", "keyWords": [] },
    { "chinese": "使人/感到难堪的", "english": "embarrassing/ embarrassed", "type": "短语", "keyWords": ["embarrass"] },
    { "chinese": "n. (C) 大使馆", "english": "embassy", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 大使，使节", "english": "ambassador", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 显现，浮现；（问题等）暴露", "english": "emerge", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 浮现，露出；出现", "english": "emergence", "type": "单词", "keyWords": [] },
    { "chinese": "船从雾里露了出来。", "english": "The ship emerged from behind the fog.", "type": "句子", "keyWords": ["emerge"] },
    { "chinese": "a. 紧急的；突然出现的", "english": "emergent", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 急诊；紧急情况", "english": "emergency", "type": "单词", "keyWords": [] },
    { "chinese": "紧急会议", "english": "emergency meeting", "type": "短语", "keyWords": ["emergency"] },
    { "chinese": "应急出口", "english": "emergency exit", "type": "短语", "keyWords": ["emergency"] },
    { "chinese": "急救室", "english": "emergency room", "type": "短语", "keyWords": ["emergency"] },
    { "chinese": "在紧急情况下", "english": "in an emergency/ in case of emergency", "type": "短语", "keyWords": ["emergency"] },
    { "chinese": "vt./vi. （使）永久移居国外", "english": "emigrate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 移居国外", "english": "emigration", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 移居外国者；移民", "english": "emigrant", "type": "单词", "keyWords": [] },
    { "chinese": "v. 发出，射出，散发（光、热、电波、声音、液体、气味等）", "english": "emit", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) (C) 发出，射出，散发；(C) 散发（或发射）物", "english": "emission", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 情感；激动", "english": "emotion", "type": "单词", "keyWords": [] },
    { "chinese": "a. 感情的；易动感情的", "english": "emotional", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 激动地；情绪化地", "english": "emotionally", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 皇帝；（帝国的）君主", "english": "emperor", "type": "单词", "keyWords": [] },
    { "chinese": "n. (pl. emphases) (C) (U) 强调，着重；重点", "english": "emphasis", "type": "单词", "keyWords": [] },
    { "chinese": "着重于", "english": "place/ put/ lay emphasis on (doing) sth.", "type": "短语", "keyWords": ["emphasis"] },
    { "chinese": "v. 强调，着重；加强...的语气", "english": "emphasize", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 帝国", "english": "empire", "type": "单词", "keyWords": [] },
    { "chinese": "v. 雇用；采/利/使用", "english": "employ", "type": "单词", "keyWords": [] },
    { "chinese": "你们为何不采用那个新方法？", "english": "Why didn't you employ the new method?", "type": "句子", "keyWords": ["employ"] },
    { "chinese": "n. (C) 雇员", "english": "employee", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 雇主", "english": "employer", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 雇用；就业；受雇", "english": "employment", "type": "单词", "keyWords": [] },
    { "chinese": "就业", "english": "get employment", "type": "短语", "keyWords": ["employment"] },
    { "chinese": "失业", "english": "be out of employment", "type": "短语", "keyWords": ["employment"] },
    { "chinese": "a. 空的；空洞的；空虚的", "english": "empty", "type": "单词", "keyWords": [] },
    { "chinese": "倒空；使空；成为空的；使排出；流出", "english": "empty v.", "type": "短语", "keyWords": ["empty"] },
    { "chinese": "空话/空洞的诺言", "english": "empty words/ promises", "type": "短语", "keyWords": ["empty"] },
    { "chinese": "流向大海", "english": "empty (itself) into the sea", "type": "短语", "keyWords": ["empty"] },
    { "chinese": "倒空口袋/盒子", "english": "empty out the pocket/ the boxes", "type": "短语", "keyWords": ["empty"] },
    { "chinese": "v. 使能够", "english": "enable", "type": "单词", "keyWords": [] },
    { "chinese": "使某人能够做某事", "english": "enable sb. to do sth.", "type": "短语", "keyWords": ["enable"] },
    { "chinese": "v. 把...包（围）在里面；围住，包住；把..装入信封，随信寄；封入，附入；装有", "english": "enclose", "type": "单词", "keyWords": [] },
    { "chinese": "随函附上", "english": "enclose sth. with the letter", "type": "短语", "keyWords": ["enclose"] },
    { "chinese": "在一个密闭的空间里", "english": "in an enclosed space", "type": "短语", "keyWords": ["enclose"] },
    { "chinese": "n. 围场；围栏；（信中）附件，装入物", "english": "enclosure", "type": "单词", "keyWords": [] },
    { "chinese": "v./n. (C) 遭遇，遇到；意外遇见；与..邂逅", "english": "encounter", "type": "单词", "keyWords": [] },
    { "chinese": "v. 鼓励，激励", "english": "encourage", "type": "单词", "keyWords": [] },
    { "chinese": "鼓励做...", "english": "encourage doing sth.", "type": "短语", "keyWords": ["encourage"] },
    { "chinese": "鼓励某人做某事", "english": "encourage sb. to do sth.", "type": "短语", "keyWords": ["encourage"] },
    { "chinese": "n. (U) 鼓励，激励", "english": "encouragement", "type": "单词", "keyWords": [] },
    { "chinese": "使人/感到激励的", "english": "encouraging/ encouraged", "type": "短语", "keyWords": ["encourage"] },
    { "chinese": "n. (C) 百科全书", "english": "encyclop(a)edia", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 结束；末尾，尽头；末日", "english": "end", "type": "单词", "keyWords": [] },
    { "chinese": "v. 结束；终止", "english": "end v.", "type": "短语", "keyWords": ["end"] },
    { "chinese": "在...尽头/末尾", "english": "at the end of", "type": "短语", "keyWords": ["end"] },
    { "chinese": "把...结束", "english": "bring ... to an end", "type": "短语", "keyWords": ["end"] },
    { "chinese": "最后", "english": "in the end", "type": "短语", "keyWords": ["end"] },
    { "chinese": "从头至尾", "english": "from beginning to end", "type": "短语", "keyWords": ["end"] },
    { "chinese": "结束", "english": "come to an end", "type": "短语", "keyWords": ["end"] },
    { "chinese": "使收支平衡", "english": "make (both) ends meet", "type": "短语", "keyWords": ["end"] },
    { "chinese": "使终结，使结束", "english": "put an end to (sth.)", "type": "短语", "keyWords": ["end"] },
    { "chinese": "我决心要制止所有这些谣言。", "english": "I am determined to put an end to all these rumours.", "type": "句子", "keyWords": ["end"] },
    { "chinese": "以...告终/结束", "english": "end in sth.", "type": "短语", "keyWords": ["end"] },
    { "chinese": "以平局告终", "english": "end in a draw", "type": "短语", "keyWords": ["end"] },
    { "chinese": "结果打了起来", "english": "end in a fight", "type": "短语", "keyWords": ["end"] },
    { "chinese": "以...告终/结束", "english": "end up (with sth./ by doing sth.)", "type": "短语", "keyWords": ["end"] },
    { "chinese": "最后蹲了监狱", "english": "end up in prison", "type": "短语", "keyWords": ["end"] },
    { "chinese": "结果成了医生", "english": "end up as a doctor", "type": "短语", "keyWords": ["end"] },
    { "chinese": "以死亡告终", "english": "end up dead", "type": "短语", "keyWords": ["end"] },
    { "chinese": "在歌声中结束", "english": "end up with a song", "type": "短语", "keyWords": ["end"] },
    { "chinese": "我们一开始不喜欢它，但我们最后却为之欢呼。", "english": "We didn't like it at first, but we ended up cheering.", "type": "句子", "keyWords": ["end"] },
    { "chinese": "过分耗费精力", "english": "burn the candle at both ends", "type": "短语", "keyWords": ["end"] },
    { "chinese": "n. (C) （故事等）结尾（结局）", "english": "ending", "type": "单词", "keyWords": [] },
    { "chinese": "a. 无限的，无穷的；无止境的", "english": "endless", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 不断地，无穷尽地", "english": "endlessly", "type": "单词", "keyWords": [] },
    { "chinese": "v. 忍受，忍耐（指“忍受较长期、较严重的痛苦、困难等的能力”）；vi. 持久；持续；忍受，忍耐", "english": "endure", "type": "单词", "keyWords": [] },
    { "chinese": "忍受痛苦/苦难/艰苦", "english": "endure pain/suffering/hardship", "type": "短语", "keyWords": ["endure"] },
    { "chinese": "忍无可忍", "english": "beyond endurance", "type": "短语", "keyWords": ["endure"] },
    { "chinese": "a. 持久的，不朽的", "english": "enduring", "type": "单词", "keyWords": [] },
    { "chinese": "持久和平", "english": "an enduring peace", "type": "短语", "keyWords": ["enduring"] },
    { "chinese": "n. (U) 持久（力）；耐久（性）；忍耐（力）", "english": "endurance", "type": "单词", "keyWords": [] },
    { "chinese": "a. 可忍受的，能忍耐的", "english": "endurable", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 敌人；（用作单或复）仇敌（集合名词）", "english": "enemy", "type": "单词", "keyWords": [] },
    { "chinese": "a. 精力充沛的", "english": "energetic", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 精力充沛地", "english": "energetically", "type": "单词", "keyWords": [] },
    { "chinese": "v. 供给...能量；使有活力", "english": "energize", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)C 能量；活力；精力（有时用复数）", "english": "energy", "type": "单词", "keyWords": [] },
    { "chinese": "精力充沛", "english": "be full of energy", "type": "短语", "keyWords": ["energy"] },
    { "chinese": "vi./vt. （使）忙碌，（使）从事于，（使）参加；vt. 使订婚；雇，聘；吸引；占用（时间、精力等）", "english": "engage", "type": "单词", "keyWords": [] },
    { "chinese": "从事，参加", "english": "engage in (doing) sth.", "type": "短语", "keyWords": ["engage"] },
    { "chinese": "乔治很快便参与到运动中。", "english": "George soon engaged in the sport.", "type": "句子", "keyWords": ["engage"] },
    { "chinese": "忙着做某事", "english": "be engaged in sth.", "type": "短语", "keyWords": ["engage"] },
    { "chinese": "他正忙着写作业。", "english": "He is engaged in his homework just now.", "type": "句子", "keyWords": ["engage"] },
    { "chinese": "和某人订婚", "english": "be engaged to sb.", "type": "短语", "keyWords": ["engage"] },
    { "chinese": "汤姆已与安妮订婚。", "english": "Tom is engaged to Anne.", "type": "句子", "keyWords": ["engage"] },
    { "chinese": "占线。/线路忙。", "english": "The line is engaged.", "type": "句子", "keyWords": ["engage"] },
    { "chinese": "n. (U) 参与；(C) 订婚；约会", "english": "engagement", "type": "单词", "keyWords": [] },
    { "chinese": "a. 已订婚的；占线；在使用中", "english": "engaged", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 引擎；发动机", "english": "engine", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 工程师；技师", "english": "engineer", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 工程学", "english": "engineering", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 英格兰；英国", "english": "England", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 英语", "english": "English", "type": "单词", "keyWords": [] },
    { "chinese": "a. 英文的；英国人的；英格兰的", "english": "English a.", "type": "短语", "keyWords": ["English"] },
    { "chinese": "英语晚会", "english": "English Evening", "type": "短语", "keyWords": ["English"] },
    { "chinese": "（总称）英吉利人；英国人；英军", "english": "the English", "type": "短语", "keyWords": ["English"] },
    { "chinese": "n. (C) 英格兰男/女人", "english": "Englishman/ Englishwoman", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 增强；增加（在价值、美、声望上增强）", "english": "enhance", "type": "单词", "keyWords": [] },
    { "chinese": "v. 喜欢，喜爱；享受...乐趣；欣赏", "english": "enjoy", "type": "单词", "keyWords": [] },
    { "chinese": "喜欢做某事", "english": "enjoy doing sth.", "type": "短语", "keyWords": ["enjoy"] },
    { "chinese": "过得快乐", "english": "enjoy oneself", "type": "短语", "keyWords": ["enjoy"] },
    { "chinese": "n. (U) 享乐", "english": "enjoyment", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有乐趣的；令人快乐的", "english": "enjoyable", "type": "单词", "keyWords": [] },
    { "chinese": "令人愉快的夜晚", "english": "an enjoyable evening", "type": "短语", "keyWords": ["enjoyable"] },
    { "chinese": "vt. 扩大", "english": "enlarge", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 扩大", "english": "enlargement", "type": "单词", "keyWords": [] },
    { "chinese": "a. 巨大的", "english": "enormous", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 巨大；暴行", "english": "enormity", "type": "单词", "keyWords": [] },
    { "chinese": "a./pron./ad. 足够", "english": "enough", "type": "单词", "keyWords": [] },
    { "chinese": "够了！", "english": "enough interj.", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "太多", "english": "more than enough", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "够了！不要再说了！", "english": "Enough of that!", "type": "句子", "keyWords": ["enough"] },
    { "chinese": "适可而止。", "english": "Enough is enough.", "type": "句子", "keyWords": ["enough"] },
    { "chinese": "果真，果然；的的确确", "english": "sure enough", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "足够的...来做", "english": "a./adv.+enough to do sth.", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "无论怎样…都不够", "english": "cannot...enough", "type": "短语", "keyWords": ["enough"] },
    { "chinese": "我对你感恩不尽。", "english": "I cannot thank you enough.", "type": "句子", "keyWords": ["enough"] },
    { "chinese": "对于你的无礼/那些废话，我已经受够了。", "english": "I have had enough of your rudeness/ the nonsense.", "type": "句子", "keyWords": ["enough"] },
    { "chinese": "v. 招（生）；吸收（成员）；vi. 入学；参加", "english": "enrol(l)", "type": "单词", "keyWords": [] },
    { "chinese": "把他吸收为俱乐部成员", "english": "enroll (vt.) him as a member of the club", "type": "短语", "keyWords": ["enrol(l)"] },
    { "chinese": "在大学注册上英语课", "english": "enroll (vi.) for English classes at college", "type": "短语", "keyWords": ["enrol(l)"] },
    { "chinese": "n. (U) 登记，入学；(C) 注册人数", "english": "enrolment", "type": "单词", "keyWords": [] },
    { "chinese": "v. 保证；担保，确保；使安全；保证得到", "english": "ensure", "type": "单词", "keyWords": [] },
    { "chinese": "我们可以保证把工作做好。", "english": "We can ensure that the work shall be done in the right way.", "type": "句子", "keyWords": ["ensure"] },
    { "chinese": "凭一封介绍信准保会接待你。", "english": "A letter of introduction will ensure you an interview.", "type": "句子", "keyWords": ["ensure"] },
    { "chinese": "v. 进入；参加", "english": "enter", "type": "单词", "keyWords": [] },
    { "chinese": "（替...）报名参加", "english": "enter sb. for...", "type": "短语", "keyWords": ["enter"] },
    { "chinese": "报名参加", "english": "enter for (exams/ races/ the competition)", "type": "短语", "keyWords": ["enter"] },
    { "chinese": "n. (C) 企业，公司；事业心", "english": "enterprise", "type": "单词", "keyWords": [] },
    { "chinese": "a. 有事业心的，有进取心的", "english": "enterprising", "type": "单词", "keyWords": [] },
    { "chinese": "v. 使快乐；给...娱乐，招待", "english": "entertain", "type": "单词", "keyWords": [] },
    { "chinese": "用...款待某人", "english": "entertain sb. with sth.", "type": "短语", "keyWords": ["entertain"] },
    { "chinese": "a. 引起乐趣的", "english": "entertaining", "type": "单词", "keyWords": [] },
    { "chinese": "一个有趣的故事", "english": "an entertaining story", "type": "短语", "keyWords": ["entertaining"] },
    { "chinese": "街头表演者", "english": "street entertainer", "type": "短语", "keyWords": ["entertain"] },
    { "chinese": "n. (U) 娱乐；招待；(C) 演出", "english": "entertainment", "type": "单词", "keyWords": [] },
    { "chinese": "音乐演奏会", "english": "a musical entertainment", "type": "短语", "keyWords": ["entertainment"] },
    { "chinese": "我感到最有趣（的是）...", "english": "much to my entertainment", "type": "短语", "keyWords": ["entertainment"] },
    { "chinese": "n. (C) 表演者；款待者", "english": "entertainer", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 热情，热心", "english": "enthusiasm", "type": "单词", "keyWords": [] },
    { "chinese": "a. 热心的，满腔热情的", "english": "enthusiastic", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 热心地，满腔热情地", "english": "enthusiastically", "type": "单词", "keyWords": [] },
    { "chinese": "a. 整个的；全部的", "english": "entire", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 完全地，全然地，一概地", "english": "entirely", "type": "单词", "keyWords": [] },
    { "chinese": "v. 给...权利（或资格）；给（书、文章等）题名；给...称号，冠名", "english": "entitle", "type": "单词", "keyWords": [] },
    { "chinese": "每个公民都有权依法受同等保护。", "english": "Every citizen is entitled to (prep.) equal protection under the law.", "type": "句子", "keyWords": ["entitle"] },
    { "chinese": "你没有资格乘坐头等（车厢、舱位等）。", "english": "You are not entitled to travel first class.", "type": "句子", "keyWords": ["entitle"] },
    { "chinese": "这篇社论的题目是《...》。", "english": 'The editorial is entitled "...".', "type": "句子", "keyWords": ["entitle"] },
    { "chinese": "n. (C) 进入；入口（处）；门口；入学（或入会、入场）", "english": "entrance", "type": "单词", "keyWords": [] },
    { "chinese": "在...入口", "english": "at the entrance to", "type": "短语", "keyWords": ["entrance"] },
    { "chinese": "大学入学考试", "english": "college entrance examination", "type": "短语", "keyWords": ["entrance"] },
    { "chinese": "n. (C) 登录；词目；进入（许可）；入口", "english": "entry", "type": "单词", "keyWords": [] },
    { "chinese": "（词典中的）词条", "english": "word entry", "type": "短语", "keyWords": ["entry"] },
    { "chinese": "他们的参战改变了整个局势。", "english": "Their entry into the war changed the whole situation.", "type": "句子", "keyWords": ["entry"] },
    { "chinese": "n. (C) 信封；封套", "english": "envelope", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 环境", "english": "environment", "type": "单词", "keyWords": [] },
    { "chinese": "a. 周围的，环境的", "english": "environmental", "type": "单词", "keyWords": [] },
    { "chinese": "环境友善的，无损于环境的", "english": "environment-friendly", "type": "短语", "keyWords": ["environment"] },
    { "chinese": "v. 羡慕，嫉妒", "english": "envy", "type": "单词", "keyWords": [] },
    { "chinese": "n. U 羡慕；(the) 妒忌的对象", "english": "envy n.", "type": "短语", "keyWords": ["envy"] },
    { "chinese": "成为...的羡慕目标", "english": "be the envy of sb.", "type": "短语", "keyWords": ["envy"] },
    { "chinese": "出于嫉妒或羡慕", "english": "out of envy", "type": "短语", "keyWords": ["envy"] },
    { "chinese": "羡慕某人某物", "english": "envy sb. sth.", "type": "短语", "keyWords": ["envy"] },
    { "chinese": "我真是羡慕你的才能哟！", "english": "How I envy you your talent!", "type": "句子", "keyWords": ["envy"] },
    { "chinese": "a. 流行的；传染的", "english": "epidemic", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) （风尚等的）流行；流行病", "english": "epidemic n.", "type": "短语", "keyWords": ["epidemic"] },
    { "chinese": "a. 相等的；平等的", "english": "equal", "type": "单词", "keyWords": [] },
    { "chinese": "v. 等于，跟...相同；比得上", "english": "equal v.", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "n. (C) 等同的事物（或量）；对手；匹敌；同辈", "english": "equal n.", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "ad. 相等地，平等地", "english": "equally", "type": "单词", "keyWords": [] },
    { "chinese": "和...相等的，等同的；胜任...", "english": "be equal to...", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "他有足够的能力管理这个部门。", "english": "He is quite equal to the task of running the office.", "type": "句子", "keyWords": ["equal"] },
    { "chinese": "他和我力气相等，但智力不同。", "english": "He equals me in strength but not in intelligence.", "type": "句子", "keyWords": ["equal"] },
    { "chinese": "与那些和你差不多或比你更好的人交往", "english": "mix with one's equals and betters", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "在音乐方面没有人比得上", "english": "have no equal in music", "type": "短语", "keyWords": ["equal"] },
    { "chinese": "n. (U) 等同性，同等；平等，相等", "english": "equality", "type": "单词", "keyWords": [] },
    { "chinese": "n. (the) 赤道", "english": "equator", "type": "单词", "keyWords": [] },
    { "chinese": "v. 配备；使有准备", "english": "equip", "type": "单词", "keyWords": [] },
    { "chinese": "供给某人某物", "english": "equip sb. with sth.", "type": "短语", "keyWords": ["equip"] },
    { "chinese": "我们使孩子们受到良好的教育。", "english": "We equip our children with a good education.", "type": "句子", "keyWords": ["equip"] },
    { "chinese": "装有自动计时器的照相机", "english": "a camera equipped with a self-timer", "type": "短语", "keyWords": ["equip"] },
    { "chinese": "准备做某事", "english": "be equipped to do sth.", "type": "短语", "keyWords": ["equip"] },
    { "chinese": "我有充分的准备去处理局势。", "english": "I was well equipped to deal with the situation.", "type": "句子", "keyWords": ["equip"] },
    { "chinese": "设备完善的；充分准备的", "english": "well/ fully-equipped", "type": "短语", "keyWords": ["equip"] },
    { "chinese": "n. (U) 装备；设备", "english": "equipment", "type": "单词", "keyWords": [] },
    { "chinese": "办公设备", "english": "office equipment", "type": "短语", "keyWords": ["equipment"] },
    { "chinese": "a. （价值、效果、意义等）相当的；对等的", "english": "equivalent", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 相等物；等价物；等量物；对应词", "english": "equivalent n.", "type": "短语", "keyWords": ["equivalent"] },
    { "chinese": "同等学历", "english": "equivalent education", "type": "短语", "keyWords": ["equivalent"] },
    { "chinese": "沉默有时等于同意。", "english": "Silence is sometimes equivalent to agreement.", "type": "句子", "keyWords": ["equivalent"] },
    { "chinese": "你能找出与那个词相对应的汉语吗？", "english": "Could you find a Chinese equivalent for that word?", "type": "句子", "keyWords": ["equivalent"] },
    { "chinese": "interj. 呃；嗯", "english": "er", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 时代，纪元", "english": "era", "type": "单词", "keyWords": [] },
    { "chinese": "一个新的和平时代来临。", "english": "A new era of peace began.", "type": "句子", "keyWords": ["era"] },
    { "chinese": "n. (C) 擦除器（尤指墨水消除剂、黑板擦、橡皮、刮字刀等）", "english": "eraser", "type": "单词", "keyWords": [] },
    { "chinese": "v. 抹去；擦掉；消磁；[计]清除", "english": "erase", "type": "单词", "keyWords": [] },
    { "chinese": "v. 建造；树立", "english": "erect", "type": "单词", "keyWords": [] },
    { "chinese": "a. 直立的，挺直的；竖起的；垂直的", "english": "erect a.", "type": "短语", "keyWords": ["erect"] },
    { "chinese": "建造一座摩天大厦", "english": "erect a skyscraper", "type": "短语", "keyWords": ["erect"] },
    { "chinese": "建立一种哲学体系", "english": "erect a philosophical system", "type": "短语", "keyWords": ["erect"] },
    { "chinese": "n. (C) 错误；差错", "english": "error", "type": "单词", "keyWords": [] },
    { "chinese": "v. 喷出；vi. （火山等）爆发；喷发", "english": "erupt", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) (U) 喷发", "english": "eruption", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 自动扶梯", "english": "escalator", "type": "单词", "keyWords": [] },
    { "chinese": "v. 逃避；避免；被忘掉", "english": "escape", "type": "单词", "keyWords": [] },
    { "chinese": "vi. 逃脱；溜走；（气体等）泄漏，逸出", "english": "escape vi.", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "n. (C) 逃跑；泄漏；出口", "english": "escape n.", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "避免做某事；逃避/逃脱某事", "english": "escape doing sth.", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "他九死一生。", "english": "He narrowly escaped death.", "type": "句子", "keyWords": ["escape"] },
    { "chinese": "逃过某人的注意", "english": "escape one's attention/ notice", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "（从监狱等地方）逃跑；逃脱", "english": "escape/ make one's escape from (prison...)", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "我不记得他的名字了。/他的名字被我忘掉了。", "english": "His name escaped me./ His name escaped my memory.", "type": "句子", "keyWords": ["escape"] },
    { "chinese": "九死一生，幸免于难", "english": "a narrow escape", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "一个在逃犯", "english": "an escaped prisoner", "type": "短语", "keyWords": ["escape"] },
    { "chinese": "a. 特别的，特殊的（尤指优于、高于、超出于）", "english": "especial", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 尤其；特别", "english": "especially", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 短文，论说文；散文；小品文，随笔", "english": "essay", "type": "单词", "keyWords": [] },
    { "chinese": "a. 绝对必要的（侧重指不可缺少）；基本的，实质的", "english": "essential", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 必要地；实质上；从根本上说", "english": "essentially", "type": "单词", "keyWords": [] },
    { "chinese": "对...必要的；必不可少的", "english": "be essential to...", "type": "短语", "keyWords": ["essential"] },
    { "chinese": "n. (U) 基本，本质；精髓", "english": "essence", "type": "单词", "keyWords": [] },
    { "chinese": "v. （稳固地）建立；确定/立；使立足", "english": "establish", "type": "单词", "keyWords": [] },
    { "chinese": "一个建立了他的声望的发现", "english": "a discovery that established his reputation", "type": "短语", "keyWords": ["establish"] },
    { "chinese": "确立了自己/某人（律师）的地位", "english": "establish oneself/ sb. as (a lawyer)", "type": "短语", "keyWords": ["establish"] },
    { "chinese": "建立联系", "english": "establish a link/ connection", "type": "短语", "keyWords": ["establish"] },
    { "chinese": "a. 已制定的，确定的", "english": "established", "type": "单词", "keyWords": [] },
    { "chinese": "既定事实", "english": "an established fact", "type": "短语", "keyWords": ["established"] },
    { "chinese": "成规", "english": "an established rule", "type": "短语", "keyWords": ["established"] },
    { "chinese": "n. (U) 建立，设立；(C) 已建立的机构", "english": "establishment", "type": "单词", "keyWords": [] },
    { "chinese": "v. 估计；评价；判断（只是猜测，甚至只是一种想法）", "english": "estimate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 估计；判断", "english": "estimation", "type": "单词", "keyWords": [] },
    { "chinese": "v. 低估；看轻", "english": "underestimate", "type": "单词", "keyWords": [] },
    { "chinese": "估计/预算数量", "english": "the estimated amount", "type": "短语", "keyWords": ["estimate"] },
    { "chinese": "据估计...", "english": "It is estimated that...", "type": "句子", "keyWords": ["estimate"] },
    { "chinese": "adv. 等等", "english": "etc.", "type": "单词", "keyWords": [] },
    { "chinese": "a. 永恒的；永远的；没完没了的", "english": "eternal", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 永恒", "english": "eternity", "type": "单词", "keyWords": ["eternal"] },
    { "chinese": "n. 欧洲", "english": "Europe", "type": "单词", "keyWords": [] },
    { "chinese": "a. 欧洲的；n. (C) 欧洲人", "english": "European", "type": "单词", "keyWords": ["Europe"] },
    { "chinese": "vt. 评价；估...的值（经过深思熟虑确定人、物的价值，不一定是金钱价值）", "english": "evaluate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)(C) 评价；评估", "english": "evaluation", "type": "单词", "keyWords": ["evaluate"] },
    { "chinese": "v. (使) 蒸发", "english": "evaporate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 蒸发", "english": "evaporation", "type": "单词", "keyWords": ["evaporate"] },
    { "chinese": "n. (C)（节日等的）前夜，前夕", "english": "eve", "type": "单词", "keyWords": [] },
    { "chinese": "在圣诞前夜", "english": "on Christmas Eve", "type": "短语", "keyWords": ["eve"] },
    { "chinese": "在...前夕", "english": "on the eve of", "type": "短语", "keyWords": ["eve"] },
    { "chinese": "ad. 甚至，即使；连(...都)；a. 平整的；均匀的；相等的；偶数的", "english": "even", "type": "单词", "keyWords": [] },
    { "chinese": "即使", "english": "even though/if", "type": "短语", "keyWords": ["even"] },
    { "chinese": "甚至那个时候，尽管那样", "english": "even then", "type": "短语", "keyWords": ["even"] },
    { "chinese": "尽管如此", "english": "even so", "type": "短语", "keyWords": ["even"] },
    { "chinese": "偶数", "english": "even numbers", "type": "短语", "keyWords": ["even"] },
    { "chinese": "n. (C) 傍晚；晚上；(联欢性的) 晚会", "english": "evening", "type": "单词", "keyWords": [] },
    { "chinese": "（电影等）夜场", "english": "evening show", "type": "短语", "keyWords": ["evening"] },
    { "chinese": "n. [C] [体育] 比赛项目；活动；事件，大事（有重要意义的事件）", "english": "event", "type": "单词", "keyWords": [] },
    { "chinese": "a. 最终发生的，最后的；结局的，结果的", "english": "eventual", "type": "单词", "keyWords": ["event"] },
    { "chinese": "ad. 最后；终于", "english": "eventually", "type": "单词", "keyWords": ["eventual"] },
    { "chinese": "ad.（用于一般疑问句）曾，曾经；（用于疑问词之后，加强语气）究竟，到底；（用于条件句和否定句）任何时候，无论何时；（用于比较从句）以前，以往；（表示惊讶、怀疑和不耐烦）可能，总会；（常与so连用）在很大程度上", "english": "ever", "type": "单词", "keyWords": [] },
    { "chinese": "从...以来", "english": "ever since", "type": "短语", "keyWords": ["ever"] },
    { "chinese": "你曾经到过北京吗？", "english": "Have you ever been to Beijing?", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "这村里从来没有发生过什么事情。", "english": "Nothing ever happens in this village.", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "（任何时候）你若到大连来，务请通知我们一声。", "english": "If you ever come to Dalian, be sure to let us know.", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "我要是抓到他的话，哼（就决不饶他）！", "english": "If I ever catch him!", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "雨比以前下得更大了。", "english": "It is raining harder than ever.", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "这是你所做的最好的工作。", "english": "This is the best work you have ever done.", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "今年农民取得了空前的大丰收。", "english": "The farmers got the biggest crop ever this year.", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "你到底何时/何地/怎样丢失了这个东西？", "english": "When/Where/How ever did you lose it?", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "他总是重复同样的话。", "english": "He is ever repeating the same words.", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "难得，几乎从来不", "english": "hardly ever", "type": "短语", "keyWords": ["ever"] },
    { "chinese": "他几乎从不吃肉。", "english": "He hardly ever eats meat.", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "就是有也极少见", "english": "seldom, if ever", "type": "短语", "keyWords": ["ever"] },
    { "chinese": "这个岛难得有船停靠。", "english": "The island is seldom, if ever, visited by ships.", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "[口] 非常，极其，十分", "english": "ever so (cold/wet/nice)", "type": "短语", "keyWords": ["ever"] },
    { "chinese": "非常感谢。", "english": "Thank you ever so much.", "type": "句子", "keyWords": ["ever"] },
    { "chinese": "a. 永久的；持久的", "english": "everlasting", "type": "单词", "keyWords": [] },
    { "chinese": "永恒的友谊", "english": "everlasting friendship", "type": "短语", "keyWords": ["everlasting"] },
    { "chinese": "a. 每一；每个的（指数目不定的许多人/物中间的每一个，“总体”意义很重）", "english": "every", "type": "单词", "keyWords": [] },
    { "chinese": "每三周", "english": "every three weeks", "type": "短语", "keyWords": ["every"] },
    { "chinese": "每隔几天", "english": "every few days", "type": "短语", "keyWords": ["every"] },
    { "chinese": "每三个座位", "english": "every third seat", "type": "短语", "keyWords": ["every"] },
    { "chinese": "每隔一天", "english": "every other day", "type": "短语", "keyWords": ["every"] },
    { "chinese": "每隔一些时候；不时", "english": "every now and then", "type": "短语", "keyWords": ["every"] },
    { "chinese": "凡人皆有得意之日/时。", "english": "Every dog has its day.", "type": "句子", "keyWords": ["every"] },
    { "chinese": "a. 每天的；日常的，平常的；平凡的", "english": "everyday", "type": "单词", "keyWords": [] },
    { "chinese": "日常工作", "english": "everyday routine", "type": "短语", "keyWords": ["everyday"] },
    { "chinese": "pron. 每个人，人人（后面不可以接of短语）", "english": "everybody", "type": "单词", "keyWords": [] },
    { "chinese": "大家都到了，不是吗？", "english": "Everybody has come haven't they/ hasn't he/she?", "type": "句子", "keyWords": ["everybody"] },
    { "chinese": "pron. 每个人，人人（后面不可以接of短语）", "english": "everyone", "type": "单词", "keyWords": [] },
    { "chinese": "其中（每）一个人/物", "english": "every one of...", "type": "短语", "keyWords": ["everyone"] },
    { "chinese": "pron. 每件事；每样东西；万事；一切（后面不可以接of短语）", "english": "everything", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 各处，到处；无论何处", "english": "everywhere", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 证据；根据；迹象", "english": "evidence", "type": "单词", "keyWords": [] },
    { "chinese": "警察有证据证明凶手是个老年妇女。", "english": "The police had evidence that the killer was an old woman.", "type": "句子", "keyWords": ["evidence"] },
    { "chinese": "a. 明显的；明白的（近obvious, clear, apparent）", "english": "evident", "type": "单词", "keyWords": [] },
    { "chinese": "（我）很清楚...", "english": "It is evident (to me) that...", "type": "句子", "keyWords": ["evident"] },
    { "chinese": "n. (C) 罪恶；a. 邪恶的；罪恶的", "english": "evil", "type": "单词", "keyWords": [] },
    { "chinese": "vt. (使) 逐渐形成；(使) 演变；(使) 演化；(使) 进化(from)；发育", "english": "evolve", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 进化；演变，演化；逐步形成；发育（比较solution）", "english": "evolution", "type": "单词", "keyWords": ["evolve"] },
    { "chinese": "a. 精确的，确切的（意为高度准确，丝毫不差）", "english": "exact", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 确切地；恰恰正是", "english": "exactly", "type": "单词", "keyWords": ["exact"] },
    { "chinese": "n. (U) 精确", "english": "exactness", "type": "单词", "keyWords": ["exact"] },
    { "chinese": "确切地说", "english": "to be exact", "type": "短语", "keyWords": ["exact"] },
    { "chinese": "vt. 夸大，夸张", "english": "exaggerate", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 夸大，夸张", "english": "exaggeration", "type": "单词", "keyWords": ["exaggerate"] },
    { "chinese": "n. (C) 考试；检查（同examination）", "english": "exam", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 考试；检查；审问", "english": "examination", "type": "单词", "keyWords": ["exam"] },
    { "chinese": "通过考试", "english": "pass an exam", "type": "短语", "keyWords": ["exam", "examination"] },
    { "chinese": "参加考试", "english": "enter for/ sit for/ take an exam", "type": "短语", "keyWords": ["exam", "examination"] },
    { "chinese": "经进一步仔细检查", "english": "on closer examination", "type": "短语", "keyWords": ["examination"] },
    { "chinese": "体格检查", "english": "a medical examination", "type": "短语", "keyWords": ["examination"] },
    { "chinese": "大学入学考试", "english": "university entrance examination", "type": "短语", "keyWords": ["examination"] },
    { "chinese": "v. 检查；对...进行考查；审查（近check）", "english": "examine", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 主考者", "english": "examiner", "type": "单词", "keyWords": ["examine"] },
    { "chinese": "就某事查问/考核某人", "english": "examine sb. on sth.", "type": "短语", "keyWords": ["examine"] },
    { "chinese": "进行眼科检查", "english": "have one's eyes examined", "type": "短语", "keyWords": ["examine"] },
    { "chinese": "n. [C] 榜样；例子", "english": "example", "type": "单词", "keyWords": [] },
    { "chinese": "比如", "english": "take ... (for example)", "type": "短语", "keyWords": ["example"] },
    { "chinese": "为...树立榜样", "english": "set an example to", "type": "短语", "keyWords": ["example"] },
    { "chinese": "是...的榜样；当作某人的教训", "english": "let this be an example to", "type": "短语", "keyWords": ["example"] },
    { "chinese": "学习某人的榜样", "english": "copy/ follow sb.'s example", "type": "短语", "keyWords": ["example"] },
    { "chinese": "a. 极好的，优秀的", "english": "excellent", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 优秀；优点；美德", "english": "excellence", "type": "单词", "keyWords": ["excellent"] },
    { "chinese": "prep. 除了...之外（近other than）；若不是，除非", "english": "except", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 例外（情况）", "english": "exception", "type": "单词", "keyWords": ["except"] },
    { "chinese": "a. 例外的，异常的；杰出的，非凡的", "english": "exceptional", "type": "单词", "keyWords": ["exception"] },
    { "chinese": "只是有...；除了有...（表示惋惜）", "english": "except for", "type": "短语", "keyWords": ["except"] },
    { "chinese": "除了，只是", "english": "except that/ what...", "type": "短语", "keyWords": ["except"] },
    { "chinese": "我只知道它是金属。", "english": "I know nothing about it except that it is a metal.", "type": "句子", "keyWords": ["except"] },
    { "chinese": "除了在报上读到的以外，我对这件事一无所知。", "english": "I know nothing about it except what I have read in the papers.", "type": "句子", "keyWords": ["except"] },
    { "chinese": "除了...之外，只得做某事", "english": "do nothing except do sth.", "type": "短语", "keyWords": ["except"] },
    { "chinese": "除了...之外", "english": "with the exception of", "type": "短语", "keyWords": ["exception"] },
    { "chinese": "毫无例外地，一律", "english": "without exception", "type": "短语", "keyWords": ["exception"] },
    { "chinese": "n. (C) 交换；交流；v. 交换；更换；交易（货物）", "english": "exchange", "type": "单词", "keyWords": [] },
    { "chinese": "文化交流", "english": "cultural exchange", "type": "短语", "keyWords": ["exchange"] },
    { "chinese": "交换", "english": "in exchange for", "type": "短语", "keyWords": ["exchange"] },
    { "chinese": "外汇", "english": "foreign exchange", "type": "短语", "keyWords": ["exchange"] },
    { "chinese": "（两国间）交换的留学生", "english": "exchange student", "type": "短语", "keyWords": ["exchange"] },
    { "chinese": "兑换", "english": "exchange sth. for sth.", "type": "短语", "keyWords": ["exchange"] },
    { "chinese": "vt. 使激动，使兴奋；引起", "english": "excite", "type": "单词", "keyWords": [] },
    { "chinese": "a. 使人/感到兴奋的", "english": "exciting/excited", "type": "单词", "keyWords": ["excite"] },
    { "chinese": "n. (U)(C) 兴奋", "english": "excitement", "type": "单词", "keyWords": ["excite"] },
    { "chinese": "为...而兴奋", "english": "be excited about/ by/ at doing sth.", "type": "短语", "keyWords": ["excited"] },
    { "chinese": "ad. 兴奋地；激动地", "english": "excitedly", "type": "单词", "keyWords": ["excited"] },
    { "chinese": "很激动地把此事告诉我", "english": "tell me about it in an excited voice", "type": "短语", "keyWords": ["excited"] },
    { "chinese": "v. 呼喊；惊呼", "english": "exclaim", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 呼喊；惊呼", "english": "exclamation", "type": "单词", "keyWords": ["exclaim"] },
    { "chinese": "看到账单上的数目吓得叫起来", "english": "exclaim at the size of the bill", "type": "短语", "keyWords": ["exclaim"] },
    { "chinese": "激动地喊了起来", "english": "exclaim with excitement", "type": "短语", "keyWords": ["exclaim"] },
    { "chinese": "a. 叫喊的；感叹的，惊叹的", "english": "exclamatory", "type": "单词", "keyWords": ["exclaim"] },
    { "chinese": "vt. 拒绝...进入；把...排斥在外；不包括", "english": "exclude", "type": "单词", "keyWords": [] },
    { "chinese": "a. 排他的", "english": "exclusive", "type": "单词", "keyWords": ["exclude"] },
    { "chinese": "prep. 不算，不包括", "english": "excluding", "type": "单词", "keyWords": ["exclude"] },
    { "chinese": "被拒绝入会", "english": "be excluded from the club", "type": "短语", "keyWords": ["exclude"] },
    { "chinese": "打消...念头", "english": "exclude the idea of...", "type": "短语", "keyWords": ["exclude"] },
    { "chinese": "n. (C)(U) 排除，除外；被排除在外的事物", "english": "exclusion", "type": "单词", "keyWords": ["exclude"] },
    { "chinese": "n. (C) 短途旅行，远足", "english": "excursion", "type": "单词", "keyWords": [] },
    { "chinese": "去...旅行", "english": "go on an excursion to...", "type": "短语", "keyWords": ["excursion"] },
    { "chinese": "n. [C] 原谅；借口；v. 原谅", "english": "excuse", "type": "单词", "keyWords": [] },
    { "chinese": "找理由", "english": "make/ find/ have an excuse", "type": "短语", "keyWords": ["excuse"] },
    { "chinese": "无知不能成为违法的理由。", "english": "Ignorance is no excuse for breaking the law.", "type": "句子", "keyWords": ["excuse"] },
    { "chinese": "原谅某人做某事", "english": "excuse/ pardon/ forgive sb. for (doing) sth.", "type": "短语", "keyWords": ["excuse"] },
    { "chinese": "原谅某人做某事", "english": "excuse sb.'s doing sth.", "type": "短语", "keyWords": ["excuse"] },
    { "chinese": "免除某人做某事", "english": "excuse sb. from (doing) sth.", "type": "短语", "keyWords": ["excuse"] },
    { "chinese": "通过第一次测验的学生可以免除第二次测验。", "english": "Students who passed the first test are excused from the second one.", "type": "句子", "keyWords": ["excuse"] },
    { "chinese": "在我看来，医生和律师都应免除当陪审团的义务。", "english": "In my state, physicians and lawyers are excused from jury duty.", "type": "句子", "keyWords": ["excuse"] },
    { "chinese": "请原谅，我去睡会儿。", "english": "If you'll excuse me, I'll get some sleep.", "type": "句子", "keyWords": ["excuse"] },
    { "chinese": "我能离开一下吗？", "english": "Won't you excuse me for a little while?", "type": "句子", "keyWords": ["excuse"] },
    { "chinese": "老师，我可以离开吗？", "english": "May I be excused, Miss?", "type": "句子", "keyWords": ["excuse"] },
    { "chinese": "a. 实行的，执行的；经营管理的；行政（的）；n. (C) 执行者；经理；主管人员；行政官；行政部门（或领导）", "english": "executive", "type": "单词", "keyWords": [] },
    { "chinese": "常务理事", "english": "executive member of the council", "type": "短语", "keyWords": ["executive"] },
    { "chinese": "执行总裁；首席执行官", "english": "Chief Executive Officer (CEO)", "type": "短语", "keyWords": ["executive"] },
    { "chinese": "n. (U) 行使；履行；锻炼；训练；n. (C) 练习；习题；v. 行使；履行；锻炼；练习", "english": "exercise", "type": "单词", "keyWords": [] },
    { "chinese": "训练记忆力", "english": "exercise one's memory", "type": "短语", "keyWords": ["exercise"] },
    { "chinese": "v. 耗尽；使筋疲力尽；排空；vi. 排出气体；排空；n. (U)（废气、废液等的）排出；（排出的）废气；废液", "english": "exhaust", "type": "单词", "keyWords": [] },
    { "chinese": "a. 使人/感到精疲力竭", "english": "exhausting/exhausted", "type": "单词", "keyWords": ["exhaust"] },
    { "chinese": "n. (C)(U) 耗尽；筋疲力尽", "english": "exhaustion", "type": "单词", "keyWords": ["exhaust"] },
    { "chinese": "耗尽了他们的油", "english": "exhaust their supply of oil", "type": "短语", "keyWords": ["exhaust"] },
    { "chinese": "用尽了我们的基金", "english": "exhaust our funds", "type": "短语", "keyWords": ["exhaust"] },
    { "chinese": "n. (C) 展览品；v. 展出；表现出；显示", "english": "exhibit", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 展览会", "english": "exhibition", "type": "单词", "keyWords": ["exhibit"] },
    { "chinese": "用微笑表示高兴", "english": "exhibit pleasure by smiling", "type": "短语", "keyWords": ["exhibit"] },
    { "chinese": "（规模较大的）展出（近on show, on display）", "english": "on exhibition", "type": "短语", "keyWords": ["exhibition"] },
    { "chinese": "vi. 存在", "english": "exist", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 存在", "english": "existence", "type": "单词", "keyWords": ["exist"] },
    { "chinese": "a. 现存的，现有的", "english": "existing", "type": "单词", "keyWords": ["exist"] },
    { "chinese": "现存的，现有的", "english": "in existence", "type": "短语", "keyWords": ["existence"] },
    { "chinese": "产生", "english": "come into existence = come into being", "type": "短语", "keyWords": ["existence"] },
    { "chinese": "当前形势", "english": "the existing situation", "type": "短语", "keyWords": ["existing"] },
    { "chinese": "n. (C) 出口；退场；vi. 退出；脱离", "english": "exit", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 扩大（增加业务、尺寸、体积、数量或范围）；扩张；展开；膨胀", "english": "expand", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 扩大；扩张；展开；膨胀", "english": "expansion", "type": "单词", "keyWords": ["expand"] },
    { "chinese": "v. 期待；预料（指对某特定事件抱有很大信心）；盼望，指望；(口)（料）想；认为", "english": "expect", "type": "单词", "keyWords": [] },
    { "chinese": "a. 意外的，未预料到的", "english": "unexpected", "type": "单词", "keyWords": ["expect"] },
    { "chinese": "期待", "english": "expect that...", "type": "短语", "keyWords": ["expect"] },
    { "chinese": "期待做某事", "english": "expect to do sth.", "type": "短语", "keyWords": ["expect"] },
    { "chinese": "期待/指望/预料某人做某事", "english": "expect sb. to do sth.", "type": "短语", "keyWords": ["expect"] },
    { "chinese": "你别指望我赞成这事。", "english": "You can't expect me to approve of it.", "type": "句子", "keyWords": ["expect"] },
    { "chinese": "他的航班预计在今晚7点到达。", "english": "His flight is expected to arrive at 7 this evening.", "type": "句子", "keyWords": ["expect"] },
    { "chinese": "对某人期待太高", "english": "expect too much of sb.", "type": "短语", "keyWords": ["expect"] },
    { "chinese": "大多数父母都对自己的子女寄予太大的希望。", "english": "Most of the parents expected too much of their children.", "type": "句子", "keyWords": ["expect"] },
    { "chinese": "正如所预料的", "english": "as (was/ had been) expected", "type": "短语", "keyWords": ["expect"] },
    { "chinese": "不出所料，销售部经理今天提出了辞职要求。", "english": "As expected, the sales manager gave in his notice at work.", "type": "句子", "keyWords": ["expect"] },
    { "chinese": "我在等一个电话。（expect指心理状态，wait指行为）", "english": "I'm expecting a telephone call.", "type": "句子", "keyWords": ["expect"] },
    { "chinese": "n. (C)(U) 期待；预料；(常用复) 期望的事物或前程", "english": "expectation", "type": "单词", "keyWords": ["expect"] },
    { "chinese": "不辜负某人的期望", "english": "live up to sb.'s expectations", "type": "短语", "keyWords": ["expectation"] },
    { "chinese": "出乎意料", "english": "beyond all expectations", "type": "短语", "keyWords": ["expectation"] },
    { "chinese": "有远大前程的年轻人", "english": "a young man with great expectations", "type": "短语", "keyWords": ["expectation"] },
    { "chinese": "n. [C] 远征；探险（辩析见tour）；考察；探险队；考察队", "english": "expedition", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 花费；费用；(C) 一笔开支（比较expend v. 花费；expenditure n. 支出）", "english": "expense", "type": "单词", "keyWords": [] },
    { "chinese": "某人付款；使某人受损", "english": "at one's expense", "type": "短语", "keyWords": ["expense"] },
    { "chinese": "自费买", "english": "buy something at his own expense", "type": "短语", "keyWords": ["expense"] },
    { "chinese": "以牺牲健康为代价完成了任务", "english": "finish the task at the expense/ cost of his health", "type": "短语", "keyWords": ["expense"] },
    { "chinese": "a. 昂贵的；索高价的", "english": "expensive", "type": "单词", "keyWords": ["expense"] },
    { "chinese": "n. (C) 经历；(U) 经验；v. 体验，经历；经受", "english": "experience", "type": "单词", "keyWords": [] },
    { "chinese": "a. (不) 富有经验的", "english": "(in)experienced", "type": "单词", "keyWords": ["experience"] },
    { "chinese": "缺乏经验", "english": "lack of experience", "type": "短语", "keyWords": ["experience"] },
    { "chinese": "获得经验", "english": "gain/ get experience", "type": "短语", "keyWords": ["experience"] },
    { "chinese": "经验是最好的老师。", "english": "Experience is the best teacher.", "type": "句子", "keyWords": ["experience"] },
    { "chinese": "从经验中吸取教训", "english": "learn from experience", "type": "短语", "keyWords": ["experience"] },
    { "chinese": "遭到困难/挫折", "english": "experience difficulties/ setbacks", "type": "短语", "keyWords": ["experience"] },
    { "chinese": "在...方面十分有/缺乏经验", "english": "be highly/ poorly experienced in...", "type": "短语", "keyWords": ["experienced"] },
    { "chinese": "在过去的30年里，我们国家经历了巨大的变化。", "english": "Our country has experienced great changes in the last 30 years.", "type": "句子", "keyWords": ["experience"] },
    { "chinese": "经验乃智慧之母。/实践出真知。", "english": "Experience is the mother of wisdom.", "type": "句子", "keyWords": ["experience"] },
    { "chinese": "n. (C) 实验；试验；a. 实验的；vi. 进行实验(on/in/with)", "english": "experiment", "type": "单词", "keyWords": [] },
    { "chinese": "a. 实验的", "english": "experimental", "type": "单词", "keyWords": ["experiment"] },
    { "chinese": "在....上做实验；用...来做实验", "english": "do/ conduct/ carry out/ perform/ make an experiment on/ with...", "type": "短语", "keyWords": ["experiment"] },
    { "chinese": "他们用猴子做实验来测试这种新药。", "english": "They carried out an experiment on monkeys to test the new drug.", "type": "句子", "keyWords": ["experiment"] },
    { "chinese": "n. [C] 专家；行家；能手；a. 有专门训练的；老练的，内行的", "english": "expert", "type": "单词", "keyWords": [] },
    { "chinese": "某方面的专家/能手；擅长于...", "english": "be an expert on/in/at", "type": "短语", "keyWords": ["expert"] },
    { "chinese": "经济学专家", "english": "an expert in economics", "type": "短语", "keyWords": ["expert"] },
    { "chinese": "驾驶赛车能手", "english": "be expert at driving racing cars", "type": "短语", "keyWords": ["expert"] },
    { "chinese": "内行意见", "english": "expert advice", "type": "短语", "keyWords": ["expert"] },
    { "chinese": "v. 说明；解释，讲解", "english": "explain", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C)(U) 说明；解释", "english": "explanation", "type": "单词", "keyWords": ["explain"] },
    { "chinese": "把自己的意思表达清楚", "english": "explain oneself", "type": "短语", "keyWords": ["explain"] },
    { "chinese": "说明...的原因", "english": "give an explanation for sth.", "type": "短语", "keyWords": ["explanation"] },
    { "chinese": "向某人解释某事", "english": "explain sth. to sb.", "type": "短语", "keyWords": ["explain"] },
    { "chinese": "向某人解释某事（直接宾语太长时后置）", "english": "explain to sb. sth.", "type": "短语", "keyWords": ["explain"] },
    { "chinese": "vt.vi. (使) 爆炸；(使) 爆发", "english": "explode", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U)(C) 爆炸", "english": "explosion", "type": "单词", "keyWords": ["explode"] },
    { "chinese": "勃然大怒，大发脾气", "english": "explode with anger", "type": "短语", "keyWords": ["explode"] },
    { "chinese": "n. (C) 炸药；a. 爆炸（性）的，爆发（性）的", "english": "explosive", "type": "单词", "keyWords": ["explode"] },
    { "chinese": "易爆的化学品", "english": "explosive chemicals", "type": "短语", "keyWords": ["explosive"] },
    { "chinese": "n. (C)（常pl.）业绩，功绩；英勇的行为", "english": "exploit", "type": "单词", "keyWords": [] },
    { "chinese": "他战时的英勇事迹后来被改编成了电影和电视剧。", "english": "His wartime exploits were later made into a film and a television series.", "type": "句子", "keyWords": ["exploit"] },
    { "chinese": "vt. 开发；利用；剥削", "english": "exploit", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 开发；利用；剥削", "english": "exploitation", "type": "单词", "keyWords": ["exploit"] },
    { "chinese": "挖掘潜力", "english": "exploit potentialities", "type": "短语", "keyWords": ["exploit"] },
    { "chinese": "开发自然资源", "english": "exploit natural resources", "type": "短语", "keyWords": ["exploit"] },
    { "chinese": "利用这个机会到国外去", "english": "exploit this opportunity to go abroad", "type": "短语", "keyWords": ["exploit"] },
    { "chinese": "剥削他人的劳动", "english": "exploit the labour of others", "type": "短语", "keyWords": ["exploit"] },
    { "chinese": "v. 勘探；探险；探索；探究", "english": "explore", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 探测者；探测器", "english": "explorer", "type": "单词", "keyWords": ["explore"] },
    { "chinese": "n. (U)(C) 探险", "english": "exploration", "type": "单词", "keyWords": ["explore"] },
    { "chinese": "深海探测", "english": "the exploration of depths of the ocean", "type": "短语", "keyWords": ["exploration"] },
    { "chinese": "n. (C) 博览会，展览会", "english": "expo", "type": "单词", "keyWords": [] },
    { "chinese": "v. 输出；出口；n. (U) 出口；(C) 出口物", "english": "export", "type": "单词", "keyWords": [] },
    { "chinese": "出口市场", "english": "export market", "type": "短语", "keyWords": ["export"] },
    { "chinese": "出口产业", "english": "export industry", "type": "短语", "keyWords": ["export"] },
    { "chinese": "v. 使暴露；接触；揭露；使处于...（作用或影响）之下", "english": "expose", "type": "单词", "keyWords": [] },
    { "chinese": "n. [U] 暴露；揭露，曝光，揭发", "english": "exposure", "type": "单词", "keyWords": ["expose"] },
    { "chinese": "使...暴露于", "english": "expose sb./sth. to sth.", "type": "短语", "keyWords": ["expose"] },
    { "chinese": "使他们的孩子受到古典音乐的影响", "english": "expose their children to classical music", "type": "短语", "keyWords": ["expose"] },
    { "chinese": "听任它被风吹雨打", "english": "leave it exposed to the weather", "type": "短语", "keyWords": ["expose"] },
    { "chinese": "他们第一次受到大城市生活的影响", "english": "their first exposure to big city life", "type": "短语", "keyWords": ["exposure"] },
    { "chinese": "由于暴露在风雨中而变旧的", "english": "be worn by exposure to the weather", "type": "短语", "keyWords": ["exposure"] },
    { "chinese": "n. (C) 快车；快递；专使；a. 急速的；v. 表达；表示", "english": "express", "type": "单词", "keyWords": [] },
    { "chinese": "快车", "english": "an express train", "type": "短语", "keyWords": ["express"] },
    { "chinese": "夜间快车", "english": "the night express", "type": "短语", "keyWords": ["express"] },
    { "chinese": "表示同情/恐惧/生气", "english": "express sympathy/ fear/anger", "type": "短语", "keyWords": ["express"] },
    { "chinese": "（写或说）表达自己的感情（思想）", "english": "express oneself", "type": "短语", "keyWords": ["express"] },
    { "chinese": "横贯欧洲快车", "english": "Trans-Europe Express", "type": "短语", "keyWords": ["express"] },
    { "chinese": "《印度快报》", "english": "Indian Express", "type": "短语", "keyWords": ["express"] },
    { "chinese": "n. (C)(U) 表情；表示；措辞，词语；表达方式", "english": "expression", "type": "单词", "keyWords": ["express"] },
    { "chinese": "毫无表情地", "english": "without expression", "type": "短语", "keyWords": ["expression"] },
    { "chinese": "他脸上的紧张神情", "english": "a tense expression on his face", "type": "短语", "keyWords": ["expression"] },
    { "chinese": "vi./vt. 伸展（身体部位、空间、时间）；伸出；延长；给予，提供", "english": "extend", "type": "单词", "keyWords": [] },
    { "chinese": "延长100千米", "english": "extend 100km", "type": "短语", "keyWords": ["extend"] },
    { "chinese": "延长她的签证有效期限", "english": "extend her visa", "type": "短语", "keyWords": ["extend"] },
    { "chinese": "欢迎/感谢某人", "english": "extend a welcome/ thanks to sb.", "type": "短语", "keyWords": ["extend"] },
    { "chinese": "我们的操场一直延伸到那些树那里。", "english": "Our playing fields extend as far as those trees.", "type": "句子", "keyWords": ["extend"] },
    { "chinese": "给某人以关心/帮助/同情", "english": "extend our regards/ our help/ our sympathy to sb.", "type": "短语", "keyWords": ["extend"] },
    { "chinese": "n. (U) 伸展；延长；扩大；(C) 延长或扩大部分；电话分机", "english": "extension", "type": "单词", "keyWords": ["extend"] },
    { "chinese": "a. 广阔的；大量的；广泛的", "english": "extensive", "type": "单词", "keyWords": ["extend"] },
    { "chinese": "泛读", "english": "extensive reading", "type": "短语", "keyWords": ["extensive"] },
    { "chinese": "n. (C) 广度；宽度；长度；范围；程度（近degree）", "english": "extent", "type": "单词", "keyWords": [] },
    { "chinese": "在一定程度上，有几分，（多少）有一点", "english": "to a certain extent/to some extent", "type": "短语", "keyWords": ["extent"] },
    { "chinese": "我部分地同意你。", "english": "I agree with you to some extent.", "type": "句子", "keyWords": ["extent"] },
    { "chinese": "很大程度上，非常", "english": "to a great extent", "type": "短语", "keyWords": ["extent"] },
    { "chinese": "达到那样的程度", "english": "to that extent", "type": "短语", "keyWords": ["extent"] },
    { "chinese": "到这样的程度以致/竟然...", "english": "to such an extent that...", "type": "短语", "keyWords": ["extent"] },
    { "chinese": "a. 外部的，外在的；表面的", "english": "exterior", "type": "单词", "keyWords": [] },
    { "chinese": "a. 外部的，外面的；表面的；[医] 外用的；外国的；外界的", "english": "external", "type": "单词", "keyWords": [] },
    { "chinese": "a. 灭绝的；(火山) 熄灭的", "english": "extinct", "type": "单词", "keyWords": [] },
    { "chinese": "n. (U) 灭绝", "english": "extinction", "type": "单词", "keyWords": ["extinct"] },
    { "chinese": "n. [C] 灭火器", "english": "extinguisher", "type": "单词", "keyWords": [] },
    { "chinese": "vt. 熄灭，消灭，压制", "english": "extinguish", "type": "单词", "keyWords": [] },
    { "chinese": "a. 额外的，外加的；ad. 额外地；特别", "english": "extra", "type": "单词", "keyWords": [] },
    { "chinese": "特别牢固的箱子", "english": "an extra strong box", "type": "短语", "keyWords": ["extra"] },
    { "chinese": "a. 非同寻常的，特别的", "english": "extraordinary", "type": "单词", "keyWords": ["extra"] },
    { "chinese": "v. 拔出，榨取，摘录；n. (C) 摘录，选粹", "english": "extract", "type": "单词", "keyWords": [] },
    { "chinese": "a. 奢侈浪费的；过分的", "english": "extravagant", "type": "单词", "keyWords": [] },
    { "chinese": "过度的表扬", "english": "extravagant praise", "type": "短语", "keyWords": ["extravagant"] },
    { "chinese": "n. (U) 奢侈，铺张，过度", "english": "extravagance", "type": "单词", "keyWords": ["extravagant"] },
    { "chinese": "a. 尽头的；极度的；极端的；过分的；n. [C] 极端", "english": "extreme", "type": "单词", "keyWords": [] },
    { "chinese": "ad. 极其，非常", "english": "extremely", "type": "单词", "keyWords": ["extreme"] },
    { "chinese": "极端气候", "english": "extreme weather", "type": "短语", "keyWords": ["extreme"] },
    { "chinese": "走极端", "english": "go to extremes", "type": "短语", "keyWords": ["extreme"] },
    { "chinese": "n. [C] 寓言", "english": "fable", "type": "单词", "keyWords": [] },
    { "chinese": "a. 寓言中的；难以置信的；[口] 妙极了的", "english": "fabulous", "type": "单词", "keyWords": [] },
    { "chinese": "n. [C] 织品，织物", "english": "fabric", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 脸；面孔；vt. 面向；面临；正视；(使) 面对；vi. 面向，朝", "english": "face", "type": "单词", "keyWords": [] },
    { "chinese": "a. 面部的；表面的", "english": "facial", "type": "单词", "keyWords": ["face"] },
    { "chinese": "扑面粉", "english": "face powder", "type": "短语", "keyWords": ["face"] },
    { "chinese": "（和...）面对面", "english": "face to face (with...)", "type": "短语", "keyWords": ["face"] },
    { "chinese": "做鬼脸", "english": "make a face/ faces", "type": "短语", "keyWords": ["face"] },
    { "chinese": "他的脸容光焕发。/喜形于色。", "english": "His face lit up.", "type": "句子", "keyWords": ["face"] },
    { "chinese": "显得很不高兴（拉长了脸）", "english": "wear/ pull a long face", "type": "短语", "keyWords": ["face"] },
    { "chinese": "当着我们的面吼", "english": "shout in our faces", "type": "短语", "keyWords": ["face"] },
    { "chinese": "朝北/东", "english": "face (to) the north/east", "type": "短语", "keyWords": ["face"] },
    { "chinese": "勇于承担责任，临危不惧", "english": "face the music", "type": "短语", "keyWords": ["face"] },
    { "chinese": "面临艰难的任务/挑战（不用vi.）", "english": "face the difficult task/ challenge", "type": "短语", "keyWords": ["face"] },
    { "chinese": "整容", "english": "facelift", "type": "单词", "keyWords": ["face"] },
    { "chinese": "（钱币或邮票等的）面值", "english": "face value", "type": "短语", "keyWords": ["face"] },
    { "chinese": "丢面子", "english": "lose face", "type": "短语", "keyWords": ["face"] },
    { "chinese": "在...面前；面对", "english": "in the face/presence of", "type": "短语", "keyWords": ["face"] },
    { "chinese": "面临...", "english": "sb. be faced with/by sth.", "type": "短语", "keyWords": ["face"] },
    { "chinese": "n. (C) 便利；(常pl.) 专用设备，设施；n. (U) 灵巧，熟练", "english": "facility", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 实际；事实", "english": "fact", "type": "单词", "keyWords": [] },
    { "chinese": "a. 事实的，实际的", "english": "factual", "type": "单词", "keyWords": ["fact"] },
    { "chinese": "实际上", "english": "in (actual) fact", "type": "短语", "keyWords": ["fact"] },
    { "chinese": "尽管事实是...", "english": "in spite of the fact that...", "type": "短语", "keyWords": ["fact"] },
    { "chinese": "事实胜于雄辩。", "english": "Facts speak louder than words.", "type": "句子", "keyWords": ["fact"] },
    { "chinese": "事实上，实际上", "english": "as a matter of fact", "type": "短语", "keyWords": ["fact"] },
    { "chinese": "n. (C) 因素", "english": "factor", "type": "单词", "keyWords": [] },
    { "chinese": "n. (C) 工厂", "english": "factory", "type": "单词", "keyWords": [] },
    { "chinese": "v. (声音等) 减弱下去；(使) 褪色；消失；枯萎，凋谢(away)", "english": "fade", "type": "单词", "keyWords": [] },
    { "chinese": "（电影画面或广播声音）渐现，淡入，渐强/渐隐，淡出，渐弱", "english": "fade in/out", "type": "短语", "keyWords": ["fade"] },
    { "chinese": "vi. 失败；不及格；忘记；衰落；衰弱；vt. 未能（接to do）；使失望；使不及格/不通过", "english": "fail", "type": "单词", "keyWords": [] },
    { "chinese": "不能或没有做某事", "english": "fail to do sth.", "type": "短语", "keyWords": ["fail"] },
    { "chinese": "衰退的视力/健康", "english": "failing sight/health", "type": "短语", "keyWords": ["fail"] },
    { "chinese": "病人的心脏停止了跳动。", "english": "The patient's heart failed.", "type": "句子", "keyWords": ["fail"] },
    { "chinese": "不及格", "english": "fail in sth.", "type": "短语", "keyWords": ["fail"] },
    { "chinese": "他让我失望了。", "english": "He failed me.", "type": "句子", "keyWords": ["fail"] },
    { "chinese": "庄稼歉收。", "english": "The crops failed.", "type": "句子", "keyWords": ["fail"] },
    { "chinese": "本学期老师没让一个学生代数不及格。", "english": "The teacher failed no students in algebra this term.", "type": "句子", "keyWords": ["fail"] },
    { "chinese": "n. (C) 失败者；失败的事；(U) 失败；缺乏；失灵，故障；破产", "english": "failure", "type": "单词", "keyWords": ["fail"] },
    { "chinese": "终归失败", "english": "end/ result in failure", "type": "短语", "keyWords": ["failure"] },
    { "chinese": "完全失败", "english": "a total/ complete failure", "type": "短语", "keyWords": ["failure"] },
    { "chinese": "庄稼歉收", "english": "a crop failure", "type": "短语", "keyWords": ["failure"] },
    { "chinese": "心力衰竭", "english": "heart failure", "type": "短语", "keyWords": ["failure"] },
    { "chinese": "电力不足/中断", "english": "a power failure", "type": "短语", "keyWords": ["failure"] },
    { "chinese": "供应中断；贮存告罄", "english": "supply failure", "type": "短语", "keyWords": ["failure"] },
    { "chinese": "他的失约使我们很失望。", "english": "His failure to keep his promise made us disappointed.", "type": "句子", "keyWords": ["failure"] },
    { "chinese": "他不是个成功的艺术家，但是个成功的美术教师。", "english": "He is a failure as an artist, but a success as an art teacher.", "type": "句子", "keyWords": ["failure"] },
    { "chinese": "n. (C)（只用单数）昏晕，昏倒；a. 微弱的，暗淡的；衰弱的，无力的；vi. 昏晕；变微弱", "english": "faint", "type": "单词", "keyWords": [] },
    { "chinese": "一线希望", "english": "a faint hope", "type": "短语", "keyWords": ["faint"] },
    { "chinese": "声音渐弱。", "english": "The sounds grew fainter.", "type": "句子", "keyWords": ["faint"] },
    { "chinese": "她昏过去了。", "english": "She went off in a faint.", "type": "句子", "keyWords": ["faint"] },
    { "chinese": "我一点也不懂你的意思。", "english": "I haven't the faintest/ least idea of what you mean.", "type": "句子", "keyWords": ["faint"] },
    { "chinese": "a.（肤色）白皙的；（头发）金黄的；公平的，按规则进行的；ad. 公平地，公正地；n. (C) 商品展览会或交易会；定期市集", "english": "fair", "type": "单词", "keyWords": [] },
    { "chinese": "金发", "english": "fair hair", "type": "短语", "keyWords": ["fair"] },
    { "chinese": "农村集市", "english": "a village fair", "type": "短语", "keyWords": ["fair"] },
    { "chinese": "书市/书展", "english": "book fair", "type": "短语", "keyWords": ["fair"] },
    { "chinese": "白皙的皮肤", "english": "fair skin", "type": "短语", "keyWords": ["fair"] },
    { "chinese": "正大光明的比赛", "english": "a fair play/game", "type": "短语", "keyWords": ["fair"] },
    { "chinese": "出口商品交易会", "english": "Export Commodities Fair", "type": "短语", "keyWords": ["fair"] },
    { "chinese": "你必须公正处事。/你必须正大光明地比赛。", "english": "You must play fair.", "type": "句子", "keyWords": ["fair"] },
    { "chinese": "ad. 公正地，不带偏见地；相当地，还算（主要用于褒义）", "english": "fairly", "type": "单词", "keyWords": [] },
    { "chinese": "尚好的，较好的；过得去的", "english": "fairly good", "type": "短语", "keyWords": ["fairly"] },
    { "chinese": "他承诺公平处理这件事。", "english": "He promised to handle the affair fairly.", "type": "句子", "keyWords": ["fairly"] },
    { "chinese": "n.仙女；精灵；小妖精", "english": "fairy", "type": "单词", "keyWords": [] },
    { "chinese": "仙境；仙界", "english": "fairyland", "type": "短语", "keyWords": ["fairy"] },
    { "chinese": "神话；童话", "english": "fairy tales", "type": "短语", "keyWords": ["fairy"] },
    { "chinese": "n.[U]信任，信心；信念，宗教信仰；忠实", "english": "faith", "type": "单词", "keyWords": [] },
    { "chinese": "a.守信的，忠实的，可靠的", "english": "faithful", "type": "单词", "keyWords": ["faith"] },
    { "chinese": "相信群众", "english": "have faith/ belief in the masses", "type": "短语", "keyWords": ["faith"] },
    { "chinese": "忠诚的雇员", "english": "a faithful employee", "type": "短语", "keyWords": ["faithful"] },
    { "chinese": "n.[C]假货，赝品；a.假的；vt.伪造，赝造；捏造，假造，仿造", "english": "fake", "type": "单词", "keyWords": [] },
    { "chinese": "n.[C]秋天；落下，倒下；跌倒；降低(pl)瀑布；vi.倒下；落下；来临；垮台；变成；vt.砍倒(树)", "english": "fall", "type": "单词", "keyWords": [] },
    { "chinese": "降了两英寸雨", "english": "a fall of two inches of rain", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "政府的倒台", "english": "the fall of a government", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "倒塌；瓦解", "english": "fall apart", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "落后", "english": "fall behind", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "塌陷；掉进水里", "english": "fall in", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "变得沉默", "english": "fall silent", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "落叶", "english": "fallen leaves", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "流星", "english": "a falling star", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "跌落(自行车等)；变少，(票价)降低；减弱", "english": "fall off", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "跌倒；绊在...上摔了一跤", "english": "fall over (a stone)", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "他们在伐木", "english": "They are falling trees.", "type": "句子", "keyWords": ["fall"] },
    { "chinese": "落在...上", "english": "fall on/upon", "type": "短语", "keyWords": ["fall"] },
    { "chinese": "今年的元旦是星期二", "english": "New Year's Day falls on a Tuesday this year.", "type": "句子", "keyWords": ["fall"] },
    { "chinese": "重音在最后一个音节上", "english": "The stress falls on the last syllable.", "type": "句子", "keyWords": ["fall"] },
    { "chinese": "他的目光落在我身上", "english": "His eye fell upon me.", "type": "句子", "keyWords": ["fall"] },
    { "chinese": "我的目光落在角落里一本小书上", "english": "My gaze fell on a small book in the corner.", "type": "句子", "keyWords": ["fall"] },
    { "chinese": "a.错误的，不正确的；假的(人造的)，不真实的；虚伪的", "english": "false", "type": "单词", "keyWords": [] },
    { "chinese": "假牙", "english": "false teeth", "type": "短语", "keyWords": ["false"] },
    { "chinese": "伪造的文件", "english": "false documents", "type": "短语", "keyWords": ["false"] },
    { "chinese": "给人以假象", "english": "give a false impression", "type": "短语", "keyWords": ["false"] },
    { "chinese": "n.[U]名声，名望", "english": "fame", "type": "单词", "keyWords": [] },
    { "chinese": "a.著名的，出名的", "english": "famous", "type": "单词", "keyWords": ["fame"] },
    { "chinese": "a.声名狼藉的", "english": "infamous", "type": "单词", "keyWords": ["fame"] },
    { "chinese": "恶名昭彰", "english": "ill fame", "type": "短语", "keyWords": ["fame"] },
    { "chinese": "作为...而著名/以...著名", "english": "be famous as/for", "type": "短语", "keyWords": ["famous"] },
    { "chinese": "她是著名的作家", "english": "She is famous as a writer.", "type": "句子", "keyWords": ["famous"] },
    { "chinese": "a.熟悉的；通晓的；常见的", "english": "familiar", "type": "单词", "keyWords": [] },
    { "chinese": "n.[U]熟悉，通晓", "english": "familiarity", "type": "单词", "keyWords": ["familiar"] },
    { "chinese": "为某人所熟悉", "english": "be familiar to sb.", "type": "短语", "keyWords": ["familiar"] },
    { "chinese": "熟悉，通晓，精通", "english": "be familiar with sth.", "type": "短语", "keyWords": ["familiar"] },
    { "chinese": "n.[C]家庭，家族，家属；[生物]科；[语言学]语系", "english": "family", "type": "单词", "keyWords": [] },
    { "chinese": "家谱", "english": "family tree", "type": "短语", "keyWords": ["family"] },
    { "chinese": "n.[C]扇子，风扇；鼓风机；迷，狂热者；vt.煽动，刺激，激起；扇", "english": "fan", "type": "单词", "keyWords": [] },
    { "chinese": "v.想象；设想，认为；n.[U]想象力；n.[C]爱好，迷恋；模糊的想法或感觉；a.空想出来的；异想天开的；花哨的", "english": "fancy", "type": "单词", "keyWords": [] },
    { "chinese": "a.爱空想的；不真实的；稀奇的", "english": "fanciful", "type": "单词", "keyWords": ["fancy"] },
    { "chinese": "热衷于下棋/旅行", "english": "have a fancy for chess/ travelling", "type": "短语", "keyWords": ["fancy"] },
    { "chinese": "我想大概要下雨", "english": "I have a fancy that it's going to rain.", "type": "句子", "keyWords": ["fancy"] },
    { "chinese": "想想看，她竟然说出这样的粗鲁话", "english": "Fancy her saying such rude things!", "type": "句子", "keyWords": ["fancy"] }
];
